### ISSUE TITLE
Different results for INT8 per run

### ISSUE THREAD

**Issue by liuchang8am** [NVIDIA/TensorRT#10]
A weird thing:

After INT8 calibration, the calibration table is cached.

Then, I repeatedly: loaded the calibration table and did INT8 inference, but got different outputs each time, as shown in the figure.

Anyone has the same issue? What may be the cause of it?

![clip](https://user-images.githubusercontent.com/1009550/59855195-8a5d3680-9342-11e9-949c-d089566ca0e4.png)

**Comment by rajeevsrao** [comment]
@liuchang8am

Can you post a relevant snippet of your sample? The first run output looks incorrect. Are subsequent results correct for the cached calibration table?

**Comment by liuchang8am** [comment]
> @liuchang8am
> 
> Can you post a relevant snippet of your sample? The first run output looks incorrect. Are subsequent results correct for the cached calibration table?

I'll try to provide a rep sample. The output is the first 20 elements of conv1_7x7's output, and actually, the second run's result is very close to FP32 result.

**Comment by rmccorm4** [comment]
@liuchang8am any update on this?

**Comment by rmccorm4** [comment]
Closing due to no response. Feel free to open a new issue and reference this one for context.

**Comment by twmht** [comment]
got the same issue
