### ISSUE TITLE
Half function undefined during compilation

### ISSUE THREAD

**Issue by 5had3z** [NVIDIA/TensorRT#1003]
## Description

I've implemented a plugin for grid sample 2D from the pytorch repo and used it within my own codebase. However when I try to add it to the Tensor RT OSS codebase to contribute, compilation fails with undefined identifiers to all the half functions used, i.e. error: identifier "__hmax" is undefined. I have noticed that I don't think I can see any other half math intrinsics used in the rest of the codebase, is that something that is to be avoided?

## Environment

**TensorRT Version**: OSS-master
**GPU Type**: RTX 3090
**Nvidia Driver Version**: 455.32.00
**CUDA Version**: 11.1
**CUDNN Version**: 
**Operating System + Version**: Ubuntu 20.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

https://github.com/5had3z/TensorRT

## Steps To Reproduce

Just compile as per the readme in the standard Tensor RT OSS instructions.

**Comment by buganini** [comment]
I got same error during bulid of  https://github.com/5had3z/stereo-to-all/blob/master/runtime/cerberus_net/trt_plugins/grid_sampler.cu
with apt-installed 7.2.2.3-1+cuda11.1

**Comment by pranavm-nvidia** [comment]
You'd probably want to guard the intrinsics with SM version checks. For example: https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/common.cuh#L67

**Comment by 5had3z** [comment]
Is there a good way to determine the earliest SM version which supports a particular function? The math intrinsics documentation doesn't specify as far as I can tell. Also is it still required that I support SM<5.3 since they are being depricated and removed in future versions of Tensor RT?
I've been without a PSU for the past few weeks so have only resumed working on this now.

**Comment by 5had3z** [comment]
Is there any particular way about going about testing for older SM arch? I've got things compiling now, however its a bit messy trying to cover float and half and recasting things if it isn't supported (especially without if constexpr). The plugin works fine in my own application with a 3090, I'm just not sure how to validate it properly as a unit test and with other GPUs.

I also haven't played with signing commits off before (previously haven't needed to do so). I've cooked some of the commits, should I be able to fix this by rebasing?

**Comment by pranavm-nvidia** [comment]
> Is there a good way to determine the earliest SM version which supports a particular function?

There's a table [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities) which shows what functionality each compute capability supports. 

> I also haven't played with signing commits off before (previously haven't needed to do so). I've cooked some of the commits, should I be able to fix this by rebasing?

You should be able to retroactively sign commits with: `git commit --amend --signoff`

CC'ing @rajeevsrao regarding how to test on older SMs,

**Comment by 5had3z** [comment]
Interestingly __hmin and __hmax only work when __CUDA_ARCH__ >= 800, otherwise returns undefined when using __CUDA_ARCH__ >= 530, even when it should be supported from then onwards. Other functions such as __hdiv or __habs work corrrectly when using __CUDA_ARCH__ >= 530.

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
