### ISSUE TITLE
ScatterND not supported workaround.

### ISSUE THREAD

**Issue by ajaichemmanam** [NVIDIA/TensorRT#1006]
I was looking for conversion of a custom model written in pytorch to tensorrt.
I managed to succesfully convert to onnx format and when I try to parse it in tensorrt, i face the error ScatterND not supported.

In previous issues, I can see that the scatterND will be added in a future version. Can anybody help me find a workaround for the problem till the actual implementation is there.

The issue is in this line

where kps is a (1,100,34) tensor and xs and ys are reshaped to (1,100,17) tensors.
 K = 100, num_joints =17.
The following code adds the xs and ys values to alternate positions in kps.
    kps[..., ::2] += xs.view(batch, K, 1).expand(batch, K, num_joints)
    kps[..., 1::2] += ys.view(batch, K, 1).expand(batch, K, num_joints)

**Comment by pshwetank** [comment]
I am facing a similar issue with such broadcasting operations in yolov5 code. Has anybody been able to convert it successfully?

**Comment by ttyio** [comment]
Hello @ajaichemmanam  @pshwetank , we are working on ScatterND support.  It will be helpful if you could share us the model, thanks!

**Comment by ttyio** [comment]
Now ScatterND is native supported, close and thanks all

**Comment by pshwetank** [comment]
Thanks a lot for that.
