### ISSUE TITLE
implentation of ConvInteger and QLinearConv

### ISSUE THREAD

**Issue by oak-tree** [NVIDIA/TensorRT#1009]
### Background
Our current flow: automatic converation of `tf2`->`onnx`->`Tensorr` (both `16` and `32`)
We recently added int8 with calibration. But we understand we would have better performance if we will do quantization aware training (`QAT)`

### Question
So, now we are doing `QAT` in `tf2`. Then we are exporting it to ONNX. This create an `conv` opcode for 8integer. It can be `ConvInteger` or `QLinearConv`. It seems that both of them are not support on `TensorRT` `7.2`. Although they exist since `opset 10`  and `TensorRT` documentation mention that `TensorRT 7.2` supports up to `Opset 11`.

What will be the best option to `convert` those `opcode` .

Thanks!

## Environment

**TensorRT Version**: 7.2 
**GPU Type**:  Xavier
**JetPack**: 4.4
**TensorFlow Version (if applicable)**: 2.3

**Comment by ttyio** [comment]
@skyw ^^

**Comment by ttyio** [comment]
Hello @oak-tree , now we support `QuantizeLinear` and `DequantizeLinear` start from TRT 8.0

https://github.com/onnx/onnx/blob/master/docs/Operators.md#QuantizeLinear
https://github.com/onnx/onnx/blob/master/docs/Operators.md#DequantizeLinear

You can try the early access release in https://developer.nvidia.com/nvidia-tensorrt-download

**Comment by ttyio** [comment]
Closing since now activity for more than 3 weeks, please reopen if you still have question, thanks!
