### ISSUE TITLE
Muti GPU

### ISSUE THREAD

**Issue by guods** [NVIDIA/TensorRT#101]
How to run a engine on mutil GPU?

**Comment by DilipSequeira** [comment]
A single engine will only run on a single GPUs. For information on how to use multiple GPUs to run multiple engines concurrently, please see the FAQ in the developer guide.

**Comment by rmccorm4** [comment]
> please see the FAQ in the developer guide.

FYI, FAQ can be found here: please see the FAQ in the developer guide.
