### ISSUE TITLE
Partial quantization  support 

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TensorRT#1011]
Is there a method to run partial quantization via Int8 calibrators ? 
ref: https://arxiv.org/pdf/2004.09602.pdf

**Comment by ttyio** [comment]
Hello @JosephChenHub , thanks for reporting.
Yes.
For PTQ, you can call `ILayer::setPrecision` and `ILayer::setOutputType` to let the int8 sensitive layers running on FP16/FP32 precision. By enable verbose log you can make sure your changes are effective. 
For QAT, you can monkey patch your code, by only replace the conv/linear/... that require int8 precision with QuantConv/QuantLinear/...

**Comment by JosephChenHub** [comment]
> Hello @JosephChenHub , thanks for reporting.
> Yes.
> 
> For PTQ, you can call `ILayer::setPrecision` and `ILayer::setOutputType` to let the int8 sensitive layers running on FP16/FP32 precision. By enable verbose log you can make sure your changes are effective.
> 
> For QAT, you can monkey patch your code, by only replace the conv/linear/... that require int8 precision with QuantConv/QuantLinear/...

Thanks for your help! I will try it.

**Comment by jonbakerfish** [comment]
> For PTQ, you can call ILayer::setPrecision and ILayer::setOutputType to let the int8 sensitive layers running on FP16/FP32 precision. By enable verbose log you can make sure your changes are effective.

Hi @ttyio , do you have any examples of how to use these two APIs and how to check the verbose log? I tried to add these to my network, but it seems that the int trt engine did not change.

**Comment by ttyio** [comment]
@jonbakerfish , did you enable `kSTRICT_TYPES` https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#abdc74c40fe7a0c3d05d2caeccfbc29c1ad3ff8ff39475957d8676c2cda337add7 ? 
to check the precision, you can check `layer information` part in the log , we have logged in/out IO, thanks!

**Comment by Jae-1409** [comment]
Hi @ttyio , I'm currently trying to run partial quantization via this [repo](https://github.com/NVIDIA-AI-IOT/torch2trt). 

I added this code before building the engine (fp16 + int8).

    if partial:

        config.set_flag(trt.BuilderFlag.FP16)

        aaa = '1 14 15 26 27 36 37 44 45 52 53 60 61 68 69 76 77 86 87 98 99 112 113 114 115 116 117 118 119'.split( )
        count = 0
            
        for i in range(network.num_layers):
                if 'CONCATENATION' not in network.get_layer(i).name:
                    if f'CONVOLUTION #{aaa[count]}' in network.get_layer(i).name:
                        set_layer_precision(network.get_layer(i), 'fp16')
                        count += 1
                        if len(aaa)==count:
                            break

However, when I tested on my dataset, the inference speed was much slower than the network converted in fp16. 

1. Am I doing right? 

2. And is there any 'python' API to set some layer's precision?

The APIs [here](https://github.com/NVIDIA/TensorRT/tree/main/samples/sampleINT8API) seems to be in C language..

**Comment by ttyio** [comment]
@Jae-1409 , we need extra reformat layout to do the layout reorder when switch between fp16 and int8, and it harms perf. 

and yes we have Python API:
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/LayerBase.html#tensorrt.ILayer
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/LayerBase.html#tensorrt.ILayer.set_output_type

**Comment by Jae-1409** [comment]
> @Jae-1409 , we need extra reformat layout to do the layout reorder when switch between fp16 and int8, and it harms perf. 
> 
> 
> 
> and yes we have Python API:
> 
> https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/LayerBase.html#tensorrt.ILayer
> 
> https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/LayerBase.html#tensorrt.ILayer.set_output_type

@ttyio , is there any repo to follow using these APIs?
I dont understant where(which phase) to use these APIs. Should I construct my own ILayer handwise, not changing builder's config?
