### ISSUE TITLE
Why 1x1 convolution and not fully_connected?

### ISSUE THREAD

**Issue by pogevip** [NVIDIA/TensorRT#1015]
```
  # FC_attention
    if config.use_int8:
        mult_all = network.add_convolution(input_tensor, 3 * hidden_size, (1, 1), Wall, Ball)
    else:
        mult_all = network.add_fully_connected(input_tensor, 3 * hidden_size, Wall, Ball)
```

https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py#L138

Why 1x1 convolution and not fully_connected?

**Comment by ttyio** [comment]
hello @pogevip , this is for performance consideration, we get better performance when replace fully_connected with 1x1 convolution. and if you use latest TensorRT, this is already built-in optimization rules and you can remove the check here still get the same perf gain.

**Comment by pogevip** [comment]
@ttyio Thanks.
