### ISSUE TITLE
ERROR: ../rtExt/cuda/cudaPointWiseRunner.cpp (158) - Cuda Error in execute: 1 (invalid argument)

### ISSUE THREAD

**Issue by szjcqu** [NVIDIA/TensorRT#1018]
Hi There! 
When I run my model (caffe model with plugin layers) in TensorRT:  context->execute(BATCH_SIZE, buffers),   it get an error like this:
ERROR: ../rtExt/cuda/cudaPointWiseRunner.cpp (158) - Cuda Error in execute: 1 (invalid argument)
ERROR: FAILED_EXECUTION: std::exception

Can anyone help me out for this ? 
Thanks!

## Environment

**TensorRT Version**:  7.1.3
**Hardware**:  Nvidia AGX Xavier
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.0
**Operating System + Version**: ubuntu18.04
**Python Version (if applicable)**: 3.6.9
**PyTorch Version (if applicable)**: 1.6.0

**Comment by ttyio** [comment]
Hello @szjcqu , thanks for reporting.
which TRT version are you using?

**Comment by szjcqu** [comment]
> Hello @szjcqu , thanks for reporting.
> which TRT version are you using?

Thank you for your replay!  

TensorRT Version: 7.1.3
Hardware: Nvidia AGX Xavier
CUDA Version: 10.2
CUDNN Version: 8.0.0
