### ISSUE TITLE
Missing repo file for ubuntu 20.04

### ISSUE THREAD

**Issue by Data-drone** [NVIDIA/TensorRT#1026]
## Description

I am trying to follow the instructions here: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#maclearn-net-repo-install-rpm

## Environment

**TensorRT Version**: 7.2.2
**GPU Type**: 2080ti
**Nvidia Driver Version**:  455.38
**Operating System + Version**: ubuntu 20.04

## Steps To Reproduce

In the instructions, to install the cuda network repository it mentions going to:
wget https://developer.download.nvidia.com/compute/cuda/repos/${os}/x86_64/cuda-repo-${os}_${cuda}-1_amd64.deb

but for ubuntu 20.04, there is no cuda-repo file.
See: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/

Is this just an oversight or is 20.04 not support yet?
In which case, when can we expect 20.04 support?

**Comment by ttyio** [comment]
Hello @Data-drone , thanks for question, could you check the rpm in https://developer.nvidia.com/nvidia-tensorrt-7x-download?

**Comment by Data-drone** [comment]
I see only 18.04 is 20.04 not supported?

**Comment by ttyio** [comment]
@Data-drone , yes only 16.04 and 18.04 is released according to https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

**Comment by Data-drone** [comment]
any eta on a `20.04` release?

**Comment by ttyio** [comment]
Hello @Data-drone , we have 20.04 release in https://developer.nvidia.com/nvidia-tensorrt-8x-download, thanks
