### ISSUE TITLE
pytroch model and Tensorrt C++ model produce different result when I give a video for models

### ISSUE THREAD

**Issue by omeralierdemir** [NVIDIA/TensorRT#1027]
## Environment

**TensorRT Version = 4.0.1**: 
**GPU Type-nvidia-jetson-tx2 jetpack version = 3.3**: 
**CUDA Version =  9.0 on jetson tx2**: 
**CUDNN Version= 7.1.5.14 on jetson tx2**: 
**Operating System + Version = Ubuntu 16.04**: 
**Python Version  = Python 3.5**: 

**PyTorch Version = torch 1.1 on jetson tx2**: 

Hello,
I have been developing a classification project.  I have built this project with pytorch at my local computer(python3.7, torch 1.6, cuda 10.2) then I have converted my pytorch code to tensorrt C++ manually for jetson tx2. 
I have been checking and comparing  pytorh model output (pytorch model have been running on local pc) and tensorrt c++ model output with a single image. Tensorrt model and pytroch model have produced same result. 
Then I gave  a video to tensorrt model with opencv C++ videocapture, I gave the  same video to pytorch model with opencv python videocapture. Then I checked model result, tensorrt and pytorch models result was different. 
Then I have parse the video to frames. I gave  first frame of the video to tensorrt model and pytorch model. Tensorrt  and pytroch model have produced same result. My opencv C++ videocapture and opencv python videocapture has default arguments. I think opencv python video capture and opencv C++ videocapture work differently. But I am not sure.

Do you now this problem reason?

**Comment by ttyio** [comment]
@omeralierdemir , have you tried compare all the frames in the video, is it possible one of the frame (not the first one) produce different result, could you isolate the frame? thanks!

**Comment by omeralierdemir** [comment]
yes I tried. I am sure that I gave the same frame to  both c++ and python source code.

**Comment by ttyio** [comment]
Hmmm, @omeralierdemir , could you mark the input layer as output in tensorrt, feed with opencv videocapture, let's check the dump output, maybe there is some difference like NCHW vs. NHWC?

**Comment by Egozjuer** [comment]
@ttyio hello,please tell me how to produce the any model middle layer's output in tensorrt

**Comment by ttyio** [comment]
Hello @Egozjuer , currently there is no direct function to do this. we can mark interested tensors as output using `markOutput`.

**Comment by Egozjuer** [comment]
@ttyio  emmm,it's OK, I have another question,my onnx model has the same result with pytorch ,but the output of tensorRT is wrong,how did I know which layer in tensort produced the wong result?

**Comment by ttyio** [comment]
@Egozjuer , 
mark all layers as output, compare with framework intermediate output, this is slow.

mark one layer as output at one time using binary search, and find out the mismatch node.

First graph surgeon your onnx model (like only leave the top 1/2 of the original onnx), and run Polygraphy (https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy) on the small model, the tool can compare TRT run and other framework run (like onnxruntime), you can also find the mismatch node using a binary search way.

**Comment by Egozjuer** [comment]
@ttyio  ok thank you, i will try

**Comment by Egozjuer** [comment]
@ttyio Hi,network->markOutput() needs to know the ITensor ,I has known the name of onnx op,how did i get the ITensor?

**Comment by ttyio** [comment]
@Egozjuer  Hmmm, It is a bit tricky to get this information, we have to enable the verbose log, and then grep these information from the parser part log.

Could you try the 3rd method, remove the tailing nodes from onnx, then run Polygraphy to compare the result? Thanks

**Comment by Egozjuer** [comment]
@ttyio  emmm my mdoel is inferenced by C++ API,did the Polygraphy suit it?

**Comment by ttyio** [comment]
@Egozjuer , polygraphy support onnx import. seems you have root cause in another thread, this is introduced in `Resize`

**Comment by Egozjuer** [comment]
@ttyio ,Hi,I checked the resize ops,and i find it's right between onnxruntime and trt,so I think there's another ops wrong.when I use polygraphy,I met another problem, I have installed polygraphy;
      Successfully installed polygraphy-0.21.1
but when i typed polygraphy --help
Traceback (most recent call last):
  File "/home/ego/anaconda3/envs/pytorch16/bin/polygraphy", line 22, in <module>
    from polygraphy.tools.util import args as args_util
ImportError: cannot import name 'args' from 'polygraphy.tools.util' (/home/ego/.local/lib/python3.8/site-packages/polygraphy/tools/util/__init__.py)
    I opened __init__.py,and find there's nothing in __init__.py

**Comment by ttyio** [comment]
> @ttyio ,Hi,I checked the resize ops,and i find it's right between onnxruntime and trt,so I think there's another ops wrong.when I use polygraphy,I met another problem, I have installed polygraphy;
> Successfully installed polygraphy-0.21.1
> but when i typed polygraphy --help
> Traceback (most recent call last):
> File "/home/ego/anaconda3/envs/pytorch16/bin/polygraphy", line 22, in
> from polygraphy.tools.util import args as args_util
> ImportError: cannot import name 'args' from 'polygraphy.tools.util' (/home/ego/.local/lib/python3.8/site-packages/polygraphy/tools/util/**init**.py)
> I opened **init**.py,and find there's nothing in **init**.py

+ @pranavm-nvidia , have you seen this error before? thanks!

**Comment by pranavm-nvidia** [comment]
It looks like the `polygraphy` binary installed there is old. 
@Egozjuer Can you try removing `/home/ego/anaconda3/envs/pytorch16/bin/polygraphy`? 
From the import path, it seems like the correct binary should be in `/home/ego/.local/bin/polygraphy`

**Comment by Ekta246** [comment]
> @ttyio ,Hi,I checked the resize ops,and i find it's right between onnxruntime and trt,so I think there's another ops wrong.when I use polygraphy,I met another problem, I have installed polygraphy;
> Successfully installed polygraphy-0.21.1
> but when i typed polygraphy --help
> Traceback (most recent call last):
> File "/home/ego/anaconda3/envs/pytorch16/bin/polygraphy", line 22, in
> from polygraphy.tools.util import args as args_util
> ImportError: cannot import name 'args' from 'polygraphy.tools.util' (/home/ego/.local/lib/python3.8/site-packages/polygraphy/tools/util/**init**.py)
> I opened **init**.py,and find there's nothing in **init**.py

Hi @Egozjuer,

First, thanks for pointing out the question in the Github. I am facing the same issues like you did. My pytorch model has been converted to onnx(which contains Resize node) and onnx model has been serialized into a TensorRT 7.1.3 engine using the trtexec tool for fp16 quantization.
However, after deserializing it, and running the context.execute inference on it when I print the output generated by the TensorRT engine I see the output shapes for the 10 output tensors are correct but the values are incorrect. Like for eg, for one of the outputs i.e., (1,54,64,64) output shape, the half of the output i.e., (1,27,64,64 ) are zeros while half are float values.

@ttyio helped me with asking to check the failing of the node using the onnx-graphsurgeon and polygraphy.
But as a novice, I am unable to get the steps to debug. Could you throw light upon the WAR and how did you manage to compare between the onnx and tensorrt?

TIA

**Comment by poornimajd** [comment]
>  Like for eg, for one of the outputs i.e., (1,54,64,64) output shape, the half of the output i.e., (1,27,64,64 ) are zeros while half are float values.

@Ekta246 Were you able to resolve this issue?

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
