### ISSUE TITLE
Could I create a plugin in python ? 

### ISSUE THREAD

**Issue by linssswww** [NVIDIA/TensorRT#103]

**Comment by narendasan** [comment]
Take a look at this sample https://docs.nvidia.com/deeplearning/sdk/tensorrt-sample-support-guide/index.html#uff_custom_plugin

**Comment by linssswww** [comment]
> Take a look at this sample
> 
> [Adding A Custom Layer To Your TensorFlow Network In TensorRT In Python](https://docs.nvidia.com/deeplearning/sdk/tensorrt-sample-support-guide/index.html#uff_custom_plugin)

My description is not clear enough， and I want to ask about  implementing a plugin in python， because python is convenient. The sample show the plugin implementing in c++

**Comment by jefflgaol** [comment]
You can find the documentation right here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#example1_add_custom_layer_python
