### ISSUE TITLE
How can I run skip layernorm and multi-head attention with INT8 when bert sequence length is customized？

### ISSUE THREAD

**Issue by FengYue95** [NVIDIA/TensorRT#1030]
## Description

I have a tensorflow tiny bert model with seq_len: 32 , num_attention_heads:2 and hidden_siz:128. Now I use bert demo in the master branch to build tensorrt engine with int8.

However, I can't directly build engine with command “-iln -imh”，it tells that only size of bert base ot bert large is supported.

Is there any way I can do it?

## Environment

**TensorRT Version**: 7.2.2.3
**GPU Type**: T4
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 11.1

## Relevant Files

[TensorRT] ERROR: INT8 IO only support sequence length 128,384 for plugin CustomQKVToContextPluginDynamic

**Comment by ttyio** [comment]
Hello @FengYue95 , sorry we have dedicated int8 kernel for sequence length 128, 384, and cannot run on any problem size. You can remove the "-imh" to use the unfused FP16 kernel, this kernel is generalized for any sequence length.

**Comment by FengYue95** [comment]
@ttyio All right~Thank you！
