### ISSUE TITLE
onnx to tensorrt error with  [TensorRT] ERROR: ../builder/myelin/myelinBuilder.cpp (418) - Myelin Error in operator(): 1 (myelinVersionMismatch : Compiled assuming that device 0 was SM 60, but device 0 is SM 0

### ISSUE THREAD

**Issue by chiminghui** [NVIDIA/TensorRT#1033]
When I transfor my onnx model to tensorrt model, I get the following error:

Beginning ONNX file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
True
Completed parsing of ONNX file
Building an engine from file /home/cmh/OpenVINO_docker/test_opencv_ocr/models/crnn.onnx; this may take a while...
[TensorRT] ERROR: ../builder/myelin/myelinBuilder.cpp (418) - Myelin Error in operator(): 1 (myelinVersionMismatch : Compiled assuming that device 0 was SM 60, but device 0 is SM 0.
)
[TensorRT] ERROR: ../builder/myelin/myelinBuilder.cpp (418) - Myelin Error in operator(): 1 (myelinVersionMismatch : Compiled assuming that device 0 was SM 60, but device 0 is SM 0.
)
Completed creating Engine
Traceback (most recent call last):
  File "tensorrt_ocr.py", line 113, in <module>
    top = tensorrt_ocr_pipline(detect_onnx_model_path='/home/cmh/east_mobilenet_52/east_mobilenet.onnx', recognise_onnx_model_path='/home/cmh/OpenVINO_docker/test_opencv_ocr/models/crnn.onnx')
  File "tensorrt_ocr.py", line 105, in __init__
    self.recognisor = tensorrt_text_recognise(recognise_onnx_model_path)
  File "tensorrt_ocr.py", line 96, in __init__
    self.recognise_engine = get_engine(self.onnx_model_path, self.engine_model_path, shape=shape)
  File "tensorrt_ocr.py", line 58, in get_engine
    return build_engine(shape=shape)
  File "tensorrt_ocr.py", line 51, in build_engine
    save_engine(engine, engine_file_path)
  File "tensorrt_ocr.py", line 11, in save_engine
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'

I don't know how to fix it, pls help! tks!

My environment is:
tensorrt: 7.2.2.3
cuda: 10.2
cudnn: 8.0.5.39
GPU: Tesla P100
GPU Driver:  440.118.02
OS: ubuntu 18.04

**Comment by ttyio** [comment]
Hello @chiminghui , thanks for reporting. previous we see error 

    Myelin Error in operator(): 1 (myelinVersionMismatch : Compiled assuming that device 0 was SM 60, but device 0 is SM 0

fixed after user reinstall the CUDA driver and reboot the machine. Could you also take a try?

**Comment by chiminghui** [comment]
@ttyio Thanks for your replay，your method  is valid for me.

**Comment by zhaohb** [comment]
@brooks0519 @ttyio I met the same problem. do we need to upgrade when reinstalling the driver, or use the original version？
