### ISSUE TITLE
TensorRT engine built problem on RTX 3070 with cuda 11.1 version

### ISSUE THREAD

**Issue by batselem** [NVIDIA/TensorRT#1035]
## Description
I have a problem building TensorRT inference engine with RTX 3070 (CUDA 11.1 / cuDNN 8.0.5) on Windows. I got the following error when I tried to execute trtexec command. It worked fine on RTX 4000 GPU without any issue. Did anyone have the same problem? I will really appreciate it if anyone helps me to solve this problem. Thank you in advance.

## Problem
```
-------------------------------------------------ENGINE BUILD ERROR-----------------------------------------
[01/29/2021-10:26:48] [F] [TRT] Assertion failed: (smVersion < SM_VERSION_A100) && "SM version not supported in this NVRTC version"
C:/source/rtExt\helpers.h:523
Aborting...
[01/29/2021-10:26:48] [E] [TRT] C:/source/rtExt\helpers.h (523) - Assertion Error in nvinfer1::fixSMVerForNVRTC: 0 ((smVersion < SM_VERSION_A100) && "SM version not supported in this NVRTC version")
[01/29/2021-10:26:48] [E] Engine creation failed
[01/29/2021-10:26:48] [E] Engine set up failed
```
-------------------------------------------------------------------------------------------------------------------

## Environment
Operating System: Windows 10
GPU Type: GeForce RTX 3070 (with 8.6 compute capability)
Cuda Version: CUDA 11.1 / cuDNN 8.0.5
TensorRT Version: TensorRT-7.2.2.3 (also tried TensorRT-7.2.1.6)

## Command
```
trtexec.exe --onnx=.../yolov4_1_3_416_416_static.onnx --explicitBatch --saveEngine=yolov4_1_3_416_416_static_fp16.engine --fp16
```

**Comment by batselem** [comment]
I found out that TensorRT by default supports SM 35, 53, 61, 70, 75 and 80 gpu archs while RTX has SM 86. So, I am trying to build TensorRT on Windows for RTX 3070 with the following commands. 

```
 cd $Env:TRT_SOURCE
 mkdir -p build ; cd build
 cmake .. -DGPU_ARCHS="86" -DTRT_LIB_DIR=E:/Programs/TensorRT-7.2.1.6/lib -DTRT_OUT_DIR=out -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/cmake_x86_64.toolchain
 msbuild ALL_BUILD.vcxproj
```

But I got an error:

```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: E:/Programs/TensorRT/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_fc750.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine 버전 15.1.550.39093

Copyright (C) Microsoft Corporation. All rights reserved.

  x86용 Microsoft (R) C/C++ 최적화 컴파일러 버전 19.10.25027

  cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D BUILD_SYSTEM=cmake_oss /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_fc750.dir\Debug\\" /Fd"cmTC_fc750.dir\Debug\vc141.pdb" /Gd /TP /analyze- /errorReport:queue  -Wno-deprecated-declarations E:\Programs\TensorRT\build\CMakeFiles\CMakeTmp\CheckIncludeFile.cxx

cl : 명령줄 error D8021: '/Wno-deprecated-declarations' 숫자 인수가 잘못되었습니다. [E:\Programs\TensorRT\build\CMakeFiles\CMakeTmp\cmTC_fc750.vcxproj]
```

However, in the log, it says it found threads: 
```
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
```

Does anyone have the same problem? I wonder what is causing this issue.

**Comment by ttyio** [comment]
Hello @batselem , sorry currently we have no official CMake for windows build in the opensource repo.

And for the failure

    Assertion Error in nvinfer1::fixSMVerForNVRTC: 0 ((smVersion < SM_VERSION_A100) && "SM version not supported in this NVRTC version")

Could you help to download https://www.dependencywalker.com/ and check the trtexec.exe, I want to check which nvinfer.dll it is loading, and make sure this nvinfer.dll is from cuda 11.0 distribution. thanks!

**Comment by batselem** [comment]
@ttyio I see. I will try your suggestion. Thank you very much!

**Comment by batselem** [comment]
@ttyio I checked it with dependency walker. I observed that my_app.exe->nvinfer.dll->cudart64_102.dll. It looks like 10.2 cuda is being used for tensorrt nvinfer but I setup my project with TensorRT-7.2.1.6.Windows10.x86_64.cuda-11.1.cudnn8.0 on visual studio. How is it possible?

**Comment by batselem** [comment]
@ttyio ah I made mistake when I setup "visual studio build customization files" setting. It was setup with cuda 10.2 but I changed it to cuda 11.1 and matched tensorrt cuda version(11.1) but still got the sm version error:
----------------------------------------------------------------
```
Input filename:   E:/Projects/pytorch-YOLOv4/yolov4_1_3_416_416_static.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.7
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
setFp16Mode
Begin building engine...
Assertion failed: (smVersion < SM_VERSION_A100) && "SM version not supported in this NVRTC version"
C:/source/rtExt\helpers.h:523
Aborting...
C:/source/rtExt\helpers.h (523) - Assertion Error in nvinfer1::fixSMVerForNVRTC: 0 ((smVersion < SM_VERSION_A100) && "SM version not supported in this NVRTC version")
Unable to create engine
```

**Comment by batselem** [comment]
@ttyio Thank you very much :). I followed your instruction and solved the problem. The problem was that after I switched my graphic card, I forgot to do the following step. It was loading the previous nvinfer1.dll from 10.2 cuda.

**Solution:**
`Copy the DLL files from <installpath>/lib to your CUDA installation directory, for example, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin, where v11.1 is your CUDA version. The CUDA installer should have already added the CUDA path to your system PATH.`

**Comment by AlanLu0808** [comment]
> @ttyio Thank you very much :). I followed your instruction and solved the problem. The problem was that after I switched my graphic card, I forgot to do the following step. It was loading the previous nvinfer1.dll from 10.2 cuda.
> 
> **Solution:**
> `Copy the DLL files from <installpath>/lib to your CUDA installation directory, for example, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin, where v11.1 is your CUDA version. The CUDA installer should have already added the CUDA path to your system PATH.`

I'm wondering if u have succeeded in compiling TensorRT on Windows?

If yes, have u make some changes in the cmake scipts? And what's your command in terminal? Tks!

**Comment by ttyio** [comment]
Hello @AlanLu0808 , sorry we have no official build support on Windows yet, I will create internal feature request to track this.

**Comment by batselem** [comment]
@AlanLu0808 I tried it for a few days and couldn't do it. I used powershell as it is recommended. I executed the cmake script but it couldn't find sublibraries such as zlib and some header files necessary for building tensorrt.
