### ISSUE TITLE
[Question] What is the best scenario to use TRT with pytorch quantized model (QAT).

### ISSUE THREAD

**Issue by dhkim0225** [NVIDIA/TensorRT#1040]
Hello, I am an avid user who is using TensorRT for service.
I want to serve the QAT model (int8) with TensorRT which is learned with pytorch 1.7.1.
What is the best scenario to serve this model ?

After some search time, I could find the following information.
Please let me know, if I have a wrong information.
1. TensorRT has the pytorch-quantization v2.0.0 package. (from 7.2.1)
2. The QAT of pytorch is still in beta, and the save format is constantly changing. (There is a version dependency.)
3. Pytorch supports `per tensor` and `per channel asymmetric` method, but TensorRT supports `per tensor` method. 

> PyTorch supports both per tensor and per channel asymmetric linear quantization. Per tensor means that all the values within the tensor are scaled the same way. Per channel means that for each dimension, typically the channel dimension of a tensor, the values in the tensor are scaled and offset by a different value (effectively the scale and offset become vectors). This allows for lesser error in converting tensors to quantized values.

I'm totally having no idea which features should I use for QAT model serving with nvidia GPU (T4).

Regards,
Anthony Kim

**Comment by ttyio** [comment]
Hello @dhkim0225 , thanks for reporting.

TensorRT supports `per tensor quant` for activation and `per tensor/channel quant` for weights. And sorry the QAT support in release 7.x is incomplete, and we will enhance it in next major release. 
Before that please use PTQ, or you can also check the demoBERT in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py#L233, we load amax from QAT and use `setDyanmicRange` API to set the scale.

**Comment by dhkim0225** [comment]
@ttyio Thanks for the reply! 
Would you mind If I ask a question about the next major release date?

**Comment by ttyio** [comment]
Hello @dhkim0225 , the rough plan is around 3 months, thanks!

**Comment by dhkim0225** [comment]
@ttyio Thank you for reply! Close issue.
