### ISSUE TITLE
Missing Python Samples

### ISSUE THREAD

**Issue by jtressle** [NVIDIA/TensorRT#105]
According to this link [Nvidia Python Samples](https://docs.nvidia.com/deeplearning/sdk/tensorrt-sample-support-guide/index.html#python_samples_section), the git should contain Python samples.  

Is the documentation incorrect?  Or are were the python samples moved?  A note in the samples readme would be great.

Thanks!

**Comment by zeroepoch** [comment]
The python samples exist in the TensorRT release from DevZone, but they have not been included in the open source release yet.

**Comment by paapu88** [comment]
Where can I find "TensorRT release from DevZone" ?

A python sample to 

1) read onnx net from file
2) convert it to tensorRT engine
3) save tensorRT engine to file
4) load tensorRT engine from file

all this with good parameters for jetson nano...
would be appreciated...

**Comment by zeroepoch** [comment]
@paapu88,
You will need an NVIDIA developer account in order to download TensorRT.  You can start the process by visiting https://developer.nvidia.com/tensorrt.  There is a tar release for most platforms which will likely be the simplest way for you to obtain these python samples without requiring any installation.

**Comment by paapu88** [comment]
Thank's!!! I had not realized the .tar option.

**Comment by jtressle** [comment]
@zeroepoch thanks for the details.

**Comment by rmccorm4** [comment]
> A python sample to
> 1. read onnx net from file
> 2. convert it to tensorRT engine
> 3. save tensorRT engine to file
> 4. load tensorRT engine from file

@paapu88, FYI, once you've installed the TensorRT release, you can find ONNX -> TensorRT samples at:
* `tensorrt/samples/python/introductory_parser_samples/onnx_resnet50.py`
* `tensorrt/samples/python/yolov3_onnx/`

For Jetson specifically, I believe you're supposed to install TensorRT through Jetpack: https://developer.nvidia.com/embedded/jetpack

Once you're setup, this repo might also help get started: https://github.com/dusty-nv/jetson-inference
