### ISSUE TITLE
How to set cuda device with tensorRT python API?

### ISSUE THREAD

**Issue by XianglongTan** [NVIDIA/TensorRT#1050]
The engine built with python api is always running on GPU:0. Is there any python api to set the device that the engine run?

**Comment by JosephChenHub** [comment]
> The engine built with python api is always running on GPU:0. Is there any python api to set the device that the engine run?

For pycuda, you can set the environment `CUDA_DEVICE` before 
```
import pycuda.driver as cuda
import pycuda.autoinit
```
e.g.,  to set `os.environ['CUDA_DEVICE'] = '1'` will make GPU:1 as the default device.  Another method provided in `onnx-tensorrt` is 
```
from ctypes import cdll, c_char_p
libcudart = cdll.LoadLibrary('libcudart.so')
libcudart.cudaGetErrorString.restype = c_char_p
def cudaSetDevice(device_idx):
    ret = libcudart.cudaSetDevice(device_idx)
    if ret != 0:
        error_string = libcudart.cudaGetErrorString(ret)
        raise RuntimeError("cudaSetDevice: " + error_string)

```

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Comment by RunningLeon** [comment]
@nvpohanh Hi, is it normal that after set device to 1, GPU memory on device 0 is also used when do inference? When I run the engine with `trtexec` with `--device=1`,  no GPU memory from device 0 is used.

**Comment by nvpohanh** [comment]
That may be a bug in trtexec code...

**Comment by RunningLeon** [comment]
> That may be a bug in trtexec code...
@nvpohanh 
Why is that? When `--device=1`, it's reasonable to use GPU memory only from device 1.

**Comment by nvpohanh** [comment]
You are correct. Could you open a new issue for this and provide repro steps? After that, @zerollzeng can try to repro and open an internal tracker for this issue. Thanks
