### ISSUE TITLE
"Could not find train-images-idx3-ubyte in data directories:" For sampleINT8API code

### ISSUE THREAD

**Issue by mehul-rigyn** [NVIDIA/TensorRT#1054]
Hello when I run the sampleINT8API application I get following error
**Could not find train-images-idx3-ubyte in data directories:**

How and where can I find this required data?

**Comment by ttyio** [comment]
Hello @mehul-rigyn , thanks for question,
this is the mnist dataset can be download from http://yann.lecun.com/exdb/mnist/

**Comment by mehul-rigyn** [comment]
@ttyio Where shall I extract these files? I see that there are 4 zip files.

**Comment by ttyio** [comment]
Hello @mehul-rigyn , you can extract to any folder, and specify using option --data, more detail is in the help:

    --data=/path/to/data/dir. Specify data directory to search for above files in case absolute paths to files are not provided. Defaults to data/samples/int8_api/ or data/int8_api/

**Comment by mehul-rigyn** [comment]
Got it Thanks @ttyio
