### ISSUE TITLE
memory cost

### ISSUE THREAD

**Issue by KOOKOKOK** [NVIDIA/TensorRT#1056]
## Description
 Python API cost more 1.5GB memmory of graphis hardware than C++ API when I use the custom model yolov5s.

## Environment

**TensorRT Version 7.2.1: 
**NVIDIA GPU RTX TITAN: 
**NVIDIA Driver 450.102.04: 
**CUDA Version 11.0: 
**CUDNN Version 8.0.5: 
**Operating System Ubuntu 18.04.5 LTS x64: 
**Python Version (if applicable) 3.7: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable) 1.7.1: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

github link : https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5

**Comment by KOOKOKOK** [comment]
In addtion, when I try to debug the code , I find that  the step of    "with open(engine_file_path, "rb") as f:
            engine = runtime.deserialize_cuda_engine(f.read())" cost more about 1.5 GB memmory, while the engine file is 16MB.

**Comment by ttyio** [comment]
Hello @KOOKOKOK , thanks for reporting,
the python binding is already open sourced, and here is the code for deserialize_cuda_engine, the code is simple just using pybind11, I did not see any extra resource allocation here.

https://github.com/NVIDIA/TensorRT/blob/master/python/src/infer/pyCore.cpp#L626

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists in TRT 8.4. Thanks
