### ISSUE TITLE
Cuda failure: 209, Only V100 or T4 GPUs is supported?

### ISSUE THREAD

**Issue by colourful-tree** [NVIDIA/TensorRT#106]
OS: ubuntu 18.04
CUDA: 10.1
cudnn: 7.6.3
TensorRT: 5.1.5

build with **V100** is everything fine.

but build with **M60** will:
```
[TensorRT] INFO: Graph construction and optimization completed in 0.00441909 seconds.
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing <reformat>(9)
[TensorRT] INFO: Tactic 0 time 0.016064
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing <reformat>(9)
[TensorRT] INFO: Tactic 0 time 0.01232
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing <reformat>(9)
[TensorRT] INFO: Tactic 0 time 0.009248
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing (Unnamed Layer* 1) [Fully Connected](15)
[TensorRT] INFO: Tactic -7597689592892725774 time 0.203616
[TensorRT] INFO: Tactic 8436800165353340181 time 0.108384
[TensorRT] INFO: Tactic 8292480392881939394 time 0.132352
[TensorRT] INFO: Tactic 6241535668063793554 time 0.192928
[TensorRT] INFO: Tactic 2624962759642542471 time 0.123168
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing (Unnamed Layer* 1) [Fully Connected](6)
[TensorRT] INFO: Tactic 0 time 0.202592
[TensorRT] INFO: Tactic 1 time 0.129856
[TensorRT] INFO: --------------- Chose 15 (8436800165353340181)
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing (Unnamed Layer* 1) [Fully Connected](15)
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing (Unnamed Layer* 1) [Fully Connected](6)
[TensorRT] INFO: Tactic 4 time 0.134848
[TensorRT] INFO: Tactic 8 time 0.1352
[TensorRT] INFO: Tactic 5 time 0.123072
[TensorRT] INFO: Tactic 9 time 0.123328
[TensorRT] INFO: --------------- Chose 6 (5)
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing <reformat>(9)
[TensorRT] INFO: Tactic 0 time 0.016544
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing <reformat>(9)
[TensorRT] INFO: Tactic 0 time 0.014688
[TensorRT] INFO:
[TensorRT] INFO: --------------- Timing (Unnamed Layer* 2) [PluginV2Ext](34)
Cuda failure: 209
Aborted (core dumped)
```

and I debug this, find error at：
qkvToContextPlugin.cu -> launchTransQkv  --> CHECK(cudaPeekAtLastError());

**Comment by DilipSequeira** [comment]
TensorRT core should run fine on M60. It seems to be a problem with the plugin; my initial suggestion would be to check that you're compiling  qkvToContextPlugin.cu file for that device.

**Comment by colourful-tree** [comment]
> TensorRT core should run fine on M60. It looks like the BERT sample is set up to compile only for SM 7.0 and 7.5. I suggest adjusting CMAKE_CUDA_FLAGS in CMakeLists.txt.

@DilipSequeira Thanks! I try to set CMAKE_CUDA_FLAGS to 60(P100) or 61(P40), it's worked.
But, when i set CMAKE_CUDA_FLAGS  to 52(M60) or 37(K80), i get a error:
![image](https://user-images.githubusercontent.com/17588577/64326568-d09a6b80-cffc-11e9-971f-c506301ea388.png)

**Comment by colourful-tree** [comment]
> TensorRT core should run fine on M60. It looks like the BERT sample is set up to compile only for SM 7.0 and 7.5. I suggest adjusting CMAKE_CUDA_FLAGS in CMakeLists.txt.

@DilipSequeira I google some information, i got this. And i try to build with compute_53, 6x and 7x is ok. So i think "Half-precision floating-point operations" is must, correct me if I wrong.
![image](https://user-images.githubusercontent.com/17588577/64329259-8e275d80-d001-11e9-8f31-baef1ea0b26c.png)

**Comment by DilipSequeira** [comment]
Thanks for trying this. I was not previously familiar with that sample, but those are indeed fp16 intrinsics. So it will not work on M60.
