### ISSUE TITLE
use fp16 or int8 to accelerate  inference of siamrpn

### ISSUE THREAD

**Issue by JensenHJS** [NVIDIA/TensorRT#107]
maybe there are something that tensorrt does not support. so i want to know whether the tensorrt can accelerate siamrpn？Siamrpn is a target tracking algorithm and I train it by pytorch.
In addition，the siamrpn network is only a few layers. Maybe i can use fp16 or int8 to inference in pytorch. What should I do？Please give me some advices.

**Comment by DilipSequeira** [comment]
I suggest using the PyTorch ONNX exporter and seeing if you can import the result into TensorRT. I'm afraid you'd have to ask elsewhere for help accelerating lower precision inference in PyTorch itself.

**Comment by GOBish** [comment]
Hi, I am looking to do something similar. Did you have any success?

**Comment by ShirGrinblat** [comment]
@GOBish @DilipSequeira @JensenHJS @rmccorm4  Any solution? I'm trying to convert [https://github.com/STVIR/pysot into ](url)TensorRT without any success.

**Comment by GOBish** [comment]
@ShirGrinblat i was not able to but you may want to check out VPI from NVIDIA

https://info.nvidia.com/rs/156-OFN-742/images/Webinar_PDF-Implementing_computer_vision_image_processing_solutions_with_VPI.pdf?mkt_tok=eyJpIjoiWVRnd05tSTVaVGxoTkdaaCIsInQiOiJNa09jeDg0bUpxcG95WjAzTzBuVVdJaFRRXC90OU5HUGhpVE0rN0RiRk5LUGFZN3VHTkRNV0hCZWtYZURUWmJ4SER4Wnl1cEd3d1RqVFhJZXRENnBtR1FmSVJISk5DZytTNzZwK1d1VHRmXC95d2VkTlRBbG1SbkdGRUpKcWNlVm0yIn0%3D
