### ISSUE TITLE
Can't release memory when I run the tensorRT inference

### ISSUE THREAD

**Issue by Mrxiaofei** [NVIDIA/TensorRT#1072]
## Description

I used the TensorRT do inference, when I want to release the memory, it failed.

## Environment

**TensorRT Version**: 7.2
**NVIDIA GPU**: 1080
**NVIDIA Driver Version**: 440.33
**CUDA Version**: 10.2
**CUDNN Version**: 8
**Operating System**: Linux
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

You can put inference in a loop,when the Object(include engine builder) release,but the memory can't release.

**Comment by JosephChenHub** [comment]
hi, you might try to free the `context` before destroying the engine builder.

**Comment by Mrxiaofei** [comment]
@JosephChenHub 
Hi,I know what you mean.
Following is my parts of class:
1、The member of class:
    IRuntime* mRuntime;
    nvinfer1::ICudaEngine* mEngine{nullptr}; //!< The TensorRT engine used to run the network
    nvinfer1::IExecutionContext* mContext;
2、The parts of build engine function:
    mRuntime = createInferRuntime(sample::gLogger.getTRTLogger());
    mEngine = mRuntime->deserializeCudaEngine(engineData.data(), fsize, nullptr);
    mContext = mEngine->createExecutionContext();
3、The deconstruct function：
        mContext->destroy();
        mEngine->destroy();
        mRuntime->destroy();
For ResNet50,the maximum memory is 388MiB，after the the deconstruct function is called,It's still there 255MiB.So I want to release all memory.
My code is writed in shared_ptr previously, such as std::shared_ptr<nvinfer1::ICudaEngine> mEngine{nullptr}。
Conlusion：I want to release all the memory,but it's there residual memory.

**Comment by ttyio** [comment]
Hello @Mrxiaofei , thanks for reporting.
After cublas, cudnn loaded, some host and device memory are reserved and will not be released until you dlclose the library or exit the process (some might for gpu kernels, some might for kernel management in host ....). 
If you call createXYZ and destroy in tensorrt multiple times, the memory reservation not increased, then we will not treat it as memory leak.

**Comment by Mrxiaofei** [comment]
Hello@ttyio ,thanks for replying.
I tested it just now. The residual memories is changeless even though loading multiple models.
Thank you again for your reply！

**Comment by KorovkoAlexander** [comment]
@Mrxiaofei did you find the solution for your case? I`m facing the same issue...

**Comment by 1811081031** [comment]
> Hello @Mrxiaofei , thanks for reporting.
> After cublas, cudnn loaded, some host and device memory are reserved and will not be released until you dlclose the library or exit the process (some might for gpu kernels, some might for kernel management in host ....).
> If you call createXYZ and destroy in tensorrt multiple times, the memory reservation not increased, then we will not treat it as memory leak.

@ttyio How to dlclose the cudnn and cublas libraries loaded by tensorrt? Looking forward to your recovery。

**Comment by ttyio** [comment]
@1811081031 , we cannot dlclose them but we have setTacticSource to disable the cudnn, cublas

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#a37a53d51544307e31a274986ab6dad53

**Comment by 1811081031** [comment]
> @1811081031 , we cannot dlclose them but we have setTacticSource to disable the cudnn, cublas
> 
> https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#a37a53d51544307e31a274986ab6dad53

Thank you for your reply！I want to release the CPU and GPU memory occupied by tensorrt without the end of the program process, because these occupations cause other programs to fail to start. Can setTacticSource do it?

**Comment by ttyio** [comment]
@1811081031 , you could take a try, you have to rebuild the trt engine file, and this can save memory when other part of your software not using culas/cudnn.

**Comment by 1811081031** [comment]
> @1811081031 , you could take a try, you have to rebuild the trt engine file, and this can save memory when other part of your software not using culas/cudnn.

Do you have a sample program to test the effect of setTacticSource? If there is this program, can it be shown for my reference? thank you very much.
