### ISSUE TITLE
MaskRCNN Sample error converting to uff: ValueError: Dimension 1 in both shapes must be equal, but are 324 and 12. Shapes are [1024,324] and [1024,12]. for 'Assign_376' (op: 'Assign') with input shapes: [1024,324], [1024,12].

### ISSUE THREAD

**Issue by sisaha9** [NVIDIA/TensorRT#1074]
ValueError: Dimension 1 in both shapes must be equal, but are 324 and 12. Shapes are [1024,324] and [1024,12]. for 'Assign_376' (op: 'Assign') with input shapes: [1024,324], [1024,12].

I get this when I am converting my custom trained model. It loads the pretrained COCO weights and uses transfer learning to update it. It also takes in images of 256 x 256 and has only 3 classes (including background) to train. It's also built on resnet50 instead of resnet101

What all changes do I need to make to get it to work?

Here is my MaskRCNN config it it helps:
Configurations:
BACKBONE                       resnet50
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  256
IMAGE_META_SIZE                15
IMAGE_MIN_DIM                  256
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [256 256   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               10
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           car_obstacle_detection
NUM_CLASSES                    3
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (8, 16, 32, 64, 128)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                5
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           32
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               5
WEIGHT_DECAY                   0.0001

I have made all the necessary changes and it seems the default COCO will work (though I cancelled it since I didn't want it. it didn't give the errors though and instead made a huge table)

**Comment by sisaha9** [comment]
Nevermind the default weights provided get a 
, line 87, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range

**Comment by sisaha9** [comment]
Second issue with default weights is resolved. I still don't know how to customize for MaskRCNN with backbone Resnet50 and changing things around depending on my configuration. Any guidance there would be appreciated

**Comment by sisaha9** [comment]
Another update. I got past that issue using this: https://github.com/NVIDIA/TensorRT/issues/240

**Comment by rgkannan676** [comment]
> Nevermind the default weights provided get a , line 87, in convert_add uff_graph.binary(inputs[0], inputs[1], 'add', name) IndexError: list index out of range

Hi, Can you please explain how you resolved this issue?
