### ISSUE TITLE
lnk2001: unresolved external symbol "class sample::Logger sample::gLogger"

### ISSUE THREAD

**Issue by batselem** [NVIDIA/TensorRT#1078]
## Description

I am using samples/common libraries with TensorRT. However, I got the following error when compiling gLogger(). It works fine if I create and use my own gLogger class. How can I solve this issue? I am using Visual Studio 2017 and have added the path to sample/common to both "Linker -> Additional Library Directories" and "C/C++ -> Additional Include Directories. I wonder if there is any way to make it run without re-building TensorRT+samples/common libraries with cmake on Windows 10.

## Error Message
```
1>Tensorrt_Yolov4.obj : error LNK2001: unresolved external symbol "class sample::LogStreamConsumer sample::gLogError" (?gLogError@sample@@3VLogStreamConsumer@1@A)
1>Tensorrt_Yolov4.obj : error LNK2001: unresolved external symbol "class sample::Logger sample::gLogger" (?gLogger@sample@@3VLogger@1@A)
1>...\Visual Studio 2017\Projects\...\x64\Release\....exe : fatal error LNK1120: 2 unresolved externals
```

## Environment

**TensorRT Version**: 7.2.1.6
**NVIDIA GPU**: RTX-3070
**NVIDIA Driver Version**: 27.21.14.6140
**CUDA Version**: 11.1
**CUDNN Version**: 8.0
**Operating System**: Windows 10
**Python Version (if applicable)**: No
**Tensorflow Version (if applicable)**: No
**PyTorch Version (if applicable)**: No
**Baremetal or Container (if so, version)**: No

**Comment by batselem** [comment]
Solved it by copying all cpp and headers to the working directory and including its path

**Comment by ttyio** [comment]
Closing since it is solved, thanks
