### ISSUE TITLE
How to run my Own yolov3 model in tensorrt ?

### ISSUE THREAD

**Issue by benz725** [NVIDIA/TensorRT#1079]
Things is like that. 
In the $TENSORRT_ROOT/samples/python/yolov3_onnx, there is a sample to use yolo to build engine to do tensorrt inference. But when I use my own weight to do inference. It reported: 

> Running inference on image dog.jpg...
> Traceback (most recent call last):
>   File "onnx_to_tensorrt.py", line 185, in <module>
>     main()
>   File "onnx_to_tensorrt.py", line 165, in main
>     trt_outputs = [output.reshape(shape) for output, shape in zip(trt_outputs, output_shapes)]
>   File "onnx_to_tensorrt.py", line 165, in <listcomp>
>     trt_outputs = [output.reshape(shape) for output, shape in zip(trt_outputs, output_shapes)]
> ValueError: cannot reshape array of size 6498 into shape (1,255,19,19)

I found the onnx_to_tensorrt.py line 154(#Output shapes expected by the post-processor): 

>     output_shapes = [(1, 255, 19, 19), (1, 255, 38, 38), (1, 255, 76, 76)]
the output shpaes has been defined, why the shapes should be defined like this.
How to run my own yolov3 weight to run this sample?
Thanks very much!

**Comment by themozel** [comment]
> Things is like that.
> In the $TENSORRT_ROOT/samples/python/yolov3_onnx, there is a sample to use yolo to build engine to do tensorrt inference. But when I use my own weight to do inference. It reported:
> 
> > Running inference on image dog.jpg...
> > Traceback (most recent call last):
> > File "onnx_to_tensorrt.py", line 185, in 
> > main()
> > File "onnx_to_tensorrt.py", line 165, in main
> > trt_outputs = [output.reshape(shape) for output, shape in zip(trt_outputs, output_shapes)]
> > File "onnx_to_tensorrt.py", line 165, in 
> > trt_outputs = [output.reshape(shape) for output, shape in zip(trt_outputs, output_shapes)]
> > ValueError: cannot reshape array of size 6498 into shape (1,255,19,19)
> 
> I found the onnx_to_tensorrt.py line 154(#Output shapes expected by the post-processor):
> 
> > ```
> > output_shapes = [(1, 255, 19, 19), (1, 255, 38, 38), (1, 255, 76, 76)]
> > ```
> 
> the output shpaes has been defined, why the shapes should be defined like this.
> How to run my own yolov3 weight to run this sample?
> Thanks very much!

I have the exact same problem. Have you found any solution for this ?

**Comment by jkjung-avt** [comment]
I shared my TensorRT yolov4/yolov3 implementation which could handle custom models directly.  Feel free to check it out.

[Demo #5: YOLOv4](https://github.com/jkjung-avt/tensorrt_demos#yolov4)
[TensorRT YOLO For Custom Trained Models (Updated)](https://jkjung-avt.github.io/trt-yolo-custom-updated/)

**Comment by themozel** [comment]
> I shared my TensorRT yolov4/yolov3 implementation which could handle custom models directly. Feel free to check it out.
> 
> [Demo #5: YOLOv4](https://github.com/jkjung-avt/tensorrt_demos#yolov4)
> [TensorRT YOLO For Custom Trained Models (Updated)](https://jkjung-avt.github.io/trt-yolo-custom-updated/)

The guide works like a charm ! 
Thank you
