### ISSUE TITLE
custom layer issue on caffe parser

### ISSUE THREAD

**Issue by ylCodelab** [NVIDIA/TensorRT#108]
std::string pluginName;
                nvinfer1::PluginFieldCollection fc;
                std::vector<nvinfer1::PluginField> f;
                if (layerMsg.type() == "Normalize")
                {
                    pluginName = "Normalize_TRT";
                    f = parseNormalizeParam(layerMsg, weights, *mBlobNameToTensor);
                }
                else if (layerMsg.type() == "PriorBox")
                {
                    pluginName = "PriorBox_TRT";
                    f = parsePriorBoxParam(layerMsg, weights, *mBlobNameToTensor);
                }
                else if (layerMsg.type() == "DetectionOutput")
                {
                    pluginName = "NMS_TRT";
                    f = parseDetectionOutputParam(layerMsg, weights, *mBlobNameToTensor);
                }
                else if (layerMsg.type() == "RPROI")
                {
                    pluginName = "RPROI_TRT";
                    f = parseRPROIParam(layerMsg, weights, *mBlobNameToTensor);
                }

                if (mPluginRegistry.find(pluginName) != mPluginRegistry.end())

for the developer who use Iplugin Creator for caffe custom layer, it seems that     if (mPluginRegistry.find(pluginName) != mPluginRegistry.end()) couldn't find the plugin layer name which I register from outside the framework.

Issue locates on caffeparser.cpp

**Comment by rmccorm4** [comment]
Hi @ylCodelab,

Can you please check if there are still issues in TensorRT 7? Also, please see this sample for adding custom layers to Caffe parser: https://github.com/NVIDIA/TensorRT/tree/release/7.0/samples/opensource/samplePlugin

**Comment by rmccorm4** [comment]
Closing since no response
