### ISSUE TITLE
Serialize multiple models at the same time

### ISSUE THREAD

**Issue by mltloveyy** [NVIDIA/TensorRT#1088]
I encapsulated the serialization operation into a function, but when I serialize and save multiple models at the same time, it will automatically exit after serializing the first model. When it is run again, it will serialize and save the second model and exit the program, and so on
I guess it was caused by the shutdown of the builder, network or parser, but I'm not sure which caused it or other reasons. Below is my function:
`serializecaffe2trt(ICudaEngine* engine, const std::string& protostr, 
                   const std::string& modelstr, const std::string& serialized_model) {
  // create the builder
  initLibNvInferPlugins(&gLogger, "");
  IBuilder* builder = createInferBuilder(gLogger);
  assert(builder != nullptr);

  builder->setMaxWorkspaceSize(1 << 30);
  builder->setMaxBatchSize(10);

  // Parse the caffe model to populate the network, then set the outputs
  INetworkDefinition* network = builder->createNetwork();
  nvcaffeparser1::ICaffeParser* parser = nvcaffeparser1::createCaffeParser();
  const nvcaffeparser1::IBlobNameToTensor* blobNameToTensor =
      parser->parse(protostr.c_str(), modelstr.c_str(), *network, DataType::kFLOAT);

  // Specify which tensors are outputs
  std::vector<std::string> blob_names = {"data", "prob"};
  blob_names = det_blob_names;
  for (int idx = 1; idx < blob_names.size(); idx++) {
    network->markOutput(*blobNameToTensor->find(blob_names[idx].c_str()));
  }

  // Build the engine
  engine = builder->buildCudaEngine(*network);
  assert(engine);

  // serialize the engine
  nvinfer1::IHostMemory* serializedModel{nullptr};
  serializedModel = engine->serialize();
  std::ofstream ofs(serialized_model, std::ios::out | std::ios::binary);
  ofs.write(static_cast<char*>(serializedModel->data()), serializedModel->size());
  ofs.close();

  // destroy the parser
  network->destroy();
  parser->destroy();
  builder->destroy();
}`

**Comment by nullian** [comment]
How did you slover this problem. I faced the similar error
