### ISSUE TITLE
Why does TensorRT OSS build requires prebuilt TensorRT binaries to build?

### ISSUE THREAD

**Issue by w3sip** [NVIDIA/TensorRT#1089]
The title pretty much says it all. Why it there that weird dependency on itself? Surely there's a reason, but is it a good one?

**Comment by pranavm-nvidia** [comment]
@w3sip TensorRT OSS does not include all the components of TRT - only parsers, plugins, samples, and python bindings. The optimizer/runtime libraries still have to come from the prebuilt packages. 

There's no dependency on components that are also part of OSS, i.e. you don't need the prebuilt parsers to build the OSS parsers, for example. It just happens to be the case that they're shipped together with the other TRT libraries.

**Comment by w3sip** [comment]
Oh. Well, that is unfortunate. We've been fighting a bug for a few weeks now, and were hoping to debug it, since there seems to be not much help from nVidia. Is serialization/deserialzation part of the OSS, or does it depend on the binaries?

For complete context, this is the issue we're trying to resolve: https://forums.developer.nvidia.com/t/issue-with-tensorrt-7-1-3-on-jetson-agx/168119/7 ... and with the cadence of Jetpack releases, it seems like fixing it on our own, either through a workaround, an open source part of TRT, or a miracle is the only way.

**Comment by pranavm-nvidia** [comment]
> Is serialization/deserialzation part of the OSS, or does it depend on the binaries?

Serialization/Deserialization is part of the core libraries, so not available in OSS. 

The bug you're describing sounds familiar. IIRC, it was a problem with the PriorBox plugin's serialization/deserialization routines (hence why you see it only in SSD). 
I believe it was fixed in 7.2, although the code here doesn't seem to include the fix - @rajeevsrao any idea what might have happened?

**Comment by w3sip** [comment]
@pranavm-nvidia - is there a way to get 7.2 binaries for Jetson? I've seen the reports of priorbox problems on 7.1.3 in my searches; while I wouldn't rule it out, dumping the individual outputs of the model's layers seem to show the divergence from the "correct" result around the layer "fc6", which is higher upstream from the priorbox.

Would love to give 7.2 a try -- but then we run into the problem of the cadence of Jetpack releases -- 4.5.1 is the latest one, and still includes 7.1.3.

**Comment by pranavm-nvidia** [comment]
@w3sip So there is a preview build here: https://developer.nvidia.com/embedded/20.09-jetson-cuda-x-ai-developer-preview

I looked briefly at the repo you linked, and it looks like your model uses [static input shapes](https://github.com/w3sip/sampleTRT/blob/master/data/model/deploy.prototxt#L3). I'm wondering if you could circumvent this issue entirely by constant-folding the prior boxes? AFAICT, they shouldn't change from run-to-run. Plus it would make inference a little bit faster :slightly_smiling_face: 


> dumping the individual outputs of the model's layers seem to show the divergence from the "correct" result around the layer "fc6", which is higher upstream from the priorbox.

This is interesting. How much divergence are we talking about? Could it be within rounding error?
And are the subsequent layers correct again?

**Comment by zmasood-sh** [comment]
@pranavm-nvidia Could you please elaborate on the "constant-folding the prior box" bit, preferably with an example? Just trying to understand what you have in mind and how you think that would help solve the case. Thanks.

**Comment by pranavm-nvidia** [comment]
@zmasood-sh As I understand it, the prior boxes only depend on the size of the input images (constant in this case) and some constant parameters. So it should be possible to generate the boxes ahead of time, and then insert them into the model as constants.

I don't have an example since I'm not terribly familiar with Caffe, but really it would just boil down to using a `Constant` layer instead of `Priorbox`.

**Comment by w3sip** [comment]
@pranavm-nvidia  -- running the modified sample_ssd with sample model (without the changes being discussed above) on Jetpack beta results in consistent assertion:
`#assertionnormalizePlugin.cpp,114`
which occurs during inference *if* the CUDA engine is deserialized. If the engine is built straight from the model files, inference completes successfully.

**Comment by w3sip** [comment]
Would it be possible for you guys to add serialization/deserialization to sample_ssd, and confirm it working on Jetpack? It seems like it's broken in all the version after 6.0, albeit in different ways.
I would never rule out a bug on our side, but then again -- having a sample as baseline would go a long way.

**Comment by pranavm-nvidia** [comment]
@rajeevsrao Do you know if we already have an SSD sample that serializes/deserializes the engine?

> And the weird thing is, with 7.2.0, we don't even need to use the de-serialized engine to trip the assertion:

That is weird, especially since `NormalizePlugin::serialize` [is const](https://github.com/NVIDIA/TensorRT/blob/release/7.2/plugin/normalizePlugin/normalizePlugin.cpp#L123).

**Comment by w3sip** [comment]
@pranavm-nvidia -- I've thought about the exact same thing about `const`. But the weirdness doesn't stop there.

The sample generates expected output (with `keep_count` of 41) when serialization is disabled as of commit 
https://github.com/w3sip/sampleTRT/blob/2429f65540b030c9379db2a9b2e6030e67536d89/samples/opensource/sampleSSD/sampleSSD.cpp

However, changing just this one thing:
https://github.com/w3sip/sampleTRT/commit/5394accce33a00c321aea41f8bf37699eef92647#diff-db566da08ea4506a1e553f5b0f68a94ffaf29dfc823c4bf795ec90dc589f5732

results in `keep_count` of 96, and some suspect looking coordinates.

It shouldn't matter if the context is created before or after the buffers? Or there are things happening implicitly during buffer creation that affect inference later?

**Comment by pranavm-nvidia** [comment]
@w3sip It shouldn't matter AFAICT - the [BufferManager constructor](https://github.com/NVIDIA/TensorRT/blob/release/7.2/samples/common/buffers.h#L245) isn't really doing much beyond checking the input/output sizes and then allocating memory. Seems like something is fundamentally broken somewhere :thinking:

**Comment by w3sip** [comment]
@pranavm-nvidia -- it looks like the weirdness is specific to beta (where it is the 3 cudaMalloc calls that BufferManager does, that make the difference with before/after placement). 

On JetpackR32.4.3/TRT 7.1.3  the relative placement of the mentioned calls doesn't make a difference, nor does a call to serialization (as long as the serialized model isn't used).

**Comment by pranavm-nvidia** [comment]
@w3sip Yeah, might be better to stay away from the preview build then. Sounds like something is very wrong there. 

Is it possible for you to build the plugins from here? You should be able to use the 7.2 plugins with the 7.1.3 TRT libraries. 
Hopefully either the `release/7.2` or `master` branch just works.

**Comment by w3sip** [comment]
@pranavm-nvidia So, I've managed to build it (which was a bit of an adventure by itself) -- and surprisingly, it fixed the original issue. 
The surprising part is two-fold:
- I've built off 7.1.3 tag. So, at least in theory, the same code as shipping on Jetpack 4.4?
- The size of the resulting library is about 3x of that found on Jetpack.

**Comment by pranavm-nvidia** [comment]
@w3sip It looks like the 7.2 fixes were [backported to 7.1.3](https://github.com/NVIDIA/TensorRT/commit/9a9cae75e7155b2114454f37ccc49eca9d3352dc), so not exactly the same code.

Looks like some of the new plugins from 7.2 were also pulled in, which might partly explain difference in library size. The other reason would be if you're building for more SMs compared to the versions in JP. Just to be sure, you're referring to the size of `libnvinfer_plugin.so` right?

**Comment by w3sip** [comment]
@pranavm-nvidia - good point. Haven't realized 7.1.3 isn't really 7.1.3 :)
Re: size, I've built it with "53;60;61;62;72" for SMs; and the size did go down rebuilding it for just "62" -- from 18MB to about 14MB.  Still far from the 5MB in Jetpack.
The size isn't a big deal by itself, just curious.
In any case, many thanks for your ongoing help.

**Comment by pranavm-nvidia** [comment]
Yeah, the other 9MB probably comes from the newly added plugins. The plugin changes are >15k LOC so that might explain it :slightly_smiling_face:

**Comment by ttyio** [comment]
I will close this, please reopen if you still have question, thanks!
