### ISSUE TITLE
fail to quantize model : Operator `Equal` in INT8 mode 

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TensorRT#1092]
## Description
It seems that the operator 'Equal' or 'Cast' does not support the INT8 mode, and the whole network fails to build the quantized model.  Any suggestions? 
 
![Screenshot from 2021-03-01 10-43-04](https://user-images.githubusercontent.com/22444830/109445904-925bfc00-7a7b-11eb-9aa2-f35e7cd6627c.png)

## Environment

**TensorRT Version**: 7.2.1
**NVIDIA GPU**: 2080Ti
**NVIDIA Driver Version**: 10.2 
**CUDA Version**:  10.2
**CUDNN Version**: 8.0
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

 
## Step to Reproduce
```
import torch
import torch.nn as nn

class Foo(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 80, kernel_size=3, stride=1, padding=1)
        self.bn = nn.BatchNorm2d(80)
        self.relu = nn.ReLU(True)

    def forward(self, x):
        x = self.relu(self.bn(self.conv(x)))
        x = torch.sigmoid(x)
        y = nn.functional.max_pool2d(x, (3,3), stride=1, padding=1)
        z = (x==y).float() # equal, cast
        return x * z


net = Foo()
x = torch.randn(1, 3, 512, 512)
y = net(x)
torch.onnx.export(net, x, "foo.onnx", export_params=True, opset_version=11)
```
The tensorrt engine is generated via
```
...
self.config.set_flag(trt.BuilderFlag.INT8)
self.config.set_flag(trt.BuilderFlag.STRICT_TYPES)
self.config.int8_calibrator = calibrator
self.builder.min_find_iterations = 1
self.builder.average_find_iterations = 1

trt_engine = self.builder.build_engine(self.network, self.config)
```
And the log is 
```
[TensorRT] VERBOSE: >>>>>>>>>>>>>>> Chose Runner Type: TiledPooling Tactic: 6553857
[TensorRT] VERBOSE:
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,512,262144,20971520), Float(1,512,262144,20971520) -> Float(1,512,262144,20971520) ***************
[TensorRT] VERBOSE: --------------- Timing Runner: {Equal_5,Cast_6,Mul_7} (Myelin)
[TensorRT] VERBOSE: Tactic: 0 is the only option, timing skipped
[TensorRT] VERBOSE: Fastest Tactic: 0 Time: 0
[TensorRT] VERBOSE: Formats and tactics selection completed in 1.37665 seconds.
[TensorRT] VERBOSE: After reformat layers: 4 layers
[TensorRT] VERBOSE: Block size 268435456
[TensorRT] VERBOSE: Block size 83886080
[TensorRT] VERBOSE: Block size 83886080
[TensorRT] VERBOSE: Total Activation Memory: 436207616
[TensorRT] INFO: Detected 1 inputs and 1 output network tensors.
[TensorRT] VERBOSE: Conv_0 + Relu_2 (scudnn) Set Tactic Name: volta_scudnn_128x32_relu_small_nn_v1
[TensorRT] VERBOSE: Layer: Conv_0 + Relu_2 Weights: 0 HostPersistent: 1664 DevicePersistent: 1582080
[TensorRT] VERBOSE: Layer: Sigmoid_3 Weights: 0 HostPersistent: 0 DevicePersistent: 0
[TensorRT] VERBOSE: Layer: MaxPool_4 Weights: 0 HostPersistent: 0 DevicePersistent: 0
[TensorRT] VERBOSE: Layer: {Equal_5,Cast_6,Mul_7} Weights: 0 HostPersistent: 0 DevicePersistent: 0
[TensorRT] VERBOSE: Total Host Persistent Memory: 1664
[TensorRT] VERBOSE: Total Device Persistent Memory: 1582080
[TensorRT] VERBOSE: Total Weight Memory: 0
[TensorRT] VERBOSE: Engine generation completed in 1.99494 seconds.
[TensorRT] VERBOSE: Builder timing cache: created 8 entries, 2 hit(s)
[TensorRT] VERBOSE: Engine Layer Information:
[TensorRT] VERBOSE: Layer(scudnn): Conv_0 + Relu_2, Tactic: -3946921629105938337, input.1[Float(3,512,512)] -> 10[Float(80,512,512)]
[TensorRT] VERBOSE: Layer(Activation): Sigmoid_3, Tactic: 0, 10[Float(80,512,512)] -> 11[Float(80,512,512)]
[TensorRT] VERBOSE: Layer(PoolingTiled): MaxPool_4, Tactic: 6553857, 11[Float(80,512,512)] -> 12[Float(80,512,512)]
[TensorRT] VERBOSE: Layer(Myelin): {Equal_5,Cast_6,Mul_7}, Tactic: 0, 11[Float(80,512,512)], 12[Float(80,512,512)] -> 15[Float(80,512,512)]
[TensorRT] VERBOSE: Allocated persistent device memory of size 1582080
[TensorRT] VERBOSE: Allocated activation device memory of size 167772160
[TensorRT] VERBOSE: Assigning persistent memory blocks for various profiles
Dump tensorrt's engine to file: eng_ptq_foo_entropy.trt
```

**Comment by JosephChenHub** [comment]
And the calibration of this graph is ok. 
![image](https://user-images.githubusercontent.com/22444830/109458932-bb3eba00-7a98-11eb-9be3-541174e75556.png)

**Comment by ttyio** [comment]
Hello @JosephChenHub , the code generator in TensorRT 7.x cannot generates kernels operating on tensor has type `BOOL`, Is there any specific reason that you add 

         self.config.set_flag(trt.BuilderFlag.STRICT_TYPES)

in your code? usually this flag is used for precision consideration. To run the model with best performance, we need remove this option. Thanks!

**Comment by JosephChenHub** [comment]
> Hello @JosephChenHub , the code generator in TensorRT 7.x cannot generates kernels operating on tensor has type `BOOL`, Is there any specific reason that you add
> 
> ```
>      self.config.set_flag(trt.BuilderFlag.STRICT_TYPES)
> ```
> 
> in your code? usually this flag is used for precision consideration. To run the model with best performance, we need remove this option. Thanks!

Hi, I remove this line but it still generates a FP32 engine rather than doing INT8 calibration.

**Comment by ttyio** [comment]
Hello @JosephChenHub , 
Current 7.x implementation because the codegen for tensor has type `BOOL` has no INT8 support yet, so TRT will disable the INT8 flag for full network when `BOOL` tensor detected. We already have feature request internally for this potential perf issue.

And for the `STRICT_TYPES`, this cannot solve the INT8 issue, this flag is used with `ILayer::setOutputType()` and `ILayer::setPrecision()`, this is used for precision control.  I did not see these API called in your paste code, so I give this suggestion, sorry for confusion.

**Comment by JosephChenHub** [comment]
> Hello @JosephChenHub ,
> Current 7.x implementation because the codegen for tensor has type `BOOL` has no INT8 support yet, so TRT will disable the INT8 flag for full network when `BOOL` tensor detected. We already have feature request internally for this potential perf issue.
> 
> And for the `STRICT_TYPES`, this cannot solve the INT8 issue, this flag is used with `ILayer::setOutputType()` and `ILayer::setPrecision()`, this is used for precision control. I did not see these API called in your paste code, so I give this suggestion, sorry for confusion.

Thanks, waiting for the new feature.
