### ISSUE TITLE
[TensorRT] Problems relatived to the function 'scaledSoftmax' lead to wrong results of BERT models (SEQ_LEN > 128 and SEQ_LEN != 384)

### ISSUE THREAD

**Issue by yuanzexi** [NVIDIA/TensorRT#1097]
## Description
The implementation of **scaledSoftmax** results in wrong results of sum of softmax such that the results of BERT models (128 < seq_len < 384 and seq_len > 384) are very large or even 'nan', especially for FP16 mode.

To fix this problem, I provided a solution in this 'pull request' (https://github.com/NVIDIA/TensorRT/pull/1096) and look forward to your code review. Welcome to discussing this problem here.

## Environment

**TensorRT Version**:  TensorRT 7.0.0.11 and TensorRT 7.2.1.6
**NVIDIA GPU**:  GeForce GTX 1660 and TITAN V and Tesla T4
**NVIDIA Driver Version**: 440.36
**CUDA Version**: 10.0 and 10.2
**CUDNN Version**: 7.6.5 and 8.0.4
**Operating System**: Ubuntu 16 and Centos 7 and Windows

## Relevant Files

**File Location** : https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/common.cuh
Line 325 to Line 385

**Reproduce**: Testing BERT-base models with 128 < SEQ_LEN < 384 and 384 < SEQ_LEN, such that the QKV_context plugin chooses the 'scaledSoftmax' branch for computing softmax operation.

## Steps To Reproduce
Following the tutorial of https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT with BERT-Base models of SEQ_LEN = 160 in FP16 mode. We found that the results are 'nan'.

**Comment by ttyio** [comment]
Good catch @yuanzexi , I have comment in your PR, thank you!

**Comment by wellinxu** [comment]
What can we do now to avoid or solve this problem？ @ttyio

**Comment by ttyio** [comment]
Hello @wellinxu , you need build the libnvinfer_plugin.so from the opensouce repo, and replace the one installed in your system.

**Comment by ttyio** [comment]
I will close this issue since the PR is already in, thanks @yuanzexi
