### ISSUE TITLE
do I have to implement IPluginFactoryV2 in plugin?

### ISSUE THREAD

**Issue by clancylian** [NVIDIA/TensorRT#11]
I have seen the how to register plugin in the code, but If I have to implement IPluginFactoryV2 ? I haven't seen in the code, and just call the function 'initLibNvInferPlugins()' ? It can auto find plugin which I have registered or I have to set parser->setPluginFactoryV2(&pluginFactoryV2);
It confused me.

**Comment by nfeng0105** [comment]
@clancylian PluginFactory and PluginRegistry are two different manners to implement plugin layer. PlugnFactory is more friend to caffe plugin layer, while PluginRegistry is new introduced type for Uff and ONNX.
