### ISSUE TITLE
coule ICaffeParser parse a network without any parameters?

### ISSUE THREAD

**Issue by yaoqi-zd** [NVIDIA/TensorRT#110]
Hi, I'm writing a bilinear sampler plugin for tensorrt. To test if it works properly, I create a prototxt with only the input layer and a bilinear sampler layer, so the created network has no parameters. 

I have tried to feed another caffemodel file together with this prototxt when parsing the network and get segmentation fault. May I ask whether the ICafferParser support parsing a network without any parameters?

**Comment by nuanxinqing** [comment]
hi I have the same question,have you solved the problem?

**Comment by yaoqi-zd** [comment]
@nuanxinqing Yes, it can support parsing a network without any parameters. The segmentation fault problem encountered comes from the bug in my code.

**Comment by nuanxinqing** [comment]
me too------------------ 原始邮件 ------------------
发件人: "yaoqi_isee"<notifications@github.com>
发送时间: 2019年9月28日(星期六) 晚上9:07
收件人: "NVIDIA/TensorRT"<TensorRT@noreply.github.com>;
抄送: "Shi Yating"<824265060@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [NVIDIA/TensorRT] coule ICaffeParser parse a network without anyparameters? (#110)



@nuanxinqing Yes, it can support parsing a network without any parameters. The segmentation fault problem encountered comes from the bug in my code.
 
&mdash;
