### ISSUE TITLE
Just a question,not problem.The size of output data is four times larger than expected.

### ISSUE THREAD

**Issue by Mrxiaofei** [NVIDIA/TensorRT#1109]
## Description

My result is no problem.I output the last layer size,it is 4000, but the size of my network'output is 1000. I try to output other layer,but the size of output data is four times larger than expected.

## Environment

**TensorRT Version**: 7.0
**NVIDIA GPU**: 1080
**NVIDIA Driver Version**: 418
**CUDA Version**: 10.0
**CUDNN Version**: 7.5.1
**Operating System**: Linux
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce
1、I use trtexec to generate engine model and I set the outputname is "prob".
Following code is used:
for (auto& s : mOutputTensorNames)
    {
        network->markOutput(*blobNameToTensor->find(s.c_str()));
    }
2、Do inference.
Following code is used:
    const float* prob = static_cast<const float*>(buffers.getHostBuffer(outputTensorName));
    cout<<buffers.size(outputTensorName)<<endl;
The size of layer "prob" is 1000,but the buffers.size("prob") is 4000.
So I want to know why the size is four times larger than expected.

**Comment by jkjung-avt** [comment]
Because the output is float32 (4 bytes each)?

**Comment by jkjung-avt** [comment]
Then I have no idea....

**Comment by ttyio** [comment]
Hello @Mrxiaofei , is this an INT8 engine? thanks

**Comment by Mrxiaofei** [comment]
@ttyio No，it is FP32.

**Comment by ttyio** [comment]
@Mrxiaofei is the batch size when you enqueue/execute the same as the batch size when call the `BufferManager::BufferManager`?

**Comment by Mrxiaofei** [comment]
@ttyio Do you mean how to construct the object BufferManager?I do like this "samplesCommon::BufferManager buffers(mEngine, batch_size);" Also, my batch size is 1.

**Comment by ttyio** [comment]
@Mrxiaofei is this caffe or onnx model before import into trt?

**Comment by Mrxiaofei** [comment]
@ttyio Is a caffe model.In infer I use *.trt file.

**Comment by ttyio** [comment]
Hello @Mrxiaofei , could you share your caffe model with us? thanks!

**Comment by Mrxiaofei** [comment]
Hello@ttyio :
        You can use the TensorRT/data/resnet50/ResNet50_fp32.caffemodel that provided by tensorRT.The output size of resnet50 is 1000,but buffers.size("prob") is 4000. Also the code I provided had a mistake: const float prob = static_cast<const float*>(buffers.getHostBuffer(outputTensorName)); the right format is :const float * prob, prob is a pointer.

**Comment by ttyio** [comment]
Hello @Mrxiaofei ,

@jkjung-avt is right, because each element is 4 bytes. 
https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L318
https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L138

**Comment by Mrxiaofei** [comment]
@ttyio I see,thanks for your explanation！
