### ISSUE TITLE
pytorch-quantization examples are incompatible with latest torchvision reference scripts API

### ISSUE THREAD

**Issue by sjain-stanford** [NVIDIA/TensorRT#1112]
## Description

The example notebooks in pytorch-quantization such as [calibrate_quant_resnet50.ipynb](https://github.com/NVIDIA/TensorRT/blob/master/tools/pytorch-quantization/examples/calibrate_quant_resnet50.ipynb) rely on convenience methods from torchvision's [train.py](https://github.com/pytorch/vision/blob/master/references/classification/train.py) - such as `evaluate`, `train_one_epoch`, and `load_data`. The functional signatures of some of these methods changed in latest torchvision and that breaks the notebooks.

For example:
[Old](https://github.com/pytorch/vision/blob/24f16a338391d6f45aa6291c48eb6d5513771631/references/classification/train.py#L82)
```
def load_data(traindir, valdir, cache_dataset, distributed):
```

[New](https://github.com/pytorch/vision/blob/afc502bd669fe97001a50d0ce2373d13c011ed44/references/classification/train.py#L82)
```
def load_data(traindir, valdir, args):
```

As a temporary fix, reverting to this hash works:
```
git checkout 24f16a338391d6f45aa6291c48eb6d5513771631
```

**Comment by ttyio** [comment]
Thank you @sjain-stanford , we also hit this error in internal pipeline after upgrade docker image, will fix it.

**Comment by ttyio** [comment]
Fixed in https://github.com/NVIDIA/TensorRT/blob/release/8.0/tools/pytorch-quantization/examples/calibrate_quant_resnet50.ipynb
thanks and closing
