### ISSUE TITLE
Why do we load label files for calibration ?

### ISSUE THREAD

**Issue by CoinCheung** [NVIDIA/TensorRT#1119]
https://github.com/NVIDIA/TensorRT/blob/c8a30a45572f7d8fac7ba803d8b669cdb91893ce/samples/common/BatchStream.h#L50

Hi, 

Do we really need label files to calibrate model for int8 inference ?

**Comment by ttyio** [comment]
Hello @CoinCheung , the calibration process is the same as normal inference using precision FP32 without any layer fusion. So the label files is not necessary during calibration.

**Comment by CoinCheung** [comment]
Thanks for telling me this !!
