### ISSUE TITLE
Can onnx parser use custom plugin?

### ISSUE THREAD

**Issue by cuijianaaa** [NVIDIA/TensorRT#112]
Can onnx parser use custom plugin? I have found an example using caffe parser "samplePlugin" and an example using uff parser "sampleUffSSD", but dose it now support onnx parser plugin ?

**Comment by rmccorm4** [comment]
Duplicate of #6, please track there. We're looking into providing samples for ONNX + plugins.

**Comment by cuijianaaa** [comment]
Thanks!



发自我的iPhone


------------------ Original ------------------
