### ISSUE TITLE
how to create an engine serve for multiple source inputs?

### ISSUE THREAD

**Issue by HoangTienDuc** [NVIDIA/TensorRT#1121]
How can i create 1 engine (ex: 1 tensorrt detector engine) that can serve for 6 or 10 camera to detect object by using threading without get confused output between these source?

**Comment by ttyio** [comment]
Hello @HoangTienDuc , could you create multiple `IExecutionContext` and assign each `IExecutionContext` with 1 cuda stream when call `enqueueV2`. They are independent with each other. Thanks!

**Comment by HoangTienDuc** [comment]
hello @ttyio . Thanks for your guide. i work with python. Do you have any examples?

**Comment by ttyio** [comment]
Hello @HoangTienDuc , the python example of `IExecutionContext` and `enqueueV2` can be found in 

https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/inference.py#L126

We did not use multiple `IExecutionContext` in the code, but you can extend it.

BTW, we also have triton server built on top of Tensorrt, it has builtin schedule to handle multiple request. paste the link here in case you also interested.

https://github.com/triton-inference-server/server

**Comment by HoangTienDuc** [comment]
i am apologise becouse don't have much time for tensorrt.
Did you mean, with each thread i need to create each context and engine?
it willl take too much resource and take long time to init engine.

**Comment by ttyio** [comment]
Hello @HoangTienDuc , 

You need perform inference concurrently in multiple CUDA streams, right?

Let's use 1 engine from `deserialize_cuda_engine`, then create multiple context using `create_execution_context`.
Here the reason to use separate context is that context contains shared resources, therefore, calling enqueue or enqueueV2 in from the same context with different CUDA streams concurrently results in undefined behavior.

**Comment by HoangTienDuc** [comment]
many thank for nvidia, i also have long time used trtis. it is awesome. But these are some models (tf-frozen, onnx) that optimized online with tensorrt is not totally use gpu. Sometime, they used CPU to much, so i decided to try with tensorrt engine and plan model. 
Could i make 1 trt engine model serve multiple request from mutiple source like that?

**Comment by ttyio** [comment]
@HoangTienDuc , thanks for supporting ;)

And yes, you can make 1 trt engine, and create multiple context to serve multiple request concurrently by assigned different cuda stream.

**Comment by HoangTienDuc** [comment]
hello @ttyio 
i create 1 engine from deserialize_cuda_engine in __init__() and create create_new_context() function. each thread, i call create_new_context to get new context. But i still get confused outputs.
Could you please help me this problem?
```
import ctypes
import pycuda.autoinit
import pycuda.driver as cuda
import tensorrt as trt
import threading

class HostDeviceMem:
    def __init__(self, host_mem, device_mem):
        self.host = host_mem
        self.device = device_mem

    def __str__(self):
        return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)

    def __repr__(self):
        return self.__str__()


class InferenceBackend:
    # initialize TensorRT
    TRT_LOGGER = trt.Logger(trt.Logger.ERROR)
    trt.init_libnvinfer_plugins(TRT_LOGGER, '')

    def __init__(self, model, batch_size):
        self.cuda_ctx = cuda.Device(0).make_context()
        if self.cuda_ctx:
            self.cuda_ctx.push()
        self.model = model
        self.batch_size = batch_size
        # load plugin if the model requires one
        if self.model.PLUGIN_PATH is not None:
            try:
                ctypes.cdll.LoadLibrary(self.model.PLUGIN_PATH)
            except OSError as err:
                raise RuntimeError('Plugin not found') from err

        # load trt engine or build one if not found
        if not self.model.ENGINE_PATH.exists():
            self.engine = self.model.build_engine(InferenceBackend.TRT_LOGGER, self.batch_size)
        else:
            runtime = trt.Runtime(InferenceBackend.TRT_LOGGER)
            with open(self.model.ENGINE_PATH, 'rb') as engine_file:
                buf = engine_file.read()
                self.engine = runtime.deserialize_cuda_engine(buf)
        if self.engine is None:
            raise RuntimeError('Unable to load the engine file')
        if self.engine.has_implicit_batch_dimension:
            assert self.batch_size <= self.engine.max_batch_size

        if self.cuda_ctx:
        	self.cuda_ctx.pop()

    def create_new_context(self):
        if self.cuda_ctx:
            self.cuda_ctx.push()
        # allocate buffers
        self.bindings = []
        self.outputs = []
        for binding in self.engine:
            shape = self.engine.get_binding_shape(binding)
            size = trt.volume(shape)
            if self.engine.has_implicit_batch_dimension:
                size *= self.batch_size
            dtype = trt.nptype(self.engine.get_binding_dtype(binding))
            # allocate host and device buffers
            host_mem = cuda.pagelocked_empty(size, dtype)
            device_mem = cuda.mem_alloc(host_mem.nbytes)
            # append the device buffer to device bindings
            self.bindings.append(int(device_mem))
            if self.engine.binding_is_input(binding):
                if not self.engine.has_implicit_batch_dimension:
                    assert self.batch_size == shape[0]
                self.input = HostDeviceMem(host_mem, device_mem)
            else:
                self.outputs.append(HostDeviceMem(host_mem, device_mem))
        self.context = self.engine.create_execution_context()
        self.stream = cuda.Stream()
        if self.cuda_ctx:
        	self.cuda_ctx.pop()
        
    def infer(self):
        self.infer_async()
        return self.synchronize()

    def infer_async(self):
        if self.cuda_ctx:
            self.cuda_ctx.push()
        cuda.memcpy_htod_async(self.input.device, self.input.host, self.stream)
        if self.engine.has_implicit_batch_dimension:
            self.context.execute_async(batch_size=self.batch_size, bindings=self.bindings,
                                       stream_handle=self.stream.handle)
        else:
            self.context.execute_async_v2(bindings=self.bindings, stream_handle=self.stream.handle)
        for out in self.outputs:
            cuda.memcpy_dtoh_async(out.host, out.device, self.stream)
        if self.cuda_ctx:
            self.cuda_ctx.pop()

    def synchronize(self):
        if self.cuda_ctx:
        	self.cuda_ctx.push()
        self.stream.synchronize()
        if self.cuda_ctx:
        	self.cuda_ctx.pop()
        return [out.host for out in self.outputs]

```

**Comment by ttyio** [comment]
Hello @HoangTienDuc ,

Is the InferenceBackend.`stream`/`context`/`input`/`output` shared among all threads? If so they will override each other even each thread call into `create_new_context`.

**Comment by HoangTienDuc** [comment]
i call create_new_context in each thread, it mean, if i have 5 thread, i also have 5 different stream/context/input/output.
i checked as bellow
```
Thread 1: self.context, self.stream:  <tensorrt.tensorrt.IExecutionContext object at 0x7f0de5041df8> <pycuda._driver.Stream object at 0x7f0de511fb20>
Thread 2: self.context, self.stream:  <tensorrt.tensorrt.IExecutionContext object at 0x7f0de5118df8> <pycuda._driver.Stream object at 0x7f0de5033df8>
```
So i think they are isolated. Only InferenceBackend() is the same between these threads.

**Comment by ttyio** [comment]
@HoangTienDuc , 
From the code I see they are isolated on creating, but they all assigned to the global `InferenceBackend`, and later when we call `InferenceBackend::infer_async`, we are refer to the same `InferenceBackend::stream`,  `InferenceBackend::context` .....
Or maybe I am wrong because python have different object management compared to C++.

Where did you add the print, could we put the log in the `infer_async` function? I want to check the `context`, `stream` ... when you run the `infer_async`, thanks!

**Comment by HoangTienDuc** [comment]
i also add print in infer_async()
the result is bellow:
```
self.context, self.stream:  <tensorrt.tensorrt.IExecutionContext object at 0x7fc8930fc6c0> <pycuda._driver.Stream object at 0x7fc8930fc570>
self.context, self.stream:  <tensorrt.tensorrt.IExecutionContext object at 0x7fc8930fc768> <pycuda._driver.Stream object at 0x7fc89311ec38>
```
they are isolated

**Comment by ttyio** [comment]
@HoangTienDuc , have you tried remove all the `self.cuda_ctx` ? CUDA runtime will create a default ctx for us, I am not sure if the push/pop operations here would cause any race condition .

**Comment by HoangTienDuc** [comment]
if remove self.cuda_ctx, i think i cannot run trt engine with threading.
https://forums.developer.nvidia.com/t/how-to-use-tensorrt-by-the-multi-threading-package-of-python/123085/8

**Comment by ttyio** [comment]
Thank you @HoangTienDuc , I just read the link you post, now also learnt that we need ctx.push/pop after run the code.

I did some modification to the code in the post link, I see the result is correct when run multiple stream, could you take a check because I did not get all of your code? thanks

https://github.com/ttyio/github-issues/tree/main/1121

**Comment by HoangTienDuc** [comment]
hi @ttyio Thank for your help. it worked.
But after kill thread, it doesn't release vram even i pop() and delete context. 
i mean, if i kill and restart thread, vram is continuos increase.
Do you know how to complete release after kill thread.

And 1 more question. Does trt engine create multi instances?

**Comment by ttyio** [comment]
Hello expert @pranavm-nvidia , could you help to answer the question

     is ther any difference bettwen self.cuda_ctx = pycuda.autoinit.context and self.cuda_ctx = cuda.Device(0).make_context()

Thanks!


Hello @HoangTienDuc ,
for the resource leak, have you tried also release the memory that allocated using `cuda.mem_alloc`? maybe define function `reclaim` in the `perthreadResource` and call this function after kill thread? Or maybe you can reuse the `perthreadResource` on a new thread, so that there will no leak and you can keep them until you exit process.

What do you mean by `Does trt engine can be create multi instances?`, I am not sure what is `instance` means here.

**Comment by HoangTienDuc** [comment]
hi @ttyio Thank for your reply.
i reimplement my problem in this [repo](https://github.com/HoangTienDuc/github_issues)
i already delete cuda.mem_alloc but it doesn't work.
Python automatically clears the garbage, so it does't reuse the perthreadResource on a new thread. i think so.

does trt engine can create multi instance like bellow?
![instance](https://user-images.githubusercontent.com/53229746/111569610-92772e00-87d5-11eb-89f8-3c1010a5c7f0.png)

**Comment by ttyio** [comment]
@HoangTienDuc , Is `on_connect` only called once and `on_message` is called multiple times?
If so, have you tried `alloc_resource` once in the `on_connect` (remove the `alloc_resouce` in the `on_message`).

For the `instance` question, I have a feeling that the `context` in tensorrt is similar to the `instance` you draw in the pic.

**Comment by HoangTienDuc** [comment]
yes, on_connect only called once and on_message is called multiple times.
but if i alloc_resource  in the on_connect. i cannot create thread 2. because thread 1 and thread 2 will have the same resource.

**Comment by ttyio** [comment]
@HoangTienDuc , to solve this issue better, we need some `thread pool` and each thread in the pool assigned one resource, there is no need to free/alloc resource during the program life cycle.
If we decide to use current design to create new thread and new resource on message received, for resources like 

            host_mem = cuda.pagelocked_empty(size, np.float32)
            cuda_mem = cuda.mem_alloc(host_mem.nbytes)

We need call `free` manfully, python runtime cannot garbage the gpu resouces. Could you take a try? thanks!

           host_mem.free()
           cuda_mem.free()

**Comment by HoangTienDuc** [comment]
i tried
```
host_mem
'numpy.ndarray' object has no attribute 'free'
```
host_mem is a numpy array. so i try to delete it. 

```
            del resource.host_mem
            resource.cuda_mem.free()
            if resource.cuda_inputs:
                del resource.cuda_inputs
            else:
                del resource.cuda_outputs
```
But it doesn't work.

**Comment by ttyio** [comment]
@HoangTienDuc  

    >>> import pycuda.autoinit
    >>> import pycuda.driver as cuda
    >>> cuda_mem = cuda.mem_alloc(1024)
    >>> type(cuda_mem)
    <class 'pycuda._driver.DeviceAllocation'>
    >>> cuda_mem.free()

**Comment by ttyio** [comment]
@HoangTienDuc you are right host_mem is ndarray, so we need only free the cuda_mem

**Comment by HoangTienDuc** [comment]
yes. i did. but no effect.

**Comment by ttyio** [comment]
@HoangTienDuc , could you point me the code to free the resource? thanks

**Comment by HoangTienDuc** [comment]
i just updated my code.
here they are:

https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L112
https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L116

**Comment by ttyio** [comment]
@HoangTienDuc , let's try adding?

    del resource.context

**Comment by HoangTienDuc** [comment]
oh. free() does not clean garbage

![Screenshot from 2021-03-18 14-21-14](https://user-images.githubusercontent.com/53229746/111587768-3a502400-87f5-11eb-919d-6a356fcb14f5.png)

**Comment by HoangTienDuc** [comment]
> @HoangTienDuc , let's try adding?
> 
> ```
> del resource.context 
> ```

yes @ttyio  does not work

**Comment by ttyio** [comment]
@HoangTienDuc , could you track both cpu resource and gpu resource after each line of resource request and free. let first find which resource is leaked? the gpu side memory can be queried using

        pycuda.driver.mem_get_info

**Comment by HoangTienDuc** [comment]
to get mem info, i need to create new context in this case
```
            context = self.engine.create_execution_context()
            (free, total) = cuda.mem_get_info()
            
            if resource.cuda_inputs:
                for mem in resource.cuda_inputs:
                    mem.free()
                del resource.cuda_inputs
            print(cuda.mem_get_info())

            if resource.cuda_outputs:
                for mem in resource.cuda_outputs:
                    mem.free()
                del resource.cuda_outputs
            print(cuda.mem_get_info())
            
            del resource.context
            print(cuda.mem_get_info())
            
            del resource.host_inputs
            print(cuda.mem_get_info())
            
            del resource.host_outputs
            print(cuda.mem_get_info())
```
and results:
```
(7954628608, 11546329088)
(7954628608, 11546329088)
(7954628608, 11546329088)
(7954628608, 11546329088)
(7954628608, 11546329088)
```

**Comment by ttyio** [comment]
@HoangTienDuc , have you run this code in multiple thread and see memory leak?

**Comment by HoangTienDuc** [comment]
@ttyio  here they are
t=1 (num thread) (free, total)
```
(8014462976, 11546329088)
(8014462976, 11546329088)
(8014462976, 11546329088)
(8014462976, 11546329088)
(8014462976, 11546329088)
(8014462976, 11546329088)
```
t = 2
```
(7928086528, 11546329088)
(7928086528, 11546329088)
(7928086528, 11546329088)
(7928086528, 11546329088)
(7928086528, 11546329088)
(7928086528, 11546329088)
```
t=3
```
(7888240640, 11546329088)
(7888240640, 11546329088)
(7888240640, 11546329088)
(7888240640, 11546329088)
(7888240640, 11546329088)
(7888240640, 11546329088)
```
t = 4
```
(7850491904, 11546329088)
(7850491904, 11546329088)
(7850491904, 11546329088)
(7850491904, 11546329088)
(7850491904, 11546329088)
(7850491904, 11546329088)
```
t=5
```
(7814840320, 11546329088)
(7814840320, 11546329088)
(7814840320, 11546329088)
(7814840320, 11546329088)
(7814840320, 11546329088)
(7814840320, 11546329088)
```

**Comment by ttyio** [comment]
Sorry @HoangTienDuc  it's beyond my knowledge to understand why the `free` and `del` not works.

let's wait expert @pranavm-nvidia to give use some suggestion. Thanks!

**Comment by pranavm-nvidia** [comment]
@HoangTienDuc Are you pushing the right context onto the stack before attempting to free?

Maybe you can try using [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy) instead? That way you wouldn't need multiple CUDA contexts, and the cleanup would be handled for you. You would just need to create a new runner for each thread and share the engine among them. Assuming you have the engine already, basic usage would be:
```python
from polygraphy.backend.common import BytesFromPath
from polygraphy.backend.trt import TrtRunner, EngineFromBytes

build_engine = EngineFromBytes(BytesFromPath("/path/to/engine"))

with build_engine() as engine, TrtRunner(engine) as r0, TrtRunner(engine) as r1:
    t1 = threading.Thread(target=r0.infer, args=({"inp_name": image0}, ))
    t2 = threading.Thread(target=r1.infer, args=({"inp_name": image1}, ))
    t1.start()
    t2.start()
    t2.join()
    t2.join()
```

There's a relevant test case [here](https://github.com/NVIDIA/TensorRT/blob/master/tools/Polygraphy/tests/backend/trt/test_runner.py#L66) and you can find the API docs [here](https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/index.html) if you need them.

**Comment by HoangTienDuc** [comment]
i check and follow your Polygraphy. Does it support threading?
i got [error](https://github.com/HoangTienDuc/github_issues/tree/polygraphy). Could you please take a check.
If use Polygraply, it will take more time to init the engine. it's not as convenient as before

i think, there are no wrong in pushing context to free. Could you take a check bellow?
https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L13
https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L121

**Comment by pranavm-nvidia** [comment]
@HoangTienDuc I see a couple issues:

- First, w/ Polygraphy, you're building the engine [separately in each thread](https://github.com/HoangTienDuc/github_issues/blob/polygraphy/subcrib_message.py#L40). That explains why it's taking longer to initialize. You should probably move the `build_engine()` call to the constructor of `MQTT_Sub`. 

- Secondly, in your original code, you [pop the CUDA context](https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L96) before you [free](https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L110). This will invalidate the allocations, so you need to pop the context _after_ freeing.

**Comment by HoangTienDuc** [comment]
hello @pranavm-nvidia 
![error](https://user-images.githubusercontent.com/53229746/111933729-a29f4e00-8af2-11eb-96ac-9f6a3bef6510.png)
- First, sorry about my carelessness. i did build the engine separately in each thread as you say. i counter above error that i cannot debug. :(
https://github.com/HoangTienDuc/github_issues/blob/polygraphy/subcrib_message.py#L66
- Second. i did free the context before pop(). but the results is still the same.
https://github.com/HoangTienDuc/github_issues/blob/main/enginer.py#L94

**Comment by neso613** [comment]
> i am apologise becouse don't have much time for tensorrt.
> Did you mean, with each thread i need to create each context and engine?
> it willl take too much resource and take long time to init engine.

Hi @HoangTienDuc I am also working on kind of similar issue where I have multiple models and among them one model is TRT. I am using threading but getting error of missing context. `
    input_memory = cuda.mem_alloc(input)
pycuda._driver.LogicError: explicit_context_dependent failed: invalid device context - no currently active context?
`

**Comment by neso613** [comment]
> @HoangTienDuc , thanks for supporting ;)
> 
> And yes, you can make 1 trt engine, and create multiple context to serve multiple request concurrently by assigned different cuda stream.

How can this done?

**Comment by neso613** [comment]
> hello @ttyio
> i create 1 engine from deserialize_cuda_engine in **init**() and create create_new_context() function. each thread, i call create_new_context to get new context. But i still get confused outputs.
> Could you please help me this problem?
> 
> ```
> import ctypes
> import pycuda.autoinit
> import pycuda.driver as cuda
> import tensorrt as trt
> import threading
> 
> class HostDeviceMem:
>     def __init__(self, host_mem, device_mem):
>         self.host = host_mem
>         self.device = device_mem
> 
>     def __str__(self):
>         return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)
> 
>     def __repr__(self):
>         return self.__str__()
> 
> 
> class InferenceBackend:
>     # initialize TensorRT
>     TRT_LOGGER = trt.Logger(trt.Logger.ERROR)
>     trt.init_libnvinfer_plugins(TRT_LOGGER, '')
> 
>     def __init__(self, model, batch_size):
>         self.cuda_ctx = cuda.Device(0).make_context()
>         if self.cuda_ctx:
>             self.cuda_ctx.push()
>         self.model = model
>         self.batch_size = batch_size
>         # load plugin if the model requires one
>         if self.model.PLUGIN_PATH is not None:
>             try:
>                 ctypes.cdll.LoadLibrary(self.model.PLUGIN_PATH)
>             except OSError as err:
>                 raise RuntimeError('Plugin not found') from err
> 
>         # load trt engine or build one if not found
>         if not self.model.ENGINE_PATH.exists():
>             self.engine = self.model.build_engine(InferenceBackend.TRT_LOGGER, self.batch_size)
>         else:
>             runtime = trt.Runtime(InferenceBackend.TRT_LOGGER)
>             with open(self.model.ENGINE_PATH, 'rb') as engine_file:
>                 buf = engine_file.read()
>                 self.engine = runtime.deserialize_cuda_engine(buf)
>         if self.engine is None:
>             raise RuntimeError('Unable to load the engine file')
>         if self.engine.has_implicit_batch_dimension:
>             assert self.batch_size <= self.engine.max_batch_size
> 
>         if self.cuda_ctx:
>         	self.cuda_ctx.pop()
> 
>     def create_new_context(self):
>         if self.cuda_ctx:
>             self.cuda_ctx.push()
>         # allocate buffers
>         self.bindings = []
>         self.outputs = []
>         for binding in self.engine:
>             shape = self.engine.get_binding_shape(binding)
>             size = trt.volume(shape)
>             if self.engine.has_implicit_batch_dimension:
>                 size *= self.batch_size
>             dtype = trt.nptype(self.engine.get_binding_dtype(binding))
>             # allocate host and device buffers
>             host_mem = cuda.pagelocked_empty(size, dtype)
>             device_mem = cuda.mem_alloc(host_mem.nbytes)
>             # append the device buffer to device bindings
>             self.bindings.append(int(device_mem))
>             if self.engine.binding_is_input(binding):
>                 if not self.engine.has_implicit_batch_dimension:
>                     assert self.batch_size == shape[0]
>                 self.input = HostDeviceMem(host_mem, device_mem)
>             else:
>                 self.outputs.append(HostDeviceMem(host_mem, device_mem))
>         self.context = self.engine.create_execution_context()
>         self.stream = cuda.Stream()
>         if self.cuda_ctx:
>         	self.cuda_ctx.pop()
>         
>     def infer(self):
>         self.infer_async()
>         return self.synchronize()
> 
>     def infer_async(self):
>         if self.cuda_ctx:
>             self.cuda_ctx.push()
>         cuda.memcpy_htod_async(self.input.device, self.input.host, self.stream)
>         if self.engine.has_implicit_batch_dimension:
>             self.context.execute_async(batch_size=self.batch_size, bindings=self.bindings,
>                                        stream_handle=self.stream.handle)
>         else:
>             self.context.execute_async_v2(bindings=self.bindings, stream_handle=self.stream.handle)
>         for out in self.outputs:
>             cuda.memcpy_dtoh_async(out.host, out.device, self.stream)
>         if self.cuda_ctx:
>             self.cuda_ctx.pop()
> 
>     def synchronize(self):
>         if self.cuda_ctx:
>         	self.cuda_ctx.push()
>         self.stream.synchronize()
>         if self.cuda_ctx:
>         	self.cuda_ctx.pop()
>         return [out.host for out in self.outputs]
> ```
I have tried this for my model and inference but this error comes - 
` File "/usr/local/lib/python3.8/dist-packages/pycuda/autoinit.py", line 9, in <module>
    context = make_default_context()
  File "/usr/local/lib/python3.8/dist-packages/pycuda/tools.py", line 204, in make_default_context
    raise RuntimeError("make_default_context() wasn't able to create a context "
RuntimeError: make_default_context() wasn't able to create a context on any of the 1 detected devices

`
Suggestion Please!

**Comment by nvpohanh** [comment]
@neso613 That error looks like some driver issue. Is it still an issue now?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
