### ISSUE TITLE
FP16 out of range (-65504~65504).

### ISSUE THREAD

**Issue by DonggeunYu** [NVIDIA/TensorRT#1122]
@ttyio 
There is 65535 out of -65504~65504 value in the middle of TensorRT graph operation.
So it diverges and the inf value is output.
Is there a good workaround?

**Comment by ttyio** [comment]
Hello @DonggeunYu , could you add batchnorm if this is CNN based network? maybe we can follow resnet. 
Also could you try normalize your input? thanks!
