### ISSUE TITLE
Failed to generate the TensorRT-OSS build container Step 9/30  useradd: UID 0 is not unique

### ISSUE THREAD

**Issue by jzhang82119** [NVIDIA/TensorRT#1123]
## Description

I am on this step to build container.
Generate the TensorRT-OSS build container.
The TensorRT-OSS build container can be generated using the Dockerfiles and build script included with TensorRT-OSS. The build container is bundled with packages and environment required for building TensorRT OSS.

Example: Ubuntu 18.04 on x86-64 with cuda-11.1

./docker/build.sh --file docker/ubuntu-18.04.Dockerfile --tag tensorrt-ubuntu-1804 --cuda 11.1

I got the following error.
Step 9/30 : RUN groupadd -r -f -g ${gid} trtuser && useradd -r -u ${uid} -g ${gid} -ms /bin/bash trtuser
 ---> Running in 413f455cdfdb
useradd: UID 0 is not unique
The command '/bin/bash -c groupadd -r -f -g ${gid} trtuser && useradd -r -u ${uid} -g ${gid} -ms /bin/bash trtuser' returned a non-zero code: 4

## Environment

**TensorRT Version**: TensorRT-7.2.3.4
**NVIDIA GPU**:  A100
**NVIDIA Driver Version**: 450.102.04 
**CUDA Version**: 11.1  (11.0 from nvidia-smi output, 11.1 in /usr/local/ folder)
**Operating System**: ubuntu 18.04
**Baremetal or Container (if so, version)**:  baremetal

**Comment by jzhang82119** [comment]
can you add -o to useradd command in the dockerfile ?

**Comment by ttyio** [comment]
Hello @jzhang82119 , are you running the script under `root` account? could you use other account to run? thanks!

**Comment by jzhang82119** [comment]
I am using root account. So the command is supposed to work with non-root account?

**Comment by ttyio** [comment]
@jzhang82119 ,
Yes, because the user in the container would share the same access privilege as the user who launch the container, we cannot do this for `root` account because the uid is `0` for `root`.
could you take a try with non-root? thanks

**Comment by themozel** [comment]
I have the same problem while building the docker image on my Xavier.
I have jetpack 4.4, cuda 10.2 and TensorRT 7.1.3.0 and I do not use docker as root but the user is in the sudoers. I get the following error:

Step 7/31 : RUN groupadd -r -f -g ${gid} trtuser && useradd -r -u ${uid} -g ${gid} -ms /bin/bash trtuser
 ---> Running in e1784496fb2b
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c groupadd -r -f -g ${gid} trtuser && useradd -r -u ${uid} -g ${gid} -ms /bin/bash trtuser' returned a non-zero code: 1

**Comment by ttyio** [comment]
hello @themozel , the cross compile docker need also run on x86 Linux machine, instead of Xavier devices.

**Comment by themozel** [comment]
Hi @ttyio ! Thank you for the fast response.
so it can not be built on Jetson devices at all ? should I build the image on a x86 linux machine and then run it on Xavier ?

**Comment by ttyio** [comment]
Yes @themozel
