### ISSUE TITLE
Couldn't find any classes after TensorRT conversion

### ISSUE THREAD

**Issue by sinuku** [NVIDIA/TensorRT#1125]
## Description

Hi,
I created pth file after training image segmentation(using yolact edge) and converted to trt.
In pth files, objects are detected in images of any size.
but in trt files, objects are not detected only in small sized images.

Is there a minimum image size for optimal conversion in TensorRT?

Test image size is 550x550 and 100x100, grayscale images, and I used FP16.

## Environment

**TensorRT Version**: 7.1.3.4
**NVIDIA GPU**: gtx1060
**NVIDIA Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 8.1.1
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.6.0
**Baremetal or Container (if so, version)**: 

## Relevant Files

https://github.com/haotian-liu/yolact_edge

**Comment by ttyio** [comment]
Hello @sinuku , just checked the code, this repo used TRTorch. It is a separate project not owned by TRT.  

Could you create issue first in https://github.com/haotian-liu/yolact_edge, if confirmed it is TRTorch issue, you can create issue in https://github.com/NVIDIA/TRTorch.

Thanks!
