### ISSUE TITLE
caffe parser for pooling layer

### ISSUE THREAD

**Issue by SunNy820828449** [NVIDIA/TensorRT#113]
Caffe
PoolingParameter{
 enum RoundMode {
    CEIL = 0;
    FLOOR = 1;
  }
  optional RoundMode round_mode = 13 [default = CEIL];
}
Tensorrt
PoolingParameter{
optional bool torch_pooling = 40 [default = false];
}

**Comment by rmccorm4** [comment]
Hi @SunNy820828449,

Do you have a specific question? I'm not sure what this post is asking.
