### ISSUE TITLE
TensorRT inference benchmark FileNotFoundError bert_large_fp32_bs128_seqlen384_benchmark.engine

### ISSUE THREAD

**Issue by jzhang82119** [NVIDIA/TensorRT#1130]
## Description
I am doing the following in the built container.
cd TensorRT/demo/BERT
scripts/inference_benchmark.sh --gpu Ampere 
Inference seems to run fine for a long time. It errors out anyway after all, I tried a few times, it seems to be persistent.

I only paste the portion near the error. Please advise.
................
==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Running benchmark: perf.py -b 4 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs4_seqlen384_benchmark.engine -w 100 -i 2000
Running 2000 iterations with Batch Size: 4
	Total Time: 72696.13787460327 ms 	Average Time: 36.34806893730163 ms	95th Percentile Time: 36.357120513916016 ms	99th Percentile Time: 36.362239837646484

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Running benchmark: perf.py -b 8 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs8_seqlen384_benchmark.engine -w 100 -i 2000
Running 2000 iterations with Batch Size: 8
	Total Time: 139804.8995513916 ms 	Average Time: 69.9024497756958 ms	95th Percentile Time: 69.9135971069336 ms	99th Percentile Time: 69.91974639892578

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Running benchmark: perf.py -b 12 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs12_seqlen384_benchmark.engine -w 100 -i 2000
Running 2000 iterations with Batch Size: 12
	Total Time: 203925.36875915527 ms 	Average Time: 101.96268437957764 ms	95th Percentile Time: 102.42047882080078 ms	99th Percentile Time: 102.44300842285156

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Running benchmark: perf.py -b 16 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs16_seqlen384_benchmark.engine -w 100 -i 2000
Running 2000 iterations with Batch Size: 16
	Total Time: 276058.8853302002 ms 	Average Time: 138.0294426651001 ms	95th Percentile Time: 138.69261169433594 ms	99th Percentile Time: 138.78579711914062

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Running benchmark: perf.py -b 24 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs24_seqlen384_benchmark.engine -w 100 -i 2000
Running 2000 iterations with Batch Size: 24
	Total Time: 400101.9320983887 ms 	Average Time: 200.05096604919433 ms	95th Percentile Time: 200.09881591796875 ms	99th Percentile Time: 200.74598693847656

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Running benchmark: perf.py -b 32 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs32_seqlen384_benchmark.engine -w 100 -i 2000
Running 2000 iterations with Batch Size: 32
	Total Time: 537569.6203613281 ms 	Average Time: 268.78481018066407 ms	95th Percentile Time: 269.44818115234375 ms	99th Percentile Time: 269.7830505371094

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Building engine: python3 builder.py -m /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1/model.ckpt -o /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs64_seqlen384_benchmark.engine -b 64 -s 384 -c /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1 -v /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1/vocab.txt --fp32
2021-03-17 03:22:21.706601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[TensorRT] INFO: Using configuration file: /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1/bert_config.json
[TensorRT] INFO: Found 394 entries in weight map
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 3 inputs and 1 output network tensors.
[TensorRT] ERROR: Internal error: plugin node (Unnamed Layer* 2) [PluginV2DynamicExt]requires 1207959552 bytes of scratch space, but only 1048576000 is available. Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1176) - OutOfMemory Error in checkPluginScratchSize: 0
[TensorRT] INFO: build engine in 34.327 Sec
Traceback (most recent call last):
  File "builder.py", line 707, in <module>
    main()
  File "builder.py", line 698, in main
    with build_engine(args.batch_size, args.workspace_size, args.sequence_length, config, weights_dict, args.squad_json, args.vocab_file, calib_cache, args.calib_num) as engine:
AttributeError: __enter__
Running benchmark: perf.py -b 64 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs64_seqlen384_benchmark.engine -w 100 -i 2000
Traceback (most recent call last):
  File "perf.py", line 133, in <module>
    main()
  File "perf.py", line 53, in main
    with open(args.engine, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime, runtime.deserialize_cuda_engine(f.read()) as engine, engine.create_execution_context() as context:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs64_seqlen384_benchmark.engine'

==== Benchmarking BERT large fp32 SEQLEN 384 on Ampere ====
Building engine: python3 builder.py -m /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1/model.ckpt -o /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs128_seqlen384_benchmark.engine -b 128 -s 384 -c /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1 -v /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1/vocab.txt --fp32
2021-03-17 03:23:12.059237: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[TensorRT] INFO: Using configuration file: /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_ckpt_large_qa_squad2_amp_384_v19.03.1/bert_config.json
[TensorRT] INFO: Found 394 entries in weight map
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 3 inputs and 1 output network tensors.
[TensorRT] ERROR: Internal error: plugin node (Unnamed Layer* 2) [PluginV2DynamicExt]requires 2415919104 bytes of scratch space, but only 1048576000 is available. Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1176) - OutOfMemory Error in checkPluginScratchSize: 0
[TensorRT] INFO: build engine in 53.125 Sec
Traceback (most recent call last):
  File "builder.py", line 707, in <module>
    main()
  File "builder.py", line 698, in main
    with build_engine(args.batch_size, args.workspace_size, args.sequence_length, config, weights_dict, args.squad_json, args.vocab_file, calib_cache, args.calib_num) as engine:
AttributeError: __enter__
Running benchmark: perf.py -b 128 -s 384 -e /workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs128_seqlen384_benchmark.engine -w 100 -i 2000
Traceback (most recent call last):
  File "perf.py", line 133, in <module>
    main()
  File "perf.py", line 53, in main
    with open(args.engine, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime, runtime.deserialize_cuda_engine(f.read()) as engine, engine.create_execution_context() as context:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/TensorRT/demo/BERT/engines/bert_large_fp32_bs128_seqlen384_benchmark.engine'

## Environment

**TensorRT Version**: TensorRT-7.2.3.4
**NVIDIA GPU**: A100 80G
**NVIDIA Driver Version**: 450.102.04
**CUDA Version**: 11.1
**CUDNN Version**: libcudnn8_8.1.1.33
**Operating System**:  ubuntu 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by jzhang82119** [comment]
ls /TensorRT/demo/BERT/engines

bert_base_fp16_bs128_seqlen128_benchmark.engine   bert_large_fp16_bs2_seqlen128_benchmark.engine
bert_base_fp16_bs128_seqlen384_benchmark.engine   bert_large_fp16_bs2_seqlen384_benchmark.engine
bert_base_fp16_bs12_seqlen128_benchmark.engine    bert_large_fp16_bs32_seqlen128_benchmark.engine
bert_base_fp16_bs12_seqlen384_benchmark.engine    bert_large_fp16_bs32_seqlen384_benchmark.engine
bert_base_fp16_bs16_seqlen128_benchmark.engine    bert_large_fp16_bs4_seqlen128_benchmark.engine
bert_base_fp16_bs16_seqlen384_benchmark.engine    bert_large_fp16_bs4_seqlen384_benchmark.engine
bert_base_fp16_bs1_seqlen128_benchmark.engine     bert_large_fp16_bs64_seqlen128_benchmark.engine
bert_base_fp16_bs1_seqlen384_benchmark.engine     bert_large_fp16_bs64_seqlen384_benchmark.engine
bert_base_fp16_bs24_seqlen128_benchmark.engine    bert_large_fp16_bs8_seqlen128_benchmark.engine
bert_base_fp16_bs24_seqlen384_benchmark.engine    bert_large_fp16_bs8_seqlen384_benchmark.engine
bert_base_fp16_bs2_seqlen128_benchmark.engine     bert_large_fp32_bs128_seqlen128_benchmark.engine
bert_base_fp16_bs2_seqlen384_benchmark.engine     bert_large_fp32_bs12_seqlen128_benchmark.engine
bert_base_fp16_bs32_seqlen128_benchmark.engine    bert_large_fp32_bs12_seqlen384_benchmark.engine
bert_base_fp16_bs32_seqlen384_benchmark.engine    bert_large_fp32_bs16_seqlen128_benchmark.engine
bert_base_fp16_bs4_seqlen128_benchmark.engine     bert_large_fp32_bs16_seqlen384_benchmark.engine
bert_base_fp16_bs4_seqlen384_benchmark.engine     bert_large_fp32_bs1_seqlen128_benchmark.engine
bert_base_fp16_bs64_seqlen128_benchmark.engine    bert_large_fp32_bs1_seqlen384_benchmark.engine
bert_base_fp16_bs64_seqlen384_benchmark.engine    bert_large_fp32_bs24_seqlen128_benchmark.engine
bert_base_fp16_bs8_seqlen128_benchmark.engine     bert_large_fp32_bs24_seqlen384_benchmark.engine
bert_base_fp16_bs8_seqlen384_benchmark.engine     bert_large_fp32_bs2_seqlen128_benchmark.engine
bert_base_fp32_bs128_seqlen128_benchmark.engine   bert_large_fp32_bs2_seqlen384_benchmark.engine
bert_base_fp32_bs12_seqlen128_benchmark.engine    bert_large_fp32_bs32_seqlen128_benchmark.engine
bert_base_fp32_bs12_seqlen384_benchmark.engine    bert_large_fp32_bs32_seqlen384_benchmark.engine
bert_base_fp32_bs16_seqlen128_benchmark.engine    bert_large_fp32_bs4_seqlen128_benchmark.engine
bert_base_fp32_bs16_seqlen384_benchmark.engine    bert_large_fp32_bs4_seqlen384_benchmark.engine
bert_base_fp32_bs1_seqlen128_benchmark.engine     bert_large_fp32_bs64_seqlen128_benchmark.engine
bert_base_fp32_bs1_seqlen384_benchmark.engine     bert_large_fp32_bs8_seqlen128_benchmark.engine
bert_base_fp32_bs24_seqlen128_benchmark.engine    bert_large_fp32_bs8_seqlen384_benchmark.engine
bert_base_fp32_bs24_seqlen384_benchmark.engine    bert_large_int8_bs128_seqlen128_benchmark.engine
bert_base_fp32_bs2_seqlen128_benchmark.engine     bert_large_int8_bs128_seqlen384_benchmark.engine
bert_base_fp32_bs2_seqlen384_benchmark.engine     bert_large_int8_bs12_seqlen128_benchmark.engine
bert_base_fp32_bs32_seqlen128_benchmark.engine    bert_large_int8_bs12_seqlen384_benchmark.engine
bert_base_fp32_bs32_seqlen384_benchmark.engine    bert_large_int8_bs16_seqlen128_benchmark.engine
bert_base_fp32_bs4_seqlen128_benchmark.engine     bert_large_int8_bs16_seqlen384_benchmark.engine
bert_base_fp32_bs4_seqlen384_benchmark.engine     bert_large_int8_bs1_seqlen128_benchmark.engine
bert_base_fp32_bs64_seqlen128_benchmark.engine    bert_large_int8_bs1_seqlen384_benchmark.engine
bert_base_fp32_bs64_seqlen384_benchmark.engine    bert_large_int8_bs24_seqlen128_benchmark.engine
bert_base_fp32_bs8_seqlen128_benchmark.engine     bert_large_int8_bs24_seqlen384_benchmark.engine
bert_base_fp32_bs8_seqlen384_benchmark.engine     bert_large_int8_bs2_seqlen128_benchmark.engine
bert_base_int8_bs128_seqlen128_benchmark.engine   bert_large_int8_bs2_seqlen384_benchmark.engine
bert_base_int8_bs128_seqlen384_benchmark.engine   bert_large_int8_bs32_seqlen128_benchmark.engine
bert_base_int8_bs12_seqlen128_benchmark.engine    bert_large_int8_bs32_seqlen384_benchmark.engine
bert_base_int8_bs12_seqlen384_benchmark.engine    bert_large_int8_bs4_seqlen128_benchmark.engine
bert_base_int8_bs16_seqlen128_benchmark.engine    bert_large_int8_bs4_seqlen384_benchmark.engine
bert_base_int8_bs16_seqlen384_benchmark.engine    bert_large_int8_bs64_seqlen128_benchmark.engine
bert_base_int8_bs1_seqlen128_benchmark.engine     bert_large_int8_bs64_seqlen384_benchmark.engine
bert_base_int8_bs1_seqlen384_benchmark.engine     bert_large_int8_bs8_seqlen128_benchmark.engine
bert_base_int8_bs24_seqlen128_benchmark.engine    bert_large_int8_bs8_seqlen384_benchmark.engine
bert_base_int8_bs24_seqlen384_benchmark.engine    bert_large_int8-qat_bs128_seqlen128_benchmark.engine
bert_base_int8_bs2_seqlen128_benchmark.engine     bert_large_int8-qat_bs128_seqlen384_benchmark.engine
bert_base_int8_bs2_seqlen384_benchmark.engine     bert_large_int8-qat_bs12_seqlen128_benchmark.engine
bert_base_int8_bs32_seqlen128_benchmark.engine    bert_large_int8-qat_bs12_seqlen384_benchmark.engine
bert_base_int8_bs32_seqlen384_benchmark.engine    bert_large_int8-qat_bs16_seqlen128_benchmark.engine
bert_base_int8_bs4_seqlen128_benchmark.engine     bert_large_int8-qat_bs16_seqlen384_benchmark.engine
bert_base_int8_bs4_seqlen384_benchmark.engine     bert_large_int8-qat_bs1_seqlen128_benchmark.engine
bert_base_int8_bs64_seqlen128_benchmark.engine    bert_large_int8-qat_bs1_seqlen384_benchmark.engine
bert_base_int8_bs64_seqlen384_benchmark.engine    bert_large_int8-qat_bs24_seqlen128_benchmark.engine
bert_base_int8_bs8_seqlen128_benchmark.engine     bert_large_int8-qat_bs24_seqlen384_benchmark.engine
bert_base_int8_bs8_seqlen384_benchmark.engine     bert_large_int8-qat_bs2_seqlen128_benchmark.engine
bert_large_fp16_bs128_seqlen128_benchmark.engine  bert_large_int8-qat_bs2_seqlen384_benchmark.engine
bert_large_fp16_bs128_seqlen384_benchmark.engine  bert_large_int8-qat_bs32_seqlen128_benchmark.engine
bert_large_fp16_bs12_seqlen128_benchmark.engine   bert_large_int8-qat_bs32_seqlen384_benchmark.engine
bert_large_fp16_bs12_seqlen384_benchmark.engine   bert_large_int8-qat_bs4_seqlen128_benchmark.engine
bert_large_fp16_bs16_seqlen128_benchmark.engine   bert_large_int8-qat_bs4_seqlen384_benchmark.engine
bert_large_fp16_bs16_seqlen384_benchmark.engine   bert_large_int8-qat_bs64_seqlen128_benchmark.engine
bert_large_fp16_bs1_seqlen128_benchmark.engine    bert_large_int8-qat_bs64_seqlen384_benchmark.engine
bert_large_fp16_bs1_seqlen384_benchmark.engine    bert_large_int8-qat_bs8_seqlen128_benchmark.engine
bert_large_fp16_bs24_seqlen128_benchmark.engine   bert_large_int8-qat_bs8_seqlen384_benchmark.engine
bert_large_fp16_bs24_seqlen384_benchmark.engine

**Comment by ttyio** [comment]
Hello @jzhang82119 

    [TensorRT] ERROR: Internal error: plugin node (Unnamed Layer* 2) [PluginV2DynamicExt]requires 2415919104 bytes of scratch space, but only 1048576000 is available. Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
    [TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1176) - OutOfMemory Error in checkPluginScratchSize: 0

seems we run out of memory for some large batch FP32 runs, could you try on a larger GPU or skip these large test? thanks.
