### ISSUE TITLE
model.py missing from samples/python/uff_custom_plugin

### ISSUE THREAD

**Issue by bw77** [NVIDIA/TensorRT#1136]
Step 3 of the "Adding A Custom Layer To Your TensorFlow Network In TensorRT In Python" sample states to run "python model.py" to generate and save the "trained_lenet5.uff" file. But there is not "model.py" file in the "samples/python/uff_custom_plugin" dir.

**Comment by kevinch-nv** [comment]
@bw77 script has been added - please try out the sample again.
