### ISSUE TITLE
Different output between Python runtime and C++ Runtime 

### ISSUE THREAD

**Issue by thomasryck** [NVIDIA/TensorRT#1137]
## Description

Different output between Python runtime and C++ Runtime 

## Environment

**TensorRT Version**:  7.1.3
**NVIDIA GPU**:  Xavier AGX
**CUDA Version**:  10.2
**CUDNN Version**:  8.0
**Python Version (if applicable)**:  3.6.9
**Jetpack**: 4.5
**L4T**: 32.5.1

I am running a segmentation model based on UNet converted from Pytorch to ONNX to TensorRT.

The TensorRT engine gives me the right result when running with Python3.6  TensorRT engine but when I try to run the engine in C++ I get a completely different output.

Since there is a preprocessing pipeline I was thinking that the problem came from my conversion of python code to C++.

So I checked input values and notice no difference.
eg: Python 0.19393784 C++ 0.19393784

So when I compare between model output I get such result (comparing the data paste from GPU):
Python: 0.9983032 C++: 0.010558193
And I have this kind of result for the whole mask.

I even try different output casting but I never got close to the Python values.

Could you give some hint to debug it ?

**Comment by pranavm-nvidia** [comment]
What does your Python/C++ inference code look like? And which one has correct outputs?

**Comment by thomasryck** [comment]
Stupid mistake from me. When copying the c++ inference code I noticed that I used wrong type for CUDA malloc resulting in wrong output size.
