### ISSUE TITLE
use fp16 but the result of inference is 0/nan

### ISSUE THREAD

**Issue by zhaohb** [NVIDIA/TensorRT#1143]
## Description

Four custom plugins were implemented, and all supported only FP32. then I quantified the model with FP16, but the inference result was 0

## Environment
TensorRT Version: 7.2.2.1
NVIDIA GPU: T4
NVIDIA Driver Version: 450.51.06
CUDA Version: 11.1
CUDNN Version:
Operating System:
Python Version (if applicable): 3.8
Tensorflow Version (if applicable):
PyTorch Version (if applicable):
Baremetal or Container (if so, version): Container 20.12

I would like to know if additional configuration is required or if all four Plugins need support for FP16 to work properly.

**Comment by zhaohb** [comment]
had fixed, close.

**Comment by EvelynZhou** [comment]
how to fix it?
