### ISSUE TITLE
Add onnx opset 10 ops

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#115]
More and more people using onnx-tensorrt convert onnx model to trt engine, but there are some tiny operators does not supported by TensorRT, such as:

```
Not
Equal
And
Scatter
Less
```

etc. 

Does there any plan to adding these operators in? I think it's not difficult to support them.......

(Since many onnx official model using there ops such as SSD FasterRCNN, MaskRCNN etc).

**Comment by jinfagang** [comment]
@rmccorm4 thanks, we are working on that

**Comment by rmccorm4** [comment]
Hi @jinfagang,

TensorRT 7 should be released within the next few days with added RNN support and expanded ONNX op support. Check out https://developer.nvidia.com/tensorrt for more info, there's a TRT7 description at the bottom of the page.

Hopefully this will solve your issues! If not, please open a new issue, thanks!

**Comment by Qjizhi** [comment]
嗨jintian，

请问scatter操作现在有解决办法了么？
