### ISSUE TITLE
Getting junk values in python , but getting proper output when using CPP

### ISSUE THREAD

**Issue by poornimajd** [NVIDIA/TensorRT#1150]
## Description

I have converted a pytorch segmentation model to tensorrt.But when I try to infer from this model using the python tensorrt API I get junk valuesfrom the model ,on the other hand when I try to infer using the same model with the CPP code,I get the correct results.I have also made sure that I do the same preprocessing to the input images in both the python and CPP scripts. 

## Environment

**TensorRT Version**: 7.1.3
**NVIDIA GPU**: 1060 ti 
**NVIDIA Driver Version**: 
**CUDA Version**:  10.2
**CUDNN Version**: 7.6.5
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: 1.7.1
**Baremetal or Container (if so, version)**: N/A

## Steps To Reproduce

Python code used to infer-

   ```
host_input=to_numpy(img[0])#img is the preprocessed image
 cuda.memcpy_htod_async(device_input, host_input, stream)

    context.execute_async_v2(bindings=[int(device_input), int(device_output)], stream_handle=stream.handle)
    
    cuda.memcpy_dtoh_async(host_output, device_output, stream)
    output_data = torch.Tensor(host_output).reshape(1,1024,1024)

    stream.synchronize()

```
Cpp code

```
//data is the preprocessed image,just the same like the one in python
vector<int> infer_with_engine(TrtSharedEnginePtr engine, vector<float>& data) {
    Dims3 out_dims = static_cast<Dims3&&>(
        engine->getBindingDimensions(engine->getBindingIndex("preds")));

    const int batchsize{1}, H{out_dims.d[1]}, W{out_dims.d[2]};
    const int in_size{static_cast<int>(data.size())};
    const int out_size{batchsize * H * W};
    vector<void*> buffs(2);
    vector<int> res(out_size);

    auto context = TrtUniquePtr<IExecutionContext>(engine->createExecutionContext());
    if (!context) {
        cout << "create execution context failed\n";
        std::abort();
    }

    cudaError_t state;
    state = cudaMalloc(&buffs[0], in_size * sizeof(float));
    if (state) {
        cout << "allocate memory failed\n";
        std::abort();
    }
    state = cudaMalloc(&buffs[1], out_size * sizeof(int));
    if (state) {
        cout << "allocate memory failed\n";
        std::abort();
    }
    cudaStream_t stream;
    state = cudaStreamCreate(&stream);
    if (state) {
        cout << "create stream failed\n";
        std::abort();
    }

    state = cudaMemcpyAsync(
            buffs[0], &data[0], in_size * sizeof(float),
            cudaMemcpyHostToDevice, stream);
    if (state) {
        cout << "transmit to device failed\n";
        std::abort();
    }
    context->enqueueV2(&buffs[0], stream, nullptr);
    // context->enqueue(1, &buffs[0], stream, nullptr);
    state = cudaMemcpyAsync(
            &res[0], buffs[1], out_size * sizeof(int), 
            cudaMemcpyDeviceToHost, stream);
    if (state) {
        cout << "transmit to host failed \n";
        std::abort();
    }
    cudaStreamSynchronize(stream);

    cudaFree(buffs[0]);
    cudaFree(buffs[1]);
    cudaStreamDestroy(stream);

    return res;
}
```
Any suggestion would be really appreciated.Stuck in this for quite a while.
Thank you

**Comment by poornimajd** [comment]
@ttyio please help.It would be really helpful if I could get through this ASAP. Thank you

**Comment by pranavm-nvidia** [comment]
Can you double check that the `dtype`s are right in your NumPy/PyCUDA arrays?

**Comment by poornimajd** [comment]
Thanks for the reply!
Yes, I checked it is float32.

**Comment by pranavm-nvidia** [comment]
Ah ok, I think maybe this is the culprit:
```python
cuda.memcpy_dtoh_async(host_output, device_output, stream)
output_data = torch.Tensor(host_output).reshape(1,1024,1024)

stream.synchronize()
```

Should be:
```
cuda.memcpy_dtoh_async(host_output, device_output, stream)
stream.synchronize()

output_data = torch.Tensor(host_output).reshape(1,1024,1024)
```
because `host_output` wouldn't be valid until the copy has finished. 

And a side note: if you're using torch, you could write the output directly into a torch device tensor rather than copying back to host. Same on the input side too - you can read from a torch device tensor.

**Comment by poornimajd** [comment]
Thanks for the reply. I had tried this change earlier but it made no difference.I still get the junk values.


> And a side note: if you're using torch, you could write the output directly into a torch device tensor rather than copying back to host. Same on the input side too - you can read from a torch device tensor.

Thank you for the suggestion.

**Comment by pranavm-nvidia** [comment]
Not really sure what it could be in that case. The Python APIs just call the corresponding C++ APIs, so there shouldn't be any differences between the two. Maybe you can try checking the raw bytes of the input/output values just before/after inference?

**Comment by poornimajd** [comment]
Yeah sure I will check it out.Thanks for the suggestion.

**Comment by poornimajd** [comment]
When I tried with https://github.com/NVIDIA-AI-IOT/torch2trt python inference script, I got the same output as cpp. Not really sure as to what might be the exact issue,will update once found.
Thank you for the help!!
