### ISSUE TITLE
Is Streaming only applied to Triton server?

### ISSUE THREAD

**Issue by RizhaoCai** [NVIDIA/TensorRT#1152]
When I read the [documentation](https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html#streaming) to seek for optimization tips, I saw that Steaming is one of the ways. However, I am confused a bit. 

![image](https://user-images.githubusercontent.com/37952703/112566528-20789780-8e1a-11eb-9427-815f4bbb82d6.png)

As mentioned, 

> With the help of streaming, the Triton Inference Server helps to manage multiple execution instances of a model.

Questions
1) Does it mean "Streaming" is only applied to the Triton server?

2) As below, in Python TensorRT API, there is "execute_async". Does it only work for the Triton server?
![image](https://user-images.githubusercontent.com/37952703/112566909-cc21e780-8e1a-11eb-826a-12f35bbd3ea0.png)

3) Does one GPU only have a stream?

4) If I am doing development on TX2 and Xavier, I can't apply Streaming?

Thanks

**Comment by ttyio** [comment]
Hello @RizhaoCai 
1. no
2. no
3. stream is software concept, there is no stream in gpu hardware, it is introduced in cuda programming model, you can think them as multiple command queue that can feed the gpu engine. With mutiple stream, you can execute command from multiple queue without false dependency.
4. stream works in any CUDA devices

**Comment by RizhaoCai** [comment]
> Hello @RizhaoCai
> 
> 1. no
> 2. no
> 3. stream is software concept, there is no stream in gpu hardware, it is introduced in cuda programming model, you can think them as multiple command queue that can feed the gpu engine. With mutiple stream, you can execute command from multiple queue without false dependency.
> 4. stream works in any CUDA devices

Hi ttyio,

Thanks for your comment. 
I am not familiar with CUDA programming. I am wonder that to take advantage of streaming, I need to do some CUDA programming, such as writing C++ code or Cython？

**Comment by ttyio** [comment]
Hello @RizhaoCai , 
You can use triton which already used cuda stream, 

or use c++, there is a SDK sample in https://github.com/zchee/cuda-sample/tree/master/0_Simple/simpleStreams

or for python, we have open sourced python binding in https://github.com/NVIDIA/TensorRT/tree/master/python, there is GIL (global interpreter lock) in python which will hurt performance, and we will fix it in next major release.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
