### ISSUE TITLE
problem about unet in  tensorrt

### ISSUE THREAD

**Issue by 1372072273** [NVIDIA/TensorRT#1159]
this is my unet model  in python 
 self.inc = inconv(n_channels, 64)
        self.down1 = down(64, 128)
        self.down2 = down(128, 256)
        self.down3 = down(256, 512)
        self.down4 = down(512, 512)
        self.up1 = up(1024, 256)
        self.up2 = up(512, 128)
        self.up3 = up(256, 64)
        self.up4 = up(128, 64)
        self.outc = outconv(64, n_classes)

I turned the model to unet.wts and then  turn the .wts file to .engine file with the tensort api,here is the c++ code:
ILayer* up_fs(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input1, ITensor& input2, int resize, int outch, int midch, std::string lname) {
	float *deval = reinterpret_cast<float*>(malloc(sizeof(float) * resize * 2 * 2));
	for (int i = 0; i < resize * 2 * 2; i++) {
		deval[i] = 1.0;
	}
	Weights emptywts{ DataType::kFLOAT, nullptr, 0 };
	Weights deconvwts1{ DataType::kFLOAT, deval, resize * 2 * 2 };
	//upsample
	IDeconvolutionLayer* deconv1 = network->addDeconvolutionNd(input1, resize, DimsHW{ 2, 2 }, deconvwts1, emptywts);
	deconv1->setStrideNd(DimsHW{ 2, 2 });
	deconv1->setNbGroups(resize);
	weightMap["deconvwts." + lname] = deconvwts1;

	int diffx = input2.getDimensions().d[1] - deconv1->getOutput(0)->getDimensions().d[1];
	int diffy = input2.getDimensions().d[2] - deconv1->getOutput(0)->getDimensions().d[2];
......
this is upsample , up_fs(network, weightMap, *x5->getOutput(0), *x4->getOutput(0), 1024, 512, 512, "up1"); its met the error :[E] [TRT] (Unnamed Layer* 34) [Deconvolution]: group count must divide input channel count  in here : int diffx = input2.getDimensions().d[1] - deconv1->getOutput(0)->getDimensions().d[1];

**Comment by ttyio** [comment]
Hello @1372072273 ,
what's the group count in `setNbGroups`? and what is the `C` in the input? thanks!

**Comment by 1372072273** [comment]
> Hello @1372072273 ,
> what's the group count in `setNbGroups`? and what is the `C` in the input?
> 
> Also have you tried export the model to onnx, and import to TRT using onnx parser?
> thanks!

我的tensorrt 复现模型结构是下面这样的，在debug到x9 时报错，在上采样是参数出错，
auto x1 = doubleConv_fs(network, weightMap, *data, 64, 3, "inc", 64);
	auto x2 = down_fs(network, weightMap, *x1->getOutput(0), 128, 1, "down1");
	auto x3 = down_fs(network, weightMap, *x2->getOutput(0), 256, 1, "down2");
	auto x4 = down_fs(network, weightMap, *x3->getOutput(0), 512, 1, "down3");
	auto x5 = down_fs(network, weightMap, *x4->getOutput(0), 512, 1, "down4");
	ILayer* x6 = up_fs(network, weightMap, *x5->getOutput(0), *x4->getOutput(0), 512, 512, 512, "up1");
	ILayer* x7 = up_fs(network, weightMap, *x6->getOutput(0), *x3->getOutput(0), 256, 256, 256, "up2");
	ILayer* x8 = up_fs(network, weightMap, *x7->getOutput(0), *x2->getOutput(0), 128, 128, 128, "up3");
	ILayer* x9 = up_fs(network, weightMap, *x8->getOutput(0), *x1->getOutput(0), 64, 64, 64, "up4");
	ILayer* x10 = outConv(network, weightMap, *x9->getOutput(0), OUTPUT_SIZE, "outc");

这是上采样部分的代码
ILayer* up_fs(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input1, ITensor& input2, int resize, int outch, int midch, std::string lname) {
	float *deval = reinterpret_cast<float*>(malloc(sizeof(float) * resize * 2 * 2));
	for (int i = 0; i < resize * 2 * 2; i++) {
		deval[i] = 1.0;
	}
	Weights emptywts{ DataType::kFLOAT, nullptr, 0 };
	Weights deconvwts1{ DataType::kFLOAT, deval, resize * 2 * 2 };
	//upsample
	IDeconvolutionLayer* deconv1 = network->addDeconvolutionNd(input1, resize, DimsHW{ 2, 2 }, deconvwts1, emptywts);
	deconv1->setStrideNd(DimsHW{ 2, 2 });
	deconv1->setNbGroups(resize);
暂时还没有用onnx的方法去做

**Comment by ttyio** [comment]
Hello @1372072273 ,
the code is different compare to the error message in the original description.

Could you print the `ITensor::getDimensions()` before `network::addDeconvolutionNd()`, also print the param passed in `setNbGroups`? thanks!

**Comment by 1372072273** [comment]
ILayer* up_fs(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input1, ITensor& input2, int resize, int outch, int midch, std::string lname) {
	float *deval = reinterpret_cast<float*>(malloc(sizeof(float) * resize * 2 * 2));
	for (int i = 0; i < resize * 2 * 2; i++) {
		deval[i] = 1.0;
	}
	Weights emptywts{ DataType::kFLOAT, nullptr, 0 };
	Weights deconvwts1{ DataType::kFLOAT, deval, resize * 2 * 2 };
	//upsample
	std::cout << input2.getDimensions().d[1] << std::endl;
	std::cout << input2.getDimensions().d[2] << std::endl;
	IDeconvolutionLayer* deconv1 = network->addDeconvolutionNd(input1, resize, DimsHW{ 2, 2 }, deconvwts1, emptywts);
	deconv1->setStrideNd(DimsHW{ 2, 2 });
	deconv1->setNbGroups(resize);
	weightMap["deconvwts." + lname] = deconvwts1;
	
	int diffx = input2.getDimensions().d[1] - deconv1->getOutput(0)->getDimensions().d[1];
	int diffy = input2.getDimensions().d[2] - deconv1->getOutput(0)->getDimensions().d[2];
	// IPoolingLayer* pool1 = network->addPooling(dcov1, PoolingType::kMAX, DimsHW{2, 2});
	// pool1->setStrideNd(DimsHW{2, 2});
	// dcov1->add_pading
	ILayer* pad1 = network->addPaddingNd(*deconv1->getOutput(0), DimsHW{ diffx / 2, diffy / 2 }, DimsHW{ diffx - (diffx / 2), diffy - (diffy / 2) });
	// dcov1->setPaddingNd(DimsHW{diffx / 2, diffx - diffx / 2},DimsHW{diffy / 2, diffy - diffy / 2});
	ITensor* inputTensors[] = { &input2,pad1->getOutput(0) };
	auto cat = network->addConcatenation(inputTensors, 2);
	assert(cat);
	
	if (midch == 64) {
		ILayer* dcov1 = doubleConv_fs(network, weightMap, *cat->getOutput(0), outch, 3, lname, outch);
		assert(dcov1);
		return dcov1;
	}
	else {
		int midch1 = outch / 2;
		ILayer* dcov1 = doubleConv_fs(network, weightMap, *cat->getOutput(0), midch1, 3, lname, outch);
		assert(dcov1);
		return dcov1;
	}

	/* assert(dcov1);

	 return dcov1;*/
}

I print the  input2.getDimensions().d[1]
	          input2.getDimensions().d[2]  before   network->addDeconvolutionNd(),
the result is 256 256; the deconv1->setNbGroups(resize); resize is 64




> Hello @1372072273 ,
> the code is different compare to the error message in the original description.
> 
> Could you print the `ITensor::getDimensions()` before `network::addDeconvolutionNd()`, also print the param passed in `setNbGroups`? thanks!

ILayer* up_fs(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input1, ITensor& input2, int resize, int outch, int midch, std::string lname) {
	float *deval = reinterpret_cast<float*>(malloc(sizeof(float) * resize * 2 * 2));
	for (int i = 0; i < resize * 2 * 2; i++) {
		deval[i] = 1.0;
	}
	Weights emptywts{ DataType::kFLOAT, nullptr, 0 };
	Weights deconvwts1{ DataType::kFLOAT, deval, resize * 2 * 2 };
	//upsample
	std::cout << input2.getDimensions().d[1] << std::endl;
	std::cout << input2.getDimensions().d[2] << std::endl;
	IDeconvolutionLayer* deconv1 = network->addDeconvolutionNd(input1, resize, DimsHW{ 2, 2 }, deconvwts1, emptywts);
	deconv1->setStrideNd(DimsHW{ 2, 2 });
	deconv1->setNbGroups(resize);
	weightMap["deconvwts." + lname] = deconvwts1;
	
	int diffx = input2.getDimensions().d[1] - deconv1->getOutput(0)->getDimensions().d[1];
	int diffy = input2.getDimensions().d[2] - deconv1->getOutput(0)->getDimensions().d[2];
	// IPoolingLayer* pool1 = network->addPooling(dcov1, PoolingType::kMAX, DimsHW{2, 2});
	// pool1->setStrideNd(DimsHW{2, 2});
	// dcov1->add_pading
	ILayer* pad1 = network->addPaddingNd(*deconv1->getOutput(0), DimsHW{ diffx / 2, diffy / 2 }, DimsHW{ diffx - (diffx / 2), diffy - (diffy / 2) });
	// dcov1->setPaddingNd(DimsHW{diffx / 2, diffx - diffx / 2},DimsHW{diffy / 2, diffy - diffy / 2});
	ITensor* inputTensors[] = { &input2,pad1->getOutput(0) };
	auto cat = network->addConcatenation(inputTensors, 2);
	assert(cat);
	
	if (midch == 64) {
		ILayer* dcov1 = doubleConv_fs(network, weightMap, *cat->getOutput(0), outch, 3, lname, outch);
		assert(dcov1);
		return dcov1;
	}
	else {
		int midch1 = outch / 2;
		ILayer* dcov1 = doubleConv_fs(network, weightMap, *cat->getOutput(0), midch1, 3, lname, outch);
		assert(dcov1);
		return dcov1;
	}

	/* assert(dcov1);

	 return dcov1;*/
}

I print the  input2.getDimensions().d[1]
	          input2.getDimensions().d[2]  before   network->addDeconvolutionNd(),
the result is 256 256; the deconv1->setNbGroups(resize); resize is 64

**Comment by 1372072273** [comment]
> Hello @1372072273 ,
> the code is different compare to the error message in the original description.
> 
> Could you print the `ITensor::getDimensions()` before `network::addDeconvolutionNd()`, also print the param passed in `setNbGroups`? thanks!

![image](https://user-images.githubusercontent.com/44405433/118930897-e4c10080-b978-11eb-9c7b-842552016c0d.png)
thank you for your reply

**Comment by nvpohanh** [comment]
@1372072273 Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
