### ISSUE TITLE
tf2.0 support for bert python demo

### ISSUE THREAD

**Issue by xiaoyunwu** [NVIDIA/TensorRT#116]
As tensorflow 2.0 is the coming to shape, (rc1 just arrived), is it possible to have a version that work with tf2.0?

**Comment by rmccorm4** [comment]
Hi @xiaoyunwu,

We don't have support for TF2.0 in that demo right now, but hopefully in a future release.

Closing for now.

**Comment by xiaoyunwu** [comment]
Now that tensorflow 2.0 is stable and 2.1 is also coming, do we have the plans to support it from tensorrt side?
