### ISSUE TITLE
compatibility mode is UNAVAILABLE

### ISSUE THREAD

**Issue by leqiao-1** [NVIDIA/TensorRT#1160]
## Description
https://github.com/NVIDIA/nvidia-docker/issues/1479#issue-844277559
Trying to run image nvcr.io/nvidia/tensorrt:20.07.1-py3 on ubuntu 18.04 with cuda driver version 440.33.01 and cuda version 10.2 . It shows error 
```
ERROR: This container was built for NVIDIA Driver Release 450.51 or later, but
       version 440.33.01 was detected and compatibility mode is UNAVAILABLE.

       [[CUDA Driver UNAVAILABLE (cuInit(0) returned 804)]]
```
However, driver version (440.33.01) is compatible with CUDA 11.0 so it will work without any issues.
See: https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility

## Environment

**TensorRT Version**:  nvcr.io/nvidia/tensorrt:20.07.1-py3
**NVIDIA GPU**:  440.33.01 
**NVIDIA Driver Version**:  440.33.01 
**CUDA Version**: 10.2
**CUDNN Version**: 
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:20.07.1-py3

## Relevant Files
![image](https://user-images.githubusercontent.com/61653207/112972927-5f447f80-9183-11eb-91da-b1b69708ce1b.png)
![image](https://user-images.githubusercontent.com/61653207/112972946-62d80680-9183-11eb-89f2-a2c76b478e3e.png)

## Steps To Reproduce
install cuda 10.2 with driver version 440.33.01 on machine. 
docker pull nvcr.io/nvidia/tensorrt:20.07.1-py3
docker run -it --rm nvcr.io/nvidia/tensorrt:20.07.1-py3 /bin/bash

**Comment by ttyio** [comment]
Hello @leqiao-1 , the doc link you posted is for `NVIDIA datacenter driver branches`,  it is tesla produces. And from your screenshot you are using geforce production. Could you upgrade the driver version according to the warning message? thanks!

**Comment by leqiao-1** [comment]
Hello @ttyio , I will update driver version later. I'm not sure if you mean that this cuda driver version compability can only be used on tesla GPU and cannot be used on geforce GPU ? Thanks.

**Comment by ttyio** [comment]
Hello @leqiao-1 , yes, this document only highlight `NVIDIA datacenter driver branches`.  and tesla and geforce are from different code branch.

**Comment by leqiao-1** [comment]
@ttyio Thanks for your help. It takes time for me to find related info from this document. 

The CUDA compatible upgrade is meant to ease the management of large production systems for enterprise customers. As such, the supported HW (hardware) for this new upgrade path is limited to NVIDIA Datacenter (Tesla) GPU products.

Thanks again.
