### ISSUE TITLE
yolov3_onnx sample: TensorRT inference time increase

### ISSUE THREAD

**Issue by chengweige** [NVIDIA/TensorRT#1161]
## Description
TensorRT inference time will increase if the post-processing is time consuming

## Environment

**TensorRT Version**: TensorRT-7.1.3.4
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: Driver Version: 450.80.02
**CUDA Version**: CUDA Version: 11.0
**CUDNN Version**: 
**Operating System**:  ubuntu1604
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files
code snipplet:

> 
    with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
        total_time = 0
        exec_times = 100
        for _ in range(exec_times):
            ############################################################################################################
            print('Running inference on image {}...'.format(input_image_path))
            start0 = time.time()
            image_raw, image = preprocessor.process(input_image_path)
            # Store the shape of the original input image in WH format, we will need it for later
            shape_orig_WH = image_raw.size
            # Output shapes expected by the post-processor
            output_shapes = [(1, 255, 19, 19), (1, 255, 38, 38), (1, 255, 76, 76)]
            print("===> preprocessor time(TRT): %.5f(ms)" % ((time.time() - start0) * 1000.0))
            ############################################################################################################
            start1 = time.time()
            # Do inference with TensorRT
            trt_outputs = []
            inputs, outputs, bindings, stream = common.allocate_buffers(engine)
            # Do inference
            # Set host input to the image. The common.do_inference function will copy the input to the GPU before executing.
            inputs[0].host = image
            trt_outputs = common.do_inference_v2(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
            print("===> inference time(TRT): %.5f(ms)" % ((time.time() - start1) * 1000.0))
            ############################################################################################################
            total_time += (time.time() - start0)*1000.0
            print("===> total inference time(TRT): %.5f(ms)" % ((time.time() - start0)*1000.0))
            
            # post for process
            # for i in range(10000000):
            #     pass
        print('average processing time: %.5f(ms)' % (total_time / exec_times))
> 

without ‘post for process’
average processing time: 69.18464(ms)

with ‘post for process’
average processing time: 98.64011(ms)

**Comment by nvpohanh** [comment]
@chengweige Could you show me the content of the post-processing part? What is it doing? Thanks

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
