### ISSUE TITLE
[TensorRT] ERROR: Network has dynamic or shape inputs, but no optimization profile has been defined.

### ISSUE THREAD

**Issue by neso613** [NVIDIA/TensorRT#1167]
## Description
I have a onnx model with [1,100,80] input and [1,30] output shapes. I have converted this to TensorRT engine and its working fine.
Now,When I tried same onnx model with [0,0,80] input and [0,0] output shapes. Here, 0 is for dynamic shape.Then am getting error :
`[TensorRT] ERROR: Network has dynamic or shape inputs, but no optimization profile has been defined.
[TensorRT] ERROR: Network validation failed.
`
code snippet for conversion-
`TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
    builder = trt.Builder(TRT_LOGGER)
    builder.fp16_mode = fp16
    config = builder.create_builder_config()
    config.max_workspace_size = 512*1024*1024
    if fp16:
        config.flags |= 1 << int(trt.BuilderFlag.FP16)
    explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = builder.create_network(explicit_batch)
    with trt.OnnxParser(network, TRT_LOGGER) as parser:
        with open(model_file, 'rb') as model:
            parsed = parser.parse(model.read())
            engine = builder.build_engine(network, config=config)
            return engine`

## Environment

**TensorRT Version**: 7.1.3.0
**Platform**: Nvidia Jetson Xavier NX
**NVIDIA (R) Cuda compiler driver**: 10.2, V10.2.89

**Comment by neso613** [comment]
any comments?

**Comment by neso613** [comment]
@rajeevsrao @mengdong

**Comment by rajeevsrao** [comment]
@neso613 for TensorRT networks with dynamic shapes (containing inputs with 0/unknown dims), you need to specify "optimization profiles" that contain (min, opt, max) range for each input during build and then specify the actual runtime dimension during inference. See here for documentation:
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#opt_profiles

**Comment by neso613** [comment]
> @neso613 for TensorRT networks with dynamic shapes (containing inputs with 0/unknown dims), you need to specify "optimization profiles" that contain (min, opt, max) range for each input during build and then specify the actual runtime dimension during inference. See here for documentation:
> https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes
> https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#opt_profiles

Thanks @rajeevsrao for quick response.
This is a NLP model. So, its min/opt/max value not certain. Also, output is also dynamic.
How do I infer the dynamic model?
We need to alocate buffer but How?
`h_input_1 = cuda.pagelocked_empty(batch_size * trt.volume(engine.get_binding_shape(0)), dtype=trt.nptype(dtype))
    h_output = cuda.pagelocked_empty(batch_size * trt.volume(engine.get_binding_shape(1)), dtype=trt.nptype(dtype))
    d_input_1 = cuda.mem_alloc(h_input_1.nbytes)
    d_output = cuda.mem_alloc(h_output.nbytes)`
This won't work.
