### ISSUE TITLE
Result mismatch between onnxruntime and TensorRT in LSTM layer

### ISSUE THREAD

**Issue by sapjunior** [NVIDIA/TensorRT#1177]
## Description

I'm trying to deploy my model on Triton Inference Server but encounter a result mismatch problem between onnxruntime and TensorRT in LSTM layer.

## Environment

**TensorRT Version**: NGC TensorRT Latest Docker Image (21.03)
**NVIDIA GPU**: 1080Ti
**NVIDIA Driver Version**:  460.32
**CUDA Version**: NGC TensorRT Latest Docker Image (21.03)
**CUDNN Version**: NGC TensorRT Latest Docker Image (21.03)
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.8.1
**Baremetal or Container (if so, version)**: 

## Relevant Files

ONNX Model File: https://drive.google.com/drive/folders/1puyOp86Dz-Zd_n5N8sZzkErvCkpNPDWk?usp=sharing

## Steps To Reproduce

run polygraph inside TensorRT docker image with following command:
`pip install onnx onnxruntime-gpu colored`
`polygraphy run sample.onnx --trt --onnxrt --onnx-outputs mark all --trt-outputs mark all --input-shapes input:[1,1,32,512]`

Here is the output from polygraph command:
https://gist.github.com/sapjunior/09626833746b66326eb802271855b7e5

If I run this command on the original weight file, the error from the output layer will be
 "Required Tolerance: [abs=15.289] OR [rel=1e-05, abs=15.289] OR [rel=1, abs=1e-05] | Mean Error: [abs=2.6891, rel=0.99997]". 

I understand that there will be some floating point error in TensorRT compared to original model but not sure is this error range normal or not? (I cannot give an original weight due to company policy but the overall model structure is the same)

Thank you

**Comment by pranavm-nvidia** [comment]
That error definitely seems way too high. I've filed a bug internally on it. 

In the meantime, the error seems to go away for me if I freeze shapes in the model first:
```bash
polygraphy surgeon sanitize sample.onnx \
    --override-input-shapes input:[1,1,32,512] \
    --fold-constants -o folded.onnx
```

```
[I] Accuracy Comparison | trt-runner-N0-04/09/21-11:13:22 vs. onnxrt-runner-N0-04/09/21-11:13:22
[I]     Comparing Output: 'output' (dtype=float32, shape=(1, 129, 200)) with 'output' (dtype=float32, shape=(1, 129, 200))
[I]         Required Tolerance: [abs=5.4017e-08] OR [rel=1e-05, abs=2.1231e-08] OR [rel=0, abs=1e-05] | Mean Error: [abs=4.8996e-09, rel=0]
            trt-runner-N0-04/09/21-11:13:22     | Stats: mean=-0.00058504, std-dev=0.039764, min=-0.094943 at (0, 128, 114), max=0.10609 at (0, 7, 26)
            onnxrt-runner-N0-04/09/21-11:13:22  | Stats: mean=-0.00058504, std-dev=0.039764, min=-0.094943 at (0, 128, 114), max=0.10609 at (0, 7, 26)
[D]         PASSED | Difference is within tolerance (rel=1e-05, abs=1e-05)
[D]     PASSED | All outputs matched | Outputs: ['output']
[D] PASSED | Command: polygraphy run folded.onnx --trt --onnxrt

**Comment by sapjunior** [comment]
> That error definitely seems way too high. I've filed a bug internally on it.
> 
> In the meantime, the error seems to go away for me if I freeze shapes in the model first:
> 
> ```shell
> polygraphy surgeon sanitize sample.onnx \
>     --override-input-shapes input:[1,1,32,512] \
>     --fold-constants -o folded.onnx
> ```
> 
> ```
> [I] Accuracy Comparison | trt-runner-N0-04/09/21-11:13:22 vs. onnxrt-runner-N0-04/09/21-11:13:22
> [I]     Comparing Output: 'output' (dtype=float32, shape=(1, 129, 200)) with 'output' (dtype=float32, shape=(1, 129, 200))
> [I]         Required Tolerance: [abs=5.4017e-08] OR [rel=1e-05, abs=2.1231e-08] OR [rel=0, abs=1e-05] | Mean Error: [abs=4.8996e-09, rel=0]
>             trt-runner-N0-04/09/21-11:13:22     | Stats: mean=-0.00058504, std-dev=0.039764, min=-0.094943 at (0, 128, 114), max=0.10609 at (0, 7, 26)
>             onnxrt-runner-N0-04/09/21-11:13:22  | Stats: mean=-0.00058504, std-dev=0.039764, min=-0.094943 at (0, 128, 114), max=0.10609 at (0, 7, 26)
> [D]         PASSED | Difference is within tolerance (rel=1e-05, abs=1e-05)
> [D]     PASSED | All outputs matched | Outputs: ['output']
> [D] PASSED | Command: polygraphy run folded.onnx --trt --onnxrt 
> ```

Which version o polygraphy are you using? Current version in latest NGC image does not support --override-input-shapes parameter.

**Comment by pranavm-nvidia** [comment]
Oh you can do something equivalent with `surgeon extract`:
```bash
polygraphy surgeon extract sample.onnx --inputs input:[1,1,32,512]:auto -o folded.onnx

polygraphy surgeon sanitize --fold-constants folded.onnx -o folded.onnx
```

**Comment by sapjunior** [comment]
> Oh you can do something equivalent with `surgeon extract`:
> 
> ```shell
> polygraphy surgeon extract sample.onnx --inputs input:[1,1,32,512]:auto -o folded.onnx
> 
> polygraphy surgeon sanitize --fold-constants folded.onnx -o folded.onnx
> ```

Here is the result after run a sanitize fold-constants command, not sure what happen with my polygraphy :(
`
root@2fb9c7802a3a:/models# polygraphy surgeon sanitize --fold-constants folded.onnx -o folded.onnx
[I] Loading model: /models/folded.onnx
[I] Original Model:
    Name: torch-jit-export | Opset: 12

    ---- 1 Graph Inputs ----
    {input [dtype=float32, shape=(1, 1, 32, 512)]}

    ---- 1 Graph Outputs ----
    {output [dtype=float32, shape=(1, 129, 200)]}

    ---- 80 Initializers ----
    (Use --mode to display)

    ---- 104 Nodes ----
    (Use --mode to display)

[I] Folding Constants | Pass 1
Traceback (most recent call last):
  File "/usr/local/bin/polygraphy", line 58, in <module>
    main()
  File "/usr/local/bin/polygraphy", line 54, in main
    sys.exit(args.subcommand(args))
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/base/tool.py", line 116, in __call__
    return self.run(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/surgeon/subtool/base.py", line 111, in run
    return self.run_impl(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/surgeon/subtool/sanitize.py", line 57, in run_impl
    model = onnx_backend.fold_constants(model, num_passes=args.num_const_fold_passes,
  File "<string>", line 3, in func_impl
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/onnx/loader.py", line 266, in call_impl
    model = gs.export_onnx(gs.import_onnx(model).fold_constants().cleanup().toposort(),
  File "/usr/local/lib/python3.8/dist-packages/onnx_graphsurgeon/ir/graph.py", line 329, in fold_constants
    temp_graph = copy.deepcopy(self)
  File "/usr/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.8/dist-packages/onnx_graphsurgeon/ir/graph.py", line 421, in __deepcopy__
    new_node = node.copy(inputs=[new_tensors[inp.name] for inp in node.inputs], outputs=[new_tensors[out.name] for out in node.outputs])
  File "/usr/local/lib/python3.8/dist-packages/onnx_graphsurgeon/ir/graph.py", line 421, in <listcomp>
    new_node = node.copy(inputs=[new_tensors[inp.name] for inp in node.inputs], outputs=[new_tensors[out.name] for out in node.outputs])
KeyError: ''

`

**Comment by pranavm-nvidia** [comment]
That bug is fixed already in the [repo](https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon). Although I don't think you actually need to do the constant folding part - on my end, just freezing the shapes seems to be enough. Maybe you can try without the `surgeon sanitize` step?

**Comment by sapjunior** [comment]
I already try to use latest onnx-surgeon from the mentioned git and found that
- If I apply freeze-shape + folded-constant, the graph cannot be execute with the following error
`
root@16c1059547df:/models# polygraphy run folded.onnx --trt --onnxrt
[I] trt-runner-N0-04/10/21-06:31:27     | Activating and starting inference
[I] Loading bytes from /models/folded.onnx
[TensorRT] WARNING: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/onnx2trt_utils.cpp:226: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[E] In node 81 (elementwiseHelper): UNSUPPORTED_NODE: Assertion failed: tensor_ptr->getDimensions().nbDims == maxNbDims && "Failed to broadcast tensors elementwise!"
[!] Could not parse ONNX correctly
`

- If I apply only freeze-shape, the graph can be run successfully but the floating point error still there
`
root@16c1059547df:/models# polygraphy run folded.onnx --trt --onnxrt
[I] trt-runner-N0-04/10/21-06:29:15     | Activating and starting inference
[I] Loading bytes from /models/folded.onnx
[TensorRT] WARNING: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/onnx2trt_utils.cpp:226: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[I] Building engine with configuration: max_workspace_size=16777216 (16.00 MB) | tf32=False, fp16=False, int8=False, strict_types=False | 1 profiles
[I] trt-runner-N0-04/10/21-06:29:15     | Input Metadata: {input [dtype=float32, shape=(1, 1, 32, 512)]}
[I] trt-runner-N0-04/10/21-06:29:15     | Output Metadata: {output [dtype=float32, shape=(1, 129, 200)]}
[D] trt-runner-N0-04/10/21-06:29:15     | Completed 1 iteration(s) in 15.3 ms | Average inference time: 15.3 ms.
[I] onnxrt-runner-N0-04/10/21-06:29:15  | Activating and starting inference
[I] Loading bytes from /models/folded.onnx
[I] onnxrt-runner-N0-04/10/21-06:29:15  | Input Metadata: {input [dtype=float32, shape=(1, 1, 32, 512)]}
[I] onnxrt-runner-N0-04/10/21-06:29:15  | Output Metadata: {output [dtype=float32, shape=(1, 129, 200)]}
[D] onnxrt-runner-N0-04/10/21-06:29:15  | Completed 1 iteration(s) in 188.2 ms | Average inference time: 188.2 ms.
[I] Accuracy Comparison | trt-runner-N0-04/10/21-06:29:15 vs. onnxrt-runner-N0-04/10/21-06:29:15
[I]     Comparing Output: 'output' (dtype=float32, shape=(1, 129, 200)) with 'output' (dtype=float32, shape=(1, 129, 200))
[I]         Required Tolerance: [abs=0.00016594] OR [rel=1e-05, abs=0.00011463] OR [rel=0.10171, abs=1e-05] | Mean Error: [abs=1.5195e-06, rel=4.7805e-06]
            trt-runner-N0-04/10/21-06:29:15     | Stats: mean=-2.1643, min=-15.289 at (0, 1, 147), max=11.984 at (0, 1, 0)
            onnxrt-runner-N0-04/10/21-06:29:15  | Stats: mean=-2.1643, min=-15.289 at (0, 1, 147), max=11.984 at (0, 1, 0)
[E]         FAILED | Difference exceeds tolerance (rel=1e-05, abs=1e-05)
[E]     FAILED | Mismatched outputs: ['output']
[!] FAILED | Command: /usr/local/bin/polygraphy run folded.onnx --trt --onnxrt
`

**Comment by sapjunior** [comment]
The error still persist in latest TensorRT 8.3.2 (TensorRT NGC Container 22.01). I am not sure that is there any progress on this problem?

**Comment by nvpohanh** [comment]
With TRT 8.4.1, I am able to get good results using the sanitized model:

```
[I]         onnxrt-runner-N0-06/15/22-03:31:52: output | Stats: mean=-0.00058504, std-dev=0.039764, var=0.0015812, median=0.0029878, min=-0.094943 at (0, 128, 114), max=0.10609 at (0, 7, 26), avg-magnitude=0.033334
[V]             ---- Histogram ----
                Bin Range          |  Num Elems | Visualization
                (-0.0949, -0.0748) |        387 | ###
                (-0.0748, -0.0547) |       1816 | ##############
                (-0.0547, -0.0346) |       3988 | ###############################
                (-0.0346, -0.0145) |       3501 | ###########################
                (-0.0145, 0.00557) |       3860 | ##############################
                (0.00557, 0.0257 ) |       5016 | ########################################
                (0.0257 , 0.0458 ) |       4387 | ##################################
                (0.0458 , 0.0659 ) |       1689 | #############
                (0.0659 , 0.086  ) |       1026 | ########
                (0.086  , 0.106  ) |        130 | #
[I]         trt-runner-N0-06/15/22-03:31:52: output | Stats: mean=-0.00058504, std-dev=0.039764, var=0.0015812, median=0.0029878, min=-0.094943 at (0, 128, 114), max=0.10609 at (0, 7, 26), avg-magnitude=0.033334
[V]             ---- Histogram ----
                Bin Range          |  Num Elems | Visualization
                (-0.0949, -0.0748) |        387 | ###
                (-0.0748, -0.0547) |       1816 | ##############
                (-0.0547, -0.0346) |       3988 | ###############################
                (-0.0346, -0.0145) |       3501 | ###########################
                (-0.0145, 0.00557) |       3860 | ##############################
                (0.00557, 0.0257 ) |       5016 | ########################################
                (0.0257 , 0.0458 ) |       4387 | ##################################
                (0.0458 , 0.0659 ) |       1689 | #############
                (0.0659 , 0.086  ) |       1026 | ########
                (0.086  , 0.106  ) |        130 | #
[I]         Error Metrics: output
[I]             Minimum Required Tolerance: elemwise error | [abs=4.6566e-08] OR [rel=0.00033911] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=5.1263e-09, std-dev=4.7075e-09, var=2.2161e-17, median=3.7253e-09, min=0 at (0, 0, 2), max=4.6566e-08 at (0, 5, 168), avg-magnitude=5.1263e-09
[V]                 ---- Histogram ----
                    Bin Range            |  Num Elems | Visualization
                    (0       , 4.66e-09) |      14600 | ########################################
                    (4.66e-09, 9.31e-09) |       7264 | ###################
                    (9.31e-09, 1.4e-08 ) |       2324 | ######
                    (1.4e-08 , 1.86e-08) |       1092 | ##
                    (1.86e-08, 2.33e-08) |        392 | #
                    (2.33e-08, 2.79e-08) |         57 |
                    (2.79e-08, 3.26e-08) |         46 |
                    (3.26e-08, 3.73e-08) |         11 |
                    (3.73e-08, 4.19e-08) |         13 |
                    (4.19e-08, 4.66e-08) |          1 |
[I]             Relative Difference | Stats: mean=6.4604e-07, std-dev=4.49e-06, var=2.016e-11, median=1.36e-07, min=0 at (0, 0, 2), max=0.00033911 at (0, 6, 173), avg-magnitude=6.4604e-07
[V]                 ---- Histogram ----
                    Bin Range            |  Num Elems | Visualization
                    (0       , 3.39e-05) |      25742 | ########################################
                    (3.39e-05, 6.78e-05) |         39 |
                    (6.78e-05, 0.000102) |         11 |
                    (0.000102, 0.000136) |          5 |
                    (0.000136, 0.00017 ) |          0 |
                    (0.00017 , 0.000203) |          1 |
                    (0.000203, 0.000237) |          0 |
                    (0.000237, 0.000271) |          1 |
                    (0.000271, 0.000305) |          0 |
                    (0.000305, 0.000339) |          1 |
[I]         PASSED | Difference is within tolerance (rel=1e-05, abs=1e-05)
[X]         Finished comparing: 'output' (dtype=float32, shape=(1, 129, 200)) [onnxrt-runner-N0-06/15/22-03:31:52] and 'output' (dtype=float32, shape=(1, 129, 200)) [trt-runner-N0-06/15/22-03:31:52]
[I]     PASSED | All outputs matched | Outputs: ['output']
[X]     Finished comparing onnxrt-runner-N0-06/15/22-03:31:52 with trt-runner-N0-06/15/22-03:31:52
[I] PASSED | Command: /home/pohanh/.local/bin/polygraphy run --onnxrt --trt --input-shapes=input:[1,1,32,512] build/github1177_sanitized.onnx -vv
```

@sapjunior Could you try TRT 8.4.1? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
