### ISSUE TITLE
A question about TensorRT cancel point and IExecutionContext

### ISSUE THREAD

**Issue by KarKLi** [NVIDIA/TensorRT#1184]
Hello there, I am a developer of inference task serving system. We use TensorRT 6/TensorRT 7 as our inference execute framework. Due to soft realtime limitation, we sometimes need to cancel current context->execute() / context->executeV2() for next inference task running safely.
I didn't find any solution on TensorRT documentation, can TensorRT development team gives me some advice of cancel context->execute()? My context->execute() is running on a single POSIX thread, can I cancel it safely? Or can you give me more information about TensorRT cancellation point? Thanks a lot!

**Comment by ttyio** [comment]
Sorry @KarKLi , it is CUDA limitation that we cannot cancel the kernels that already enqueued. even for cudaDeviceReset, it will first flush the work that pending in the queue and wait for GPU idle first.

**Comment by KarKLi** [comment]
> Sorry @KarKLi , it is CUDA limitation that we cannot cancel the kernels that already enqueued. even for cudaDeviceReset, it will first flush the work that pending in the queue and wait for GPU idle first.

Thx. And I have another question that the IExecutionContext created by engine->CreateExecutionContext() / engine->CreateExecutionContextWithoutDeviceMemory() can be reused? The "reused" means I don't call ctx->destroy(), save the pointer and use it again for later inference with CUDA stream or just CUDA. Will the inference execute properly?

**Comment by ttyio** [comment]
Hello @KarKLi , yes the `IExecutionContext` can be reused. But do not call `IExecutionContext::enqueue()`  with 2 different cuda stream simultaneously.  This is because intermediate tensor is resource of `IExecutionContext`,  behavior of execute the same context simultaneously on 2 different stream is undefined.

**Comment by KarKLi** [comment]
> Hello @KarKLi , yes the `IExecutionContext` can be reused. But do not call `IExecutionContext::enqueue()` with 2 different cuda stream simultaneously. This is because intermediate tensor is resource of `IExecutionContext`, behavior of execute the same context simultaneously on 2 different stream is undefined.

thanks for your reply! What if I create two IExecutionContext pointer by the same engine or different engines and call ```IExecutionContext::enqueue()``` / ```IExecutionContext::enqueueV2()``` with same cuda stream, will it cause undefined behaviour?

**Comment by ttyio** [comment]
Hello @KarKLi , 
cases are valid:
- ctx A and ctx B run on cuda stream A 
- ctx A run on cuda stream A and ctx B run on cuda stream B
- ctx A run on cuda stream A, then run on stream B after waiting stream A finished

only invalid case:
- ctx A run on cuda stream A, and run on stream B without event sync/wait

**Comment by KarKLi** [comment]
> Hello @KarKLi ,
> cases are valid:
> 
> * ctx A and ctx B run on cuda stream A
> * ctx A run on cuda stream A and ctx B run on cuda stream B
> * ctx A run on cuda stream A, then run on stream B after waiting stream A finished
> 
> only invalid case:
> 
> * ctx A run on cuda stream A, and run on stream B without event sync/wait

Thanks! I have last question that can the ctx's execution memory be exposed to user by some kind of TensorRT API? If not, forget to record the device memory address when I call ```ctx->setDeviceMemory()``` will cause GPU memory leak?

**Comment by ttyio** [comment]
Helo @KarKLi , 
do you mean activations when you say `execution memory`? activations are shared between contexts for the same engine.
currently only the device memory is exposed and you can use `createExecutionContextWithoutDeviceMemory`/`setDeviceMemory` to set them, or use `createExecutionContext` to ask TRT to manage this part of memory. and yes there will be memory leak if you manage it but not proper released.

**Comment by KarKLi** [comment]
> Helo @KarKLi ,
> do you mean activations when you say `execution memory`? activations are shared between contexts for the same engine.
> currently only the device memory is exposed and you can use `createExecutionContextWithoutDeviceMemory`/`setDeviceMemory` to set them, or use `createExecutionContext` to ask TRT to manage this part of memory. and yes there will be memory leak if you manage it but not proper released.

Got it. Thanks!
