### ISSUE TITLE
What are strict_type_constraints?

### ISSUE THREAD

**Issue by DonggeunYu** [NVIDIA/TensorRT#1191]
I've read the description of strict_type_constraints, but I don't understand well.
Can you give an example?

**Comment by ttyio** [comment]
Hello @DonggeunYu .

e.g, for INT8 network, you know some node is sensitive to accuracy,  you decide to run those nodes run on higher precision (half, fp32). Then you need enable the `strict_type_constraints`,  set the precision for these layer, also the data type for those layer output.

**Comment by ttyio** [comment]
BTW, the linked content is deprecated, now we recommend user to create `builderConfig`, and set `strict_types` in it.
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/NetworkConfig.html#tensorrt.BuilderFlag

**Comment by DonggeunYu** [comment]
Oh, Thanks for your help every time :)
