### ISSUE TITLE
ERROR] ../builder/cudnnBuilderGraphOptimizer.cpp (3121) 

### ISSUE THREAD

**Issue by chenjun2hao** [NVIDIA/TensorRT#1199]
when i parser one onnx model on tx2/nx, i get this error:
```
[2021-04-16 01:44:21   ERROR] ../builder/cudnnBuilderGraphOptimizer.cpp (3121) - Assertion Error in mergeDAG: 0 (d1Inputs.size() == n1.inputs.size())
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
Aborted (core dumped)
```

but, the same model works well on my pc which is ubuntu18.04.this is my onnx model.

[litehrnet.zip](https://github.com/NVIDIA/TensorRT/files/6321963/litehrnet.zip)

**waiting for help, thanks!!**

**Comment by ttyio** [comment]
Sorry @chenjun2hao , this is duplicate to https://github.com/NVIDIA/TensorRT/issues/548

Current Jetpack is based on TRT7.1, the fix is in the TensorRT core part, so we have to wait for Jetpack release with 7.2.

**Comment by NikolasMarkou** [comment]
Hi @chenjun2hao @ttyio , i have posted a solution https://github.com/NVIDIA/TensorRT/issues/548

**Comment by chenjun2hao** [comment]
@NikolasMarkou ，thanks! however my model don't have `mul` op.

**Comment by NikolasMarkou** [comment]
@chenjun2hao the same goes for SUB (very often done to get an all zero tensor)

**Comment by chenjun2hao** [comment]
@NikolasMarkou ，i also don't have `SUB` op . `very often done to get an all zero tensor` ， What does this mean? thanks.

**Comment by NikolasMarkou** [comment]
@chenjun2hao if you want to get an all zero's tensor in the shape of a specific tensor there are multiple ways to do so. The optimizer chooses to substract a tensor from it self. This is a valid operation but tensorrt under some specific conditions doesn't like it.

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
