### ISSUE TITLE
[tf->onnx->trt][dynamic input shape] Encounted errors when build the engine

### ISSUE THREAD

**Issue by lulindeng** [NVIDIA/TensorRT#1200]
Hi,

The TensorFlow model I used is require dynamic input shape, so I try to convert it to onnx model and then to TensorRT.

I use [tf2onnx](https://github.com/onnx/tensorflow-onnx) convert the model, and then use following code to build the engine.
```
def build_engine(onnx_path):

    EXPLICIT_BATCH = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, \
            trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_workspace_size = 1 << 10

        with open(onnx_path, 'rb') as model:
            parser.parse(model.read())
            if not parser.parse(model.read()):
                print(f"num_of_error:{parser.num_errors}")
                for error in range(parser.num_errors):
                    print(parser.get_error(error))

        print("The input shape is:")
        print(network.get_input(0).shape)
        network.add_input(INPUT_NODE, trt.float32, (1, -1, -1, 3))
        config = builder.create_builder_config()
        config.max_workspace_size = 1 << 10

        profile = builder.create_optimization_profile()
        profile.set_shape(network.get_input(0).name,
                          min=(1, 100, 200, 3),
                          opt=(1, 1000, 500, 3),
                          max=(1, 2000, 1000, 3))

        print("The number of layers in network:")
        print(network.num_layers)
        last_layer = network.get_layer(network.num_layers - 1)
        network.mark_output(last_layer.get_output(0))

        # config.add_optimization_profile(profile)
        engine = builder.build_engine(network, config)
        return engine
```
After running the code, Encounted these errors:
```
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
The input shape is:
(1, -1, -1, 3)
The number of layers in network:
0
python: ../builder/Network.cpp:1195: virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed.
Aborted (core dumped)

```
I have two questions, 

1. Is the profile.set_shape for dynamic shape input need to add in the config when build the engine? More specific, `config.add_optimization_profile(profile)` is needed in the `builder.build_engine(network, config)` step?

2. If I comment these two lines of code
```
last_layer = network.get_layer(network.num_layers - 1)
network.mark_output(last_layer.get_output(0))
```
It would have the error:
```
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
```
So I add these two lines to solve this problem, but it is exactly these two lines caused the first error as I mentioned before, and then I printed `network.num_layers` , find that it is 0. Would this caused by the onnx model? but when I print `network.get_input(0).shape`, it works fine. Anyone have some ideas about this issue? 

Deepest thanks for your reply!

BTW, I also tried the onnx-simplify model, still the same issue.

Environment:
1. Ubuntu 16.04
2. Cuda: 10.0
3. python: 3.7.10
4. tensorflow-gpu: 2.0.0 
5. tensorrt: 7.2.3.4
6. tf2onnx: 1.8.4

**Comment by ttyio** [comment]
Hello @lulindeng 
1. `add_optimization_profile` is necessary for engine build with dynamic shapes
2. `network.mark_output` is not necessary for model import from onnx.  The onnx spec already marked output nodes.

also ` network.add_input`  is not necessary in your code. If you want to export onnx with dynamic shape support, you have to export onnx whose input dimension includes -1.

**Comment by lulindeng** [comment]
> Hello @lulindeng
> 
> 1. `add_optimization_profile` is necessary for engine build with dynamic shapes
> 2. `network.mark_output` is not necessary for model import from onnx.  The onnx spec already marked output nodes.
> 
> also ` network.add_input` is not necessary in your code. If you want to export onnx with dynamic shape support, you have to export onnx whose input dimension includes -1 (you can use netron https://github.com/lutzroeder/netron to visialize the onnx make sure it is dynamic shape).

Thanks for your answer!

I found that the error is from the onnxparser, turns out my model has reflect mode pad, but TensorRT can only support constant zero padding now. This issue looks tricky.

**Comment by ttyio** [comment]
Sorry @lulindeng , this is known issue https://github.com/NVIDIA/TensorRT/issues/1019, and we already have internal RFE request to track this.

**Comment by ttyio** [comment]
This will be supported in next release, close as duplicate to https://github.com/NVIDIA/TensorRT/issues/1019, thanks
