### ISSUE TITLE
Support for refittable networks with dynamic shapes

### ISSUE THREAD

**Issue by m-ky** [NVIDIA/TensorRT#1202]
Hello,

I would like to ask whether support for refittable networks with dynamic shapes is planned in near future. Or if it is not a priority.
Use case: U-net like networks where we need to change all weights (without having to rebuild whole network).
I am using TensorRT 7.2.3.4 and Win10.
Currently the network won't build with this error message:
Refittable networks with dynamic shapes is not supported.

**Comment by ttyio** [comment]
Sorry @m-ky , there is no support for refit on dynamic shapes. It is not in the high priority queue. 
Do you want N to be the dynamic shape? If so you can WAR using the implicit batch in TRT.

**Comment by m-ky** [comment]
Thanks for answer.
I am aware N can be dynamic with implicit batch, but I need to have dynamic size X and Y as well.

**Comment by pmixer** [comment]
> Sorry @m-ky , there is no support for refit on dynamic shapes. It is not in the high priority queue.
> Do you want N to be the dynamic shape? If so you can WAR using the implicit batch in TRT.

Hi Vincent,

Same question and similar needs here, but for recommendation scenario.

I could understand the engineering burden to support refit feature for dynamic batch input, as it concerns the new runtime used for dynamic shape input networks introduced in TrT6.

Just want to double check that:

0) refit for dynamic shape input networks is doable, just not implemented yet?
1) for NCHW input, if we get NC fixed, only HW accept dynamic shape input, would it be easier to support refit feature?

I still think dynamic shape input feature is of great value for encouraging wider use of TrT with more flexibility. People used to fail using it as the feature was kind of incomplete(like N, C need to be fixed etc.) before which makes it seems of low priority.

cc @joohoon FYI.

Regards,
Peter
