### ISSUE TITLE
TRT engine (de)serialization on jetson issue

### ISSUE THREAD

**Issue by limitz** [NVIDIA/TensorRT#1206]
## Description

When deserializing a previously serialized engine the program produces invalid results. This only happens on Jetson devices (both Xavier NX and Nano), no problems on the desktop, so probably something to do with the version / the NMS plugin?

This might be similar to https://github.com/NVIDIA/TensorRT/issues/1175, the difference is that I'm specifically building the engine in code without trtexec, and get different results when I build the engine in code or deserialize it

_First run, engine built in code and serialized_
![with a freshly built engine](https://user-images.githubusercontent.com/634038/115443588-bc2bd680-a213-11eb-874e-6eec4de9dc2d.png)

_Second run, uses the serialized engine_
![with a deserialized engine](https://user-images.githubusercontent.com/634038/115443618-c4841180-a213-11eb-83dc-71e3a2bdf0bf.png)

## Environment

**TensorRT Version**: 7.1.3.0-1+cuda10.2
**NVIDIA GPU**: both Jetson Xavier NX and Jetson Nano
**CUDA Version**: 10.2.89
**CUDNN Version**: 8.0.0.180-1+cuda10.2 
**Operating System**: L4T

## Relevant Files

[My repo](https://github.com/limitz/cuda-infer-template)
[More specifically this example](https://github.com/limitz/cuda-infer-template/tree/main/examples/basic)
[About downloading the weights](https://github.com/limitz/cuda-infer-template/blob/main/models/README.md)

## Steps To Reproduce

1. The first run builds the TensorRT engine from a prototxt/caffemodel, similar to [this sample](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleSSD)
2. The program then serializes and saves the engine to a file
3. The program produces valid results
4. When the program is restarted the previously serialized engine is loaded instead of building the model.
5. The program produces invalid results

**Comment by ttyio** [comment]
Hello @limitz , could you check https://github.com/NVIDIA/TensorRT/issues/1089
Is this the same issue, if so this can be solved by build plugin from opensource repo. thanks!

**Comment by limitz** [comment]
Hi @ttyio, unfortunately that did not seem to help.
 
First I tried tag 7.1.3, built it and installed it over the existing version. This gave me errors at runtime both when building the engine and deserializing it (2 different errors).

After that I tried tag 7.2.1 and installed it, now there are no more errors but the problem as described above persists.
For completeness I built trt oss like:
```
cmake .. -DCUDA_VERSION=10.2 -DGPU_ARCHS="72"
make -j6
make install
sudo cp -P ~/projects/TensorRT/lib/libnv* /usr/lib/aarch64-linux-gnu/
```

**Comment by ttyio** [comment]
@limitz 
the build command for 7.2 is OK to me, the only concern is the version number in the output, I am not sure if the symbol `libnvinfer_plugin.so` link to `nvinfer_plugin.so.7.2.1` or `nvinfer_plugin.so.7.1.3` in your system.

Also what's the error when use oss 7.1.3 build? thanks!

**Comment by limitz** [comment]
@ttyio Ok, the weirdest thing is that it now works on 7.1.3. 
What I did differently this time is that I explicitly set the GPU_ARCHS="72" for the build whereas before I just didn't define it and went with the default settings (which seem to exclude 72). 
The error I had before had something to do with NCHW conversion not being a device function IIRC, and during deserialize there was an issue with Normalization (Layer or plugin i can't remember). I could do a build without the GPU_ARCHS setting if you are really interested. 

Thanks for your help!

**Comment by ttyio** [comment]
Cool @limitz , Xavier has sm_72 capability, and the sass code is not compatible between different sm arch. I will close this since now TRT works on your jetson, thanks~

**Comment by Sixkplus** [comment]
> @ttyio Ok, the weirdest thing is that it now works on 7.1.3.
> What I did differently this time is that I explicitly set the GPU_ARCHS="72" for the build whereas before I just didn't define it and went with the default settings (which seem to exclude 72). I only added the GPU_ARCHS when I built 7.2.1 when I think about it.
> The error I had before had something to do with NCHW conversion not being a device function IIRC, and during deserialize there was an issue with Normalization (Layer or plugin i can't remember). I could do a build without the GPU_ARCHS setting if you are really interested.
> 
> Thanks for your help!

Thanks a lot, I met this problems these days on Jetson NX, this helps me a lot!
