### ISSUE TITLE
how to get  weight  value and  calib table after  int8 quantization

### ISSUE THREAD

**Issue by zhvn100** [NVIDIA/TensorRT#1212]
## Description
I want to deploy the network on my accelerator . Can i  insert output  sentences  in program when i generate int8 engine ? 
So the weight value and calib table  will display on the terminal  when inferencing on gpu.
Please tell me  whether i can get int8 weight and calib table  throught this way  or I can do it in other ways。

**Comment by ttyio** [comment]
Hello @zhvn100 , 

For PTQ, we support dump the scale for the activation only, see https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Int8/Calibrator.html#tensorrt.IInt8Calibrator.write_calibration_cache, but we have no way to dump the scale for the weights.

For QAT, you can check the scale using visualization tools like Netron.

**Comment by zhvn100** [comment]
@ttyio ok，thank you
