### ISSUE TITLE
how support permute_layer with four "order"s?

### ISSUE THREAD

**Issue by mmx110** [NVIDIA/TensorRT#1215]
I know tensorRT support permute layer with "c、h、w" as follow:
layer {
  name: "permuted"
  type: "Permute"
  bottom: "fc5"
  top: "permuted_fc5"
  cw_permute_param {
    order: 0
    order: 1
    order: 2
  }
}
but how can i do to support four dimensions "n、c、h、w" as follow:
layer {
  name: "permuted"
  type: "Permute"
  bottom: "fc5"
  top: "permuted_fc5"
  cw_permute_param {
    order: 3
    order: 0
    order: 1
    order: 2
  }
}

**Comment by ttyio** [comment]
Hello @mmx110 , could you check the `permutation` in IShuffleLayer? 
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_shuffle_layer.html
