### ISSUE TITLE
How to infer in parallel on multiple GPUs

### ISSUE THREAD

**Issue by wellinxu** [NVIDIA/TensorRT#1216]
## Description

We have four GPUs, and we build a BertInference object on each GPU,but we can't infer in parallel。

![multi-gpu](https://user-images.githubusercontent.com/10526965/116202634-6607e780-a76d-11eb-8de1-f53d99b2ff1c.jpg)

The figure above shows the usage of GPU at a certain time, which does not seem to be parallel。How to infer in parallel on multiple GPUs？

## Environment

**TensorRT Version**: 7.2.2.3
**NVIDIA GPU**: V100-30g
**NVIDIA Driver Version**: 
**CUDA Version**: 11.1
**CUDNN Version**: 8
**Operating System**: ubuntu-18.04
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

Here is code.
## Relevant Files
```python

import os
import sys
import time
import numpy as np
import threading

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'build'))

import infer_c


if __name__ == '__main__':

    engine = "/workspace/engines/tiny-bert.engin"
    batch_size = 75
    max_seq_length = 256
    enable_graph = True

    gpus = [0, 1, 2, 3]
    berts = []
    for device in gpus:
        bert = infer_c.bert_inf(engine, batch_size, max_seq_length, enable_graph, device)
        bert.prepare(batch_size)
        berts.append(bert)

    pseudo_vocab_size = 30522
    pseudo_type_vocab_size = 2
    np.random.seed(10086)


    def dotask():
        for i in range(100):
            input_ids = np.random.randint(0, pseudo_vocab_size, (max_seq_length, batch_size),
                                          dtype=np.int32).ravel()
            segment_ids = np.random.randint(0, pseudo_type_vocab_size,
                                            (max_seq_length, batch_size), dtype=np.int32).ravel()
            input_mask = np.ones((max_seq_length, batch_size), dtype=np.int32).ravel()
            # input_ids = np.ascontiguousarray(feature.input_ids.ravel())
            # segment_ids = np.ascontiguousarray(feature.segment_ids.ravel())
            # input_mask = np.ascontiguousarray(feature.input_mask.ravel())
            while not gpus:
                pass
            id = gpus.pop(0)
            bert = berts[id]
            h_output = bert.run(input_ids, segment_ids, input_mask)
            gpus.append(id)


    thread_num = 10
    threads = []
    start = time.time()
    for i in range(thread_num):
        t = threading.Thread(target=dotask)
        threads.append(t)
        t.start()

    for t in threads:
        t.join()

    end = time.time()
    print("thread num:", thread_num, "num of per thread: 100", "time:", (end - start))
```

**Comment by ttyio** [comment]
Hello @wellinxu ,

We have nsight system that can show the multi gpu usage in the same timeline https://developer.nvidia.com/nsight-systems 

Also python has GIL (Global Interpreter Lock), so maybe switch to C++ API is a better choice, and you can take this code as reference
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec

Thanks!

**Comment by wellinxu** [comment]
@ttyio  Thanks!
Have you compared it with FasterTransformer, and whose speed is faster? https://github.com/NVIDIA/FasterTransformer#encoder-performance

**Comment by ttyio** [comment]
@wellinxu 
no, 
FYI, fastertransformer now also merge some of the code from trt, e.g,
https://github.com/NVIDIA/TensorRT/tree/master/plugin/bertQKVToContextPlugin
https://github.com/NVIDIA/FasterTransformer/tree/main/fastertransformer/trt_fused_multihead_attention

**Comment by wellinxu** [comment]
@ttyio Thank you!
