### ISSUE TITLE
engine->getNbBindings() is not '2'

### ISSUE THREAD

**Issue by sinuku** [NVIDIA/TensorRT#1217]
## Description
Hi!
I converted my custom trained model to .trt file(using torch2trt)

`engine->getNbBindings()` value should be 2, but 10

Is it because of a mistake when converting?

## Environment

**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: gtx1060
**NVIDIA Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 8.1.1
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.7.0
**Baremetal or Container (if so, version)**: 

## Relevant Files

This is the .trt file I converted.
https://drive.google.com/file/d/1p6-Ln2q-2bdtVoFTsZHID4yYPE__eQ_q/view?usp=sharing

**Comment by ttyio** [comment]
Sorry @sinuku , torchtrt called `addInput()` and TRT just generate engine has identical network inputs.
So maybe you could ask the question in 
https://github.com/NVIDIA-AI-IOT/torch2trt
Thanks！

**Comment by sinuku** [comment]
Thank you for your help!
