### ISSUE TITLE
Error Launching Tensorrt docker container

### ISSUE THREAD

**Issue by tirankas** [NVIDIA/TensorRT#1235]
Hello,
I have followed the README example on setting up a docker container to build the OSS tensorrt.
When launching the docker (setup went ALL ok) I get this:

docker run  --gpus all -v /home/osboxes/TensorRT:/workspace/TensorRT --rm -it tensorrt-cross-jetpack:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

I am using Ubuntu 18.04, docker version is 20.10.6.
I built the "Ubuntu 18.04 cross-compile for Jetson (arm64) with cuda-10.2 (JetPack SDK)" docker

Any clue what am I missing?

Thanks

**Comment by karenyun** [comment]
Hi, 
Have you solved this problem? I encounter the same issue. @tirankas 

Thanks

**Comment by nvpohanh** [comment]
@tirankas This usually means that the driver version does not match the expected driver version by that container. Could you run `nvidia-smi` to show what driver version you have in the local machine? Thanks

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
