### ISSUE TITLE
 implemented in c++ CUDA vs TensorRT

### ISSUE THREAD

**Issue by DonggeunYu** [NVIDIA/TensorRT#1245]
@ttyio
Recently, the object detection model has been successfully converted and the inference rate has also been reduced.
TensorRT uses C++ CUDA more efficiently than PyTorch. For this reason, I am wondering which is the fastest, which is the fastest model implemented in c++ cuda or the model converted to TensorRT.
If the model is implemented in c++ CUDA and the speed is better than TensorRT, the model will be directly implemented in c++ CUDA.
Can i get a public indicator of this?

**Comment by ttyio** [comment]
Hello @DonggeunYu , TRT has various optimization for your network, like graph fusion, memory optimization and optimized kernels for different precisions.  It is a lot of effort if you implement all of them. And TRT keep evolution on new GPU arch. There are a lot of adapter work if you direct implement in C++ CUDA.
