### ISSUE TITLE
TensorRT execute crash

### ISSUE THREAD

**Issue by OtisZZ** [NVIDIA/TensorRT#1246]
Hi,

I am using a TensorRT model on my pc, but after running about two hous, it returned false when after call context->execute, and the software crashed at the second time call context->execute.

Also, the pc sometimes cannot find usb device, ist something wrong about nvidia driver?

env:
windows 10
tensorRT 7.0
nvidia driver 451.48

**Comment by OtisZZ** [comment]
hello?
anybody can help?

**Comment by ttyio** [comment]
@OtisZZ  sorry the issue seems not related to tensorrt, I have not seen any similar failure like your case. Could you try to see if you can repro the issue on other machine? Thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!

**Comment by OtisZZ** [comment]
hi ttyio,
Thanks for the reply, may I ask what the situation would cause the execute() return false?

**Comment by ttyio** [comment]
@OtisZZ ，sorry I cannot tell the reason without seeing the call stack for the crash point, also have you tried TRT 8.0? we have a lot of improvement in the new version, thanks!
