### ISSUE TITLE
which version introduced `setOptimizationProfileAsync` ?

### ISSUE THREAD

**Issue by EmilioZhao** [NVIDIA/TensorRT#1247]
I used TensorRT 7.1.3, the compiler reported an error "‘class nvinfer1::IExecutionContext’ has no member named setOptimizationProfileAsync "  ?
Did I miss something or I have to upgrade to version > 7.2.x ?

**Comment by ttyio** [comment]
Hello @EmilioZhao , yes it is introduced in 7.2.
