### ISSUE TITLE
pose int8

### ISSUE THREAD

**Issue by alicera** [NVIDIA/TensorRT#1248]
ENV: 
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-04.html#rel_21-04

project:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch

Q:
I try to use the model to generate the INT8.
But the result of INT8 doesnt detect any object.
The result of FP16 can detect the object.
Do you have any idea?

[pose.onnx.zip](https://github.com/NVIDIA/TensorRT/files/6458792/pose.onnx.zip)

**Comment by nvpohanh** [comment]
@alicera  Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
