### ISSUE TITLE
The time cost problem for inference FP16 engine which is from onnx model converted by trtexec. 

### ISSUE THREAD

**Issue by favorxin** [NVIDIA/TensorRT#1250]
## Description
I converted an onnx CV model to engine by trtexec. While I get FP32 bit engine is normal and inference time is reasonable.  When I use FP16 bit which has nearly has four times reduction in memory overhead, the inference time is nearly with FP32 bit engine's performance. 

The convert code is as following:
` ./trtexec --onnx=/****/desenet_num18.onnx \
--shapes='the_input:0'1x32x148x1 \
--workspace=4096 \
--saveEngine=/****/densenet_num18_fp16.engine \
--fp16
`

The following image is the trtexec log. I confused the Precision 'FP32+FP16' which is not the same as I set in trtexec code.
![image](https://user-images.githubusercontent.com/31987475/118068447-f7fe2a00-b3d4-11eb-82b3-545327c5970e.png)

## Environment

**TensorRT Version**: 7.2.1.6
**NVIDIA GPU**: 2080Ti
**NVIDIA Driver Version**: 450.80.02
**CUDA Version**: 11.0
**CUDNN Version**: 7.6.5
**Operating System**: 
**Python Version (if applicable)**: 3.6.13
**Tensorflow Version (if applicable)**: 1.15.0
**PyTorch Version (if applicable)**: 1.7.1
**Baremetal or Container (if so, version)**: 

The tensorflow version is used in Tencent's [Forward](https://github.com/Tencent/Forward) library.

My model is here.
[densenet_num18_all_model.zip](https://github.com/NVIDIA/TensorRT/files/6470021/densenet_num18_all_model.zip)

**Comment by favorxin** [comment]
My original model is keras model, and I convert the model to onnx model. Finally, I use TensorRT to accelerate the inference.

Here is my trtexec log.
![image](https://user-images.githubusercontent.com/31987475/118069406-b5d5e800-b3d6-11eb-9493-a85a2137afae.png)

The normal TensorRT FP32 engine inference time is 1.0ms, and the TensorRT FP32+FP16 engine inference time is 0.9ms. I want to use the FP16 to accelerate the inference time.

When I use [Forward](https://github.com/Tencent/Forward) to accelerate ResNet18 model (Pytorch). The accelerating ratio is 2x between FP32 and FP16. So I wonder if my trtexec code is correct.

**Comment by ttyio** [comment]
Hello @favorxin , the command line looks fine to me. Could you take a try with latest 8.0 release? 

If you still observe the issue, please run with `--verbose --separateProfileRun --dumpProfile` and attach the log here, thanks!

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
