### ISSUE TITLE
why builder.fp16_mode is useless

### ISSUE THREAD

**Issue by LoadLife** [NVIDIA/TensorRT#1252]
## Description
i created a network using tensorRT python api
the pseudocode is like:
```
network = builder.create_network()
input_tensor = network.add_input("input", trt.DataType.HALF, input_shape)
pooling = network.add_pooling(input_tensor, trt.PoolingType.AVERAGE, pooling_window)
pooling.precision = trt.DataType.HALF
pooling.set_ouput_type(0, trt.DataType.HALF)
network.mark_ouput(pooling.get_output(0)) 
```
in this case, i also set `builder.fp16_mode = True && builder.strict_type_constraints = True`, it's also useless, the pooling's ouput dtype get from `engine.get_binding_dtype(pooling_tensor.index) ` is FLOAT, not is HALF

## Environment 
**TensorRT Version**: 7.0
**NVIDIA GPU**: RTX 2070
**NVIDIA Driver Version**: 410.48
**CUDA Version**: cuda 10.0
**CUDNN Version**: unknown
**Operating System**: ubuntu 16.04
**Python Version (if applicable)**: python3.6.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by LoadLife** [comment]
in this case, i also set `builder.fp16_mode = True && builder.strict_type_constraints = True`, it's also useless, the pooling's ouput dtype get from `engine.get_binding_dtype(pooling_tensor.index) ` is FLOAT, not is HALF

**Comment by 842974287** [comment]
I'm not the expert but it seems like `layer.set_output_type` doesn't really change the output type of the tensor. If you really want to set the type of a tensor you need to call `tensor.dtype = some_type`. Reference: https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_layer.html#ad0b6623245e60aaa8235e5100c782a24

**Comment by ttyio** [comment]
Hello @LoadLife , TRT network output is `fp32` by default, to change it we need use reformatFree feature, the sample is in https://github.com/NVIDIA/TensorRT/tree/release/7.2/samples/opensource/sampleReformatFreeIO, thanks

**Comment by LoadLife** [comment]
> Hello @LoadLife , TRT network output is `fp32` by default, to change it we need use reformatFree feature, the sample is in https://github.com/NVIDIA/TensorRT/tree/release/7.2/samples/opensource/sampleReformatFreeIO, thanks

thanks a lot
