### ISSUE TITLE
Saving a context

### ISSUE THREAD

**Issue by fdlci** [NVIDIA/TensorRT#1255]
Hi,

I am using your inference.py algorithm in the demo/BERT folder. To run inference, you need to load the engine to build the context as follows:

  with open(args.engine, "rb") as f, \
      trt.Runtime(TRT_LOGGER) as runtime, \
      runtime.deserialize_cuda_engine(f.read()) as engine, \
      engine.create_execution_context() as context:

Is it possible to save the context so that we don't have to load it every time we want to run inference? 
Thank you for your answer!

**Comment by ttyio** [comment]
Hello @fdlci , you can reuse the context, no need to create it for every inference. Did you hit any error? thanks!

**Comment by fdlci** [comment]
Yes I can run several inferences without loading the context again. I thought I couldn't do that as I was running inference.py on one example only and everytime I tried a new example I had to run the entire code and reload the context again.
Thank you for your answer!

**Comment by ttyio** [comment]
@fdlci Thanks for confirm, closing
