### ISSUE TITLE
What does enqueueV2 do? Why does it take so long ?

### ISSUE THREAD

**Issue by EmilioZhao** [NVIDIA/TensorRT#1256]
We used TensorRT asynchronous interface to do model inference and found that function `enqueueV2` took about 20ms+ on host side? I was wondering what `enqueueV2` actually do and why it take so long?
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_execution_context.html#a2f4429652736e8ef6e19f433400108c7

**Comment by ttyio** [comment]
Hello @EmilioZhao , `enqueuV2` has some kernel setup work for each layer and launch the kernel in each layer. The efficiency of enqueue depends on your CPU.
