### ISSUE TITLE
How to get ONNX model?

### ISSUE THREAD

**Issue by fdlci** [NVIDIA/TensorRT#1257]
Hi!
I am using your demo/BERT folder to run some examples on the squad dataset. I would like to try my own pytorch models. Unfortunately when I convert my model to onnx I get a mismatch between:
w.dims (1, 512) and np.frombuffer(w.raw_data, np.float32) (1024,)

In your repo you give an example of a pytorch model converted to onnx: bert_pyt_onnx_large_qa_squad11_amp_fake_quant_v1/bert_large_v1_1_fake_quant.onnx

How did you get this model please?

**Comment by ttyio** [comment]
Hello @fdlci , it is not exact the same, but you could use below link as as reference
https://github.com/NVIDIA/FasterTransformer/tree/main/bert-quantization/bert-pyt-quantization

**Comment by fdlci** [comment]
Thank you I will take a look at the repo!
