### ISSUE TITLE
Two inputs cause error in trt6.0

### ISSUE THREAD

**Issue by ailias** [NVIDIA/TensorRT#126]
my python code is as follow:
```python
            torch.onnx.export(self.model,
                              (input1, input2),
                              os.path.join(out_path, 'model.onnx'),
                              #export_params=True,
                              verbose=True,
                              input_names=['input', 'input2'],
                              output_names=['output']
                              )
```

but when I parse the network with code
"engine = builder->buildCudaEngine(*network);"
 it shows me:
[E] [TRT] Unused Input: input2 

Why???

**Comment by rmccorm4** [comment]
Hi @ailias,

Can you provide a minimal example (simple model with 2 inputs) that I can run to reproduce the issue so I can further look into this?

**Comment by bfortuner** [comment]
Were you able to figure this out?

**Comment by ma-siddiqui** [comment]
I am also facing this. Anyone solved it?

**Comment by rmccorm4** [comment]
TensorRT 7 should be released within the next few days with added RNN support and expanded ONNX op support. Check out https://developer.nvidia.com/tensorrt for more info, there's a TRT7 description at the bottom of the page.

Hopefully this will solve your issues! If not, please open a new issue and follow the bug template, thanks!

**Comment by longnanxi** [comment]
> my python code is as follow:
> 
> ```python
>             torch.onnx.export(self.model,
>                               (input1, input2),
>                               os.path.join(out_path, 'model.onnx'),
>                               #export_params=True,
>                               verbose=True,
>                               input_names=['input', 'input2'],
>                               output_names=['output']
>                               )
> ```
> 
> but when I parse the network with code
> "engine = builder->buildCudaEngine(*network);"
> it shows me:
> [E] [TRT] Unused Input: input2
> 
> Why???

Were you able to figure this out?

**Comment by longnanxi** [comment]
> Were you able to figure this out?

Were you able to figure this out?

**Comment by longnanxi** [comment]
> I am also facing this. Anyone solved it?

Were you able to figure this out?

**Comment by longnanxi** [comment]
> Hi @ailias,
> 
> Can you provide a minimal example (simple model with 2 inputs: pytorch code + onnx model) that I can run to reproduce the issue so I can further look into this?

Were you able to figure this out?
