### ISSUE TITLE
trtexec gives 0 throughput for various onnx models

### ISSUE THREAD

**Issue by quic-nmorillo** [NVIDIA/TensorRT#1261]
TensorRT:  v8.0 - bleeding edge
Cuda:  11.3

I'm running trtexec for onnx models provided in /usr/src/tenssorrt/data and I'm getting 0 thoughput.  
I can run caffe2 model fine within the same container, meaning I get a non-zero throughput. 

./trtexec --onnx=/workspace/TensorRT/data/mnist/mnist.onnx --batch=1 --int8 --duration=30 --explicitBatch

_05/21/2021-16:35:50] [I] Host Latency
[05/21/2021-16:35:50] [I] min: 0.03125 ms (end to end 0.0410156 ms)
[05/21/2021-16:35:50] [I] max: 2.45703 ms (end to end 2.46484 ms)
[05/21/2021-16:35:50] [I] mean: 0.041071 ms (end to end 0.0494336 ms)
[05/21/2021-16:35:50] [I] median: 0.0410156 ms (end to end 0.0488281 ms)
[05/21/2021-16:35:50] [I] percentile: 0.0507812 ms at 99% (end to end 0.0593262 ms at 99%)
[05/21/2021-16:35:50] [I] throughput: 0 qps
[05/21/2021-16:35:50] [I] walltime: 30.0001 s
[05/21/2021-16:35:50] [I] Enqueue Time
[05/21/2021-16:35:50] [I] min: 0.0214844 ms
[05/21/2021-16:35:50] [I] max: 2.0127 ms
[05/21/2021-16:35:50] [I] median: 0.0263672 ms
[05/21/2021-16:35:50] [I] GPU Compute
[05/21/2021-16:35:50] [I] min: 0.0214844 ms
[05/21/2021-16:35:50] [I] max: 2.01758 ms
[05/21/2021-16:35:50] [I] mean: 0.0298031 ms
[05/21/2021-16:35:50] [I] median: 0.0292969 ms
[05/21/2021-16:35:50] [I] percentile: 0.0371094 ms at 99%
[05/21/2021-16:35:50] [I] total compute time: 12.5851 s
&&&& PASSED TensorRT.trtexec # ./trtexec --onnx=/workspace/TensorRT/data/mnist/mnist.onnx --batch=1 --int8 --duration=30 --explicitBatch_

_./trtexec --deploy=/workspace/TensorRT/data/mnist/mnist.prototxt --model=/workspace/TensorRT/data/mnist/mnist.caffemodel --output=prob --batch=16 --saveEngine=mnist16.trt

[05/21/2021-16:33:40] [I] Host Latency
[05/21/2021-16:33:40] [I] min: 0.113403 ms (end to end 0.124268 ms)
[05/21/2021-16:33:40] [I] max: 1.67358 ms (end to end 1.68872 ms)
[05/21/2021-16:33:40] [I] mean: 0.122154 ms (end to end 0.135326 ms)
[05/21/2021-16:33:40] [I] median: 0.119873 ms (end to end 0.131104 ms)
[05/21/2021-16:33:40] [I] percentile: 0.249756 ms at 99% (end to end 0.409134 ms at 99%)
**[05/21/2021-16:33:40] [I] throughput: 116995 qps**
[05/21/2021-16:33:40] [I] walltime: 3.00032 s
[05/21/2021-16:33:40] [I] Enqueue Time
[05/21/2021-16:33:40] [I] min: 0.0865479 ms
[05/21/2021-16:33:40] [I] max: 1.65479 ms
[05/21/2021-16:33:40] [I] median: 0.0897217 ms
[05/21/2021-16:33:40] [I] GPU Compute
[05/21/2021-16:33:40] [I] min: 0.0992432 ms
[05/21/2021-16:33:40] [I] max: 1.65283 ms
[05/21/2021-16:33:40] [I] mean: 0.107237 ms
[05/21/2021-16:33:40] [I] median: 0.104492 ms
[05/21/2021-16:33:40] [I] percentile: 0.232071 ms at 99%
[05/21/2021-16:33:40] [I] total compute time: 2.35267 s_

Thank you in advance!

**Comment by quic-nmorillo** [comment]
@ttyio, thanks for your response.  Here is the path to various library: 
_root@1daf181cb817:/workspace/TensorRT/build/out# ldd trtexec
	linux-vdso.so.1 (0x00007ffcadffc000)
	libcudart.so.11.0 => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f00638a1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f006369d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f006347e000)
	libnvcaffeparser.so.7 => /workspace/TensorRT/build/out/libnvcaffeparser.so.7 (0x00007f0063058000)
	libnvonnxparser.so.7 => /workspace/TensorRT/build/out/libnvonnxparser.so.7 (0x00007f0062c89000)
	libnvparsers.so.7 => /usr/lib/x86_64-linux-gnu/libnvparsers.so.7 (0x00007f0062757000)
	libnvinfer.so.7 => /usr/lib/x86_64-linux-gnu/libnvinfer.so.7 (0x00007f00467c9000)
	libnvinfer_plugin.so.7 => /workspace/TensorRT/build/out/libnvinfer_plugin.so.7 (0x00007f0044891000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0044508000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f004416a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0043f52000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0043b61000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0063d58000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0043959000)
	libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f0043730000)
	libmyelin.so.1 => /usr/lib/x86_64-linux-gnu/libmyelin.so.1 (0x00007f0042eb1000)
	libnvrtc.so.11.0 => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libnvrtc.so.11.0 (0x00007f00416c6000)
	libcublas.so.11 => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublas.so.11 (0x00007f003b876000)
	libcublasLt.so.11 => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublasLt.so.11 (0x00007f00306e7000)_

One other observation was that, when I'm inside the container of tensorrt-ubuntu-1804, I don't have access to /usr/src/tensorrt directory.  Is it to be expected?  
Outside of the container, on the host itself, I can access /usr/src/tensorrt directory
**_ls /usr/src/tensorrt/
bin  data  sample_**s
Inside the container, this directory is not found:
**_root@1daf181cb817:/workspace/TensorRT/build/out# ls /usr/src/tensorrt
ls: cannot access '/usr/src/tensorrt': No such file or directory_**

Thanks for your help!

**Comment by quic-nmorillo** [comment]
Hello @ttyio 
Thanks, I built a tensorrt container with TRT8.0.0.3.   
   
ldd /usr/src/tensorrt/bin/trtexec
	linux-vdso.so.1 (0x00007ffdb3df0000)
	libnvinfer.so.8 => /usr/lib/x86_64-linux-gnu/libnvinfer.so.8 (0x00007f55e9387000)
	libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f55e90ee000)
	libnvparsers.so.8 => /usr/lib/x86_64-linux-gnu/libnvparsers.so.8 (0x00007f55e8bac000)
	libnvonnxparser.so.8 => /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.8 (0x00007f55e8719000)
	libnvinfer_plugin.so.8 => /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.8 (0x00007f55e73ab000)
	libcublas.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11 (0x00007f55e036b000)
	libcublasLt.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.11 (0x00007f55d478d000)
	libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f55d4563000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f55d435f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f55d4140000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f55d3d33000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f55d3995000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f55d377d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55d338c000)
	libnvrtc.so.11.2 => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc.so.11.2 (0x00007f55d0657000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f55d044f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f560ecfe000)

However, when I tried to make -j$(nproc), I'm running into errors.  
 
**[ 28%] Linking CXX static library ../out/libnvinfer_plugin_static.a
[ 51%] Built target nvinfer_plugin_static
[ 51%] Built target caffe_proto
[ 57%] Built target nvcaffeparser
[ 63%] Built target nvcaffeparser_static
[ 64%] Built target gen_onnx_proto
[ 65%] Built target onnx_proto
[ 67%] Built target nvonnxparser_static
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libmyelin.so', needed by 'out/libnvonnxparser.so.7.2.2'.  Stop.
CMakeFiles/Makefile2:1250: recipe for target 'parsers/onnx/CMakeFiles/nvonnxparser.dir/all' failed
make[1]: *** [parsers/onnx/CMakeFiles/nvonnxparser.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error** 

Somehow the makefile is hard-coded to use **libnvonnxparser.so.7.2.2**?

https://github.com/NVIDIA/TensorRT

This is the git repo I'm running from.  Failed at "
 cd $TRT_OSSPATH
 mkdir -p build && cd build
 cmake .. -DTRT_LIB_DIR=$TRT_LIBPATH -DTRT_OUT_DIR=`pwd`/out
 **make -j$(nproc)**

**Comment by ttyio** [comment]
Hello @quic-nmorillo , the OSS build for TRT8 is not released yet. please use the trtexec from the binary build in https://developer.nvidia.com/nvidia-tensorrt-download

**Comment by quic-nmorillo** [comment]
@ttyio Thanks!  If I understand you correctly, I'm going to have to do the followings:
1) Uninstall TRT8
2)  Re-install TRT7 
3) Rebuild container with TRT7 and Cuda 11.0 or 11.1
4)  Download trtexec from Nvidia binary build directory.  Do I overwrite trtexec in the container $PWD/build/out/trtexec or do I overwrite trtexec under /usr/src/tensorrt/bin/trtexec?

**Comment by ttyio** [comment]
Sorry @quic-nmorillo , for the networks that contains `boolean` or `loop`, TRT cannot always generate the engine that work with the cuda graph.

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
