### ISSUE TITLE
Onnx Dynamic input to TensorRT

### ISSUE THREAD

**Issue by BarryKCL** [NVIDIA/TensorRT#1264]
[TensorRT] INTERNAL ERROR: Assertion failed: aMatrix.second == bMatrix.first
../rtExt/cuda/cudaMatrixMultiplyRunner.cpp:35
Aborting...
[TensorRT] ERROR: ../rtExt/cuda/cudaMatrixMultiplyRunner.cpp (35) - Assertion Error in assertDimsOkayForMatrixMultiplyLayer: 0 (aMatrix.second == bMatrix.first)

**Comment by ttyio** [comment]
Hello @BarryKCL 
The error means that some `MatrixMultiply` has illegal input shape,  for A x B, we must have A with shape {M, K} and B with shape {K, N}. Could you a check of your model or share a repro for us? thanks!

**Comment by BarryKCL** [comment]
> Hello @BarryKCL
> The error means that some `MatrixMultiply` has illegal input shape, for A x B, we must have A with shape {M, K} and B with shape {K, N}. Could you a check of your model or share a repro for us? thanks!

Thanks,I split the model into 2 to replace dynamic control flows,solved this problem.But,I meet another problem:

with Tesla T4,15G memory,FP16
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)

Even set small dynamic input.

**Comment by ttyio** [comment]
@BarryKCL , have you tried small batch size, small workspace size? thanks

**Comment by ttyio** [comment]
@BarryKCL , could you limit your batch size to smaller number since you get output of memory for `20`?

**Comment by BarryKCL** [comment]
yes.I tried batch size==1,also output of memory.But do not use dynamic input ,and set max size it worked.

**Comment by ttyio** [comment]
@BarryKCL do you mean `min = opt = max = 1` in the dynamic shape profile?

**Comment by BarryKCL** [comment]
> @BarryKCL do you mean `min = opt = max = 1` in the dynamic shape profile?

yes.like this:
            print("network.get_input(0).name", network.get_input(0).name)
            profile.set_shape(network.get_input(
                0).name, (1, 1), (1, 1), (1, 1))

            print("network.get_input(1).name", network.get_input(1).name)
            profile.set_shape(network.get_input(
                1).name, (1, 1 , 1), (1, 1 , 1), (1, 1 , 1))

            
            print("network.get_input(2).name", network.get_input(2).name)
            profile.set_shape(network.get_input(
                2).name, (16, 1 , 1,512), (16, 1 , 1,512), (16, 1 , 1,512))

**Comment by ttyio** [comment]
@BarryKCL , could you set `input2` batch size also to 1?

**Comment by BarryKCL** [comment]
@ttyio Do you mean dim0 must be batch size?

**Comment by BarryKCL** [comment]
@ttyio I tried permute(1,0,2,3) set input2 batch size also to 1.But it also out of memory.

**Comment by ttyio** [comment]
@BarryKCL dim0 is not necessary batch, 

could you share both the passed static input shape and failed dynamic input shape? thanks

**Comment by BarryKCL** [comment]
static input shape:
                             ys = torch.randint(low=0, high=4813, size=(20,100),dtype=torch.int32).cuda()
                             ymasks = torch.ones((20,100,100)).int().cuda()
                             batch_state = torch.zeros((16,20,99,512),dtype=torch.float32).cuda()
 dynamic input shape:
                                    ys:(1, 1), (1, 1), (1, 1)
                                    ymasks:(1, 1 , 1), (1, 1 , 1), (1, 1 , 1)
                                    batch_state:(16, 1 , 1,512), (16, 1 , 1,512), (16, 1 , 1,512))

**Comment by ttyio** [comment]
@BarryKCL 
oh so you mean pytorch static input shape, not trt static input shape.
How large is the workspace? could you share the onnx file?

**Comment by BarryKCL** [comment]
> @BarryKCL
> oh so you mean pytorch static input shape, not trt static input shape.
> How large is the workspace? could you share the onnx file?
I mean set onnx max static input shape ,can turn onnx to tensorrt engine.
But  set onnx dynamic input shape,turn onnx to tensorrt engine out of memory.
config.max_workspace_size = common.GiB(15)

**Comment by ttyio** [comment]
@BarryKCL , workspace is the temporal memory that kernel used at execution time, we also need other memory like intermediate tensor, weights, etc.. 

Have you tried limit the max_workspace_size ? say 1G workspace?

**Comment by BarryKCL** [comment]
@ttyio The onnx file is send to <ttyio@hotmail.com>,please check

**Comment by BarryKCL** [comment]
> @BarryKCL , workspace is the temporal memory that kernel used at execution time, we also need other memory like intermediate tensor, weights, etc..
> 
> Have you tried limit the max_workspace_size ? say 1G workspace?

Yes,I tried

**Comment by BarryKCL** [comment]
@ttyio 
            config.max_workspace_size = common.GiB(1)
            and set min input,it worked.

**Comment by ttyio** [comment]
Cool, I will close this since the issue solved, thanks

**Comment by BarryKCL** [comment]
@ttyio But min input model is useless.

**Comment by ttyio** [comment]
@BarryKCL , could you try 1G workspace + dynamic batch?

**Comment by BarryKCL** [comment]
1G workspace
2G workspace
4G workspace
also out of memory.
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] WARNING: GPU memory allocation error during getBestTactic: Unsqueeze_1465
[TensorRT] ERROR: Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.

**Comment by ttyio** [comment]
@BarryKCL 
I mean always use 1G workspace and increate the batch size in `profile.set_shape( ... )`

**Comment by BarryKCL** [comment]
@ttyio 
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (396) - Myelin Error in compileGraph: 69 (myelinExceededMemBudget : Exceeded mem budget of 4294967296. Need 18255183872
)
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (396) - Myelin Error in compileGraph: 69 (myelinExceededMemBudget : Exceeded mem budget of 4294967296. Need 18255183872
)

**Comment by BarryKCL** [comment]
@ttyio the min input onnx2trt used T4 14G memory.

**Comment by ttyio** [comment]
@BarryKCL , the error means that the TRT's RNN compiler require around 4G workspace memory to run with given input shape.

Could you take a try on TRT 8.0, we have more optimization in this new build.

**Comment by BarryKCL** [comment]
@ttyio does TensorRT support multi-GPU Onnx2trt build?

**Comment by ttyio** [comment]
@BarryKCL no, you have to breakdown large model by yourself.

**Comment by BarryKCL** [comment]
@ttyio why pytorch inference only need 2G memory,Onnx2trt need huge.

**Comment by ttyio** [comment]
@BarryKCL because we optimized the loop, and require extra workspace to run the optimized subgraph.

**Comment by ttyio** [comment]
Hello @BarryKCL , I want to dig into the large workspace issue, but I see all the 3 inputs has batch in the first dimension in the model , so it seems different compared to what you described in this thread. 


![image](https://user-images.githubusercontent.com/365590/120445422-2d39de80-c3bb-11eb-9722-e096eeb69672.png)

**Comment by ttyio** [comment]
Thanks @BarryKCL , also the `where_170` inputs are not conformable in the model I got from email, we cannot broadcast scalar to a tensor.

Could you elaborate why 7.2.1 solved your problem, did you mean 7.2.1 use less workspace compared to 8.0? 


![image](https://user-images.githubusercontent.com/365590/120459363-b60c4680-c3ca-11eb-8bad-b8c85828dbc1.png)

**Comment by BarryKCL** [comment]
@ttyio We are using C++ TensorRT to optimize a torch net，but got a problem. As for the input data is very large , so we need to remove all the memcpy. We take the data pointer of torch tensor as the input of TRT which is CUDA memory and use the output as a new Tensor’s data pointer. Our input is dynamic, when the input size reaches a certain size, error occurred which is shown “an illegal memory access was encountered”. The error occurs when we print or use the result tensor after TRT inference. I want to ask what could cause this error.Thanks

**Comment by BarryKCL** [comment]
@ttyio Yes,I do not try Tensorrt8.0.But Tensorrt7.2.1 support transform this onnx to tensorrt engine.

**Comment by BarryKCL** [comment]
@ttyio where_170 is min_value = float(-65504.0).
![image](https://user-images.githubusercontent.com/48039828/120474083-53bb4200-c3da-11eb-8e9b-5e10bc2e235b.png)

**Comment by ttyio** [comment]
> @ttyio We are using C++ TensorRT to optimize a torch net，but got a problem. As for the input data is very large , so we need to remove all the memcpy. We take the data pointer of torch tensor as the input of TRT which is CUDA memory and use the output as a new Tensor’s data pointer. Our input is dynamic, when the input size reaches a certain size, error occurred which is shown “an illegal memory access was encountered”. The error occurs when we print or use the result tensor after TRT inference. I want to ask what could cause this error.Thanks

Could you use cuda-memcheck to show more detail like which kernel reported this illegal memory access? thanks

**Comment by ttanzhiqiang** [comment]
https://github.com/ttanzhiqiang/onnx_tensorrt_project

**Comment by nvpohanh** [comment]
@BarryKCL Could you try the latest TRT 8.4 GA release and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
