### ISSUE TITLE
TensorRT inference result for BERT 

### ISSUE THREAD

**Issue by quic-nmorillo** [NVIDIA/TensorRT#1265]
Is there a way to convert the inference result from Sentences/Sec to Samples/Sec?   Most of Nvidia performance metric has been published in either samples/sec or queries/sec for BERT.  Why does TensorRT gives sentences/sec?  

_Question: What is TensorRT?
------------------------
Running inference in 71.507 Sentences/Sec
------------------------
Answer: 'a high performance deep learning inference platform'_

**Comment by ttyio** [comment]
Hello @quic-nmorillo , the `sentences/sec` is the same as `queries/sec`, calculated using 

       batch_size/eval_time_elapsed

see https://github.com/NVIDIA/TensorRT/blob/release/7.2/demo/BERT/inference.py#L218

**Comment by quic-nmorillo** [comment]
@ttyio - Thanks for the answer.   

Hmm, the number doesn't look good compared to what Nvidia has published.   I'm running BERT base, 128 sequence length, fp16 precision.   

To compared to what Nvidia has published, I ran with the bert base 128, int8 and I got 137.79 sentences/sec.   
Compared that to NVidia number for the same network, I'm 1/10th of the number.  Hmm, what did I do wrong? 


BERT-BASE | 2 | 1,098 sequences/sec | 16 sequences/sec/watt | 1.82 | 1x T4 | Supermicro SYS-4029GP-TRT | 21.04-py3 | INT8 | Real (Q&amp;A provided as text input) | TensorRT 7.2 | NVIDIA T4
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
&nbsp; | 8 | 1,757 sequences/sec | 27 sequences/sec/watt | 4.55 | 1x T4 | Supermicro SYS-4029GP-TRT | 21.04-py3 | INT8 | Real (Q&amp;A provided as text input) | TensorRT 7.2 | NVIDIA




https://developer.nvidia.com/deep-learning-performance-training-inference

**Comment by ttyio** [comment]
@quic-nmorillo , we did not use inference.py to measure the perf, this file mainly for functional verification, you can check below link on how to measure perf
https://github.com/NVIDIA/TensorRT/tree/release/7.2/demo/BERT#benchmarking
thanks
