### ISSUE TITLE
What's the difference between trtexec and TensorRT python API

### ISSUE THREAD

**Issue by Chakib08** [NVIDIA/TensorRT#1266]
I am wondering if trtexec and TensorRT python API use the same approach to build TRT engines and run the inference because i've used trtexec with **YOLOv3 Tiny 416x416** (batch size = 16)  with the **_Jetson AGX XAVIER_** and get over 1000 FPS (as NVIDIA Benchmarks) but when i used the python API with the same configuration i got only 700 FPS 

So the question is :
Is TensorRT python API use trtexec too to build engines and run the inference ?

**Comment by ttyio** [comment]
Hello @Chakib08 , python API will call into TRT core (which is written in C++ and CUDA) using pybind https://github.com/NVIDIA/TensorRT/tree/master/python
trtexec direct call into TRT core using C++ API, and it is opensourced in https://github.com/NVIDIA/TensorRT/tree/release/7.2/samples/opensource/trtexec

So they are the same. trtexec support `--loadEngine`, you can check the performance using the engine built from python API.
