### ISSUE TITLE
TRT8.0.0.3 and CUDA11.3 - Missing libmyelin.so.1 library

### ISSUE THREAD

**Issue by quic-nmorillo** [NVIDIA/TensorRT#1268]
Hi

I built a tensorrt container with TRT8.0.0.3 version and cuda11.3.   Inside the container, I tried to issue cmake command but it failed.  I copied the following log:

cmake .. -DTRT_LIB_DIR=$TRT_LIBPATH -DTRT_OUT_DIR=`pwd`/out
_Building for TensorRT version: 7.2.3, library version: 7
...
-- Found TensorRT headers at /workspace/TensorRT/include
-- Find TensorRT libs at /usr/lib/x86_64-linux-gnu/libnvinfer.so;/usr/lib/x86_64-linux-**gnu/libnvinfer_plugin.so;TENSORRT_LIBRARY_MYELIN-NOTFOUND
-- Could NOT find TENSORRT (missing: TENSORRT_LIBRARY) 
ERRORCannot find TensorRT library.**
-- Adding new sample: sample_algorithm_selector
--     - Parsers Used: caffe
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TENSORRT_LIBRARY_MYELIN
    linked by target "nvonnxparser_static" in directory /workspace/TensorRT/parsers/onnx
    linked by target "nvonnxparser" in directory /workspace/TensorRT/parsers/onnx
...
-- Configuring incomplete, errors occurred!
See also "/workspace/TensorRT/build/CMakeFiles/CMakeOutput.log".
See also "/workspace/TensorRT/build/CMakeFiles/CMakeError.log"._

Where does the CMakeLists.txt gets the TRT VERSION from? 

root@0e9dd8d40cef:/workspace/TensorRT/build# echo $TRT_VERSION
8.0.0.3
root@0e9dd8d40cef:/workspace/TensorRT/build# printenv
_CUDNN_VERSION=8.2.0.53
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/workspace/TensorRT/build/out:/usr/lib/x86_64-linux-gnu
HOSTNAME=0e9dd8d40cef
NVIDIA_VISIBLE_DEVICES=all
NCCL_VERSION=2.9.6
PWD=/workspace/TensorRT/build
HOME=/root
TRT_VERSION=8.0.0.3
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
TERM=xterm
CUDA_VERSION=11.3.0
TRT_OSSPATH=/workspace/TensorRT
TRT_LIBPATH=/usr/lib/x86_64-linux-gnu
NVIDIA_DRIVER_CAPABILITIES=compute,utility
SHLVL=1
NVIDIA_REQUIRE_CUDA=cuda>=11.3 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/printenv
OLDPWD=/workspace/TensorRT_
root@0e9dd8d40cef:/workspace/TensorRT/build# 

What happened to my libmyelin.so.1 library with TRT8.0.0.3 & CUDA13.1?  
libmyelin.so.1 => /usr/lib/x86_64-linux-gnu/libmyelin.so.1 (0x00007f0042eb1000

**ldd /usr/src/tensorrt/bin/trtexec**
_linux-vdso.so.1 (0x00007ffdb3df0000)
libnvinfer.so.8 => /usr/lib/x86_64-linux-gnu/libnvinfer.so.8 (0x00007f55e9387000)
libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f55e90ee000)
libnvparsers.so.8 => /usr/lib/x86_64-linux-gnu/libnvparsers.so.8 (0x00007f55e8bac000)
libnvonnxparser.so.8 => /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.8 (0x00007f55e8719000)
libnvinfer_plugin.so.8 => /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.8 (0x00007f55e73ab000)
libcublas.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11 (0x00007f55e036b000)
libcublasLt.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.11 (0x00007f55d478d000)
libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f55d4563000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f55d435f000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f55d4140000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f55d3d33000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f55d3995000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f55d377d000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55d338c000)
libnvrtc.so.11.2 => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc.so.11.2 (0x00007f55d0657000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f55d044f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f560ecfe000)_

**Comment by ttyio** [comment]
Hello @quic-nmorillo , the OSS 8.0 build is not ready yet, we plan to release it in June, thanks

**Comment by ttyio** [comment]
Now the 8.0 OSS is available, closing, thanks!
