### ISSUE TITLE
different result in softamx, by axis

### ISSUE THREAD

**Issue by royinx** [NVIDIA/TensorRT#1270]
My model needs softamx axis=1 which is working smooth in trt6

When I shift the model from 6.0 to 7.0 / 7.1 / 7.2, the wrong result occurred.

I created a one layer softmax model for testing, with input (1,3,4,5), node (softmax axis =1),
I wanna reproduce the result in trt6 , that is 0.3333

Container tested:
|notebook|container|
|:--:|:--:|
|[TensorRT6 notebook ](https://github.com/royinx/trtis_issues/blob/master/trt6.ipynb)|19.12-py3|
|[TensorRT7 notebook ](https://github.com/royinx/trtis_issues/blob/master/trt7.ipynb)|20.09-py3<br/>20.11-py3<br/>21.03-py3|

_Originally posted by @royinx in https://github.com/NVIDIA/TensorRT/issues/399#issuecomment-849407283_

**Comment by ttyio** [comment]
Already solved in https://github.com/NVIDIA/TensorRT/issues/399#issuecomment-850322280, closing this, thanks
