### ISSUE TITLE
TensorRT throws assert and stops during inference, reason unclear

### ISSUE THREAD

**Issue by Jaliborc** [NVIDIA/TensorRT#1272]
## Description
We're currently being unable to get a TensorRT model to do inference. In particular, we are trying to get it to use DirextX structured buffers as input, so that it can interplay with Falcor.

We implemented a Falcor rendering pass that just loads a dummy model into TensorRT and feeds it the CUDA addresses of the structured buffers. However, when we run it, we get:
````cpp
Assertion failed: !mProfiles.empty() || mIsAllDimensionsStatic
C:\source\rtExt\engine.cpp:1885
Aborting...
````

## Environment
**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: 2080 TI
**NVIDIA Driver Version**:  466.47
**CUDA Version**: 11.1
**CUDNN Version**: 8.1.1
**Operating System**: Windows 10

## Relevant Files
Our code is a fork of Falcor:
https://github.com/Snosixtyboo/Falcor/tree/tensor_rt

Relevant code is a single .cpp and .h file pair:
https://github.com/Snosixtyboo/Falcor/blob/tensor_rt/Source/RenderPasses/AdaptiveVRS/Jaliborc/JaliVRS.h
https://github.com/Snosixtyboo/Falcor/blob/tensor_rt/Source/RenderPasses/AdaptiveVRS/Jaliborc/JaliVRS.cpp

## Steps To Reproduce
1. Falcor needs to be installed per its instructions
1. As per Falcor instructions, make a symbolic link of the cuda instalation into Falcor's `.packman/Cuda` folder. However, also make a `.packman/TensorRT` symbolic link.
1. Compile using either DebugD3D12 or ReleaseD3D12 modes
1. Make sure to set a directory as the `FALCOR_MEDIA_FOLDERS` environment variable. Put https://developer.nvidia.com/orca/amazon-lumberyard-bistro under `FALCOR_MEDIA_FOLDERS/Bistro`
1. Download this dummy .onnx model file and place it in the `Source/RenderPasses/AdaptiveVRS/Jaliborc/JaliVRS` directory.
1. Run Mogwai and load the `Mogwai/Data/VRS/bistro.py` script. It just loads the scene and the rendering pipeline which includes the rendering pass in question.

[4channel.zip](https://github.com/NVIDIA/TensorRT/files/6556236/4channel.zip)

**Comment by ttyio** [comment]
Hello @Jaliborc sorry for the late response, 

could you try make `ICudaEngine* engine` also class member of your class because the `ExecutionContext` would access some resources in it and we need make sure its life time longer than `ExecutionContext`. 

Thanks

**Comment by Jaliborc** [comment]
That was it! Thank you very much for the help.
