### ISSUE TITLE
TensorRT don't support torch.cumsum

### ISSUE THREAD

**Issue by wxyhv** [NVIDIA/TensorRT#1275]
## Description
when I use TensorRT7.2.3.4 to build engine, I encounter the following ERROR:

input_shape: [2, 16]
builder.max_workspace_size: 268435456
Loading ONNX file from path ./encoder.onnx...
Beginning ONNX file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
**[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin CumSum version 1**
**ERROR: Failed to parse the ONNX file.
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"**

It means that tensorrt don't support torch.cumsum(tensor, dim), how to solve it? It is difficult to implement custom cumsum plugin, who can help me? Thanks!

**Comment by ttyio** [comment]
Hello @wxyhv this is supported in 8.0, see https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html, thanks
