### ISSUE TITLE
How can i get tensorrt4.x lib?

### ISSUE THREAD

**Issue by asdf2kr** [NVIDIA/TensorRT#1276]
I want to use the built tensorrt 4.x using cuda 8.0 and cudnn 6 on tx2.

Can I get the built library or full code from the above mentioned environment?

**Comment by pmixer** [comment]
https://developer.nvidia.com/nvidia-tensorrt-download

**Comment by ttyio** [comment]
Hello @asdf2kr , TRT for l4t is delivered inside the Jetpack package.

https://developer.nvidia.com/embedded/jetpack

**Comment by asdf2kr** [comment]
Hello @ttyio Thanks for your reply

I want to upgrade only the TensorRT4.0 version from Jetpack 3.1.
So i'm looking for a library that supports TensorRT 4.0, CUDA 8.0 and cudnn 6.0. 

JetPack 3.1 has TensorRT 2.1, CUDA8.0, CUDNN 6.0 (https://developer.nvidia.com/embedded/jetpack-3_1)
JetPack 3.3 has TensorRT 4.0, but supports CUDA 9.0 and CUDNN 7.1.5  (https://developer.nvidia.com/embedded/jetpack-3_3)

**Comment by ttyio** [comment]
Sorry @asdf2kr , there is no official support for this cross usage because trt has dependency on cuda, cudnn libraries .

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question.
