### ISSUE TITLE
ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin Switch version 1

### ISSUE THREAD

**Issue by LW-CVer** [NVIDIA/TensorRT#1278]
ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin Switch version 1
ERROR: builtin_op_importers.cpp:3661 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

not support Switch op？

**Comment by ttyio** [comment]
Hello @LW-CVer, I did not see `switch` from the ONNX spec.
https://github.com/onnx/onnx/blob/master/docs/Operators.md

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
