### ISSUE TITLE
Running a fully FP16 precision engine from a FP32 ONNX model in TensorRT  

### ISSUE THREAD

**Issue by ju9379** [NVIDIA/TensorRT#1280]
Hi, 

I created a network definition by importing a ONNX model using the C++ Parser API.
The data type of the ONNX model is FP32 precision. 

For better performance, I triggered mixed precision with the following flag:
`config->setFlag(BuilderFlag::kFP16);`
This enables TensorRT to use fp16 reduced  computational precision kernels (if faster).
The documentation precise that "Weights can be specified in FP16 or FP32, and they will be converted automatically to the appropriate precision for the computation."
Network inputs and outputs are still in FP32. 

I would like to compare the mixed precision performance to a fully FP16 inference performance. 
Documentation says :
> The `BuilderFlag::kFP16` flag allows, but does not guarantee, that 16-bit kernels will be used when building the engine. You can choose to force 16-bit precision by setting the following builder flag: `config->setFlag(BuilderFlag::kSTRICT_TYPES)`

1. Will the weights be converted to FP16 at the beginning once and for all ?
2. I need to feed the network with FP16 input values but the function `getBindingDataType `
of the ICudaEngine created is still FP32. How to change that ? 
3. What is the correct procedure to run in fully FP16 a TensorRT engine? 

Thanks in advance,
Ju

**Comment by ttyio** [comment]
Hello @ju9379 ,
1. The convert to FP16 weights is done in build stage.
2. Could you try reformatFreeIO, check sample https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleReformatFreeIO
3. Use `BuildConfig::kSTRICT_TYPES` https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#abdc74c40fe7a0c3d05d2caeccfbc29c1ad3ff8ff39475957d8676c2cda337add7, and explicitly set the `ILayer::setPrecision(kFP16)` and `ILayer::setOutputType(idx, kFP16)`, but this will produce a engine not as fast as what you get now

Thanks

**Comment by ju9379** [comment]
Hi @ttyio,
Thank you for your answer. 
Please, could you explain to me why using a fully FP16 engine would be slower than a FP32 engine with mixed precison enabled ?
I thought a fully FP16 engine would be faster ...
Thanks in advance

**Comment by ttyio** [comment]
Sorry @ju9379 , I need clarify that we <b>might</b> get a slower engine. Because for the `BuildConfig::kSTRICT_TYPES`, TRT will consider the data type restriction, while without this option, TRT will only try to find a fastest execution path, without any data type restriction.

**Comment by ju9379** [comment]
Hi @ttyio ,
Thanks again for you answer.
So, TensorRT has more flexibility in mixed precision without the kSTRICT_TYPES flag. 
But according to you, why typically  FP16*FP16=>FP32 would be faster than FP16*FP16=>FP16 ?

**Comment by ttyio** [comment]
Hello @ju9379 , not typically, but in some of the cases, 
e.g, the next layer is an plugin layer, and the author only implemented FP32 kernels, then if the first layer output FP16, then there is reformat layer needed to do the type transformation.
e.g, tanh.approx.f32 is faster than fp16 tanh on Turing+

**Comment by ju9379** [comment]
Thanks @ttyio, it is clear for me
