### ISSUE TITLE
Extracting features from the classification model

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [NVIDIA/TensorRT#1282]
## Description

I get input and output bindings from the trt engine, however i want to extract features from the layer which is prior to prediction layer. Any code sample for the same?

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
Hello @VeeranjaneyuluToka , have you tried first check `num_layers`, and use `get_layer` to find out the layer before last, and use `mark_output` to mark the output of this layer as network output.
There is no existing code but we have a doc about the functions that I mentioned.
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Network.html#tensorrt.INetworkDefinition.mark_output
Thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
