### ISSUE TITLE
How to build 3D tensor with c++ in Tensorrt

### ISSUE THREAD

**Issue by wangzhenlin123** [NVIDIA/TensorRT#1283]
I try to inferent 3dcnn model with tensorrt，but i have no idea adout how to build 3d tensor in tensorrt with c++, could you provide some example to it?

**Comment by ttyio** [comment]
Hello @wangzhenlin123 , tensor support at 8d tensor at most.  The n-d tensor are the same, and are you asking for 3d conv? You can use `addConvolutionNd` to add it. Sorry there is no existing sample that I am aware.

**Comment by wangzhenlin123** [comment]
Forgive me for my unclear explanation，for example：“cudaMemcpyAsync(buffers[inputIndex], input, batchSize *INPUT_SIZE * sizeof(float), cudaMemcpyHostToDevice, stream)”  We can use OpenCV to read a 2D Mat graph and put it in the Buffer, but， In the case of 3D, is it possible to build the 3D Tensorr input by reading multiple 2D images in succession and then placing them in the Buffer one by one？

**Comment by wangzhenlin123** [comment]
Forgive me for my unclear explanation，for example：“cudaMemcpyAsync(buffers[inputIndex], input, batchSize *INPUT_SIZE * sizeof(float), cudaMemcpyHostToDevice, stream)” We can use OpenCV to read a 2D Mat graph and put it in the Buffer, but， In the case of 3D, is it possible to build the 3D Tensorr input by reading multiple 2D images in succession and then placing them in the Buffer one by one？3D is very important to me because I work with medical 3D images .

**Comment by ttyio** [comment]
Hello @wangzhenlin123 , yes it is the same, we can first check the input layout of your network, allocate GPU buffer has the same size, and finally use cudaMemcpyAsync to initialize the content of the GPU buffer. Did you hit any issue in doing so? thanks

**Comment by wangzhenlin123** [comment]
I haven't tried yet，just Do some technical advice first。

**Comment by ttyio** [comment]
Thanks @wangzhenlin123 , closing, please reopen if you have more issues, thanks
