### ISSUE TITLE
Question about PTQ and INT8 inference with ONNX model

### ISSUE THREAD

**Issue by gaizerik** [NVIDIA/TensorRT#1285]
## Description
Actually, I think this is not a bug reporting, I got  question about pytorch PTQ and tensorRT inferencing.
What I want to do is as below,(like many other guys..)
With torch 1.8.0, do train -> using pytorch_quantization, do PTQ(static calibration) -> export ONNX model -> With jetson AGX Xaivier & TensorRT, do inference with INT8 tensorcore support
Now I got ONNX parsing error as below like other guys did, 
```
[TensorRT] VERBOSE: ModelImporter.cpp:125: DequantizeLinear_11 [DequantizeLinear] inputs: [845 -> (16, 3, 3, 3)], [846 -> ()], [847 -> ()],
[TensorRT] VERBOSE: ImporterContext.hpp:116: Registering tensor: 848 for ONNX tensor: 848
[TensorRT] VERBOSE: ModelImporter.cpp:179: DequantizeLinear_11 [DequantizeLinear] outputs: [848 -> (16, 3, 3, 3)],
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: Conv_12 [Conv]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 842
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 848
[TensorRT] VERBOSE: ModelImporter.cpp:125: Conv_12 [Conv] inputs: [842 -> (1, 3, 512, 512)], [848 -> (16, 3, 3, 3)],
[TensorRT] VERBOSE: Kernel weights are not set yet. Kernel weights must be set using setInput(1, kernel_tensor) API call.
[TensorRT] ERROR: Parameter check failed at: ../builder/Layers.cpp::setInput::555, condition: mNetwork->hasExplicitPrecision() ? index <= 1 : index <= 0
[TensorRT] VERBOSE: ImporterContext.hpp:141: Registering layer: Conv_12 for ONNX node: Conv_12
[TensorRT] ERROR: Conv_12: kernel weights has count 0 but 432 was expected
[TensorRT] ERROR: Conv_12: count of 0 weights in kernel, but kernel dimensions (3,3) with 3 input channels, 16 output channels and 1 groups were specified. Expected Weights count is 3 * 3*3 * 16 / 1 = 432
```
I have bit of confusing points after searching issues.
In my case,
1. I got FP32 torch model and weights.
2. I did PTQ & exporting ONNX model as "https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html" example guided.
  --> I got ①PTQ calibrated weights and ②onnx graph.
I can see amaxs, which is fake quantization information in ①PTQ calibrated weights as below.
```
QuantConv2d(  3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False
  (_input_quantizer): TensorQuantizer(8bit narrow fake per-tensor amax=0.9995 calibrator=HistogramCalibrator scale=1.0 quant)
  (_weight_quantizer): TensorQuantizer(8bit narrow fake per-tensor amax=1.7110 calibrator=HistogramCalibrator scale=1.0 quant))
```
and I can see scales in ②onnx graph (I think amax can be calculated from scale like 127×sclae, right?)
https://github.com/gaizerik/img/blob/main/Screenshot.jpg

My question is, 
You've mentioned amax as below. (amax only in QAT?)
https://github.com/NVIDIA/TensorRT/issues/994#issuecomment-757809960
> Hello @ShiinaMitsuki ,
**a_max is only computed after QAT training,** and we need fake_quant to do this, ...

and the BERT sample code, there is tensorRT calibrator when using INT8 mode.
According to this, do I have to do something more before making parsing function for ONNX model? 
Or, is the calibration result from pytorch_quantization package is useless with 7.x version, and to use INT8 inferencing, do I have to use tensorRT calibrator?
 
## Environment
Jetson AGX Xavier with jetpack 4.5
**TensorRT Version**: 7.1.3.0
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by Ricardosuzaku** [comment]
TensorRT 7+ can not parse pytorch_quantization onnx model, you should update TensorRT to 8.0, I do and I succeed.
see https://github.com/NVIDIA/TensorRT/issues/994.

**Comment by gaizerik** [comment]
> TensorRT 7+ can not parse pytorch_quantization onnx model, you should update TensorRT to 8.0, I do and I succeed.
> see #994.

Hi @Ricardosuzaku , thanks for advise. 
Yes, I know that TRT7.x version does not support direct parsing from ONNX QDQ inserted graph.
Unfortunately, I have to deploy my model on Jetson AGX Xavier, which support up to 7.1.3 version. 
So, I need to know the way converting QDQ scale information to TRT-compatible information for INT8 inference.
Seems that there is a way according to #1144.

Actually, in #994 @ttyio refered BERT builder set_output_range example.
But according to code, I need amax to set dynamic range. 
Is there any way to convert QDQ scale to amax?

**Comment by ttyio** [comment]
Hello @gaizerik , Could you check the `y_scale` attribute in the `QuantizeLinear` and use `127.f * y_scale` as the amax? thanks

**Comment by gaizerik** [comment]
> Hello @gaizerik , Could you check the `y_scale` attribute in the `QuantizeLinear` and use `127.f * y_scale` as the amax? thanks

Hi, @ttyio, thank you very much for your reply. I'll try it.
And as you've mentioned, TRT 7.x OnnxParser cannot parse torch onnx exported graph properly, which means I have to make ①weight / scale information dictionary generation code and ②network build code from onnx graph not using trt.OnnxParser like BERT example, is it right? 

Actually, I got parsing error when I try to parse model using trt.OnnxParser, but there are no error for some other QuantizeLinear layers.(below part is MobileNetV3 Squeeze and Excitation block)
> Error case
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: QuantizeLinear_198 [QuantizeLinear]
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1024
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1025
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 1026
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: QuantizeLinear_198 [QuantizeLinear] **inputs: [1024 -> (-1, -1)]**, [1025 -> ()], [1026 -> ()], 
[TensorRT] ERROR: QuantizeLinear_198_quantize_scale_node: at least 4 dimensions are required for input.
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:120: Registering tensor: 1027 for ONNX tensor: 1027
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: QuantizeLinear_198 [QuantizeLinear] outputs: [1027 -> ()], 
<img src="https://github.com/gaizerik/img/blob/main/s1.jpg" width = 300>

> No error case
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:107: Parsing node: QuantizeLinear_69 [QuantizeLinear]
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 895
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 896
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:123: Searching for input: 897
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:129: QuantizeLinear_69 [QuantizeLinear] **inputs: [895 -> (1, 16, 256, 256)]**, [896 -> ()], [897 -> ()], 
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ImporterContext.hpp:120: Registering tensor: 898 for ONNX tensor: 898
[TensorRT] VERBOSE: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:183: QuantizeLinear_69 [QuantizeLinear] outputs: [898 -> (1, 16, 256, 256)], 
<img src="https://github.com/gaizerik/img/blob/main/s2.jpg" width = 300>

**Comment by ttyio** [comment]
Hello @gaizerik , yes TRT 7.x failed to handle the Q/DQ node, so for the network importing, you need either import an ONNX without Q/DQ, or manually built your network using TRT native API like we do in demobert (https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py).

For the setDynamicRange part, probably you need offline process the ONNX with Q/DQ node, and get `yscale * 127.f` for all the activations (weights is auto calibrated by TRT in PTQ mode)

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
