### ISSUE TITLE
C++ TensorRT Inference got " CUDA error: an illegal memory access was encountered"

### ISSUE THREAD

**Issue by BarryKCL** [NVIDIA/TensorRT#1287]
We are using C++ TensorRT to optimize a torch net，but got a problem. As for the input data is very large , so we need to remove all the memcpy. We take the data pointer of torch tensor as the input of TRT which is CUDA memory and use the output as a new Tensor’s data pointer. Our input is dynamic, when the input size reaches a certain size, error occurred which is shown “an illegal memory access was encountered”. The error occurs when we print or use the result tensor after TRT inference. I want to ask what could cause this error.Thanks

**Comment by ttyio** [comment]
Hello @BarryKCL  have you checked if the torch tensor is contiguous? 
https://pytorch.org/docs/stable/generated/torch.Tensor.contiguous.html

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
