### ISSUE TITLE
volta_scudnn while Gpu is Turing

### ISSUE THREAD

**Issue by callbarian** [NVIDIA/TensorRT#1288]
## Description

Nsight System tells the inference is on volta_scudnn on cuda, or trt_volta_scudnn on tensorrt.
The Gpu running is RTX 2080Ti, which is Turing.

What might be the issue?

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: RTX 2080 Ti
**NVIDIA Driver Version**:  466
**CUDA Version**:  11.2
**CUDNN Version**:  8.2
**Operating System**:  Windows 10 x64
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
Hello @callbarian , volta is the minimal SM arch requirement. It is fine to use these kernels.

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
