### ISSUE TITLE
Random Inference Faults in Release Build

### ISSUE THREAD

**Issue by OrcunCanDeniz** [NVIDIA/TensorRT#1290]
## Description

While my code is in debug mode tensorrt engine works as expected. But if the inference code is compiled in release mode the engine sometimes(randomly) fails to detect anything, yielding empty prediction array. I'm sure that there is nothing in code that I enable or disable explicitly with respect to build mode.

## Environment

**TensorRT Version**: 7.0.0.11
**NVIDIA GPU**:  RTX 2070
**NVIDIA Driver Version**:  460
**CUDA Version**:  10.0
**CUDNN Version**:  7.6.5
**Operating System**:  Ubuntu 18.04

## Relevant Files

[onnx file ](https://drive.google.com/ucid=1ZYoBqVynmO5kKntyN56GEbELRpuXG8Ym) file i used to create engine.

**Comment by OtisZZ** [comment]
same issue, smoetimes got an inference error

**Comment by ttyio** [comment]
Hello @OrcunCanDeniz , have you tried latest 8.0 trt? thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
