### ISSUE TITLE
DefaultLogger INVALID_ARGUMENT: Cannot set empty memory

### ISSUE THREAD

**Issue by pimonteiro** [NVIDIA/TensorRT#1294]
## Description
My converted model from tensorflow to TensorRT keeps giving me warnings 

2021-06-07 12:41:53.232251: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger INVALID_ARGUMENT: Cannot set empty memory.

which increased the time required to finish.

## Environment

**TensorRT Version**:  7.2.3
**NVIDIA GPU**:  RTX 3080 10GB
**NVIDIA Driver Version**: 465.31 
**CUDA Version**: 11.3
**CUDNN Version**: 8
**Operating System**: Pop-OS 
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 2.4.0
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: Docker container (nvcr.io/nvidia/tensorrt:21.05-py3)

## Relevant Files

Please check  https://github.com/pimonteiro/Semantic-Segmentation-Thesis/blob/main/src/tensorrt_converter.py, for the converter from tensorflow to TRT and https://github.com/pimonteiro/Semantic-Segmentation-Thesis/blob/main/src/evaluate.py for the script that generates the warnings.

## Steps To Reproduce

Simply convert the model and run it with a batch of zeros with shape (X, 375, 513, 3). The number of batches does not change the outcome.

![Screenshot from 2021-06-07 12-47-58](https://user-images.githubusercontent.com/25423909/121011696-cdfb1600-c78e-11eb-97b3-77901872a6bc.png)
As we can see, the GPU memory does not get maxed out and I still get the warnings. The converter was used with the default parameters.

**Comment by Tailwhip** [comment]
Same problem :/

**Comment by andrusza2** [comment]
I have the same bug with TensorFlow 2.5 (although my model seems to work fine even though the error was printed). 
With TensorFlow 2.4 (I tested both - TF image from NGC and manual installation with pip) this problem does not occur.

**Comment by pimonteiro** [comment]
> I have the same bug with TensorFlow 2.5 (although my model seems to work fine even though the error was printed).
> With TensorFlow 2.4 (I tested both - TF image from NGC and manual installation with pip) this problem does not occur.

The thing is I am also using Tensorflow 2.4 and, while the model does infer as needed, it takes a long time processing large long ammounts of data using batches. I will retry by previously building the model on TRT with an input function (something I did not use so far, letting the model build on the first inference) and only using a batch of 1 image. I will post here any further  development.

**Comment by andrusza2** [comment]
> edit: is it possible for you to specify how you did the conversion of your model? Parameters, settings and environment of development used could help tracking the problem.

Sure, no problem.

My models were converted from keras as in the guide for TensorFlow 2.0 (saved_model and `TrtGraphConverterV2`). The conversion was done with the default parameters. I did the actual conversion some time ago - it was on the NGC 20.12 image (so it was TF 2.3.1 with TRT 7.2.2 linked and TRT 7.2.2 loaded).

I have tested and used these converted models without problems in the following configurations:
- NGC TF 20.12, TensorFlow 2.3.1, TRT linked 7.2.2, TRT loaded 7.2.2
- NGC TF 21.05, Tensorflow 2.4.0, TRT linked 7.2.3, TRT loaded 7.2.3
- Cuda 11.3 base image, TensorFlow 2.4.1 (from pip), TRT linked 7.1.3, TRT loaded 7.2.3

The problem with the `INVALID_ARGUMENT: Cannot set empty memory` error appeared when I tried to use TF 2.5 (I was using the exact same code that worked with no problem in previous tests).

When it comes to performance - I only tested the inference with batch 1 and in this case I didn’t notice any slowdown despite the error.

**Comment by ttyio** [comment]
Hello @pimonteiro , this is fixed in TRT 8.0, and please wait for TF container that has integrated TRT8.0, thanks!

**Comment by ttyio** [comment]
Here is the TF container that with 8.0 TRT https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_21-07.html#rel_21-07

closing, please reopen if you still have question, thanks!

**Comment by pimonteiro** [comment]
> Hey @pimonteiro,
> 
> I am also getting this error at inference time. I also noticed that this is consuming way more gpu-memory than usual.
> 
> ## Environment
> **TensorRT Version**: 7.2.3-1
> **GPU Type**: NVIDIA GeForce RTX 3080
> **Nvidia Driver Version**: 470.57.02
> **CUDA Version**: 11.1
> **CUDNN Version**: 8.1.0
> **Operating System + Version**: Ubuntu 18.04.5 LTS
> **Python Version (if applicable)**: 3.9.6
> **TensorFlow Version (if applicable)**: 2.5.0
> **PyTorch Version (if applicable)**: NA
> **Baremetal or Container (if container which image + tag)**: NA
> 
> Can you tell me how did you install tensorrt? Did you follow the steps mentioned in [tf-docs](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_110)?
> 
> I want to figure out if this error is causing the memory issue.

Hi,

No, I attempted to try TensorRT following those, but at the time there was an incompatibility of my system to install the latest version of it.
So I decided to use a docker container with all the necessary packages, provided by nvidia. As mentioned on a previous reply to this thread by @ttyio , this bug was fixed on the latest version of TensorRT. Use the container indicated by him. I haven't tried it myself, as the work I was doing is finished, but It would be great to have your feedback after using it. Good luck!

**Comment by memr5** [comment]
Actually, as of now we are not planning to go with the container. Does TF2.5 supports the latest TensorRT? Because when I try to convert a model to TensorRT format in TF2.5, it throws an error that it could't find **libnvinfer.so.7**. Which goes away If I use TensorRT7.

**Comment by pimonteiro** [comment]
> Hey @pimonteiro,
> 
> Actually, as of now we are not planning to go with the container. Does TF2.5 supports the latest TensorRT? Because when I try to convert a model to TensorRT format in TF2.5, it throws an error that it could't find **libnvinfer.so.7**. Which goes away If I use TensorRT7.

Any specific reason why not to use the container? I did not noticed any type of bottleneck on any of my benchmarks. As for the error, if I'm not mistaken I suffered the same, hence the reason I downgraded to TensorRT7. The whole installation was a mess for it, in the end, not to work as intended. Going with the container should have been my first option to be honest.

**Comment by memr5** [comment]
Thanks, 

There is no specific reason to not to use container. But that would be the last priority. 
Anyway, will try using the container to check if the memory issue is still there or not.
