### ISSUE TITLE
How to install TensorRT OSS on Jetson TX2?

### ISSUE THREAD

**Issue by rsj007** [NVIDIA/TensorRT#1296]
## Description

I want to install tensorrt OSS on my Jetson TX2 and add a grid_sample tensorrt plugin. When I run the command  "./docker/build.sh --file docker/ubuntu-cross-aarch64.Dockerfile --tag tensorrt-cross-jetpack --cuda 10.2", it appears that my tx2 doesn't have enough disk space.
I wonder how much space I need to install Tensorrt OSS. I only have 1GB left space.

Thanks a lot!!

## Environment
TX2+ ubuntu18.04

**Comment by sksenthilkumar** [comment]
You can follow the steps in this blog to build OSS on jetson devices:
https://docs.nvidia.com/metropolis/TLT/tlt-user-guide/text/instance_segmentation/mask_rcnn.html#tensorrt-open-source-software-oss

**Comment by rsj007** [comment]
> You can follow the steps in this blog to build OSS on jetson devices:
> https://docs.nvidia.com/metropolis/TLT/tlt-user-guide/text/instance_segmentation/mask_rcnn.html#tensorrt-open-source-software-oss

Thanks very much. I will try it.
