### ISSUE TITLE
unable to set up build environment

### ISSUE THREAD

**Issue by skywo1f** [NVIDIA/TensorRT#1297]
Not sure if the instructions are deprecated:
~/Downloads/TensorRT-8.0.0.3$ ./docker/build.sh --file docker/ubuntu-18.04.Dockerfile --tag tensorrt-ubuntu-1804 --cuda 11.1
bash: ./docker/build.sh: No such file or directory

So I updated them for my system:
~/Downloads/TensorRT-8.0.0.3$ docker build --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu-2004 --cuda 11.2
unknown flag: --cuda
See 'docker build --help'.

but it still didn't work. Any ideas?

**Comment by ttyio** [comment]
Hello @skywo1f ,
could you follow https://github.com/NVIDIA/TensorRT/tree/release/7.2#generate-the-tensorrt-oss-build-container? thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
