### ISSUE TITLE
Unable to run sample programs

### ISSUE THREAD

**Issue by ANSHUMAN87** [NVIDIA/TensorRT#13]
I am trying to execute sample: sample_onnx_mnist

But i get an exception @https://github.com/NVIDIA/TensorRT/blob/0d36bbb29732cdefbed6a60b51039ea1fa747742/samples/opensource/sampleOnnxMNIST/sampleOnnxMNIST.cpp#L244

There is no buffer with name "Input3" which is set by default.
I downloaded model from (https://github.com/onnx/models/tree/master/mnist )

Below i have attached output log of model parsing:
![image](https://user-images.githubusercontent.com/32511895/60004422-34fa8f80-968a-11e9-9e24-d1ee8639d035.png)

Here i can not see any node with name "Input3" and output node name also is different.

Would you please help me resolve the issue, TIA!

**Comment by rajeevsrao** [comment]
Please download the model for ONNX v1.3 (opset 8), not the older ones.
https://onnxzoo.blob.core.windows.net/models/opset_8/mnist/mnist.tar.gz

A copy of mnist.onnx, alongwith the requires test images can be found in the TensorRT binary installation's data/mnist directory.

**Comment by ANSHUMAN87** [comment]
@rajeevsrao : Thank you! Now it works fine with v1.3 model. With v1.0, i modified some code and able to execute, but the prediction is wrong. Would you be able to throw some light on it. TIA!

**Comment by rmccorm4** [comment]
Hi @ANSHUMAN87, can you try this again with the TensorRT 6.x release and see if your issue still persists?

**Comment by rmccorm4** [comment]
Closing since no response. Feel free to open a new issue or ask to reopen this one.
