### ISSUE TITLE
Does it support grid_sample operation?

### ISSUE THREAD

**Issue by donnyyou** [NVIDIA/TensorRT#130]
https://pytorch.org/docs/stable/nn.functional.html?highlight=grid_sample#torch.nn.functional.grid_sample

**Comment by rmccorm4** [comment]
Hi @donnyyou,

It looks like it's not on the list of supported ops yet: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#supported-ops

However, you can implement a plugin layer for the op if you need it: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#extending

**Comment by hersh92** [comment]
Hi @donnyyou , did you end up implementing your own custom ops for translating grid-sample from pytorch -> onnx -> TensorRT? If so, can you point me to the code? If not, how did you work around this issue?

**Comment by yingsiq** [comment]
+1

**Comment by yangfh2004** [comment]
+1

**Comment by asimukaye** [comment]
+1

**Comment by long2double** [comment]
+1

**Comment by atztao** [comment]
+1

**Comment by billaram** [comment]
+1
