### ISSUE TITLE
bash: ../0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch: No such file or directory

### ISSUE THREAD

**Issue by akshayacharya97** [NVIDIA/TensorRT#1309]
I am not able to find the patch file ot convert the model. I am using Jetson Xavier NX. I have completed all the steps as shown in the Readme file. However after i checkout into the 3deaec5 branch, I am not able to find the patch file. Where is it and how do i convert my keras model? I am following the Segmentation tutorial.

**Comment by ttyio** [comment]
Hello @akshayacharya97 , are you looking for https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffMaskRCNN/converted/0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch? thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
