### ISSUE TITLE
If the same context run on different CUDA streams in trtexec multiple streams examples?

### ISSUE THREAD

**Issue by nannanmath** [NVIDIA/TensorRT#1311]
When I read the code of `sampleInference.cpp`, I feel that if there is only one thread with multiple streams, the code following may result in one context will run on different streams?

https://github.com/NVIDIA/TensorRT/blob/b2d60b6e1003f973983903de154a274b569006b8/samples/common/sampleInference.cpp#L515-L524

**Comment by BraveLii** [comment]
@rajeevsrao  i am confuded too

**Comment by nvpohanh** [comment]
Yes, and I fixed the issue in TRT 8.4 as Oxana mentioned. :) Thanks for reporting this. Closing this for now.
