### ISSUE TITLE
Kernel weights are not set yet. Kernel weights must be set using setInput(1, kernel_tensor) API call.

### ISSUE THREAD

**Issue by banjuanshua** [NVIDIA/TensorRT#1314]
When use 
```

convLayer = net->addConvolutionNd(*inputs[0],
                                  static_cast<int>((conv.num_output())),
                                  nvinfer1::DimsHW{param.kernel_h,
                                                   param.kernel_w},
                                  conv_weight,
                                  bias_weight);
```

I got
Kernel weights are not set yet. Kernel weights must be set using setInput(1, kernel_tensor) API call.

Should I set input in every addconvolution Layer? and HOW?

**Comment by ttyio** [comment]
@banjuanshua ,

you can pass dummy kernel weights like this if you want to call setInput(1, ...) later.

       auto kernel_weights = nvinfer1::Weights{nvinfer1::DataType::kFLOAT, nullptr, 0};

FYI, we can follow `conv` in onnx2trt in https://github.com/onnx/onnx-tensorrt/blob/8fea430fc1ad452085add61b04045a9efbf2b981/builtin_op_importers.cpp#L519
