### ISSUE TITLE
Assertion Error in getSupportedFormats: 0 (!formats.empty(), when converting onnx to tensorrt

### ISSUE THREAD

**Issue by v-qjqs** [NVIDIA/TensorRT#1315]
## Description
When converting my exported onnx model (which contains my customized tensorrt plugin) to tensort, I got the following error:
`[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (2032) - Assertion Error in getSupportedFormats: 0 (!formats.empty())`. 
For more details about the verbose log, see the below:
![WXWorkCapture_16241967018763](https://user-images.githubusercontent.com/34116221/122676545-24496980-d211-11eb-8307-6f294925406b.png)

Please  help me, thanks very much. 

## Environment

**TensorRT Version**: 7.2.1.6
**NVIDIA GPU**: GeForce GTX 1660
**NVIDIA Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.5
**Operating System**: Ubuntu 16.04
**Python Version (if applicable)**: 3.7.10
**PyTorch Version (if applicable)**: 1.6+cuda102

**Comment by qjqfl** [comment]
Hi, Any comments?

**Comment by v-qjqs** [comment]
Hi, any comments?

**Comment by ttyio** [comment]
@v-qjqs , Is this error only occur when the network contains your plugin? If you could you check your `supportsFormatCombination` implementation in your plugin, thanks!

**Comment by qjqfl** [comment]
Hi @ttyio, thanks for your reply!
Yes, this error only occur when the network contains my customized `cumsum` plugin, which use 'x' and 'axis' as it's inputs. The following is the implementation of my `supportsFormatCombination`, I'm not sure how to write the dtype and format for `axis`.
Looking forward to your replies!

**Comment by v-qjqs** [comment]
Hi @ttyio, thanks for your reply!
Yes, this error only occur when the network contains my customized `cumsum` plugin. The plugin uses `x` and `axis` as it's inputs:`y=cumsum(x,axis)`, and the following is the implementation of my `supportsFormatCombination`, but I'm not sure about how to handle the dtype and format for `axis`:
![issue_cumsum](https://user-images.githubusercontent.com/83416752/124605623-b0f55800-de9e-11eb-862e-2957b94cf490.png)

Looking forward to your replies!

**Comment by v-qjqs** [comment]
Hi @ttyio, thanks for your kind reply. 
Yes `CumSum` is already supported in trt8, while not for for trt7.2, and I need to use trt7.2 in my experiments.

**Comment by ttyio** [comment]
Hello @v-qjqs , yes you can set breakpoint or print all the coming datatype, layout in the `supportsFormatCombination` API.

Also, you could take a try to copy the cumsum from 8.0 parser to 7.2, I don't think there is TRT core part change for the `cumsum` implementation, https://github.com/onnx/onnx-tensorrt/blob/8fea430fc1ad452085add61b04045a9efbf2b981/builtin_op_importers.cpp#L872

Thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
