### ISSUE TITLE
Does RTX3090 generated trt engine can run on A100? They all Ampare arch

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#1318]
Does RTX3090 generated trt engine can run on A100? They all Ampare arch

**Comment by jinfagang** [comment]
Suppose on same machine, 2 types cards.

**Comment by ttyio** [comment]
@jinfagang , no, their compute capability is different.

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
