### ISSUE TITLE
[TRT] UffParser: Validator error: mrcnn_detection_bboxes: Unsupported operation _SpecialSlice_TRT &&&& FAILED TensorRT.sample_maskrcnn # ./build/out/sample_uff_maskRCNN -d TensorRT/data

### ISSUE THREAD

**Issue by MLcoder1** [NVIDIA/TensorRT#132]
I get an error when I try to run MaskRCNN as below:

<img width="1145" alt="1" src="https://user-images.githubusercontent.com/55478964/65420046-cd391980-de1d-11e9-97d5-8601a6229387.png">

I have installed libnvinfer 6 also:

**$ apt list --installed | grep -i -e nvinfer -e nvparser** 
It gives the following output:

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
libnvinfer-plugin-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
libnvinfer-plugin6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
libnvinfer5/unknown,unknown,now 5.1.5-1+cuda10.1 amd64 [installed]
libnvinfer6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
libnvparsers-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
libnvparsers6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed,automatic]
python-libnvinfer/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
python-libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
python3-libnvinfer/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
python3-libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
```

**Comment by SongXia84** [comment]
**Got same error!**
ubuntu14.04+cuda9.0+tensorRT6.0.1.5 +tensorflow1.12.0.


**Another issue is:**
When use tensorflow 1.14.0, I can not convert the h5 model to the UFF model.

    File_ "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/converter_functions.py", line 40, in convert_add
        uff_graph.binary(inputs[0], inputs[1], 'add', name)
    IndexError: list index out of range

**Comment by fuman5000** [comment]
I get the same error as SongXia84.

**Comment by dssdyx** [comment]
I think it's the problem that exe cannot link libnvinfer_plugin.so correctly.

**Comment by dssdyx** [comment]
I mean we have to cmake and make TensorRT source as what tutorial says, otherwise it will result in some strange errors...

**Comment by MLcoder1** [comment]
The problem persists even after cmake and make. :(

**Comment by dssdyx** [comment]
> The problem persists even after cmake and make. :(

If you have install TensorRT before you try this sample , you may fail to build and run it. Because in your computer there has been a library called libnvinfer_plugin.so without the needed plugins in this sample.So, I think maybe you should reinstall TensorRT. At least, don't let the exe link to wrong .so

**Comment by rtrobin** [comment]
I downgraded keras to 2.1.6. It could convert model to uff successfully. Hope it could help anyone here. @SongXia84 @fuman5000

**Comment by ShawnNew** [comment]
> I downgraded keras to 2.1.6. It could convert model to uff successfully. Hope it could help anyone here. @SongXia84 @fuman5000

I have Keras version of 2.1.3 as shown in the following picture.
![image](https://user-images.githubusercontent.com/21559339/68014476-adbdc800-fcca-11e9-9ca8-e96d89b9ffb5.png)
and tensorflow version < 2.0.
![image](https://user-images.githubusercontent.com/21559339/68014514-c928d300-fcca-11e9-9956-76863486d82f.png)
But I still got the problem of list index out of range when I issued `python3 mrcnn_to_trt_single.py` command. Surely the parameters were correctly assigned to the command.
Please refer to the error log:
![image](https://user-images.githubusercontent.com/21559339/68014671-2ae93d00-fccb-11e9-930f-19c3cbfe8451.png)

Anyone here can help? Thanks in advance!!

**Comment by rtrobin** [comment]
@ShawnNew please refer this [post](https://github.com/NVIDIA/TensorRT/issues/125#issuecomment-548445950). 

> TensorRT: 6.0.1.5
CUDA: 9.0
CuDNN: 7.6.3
python: 3.6.5
Tensorflow-gpu==1.9.0
Keras: 2.1.3

**Comment by ShawnNew** [comment]
> @ShawnNew please refer this [post](https://github.com/NVIDIA/TensorRT/issues/125#issuecomment-548445950).
> 
> > TensorRT: 6.0.1.5
> > CUDA: 9.0
> > CuDNN: 7.6.3
> > python: 3.6.5
> > Tensorflow-gpu==1.9.0
> > Keras: 2.1.3

Is it true that this problem stems from version mismatching?

**Comment by rtrobin** [comment]
@ShawnNew what problem are you referring to?

For your post, yes it is about mismatching of the version of tf or keras or both. For my experience, the different version of keras does lead to converting problem.

For the original post, it is about lacking the plugin in runtime. It could be fixed by loading custom op plugin library dynamically, or rebuild and reinstall whole trt plugin.

**Comment by ShawnNew** [comment]
@rtrobin Thank you very much. I can link the plugin correctly, while still get the **list** **index out of range** problem I posted even though I installed the right keras version. The only difference in my setting is I have `tensorflow-gpu==1.14.0`, I don't know if that will make things go south. 
Will try older tf version and report the result soon.

**Comment by gemmit** [comment]
> > I downgraded keras to 2.1.6. It could convert model to uff successfully. Hope it could help anyone here. @SongXia84 @fuman5000
> 
> I have Keras version of 2.1.3 as shown in the following picture.
> ![image](https://user-images.githubusercontent.com/21559339/68014476-adbdc800-fcca-11e9-9ca8-e96d89b9ffb5.png)
> and tensorflow version < 2.0.
> ![image](https://user-images.githubusercontent.com/21559339/68014514-c928d300-fcca-11e9-9956-76863486d82f.png)
> But I still got the problem of **list index out of range** when I issued `python3 mrcnn_to_trt_single.py` command. Surely the parameters were correctly assigned to the command.
> Please refer to the error log:
> ![image](https://user-images.githubusercontent.com/21559339/68014671-2ae93d00-fccb-11e9-930f-19c3cbfe8451.png)
> 
> Anyone here can help? Thanks in advance!!

@ShawnNew  I don't know if this helps, but did you make the changes in converter_functions.py as mentioned in the Readme [here](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN)?

**Comment by ShawnNew** [comment]
> > > I downgraded keras to 2.1.6. It could convert model to uff successfully. Hope it could help anyone here. @SongXia84 @fuman5000
> > 
> > 
> > I have Keras version of 2.1.3 as shown in the following picture.
> > ![image](https://user-images.githubusercontent.com/21559339/68014476-adbdc800-fcca-11e9-9ca8-e96d89b9ffb5.png)
> > and tensorflow version < 2.0.
> > ![image](https://user-images.githubusercontent.com/21559339/68014514-c928d300-fcca-11e9-9956-76863486d82f.png)
> > But I still got the problem of **list index out of range** when I issued `python3 mrcnn_to_trt_single.py` command. Surely the parameters were correctly assigned to the command.
> > Please refer to the error log:
> > ![image](https://user-images.githubusercontent.com/21559339/68014671-2ae93d00-fccb-11e9-930f-19c3cbfe8451.png)
> > Anyone here can help? Thanks in advance!!
> 
> @ShawnNew I don't know if this helps, but did you make the changes in converter_functions.py as mentioned in the Readme [here](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN)?

@gemmit I have already changed the index in 'converter_functions.py'.

**Comment by ShawnNew** [comment]
@Tyler-D I have already uninstall tensorflow (CPU version). But still got no luck.
My development environment depends on cuda 10.1, so I cannot install `tensorflow==1.9.0`.

**Comment by rtrobin** [comment]
@ShawnNew You can pull a tensorflow(==1.9.0) docker image do the conversion job. Once you get the uff model, you can use it in your development environment for deployment.

**Comment by Tyler-D** [comment]
@ShawnNew OK. That's the point. Look at this https://www.tensorflow.org/install/gpu 
I think tensorflow is not compatible with with CUDA 10.1 ---- That's why it turn to CPU-version convolution.

**Comment by rmccorm4** [comment]
Re: TF compatability with CUDA 10.1, it looks like it's pretty easy to do if building from source: https://github.com/tensorflow/tensorflow/issues/26150#issuecomment-506807444

I'm not sure how it works with the current pip package.

I generally work with/in containers for simplicity, similar to @rtrobin's suggestion.

FWIW, Nvidia's latest NGC container (19.10) comes built with CUDA 10.1 + TF 1.14: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_19.10.html#rel_19.10

**Comment by Tyler-D** [comment]
Yes. But if users use `pip install` to install tensorflow, a library of tensorflow compiled with CUDA10.0 will be downloaded.

**Comment by ShawnNew** [comment]
@rtrobin Can I use this `tensorflow/tensorflow:1.9.0-gpu-py3` as the image to run the `mrcnn_to_trt_single` sample?

**Comment by ShawnNew** [comment]
> Yes. But if users use `pip install` to install tensorflow, a library of tensorflow compiled with CUDA10.0 will be downloaded.

Indeed, with CUDA version 10.1, pip will download tf version (>1.9.0). So we can try the docker approach, refer https://github.com/NVIDIA/TensorRT/issues/132#issuecomment-550120904.

**Comment by rtrobin** [comment]
@ShawnNew Check this [post](https://github.com/NVIDIA/TensorRT/issues/159).

**Comment by ShawnNew** [comment]
@rtrobin Hi, I have tried link the .so library to `/usr/lib/x86_64-linux-gnu` directory, but still failed.

**Comment by rmccorm4** [comment]
Hi all,

Hopefully this post can help any still struggling: https://github.com/NVIDIA/TensorRT/issues/123#issuecomment-551269792

**Comment by ShawnNew** [comment]
Thanks @rmccorm4 , but I have already passed the conversion step by using `tensorflow/tensorflow:1.9.0-gpu-py3` image.
My problem now is I cannot proceed to the next step, which means inference failed.

![](https://user-images.githubusercontent.com/21559339/68273648-0d88ea00-00a2-11ea-8408-3dc29c1ab105.png)
 This is the screenshot of the error.

**Comment by rmccorm4** [comment]
What environment are you trying to convert the UFF -> TRT like in your screenshot? That still just looks something like auto conversion from add->addV2, which I think happens in TF >= 1.15 similar to here, I think you need to use TF <= 1.14 for the whole process TF -> UFF -> TRT, but you only did the (TF -> UFF) part in your container. Once you've converted UFF -> TRT, your tensorflow version shouldn't matter anymore because you should strictly be using the TensorRT API at that point to do inference on your TRT engine.

You might be able to also convert UFF -> TRT in that `tensorflow/tensorflow:1.9.0-gpu-py3 container`, but I'm not sure. If you're going to try using a container for parsing UFF -> TRT, I would suggest going with `nvcr.io/nvidia/tensorflow:19.10-py3` at the moment.

**Comment by ShawnNew** [comment]
Thanks @rmccorm4 , will try using tensorrt API to convert UFF model to TRT within the container.

**Comment by ShawnNew** [comment]
I finally succeed in the `sampleUffMaskRCNN` example by using https://github.com/NVIDIA/TensorRT/issues/123#issuecomment-551269792. Many thanks to @rmccorm4.

**Comment by rmccorm4** [comment]
Woohoo!

I think there's now enough information in this thread and #123 to make this work. Along with a couple tweaks I made in #208 to hopefully avoid some pitfalls. 

I'm going to close this now. Feel free to ask to have this one re-opened if you're still unable to get it working with the above information.

**Comment by Apsu95** [comment]
Hello all,

I successfully converted my model to UFF.

When I run the sample, I have this error:

&&&& RUNNING TensorRT.sample_maskrcnn # ./sample_maskRCNN -d /mnt/DTAA_data/DTAA/code/z662728/optimization/data/
[05/04/2020-09:24:19] [I] Building and running a GPU inference engine for Mask RCNN
[05/04/2020-09:24:21] [E] [TRT] UffParser: Validator error: mrcnn_detection_bboxes: Unsupported operation _SpecialSlice_TRT
&&&& FAILED TensorRT.sample_maskrcnn # ./sample_maskRCNN -d /mnt/DTAA_data/DTAA/code/z662728/optimization/data/

How did you solve it? @rmccorm4 @ShawnNew I would be very grateful if you could please help me :)

Config:
TF-gpu 1.14.0
CUDA 10.0
TensorRT: 6.0.1.5
Keras 2.1.3

Thanks!

**Comment by leepaul009** [comment]
> I get an error when I try to run MaskRCNN as below:
> 
> <img alt="1" width="1145" src="https://user-images.githubusercontent.com/55478964/65420046-cd391980-de1d-11e9-97d5-8601a6229387.png">
> 
> I have installed libnvinfer 6 also:
> 
> **$ apt list --installed | grep -i -e nvinfer -e nvparser**
> It gives the following output:
> 
> ```
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> libnvinfer-plugin-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> libnvinfer-plugin6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> libnvinfer5/unknown,unknown,now 5.1.5-1+cuda10.1 amd64 [installed]
> libnvinfer6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> libnvparsers-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> libnvparsers6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed,automatic]
> python-libnvinfer/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> python-libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> python3-libnvinfer/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> python3-libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed]
> ```

for this issue, "UffParser: Validator error: mrcnn_detection_bboxes: Unsupported operation _SpecialSlice_TRT"
It is because maskrcnn use a tensorrt plugin, specialSlicePlugin, which system failed to search it in libnvinfer_plugin.so
You could have a try to solve it by using libnvinfer_plugin.so which is built by yourself. It located in the folder along with executable sample_uff_maskRCNN.
