### ISSUE TITLE
when coeff!=1, trtexec not support eltwise in caffe

### ISSUE THREAD

**Issue by ALittleaseWolf** [NVIDIA/TensorRT#1321]
In TensorRT 7.2.3.4. When I used trtexec to convert caffemodel to engine, it seemed work normally. 
But when i inference the enigne, one output in engine compared to caffe gaps so large.
|layer|average gap|
|-|-|
|conv52|34.670227028177074|

Then I had compared every layer output in model, and I found the error soon.
|layer|average gap|
|-|-|
|sub1|**1.2448702256391917**|
 
```
layer {
  name: "sub1"
  type: "Eltwise"
  bottom: "view1"
  bottom: "relu50"
  top: "sub1"
  eltwise_param {
    operation: SUM
    coeff: 1.0
    coeff: -1.0
  }
}
```

After a while, I found the possible answer(Nov 07 '18) in nvidia forums
![image](https://user-images.githubusercontent.com/37907356/123195746-45dd7600-d4db-11eb-8462-9be6127f111f.png)

SO NOW IF COPING WITH THIS,
I need divide the network to three pieces.  Part one and part three convert to engine in cuda, when part two(the eltiwise layer)runs in cpu? or other simpler solution?

**Comment by ttyio** [comment]
@ALittleaseWolf , could you export your model to ONNX? thanks

**Comment by ALittleaseWolf** [comment]
It is alright using caffe2onnx
