### ISSUE TITLE
Does keras.layers.ZeroPadding2D is supported by TensorRT currently?

### ISSUE THREAD

**Issue by Neronjust2017** [NVIDIA/TensorRT#1322]
## Description

When I try to convert onnx (converted from keras) to tensorrt engine, this error occurs. 

`IndexError: Attribute not found: pads. 
`
I found my keras model contains  keras.layers.ZeroPadding2D layers (keras version is 2.2.4). Does keras.layers.ZeroPadding2D is supported by TensorRT? 

## Environment

**TensorRT Version**: 7.2.34.
**NVIDIA GPU**: Tesla P100
**NVIDIA Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System**: CentOS
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 1.14.0

**Comment by ttyio** [comment]
@Neronjust2017 , 
could you try latest 8.0, it support `Pad` without attribute `pads`, and read it from initializer. 
or you can export your ONNX to opset 10 if you want to stick to trt 7.2
thanks!

**Comment by Neronjust2017** [comment]
Hi, Thanks. I found the problem. I used TensorRT 7.2.3.4 to build engine from onnx model, but in my environment path, I set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/xxx/TensorRT/TensorRT-7.0.0.11/lib. So, TensorRT actually uses files in TensorRT-7.0.0.11/lib, which leading the “Attribute not found” error somehow.
