### ISSUE TITLE
What is the distribution when using trtexec to randomly generate data/weight?

### ISSUE THREAD

**Issue by xyyaman** [NVIDIA/TensorRT#1323]
For example:
`trtexec --deploy=model.prototxt --iterations=100 --device=0 --avgRuns=1 --warmUp=0 --duration=0 --loadEngine=myengine.eg --output=output --batch=1 --fp16 `

Then the inputs and weights are both randomly generated. What is the distribution of them? Are they uniform distribution?

**Comment by ttyio** [comment]
@xyyaman , the weights come from `myengine.eg` when `--loadEngine` is used, else it is random. 
The input is random when `--loadInputs` is not used.

And yes it is uniform distribution, the range is [-128, 127] for int type and [-1, 1] for floating type.

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
