### ISSUE TITLE
Onnx -> TensorRT. No speed difference between models of different sizes.

### ISSUE THREAD

**Issue by Fschoeller** [NVIDIA/TensorRT#1325]
I have two yolov5 models of different sizes. One has 35.9m parameters, the other 12.7m.
When I convert the models to TensorRT with `trtexec --onnx=model.onnx --batch=5 --fp16` the resulting models have roughly the same inference speed (21 fps) even though the speed should be vastly different.
What am I doing wrong?

**Comment by ttyio** [comment]
@Fschoeller , could you check if the batch dimension in the the onnx input has dynamic shape (-1)?
Also trtexec need `--minShapes, --optShapes, --maxShapes` to build engine with dynamic shapes, and need `--shapes` to inference engine with dynamic shapes.
Thanks

**Comment by Fschoeller** [comment]
The engine was built with a static input size of `(5,3,1280,1280)`
Thanks

**Comment by ttyio** [comment]
@Fschoeller , could you share the 2 models? thanks!

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
