### ISSUE TITLE
ONNX -> TensorRT FP32 model with INT8 input produces error: Calibration failure occurred with no scaling factors detected

### ISSUE THREAD

**Issue by simunovic-antonio** [NVIDIA/TensorRT#1326]
## Description

I'm converting my detector model from ONNX to TensorRT. Input to the model is a Tensor of type INT8 and the model is running in FP32 precision.

Converting the model to TensorRT produces this error:

```
[TensorRT] WARNING: Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32.
[TensorRT] ERROR: 4: [standardEngineBuilder.cpp::initCalibrationParams::2076] Error Code 4: Internal Error (Calibration failure occurred with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
```

It seems that the conversion procedure is assuming that model should be calibrated to INT8, but that is not specified in the configuration. If I specify input as FP32, the model is converted correctly, but then I need to cast my inputs to FP32 before running the model.

Here is the code:

```
from io import BytesIO
import tensorrt as trt
trt_logger = trt.Logger(trt.Logger.VERBOSE)

def convert_onnx_to_tensorrt():
    shape = (1, 3, 720, 1280)
    MIN_INPUT_SHAPE = (1, 3, shape[-2], shape[-1])
    OPT_INPUT_SHAPE = (4, 3, shape[-2], shape[-1])
    MAX_INPUT_SHAPE = (8, 3,  shape[-2], shape[-1])
    flags = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    tensorrt_model_buffer = BytesIO() 
    with open('model.onnx', 'rb') as onnx_model_buffer:
        with trt.Builder(trt_logger) as builder, builder.create_network(flags) as network, trt.OnnxParser(network, trt_logger) as parser:
            builder.max_batch_size = 8
            onnx_model_buffer.seek(0)            
            success = parser.parse(onnx_model_buffer.read())
            if not success:
                for error in range(parser.num_errors):
                    print(parser.get_error(error))
                raise Exception
            else:                
                with builder.create_builder_config() as config:
                    config.max_workspace_size = 1 << 20
                    profile = builder.create_optimization_profile()
                    profile.set_shape('input', MIN_INPUT_SHAPE, OPT_INPUT_SHAPE, MAX_INPUT_SHAPE)
                    config.add_optimization_profile(profile)                
                    with builder.build_engine(network, config) as engine:                   
                        tensorrt_model_buffer.write(engine.serialize())
    return tensorrt_model_buffer
```

## Relevant Files

ONNX model file is available at: https://drive.google.com/file/d/1FoFxYLNuppW8yFlUDd7N-DBUS2prK_hN/view?usp=sharing

## Environment

**TensorRT Version**: 8.0.0.3
**NVIDIA GPU**: NVIDIA GeForce GTX TITAN X
**NVIDIA Driver Version**: 465.19.01
**CUDA Version**: 11.3
**CUDNN Version**: 8.2.0
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**PyTorch Version (if applicable)**: 1.8.1+cu102
**Baremetal or Container (if so, version)**: Baremetal

**Comment by ttyio** [comment]
Hi @simunovic-antonio ,

Is there any specific reason the input has to be INT8? Is the accuracy meet your needs when the input is in this narrow range [-128, 127] ?

The reason TRT reject your model is that: the INT8 resolution is low so that normally we need quantization to make it work.  Then we need multiply the scale back when the int8 go back to high precision. And your failure message here means TRT failed to find the scale when see INT8.

**Comment by simunovic-antonio** [comment]
Hi @ttyio

The input is INT8 because it's an image, with values ranging from 0-255. This way i can transfer one byte per channel pixel, and do the normalization on device. That was my motivation for the question.

**Comment by ttyio** [comment]
Thanks @simunovic-antonio for the explanations, the INT8 range in TRT is [-128, 127], so we cannot hold the [0, 255] values. 
Could we use FP32 as input, feed it with value 0.f-255.f, and we can still keep the normalization on device by `input/127.5f-1.f`

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
