### ISSUE TITLE
ONNX -> TensorRT, `set_optimizaton_profile_async` throws error

### ISSUE THREAD

**Issue by MagiaSN** [NVIDIA/TensorRT#1327]
## Description

I have built a TensorRT engine from a toy ONNX model, but when I was trying to use the engine for inference, an error raised when I was calling `set_optimization_profile_async`. I have attached scripts below to reproduce this issue.

## Environment

**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: GRID T4-8C
**NVIDIA Driver Version**: 450.102.04
**CUDA Version**: 11.3
**CUDNN Version**: 
**Operating System**: CentOS 7
**Python Version (if applicable)**: 3.8.5
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:21.06-py3

## Relevant Files

[files_for_reproduction.tar.gz](https://github.com/NVIDIA/TensorRT/files/6715958/files_for_reproduction.tar.gz)

## Steps To Reproduce

1. `tar -zxf files_for_reproduction.tar.gz` and put `onnx_model.bin` and `main.py` in current directory

2. `nvidia-docker run -it --rm -v $(pwd):/data nvcr.io/nvidia/tensorrt:21.06-py3 /bin/bash`

3. Within the container, `cd /data; python3 main.py`

You will see the following error message:

```
...
before set_optimization_profile_async
[TensorRT] INTERNAL ERROR: Assertion failed: mGraphContexts.find(&context) == mGraphContexts.end()
myelin/myelinRunner.cpp:163
Aborting...
[TensorRT] ERROR: INTERNAL_ERROR: std::exception
after set_optimization_profile_async
```

**Comment by MagiaSN** [comment]
Anyone help?

**Comment by ttyio** [comment]
@MagiaSN , we need `engine` alive when using `context`, could you try changing code like


       with deserialize_cuda_engine() as trt_engine, trt_engine.create_execution_context() as trt_context
             print("before set_optimization_profile_async")
             trt_context.set_optimization_profile_async(0, stream.handle)

Thanks

**Comment by MagiaSN** [comment]
@ttyio hi, I changed

```python
with open(TRT_MODEL_PATH, "rb") as f:
    trt_engine = trt_runtime.deserialize_cuda_engine(f.read())
    trt_context = trt_engine.create_execution_context()

print("before set_optimization_profile_async")
trt_context.set_optimization_profile_async(0, stream.handle)
print("after set_optimization_profile_async")
```

to

```python
with open(TRT_MODEL_PATH, "rb") as f:
    with trt_runtime.deserialize_cuda_engine(f.read()) as trt_engine, trt_engine.create_execution_context() as trt_context:
        print("before set_optimization_profile_async")
        trt_context.set_optimization_profile_async(0, stream.handle)
        print("after set_optimization_profile_async")
```

and still got the same error

```
before set_optimization_profile_async
[TensorRT] INTERNAL ERROR: Assertion failed: mGraphContexts.find(&context) == mGraphContexts.end()
myelin/myelinRunner.cpp:163
Aborting...
[TensorRT] ERROR: INTERNAL_ERROR: std::exception
after set_optimization_profile_async
```

I think engine is still alive in the original script, because it does not go out of scope

**Comment by ttyio** [comment]
Hello @MagiaSN , I just tried and can reproduce the failure in 7.2, and this is fixed in 8.0, could you take a try? thanks

**Comment by MagiaSN** [comment]
Hello @ttyio , I tried TensorRT-8.0.1.6 and this is fixed, thanks! I am closing this issue.

**Comment by avideci** [comment]
On TensorRT < 8 you should use:
'execution_context.active_optimization_profile = 0' instead of `execution_context.set_optimization_profile_async(0, stream.handle`)
