### ISSUE TITLE
Unable to include TensorRT

### ISSUE THREAD

**Issue by fbens47** [NVIDIA/TensorRT#1329]
## Description

When trying to `#include <NvWhatEverHeader.h>` in my code I have the `Process finished with exit code -1073741515 (0xC0000135)` output. Having never used Windows for programming I am quite lost. CMake finds every `.lib` required but from what I found at runtime the program isn't able to find any `.dll`. I am only trying to include the library

## Environment

**TensorRT Version**:  7.2.3.4
**NVIDIA GPU**:  NVIDIA GeForce GTX 1660 Ti
**NVIDIA Driver Version**:  471.11
**CUDA Version**:  11.3
**CUDNN Version**:  8.2.1
**Operating System**:  Win10
**Python Version (if applicable)**:  NC
**Tensorflow Version (if applicable)**:  NC
**PyTorch Version (if applicable)**:  NC
**Baremetal or Container (if so, version)**:  NC

## Relevant Files

* Code

```
#include <iostream>
#include <cuda.h>
#include <cuda_runtime_api.h>
#include <NvInfer.h>
// #include <NvInferRuntime.h>  // Same
// #include <NvInferPlugin.h>   // Same
// #include <NvUffParser.h>  // Same
// #include <NvOnnxParser.h>  // Same

int main() {
    std::cout << "Orbis, te saluto!" << std::endl;
    int deviceCount;
    cudaError_t e = cudaGetDeviceCount(&deviceCount);
    bool success;
    success = (e==cudaSuccess);
    std::cout << "GPU repéré: " << success << std::endl;
    return e == cudaSuccess ? deviceCount: -1;
}
```
Output:  `Process finished with exit code -1073741515 (0xC0000135)` 

If no lib from TensorRT is loaded:

```
#include <iostream>
#include <cuda.h>
#include <cuda_runtime_api.h>

int main() {
    std::cout << "Orbis, te saluto!" << std::endl;
    int deviceCount;
    cudaError_t e = cudaGetDeviceCount(&deviceCount);
    bool success;
    success = (e==cudaSuccess);
    std::cout << "GPU repere: " << success << std::endl;
    return e == cudaSuccess ? deviceCount: -1;
}
```
Output: 1

**Comment by ttyio** [comment]
@fbens47 Have you tried using Visual Studio? thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
