### ISSUE TITLE
Xavier NX cross-compile need more support !!!!

### ISSUE THREAD

**Issue by WangFengtu1996** [NVIDIA/TensorRT#1332]
## Description

* I install related related software under the  `README.md` file. But there are some lib files`.so` that are copied  from the device.
```
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: warning: libnvrtc.so.10.2, needed by /pdk_files/tensorrt/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: warning: libnvdla_compiler.so, needed by /pdk_files/tensorrt/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: warning: libnvmedia.so, needed by /pdk_files/tensorrt/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: warning: libEGL.so.1, needed by /pdk_files/tensorrt/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)

```
* please produce related `deb` package to install to resolve this problem.

**Comment by TUT-jiayou** [comment]
# Environment
TensorRT Version: 7.1.3
NVIDIA GPU:
NVIDIA Driver Version:
CUDA Version: 10.2
CUDNN Version:
Operating System: ubuntu 18.04

jeston jepack 4.5
xavier xavier nx

**Comment by csq20081052** [comment]
Hi, I got the same error as yours. Can you tell me how to fix this problem? Do I need to install some ".deb" file? Thx.

**Comment by TUT-jiayou** [comment]
* I can not find good way to fix the bug.
* I copy the needed dynamic libraries (.so file) from the development Kit to the X86 machine.

**Comment by csq20081052** [comment]
OK, I got it. Thank you~

**Comment by ttyio** [comment]
closing old issues that is inactive for long time, thanks all!
