### ISSUE TITLE
Memory Leak in yolov5

### ISSUE THREAD

**Issue by m-vaibhav** [NVIDIA/TensorRT#1336]
yolov5: Memory is increasing till GPU got out of memory (during inference).

Tensorrt: 7.2.2
PyTorch: 1.6
OS: ubuntu 20.04.2 LTS

Logs:
* **cuda-memcheck --leak-check full**:  got 0 errors 0 leaks [cuda-memcheck.log](https://github.com/NVIDIA/TensorRT/files/6748969/cuda-memcheck.log)
* **valgrind -v --tool=memcheck --leak-check=full --log-file=valgrind.log**: 16 bytes in 1 blocks are possibly lost in loss record 90 of 16,971 [valgrind.log](https://github.com/NVIDIA/TensorRT/files/6748971/valgrind.log)

**Comment by ttyio** [comment]
Hello @m-vaibhav , the log show the definitely loss memory come from the pytorch stack? Could you take a check? thanks

     ==2765== 128 bytes in 1 blocks are definitely lost in loss record 15,281 of 16,971
     ==2765==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
     ==2765==    by 0x2A8F8ED0: c10::cuda::CUDACachingAllocator::THCCachingAllocator::malloc(void**, int, unsigned long, CUstream_st*) (in /workspace/pytorch-install/lib/libc10_cuda.so)
     ==2765==    by 0x2A8FAB7D: c10::cuda::CUDACachingAllocator::CudaCachingAllocator::allocate(unsigned long) const (in /workspace/pytorch-install/lib/libc10_cuda.so)
     ==2765==    by 0x5A9912D4: THCStorage_resizeBytes(THCState*, c10::StorageImpl*, long) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5A8C871E: at::native::resize_impl_cuda_(c10::TensorImpl*, c10::ArrayRef<long>, c10::optional<c10::ArrayRef<long> >, bool) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5C0AFAB3: at::native::(anonymous namespace)::resize_cuda_(at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5C0AFB55: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor& (*)(at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>), at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat> > >, at::Tensor& (at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x2F0AC001: at::Tensor::resize_(c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) const (in /workspace/pytorch-install/lib/libtorch_cpu.so)
     ==2765==    by 0x2EC95A0F: at::TensorIterator::resize_outputs(at::TensorIteratorConfig const&) (in /workspace/pytorch-install/lib/libtorch_cpu.so)
     ==2765==    by 0x2EC95B25: at::TensorIterator::build(at::TensorIteratorConfig&) (in /workspace/pytorch-install/lib/libtorch_cpu.so)
     ==2765==    by 0x2EC95DCB: at::TensorIterator::TensorIterator(at::TensorIteratorConfig&) (in /workspace/pytorch-install/lib/libtorch_cpu.so)
     ==2765==    by 0x2EC962DC: at::TensorIterator::unary_op(at::Tensor&, at::Tensor const&, bool) (in /workspace/pytorch-install/lib/libtorch_cpu.so)
     ==2765== 
     
     ==2765== 128 bytes in 1 blocks are definitely lost in loss record 15,282 of 16,971
     ==2765==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
     ==2765==    by 0x2A8F8ED0: c10::cuda::CUDACachingAllocator::THCCachingAllocator::malloc(void**, int, unsigned long, CUstream_st*) (in /workspace/pytorch-install/lib/libc10_cuda.so)
     ==2765==    by 0x2A8FAB7D: c10::cuda::CUDACachingAllocator::CudaCachingAllocator::allocate(unsigned long) const (in /workspace/pytorch-install/lib/libc10_cuda.so)
     ==2765==    by 0x5A9912D4: THCStorage_resizeBytes(THCState*, c10::StorageImpl*, long) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5A8C871E: at::native::resize_impl_cuda_(c10::TensorImpl*, c10::ArrayRef<long>, c10::optional<c10::ArrayRef<long> >, bool) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5C0AFAB3: at::native::(anonymous namespace)::resize_cuda_(at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5C0AFB55: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor& (*)(at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>), at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat> > >, at::Tensor& (at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>)>::call(c10::OperatorKernel*, at::Tensor&, c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x2F0AC001: at::Tensor::resize_(c10::ArrayRef<long>, c10::optional<c10::MemoryFormat>) const (in /workspace/pytorch-install/lib/libtorch_cpu.so)
     ==2765==    by 0x5C120225: at::native::cat_out_cuda(at::Tensor&, c10::ArrayRef<at::Tensor>, long) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5C120C83: at::native::cat_cuda(c10::ArrayRef<at::Tensor>, long) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5A8DC9BE: at::CUDAType::_cat(c10::ArrayRef<at::Tensor>, long) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==    by 0x5A90404F: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<at::Tensor>, long), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<at::Tensor>, long> >, at::Tensor (c10::ArrayRef<at::Tensor>, long)>::call(c10::OperatorKernel*, c10::ArrayRef<at::Tensor>, long) (in /workspace/pytorch-install/lib/libtorch_cuda.so)
     ==2765==

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
