### ISSUE TITLE
Need help to understand a TRT error message: Error Code 2: Internal Error (Assertion asCopyingLeafNode() ? candidateChoices.empty() : !candidateChoices.empty() failed

### ISSUE THREAD

**Issue by jerryzh168** [NVIDIA/TensorRT#1337]
## Description

Hi, I'm trying out PyTorch Quantization + TensorRT explicit quantization integration (available in 8.0) by quantizing a resnet18 with pytorch quantization and lower the quantized model to TensorRT with fx2trt (https://github.com/pytorch/pytorch/pull/60589) and got the following error:

```
[TensorRT] ERROR: 2: [optimizer.cpp::isPolymorphic::1018] Error Code 2: Internal Error (Assertion asCopyingLeafNode() ? candidateChoices.empty() : !candidateChoices.empty() failed.)
```

Can anyone tell me what this means? I can provide more detail about integration if needed.
## Environment

**TensorRT Version**: 8.0
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 11.3
**CUDNN Version**: 
**Operating System**: linux
**Python Version (if applicable)**: 3.9
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: master
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

1. checkout https://github.com/pytorch/pytorch/pull/60589
2. run `python test/test_quantization.py TestQuantizeFxModels.test_reference_resnet18_to_trt`

**Comment by ttyio** [comment]
Hello @jerryzh168 , could you attach the exported ONNX here? thanks

**Comment by jerryzh168** [comment]
Hi @ttyio, I'm not using the onnx path, I found that there was some problem in the produced model. This problem is resolved now.

The problem is that the data type is not correct for some layers, I had quantize - maxpool - dequantize in the graph before, but it should be quantize - dequantize - maxpool - quantize - dequantize

**Comment by ttyio** [comment]
Thanks @jerryzh168 , Yes for TensorRT we already put the Q/DQ pair together.
I will close this issue, and please create new issue if you have more question.

**Comment by srihari-humbarwadi** [comment]
Found another pattern: `X` -> `Q` -> `transpose` -> `DQ`
This triggers the the same error while exporting with this workflow ---
while exporting `TF2,x QAT` -> `ONNX` -> `TensorRT`.

**Comment by jerryzh168** [comment]
Yes, I guess you'll probably need X -> Q - > DQ -> Transpose -> Q -> DQ

**Comment by srihari-humbarwadi** [comment]
Yeah, getting rid of the transpose op fixes this.
