### ISSUE TITLE
when batchSize = 1 , the net output of int8 is equal to fp32

### ISSUE THREAD

**Issue by zy30106** [NVIDIA/TensorRT#1338]
hello , i run the sample_int8(sampleINT8) in docker ( NVIDIA NGC 20.12-py3) ,  i change the batch size to 1 , and i found that the net outpt of int8 is euqal to that of fp32 , can you tell me why, thank you.

**Comment by zy30106** [comment]
Hi, i have another question now.
How do I know which layers have int8 inference implements?

**Comment by franksilke** [comment]
u mean the outputs of the model or the size of the model?
I generate a model using fp32, model's size is 500M
and when I use int8, model's size is also 500M
I dont know how to deal

**Comment by nvpohanh** [comment]
@zy30106 Could you elaborate on what "net outpt of int8 is euqal to that of fp32" means? Like latency is the same? Or the output values?

Also, please share what GPUs you were using. You can check which layers use INT8 by utilizing the engine inspector API: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#engine-inspector

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
