### ISSUE TITLE
[Error] ModuleNotFoundError: No module named 'onnx_helper'

### ISSUE THREAD

**Issue by ingbeeedd** [NVIDIA/TensorRT#1339]
Hello, tensorrt system was configured in a docker. No problem until nvidia-smi, and I confirmed that the package was installed through the pip list. However, an error occurred when I simply run the Python terminal to import onnx_helper. Why?

**Comment by ttyio** [comment]
@ingbeeedd , we have official container you can play with `nvcr.io/nvidia/tensorrt:21.06-py3`, thanks
