### ISSUE TITLE
Do I have to create and run the engine on the same Nvidia Graphics Card?

### ISSUE THREAD

**Issue by BChunlei** [NVIDIA/TensorRT#1349]
I generate tensorrt model (.trt) from pytorch model in machine A, and want to run the .trt file in machine B, (A and B have different  Graphics Cards). Is it allowed?

**Comment by ttyio** [comment]
Hello @BChunlei , it is not allowed, some generated kernel is device dependent in the mode.

**Comment by BChunlei** [comment]
ok, thanks. @ttyio

**Comment by BChunlei** [comment]
ok, thanks. @ttyio
