### ISSUE TITLE
Undefined reference to xxx, when my project depends on libnvonnxparser_runtime_static.a

### ISSUE THREAD

**Issue by YirongMao** [NVIDIA/TensorRT#135]
Hi, 
    My project dependency files include:
        libnvinfer_static.a
        libnvonnxparser_runtime_static.a 
        libnvinfer_plugin_static.a
        libnvonnxparser_static.a 
        libnvparsers_static.a

 And then I plan to deserialize the engine with Unsample Operation:
       ICudaEngine* engine = runtime->deserializeCudaEngine(buffer, length,
                                       nvonnxparser::createPluginFactory(gLogger));
 
**Error occur:**
libnvonnxparser_runtime_static.a(builtin_plugins.cpp.o): In function `FancyActivationPluginCreator::deserializePlugin(char const*, void const*, unsigned long)':
    builtin_plugins.cpp:(.text._ZN28FancyActivationPluginCreator17deserializePluginEPKcPKvm[_ZN28FancyActivationPluginCreator17deserializePluginEPKcPKvm]+0x36): undefined reference to `vtable for FancyActivationPlugin'

libnvonnxparser_runtime_static.a(builtin_plugins.cpp.o): In function `ResizeNearestPluginCreator::deserializePlugin(char const*, void const*, unsigned long)':
builtin_plugins.cpp:(.text._ZN26ResizeNearestPluginCreator17deserializePluginEPKcPKvm[_ZN26ResizeNearestPluginCreator17deserializePluginEPKcPKvm]+0x36): undefined reference to `vtable for ResizeNearestPlugin'

**Comment by rmccorm4** [comment]
Hi @YirongMao,

Did you make sure to properly register your plugins? See the docs on this: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#extending

Specifically, this snippet might be relevant, but it's good to read all of the documentation:
> **Note**: To use TensorRT registered plugins in your application, the libnvinfer_plugin.so library must be loaded and all plugins must be registered. This can be done by calling initLibNvInferPlugins(void* logger, const char* libNamespace)() in your application code.

> **Note**: If you have your own plugin library, you can include a similar entry point to register all plugins in the registry under a unique namespace. This ensures there are no plugin name collisions during build time across different plugin libraries.

**Comment by rmccorm4** [comment]
I've also posted steps on how to build the OSS components inside our NGC containers (assuming you're running Linux.)

Some of the steps listed there might help you figure out which libraries/plugins aren't being linked correctly: https://github.com/NVIDIA/TensorRT/issues/190#issuecomment-550037253

Closing for now.
