### ISSUE TITLE
How to implement ScatterND plugin in Tensorrt7.2.3.4?

### ISSUE THREAD

**Issue by rsj007** [NVIDIA/TensorRT#1350]
I want to convert my onnx to tensorrt. However it meets an error that scatternd plugin is not supported. I find scatternd has been added to Tensorrt OSS 8.0 recently. So I copy the scatter plugin folder to my Tensorrt OSS plugin and rebuild it. But it shows the error as below.  Can someone tell me why or tell me how to add scatter plugin?

My command is "make nvinfer_plugin -j4 ".
![Screenshot from 2021-07-07 15-14-58](https://user-images.githubusercontent.com/29651895/124716412-a25a7f80-df36-11eb-9df2-3f71319c4197.png)

## Environment

**TensorRT Version**:  7.2.3.4
**TensorRT OSS Version**:  21.05
**CUDA Version**:  10.2
**Operating System**:  Jetson TX2,  jetpack 4.5
**Python Version (if applicable)**: 3.6.9
**PyTorch Version (if applicable)**: 1.7

**Comment by ttyio** [comment]
Hello @rsj007 , it is defined in 
https://github.com/NVIDIA/TensorRT/blob/release/8.0/plugin/common/kernels/kernel.h#L94
implementation in 
https://github.com/NVIDIA/TensorRT/blob/release/8.0/plugin/scatterPlugin/scatterLayer.cu

Thanks

**Comment by rsj007** [comment]
Thanks! It has been installed.
