### ISSUE TITLE
Does TensorRT 8.0.1 OSS support windows build?

### ISSUE THREAD

**Issue by p890040** [NVIDIA/TensorRT#1351]
I'm very excited about TensorRT8.0.1 new features.
Even though there is prebuild version, I still want to know that TensorRT8.0.1 OOS native build will be official supported?

**Comment by ttyio** [comment]
Sorry @p890040 no official windows build for OSS yet.

**Comment by pustar** [comment]
What's the meaning of OSS?

**Comment by ttyio** [comment]
@pustar 
Open-source software
