### ISSUE TITLE
TensorRT OSS container build: error CUDA initialization failure with error 804

### ISSUE THREAD

**Issue by quangngn** [NVIDIA/TensorRT#1354]
## Description  
I follow the instruction on this TensorRT repo to run TSRT8 under the docker container. However, when I start creating builder,  I got the error:
"[TensorRT] INTERNAL ERROR: [runtime.cpp::isCudaInstalledCorrectly::41] Error Code 6: Internal Error (CUDA initialization failure with error 804. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    create_engine(model_path=MODEL_PATH)
  File "test.py", line 15, in create_engine
    with trt.Builder(LOGGER) as builder, builder.create_builder_config() as config:
TypeError: pybind11::init(): factory function returned nullptr"

I checked nvidia-smi and everything seems to be alright. Does anyone know how to overcome this issue? Many thanks!

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**: 2080ti
**NVIDIA Driver Version**: 
**CUDA Version**: 11.3.1
**CUDNN Version**: N/A
**Operating System**: Ubuntu18.4
**Python Version (if applicable)**: Python3

**Comment by quangngn** [comment]
I solve it. So it was my bad. The CUDA version on driver is only 11.2 when I run command nvidia-smi. Clearly 11.2 < 11.3.

**Comment by Xieyuan0018** [comment]
I'm having the same problem. Could you please explain how you solved it? My local CUDA version is 11.1, but if I build the container with cuda 11.1, there will be error installing tensorrt...

**Comment by quangngn** [comment]
> I'm having the same problem. Could you please explain how you solved it? My local CUDA version is 11.1, but if I build the container with cuda 11.1, there will be error installing tensorrt...

Hi! You can try the CUDA 10.2 version. I believe the Docker OSS only support 10.2 and 11.3 so 11.1 won’t work. You can use the same command but change 11.3 to 10.2. 

I personally would recommend you also try the TSRT 7 version with CUDA 11. With TSRT8 and CUDA 10.2, I got into some weird error with CUBLAS.
