### ISSUE TITLE
Tesla T4

### ISSUE THREAD

**Issue by guods** [NVIDIA/TensorRT#136]
windows
cuda 10.0
cudnn 7.5
TensorRT 5.1.5.0
caffe-yolov3
The acceleration effect on Int8 mode is very poor onsingle Tesla T4, it costs 90ms one image, but that is 32ms on GTX 1060.

**Comment by litaotju** [comment]
If you provide more info @guods like the repro steps and networks, it would help the maintainer to repsond to you more quickly.

**Comment by zt706** [comment]
I have the same problem, and the sampe model in P100 is faster twice than T4 in fp16.
And i found the erery layer is slower than P100 .

**Comment by rmccorm4** [comment]
Hi @guods,

Do you still experience this performance issue using TensorRT 6.x ?

**Comment by rmccorm4** [comment]
Closing since no response. Feel free to open a new issue and follow the bug template, thanks.
