### ISSUE TITLE
How to run inference in multithread( only Allocate host and device buffers once for all execution contexts)

### ISSUE THREAD

**Issue by Neronjust2017** [NVIDIA/TensorRT#1367]
Hi,

I have several TensorRT engines including yolo and inception for detection and classification tasks, respectively. What I have done is running these engines one by one, which takes much time though. What I want to do is to run them in parallel using multi-threading in python. I know the TensorRT runtime can be used by multiple threads simultaneously, so long as each object uses a different execution context. But in each execution context, It will allocate host and device buffers for itself, so the total allocated buffers will be quite large. Is there any way to run inferences in multi-threading and only allocate buffers once for all execution contexts?  Is it possible for all execution contexts to share the host and device buffers? Maybe using Thanks!

**Comment by nvpohanh** [comment]
@Neronjust2017 Yes, you can allocate only one set of input/output buffers, and use that set of buffers (called "bindings") to call different contexts' enqueueV2() function. However, you will need to manage the synchronization on your own to make sure that no two contexts are running inference at the same time, creating race conditions.

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
