### ISSUE TITLE
How to init two different tensorrt model in one program?

### ISSUE THREAD

**Issue by Sampson2016** [NVIDIA/TensorRT#1368]
When i init two different tensorrt model in one program, when i do inference, the error occurs.
[TensorRT] ERROR: ../rtExt/cuda/cudaGatherRunner.cpp (111) - Cuda Error in execute: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception

**Comment by nvpohanh** [comment]
Could you share your code? This should be possible.

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
