### ISSUE TITLE
Problems building TensorRT OSS

### ISSUE THREAD

**Issue by Echambouleyron** [NVIDIA/TensorRT#1375]
## Description

Cmake command runs perfectly well but make -j does not. [Here](https://portahnos-my.sharepoint.com/:f:/g/personal/echambouleyron_porta_com_ar/EgeB_0gohZNLmS0b6qrsOGUBJTvA6MfaJuYQZwzzagfoeQ?e=lCkywR) you can find the output.

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**:  Nvidia GTX 1050
**NVIDIA Driver Version**: 470.42.01
**CUDA Version**: 11.3
**CUDNN Version**: 8.2
**Operating System**: Ubuntu 20.04 LTS
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: 2.5

## Steps To Reproduce
git clone -b master https://github.com/nvidia/TensorRT TensorRT
cd TensorRT
git submodule update --init --recursive
mkdir -p build && cd build
cmake .. -DGPU_ARCHS="61" -DTRT_LIB_DIR=/home/deep2/TensorRT-8.0.1.6/lib -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CUDA_COMPILER:PATH=/usr/local/cuda/bin/nvcc -DCUDA_VERSION=11.3.1 -DCUBLASLT_LIB=/usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so -DCUBLAS_LIB=/usr/local/cuda/targets/x86_64-linux/lib/libcublas.so -DCUDART_LIB=usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.3.109
make -j$(nproc)

**Comment by rajeevsrao** [comment]
There is a missing `/` in your cudart path in cmake command. Should be `-DCUDART_LIB=/usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.3.109` .

**Comment by Echambouleyron** [comment]
> @Echambouleyron there is a missing `/` in your cudart path in cmake command. Should be `-DCUDART_LIB=/usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.3.109` .

I corrected it and still got the same error

**Comment by rajeevsrao** [comment]
Can you try a clean build (`rm -rf build` and start over)? I saw the error resolved when I fixed the path.

**Comment by Echambouleyron** [comment]
> Can you try a clean build (`rm -rf build` and start over)? I saw the error resolved when I fixed the path.

Awesome! It worked. Thanks
