### ISSUE TITLE
Question about ConcatenationLayer

### ISSUE THREAD

**Issue by 842974287** [NVIDIA/TensorRT#1385]
## Description

Hi, 

For concatenation layer we need to specify the axis along which we want to concatenate on. In the document it says "0 is the major axis (excluding the batch dimension)". Does this only hold for implicit batch dimension network? Asking because I'm seeing an error for explicit batch dimension network.

The shapes of inputs to concatenation layer are (2, 3, 4) and (2, 1, 4). I set axis to 0 and got the following error
```
[TensorRT] ERROR: cat_1: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at index 1. Input 0 shape: [1,2,3], Input 1 shape: [1,1,3]
```
This seems like with explicit batch dimension, the axis of concatenation layer uses 0 to represent batch dimension. Could this be a typo in the documentation or maybe I misunderstood something?

## Environment

**TensorRT Version**: 7.2
**NVIDIA GPU**: A100

## Steps To Reproduce

```
import tensorrt as trt

logger = trt.Logger(trt.Logger.VERBOSE)
builder = trt.Builder(logger)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
network = builder.create_network(EXPLICIT_BATCH)
# network = builder.create_network()
input_val = network.add_input(name="x", shape=(2, 3, 4), dtype=trt.float16)
other_val = network.add_input(name="y", shape=(2, 1, 4), dtype=trt.float16)
layer = network.add_concatenation(inputs=[input_val, other_val])
layer.axis = 0
output = layer.get_output(0)
output.name = "output"
network.mark_output(output)
output.dtype = trt.float16

builder.max_batch_size = 16
builder_config = builder.create_builder_config()
builder_config.max_workspace_size = 1 << 25
builder_config.set_flag(trt.BuilderFlag.FP16)
engine = builder.build_engine(network, builder_config)
```

**Comment by nvpohanh** [comment]
> In the document it says "0 is the major axis (excluding the batch dimension)". Does this only hold for implicit batch dimension network?

@842974287 Yes, this only holds for implicit batch dim mode. For explicit batch dim mode, axis 0 is just the batch dimension. We need to fix our documentation. Thanks for pointing this out.

**Comment by nvpohanh** [comment]
I have updated the docs internally. It will appear in future TensorRT versions. Thanks for reporting this!

I am going to close this issue for now. Please let me know if you have more questions. Thanks
