### ISSUE TITLE
about   Cuda Error in cuInt8::NCHWToNCHHW2 

### ISSUE THREAD

**Issue by zhanghongyong123456** [NVIDIA/TensorRT#1391]
My environment uses  win10  cuda10.2 cudnn 8.0.5.39 tensorRT 7.2.1.6 cuda10.2  python=3.7 pytorch=1.8.1 VS2019 ， 
![19](https://user-images.githubusercontent.com/48466610/126465604-eb233feb-2079-4efc-a254-f8bd04b3c83b.png)
I have tried cuda11.1 cudnn8.0 tensorRT7.4.1.6 and cuda10.1 cudnn7.6.5 TensorRT6.0.1.5. I am not sure how to fix this problem

**Comment by ttyio** [comment]
Hello @zhanghongyong123456 , Have you tried TRT 8.0GA? thanks!

**Comment by zhanghongyong123456** [comment]
> Hello @zhanghongyong123456 , Have you tried TRT 8.0GA? thanks!

No，I didn't try

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
