### ISSUE TITLE
Implement  Pixel Shuffle of Pytorch in TensorRT

### ISSUE THREAD

**Issue by thancaocuong** [NVIDIA/TensorRT#1393]
Hi. I want to implement pixel shuffle function in TensorRT. In detail, I want to reshape tensor from shape (8x2x2) to (2x2x2x2x2). So I use add_shuffle function and set the reshape to {2x2x2x2x2}. But I got an error below
```
Input dimensions [8,2,2] have volume 32 and output dimensions [2,2] have volume 4
```
So how should I do?
my code looks like
```
// pixel shuffle
// input shape is 8x2x2
IShuffleLayer *PixelShuffle(INetworkDefinition *network, ITensor &input, int scale_factor)
{
    auto pixel_shuffle_1 = network->addShuffle(input);
    auto inputDim = input.getDimensions();
    // get input dimensions
    // int batchsize = inputDim.d[0];
    int inChannels = inputDim.d[0];
    int inHeight = inputDim.d[1];
    int inWidth = inputDim.d[2];
    int outChannels = int(inChannels / (scale_factor * scale_factor));
    int outHeight = int(inHeight * scale_factor);
    int outWidth = int(inWidth * scale_factor);
    nvinfer1::Dims dims1{outChannels, scale_factor, scale_factor, inHeight, inWidth};
    pixel_shuffle_1->setReshapeDimensions(dims1);
    assert(pixel_shuffle_1 != nullptr);
    std::cout << "Done ps1" << std::endl;
    // permute and reshape
    auto pixel_shuffle_2 = network->addShuffle(*pixel_shuffle_1->getOutput(0));
    // tensorRT does not accept batch dimension
    pixel_shuffle_2->setFirstTranspose(nvinfer1::Permutation{0, 3, 1, 4, 2});
    pixel_shuffle_2->setReshapeDimensions(nvinfer1::DimsCHW(outChannels, outHeight, outWidth));
    assert(pixel_shuffle_2 != nullptr);
    return pixel_shuffle_2;
}
```

**Comment by owoshch** [comment]
Hi @thancaocuong! Did you manage to solve the issue?

**Comment by thancaocuong** [comment]
@owoshch Ow
 yes, I will post my code here. Wait me for a second.

**Comment by owoshch** [comment]
@thancaocuong Thank you for sharing the code!
Do you mind helping me with few things I didn't understand so far?

I'm trying to transfer to tensorrt a model that uses nn.PixelShuffle layer from Pytorch: https://github.com/Halmstad-University/SalsaNext/blob/master/train/tasks/semantic/modules/SalsaNext.py#L143

I don't get the `network` parameter in you pixel_shuffle function and how you initialize it. Also, it's not quite clear what libraries you use to import `add_reshape` and `trt`.

Thank you!

**Comment by thancaocuong** [comment]
@owoshch Im using Tensorrt Python API to implement network from scratch. You can refer to the repo named tensorrtx. Btw, I will try to implement the network defined under your link  you sent. I will put it here when I finish.
