### ISSUE TITLE
About ONNX INT8  dynamic range method

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [NVIDIA/TensorRT#14]
I want to use onnx int8 without calibration method .something i want to make sure about getting the dynamic range. I train a model use pytorch and export to onnx then run it on tensor RT.
First, when I run the model in pytorch as follow:
```python
model = detection_net()
model.load_state_dict(torch.load('detection_net_epoch200.pth'))
...
```

```python
def get_features_hook(self,input,output):
    print(output.min(),output.max())
    model.layer[1].register_forward_hook(get_features_hook)
    a = model(input_img)
...
```

the output of get_features_hook is the dynamic range?
Second, in the sample of sampleINT8API(D:\TensorRT-5.1.5.0\samples),resnet50_per_tensor_dynamic_range.txt,

```
...
gpu_0/conv1_1:5.43116007373
gpu_0/res_conv1_bn_1:8.69735834748
gpu_0/res_conv1_bn_2:8.69735834748
...
```

the content of this txt such as: `gpu_0/res_conv1_bn_1:8.69735834748, 8.69735834748` is the dynamic range? max or -max,which is it?

I'm a beginner of TensorRT, maybe these questions are too elementary.

**Comment by rajeevsrao** [comment]
resnet50_per_tensor_dynamic_range.txt contains the (symmetric) dynamic ranges for all the tensors in the ResNet50 ONNX model. For example the line "gpu_0/conv1_1:5.43116007373" means that the dynamic range for tensor "gpu_0/conv1_1" is -5.43116007373 to 5.43116007373.

To determine the dynamic range, you need to evaluate (either during training or by parsing validation dataset): M = absmax(tensor.min(), tensor.max()). The dynamic range is -M to M. You will need this (M) for every tensor, not just the output.

**Comment by guangdongliang** [comment]
> I want to use onnx int8 without calibration method .something i want to make sure about getting the dynamic range. I train a model use pytorch and export to onnx then run it on tensor RT.
> First, when I run the model in pytorch as follow:
> model = detection_net()
> model.load_state_dict(torch.load('detection_net_epoch200.pth'))
> ....
> ....
> def get_features_hook(self,input,output):
> print(output.min(),output.max())
> model.layer[1].register_forward_hook(get_features_hook)
> a = model(input_img)
> ...
> .....
> the output of get_features_hook is the dynamic range?
> Second, in the sample of sampleINT8API(D:\TensorRT-5.1.5.0\samples),resnet50_per_tensor_dynamic_range.txt,
> 
> ...
> gpu_0/conv1_1:5.43116007373
> gpu_0/res_conv1_bn_1:8.69735834748
> gpu_0/res_conv1_bn_2:8.69735834748
> .....
> the content of this txt such as: gpu_0/res_conv1_bn_1:8.69735834748, 8.69735834748 is the ynamic range? max or -max,which is it?
> 
> I'm a beginner of TensorRT, maybe these questions are too elementary.

have you finish " pytorch to tensorrt int8 without calibration "?  I am doing this work because I can not get good performance  with calibration(1500 images) and it is very time-consuming.

look forward to your replay !

**Comment by rmccorm4** [comment]
Hi @guangdongliang,

If you want to avoid doing calibration repeatedly, you can either save and make use of a calibration cache after the first time: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Int8/Calibrator.html#tensorrt.IInt8Calibrator.read_calibration_cache

Or you can look into "quantization aware training" in your training framework, here's a doc for Pytorch: https://pytorch.org/docs/stable/quantization.html

If you use "quantization aware training", I believe you don't need to do int8 calibration at all in TensorRT.
