### ISSUE TITLE
Program terminated with signal 8, Arithmetic exception.

### ISSUE THREAD

**Issue by alongwithyou** [NVIDIA/TensorRT#1400]
## Description

I have designed and implemented a computing lib which use streams as basic thread resource to compute our model, one stream for one thread

there are 2 different models, I initilzed 2 different computing objectives
and first model, I used 24 threads (24 streams)
and the second I used 6 threads (6 streams)

As aforementioned before,  the total pipeline is:

compute first model and then compute the next model

In the main thread, I want to lanuch more than one thread to execute the above pipeline, but it core dump

When I used only one pipeline thread, it runs properly.

core dump trace as follows 👍 

warning: Error querying the rpm file `/lib64/libcuda.so.1': nvidia-x11-drv-450.80.02-1.el7_9.elrepo.nosrc.rpm-debuginfo.x86_64
Missing separate debuginfo for /lib64/libcuda.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/81/b0b00f7a42f1dfb266364925e18e6524d0a1cf.debug
Core was generated by `./word-multi-threads -config demoEnv/scripts/us_char_cfg.txt'.
Program terminated with signal 8, Arithmetic exception.
#0  0x00007f8a3589f259 in nvinfer1::rt::cuda::volumeFused(nvinfer1::Dims const&, int) () from /ai-cephfs/Share/paraspace/trt7-related/TensorRT-7.2.2.3/lib/libnvinfer.so.7
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-44.el7.x86_64
(gdb) bt
#0  0x00007f8a3589f259 in nvinfer1::rt::cuda::volumeFused(nvinfer1::Dims const&, int) () from /ai-cephfs/Share/paraspace/trt7-related/TensorRT-7.2.2.3/lib/libnvinfer.so.7
#1  0x00007f8a358a2ab1 in nvinfer1::rt::cuda::CudnnFusedConvActRunner::execute(nvinfer1::rt::CommonContext const&, nvinfer1::rt::ExecutionParameters const&) const ()
   from /ai-cephfs/Share/paraspace/trt7-related/TensorRT-7.2.2.3/lib/libnvinfer.so.7
#2  0x00007f8a35829fd0 in nvinfer1::rt::ExecutionContext::enqueueInternal(CUevent_st**) () from /ai-cephfs/Share/paraspace/trt7-related/TensorRT-7.2.2.3/lib/libnvinfer.so.7
#3  0x00007f8a3582bbfc in nvinfer1::rt::ExecutionContext::enqueueV2(void**, CUstream_st*, CUevent_st**) ()
   from /ai-cephfs/Share/paraspace/trt7-related/TensorRT-7.2.2.3/lib/libnvinfer.so.7
#4  0x00007f8a51778c8f in RunInference (this=0x2dd1d3e0) at ../structure-utils/Trt-sample-dynamic-reshape.h:311
#5  sample::TrtSampleComputer::OnlineDynamicInferWorker (thread_id=<optimized out>, env=0x2045a400) at Trt-sample-dynamic-reshape.cc:368
#6  0x00007f8a5177cf13 in __invoke_impl<int, int (*)(int, sample::InferenceEnv*), int, sample::InferenceEnv*> (__f=<optimized out>)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:196
#7  __invoke<int (*)(int, sample::InferenceEnv*), int, sample::InferenceEnv*> (__fn=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/invoke.h:95
#8  _M_invoke<0, 1, 2> (this=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:244
#9  operator() (this=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:253
#10 std::thread::_State_impl<std::thread::_Invoker<std::tuple<int (*)(int, sample::InferenceEnv*), int, sample::InferenceEnv*> > >::_M_run (this=<optimized out>)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/thread:196
#11 0x00007f8a5211c408 in std::execute_native_thread_routine (__p=0x2dd2aeb0)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#12 0x00007f8a46f5b2ce in start_thread (arg=0x7f84417fb640) at pthread_create.c:463
#13 0x00007f8a166a372f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

## Environment

**TensorRT Version**: 7.2.2.3
**NVIDIA GPU**: v100
**NVIDIA Driver Version**: 11.0
**CUDA Version**: 10.2
**CUDNN Version**: 11.2
**Operating System**: centos 7.9
**Python Version (if applicable)**: python3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
