### ISSUE TITLE
Data and model files in samples

### ISSUE THREAD

**Issue by mungsoo** [NVIDIA/TensorRT#1402]
Hi, I had trouble in locating the data and model files used in samples. Where can I download them?

**Comment by ttyio** [comment]
Hello @mungsoo , which sample are you looking for? could you check the readme file in https://github.com/NVIDIA/TensorRT/tree/master/samples ? 
thanks

**Comment by mungsoo** [comment]
> Hello @mungsoo , which sample are you looking for? could you check the readme file in https://github.com/NVIDIA/TensorRT/tree/master/samples ? thanks

I found the data files in the TensorRT tar file. Thanks for the clarification!

**Comment by ttyio** [comment]
Closing and thanks
