### ISSUE TITLE
Structure sparsity over Tensorrt8

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/TensorRT#1403]
Hi,

I am expermenting the new structure sparsity feature in TensorRT8.
But after finetune get the weight pruned onnx file, I find tensorrt don't choose any layer in the onnx for sparsity accerlation.

The output like below:
[TensorRT] INFO: (Sparsity) Layers eligible for sparse math: Conv_0
[TensorRT] INFO: (Sparsity) TRT inference plan picked sparse implementation for layers:

The onnx only contain one conv layer, and its layer input/out as 1x64x2176x3840/1x64x2176x3840, while weight size is 64x64x3x3, bias size as <64>

**Comment by leiwen83** [comment]
I test resnext101_32x8d_sparse_onnx_v1/resnext101_32x8d_dense_onnx_v1 model with the trtexec as [the blog](https://developer.nvidia.com/blog/accelerating-inference-with-sparsity-using-ampere-and-tensorrt/)   said.
The sparse result as:
[07/28/2021-08:45:44] [I] Throughput: 501.618 qps
[07/28/2021-08:45:44] [I] Latency: min = 1.81982 ms, max = 3.1843 ms, mean = 2.05464 ms, median = 2.02905 ms, percentile(99%) = 2.29761 ms

The dense result as:
[07/28/2021-08:48:35] [I] Throughput: 498.367 qps
[07/28/2021-08:48:35] [I] Latency: min = 1.78882 ms, max = 2.14081 ms, mean = 2.06509 ms, median = 2.06612 ms, percentile(99%) = 2.10205 ms

I also use nsys to profile the kernel trace, but fail to see any different with the kernel used by sparse with the one used by dense model…

I am doing the experiment over 3090 with nvcr.io/nvidia/pytorch:21.07-py3
docker image. Any idea?

**Comment by nvpohanh** [comment]
@leiwen83 For sparsity math to be faster than dense math, typically the input and output channels need to be 256 or above. In your case, the input and output channels are only 64, so although TRT does recognize the sparsity pattern, the sparse kernel runs more slowly than the dense kernel, so TRT still uses dense kernel for that layer.

If you increase the input/output channel size to 256 or 1024, you should start to see the sparse kernels. Thanks

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
