### ISSUE TITLE
Multi-threaded model loading performance

### ISSUE THREAD

**Issue by evanbro** [NVIDIA/TensorRT#1405]
## Description

We are attempting to speed up TensorRT model load times by loading models in parallel to different GPUs. We see no model load time difference between multithreaded and sequential loading while multi-process loading sees substantial speedup. Is there some internal mechanism causing multithreaded loading to run sequentially?

```
Running multi-threaded load
real    0m32.279s
user    0m27.608s
sys     0m5.714s

Running sequential load
real    0m30.345s
user    0m25.024s
sys     0m4.964s

Running multi-process load
real    0m17.652s
user    0m12.687s
sys     0m4.539s
```

## Environment

**TensorRT Version**: 20.11
**NVIDIA GPU**: RTX A5000, Quadro RTX 5000
**NVIDIA Driver Version**: 460.91.03
**CUDA Version**: 11.0
**CUDNN Version**: 8.0.4
**Operating System**: Ubuntu 18.04.5 LTS
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.7.0
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:20.11-py3

## Relevant Files

https://github.com/maka-autonomous-robotic-systems/TensorRT/blob/evan/parallel-load/parallel_test.sh
https://github.com/maka-autonomous-robotic-systems/TensorRT/tree/evan/parallel-load/samples/opensource/trtexec_parallel

## Steps To Reproduce

1. Install samples dependencies 
2. Clone https://github.com/maka-autonomous-robotic-systems/TensorRT
3. Checkout branch evan/parallel-load
4. Run `git submodule update --init --recursive`
5. Run `./parallel_test.sh`

**Comment by nvpohanh** [comment]
@evanbro If I read your code, it looks like you are not just measuring the "engine deserialization" time but also the time to "parse the model" + "build the engine", right? TRT's builder is not thread safe, so I don't think we support building two engines in parallel in the same process.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
