### ISSUE TITLE
onnx parse error with pytorch-quantization onnx model

### ISSUE THREAD

**Issue by un-knight** [NVIDIA/TensorRT#1406]
## Description

Using the following script to export pytorch-quantization onnx model which references to https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html#export-to-onnx:

```python
from pytorch_quantization import nn as quant_nn
from pytorch_quantization import quant_modules
from pytorch_quantization import tensor_quant
quant_nn.TensorQuantizer.use_fb_fake_quant = True
import torch
from torchvision import models


quant_modules.initialize()
# quant_nn.QuantConv2d.default_quant_desc_weight = tensor_quant.QUANT_DESC_8BIT_PER_TENSOR

model = models.resnet18(pretrained=True)

torch.onnx.export(model, torch.randn(1, 3, 224, 224), "quant_resnet18.onnx", verbose=False, opset_version=10, enable_onnx_checker=False)
```

Then try to build tensorrt engine with onnx model:

```python
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
EXPLICIT_PRECISION = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_PRECISION)

builder = trt.Builder(TRT_LOGGER)
network = builder.create_network(EXPLICIT_BATCH | EXPLICIT_PRECISION)
config = builder.create_builder_config()
config.set_flag(trt.BuilderFlag.INT8)
config.max_workspace_size = trt_common.GiB(4)

parser = trt.OnnxParser(network, TRT_LOGGER)
with open(onnx_path, 'rb') as model:
    if not parser.parse(model.read()):
        print ('ERROR: Failed to parse the ONNX file.')
        for error in range(parser.num_errors):
            print (parser.get_error(error))
        return None

engine = builder.build_engine(network, config)
```

But got an error with dimension mismatch.

```bash
[TensorRT] ERROR: QuantizeLinear_7_quantize_scale_node: shift weights has count 64 but 3 was expected
ERROR: Failed to parse the ONNX file.
In node -1 (importDequantizeLinear): INVALID_NODE: Assertion failed: K == scale.count()
```

What's more, if I add `Linear` into `float_module_list`, which means do not quantize linear layer, then I export onnx model and try to build it, and got the following errors.

```bash
[TensorRT] VERBOSE: Original: 173 layers
[TensorRT] VERBOSE: After dead-layer removal: 173 layers
[TensorRT] VERBOSE: BinaryFusion: Fusing Flatten_313 with (Unnamed Layer* 170) [Shuffle]
[TensorRT] VERBOSE: Removing Flatten_313 + (Unnamed Layer* 170) [Shuffle]
[TensorRT] VERBOSE: After Myelin optimization: 171 layers
[TensorRT] VERBOSE: Convert layer type of Gemm_314 from FULLY_CONNECTED to CONVOLUTION
[TensorRT] VERBOSE: Removing shuffle_before_435
[TensorRT] VERBOSE: After scale fusion: 171 layers
[TensorRT] VERBOSE: Swap the layer type of GlobalAveragePool_312 from REDUCE to POOLING
[TensorRT] VERBOSE: Rotating DequantizeLinear_11_dequantize_scale_node over Conv_12
[TensorRT] INTERNAL ERROR: Assertion failed: !overlap(t->start, t->extent, f.first, f.second)
../builder/cudnnBuilderGraph.cpp:923
Aborting...
[TensorRT] ERROR: ../builder/cudnnBuilderGraph.cpp (923) - Assertion Error in checkSanity: 0 (!overlap(t->start, t->extent, f.first, f.second))

```

## Environment

**TensorRT Version**: 7.2.3.4
**Python Version (if applicable)**: 3.7.6
**PyTorch Version (if applicable)**: 1.9

## Relevant Files

- [quant_resnet18_pc.onnx](https://drive.google.com/file/d/1hpk1EplAudpIT_gIzI-tT1QNFJCrxYGI/view?usp=sharing), whose weights are quantized with per-channel
- [quant_resnet18_pt.onnx](https://drive.google.com/file/d/1HLcbGiE7_N44dBqc4nrP5t2H6Kz5r4VY/view?usp=sharing), whose weights are quantized with per-tensor
- [quant_resnet18_pt_wo_fc.onnx](https://drive.google.com/file/d/1uUXe2N8biLVREtr2aP3mE7brbnr5313C/view?usp=sharing), whose linear layer is not quantized and conv weights are quantized with per-tensor

**Comment by un-knight** [comment]
After update tensorrt to version `8.0.1.6`, the engine building error can be solved.

**Comment by ShaneYS** [comment]
I get the same error with TensorRT 7.1.3.0 on Xavier.
The tensorrt version is bundled with Xavier, so I can't upgrade tensorrt to 8.x.
How should I convert fake-quant onnx model to tensorrt engine?

**Comment by galagam** [comment]
@ShaneYS You can upgrade most to most recent [JetPack version](https://developer.nvidia.com/embedded/jetpack). 
Currently, this is JetPack 4.6.1 that includes TensorRT 8.2.
