### ISSUE TITLE
windows build TR_LIB rt

### ISSUE THREAD

**Issue by guods** [NVIDIA/TensorRT#141]
I build TensorRT 6.0 with cmake, it happen the error "RT_LIB_NOTFOUND",  what is the "RT_LIB" on line 181 in "cmakekist.txt"?

**Comment by rmccorm4** [comment]
Hi @guods,

What version of `cmake` are you running?

**Comment by oscarriddle** [comment]
I met the same problem. Found below lines:
```
########################################### DEPENDENCIES FOR BUILDING OUTSIDE OF NVIDIA ############################################
endif()

find_library_create_target(nvinfer nvinfer SHARED ${TRT_LIB_DIR})

if (NOT (NVINTERNAL OR NVPARTNER))
    find_library_create_target(nvuffparser nvparsers SHARED ${TRT_LIB_DIR})
endif()

find_library(CUDART_LIB cudart HINTS ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES lib lib64)
find_library(RT_LIB rt)

set(CUDA_LIBRARIES ${CUDART_LIB})
############################################################################################


```

so what is rt?

**Comment by rmccorm4** [comment]
Closing since no response from OP and I believe @oscarriddle solved above.

**Comment by ShiinaMitsuki** [comment]
> I met the same problem. Found below lines:
> 
> ```
> ########################################### DEPENDENCIES FOR BUILDING OUTSIDE OF NVIDIA ############################################
> endif()
> 
> find_library_create_target(nvinfer nvinfer SHARED ${TRT_LIB_DIR})
> 
> if (NOT (NVINTERNAL OR NVPARTNER))
>     find_library_create_target(nvuffparser nvparsers SHARED ${TRT_LIB_DIR})
> endif()
> 
> find_library(CUDART_LIB cudart HINTS ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES lib lib64)
> find_library(RT_LIB rt)
> 
> set(CUDA_LIBRARIES ${CUDART_LIB})
> ############################################################################################
> ```
> 
> so what is rt?
> I build TensorRT-OSS with cmake3.14.6, gcc7.4, TensorRT7, CUDA10.2, cudnn7.6,
> 
> OK, I got it. librt is a component in glibc, that located in the lib directory of built glibc.

Did you succeed compiling under windows?

**Comment by AlanLu0808** [comment]
> I met the same problem. Found below lines:
> 
> ```
> ########################################### DEPENDENCIES FOR BUILDING OUTSIDE OF NVIDIA ############################################
> endif()
> 
> find_library_create_target(nvinfer nvinfer SHARED ${TRT_LIB_DIR})
> 
> if (NOT (NVINTERNAL OR NVPARTNER))
>     find_library_create_target(nvuffparser nvparsers SHARED ${TRT_LIB_DIR})
> endif()
> 
> find_library(CUDART_LIB cudart HINTS ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES lib lib64)
> find_library(RT_LIB rt)
> 
> set(CUDA_LIBRARIES ${CUDART_LIB})
> ############################################################################################
> ```
> 
> so what is rt?
> I build TensorRT-OSS with cmake3.14.6, gcc7.4, TensorRT7, CUDA10.2, cudnn7.6,
> 
> OK, I got it. librt is a component in glibc, that located in the lib directory of built glibc.

So how to set RT_LIB in windows? It troubles a lot！Tks！

**Comment by ShiinaMitsuki** [comment]
> > I met the same problem. Found below lines:
> > ```
> > ########################################### DEPENDENCIES FOR BUILDING OUTSIDE OF NVIDIA ############################################
> > endif()
> > 
> > find_library_create_target(nvinfer nvinfer SHARED ${TRT_LIB_DIR})
> > 
> > if (NOT (NVINTERNAL OR NVPARTNER))
> >     find_library_create_target(nvuffparser nvparsers SHARED ${TRT_LIB_DIR})
> > endif()
> > 
> > find_library(CUDART_LIB cudart HINTS ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES lib lib64)
> > find_library(RT_LIB rt)
> > 
> > set(CUDA_LIBRARIES ${CUDART_LIB})
> > ############################################################################################
> > ```
> > 
> > 
> > so what is rt?
> > I build TensorRT-OSS with cmake3.14.6, gcc7.4, TensorRT7, CUDA10.2, cudnn7.6,
> > OK, I got it. librt is a component in glibc, that located in the lib directory of built glibc.
> 
> So how to set RT_LIB in windows? It troubles a lot！Tks！

I kinda remember there' no need for `RT_LIB` on windows.
indeed,  the compilation of PROTOBUF and ONNX(python needed) is all you need to use TensorRT binary.

**Comment by AlanLu0808** [comment]
> > > I met the same problem. Found below lines:
> > > ```
> > > ########################################### DEPENDENCIES FOR BUILDING OUTSIDE OF NVIDIA ############################################
> > > endif()
> > > 
> > > find_library_create_target(nvinfer nvinfer SHARED ${TRT_LIB_DIR})
> > > 
> > > if (NOT (NVINTERNAL OR NVPARTNER))
> > >     find_library_create_target(nvuffparser nvparsers SHARED ${TRT_LIB_DIR})
> > > endif()
> > > 
> > > find_library(CUDART_LIB cudart HINTS ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES lib lib64)
> > > find_library(RT_LIB rt)
> > > 
> > > set(CUDA_LIBRARIES ${CUDART_LIB})
> > > ############################################################################################
> > > ```
> > > 
> > > 
> > > so what is rt?
> > > I build TensorRT-OSS with cmake3.14.6, gcc7.4, TensorRT7, CUDA10.2, cudnn7.6,
> > > OK, I got it. librt is a component in glibc, that located in the lib directory of built glibc.
> > 
> > 
> > So how to set RT_LIB in windows? It troubles a lot！Tks！
> 
> I kinda remember there' no need for `RT_LIB` on windows.
> indeed, the compilation of PROTOBUF and ONNX(python needed) is all you need to use TensorRT binary.

What do u mean by "the compilation of PROTOBUF and ONNX(python needed) is all you need to use TensorRT binary"?

Does it mean I should compile PROTOBUF and ONNX first?
