### ISSUE TITLE
"Cuda Error in findFastestTactic" when implement 3D V-Net

### ISSUE THREAD

**Issue by Sanyuanliu** [NVIDIA/TensorRT#142]
Hi ,
I am running tensorrt inference with 3D V-Net converted from pytorch, when i set the input shape to [1,1,32,32,32], the result was correct. However, when i try the bigger shape [1,1,64,64,64], I get the following error:
`
 [E] [TRT] ../builder/cudnnBuilderUtils.cpp (354) - Cuda Error in findFastestTactic: 77 (an illegal memory access was encountered)

[E] [TRT] ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 77 (an illegal memory access was encountered)

terminate called after throwing an instance of 'nvinfer1::CudaError'
`
when i remove the torch.add layer, the network works normally.
My gpu is TITAN RTX with 24G memory, cuda 10.0, cudnn 7.6.3
Thanks

**Comment by anuar12** [comment]
@Sanyuanliu I got the same error!
I am trying to parse onnx'ed R3D-18 (from here: https://pytorch.org/docs/stable/torchvision/models.html#video-classification). I had to slightly modify it because onnx-tensorrt didn't take AdaptiveAvgPool3D. And then next I received the same error as yours.

TensorRT 6.0, ONNX==1.6.0, Opset=9, 2080 Ti

Did you manage to solve it?

**Comment by anuar12** [comment]
Found an issue on Nvidia Forums: https://devtalk.nvidia.com/default/topic/1065355/tensorrt/conv3d-with-strides-2-and-user-defined-padding

**Comment by rmccorm4** [comment]
Related to https://github.com/NVIDIA/TensorRT/issues/180#issuecomment-547714588

Waiting to hear back from the engineering team on this one.

**Comment by rmccorm4** [comment]
Hi @Sanyuanliu,

They found a bug in how they were [fusing certain layers](https://docs.nvidia.com/deeplearning/sdk/tensorrt-best-practices/index.html#layer-fusion) for this model. It should be fixed in the next release.

**Comment by Nioolek** [comment]
你好，我目前是在将3DCNN从Pytorch转换为onnx或者tensorrt以实现部署加速，但是目前pytorch的推理结果和onnx的推理结果一直不同，所以想请教一下你，我是在哪里遇到了问题。能添加我的微信：asda1231吗？
