### ISSUE TITLE
Silent fail with return code 1 during build_engine in TensorRT 8.0

### ISSUE THREAD

**Issue by jerryzh168** [NVIDIA/TensorRT#1420]
## Description

When I'm running build_engine on a quantized network, it fails with return code 1 but I did not see any error messages, how do I know what is wrong?

It has a few warnings:
```
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.1.0
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.0.5
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
```

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**: A100
**NVIDIA Driver Version**: ?
**CUDA Version**: ?
**CUDNN Version**: linked 8.2.1 loaded 8.0.5
**Operating System**: linux
**Python Version (if applicable)**: python3
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: master version
**Baremetal or Container (if so, version)**:

**Comment by jerryzh168** [comment]
I tried something else and here that still fails silently but now it has a new warning:
```
[TensorRT] WARNING: No implementation of layer add_2 obeys the requested constraints in strict mode. No conforming implementation was found i.e. requested layer computation precision and output precision types are ignored, using the fastest implementation.
```
not sure if this is related or not

**Comment by netaz** [comment]
Hi Jerry,

> I tried something else and here that still fails silently but now it has a new warning:
> 
> ```
> [TensorRT] WARNING: No implementation of layer add_2 obeys the requested constraints in strict mode. No conforming implementation was found i.e. requested layer computation precision and output precision types are ignored, using the fastest implementation.
> ```
> 
> not sure if this is related or not

This means that layer `add_2` was requested to run at some precision (I assume Int8) but a kernel implementation does not exist.   This should not happen in general and more logs will help.  Please enable verbose logging - something like this when you use Python:
```
logger = trt.Logger(trt.Logger.VERBOSE)
with trt.Builder(logger) as builder:
    ...
```

**Comment by jerryzh168** [comment]
Got some error messages now when building the engine: ERROR:2021-08-02 11:38:18 1495972:1516278 EventProfilerController.cpp:128] Thread 1516277 appears stuck!

**Comment by zhouyuangan** [comment]
@jerryzh168 Do you solve the problem? I meet the same error.

**Comment by jerryzh168** [comment]
this only appears occasionally, I don't have any conclusions yet, will let you know if I find anything

**Comment by ttyio** [comment]
Hello @jerryzh168 , are these still QAT models from your FX? Q/DQ is explicit precision for TRT, we don't have INT8/ mixed precision for all layers, could you share the repro that we can debug? thanks!

**Comment by jerryzh168** [comment]
sorry just saw this, I have upgraded TensorRT and no longer seeing this problem I think, maybe we can close this for now
