### ISSUE TITLE
'Assertion Error in nvinfer1::rt::task::trtSmToCask: 0 (Unsupported SM.)' problem, with RTX 3060, cuda 11.2, win10, cudnn 8.1

### ISSUE THREAD

**Issue by pustar** [NVIDIA/TensorRT#1428]
'Assertion Error in nvinfer1::rt::task::trtSmToCask: 0 (Unsupported SM.)' problem, with RTX 3060, cuda 11.2, win10, cudnn 8.1

Hi, I encounter the same problem on RTX 3060, getting the following error:
[V] [TRT] LegacySASSConvolution has no valid tactics for this config, skipping
[F] [TRT] Assertion failed: Unsupported SM.
C:\source\rtSafe\cuda\caskUtils.cpp:80
Aborting…

[E] [TRT] C:\source\rtSafe\cuda\caskUtils.cpp (80) - Assertion Error in nvinfer1::rt::task::trtSmToCask: 0 (Unsupported SM.)

Can you help me?

±----------------------------------------------------------------------------+
| NVIDIA-SMI 471.11 Driver Version: 471.11 CUDA Version: 11.4 |
|-------------------------------±---------------------±---------------------+
| GPU Name TCC/WDDM | Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 NVIDIA GeForce … WDDM | 00000000:01:00.0 On | N/A |
| 53% 50C P2 40W / 170W | 976MiB / 12288MiB | 1% Default |
| | | N/A |
±------------------------------±---------------------±---------------------+

Environment
TensorRT Version : 7.2.3.4
GPU Type : RTX 3060
Nvidia Driver Version : 471.11
CUDA Version : cuda11.2
CUDNN Version : 8.x
Operating System + Version : Windows 10

![image](https://user-images.githubusercontent.com/10677439/127993847-f1787642-40fe-4f0a-84f2-54012309c25a.png)

The code and error info are:(these codes can work fine on RTX 1070、2080 with CUDA 10.0, TensorRT 5.1, cudnn 7, win 10)
```

		void createEngine() {
                loadWTS(m_wtsModelFile);
		int input_c = INPUT_C;
		int input_h = INPUT_H;
		int input_w = INPUT_W;
		nvinfer1::IBuilder *builder = nvinfer1::createInferBuilder(m_logger);
		m_network = builder->createNetwork();
		nvinfer1::ITensor *input = m_network->addInput(m_inputBindingName.c_str(), nvinfer1::DataType::kFLOAT, nvinfer1::DimsCHW{ static_cast<int>(input_c),static_cast<int>(input_h), static_cast<int>(input_w) });

		Layers["input"] = input;

		Layers["conv1"] = trt_conv("input", "conv1.weight", "", 64, 7, 2, 3);
		Layers["bn1"] = trt_batchNorm("conv1", "bn1");
		Layers["relu"] = trt_activation("bn1", "relu");    // layer0  passed ok		
...
...
...
                Layers["layer4.1.conv1"] = trt_conv("layer4.0.eltwise1.relu", "layer4.1.conv1.weight", "", 512, 3, 1, 1);
		Layers["layer4.1.bn1"] = trt_batchNorm("layer4.1.conv1", "layer4.1.bn1");
		Layers["layer4.1.relu"] = trt_activation("layer4.1.bn1", "relu");
		Layers["layer4.1.conv2"] = trt_conv("layer4.1.relu", "layer4.1.conv2.weight", "", 512, 3, 1, 1);
		Layers["layer4.1.bn2"] = trt_batchNorm("layer4.1.conv2", "layer4.1.bn2");

		Layers["layer4.1.eltwise1"] = trt_eltwise("layer4.1.bn2", "layer4.0.eltwise1.relu", "sum");
		Layers["layer4.1.eltwise1.relu"] = trt_activation("layer4.1.eltwise1", "relu");

		Layers["AvgPool"] = trt_pool("layer4.1.eltwise1.relu", "avg", 7, 1, 0);
		Layers["fc0"] = trt_fc("AvgPool", "fc.0.weight", "fc.0.bias", 256);
		Layers["relu_0"] = trt_activation("fc0", "relu");
		Layers["fc3"] = trt_fc("relu_0", "fc.3.weight", "fc.3.bias", 2);

		Layers["fc3"]->setName(m_outputBindingName.c_str());
		m_network->markOutput(*Layers["fc3"]);


		builder->setMaxBatchSize(BloodBatchSize);// Parameter check failed at: engine.cpp::nvinfer1::rt::ExecutionContext::enqueue::292, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 8, but engine max batch size was: 4
		builder->setMaxWorkspaceSize(1 << 30);

		
		m_engine = builder->buildCudaEngine(*m_network);
		nvinfer1::IHostMemory *modelStream = m_engine->serialize();
		ofstream engineFile;
		engineFile.open(m_expectedTrtModelFile, ios_base::binary);
		engineFile.write(static_cast<const char*>(modelStream->data()), modelStream->size());
		engineFile.close();

		m_network->destroy();
		modelStream->destroy();
}
```

When I use TensorRT 8.0 for win 10 on RTX 3060, CUDA 11.2, the following problem occured:
![image](https://user-images.githubusercontent.com/10677439/127994008-41288268-09aa-47dc-8fbe-c876d1ffc33c.png)

![image](https://user-images.githubusercontent.com/10677439/127994036-610157cd-4ef1-40dd-a95c-cc6fcae872d7.png)

**Comment by ssggle** [comment]
I have encountered the same problem. The initialization pointer is null because the tensorrt path does not correspond. I hope it can help you

**Comment by 0oyyo0** [comment]
Has your problem been solved? How to solve it? I encountered the same problem on 3060. 
But with the same config could run correctly on 1050 and 2060.

**Comment by nvpohanh** [comment]
TRT 7.2 does not support such a new GPU (SM86). Please use newer TensorRT versions. Thanks

**Comment by nvpohanh** [comment]
I am going to close this due to >2wk of no action. Please feel free to reopen if this issue still exists. Thanks!
