### ISSUE TITLE
The ExecutionContext must be destroyed before the corresponding ICudaEngine?

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/TensorRT#143]
It seems trt6.0.1.5 has involved the restriction. In trt5.1.5.0, the ExecutionContext can be destroyed after its corresponding ICudaEngine.

**Comment by rajeevsrao** [comment]
@xiaocenxiaocen yes, the ExecutionContexts are assumed to be invalid when the Engine object destroyed (i.e., they must be destroyed prior to it).
