### ISSUE TITLE
question about how cuda context works

### ISSUE THREAD

**Issue by menglin0320** [NVIDIA/TensorRT#1430]
I'm trying to optimize the inference throughput for a model with dynamic input. the size difference between samples can be quite significant. So I want to avoid padding and do something similar to batching,  I want to run several samples concurrently with the same engine. The inference time will still be bottlenecked by the biggest sample in the batch but a lot of flops are saved, also it prevents possible performance drop from padding too much.

From what I learned If works are in different cuda contexts there is no real parallel working, instead it is just better scheduling. Also one process can only have one cuda context and threads can share contexts.  But I didn't find anything talking about how to share one context among threads yet.

When there is problem on context in a threading, most of the solutions just suggest to use 
```
Device.make_context()
```
 There's not much difference between multithreading and multiprocess then. If each thread owns it's own context then there is no real concurrent work.

Is my understanding right and anyone knows how to do the thing I want to do correctly.

If possible I want a solution that works on python. Thank you guys very much.

**Comment by menglin0320** [comment]
@ttyio

**Comment by ttyio** [comment]
CC @pranavm-nvidia , 

@menglin0320 ,could you check the open source polygraphy multiple thread code https://github.com/NVIDIA/TensorRT/blob/master/tools/Polygraphy/tests/backend/trt/test_runner.py#L80

the doc is in https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/index.html

BTW there is also triton you can play with https://github.com/triton-inference-server/server 

Thanks

**Comment by menglin0320** [comment]
Thanks ttyio, with polygraphy may be we can solve the context problem. But unfortunately I just found that python has GIL, even if we can share the context, python just doesn't have "real" multithreading. Is there any other tool?

**Comment by menglin0320** [comment]
okay, and do you know if polygraphy shares context between threads? Seems that we don't need to deal with context with polygraphy from the tests in https://github.com/NVIDIA/TensorRT/blob/master/tools/Polygraphy/tests/backend/trt/test_runner.py#L80

**Comment by pranavm-nvidia** [comment]
Yes, it does. It uses the default CUDA context, and I think you should be able to do something similar outside of Polygraphy too (you could use the [CUDA utilities from Polygraphy](https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/cuda/toc.html) if it helps).

**Comment by menglin0320** [comment]
That's great, I'll try it.

**Comment by menglin0320** [comment]
Hi all, I tried to use polygraphy to do the multithreading but the time required to run inference did not decrease
I tried to profile the result with nsight and it shows that the trt execute is not paralleled, you can see it from the screen shot.
![Screenshot from 2021-08-12 11-22-24](https://user-images.githubusercontent.com/14263971/129223943-144314f8-c67b-46e9-a4a1-66d03d1471ce.png)

the function in the thread is
```
    device_input_input = cuda.DeviceBuffer((np_im_tensor.size, engine.max_batch_size), dtype=np.float32)
    device_output = cuda.DeviceBuffer((int(length), lexicon_size), dtype=np.float32)
    copy_start_time = time.time()
    device_input_input.copy_from(np_im_tensor)
    print('{} copy takes {}'.format(length, time.time() - copy_start_time))
    execute_start_time = time.time()
    print('{} execute start'.format(length))
    context.execute_v2(bindings=[int(device_input_input.address()), int(device_output.address())])
    print('{} execute end time {}'.format(length, time.time() - execute_start_time))
```
Also I defined n_stream IExecutionContext and streams
```
    contexts = [engine.create_execution_context() for _ in range(max_streams)]
    streams = [cuda.Stream() for _ in range(max_streams)]
```

Here cuda is from polygraphy. Is there anything else I need to do to get real concurrent work? The trt version is 7.2.2-1+cuda11.1 and I'm using dynamic size input

**Comment by pranavm-nvidia** [comment]
@menglin0320 Could you try that with TRT 8? 

IIRC there was a bug in TRT 7.2 with `execute_v2` and multithreading. You could also try `execute_async_v2` instead to work around it. 

(also, a side note: you'd probably want to move the memory allocations outside the inference loop)

**Comment by menglin0320** [comment]
After some work and some modification to adept with multiple profiles I run in to 
```
[TensorRT] INTERNAL ERROR: [resources.cpp::~ScopedCudaEvent::438] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
```
I didn't modify my original code a lot.
```
def run_inference(np_im_tensor, host_output, length, context, stream):
    device_input_input = cuda.DeviceArray((np_im_tensor.size, engine.max_batch_size), dtype=np.float32)
    device_output = cuda.DeviceArray((int(length), lexicon_size), dtype=np.float32)
    copy_start_time = time.time()
    device_input_input.copy_from(np_im_tensor, stream = stream)
    print('{} copy takes {}'.format(length, time.time() - copy_start_time))
    execute_start_time = time.time()
    print('{} execute start'.format(length))
    context.execute_async_v2(bindings=[int(device_input_input.ptr), int(device_output.ptr)], stream_handle = stream.ptr)
    print('{} execute end time {}'.format(length, time.time() - execute_start_time))
    # exit()
    device_output.copy_to(host_output)
```
```
profiles = [builder.create_optimization_profile() for _ in range(0,5)]

[profile.set_shape("input", small, optimal, big) for profile in profiles]
for profile in profiles:
    trt_config.add_optimization_profile(profile)
```
```
contexts[i].set_optimization_profile_async(i, streams[i].ptr)
streams[i].synchronize()
contexts[i].set_binding_shape(2 * i, (1, 1, 32, w))
```

Here are the parts I modified or added after modifying to trt8

**Comment by pranavm-nvidia** [comment]
@menglin0320 One thing I noticed is that the device-to-host copy at the end doesn't use the stream; it should be:
```py
    device_output.copy_to(host_output, stream)
```

Also , `engine.max_batch_size` is deprecated, and might be `-1` or `0` in your case, so may want to double check that. 

Besides that, could you post more of/all your code? It's a little hard to tell what could be wrong just from the snippets.

**Comment by menglin0320** [comment]
```
def build_engine(onnx_path):

    TRT_LOGGER = trt.Logger()
    builder = trt.Builder(TRT_LOGGER)
    network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
    parser = trt.OnnxParser(network, TRT_LOGGER)
    trt_config = builder.create_builder_config()
    print('platform_has_fast_fp16: {}'.format(builder.platform_has_fast_fp16))
    # if builder.platform_has_fast_fp16:
    #     builder.fp16_mode = True
    with open(onnx_path, 'rb') as model:
        print('Beginning ONNX file parsing')
        parser.parse(model.read())
    print('Completed parsing of ONNX file')

    profiles = [builder.create_optimization_profile() for _ in range(0,max_streams)]

    [profile.set_shape("input", small_size, optimal_size, big_size) for profile in profiles]
    for profile in profiles:
        trt_config.add_optimization_profile(profile)

    trt_config.max_workspace_size = 1 << 30
    engine = builder.build_engine(network, config=trt_config)
    return engine


def run_inference(np_im_tensor, host_output, length, device_input_input, device_output, context, stream):
    copy_start_time = time.time()
    device_input_input.copy_from(np_im_tensor, stream = stream)
    execute_start_time = time.time()
    context.execute_async_v2(bindings=[int(device_input_input.ptr), int(device_output.ptr)], stream_handle = stream.ptr)
    device_output.copy_to(host_output, stream = stream)


if __name__ == '__main__':
    engine = build_engine(onnx_path)
    max_streams = 5
    ims_dict = load_im_dict(im_folder_path)
    contexts = [engine.create_execution_context() for _ in range(max_streams)]
    streams = [cuda.Stream() for _ in range(max_streams)]
    total_start_time = time.time()
    for binding in engine:
        print(engine.get_binding_shape(binding))
    im_paths = list(ims_dict.values())[:10]
    batched_im_paths = []
    count = 0
    batch_im_paths = []
    ## simple algorithm to batch im_paths
    for batch_im_paths in batched_im_paths:
        device_outputs = []
        host_outputs = []
        ims = []
        length_list = []
        ws = []
        threads = []

        for i, im_path in enumerate(batch_im_paths):
            ##preprocess im and get out length of the dynamic dim code

        for i, (np_im_tensor, length, w) in enumerate(zip(ims, length_list, ws)):
            contexts[i].set_optimization_profile_async(i, streams[i].ptr)
            streams[i].synchronize()
            contexts[i].set_binding_shape(2 * i, cur_input_size)
            # print(context.get_binding_shape(0))
            host_output = np.zeros((int(length), lexicon_size), dtype=np.float32)
            host_outputs.append(host_output)
            device_input_input = cuda.DeviceArray((np_im_tensor.size, 1), dtype=np.float32)
            device_output = cuda.DeviceArray((int(length), lexicon_size), dtype=np.float32)
            cur_thread = threading.Thread(target=run_inference,
                                          args=(np_im_tensor, host_output, length, device_input_input, device_output, contexts[i], streams[i]))
            # cur_thread.start()
            threads.append(cur_thread)
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()
        for stream in streams:
            stream.synchronize()
        # exit()
        
    ##postprocess, doesn't matter here
```
here is fuller code, ## means this part of code is omitted, also this code is not runnable.

Here are some error message:
```
errors [TensorRT] ERROR: [executionContext.cpp::enqueueInternal::322] Error Code 3: Internal Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::322, condition: bindings[x] != nullptr
)
[TensorRT] ERROR: [executionContext.cpp::enqueueInternal::322] Error Code 3: Internal Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::322, condition: bindings[x] != nullptr
)
47 execute end
93 execute end
[TensorRT] ERROR: [convolutionRunner.cpp::executeConv::454] Error Code 1: Cudnn (CUDNN_STATUS_BAD_PARAM)
11 execute end time 0.0008933544158935547
[TensorRT] ERROR: [convolutionRunner.cpp::executeConv::454] Error Code 1: Cudnn (CUDNN_STATUS_BAD_PARAM)
```

**Comment by pranavm-nvidia** [comment]
Ah I see the issue; some background: each profile has separate bindings. So for example, if you have 1 input, 1 output, and 2 profiles, the bindings are laid out as follows:
```
Binding 0: input [profile 0]
Binding 1: output [profile 0]

Binding 2: input [profile 1]
Binding 3: output [profile 1]
```
(try saving the engine and running `polygraphy inspect model /path/to/engine` for a clearer picture of the whole thing, [example here](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/cli/inspect/02_inspecting_a_tensorrt_engine))

Because of this, you need to offset the bindings by `profile_idx * bindings_per_profile`. You can see how Polygraphy does it [here](https://github.com/NVIDIA/TensorRT/blob/master/tools/Polygraphy/polygraphy/backend/trt/runner.py#L222). `start_binding` is calculated [here](https://github.com/NVIDIA/TensorRT/blob/eb8442dba3c9e85ffb77e0d870d2e29adcb0a4aa/tools/Polygraphy/polygraphy/backend/trt/util.py#L484).

**Comment by menglin0320** [comment]
It seem to work, though on my machine with 2080 super there's strange bug, on a machine with 3090 it works and gives a little bit improvements.
But when I want to make sure it works with nsys
I got 
```
[libprotobuf ERROR /build/agent/work/20a3cfcd1c25021d/Imports/Source/ProtoBuf/protobuf-3_10_0/src/google/protobuf/message_lite.cc:122] Can't parse message of type "QuadDAnalysis.Data.SessionState" because it is missing required fields: GenericEventMapEntries[1].Domain, GenericEventMapEntries[2].Domain, GenericEventMapEntries[3].Domain
``` 
when trying to open the qdrep file
I ran this line to get the qdrep line:
```
/usr/local/cuda-11/bin/nsys profile --gpuctxsw true --cuda-memory-usage true --force-overwrite true --output multithread python onnx2tensorrt_multithread.py
```

**Comment by menglin0320** [comment]
I see two things that are very mysterious
1. polygraphy is a lot slower than pycuda:
```
#with pycuda
copy_from_start: 1.3113021850585938e-05
exe time: 0.0038957595825195312
copy to time: 4.76837158203125e-07

#with polygraphy
copy_from_start: 0.00028204917907714844
exe time: 0.0056056976318359375
copy to time: 0.0004527568817138672
```
There are other modules that used pycuda in this program, will that influence the performance?
also as you can see the exe time is very different:
```
#quick code is:
        device_input_input = cuda.DeviceArray((im.size, 1), np.float32)
        device_output = cuda.DeviceArray((int(length), lexicon_size), np.float32)
        device_input_inputs.append(device_input_input)
        device_outputs.append(device_output)
        # cur_thread = threading.Thread(target=run_inference,
        #                               args=(
        #                                   im, host_output, device_input_input, device_output, contexts[ind],
        #                                   streams[ind], ind))
        # threads.append(cur_thread)
        # cur_thread.start()
        run_inference(im, host_output, device_input_input, device_output, contexts[ind],streams[ind], ind)


#slower code is:
        device_input_input = cuda.DeviceArray((im.size, 1), np.float32)
        device_output = cuda.DeviceArray((int(length), lexicon_size), np.float32)
        device_input_inputs.append(device_input_input)
        device_outputs.append(device_output)
        cur_thread = threading.Thread(target=run_inference,
                                      args=(
                                          im, host_output, device_input_input, device_output, contexts[ind],
                                          streams[ind], ind))
        threads.append(cur_thread)
        cur_thread.start()
        # run_inference(im, host_output, device_input_input, device_output, contexts[ind],streams[ind], ind)
    # for thread in threads:
    #     thread.start()
    for thread in threads:
        thread.join()
    for stream in streams:
        stream.synchronize()

```
Is it because of pycuda, should polygraphy be this slow? input size is about 32 * 320

**Comment by pranavm-nvidia** [comment]
@menglin0320 It is possible there are overheads in `copy_from`/`copy_to`, which I've been working on improving for the next release. I'm not sure why the inference time is also so much slower though. 

If PyCUDA works better, you should be able to use that. I think it would work if you use the default context (i.e. the one created by `pycuda.autoinit`) across threads.

**Comment by menglin0320** [comment]
I don't think in this time using multithread trt in python is a good idea. For some reason beyond my knowledge, everything is slower in a thread even if there's only one thread.
I posted a question on stackoverflow and python forum since I feel that it can only be solved by an expert who knows details about how python threading works. I used a profile tool yappi to profile the threads.
Here is the link to the stackoverflow post: https://stackoverflow.com/questions/68869093/question-about-python-multithreading-overheads

**Comment by menglin0320** [comment]
okay finally I made it by writing the tensorrt code in c++ and link the modules with cython.
Can I ask some more basic things about c++ since I'm somewhat a newbee to really use c++ for a bigger project?
why when using smart ptr for context we need the newly defined deleter?
```
struct InferDeleter
{
    template <typename T>
    void operator()(T* obj) const
    {
        delete obj;
    }
};
```
Also tensorrt8 prefer us to define the Ihostmemory then deserialize it to have the engine. What is the benefit?

**Comment by pranavm-nvidia** [comment]
@menglin0320 The deleter is left over from when TensorRT did not expose the destructor publicly. Previously, the body of the deleter would have been:
```cpp
obj->destroy();
```

The deleter is no longer needed, and you can use smart pointers with the default deleter now (e.g. `std::unique_ptr<nvinfer1::IBuilder>`). 

Regarding your second question, I assume you're referring to the deprecation of `buildEngineWithConfig`. I'm not entirely sure on the motivation behind that, but I'll ask around and get back to you.

**Comment by menglin0320** [comment]
thx

**Comment by pranavm-nvidia** [comment]
To answer your second question, the motivation was to keep the runtime light-weight by moving the engine serialization code into the optimizer/builder.

**Comment by menglin0320** [comment]
Thx, sorry to bother again
When we try to have multiple optimization profile for another model we developed. We get
```
[TensorRT] ERROR: 2: [standardEngineBuilder.cpp::makeEngineFromGraph::1288] Error Code 2: Internal Error (Assertion engineRegions.count(it->name) == 0 failed.)
```
The code is 
```
profiles = [builder.create_optimization_profile() for _ in range(0, 5)]
for profile in profiles:
    profile.set_shape("input", (1, 1, height, width_min), (1, 1, height, width_optim), (1, 1, height,  width_max))
    profile.set_shape("input_mask", (1, 1, height, width_min), (1, 1, height, width_optim), (1, 1, height, width_max))

for profile in profiles:   
    trt_config.add_optimization_profile(profile)
    engine = builder.build_engine(network, config=trt_config)
```
The model has two inputs and two outputs, is it the reason for the failure
I can not find anything related to the assertion failure on google so I can only ask the question here I guess.

**Comment by menglin0320** [comment]
I don't think there's enough information for debugging, I'll open another question on a forum

**Comment by iammeizu** [comment]
> Thx, sorry to bother again When we try to have multiple optimization profile for another model we developed. We get
> 
> ```
> [TensorRT] ERROR: 2: [standardEngineBuilder.cpp::makeEngineFromGraph::1288] Error Code 2: Internal Error (Assertion engineRegions.count(it->name) == 0 failed.)
> ```
> 
> The code is
> 
> ```
> profiles = [builder.create_optimization_profile() for _ in range(0, 5)]
> for profile in profiles:
>     profile.set_shape("input", (1, 1, height, width_min), (1, 1, height, width_optim), (1, 1, height,  width_max))
>     profile.set_shape("input_mask", (1, 1, height, width_min), (1, 1, height, width_optim), (1, 1, height, width_max))
> 
> for profile in profiles:   
>     trt_config.add_optimization_profile(profile)
> engine = builder.build_engine(network, config=trt_config)
> ```
> 
> The model has two inputs and two outputs, is it the reason for the failure I can not find anything related to the assertion failure on google so I can only ask the question here I guess.

met the same problem when use trt c++ api, you can use only one profile to avoid this problem. or update to trt8.2 GA version.
