### ISSUE TITLE
(Q&A)Is there a python version TensorRT config flag which is same with setProfileStream in C/C++ TensorRT?

### ISSUE THREAD

**Issue by linmuchuiyang** [NVIDIA/TensorRT#1435]
We know we could set setProfileStream with the IBuilderConfig within in C/C++ TensorRT? However, I did not find a same function in Python TRT.  
We could use config.profile_stream in Python TensorRT to pass a int handle of profile stream. But it's not a direct stream handle.

**Comment by pranavm-nvidia** [comment]
Not quite sure what you mean; `config.profile_stream` does accept a CUDA stream handle. 
e.g. with a PyCUDA stream, you would do: `config.profile_stream = stream.handle`

**Comment by linmuchuiyang** [comment]
Does the config.profile_stream(Python TensorRT) is the same function with setProfileStream(C/C++ TensorRT)?

**Comment by pranavm-nvidia** [comment]
Yes, you can see the implementation [here](https://github.com/NVIDIA/TensorRT/blob/master/python/src/infer/pyCore.cpp#L223). It just calls `setProfileStream`:
```cpp
self.setProfileStream(reinterpret_cast<cudaStream_t>(streamHandle));
```
