### ISSUE TITLE
TensorRT for Cuda 11.4 ?

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA/TensorRT#1438]
## Description

Failed to build this [github TensorRT](https://github.com/NVIDIA/TensorRT) from source .

## Environment

**TensorRT Version**: N/A. There is NO TensorRT for Cuda 11.4 yet.
**NVIDIA GPU**: NVIDIA GeForce 2080 Ti
**NVIDIA Driver Version**: 470.57.02
**CUDA Version**: 11.4.1
**CUDNN Version**: 8.2.2
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: 2.7.0
**PyTorch Version (if applicable)**: 1.10.0
**Baremetal or Container (if so, version)**:  N/A

## Relevant Files

[parsers/onnx/getSupportedAPITest](https://github.com/onnx/onnx-tensorrt/blob/7d4f86d540738be76da0fe41bed401f4ce67614c/getSupportedAPITest.cpp) ???

## Steps To Reproduce

just build [github TensorRT](https://github.com/NVIDIA/TensorRT) from source.

```console
[ 58%] Linking CXX executable getSupportedAPITest
cd ....../TensorRT/build/parsers/onnx && /usr/bin/cmake -E cmake_link_script CMakeFiles/getSupportedAPITest.dir/link.txt --verbose=1
/usr/local/bin/g++ -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -Wall -Wno-deprecated-declarations -Wno-unused-function -O3 -DNDEBUG CMakeFiles/getSupportedAPITest.dir/getSupportedAPITest.cpp.o CMakeFiles/getSupportedAPITest.dir/ModelImporter.cpp.o -o getSupportedAPITest  /usr/local/lib/libprotobuf.so libnvonnxparser_static.a -lpthread -ldl third_party/onnx/libonnx_proto.a /usr/local/lib/libprotobuf.so -lpthread /usr/local/lib/libprotobuf.so -lTENSORRT_LIBRARY_INFER-NOTFOUND -lTENSORRT_LIBRARY_INFER_PLUGIN-NOTFOUND 
/usr/bin/ld: cannot find -lTENSORRT_LIBRARY_INFER-NOTFOUND
/usr/bin/ld: cannot find -lTENSORRT_LIBRARY_INFER_PLUGIN-NOTFOUND
collect2: error: ld returned 1 exit status
make[2]: *** [parsers/onnx/CMakeFiles/getSupportedAPITest.dir/build.make:121: parsers/onnx/getSupportedAPITest] Error 1
make[2]: Leaving directory '....../TensorRT/build'
make[1]: *** [CMakeFiles/Makefile2:1013: parsers/onnx/CMakeFiles/getSupportedAPITest.dir/all] Error 2
make[1]: Leaving directory '....../TensorRT/build'
make: *** [Makefile:159: all] Error 2
```

**Comment by ttyio** [comment]
Hello @jiapei100 ,could you use the branch `release/8.0` and follow the readme in this branch? thanks

**Comment by xkszltl** [comment]
@ttyio 
Will there be any pre-built binary for 11.4?
Does the 11.3 binary works with CUDA 11.4?
What's the compatibility mapping of those version?

**Comment by ttyio** [comment]
@xkszltl , could you wait for 11.4 build in next release, it is available in around 1 month.

And TRT static link to cuda runtime, so the run of 11.3 binary on CUDA 11.4 is provided by CUDA compatibility https://docs.nvidia.com/deploy/cuda-compatibility/, you can find the detail in this doc, thanks

**Comment by xkszltl** [comment]
Sure.
Didn't know it's statically linked before, thanks for the clarification!

**Comment by ttyio** [comment]
Closing since there is no issue, thanks
