### ISSUE TITLE
Error message reports strange code location

### ISSUE THREAD

**Issue by thinhphamtechvico** [NVIDIA/TensorRT#144]
Hi all,
With Jetpack4.2.2 (TRT5.1.5), I tried to run my own script and got an error message:
`python3: nmsPlugin.cpp:139: virtual void nvinfer1::plugin::DetectionOutput::configureWithFormat(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, nvinfer1::DataType, nvinfer1::PluginFormat, int): Assertion 'numPriors * numLocClasses * 4 == inputDims[param.inputOrder[0]].d[0]' failed.`
I tried to look up this code in TRT github  (branch release/5.1) but noticed that code doesn't exist. Can anyone please help me?
Thanks

**Comment by rmccorm4** [comment]
Hi @thinhphamtechvico,

This repo is just the open source components of TensorRT, and they may be ahead of what comes with the full TensorRT release via DevZone / JetPack (for Jetson).

You can look at https://github.com/NVIDIA/TensorRT/tree/master/plugin/nmsPlugin for some insight, but it looks like it doesn't line up exactly with the code in Jetpack 4.2.2 based on your error message. Unfortunately, I don't think the OSS components supported Jetson products yet, see related issue: https://github.com/NVIDIA/TensorRT/issues/81
