### ISSUE TITLE
How to enable DEBUG_PRINTF macro?

### ISSUE THREAD

**Issue by ashkanaev** [NVIDIA/TensorRT#145]
Hi everyone! 
There are a lot of DEBUG_PRINTF macros which could be very informative during troubleshooting, but at debug unavailable.

How to enable  DEBUG_PRINTF macro?

**Comment by rmccorm4** [comment]
Hi @ashkanaev,

I haven't tried this myself but I believe it can be turned on by adding the `-DDEBUG` flag when building, or in this case, when calling `cmake ...` as described in the README, similar to flags like `-DTRT_LIB_DIR`: https://github.com/NVIDIA/TensorRT#building-the-tensorrt-oss-components

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.
