### ISSUE TITLE
error: 'scatterNDInference' was not declared in this scope & note: suggested alternative: 'roiInference'

### ISSUE THREAD

**Issue by MichaelWU0726** [NVIDIA/TensorRT#1451]
## Description

```bash
TensorRT/plugin/scatterPlugin/scatterPlugin.cpp: In member function 'virtual int32_t nvinfer1::plugin::ScatterND::enqueue(const nvinfer1::PluginTensorDesc*, const nvinfer1::PluginTensorDesc*, const void* const*, void* const*, void*, cudaStream_t)':
TensorRT/plugin/scatterPlugin/scatterPlugin.cpp:175:5: error: 'scatterNDInference' was not declared in this scope
     scatterNDInference(stream, transformCoeff,
     ^~~~~~~~~~~~~~~~~~
TensorRT/plugin/scatterPlugin/scatterPlugin.cpp: In member function 'virtual int32_t nvinfer1::plugin::ScatterND::enqueue(const nvinfer1::PluginTensorDesc*, const nvinfer1::PluginTensorDesc*, const void* const*, void* const*, void*, cudaStream_t)':
TensorRT/plugin/scatterPlugin/scatterPlugin.cpp:175:5: error: 'scatterNDInference' was not declared in this scope
     scatterNDInference(stream, transformCoeff,
     ^~~~~~~~~~~~~~~~~~
TensorRT/plugin/scatterPlugin/scatterPlugin.cpp:175:5: note: suggested alternative: 'roiInference'
     scatterNDInference(stream, transformCoeff,
     ^~~~~~~~~~~~~~~~~~
     roiInference
TensorRT/plugin/scatterPlugin/scatterPlugin.cpp:175:5: note: suggested alternative: 'roiInference'
     scatterNDInference(stream, transformCoeff,
     ^~~~~~~~~~~~~~~~~~
     roiInference
plugin/CMakeFiles/nvinfer_plugin_static.dir/build.make:82: recipe for target 'plugin/CMakeFiles/nvinfer_plugin_static.dir/scatterPlugin/scatterPlugin.cpp.o' failed
make[2]: *** [plugin/CMakeFiles/nvinfer_plugin_static.dir/scatterPlugin/scatterPlugin.cpp.o] Error 1
CMakeFiles/Makefile2:1045: recipe for target 'plugin/CMakeFiles/nvinfer_plugin_static.dir/all' failed
make[1]: *** [plugin/CMakeFiles/nvinfer_plugin_static.dir/all] Error 2
```

## Environment

**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: 2080TI
**NVIDIA Driver Version**: 460.80
**CUDA Version**: 11.0 update1
**CUDNN Version**: 8.0
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.7.8
**Baremetal or Container (if so, version)**: docker 19.04

## Relevant Files

1. [The branch TensorRT 7.2](https://github.com/NVIDIA/TensorRT/tree/release/7.2)
2. [The scatterPlugin in TensorRT 8.0](https://github.com/NVIDIA/TensorRT/tree/release/8.0/plugin/scatterPlugin)

## Steps To Reproduce

When transform onnx to tensorrt, operator `scatterND` is unsupported by onnx parser in tensorrt v7.2 and i found it is supported in v8.0. So i tried to migrate the operator in v8.0 to v7.2.

1. I copy the directory `plugin/scatterPlugin` in v8.0 into the directory `plugin` in v7.2 and delete `noexcept` in `scatterPlugin.cpp`  
2. Register the new plugin: In `InferPlugin.cpp`, add the code `#include "scatterPlugin.h"` and `initializePlugin<nvinfer1::plugin::ScatterNDPluginCreator>(logger, libNamespace);` in the function `bool initLibNvInferPlugins(void* logger, const char* libNamespace)`. And in `CMakeLists.txt` add `scatterPlugin` to `PLUGIN_LISTS`.  
3. Make project: create the directory `build` in root directory of the project and switch into it.
    ```bash
    cmake .. -DBUILD_PARSERS=ON -DBUILD_SAMPLES=OFF -DTRT_LIB_DIR=$TENSORRT_LIB_PATH -DTRT_BIN_DIR=`pwd`/out -DBUILD_PLUGINS=ON
    ```

Thanks for your help !

**Comment by anasmajid** [comment]
Hi Michael,

In transferring the plugin over from v8.0 to v7.2, you might have not transferred the declaration of the scatterND plugin. Please add this declaration to your v7.2 directory in plugin/common/kernel.h:

`pluginStatus_t scatterNDInference(cudaStream_t stream, int* outputDims, int nOutputDims, int sliceRank, int nRows, int rowSize, int CopySize, int sizeOfElementInBytes, const void* index, const void* updates, const void* data, void* output, void* workspace);`

You can find this here:
https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/kernel.h#L94

**Comment by MichaelWU0726** [comment]
> Hi Michael,
> 
> In transferring the plugin over from v8.0 to v7.2, you might have not transferred the declaration of the scatterND plugin. Please add this declaration to your v7.2 directory in plugin/common/kernel.h:
> 
> `pluginStatus_t scatterNDInference(cudaStream_t stream, int* outputDims, int nOutputDims, int sliceRank, int nRows, int rowSize, int CopySize, int sizeOfElementInBytes, const void* index, const void* updates, const void* data, void* output, void* workspace);`
> 
> You can find this here:
> https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/kernel.h#L94

1. It works but I am confused that why a declaration is needed after `initLibNvInferPlugins` in register plugins. 
2. I use the following command to make `Parser` and `Plugin`. Why the plugin `libmyelin` in the directory `target/x86_64-linux-gnu` was build into `tensorrt/lib` and i don't need the plugin `libmyelin` ?
`cmake .. -DBUILD_SAMPLES=OFF -DTRT_LIB_DIR=/usr/local/tensorrt/lib -DTRT_OUT_DIR=`pwd`/out`.  
3. I just made the whole reposity `TensorRT`. Are there a way to only make the plugin `scatterPlugin` with being parserred by onnx-parser ?

Thanks very much for your help!

**Comment by MichaelWU0726** [comment]
> > Hi Michael,
> > In transferring the plugin over from v8.0 to v7.2, you might have not transferred the declaration of the scatterND plugin. Please add this declaration to your v7.2 directory in plugin/common/kernel.h:
> > `pluginStatus_t scatterNDInference(cudaStream_t stream, int* outputDims, int nOutputDims, int sliceRank, int nRows, int rowSize, int CopySize, int sizeOfElementInBytes, const void* index, const void* updates, const void* data, void* output, void* workspace);`
> > You can find this here:
> > https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/kernel.h#L94
> 
> 1. It worked only when building engine. It showed the following when use `runtime.deserialize_cuda_engine` to load the engine.
> 
> ```
> [TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1
> [TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> [TensorRT] ERROR: INVALID_STATE: std::exception
> [TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
> ```
> 
> 1. I use the following command to make `Parser` and `Plugin`. Why the plugin `libmyelin` in the directory `target/x86_64-linux-gnu` was build into `tensorrt/lib` and i don't need the plugin `libmyelin` ?
>    `cmake .. -DBUILD_SAMPLES=OFF -DTRT_LIB_DIR=/usr/local/tensorrt/lib -DTRT_OUT_DIR=`pwd`/out  `
> 2. I just made the whole reposity `TensorRT`. Are there a way to only make the plugin `scatterPlugin` with being parserred by onnx-parser ?
> 
> Thanks very much for your help!

It worked after adding `trt.init_libnvinfer_plugins(TRT_LOGGER, "")` but i confused why it isn't enough to use `import pycuda.autoinit`

**Comment by ttyio** [comment]
Hello @MichaelWU0726 , is this duplicate to https://github.com/NVIDIA/TensorRT/issues/1457 ? thanks

**Comment by MichaelWU0726** [comment]
> Hello @MichaelWU0726 , is this duplicate to #1457 ? thanks

I didn't know whether the reason caused was same.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
