### ISSUE TITLE
python_setup.sh in nvcr.io/nvidia/tensorrt:21.07-py3 Docker image cannot install tensorflow

### ISSUE THREAD

**Issue by koval** [NVIDIA/TensorRT#1452]
## Description

`nvcr.io/nvidia/tensorrt:21.07-py3` Docker image suggests installing Python dependencies using `/opt/tensorrt/python/python_setup.sh` script. The script tries to install `tensorflow<2.0` which is not available for Python 3.8 version in the container.

## Environment

**TensorRT Version**: 21.07
**NVIDIA GPU**:  Tesla T4
**NVIDIA Driver Version**: 470.57.02
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**:  Amazon Linux 2
**Python Version (if applicable)**: Python 3.8
**Tensorflow Version (if applicable)**: Tensorflow v1
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:21.07-py3 Docker container

## Steps To Reproduce

- Start the container with `docker run --gpus all -it --rm nvcr.io/nvidia/tensorrt:21.07-py3`
- Run `/opt/tensorrt/python/python_setup.sh`
- Notice first few lines in the script output:

```
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0)
ERROR: No matching distribution found for tensorflow<2.0
```

- Subsequent commands in `python_setup.sh` that depend on tensorflow also fail:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/uff/__init__.py", line 49, in <module>
    from uff.converters.tensorflow.conversion_helpers import from_tensorflow  # noqa
  File "/usr/local/lib/python3.8/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 59, in <module>
    from .converter_functions import *  # noqa
  File "/usr/local/lib/python3.8/dist-packages/uff/converters/tensorflow/converter_functions.py", line 59, in <module>
    from uff.converters.tensorflow.converter import TensorFlowToUFFConverter as tf2uff
  File "/usr/local/lib/python3.8/dist-packages/uff/converters/tensorflow/converter.py", line 60, in <module>
    from tensorflow.compat.v1 import AttrValue
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by ttyio** [comment]
@koval , I have created internal issue to track this, thanks!

**Comment by ttyio** [comment]
@koval , will fix in next release, thanks

**Comment by ttyio** [comment]
8.2 is already released, closing and thanks
