### ISSUE TITLE
cannot export pytorch model to onnx after QAT

### ISSUE THREAD

**Issue by XingBin111** [NVIDIA/TensorRT#1454]
## Description

I'm doing QAT using resnet18 on cifar100, but encounter following error when export finetuned model to onnx:

`/home/xingb001/github_projects/TensorRT/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0, 
`
`
/home/xingb001/github_projects/TensorRT/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])
`

I follow the QAT instruction [https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html#quantization-aware-training](). I try two different opset 10 and 13, but failed.

## Environment

**TensorRT Version**: TensorRT-7.2.1.6
**NVIDIA GPU**: 1080ti
**NVIDIA Driver Version**: 460.80
**CUDA Version**: 11.2
**CUDNN Version**: 8.0.4
**Operating System**: 16.04.7 LTS
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 2.6.0
**PyTorch Version (if applicable)**: 1.8.0
**Baremetal or Container (if so, version)**:

**Comment by nanmi** [comment]
i have the same problem.how do you solve it ?

**Comment by SarchWu** [comment]
> i have the same problem.how do you solve it ?

Did you solved it ? And how?

**Comment by Meize0729** [comment]
Have you solved this problem？I have the same problem
