### ISSUE TITLE
[FEATURE REQUEST] DLA only support 2D conv

### ISSUE THREAD

**Issue by hyperfraise** [NVIDIA/TensorRT#1459]
This is pretty straightfoward. I'd be very interested in seeing DLA compatibility with 3d convolution.

Is there any plans to implement this ?

If not, can we create a feature tracking request, please ?

**Comment by ttyio** [comment]
@hyperfraise , could you create quest to DLA in https://github.com/nvdla/hw/issues? thanks

**Comment by hyperfraise** [comment]
Sure.

**Comment by ttyio** [comment]
I will close this one, thanks @hyperfraise
