### ISSUE TITLE
Convert QAT model to tensorrt error

### ISSUE THREAD

**Issue by XingBin111** [NVIDIA/TensorRT#1461]
## Description

Error occurred QAT with resnet18 using TensorRT8.0.1.6 following the guidance of pytorch-quantization toolbox
Error Message:

> [08/26/2021-02:53:06] [E] Error[10]: [optimizer.cpp::computeCosts::1855] Error Code 10: Internal Error (Could not find any implementation for node layer4.0.conv2.weight + QuantizeLinear_222_quantize_scale_node + Conv_224 + Add_243 + Relu_244.)
[08/26/2021-02:53:06] [E] Error[2]: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
Segmentation fault (core dumped)

export onnx to trt script:
`/opt/tensorrt/bin/trtexec --explicitBatch --onnx=resnet18.onnx --saveEngine=resnet18.engine --int8 --workspace=4096`

I also tried a simple model doing QAT on cifar100 following the guidance of pytorch-quantization toolbox. successfully convert the simple model to trt engine.

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 1080ti
**NVIDIA Driver Version**: 470.63.01
**CUDA Version**: 11.2
**CUDNN Version**: 8.0.4
**Operating System**:16.04.7 LTS
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Container (if so, version)**: nvcr.io/nvidia/pytorch:21.07-py3

## Relevant Files

[convert.log](https://github.com/NVIDIA/TensorRT/files/7051373/convert.log)
[onnx file](https://drive.google.com/file/d/13rUiZIxh12xz1_uDEPpiErw_uFaScI4I/view?usp=sharing)

**Comment by thanhnt-2658** [comment]
@XingBin111 Hi, did you solve this issue? If yes, can you share your solution. Thank you.

**Comment by thanhnt-2658** [comment]
I got same issue. 
Error[10]: [optimizer.cpp::computeCosts::1855] Error Code 10: Internal Error (Could not find any implementation for node layers.1.layers.0.weight + QuantizeLinear_23_quantize_scale_node + Conv_27 + Relu_29.)
