### ISSUE TITLE
INT8 inference with TensorRT 8 with efficientdet-lite2 and efficientdet-lite1 detect nothing at all.

### ISSUE THREAD

**Issue by ethan28135** [NVIDIA/TensorRT#1464]
INT8 inference with TensorRT 8 with efficientdet-lite2 and efficientdet-lite1 in NVIDIA V100, Jetson Xavier NX and Jetson Xavier AGX detect nothing at all across all test images, no matter what image is fed in whether it is from coco dataset or outside coco dataset, with the exception that only in some situations, efficientdet-lite1 gives good detections for all test images if certain input resolutions, certain image input batch size, certain calibration batch size and certain calibration image files are used. This is kinda weird. By the way, I use images in coco train set to calibrate for INT8. I also used coco val set to calibrate, but the same problem happens.

However, FP16 is always giving good detections no matter what settings and what images are used, so likely it is a problem with INT8, but I am not sure where is the problem. I did not modify any of the codes.

# Steps to reproduce (executing in Jupyter Notebook/Lab):

min_score_thresh = 0.35
saved_model_dir = '/path/to/savedmodel'
coco_trainset = 'train2017'

// inspect.py is the code in google/automl repository
!python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-lite2 --ckpt_path=efficientdet-lite2 \
  --hparams="image_size=1280x720" --saved_model_dir={saved_model_dir}

// create_onnx.py is the code in NVIDIA/TensorRT repository
!python create_onnx.py     \
    --input_shape '1,3,720,1280'     \
    --saved_model {saved_model_dir}     \
    --onnx /path/to/efficientdet-lite2.onnx

// build_engine.py is the code in NVIDIA/TensorRT repository
!python /path/to/TensorRT/samples/python/efficientdet/build_engine.py \
    --onnx /path/to/efficientdet-lite2.onnx \
    --engine /path/to/efficientdet-lite2-engine.trt \
    --precision int8 --workspace 32 \
    --calib_cache /path/to/calibration-efficientdet-lite2.cache \
    --calib_input /path/to/{coco_trainset} \
    --calib_batch_size 8 \
    --calib_num_images 5000

After that, I just use /path/to/TensorRT/samples/python/efficientdet/infer.py to perform inference.

When generating onnx, changing from input_shape '1,3,720,1280' to '1,720,1280,3' or to multiple batch size such as '2,3,720,1280' do not solve the problem, but in FP16, these work perfectly well.

Changing calib_batch_size and calib_num_images do not work as well. However, as mentioned, in some situations, INT8 efficientdet-lite1 gives good detections for all test images, provided if input_shape is '1,3,720,1280' and calib_batch_size is 1 and calib_num_images is 1000 and if certain calibration images in the coco train set are used (if you are lucky to choose the right 1000 images). But for efficientdet-lite2, no matter how, INT8 with trt engine gives no detections at all for all test images. This is kinda weird.

I need INT8 because it is giving a lot speed boost compared to FP16.

Please help on this.

Thanks.

**Comment by nvpohanh** [comment]
@ethan28135 Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Comment by iainwilson79** [comment]
I am experiencing a similar issue. 

I have a locally trained model efficientdet-lite1 and have exported to onnx and then tensorrt using the methods described in the [readme](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/efficientdet#readme).

Converting to 16bit I get performance as expected however with int8 I get no bboxes, or junk results. 

I have tried a pre-trained [checkpoint](https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/efficientdet-lite1.tgz) and the same results,  using coco images for quantisation.

This is using TensorRT 8.5.2.2.

Using the latest container `nvcr.io/nvidia/tensorrt:23.10-py3`  TensorRT 8.6.1.6, the pre-trained checkpoint works with int8, but my locally trained version does not.

Any suggestions?
