### ISSUE TITLE
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (396) - Myelin Error in compileGraph: 64 ()

### ISSUE THREAD

**Issue by PhilCuriosity** [NVIDIA/TensorRT#1466]
## Description

[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (396) - Myelin Error in compileGraph: 64 ()

## Environment
Jetson Xavier NX
Jetpack 4.4.1
pytorch 1.6

## Relevant Files
https://drive.google.com/file/d/1NlTZ0B8ZGzPr1FhymsF-L6e5ec-OShQ0/view?usp=sharing
![test onnx](https://user-images.githubusercontent.com/52873355/131433503-59e438c4-d6a0-4d61-9157-b717a694988f.png)

## Code
```

import sys
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit

TRT_LOGGER = trt.Logger()
def export(onnx_file_path='test.onnx', engine_file_path='test.trt',save_engine=True, max_batch_size=10, fp16_mode=False, int8_mode=False):
    explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH) 
    with trt.Builder(TRT_LOGGER) as builder, \
        builder.create_network(explicit_batch) as network,  \
        trt.OnnxParser(network, TRT_LOGGER) as parser, \
        builder.create_builder_config() as config: 
        profile = builder.create_optimization_profile()
        profile.set_shape("input", (10, 1, 32, 160),(10,1,32,224),(10,1,32,320))
        config.add_optimization_profile(profile)
        config.max_workspace_size = 1<<30 
        builder.max_batch_size = max_batch_size 
        builder.fp16_mode = fp16_mode
        builder.int8_mode = int8_mode
        if int8_mode:
            # To be updated
            raise NotImplementedError

        if not os.path.exists(onnx_file_path):
            quit("ONNX file {} not found!".format(onnx_file_path))

        parser.parse_from_file(onnx_file_path) 
        print("Completed parsing of onnx file")
        print("loading onnx file from path {} ...".format(onnx_file_path))

        engine = builder.build_engine(network,config) 
        print("Completed creating Engine")
        if save_engine: 
            with open(engine_file_path,"wb") as f:
                f.write(engine.serialize())  
export()
```

## log
even@even-desktop:~/Project/OCR/model$ python3 export3.py 
loading onnx file from path test.onnx ...
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Completed parsing of onnx file
Building an engine from filetest.onnx' this may take a while... 
[TensorRT] WARNING: DLA requests all profiles have same min, max, and opt value. All dla layers are falling back to GPU
[TensorRT] WARNING: Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are:  (# 2 (RESHAPE (MUL_ADD 10 E0 10) 512 | (+ E0 1) 10 -1 zeroIsPlaceholder)) where E0=(FLOOR_DIV (FLOOR_DIV (+ (# 3 (SHAPE input)) -1) 2) 2) (+ (FLOOR_DIV (FLOOR_DIV (+ (# 3 (SHAPE input)) -1) 2) 2) 1)
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (396) - Myelin Error in compileGraph: 64 (myelinProgramAnalysisError : Incompatible shapes in fully-connected op between: (Unnamed Loop_ 1)_(Unnamed Layer_ 681) [Constant]_(Unnamed Layer_ 682) [Constant]_(Unnamed Layer_ 677) [Constant] _ (Unnamed Layer_ 678) [Shuffle]_ConstantOfShape_517_(Unnamed Layer_ 696) [Iterator]_(Unnamed Layer_ 697) [Iterator]_(Unnamed Layer_ 695) [TripLimit]_(Unnamed Layer_ 703) [Shuffle]_(Unnamed Layer_ 709) [Shuffle]_LSTM_518_(Unnamed Layer_ 712) [Recurrence]_(Unnamed Layer_ 710) [Concatenation]_(Unnamed Layer_ 714) [Matrix Multiply]_(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 715) [ElementWise]_(Unnamed Layer_ 716) [ElementWise]_(Unnamed Layer_ 717) [Slice]_(Unnamed Layer_ 720) [Slice]_(Unnamed Layer_ 723) [Slice]_(Unnamed Layer_ 729) [Slice]_(Unnamed Layer_ 719) [Activation]_(Unnamed Layer_ 722) [Activation]_(Unnamed Layer_ 725) [Activation]_(Unnamed Layer_ 731) [Activation]_(Unnamed Layer_ 726) [ElementWise]_(Unnamed Layer_ 727) [ElementWise]_(Unnamed Layer_ 728) [ElementWise]_(Unnamed Layer_ 732) [Activation]_(Unnamed Layer_ 733) [ElementWise]_(Unnamed Layer_ 741) [Slice]_(Unnamed Layer_ 742) [Slice]_(Unnamed Layer_ 743) [LoopOutput]_(Unnamed Layer_ 744) [LoopOutput]__U0^(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 681) [Constant]_(Unnamed Layer_ 682) [Constant]_(Unnamed Layer_ 677) [Constant] _ (Unnamed Layer_ 678) [Shuffle]_ConstantOfShape_517_(Unnamed Layer_ 696) [Iterator]_(Unnamed Layer_ 697) [Iterator]_(Unnamed Layer_ 695) [TripLimit]_(Unnamed Layer_ 703) [Shuffle]_(Unnamed Layer_ 709) [Shuffle]_LSTM_518_(Unnamed Layer_ 712) [Recurrence]_(Unnamed Layer_ 710) [Concatenation]_(Unnamed Layer_ 714) [Matrix Multiply]_(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 715) [ElementWise]_(Unnamed Layer_ 716) [ElementWise]_(Unnamed Layer_ 717) [Slice]_(Unnamed Layer_ 720) [Slice]_(Unnamed Layer_ 723) [Slice]_(Unnamed Layer_ 729) [Slice]_(Unnamed Layer_ 719) [Activation]_(Unnamed Layer_ 722) [Activation]_(Unnamed Layer_ 725) [Activation]_(Unnamed Layer_ 731) [Activation]_(Unnamed Layer_ 726) [ElementWise]_(Unnamed Layer_ 727) [ElementWise]_(Unnamed Layer_ 728) [ElementWise]_(Unnamed Layer_ 732) [Activation]_(Unnamed Layer_ 733) [ElementWise]_(Unnamed Layer_ 741) [Slice]_(Unnamed Layer_ 742) [Slice]_(Unnamed Layer_ 743) [LoopOutput]_(Unnamed Layer_ 744) [LoopOutput]__subGraph0^(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 681) [Constant]_(Unnamed Layer_ 682) [Constant]_(Unnamed Layer_ 677) [Constant] _ (Unnamed Layer_ 678) [Shuffle]_ConstantOfShape_517_(Unnamed Layer_ 696) [Iterator]_(Unnamed Layer_ 697) [Iterator]_(Unnamed Layer_ 695) [TripLimit]_(Unnamed Layer_ 703) [Shuffle]_(Unnamed Layer_ 709) [Shuffle]_LSTM_518_(Unnamed Layer_ 712) [Recurrence]_(Unnamed Layer_ 710) [Concatenation]_(Unnamed Layer_ 714) [Matrix Multiply]_(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 715) [ElementWise]_(Unnamed Layer_ 716) [ElementWise]_(Unnamed Layer_ 717) [Slice]_(Unnamed Layer_ 720) [Slice]_(Unnamed Layer_ 723) [Slice]_(Unnamed Layer_ 729) [Slice]_(Unnamed Layer_ 719) [Activation]_(Unnamed Layer_ 722) [Activation]_(Unnamed Layer_ 725) [Activation]_(Unnamed Layer_ 731) [Activation]_(Unnamed Layer_ 726) [ElementWise]_(Unnamed Layer_ 727) [ElementWise]_(Unnamed Layer_ 728) [ElementWise]_(Unnamed Layer_ 732) [Activation]_(Unnamed Layer_ 733) [ElementWise]_(Unnamed Layer_ 741) [Slice]_(Unnamed Layer_ 742) [Slice]_(Unnamed Layer_ 743) [LoopOutput]_(Unnamed Layer_ 744) [LoopOutput]__subGraph0_input_A:f32,trA=false,[10,1] and (Unnamed Loop_ 1)_(Unnamed Layer_ 681) [Constant]_(Unnamed Layer_ 682) [Constant]_(Unnamed Layer_ 677) [Constant] _ (Unnamed Layer_ 678) [Shuffle]_ConstantOfShape_517_(Unnamed Layer_ 696) [Iterator]_(Unnamed Layer_ 697) [Iterator]_(Unnamed Layer_ 695) [TripLimit]_(Unnamed Layer_ 703) [Shuffle]_(Unnamed Layer_ 709) [Shuffle]_LSTM_518_(Unnamed Layer_ 712) [Recurrence]_(Unnamed Layer_ 710) [Concatenation]_(Unnamed Layer_ 714) [Matrix Multiply]_(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 715) [ElementWise]_(Unnamed Layer_ 716) [ElementWise]_(Unnamed Layer_ 717) [Slice]_(Unnamed Layer_ 720) [Slice]_(Unnamed Layer_ 723) [Slice]_(Unnamed Layer_ 729) [Slice]_(Unnamed Layer_ 719) [Activation]_(Unnamed Layer_ 722) [Activation]_(Unnamed Layer_ 725) [Activation]_(Unnamed Layer_ 731) [Activation]_(Unnamed Layer_ 726) [ElementWise]_(Unnamed Layer_ 727) [ElementWise]_(Unnamed Layer_ 728) [ElementWise]_(Unnamed Layer_ 732) [Activation]_(Unnamed Layer_ 733) [ElementWise]_(Unnamed Layer_ 741) [Slice]_(Unnamed Layer_ 742) [Slice]_(Unnamed Layer_ 743) [LoopOutput]_(Unnamed Layer_ 744) [LoopOutput]__U0^(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 681) [Constant]_(Unnamed Layer_ 682) [Constant]_(Unnamed Layer_ 677) [Constant] _ (Unnamed Layer_ 678) [Shuffle]_ConstantOfShape_517_(Unnamed Layer_ 696) [Iterator]_(Unnamed Layer_ 697) [Iterator]_(Unnamed Layer_ 695) [TripLimit]_(Unnamed Layer_ 703) [Shuffle]_(Unnamed Layer_ 709) [Shuffle]_LSTM_518_(Unnamed Layer_ 712) [Recurrence]_(Unnamed Layer_ 710) [Concatenation]_(Unnamed Layer_ 714) [Matrix Multiply]_(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 715) [ElementWise]_(Unnamed Layer_ 716) [ElementWise]_(Unnamed Layer_ 717) [Slice]_(Unnamed Layer_ 720) [Slice]_(Unnamed Layer_ 723) [Slice]_(Unnamed Layer_ 729) [Slice]_(Unnamed Layer_ 719) [Activation]_(Unnamed Layer_ 722) [Activation]_(Unnamed Layer_ 725) [Activation]_(Unnamed Layer_ 731) [Activation]_(Unnamed Layer_ 726) [ElementWise]_(Unnamed Layer_ 727) [ElementWise]_(Unnamed Layer_ 728) [ElementWise]_(Unnamed Layer_ 732) [Activation]_(Unnamed Layer_ 733) [ElementWise]_(Unnamed Layer_ 741) [Slice]_(Unnamed Layer_ 742) [Slice]_(Unnamed Layer_ 743) [LoopOutput]_(Unnamed Layer_ 744) [LoopOutput]__subGraph0^(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 681) [Constant]_(Unnamed Layer_ 682) [Constant]_(Unnamed Layer_ 677) [Constant] _ (Unnamed Layer_ 678) [Shuffle]_ConstantOfShape_517_(Unnamed Layer_ 696) [Iterator]_(Unnamed Layer_ 697) [Iterator]_(Unnamed Layer_ 695) [TripLimit]_(Unnamed Layer_ 703) [Shuffle]_(Unnamed Layer_ 709) [Shuffle]_LSTM_518_(Unnamed Layer_ 712) [Recurrence]_(Unnamed Layer_ 710) [Concatenation]_(Unnamed Layer_ 714) [Matrix Multiply]_(Unnamed Layer_ 713) [Matrix Multiply]_(Unnamed Layer_ 715) [ElementWise]_(Unnamed Layer_ 716) [ElementWise]_(Unnamed Layer_ 717) [Slice]_(Unnamed Layer_ 720) [Slice]_(Unnamed Layer_ 723) [Slice]_(Unnamed Layer_ 729) [Slice]_(Unnamed Layer_ 719) [Activation]_(Unnamed Layer_ 722) [Activation]_(Unnamed Layer_ 725) [Activation]_(Unnamed Layer_ 731) [Activation]_(Unnamed Layer_ 726) [ElementWise]_(Unnamed Layer_ 727) [ElementWise]_(Unnamed Layer_ 728) [ElementWise]_(Unnamed Layer_ 732) [Activation]_(Unnamed Layer_ 733) [ElementWise]_(Unnamed Layer_ 741) [Slice]_(Unnamed Layer_ 742) [Slice]_(Unnamed Layer_ 743) [LoopOutput]_(Unnamed Layer_ 744) [LoopOutput]__subGraph0_input_B:f32,trB=false,[512,2048].
)
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (396) - Myelin Error in compileGraph: 64 ()
Completed creating Engine
Traceback (most recent call last):
  File "export3.py", line 50, in <module>
    export()
  File "export3.py", line 48, in export
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by ttyio** [comment]
Hello @PhilCuriosity , have you tried JetPack 4.6? thanks
https://developer.nvidia.com/embedded/jetpack

**Comment by PhilCuriosity** [comment]
Thank you for your reply. Not yet, I'll try.
