### ISSUE TITLE
Does tensorrt support univl

### ISSUE THREAD

**Issue by RyanHuangNLP** [NVIDIA/TensorRT#1467]
univl is three part of transformer, two transformer for frame feature and text feature, and one transformer for multimodal future, does tensorrt support this type of transformer, or need to seperate three parts of univl?
![image](https://user-images.githubusercontent.com/49582480/131493779-d82803c0-0b04-4a35-985f-c003b2617c8f.png)

**Comment by ttyio** [comment]
hello @RyanHuangNLP , have you tried export the three part into single onnx? thanks

**Comment by RyanHuangNLP** [comment]
@ttyio I have try to export the lxmbert to onnx, which has similar structure as univl

**Comment by ttyio** [comment]
@RyanHuangNLP , did you hit any failure when run the onnx in tensorrt? thanks!

**Comment by RyanHuangNLP** [comment]
@ttyio I did not try to run the onnx in tensorrt, I should take a try. Thanks!

**Comment by nvpohanh** [comment]
closing this for now due to >14 days with no response. please reopen if the issue still exists. Thanks
