### ISSUE TITLE
Erro in command: convert-to-uff frozen_inference_graph.pb -O NMS -p config.py

### ISSUE THREAD

**Issue by thimabru1010** [NVIDIA/TensorRT#147]
Error: convert-to-uff: command not found
Why the command is not found ?? I followed all the instructions

**Comment by taomiao** [comment]
encounter this issue,too

**Comment by taomiao** [comment]
problem solved. you need to install /opt/tensorrt/python/uff-converter-tf_6.0.1-1+cuda10.1_amd64.deb
```
dpkg -i graphsurgeon-tf_6.0.1-1+cuda10.1_amd64.deb
dpkg -i uff-converter-tf_6.0.1-1+cuda10.1_amd64.deb
```

**Comment by rmccorm4** [comment]
@taomiao is correct. I'll see if I can get this to be more clear in the docs.
