### ISSUE TITLE
Error about uses tensorrt to convert dynamic shape input/output (SRModel)

### ISSUE THREAD

**Issue by Huang9495** [NVIDIA/TensorRT#1474]
## Description
A error about use tensorrt to transfer the model of SRModel with dynamic shape inputs/output

## Environment

**TensorRT Version**:  7.0.0.11
**NVIDIA GPU**:  P100
**NVIDIA Driver Version**:  430.64
**CUDA Version**: 10.1
*CUDNN Version**: 7.6.5
**Operating System**: Ubuntu 16.04
**Python Version (if applicable)**:  3.7.0
**PyTorch Version (if applicable)**: 1.7.0

## Relevant Files
1. project files website: https://github.com/NVIDIA-AI-IOT/torch2trt
2. Model path: https://github.com/xinntao/BasicSR (srresnet_arch)

## Steps To Reproduce
Before proposing this question, I have tried to do some test here:

1. Load the network in project, the shuffle_layer and interplote not work and I redefined a new class and refuse the issue.
2. I try to do three test to transfer this model by as fellow:
         A. I set the single input as (1,3,112,112) with output is (1,3,448,448), then I set dynamic as the office document (https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#runtime_dimensions). With the code as:

**Build engine:**

     input -> (1,3,112,112), inference_input -> (1,3,112,112), with output ->(1,3,448,448)
     with ConversionContext(network, torch2trt_kwargs=kwargs) as ctx:
            opt_shape_param = [(1,3,112,112),(1,3,224,224),(1,3,512,512)]
            config = builder.create_builder_config()
            profile = builder.create_optimization_profile()
            if isinstance(inputs, list):
                inputs = tuple(inputs)
            if not isinstance(inputs, tuple):
                inputs = (inputs,)
            ctx.add_inputs(inputs, input_names, opt_shape_param)
            outputsss = []
            profile.set_shape(network.get_input(0).name, opt_shape_param[0], opt_shape_param[1], opt_shape_param[2])
            for i, tensor in enumerate(inputs):
                outputs = module(tensor)
                if not isinstance(outputs, tuple) and not isinstance(outputs, list):
                    outputsss += (outputs,)
            ctx.mark_outputs(outputsss, output_names)
            config.add_optimization_profile(profile)`

**add input/ mark output:**

     def add_inputs(self, torch_inputs, names=None):
        if names is None:
            names = default_input_names(len(torch_inputs))
        self.input_names = names
        for i, torch_input in enumerate(torch_inputs):
            if not hasattr(torch_input, "_trt"):
                trt_tensor = self.network.add_input(
                    name=names[i],
                    shape=tuple(torch_input.shape)[1:],
                    dtype=torch_dtype_to_trt(torch_input.dtype),
                )
                trt_tensor.location = torch_device_to_trt(torch_input.device)
                torch_input._trt = trt_tensor
    def mark_outputs(self, torch_outputs, names=None):
        if names is None:
            names = default_output_names(len(torch_outputs))
        self.output_names = names
        for i, torch_output in enumerate(torch_outputs):
            trt_tensor = torch_output._trt
            trt_tensor.name = names[i]
            trt_tensor.location = torch_device_to_trt(torch_output.device)
            trt_tensor.dtype = torch_dtype_to_trt(torch_output.dtype)
            self.network.mark_output(trt_tensor)

**Inference:**

        for i, input_name in enumerate(self.input_names):
            idx = self.engine.get_binding_index(input_name)
            self.context.set_binding_shape(idx, tuple(inputs[i].shape))
            bindings[idx] = inputs[i].contiguous().data_ptr()
        # create output tensors
        outputs = [None] * len(self.output_names)
        for i, output_name in enumerate(self.output_names):
            idx = self.engine.get_binding_index(output_name)
            dtype = torch_dtype_from_trt(self.engine.get_binding_dtype(idx))
            shape = tuple(self.context.get_binding_shape(idx))
            device = torch_device_from_trt(self.engine.get_location(idx))
            output = torch.empty(size=(1,3,448,448), dtype=dtype, device=device)
            outputs[i] = output
            bindings[idx] = output.data_ptr()`

**Error:**
        torch2trt.tests.torchvision.classification.msrresnet | float16 |        [(1, 3, 112, 112)] | {'fp16_mode': True} | 3.03E-02 | 0.00 | 0.00E+00 | 0 | 0 | 0 | 0 |`

 B. if I change the inference_input -> (1,3,224,224), with output ->(1,3,896,896)
**Error:**
       Nothing is outputed and it seems the network is not work on the input`

C. Last, I change the input with  input -> (1,3,112,112), (1,3,224,224) with output (1,3,448,448), (1,3,896,896)
through operate fellow code two times
     profile.set_shape(network.get_input(0).name, opt_shape_param[0], opt_shape_param[1], opt_shape_param[2])`
Meantime I change the bindings:[None, None, None, None] or bindings: [None, None] and push the input and output number into corresponding position.
**Error:**
     Nothing is outputed and it seems the network is not work on the input`

**Others:**
I try to set the add_input for network as fellow:
`network_definition.add_input("foo", trt.float32,(3, -1, -1))`
A new issue is occuring : 
`ERROR: Parameter check failed at: ../builder/Network.cpp::addInput::957, condition: isValidDims(dims, hasImplicitBatchDimension())`

@ttyio @kevinch-nv 

**How I work it and whether my thinking is wrong ? Please help me !**

**Comment by ttyio** [comment]
Hello @Huang9495 , have you tried export ONNX from pytorch, and using trtexec to build the engine? 
thanks

**Comment by Huang9495** [comment]
Thanks @ttyio I will try to do as you suggest and update the result later.

**Comment by Huang9495** [comment]
@ttyio Hello， I try to do by another way as : pytorch -> onnx -> tensorrt
New issue occurs as follow:

**The environment is same as above**

**1. Single input:**
`
# ONNX：
onnx_model = torch_2_onnx(input1, model, save_path_onnx)
def torch_2_onnx(data, model, save_path):
    '''
    @data: input numpy is creat by torch
    @model: torch model
    @save_path: the save path of onnx model
    @return: onnx model
    '''
    model.eval()
    input_names = ["input"]
    output_names = ["output"]
    torch.onnx.export(model, data, save_path, export_params=True, opset_version=11, input_names=input_names, output_names=output_names)
    print("==>Completa Onnx")
    return save_path
# Tensorrt：
 def get_engine(self):
        '''
        @dynamic_input: True/False
        @returns:                    ICudaEngine
        '''            
        explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        # In TensorRT 7.0, the ONNX parser only supports full-dimensions mode, meaning that your network definition must be created with the explicitBatch flag set. For more information, see Working With Dynamic Shapes.

        with trt.Builder(self.TRT_LOGGER) as builder, \
            builder.create_network(explicit_batch) as network,  \
            trt.OnnxParser(network, self.TRT_LOGGER) as parser:

            builder.max_workspace_size = 1<<30
            builder.max_batch_size = self.max_batch_size
            builder.fp16_mode = self.fp16_mode

            if not os.path.exists(self.onnx_path):
                quit("ONNX file {} not found!".format(self.onnx_path))
            print('loading onnx file from path {} ...'.format(self.onnx_path))
            with open(self.onnx_path, 'rb') as model:
                print("Begining onnx file parsing")
                parser.parse(model.read())  

            network.get_input(0).shape = [1,3,224,224]
            #################
            network.mark_output(network.get_layer(network.num_layers -1).get_output(0))
            engine = builder.build_cuda_engine(network)
            if self.save_engine:
                with open(self.trt_path, 'wb') as f:
                    f.write(engine.serialize())
            return engine
    
  **Note：** single input is work, but the error of tensorrt model is large

**2. Dynamic input:**

# ONNX:
def torch_2_onnx_dynamic(dynamic_input, data, model, save_path):
    '''
    @data: input numpy is creat by torch
    @model: torch model
    @save_path: the save path of onnx model
    @return: onnx model
    '''
    model.eval()
    input_names = ["input1"]
    output_names = ["output1"]
    torch.onnx.export(model, data, save_path, export_params=True, opset_version=11, input_names=input_names, output_names=output_names, dynamic_axes=dynamic_input)
    print("==>Completa Onnx")
    return save_path

# Tensorrt:
  def get_engine_dynamic(self, dynamic_input=False):
        '''
        @dynamic_input: True/False
        @returns:                    ICudaEngine
        '''
        explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
        # In TensorRT 7.0, the ONNX parser only supports full-dimensions mode, meaning that your network definition must be created with the explicitBatch flag set. For more information, see Working With Dynamic Shapes.

        with trt.Builder(TRT_LOGGER) as builder, \
            builder.create_network(explicit_batch) as network,  \
            builder.create_builder_config() as config,  \
            trt.OnnxParser(network, TRT_LOGGER) as parser, \
            trt.Runtime(TRT_LOGGER) as runtime:
            config.max_workspace_size = 1<<30 
            builder.max_batch_size = self.max_batch_size
            profile = builder.create_optimization_profile()
            if not os.path.exists(self.onnx_path):
                quit("ONNX file {} not found!".format(self.onnx_path))
            print('loading onnx file from path {} ...'.format(self.onnx_path))
            with open(self.onnx_path, 'rb') as model: 
                print("Begining onnx file parsing")
                **parser.parse(model.read())**
                print("Completed parsing of onnx file")
            profile.set_shape_input(network.get_input(0).name, [1,3,224,224], [1,3,448,448], [1,3,512,512])
            config.add_optimization_profile(profile)
            engine = builder.build_cuda_engine(network, config) 
            if self.save_engine: 
                with open(self.trt_path, 'wb') as f:
                    f.write(engine.serialize()) 
            return engine
**Note:** dynamic input of torch to onnx is work but it's not work in the process of transfer the onnx model to tensorrt

**Error**
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 85, in main
    O2T.trt_inference(input2, torch_out)
  File "/data/hzy/Torch-Onnx-Tensorrt/onnx2tensorrt.py", line 306, in trt_inference
    engine = self.get_engine_dynamic(dynamic_input=dynamic_input)
  File "/data/hzy/Torch-Onnx-Tensorrt/onnx2tensorrt.py", line 172, in get_engine_dynamic
    engine = builder.build_cuda_engine(network, config)  # 注意，这里的network是INetworkDefinition类型，即填充后的计算图
TypeError: build_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Builder, network: tensorrt.tensorrt.INetworkDefinition) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Builder object at 0x7f0152db0730>, <tensorrt.tensorrt.INetworkDefinition object at 0x7f013c91a730>, <tensorrt.tensorrt.IBuilderConfig object at 0x7f01346b0148>

I have try to resolve this error by search the methods from website but is not work.
How to do and where the issue is ?

**My next work:**
I will try to do this test in tensorrt-v8.0
Hope the end is .

![super_resolution](https://user-images.githubusercontent.com/26674689/132946054-eb3352e8-7dea-4525-940a-398e0270f050.png)

**Comment by nvpohanh** [comment]
@Huang9495 Could you try TRT 8.2/8.4 since they have much better dynamic shapes support? If the issue still exists, please share the ONNX file and which GPU you were using. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
