### ISSUE TITLE
WARNING: The logger passed into createInferRuntime differs from one already provided for an existing builder

### ISSUE THREAD

**Issue by zhouyuangan** [NVIDIA/TensorRT#1475]
## Description

When I build trt model from onnx，get a Warning
 `WARNING: The logger passed into createInferRuntime differs from one already provided for an existing builder, runtime, or refitter. TensorRT maintains only a single logger pointer at any given time, so the existing value, which can be retrieved with getLogger(), will be used instead. In order to use a new logger, first destroy all existing builder, runner or refitter objects.`

But the inference result is right, how to remove this warning?

## Environment

**TensorRT Version**: 8.0.1
**NVIDIA GPU**: 2080Ti
**NVIDIA Driver Version**: 470.63.01
**CUDA Version**: 11.4
**CUDNN Version**: 8.2.1
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**:  None
**PyTorch Version (if applicable)**: 1.5.1
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:21.08-py3

**Comment by zhouyuangan** [comment]
I can't find getLogger in tensorrt python api index....., it only exist in c++ header.

**Comment by ttyio** [comment]
Hello @zhouyuangan ,
In python we use code like this

       TRT_LOGGER = trt.Logger(trt.Logger.INFO)

https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Logger.html

**Comment by zhouyuangan** [comment]
@ttyio Thank you, it works.
