### ISSUE TITLE
Question relate to format of input and output

### ISSUE THREAD

**Issue by taquanghung1705199** [NVIDIA/TensorRT#1482]
I have a question !

I know 2 variables to set data types of input and output: --inputIOFormats and --outputIOFormats. 2 variables are set for all input and output. (These inputs and outputs have the same data types)

And my question is if my model have multi input (or multi output) and these inputs have different data types, , how to adjust properly? 

For example: if I have 3 inputs, input1: int32, input2: float32, input3: float64, and 2 outputs, output1: float16, output2: float32. What should I do ?

Thanks for reading and hope to get reply soon !

**Comment by ttyio** [comment]
Hello @taquanghung1705199 , we can use comma to separated them, e.g,

       --inputIOFormats=int32:chw,float32:chw
