### ISSUE TITLE
Plugin use constant node as input (reformatted node is added automatically)

### ISSUE THREAD

**Issue by haoxuhao** [NVIDIA/TensorRT#1489]
## Description

I extended the IPluginV2IOExt to implement a matmul plugin. When using a constant layer as input, a reformatted layer is automatically inserted by TensorRT (reformatted from shape [1, 64] to [-2, 64]). I want to know is there any solutions to avoid this since it hurts the performance much. Thanks for any advice! 

## Environment

**TensorRT Version**: 8.0
**CUDA Version**: 11

**Comment by ttyio** [comment]
@haoxuhao
when the output tensor layout (`TensorFormat`) from previous layer not supported by your plugin's `supportsFormatCombination`, we will insert reformat to make the layout match, then call your plugin.
so you can add breakpoint to check the missing layout, and implement the layout in your kernel to remove this reformat.
Thanks!

**Comment by haoxuhao** [comment]
Thanks!!!, I've already solved it through setting "canBroadcastInputAcrossBatch".

**Comment by ttyio** [comment]
> Thanks!!!, I've already solved it through setting "canBroadcastInputAcrossBatch".

Great, thanks for let me know. You are right, just checked the code:

    For IPlugin, when the input is broadcast and kernel did not use N stride = 0, the plugin crashed;
    For IPluginV2, broadcast tensors are replicated before feed plugin, plugin kernel can access it as non-broadcast tensor;
    For IPluginV2Ext, when the input is broadcast and the canBroadcastInputAcrossBatch() return true, the input is a broadcast tensor like IPlugin;

**Comment by duduscript** [comment]
Hi @ttyio , I extended IPluginV2DynamicExt and I can not override "canBroadcastInputAcrossBatch", how to solve this problem?
