### ISSUE TITLE
[TRT] Cuda initialization failure with error

### ISSUE THREAD

**Issue by huangsiyuzhoujie** [NVIDIA/TensorRT#149]
编译成功，运行./sample_mnist时出现错误
&&&& RUNNING TensorRT.sample_mnist # ./sample_mnist
[I] Building and running a GPU inference engine for MNIST
[E] [TRT] Cuda initialization failure with error 2. Please check cuda installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html.
&&&& FAILED TensorRT.sample_mnist # ./sample_mnist

**Comment by tzattack** [comment]
I have the similar problem when I try to infer an offline model with 
`[E] [TRT] Cuda initialization failure with error 100. Please check cuda installation: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html.`

**Comment by wanhaipeng** [comment]
I have the similar problem，CUDA11.1 driver 450.80 TRT 7.2.2.3

**Comment by jalola** [comment]
I also have this issue
TensorRT: 7.0.0
CUDA: 11.2
Driver: 460.73.01
GPU: T4

**Comment by karenyun** [comment]
Have someone solved this issue?
I meet the same issue.
