### ISSUE TITLE
Using polygraphy to save engine to disk

### ISSUE THREAD

**Issue by dataplayer12** [NVIDIA/TensorRT#1495]
Hi, I am going through polygraphy API and I can see that it allows creation of tensorRT engine from onnx files.

`engine = engine_from_network(network_from_onnx_path("/path/to/model.onnx"))`

Is it possible to save this engine to disk with something like this?

```python
with open("model.engine",'wb') as f:
    f.write(engine)
```

Will tensorRT recognize this saved engine if it is loaded into a tensorRT program created in C++?

**Comment by pranavm-nvidia** [comment]
To both your questions, yes. `engine` is a `trt.ICudaEngine`. 

You can alternatively use Polygraphy's [`save_engine`](https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/backend/trt/loader.html?highlight=save_engine#polygraphy.backend.trt.loader.save_engine) API to save the engine to disk.
