### ISSUE TITLE
How to perform refitting correctly?

### ISSUE THREAD

**Issue by doramasma** [NVIDIA/TensorRT#1496]
## Description

I want to be able to refit my model. In this case, the model is a simple MLP of 4 layers. However, when I want to modify the weights, I'm not sure at all, what I have to modify. For example, if I use the command _"refitter.get_all_weights()"_ , i get as output: 

```
'12',
 'model.pos_enc.B',
 '46',
 'model.trainable_net.0.linear.bias',
 '21',
 '47',
 'model.trainable_net.1.linear.bias'
```

## Relevant Files

The trt model is created as follows:

```
engine = get_engine("model.onnx", "model.trt")

refitter = trt.Refitter(engine, trt.Logger())

context = engine.create_execution_context()
```
where get_engine does:

```
with open(engine_file_path, "rb") as f:
            runtime = trt.Runtime(TRT_LOGGER)
            return runtime.deserialize_cuda_engine(f.read())
```

So, my idea was from the model weights stored as a state_dict. Modify the weights of the model that is currently loaded. However, the model created does not have the key layers I would expect. Any ideas?

Thank you in advance,
Doramas

**Comment by nvpohanh** [comment]
@doramasma Could you share your ONNX file so that we can assist you? Thanks

**Comment by doramasma** [comment]
@nvpohanh Unfortunately I can't share my onnx file, However, this problem was solved in this issue: 
https://github.com/NVIDIA/TensorRT/issues/1468
