### ISSUE TITLE
Is it possible that the weights get messed up when refitting?

### ISSUE THREAD

**Issue by doramasma** [NVIDIA/TensorRT#1501]
## Description

The problem I am carrying out consists of performing inference for a model and then modifying the weights of that model. Testing, I have modified the weights of the model to the same weights of the first inference. And I get as output, something similar to what I expected but that seems to be messed up. 

Are there any known problems with this? 
Is it possible to check the weights of the model I currently have loaded, to see if they are being modified correctly ?

## Environment

Using docker container:
`FROM nvcr.io/partners/gridai/pytorch-lightning:v1.4.0`

Greetings

**Comment by nvpohanh** [comment]
@doramasma If that happens, it is probably a TensorRT bug. Could you provide the repro steps so that we can debug this? Thanks

**Comment by doramasma** [comment]
@nvpohanh This problem was resolved in this issue
https://github.com/NVIDIA/TensorRT/issues/1468
