### ISSUE TITLE
quant_modules.initialize not affected 

### ISSUE THREAD

**Issue by thanhnt-2658** [NVIDIA/TensorRT#1502]
I run `quant_modules.initialize()` then create model but no effect of `automatic layer substitution`. I use model from insightface

https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/backbones/mobilefacenet.py#L88

**Comment by Scass0807** [comment]
@thanhnt-2658 Did you solve this?

**Comment by thanhnt-2658** [comment]
Yes, It was my fault. There was an importation that created the model before `quant_modules.initialize()`. Make sure to call `quant_modules.initialize()` before that.
