### ISSUE TITLE
FEATURE REQUEST Be compatible with UINT8 input data type

### ISSUE THREAD

**Issue by hyperfraise** [NVIDIA/TensorRT#1503]
TensorRT can't take UINT8 inputs, unlike openvino or pytorch for example. This topic makes me think it's pretty important to users though https://github.com/onnx/onnx-tensorrt/issues/400

This means that all conversions must be done on CPU before feeding the data to GPU. 

I think it'd be useful if TensorRT could take UINT8 inputs, since it's the most common data type for image data.

**Comment by nvpohanh** [comment]
UINT8 support is on roadmap.

**Comment by justinblaber** [comment]
This is especially useful if you want to do real time processing on large images, so would be nice if it was supported directly.

**Comment by ttyio** [comment]
I will close this issue since now UINT8 input is supported start TRT8.5, thanks all!

https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html#rel-8-5-1
