### ISSUE TITLE
FP16 create eng problem

### ISSUE THREAD

**Issue by YLongJin** [NVIDIA/TensorRT#1505]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

In my preject，the network can build successful with int8, but it can not build with FP16.
 
The log follow:

UNKNOWN: Builder timing cache: created 746 entries, 6450 hit(s)
ERROR: C:\source\builder\tacticOptimizer.cpp (1814) - TRTInternal Error in nvinfer1::builder::`anonymous-namespace'::LeafCNode::computeCosts: 0 (Could not find any implementation for node 2-layer MLP: conv_body21_fc1 + relu_body21_0 -> relu_body21_sigmoid.)
Assertion failed: engine != nullptr, file d:\workplace\createng\src\trtnet.cpp, line 150

**Comment by nvpohanh** [comment]
@YLongJin This should have been fixed in the latest TensorRT version. Could you try TRT 8.2 or 8.4 EA? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
