### ISSUE TITLE
How to implement 'Range' op in TensorRT6

### ISSUE THREAD

**Issue by OYCN** [NVIDIA/TensorRT#1509]
## How to implement `Range` in TensorRT6?

I'm using Nvidia Drive platform,  there isn't the `Fill` layer in TensorRT6. 
When I want to implement the `Range` op as a plugin, I found I can't compute the size of output in `getOutputDimensions`. Although I try to using `ElementWise` layer compute the outputs size before invoke the plugin importer in onnx-parser, I can't read the value of inputs in build-time.

Any way to implement the `Range` op in TRT6?

In my case, the `Range` is converted from below code by pytorch:

```
# in pytorch 
A[1, :, 4]

# in Onnx, 
%1 : A
%2 : Tensor = onnx::Shape(%1)
%3 : Tensor = onnx::Constant[value={1}]()
%4 : Long() = onnx::Gather[axis=0](%2, %3)
%5 : Tensor = onnx::Cast[to=7](%4)
%6 : Tensor = onnx::Constant[value={0}]()
%7 : Tensor = onnx::Constant[value={1}]()
%4434 : Tensor = onnx::Range(%6, %5, %7)
```

**Comment by nvpohanh** [comment]
@OYCN Unfortunately, with TensorRT 6, the option is very limited. As you said, if you implement the Range plugin, you will probably need to hard-code the output dimensions for your use case.

If you are doing just `A[1, :, 4]`, I think there is a way to use ONNX to achieve this without using Range op, but you will need to manually update the ONNX file using ONNX-graphsurgeon.

Upgrading TensorRT version will save a lot of these efforts.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
