### ISSUE TITLE
GridAnchorPluginCreator parameters does not correspond to documentation

### ISSUE THREAD

**Issue by hobrasoft** [NVIDIA/TensorRT#1512]
Parameters in README.md:
- minSize
- maxSize
- aspectRatios
- numAspectRatios
- H
- W
- variance

Parameters in GridAnchorPluginCreator:
- minSize
- maxSize
- aspectRatios
- featureMapShapes
- variance
- numLayers

**Comment by nvpohanh** [comment]
@rajeevsrao Do you have any insight on this?

**Comment by rajeevsrao** [comment]
@hobrasoft thanks for reporting the issue. The documentation looks busted and likely regressed when we added support for rectangular featuremap inputs in `GridAnchor` plugin. @nvpohanh please create an internal bug request and assign to @samurdhikaru .

**Comment by nvpohanh** [comment]
Internal bug id: 3660418

Assigned to @samurdhikaru

**Comment by nvpohanh** [comment]
This has been fixed internally and will be available in next release. Thanks for reporting this!
