### ISSUE TITLE
onnx2tensorRT 结果差异较大

### ISSUE THREAD

**Issue by Fanky186** [NVIDIA/TensorRT#1513]
你好，我有一个onnx模型，当我转换成tensorRT的模型后，发现结果差异很大，
这是我的onnx model，与 tensorRT model, 还有数据
[diff.zip](https://github.com/NVIDIA/TensorRT/files/7222944/diff.zip)

**Comment by apintec** [comment]
你的模型精度是fp32还是int8的？我这边也遇到onnx转trt之后掉精度的现象，不过是int8的onnx模型下会掉，fp32的onnx模型不会

**Comment by oxana-nvidia** [comment]
Hi @Fanky186,
I've used[ polygraphy tool ](https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/index.html) to analyze your model and it shows that int8 range is not enough to represent you model and all values are converted to zero. 

[I] Accuracy Comparison | onnxrt-runner-N0-06/22/22-13:16:45 vs. trt-runner-N0-06/22/22-13:16:45
[I]     Comparing Output: 'save_infer_model/scale_0.tmp_1' (dtype=float32, shape=(1, 1, 640, 640)) with 'save_infer_model/scale_0.tmp_1' (dtype=float32, shape=(1, 1, 640, 640))
[I]     Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[I]         onnxrt-runner-N0-06/22/22-13:16:45: save_infer_model/scale_0.tmp_1 | Stats: mean=7.276e-14, std-dev=4.6566e-11, var=2.1684e-21, median=0, min=0 at (0, 0, 0, 0), max=2.9802e-08 at (0, 0, 356, 25), avg-magnitude=7.276e-14
[I]         trt-runner-N0-06/22/22-13:16:45: save_infer_model/scale_0.tmp_1 | Stats: mean=0, std-dev=0, var=0, median=0, min=0 at (0, 0, 0, 0), max=0 at (0, 0, 0, 0), avg-magnitude=0

**Comment by oxana-nvidia** [comment]
Closing as no response provided in >=14  days. Please reopen if there are any updates.
