### ISSUE TITLE
tf-trt converter.save error. ValueError: Input 0 of node xxx/Assign was passed float from xxx/bias:0 incompatible with expected float_ref.

### ISSUE THREAD

**Issue by uygnef** [NVIDIA/TensorRT#1518]
tensorflow version: 1.15.0
GPU: V100
CUDA: V10.0.130
CuDNN: 7.0
GPU DRIVER: 410.79
-------------------
convert from pb file
`import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverter(input_saved_model_dir='.', 
input_saved_model_signature_key='predictor',
input_saved_model_tags=[tf.saved_model.tag_constants.SERVING],
                                  is_dynamic_op=True,
                               
                                  precision_mode="FP16"
                                 )
converter.convert()
converter.save("trt_model.pb")
`
 save converted graph fail, here is error stack
`Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node inference/dpc_embedding_sequenceattention/bias/Assign was passed float from inference/dpc_embedding_sequenceattention/bias:0 incompatible with expected float_ref.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "converter.py", line 11, in <module>
    converter.save("trt_model.pb")
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 713, in save
    importer.import_graph_def(self._converted_graph_def, name="")
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node inference/dpc_embedding_sequenceattention/bias/Assign was passed float from inference/dpc_embedding_sequenceattention/bias:0 incompatible with expected float_ref.`

does it mean something wrong when convert assign op? 
how can I fix it?

**Comment by uygnef** [comment]
It seems that tf_optimizer.OptimizeGraph convert assign + identity to assign. make that error

before convert: 
1494 global_step/Assign Assign
1495 global_step/read Identity

after convert:
16012 global_step/Assign Assign

**Comment by uygnef** [comment]
before convert
name: "global_step/Assign"
op: "Assign"
input: "global_step"
input: "global_step/Initializer/zeros"
attr {
  key: "T"
  value {
    type: DT_INT64
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@global_step"
    }
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
      }
    }
  }
}
attr {
  key: "use_locking"
  value {
    b: true
  }
}
attr {
  key: "validate_shape"
  value {
    b: true
  }
}


after convert:

name: "global_step/Assign"
op: "Assign"
input: "global_step"
input: "global_step/Initializer/zeros"
attr {
  key: "T"
  value {
    type: DT_INT64
  }
}
attr {
  key: "use_locking"
  value {
    b: true
  }
}
attr {
  key: "validate_shape"
  value {
    b: true
  }
}

**Comment by nvpohanh** [comment]
@uygnef Could you try converting the TF graph to ONNX using https://github.com/onnx/tensorflow-onnx ? Then, pass the ONNX file into TRT. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
