### ISSUE TITLE
How do I install TRT after compilation on a TX2?

### ISSUE THREAD

**Issue by JustinMBrown** [NVIDIA/TensorRT#152]
I installed TRT 5.1.6 from a dpkg on my TX2. I want to upgrade to 6.0, and so I need to compile from source.

I've compiled 6.0 from source on a TX2, but when I go to install, my existing TRT install doesn't get updated.
Here are the commands I ran:

`nvidia@nvidia-desktop:~/TensorRT/build$ cmake .. -DTRT_LIB_DIR=$TRT_LIB_DIR -DTRT_BIN_DIR=`pwd`/out -DCUDA_VERSION=10.0 -DCUDNN_VERSION=7.5 -DCMAKE_BUILD_TYPE=Release`

where $TRT_LIB_DIR is `/usr/lib/aarch64-linux-gnu/`

Result:

> -- Targeting TRT Platform: x86_64
-- CUDA version set to 10.0
-- cuDNN version set to 7.5
-- Protobuf version set to 3.0.0
-- Setting up another Protobuf build for cross compilation targeting aarch64-Linux
-- Using libprotobuf /home/nvidia/TensorRT/build/third_party.protobuf_aarch64/lib/libprotobuf.a
-- ========================= Importing and creating target nvinfer ==========================
-- Looking for library nvinfer
-- Library that was found /usr/lib/aarch64-linux-gnu/libnvinfer.so
-- ==========================================================================================
-- ========================= Importing and creating target nvuffparser ==========================
-- Looking for library nvparsers
-- Library that was found /usr/lib/aarch64-linux-gnu/libnvparsers.so
-- ==========================================================================================
-- Protobuf proto/trtcaffe.proto -> proto/trtcaffe.pb.cc proto/trtcaffe.pb.h
-- /home/nvidia/TensorRT/build/parsers/caffe
-- 
-- ******** Summary ********
--   CMake version         : 3.15.4
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/g++
--   C++ compiler version  : 7.4.0
--   CXX flags             : -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -Wall -Wno-deprecated-declarations -Wno-unused-function -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : _PROTOBUF_INSTALL_DIR=/home/nvidia/TensorRT/build/third_party.protobuf;ONNX_NAMESPACE=onnx2trt_onnx
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /lib/..
--   CMAKE_MODULE_PATH     : 
-- 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx2trt_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- GPU_ARCH is not defined. Generating CUDA code for default SMs.
-- Found TensorRT headers at /home/nvidia/TensorRT/include
-- Find TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/TensorRT/build

`nvidia@nvidia-desktop:~/TensorRT/build$ make -j$(nproc)`

>...
[100%] Built target trtexec

`nvidia@nvidia-desktop:~/TensorRT/build$ sudo make install`

>Install the project...
-- Install configuration: "Release"
-- Up-to-date: /lib/../lib/libnvinfer_plugin.so.6.0.1.0
-- Up-to-date: /lib/../lib/libnvinfer_plugin.so.6.0.1
-- Up-to-date: /lib/../lib/libnvinfer_plugin.so
-- Up-to-date: /lib/../lib/libnvcaffeparser.so.6.0.1.0
-- Up-to-date: /lib/../lib/libnvcaffeparser.so.6.0.1
-- Up-to-date: /lib/../lib/libnvcaffeparser.so
-- Up-to-date: /lib/../bin/onnx2trt
-- Up-to-date: /lib/../lib/libnvonnxparser.so.6.0.1
-- Up-to-date: /lib/../lib/libnvonnxparser.so.6
-- Up-to-date: /lib/../lib/libnvonnxparser.so
-- Up-to-date: /lib/../lib/libnvonnxparser_static.a
-- Up-to-date: /lib/../include/NvOnnxParser.h
-- Up-to-date: /lib/../bin/sample_char_rnn
-- Up-to-date: /lib/../bin/sample_dynamic_reshape
-- Up-to-date: /lib/../bin/sample_fasterRCNN
-- Up-to-date: /lib/../bin/sample_googlenet
-- Up-to-date: /lib/../bin/sample_int8
-- Up-to-date: /lib/../bin/sample_int8_api
-- Up-to-date: /lib/../bin/sample_mlp
-- Up-to-date: /lib/../bin/sample_mnist
-- Up-to-date: /lib/../bin/sample_mnist_api
-- Up-to-date: /lib/../bin/sample_movielens
-- Up-to-date: /lib/../bin/sample_movielens_mps
-- Up-to-date: /lib/../bin/sample_nmt
-- Up-to-date: /lib/../bin/sample_onnx_mnist
-- Up-to-date: /lib/../bin/sample_plugin
-- Up-to-date: /lib/../bin/sample_reformat_free_io
-- Up-to-date: /lib/../bin/sample_ssd
-- Up-to-date: /lib/../bin/sample_uff_fasterRCNN
-- Up-to-date: /lib/../bin/sample_uff_maskRCNN
-- Up-to-date: /lib/../bin/sample_uff_mnist
-- Up-to-date: /lib/../bin/sample_uff_plugin_v2_ext
-- Up-to-date: /lib/../bin/sample_uff_ssd
-- Up-to-date: /lib/../bin/trtexec

But when I go to check if it has been installed, 5.1.6 is still there

`nvidia@nvidia-desktop:~/TensorRT/build$ dpkg -l | grep TensorRT`

>ii  graphsurgeon-tf                               5.1.6-1+cuda10.0                                arm64        GraphSurgeon for TensorRT package
ii  libnvinfer-dev                                5.1.6-1+cuda10.0                                arm64        TensorRT development libraries and headers
ii  libnvinfer-samples                            5.1.6-1+cuda10.0                                all          TensorRT samples and documentation
ii  libnvinfer5                                   5.1.6-1+cuda10.0                                arm64        TensorRT runtime libraries
ii  python-libnvinfer                             5.1.6-1+cuda10.0                                arm64        Python bindings for TensorRT
ii  python-libnvinfer-dev                         5.1.6-1+cuda10.0                                arm64        Python development package for TensorRT
ii  python3-libnvinfer                            5.1.6-1+cuda10.0                                arm64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev                        5.1.6-1+cuda10.0                                arm64        Python 3 development package for TensorRT
ii  tensorrt                                      5.1.6.1-1+cuda10.0                              arm64        Meta package of TensorRT
ii  uff-converter-tf                              5.1.6-1+cuda10.0                                arm64        UFF converter for TensorRT package

Am I misunderstanding the install instructions?

**Comment by rmccorm4** [comment]
Hi @JustinMBrown,

I'm not sure that building from source is supported for Jetson at the moment. The supported path is to use Jetpack.

JetPack 4.3 Developer Preview, which is packaged with TRT6 is available as a beta here: https://developer.nvidia.com/jetpack-4_3_DP

Stay tuned for the official production release of Jetpack 4.3.

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.

**Comment by wumeng2** [comment]
> Closing - Reopen if you are still having a problem.
@rmccorm4 hi, thank you for tensorrt. it is nice tools. Now, I  need to use tensorrt7.0 for cuda10.0 and cudnn7.6 in jetson nano(arrch64).  I know tensorrt6.0 for cuda10.0 in jetpack4.3 and tensorrt7.1 for cuda10.2 in  jetpack4.4. Is this way to compile tensorrt7.0 from source  feasibleI ?  Looking forward to your reply.
