### ISSUE TITLE
C++ model drop accuracy compare to python.

### ISSUE THREAD

**Issue by quocnhat** [NVIDIA/TensorRT#1520]
I saw both detection and reID result are not good as the original in the python environment.
I don't know whether I was wrong or c++ model drop accuracy compare to it in python.
Any comment is very appreciated. Thanks

**Comment by ttyio** [comment]
@quocnhat , python is just a thin layer that wrap C++ using pybind11, check https://github.com/NVIDIA/TensorRT/tree/main/python, there should not be any accuracy difference, do you have simple repro? thanks
