### ISSUE TITLE
Could NOT find TENSORRT (missing: TENSORRT_LIBRARY)

### ISSUE THREAD

**Issue by Ragu2399** [NVIDIA/TensorRT#1522]
Find TensorRT libs at TENSORRT_LIBRARY_INFER-NOTFOUND;TENSORRT_LIBRARY_INFER_PLUGIN-NOTFOUND
-- Could NOT find TENSORRT (missing: TENSORRT_LIBRARY)
ERRORCannot find TensorRT library.
-- Adding new sample: sample_algorithm_selector
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_char_rnn
--     - Parsers Used: uff;caffe;onnx
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_dynamic_reshape
--     - Parsers Used: onnx
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_fasterRCNN
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: sample_googlenet
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_int8
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: sample_int8_api
--     - Parsers Used: onnx
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_mlp
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_mnist
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_mnist_api
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_nmt
--     - Parsers Used: none
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_onnx_mnist
--     - Parsers Used: onnx
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_reformat_free_io
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_ssd
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: sample_uff_fasterRCNN
--     - Parsers Used: uff
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: sample_uff_maskRCNN
--     - Parsers Used: uff
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: sample_uff_mnist
--     - Parsers Used: uff
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_uff_plugin_v2_ext
--     - Parsers Used: uff
--     - InferPlugin Used: OFF
--     - Licensing: samples
-- Adding new sample: sample_uff_ssd
--     - Parsers Used: uff
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: sample_onnx_mnist_coord_conv_ac
--     - Parsers Used: onnx
--     - InferPlugin Used: ON
--     - Licensing: samples
-- Adding new sample: trtexec
--     - Parsers Used: caffe;uff;onnx
--     - InferPlugin Used: OFF
--     - Licensing: samples
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUBLASLT_LIB
    linked by target "nvinfer_plugin" in directory E:/TensorRT/plugin
CUBLAS_LIB
    linked by target "nvinfer_plugin" in directory E:/TensorRT/plugin
    linked by target "sample_algorithm_selector" in directory E:/TensorRT/samples/sampleAlgorithmSelector
    linked by target "sample_char_rnn" in directory E:/TensorRT/samples/sampleCharRNN
    linked by target "sample_dynamic_reshape" in directory E:/TensorRT/samples/sampleDynamicReshape
    linked by target "sample_fasterRCNN" in directory E:/TensorRT/samples/sampleFasterRCNN
    linked by target "sample_googlenet" in directory E:/TensorRT/samples/sampleGoogleNet
    linked by target "sample_int8" in directory E:/TensorRT/samples/sampleINT8
    linked by target "sample_int8_api" in directory E:/TensorRT/samples/sampleINT8API
    linked by target "sample_mlp" in directory E:/TensorRT/samples/sampleMLP
    linked by target "sample_mnist" in directory E:/TensorRT/samples/sampleMNIST
    linked by target "sample_mnist_api" in directory E:/TensorRT/samples/sampleMNISTAPI
    linked by target "sample_nmt" in directory E:/TensorRT/samples/sampleNMT
    linked by target "sample_onnx_mnist" in directory E:/TensorRT/samples/sampleOnnxMNIST
    linked by target "sample_reformat_free_io" in directory E:/TensorRT/samples/sampleReformatFreeIO
    linked by target "sample_ssd" in directory E:/TensorRT/samples/sampleSSD
    linked by target "sample_uff_fasterRCNN" in directory E:/TensorRT/samples/sampleUffFasterRCNN
    linked by target "sample_uff_maskRCNN" in directory E:/TensorRT/samples/sampleUffMaskRCNN
    linked by target "sample_uff_mnist" in directory E:/TensorRT/samples/sampleUffMNIST
    linked by target "sample_uff_plugin_v2_ext" in directory E:/TensorRT/samples/sampleUffPluginV2Ext
    linked by target "sample_uff_ssd" in directory E:/TensorRT/samples/sampleUffSSD
    linked by target "sample_onnx_mnist_coord_conv_ac" in directory E:/TensorRT/samples/sampleOnnxMnistCoordConvAC
    linked by target "trtexec" in directory E:/TensorRT/samples/trtexec
CUDART_LIB
    linked by target "nvinfer_plugin" in directory E:/TensorRT/plugin
    linked by target "sample_algorithm_selector" in directory E:/TensorRT/samples/sampleAlgorithmSelector
    linked by target "sample_char_rnn" in directory E:/TensorRT/samples/sampleCharRNN
    linked by target "sample_dynamic_reshape" in directory E:/TensorRT/samples/sampleDynamicReshape
    linked by target "sample_fasterRCNN" in directory E:/TensorRT/samples/sampleFasterRCNN
    linked by target "sample_googlenet" in directory E:/TensorRT/samples/sampleGoogleNet
    linked by target "sample_int8" in directory E:/TensorRT/samples/sampleINT8
    linked by target "sample_int8_api" in directory E:/TensorRT/samples/sampleINT8API
    linked by target "sample_mlp" in directory E:/TensorRT/samples/sampleMLP
    linked by target "sample_mnist" in directory E:/TensorRT/samples/sampleMNIST
    linked by target "sample_mnist_api" in directory E:/TensorRT/samples/sampleMNISTAPI
    linked by target "sample_nmt" in directory E:/TensorRT/samples/sampleNMT
    linked by target "sample_onnx_mnist" in directory E:/TensorRT/samples/sampleOnnxMNIST
    linked by target "sample_reformat_free_io" in directory E:/TensorRT/samples/sampleReformatFreeIO
    linked by target "sample_ssd" in directory E:/TensorRT/samples/sampleSSD
    linked by target "sample_uff_fasterRCNN" in directory E:/TensorRT/samples/sampleUffFasterRCNN
    linked by target "sample_uff_maskRCNN" in directory E:/TensorRT/samples/sampleUffMaskRCNN
    linked by target "sample_uff_mnist" in directory E:/TensorRT/samples/sampleUffMNIST
    linked by target "sample_uff_plugin_v2_ext" in directory E:/TensorRT/samples/sampleUffPluginV2Ext
    linked by target "sample_uff_ssd" in directory E:/TensorRT/samples/sampleUffSSD
    linked by target "sample_onnx_mnist_coord_conv_ac" in directory E:/TensorRT/samples/sampleOnnxMnistCoordConvAC
    linked by target "trtexec" in directory E:/TensorRT/samples/trtexec
CUDNN_LIB
    linked by target "nvinfer_plugin" in directory E:/TensorRT/plugin
    linked by target "sample_algorithm_selector" in directory E:/TensorRT/samples/sampleAlgorithmSelector
    linked by target "sample_char_rnn" in directory E:/TensorRT/samples/sampleCharRNN
    linked by target "sample_dynamic_reshape" in directory E:/TensorRT/samples/sampleDynamicReshape
    linked by target "sample_fasterRCNN" in directory E:/TensorRT/samples/sampleFasterRCNN
    linked by target "sample_googlenet" in directory E:/TensorRT/samples/sampleGoogleNet
    linked by target "sample_int8" in directory E:/TensorRT/samples/sampleINT8
    linked by target "sample_int8_api" in directory E:/TensorRT/samples/sampleINT8API
    linked by target "sample_mlp" in directory E:/TensorRT/samples/sampleMLP
    linked by target "sample_mnist" in directory E:/TensorRT/samples/sampleMNIST
    linked by target "sample_mnist_api" in directory E:/TensorRT/samples/sampleMNISTAPI
    linked by target "sample_nmt" in directory E:/TensorRT/samples/sampleNMT
    linked by target "sample_onnx_mnist" in directory E:/TensorRT/samples/sampleOnnxMNIST
    linked by target "sample_reformat_free_io" in directory E:/TensorRT/samples/sampleReformatFreeIO
    linked by target "sample_ssd" in directory E:/TensorRT/samples/sampleSSD
    linked by target "sample_uff_fasterRCNN" in directory E:/TensorRT/samples/sampleUffFasterRCNN
    linked by target "sample_uff_maskRCNN" in directory E:/TensorRT/samples/sampleUffMaskRCNN
    linked by target "sample_uff_mnist" in directory E:/TensorRT/samples/sampleUffMNIST
    linked by target "sample_uff_plugin_v2_ext" in directory E:/TensorRT/samples/sampleUffPluginV2Ext
    linked by target "sample_uff_ssd" in directory E:/TensorRT/samples/sampleUffSSD
    linked by target "sample_onnx_mnist_coord_conv_ac" in directory E:/TensorRT/samples/sampleOnnxMnistCoordConvAC
    linked by target "trtexec" in directory E:/TensorRT/samples/trtexec
RT_LIB
    linked by target "sample_algorithm_selector" in directory E:/TensorRT/samples/sampleAlgorithmSelector
    linked by target "sample_char_rnn" in directory E:/TensorRT/samples/sampleCharRNN
    linked by target "sample_dynamic_reshape" in directory E:/TensorRT/samples/sampleDynamicReshape
    linked by target "sample_fasterRCNN" in directory E:/TensorRT/samples/sampleFasterRCNN
    linked by target "sample_googlenet" in directory E:/TensorRT/samples/sampleGoogleNet
    linked by target "sample_int8" in directory E:/TensorRT/samples/sampleINT8
    linked by target "sample_int8_api" in directory E:/TensorRT/samples/sampleINT8API
    linked by target "sample_mlp" in directory E:/TensorRT/samples/sampleMLP
    linked by target "sample_mnist" in directory E:/TensorRT/samples/sampleMNIST
    linked by target "sample_mnist_api" in directory E:/TensorRT/samples/sampleMNISTAPI
    linked by target "sample_nmt" in directory E:/TensorRT/samples/sampleNMT
    linked by target "sample_onnx_mnist" in directory E:/TensorRT/samples/sampleOnnxMNIST
    linked by target "sample_reformat_free_io" in directory E:/TensorRT/samples/sampleReformatFreeIO
    linked by target "sample_ssd" in directory E:/TensorRT/samples/sampleSSD
    linked by target "sample_uff_fasterRCNN" in directory E:/TensorRT/samples/sampleUffFasterRCNN
    linked by target "sample_uff_maskRCNN" in directory E:/TensorRT/samples/sampleUffMaskRCNN
    linked by target "sample_uff_mnist" in directory E:/TensorRT/samples/sampleUffMNIST
    linked by target "sample_uff_plugin_v2_ext" in directory E:/TensorRT/samples/sampleUffPluginV2Ext
    linked by target "sample_uff_ssd" in directory E:/TensorRT/samples/sampleUffSSD
    linked by target "sample_onnx_mnist_coord_conv_ac" in directory E:/TensorRT/samples/sampleOnnxMnistCoordConvAC
    linked by target "trtexec" in directory E:/TensorRT/samples/trtexec
TENSORRT_LIBRARY_INFER
    linked by target "nvonnxparser" in directory E:/TensorRT/parsers/onnx
    linked by target "nvonnxparser_static" in directory E:/TensorRT/parsers/onnx
TENSORRT_LIBRARY_INFER_PLUGIN
    linked by target "nvonnxparser" in directory E:/TensorRT/parsers/onnx
    linked by target "nvonnxparser_static" in directory E:/TensorRT/parsers/onnx

-- Configuring incomplete, errors occurred!
See also "E:/TensorRT/build/CMakeFiles/CMakeOutput.log".
See also "E:/TensorRT/build/CMakeFiles/CMakeError.log".
PS E:\TensorRT\build>  msbuild ALL_BUILD.vcxproj
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj

**Comment by laoxing797373** [comment]
Have you solved it yet?

**Comment by nvpohanh** [comment]
@Ragu2399 Did you install TensorRT via https://developer.nvidia.com/nvidia-tensorrt-download ?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
