### ISSUE TITLE
[Perf] TF-TRT (TRT 6.0) 3D pooling/convolutions slower than TF

### ISSUE THREAD

**Issue by ralovich** [NVIDIA/TensorRT#153]
$ python3 /usr/lib/python3.6/dist-packages/uff/bin/convert_to_uff.py model_100.pb -o model_100.uff
Loading model_100.pb
WARNING:tensorflow:From /usr/lib/python3.6/dist-packages/uff/bin/../../uff/converters/tensorflow/conversion_helpers.py:227: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

NOTE: UFF has been tested with TensorFlow 1.14.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.5
[...]
Warning: No conversion function registered for layer: Conv3D yet.
Converting inception_v3_3d_1/inception_1/mixed_35x35x256a/branch1x1/Conv/Conv3D as custom op: Conv3D
[...]
Warning: No conversion function registered for layer: AvgPool3D yet.
Converting inception_v3_3d_1/inception_1/mixed_35x35x256a/branch_pool/AvgPool3D as custom op: AvgPool3D
Warning: No conversion function registered for layer: MaxPool3D yet.
Converting inception_v3_3d_1/full_conv/pool2 as custom op: MaxPool3D
[...]

**Comment by rmccorm4** [comment]
Hi @ralovich,

Conv3D and 3D pooling are supported by the ONNX parser as seen here: https://github.com/onnx/onnx-tensorrt/blob/master/operators.md

You can convert your Tensorflow model to ONNX using tf2onnx: https://github.com/onnx/tensorflow-onnx

and then use TensorRT's ONNX parser to convert to TensorRT instead. See the relevant ONNX samples for this.

**Comment by ralovich** [comment]
> Hi @ralovich,
> 
> Conv3D and 3D pooling are supported by the ONNX parser as seen here: https://github.com/onnx/onnx-tensorrt/blob/master/operators.md
> 
> You can convert your Tensorflow model to ONNX using tf2onnx: https://github.com/onnx/tensorflow-onnx
> 
> and then use TensorRT's ONNX parser to convert to TensorRT instead. See the relevant ONNX samples for this.

Hi @rmccorm4,

thank you for looking into this! Unfortunately tf2onnx is not able to deal with 3D convolutions and pooling due to https://github.com/onnx/tensorflow-onnx/issues/461 . A reproducer network that fails is available at: https://github.com/ralovich/trt-regression . Am I missing something?

**Comment by xiuxin121** [comment]
same issue.the tensorflow-onnx:https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py
def conv_kernel_shape(ctx, node, input_idx, spatial=2):
    kernel_shape = ctx.get_shape(node.input[input_idx])
    if len(kernel_shape) != 2 * spatial:
        raise ValueError("kernel rank must be 2* spatial")
    kernel_shape = kernel_shape[0:spatial]
    node.set_attr("kernel_shape", kernel_shape)
    return kernel_shape
it is only support 2dconv????

**Comment by rmccorm4** [comment]
Hi @ralovich,

It seems it's not yet supported on the tf2onnx side of things. It looks like they plan to implement it based on demand: https://github.com/onnx/tensorflow-onnx/issues/461#issuecomment-547417664

You could try to play with TF-TRT until that happens to see if that works for you: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usingtftrt

**Comment by ralovich** [comment]
> Hi @ralovich,
> 
> It seems it's not yet supported on the tf2onnx side of things. It looks like they plan to implement it based on demand: [onnx/tensorflow-onnx#461 (comment)](https://github.com/onnx/tensorflow-onnx/issues/461#issuecomment-547417664)
> 
> You could try to play with TF-TRT until that happens to see if that works for you: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usingtftrt

Dear @rmccorm4,

thank you for the suggestion. We have patched TF-TRT [already](https://github.com/tensorflow/tensorflow/commit/4297539768bfb6d45d3248fc6471e84e260efc6c) to allow 3D pooling to be offloaded as well. Unfortunately it appears to be slower (!) than TF for 3D convnets in our testing [report1](https://devtalk.nvidia.com/default/topic/1064822/tensorrt/tensorrt-6-slower-than-tensorflow-with-3d-convolutions-and-pooling/) and [report2](https://stackoverflow.com/questions/58607849/how-to-avoid-tensorrt-6-0-1-preformance-regression-against-tensorflow-with-3d-co). Is this expected? We have shared a [reproducer](https://github.com/ralovich/trt-regression) for this, do you think someone from NVIDIA could help looking into it?

Thank you,
Kristof

**Comment by xiuxin121** [comment]
i user TF-TRT without&nbsp;3D pooling. it can speed up 20%x




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ralovich"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 下午4:51
收件人: "NVIDIA/TensorRT"<TensorRT@noreply.github.com&gt;; 
抄送: "树之荫"<1093625517@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [NVIDIA/TensorRT] UFF converter 0.6.5 does not support 3D pooling and convolutions (TRT 6.0.1) (#153)



 
Hi @ralovich,
 
It seems it's not yet supported on the tf2onnx side of things. It looks like they plan to implement it based on demand: onnx/tensorflow-onnx#461 (comment)
 
You could try to play with TF-TRT until that happens to see if that works for you: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usingtftrt
  
Dear @rmccorm4,
 
thank you for the suggestion. We have patched TF-TRT already to allow 3D pooling to be offloaded as well. Unfortunately it appears to be slower (!) than TF for 3D convnets in our testing report1 and report2. Is this expected? We have shared a reproducer for this, do you think someone from NVIDIA could help looking into it?
 
Thank you,
 Kristof

**Comment by rmccorm4** [comment]
Hi @ralovich,

Thanks for sharing all of this information. I passed it on to the engineering team and hopefully they can help figure out the issue.

**Comment by rmccorm4** [comment]
Hi @ralovich,

1. Can you share **verbose** TF logs for your repro model as mentioned here: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#verbose

2. Can you share the following environment information? The CUDNN version may be particularly important for 3D convolution performance:

## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Operating System + Version**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by ralovich** [comment]
> ## Environment
> **TensorRT Version**:
> **GPU Type**:
> **Nvidia Driver Version**:
> **CUDA Version**:
> **CUDNN Version**:
> **Python Version (if applicable)**:
> **TensorFlow Version (if applicable)**:
> **PyTorch Version (if applicable)**:
> **Operating System + Version**:
> **Baremetal or Container (if container which image + tag)**:

Environment
TensorRT Version: 6.0.1-1+cuda10.0
GPU Type: GeForce GTX 1080
Nvidia Driver Version: 430.26 
CUDA Version: 10.0.130-1
CUDNN Version: 7.6.3.30-1+cuda10.0
Python Version (if applicable): N/A
TensorFlow Version (if applicable): 1.15 branch + https://github.com/tensorflow/tensorflow/commit/4297539768bfb6d45d3248fc6471e84e260efc6c
PyTorch Version (if applicable): N/A
Operating System + Version: Ubuntu 18.04.3 LTS
Baremetal or Container (if container which image + tag): Baremetal

**Comment by rmccorm4** [comment]
Thanks, I'll pass it on

**Comment by zheng-xing** [comment]
> Hi @ralovich,
> 
> It seems it's not yet supported on the tf2onnx side of things. It looks like they plan to implement it based on demand: [onnx/tensorflow-onnx#461 (comment)](https://github.com/onnx/tensorflow-onnx/issues/461#issuecomment-547417664)
> 
> You could try to play with TF-TRT until that happens to see if that works for you: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usingtftrt

Hi @rmccorm4 ,

Thanks for your response.
I managed to convert models in TensorFlow with Conv3D operator in Pytorch and then inside Pytorch managed to export to ONNX format.

However, when I tried to parse this model with TensorRT-6.0.1.5 on Windows platform, I got the warning: 

> While parsing node number 0 [pad]:
> ERROR: builtin_op_importers.cpp:1415 In function importPad:
> [8] Assertion failed: onnx_padding.size() == 8

It looks like the parser does not support 3D input, right?

Thanks in advance.
Zheng

**Comment by rmccorm4** [comment]
Hi @ralovich,

Sorry no ones gotten back to me and thus I haven't gotten back to you.

However, TRT 7.0 was just released yesterday, could you see if perhaps your performance problems were fixed in the new version? 

Similarly, maybe upgrading to CUDNN 7.6.5 could help as well. I noticed as I say this that the docs specifically mention that CUDNN 7.6.5 is the supported version here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-601/tensorrt-support-matrix/index.html. It may be related.

**Comment by rmccorm4** [comment]
@zheng-xing I'm guessing this was your response based on the username, but does this help solve your issue: https://devtalk.nvidia.com/default/topic/1068358/tensorrt/assertion-failed-onnx_padding-size-8/post/5413011/#5413011 ?

**Comment by zheng-xing** [comment]
> @zheng-xing I'm guessing this was your response based on the username, but does this help solve your issue: https://devtalk.nvidia.com/default/topic/1068358/tensorrt/assertion-failed-onnx_padding-size-8/post/5413011/#5413011 ?

Yes, that's my reply. I do manage to solve my problem with the 3D pooling operator after merging it into the Conv3D operator.

**Comment by rmccorm4** [comment]
Thanks for the quick reply @zheng-xing, can you share a code snippet for merging the pooling 3d op into the conv 3D op to help other users that experience this issue? That would be greatly appreciated!

**Comment by zheng-xing** [comment]
> Thanks for the quick reply @zheng-xing, can you share a code snippet for merging the pooling 3d op into the conv 3D op to help other users that experience this issue? That would be greatly appreciated!

Sorry was busy with other stuff. 
Definitely. I used the following code for the conversion. I'm not sure it is the best way to do so because I am also new to this.

```
import onnx

model = onnx.load("your_model.onnx")

padNodeList = []
for i in range(147):
    if model.graph.node[i].op_type == "Pad" and model.graph.node[i+1].op_type == "Conv":
        padNodeList.append(i)

# modify the Pad3D op
for ind_pad in padNodeList:
    # Conv3D op is always after Pad3D op
    ind_conv = ind_pad + 1 

    # copy the padding size
    model.graph.node[ind_conv].attribute[3].ints[0] = model.graph.node[ind_pad].attribute[1].ints[2]
    model.graph.node[ind_conv].attribute[3].ints[1] = model.graph.node[ind_pad].attribute[1].ints[3]
    model.graph.node[ind_conv].attribute[3].ints[2] = model.graph.node[ind_pad].attribute[1].ints[4]
    model.graph.node[ind_conv].attribute[3].ints[3] = model.graph.node[ind_pad].attribute[1].ints[7]
    model.graph.node[ind_conv].attribute[3].ints[4] = model.graph.node[ind_pad].attribute[1].ints[8]
    model.graph.node[ind_conv].attribute[3].ints[5] = model.graph.node[ind_pad].attribute[1].ints[9]

# Convert Pad3D to Identity op, which is mostly supported
for ind_pad in padNodeList:
    del model.graph.node[ind_pad].attribute[0:3]
    model.graph.node[ind_pad].op_type = "Identity"

onnx.save(model, "your_model_updated.onnx")
```

For me, the `Pad` and `Conv` op looks like following:
Pad node

> input: "136"
> output: "137"
> op_type: "Pad"
> attribute {
>   name: "mode"
>   s: "constant"
>   type: STRING
> }
> attribute {
>   name: "pads"
>   ints: 0
>   ints: 0
>   ints: 1
>   ints: 1
>   ints: 1
>   ints: 0
>   ints: 0
>   ints: 1
>   ints: 1
>   ints: 1
>   type: INTS
> }
> attribute {
>   name: "value"
>   f: 0.0
>   type: FLOAT
> }

And Conv node

> input: "137"
> input: "block.1.dilation_block.0.residual_block.1.convolutional_block.3.weight"
> output: "138"
> op_type: "Conv"
> attribute {
>   name: "dilations"
>   ints: 1
>   ints: 1
>   ints: 1
>   type: INTS
> }
> attribute {
>   name: "group"
>   i: 1
>   type: INT
> }
> attribute {
>   name: "kernel_shape"
>   ints: 3
>   ints: 3
>   ints: 3
>   type: INTS
> }
> attribute {
>   name: "pads"
>   ints: 0
>   ints: 0
>   ints: 0
>   ints: 0
>   ints: 0
>   ints: 0
>   type: INTS
> }
> attribute {
>   name: "strides"
>   ints: 1
>   ints: 1
>   ints: 1
>   type: INTS
> }
>

**Comment by zheng-xing** [comment]
> > Hi @ralovich,
> > It seems it's not yet supported on the tf2onnx side of things. It looks like they plan to implement it based on demand: [onnx/tensorflow-onnx#461 (comment)](https://github.com/onnx/tensorflow-onnx/issues/461#issuecomment-547417664)
> > You could try to play with TF-TRT until that happens to see if that works for you: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usingtftrt
> 
> Dear @rmccorm4,
> 
> thank you for the suggestion. We have patched TF-TRT [already](https://github.com/tensorflow/tensorflow/commit/4297539768bfb6d45d3248fc6471e84e260efc6c) to allow 3D pooling to be offloaded as well. Unfortunately it appears to be slower (!) than TF for 3D convnets in our testing [report1](https://devtalk.nvidia.com/default/topic/1064822/tensorrt/tensorrt-6-slower-than-tensorflow-with-3d-convolutions-and-pooling/) and [report2](https://stackoverflow.com/questions/58607849/how-to-avoid-tensorrt-6-0-1-preformance-regression-against-tensorflow-with-3d-co). Is this expected? We have shared a [reproducer](https://github.com/ralovich/trt-regression) for this, do you think someone from NVIDIA could help looking into it?
> 
> Thank you,
> Kristof

@ralovich @rmccorm4 

I recently managed to run a network that is full of conv3d operations with different dilation values and no 3d pooling, with TensorRT v7.  I also observe performance drop.
With TF at FP32, the inference takes about 0.5-0.6 seconds. With TensorRT 7 at FP32, it takes about 0.8-0.9 seconds. And TensorRT 7 at FP16 is relatively same with TF at FP32. And I have a RTX 2080 ti.

Sincerely,
Zheng

**Comment by rajeevsrao** [comment]
@zheng-xing thanks for the last update. We are investigating this.

**Comment by ralovich** [comment]
After switching to TensorRT 7.1.3.4 the slowdown does not appear to be present. The issue may be closed from our side. Thank you!
