### ISSUE TITLE
build samples with cmake error

### ISSUE THREAD

**Issue by tjich** [NVIDIA/TensorRT#1530]
## Description

When I build samples, there is a cmake error.
My cmake version is not problem. it is 3.21.2, I have tried 3.14,
always this error... 

CMake Error at CMakeSamplesTemplate.txt:22 (set_ifndef):
  Unknown CMake command "set_ifndef".
Call Stack (most recent call first):
  sampleAlgorithmSelector/CMakeLists.txt:23 (include)

## Environment

**TensorRT Version**:  7.2
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System**: Centos7
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

cd samples
mkdir build
cd build
cmake ..

**Comment by ttyio** [comment]
Hello @tjich , have you tried using the docker ?

https://github.com/NVIDIA/TensorRT/tree/release/8.2#generate-the-tensorrt-oss-build-container

thanks

**Comment by musicrainie** [comment]
The same error occurred to me.
![QQ截图20220118175713](https://user-images.githubusercontent.com/8542925/149914644-76e4b7c0-2148-41cf-9f4c-c894a35b9c4c.png)

**Comment by musicrainie** [comment]
The answer is it should be built under 'TensorRT/' not 'TensorRT/samples'. Nothing anymore.

**Comment by nvpohanh** [comment]
closing this issue for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
