### ISSUE TITLE
Using tensorrt to load two different models in one process, the following error and warning occurs，please help me？

### ISSUE THREAD

**Issue by zsffuture** [NVIDIA/TensorRT#1539]
WARNING: The logger passed into createInferBuilder differs from one already provided for an existing builder, runtime, or refitter. TensorRT maintains only a single logger pointer at any given time, so the existing value, which can be retrieved with getLogger(), will be used instead. In order to use a new logger, first destroy all existing builder, runner or refitter objects.

**Comment by linyu0219** [comment]
you need two classes.
In def init:
1.pycuda.autoinit()  
2.iniation the runtime engine context stream.
3.Make a predict function,which use the runtime engine context stream to infer
4. set self.predict = predict
in def forward :
 use self.predict

by the way, when use multiprocess https://forums.developer.nvidia.com/t/how-to-use-tensorrt-by-the-multi-threading-package-of-python/123085/8

**Comment by nvpohanh** [comment]
@zsffuture That warning should have been fixed in the latest TRT (8.4.1). Could you give it a try? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
