### ISSUE TITLE
Does trtexec option inputIOFormats indeed need ?

### ISSUE THREAD

**Issue by linyu0219** [NVIDIA/TensorRT#1542]
I have two input of shape((1,3,256,256)->image , (1,512) -> a float latent ).
I don't use inputIOFormats when i use --fp16.
I don't use inputIOFormats because i don't know how to write the format of the(1,512) latent.
I find it works, the speed is faster than fp32, is it really worked at fp16?
But the input dtype must fp32,maybe the default inputIOFormats=fp32  worked.
I don't know why modify the option inputIOFormats=fp16 when use --fp16, does  indeed need ?

Can anyone tell me how to use it?
Thank you very much.

**Comment by ttyio** [comment]
Hello @linyu0219 , TensorRT can insert the `reformat` layer in places where layout changed in the neighbor layers. the `inputIOFormats` just used to save the remove between input tensor and the first layer. It is fine to build FP16 network without this option.
Thanks!

**Comment by linyu0219** [comment]
thanks for your answer, I got it .
