### ISSUE TITLE
how to input a 5-dimensional matrix in tensorrt to inference by c++

### ISSUE THREAD

**Issue by HW140701** [NVIDIA/TensorRT#1553]
My deep learning model requires a 5-bit matrix as input data, but tensorrt only provides Dims4. So how to input a 5-dimensional matrix in tensorrt to inference by c++?

**Comment by ttyio** [comment]
Hello @HW140701 , could you use `Dims32`
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_dims32.html

TRT supports up to 8 dims tensor, thanks!

**Comment by HW140701** [comment]
> Hello @HW140701 , could you use `Dims32` https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_dims32.html
> 
> TRT supports up to 8 dims tensor, thanks!

Thanks for your reply . I have solved this problem, you can check the specific solution:[https://www.stubbornhuang.com/1761/](https://www.stubbornhuang.com/1761/)
