### ISSUE TITLE
dynamic shape

### ISSUE THREAD

**Issue by Qiancj0605** [NVIDIA/TensorRT#1557]
@ttyio Hi，If the input batchsize is 50，what is the batchsize during inference？

Set as follows：dynamic shape([-1,4561])
    auto profile = builder->createOptimizationProfile();
    profile->setDimensions(“inputname”, OptProfileSelector::kMIN, Dims{8, 4561});
    profile->setDimensions(“inputname”,, OptProfileSelector::kOPT, Dims{32, 4561});
    profile->setDimensions(“inputname”,, OptProfileSelector::kMAX, Dims{64, 4561});

**Comment by ttyio** [comment]
@Qiancj0605 , trt has symbolic system, and the actual batchsize is the same as the one you specified in `set_binding_shape`.

**Comment by ttyio** [comment]
Hello @Qiancj0605 , during inference, the input shape is determined before `enqueue`, right? You need call `set_binding_shape` whenever the input shape changed. Else the behavior is undefined.

**Comment by ttyio** [comment]
Hi @Qiancj0605 ,
we will first filter all the valid algorithm using [kMIN, kMAX], then setup the problem size to kOPT in the filter out algorithms. finally choose the fastest one.

**Comment by ttyio** [comment]
I will close this since the question is answered, thanks!
