### ISSUE TITLE
Runtime - > deserializecudaengine() causes the CPU to consume too much memory

### ISSUE THREAD

**Issue by liyaoshun** [NVIDIA/TensorRT#1558]
## Description

Why does calling the runtime - > deserializecudaengine() function to deserialize the TRT model increase the CPU memory consumption, rather than just increasing the GPU memory?
using :
       1. CPU mem : 800MB
       2. GPU mem : 433MB

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: Jetson Xavier NX
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: Jetpack 4.4   32.4.2
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
Hello @liyaoshun , because there is also some CPU side setup for some of the kernels. We can also check the cudnn library, we can see both CPU and GPU memory are increased when we load cudnn library. thanks!

**Comment by liyaoshun** [comment]
Thank you for your reply. Through the Valgrind tool, we also found that cudnn occupied CPU memory
