### ISSUE TITLE
I want to use int8 fro tensort calibration and I get the engine as none.

### ISSUE THREAD

**Issue by matinhosseiny** [NVIDIA/TensorRT#1570]
## Description

I tried to change the sample of resnet to int8 and I got the builder engine as empty but when I try exact same code for trt.BuilderFlag.FP16 I can create the output.

## Environment

**TensorRT Version**: 8.0.1.6-1+cuda10.2 
**NVIDIA Driver Version**: jetson46
**Operating System**: Ubuntu 16 
**Python Version (if applicable)**: 3.6

The code is as follows:

def build_engine_onnx(model_file):

    builder = trt.Builder(TRT_LOGGER)

    network = builder.create_network(common.EXPLICIT_BATCH)
    config = builder.create_builder_config()

    config.set_flag(trt.BuilderFlag.INT8)
    parser = trt.OnnxParser(network, TRT_LOGGER)

    config.max_workspace_size = common.GiB(1)

    with open(model_file, 'rb') as model:
        if not parser.parse(model.read()):
            print ('ERROR: Failed to parse the ONNX file.')
            for error in range(parser.num_errors):
                print (parser.get_error(error))
            return None
    return builder.build_engine(network, config)

**Comment by nvpohanh** [comment]
@matinhosseiny Should you show the verbose logs so that we can debug this? Thanks

**Comment by matinhosseiny** [comment]
I was working on this last year. I fixed it. if someone has this problem change the code to newer version.
