### ISSUE TITLE
How change python data or object to the PluginField format of TensorRT

### ISSUE THREAD

**Issue by MichaelWU0726** [NVIDIA/TensorRT#1571]
## Description

How change the List(int) object or List(custom class) or numpy objects to the trt.PluginField format of TensorRT?  

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: RTX2080Ti
**NVIDIA Driver Version**: 460.80
**CUDA Version**: cuda11.1
**CUDNN Version**: 0.8
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.7.8

## Relevant Files

1. [class tensorrt.PluginField(*args, **kwargs)](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-723/api/python_api/infer/Plugin/IPluginCreator.html#tensorrt.PluginField)
2. [yolov5 in wang-xinyu](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5)
3. [yolov5 in my github](https://github.com/MichaelWU0726/TRTx/tree/main/YOLOv5)
4. [the issue commited by me](https://github.com/wang-xinyu/tensorrtx/issues/781)

## Steps To Reproduce

`data` needed by `__init__()` must be a buffer object and I don't know what's that. I tried to wrapper the list object with `numpy.array()` but the plugin output shape was incorrectly gotten by `getOutputDimensions` in the `create_plugin()` after running as No.4 in Relevant Files. So i guessed there are problems in PluginFields.

**Comment by MichaelWU0726** [comment]
> @MichaelWU0726 I just realized that it makes more sense for you to reference the plugin creator code here:
> 
> https://github.com/jkjung-avt/tensorrt_demos/blob/master/plugins/yolo_layer.cu#L330-L334

I did something for it and it still didn't work. I tried to debug it and found [the first wh](https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/plugins/yololayer.cu#L310-L311) was inconsistent as  [that passed to `PluginFieldCollection()`](https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/YOLOv5/yololayer.py#L284).

Their values as following:
I inspected the `wh_0` is [80 80]
```
wh_0:array([80, 80], dtype=int32)
wh_1:array([40, 40], dtype=int32)
wh_2:array([20, 20], dtype=int32)
```
I also inspected the `wh_0` by [the cout commands](https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/plugins/yololayer.cu#L327-L328)
```
1: 20 20
3: 40 40
5: 20 20
```
It showed those `wh_0` were not same. I hope to get your help,thanks!

**Comment by jkjung-avt** [comment]
1. https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/YOLOv5/yololayer.py#L284-L285
   You add 3 pairs of "wh" and "anchor" with exactly the same FieldCollection names.  I think this is not good.  It would be better to use, say, "wh_0", "anchor_0",  "wh_1", "anchor_1",  "wh_2", and "anchor_2".

2. https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/plugins/yololayer.cu#L291-L292
   Wouldn't these 2 assertions fail??

3. https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/plugins/yololayer.cu#L308-L309

   This code is obviously wrong.  You check whether the PluginField data type is "float32", but you access the data as "int" type!

4. I think this is what you try to accomplish in the for loop.
```
        for (int i = 1; i < fc->nbFields; i += 2)
        {
            Yolo::YoloKernel kernel;

            // handle kernel wh
            assert(strcmp(fc->fields[i].name, "wh") == 0);
            assert(fc->fields[i].type == PluginFieldType::kFLOAT32);
            // NOTE: wh has been passed in from Python code as float32!
            float *p_yolo = (float*)(fc->fields[i].data);
            kernel.width  = (int)(p_yolo[0]);
            kernel.height = (int)(p_yolo[1]);

            // handle kernel anchor
            assert(strcmp(fc->fields[i+1].name, "anchor") == 0);
            assert(fc->fields[i+1].type == PluginFieldType::kFLOAT32);
            memcpy(kernel.anchors, static_cast<const float*>(fc->fields[i].data), CHECK_COUNT * 2 * sizeof(float));

            kernels[(i+1)/2] = kernel;
        }
```

**Comment by MichaelWU0726** [comment]
> 1. https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/YOLOv5/yololayer.py#L284-L285
>    You add 3 pairs of "wh" and "anchor" with exactly the same FieldCollection names.  I think this is not good.  It would be better to use, say, "wh_0", "anchor_0",  "wh_1", "anchor_1",  "wh_2", and "anchor_2".
> 2. https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/plugins/yololayer.cu#L291-L292
>    Wouldn't these 2 assertions fail??
> 3. https://github.com/MichaelWU0726/TRTx/blob/55efd9a58f85e74afcbf4448dc319bfad9908a8c/plugins/yololayer.cu#L308-L309
>    This code is obviously wrong.  You check whether the PluginField data type is "float32", but you access the data as "int" type!
> 4. I think this is what you try to accomplish in the for loop.
> 
> ```
>         for (int i = 1; i < fc->nbFields; i += 2)
>         {
>             Yolo::YoloKernel kernel;
> 
>             // handle kernel wh
>             assert(strcmp(fc->fields[i].name, "wh") == 0);
>             assert(fc->fields[i].type == PluginFieldType::kFLOAT32);
>             // NOTE: wh has been passed in from Python code as float32!
>             float *p_yolo = (float*)(fc->fields[i].data);
>             kernel.width  = (int)(p_yolo[0]);
>             kernel.height = (int)(p_yolo[1]);
> 
>             // handle kernel anchor
>             assert(strcmp(fc->fields[i+1].name, "anchor") == 0);
>             assert(fc->fields[i+1].type == PluginFieldType::kFLOAT32);
>             memcpy(kernel.anchors, static_cast<const float*>(fc->fields[i].data), CHECK_COUNT * 2 * sizeof(float));
> 
>             kernels[(i+1)/2] = kernel;
>         }
> ```

I'm sorry，I had updated new codes before your view, which some codes were inconsistent. Could you review my codes? Or, have a look to [my new issue](https://github.com/NVIDIA/TensorRT/issues/1595) from this repo?

**Comment by jkjung-avt** [comment]
@MichaelWU0726  I think I have pointed out most of the problems in your code.  Please debug the code by yourself.

**Comment by MichaelWU0726** [comment]
> @MichaelWU0726 I think I have pointed out most of the problems in your code. Please debug the code by yourself.

You only pointed out type errors because some codes include types have been updated before you viewed . In fact, type errors didn't exist. What's more, type problems weren't related about my issue, otherwise the same cycles had only the first one wrong!

**Comment by MichaelWU0726** [comment]
> @MichaelWU0726 I think I have pointed out most of the problems in your code. Please debug the code by yourself.

**Comment by oxana-nvidia** [comment]
closing this one as issue is discussed in https://github.com/NVIDIA/TensorRT/issues/1595
