### ISSUE TITLE
[Question] LSTM via Loop vs RNNv2

### ISSUE THREAD

**Issue by o0fatigue** [NVIDIA/TensorRT#1572]
From the [document](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#replacing-with-loops) I found that RNNv2 is deprecated. Since the document does not metion much about it (replacing rnnv2 layer with loop API), may I ask a few questions?

1. What is the motivation behind? Or, how will I benefit from it?
2. Is it expected with better performance (inference speed)?
3. Is it expected with int8 quantization support?

**Comment by ttyio** [comment]
Hello @o0fatigue ,

1. We switch to new backend for the loop based API. it is more generic and efficient.
2. Yes.
3. Only INT8 QAT now, but we will also support INT8 PTQ in the future.

Thanks!
