### ISSUE TITLE
How to perform multiple trt inferences on one GPU at the same time

### ISSUE THREAD

**Issue by wojiazaiyugang** [NVIDIA/TensorRT#1576]
## Description

Hello, I need to run multiple trt models at the same time to complete the task together, such as a detection model for detection, and then the detected results will enter another classification model for classification. I use multiple processes to run. I found that when running multiple models at the same time, the inference speed of each model will slow down. For example, when there is only one model running, the inference time is 10ms. When there are 10 models inferring at the same time, it will take a few Ten to several hundred ms, how can I solve it? I tried mps but it didn't work well

## Environment

**TensorRT Version**:  7.2
**NVIDIA GPU**:  2080TI
**NVIDIA Driver Version**:  
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by peterlee909** [comment]
I would also like to find the answer for this question.

**Comment by oxana-nvidia** [comment]
Hi @wojiazaiyugang,

You can try to use Triton Inference Server that has TensorRT as one of its backends.
https://github.com/triton-inference-server/server/blob/main/docs/model_management.md

**Comment by nvpohanh** [comment]
> For example, when there is only one model running, the inference time is 10ms. When there are 10 models inferring at the same time, it will take a few Ten to several hundred ms, how can I solve it?

@wojiazaiyugang Isn't this expected? If one inference takes 10ms and already takes up most of GPU compute resource, you would expect that the latency to become 10x when there are 10 models running in parallel, since GPU compute resource is limited.


closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
