### ISSUE TITLE
Support on 1080 and Titan X

### ISSUE THREAD

**Issue by anmol039w** [NVIDIA/TensorRT#158]
Hi does this sample works on GTX 1080 ti and Titian X?

**Comment by rmccorm4** [comment]
Hi @anmol039w,

You can see the support matrix for hardware here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#hardware-precision-matrix

And according to here: http://www.nvidia.com/object/geforce_family.html, both GTX 1080 ti and Titan X have Compute Capability 6.1

Please refer to the support matrix row above corresponding to CC6.1 for what is supported and not supported.

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.

**Comment by anmol039w** [comment]
Thanks for the support ryan

**Comment by Edwardmark** [comment]
@rmccorm4 how to get compute capability using cpp code?

**Comment by rmccorm4** [comment]
@Edwardmark I'm not sure off the top of my head. What's your goal for knowing CC? 

TensorRT has some built-in methods to see if the hardware supports things like FP16/INT8, if that's what you're looking for: 
https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_builder.html#a1d18b948852cb088d22a87cff70a2b2f
