### ISSUE TITLE
pytorch-quantization Zero-point must be Int32, Float or Half, found

### ISSUE THREAD

**Issue by AncientRemember** [NVIDIA/TensorRT#1580]
# the date type incompilate
## pytorch-quantization call torch.fake_quantize_per_channel_affine
https://github.com/NVIDIA/TensorRT/blob/96e23978cd6e4a8fe869696d3d8ec2b47120629b/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py#L294

## the pytorch implements constraint
https://github.com/pytorch/pytorch/blob/fc82ad186a943c9f75ef5adbe101cc8abccf6976/aten/src/ATen/native/quantized/fake_quant_per_channel_affine.cpp#L51

```
std::tuple<Tensor, Tensor> fake_quantize_per_channel_affine_cachemask(
    const Tensor& self,
    const Tensor& scale,
    const Tensor& zero_point,
    int64_t axis,
    int64_t quant_min,
    int64_t quant_max) {
  TORCH_CHECK(zero_point.scalar_type() == ScalarType::Int || zero_point.scalar_type() == ScalarType::Float || zero_point.scalar_type() == ScalarType::Half,
              "Zero-point must be Int32, Float or Half, found ", zero_point.scalar_type());
  TORCH_CHECK(scale.dim() == 1, "scale should be a 1-D tensor");
  TORCH_CHECK(zero_point.dim() == 1, "zero point should be a 1-D tensor");
  TORCH_CHECK(
      scale.numel() == zero_point.numel(),
      "scale and zero-point need to have the same dimensions");
  TORCH_CHECK(
      scale.numel() == self.size(axis),
      "dimensions of scale and zero-point are not consistent with input tensor")

  TORCH_CHECK(
      quant_min <= quant_max,
      "`quant_min` should be less than or \
        equal to `quant_max`.");

  TORCH_CHECK(
      at::min(zero_point).item().toInt() >= quant_min &&
          at::max(zero_point).item().toInt() <= quant_max,
      "`zero_point` must be between `quant_min` and `quant_max`.");

  TORCH_CHECK(
      axis >= 0 && axis <= self.dim(),
      "`axis` must be between 0 and number of dimensions of input");
```

**Comment by pommedeterresautee** [comment]
Hi, I tried to quantize a Bert based model and got similar error message when trying to perform onnx export:
```
RuntimeError: Zero-point must be Int32, found Long
```

**Comment by ttyio** [comment]
Good catch @AncientRemember , just checked current quantization toolkit support pytorch up to 1.8, the constrain is added in newer version, we will update the code when we move to new pyT. thanks again!

**Comment by jinfagang** [comment]
@ttyio Does it solved now? I met this problem as well. I don't know which code caused it in pytorch_quantization

**Comment by ttyio** [comment]
@jinfagang  It is already fixed in latest version, see

https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py#L294
