### ISSUE TITLE
tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py license?

### ISSUE THREAD

**Issue by tambry** [NVIDIA/TensorRT#1582]
Top-level `LICENSE` specifies that `tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py` is BSD 3-clause. However, [the file itself](https://github.com/NVIDIA/TensorRT/blob/9ec6eb6db39188c9f3d25f49c8ee3a9721636b56/tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py) only has the Apache 2.0 header. [When it was added](https://github.com/NVIDIA/TensorRT/commit/d7baf010e4396c87d58e4d8a33052c01c2d89325#diff-8602dd68bd9d132794e870cc55684df8243efa03092962d6e9d25b71ac0c4723) it also had a BSD 3-clause header.

Please clarify the licencing situation for this file. Is it dual-licenced, Apache 2.0 only or BSD 3-clause only?

**Comment by ttyio** [comment]
thanks @tambry , I have created internal request for this.

**Comment by nvpohanh** [comment]
@ttyio Has this been fixed?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Comment by tambry** [comment]
I'm unable to re-open this issue. The BSD 3-clause header seems to have been added to the file, but the Apache 2.0 kept and a SPDX licence identifier for Apache 2.0 also added. Apache 2.0 and BSD 3-clause are probably compatible, but I believe the identifier ought to specify the original licence unless NVIDIA has gotten permission from all copyright holders to licence it as Apache 2.0 as there might be wording nuances that might change the substance if there were any disputes. Or at least the identification ought to specify both licences.
