### ISSUE TITLE
Christian Rau's half.h license?

### ISSUE THREAD

**Issue by tambry** [NVIDIA/TensorRT#1583]
Top-level `LICENSE` specifies that `samples/common/half.h` is MIT. The [file itself](https://github.com/NVIDIA/TensorRT/blob/9ec6eb6db39188c9f3d25f49c8ee3a9721636b56/samples/common/half.h) however also has the Apache 2.0 header.

Please clarify whether the author (Christian Rau) has granted permission to additionally licence this under Apache 2.0.

Other copies of the same file, `parsers/common/ieee_half.h` and `third_party/ieee/half.h` do not include an Apache 2.0 header. It would seem helpful to mention them together with `samples/common/half.h` in `LICENSE`.

**Comment by ttyio** [comment]
Thanks @tambry , I have create internal issue to track this.

**Comment by rajeevsrao** [comment]
Fixed in the 22.04 release.
