### ISSUE TITLE
[Question] trtexec with multi streams

### ISSUE THREAD

**Issue by ShiyangZhang** [NVIDIA/TensorRT#1590]
Hi, 
I built an engine with dynamic batching input, and num_optimization_profiles == 1,

but trtexec support streams=2. How it happend, as multi-contexts can not  use the same profile at the same time? Did I miss something?

**Comment by ttyio** [comment]
Hello @ShiyangZhang , yes you are right, when dynamic shape is enabled, each profile can only assign to single context.
I just check trtexec:

   --streams=N                 Instantiate N engines to use concurrently

So we create 2 engines in your case. thanks

**Comment by ShiyangZhang** [comment]
thx

[related](https://github.com/NVIDIA/TensorRT/issues/1597#issue)

**Comment by nvpohanh** [comment]
@yuekaizhang trtexec does not support multiple optimization profiles yet
