### ISSUE TITLE
How to implement multi-instance tensorrt with dynamic batch-shape?

### ISSUE THREAD

**Issue by ShiyangZhang** [NVIDIA/TensorRT#1597]
Hi, 
How to implement multi-instance tensorrt with dynamic batch-shape?  As tensorrt does  not support multi optimization profiles with the same shape. So it is hard to use multi contexts, and we have to deserialize multi engines.

**Comment by ttyio** [comment]
Hello @ShiyangZhang , we could create multiple optimization profile with the same shape. What's the error you hit? thanks

**Comment by Horikita123** [comment]
with Profile 0 has been chosen by another IExecutionContext. Use another profileIndex or destroy the IExecutionContext that use this profile.

**Comment by ShiyangZhang** [comment]
Yes we could create multiple optimization profile with the same shape. But when I try to use the second profile,
tensorrt says: Profile 0 has been chosen by another IExecutionContext. Use another profileIndex or destroy the IExecutionContext that use this profile. It seems that profile 1 is a reference to profile 0

**Comment by ShiyangZhang** [comment]
> Hello @ShiyangZhang , we could create multiple optimization profile with the same shape. What's the error you hit? thanks

Yes we can call addOptimizationProfile multi-times with the same shape.  But tensorrt says:
Profile 0 has been chosen by another IExecutionContext. Use another profileIndex or destroy the IExecutionContext that use this profile.

**Comment by ttyio** [comment]
@ShiyangZhang , do you have a simple repro? thanks!

**Comment by ShiyangZhang** [comment]
@ttyio 
Here it is. 
It says : _[TensorRT] WARNING: Could not set default profile 0 for execution context. Profile index must be set explicitly._

```python
from __future__ import print_function

import os
import numpy as np

import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)  # VERBOSE WARNING INFO


def get_engine(
    batching_sizes=(1, 1, 8),
    onnx_bytes="",
    fp16_mode=False
):

    explicit_batch = 1 << (int)(
        trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(explicit_batch) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        parser.parse(onnx_bytes)
        for i in range(parser.num_errors):
            print("TensorRT ONNX parser error:", parser.get_error(i))
        if 0 != (parser.num_errors):
            return None

        config = builder.create_builder_config()
        config.max_workspace_size = 1 << 30  # 1GB
        for _ in range(2):
            profile = builder.create_optimization_profile()

            net_sp = network.get_input(0).shape

            if net_sp[0] != -1 and net_sp[0] != 1:
                print("onnx: batch dim must be dynamic or one: ", net_sp)
                return None
            net_sp_3 = net_sp[1:]

            profile.set_shape(
                network.get_input(0).name,
                (batching_sizes[0], *net_sp_3),
                (batching_sizes[1], *net_sp_3),
                (batching_sizes[2], *net_sp_3),
            )

            if builder.platform_has_tf32:
                print("tf32 enabled")
                config.set_flag(trt.BuilderFlag.TF32)
            if fp16_mode:
                if not builder.platform_has_fast_fp16:
                    print("fp16 not supported, use fp32 instead ")
                else:
                    config.set_flag(trt.BuilderFlag.FP16)

            config.add_optimization_profile(profile)
        engine = builder.build_engine(network, config)

        if engine is None:
            print("Failed to create the engine")
            return None
        print("num_optimization_profiles ", engine.num_optimization_profiles)
        contexts = []
        for i in range(2):

            context = engine.create_execution_context()
            contexts.append(context)
        return engine


def main():
    onnx_file_path = "/workspace/models/layer1.onnx"  # dynamic onnx -1, 3, 224, 224
    if not os.path.exists(onnx_file_path):
        quit("ONNX file {} not found".format(onnx_file_path))

    with open(onnx_file_path, "rb") as f:

        engine = get_engine(
            batching_sizes=(1, 1, 8),
            onnx_bytes=f.read(),
            fp16_mode=True)


if __name__ == '__main__':
    main()
```

**Comment by ttyio** [comment]
Thanks @ShiyangZhang , the warning is no harm here, this is because the default profile is 0 after you call:

              engine.create_execution_context()

So you can safe to run the remaining of the code since you change the `active_optimization_profile` immediate after `create_execution_context`

**Comment by ShiyangZhang** [comment]
@ttyio thx, I got it.
