### ISSUE TITLE
About tensorrt on tx2

### ISSUE THREAD

**Issue by faedtodd** [NVIDIA/TensorRT#16]
how cani build tensorrt 5.1.5-open source on tx2

**Comment by xiaoxiaotao** [comment]
Do you solve it,please?

**Comment by faedtodd** [comment]
> Do you solve it,please?

mei a, xiong di, help

**Comment by rajeevsrao** [comment]
This is a duplicate of https://github.com/NVIDIA/TensorRT/issues/9. We are working on it for upcoming release (soon).

**Comment by rmccorm4** [comment]
Closing as dup of #9, which was solved: https://github.com/NVIDIA/TensorRT/issues/9#issuecomment-575106079
