### ISSUE TITLE
why tensorRT lib is not included in this rep

### ISSUE THREAD

**Issue by zchuang11** [NVIDIA/TensorRT#160]
I want to install the tensorRT from source by cmake, but the lib folder is not found ?

**Comment by rmccorm4** [comment]
Hi @zchuang11 ,

The TensorRT source can be installed from here: https://developer.nvidia.com/tensorrt which should come with the `lib/` folder after installing.

This repo only contains the current open source components.

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.
