### ISSUE TITLE
Ask for reservation of related model infos during the conversion 

### ISSUE THREAD

**Issue by SpringWave1** [NVIDIA/TensorRT#1601]
## Description
For my case, after using gs to import & export my `.onnx` file, the exported model holds a different `ir_version` compared with the original `.onnx`. It also loses the producer_name, producer_version information, which makes it unavailable in my target backend device. I manually changed it back, but I wonder whether you can add the feature to the lib.

```
onnx.save(gs.export_onnx(graph), "modified.onnx")
md = onnx.load("modified.onnx")
md.ir_version = imported_model.ir_version
md.producer_name = imported_model.producer_name
md.producer_version = imported_model.producer_version
onnx.save(md, "modified.onnx")
```

## Steps To Reproduce
any `.onnx`

**Comment by ttyio** [comment]
Thanks @SpringWave1 , I have created internal request to tracking this.

**Comment by ttyio** [comment]
this will be released in next build, thanks
