### ISSUE TITLE
Missing weights when refitting from an onnx

### ISSUE THREAD

**Issue by doramasma** [NVIDIA/TensorRT#1612]
## Description

I'm trying to refit a model already loaded in TRT (this model before refit performs as expected), from the weights, reads from a model in onnx format. However, after performing the refitting, the results obtained are not expected.

## Environment

**TensorRT Version**: 8.0.3.4
**NVIDIA GPU**: 2060 RTX
**NVIDIA Driver Version**:  496.49
**CUDA Version**: 11.5
**Operating System**: Windows 11
**Python Version (if applicable)**: 3.8.10
**PyTorch Version (if applicable)**: 1.10.0
**Docker  Container**: FROM nvcr.io/nvidia/tensorrt:21.10-py3

## Steps To Reproduce

So, I perform the refitting as follows:

1. I load the engine (from a TRT file), and create the trt.Refitter from that engine.
```
engine = get_engine("path/name_model.onnx", "path/name_model.trt")

refitter = trt.Refitter(engine, trt.Logger())
``` 
2. I load the onnx model, and create the graph using "onnx_graphsurgeon". Then, I iterate over all the possible refittable weights, and I set the weights. 

```
import onnx
import onnx_graphsurgeon as gs

original_model = onnx.load("path/name_model.onnx")
graph = gs.import_onnx(original_model)

for name in refitter.get_all_weights():

    if graph.tensors()[name].shape is not None:
        refitter.set_named_weights(name, graph.tensors()[name].values)
    else:
        print(graph.tensors()[name])

for x in refitter.get_missing_weights():
    refitter.set_named_weights(x, np.array([30],dtype='float32'))

refitter.refit_cuda_engine()
```
At this points, there are some things to take into account:

- The "original_model" (onnx) has some layers that are type variable and has shape=None and dtype=None
![image](https://user-images.githubusercontent.com/7035260/141292768-f0b682e6-6bd7-4ea3-9fa7-2825fc88c9ef.png)

- If we only perform refitting over the weights that have shape, we can't perform `refitter.refit_cuda_engine()` as after refit there are some missing weights, specifically, some of the layers that in onxx has not shape.
![image](https://user-images.githubusercontent.com/7035260/141296990-2a4b1290-c106-4c2b-beb5-cbaf4c772b22.png)

 
- Using Netron, I notice that the layers with no shape in onnx, are referred to a constant value of 30. So, I loop over the missing weights and set the value to 30. After that, I was able to perform refit `refitter.refit_cuda_engine() == True` 
![image](https://user-images.githubusercontent.com/7035260/141297101-94aca01e-9abd-4be8-b6f7-e7d6f5419088.png)

3. I allocate the buffers, and do inference (this workflow works, due to the fact that the model in TRT without refit performs as expected). 

Any idea what the problem might be? Thank you in advance

**Comment by doramasma** [comment]
@pranavm-nvidia

**Comment by pranavm-nvidia** [comment]
Does this happen with TensorRT 8.2 as well? And does the model you're refitting with have exactly the same structure as the original?

**Comment by doramasma** [comment]
- I have not been able to test it with TensorRT 8.2 yet (I'm really excited about the engine-inspector). Since, I'm waiting for the docker container to be released.
- Yes, the models have the same structure. 
- Also, I tested to refit the model using the same weights. In other words, the weights that I used for these tests are the same that I used for the creation of the TRT engine from the onnx file. And I notice that i could refit all the weights, except 1 layer... So, it could be that TensorRT for that layer makes something internally, and now it is not compatible with the weights of the onnx file? 

I hope I have explained myself correctly, best regards.

**Comment by pranavm-nvidia** [comment]
The ONNX parser may generate new weights or transform existing ones, so that could be the source of the problem. In the latter case, you would have to mimic the weight transformations when refitting. There were some improvements for that in TRT 8.2, so it's possible that this is already fixed there. 

In the meantime, do you see any warning messages from the ONNX parser regarding the weights in the model?

**Comment by doramasma** [comment]
Hi, again! 

I check the messages from the ONNX parser: 

_[11/17/2021-09:23:59] [W] [TRT] ShapedWeights.cpp:171: Weights model.xxx has been transposed with permutation of (1, 0)! If you plan on overwriting the weights with the Refitter API, the new weights must be pre-transposed._

So, I permute that layer, and finally, the refit WORKS! 

I really, appreciate all your support, thanks!

**Comment by shanyu155** [comment]
Hi， I have the same problem.
Could you tell me  how to permute that layer,Thanks!
