### ISSUE TITLE
torch.einusm   how to convert it to trt?  trt8.0 support this op?

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/TensorRT#1617]
[TensorRT] VERBOSE: ModelImporter.cpp:179: Reshape_55 [Reshape] outputs: [231 -> (-1, -1, -1, -1, -1)], 
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: Einsum_56 [Einsum]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 231
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 602
[TensorRT] VERBOSE: ModelImporter.cpp:125: Einsum_56 [Einsum] inputs: [231 -> (-1, -1, -1, -1, -1)], [602 -> (3, 26, 26)], 
[TensorRT] INFO: ModelImporter.cpp:135: No importer registered for op: Einsum. Attempting to import as plugin.
[TensorRT] INFO: builtin_op_importers.cpp:3771: Searching for plugin: Einsum, plugin_version: 1, plugin_namespace: 
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin Einsum version 1
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

**Comment by ttyio** [comment]
Hello @henbucuoshanghai , `Einsum` is supported in 8.2, could you upgrade your trt? thanks

**Comment by henbucuoshanghai** [comment]
@ttyio thanks for ur answer。I am native TRT user，trt8.2 has this op?

**Comment by ttyio** [comment]
yes @henbucuoshanghai , 
https://github.com/onnx/onnx-tensorrt/blob/e9456d57605c883cdf985e634ab483e2c1500bb1/builtin_op_importers.cpp#L1333

**Comment by henbucuoshanghai** [comment]
nvinfer1::IEinsumLayer* einsumLayer = ctx->network()->addEinsum

I see,tks,trt8.2 is great,I will try it
