### ISSUE TITLE
export QAT model to onnx file

### ISSUE THREAD

**Issue by nanmi** [NVIDIA/TensorRT#1619]
## Description

When I export QAT model to onnx file, I find this problem:
 ```shell
/root/.virtualenvs/py38/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0,
/root/.virtualenvs/py38/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])

```

## Environment

**TensorRT Version**: 8005
**NVIDIA GPU**: T4
**NVIDIA Driver Version**: 460.73.01
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: None
**PyTorch Version (if applicable)**: 1.10.0
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
Hello @nanmi , did you call below code before export ONNX? thanks!

    quant_nn.TensorQuantizer.use_fb_fake_quant = True

**Comment by nanmi** [comment]
> Hello @nanmi , did you call below code before export ONNX? thanks!
> 
> ```
> quant_nn.TensorQuantizer.use_fb_fake_quant = True
> ```

Yes, I have added this, I found that when I export onnx with opset=10, it whill not generated the question , but if somebody use `per-channel quantization` he must use opset=11,so opset 11 will generate this problem.Thanks.
