### ISSUE TITLE
How to implement "Expand" operation???

### ISSUE THREAD

**Issue by reborm** [NVIDIA/TensorRT#162]
Hi, I use TensorRT6.0 to transfer my pytorch model into the TensorRT model. My model has the "Expand" operation. but I find that the TensorRT seems to unsupport the "Expand" operation. Could anyone enlight me how to solve this problem of walk around this problem?? By the way, my model is mobileNet V3. here is my error information and the location of my "Expand" operation.
The error is:
While parsing node number 43 [Expand -> "277"]:
ERROR: /home/xxx/tools/onnx-tensorrt/ModelImporter.cpp:140 In function importNode:
[8] No importer registered for op: Expand

The location in my model is:
    def forward(self, x):
        b, c, d, e = x.size()
        y = self.avg_pool(x).view(b, c)
        y = self.fc(y).view(b, c, 1, 1)
        #result = x*y

        #test4 = y.resize(1,16,56,56)
        #result = x*y.expand_as(x)
        #print(result.size())
        return x * y.expand_as(x)

**Comment by rmccorm4** [comment]
Hi @reborm,

According to here: https://github.com/onnx/onnx-tensorrt/blob/master/operators.md

The `Expand` op isn't yet supported.

There does seem to be a similar effort for converting MobilenetV3 -> ONNX -> TensorRT, maybe there is a workaround or reference for avoiding the Expand op: https://github.com/rwightman/gen-efficientnet-pytorch/blob/master/geffnet/mobilenetv3.py

**Comment by reborm** [comment]
Hi, @rmccorm4
It's Ok!!! Thank you very much

**Comment by ShaneYS** [comment]
> Hi, @rmccorm4
> It's Ok!!! Thank you very much

how do you solve this problem?
