### ISSUE TITLE
A BUG? Why pytorch_quantization toolkit default output have ERROR

### ISSUE THREAD

**Issue by nanmi** [NVIDIA/TensorRT#1621]
## Description

When use fake quantization with pytorch_quantization toolkit, i find a problem like a bug
QAT default use fake quantization,but pytorch_quantization/nn/modules/tensor_quantizer.py line 120 defalut output ERROR? 

## Environment

**TensorRT Version**: 8005
**NVIDIA GPU**: T4
**NVIDIA Driver Version**: 460.73.01
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: Ubuntu18.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: None
**PyTorch Version (if applicable)**: 1.10.0
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
Hello @nanmi , PyTorch 1.10.0 is not tested, could you try `nvcr.io/nvidian/pytorch:21.09-py3`?

**Comment by nanmi** [comment]
> 你好@nanmi，PyTorch 1.10.0 没有经过测试，你能试试`nvcr.io/nvidian/pytorch:21.09-py3`吗？谢谢

Thanks, I have test Pytorch 1.10.0 and I known that the question can be ignored when program running.
