### ISSUE TITLE
How to accelerate Albert with tensorrt?

### ISSUE THREAD

**Issue by mdztravelling** [NVIDIA/TensorRT#1622]
## Environment

**TensorRT Version**:  8.0.3
**NVIDIA GPU**:  T4
**NVIDIA Driver Version**:  465.19.01 
**CUDA Version**: 11.3
**CUDNN Version**: 7
**Operating System**:  CentOS 8.2
**Python Version (if applicable)**:  3.8
**Tensorflow Version (if applicable)**:  2.6
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

How to  accelerate albert  use tensorrt?

**Comment by ttyio** [comment]
Hello @mdztravelling , have you tried using Albert onnx model with TRT 8.2? thanks!

**Comment by mdztravelling** [comment]
> Hello @mdztravelling , have you tried using Albert onnx model with TRT 8.2? thanks!

I tried it  but does not work. I'm writing albert plugin now.

**Comment by ttyio** [comment]
@mdztravelling , which ONNX operator is unsupported? thanks

**Comment by mdztravelling** [comment]
> @mdztravelling , which ONNX operator is unsupported? thanks

you can  refer to this link https://forums.developer.nvidia.com/t/how-to-accelerate-albert-with-tensorrt/195622/9, it show error infomations.

**Comment by ttyio** [comment]
Thanks @mdztravelling , I have create internal request for `onehot`.

**Comment by mdztravelling** [comment]
> Thanks @mdztravelling , I have create internal request for `onehot`.

Thanks @ttyio ！

**Comment by mdztravelling** [comment]
This repo ( https://github.com/mdztravelling/albert_trt_plugin  ) is albert's plugin with tensorrt 8.0.3.

**Comment by ttyio** [comment]
closing old issues that is inactive for long time, thanks all!
