### ISSUE TITLE
[E] [TRT] UffParser: Validator error: functional_1/up_sampling2d_5/resize/ResizeNearestNeighbor: Unsupported operation _ResizeNearestNeighbor

### ISSUE THREAD

**Issue by neverstoplearn** [NVIDIA/TensorRT#1631]
## Description

when I use trtexec to transform uff --> trt engine. I got this error:
[E] [TRT] UffParser: Validator error: functional_1/up_sampling2d_5/resize/ResizeNearestNeighbor: Unsupported operation _ResizeNearestNeighbor

## Environment

**TensorRT Version**: 8.2.0
**NVIDIA GPU**:  3060
**NVIDIA Driver Version**: 460.91
**CUDA Version**: 11.2
**CUDNN Version**: 8
**Operating System**: ubuntu20
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

https://github.com/chineseocr/table-detect

**Comment by ttyio** [comment]
Hello @neverstoplearn , could you try exporting ONNX? uff is deprecated, thanks!

**Comment by neverstoplearn** [comment]
ok，thanks.
