### ISSUE TITLE
Internal Error (Assertion min_ <= max_ failed.)

### ISSUE THREAD

**Issue by janbernloehr** [NVIDIA/TensorRT#1634]
## Description

When converting an ONNX model to TensorRT with int8 calibration, we observe the error

```
[TensorRT] VERBOSE: Calculating Maxima
[TensorRT] INFO: Starting Calibration.
[TensorRT] INFO:   Calibrated batch 0 in 2.67053 seconds.
[TensorRT] INFO:   Calibrated batch 1 in 2.61013 seconds.
...
[TensorRT] INFO:   Calibrated batch 49 in 2.70075 seconds.
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 1775, GPU 6334 (MiB)
[TensorRT] ERROR: 2: [quantization.cpp::DynamicRange::65] Error Code 2: Internal Error (Assertion min_ <= max_ failed.)
``` 

This error is new in TensorRT 8. The same ONNX model converts fine on TensorRT 6.0.0 and 7.2.3. Moreover, when a calibration cache exists, then the model can also be converted on TensorRT 8.0.3 / 8.2.0. The error only occurs when converting the model on TRT 8 without a pre-existing calibration cache.

Unfortunately, I cannot share the model right now and would like to extract a minimal example to repro this issue. Any clue on how to identify where (which layer) this error is coming from would be very helpful.

## Environment

**TensorRT Version**: 8.0.3 and 8.2.0
**NVIDIA GPU**:  GTX 1070, RTX 2080 Ti, RTX 3060 Ti
**NVIDIA Driver Version**:  470.74 and 495.29.05
**CUDA Version**: 11.3 and 11.4
**CUDNN Version**: 8.2.1 and 8.2.4
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 2.7
**PyTorch Version (if applicable)**: -
**Baremetal or Container (if so, version)**: -

## Relevant Files

Unfortunately, we cannot share the model right now.

## Steps To Reproduce

```
trt_logger = trt.Logger(trt_logger_severity)

# The onnx parser version we currently use requires this to be used
explicit_batch = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

with trt.Builder(trt_logger) as builder, builder.create_network(explicit_batch) as network:
    with trt.OnnxParser(network, trt_logger) as onnx_parser, builder.create_builder_config() as config:
        profile = trt_builder.create_optimization_profile()
        trt_input = trt_network.get_input(0)
        profile.set_shape(trt_input.name, min=[3, 896, 1792], opt=[3, 896, 1792], max=[3, 896, 1792])
        config.add_optimization_profile(profile)

        config.int8_calibrator = int8_calibrator
        config.flags = config.flags | 1 << (int)(trt.BuilderFlag.INT8)

        cuda_engine = builder.build_engine(network, config)
```

the int8 calibrator implements `trt.IInt8EntropyCalibrator2`

**Comment by janbernloehr** [comment]
The cause of the issue was a division by zero in the network during int8 calibration. It seems this had no effect prior to TRT 8 but now causes this error. It would have been very helpful if the error message contained more information in particular the layer name, and also that the value is nan.

**Comment by Linaom1214** [comment]
same error 
CUDA10.1、CUDNN7.5、tensorrt install by pip wheel

**Comment by ShaneYS** [comment]
same error.
convert ultralytics/yolov5 to int8 with tensorrt8 and encountered this error.
convert is ok with tensorrt7.
any solution?

**Comment by ShaneYS** [comment]
> same error CUDA10.1、CUDNN7.5、tensorrt install by pip wheel

hi, do you solved this error?

**Comment by Data-Iab** [comment]
Try `IInt8MinMaxCalibrator` instead of `IInt8EntropyCalibrator`

**Comment by Data-Iab** [comment]
Another thing you may want to check is the calibration file of the `int8_calibrator`. Make sure there's no previous file with the same name, if so, remove it first.

**Comment by oxana-nvidia** [comment]
@janbernloehr @ShaneYS @Linaom1214  do you have a model to share for developers to reproduce?

**Comment by Maxung** [comment]
@oxana-nvidia I have the same error, also with YOLOv5. Attached is the ONNX file. Using IInt8MinMaxCalibrator as @Data-Iab suggested works, but for the DLA in Jetson devices IInt8EntropyCalibrator2 is required. When using [tensorrtx](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5), which directly implements YOLOv5 in C++ with TRT-API IInt8EntropyCalibrator2 works though.

[yolov5s.onnx.zip](https://github.com/NVIDIA/TensorRT/files/8998950/yolov5s.onnx.zip)

**Comment by oxana-nvidia** [comment]
@Maxung which TensorRT version are you using? is the issue still present if you use TensorRT 8.4? 
Which shape are you using?
Could you please provide more details about your setup? Please use this template if possible:
TensorRT Version: 
NVIDIA GPU: 
NVIDIA Driver Version: 
CUDA Version: 
CUDNN Version:
Operating System: 

I've tried to reproduce the issue using polygraphy tool, but no issues detected (TensorRT 8.4, cuda 11.6, Titan RTX): 
```
polygraphy run yolov5s.onnx --trt --int8
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[I] trt-runner-N0-06/28/22-09:54:11     | Activating and starting inference
[06/28/2022-09:54:12] [TRT] [W] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[I]     Configuring with profiles: [Profile().add('images', min=[32, 3, 640, 640], opt=[32, 3, 640, 640], max=[32, 3, 640, 640])]
[I] Building engine with configuration:
    Workspace            | 16777216 bytes (16.00 MiB)
    Precision            | TF32: False, FP16: False, INT8: True, Obey Precision Constraints: False, Strict Types: False
    Tactic Sources       | ['CUBLAS', 'CUBLAS_LT', 'CUDNN', 'EDGE_MASK_CONVOLUTIONS', 'JIT_CONVOLUTIONS']
    Safety Restricted    | False
    Refittable           | False
    Calibrator           | Calibrator(DataLoader(seed=1, iterations=1, int_range=(1, 25), float_range=(-1.0, 1.0), val_range=(0.0, 1.0)), BaseClass=<class 'tensorrt.tensorrt.IInt8EntropyCalibrator2'>)
    Profiles             | 1 profile(s)
[06/28/2022-09:54:57] [TRT] [W] Missing scale and zero-point for tensor onnx::Transpose_338, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
...
[06/28/2022-09:58:51] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[I] Finished engine building in 278.379 seconds
[I] trt-runner-N0-06/28/22-09:54:11
    ---- Inference Input(s) ----
    {images [dtype=float16, shape=(32, 3, 640, 640)]}
[I] trt-runner-N0-06/28/22-09:54:11
    ---- Inference Output(s) ----
    {output [dtype=float16, shape=(32, 25200, 85)]}
[I] trt-runner-N0-06/28/22-09:54:11     | Completed 1 iteration(s) in 71.7 ms | Average inference time: 71.7 ms.
[I] PASSED | Command: polygraphy run yolov5s.onnx --trt --int8
```

**Comment by oxana-nvidia** [comment]
@Maxung Thanks for detailed repro! 
I've created an internal bug to investigate.
Internal number: 3700165
cc @nvpohanh @jhalakp-nvidia

**Comment by oxana-nvidia** [comment]
We are still debugging the issue, no updates about root cause at this point. 
Our engineering team is suggesting a workaround for now to change the input image type from FP32 to FP16. Specifically, in int8dataloader.py change 
`img = np.ascontiguousarray(img, dtype=np.float32)`
to
`img = np.ascontiguousarray(img, dtype=np.float16)`

@Maxung please try if it is applicable to your case.

**Comment by Maxung** [comment]
@oxana-nvidia thank you for the follow up, I forgot to mention it here, but I searched for alternatives and when using the Polygraphy tool with the custom data loader it works fine. So I'm not sure where the error is exactly, but for me it solved the problem.

**Comment by yibinl-nvidia** [comment]
@Maxung the root cause is indeed the mismatch of your input data type (fp32) and onnx model input type (fp16). If the input data is a numpy array, polygraphy checks whether the input type matches expected input type, but in the case of a `data_ptr`, polygraphy skips type check and assumes the input data has the same type as the onnx model expected input type. Float value might be processed incorrectly when the calibrator trying to "cast" fp32 data to fp16, which could write NaN value to the memory. The error is exposed in the creation of quantization histogram where it throws an error of NaN value.

**Comment by clveryang** [comment]
I have the same question, but my situation in the C++ development environment.  The weird point is that errors occur in L4 Gpu, and disappear in T4 Gpu(all in one yolov5 calibrate int8 code and tensorrt is 8.6.1.6).

**Comment by Egorundel** [comment]
Hello, I have the same problem, but I have a C++ code. Can you help me and find a problem place in my code?

https://github.com/Egorundel/int8_calibrator_cpp

**Comment by Egorundel** [comment]
@oxana-nvidia I have the following specifications:

**TensorRT Version**: 8.6.1.6
**NVIDIA GPU**: RTX 3060
**NVIDIA Driver Version**: 555.42.02
**CUDA Version**: 11.1
**CUDNN Version**:  8.0.6
Python Version: 3.8

**Comment by oxana-nvidia** [comment]
@Egorundel 8.6.1 is relatively old version. Could you please try newer version of TRT and cuda? TRT 10.3 is just released. It supports cuda 12.5. 

Have you tried to debug your code? Have you checked that all buffer sizes are as expected? This error message usually shows up when you provide some incorrect pointers to the buffers (actual allocated memory is not of the expected size, most commonly due to the type mismatch).

**Comment by Egorundel** [comment]
@oxana-nvidia Thanks! I've reworked my code and now it's working correctly.

https://github.com/Egorundel/int8_calibrator_cpp
