### ISSUE TITLE
Onnx model conversion - fallback to NoOp kind operation

### ISSUE THREAD

**Issue by tisma** [NVIDIA/TensorRT#1635]
Building the TRT engines from an onnx exported model could be very painful because of the unsupported operations. First of all, there are two separate list of supported operations: 
1. one is the official [onnx operators list](https://github.com/onnx/onnx/blob/master/docs/Operators.md) 
2. second [onnx-tensorrt operators list](https://github.com/onnx/onnx-tensorrt/blob/master/docs/operators.md)

When you develop the model, you're basically limited to the second one list if you want to use TensorRT, and the solution for the unsupported layers are custom plugins.

On the other side, TF-TRT conversion approach gives you less utilization/speedup, but it is a fail-safe conversion since the unsupported operations will fallback to TF's one. That is IMHO better approach since it is guaranteed that conversion will success no matter if there are some unsupported operations.
Is it possible to implement some kind of generic NoOp layer inside TensorRT that will be used when unsupported operation in onnx model is present? For example just to pass-through tensors, or add constant weights or anything that won't be harmful but still makes this conversion to succeed.

**Comment by pranavm-nvidia** [comment]
What's the use-case for this? 
A generic NoOp layer is not really possible because some layers may have a different number of outputs vs. inputs or the outputs may have different shapes than the inputs, etc.

Even if you implemented such a layer, the resulting model would give you garbage outputs and it wouldn't be very useful for latency/throughput metrics either because of the NoOp layers.

**Comment by tisma** [comment]
I know this not a trivial thing to implement, because of different shapes, inputs/outputs, etc. But I cannot quite understand why operations that are not supported simply just can't be inserted as is in the optimized graph?

For example, let use simple imaginary graph:
```
opA -> opB -> opC -> opD -> opE -> opF
```
And let's assume that `opB, opC` are fused into `TRTop1` and `opE, opF` are fused into `TRTop2`
```
opA -> TRTop1 -> opD -> TRTop2
```
And for example `opD` is not supported, why this can't be added to the serialized engines as it is?

My thought is to have a similar behavior like TF-TRT conversion. End users will have a better user experience, now it looks like this is a semi product that could have potential, but isn't polished well. It's fine to let user having ability to implement their own layer via plugins, but again if someone wants to use the onnx exported model, it cannot rely on full onnx specification, but just on the subset of the operations that are supported with TensorRT and custom plugins for the rest.

**Comment by pranavm-nvidia** [comment]
But if TRT doesn't have implementations for `opA` and `opD`, how would you run the engine? 
You'd have to have some kind of mechanism to insert custom implementations into the engine.
Alternatively you would need logic at a higher level to partition the graph and offload subgraphs to TRT or other implementations. 
And if you implement either of those, I think you'd arrive at one of these existing solutions:

- Plugins, where TRT will optimize `opB, opC, opE, opF` and will use provided plugin implementations for `opA` and `opD`. 
- ONNX-Runtime, which is able to offload supported subgraphs to TensorRT and use alternative implementations for layers unsupported by TensorRT. So in your example, ONNX-Runtime might do something like:
```
[opA] (CPU) -> [opB -> opC] (TRT) -> [opD] (CPU) -> [opE -> opF] (TRT)
```

**Comment by tisma** [comment]
>But if TRT doesn't have implementations for opA and opD, how would you run the engine?

Well this is the part that I didn't understand. I thought this could be implemented by some generic operation or insert the NoOp instead, to let the conversion finish instead of break the parsing and report that operation is not supported. My idea was led by TF-TRT conversion and fallback to Tensorflow operation when there is no possibility to create the TRT engine.

>ONNX-Runtime, which is able to offload supported subgraphs to TensorRT and use alternative implementations for layers unsupported by TensorRT.

Did you mean on this onnx-runtime? https://github.com/microsoft/onnxruntime
I see that it also has support for TensorRT backend. I'm wandering if this has solution to the problem with unknown operations that couldn't run TRT and offload those to the CPU instead.

**Comment by pranavm-nvidia** [comment]
Yes, that's the one; this [blog post](https://azure.microsoft.com/en-us/blog/onnx-runtime-integration-with-nvidia-tensorrt-in-preview/) has more information on ONNX-Runtime <-> TRT integration.

**Comment by ttyio** [comment]
Closing since this question is answered, thanks all
