### ISSUE TITLE
Internal Error (Assertion paramWeights.count() == aspectWeights.count() failed.) when convert to engine

### ISSUE THREAD

**Issue by twmht** [NVIDIA/TensorRT#1637]
## Description

I use the [quantization toolkit](https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization) to quantize my model.

but TensorRT threw the exceptions when convert the model to tensorrt engine

```
[11/24/2021-18:03:50] [E] Error[2]: [layerAspects.cpp::flipAspects::24] Error Code 2: Internal Error (Assertion paramWeights.count() == aspectWeights.count() failed.)
[11/24/2021-18:03:50] [E] Error[2]: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
```

the model  is first trained from [mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/configs/atss/) and then quantize by the toolkit. 

the onnx file is provided as below.

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**: 1080 ti
**NVIDIA Driver Version**: 460.73.01
**CUDA Version**: 11.1
**CUDNN Version**: 8.2.1
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**: 3.7

## Relevant Files

[log.txt](https://github.com/NVIDIA/TensorRT/files/7594740/log.txt)

Here are the onnx file
https://drive.google.com/file/d/1kLv4NPM8gBFg_wlyj5hKElhxr_GAJF-j/view?usp=sharing

## Steps To Reproduce

```bash
../TensorRT-8.0.1.6/bin/trtexec --onnx=epoch_12_calib.onnx --int8 --verbose
```

**Comment by twmht** [comment]
It seems that the problem came from FPN(https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/fpn.py). I have tried not to quantize the convolution in FPN, and it can work with trtexec.

**Comment by zerollzeng** [comment]
Could you try TRT 8.2?

**Comment by twmht** [comment]
@zerollzeng 

I can't since it's bundle with jetpack 4.6.

**Comment by liuanhua110** [comment]
meet the same erro any update?

**Comment by oxana-nvidia** [comment]
@twmht @liuanhua110 Could you please check if you can repro this issue with TensorRT 8.4? I've tested on my local set up and issue is not reproducible with provided model.

**Comment by oxana-nvidia** [comment]
Closing as no response provided in >=14  days. Please reopen if there are any updates.
