### ISSUE TITLE
Excuse me! I want to get the bool value from ITensor with DIms(1)  to select index, how can do it?

### ISSUE THREAD

**Issue by thx13** [NVIDIA/TensorRT#1640]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
Hello @thx13 , we support `kBOOL` data type in 

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29

also to make the task easier, maybe you can using PyT or TF to build your network, export ONNX and finally using ONNX2TRT to import your network. Thanks!

**Comment by thx13** [comment]
Thank you so much!
