### ISSUE TITLE
Is it possible to share work load between GPU and CPU?

### ISSUE THREAD

**Issue by yashC97** [NVIDIA/TensorRT#1645]
## Description

Is it possible to divide workload between GPU and Host CPU using TensorRT?

I have my GPU installed on a relatively powerful system which is idle for most part during GPU execution. Can I configure TensorRT to make use of the CPU power by dividing some steps to take place on the CPU and some on the GPU?

My current understanding is that no matter what precision or input format I compile my trt for, the input given to tensorRT is directly given to GPU without using any CPU power. Is this understanding correct?

## Environment

**TensorRT Version**: 8003
**NVIDIA GPU**: NVIDIA T4
**NVIDIA Driver Version**: 450.51.05
**CUDA Version**: 11.0
**CUDNN Version**: 
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
No, TensorRT is a SDK for high-performance deep learning inference in GPU, when you build a TRT engine, the engine only executes on Nvidia hardware.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
