### ISSUE TITLE
segment fault when buildcudaengine

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/TensorRT#1647]
recently，I implemented a custom upsample plugin，but it only support fp32. when i add the support fp16, then it occurs segment fault when buildcudaengine. my tensorrt version is 5.1.5.
if i cancel the support of fp16 in supportformat() function, it will execute smoothly. How to troubleshoot this problem？and
Is there any information about the fp16 plugin?

**Comment by ttyio** [comment]
Hello @GeneralJing ,
This is usually your plugin cuda kernel issue, you need debug your cuda kernel.
BTW, could you upgrade your TRT version, upsample is supported as native operator in newer TRT, thanks!

**Comment by GeneralJing** [comment]
you mean the implementation of the kernel function is something wrong? i add many execution print logs in the plugin class. it seems when the program exit the class, the program went wrong. because our project limit, i cannot just update the version of trt. are there some fp16 upsample plugin materials that i can refer to? thanks.

**Comment by GeneralJing** [comment]
In which version does the upsampling operator begin to be supported？and Is this plugin a closed source part？

**Comment by ttyio** [comment]
Hello @GeneralJing , the cuda kernel is run asynchronously, so maybe you can insert some `cudaDeviceSynchronize()` before exit your plugin. Also you can use cuda-memcheck, it also tells some error detail.

TRT support upsample in 8.0.1 (https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel_8-0-1). 

thanks!

**Comment by GeneralJing** [comment]
OK，thank you for your advice.

**Comment by ttyio** [comment]
Closing and please reopen if you still have question, thanks!
