### ISSUE TITLE
Two dynamic inputs

### ISSUE THREAD

**Issue by zang5xixi** [NVIDIA/TensorRT#1648]
If i have two dynamic inputs, how to write the trtexec command with two dynamic inputs?

```
./trtexec --onnx=model.onnx --minShapes=input1:...,input2:... --optShapes=input1:...,input2:... --maxShapes=iinput1:...,input2:... 
```

**Comment by devaale** [comment]
@zang5xixi 
What was the answer to that ?

**Comment by zang5xixi** [comment]
> 

hi,
i do not know the parameter format in trtexec command last month, but i have already known how to write.
```
trtexec --onnx=model.onnx --minShapes=input1:2x120x120,input2:120 --optShapes=input1:2x150x120,input2:150 --maxShapes=input1:2x200x120,input2:200 
```
x is letter x
