### ISSUE TITLE
Could not find 0.pgm in data directories:

### ISSUE THREAD

**Issue by sbbug** [NVIDIA/TensorRT#165]
Could not find 0.pgm in data directories:

**Comment by rmccorm4** [comment]
Hi @sbbug ,

Please elaborate on your issue. Which sample did you experience this in? Did you download the dataset before running the sample? Did you pass in the right path to the dataset when running the sample?

**Comment by Ewaolx** [comment]
Hi, I think after downloading data, you need to run _generate_pgms.py_ in order to extract _pgms_ from your data.

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.

**Comment by wavesCHJ** [comment]
Hi, @Ewaolx , where can i find the  generate_pgms.py?

**Comment by rmccorm4** [comment]
Hi @wavesCHJ,

I'm not at a computer to look into it for TRT7 as I'm on holiday - it may have been missed. But if you need it now, I think you can copy it out of one of the earlier releases, you could do that easily with a docker container from NGC. Something like this:

```
$ nvidia-docker run -it -v ${PWD}:/mnt nvcr.io/nvidia/tensorrt:19.10-py3
$ cp /opt/tensorrt/samples/data/mnist/generate_pgms.py /mnt
$ exit
# Now the file should be in your current directory
```

The path may not be totally right, just guessing off the top of my head in case you're in a hurry.

**Comment by rmccorm4** [comment]
Answer in other thread: https://github.com/NVIDIA/TensorRT/issues/256#issuecomment-568382745

**Comment by wangtianlong1994** [comment]
I have the opposite problem

If I import torch first and then tensorrt, I will get an error

Traceback (most recent call last):
  File "D:/yolov5/1.py", line 5, in <module>
    import tensorrt as trt
  File "C:\Users\QC\Anaconda3\envs\yolo\lib\site-packages\tensorrt\__init__.py", line 127, in <module>
    ctypes.CDLL(find_lib(lib))
  File "C:\Users\QC\Anaconda3\envs\yolo\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

If I reverse the order, loading the Engine model gets stuck at some point and can't continue
