### ISSUE TITLE
How to use C++ api to convert onnx split op?

### ISSUE THREAD

**Issue by jike-algorithm-zhangxiao** [NVIDIA/TensorRT#1651]
## Environment

**TensorRT Version**: 7.2.2
**NVIDIA GPU**: 3060
**NVIDIA Driver Version**: 
**CUDA Version**: 11.1
**CUDNN Version**: 
**Operating System**: Unbuntu
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

If i want to spilt (1,1024,1,-1) tensor to (1,512,1,-1) and (1,512,1,-1), how can i use the C++ api to do this?
I tried the ISliceLayer, but I don't know how to set the setInput value,
also tried the IGatherlayer, could't get the correct result.
could u give me some advice?

**Comment by ttyio** [comment]
Hello @jike-algorithm-zhangxiao ,
here is the onnx split on implementation, could yo take a check? thanks!

https://github.com/onnx/onnx-tensorrt/blob/e9456d57605c883cdf985e634ab483e2c1500bb1/builtin_op_importers.cpp#L4294

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
