### ISSUE TITLE
Huggingface demos use an older version (4.6.1) of transformers, which has a bug in the implementation of t5

### ISSUE THREAD

**Issue by sam-writer** [NVIDIA/TensorRT#1655]
The Huggingface/demos requirements file [specifies](https://github.com/NVIDIA/TensorRT/blob/main/demo/HuggingFace/requirements.txt#L17) `transformers==4.6.1`

It is my understanding from [this PR in `transformers`](https://github.com/huggingface/transformers/pull/11621) that in 4.6.1 and before, T5's decoder used the encoder's attention mask when decoding and that the changes introduced in that PR (which show up in all versions of `transformers>4.6.1`) change the signature of T5 so that the decoder can have its own attention masking.

(Note: I didn't use the normal issue template because this isn't really a bug in TRT, but it seems worth being aware of.)

**Comment by ttyio** [comment]
Thanks @sam-writer , I have create internal issue to track this。

**Comment by nvpohanh** [comment]
@ttyio Is this still an issue?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
