### ISSUE TITLE
 Cudnn Error in executeConv: 3 (CUDNN_STATUS_BAD_PARAM) when inferencing with dynamic shape on T4

### ISSUE THREAD

**Issue by shiyanan96** [NVIDIA/TensorRT#1657]
## Description

When inferencing image with dynamic shape, it throws out this error:
ERROR: ../rtSafe/cuda/cudaConvolutionRunner.cpp (483) - Cudnn Error in executeConv: 3 (CUDNN_STATUS_BAD_PARAM)
ERROR: FAILED_EXECUTION: std::exception

I have trained the model by pytorch, and transfer pth to the onnx type using export_onnx.py (as shown in Relevant Files), and I use c++ project to compile onnx model to trt type. However, when I compile with fp32(which is default), the transformed trt type throws out the error; but when I compile with fp16, the transformed trt type works well. And the phenomenon only occurs on T4 graphics card, not 2080Ti. In order to exclude the cause of model itself, I changed another pth model, then the same error appeared with both fp32 trt and fp16 trt...

## Environment

**TensorRT Version**:  7.2.3.4
**NVIDIA GPU**: T4
**NVIDIA Driver Version**: 460.73.01
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.5
**Operating System**: Ubuntu 16.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**:  Not Used
**PyTorch Version (if applicable)**: 1.9.0
**Baremetal or Container (if so, version)**: 

## Relevant Files

http://202.168.96.10:8000/relevant_files.tar.gz

## Steps To Reproduce

1 tar -zxvf relevant_files.tar.gz -C ./
2 (already generated segment, this step can skip)  cd build, cmake . ,   make clean and make -j8
3  ./segment compile ../model/model_coco_0.7242.onnx ../model/model_coco_0.7242.trt
4  ./segment run ../model/model_coco_0.7242.trt ../test.jpg ../output.jpg

**Comment by nvpohanh** [comment]
I think this has been fixed as of TensorRT 8.2 or 8.4EA. Could you try upgrading TensorRT version? Thanks

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
