### ISSUE TITLE
Inaccurate detections after exporting the model to tensor rt

### ISSUE THREAD

**Issue by ARMUGHAN-SHAHID** [NVIDIA/TensorRT#1663]
I followed this tutorial [here](https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html) to quantize a pytorch detection model.

PQT (Model Calibration)  and then QAT (Quantization Aware Training) was done, to further tune the weights.
This model was then converted to onnx model and then to tensor rt model. 
 
Visualizing the results, showed that the onnx and pytorch models produced the correct results. 
![result_onnx](https://user-images.githubusercontent.com/16501299/145022239-b80966ee-c0fc-43ce-82d4-9f45ae323d66.png)

 
But when the model was converted to tensor rt using :
`trtexec --int8 --onnx=<model_path> --saveEngine=<output_path> --explicitBatch` 

the results were weird:

![result_trt](https://user-images.githubusercontent.com/16501299/145022314-9c4b0b08-e710-4af9-889a-652e84008843.png)

P.S I also tried a non-quantized pytorch model (the one originally used for QAT), and it gave correct results even after exporting to tensor rt .

**Comment by ttyio** [comment]
hello @ARMUGHAN-SHAHID , have you tried latest TRT 8.2? thanks

**Comment by ARMUGHAN-SHAHID** [comment]
Yes. It gave the same results

**Comment by ttyio** [comment]
thanks @ARMUGHAN-SHAHID , could you share onnx for us to debug? thanks!

**Comment by ARMUGHAN-SHAHID** [comment]
I have shared the file with you via drive/email.

**Comment by ttyio** [comment]
Received thanks @ARMUGHAN-SHAHID ,
what's the input to the network? how did you preprocess your image?

**Comment by ARMUGHAN-SHAHID** [comment]
The input is normalized image with channels last shape. I have shared the pre-processing and post processing code with you .

**Comment by ttyio** [comment]
Thanks @ARMUGHAN-SHAHID , I have create internal bug to track this issue.

**Comment by ttyio** [comment]
@ARMUGHAN-SHAHID , the fix will be available in next major release, thanks!

**Comment by nvpohanh** [comment]
@ttyio Is this fixed in TRT 8.4.1?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
