### ISSUE TITLE
link error: file format not recognized

### ISSUE THREAD

**Issue by yuxianmin** [NVIDIA/TensorRT#1668]
## Description

build TensorRT 8.2.1 fail,  link errors:

```
/usr/bin/ld: cannot find   /home/tensorrt/TensorRT-8.2.1.8/lib:  File format not recognized
collect2: error: ld returned 1 exit status
plugin/CMakeFiles/nvinfer_plugin.dir/build.make:1141: recipe for target 'output/libnvinfer_plugin.so.8.2.1' failed
make[2]: *** [output/libnvinfer_plugin.so.8.2.1] Error 1
CMakeFiles/Makefile2:1192: recipe for target 'plugin/CMakeFiles/nvinfer_plugin.dir/all' failed
make[1]: *** [plugin/CMakeFiles/nvinfer_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
 The directory of /home/tensorrt/TensorRT-8.2.1.8/lib exists.

 `export TRT_LIBPATH=/home/tensorrt/TensorRT-8.2.1.8

cmake .. -DTRT_LIB_DIR=/home/tensorrt/TensorRT-8.2.1.8  -DTRT_OUT_DIR=`pwd`/output -DGPU_ARCHS="61" -Dnvinfer_LIB_PATH=$TRT_LIBPATH/lib -Dnvparsers_LIB_PATH=$TRT_LIBPATH/lib -DCMAKE_CUDA_ARCHITECTURES="61"
`

## Environment

**TensorRT Version**:  8.2.1.8(TensorRT-8.2.1.8.Linux.x86_64-gnu.cuda-10.2.cudnn8.2)
**NVIDIA GPU**: P102-100
**NVIDIA Driver Version**: 440.118.02
**CUDA Version**: 10.2
**CUDNN Version**: 8.2
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@yuxianmin , have you tried using the container to build? thanks

https://github.com/NVIDIA/TensorRT/tree/release/8.2#setting-up-the-build-environment

**Comment by philoxmyu** [comment]
not yet, I will try to build with a container. thanks

**Comment by ttyio** [comment]
Closing and please reopen if you still have question, thanks!

**Comment by jamdodot** [comment]
Excuse me, do we have to use docker to build a container to solve this problem? If so, will the 18.09 version of docker work?



```
export TRT_LIBPATH=/root/TensorRT/TensorRT-8.2.5.1/lib/
export TRT_OSSPATH=/root/TensorRT/TensorRT-8.2.1
cmake .. -DTRT_LIB_DIR=$TRT_LIBPATH -DTRT_OUT_DIR=`pwd`/out -DTRT_PLATFORM_ID=aarch64 -DCUDA_VERSION=11.4 -Dnvinfer_LIB_PATH=$TRT_LIBPATH -Dnvparsers_LIB_PATH=$TRT_LIBPATH


[ 51%] Linking CXX shared library ../out/libnvinfer_plugin.so
/usr/bin/ld: read in flex scanner failed
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugin/CMakeFiles/nvinfer_plugin.dir/build.make:2219: out/libnvinfer_plugin.so.8.2.1] Error 1
make[2]: Leaving directory '/root/TensorRT/TensorRT-8.2.1/build'
make[1]: *** [CMakeFiles/Makefile2:1500: plugin/CMakeFiles/nvinfer_plugin.dir/all] Error 2
```
