### ISSUE TITLE
[RFE] Device-side parameter reset for genetic algorithms

### ISSUE THREAD

**Issue by cqiaoYc** [NVIDIA/TensorRT#167]
tensorRT is a very good library. Many thanks to the development team for their contributions. Using evolutionary algorithms to train deep neural networks is a good research direction. If tensorRT opens device-side network parameter reset and input data settings, it can provide a seamless integration solution for this direction.
tensorRT open device-side network parameter reset and input data settings can make tensorRT more widely used.

**Comment by rmccorm4** [comment]
Hi @cqiaoYc ,

We always appreciate community feedback! Please stay tuned.

If you could elaborate on the kinds of API feature requests you are looking for, that would be helpful!

**Comment by cqiaoYc** [comment]
My requirement is to reset network parameters and input on the device side. When the neural network is trained using the genetic algorithm, the generated new network parameters reside on the device side, so the network parameters need to be reset from the device side instead of the host side.
        The training data set also resides on the device side, and also requires an API to directly pass input data to the network on the device side.
        tensorRT now only resets network parameters and input data on the host side. If it is used in conjunction with genetic algorithms to build a semi-supervised learning system, it needs to transfer data back and forth between the device and the host. The efficiency is too low.

**Comment by cqiaoYc** [comment]
This is an easy enhancement for you. Do you have any plans for it?

**Comment by rajeevsrao** [comment]
@cqiaoYc perhaps I need to understand your use-case better. Since this relates to the core TensorRT design and APIs, and extends beyond our open source components, please reach out to me at rajeevrao@nvidia.com and we can discuss options. Thanks.
