### ISSUE TITLE
Problem building Python binding for Python3.9

### ISSUE THREAD

**Issue by tt-yoshi** [NVIDIA/TensorRT#1670]
## Description

As Python3.6 is nearing is end-of-life, I want to upgrade my Jetson Nano with Python3.9.

As suggested [here](https://forums.developer.nvidia.com/t/using-tensorrt-with-python-3-9-on-jetson-nano/197431), I'm trying to build the Python binding, following the instructions at https://github.com/NVIDIA/TensorRT/tree/main/python.  
However, the `build.sh` script reported the following errors:
```
/workspace/TensorRT/python/build /workspace/TensorRT/python
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/TensorRT/python/build
Scanning dependencies of target tensorrt
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyAlgorithmSelector.cpp.o
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyCore.cpp.o
[ 25%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyFoundationalTypes.cpp.o
[ 33%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyGraph.cpp.o
[ 41%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyCaffe.cpp.o
[ 75%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyOnnx.cpp.o
[ 50%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyPlugin.cpp.o
[ 58%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o
[ 66%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyUff.cpp.o
[ 83%] Building CXX object CMakeFiles/tensorrt.dir/src/pyTensorRT.cpp.o
[ 91%] Building CXX object CMakeFiles/tensorrt.dir/src/utils.cpp.o
[100%] Linking CXX shared library tensorrt/tensorrt.so
/usr/bin/ld: cannot find -lnvinfer
/usr/bin/ld: cannot find -lnvonnxparser
/usr/bin/ld: cannot find -lnvparsers
/usr/bin/ld: cannot find -lnvinfer_plugin
collect2: error: ld returned 1 exit status
CMakeFiles/tensorrt.dir/build.make:233: recipe for target 'tensorrt/tensorrt.so' failed
make[2]: *** [tensorrt/tensorrt.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/tensorrt.dir/all' failed
make[1]: *** [CMakeFiles/tensorrt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Generating python 3.9 bindings for TensorRT 8.2.0.6
/workspace/TensorRT/python/packaging /workspace/TensorRT/python/build /workspace/TensorRT/python
/workspace/TensorRT/python/build /workspace/TensorRT/python
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/workspace/TensorRT/python
```

The specific steps I took are described below. Please tell me what I did wrong.

## Environment

**TensorRT Version**: v8.2.1.8
**NVIDIA GPU**: GeForce RTX 2080
**NVIDIA Driver Version**: 495.29.05
**CUDA Version**: 11.5
**CUDNN Version**: 8.2
**Operating System**: Ubuntu 20.04

## Steps To Reproduce

1. Follow the instruction [here](https://github.com/NVIDIA/TensorRT) to build TensorRT OSS. Using the provided [Docker file](https://github.com/NVIDIA/TensorRT/blob/main/docker/ubuntu-cross-aarch64.Dockerfile) I successfully built for `Ubuntu 18.04 Cross-Compile for Jetson (aarch64) with cuda-10.2 (JetPack)`. One thing I'm a bit confused about is the version of TensorRT. On the host machine I'm running v8.2.1.8, but I don't know if it's okay for the Jetson Nano. I also tried `Native build on Jetson (aarch64) with cuda-10.2`, but the build failed (`LIB_CUDNN` not found). Will provide more details if necessary.
2. Still in the Docker container:
```
# Create a directory for external sources and download pybind11 into it.
export EXT_PATH=~/external

mkdir -p $EXT_PATH && cd $EXT_PATH
git clone https://github.com/pybind/pybind11.git

# Add Main Headers
wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz
tar -xvf Python-3.9.9.tgz
mkdir -p $EXT_PATH/python3.9/include
cp -r Python-3.9.9/Include/* $EXT_PATH/python3.9/include/

# Add PyConfig.h
wget http://ftp.jp.debian.org/debian/pool/main/p/python3.9/libpython3.9-dev_3.9.9-1_arm64.deb
ar x libpython3.9-dev_3.9.9-1_arm64.deb
tar -xvf data.tar.xz
cp -r ./usr/include/aarch64-linux-gnu/python3.9/pyconfig.h $EXT_PATH/python3.9/include/

# Build Python bindings
cd $TRT_OSSPATH/python
PYTHON_MAJOR_VERSION=3 PYTHON_MINOR_VERSION=9 TARGET_ARCHITECTURE=aarch64-linux-gnu ./build.sh
```

**Comment by tomihisaw** [comment]
I am getting the same error, with a different version of python (3.7). I followed similar steps.

Were you ever able to resolve the problem?

**Comment by jstumpin** [comment]
Using conda (python) 3.8 here, errors went away after inserting `link_directories(/usr/lib/aarch64-linux-gnu/tegra)` into CMakeLists.txt.

**Comment by nvpohanh** [comment]
@tt-yoshi Could you try TRT 8.4.1 (8.4GA) and see if the issue still exists? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
