### ISSUE TITLE
Only FP32/FP16 type bounding boxes are supported and SCORE type not supported

### ISSUE THREAD

**Issue by MichaelWU0726** [NVIDIA/TensorRT#1673]
## Description

When i used `batchedNMSPlugin` to add nms layer into yolov5, it showed the following:
```
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 4 output network tensors.
Only FP32/FP16 type bounding boxes are supported.
Only FP32/FP16 type bounding boxes are supported.
SCORE type not supported.
SCORE type not supported
Only FP32/FP16 type bounding boxes are supported.
Only FP32/FP16 type bounding boxes are supported.
SCORE type not supported.
SCORE type not supported
Only FP32/FP16 type bounding boxes are supported.
Only FP32/FP16 type bounding boxes are supported.
SCORE type not supported.
SCORE type not supported
Only FP32/FP16 type bounding boxes are supported.
Only FP32/FP16 type bounding boxes are supported.
SCORE type not supported.
SCORE type not supported
Completed creating Engine
Only FP32/FP16 type bounding boxes are supported.
Only FP32/FP16 type bounding boxes are supported.
[TensorRT] INTERNAL ERROR: Assertion failed: status == STATUS_SUCCESS
/home/TensorRT-release-7.2/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp:225
Aborting...
```

I was confused what the type `SCORE type` was. I didn't use `SCORE` type object. What's more, what was `FP32/FP16 type bounding boxes`

## Environment

**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: 2080Ti
**NVIDIA Driver Version**: 460.80
**CUDA Version**: cuda11.1
**CUDNN Version**: 0.8
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.7.8

**Comment by ttyio** [comment]
@MichaelWU0726 , they should be the `nmsed_boxes` and `nmsed_scores`.  according to the readme of https://github.com/NVIDIA/TensorRT/tree/main/plugin/batchedNMSPlugin, they must be FP32, and trt can optimize it with fp16 when build fp16 plan file. thanks!

**Comment by MichaelWU0726** [comment]
> @MichaelWU0726 , they should be the `nmsed_boxes` and `nmsed_scores`. according to the readme of https://github.com/NVIDIA/TensorRT/tree/main/plugin/batchedNMSPlugin, they must be FP32, and trt can optimize it with fp16 when build fp16 plan file. thanks!

`network.add_plugin_v2([reshaped_boxes.get_output(0), updated_scores.get_output(0)], nms_layer)`, I have checked `reshaped_boxes.get_output(0)` and `updated_scores.get_output(0)` were all `DataType.FLOAT`, which was supported by batchedNMSPlugin

**Comment by ttyio** [comment]
@MichaelWU0726 , could you share with us a simple repro to debug? thanks

**Comment by MichaelWU0726** [comment]
> @MichaelWU0726 , could you share with us a simple repro to debug? thanks

[yolov5](https://github.com/MichaelWU0726/TRTx/tree/helmetfire-yolov5)

**Comment by ttyio** [comment]
sorry @MichaelWU0726 , just realize you are running 7.2, could you also try 8.2? thanks

**Comment by MichaelWU0726** [comment]
> sorry @MichaelWU0726 , just realize you are running 7.2, could you also try 8.2? thanks

I thought it didn't matter about version
