### ISSUE TITLE
two inputs (data and weights) are allowed only in explicit-quantization mode.

### ISSUE THREAD

**Issue by lsdNorman** [NVIDIA/TensorRT#1675]
root@90e0df0b7943:/home/TensorRT/parsers/onnx/build# ./onnx2trt /home/my.onnx -o my.trt
Input filename: /home/my.onnx
ONNX IR version: 0.0.6
Opset version: 12
Producer name: pytorch
Producer version: 1.8
Domain:
Model version: 0
Doc string:
Parsing model
[2021-12-20 08:58:04 WARNING] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2021-12-20 08:58:04 ERROR] Conv_90: two inputs (data and weights) are allowed only in explicit-quantization mode.
While parsing node number 90 [Conv -> "883"]:
ERROR: ModelImporter.cpp:177 In function parseGraph:
[6] Invalid Node - Conv_90
Conv_90: two inputs (data and weights) are allowed only in explicit-quantization mode.

**Comment by ttyio** [comment]
Hello @lsdNorman , could you try latest 8.2 release, using trtexec to inference your onnx like this:

      trtexec --onnx=/home/my.onnx --int8 --saveEngine=my.trt

Thanks!

**Comment by lsdNorman** [comment]
@ttyio Hello, can I use precision fp32?
Thanks!

**Comment by ttyio** [comment]
@lsdNorman , for QAT onnx, it is quantized, you have to enable --int8.

**Comment by DeriZSY** [comment]
> Hello @lsdNorman , Is your model generated from QAT toolkit? https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization
> 
> If yes, could you try latest 8.2 release, using trtexec to inference your onnx like this:
> 
> ```
>   trtexec --onnx=/home/my.onnx --int8 --saveEngine=my.trt
> ```
> 
> If not, trt currently only support conv weights as initializer, we do not support conv weights from activation.
> 
> Thanks!

Hi, I met the same problem with trt 8.2.1.8 w/ and w/o --fp16 parameter. 
I was trying to apply 2D convolution with a temporal tensor instead of initialized weights. 
Do you mean that such operation cannot be supported anyway?
Or can I solved the problem by upgrade to some version newer than 8.2.1.8?

**Comment by ttyio** [comment]
> a temporal tensor instead of initialized weights.
> Do you mean that such operation cannot be supported anyway?
> Or can I solved the problem by upgrade t

Sorry we do not support conv weights from activation. could you modify your ONNX model to use initialized weights? thanks

**Comment by hyuan-kamuda** [comment]
> > a temporal tensor instead of initialized weights.
> > Do you mean that such operation cannot be supported anyway?
> > Or can I solved the problem by upgrade t
> 
> Sorry we do not support conv weights from activation. could you modify your ONNX model to use initialized weights? thanks

I met same error with TRT 8.20.3, adding --int8 still can't fix the issue, help?

**Comment by jcyhcs** [comment]
@lsdNorman  
hi,professor:
do you have any solution to reolve this problem?
i also have a siamese tracking network, i want to convert onnx to tensorrt, i come with the same error,

**Comment by joonjeon** [comment]
Hi!

Same issue here and the problem seems to persist even on TensorRT 8.4.1.

**Comment by ttyio** [comment]
@joonjeon , could you try 8.5? thanks

**Comment by LightSun** [comment]
same to me
