### ISSUE TITLE
How to change the apt-get url?

### ISSUE THREAD

**Issue by ZJU-lishuang** [NVIDIA/TensorRT#1676]
When I Generate the TensorRT-OSS build container,I Failed to fetch https://developer.download.nvidia.com.
How to change the `https://developer.download.nvidia.com.` to `https://developer.download.nvidia.cn.` When [apt-get install](https://github.com/NVIDIA/TensorRT/blob/main/docker/ubuntu-20.04.Dockerfile#L72)

**Comment by ttyio** [comment]
@ZJU-lishuang , maybe comment out these `apt-get` lines in https://github.com/NVIDIA/TensorRT/blob/main/docker/ubuntu-20.04.Dockerfile#L36, and manually install it after you enter the image?

**Comment by ZJU-lishuang** [comment]
yes，so I download and extract the TensorRT GA build from NVIDIA Developer Zone.:smile:
