### ISSUE TITLE
How to use the ONNX model with int8 calibration? 

### ISSUE THREAD

**Issue by lzmisscc** [NVIDIA/TensorRT#1678]
Hi,

I am trying to following the example in PyTorch-Quantization Toolkit to do the int8 Quantization.
However, after I manager to get the generated onnx file. I am not sure how to use this onnx file and use trtexec to complete the inference of python tensorrt.

**Comment by ttyio** [comment]
@lzmisscc , you can use 

        trtexec --onnx your_onnx_file --int8

thanks

**Comment by lzmisscc** [comment]
> @lzmisscc , you can use
> 
> ```
>     trtexec --onnx your_onnx_file --int8
> ```
> 
> thanks

But after I converted to int8, I used tensorrt for reasoning,  video memory did not decrease, only the speed decreased. What's the matter?

thanks

**Comment by Water2style** [comment]
> Hi,
> 
> I am trying to following the example in PyTorch-Quantization Toolkit to do the int8 Quantization. However, after I manager to get the generated onnx file. I am not sure how to use this onnx file and use trtexec to complete the inference of python tensorrt.

兄弟你可以成功转onnx吗？我们直接失败了.还在debug
要不要合作一波啊 一起搞.

**Comment by lzmisscc** [comment]
> > Hi,
> > I am trying to following the example in PyTorch-Quantization Toolkit to do the int8 Quantization. However, after I manager to get the generated onnx file. I am not sure how to use this onnx file and use trtexec to complete the inference of python tensorrt.
> 
> 兄弟你可以成功转onnx吗？我们直接失败了.还在debug 要不要合作一波啊 一起搞.

email: 1028741371@qq.com

**Comment by ttyio** [comment]
> > @lzmisscc , you can use
> > ```
> >     trtexec --onnx your_onnx_file --int8
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > thanks
> 
> But after I converted to int8, I used tensorrt for reasoning, video memory did not decrease, only the speed decreased. What's the matter?
> 
> thanks

From our previous experience, the most use of gpu memory come from the load of cudnn, cublas library. The weights and activations not contribute to the major of the memory consumption.

**Comment by lzmisscc** [comment]
> > > @lzmisscc , you can use
> > > ```
> > >     trtexec --onnx your_onnx_file --int8
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > thanks
> > 
> > 
> > But after I converted to int8, I used tensorrt for reasoning, video memory did not decrease, only the speed decreased. What's the matter?
> > thanks
> 
> From our previous experience, the most use of gpu memory come from the load of cudnn, cublas library. The weights and activations not contribute to the major of the memory consumption.

ok，I see. Thanks!

**Comment by ttyio** [comment]
Closing and please reopen if you still have question, thanks!
