### ISSUE TITLE
Is layer name is required or not?

### ISSUE THREAD

**Issue by H-xie** [NVIDIA/TensorRT#168]
I am looking into nvcaffeparse.

Some newly added plugins has its constructors with `std::string name` as the first parameter. While most of the old plugins, added when this repo init, do not have any constructor with `name`.

`name` is the name of layer (not layer type), which filled by IPluginCretor::createPlugin for the first time.

So, is the constructors with `name` which refers to *layer name* is needed? If so, why it is needed?

Thanks

**Comment by rmccorm4** [comment]
Hi @H-xie ,

I'm not 100% sure on this, but I believe the `name` parameter is added for convenience. Many of the API functions allow you get date by either (1) index or (2) name, as you can see here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Core/Engine.html

Sometimes you know the name of your input/output layer for example and want to look it up by name to see how it looks after parsing into a TensorRT CUDA Engine, to verify correctness.

**Comment by rmccorm4** [comment]
Closing - please reopen if you have more issues.
