### ISSUE TITLE
TensorRt Engines For SampleMaskRCNN

### ISSUE THREAD

**Issue by hakunaMatataHub** [NVIDIA/TensorRT#1684]
Hi have been using the sampleUffMaskRCNN in the repository for building a segmentation application. For which i have made and saved the engine files locally. I have mofdified the sample code to suit my requirements.

I have two different engines both built for the image segmentation based on MaskRCNN but slight different. I want to deserilize and load both engine to memory so that my application can choose which engien to run inference on as per the inpus given to the application. Is this possible i.e loading two tensorrt engines simulatenously to jetsoon Xavier Nx's memory?

Jetpack version 4.6

**Comment by zerollzeng** [comment]
Yes you can do that

**Comment by ttyio** [comment]
Closing since the question is answered, thanks
