### ISSUE TITLE
Does TensorRT support accelerating Tacotron model inference?

### ISSUE THREAD

**Issue by superhg2012** [NVIDIA/TensorRT#169]
There are some Bi-LSTM modules in Tacotron model(TTS network) and some convs that are wrapped, does tensorrt support this?

**Comment by rmccorm4** [comment]
Hi @superhg2012,

1. For `tacotron` implemented in TensorFlow, like so: https://github.com/keithito/tacotron

I would think you can use TF-TRT, where TRT-compatible nodes will be sped up and incompatible nodes will fallback to the TF implementation. I did find one post on a user trying this but failing here: https://devtalk.nvidia.com/default/topic/1062601/tensorrt/fail-to-speed-up-model-by-tensorrt-/ but that might be different now.

2. For `tacotron2`, there's a Pytorch implementation: https://github.com/NVIDIA/tacotron2 which you might be able to export to ONNX, and try to convert to TensorRT, but I don't know if it will work at the moment.

3. You could also try the same as (1) above for tacotron2 implemented in Tensorflow, maybe like this one: https://github.com/Rayhane-mamah/Tacotron-2
