### ISSUE TITLE
Jetpack 4.6 inference with TensorRT encounter Cuda Runtime (an illegal memory access was encountered)

### ISSUE THREAD

**Issue by limithsieh** [NVIDIA/TensorRT#1695]
## Description
I used Jetson NX inference model "vocGAN" with TensorRT encounter Cuda Runtime (an illegal memory access was encountered).
Everything works fine when I do this with PC(TensorRT 8.0).
Anything I need to pay attention when inference with Jetson NX?

vocGan: https://github.com/rishikksh20/VocGAN

>[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 2417, GPU 7289 (MiB)
root@stan-jetson:~/Project/Desktop/ATEN/AI/TensorRT_8.2/demo/stan_test# python3 inference_mel_tsRT.py 
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +353, GPU +0, now: CPU 421, GPU 5390 (MiB)
[TensorRT] INFO: Loaded engine size: 92 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 513 MiB, GPU 5576 MiB
[TensorRT] VERBOSE: Using cublas a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +226, GPU +243, now: CPU 747, GPU 5824 (MiB)
[TensorRT] VERBOSE: Using cuDNN as a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +308, GPU +306, now: CPU 1055, GPU 6130 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 1054, GPU 6130 (MiB)
[TensorRT] VERBOSE: Deserialization required 3318284 microseconds.
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 1054 MiB, GPU 6130 MiB
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation begin: CPU 962 MiB, GPU 6039 MiB
[TensorRT] VERBOSE: Using cublas a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +0, now: CPU 963, GPU 6039 (MiB)
[TensorRT] VERBOSE: Using cuDNN as a tactic source
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 963, GPU 6039 (MiB)
[TensorRT] VERBOSE: Total per-runner device memory is 80197632
[TensorRT] VERBOSE: Total per-runner host memory is 224400
[TensorRT] VERBOSE: Allocated activation device memory of size 164019712
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation end: CPU 966 MiB, GPU 6045 MiB
torch.Size([1, 1, 310016])
Running vocGAN with TensorRT
[TensorRT] ERROR: 1: [gatherRunner.cpp::execute::104] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Finished vocGAN with TensorRT
[TensorRT] ERROR: 1: [hardwareContext.cpp::terminateCommonContext::141] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [defaultAllocator.cpp::free::85] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[TensorRT] WARNING: Unable to determine GPU memory usage
[TensorRT] WARNING: Unable to determine GPU memory usage
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 2417, GPU 0 (MiB)
[TensorRT] INTERNAL ERROR: [defaultAllocator.cpp::free::85] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [resources.cpp::~ScopedCudaStream::455] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
.
.
.
[TensorRT] INTERNAL ERROR: [resources.cpp::~ScopedCudaEvent::438] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [resources.cpp::~ScopedCudaEvent::438] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [defaultAllocator.cpp::free::85] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [resources.h::operator()::445] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [resources.h::operator()::445] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[TensorRT] INTERNAL ERROR: [resources.h::operator()::445] Error Code 1: Cuda Driver (an illegal memory access was encountered)
.
.
.
> 

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**: etson Xavier NX 
**NVIDIA Driver Version**: jetpack 4.6
**CUDA Version**: 10.2
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.6.9
**PyTorch Version (if applicable)**: 1.9.0
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/l4t-ml:r32.6.1-py3

## Relevant Files

`def infer_vocGAN_trt(vocGAN, vocGAN_context, mel, fp16):

    mel_size = mel.size(2)
    print(mel_size)
    batch_size = mel.size(0)
    print(batch_size)
    stride = 256

    audios = torch.zeros(batch_size, 1, mel_size*stride).cuda()
    print(audios.shape)
    if fp16:
        mel = mel.half()
        audios = audios.half()

    vocGAN_tensors = {
        "inputs" : {'input': mel},
        "outputs" : {'output': audios}
    }

    print("Running vocGAN with TensorRT")
    run_trt_engine(vocGAN_context, vocGAN, vocGAN_tensors)
    print("Finished vocGAN with TensorRT")
    return audios

def load_mel(data_paths):

    with torch.no_grad():
        mel = torch.from_numpy(np.load(data_paths))
       
        if len(mel.shape) == 2:
            mel = mel.unsqueeze(0)

    return mel

def main():

    enable_fp16 = 0
    MAX_WAV_VALUE = 32768.0

    hop_length = 256

    torch.cuda.init()

    TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)

    vocGAN = load_engine("engine/MyRef1d_voc_nx.engine", TRT_LOGGER)
  
    vocGAN_context = vocGAN.create_execution_context()

    data_paths = "mel_npy/0011.npy"
    mel = load_mel(data_paths)

    audios = infer_vocGAN_trt(vocGAN, vocGAN_context, mel, enable_fp16)

if __name__ == "__main__":
    main()
`

## Steps To Reproduce

 1. convert onnx to tensorRT.engine 
 > trtexec --onnx=vocGan.onnx --workspace=1000 --minShapes=input1x80x100 --optShapes=input1x80x1000 --maxShapes=input1x80x2000 --saveEngine=vocGan.engine

2. inference with vocGan.engine on Jetson NX

**Comment by zerollzeng** [comment]
On NX there is no device memory, so the GPU is using the onboard memory which shared with CPU

**Comment by limithsieh** [comment]
> On NX there is no device memory, so the GPU is using the onboard memory which shared with CPU

Thx your reply. 

As I know, the attribute to limit GPU memory usage is "maxWorkspace",  which I had set it to "1000".

**Comment by limithsieh** [comment]
I forgot attach data to GPU memory cause the issue.
