### ISSUE TITLE
Why has the scrfd model not  been accelerated by tensorrt?

### ISSUE THREAD

**Issue by Suke0** [NVIDIA/TensorRT#1696]
## Environment

**TensorRT Version**: 8.2GA
**NVIDIA GPU**: V100S
**NVIDIA Driver Version**: 470.57.02
**CUDA Version**: 11.4.2
**CUDNN Version**: 8.2
**Operating System**: ubuntu1804
**Python Version (if applicable)**: 3.7
**PyTorch Version (if applicable)**: 1.10

It warned "TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.6.1"，when the model was built. 
Is it the reason why the model has not been accelerated?

**Comment by zerollzeng** [comment]
> It warned "TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.6.1"，when the model was built.
> Is it the reason why the model has not been accelerated?

This should not the reason usually, it just means that the  cuBLAS/cuBLAS LT linked at running is not the same as it linked when being build.

The reason why it hasn't been accelerated by Tensorrt might be following:
1. The network has some operators that are is unfriendly to GPU or too many operators that rely on memory operation.
2. TensorRT has poor support on some network structures thus can not do much fusion on the network. 

there are some ways you can try to speed up your model.
1. Enable INT8/FP16 precision.
2. Enable cuda graph.

You can also run you model with trtexec and use option --dumpProfile to find the bottleneck, it will print the time of every TRT layer.

**Comment by Suke0** [comment]
Thanks，best wishes to you!
