### ISSUE TITLE
onnx does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by tdp2110** [NVIDIA/TensorRT#17]
Configure output:

```
CMake Error at parsers/CMakeLists.txt:42 (add_subdirectory):
  The source directory

    /home/tom/projects/TensorRT/parsers/onnx

  does not contain a CMakeLists.txt file.
```

maybe this is supposed to be in an `if (NVINTERNAL OR NVPARTNER)` block?

**Comment by rajeevsrao** [comment]
@tdp2110 

TensorRT's ONNX parser is an independent project (https://github.com/onnx/onnx-tensorrt), and is synced as a submodule. After cloning TensorRT, the submodule update command should fetch these dependent projects:
`git submodule update --init --recursive`

**Comment by tdp2110** [comment]
thank you!

**Comment by Hassan313** [comment]
@rajeevsrao Thank you very much.

**Comment by hopezhou** [comment]
thank you!

**Comment by nick-025** [comment]
> @tdp2110
> 
> TensorRT's ONNX parser is an independent project (https://github.com/onnx/onnx-tensorrt), and is synced as a submodule. After cloning TensorRT, the submodule update command should fetch these dependent projects: `git submodule update --init --recursive`

Hello, I've done what @tdp2110 recommended, but I had no success. I got these error messages:

![image](https://github.com/NVIDIA/TensorRT/assets/64695893/94ae4465-55b6-402f-a8a8-5b993e1fa85a)


Does anyone have an idea of what's going on?
