### ISSUE TITLE
TensorRT v7/v8 using more GPU memory per model than v6, diffrence in createExecutionContext() API call

### ISSUE THREAD

**Issue by hrenek** [NVIDIA/TensorRT#1701]
## Description
I am using TensorRT C++ API to load multiple models. I'm migrating our codebase to TensorRT v7/v8 from v6 and I've noticed that there is a substantially more of GPU memory used per model. This results in application failing to load some the models on the same hardware it works on TFv6 due to out of GPU memory errors. 

Model files are completely the same no difference between versions. I've observed it for all models tried. Using the onnx or uff format, explicit or implict batch dimension, multiple configurations of workspace size, using IAlgorithmSelector to select different layer implementations seems to have no influence on this memory overhead. 

I've tracked memory overhead to the `nvinfer1::ICudaEngine::createExecutionContext()` API call.

On TRT v6 it allocates exactly `getDeviceMemorySize()` and `createExecutionContextWithoutDeviceMemory()` allocates zero bytes of GPU memory. 

On TRT v7/v8 `createExecutionContext()` allocates more than `getDeviceMemorySize()` and `createExecutionContextWithoutDeviceMemory()` allocates more than zero bytes, roughly the size of the observed overhead increase per model. 

I'm testing the memory usage by looking at nvidia-smi output after each API call. Here are some stats on the typical models we use. Small retina net model. Object recognition model (inception resnet) and a larger object recognition model. 

| Mem usage | Small retina TRTv6 | Small retina TRTv7 | Obj recog v6 | Obj recog v7 | Large obj recog v6 |   Large obj recog v7 |
| --- | --- | --- | --- | --- | --- | --- |
| Serialized model on disk | 3,1 MB  | 4,5 MB | 95 MB | 91,5 MB | 288 MB | 288 MB | 
| Observed overhead per model  | 21 MB | 41 MB | 247 MB | 347 MB | 947MB | 1164 MB |
| TRTv7-TRTv8 difference| --- | 20 MB | --- | 100 MB | --- | 217 MB |
| `getDeviceMemorySize()` | 11 MB | 12 MB | 140 MB | 137 MB | 650 MB | 612 MB |
| `createExecutionContext()` overhead | 11 MB | 32 MB | 140 MB | 243 MB | 651 MB | 868 MB | 
| TRTv7 log Allocated persistent device memory of size | --- | 3 MB | --- | 91,5 MB | --- | 250 MB |
| TRTv7 log Allocated activation device memory of size | --- | 12,9 MB | --- | 143,7 MB | --- | 642.3 MB |

Observed numbers are for the whole model with input output buffer allocations after multiple model initializations so that everything is warm. 

TrtV7 log rows are what what `createExecutionContext()` outputs in the log. 

From the above numbers additional overhead track loosely to the size of the model but not perfectly. My best guess is that the weights are duplicated in the execution context+ some more stuff. 

This is observed on Windows and Linux on mulitple GPUs. The numbers above are from Windows 10, GTX 1080 ti card.

## Environment

**TensorRT Version**: 7.2.3 but observed on any v7/v8 version
**NVIDIA GPU**: tested on GTX 1080 ti but observed on RTX cards as well
**NVIDIA Driver Version**: 461.09
**CUDA Version**: 11.1
**CUDNN Version**: 8.2.1
**Operating System**: Windows 10, but observed on linux as well. 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**:

**Comment by zerollzeng** [comment]
Things might be a little complicated here, but usually, the memory consumption of a model(weights + activations) won't change too much across different versions. the extra memory consumption you observed might be due to CUDNN/CUBLAS.

@ttyio Any comments here?

**Comment by zhou-git** [comment]
I have the same problem at hand. Using exactly the same serialized model (2D recognition model Yolo converted to tensorrt by a library called tkdnn). Using tensorrt 6.0.1.5+CUDA10.0, The memory usage from nvidia-smi is roughly 950MB. Now with the new lib stack: Tensorrt 8.2.4.2 + CUDA11.5, the Gpu memroy usage increased to 2550MB.

**Comment by azad96** [comment]
Did you find a solution? I've used TensorRT 5/6/7 in the past, but I have to use the version 8 as I have Ubuntu 20.04. I have the same memory issue even with a one layer convolutional network.

**Comment by nvpohanh** [comment]
@hrenek Do you have a simple ONNX file that we can use to repro the issue? I guess we added some new tactics which run faster but require more memory to run, but will need an example to confirm that.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
