### ISSUE TITLE
Error when load a int8 cache using trtexec

### ISSUE THREAD

**Issue by XXXVincent** [NVIDIA/TensorRT#1703]
Trtexec works fine without specifying a int8 cache file, but throws a error when loading int8 cache file.

**/usr/src/tensorrt/bin/trtexec --onnx=erfnet.onnx --int8 --saveEngine=erf_int8.engine --calib=erfnet_quantized_int8.cache --verbose**

 _----- Parsing of ONNX model erfnet.onnx is Done ---- 
[01/04/2022-16:10:16] [V] [TRT] Original: 83 layers
[01/04/2022-16:10:16] [V] [TRT] After dead-layer removal: 83 layers
[01/04/2022-16:10:16] [V] [TRT] After scale fusion: 83 layers
[01/04/2022-16:10:16] [V] [TRT] After vertical fusions: 83 layers
[01/04/2022-16:10:16] [V] [TRT] After final dead-layer removal: 83 layers
[01/04/2022-16:10:16] [V] [TRT] After concat removal: 83 layers
[01/04/2022-16:10:16] [V] [TRT] After tensor merging: 83 layers
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)_

**Comment by ttyio** [comment]
@XXXVincent  how did you generate erfnet_quantized_int8.cache? thanks

**Comment by XXXVincent** [comment]
> @XXXVincent how did you generate erfnet_quantized_int8.cache? thanks

Using code from this repo : https://github.com/Wulingtian/yolov5_tensorrt_int8_tools

**Comment by XXXVincent** [comment]
How is that possible when I specified a none-existsed calib file and still get a decent result? However when not specifying a calib file, the result infered by exported int8 model is totally wrong?

_**&&&& PASSED TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --onnx=lannet_20220308.onnx --calib=a_not_exists_file.notexist --int8 --explicitBatch --saveEngine=test_not_exists.engine**_

And also, I found the results of int8 model infered between Linux(RTX2060) and QNX platform are quite different. So weird.
@ttyio

**Comment by nvpohanh** [comment]
@XXXVincent When no calib file is provided, trtexec simply use random dynamic ranges for all tensors. That's why you got wrong outputs.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
