### ISSUE TITLE
ONNX runtime result differs from pytorch quantized model

### ISSUE THREAD

**Issue by spivakoa** [NVIDIA/TensorRT#1706]
Hello,
I'm using the pytorch quantization toolkit to quantize the pytorch trained model. I followed the steps described in the toolkit documentation and exported the quantized model to ONNX file. However when I use the onnxruntime to inference and compare to the pytorch quantized model, the results are totally different. 

My environment:

TensorRT Version: 8.2.0.6
GPU Type: RTX2080
Nvidia Driver Version: 470.86
CUDA Version: 11.4
CUDNN Version: 8.2.4
Operating System + Version: Ubuntu 18.04
Python Version (if applicable): 3.7.11
PyTorch Version (if applicable): 1.9.0
Pytorch-Quantization Version: 2.1.1
ONNXRuntime Version: 1.10.0
[model.zip](https://github.com/NVIDIA/TensorRT/files/7816376/model.zip)

I also attach the pytorch - quantized pt file and its ONNX exported file. 

Thank you.

**Comment by ZyrianovS** [comment]
@ttyio 
Same issue.

Ubuntu 18.04,
CUDA 11.1
onnxruntime 1.10.0
pytorch_quantization 2.0.1

I am following a tutorial from https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html.

And I tested with pytorch 1.9.1 and 1.8.1. Logs are attached.
[tutorial_torch_191.txt](https://github.com/NVIDIA/TensorRT/files/7819469/tutorial_torch_191.txt)
[tutorial_torch_181.txt](https://github.com/NVIDIA/TensorRT/files/7819471/tutorial_torch_181.txt)

As you can see from the logs in both cases (just calibrated and qat finetuned models) pytorch and onnx runtime inference results differ, much more for finetuned model.

Calibrated and finetuned models and their onnx are attached for your reference.
[quant_resnet50-calibrated.zip](https://drive.google.com/file/d/1il7ZgMENAPfNqVE9hGd0chgpADJ0xIir/view?usp=sharing)
[quant_resnet50-finetuned.zip](https://drive.google.com/file/d/13kbp0ZISvEHHBvF8HcK-eXq_fbKg68Xp/view?usp=sharing)

My script is below:
```
import torch
import torch.utils.data
import os
import sys
import collections
import onnxruntime as ort

from torch import nn
from tqdm.auto import tqdm

from pytorch_quantization import nn as quant_nn
from pytorch_quantization import calib
from pytorch_quantization.tensor_quant import QuantDescriptor

from torchvision import models

sys.path.append("path to pytorch/vision/references/classification")
from train import evaluate, train_one_epoch, load_data

from pytorch_quantization import quant_modules
quant_modules.initialize()

# OPSET_VERSION = 10
OPSET_VERSION = 13

quant_desc_input = QuantDescriptor(calib_method='histogram')
quant_nn.QuantConv2d.set_default_quant_desc_input(quant_desc_input)
quant_nn.QuantLinear.set_default_quant_desc_input(quant_desc_input)

model = models.resnet50(pretrained=True)
model.cuda()

data_path = "path to ImageNet"
batch_size = 32

traindir = os.path.join(data_path, 'train')
valdir = os.path.join(data_path, 'train')
args = collections.namedtuple('args', [
    'val_resize_size',
    'val_crop_size',
    'train_crop_size',
    'interpolation',
    'cache_dataset',
    'weights',
    'distributed'
    ])

dataset, dataset_test, train_sampler, test_sampler = load_data(
    traindir, valdir,
    args(val_resize_size=256, val_crop_size=224, train_crop_size=224, interpolation='bilinear', cache_dataset=False, weights=None, distributed=False))

data_loader = torch.utils.data.DataLoader(
    dataset, batch_size=batch_size,
    sampler=train_sampler, num_workers=4, pin_memory=True)

data_loader_test = torch.utils.data.DataLoader(
    dataset_test, batch_size=batch_size,
    sampler=test_sampler, num_workers=4, pin_memory=True)


def collect_stats(model, data_loader, num_batches):
    """Feed data to the network and collect statistic"""

    # Enable calibrators
    for name, module in model.named_modules():
        if isinstance(module, quant_nn.TensorQuantizer):
            if module._calibrator is not None:
                module.disable_quant()
                module.enable_calib()
            else:
                module.disable()

    for i, (image, _) in tqdm(enumerate(data_loader), total=num_batches):
        model(image.cuda())
        if i >= num_batches:
            break

    # Disable calibrators
    for name, module in model.named_modules():
        if isinstance(module, quant_nn.TensorQuantizer):
            if module._calibrator is not None:
                module.enable_quant()
                module.disable_calib()
            else:
                module.enable()

def compute_amax(model, **kwargs):
    # Load calib result
    for name, module in model.named_modules():
        if isinstance(module, quant_nn.TensorQuantizer):
            if module._calibrator is not None:
                if isinstance(module._calibrator, calib.MaxCalibrator):
                    module.load_calib_amax()
                else:
                    module.load_calib_amax(**kwargs)
            print(F"{name:40}: {module}")
    model.cuda()

# It is a bit slow since we collect histograms on CPU
with torch.no_grad():
    collect_stats(model, data_loader, num_batches=32)
    compute_amax(model, method="percentile", percentile=99.99)

criterion = nn.CrossEntropyLoss()
with torch.no_grad():
    evaluate(model, criterion, data_loader_test, device="cuda", print_freq=20)

# Save the model
torch.save(model.state_dict(), "quant_resnet50-calibrated.pth")

#ONNX
quant_nn.TensorQuantizer.use_fb_fake_quant = True
dummy_input = torch.randn(1, 3, 224, 224, device='cuda')
input_names = ["input" ]
output_names = ["output"]
onnx_file = "quant_resnet50-calibrated.onnx"
torch.onnx.export(
    model, dummy_input, onnx_file, verbose=False, opset_version=OPSET_VERSION, enable_onnx_checker=False, input_names=input_names, output_names=output_names)
quant_nn.TensorQuantizer.use_fb_fake_quant = False

torch_out = model(dummy_input)
ort_sess = ort.InferenceSession(onnx_file)
ort_out = ort_sess.run(None, {'input': dummy_input.cpu().numpy()})[0]
diff = torch_out.detach().cpu().numpy() - ort_out
print('TORCH', torch_out[0,:20])
print('ORT', ort_out[0,:20])
print('MODEL MAX DIFF', diff.max())
print('MODEL MIN DIFF', diff.min())

#QAT
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.1)

args = collections.namedtuple('args', [
    'print_freq',
    'amp',
    'clip_grad_norm'
    ])

# Training takes about one and half hour per epoch on a single V100
train_one_epoch(
    model, criterion, optimizer, data_loader, "cuda", 0, 
    args(print_freq=10, amp=False, clip_grad_norm=None))

# Save the model
torch.save(model.state_dict(), "quant_resnet50-finetuned.pth")

#ONNX
onnx_file = "quant_resnet50-finetuned.onnx"
quant_nn.TensorQuantizer.use_fb_fake_quant = True
torch.onnx.export(
    model, dummy_input, onnx_file, verbose=False, opset_version=OPSET_VERSION, enable_onnx_checker=False, input_names=input_names, output_names=output_names)
quant_nn.TensorQuantizer.use_fb_fake_quant = False

torch_out = model(dummy_input)
ort_sess = ort.InferenceSession(onnx_file)
ort_out = ort_sess.run(None, {'input': dummy_input.cpu().numpy()})[0]
diff = torch_out.detach().cpu().numpy() - ort_out
print('TORCH', torch_out[0,:20])
print('ORT', ort_out[0,:20])
print('MODEL MAX DIFF', diff.max())
print('MODEL MIN DIFF', diff.min())
```

**Comment by ttyio** [comment]
@spivakoa , is this the same as https://github.com/NVIDIA/TensorRT/issues/1699? thanks!

**Comment by spivakoa** [comment]
Hi @ttyio , this is another issue I'm trying to resolve. As we expect the onnx-runtime to be equal to TRT-runtime, I would expect the pytorch quantized model inference to be equal to onnx-runtime. However, testing the outputs of those lead to different results.
I attach the pytorch code to test this and both the pytorch weights of the quantized model and its onnx file.

Thank you!
[4Nvda.zip](https://github.com/NVIDIA/TensorRT/files/8134532/4Nvda.zip)

**Comment by ttyio** [comment]
Sorry @spivakoa  for the delay response.

I have tried your model with 

       polygraphy run --trt --onnxrt quantized_depthnet.onnx --int8 --float-min=0 --float-max=0.6

(the reason I choose 0~0.6 is that i see the scale in the first Q/DQ is 0.0053091105073690414)

I did not see obvious distribution error, did you see failure using real data? thanks!

     Comparing Output: 'depth' (dtype=float32, shape=(1, 480, 3456)) with 'depth' (dtype=float32, shape=(1, 480, 3456)) | Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
         trt-runner-N0-03/15/22-08:01:28: depth | Stats: mean=6.9095, std-dev=1.9565, var=3.828, median=7.5502, min=0.36622 at (0, 4, 2920), max=11.208 at (0, 266, 2882), avg-magnitude=6.9095
             ---- Histogram ----
             Bin Range     |  Num Elems | Visualization
             (0.366, 1.66) |       1404 |
             (1.66 , 2.95) |      29000 | ##
             (2.95 , 4.24) |     196092 | ###############
             (4.24 , 5.54) |     247592 | ###################
             (5.54 , 6.83) |     192872 | ###############
             (6.83 , 8.12) |     399984 | ###############################
             (8.12 , 9.42) |     511288 | ########################################
             (9.42 , 10.7) |      79908 | ######
             (10.7 , 12  ) |        740 |
             (12   , 13.3) |          0 |
         onnxrt-runner-N0-03/15/22-08:01:28: depth | Stats: mean=6.9246, std-dev=1.9559, var=3.8257, median=7.5437, min=0.75389 at (0, 4, 908), max=13.295 at (0, 0, 78), avg-magnitude=6.9246
             ---- Histogram ----
             Bin Range     |  Num Elems | Visualization
             (0.366, 1.66) |        928 |
             (1.66 , 2.95) |      27236 | ##
             (2.95 , 4.24) |     189416 | ###############
             (4.24 , 5.54) |     257408 | ####################
             (5.54 , 6.83) |     193140 | ###############
             (6.83 , 8.12) |     404972 | ################################
             (8.12 , 9.42) |     491864 | ########################################
             (9.42 , 10.7) |      92096 | #######
             (10.7 , 12  ) |       1716 |
             (12   , 13.3) |        104 |

     Comparing Output: 'error' (dtype=float32, shape=(1, 480, 3456)) with 'error' (dtype=float32, shape=(1, 480, 3456)) | Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
         trt-runner-N0-03/15/22-08:01:28: error | Stats: mean=1.2864, std-dev=0.56041, var=0.31406, median=1.162, min=0.078326 at (0, 474, 1998), max=5.8695 at (0, 4, 76), avg-magnitude=1.2864
             ---- Histogram ----
             Bin Range       |  Num Elems | Visualization
             (0.0783, 0.715) |      73156 | ##
             (0.715 , 1.35 ) |    1106288 | ########################################
             (1.35  , 1.99 ) |     351064 | ############
             (1.99  , 2.63 ) |      68424 | ##
             (2.63  , 3.26 ) |      28440 | #
             (3.26  , 3.9  ) |      18240 |
             (3.9   , 4.54 ) |       9136 |
             (4.54  , 5.17 ) |       3700 |
             (5.17  , 5.81 ) |        424 |
             (5.81  , 6.45 ) |          8 |
         onnxrt-runner-N0-03/15/22-08:01:28: error | Stats: mean=1.2819, std-dev=0.55372, var=0.30661, median=1.1621, min=0.10394 at (0, 28, 2392), max=6.4489 at (0, 4, 76), avg-magnitude=1.2819
             ---- Histogram ----
             Bin Range       |  Num Elems | Visualization
             (0.0783, 0.715) |      75104 | ##
             (0.715 , 1.35 ) |    1103036 | ########################################
             (1.35  , 1.99 ) |     357084 | ############
             (1.99  , 2.63 ) |      67560 | ##
             (2.63  , 3.26 ) |      25144 |
             (3.26  , 3.9  ) |      18020 |
             (3.9   , 4.54 ) |       9164 |
             (4.54  , 5.17 ) |       3112 |
             (5.17  , 5.81 ) |        556 |
             (5.81  , 6.45 ) |        100 |
         Error Metrics: error


     Comparing Output: 'rgb_feats' (dtype=float32, shape=(1, 480, 3456, 10)) with 'rgb_feats' (dtype=float32, shape=(1, 480, 3456, 10)) | Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
         trt-runner-N0-03/15/22-08:01:28: rgb_feats | Stats: mean=-0.08473, std-dev=0.35423, var=0.12548, median=-0.13429, min=-2.64 at (0, 160, 4, 7), max=2.025 at (0, 8, 2780, 9), avg-magnitude=0.29166
             ---- Histogram ----
             Bin Range        |  Num Elems | Visualization
             (-2.68 , -2.21 ) |        560 |
             (-2.21 , -1.74 ) |       2932 |
             (-1.74 , -1.27 ) |       9576 |
             (-1.27 , -0.795) |     150260 |
             (-0.795, -0.325) |    4204532 | ###################
             (-0.325, 0.145 ) |    8443224 | ########################################
             (0.145 , 0.615 ) |    2931600 | #############
             (0.615 , 1.08  ) |     819448 | ###
             (1.08  , 1.55  ) |      26472 |
             (1.55  , 2.03  ) |        196 |
         onnxrt-runner-N0-03/15/22-08:01:28: rgb_feats | Stats: mean=-0.084599, std-dev=0.35455, var=0.12571, median=-0.13477, min=-2.6758 at (0, 160, 4, 7), max=1.955 at (0, 8, 1476, 9), avg-magnitude=0.29184
             ---- Histogram ----
             Bin Range        |  Num Elems | Visualization
             (-2.68 , -2.21 ) |        596 |
             (-2.21 , -1.74 ) |       2864 |
             (-1.74 , -1.27 ) |       9684 |
             (-1.27 , -0.795) |     149228 |
             (-0.795, -0.325) |    4191284 | ###################
             (-0.325, 0.145 ) |    8447500 | ########################################
             (0.145 , 0.615 ) |    2939628 | #############
             (0.615 , 1.08  ) |     818180 | ###
             (1.08  , 1.55  ) |      29636 |
             (1.55  , 2.03  ) |        200 |

**Comment by nvpohanh** [comment]
Closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks!
