### ISSUE TITLE
How to using topK when already got forward output?

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#172]
Hi,

I have a post-processing need using topK, so if I got a tensor with shape [1, 80, 128, 128] which is `batch, cls, size, size` in a `float*` memory block on CPU

How to call TensorRT topK op with it?

**Comment by rmccorm4** [comment]
Hi @jinfagang,

The best I can do at the moment is recommend checking out these notes on using the TopK layer: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#topk-layer

Or try adding the TopK layer into your original framework's network before parsing into a TensorRT network.

**Comment by jinfagang** [comment]
@rmccorm4  Not very related but wanna quick ask, does TensorRT natively support Equal op now? It's quite often used in modern models.

**Comment by rmccorm4** [comment]
> This repository contains the Open Source Software (OSS) components of NVIDIA TensorRT. Included are the sources for TensorRT plugins and parsers (Caffe and ONNX)

The ONNX parser is one of the open-source components that TensorRT uses, so it's included in this repo :slightly_smiling_face: 

You can see that in `TensorRT/parser/`, the `onnx` folder is actually a git submodule pointing to the https://github.com/onnx/onnx-tensorrt repo if you click on it.
