### ISSUE TITLE
In the docker container, jupyter notebook "could not locate runnable browser" .

### ISSUE THREAD

**Issue by minertom** [NVIDIA/TensorRT#1729]
I loaded the Nvidia docker as shown here [https://developer.nvidia.com/blog/real-time-nlp-with-bert-using-tensorrt-updated/](url) for TensorRT.

But when I attempt to use the jupyter notebook I get an error "could not locate runnable browser"

The command that I use to run the docker container is
`docker run  --gpus all -v /home/somedirectory/someotherdirectory/TensorRT/TensorRT:/workspace/TensorRT --rm -it tensorrt-ubuntu18.04-cuda11.5:latest`

The warning that I get is
`no web browser found: could not locate runnable browser.`

Also, one clue is that the link that is given for the file to be opened, opens the wrong directory of ipynb files. It opens the directory that I had used previously in another project, having nothing to do with this docker image.

Thank You
Tom

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
