### ISSUE TITLE
where can I find tensorrt examples for python?

### ISSUE THREAD

**Issue by ivgenyk** [NVIDIA/TensorRT#173]
The docs says that the examples are located at /usr/src/tensorrt/samples/python/ but I can't locate this folder anywhere including in this git repo. Can anyone please point me to the location of these examples?
source: https://docs.nvidia.com/deeplearning/sdk/pdf/TensorRT-Sample-Support-Guide.pdf

**Comment by anuar12** [comment]
One good piece of code that I found useful is https://github.com/NVIDIA/object-detection-tensorrt-example

**Comment by rmccorm4** [comment]
Hi @ivgenyk ,

The python samples come with the full TensorRT installation, this repo currently only includes the open source components.

You can find installation instructions to install on your host machine here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html

Or for simplicity you can use Docker + NVIDIA-Docker (https://github.com/NVIDIA/nvidia-docker) to run various versions of TensorRT in our Tensorflow/TensorRT containers published monthly on NGC: https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt

**Comment by dongfangduoshou123** [comment]
@rmccorm4 Hi, Please have a look at my issue:https://github.com/NVIDIA/TensorRT/issues/178, need your help.

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.

**Comment by mdegans** [comment]
Is there a good reason for the restrictive license in the Python while the c++ is apache?
```
...
# These Licensed Deliverables contained herein is PROPRIETARY and
# CONFIDENTIAL to NVIDIA and is being provided under the terms and
# conditions of a form of NVIDIA software license agreement by and
# between NVIDIA and Licensee ("License Agreement") or electronically
# accepted by Licensee.  Notwithstanding any terms or conditions to
# the contrary in the License Agreement, reproduction or disclosure
# of the Licensed Deliverables to any third party without the express
# written consent of NVIDIA is prohibited.
...
```

My reading of this is that I can't use these samples anywhere, since I'm under NDA with Nvidia. If I use bits of it in my client's code (client has already copied without attribution anyway), it's a licensing nightmare. It would be helpful if this was relicensed, since it's example code and documentation.
