### ISSUE TITLE
A question on the INT8 Calibrator python example

### ISSUE THREAD

**Issue by moran991231** [NVIDIA/TensorRT#1732]
Why does the calibrator use not `train_set` but `test_set`? In the 93th line in the below source code, the `train_set` variable get the path from `data_files`, but never used.

https://github.com/NVIDIA/TensorRT/blob/498dcb009fe4c2dedbe9c61044d3de4f3c04a41b/samples/python/int8_caffe_mnist/sample.py#L92-L98

By the way, I can find the parameter's name is `training_data` in the constructor of Calibrator
https://github.com/NVIDIA/TensorRT/blob/498dcb009fe4c2dedbe9c61044d3de4f3c04a41b/samples/python/int8_caffe_mnist/calibrator.py#L47-L59

I checked that the program ran well when I gave `train_set` instead of `test_set` to the constructor of calibrator.

  
+) I found another problem in the code
https://github.com/NVIDIA/TensorRT/blob/498dcb009fe4c2dedbe9c61044d3de4f3c04a41b/samples/python/int8_caffe_mnist/sample.py#L81-L82
`output.reshape(32,10)...` should be `output.reshape(batch_size,10)...`. The above code assumes only if batch_size is 32 and hard coded it.

**Comment by ttyio** [comment]
Fixed in next build, thanks @moran991231

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
