### ISSUE TITLE
[E] [TRT] cuda/caskConvolutionLayer.cpp (355) - Cuda Error in execute: 9 (invalid configuration argument)

### ISSUE THREAD

**Issue by forvd** [NVIDIA/TensorRT#1734]
## Description
try to infer my model. but get this error.
I've already get correct output with tensorrt python backend.
but i can't run it in c++

## Environment

**TensorRT Version**: 5.1.5
**NVIDIA GPU**: 1080ti
**NVIDIA Driver Version**: 
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System**: 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

void solov2::doInference(nvinfer1::IExecutionContext& context, float* input, float* output1, float * output2, float * output3, int batchSize)
{
    const nvinfer1::ICudaEngine& engine = context.getEngine();
    // Pointers to input and output device buffers to pass to engine.
    // Engine requires exactly IEngine::getNbBindings() number of buffers.
    assert(engine.getNbBindings() == 4);
    void* buffers[4];
    // float *temp;

    // In order to bind the buffers, we need to know the names of the input and output tensors.
    // Note that indices are guaranteed to be less than IEngine::getNbBindings()
    const int inputIndex = engine.getBindingIndex(INPUT_BLOB_NAME);
    const int outputIndex0 = engine.getBindingIndex(OUTPUT_BLOB_solov20);
    const int outputIndex1 = engine.getBindingIndex(OUTPUT_BLOB_solov21);
    const int outputIndex2= engine.getBindingIndex(OUTPUT_BLOB_solov22);
//    const int outputclass = engine.getBindingIndex(OUTPUT_BLOB_CLASS);

    // Create GPU buffers on device
    CHECK(cudaMalloc(&buffers[inputIndex], batchSize * 3 * INPUT_H * INPUT_W * sizeof(float)));
    CHECK(cudaMalloc(&buffers[outputIndex0], batchSize * (320*96*128) * sizeof(float)));
    CHECK(cudaMalloc(&buffers[outputIndex1], batchSize * (27996) * sizeof(float)));
    CHECK(cudaMalloc(&buffers[outputIndex2], batchSize * (27996*128) * sizeof(float)));

//    CHECK(cudaMalloc(&buffers[outputclass], 4 * sizeof(float)));
    // float* temp = output+batchSize * (OUTPUT_SIZE-4);
    // Create stream
    cudaStream_t stream;
    CHECK(cudaStreamCreate(&stream));
    // DMA input batch data to device, infer on the batch asynchronously, and DMA output back to host
    CHECK(cudaMemcpyAsync(buffers[inputIndex], input, batchSize * 3 * INPUT_H * INPUT_W * sizeof(float), cudaMemcpyHostToDevice, stream));
    context.enqueue(batchSize, buffers, stream, nullptr);
    CHECK(cudaMemcpyAsync(output1, buffers[outputIndex0], batchSize * 320*96*128 * sizeof(float), cudaMemcpyDeviceToHost, stream));
    CHECK(cudaMemcpyAsync(output2, buffers[outputIndex1], batchSize * 27996 * sizeof(float), cudaMemcpyDeviceToHost, stream));
    CHECK(cudaMemcpyAsync(output3, buffers[outputIndex2], batchSize * (27996*128) * sizeof(float), cudaMemcpyDeviceToHost, stream));
    cudaStreamSynchronize(stream);
    // Release stream and buffers
    cudaStreamDestroy(stream);
    CHECK(cudaFree(buffers[inputIndex]));
    CHECK(cudaFree(buffers[outputIndex0]));
    CHECK(cudaFree(buffers[outputIndex1]));
    CHECK(cudaFree(buffers[outputIndex2]));
    // CHECK(cudaFree(temp));
    // if(temp)
    // temp=nullptr;
}
bool solov2::runTimeInit(const std::string &engineFile)
{
    std::ifstream file(engineFile, std::ios::binary);
    if (file.good()) {
        file.seekg(0, file.end);
        size = file.tellg();
        file.seekg(0, file.beg);
        trtModelStream = new char[size];
        assert(trtModelStream);
        file.read(trtModelStream, size);
        file.close();
    }
    //init color map
//    colorMap = get_color_map();
    //init engine

    initLibNvInferPlugins(&gLogger, "");
    cudaSetDevice(0);
    runtime = createInferRuntime(gLogger);

    float data[INPUT_H * INPUT_W * 3];
    for (int i = 0; i < INPUT_H * INPUT_W * 3; i++)
        data[i] = 1.0;

    assert(runtime != nullptr);
    engine = runtime->deserializeCudaEngine(trtModelStream, size, nullptr);
    assert(engine != nullptr);
    context = engine->createExecutionContext();
    assert(context != nullptr);
    assert(engine->getNbBindings() == 4);
//    delete[] trtModelStream;
    //

    for (int i = 0; i < 1000; i++) {
        auto start = std::chrono::system_clock::now();
        solov2::doInference(*context, data, seg, cate, kernel, 1);
        auto end = std::chrono::system_clock::now();
        //std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;
    }
    context->destroy();
    engine->destroy();
    runtime->destroy();

//    CHECK(cudaHostAlloc((void **)&inputT, BATCH_SIZE * 3 * INPUT_H * INPUT_W * sizeof(float), cudaHostAllocMapped));
//    CHECK(cudaHostAlloc((void **)&probsolov20, BATCH_SIZE * 320*96*128 * sizeof(float), cudaHostAllocMapped));
//    CHECK(cudaHostAlloc((void **)&probsolov21, BATCH_SIZE * 27996 * sizeof(float), cudaHostAllocMapped));
//    CHECK(cudaHostAlloc((void **)&probsolov22, BATCH_SIZE * 27996*128 * sizeof(float), cudaHostAllocMapped));
//
//
//
//
//    //gei index
//    inputIndex = engine->getBindingIndex(INPUT_BLOB_NAME);
////    printf(outputsolov2Index0);
//    outputsolov2Index0 = engine->getBindingIndex(OUTPUT_BLOB_solov20);
//    outputsolov2Index1 = engine->getBindingIndex(OUTPUT_BLOB_solov21);
//    outputsolov2Index2 = engine->getBindingIndex(OUTPUT_BLOB_solov22);
//
////    CHECK(cudaMalloc(&buffers[inputIndex], BATCH_SIZE * 3 * INPUT_H * INPUT_W * sizeof(float)));
////    CHECK(cudaMalloc(&buffers[outputsolov2Index0], BATCH_SIZE * 3932160 * sizeof(float)));
////    CHECK(cudaMalloc(&buffers[outputsolov2Index1], BATCH_SIZE * 27996 * sizeof(float)));
////    CHECK(cudaMalloc(&buffers[outputsolov2Index2], BATCH_SIZE * 27996*128 * sizeof(float)));
//
//    CHECK(cudaStreamCreate(&stream));
//    cudaHostGetDevicePointer((void **)&buffers[inputIndex], (void *)inputT, 0);  // buffers[inputIndex]-->data
//    cudaHostGetDevicePointer((void **)&buffers[outputsolov2Index0], (void *)probsolov20, 0); // buffers[outputIndex] --> prob
//    cudaHostGetDevicePointer((void **)&buffers[outputsolov2Index1], (void *)probsolov21, 0); // buffers[outputIndex] --> prob
//    cudaHostGetDevicePointer((void **)&buffers[outputsolov2Index2], (void *)probsolov22, 0); // buffers[outputIndex] --> prob
//
//     std::cout<<"runTime init succss!!"<<std::endl;
    return true;
}

**Comment by ttyio** [comment]
@forvd , have you tried upgrade your TRT version?

**Comment by galagam** [comment]
Closing due to lack of response from author and old TensorRT version (5.1.5).
