### ISSUE TITLE
 Error Code 6: Internal Error (Loop API is not supported on this configuration. This may be because the requested platform does not support loops, or because TensorRT has been statically linked.) 

### ISSUE THREAD

**Issue by expresschen** [NVIDIA/TensorRT#1737]
## Environment

**TensorRT Version 8.0.1.6: 
**NVIDIA GPU p40: 
**NVIDIA Driver Version 440.18.02: 
**CUDA Version 10.2: 
**CUDNN Version 8.2: 
**Operating System centos: 
**Python Version (if applicable) 3.6: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)1.7.1: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@expresschen  are you using implicit batch?

**Comment by KaiLei1991** [comment]
I have got the same error. My Environment is TensorRT Version 8.0.2.3, NVIDIA GPU T400, CUDA Version 10.2, Operating System Win10. I use the tensorrt C++ API, and  I have called net= fBuilder->createNetworkV2(1U << static_cast<int32_t>(nvinfer1::NetworkDefinitionCreationFlag::kEXPLICIT_BATCH)). The progrom runs well when I use P1000 GPU, so what is wrong with  T400 GPU?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Comment by linus-gates** [comment]
Hi, I'm using TX2 with tensorrt 8.2 and got the same error
@expresschen  @KaiLei1991 did you find any solution?
thanks:)
