### ISSUE TITLE
add custom op in tensorrt 6.0 used in python failed

### ISSUE THREAD

**Issue by Magicwangs** [NVIDIA/TensorRT#174]
the code work well in tensorrt 5.0 but failed in 6.0
code is here https://github.com/souseiki/UpsamplingPlugin

**Comment by rmccorm4** [comment]
Hi @Magicwangs ,

Maybe this section in the docs for migrating plugins from 5.x to 6.x can help? 

https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#migrating-plugins-5xx-6xx

**Comment by Magicwangs** [comment]
i  update my code to 
https://github.com/Magicwangs/UpsamplingPlugin
build sucessed but still failed to find this plugin in python

**Comment by rmccorm4** [comment]
Hi @Magicwangs,

Please provide more details about the error, the traceback, your environment versions, etc.

**Comment by Magicwangs** [comment]
sorry, i figure out now, that's because  of the wrong link with old version(5.0)
thanks for your answer!

**Comment by rmccorm4** [comment]
No problem. 

@Magicwangs can you please post more details on how you fixed linking your plugin?

There are several other users who are having issues with plugins, so it might be very helpful to them.

Thanks!
