### ISSUE TITLE
Where are the implementations of class IBuilder and class INetworkDefinition in TensorRT? I want to see the internal implementation of these classes but cannot find any? 

### ISSUE THREAD

**Issue by blackbaba980** [NVIDIA/TensorRT#1742]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
they are not open-source
