### ISSUE TITLE
Yolo v5 nabo

### ISSUE THREAD

**Issue by ONNONS** [NVIDIA/TensorRT#1745]
Can yolov5 nano version be supported too? I can't make an engine file.

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zhiqwang** [comment]
Hi @ONNONS YOLOv5 should be able to converted from ONNX, there are two ways as I knew:

1. Export the ONNX as suggested by https://github.com/ultralytics/yolov5/issues/251 .
2. I embedded the `batchNMS_plugin` at the end of the above ONNX, check https://zhiqwang.com/yolov5-rt-stack/notebooks/onnx-graphsurgeon-inference-tensorrt.html for more details.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
