### ISSUE TITLE
Migrating from TensorRT 5.0 to 6.0?

### ISSUE THREAD

**Issue by anuar12** [NVIDIA/TensorRT#175]
Are there any changes in the Python API in TensorRT 6.0 wrt 5.0? Most of the examples online are in 5.0

**Comment by rmccorm4** [comment]
Hi @anuar12 ,

You can see all of the changes in the release notes here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html#rel_6-0-1

These should apply to the Python API as well. One notable change is dynamic shapes and optimization profiles (https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Core/OptimizationProfile.html).

You can see an example of these in the BERT demo: https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/python/bert_builder.py#L329-L355

**Comment by anuar12** [comment]
Alright, thank you. Seems like there are not breaking changes in the api.
