### ISSUE TITLE
[QST] Does TRT support setting/getting custom metadata fields?

### ISSUE THREAD

**Issue by seanajohnston** [NVIDIA/TensorRT#1751]
The models my application uses at runtime can be variable. Models are stored as serialized engines. I would like some ability to query models for various capability options so the application can handle accordingly. This data could be as simple as strings. Does TensorRT support such options?

**Comment by pranavm-nvidia** [comment]
The serialized engine is returned as a byte buffer, so you're free to prepend/append with arbitrary custom metadata. For example, in Python:
```py
engine_bytes = bytes(engine.serialize())

with open("with_custom_metadata.engine", "wb") as f:
    tags = "My Custom Tag"
    f.write(bytes(len(tags)))
    f.write(tags.encode())
    f.write(engine_bytes)
```

**Comment by seanajohnston** [comment]
Ok thanks. Manipulating the file TRT directly was the backup plan. Guess that'll do. Thanks.
