### ISSUE TITLE
How to use FP16 precision in C++

### ISSUE THREAD

**Issue by DavidBaldsiefen** [NVIDIA/TensorRT#1754]
I am trying run inference on an FP16-Engine in C++. `engine->getBindingDataType(i)` correctly returns '1' (kHALF) for all Bindings. However, when I am using the following lines to get the output, the compiler is obviously interpreting it as normal floats (=FP32)
```

std::vector<float> cpu_output(getSizeByDim(output_dims[0]) * 1);
cudaMemcpy(cpu_output.data(), buffers[outputIndex], cpu_output.size() * sizeof(float), cudaMemcpyDeviceToHost);
```

How can I make sure that the contents are correctly converted to float, or what datatype can I use to interpret them as halfs? Right now, the `cpu_output` vector somehow casts the halfs so that the output floats are way too large (estimated ~100 times larger than they should be). Can I just do something like "`cpu_output[i] = cpu_output[i]<<8`"?

**Comment by nvpohanh** [comment]
You can use libraries like this one to convert float to half: https://github.com/ramenhut/half

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
