### ISSUE TITLE
Bug in converting T5 base model

### ISSUE THREAD

**Issue by VikasOjha666** [NVIDIA/TensorRT#1772]
## Environment

**TensorRT Version:8.2 
**NVIDIA GPU: Tesla K80 or Tesla P100
**NVIDIA Driver Version**: 
**CUDA Version**: 11.2
**CUDNN Version**: 
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: 2.7
**PyTorch Version (if applicable)**: 1.10
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce
In Google colab

Clone TensorRT Nvidia repo.
Install TensorRT 8.2 using pip install nvidia-tensorrt==8.2.* --index-url https://pypi.ngc.nvidia.com

Restart runtime 
Install requirements of hugging face TensorRT

Follow this notebook:
https://github.com/NVIDIA/TensorRT/blob/release/8.2/demo/HuggingFace/notebooks/t5.ipynb

Was able to convert the T5 small model using the steps but getting following issue in the TRT engine building part:
PolygraphyException                       Traceback (most recent call last)
<ipython-input-18-ea28c3a202b5> in <module>()
      1 t5_trt_encoder_engine = T5EncoderONNXFile(
      2                 os.path.join(onnx_model_path, encoder_onnx_model_fpath), metadata
----> 3             ).as_trt_engine(os.path.join(tensorrt_model_path, encoder_onnx_model_fpath) + ".engine")
      4 
      5 t5_trt_decoder_engine = T5DecoderONNXFile(

8 frames
<string> in func_impl(network, config, save_timing_cache)

<string> in func_impl(serialized_engine)

/usr/local/lib/python3.7/dist-packages/polygraphy/logger/logger.py in critical(self, message)
    347         from polygraphy.exception import PolygraphyException
    348 
--> 349         raise PolygraphyException(message) from None
    350 
    351     def internal_error(self, message):

PolygraphyException: Invalid Engine. Please ensure the engine was built correctly

**Comment by gennarovaccaro** [comment]
Hi @VikasOjha666, I have the same problem. I tried with my own trained t5-base. How did you solve the problem?

**Comment by VikasOjha666** [comment]
Hi @gennarovaccaro .I was installed the tensorRT with pip command and hence I was facing the issue. I tried with docker version it did worked. You can also install TensorRT in your own environment by following proper installation instructions from TensorRT docs. If you still fave issue let me know I will give you the full steps for Ubuntu 18.04

**Comment by gennarovaccaro** [comment]
@VikasOjha666 Thank you for the answer. I followed [this](https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/) guide and used this [code](https://github.com/NVIDIA/TensorRT/blob/main/demo/HuggingFace/notebooks/t5.ipynb). 

This code is working fine with a pre-trained T5-small and a T5-base, but I have the issue using my finetuned T5-base.

**Comment by VikasOjha666** [comment]
@gennarovaccaro You need to change the vocab_size parameter in T5/T5ModelConfig.py to the one in your model config file. I faced the same issue once. Whenever a model is fine-tuned it's vocab size becomes equal to the unique words in the dataset.To get the value you need to look in model config file. After changing that everything should work fine.

**Comment by gennarovaccaro** [comment]
@VikasOjha666 thank you for the answer! I changed the vocab_size, but I still have this error: 
`RuntimeError: The expanded size of the tensor (13) must match the existing size (14) at non-singleton dimension 0.  Target sizes: [13].  Tensor sizes: [14]`

I don't know if I need to change other things. This is my model config:

`_name_or_path:"./MyNet/"
architectures:
d_ff:3072
d_kv:64
d_model:768
decoder_start_token_id:0
dropout_rate:0.1
eos_token_id:1
feed_forward_proj:"relu"
initializer_factor:1
is_encoder_decoder:true
layer_norm_epsilon:0.000001
model_type:"t5"
n_positions:512
num_decoder_layers:12
num_heads:12
num_layers:12
output_past:true
pad_token_id:0
relative_attention_num_buckets:32
task_specific_params:
torch_dtype:"float32"
transformers_version:"4.16.2"
use_cache:true
vocab_size:32102`


I see the difference is in the vocab_size and there is also torch_dtype:"float32". Maybe this?

**Comment by VikasOjha666** [comment]
This kind of error happens when the memory block allocated by TensorRT is different than the input shape. For this you need to see the forward methods of encoder/decoder in trt.py and check if the tensor shapes grabbed by the forward function is correct.

**Comment by gennarovaccaro** [comment]
@VikasOjha666 I saw the two forward function. How can I verify if the tensor shapes grabbed by the forward function is correct?

I saw that using CPU and not CUDA (the GPU) all work fine. So I used the CPU code for GPU and all works fine. Thank you for the support.

**Comment by gennarovaccaro** [comment]
@VikasOjha666 Okay thank you for the info. So for long outputs it is not convenient for now. Can you get some optimization currently with the TensorRT container for T5? Using for example the `.pt` model (and not .bin)?

**Comment by VikasOjha666** [comment]
@gennarovaccaro As of now tensorRT is useless for T5 optimization. I wasted around 15 days on this.

**Comment by gennarovaccaro** [comment]
@VikasOjha666 oh okay thanks. Currently the only way to speed up a T5 is to do GPU inference (`.pt` o `.bin` for pytorch), then?

**Comment by VikasOjha666** [comment]
@gennarovaccaro  Try ONNX GPU with IO bindings. Just search transformer deploy github. There the owner has implemented the approach for GPT2 you can take idea from there. Also check FastT5 project on github.

**Comment by VikasOjha666** [comment]
You can also try fp16 on the ONNX or with torch itself. But for T5-base and above do not perform quantization for T5 encoder as they become unstable. Quantize only decoder.

**Comment by gennarovaccaro** [comment]
@VikasOjha666 Fast-T5 does not support GPU for now (if I'm not mistaken) with quantization, and without quantization GPU is better.

In the case of transformer deploy, are you referring to [this](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2_with_OnnxRuntime_on_CPU.ipynb)? But it's on CPU and not GPU. I saw also [this ](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb) on GPU but without IO binding.

In reference to this:
> You can also try fp16 on the ONNX or with torch itself. But for T5-base and above do not perform quantization for T5 encoder as they become unstable. Quantize only decoder.

Is there any reference code?
Thank you.

**Comment by VikasOjha666** [comment]
In transformer deploy there is optimization of GPT-2 for GPU by ONNX,ONNX with IO bindings and TensorRT. In Fast T5 you can check pull section of the repo.There is something called cuda support. Although there is bug in it and it doesn't work but still you can get the idea. I got the idea from these repos for my implementation.
