### ISSUE TITLE
Is it normal that the first call to executeV2 takes long?

### ISSUE THREAD

**Issue by katrasnikj** [NVIDIA/TensorRT#1776]
The first call to executeV2 after engine and execution context initialization takes much longer (1 s) than all subsequent calls to executeV2 (10 ms). Is this normal? Is there anything that can be done to reduce the duration of the first executeV2 call?

**Comment by spivakoa** [comment]
Yes, totally. The first call to the driver API takes time.

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
