### ISSUE TITLE
Could not find mnist.prototxt in data directories

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/TensorRT#1778]
&&&& RUNNING TensorRT.sample_mnist [TensorRT v8201] # ./build/out/sample_mnist
Could not find mnist.prototxt in data directories:
	data/mnist/
	data/samples/mnist/
&&&& FAILED
there isn't the data directory.

**Comment by ttyio** [comment]
@GeneralJing , could you check https://github.com/NVIDIA/TensorRT/tree/main/samples/sampleMNIST#preparing-sample-data?

**Comment by GeneralJing** [comment]
i found the data from tensorrt official tar file. thank you.
