### ISSUE TITLE
/usr/include/c++/11/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const   770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#1783]
Build error:

```
/usr/include/c++/11/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

g++ 11.2 Ubuntu 21.10

this error happens by decent g++ used here and it was protobuf problem:

https://code.videolan.org/videolan/vlc/-/merge_requests/1029/diffs

**Comment by samurdhikaru** [comment]
@jinfagang Can you please provide the steps that led to this error? i.e. What steps did you follow to issue the build?

**Comment by ttyio** [comment]
@jinfagang , currently we only tested with the gcc tool chain in the offcial docker enviroment

https://github.com/NVIDIA/TensorRT#setting-up-the-build-environment

**Comment by jinfagang** [comment]
It's not with g++11, downgrade to g++8 can build.

Seems this is not tensorrt issue, it's protobuf issue. Close this due to can be solved.

**Comment by sinaazimii** [comment]
can be resolved how? @lucasjinreal
