### ISSUE TITLE
How to use IGatherLayer ?

### ISSUE THREAD

**Issue by baoachun** [NVIDIA/TensorRT#1795]
I'm very confused about using gather layer, I reshape indices into 1 dimension, axis is set to 0, GatherMode is set to kDEFAULT, but the output is always incorrect. For example, if the input indices are [3, 2, 3] and the input tensor shape is [5, 3], the output result is incorrect. If the indices are reversed according to the output, the indices are [3, 0, 2], so I found that the first index of the reversely speculated indices is always correct, the second index is always 0, and the third index is always the second index that was originally entered correctly. So I'm curious if it's a problem with my usage, or does gather have special requirements for the input?

Input indices :                                  [3, 2, 3]
Indices deduced from the result:   [3, 0, 2]

Input indices :                                  [3, 4, 3]
Indices deduced from the result:   [3, 0, 4]

Input indices :                                  [2, 1, 2]
Indices deduced from the result:   [2, 0, 1]

Input indices :                                  [3, 1, 0, 0]
Indices deduced from the result:   [3, 0, 1, 0]

**Comment by ttyio** [comment]
@baoachun , trt gather `default` mode is the same as onnx `gather`, check https://github.com/onnx/onnx/blob/main/docs/Operators.md#gather, there is also examples, thanks!

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
