### ISSUE TITLE
require for explicit version of onnxruntime in Polygraphy

### ISSUE THREAD

**Issue by jinluyang** [NVIDIA/TensorRT#1800]
## Description

Could we write the version of onnxruntime here? https://github.com/NVIDIA/TensorRT/blob/42805f078052daad1a98bc5965974fcffaad0960/tools/Polygraphy/polygraphy/backend/onnxrt/requirements.txt#L1
Because it seems not all versions works well. I tried 1.10.0, it causes core dumps. 1.6.0 works well.

## Environment

**TensorRT Version**: 8.2.3
**NVIDIA GPU**: T4
**NVIDIA Driver Version**:460 
**CUDA Version**: 11
**Operating System**:redhat 
**Python Version (if applicable)**:3.8 

## Steps To Reproduce

just run whatever onnx file using polygraphy with --onnxrt

**Comment by pranavm-nvidia** [comment]
That's weird, it seems to be working fine for me:
```
[V] Loaded Module: polygraphy.util    | Path: ['/home/pranavm/TensorRT/infrastructure/Polygraphy/polygraphy/util']
[V] Model: tests/models/identity.onnx
[V] Loaded Module: polygraphy         | Version: 0.33.2 | Path: ['/home/pranavm/TensorRT/infrastructure/Polygraphy/polygraphy']
[I] onnxrt-runner-N0-02/16/22-06:09:41  | Activating and starting inference
[V] Loaded Module: onnxruntime        | Version: 1.10.0 | Path: ['/home/pranavm/.local/lib/python3.6/site-packages/onnxruntime']
[V] Loaded Module: numpy              | Version: 1.19.5 | Path: ['/home/pranavm/.local/lib/python3.6/site-packages/numpy']
[V] Loading inputs from data loader
[V] Generating data using numpy seed: 1
[V] Input tensor: x | Generating input data in range: [0.0, 1.0]
[I] onnxrt-runner-N0-02/16/22-06:09:41 
    ---- Inference Input(s) ----
    {x [dtype=float32, shape=(1, 1, 2, 2)]}
[V] Runner input metadata is: {x [dtype=float32, shape=(1, 1, 2, 2)]}
[I] onnxrt-runner-N0-02/16/22-06:09:41 
    ---- Inference Output(s) ----
    {y [dtype=float32, shape=(1, 1, 2, 2)]}
[I] onnxrt-runner-N0-02/16/22-06:09:41  | Completed 1 iteration(s) in 0.09561 ms | Average inference time: 0.09561 ms.
[V] Successfully ran: ['onnxrt-runner-N0-02/16/22-06:09:41']
[I] PASSED | Command: polygraphy run tests/models/identity.onnx --onnxrt -v
```

Does it show you any errors/warnings before it crashes?

**Comment by jinluyang** [comment]
the output is as follows, no error/warning, but gdb might give something useful.
polygraphy run /home/service/to_onnx_pb/designpoints_kvcache.onnx --model-type onnx --input-shapes input:[1,2] seg:[1,1]  pasts:[1,12,2,12,1,64] --onnxrt -v
[V] Loaded Module: polygraphy.util    | Path: ['/home/admin/TensorRT/tools/Polygraphy/polygraphy/util']
[V] Model: /home/service/to_onnx_pb/designpoints_kvcache.onnx
[V] Loaded Module: polygraphy         | Version: 0.33.0   | Path: ['/home/admin/TensorRT/tools/Polygraphy/polygraphy']
[I] Will generate inference input data according to provided TensorMetadata: {input [shape=(1, 2)],
     seg [shape=(1, 1)],
     pasts [shape=(1, 12, 2, 12, 1, 64)]}
[I] onnxrt-runner-N0-02/17/22-09:46:36  | Activating and starting inference
[V] Loaded Module: onnxruntime        | Version: 1.10.0   | Path: ['/home/admin/.local/lib/python3.8/site-packages/onnxruntime']
Segmentation fault (core dumped)


File "/home/admin/TensorRT/tools/Polygraphy/bin/../polygraphy/backend/onnxrt/loader.py", line 44, in call_impl
    return onnxruntime.InferenceSession(model_bytes)
  File "/home/admin/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/admin/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
RuntimeError: /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 0 error msg:


Thread 2 "python" received signal SIGSEGV, Segmentation fault.

> That's weird, it seems to be working fine for me:
> 
> ```
> [V] Loaded Module: polygraphy.util    | Path: ['/home/pranavm/TensorRT/infrastructure/Polygraphy/polygraphy/util']
> [V] Model: tests/models/identity.onnx
> [V] Loaded Module: polygraphy         | Version: 0.33.2 | Path: ['/home/pranavm/TensorRT/infrastructure/Polygraphy/polygraphy']
> [I] onnxrt-runner-N0-02/16/22-06:09:41  | Activating and starting inference
> [V] Loaded Module: onnxruntime        | Version: 1.10.0 | Path: ['/home/pranavm/.local/lib/python3.6/site-packages/onnxruntime']
> [V] Loaded Module: numpy              | Version: 1.19.5 | Path: ['/home/pranavm/.local/lib/python3.6/site-packages/numpy']
> [V] Loading inputs from data loader
> [V] Generating data using numpy seed: 1
> [V] Input tensor: x | Generating input data in range: [0.0, 1.0]
> [I] onnxrt-runner-N0-02/16/22-06:09:41 
>     ---- Inference Input(s) ----
>     {x [dtype=float32, shape=(1, 1, 2, 2)]}
> [V] Runner input metadata is: {x [dtype=float32, shape=(1, 1, 2, 2)]}
> [I] onnxrt-runner-N0-02/16/22-06:09:41 
>     ---- Inference Output(s) ----
>     {y [dtype=float32, shape=(1, 1, 2, 2)]}
> [I] onnxrt-runner-N0-02/16/22-06:09:41  | Completed 1 iteration(s) in 0.09561 ms | Average inference time: 0.09561 ms.
> [V] Successfully ran: ['onnxrt-runner-N0-02/16/22-06:09:41']
> [I] PASSED | Command: polygraphy run tests/models/identity.onnx --onnxrt -v
> ```
> 
> Does it show you any errors/warnings before it crashes?

**Comment by pranavm-nvidia** [comment]
Looks like there are similar issues reported here: 
- https://github.com/microsoft/onnxruntime/issues/8313
- https://github.com/microsoft/onnxruntime/issues/10113

One of the suggestions there is to use the CPU version of ONNX-Runtime
