### ISSUE TITLE
PyTorch FCN-ResNet50 -> ONNX -> TensorRT

### ISSUE THREAD

**Issue by berkay1** [NVIDIA/TensorRT#1801]
I saw samples on nvidia's website then I wanted to proceed with a straightforward example of PyTorch --> ONNX --> TRT

**Using torch.hub model**
model = torch.hub.load('pytorch/vision:v0.10.0', 'fcn_resnet50', pretrained=True)

#EXPORTING MODEL TO ONNX FORMAT
dummy_input = torch.randn(1,3,720,1280)
input_names = 'input'
output_names = 'output'
torch.onnx.export(model, dummy_input, "fcn_resnet50.onnx", verbose=False, opset_version=11)

**and following**

!trtexec --onnx=fcn_resnet50.onnx --saveEngine=fcn_resnet50.trt  --explicitBatch --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --fp16 --workspace=707788800

succesfully creates fcn_resnet50.trt but,

at the execution I get the following error

LogicError: cuMemcpyDtoHAsync failed: an illegal memory access was encountered

or sometimes

[tensorrt] error: 3: [executioncontext.cpp::enqueueinternal::322] error code 3: internal error (parameter check failed at: runtime/api/executioncontext.cpp::enqueueinternal::322, condition: bindings[x] != nullptr)

# ENVIRONMENT
CUDA 11.3.1
TensorRT 8.0.3.4
cuDNN 8.2.1
Ubuntu 20.04

# EXECUTION

`import numpy as np`
`import pycuda.driver as cuda`
`import pycuda.autoinit`

`input_batch = np.empty([1,3,720,1280], dtype=np.float16)`
`output = np.empty([1, 21, 720, 1280], dtype = np.float16)`
`d_input = cuda.mem_alloc(1 * input_batch.nbytes)`
`d_output = cuda.mem_alloc(1 * output.nbytes)`
`bindings = [int(d_input), int(d_output)]`
`stream = cuda.Stream()`

`import tensorrt as trt`

`f = open("fcn_resnet50.trt", "rb")`
`runtime = trt.Runtime(trt.Logger(trt.Logger.WARNING)) `
`engine = runtime.deserialize_cuda_engine(f.read())`
`context = engine.create_execution_context()`
`def predict(batch):`
    `cuda.memcpy_htod_async(d_input, batch, stream)`
    `context.execute_async_v2(bindings, stream.handle, None)`
    `cuda.memcpy_dtoh_async(output, d_output, stream)`
    `stream.synchronize()`
    `return output`

I can execute same code above with FCN-ResNet18.onnx which is from jetson-inference module.

**Comment by berkay1** [comment]
I applied same process to torchvision.models.resnet50 and it seems to work out correctly. How can i determine whether the onnx is broken or includes some unsupported plugins? Where should i look?

**Comment by berkay1** [comment]
Tried to convert onnx from https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/fcn/model to TRT but still got the same issue.

**Comment by nvpohanh** [comment]
@berkay1 In your execution script, could you make sure engine's get_binding_shape(1) and get_binding_dtype(1) matches your expectation?
