### ISSUE TITLE
Discrepancy in output between onnxRT/Pytorch and TensorRT

### ISSUE THREAD

**Issue by andrearosasco** [NVIDIA/TensorRT#1802]
## Description

I'm trying to run with TensorRT [this](https://github.com/andrearosasco/pcr/blob/unfactored/model/Backbone.py) PyTorch module but despite actually managing to generate the engine and achieving a substantial speedup I observed a severe discrepancy between the output that I get by running the engine and the one I get by running the PyTorch script or the onnx file.

The reason I'm writing this is that I'm not sure how to debug this kind of problem and I'm essentially stuck at a dead-end.

My last attempt was to run `polygraphy run pcr.onnx --trt --onnxrt --trt-outputs mark all --onnx-outputs mark all --fail-fast --gen-script -` to generate the following python script
```python
#!/usr/bin/env python3
# Template auto-generated by polygraphy [v0.35.1] on 02/16/22 at 09:27:13
# Generation Command: \Users\arosasco\.conda\envs\pcr_aux\Scripts\polygraphy run pcr.onnx --trt --onnxrt --trt-outputs mark all --onnx-outputs mark all --fail-fast --gen-script -
# This script compares C:\Users\arosasco\PycharmProjects\pcr\pcr.onnx between TensorRT and ONNX Runtime.

from polygraphy.logger import G_LOGGER

from polygraphy import constants
from polygraphy.backend.onnx import BytesFromOnnx, ModifyOutputs as ModifyOnnxOutputs, OnnxFromPath
from polygraphy.backend.onnxrt import OnnxrtRunner, SessionFromOnnx
from polygraphy.backend.trt import EngineFromNetwork, ModifyNetworkOutputs, NetworkFromOnnxPath, TrtRunner
from polygraphy.comparator import Comparator, CompareFunc
import sys

# Loaders
parse_network_from_onnx = NetworkFromOnnxPath('C:\\Users\\arosasco\\PycharmProjects\\pcr\\pcr.onnx')
modify_network = ModifyNetworkOutputs(parse_network_from_onnx, outputs=constants.MARK_ALL)
build_engine = EngineFromNetwork(modify_network)
load_onnx = OnnxFromPath('C:\\Users\\arosasco\\PycharmProjects\\pcr\\pcr.onnx')
modify_outputs = ModifyOnnxOutputs(load_onnx, outputs=constants.MARK_ALL)
serialize_onnx = BytesFromOnnx(modify_outputs)
build_onnxrt_session = SessionFromOnnx(serialize_onnx)

# Runners
runners = [
    TrtRunner(build_engine),
    OnnxrtRunner(build_onnxrt_session),
]

# Runner Execution
results = Comparator.run(runners)

success = True
# Accuracy Comparison
compare_func = CompareFunc.simple(fail_fast=True)
success &= bool(Comparator.compare_accuracy(results, compare_func=compare_func, fail_fast=True))

# Report Results
cmd_run = ' '.join(sys.argv)
if not success:
    G_LOGGER.critical("FAILED | Command: {}".format(cmd_run))
G_LOGGER.finish("PASSED | Command: {}".format(cmd_run))
```

but when I try to run it, it throws this error `Process finished with exit code -1073740791 (0xC0000409)` while trying to build the engine. I think that building the engine with all the outputs marked might require too much GPU memory but no exception is raised so it's pretty difficult to find the correct reason for this failure.

Here are the outputs of the scripts that create the onnx and the engine files.
| Action  | Code | Output |
| ------------- | ------------- | ------------- |
| Exporting Onnx  | [export_onnx.py](https://github.com/andrearosasco/pcr/blob/unfactored/production/export_onnx.py) | [onnx_generation.txt](https://github.com/NVIDIA/TensorRT/files/8078446/onnx_generation.txt) [pcr.onnx](https://drive.google.com/file/d/1PFeCSYCKL7G25D5cXe5qNPAFs-7lNg8N/view?usp=sharing) [onnx_graph.txt](https://github.com/NVIDIA/TensorRT/files/8078528/onnx_graph.txt) |
| Onnx &#8594; Engine  | [tiny_tenor_rt.py](https://github.com/andrearosasco/pcr/blob/unfactored/production/tiny_tensor_rt.py)  | [engine_generation.txt](https://github.com/NVIDIA/TensorRT/files/8078377/engine_generation.txt) [pcr.engine](https://drive.google.com/file/d/1LLYS8kqyDuDM41UNY88BJfcN-b0N19y9/view?usp=sharing) [trt_graph.txt](https://github.com/NVIDIA/TensorRT/files/8078498/trt_graph.txt)|
| Running Inference | [tiny_tenor_rt.py](https://github.com/andrearosasco/pcr/blob/unfactored/production/tiny_tensor_rt.py) |

## Environment

**TensorRT Version**: 8.2.3.0
**NVIDIA GPU**: GeForce GTX 1650 Ti
**NVIDIA Driver Version**: 30.0.14.9649
**CUDA Version**: 11.4
**CUDNN Version**: 8.2.1.32
**Operating System**: Windows 10
**Python Version (if applicable)**: 3.7
**PyTorch Version (if applicable)**: 1.10.1
**Baremetal or Container (if so, version)**: Baremetal

## Steps To Reproduce

All the code can be found in the branch `unfactored`  of the repository https://github.com/andrearosasco/pcr.git

**Comment by zerollzeng** [comment]
I don't recommend to mark all tensor as output, it will break the TensorRT's layer fusion so you might get a different result. to debug accuracy issue, try marking the output with the bisect technique to narrow down the problematic layer.

**Comment by nvpohanh** [comment]
@andrearosasco Could you try TRT 8.4 GA (8.4.1) and see if the issue still exists? If it does, please share pcr.onnx file so that we can repro and debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
