### ISSUE TITLE
Generate the TensorRT-OSS build container get the error of ""No package libnvinfer8-8.2.0-1.cuda10 available."" 

### ISSUE THREAD

**Issue by will-wiki** [NVIDIA/TensorRT#1804]
## Description

I'm use the office script "./docker/build.sh --file docker/centos-7.Dockerfile --tag tensorrt-centos7-cuda10.2 --cuda 10.2" to build container,but get the error of  ""No package libnvinfer8-8.2.0-1.cuda10 available."".

Step 16/31 : RUN v="${TRT_VERSION%.*}-1.cuda${CUDA_VERSION%.*}" &&    yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo &&    yum -y install libnvinfer8-${v} libnvparsers8-${v} libnvonnxparsers8-${v} libnvinfer-plugin8-${v}         libnvinfer-devel-${v} libnvparsers-devel-${v} libnvonnxparsers-devel-${v} libnvinfer-plugin-devel-${v}         python3-libnvinfer-${v}
 ---> Running in e06c90b06c0d
Loaded plugins: fastestmirror, ovl
adding repo from: https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
grabbing file https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo to /etc/yum.repos.d/cuda-rhel7.repo
repo saved to /etc/yum.repos.d/cuda-rhel7.repo
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.bupt.edu.cn
 * extras: mirrors.bupt.edu.cn
 * updates: mirrors.aliyun.com
No package libnvinfer8-8.2.0-1.cuda10 available.
No package libnvparsers8-8.2.0-1.cuda10 available.
No package libnvonnxparsers8-8.2.0-1.cuda10 available.
No package libnvinfer-plugin8-8.2.0-1.cuda10 available.
No package libnvinfer-devel-8.2.0-1.cuda10 available.
No package libnvparsers-devel-8.2.0-1.cuda10 available.
No package libnvonnxparsers-devel-8.2.0-1.cuda10 available.
No package libnvinfer-plugin-devel-8.2.0-1.cuda10 available.
No package python3-libnvinfer-8.2.0-1.cuda10 available.

## Steps To Reproduce

The execution code is under [Tensorrt](https://github.com/NVIDIA/TensorRT) web page under "Setting Up The Build Environment" directory, Example: CentOS/RedHat 7 on x86-64 with cuda-10.2

**Comment by nvpohanh** [comment]
@will-wiki Does this issue still exist in latest OSS? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
