### ISSUE TITLE
INT8 calibration cache doesn't created

### ISSUE THREAD

**Issue by zeen263** [NVIDIA/TensorRT#1806]
## Description

Hi, I'm trying to build my centerNet model with INT8 engine. I read the guide and samples and followed it. [(link)](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/efficientdet)   
However, the INT8 engine was created, but the calibration cache was not created. 
I've run it several times, but calibration cache was still not created. I'd appreciate a lot if someone could give me advice.   

## Environment

**TensorRT Version**: 7.2.2-1
**NVIDIA GPU**: Titan Xp
**CUDA Version**: 11.1
**CUDNN Version**: 8.0.5
**Operating System**: CentOS
**Docker image** : nvcr.io/nvidia/tensorrt:20.12-py3   

## Relevant Files

[Repository](https://github.com/zeen263/TRT_int8)

## Steps To Reproduce
command :   
python onnx_to_trt.py --onnx *[my_onnx_path]* --output *[my_engine_path]* --max_batch_size 4 --verbosity simple --explicit_batch --int8 --calibration_cache *[my_calib_cache_path]* --calibration_data *[my_calib_data_path]* --calibration_batch_size 4 --preprocess_func resize_

log :   
2022-02-18 08:14:27 - __main__ - INFO - TRT_LOGGER Verbosity: Severity.INFO
2022-02-18 08:14:37 - __main__ - INFO - Using INT8 build flag
2022-02-18 08:14:37 - __main__ - INFO - Calib cache does not exist, doing calibration...
2022-02-18 08:14:37 - calibrator - INFO - Collecting calibration files from: ../data/calibration/argos
2022-02-18 08:14:37 - calibrator - INFO - Number of Calibration Files found: 500
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:218: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
2022-02-18 08:14:38 - __main__ - INFO - Building Engine...
[TensorRT] INFO: Detected 1 inputs and 7 output network tensors.
2022-02-18 08:15:36 - __main__ - INFO - Writing engine to *[my_engine_path]*

**Comment by ttyio** [comment]
Hello @zeen263 , have you check if you have write permission to the the cache path? also maybe add `printf` to check if `write_calibration_cache` is called, if it is not called, maybe upgrade TRT to a newer one, there is possible some bug in this old version, thanks!

**Comment by zeen263** [comment]
Hello @ttyio, Because I've tried with root permission, maybe it is version issue...? I'll try upgraing TRT. thanks for your responce!

**Comment by nvpohanh** [comment]
closing for now . Please feel free to reopen if the issue still exists. Thanks
