### ISSUE TITLE
Creating a AGX Xavier trt file from x86 

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [NVIDIA/TensorRT#1810]
For our workflow it would be very convenient to not have to use a Xavier to create each trt on an actual Xavier device to test. Is there any way to do this? Can the Xavier environment be emulated in any way with docker and qemu?

**Comment by zerollzeng** [comment]
we don't support this feature now :-) building a trt engine require running all kernel on a device and choosing the fastest kernel. so it needs to be built on the actual device.

**Comment by ttyio** [comment]
Closing since no activatity for more than 3 weeks, thanks!
