### ISSUE TITLE
Python 3.8 No module named 'tensorrt' 

### ISSUE THREAD

**Issue by BjornS98** [NVIDIA/TensorRT#1811]
Hey Everyone!

I have some problems with my **jetson nano.**
I want to install TensorRT for python 3.8, but I don't find anything that works. 
- pip3 install nvidia-tensorrt , apt-get didn't work(it installed it on python 3.6) even evreything is linked to python 3.8
Anybody got some tips that could help?

(LOG)
yptf@yptf-desktop:~$ ls -la /usr/lib/python3/dist-packages/tensorrt
ls: cannot access '/usr/lib/python3/dist-packages/tensorrt': No such file or directory
yptf@yptf-desktop:~$ ls -la /usr/lib/python3.8/dist-packages/tensorrt
ls: cannot access '/usr/lib/python3.8/dist-packages/tensorrt': No such file or directory
yptf@yptf-desktop:~$ ls -la /usr/lib/python3.6/dist-packages/tensorrt
total 3316
drwxr-xr-x 3 root root    4096 Feb 21 16:28 .
drwxr-xr-x 9 root root    4096 Aug 13  2021 ..
-rw-r--r-- 1 root root    5746 Jun 26  2021 __init__.py
drwxr-xr-x 2 root root    4096 Feb 21 16:28 __pycache__
-rw-r--r-- 1 root root 3373008 Jun 26  2021 tensorrt.so
yptf@yptf-desktop:~$ 

I also looked ad python bindings, need to give that a try.

**Comment by BjornS98** [comment]
Default python is 3.6 and Im trying to use 3.7, also the binding didn't work

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-debian

**Comment by BjornS98** [comment]
It's a Jetson Nano, jetpack SDK which comes installed with TensorRT, the problem it's installed under python3.6 dist-packages, and I want to use it in python >3.6

**Comment by zerollzeng** [comment]
Oh Sry I miss the platform, you can't upgrade the python version in this case

**Comment by zerollzeng** [comment]
An alternative is to create the python binding by yourself with c++ API, e.g. with pybind11.  perhaps you can try my project :-) you can compile it with python 3.8 see https://github.com/zerollzeng/tiny-tensorrt

**Comment by BjornS98** [comment]
I need Tensorrt for torch2rt, will it work with your project?

**Comment by zerollzeng** [comment]
@BjornS98 https://github.com/NVIDIA/TensorRT/tree/main/python you should be able to build the python binding on your own since TRT 8.0

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
