### ISSUE TITLE
tensorrt profile wrong when try to convert onnx to trt engine

### ISSUE THREAD

**Issue by superhg** [NVIDIA/TensorRT#1812]
## Description

when convert onnx to trt engine wiht dynamic inputs shapes, an error occured as below:

it seems that profile is not correctly added

`[02/22/2022-03:35:30] [TRT] [E] 4: [network.cpp::validate::2948] Error Code 4: Internal Error (inputs:0: dynamic input is missing dimensions in profile 0.)
[02/22/2022-03:35:30] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )`

## Environment

**TensorRT Version**: 8.2.3
**NVIDIA GPU**:  TianX
**NVIDIA Driver Version**: 
**CUDA Version**: 7.6.5
**CUDNN Version**: 8.0.2
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**:  3.7
**Tensorflow Version (if applicable)**:  tensorflow-gpu 1.14
**PyTorch Version (if applicable)**: None
**Baremetal or Container (if so, version)**: None

## Relevant Files

`from builtins import print
import os
import tensorrt as trt

ONNX_SIM_MODEL_PATH = 'onnx.onnx'
TENSORRT_ENGINE_PATH_PY = './tmp/engine'

def build_engine(onnx_file_path, engine_file_path, flop=16):
    trt_logger = trt.Logger(trt.Logger.VERBOSE)  # trt.Logger.ERROR
    builder = trt.Builder(trt_logger)
    network = builder.create_network(
        1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    )
    
    parser = trt.OnnxParser(network, trt_logger)
    # parse ONNX
    with open(onnx_file_path, 'rb') as model:
        if not parser.parse(model.read()):
            print('ERROR: Failed to parse the ONNX file.')
            for error in range(parser.num_errors):
                print(parser.get_error(error))
            return None
    print("Completed parsing ONNX file")
    # builder.max_workspace_size = 2 << 30
    # default = 1 for fixed batch size
    builder.max_batch_size = 1
    # set mixed flop computation for the best performance
    # if builder.platform_has_fast_fp16 and flop == 16:
    #     builder.fp16_mode = True

    if os.path.isfile(engine_file_path):
        try:
            os.remove(engine_file_path)
        except Exception:
            print("Cannot remove existing file: ",
                engine_file_path)

    print("Creating Tensorrt Engine")

    print(network.get_input(0).name)
    print(network.get_input(1).name)
    print(network.get_input(2).name)
    print(network.get_input(3).name)
    print(network.num_inputs)
    print(network.num_outputs)

    profile = builder.create_optimization_profile()

    profile.set_shape_input(network.get_input(0).name, min=[1, 3], opt=[1, 57], max=[1, 100])     
    profile.set_shape_input(network.get_input(1).name, min=[1], opt=[1], max=[1]) 

    config = builder.create_builder_config()
    # config.set_tactic_sources(1 << int(trt.TacticSource.CUBLAS))
    config.max_workspace_size = 8 * 1 << 30
    # config.set_flag(trt.BuilderFlag.FP16)
    # config.add_optimization_profile(profile2)
    config.add_optimization_profile(profile)

    engine = builder.build_serialized_network(network, config)
    print(engine)
    with open(engine_file_path, "wb") as f:
        f.write(engine)
    print("Serialized Engine Saved at: ", engine_file_path)
    return engine

if __name__ == "__main__":    
    build_engine(ONNX_SIM_MODEL_PATH, TENSORRT_ENGINE_PATH_PY)`

## Steps To Reproduce

python run.py   # code as above

**Comment by joan126** [comment]
@ttyio please help to see this issue,  my network has three inputs, then how to use profile to set dynamic shapes?

**Comment by ttyio** [comment]
@superhg  @joan126 

we have to call `profile.set_shape` for each of the input and here is sample code
https://github.com/NVIDIA/TensorRT/blob/main/demo/BERT/builder.py#L367

**Comment by ttyio** [comment]
Closing since no activation for more than 3 weeks. please reopen if you still have question, thanks!
