### ISSUE TITLE
TRT add_constant does not support BOOL type

### ISSUE THREAD

**Issue by frank-wei** [NVIDIA/TensorRT#1815]
Hi, TRT team,

I have a question on why BOOL type is not supported on add_constant API? Do you have plan to support it? I'd like to use the output in the next layer which is add_select(cond, x, y) where cond must be BOOL type.

**Comment by ttyio** [comment]
@frank-wei , 
`bool` is new added type when we add support for `lstm`, so there is still some limitation that we are working on.

Could you WAR this by using `addUnary` + `kSIGN` , and then feed into `addSelect`? thanks!

**Comment by frank-wei** [comment]
> kSIGN

@ttyio , I do not think it works. Here is the situation:
cond1_bool #constant torch tensor with bool type
cond1_float = cond1_bool.to(torch.float)
cond1 = add_constant(cond1_float)
output1 = add_unary(cond1, kSIGN)  #output1 is still float
add_select(output1, if_val, else_val) #here the output1 needs to be BOOL type. So we need to cast the output1 to BOOL type explicitly
So far, I do not find any way to do the casting.

**Comment by ttyio** [comment]
@frank-wei 

hmmm, you are right, `sign` output is not bool. what about `elementwise`, some of the elementwise op outputs bool

    cond1_bool = add_elementwise(kAND，kEQUAL，kGREATER，kLESS，kOR，kXOR)
    add_select(cond1_bool, if_val, else_val)

thanks!

**Comment by frank-wei** [comment]
@ttyio 
Thanks for the suggestion. The elementwise op like logic may be useful but their input are restricted to bool:
Operations kAND, kOR, and kXOR must have inputs of [DataType](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29) kBOOL.
Our situation is inputs are all float/int but we want to generate bool which is impossible here.

**Comment by ttyio** [comment]
Sorry @frank-wei for the delay response, Have you tried the `kGREATER/kLESS ` ? it support both float and int32 input, also produce bool output. Thanks!

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
