### ISSUE TITLE
libnvinfer.so.8 error while running sampleMNIST sample

### ISSUE THREAD

**Issue by FraPochetti** [NVIDIA/TensorRT#1817]
Hi,
I have just installed `TensorRT-8.4.0.6` and I can't seem to be able to run the sampleMNIST example.
Here the detailed info:
* `uname -a`: 
```
Linux ip-<my ip> 5.4.0-1066-aws #69~18.04.1-Ubuntu SMP Wed Feb 9 15:36:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
* CUDA: 10.2 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1206519/155885725-f413070b-bf8d-44d9-ab1a-7f864dc176ee.png">

* cudNN: 8.3 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1206519/155885752-484092cc-127f-4d15-9a48-815ec3f86e2b.png">

Here what I have added to `~/.bashrc`
```
# set env for TensorRT
export TENSORRT_DIR=$/home/ubuntu/TensorRT-8.4.0.6
export LD_LIBRARY_PATH=$TENSORRT_DIR/lib:$TENSORRT_DIR
```
Here what I have added to `~/.profile`
```
# set PATH for cuda 10.2 installation
if [ -d "/usr/local/cuda-10.2/bin/" ]; then
    export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
fi
```
Here what my `TensorRT-8.4.0.6` looks like
![image](https://user-images.githubusercontent.com/1206519/155885901-17962395-2023-4b0c-820e-9f1d70225d1c.png)

I have already built the sample, so now when I execute `make` from the directory I get the following
![image](https://user-images.githubusercontent.com/1206519/155885992-c46b366d-e5bb-4173-8a11-98c45bc55b9c.png)
as a result, a `sample_mnist` file has been created inside `/home/ubuntu/TensorRT-8.4.0.6/bin`.
Inside the `/home/ubuntu/TensorRT-8.4.0.6/samples/sampleMNIST` I have created a `mnist` folder with the requested images
![image](https://user-images.githubusercontent.com/1206519/155886106-8f01b406-5668-4237-b8ab-8fa682e87303.png)

How do I execute the sample now?
This is what I tried from within the `/home/ubuntu/TensorRT-8.4.0.6/bin` directory
`./sample_mnist --datadir=../samples/sampleMNIST/mnist --fp16`
which raises 
```
./sample_mnist: error while loading shared libraries: libnvinfer.so.8: cannot open shared object file: No such file or directory
```
![image](https://user-images.githubusercontent.com/1206519/155886196-ff3a58e2-8801-4bc2-8fea-98ae4c76c73f.png)

Is this the right way to run the test sample?
If yes, am I just missing something super silly with PATHs?

**Comment by zerollzeng** [comment]
What does your LD_LIBRARY_PATH look like?

**Comment by FraPochetti** [comment]
Thanks a lot for the prompt reply!
Here it is: 
```
> echo $LD_LIBRARY_PATH
> $/home/ubuntu/TensorRT-8.4.0.6/lib:$/home/ubuntu/TensorRT-8.4.0.6
```

**Comment by FraPochetti** [comment]
Inside `/home/ubuntu/TensorRT-8.4.0.6/lib` there is indeed `libnvinfer.so.8`
![image](https://user-images.githubusercontent.com/1206519/155887342-7bcdb6f4-b09e-4b03-b7a1-4a4987999a7e.png)

**Comment by FraPochetti** [comment]
Alright, apparently I had to append `/home/ubuntu/TensorRT-8.4.0.6/lib` to `LD_LIBRARY_PATH `.
Now it looks like this 
```
$/home/ubuntu/TensorRT-8.4.0.6/lib:$/home/ubuntu/TensorRT-8.4.0.6:/home/ubuntu/TensorRT-8.4.0.6/lib
```
I think the first part is actually not needed, e.g. I am repeating `/home/ubuntu/TensorRT-8.4.0.6/lib` twice.

Anyway, thanks for the input!

**Comment by STAROFWIND** [comment]
I have a error like :  error while loading shared libraries: libnvinfer.so.8: cannot open shared object file: No such file or directory. 
I added to ./bashrc like you and LD_LIBRARY_PATH look like: /home/ducnm/Downloads/TensorRT-8.4.0.6/lib:$/home/ducnm/Downloads/TensorRT-8.4.0.6:$/home/ducnm/Downloads/TensorRT-8.4.0.6/lib 
But the error still there. any support ? 
Thank you so much

**Comment by HyeonseopLim** [comment]
> I have a error like : error while loading shared libraries: libnvinfer.so.8: cannot open shared object file: No such file or directory. I added to ./bashrc like you and LD_LIBRARY_PATH look like: /home/ducnm/Downloads/TensorRT-8.4.0.6/lib:$/home/ducnm/Downloads/TensorRT-8.4.0.6:$/home/ducnm/Downloads/TensorRT-8.4.0.6/lib But the error still there. any support ? Thank you so much

me as well.

**Comment by Turing47** [comment]
I have the same problem but the **_libnvinfer_plugin.so.8_** is in the “/TensorRT-8.5.3.1/targets/x86_64-linux-gnu/lib”
