### ISSUE TITLE
Is it possible to install trt6 on jetson nano?

### ISSUE THREAD

**Issue by stiv-yakovenko** [NVIDIA/TensorRT#182]
If yes, where can I get distribution?

**Comment by rmccorm4** [comment]
Hi @stiv-yakovenko,

Hello,

JetPack 4.3 Developer Preview, which is packaged with TRT6 is available as a beta here: https://developer.nvidia.com/jetpack-4_3_DP

Stay tuned for the official production release of Jetpack 4.3.
