### ISSUE TITLE
Error Code 2: Internal Error (Assertion mergedNbAxes - channelAxis <= 3 failed

### ISSUE THREAD

**Issue by hjchen2** [NVIDIA/TensorRT#1821]
I got the above error when I tried to use TensorRT. Below is a minimal reproduction code, it will report the same error in either version 8.4 or 8.0. Please help guide how to solve this problem, thanks very much.
 
```python
import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
builder = trt.Builder(TRT_LOGGER)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

network = builder.create_network(EXPLICIT_BATCH)

input0 = network.add_input(name="input0", dtype=trt.float32, shape=(1, 256, 16, 16))
input1 = network.add_input(name="input1", dtype=trt.float32, shape=(1, 256, 1, 1))
input2 = network.add_input(name="input2", dtype=trt.float32, shape=(1, 256, 1, 1))

slice = network.add_slice(input0, start=(0, 0, 1, 1), shape=(1, 256, 14, 14), stride=(1, 1, 1, 1))
mul0 = network.add_elementwise(slice.get_output(0), input1, op=trt.ElementWiseOperation.PROD)
mul1 = network.add_elementwise(mul0.get_output(0), input2, op=trt.ElementWiseOperation.PROD)

network.mark_output(mul1.get_output(0))

config = builder.create_builder_config()
#config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 24) # 16 MiB
engine = builder.build_serialized_network(network, config)
```

**Comment by 201419** [comment]
I had a similar problem, is there anything new ?

**Comment by hjchen2** [comment]
> I had a similar problem, is there anything new ?

I have tried adding an identity layer after the slice operation, which can bypass this error.
```python
slice = network.add_slice(input0, start=(0, 0, 1, 1), shape=(1, 256, 14, 14), stride=(1, 1, 1, 1))
slice = network.add_identity(slice.get_output(0))
```

**Comment by 201419** [comment]
> > I had a similar problem, is there anything new ?
> 
> I have tried adding an identity layer after the slice operation, which can bypass this error.
> 
> ```python
> slice = network.add_slice(input0, start=(0, 0, 1, 1), shape=(1, 256, 14, 14), stride=(1, 1, 1, 1))
> slice = network.add_identity(slice.get_output(0))
> ```

It works for me. Thank you very much!

**Comment by galagam** [comment]
Was not able to reproduce with TRT 8.4, CUDA 11.4, Ubuntu 20.04. 
Please provide more details on your environment in order to allow us to reproduce.

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
