### ISSUE TITLE
How does Tensorrt implement specific layers using FP16 precision

### ISSUE THREAD

**Issue by zhaohb** [NVIDIA/TensorRT#1823]
Now I want the FC layer to use FP16 precision using the following code, others use FP32 precision：
```shell
......
        for i in range(network.num_layers):
            if network.get_layer(i).type == trt.LayerType.FULLY_CONNECTED :
                network.get_layer(i).precision = trt.DataType.HALF
                network.get_layer(i).set_output_type(0, trt.DataType.HALF)
......
```
but I get that error:
```shell
......
[03/02/2022-08:37:37] [TRT] [E] 4: [network.cpp::validate::2787] Error Code 4: Internal Error (fp16 precision has been set for a layer or layer output, but fp16 is not configured in the builder)
......
```

if I set trt.BuilderFlag.FP16 in builder, fix it, but I do not know this will achieve the effect I want.

thank you very much.

**Comment by zhaohb** [comment]
who can help me?

**Comment by AllentDan** [comment]
Same here. Wonder for some operations that cannot use FP16, overflow for example, what could we do to make them FP32 while keeping others FP16.

**Comment by nvpohanh** [comment]
First of all, you must enable trt.BuilderFlag.FP16 in builder config in order to use FP16 for any layer.

If you want to keep some layers to FP32, you can then set the layer precisions and set OBEY_PRECISION_CONSTRAINTS or PREFER_PRECISION_CONSTRAINTS in builder config to achieve this.

**Comment by nvpohanh** [comment]
closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Comment by atztao** [comment]
The same issue.

**Comment by Yebi1837** [comment]
hi @nvpohanh , I am facing the same issue. 
So assuming I have a network with 3 layers: layer1->layer2->layer3, and I want to convert to TRT with layer2 in `fp32`, while layer1 and layer3 in `fp16`.
When originally loaded from ONNX, they are by default all in fp32 precision. I guess I need to:
1. enable trt.BuilderFlag.FP16 in builder config
2. set fp16 for layer1 and layer3
3. set OBEY_PRECISION_CONSTRAINTS or PREFER_PRECISION_CONSTRAINTS in builder config
then build the engine. 
is this understanding correct?

**Comment by atztao** [comment]
> * set fp16 for layer1 and layer3

Yeah, it also confused me, i tried, but it not work, the layer2 also convert to fp16.

**Comment by Yebi1837** [comment]
hi @atztao I think I figured this out.
in addition to 
> set fp16 for layer1 and layer3
We also need to 
**set fp32 for layer2**
then I am able to generate mix-precision engine. 
basically you need to make sure `layer.precision_is_set` flag is true, then TensorRT will honor the precision.
