### ISSUE TITLE
How to use TF32 in Tensorrt

### ISSUE THREAD

**Issue by zhaohb** [NVIDIA/TensorRT#1824]
## Description

Now I have A30 card, so I want to try to use TF32 precision, so I added config.set_flag (trt.builderFlag.TF32) setting when converting to plan file, I used perf_analyzer tool to pressure, but compared to FP32,  there is no difference between TF32 and FP32 performance

who can help me? thank you very much.

**Comment by pranavm-nvidia** [comment]
TF32 is on by default. Is it possible you're comparing TF32 vs. TF32 instead of vs. FP32?

**Comment by zhaohb** [comment]
@pranavm-nvidia  ok, thank you very much
