### ISSUE TITLE
How to update TensorRT to 8.2 in jetson AGX with jetpack4.6

### ISSUE THREAD

**Issue by oym1994** [NVIDIA/TensorRT#1825]
Hi, thanks for your great attention.
The tensorRT version in my AGX is 8.0. Unfortunately, some operations(such as einsum) are not supported by this tensorRT。 According to the forums, TensorRT8.2 is required and successfully tested in my X86 computer. My question is how can I updade the tensorRT version to 8.2 in AGX ? Or is it impossible to update for the tensorRT is binded with the Jetpack?
Thanks for any good advice!

**Comment by wywywy01** [comment]
cool problem

**Comment by d57montes** [comment]
In case you were still wondering, TensorRT is binded with JetPack so you cannot upgrade TRT without waiting for a new release of JP; however, JP 4.6.1 was released today and it includes TRT 8.2.

**Comment by mohammadhaqqi** [comment]
> In case you were still wondering, TensorRT is binded with JetPack so you cannot upgrade TRT without waiting for a new release of JP; however, JP 4.6.1 was released today and it includes TRT 8.2.

How can I upgrade to this version JP 4.6.1?

**Comment by d57montes** [comment]
One way is with the Nvidia SDK Manager.
