### ISSUE TITLE
[TensorRT] ERROR: Network must have at least one output

### ISSUE THREAD

**Issue by marooncn** [NVIDIA/TensorRT#183]
Hi,  I try to convert my .onnx model to .trt model using tensorrt, my script is:

```
import tensorrt as trt

def ONNX_build_engine(onnx_file_path, engine_file_path):
    G_LOGGER = trt.Logger(trt.Logger.WARNING)
    with trt.Builder(G_LOGGER) as builder, builder.create_network() as network, trt.OnnxParser(network, G_LOGGER) as parser:
        builder.max_batch_size = 16
        builder.max_workspace_size = 1 << 20

        print('Loading ONNX file from path {}...'.format(onnx_file_path))
        with open(onnx_file_path, 'rb') as model:
            print('Beginning ONNX file parsing')
            parser.parse(model.read())
        print('Completed parsing of ONNX file')

        print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
        engine = builder.build_cuda_engine(network)
        print("Completed creating Engine")

        with open(engine_file_path, "wb") as f:
            f.write(engine.serialize())
        return engine

ONNX_build_engine('./BiSeNet.onnx', './BiSeNet.trt')
```
I have tested in my two desktops, one configue:

> cuda 10.0
> pytorch1.3
> torch 5.0.6.6

the other configure:

> cuda 10.1
> pytorch1.3
> torch6.0.1.5

Both have the same error. there is an error:

> Loading ONNX file from path ./BiSeNet_simplifier.onnx...
> Beginning ONNX file parsing
> Completed parsing of ONNX file
> Building an engine from file ./BiSeNet_simplifier.onnx; this may take a while...
> [TensorRT] ERROR: Network must have at least one output
> Completed creating Engine
> Traceback (most recent call last):
>   File "onnx2trt.py", line 31, in <module>
>     ONNX_build_engine('./BiSeNet_simplifier.onnx', './BiSeNet.trt')
>   File "onnx2trt.py", line 28, in ONNX_build_engine
>     f.write(engine.serialize())
> AttributeError: 'NoneType' object has no attribute 'serialize'

The .onnx file is converted by _torch.onnx.export_ fcn, it seems right.
```
import torch
from model.build_BiSeNet import BiSeNet

model = BiSeNet(13, 'resnet18').eval()  # .cuda().half().eval()
model.load_state_dict(torch.load('./checkpoints_18_sgd/best_dice_loss_13_class.pth'))
x = torch.ones((1, 3, 720, 960))  # .cuda().half()
output_names = ["output"]
onnx_model = torch.onnx._export(model, x, "BiSeNet.onnx", verbose=False, output_names=output_names, export_params=True) #,  keep_initializers_as_inputs=True)
```

**Comment by rmccorm4** [comment]
Hi @marooncn,

There's probably a way to fix this in the PyTorch code so that the ONNX parser recognizes the output, but I'm not sure how to do that off the top of my head - maybe someone else can chime in on this.

However, I think you can fix this on the TensorRT side with something like this:

```python
last_layer = network.get_layer(network.num_layers - 1)
# Check if last layer recognizes it's output
if not last_layer.get_output(0):
    # If not, then mark the output using TensorRT API
    network.mark_output(network.get_layer(network.num_layers - 1).get_output(0))
```

You can see similar code being used in this issue: https://github.com/NVIDIA/tensorrt-inference-server/issues/76

**Comment by marooncn** [comment]
Hi @rmccorm4 ,
It fails, the error is

> python3: ../builder/Network.cpp:863: virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed.
> Aborted

**Comment by marooncn** [comment]
I also test on pytorch1.1.0, the error is the same as the original however. 

> AttributeError: 'NoneType' object has no attribute 'serialize'

It's so weird.

**Comment by rmccorm4** [comment]
> Assertion `layerIndex >= 0' failed.

This means you called `network.get_layer(num)` where `num < 0`. Which probably means that `network.num_layers` returned 0, so `network.num_layers - 1` returned -1.

Did you do these steps **after** parsing?
```
# parser.parse() is what populates the network object with information from the model file
 with open(onnx_file_path, 'rb') as model:
            print('Beginning ONNX file parsing')
            parser.parse(model.read())

last_layer = network.get_layer(network.num_layers - 1)
# Check if last layer recognizes it's output
if not last_layer.get_output(0):
    # If not, then mark the output using TensorRT API
    network.mark_output(last_layer.get_output(0))
```

**Comment by marooncn** [comment]
Yes, I added it after parsing.  Maybe tensorrt is not installed successfully on Pytorch1.3 desktop. But for pytorch1.1, the error is still as the original.

**Comment by rmccorm4** [comment]
Can you post the full error for pytorch 1.1?

The NoneType error on calling engine.deserialize() is usually because something went wrong before/during creating the engine, it isnt specific to any particular issue.

**Comment by marooncn** [comment]
Yes, all of output message is:

> Loading ONNX file from path ./BiSeNet/BiSeNet.onnx...
> Beginning ONNX file parsing
> Completed parsing of ONNX file
> Building an engine from file ./BiSeNet/BiSeNet.onnx; this may take a while...
> [TensorRT] ERROR: Network must have at least one output
> Completed creating Engine
> Traceback (most recent call last):
>   File "test.py", line 35, in <module>
>     ONNX_build_engine('./BiSeNet/BiSeNet.onnx', './BiSeNet.trt')
>   File "test.py", line 32, in ONNX_build_engine
>     f.write(engine.serialize())
> AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by marooncn** [comment]
Yes, all of the output are
> Loading ONNX file from path ./BiSeNet/BiSeNet.onnx...
> Beginning ONNX file parsing
> Completed parsing of ONNX file
> Building an engine from file ./BiSeNet/BiSeNet.onnx; this may take a while...
> [TensorRT] ERROR: Network must have at least one output
> Completed creating Engine
> Traceback (most recent call last):
>   File "test.py", line 35, in <module>
>     ONNX_build_engine('./BiSeNet/BiSeNet.onnx', './BiSeNet.trt')
>   File "test.py", line 32, in ONNX_build_engine
>     f.write(engine.serialize())
> AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by marooncn** [comment]
just add

> last_layer = network.get_layer(network.num_layers - 1)
> network.mark_output(last_layer.get_output(0))

it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.

**Comment by rmccorm4** [comment]
Yeah, I just added the `if` statement so you don't get an error for a model that already recognizes it's output.

Closing.

**Comment by RizhaoCai** [comment]
> just add
> 
> > last_layer = network.get_layer(network.num_layers - 1)
> > network.mark_output(last_layer.get_output(0))
> 
> it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.



> Hi @marooncn,
> 
> There's probably a way to fix this in the PyTorch code so that the ONNX parser recognizes the output, but I'm not sure how to do that off the top of my head - maybe someone else can chime in on this.
> 
> However, I think you can fix this on the TensorRT side with something like this:
> 
> ```python
> ...
> last_layer = network.get_layer(network.num_layers - 1)
> # Check if last layer recognizes it's output
> if not last_layer.get_output(0):
>     # If not, then mark the output using TensorRT API
>     network.mark_output(last_layer.get_output(0))
> ```
> 
> You can see similar code being used in this issue: [NVIDIA/triton-inference-server#76](https://github.com/NVIDIA/triton-inference-server/issues/76)
> 
> Let me know if this or something similar fixes your issue.

Hi, @rmccorm4 

Thanks for your solution. It works for many cases.
However, when my network has two outputs, this seems not work.

For examples
class Net(torch.nn.Module):
    ....
    def forward(x):
        ....
        return output1, output2

In this case, using last_layer.get_output(0) is OK. But if I put last_layer.get_output(1), and OutOfIndex error will occur. 
And I find that the using 
    `second_last_layer = network.get_layer(network.num_layers - 2)`
    `second_last_layer.get_output(0)`
do not give me what I want.

**Comment by giussepi** [comment]
Hi @RizhaoCai 

I just had the same issue with TensorRT 7.0. The solution, as mentioned in the [documentaiton](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#import_onnx_python),  was creating the network using the EXPLICIT_BATCH flag:

``` python
explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
network = builder.create_network(explicit_batch)
```

**Comment by Captain1986** [comment]
> just add
> 
> > last_layer = network.get_layer(network.num_layers - 1)
> > network.mark_output(last_layer.get_output(0))
> 
> it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.

but I meet network.num_layers equals to 0 bug : virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed
any suggestion is welcome

**Comment by oleksii-udod** [comment]
> > just add
> > > last_layer = network.get_layer(network.num_layers - 1)
> > > network.mark_output(last_layer.get_output(0))
> > 
> > 
> > it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.
> 
> but I meet network.num_layers equals to 0 bug : virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed
> any suggestion is welcome

https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-657673563 helped me with the similar issue.

**Comment by Captain1986** [comment]
> > > just add
> > > > last_layer = network.get_layer(network.num_layers - 1)
> > > > network.mark_output(last_layer.get_output(0))
> > > 
> > > 
> > > it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.
> > 
> > 
> > but I meet network.num_layers equals to 0 bug : virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed
> > any suggestion is welcome
> 
> [#183 (comment)](https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-657673563) helped me with the similar issue.

So, I need to upgrade my TensorRT 6.0.1.5 to TensoeRT 7?

**Comment by oleksii-udod** [comment]
> > > > just add
> > > > > last_layer = network.get_layer(network.num_layers - 1)
> > > > > network.mark_output(last_layer.get_output(0))
> > > > 
> > > > 
> > > > it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.
> > > 
> > > 
> > > but I meet network.num_layers equals to 0 bug : virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed
> > > any suggestion is welcome
> > 
> > 
> > [#183 (comment)](https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-657673563) helped me with the similar issue.
> 
> So, I need to upgrade my TensorRT 6.0.1.5 to TensoeRT 7?

Not sure, I had the same issue with TensorRT 7. Maybe try  @giussepi solution with TensorRT 6 first.

**Comment by Darshcg** [comment]
Hi,
I am converting my Custom model from ONNX to TRT.

I am using the below code to convert from ONNX to TRT:

```
`import tensorrt as trt
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
trt_runtime = trt.Runtime(TRT_LOGGER)
def build_engine(onnx_path, shape = [1,1,224,224]):
with trt.Builder(TRT_LOGGER) as builder, builder.create_network(1) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
builder.max_workspace_size = (256 << 20)
with open(onnx_path, ‘rb’) as model:
parser.parse(model.read())
network.get_input(0).shape = shape
engine = builder.build_cuda_engine(network)
return engine
def save_engine(engine, file_name):
buf = engine.serialize()def load_engine(trt_runtime, plan_path):
with open(engine_path, ‘rb’) as f:
engine_data = f.read()
def load_engine(trt_runtime, plan_path):
with open(engine_path, ‘rb’) as f:
engine_data = f.read()
engine = trt_runtime.deserialize_cuda_engine(engine_data)
return engine
from onnx import ModelProto

engine_name = “xyz.plan”
onnx_path = “xyz.onnx”

model = ModelProto()
with open(onnx_path, “rb”) as f:
model.ParseFromString(f.read())

batch_size = 1

d0 = model.graph.input[0].type.tensor_type.shape.dim[1].dim_value
d1 = model.graph.input[0].type.tensor_type.shape.dim[2].dim_value
d2 = model.graph.input[0].type.tensor_type.shape.dim[3].dim_value
shape = [batch_size , d0, d1 ,d2]

engine = build_engine(onnx_path)
save_engine(engine, engine_name) `

```
The error I am facing is:
[TensorRT] ERROR: Network must have at least one output [TensorRT] ERROR: Network validation failed

TensorRT Version : 7.0.0-1.
Cuda Version : 10.2

May I know how to get rid of this Issue? would be a great help!

Thanks

**Comment by Abraham423** [comment]
I got exactly the same error, suggestions from 
https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-547793843
 and 
https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-657673563
or both won't help at all. I have TensorRT-6.0.1.5 + Cuda10.1 installed, any other suggestions will be appreciate ~

**Comment by giussepi** [comment]
> I got exactly the same error, suggestions from
> [#183 (comment)](https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-547793843)
> and
> [#183 (comment)](https://github.com/NVIDIA/TensorRT/issues/183#issuecomment-657673563)
> or both won't help at all. I have TensorRT-6.0.1.5 + Cuda10.1 installed, any other suggestions will be appreciate ~

@Abraham423 Try using tensorRT >= 7.1, that version got rid of most the issues I had when working with tensorRT

**Comment by theharshwardhan** [comment]
> just add
> 
> > last_layer = network.get_layer(network.num_layers - 1)
> > network.mark_output(last_layer.get_output(0))
> 
> it will work. It's a necessary procedure to convert successfully, I'm curious why most tutorials don't mention it.

Doesn't work for me. I'm getting network.num_layers = 0. Why?

**Comment by theharshwardhan** [comment]
> > Assertion `layerIndex >= 0' failed.
> 
> This means you called `network.get_layer(num)` where `num < 0`. Which probably means that `network.num_layers` returned 0, so `network.get_layer(network.num_layers - 1) == network.get_layer(-1)`.
> 
> @marooncn Did you do these steps **after** parsing?
> 
> ```python
> # parser.parse() populates the network object with information from the model file
> with open(onnx_file_path, 'rb') as model:
>     parser.parse(model.read())
> 
> last_layer = network.get_layer(network.num_layers - 1)
> # Check if last layer recognizes it's output
> if not last_layer.get_output(0):
>     # If not, then mark the output using TensorRT API
>     network.mark_output(last_layer.get_output(0))
> ```

I have the exact same issue and this solution doesn't work. Why do I get network.num_layers = 0?

**Comment by stardust2602** [comment]
> Hi @rmccorm4 ,
> It fails, the error is
> 
> > python3: ../builder/Network.cpp:863: virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed.
> > Aborted

Hi, have you been able to solve this error ? I also get this error when convert from ONNX to TRT
My config is:

TensorRT 7.0.0.11
CUDA 10.0
Tensorflow 1.15.3
onnx 1.8.1
onnx-simplifier 0.2.9
tf2onnx 1.8.5
