### ISSUE TITLE
How to make conv(merged bn) + relu + add work in explict quantization mode

### ISSUE THREAD

**Issue by Oldpan** [NVIDIA/TensorRT#1831]
## Description
When I used pytorch-quantization-tool to export a QDQ model:

![image](https://user-images.githubusercontent.com/9389127/156538211-67be2b8d-985e-4338-a089-7787457f504d.png)

And TensorRT can fuse conv + relu + add, and this is engine draw:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/9389127/156538138-b3ff06b0-8f99-4c4e-b7f5-4bf74f5ea123.png">

But when I change to use torch.fx and fx2trt to export a model:
![image](https://user-images.githubusercontent.com/9389127/156538394-e5360429-a9d2-4ea2-ba8d-ae3be6b4c59e.png)
tensorrt cant fuse conv and relu + add :
![image](https://user-images.githubusercontent.com/9389127/156538526-b9aa8c2f-e48c-4932-8e13-17d94c48cf19.png)

I compared the first onnx model and second fx model, and removed the QDQ op in fx model:
![image](https://user-images.githubusercontent.com/9389127/156538951-6591c73a-29ff-4d32-ae1d-38fc094683db.png)

Finally the engine fx2trt produced is not working and the graph is not right (seems a tensorrt bug?), the precision is also none.
Is there a way I can change the fx model graph(to change or move qdq op or something) to make conv + relu + add work in tensorrt engine? Thanks

## Environment

**TensorRT Version**:  TensorRT 8.0.1.6
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by wywywy01** [comment]
hi，excuse me;  i want to known how to draw engine node like above?

**Comment by zhiqwang** [comment]
FYI @wywywy01 , fx2trt previously provides a tool to draw the serialized engine node.

**Comment by Oldpan** [comment]
Change to TensorRT-8.2.3 solve this

**Comment by netaz** [comment]
@wywywy01 to draw engine graphs you can use trex -
  https://github.com/NVIDIA/TensorRT/tree/main/tools/experimental/trt-engine-explorer
