### ISSUE TITLE
Converting yolov5s.onnx to int8 engine give me lower mAP results.

### ISSUE THREAD

**Issue by matinhosseiny** [NVIDIA/TensorRT#1834]
## Description
I am converting the yolov5s ONNX model to a Tensorrt engine. After conversion to fp32 engine the mAP does not drop  (mAP@50 = 0.56) but when I convert it to int8 the mAP drops (mAP@50 = 0.48). I am using the following part of the code in addition to the fp32 provided by yolov5.
if do_int_8:
      config.set_flag(trt.builder_flag.INT8)
      config.int8_calibrator = YOLOEntropyCalibrator(Image_dir,(640,640),'calib_%s.bin'%model_name)
      config.set_calibrator_profile(profile)
I am using https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/calibrator.py as calibrator and 
do inferencing with: https://github.com/ultralytics/yolov5/blob/master/val.py
the results are low for all the yolov5 versions.
I tested this on T4 with tensorrt 8.4 and Ubuntu 18.04 
could you please help me to improve my results?

Thanks

**Comment by zerollzeng** [comment]
Perhaps consider using QAT.

**Comment by galagam** [comment]
Depending on the specific model & weights, post training quantization may indeed lead to some accuracy loss. 
Please review the material on quantization aware training on [NVIDIA Developer blog](https://developer.nvidia.com/blog/achieving-fp32-accuracy-for-int8-inference-using-quantization-aware-training-with-tensorrt/).
