### ISSUE TITLE
Converting X4 SR model FAILED with OUT of MEM error.

### ISSUE THREAD

**Issue by ShiinaMitsuki** [NVIDIA/TensorRT#1836]
Hello, 
  Im trying to convert a super-resolution model from onnx to tensorrt, the model is from this paper [BasicVSR: The Search for Essential Components in Video Super-Resolution and Beyond](https://arxiv.org/pdf/2012.02181.pdf), and the pytorch implementation is from [Here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/models/backbones/sr_backbones/basicvsr_net.py#L15).
  I first convert the model from pytorch to onnx, using a input shape [N=1, T=5, C=3, H=1080, W=1920], the model is a X4 model, so , a output of shape [N=1, T=5, C=3, H=4320, W=7680] would be produced.
  The conversion from onnx to tenserrt always FAILED with Out of Mem error, even I tried using a 48G A6000 and a maximum workspace I can give(aka 40G or 48G). 
  
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/16696202/156956337-46a0982b-314c-4288-8a8d-237416362a87.png">
   
   I am aware of that Tensorrt is made totally for accelaration, BUT is it possible for Tensorrt making a conversion with some constraint? For example, a limited GPU Mem even if no optimization or accelaration at all. This model I mentioned above can run smoothly on a RTX Titan 24G GPU with pytorch fp16 mode, I wonder why it would failed converting to Tensorrt.
   Is there any suggestion ? THANKS.

**Comment by zerollzeng** [comment]
Can you paste trtexec verbose log here? maybe disable some tactic source will let you build the engine successfully

**Comment by galagam** [comment]
Closing due to lack of response from author.
