### ISSUE TITLE
can v100+ cuda11.1+ubuntu16.04 support the T5 inference?

### ISSUE THREAD

**Issue by 520jefferson** [NVIDIA/TensorRT#1838]
The readme say when i  want to support t5 inference, the cuda version should be 11.4. Can the cuda 11.1 and ubuntu 16.04 support T5 inference?  and which docker image should i use?

## Environment

**TensorRT Version: 8.2
**NVIDIA GPU: V100
Driver Version: 455.32.00    
CUDA Version: V11.1.105
**CUDNN Version：7
**Operating System:ubuntu 16.04

**Comment by ttyio** [comment]
Hello @520jefferson , we have not tested the 16.04, could you try 18.04 container? https://github.com/NVIDIA/TensorRT/tree/release/8.2#setting-up-the-build-environment
Thanks

**Comment by 520jefferson** [comment]
FT5.0 support t5 with cuda11.1.
https://github.com/NVIDIA/FasterTransformer/issues/202
