### ISSUE TITLE
Bert lost a lot of accuracy when using fp16

### ISSUE THREAD

**Issue by float123** [NVIDIA/TensorRT#1839]
## Description
hello！
I encountered a problem when I using nvonnxparser creating tensorrt engine，the bert model performs normally in the case of FP32，but when using FP16, the result is completely incorrect
The model is trained using pytorch's transform toolkit.
Has anyone noticed such problems and how to solve them?

## Environment

**TensorRT Version**: 8.2.3.4
**NVIDIA GPU**: 2080ti 
**NVIDIA Driver Version**: 465.27
**CUDA Version**: cuda10.2
**CUDNN Version**: 8.3.1.22
**Operating System**: centos7.9
**Python Version (if applicable)**: 3.6
**PyTorch Version (if applicable)**: 1.9.0

**Comment by ttyio** [comment]
closing old issues that is inactive for long time, thanks all!
