### ISSUE TITLE
ResizeNearestNeighbor is not supported in TensorRT 6.0

### ISSUE THREAD

**Issue by OblivionStaff** [NVIDIA/TensorRT#185]
In the TensorRT Release Note, the ResizeNearestNeighbor is added in the TensorFlow supported operators. But it is failed to parse a NHWC TensorFlow model as the ResizeNearestNeighbor operator is not supported yet. I test it in the docker image: tensorrt:19.10-py3 and the libraries in the TensorRT-6.0.1.5.Ubuntu-16.04.x86_64-gnu.cuda-10.0.cudnn7.6.

**Comment by rmccorm4** [comment]
Hi @OblivionStaff,

How are you parsing the model? I believe this op is supported for TF -> ONNX -> TensorRT

This PR supports the above on the TF -> ONNX side: https://github.com/onnx/tensorflow-onnx/pull/20

**Comment by OblivionStaff** [comment]
> Hi @OblivionStaff,
> 
> How are you parsing the model? I believe this op is supported for TF -> ONNX -> TensorRT
> 
> This PR supports the above on the TF -> ONNX side: [onnx/tensorflow-onnx#20](https://github.com/onnx/tensorflow-onnx/pull/20)

I used the UFF Parer in the Python API

**Comment by rmccorm4** [comment]
Can you try using the ONNX parser instead? You should be able to convert your model from TF -> ONNX using https://github.com/onnx/tensorflow-onnx/tree/master/tf2onnx.

**Comment by rmccorm4** [comment]
Happy to help!

@OblivionStaff If you have any useful code snippets or tips on how you used the ONNX parser for this, please share in case others run into a similar issue so they can have a reference!
