### ISSUE TITLE
Does cuda graph support plugins ? 

### ISSUE THREAD

**Issue by xhf1869** [NVIDIA/TensorRT#1856]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@xhf1869 , yes and you can experiment your model with plugin using `trtexec --useCudaGraph`, thanks

**Comment by xhf1869** [comment]
thinks
