### ISSUE TITLE
windows oos kRepHeaderSize wrong

### ISSUE THREAD

**Issue by laoxing797373** [NVIDIA/TensorRT#1858]
## Description
![image](https://user-images.githubusercontent.com/32096051/158381589-56ab2d87-c663-4658-b897-b90a152846f6.png)

version：7.2 8.2 on msbuild ALL_BUILD.vcxproj ，the same mistake occurred

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@laoxing797373 , TRT has no offcial windows build for OSS yet. Internally we did not this CMake for the windows build. We have some internal toolchain.

**Comment by laoxing797373** [comment]
@ttyio Thank you, how can I add a custom operator to the dll?
