### ISSUE TITLE
Parse onnx file, got "broadcast dimensions must be conformable"

### ISSUE THREAD

**Issue by luyi404** [NVIDIA/TensorRT#1870]
## Description

After quantization to my yolov5 model, I get a onnx file and a record of model's clip range.
And when I use tensorrt's python api to convert this onnx model to trt engine, when "parser.parse", I got error like: 

`RuntimeError: parse onnx failed:
In node 343 (parseGraph): INVALID_NODE: Invalid Node - Mul_1152
[graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 9: Internal Error (Mul_1152: broadcast dimensions must be conformable
)
`

## Environment

**TensorRT Version**: '8.0.1.6'
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: 450.51.05
**CUDA Version**: 11.0
**CUDNN Version**:  
**Operating System**: Ubuntu 18.04 (docker)
**Python Version (if applicable)**: 3.9.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.10.1
**Baremetal or Container (if so, version)**: 

## Relevant Files

The onnx file and the clip range json file in google drive:

https://drive.google.com/drive/folders/16l4WIcoXg9eJI9sTnf_jRxUdEjZDYucJ?usp=sharing

## Steps To Reproduce

The converted code(onnx2trt.py) I use to convert onnx to trt:

`
import onnx
import pycuda.autoinit # noqa F401
import tensorrt as trt
import torch
import json
import pycuda.driver as cuda
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import os
import numpy as np
import argparse

def onnx2trt(onnx_model,
             trt_path,
             batch_size=1,
             cali_batch=10,
             log_level=trt.Logger.ERROR,
             max_workspace_size=1 << 30,
             device_id=0,
             mode='int8',
             dynamic_range_file=None):
    if os.path.exists(trt_path):
        print(f'The "{trt_path}" exists. Remove it and continue.')
        os.remove(trt_path)

    device = torch.device('cuda:{}'.format(device_id))

    logger = trt.Logger(log_level)
    builder = trt.Builder(logger)
    EXPLICIT_BATCH = 1 << (int)(
        trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = builder.create_network(EXPLICIT_BATCH)

    parser = trt.OnnxParser(network, logger)

    with open(onnx_model, 'rb') as model:
        if not parser.parse(model.read()):   
            error_msgs = ''
            for error in range(parser.num_errors):
                error_msgs += f'{parser.get_error(error)}\n'
            raise RuntimeError(f'parse onnx failed:\n{error_msgs}')

    config = builder.create_builder_config()
    config.max_workspace_size = max_workspace_size

    if mode == 'int8':
        config.set_flag(trt.BuilderFlag.INT8)
        if dynamic_range_file:
            with open(dynamic_range_file, 'r') as f:
                dynamic_range = json.load(f)['tensorrt']['blob_range']

            for input_index in range(network.num_inputs):
                input_tensor = network.get_input(input_index)
                if input_tensor.name in dynamic_range:
                    amax = dynamic_range[input_tensor.name]
                    input_tensor.dynamic_range = (-amax, amax)
                    print(f'Set dynamic range of {input_tensor.name} as [{-amax}, {amax}]')

            for layer_index in range(network.num_layers):
                layer = network[layer_index]
                output_tensor = layer.get_output(0)
                if output_tensor.name in dynamic_range:
                    amax = dynamic_range[output_tensor.name]
                    output_tensor.dynamic_range = (-amax, amax)
                    print(f'Set dynamic range of {output_tensor.name} as [{-amax}, {amax}]')

    with torch.cuda.device(device):
        engine = builder.build_engine(network, config)

    with open(trt_path, mode='wb') as f:
        f.write(bytearray(engine.serialize()))
    return engine
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Onnx to tensorrt')
    parser.add_argument('--onnx-path', type=str, default=None)
    parser.add_argument('--trt-path', type=str, default=None)
    parser.add_argument('--mode', choices=['fp32', 'int8'], default='int8')
    parser.add_argument('--clip-range-file', type=str, default=None)
    parser.add_argument('--batch-size', type=int, default=10)
    parser.add_argument('--evaluate', action='store_true')
    parser.add_argument('--verbose', action='store_true')
    args = parser.parse_args()

    if args.onnx_path:
        onnx2trt(args.onnx_path,
                 trt_path=args.trt_path,
                 mode=args.mode,
                 batch_size=10,
                 cali_batch=10,
                 log_level=trt.Logger.VERBOSE if args.verbose else trt.Logger.ERROR,
                 dynamic_range_file=args.clip_range_file)

`

I run this code with 
`python onnx2trt.py --onnx mqbench_qmodel_deploy_model.onnx --trt yolov5.trt --clip mqbench_qmodel_clip_ranges.json `

Then, the output belike: 

`
Traceback (most recent call last):
  File "/root/xxx/onnx/xxx/application/xxx/onnx2trt.py", line 128, in <module>
    onnx2trt(args.onnx_path,
  File "/root/xxx/onnx/xxx/application/xxx/onnx2trt.py", line 47, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node 343 (parseGraph): INVALID_NODE: Invalid Node - Mul_1152
[graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 9: Internal Error (Mul_1152: broadcast dimensions must be conformable
)

`

**Comment by dav-ell** [comment]
Also seeing this error, but when using Torch-TensorRT to convert a model.

**Comment by ttyio** [comment]
@luyi404 , the error means that the `Mul_1152` has 2 inputs and the 2 inputs has different dims, they are not identical and also cannot use broadcast to make them equal. I tried onnxruntime, it also report similar error:

    onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from 
    /home/vincenth/trt/mqbench_qmodel_deploy_model.onnx failed:Node (Mul_1756) Op (Mul) [ShapeInferenceError] 
    Incompatible dimensions

Could you check if your ONNX model is correct? thanks

**Comment by luyi404** [comment]
@ttyio 
Hi, thanks for your reply. I solve this issue by using onnx_simplify before converting to the tensorrt engine. After the simplification, this error just disappeared : )
