### ISSUE TITLE
Fail to run efficientdet on NVDLA of Jetson

### ISSUE THREAD

**Issue by zhiqi-0** [NVIDIA/TensorRT#1871]
## Description

Fail to convert EfficientDet ONNX model to NVDLA-TRT engine (`--useDLACore=0` compiling flag)

Hi, I could generate TensorRT engines of Efficientdet following steps in [sample](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/efficientdet).

But when I try to compile it using NVDLA cores, it causes segmentation fault. The command is following:

```sh
/usr/src/tensorrt/bin/trtexec \
    --onnx=/data/models/pretrained/d0/d0.onnx \
    --workspace=32 \ 
    --useDLACore=0 --allowGPUFallback --fp16 
```

The d0.onnx is generated by steps in above sample.

## Environment

**Device Type**: Jetson AGX Xavier
**TensorRT Version**:  8.0.1.6+cuda10.2
**CUDA Version**: 10.2
**Operating System**: Ubuntu 18.04.6 LTS
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: 2.6.0
**Baremetal or Container (if so, version)**: Baremetal

## Steps To Reproduce

Following can reproduce the results:

```sh
modeldir=/data/models/pretrained/
name=d0
resolution='1,512,512,3'

mkdir -p ${modeldir}${name}
wget https://storage.googleapis.com/tfhub-modules/tensorflow/efficientdet/${name}/1.tar.gz
mv 1.tar.gz ${name}.tar.gz
tar -C ${modeldir}${name} -zxf ${name}.tar.gz

# --> success!
python3 create_onnx.py \
    --input_shape ${resolution} \
    --saved_model ${modeldir}${name}/ \
    --onnx ${modeldir}${name}/${name}.onnx \
    --nms_threshold 0.0

# --> success!
python3 build_engine.py \
    --onnx ${modeldir}${name}/${name}.onnx \
    --engine ${modeldir}${name}/${name}.trt \
    --precision fp16

# --> fail: segmentation fault
/usr/src/tensorrt/bin/trtexec \
    --onnx=${modeldir}${name}/${name}.onnx \
    --workspace=32 \ 
    --useDLACore=0 --allowGPUFallback --fp16 
```

Anyone has ideas on how to run Efficientdet on NVDLA cores?
Thanks!

**Comment by zerollzeng** [comment]
can you share the onnx file here?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
