### ISSUE TITLE
AttributeError: 'T5TRTDecoder' object has no attribute 'return_device'

### ISSUE THREAD

**Issue by tonyhkassab** [NVIDIA/TensorRT#1873]
## Description

Running TensorRT T5 optimization demo found here: https://github.com/NVIDIA/TensorRT/blob/release/8.2/demo/HuggingFace/notebooks/t5.ipynb

The demo works until the **Inference with TensorRT engine** section. The decoder output gives `AttributeError`: 
```python
outputs = t5_trt_decoder(input_ids, encoder_last_hidden_state)
```
`AttributeError: 'T5TRTDecoder' object has no attribute 'return_device'`

I'm looking at src code here: https://github.com/NVIDIA/TensorRT/blob/release/8.2/demo/HuggingFace/T5/trt.py but could use your help.

## Environment

**TensorRT Version**:  8.2.1-1+cuda11.4 
**NVIDIA GPU**:  V100
**NVIDIA Driver Version**:  1.7.0.0
**CUDA Version**: Cuda compilation tools, release 11.4, V11.4.152 Build cuda_11.4.r11.4/compiler.30521435_0
**CUDNN Version**: Cuda compilation tools, release 11.4, V11.4.152 Build cuda_11.4.r11.4/compiler.30521435_0
**Operating System**: Linux (ubuntu 20.04)
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

See above links please.

## Steps To Reproduce
https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/

**Comment by ttyio** [comment]
@tonyhkassab , I check the code and see now there is a fix
https://github.com/NVIDIA/TensorRT/commit/af356e1b40ced115235a5cc71acc6cc62ff5cf11

Could you take a check if this patch is applied? thanks!

**Comment by tonyhkassab** [comment]
Thank you
