### ISSUE TITLE
onnx debug by myself

### ISSUE THREAD

**Issue by alicera** [NVIDIA/TensorRT#1874]
## Description
I try to convert onnx to trt and meet some error.
Could not find any implementation for node
How can I debug it ?
How can  I search  what is the node_of_798

## Environment

**TensorRT Version**: 
https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt
tensorrt 22.02

Error 

```
19:54:12.555	ERROR	TRT: 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[node_of_onnx::Gather_796...node_of_798]}.)	trt_utils.cpp:253
19:54:12.555	ERROR	TRT: 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )	trt_utils.cpp:253
19:54:12.555
```

**Comment by ttyio** [comment]
@alicera  It seems myelin failure from the keyword `ForeignNode`, have you tried 8.4EA? thanks!

**Comment by alicera** [comment]
what do you mean 8.4EA

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-0-EA

**Comment by alicera** [comment]
No, I dont use 8.4 EA.
I only follow the release https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt/tags

And I found some strange 
The document say `Release 22.02 is based on [NVIDIA CUDA 11.6.0](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html), which requires [NVIDIA Driver](http://www.nvidia.com/Download/index.aspx?lang=en-us) release 510 or later.`

But anther document say `This TensorRT release supports NVIDIA CUDA®:
[11.5](https://developer.nvidia.com/cuda-toolkit-archive)`
![image](https://user-images.githubusercontent.com/59388989/160577920-4de9f583-c209-465d-a0ca-da6df042ff8f.png)

One support CUDA 11.6.0,  
anther support CUDA 11.5

**Comment by ttyio** [comment]
Hello @alicera , this is because cuda support minor version compatibility since 11
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility

the release notes contains the enviroment we test for 8.2.3, besides that we have monthly container release, the container release may upgrade the cuda version.

Could you try 8.4 EA? we have improvements in the new version. thanks!

**Comment by alicera** [comment]
Sorry, I only know docker pull method to update tensorrt.
https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_22-03.html#rel_22-03
Do you have the step to install 8.4 EA?


> the release notes contains the enviroment we test for 8.2.3, besides that we have monthly container release, the container release may upgrade the cuda version.
Do you mean the Release 22.02 can run on cuda 11.6, but no test it, right ?

**Comment by ttyio** [comment]
Sorry @alicera for the delay response.
1. You can follow https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing to install trt. I can also take a try if you can attach the onnx here.
2. Yes.

**Comment by alicera** [comment]
onnx https://www.dropbox.com/s/3zne1opnt7q3pgq/123.onnx?dl=0

**Comment by ttyio** [comment]
Verified it passed with 8.4 on Turing (RTX8000), thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
