### ISSUE TITLE
Generate engine for Nano on Host

### ISSUE THREAD

**Issue by ishantbansal** [NVIDIA/TensorRT#1879]
if it is possible to generate tensorrt engine for jetson nano on host device having same tensorrt version installed with a nvidia gpu card available

**Comment by ttyio** [comment]
Hello @ishantbansal, currently TRT require you to build engine on the same device the same enviroment, cannot use host device to build engine for jetson.

**Comment by ishantbansal** [comment]
Thanks @ttyio for the clarification.
