### ISSUE TITLE
error: 'class nvonnxparser::IParser' has no member named 'reportParsingInfo'

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/TensorRT#1886]
/workspace/TensorRT/samples/sampleOnnxMNIST/sampleOnnxMNIST.cpp:128:14: error: 'class nvonnxparser::IParser' has no member named 'reportParsingInfo'
parser1->reportParsingInfo();
i want to print the network infomation using this function but met an error. the tenrort version is 8, does this fuction is deprecated in this version?

**Comment by samurdhikaru** [comment]
@GeneralJing `reportParsingInfo()` is no longer a part of the API. Its mention in sampleOnnxMNIST/README is outdated and will be fixed in a future release.

**Comment by GeneralJing** [comment]
thank you

**Comment by lovedreamms** [comment]
I encountered the same issue while compiling Tensor. The version I compiled is realse/9.0
The error is as follows:
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp: In lambda function:
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:79:27: error: ‘class nvonnxparser::IParser’ has no member named ‘getUsedVCPluginLibraries’
     auto libCArray = self.getUsedVCPluginLibraries(nbPluginLibs);
                           ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:87:59: error: no matching function for call to ‘std::__cxx11::basic_string<char>::basic_string(<brace-enclosed initializer list>)’
         vcPluginLibs.emplace_back(std::string{libCArray[i]});
                                                           ^
In file included from /usr/include/c++/7/string:52:0,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/c++/7/array:39,
                 from /usr/include/c++/7/tuple:39,
                 from /usr/include/c++/7/bits/unique_ptr.h:37,
                 from /usr/include/c++/7/memory:80,
                 from /home/ms/extern/pybind11/include/pybind11/detail/common.h:318,
                 from /home/ms/extern/pybind11/include/pybind11/attr.h:13,
                 from /home/ms/extern/pybind11/include/pybind11/detail/class.h:12,
                 from /home/ms/extern/pybind11/include/pybind11/pybind11.h:12,
                 from /home/ms/TensorRT/python/include/ForwardDeclarations.h:30,
                 from /home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:19:
/usr/include/c++/7/bits/basic_string.h:604:9: note: candidate: template<class _InputIterator, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&)
         basic_string(_InputIterator __beg, _InputIterator __end,
         ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:604:9: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/basic_string.h:566:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(basic_string&& __str, const _Alloc& __a)
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:566:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:562:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const basic_string& __str, const _Alloc& __a)
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:562:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:558:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::initializer_list<_Tp>, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(initializer_list<_CharT> __l, const _Alloc& __a = _Alloc())
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:558:7: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/7/bits/basic_string.h:531:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(basic_string&& __str) noexcept
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:531:7: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/7/bits/basic_string.h:519:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:519:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:509:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:509:7: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/7/bits/basic_string.h:499:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const _CharT* __s, size_type __n,
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:499:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:481:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const basic_string& __str, size_type __pos,
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:481:7: note:   candidate expects 4 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:465:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const basic_string& __str, size_type __pos,
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:465:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:450:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const basic_string& __str, size_type __pos,
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:450:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/7/bits/basic_string.h:437:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const basic_string& __str)
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:437:7: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/7/bits/basic_string.h:429:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:429:7: note:   conversion of argument 1 would be ill-formed:
/usr/include/c++/7/bits/basic_string.h:420:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string()
       ^~~~~~~~~~~~
/usr/include/c++/7/bits/basic_string.h:420:7: note:   candidate expects 0 arguments, 1 provided
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp: In function ‘void tensorrt::bindOnnx(pybind11::module&)’:
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:113:42: error: ‘getFlags’ is not a member of ‘nvonnxparser::IParser’
         .def_property("flags", &IParser::getFlags, &IParser::setFlags)
                                          ^~~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:113:62: error: ‘setFlags’ is not a member of ‘nvonnxparser::IParser’
         .def_property("flags", &IParser::getFlags, &IParser::setFlags)
                                                              ^~~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:114:38: error: ‘clearFlag’ is not a member of ‘nvonnxparser::IParser’
         .def("clear_flag", &IParser::clearFlag, "flag"_a, OnnxParserDoc::clear_flag)
                                      ^~~~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:115:36: error: ‘setFlag’ is not a member of ‘nvonnxparser::IParser’
         .def("set_flag", &IParser::setFlag, "flag"_a, OnnxParserDoc::set_flag)
                                    ^~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:116:36: error: ‘getFlag’ is not a member of ‘nvonnxparser::IParser’
         .def("get_flag", &IParser::getFlag, "flag"_a, OnnxParserDoc::get_flag)
                                    ^~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:121:15: error: ‘OnnxParserFlag’ was not declared in this scope
     py::enum_<OnnxParserFlag>(m, "OnnxParserFlag", OnnxParserFlagDoc::descr, py::module_local())
               ^~~~~~~~~~~~~~
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:121:29: error: template argument 1 is invalid
     py::enum_<OnnxParserFlag>(m, "OnnxParserFlag", OnnxParserFlagDoc::descr, py::module_local())
                             ^
/home/ms/TensorRT/python/src/parsers/pyOnnx.cpp:122:39: error: ‘OnnxParserFlag’ is not a class, namespace, or enumeration
         .value("NATIVE_INSTANCENORM", OnnxParserFlag::kNATIVE_INSTANCENORM, OnnxParserFlagDoc::NATIVE_INSTANCENORM);
                                       ^~~~~~~~~~~~~~
[ 80%] Building CXX object CMakeFiles/tensorrt.dir/src/pyTensorRT.cpp.o
CMakeFiles/tensorrt.dir/build.make:140: recipe for target 'CMakeFiles/tensorrt.dir/src/parsers/pyOnnx.cpp.o' failed
make[2]: *** [CMakeFiles/tensorrt.dir/src/parsers/pyOnnx.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/tensorrt.dir/all' failed
make[1]: *** [CMakeFiles/tensorrt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by samurdhikaru** [comment]
@lovedreamms It looks like you're trying to compile TensorRT with a mismatched version of the TRT parser source (specifically a mismatched `NvOnnxParser.h`). Note that within the TensorRT GitHub repo, `TensorRT/parsers/onnx` is a submodule pointing to `https://github.com/onnx/onnx-tensorrt`. Please make sure you're updating the git submodules in your clone before attempting to compile.
