### ISSUE TITLE
tensorrt docker

### ISSUE THREAD

**Issue by alicera** [NVIDIA/TensorRT#1888]
Where can I reference the docker content on [tensorrt:22.03-py3](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_22-03.html#rel_22-03)

For example,
https://github.com/NVIDIA/TensorRT/blob/main/docker/ubuntu-20.04.Dockerfile

**Comment by ttyio** [comment]
Sorry @alicera , could you elborate your request? Is `docker pull nvcr.io/nvidia/tensorrt:22.03-py3` sufficient for you? thanks

**Comment by alicera** [comment]
For example,

Assume
I write a docker file 
```
ARG CUDA_VERSION=11.4.2
ARG OS_VERSION=20.04

FROM nvidia/cuda:${CUDA_VERSION}-cudnn8-devel-ubuntu${OS_VERSION}
LABEL maintainer="NVIDIA CORPORATION"
RUN apt-get update && apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev
```
And I push it with `docker push nvcr.io/nvidia/tensorrt:22.03-py3`


I just want to know the actual dockerfile content of  image `nvcr.io/nvidia/tensorrt:22.03-py3`

**Comment by wbudd** [comment]
I have the same question.

The `nvcr.io/nvidia/tensorrt:22.03-py3` image is 6.21 GB, which is arguably too large for my needs. If possible, I'd like to view the Dockerfile(s) with which these base images are built, and customize them (i.e., yeet stuff out) as I see fit.

**Comment by nvpohanh** [comment]
I don't think NVIDIA has exposed the layer details of any NGC docker images. If docker image size is a concern, you may be able to manually build a TRT container from a base container, like `11.6.1-cudnn8-devel-ubuntu20.04`. But given that `11.6.1-cudnn8-devel-ubuntu20.04` is already 3.75GB, I am not sure how much more we can squeeze from it.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
