### ISSUE TITLE
TensorRT Python API: Custom Profiler Not Working

### ISSUE THREAD

**Issue by malithj** [NVIDIA/TensorRT#1894]
## Description

Created a custom profiler using the instructions [https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Profiler.html)](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Profiler.html). However, when performing inference an error is encountered ```TypeError: MyProfiler: No constructor defined!```.  

I looked at the core API implementation [https://github.com/NVIDIA/TensorRT/blob/main/python/src/infer/pyCore.cpp](https://github.com/NVIDIA/TensorRT/blob/main/python/src/infer/pyCore.cpp ); It allows the use of IProfiler through pybind11 ```PYBIND11_OVERLOAD_PURE_NAME```.

## Environment

**TensorRT Version**:  7.0.0.11
**NVIDIA GPU**: RTX 2080 Ti
**NVIDIA Driver Version**: 450.119.03 
**CUDA Version**: 10.0
**CUDNN Version**: 7605
**Operating System**: Ubuntu 18.04.3 LTS
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: 1.9.0+cu102
**Baremetal or Container (if so, version)**: Baremetal

## Steps To Reproduce

1. Created a custom profiler using the instructions [https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Profiler.html)](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Profiler.html).

```
class MyProfiler(trt.IProfiler):
    def __init__(self):
        trt.IProfiler.__init__(self)
    
    def report_layer_time(layer_name, ms):
        print(layer_name, ms)
```

2. Inference code is as follows. 

```
trt_model.context.profiler = MyProfiler()
trt_model(torch.randn([128, 3, 32, 32], dtype=torch.float32).cuda())
```

3. Received error while performing inference. 

```
Traceback (most recent call last):
  File "infer.py", line 106, in <module>
    main()
  File "infer.py", line 72, in main
    trt_model.context.profiler = MyProfiler()
  File "infer.py", line 67, in __init__
    trt.IProfiler.__init__(self)
TypeError: MyProfiler: No constructor defined!
```

**Comment by pranavm-nvidia** [comment]
IIRC this was fixed in a later release. Could you try TRT 8.2 or newer?

**Comment by malithj** [comment]
Thank you! I tried with TensorRT-8.4.0.6 and my custom profiler works. I'm closing this issue.
