### ISSUE TITLE
int8.trt slower than fp16

### ISSUE THREAD

**Issue by weizh588** [NVIDIA/TensorRT#1895]
## Environment
cuda10.2+tensorrt7.2.3.4

First I used python interface to implement int8.trt. Then I used trtexe to export fp16.trt. 

Why is the file of trt16 smaller and faster than int8.trt?

Thanks !

**Comment by Abdellah-Laassairi** [comment]
I think that's normal. Depending on which GPU you're using  & its architecture FP16 might be faster that int8 because of what the type of operation accelerators it's using, so it's better to implement mixed precision instead.

**Comment by nvpohanh** [comment]
Closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
