### ISSUE TITLE
QAT Model Parsing Failed: INVALID_NODE: Invalid Node - Clip_3

### ISSUE THREAD

**Issue by ZhangZhiPku** [NVIDIA/TensorRT#1897]
## Description

I try to feed an quantized mnasnet model to TensorRT, however it states there is an invalid node clip_3, don't know how to deal with that, is clip not supported in quantized model?

## Environment

**TensorRT Version**: 8.4 
**NVIDIA GPU**: GTX 1080 TI
**NVIDIA Driver Version**: 465.31
**CUDA Version**: 11.3
**CUDNN Version**: do not know
**Operating System**: ubantu 20.04
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: not used
**PyTorch Version (if applicable)**: 1.10
**Baremetal or Container (if so, version)**: 

## Relevant Files

https://pan.baidu.com/s/18yffzOV2irGYbbl_Ijz9sA?pwd=kic9
zip file contains model and python code.

## Steps To Reproduce
run python code inside zip:

[03/31/2022-21:41:46] [TRT] [V] Parsing node: Clip_3 [Clip]
[03/31/2022-21:41:46] [TRT] [V] Searching for input: PPQ_Generated_Var_148
[03/31/2022-21:41:46] [TRT] [V] Searching for input: 317
[03/31/2022-21:41:46] [TRT] [V] Searching for input: 318
[03/31/2022-21:41:46] [TRT] [V] Clip_3 [Clip] inputs: [PPQ_Generated_Var_148 -> (1, 32, 112, 112)[FLOAT]], [317 -> ()[FLOAT]], [318 -> ()[FLOAT]], 
ERROR: Failed to parse the ONNX file.
In node 111 (parseGraph): INVALID_NODE: Invalid Node - Clip_3

**Comment by ttyio** [comment]
Hello @ZhangZhiPku , seems you are using an old version TRT so that the onnx operator `clip` is not supported. However I run your model even with `clip` supported we still see failures becase the Q/DQ insertion is not the same as TRT official QAT toolkit. Maybe you can refer to the links I provide in https://github.com/NVIDIA/TensorRT/issues/1900, thanks

**Comment by nvpohanh** [comment]
Closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
