### ISSUE TITLE
Pytorch BatchNorm1d conversion error to tensorrt engine

### ISSUE THREAD

**Issue by Tristels** [NVIDIA/TensorRT#190]
## Description

When trying to convert with pytorch created onnx file to tensorrt engine, engine parsing fails on BatchNorm1d layer with error:

```
[TensorRT] VERBOSE: 200:Reshape -> (256)
[TensorRT] VERBOSE: /home/jenkins/workspace/TensorRT/helpers/rel-6.0/L1_Nightly/build/source/parsers/onnxOpenSource/builtin_op_importers.cpp:1094: GEMM: A: (256), B: (256, 256), C: (256)
[TensorRT] VERBOSE: /home/jenkins/workspace/TensorRT/helpers/rel-6.0/L1_Nightly/build/source/parsers/onnxOpenSource/builtin_op_importers.cpp:1131: Using opA: 2 opB: 0
[TensorRT] VERBOSE: /home/jenkins/workspace/TensorRT/helpers/rel-6.0/L1_Nightly/build/source/parsers/onnxOpenSource/builtin_op_importers.cpp:1132: GEMM: A, after squeezing: (256)
[TensorRT] VERBOSE: 201:Gemm -> (256)
[TensorRT] VERBOSE: /home/jenkins/workspace/TensorRT/helpers/rel-6.0/L1_Nightly/build/source/parsers/onnxOpenSource/builtin_op_importers.cpp:1981: Unsqueezing from (256) to (256, 0)
Floating point exception (core dumped)
```
It unsqueezed to (256, 0) not (256, 1) which gives Floating point exception. If I remove the BatchNorm1d layer the conversion works and I can create the engine file.

## Environment

**TensorRT Version**: 6.0.1.5-ga
**GPU Type**: Nnidia RTX 2060 SUPER
**Nvidia Driver Version**: 418.87
**CUDA Version**: 10.1
**CUDNN Version**: 7.6.2
**Python Version**: 3.6.8
**PyTorch Version**: 1.2.0
**Operating System + Version**: Ubuntu 18.04
**Baremetal or Container**: Baremetal

## Steps To Reproduce

```
# Creating onnx file from pytorch model with BatchNorm1d
torch.onnx.export(net, dummy_input, "output.onnx", verbose=True, opset_version=9)

# ...

# Model parsing to tensorrt engine
  def _build_engine(self, onnx_path, engine_path):
    TRT_LOGGER = trt.Logger()
    with trt.Builder(TRT_LOGGER) as builder:
      builder.max_workspace_size = 1 << 30 # 1GB
      builder.max_batch_size = 1
      builder.fp16_mode = sTrue

      with builder.create_network() as network:
        with trt.OnnxParser(network, TRT_LOGGER) as parser:
          with open(onnx_path, 'rb') as model:
            parser.parse(model.read())
            engine = builder.build_cuda_engine(network)

        with open(engine_path, "wb") as f:
          f.write(engine.serialize())
    return engine
```

**Comment by rmccorm4** [comment]
Hi @Tristels,

Can you please either attach your onnx model that fails, or a simple dummy model containing `BatchNorm1d` that reproduces the issue?

**Comment by Tristels** [comment]
Hi @rmccorm4 

Sorry for the late answer, but here is an untrained dummy model with the mentioned problem. 

https://drive.google.com/open?id=1QfC1VlvM46k3WGUiNFj3cdYaInroB9Os

**Comment by rmccorm4** [comment]
Hey @Tristels,

Thanks for sharing, I was able to reproduce with your code snippet and model
```python
import tensorrt as trt

def build_engine(onnx_path, engine_path):
  TRT_LOGGER = trt.Logger()
  with trt.Builder(TRT_LOGGER) as builder:
    builder.max_workspace_size = 1 << 30 # 1GB
    builder.max_batch_size = 1
    builder.fp16_mode = True

    with builder.create_network() as network:
      with trt.OnnxParser(network, TRT_LOGGER) as parser:
        with open(onnx_path, 'rb') as model:
          parser.parse(model.read())
          engine = builder.build_cuda_engine(network)

      with open(engine_path, "wb") as f:
        f.write(engine.serialize())
  return engine

if __name__ == '__main__':
  build_engine('batchnorm1d_dummy.onnx', 'model.engine')
```

Steps to reproduce:
```bash
nvidia-docker run -it -v ${PWD}:/mnt --workdir=/mnt nvcr.io/nvidia/tensorrt:19.10-py3
python convert.py
```
And got:
```
Floating point exception (core dumped)
```

---

I've escalated this to see if we can figure out why this is happening.

**Comment by CasiaFan** [comment]
Same problem here. I have to wrap BatchNorm2d + Conv2d to replace BatchNorm1d + Linear.

**Comment by rmccorm4** [comment]
Hi @Tristels @CasiaFan,

So if you build the OSS components to get a more up-to-date ONNX parser, it seems that issue has been fixed. However, you'll still get an error with that code snippet and dummy model:

```bash
root@2a4d970b10ec:/mnt# python convert.py 
[TensorRT] ERROR: Network must have at least one output

Traceback (most recent call last):
  File "convert.py", line 28, in <module>
    _build_engine('batchnorm1d_dummy.onnx', 'model.engine')
  File "convert.py", line 17, in _build_engine
    f.write(engine.serialize())
```

The relevant error is : `[TensorRT] ERROR: Network must have at least one output`

Generally, this is fixed by adding the line 
```bash
network.mark_output(network.get_layer(network.num_layers-1).get_output(0))
```

### Solution

BUT, in this case, it seems this ONNX model is an explicit batch model, so you'll have to create the network with the expicit_batch_flag: `1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)`.

The new code should look like this:
```python
import tensorrt as trt

def build_engine(onnx_path, engine_path):
  TRT_LOGGER = trt.Logger()
  with trt.Builder(TRT_LOGGER) as builder:
    builder.max_workspace_size = 1 << 30 # 1GB
    builder.max_batch_size = 1
    builder.fp16_mode = True

    #with builder.create_network() as network:
    explicit_batch_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    with builder.create_network(explicit_batch_flag) as network:
      with trt.OnnxParser(network, TRT_LOGGER) as parser:
        with open(onnx_path, 'rb') as model:
          parser.parse(model.read())
          network.mark_output(network.get_layer(network.num_layers-1).get_output(0))
          engine = builder.build_cuda_engine(network)

      with open(engine_path, "wb") as f:
        f.write(engine.serialize())
  return engine

if __name__ == '__main__':
  build_engine('batchnorm1d_dummy.onnx', 'model.engine')
```

And you can run it like so:
```
nvidia-docker run -it -v ${PWD}:/mnt --workdir=/mnt nvcr.io/nvidia/tensorrt:19.10-py3
# ...
# Build TensorRT OSS components inside NGC container (see README)
# ...
python convert.py
```

### Misc Details for Reference

1. :x: If you add explicit batch flag but don't use OSS parser, you should expect:
```
root@478392c30fb1:/mnt# python convert.py 
[TensorRT] ERROR: (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
[TensorRT] ERROR: (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
```

2. :x: If you use OSS parser but don't add explicit batch flag, you should expect:
```
root@2a4d970b10ec:/mnt# python convert.py 
[TensorRT] ERROR: Network must have at least one output
```

3. :heavy_check_mark: If you use both OSS parser with explicit batch flag, it should work.

**Comment by rmccorm4** [comment]
To build the OSS components inside of the TensorRT NGC Container, I did the following interactively:

Launch NGC container - v19.10 contains TRT 6.0
```bash
# See release page to see all relevant packages that container comes with: 
#   https://docs.nvidia.com/deeplearning/sdk/tensorrt-container-release-notes/index.html
nvidia-docker run -it -v ${PWD}:/mnt --workdir=/mnt nvcr.io/nvidia/tensorrt:19.10-py3
```

Build OSS Components inside container:
```bash
# Download OSS Components
git clone -b master https://github.com/nvidia/TensorRT TensorRT
cd TensorRT
git submodule update --init --recursive
export TRT_SOURCE=`pwd`

# Install required libraries
apt-get update && apt-get install -y --no-install-recommends \
	libcurl4-openssl-dev \
	wget \
	zlib1g-dev \
	git \
	pkg-config

# Install CMake >= 3.13
pushd /tmp
wget https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Linux-x86_64.sh
chmod +x cmake-3.14.4-Linux-x86_64.sh
./cmake-3.14.4-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir --skip-license
rm ./cmake-3.14.4-Linux-x86_64.sh
popd

# Set relevant env variables relative to NGC container paths
export TRT_RELEASE=/usr/src/tensorrt
export TRT_LIB_DIR=$TRT_RELEASE/lib
export TRT_SOURCE=/mnt/TensorRT
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRT_LIB_DIR

# Generate Makefiles and build
cd $TRT_SOURCE
mkdir -p build && cd build 
cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out
make -j$(nproc)

# Install OSS Components
make install
```

Test installation:
```bash
# Test installation
cd $TRT_RELEASE/bin/
./sample_googlenet
```

Output (on an 8GB - P4 GPU):
```bash
root@2c76ce1aa072:/mnt/TensorRT/build# cd $TRT_RELEASE/bin/
root@2c76ce1aa072:/usr/src/tensorrt/bin# ./sample_googlenet
&&&& RUNNING TensorRT.sample_googlenet # ./sample_googlenet
[10/05/2019-21:41:55] [I] Building and running a GPU inference engine for GoogleNet
[10/05/2019-21:41:57] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[10/05/2019-21:42:03] [I] [TRT] Detected 1 inputs and 1 output network tensors.
[10/05/2019-21:42:03] [I] Ran ./sample_googlenet with: 
[10/05/2019-21:42:03] [I] Input(s): data 
[10/05/2019-21:42:03] [I] Output(s): prob 
&&&& PASSED TensorRT.sample_googlenet
```

I'll see if I can get this added in the README somewhere as it seems like a pretty common use case to avoid having to install the `TRT_RELEASE` on host if you don't want to.

You can also package all of this up nicely into a Dockerfile for easier reproducibility similar to here: https://github.com/NVIDIA/TensorRT/blob/master/docker/ubuntu-18.04.Dockerfile

But with a few modifications.

**Comment by anhtu812** [comment]
Hi @rmccorm4 
I run my C++ code with tensorrt6.0.1, it build engine from UFF file. It worked without dynamic_shape and out error when use dynamic_shape:
`[W] [TRT] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
[W] [TRT] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
[E] [TRT] model/lambda/add: at least 4 dimensions are required for input
[E] [TRT] model/lambda/truediv: elementwise inputs must have same dimensions or follow broadcast rules (input dimensions were [-1,-1,1] and [])
[E] [TRT] UffParser: Parser error: model/forward_1_conv2D/Conv2D: Order size is not matching the number dimensions of TensorRT
[E] [TRT] Network must have at least one output
Segmentation fault (core dumped)`

I used explicit batch flag
`network = builder->createNetworkV2(1U << static_cast<int>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH));`
I installed:
`apt-get -y install libnvinfer6=6.0.1-1+cuda10.0 libnvinfer-dev=6.0.1-1+cuda10.0
apt-get -y install libnvparsers6=6.0.1-1+cuda10.0 libnvparsers-dev=6.0.1-1+cuda10.0
apt-get -y install libnvinfer-plugin6=6.0.1-1+cuda10.0 libnvinfer-plugin-dev=6.0.1-1+cuda10.0`

I have to build and install OSS Components ???

**Comment by rmccorm4** [comment]
Hi @anhtu812,

Yes, I believe some (if not all) of the samples in this repo depend on the OSS components. They're basically add some minor patches on top of the TRT 6.0 parsers/plugins/etc. which may be necessary to run some of the examples.

**Comment by anhtu812** [comment]
Hi @rmccorm4 ,

I installed OSS Components and rebuild my code, it out same error.
How to use OSS components?
I have to uninstall some things before install OSS?

**Comment by anhtu812** [comment]
dynamic shape is currently not supported by UFF parser
[https://devtalk.nvidia.com/default/topic/1068819/tensorrt/dynamic_shape-uff-parser-error-quot-at-least-4-dimensions-are-required-quot-/](url)
