### ISSUE TITLE
input: "300" output: "303" name: "Mul_163" op_type: "Mul"  [04/04/2022-12:49:39] [E] [TRT] ModelImporter.cpp:776: --- End node --- [04/04/2022-12:49:39] [E] [TRT] ModelImporter.cpp:779: ERROR: onnx2trt_utils.cpp:889 In function elementwiseHelper: [8] Assertion failed: elementwiseCheck(inputs, binary_op) && "Elementwise layer does not support the given inputs and op erator."

### ISSUE THREAD

**Issue by 2017ZYS** [NVIDIA/TensorRT#1901]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by samurdhikaru** [comment]
@2017ZYS Can you please update the description with a code snippet of what lead to this error?

**Comment by 2017ZYS** [comment]
Thanks! I sovled the problem ownself. It should be that the mul operator cannot handle the bool type.  I modified the inputs of the mul operator to float type, and the whole conversion is normal!

**Comment by samurdhikaru** [comment]
@2017ZYS Related issue with the workaround #1872.
