### ISSUE TITLE
INT16 Inference

### ISSUE THREAD

**Issue by schmiph2** [NVIDIA/TensorRT#1907]
I’m currently working on a special use case where I need INT16 inference (not fp16 or INT8). I saw in the [documentation ](https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#layers-precision-matrix) hat INT16 inference is not supported by TensorRT. Do you have any plans to support it in the future?

**Comment by ttyio** [comment]
sorry @schmiph2 , not in plan yet.

**Comment by nvpohanh** [comment]
closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
