### ISSUE TITLE
platform_has_fast_fp16平台支持问题

### ISSUE THREAD

**Issue by ggyybb** [NVIDIA/TensorRT#1908]
您好，我想问一下笔记本mx系列显卡（mx150、mx250、mx350、mx330）支持fp16 的engine么？

**Comment by ttyio** [comment]
Hello @ggyybb , they are pascal devices with capability sm61, fp16 is supported but not enabled in TRT due to they are not high performance. Thanks

**Comment by nvpohanh** [comment]
closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
