### ISSUE TITLE
how to visualize tensorrt optimized graph with tensorboard?

### ISSUE THREAD

**Issue by superhg2012** [NVIDIA/TensorRT#191]
Hi, I converted my model with TensorRT    TrtGraphConverter  api, the converted savedmodel can not be imported to Tensorboard for visualization.  

tensorflow 1.14.1  bazel  + cuda support

tensorrt  5.1.5

pyhton 3.5.6

**Comment by rmccorm4** [comment]
Hi @superhg2012,

I think this is better suited for the TF-TRT folks: https://github.com/tensorflow/tensorrt

Sorry I can't help more.

**Comment by ysyyork** [comment]
But any plans to support this?
