### ISSUE TITLE
cross Operating System platform compatibility with the same GPU platform

### ISSUE THREAD

**Issue by leimeng86** [NVIDIA/TensorRT#1911]
A quick question:
I have compiled a TensorRT inference engine on Linux x86-64 Ubuntu 18.04.2 LTS and GPU 3070.
1. Is it ok to reuse it on Windows-7 x86-64 and the same GPU 3070, plus the same (or as similar as possible) TensorRT and CUDA environment?
2. If not, any issue or problem?
3. And what can I do about it?

Regards

**Comment by zerollzeng** [comment]
no, we don't support that

**Comment by ttyio** [comment]
Hello @leimeng86 , this is not recommend workflow and not tested by QA, Could you elaborate the use scenario here? thanks
