### ISSUE TITLE
Training code for models in demo/BERT

### ISSUE THREAD

**Issue by koast0** [NVIDIA/TensorRT#1914]
Hello.
I have tried to find the training code for models used in demo/BERT, but was unable to.
Can you provide the source code for models used in demo or it is not public?

I am mostly interested in training of pytorch QAT BERT and Megatron-LM models.

**Comment by ttyio** [comment]
@koast0 , please check this link , thanks!
https://github.com/NVIDIA/FasterTransformer/tree/main/bert-quantization

**Comment by nvpohanh** [comment]
Closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
