### ISSUE TITLE
Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Unsqueeze_93...Softmax_2088]}

### ISSUE THREAD

**Issue by Xinchengzelin** [NVIDIA/TensorRT#1917]
I use trtexec (TensorRT 8.2.4.2 GA    CUDA11.4) to convert my onnx model to trt engine, It show the error below.  I tried TensorRT8.4EA  Cuda11.5, the transform is OK. and I check the [support operator](https://github.com/onnx/onnx-tensorrt/blob/8.2-GA/docs/operators.md) in 8.2GA includes `Unsequeeze  Softmax`, and it's same with that of 8.4EA,  So I don't know why this error happens?

```
[04/12/2022-11:30:51] [V] [TRT] *************** Autotuning format combination: Bool(450,1), Bool(22500,50,1), Float(202500,450,9,1), Float(900,2,1) -> Float(512,1), Float(3,1) ***************
[04/12/2022-11:30:51] [V] [TRT] --------------- Timing Runner: {ForeignNode[Unsqueeze_93...Softmax_2088]} (Myelin)
[04/12/2022-11:30:51] [W] [TRT] Skipping tactic 0 due to insuficient memory on requested size of 26931712 detected for tactic 0.
[04/12/2022-11:30:51] [V] [TRT] Fastest Tactic: -3360065831133338131 Time: inf
[04/12/2022-11:30:51] [E] Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Unsqueeze_93...Softmax_2088]}.)
[04/12/2022-11:30:51] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
[04/12/2022-11:30:51] [E] Engine could not be created from network
[04/12/2022-11:30:51] [E] Building engine failed
[04/12/2022-11:30:51] [E] Failed to create engine from model.
[04/12/2022-11:30:51] [E] Engine set up failed
```

**Comment by ttyio** [comment]
@Xinchengzelin , the `ForeignNode[Unsqueeze_93...Softmax_2088]` include several nodes that handle by our internal myelin compiler, seems we fixed a failure between 8.2 and 8.4, could you use 8.4 since it fixed your issue? thanks

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin , the `ForeignNode[Unsqueeze_93...Softmax_2088]` include several nodes that handle by our internal myelin compiler, seems we fixed a failure between 8.2 and 8.4, could you use 8.4 since it fixed your issue? thanks

I find the [release notes](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-0-EA):

> The --workspace flag in trtexec has been deprecated. TensorRT now allocates as much workspace as available GPU memory by default when the --workspace/--memPoolSize flags are not added, instead of having 16MB default workspace size limit in the trtexec in TensorRT 8.2. To limit the workspace size, use the --memPoolSize=workspace:<size> flag instead.

Unfortunately, my  problem seems to with it,  Could I have the solutions to solve it?  the error happens in C++ code when `createExcutionContext`

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin , the `ForeignNode[Unsqueeze_93...Softmax_2088]` include several nodes that handle by our internal myelin compiler, seems we fixed a failure between 8.2 and 8.4, could you use 8.4 since it fixed your issue? thanks

**Comment by handoku** [comment]
```bash
[04/13/2022-11:48:34] [W] [TRT] Skipping tactic 0 due to Myelin error: Copy operation "concat" has 513 inputs.
[04/13/2022-11:48:34] [E] Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[MPS_VAR_3/strided_slice_1__843:0[Constant]...strided_slice_8__923]}.)
[04/13/2022-11:48:34] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
[04/13/2022-11:48:34] [E] Engine could not be created from network
[04/13/2022-11:48:34] [E] Building engine failed
[04/13/2022-11:48:34] [E] Failed to create engine from model.
[04/13/2022-11:48:34] [E] Engine set up failed
```
similar problem here, can it be solved by any other method other than using trt8.4

**Comment by ttyio** [comment]
> > @Xinchengzelin , the `ForeignNode[Unsqueeze_93...Softmax_2088]` include several nodes that handle by our internal myelin compiler, seems we fixed a failure between 8.2 and 8.4, could you use 8.4 since it fixed your issue? thanks
> 
> I find the [release notes](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-0-EA):
> 
> > The --workspace flag in trtexec has been deprecated. TensorRT now allocates as much workspace as available GPU memory by default when the --workspace/--memPoolSize flags are not added, instead of having 16MB default workspace size limit in the trtexec in TensorRT 8.2. To limit the workspace size, use the --memPoolSize=workspace: flag instead.
> 
> Unfortunately, my problem seems to with it, Could I have the solutions to solve it? the error happens in C++ code when `createExcutionContext`

Yes we changed the default workspace to max GPU memory start from 8.4. So no need to set workspace memory in 8.4.
Did you serialize cuda engine using trtexec and load it from C++? can you check the trtexec source code and fix your code since trtexec works? https://github.com/NVIDIA/TensorRT/tree/release/8.2/samples/trtexec

**Comment by ttyio** [comment]
> ```shell
> [04/13/2022-11:48:34] [W] [TRT] Skipping tactic 0 due to Myelin error: Copy operation "concat" has 513 inputs.
> [04/13/2022-11:48:34] [E] Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[MPS_VAR_3/strided_slice_1__843:0[Constant]...strided_slice_8__923]}.)
> [04/13/2022-11:48:34] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
> [04/13/2022-11:48:34] [E] Engine could not be created from network
> [04/13/2022-11:48:34] [E] Building engine failed
> [04/13/2022-11:48:34] [E] Failed to create engine from model.
> [04/13/2022-11:48:34] [E] Engine set up failed
> ```
> 
> similar problem here, can it be solved by any other method other than using trt8.4

@handoku , sorry, better to upgrade TRT8.4

**Comment by Xinchengzelin** [comment]
> 



> > > @Xinchengzelin , the `ForeignNode[Unsqueeze_93...Softmax_2088]` include several nodes that handle by our internal myelin compiler, seems we fixed a failure between 8.2 and 8.4, could you use 8.4 since it fixed your issue? thanks
> > 
> > 
> > I find the [release notes](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-0-EA):
> > > The --workspace flag in trtexec has been deprecated. TensorRT now allocates as much workspace as available GPU memory by default when the --workspace/--memPoolSize flags are not added, instead of having 16MB default workspace size limit in the trtexec in TensorRT 8.2. To limit the workspace size, use the --memPoolSize=workspace: flag instead.
> > 
> > 
> > Unfortunately, my problem seems to with it, Could I have the solutions to solve it? the error happens in C++ code when `createExcutionContext`
> 
> Yes we changed the default workspace to max GPU memory start from 8.4. So no need to set workspace memory in 8.4. Did you serialize cuda engine using trtexec and load it from C++? can you check the trtexec source code and fix your code since trtexec works? https://github.com/NVIDIA/TensorRT/tree/release/8.2/samples/trtexec

@ttyio Yes,  I serialize cuda engine using trtexec and load it from C++
You mean I should change the trtexec source code? Could you specificlly tell me how to fix my code?

**Comment by ttyio** [comment]
@Xinchengzelin , trtexec also support --saveEngine --loadEngine, did you also hit failure when using trtexec? If not you can check the trtexec source to see what's difference between yours and trtexec.

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin , trtexec also support --saveEngine --loadEngine, did you also hit failure when using trtexec? If not you can check the trtexec source to see what's difference between yours and trtexec.

@ttyio Thank you very much!  I could use `trtexec` to load engine. now I can check the difference between my code and `trtexec.cpp`.  `trtexec.cpp`, right?

**Comment by ttyio** [comment]
Yes @Xinchengzelin , the mainly code in 2 dirs
https://github.com/NVIDIA/TensorRT/tree/release/8.2/samples/trtexec
https://github.com/NVIDIA/TensorRT/tree/release/8.2/samples/common
Thanks!

**Comment by handoku** [comment]
> > ```shell
> > [04/13/2022-11:48:34] [W] [TRT] Skipping tactic 0 due to Myelin error: Copy operation "concat" has 513 inputs.
> > [04/13/2022-11:48:34] [E] Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[MPS_VAR_3/strided_slice_1__843:0[Constant]...strided_slice_8__923]}.)
> > [04/13/2022-11:48:34] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
> > [04/13/2022-11:48:34] [E] Engine could not be created from network
> > [04/13/2022-11:48:34] [E] Building engine failed
> > [04/13/2022-11:48:34] [E] Failed to create engine from model.
> > [04/13/2022-11:48:34] [E] Engine set up failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > similar problem here, can it be solved by any other method other than using trt8.4
> 
> @handoku , sorry, better to upgrade TRT8.4

@ttyio hava just tried with trt 8.4.0.6, still get same error

**Comment by handoku** [comment]
Is there any way to prevent myelin from doing this op fusion？ 

It seems that myelin fused some node into a single one，however,  can't find a corresponding implementation to run it.

**Comment by ttyio** [comment]
@handoku , have you tried increase the workspace size `--workspace` if you are using `trtexec`, if it still failed, could you share your onnx here? thanks

**Comment by handoku** [comment]
@ttyio hello, I hava already set workspace=12Gb on T4. The model can be found here([model.onnx](https://drive.google.com/file/d/1tkzBwoctrAJQ9xysPYohGQr2JuKmED6T/view?usp=sharing)), thanks for looking into this.

**Comment by ttyio** [comment]
Thanks @handoku , internal issue created to track the failure.

**Comment by ttyio** [comment]
@handoku ,  your issue is fixed in 8.4 GA, please upgrade 8.4 GA when we release the binary in https://developer.nvidia.com/tensorrt, thanks!

**Comment by Xinchengzelin** [comment]
> @handoku , your issue is fixed in 8.4 GA, please upgrade 8.4 GA when we release the binary in https://developer.nvidia.com/tensorrt, thanks!

Thanks for your advices,  I compared and changed my code with trtexec code,  now it works. Thank you very much

**Comment by handoku** [comment]
@ttyio thanks，and when will the GA version be released

**Comment by ttyio** [comment]
@handoku , GA should be available in earl June, thanks!

**Comment by edric1261234** [comment]
I have the similar problem, but fixed by adding /path/to/TensorRT-8.2.4.2/lib to LD_LIBRARY_PATH

**Comment by a227799770055** [comment]
Hi, I meet the similar problem. And I have tried "--workspace=32", but the problem still occur. 
My tensorrt version is 8.5.1.7, and os is ubuntu 20.
Thanks!
'''
[01/17/2023-10:14:48] [W] [TRT] Skipping tactic 0x0000000000000000 due to Myelin error: autotuning: CUDA error 2 allocating 4362077693-byte buffer: out of memory
[01/17/2023-10:14:48] [E] Error[10]: [optimizer.cpp::computeCosts::3728] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[(Unnamed Layer* 1590) [Shuffle]...Reshape_11153 + Transpose_11154]}.)
[01/17/2023-10:14:48] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[01/17/2023-10:14:48] [E] Engine could not be created from network
[01/17/2023-10:14:48] [E] Building engine failed
[01/17/2023-10:14:48] [E] Failed to create engine from model or file.
[01/17/2023-10:14:48] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8501] # trtexec --onnx=/home/insign/Doc/insign/Monocular-Depth-Estimation-Toolbox/toTRT/depth2023_sim.onnx --int8
'''

**Comment by lix19937** [comment]
> CUDA error 2 allocating 4362077693-byte buffer: out of memory    

 CUDA error 2 allocating 4362077693-byte buffer: `out of memory`
