### ISSUE TITLE
Einsum Layer

### ISSUE THREAD

**Issue by vuminhduc97** [NVIDIA/TensorRT#1918]
## Environment

**TensorRT Version**: 7.1.3
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

Hi Nvidia team! How can I read the Einsum plugin source code? I must deploy in Tensorrt ver 7. So I need  Einsum plugin source code to add custom plugin. Thank you very much!

**Comment by samurdhikaru** [comment]
@vuminhduc97 The source code for TensorRT layers is not available in our OSS releases. You can take a look at the [ONNX runtime implementation](https://github.com/microsoft/onnxruntime/tree/c99aa3a3f3834adcbb888ce4b964f2695c524eae/onnxruntime/core/providers/cuda/math) of Einsum for help.

**Comment by vuminhduc97** [comment]
thank you
