### ISSUE TITLE
SkipLayerNorm plugin  Error!!!

### ISSUE THREAD

**Issue by DataXujing** [NVIDIA/TensorRT#1919]
When I use SkipLayerNorm Plugin in ONNX,and execute trtexec, I get the Error:

````
[04/12/2022-11:26:49] [I] [TRT] Searching for plugin: CustomSkipLayerNormPluginDynamic, plugin_version: 3, plugin_namespace:
[04/12/2022-11:26:49] [E] [TRT] SkipLayerNorm: invalid beta
[04/12/2022-11:26:49] [E] [TRT] SkipLayerNorm: invalid gamma
[04/12/2022-11:26:49] [F] [TRT] Assertion failed: mLd > 0
/home/jenkins/agent/workspace/OSS/OSS_L0_MergeRequest/oss/plugin/skipLayerNormPlugin/skipLayerNormInt8InterleavedPlugin.cpp:81
Aborting...

Aborted (core dumped)

```

**Comment by DataXujing** [comment]
![1649763683(1)](https://user-images.githubusercontent.com/24708267/162952329-04298357-9dd9-430b-84b8-824855d8c08e.png)

**Comment by ttyio** [comment]
Thanks @DataXujing , checked that the `getFieldNames()` implementation is not correct. Will fixed this, before we release the fix, you could WAR this by manually build the OSS after some patch like this (emplace all the necessary fields in mPluginAttributes):
https://github.com/NVIDIA/TensorRT/blob/main/plugin/fcPlugin/fcPlugin.cpp#L691

**Comment by DataXujing** [comment]
OK，thanks for your reply!
