### ISSUE TITLE
How to use *.engine file in VS2017?

### ISSUE THREAD

**Issue by June1124** [NVIDIA/TensorRT#1924]
I have exported *.onnx to *.engine file, but I cannot find an approach to call it wherein demos.

**Comment by ttyio** [comment]
@June1124 , you can use `trtexec --loadEngine` to use the file, the source code is also open sourced, thanks!

**Comment by nvpohanh** [comment]
closing this issue for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
