### ISSUE TITLE
onnx->trt:all named dimensions that share the same name must be equal

### ISSUE THREAD

**Issue by ioir123ju** [NVIDIA/TensorRT#1930]
command:
` ./tensorrt/bin/trtexec  --explicitBatch --minShapes=speech:1x16x80 --optShapes=speech:4x256x80 --maxShapes=speech:16x256x80  --onnx=encoder_change.onnx --saveEngine=encoder.plan --workspace=28012`

What does this error mean？
ERROR:
![image](https://user-images.githubusercontent.com/14951957/163685467-1181627d-6b41-48dc-80b1-1e7c14be9fa6.png)

**Comment by ttyio** [comment]
@ioir123ju TRT would add assertion the make sure that the dimension in different input that share the same dimension name are always equal, and seems your dynamic shape binding disobey this restriction. Could you take a check? thanks!

**Comment by ioir123ju** [comment]
The problem has been solved, and some inputs have no specified shape.

**Comment by safehumeng** [comment]
> The problem has been solved, and some inputs have no specified shape.

can you tell how to solve this problem,please
