### ISSUE TITLE
where can i found the dynamic batch size guide documentation in tensorRT 6.0.1.5 ?

### ISSUE THREAD

**Issue by zhangxiaodi** [NVIDIA/TensorRT#1932]
i want to watch some info about how to transform the pytorch model to onnx then to trt in pytorch 1.2.0 with dynamic batch.

**Comment by ttyio** [comment]
@zhangxiaodi , 
for torch1.2.0 to onnx, could you take a check https://pytorch.org/docs/1.2.0/onnx.html#torch.onnx.export? 

for onnx to trt, could you try `trtexec --onnx=<your_onnx_file> --fp16/--int8`
thanks!

**Comment by nvpohanh** [comment]
closing this issue for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
