### ISSUE TITLE
Can TensorRT support TensorFlow1.10.0?

### ISSUE THREAD

**Issue by hliunim** [NVIDIA/TensorRT#1933]
As we all know, TensorFlow1.10.0 is an earlier version. Is it not supported to convert to onnx model using tf2onnx？
![image](https://user-images.githubusercontent.com/19989312/163943980-99db8551-b450-4222-bf09-9adb2e4e0943.png)
So can TensorRT support TensorFlow1.10.0? If yes, what is the specific implementation method？ Thank you

**Comment by ttyio** [comment]
Hi @hliunim , we also have TF-TRT project https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html

Could you check if the TF1.10 in any container from https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/index.html? Thanks

**Comment by nvpohanh** [comment]
closing this issue for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
