### ISSUE TITLE
UNAVAILABLE: Internal: unable to create TensorRT engine 

### ISSUE THREAD

**Issue by imharshitagrawal** [NVIDIA/TensorRT#1936]
I have a plan file (tensorrt). I want to run inferences in triton server. When I try to load this model file in triton, the following error is thrown UNAVAILABLE: Internal: unable to create TensorRT engine . What is the entire process of running a plan model in triton?

**Comment by ttyio** [comment]
@imharshitagrawal , could you create issue in https://github.com/triton-inference-server/server/issues, triton is maintained in a separate team, thanks!

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
