### ISSUE TITLE
pytorch-quantization example classfication_flow.py has incorrect import path

### ISSUE THREAD

**Issue by Jeremalloch** [NVIDIA/TensorRT#1938]
In the `tools/pytorch-quantization/examples/torchvision/classification_flow.py` file, [in line 42](https://github.com/NVIDIA/TensorRT/blob/f4a8635399adbfc9264707e9af4535d55829d956/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L42), custom (Nvidia modified) pytorch models are imported.  However, the code defining these models was later nested further under a classification directory, so the correct path should be `models.classification`.  In the same file, a [check](https://github.com/NVIDIA/TensorRT/blob/f4a8635399adbfc9264707e9af4535d55829d956/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L149) is performed to see if a custom implementation exists for a model (specified by name), or if the script should fall back to torchvision implementation.  This incorrect path results in the model **always** falling back to the torchvision implementation, without warning to the user.  The modified models were authored because they made minor changes to allow quantization of residual connections (during TRT export), but by falling back to the torchvision implementation, the residual connections are left unquantized, resulting in a slower model.
The first figure below is a [Netron](https://github.com/lutzroeder/netron) visualization of a block in a ResNet-50 onnx model generated by the current implementation of the `classification_flow.py` script.
![Unquantized Residual Onnx](https://user-images.githubusercontent.com/16086901/164120133-d1248a89-327d-42e4-abca-c06df32e7d9f.png)
The second figure, below, highlights the addition of the QuantizeLinear and DequantizeLinear layers along the residual path that are [added by the custom implementation](https://github.com/NVIDIA/TensorRT/blob/f4a8635399adbfc9264707e9af4535d55829d956/tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py#L123):
![Quantized Residual Onnx](https://user-images.githubusercontent.com/16086901/164120144-f6f33298-a542-4d8e-96a8-6941444c805b.png)

## Environment
N/A, this is a universal issue.

## Relevant Files

In this [Google drive folder](https://drive.google.com/drive/folders/1vpxNQt3TmYE9yU0vJf3okEkK5NaOPrRg?usp=sharing), I have included the above screenshots, as well as the onnx files that were used to generate them.

## Steps To Reproduce
Run the Nvidia authored `classification_flow.py` already included in the repository.  Then either insert a PDB breakpoint at [line 150](https://github.com/NVIDIA/TensorRT/blob/f4a8635399adbfc9264707e9af4535d55829d956/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L150) to verify this path is never being reached, or visualize the exported onnx file and verify the lack of QuantizeLinear and DequantizeLinear layers along residual paths.

**Comment by ttyio** [comment]
Thanks @Jeremalloch for the catch, yes we reorg the folder structure and the `classification_flow.py` can no longer find the correct resnet. I had just merged your code, thanks again!
