### ISSUE TITLE
Processing time by Tensorrt python

### ISSUE THREAD

**Issue by vuminhduc97** [NVIDIA/TensorRT#1940]
## Environment

**TensorRT Version**: 7.1.3
**NVIDIA GPU**: 1080Ti
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

Hi Nvidia team!
I implement GCN with TensorRT python after sucessful converting engine model. Processing time below: 
+ memcpy_htod time 7.319450378417969e-05 
+ inference time: 0.001241922378540039
+ memcpy_dtoh time: 0.16266417503356934 
Data transfers time from host to device is small but data transfers time from device to host is so long. What is the cause of this problem? And How can I solve this problem? 
thank you

**Comment by ttyio** [comment]
@vuminhduc97 , how did you measure the time, the TRT `enqueue` API is asynchronous, `you need insert explicit `cudaStreamSynchronize` if you want to measure the kernel execution time only. Else the memcpy_dtoh also include the inference execution time. Thanks!

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
