### ISSUE TITLE
TensorRT compilation on Linux Ubuntu succeeded vs. on Windows 10 failed

### ISSUE THREAD

**Issue by leimeng86** [NVIDIA/TensorRT#1946]
## Description

PyTorch nn.module compiled by TensorRT on Linux cannot be compiled on Windows with error of "Segmentation fault".

About the PyTorch nn.module:
PyTorch implementation of the relation module of [Relation Distillation Networks for Video Object Detection](https://arxiv.org/abs/1908.09511) which is based on ["Relation Network for Object Detections"](https://arxiv.org/abs/1711.11575)

### on Windows 10

**TensorRT Version**: 8.2.4.2
**NVIDIA GPU**: 3070
**NVIDIA Driver Version**: 512.15
**CUDA Version**: 11.3.58
**CUDNN Version**: 8.4.0.27
**Operating System**: Windows 10
**Python Version (if applicable)**: 3.9.12
**Tensorflow Version (if applicable)**: na
**PyTorch Version (if applicable)**: 1.10.2
**Baremetal or Container (if so, version)**: na

### on Linux Ubuntun 18.04

**TensorRT Version**: 8.2.2.1
**NVIDIA GPU**: TITAN RTX
**NVIDIA Driver Version**: 450.119.03
**CUDA Version**: 11.6.55
**CUDNN Version**: 8.3.2.44
**Operating System**: Ubuntu 18.04.2 LTS
**Python Version (if applicable)**: 3.9.5
**Tensorflow Version (if applicable)**: na
**PyTorch Version (if applicable)**: 1.10.1
**Baremetal or Container (if so, version)**: na

## Relevant Files

<img width="1121" alt="Screen Shot 2022-04-23 at 14 19 04" src="https://user-images.githubusercontent.com/26152648/164884958-dc235ab5-f92e-4914-99e5-0982ca62ba90.png">

## Steps To Reproduce

1. PyTorch ==> TorchSciprt of script mode
2. TorchScript ==> ONNX
3. ONNX ==> TensorRT inference engine

**Comment by ttyio** [comment]
@leimeng86 , 
Do you mean the Linux passed while Windows failed? Could you confirm that the same onnx is loaded in TRT? 
Also I see 2 warning in your log complains the `cuBLAS/cuBLASLt` version mismatch, and `cuDNN` version mismatch, also better to fix this warning. Thanks!

**Comment by leimeng86** [comment]
@ttyio ,

Yes, "the Linux passed while Windows failed".

The ONNX files are exported on Windows and Linux respectively. I just tried to use the ONNX file exported on Linux on Windows in TensorRT, which yielded the same error message "Segmentation fault".

The mismatch warning messages also show up when I use TensorRT on Linux. (please refer to the attached log file) I will try to fix the mismatches.
[linux_tensorrt_conversion.log](https://github.com/NVIDIA/TensorRT/files/8559299/linux_tensorrt_conversion.log)

Regards

**Comment by nvpohanh** [comment]
@leimeng86 Could you share the ONNX file directly so that we can try to repro this? thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
