### ISSUE TITLE
The volume of a tensor cannot exceed 2^31-1  (tensorRT 8.0.16)

### ISSUE THREAD

**Issue by 773041642** [NVIDIA/TensorRT#1948]
[Matrix Multiply]_output: tensor volume exceeds (2^31)-1, dimensions are [4,65536,65536])

what should I do?

**Comment by ttyio** [comment]
@773041642 , tensor size has 2G limitation in TensorRT, could you make your network smaller? Thanks

**Comment by 773041642** [comment]
Whether there is a way to modify this limit, changing the size will affect the accuracy of the model .

**Comment by ttyio** [comment]
@773041642 , sorry this is not configurable , because many kernel implementations using 32bit when addressing the offset in tensors.

**Comment by gesanqiu** [comment]
@ttyio Any update about this limitation? For stable-diffusion model, it's tensor size can exceed this limitation easily.

**Comment by DamonsJ** [comment]
@ttyio  is there any update here ?

or is there any solution for dit models which seqlen is really large

**Comment by HanG-CS** [comment]
any update?????
