### ISSUE TITLE
Shuffle layer causes an 'Internal Error': (Assertion status == kSTATUS_SUCCESS failed. )

### ISSUE THREAD

**Issue by kobzaond** [NVIDIA/TensorRT#1950]
## Description
Shuffle layer causes an 'Internal Error': (Assertion status == kSTATUS_SUCCESS failed. )

I am building a neural network through Python API. In the input, I have a list of tokens, first I collect embeddings from embedding layer and obtain a tensor of shape (-1, 768); [Note, this part does not cause any error while building]; Next I am trying to reshape the tensor by inserting a shuffle layer:
```
input_tensor_l = network.add_shuffle(input_tensor)
input_tensor_l.reshape_dims = (-1,hidden_size,1,1)
input_tensor = input_tensor_l.get_output(0)
```
However, after the insertion, Im getting the following error: 

```
[E] 2: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed. )

```

Note, that if I try to reshape to only (-1,768,1) instead of (-1,768,1,1), it works.

The building code:

def build_engine(batch_sizes, workspace_size, sequence_lengths, config, weights_dict):
    trt_version = [int(n) for n in trt.__version__.split('.')]

    explicit_batch_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(explicit_batch_flag) as network, builder.create_builder_config() as builder_config:
        builder_config.max_workspace_size = workspace_size * (1024 * 1024)
        builder_config.set_flag(trt.BuilderFlag.FP16)

        TRT_LOGGER.log(TRT_LOGGER.INFO, "Setting sparsity flag on builder_config.")
        builder_config.set_flag(trt.BuilderFlag.SPARSE_WEIGHTS)

        if trt_version[0] >= 8:
            tactic_source = 1 << int(trt.TacticSource.CUBLAS) | 1 << int(trt.TacticSource.CUBLAS_LT)
            builder_config.set_tactic_sources(tactic_source)
            if config.timing_cache != None:
                if os.path.exists(config.timing_cache):
                    with open(config.timing_cache, "rb") as f:
                        cache = builder_config.create_timing_cache(f.read())
                        builder_config.set_timing_cache(cache, ignore_mismatch = False)
                else:
                    cache = builder_config.create_timing_cache(b"")
                    builder_config.set_timing_cache(cache, ignore_mismatch = False)

        create_profiles(builder, sequence_lengths, batch_sizes, builder_config)
        token_emb_l, pos_emb_l = emb_layernorm(builder, network, config, weights_dict) #cu_seqlens, max_seqlen
        embeddings = token_emb_l.get_output(0)
        mask_idx = None#token_emb_l.get_output(1)
        casual_mask=None
        output = model(config, weights_dict, network, embeddings, mask_idx, None, None, casual_mask, None)
        network.mark_output(output)

        build_start_time = time.time()
        engine = builder.build_engine(network, builder_config)
        build_time_elapsed = (time.time() - build_start_time)
        TRT_LOGGER.log(TRT_LOGGER.INFO, "build engine in {:.3f} Sec".format(build_time_elapsed))

        # save global timing cache
        if trt_version[0] >= 8 and config.timing_cache != None:
            cache = builder_config.get_timing_cache()
            with cache.serialize() as buffer:
                with open(config.timing_cache, "wb") as f:
                    f.write(buffer)
                    f.flush()
                    os.fsync(f)

        return engine```

```
where "model" function gets the input embedding and only adds the shuffle layer.


## Environment

**TensorRT Version**: 8.2.1.8, 8.4.0.6
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: 
**CUDA Version**: 11.5
**Operating System**: Ubuntu 18:04
**Python Version (if applicable)**: 3.7

**Comment by ttyio** [comment]
@kobzaond , is this code taken from https://github.com/NVIDIA/TensorRT/blob/main/demo/BERT/builder_varseqlen.py? the error come from the plugin instead of shuffle according to your error message. Could you follow the original code or explain where and why do you want to insert this shuffle? thanks!

**Comment by nvpohanh** [comment]
closing this issue for now due to >14 days of no response. Please feel free to reopen if the issue still exists. Thanks
