### ISSUE TITLE
Question about INT8 quantization ranges

### ISSUE THREAD

**Issue by yeliang2258** [NVIDIA/TensorRT#1951]
Hi, I have two questions and I am looking forward to replying: 

1. it is written in the file that the activation value will be quantized to -128~127, then when I set tensor->setDynamicRange(min_float, max_float), if the value of tensor is less than min_float, is it quantized to -128?
2. If you need to use the QuantizeLinear OP in ONNX to express this quantization relationship, how should scale and zero be set? That is, how do I convert implicit quantization like tensor->setDynamicRange(min_float, max_float) to explicit quantization?

![image](https://user-images.githubusercontent.com/30516196/165464217-d2c2b0e1-8db9-45a5-9a6f-f78b8d3757d8.png)

**Comment by ttyio** [comment]
@yeliang2258 , 
1. yes, it is clipped to the boundary, we also have a whitepaper explain more details in https://arxiv.org/pdf/2004.09602.pdf
2. currently only symmetric quantization is supported in TRT, so the zero must set to 0. To generate the Q/DQ nodes, we recommend https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization

Thanks

**Comment by nvpohanh** [comment]
closing this issue for now due to >14 days of no response. Please feel free to reopen if the issue still exists. Thanks
