### ISSUE TITLE
docker image creation 

### ISSUE THREAD

**Issue by riyaj8888** [NVIDIA/TensorRT#1952]
I am trying to create docker image directly from docker script that is provided here but i ma getting below issue

 => ERROR [internal] load metadata for docker.io/nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04                                                  12.3s 
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                                                     0.0s 
------
 > [internal] load metadata for docker.io/nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch 
oauth token: Get "https://auth.docker.io/token?scope=repository%3Anvidia%2Fcuda%3Apull&service=registry.docker.io": net/http: TLS handshake timeout 
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker build --pull --rm -f "Dockerfile.dockerfile" -t contenttagging:latest "."" terminated with exit code: 1.

**Comment by nvpohanh** [comment]
This looks like a networking issue. @riyaj8888 Does this issue still exist?

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
