### ISSUE TITLE
Exploding results in nvcr.io/nvidia/tensorrt:"21.06~22.03"-py3  8.x

### ISSUE THREAD

**Issue by kimdwkimdw** [NVIDIA/TensorRT#1954]
## Description

Results are exploding to `inf`

## Environment

**TensorRT Version**: 8.x  ex) [8.2.3](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html)
**NVIDIA GPU**:  RTX 3090
**NVIDIA Driver Version**:  495.29.05
**CUDA Version**: 11.5
**CUDNN Version**: 
**Operating System**: Linux Ubuntu

## Relevant Files

[
](https://github.com/NVIDIA/TensorRT/issues/1707)
https://gist.github.com/kimdwkimdw/2188b4b9ff9f9bf2f7e8dbd999769796

## Steps To Reproduce

Follow steps in 1~3
https://github.com/triton-inference-server/server/issues/3978#issuecomment-1111737215
https://gist.github.com/kimdwkimdw/2188b4b9ff9f9bf2f7e8dbd999769796

**Comment by nvpohanh** [comment]
@kimdwkimdw Could you share the ONNX file directly so that we can repro this faster?

Also, could you try clipping the input values to [-1.0, 1.0] and the weights to [-0.1, 0.1] and see if it still explodes? The range of `torch.rand((1, 81, 80))` is sometimes too large for FP16 networks.

**Comment by nvpohanh** [comment]
Oh I see, the culprit may be the `l2_normalize` op because it tends to overflow in FP16. One thing you can try is to force that layer to run in FP32 by setting the layer precision to kFLOAT and set kOBEY_PRECISION_CONSTRAINTS flag in builder config.

In trtexec, you would add `--precisionConstraints=obey --layerPrecisions=<LAYER_NAME>:fp16` where <LAYER_NAME> will be the names of the layers corresponding to that l2_normalize op (especially the Pow layer).

**Comment by kimdwkimdw** [comment]
@nvpohanh Before TensorRT 8.x, TensorRT 7.x doesn't make overflow in FP16 with same trtexec command.

It is sad to add additional command like `--precisionConstraints=obey --layerPrecisions=<LAYER_NAME>:fp16`.

Thanks for investigating the problem. I hope TensorRT can automatically detect problem like overflow after converting.
I had no problem in TensorRT 7.x....

**Comment by nvpohanh** [comment]
> I hope TensorRT can automatically detect problem like overflow after converting.

This is already on our roadmap.

Could you share the verbose logs by adding `--verbose` with TRT 7.x and 8.x? It is possible that TRT 7.x was not using FP16 for those layers.

**Comment by kimdwkimdw** [comment]
It can be easily reproduced using my script https://github.com/triton-inference-server/server/issues/3978#issuecomment-1111737215/ https://gist.github.com/kimdwkimdw/2188b4b9ff9f9bf2f7e8dbd999769796

Only change is using [TensorRT ngc versions](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt) `21.03~21.06, not `22.01`

**Comment by nvpohanh** [comment]
@kimdwkimdw I can't repro this locally with TRT 8.2.... Could you try this script and see if you can still repro the issue? Thanks

```
import tensorflow as tf
from tensorflow.keras import Model, layers, mixed_precision
from tensorflow.keras.regularizers import l2

import onnx
import tf2onnx.convert

import tensorrt as trt
import torch

def conv_block(inputs, filters, kernel_size, dilation_rate=1, wd=1e-2):
    x = layers.Conv2D(
        filters=filters,
        kernel_size=kernel_size,
        dilation_rate=dilation_rate,
        padding="same",
        kernel_initializer="he_normal",
        kernel_regularizer=l2(wd),
        use_bias=False,
    )(inputs)
    x = layers.Activation("relu")(x)
    x = layers.BatchNormalization(scale=False)(x)
    return x


def SimpleCNN(input_shape, out_units=1024, wd=1e-3):
    input_layer = layers.Input(input_shape, name="input")
    x = input_layer
    x = layers.BatchNormalization()(x)

    x = tf.expand_dims(x, axis=-1)
    # CNN
    x = conv_block(x, filters=64, kernel_size=5, wd=wd)
    x = conv_block(x, filters=128, kernel_size=1, wd=wd)
    x = conv_block(x, filters=128, kernel_size=5, dilation_rate=2, wd=wd)
    x = conv_block(x, filters=256, kernel_size=1, wd=wd)
    x = conv_block(x, filters=256, kernel_size=3, dilation_rate=3, wd=wd)
    x = conv_block(x, filters=512, kernel_size=1, wd=wd)
    # Output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(units=out_units, kernel_initializer="he_normal", kernel_regularizer=l2(wd))(x)
    x = layers.Activation("relu")(x)
    x = tf.math.l2_normalize(x, axis=-1)
    x = layers.Activation("linear", dtype="float32", name="output")(x)
    return Model(input_layer, x)


policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)

model = SimpleCNN(input_shape=[81, 80])
onnx_model, _ = tf2onnx.convert.from_keras(model, opset=13)
output_name = "build/l2_norm_test.onnx"
onnx.save(
    onnx_model,
    output_name,
    convert_attribute=True,
    size_threshold=0,
)

logger = trt.Logger(trt.ILogger.Severity.VERBOSE)
builder = trt.Builder(logger)
builder_config = builder.create_builder_config()
builder_config.set_flag(trt.BuilderFlag.FP16)
builder_config.max_workspace_size = 1 << 30

profile = builder.create_optimization_profile()
min_batch = (1, 81, 80)
opt_batch = (1, 81, 80)
max_batch = (1, 81, 80)
profile.set_shape("input", min=min_batch, opt=opt_batch, max=max_batch)
builder_config.add_optimization_profile(profile)

network = builder.create_network(1)
parser = trt.OnnxParser(network, logger)
with open(output_name, "rb") as f:
    parser.parse(f.read())

engine = builder.build_engine(network, builder_config)
context = engine.create_execution_context()

input_idx = 0
output_idx = 1

torch.manual_seed(3)
input_tensor = torch.rand((1, 81, 80)).cuda()
output_tensor = torch.zeros((1, 1024)).cuda()
input_ptr = input_tensor.data_ptr()
output_ptr = output_tensor.data_ptr()

buffers = [None] * 2  # Assuming 1 input and 1 output
buffers[input_idx] = input_ptr
buffers[output_idx] = output_ptr
context.set_binding_shape(input_idx, (1, 81, 80))

torch_stream = torch.cuda.Stream()
print(output_tensor.cpu())

context.execute_v2(buffers)

print(output_tensor.cpu())
print(list(filter(lambda x: x > 1e5, list(output_tensor.reshape(-1)))))

```

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
