### ISSUE TITLE
tensorflow 1.15 is not available on PIP

### ISSUE THREAD

**Issue by snlpatel001213** [NVIDIA/TensorRT#1955]
## Description
MaskRCNN documentation requires tensorflow==1.15 to be installed but is no more available from pip.
Ref:  https://github.com/NVIDIA/TensorRT/tree/main/samples/sampleUffMaskRCNN

Please update the tutorial to the latest TensorFlow releases

## Environment

**TensorRT Version**: 8.1
**NVIDIA GPU**: P1000
**NVIDIA Driver Version**:  470.103.01
**CUDA Version**: 11.6
**CUDNN Version**: Not applicable to the issue
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

```
 pip3 install tensorflow-gpu==1.15
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.9.0rc0, 2.9.0rc1)
ERROR: No matching distribution found for tensorflow-gpu==1.15
```

**Comment by nvpohanh** [comment]
@rajeevsrao for visibility.

@snlpatel001213 What OS are you using?

**Comment by snlpatel001213** [comment]
This was solved
