### ISSUE TITLE
Support for ONNX opset version 15

### ISSUE THREAD

**Issue by naor2013** [NVIDIA/TensorRT#1962]
## Description

I did not test it out yet but I can't find anything claiming TensorRT supports export from opset version 15.
It would be great if it would be supported because of the addition support to optionals in opset version 15 is really helpful for my model.

**Comment by ttyio** [comment]
@naor2013 , may I know which operator in opset 15 is needed in your model? thanks!

**Comment by naor2013** [comment]
@ttyio I don't know of a specific operator (as I mentioned I didn't test it with TensorRT), but I need the new optional logic.
I think they have 2/3 operators for the optional logic? I'm not quite sure.

**Comment by ttyio** [comment]
Closing since now the onnx parser already catch up with the requested the version, thanks!
