### ISSUE TITLE
How to register skiplayernorm in onnx for tensorrt parser

### ISSUE THREAD

**Issue by triple-Mu** [NVIDIA/TensorRT#1964]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@triple-Mu , could you try create onnx node with type `CustomSkipLayerNormPluginDynamic` and correct `plugin_version`, `type_id`, 'beta', 'gamma', 'ld'..., the onnx parser has a fallback path, when there is no registered op, we will search the plugin list and load the plugin with the same name, more detail see

https://github.com/onnx/onnx-tensorrt/blob/e9456d57605c883cdf985e634ab483e2c1500bb1/builtin_op_importers.cpp#L4861

**Comment by nvpohanh** [comment]
Closing the issue for now due to >14 days of no response. Please feel free to reopen if the issue still exists. Thanks
