### ISSUE TITLE
Quick Start, Unable to prepare engine 

### ISSUE THREAD

**Issue by DaveBGld** [NVIDIA/TensorRT#1965]
## Description
When converting ONNX model, I get an error:
[Error (Could not find any implementation for node ArgMax_260.)](https://forums.developer.nvidia.com/t/error-could-not-find-any-implementation-for-node-argmax-260/212988)

## Environment

**TensorRT Version**: 8.2.0
**NVIDIA GPU**: RTX3090
**NVIDIA Driver Version**: 510.60.02
**CUDA Version**: Cuda compilation tools, release 11.4, V11.4.152
**CUDNN Version**: 8.4
**Operating System**: Ubuntu 20.04

## Steps To Reproduce
Downloaded and built plus make install according to the readme

Then

```
docker run --rm -it --gpus all -p 8888:8888 -v `pwd`:/workspace -w /workspace/SemanticSegmentation nvcr.io/nvidia/pytorch:20.12-py3 bash
python export.py
trtexec --onnx=fcn-resnet101.onnx --fp16 --workspace=64 --minShapes=input:1x3x256x256 --optShapes=input:1x3x1026x1282 --maxShapes=input:1x3x1440x2560 --buildOnly --saveEngine=fcn-resnet101.engine

```
The relevant part of the output is: 

> 
> 
> 04/29/2022-15:21:52] [E] Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node ArgMax_260.)
> [04/29/2022-15:21:52] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
> [04/29/2022-15:21:52] [E] Engine could not be created from network
> [04/29/2022-15:21:52] [E] Building engine failed
> [04/29/2022-15:21:52] [E] Failed to create engine from model.
> [04/29/2022-15:21:52] [E] Engine set up failed
> &&&& FAILED TensorRT.trtexec [TensorRT v8200] # trtexec --onnx=fcn-resnet101.onnx --fp16 --workspace=64 --minShapes=input:1x3x256x256 --optShapes=input:1x3x1026x1282 --maxShapes=input:1x3x1440x2560 --buildOnly --saveEngine=fcn-resnet101.engine
> Segmentation fault (core dumped)

**Comment by jasxu-nvidia** [comment]
@DaveBGld Increase the workspace size can fix your problem, e.g. `trtexec --onnx=fcn-resnet101.onnx --fp16 --workspace=4096 --minShapes=input:1x3x256x256 --optShapes=input:1x3x1026x1282 --maxShapes=input:1x3x1440x2560 --buildOnly --saveEngine=fcn-resnet101.engine`

I think the story here is that when we writing the quick start guide, we are using TRT 7.x and at that time, 64MB workspace should be enough for the model to be built successfully. But after we upgrading to TRT 8.x(for your case seems you are using TRT 8.2), 64MB is not enough. I guess we need update the cmd in the guide. Thanks for reporting this issue.

**Comment by DaveBGld** [comment]
I can confirm that the larger workspace allows the command to execute with no errors. 

I did not try the converted model in the quick start code, since I have already implemented my own.
