### ISSUE TITLE
genericReformat.cu::executeMemcpy::1334] Error Code 1: Cuda Runtime (invalid argument)

### ISSUE THREAD

**Issue by nanmi** [NVIDIA/TensorRT#1969]
## Description

When I run engine for inference, I got this :
[E] [TRT] 1: [genericReformat.cu::executeMemcpy::1334] Error Code 1: Cuda Runtime (invalid argument)

Some people think it is a bug of TRT8 for torch.cat, reference link: <https://blog.csdn.net/oZincO/article/details/124397604>

## Environment

**TensorRT Version**: 8.2.4.2
**NVIDIA GPU**: A10
**NVIDIA Driver Version**: 470.82.01
**CUDA Version**: 11.4
**CUDNN Version**: 8.2.4
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
@nanmi have you tried 8.4EA? could you share us a repro if you still see failure, thanks!

**Comment by marcortiz11** [comment]
Same happens to me. I have a ONNX graph with a concatenate operation at the end of itwhich is the source of my errors. TensorRT 8.2.1 throws an error at runtime while previos TensorRT version does not.

**Comment by nanmi** [comment]
> @nanmi have you tried 8.4EA? could you share us a repro if you still see failure, thanks!

Yes, according to your suggestion, I tried version `8.4EA`, and I found that this problem still exists. I located the error generated in step `context->enqueue(batch_size, (void**)buffers, stream, nullptr);`,  but strangely, this problem will not affect the result of inference,

**Comment by nanmi** [comment]
> Same happens to me. I have a ONNX graph with a concatenate operation at the end of itwhich is the source of my errors. TensorRT 8.2.1 throws an error at runtime while previos TensorRT version does not.

it seems to look like this

**Comment by nvpohanh** [comment]
@nanmi Could you share your ONNX file or the code you used so that we can repro and debug? Thanks

**Comment by nanmi** [comment]
> @nanmi Could you share your ONNX file or the code you used so that we can repro and debug? Thanks

Sure, you can download yolact.onnx with [link](https://drive.google.com/file/d/1sFxEZ8XfYRMA1uD_u1656nG9PsG78MSe/view?usp=sharing)

**Comment by nvpohanh** [comment]
@nanmi It seems that I don't have permission to that google drive link. could you give me the permission? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Comment by duduscript** [comment]
@marcortiz11 Thank you, I add an identity layer for output tensor solved this problem.
