### ISSUE TITLE
Image Segmentation(Caffe model) inference: TensorRT4.1.1 given bad result, but TensorRT>5.1.5 works

### ISSUE THREAD

**Issue by pierrelzw** [NVIDIA/TensorRT#197]
Hi, as mentioned, when converting a Caffe model to tensorRT and doing inference, I find that TensorRT4.1.1 given bad result, but TensorRT>5.1.5 works fine.

I‘m using tensorRT for deploying an Image Segmentation model on PX2. So I have to use TRT<=4.1.1. 

According to the following link, it seems there is a bug in CaffeParser for the Crop layer. 
https://devtalk.nvidia.com/default/topic/1047637/tensorrt/fcn-segmentation-imported-model-with-tensorrt-gives-significantly-worse-results-than-pycaffe/  
Is that true? How can i do if I have to use TensorRT<4.1.1

**Comment by rmccorm4** [comment]
Hi @pierrelzw,

You might be able to fix the issue in the 5.1 OSS branch (if it's not already fixed there) and build it on your device following something similar to here: https://github.com/NVIDIA/TensorRT/issues/9

But I don't believe we have a full supported path explaining how to do so.
