### ISSUE TITLE
whl is not supported on Xavier

### ISSUE THREAD

**Issue by mcjqwer** [NVIDIA/TensorRT#1971]
## Environment
**gcc version**:7.5.0
**TensorRT Version**: 8.0.3.4
**NVIDIA GPU**: Xavier
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 8.2.1
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.7.0
![Screenshot from 2022-05-08 16-45-45](https://user-images.githubusercontent.com/59089548/167288835-d20f5600-f8ad-48d9-a8b3-21738bb0095f.png)

**Baremetal or Container (if so, version)**:

**Comment by mcjqwer** [comment]
![Uploading Screenshot from 2022-05-08 16-50-40.png…]()

**Comment by mcjqwer** [comment]
![Screenshot from 2022-05-08 16-50-40](https://user-images.githubusercontent.com/59089548/167288967-fbf53880-6431-442e-800c-545a6b92eb6c.png)
I can run the mnist sample successfully on the Xavier.
Is the problem of GCC version?

**Comment by mcjqwer** [comment]
![11](https://user-images.githubusercontent.com/59089548/167289055-a8bfab85-87c2-4af6-96b3-36aa45cd767b.PNG)

**Comment by zerollzeng** [comment]
pip install **./**tensorrt_xxxx.whl

you need to add a path prefix on the whl

**Comment by galagam** [comment]
@mcjqwer it looks like you've downloaded an x86 version of TensorRT to Jetson Xavier. However, the Jetson family of modules contain ARM CPUs. See more details here: [Jetson Modules](https://developer.nvidia.com/embedded/jetson-modules). 
In any case, TensorRT should already be installed as part of the JetPack SDK. Please check `/usr/src/tensorrt` to verify it exists.
To upgrade the JetPack SDK to the latest version, please review: [How to Install Jetpack](https://docs.nvidia.com/jetson/jetpack/install-jetpack/index.html)
