### ISSUE TITLE
.engine vs .plan file

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/TensorRT#1975]
Hi, I often see reference to `.engine` and `.plan` files. Are these the same thing? 

If I have an `end2end.engine` file (from [MMDeploy](https://github.com/open-mmlab/mmdeploy)) and my Triton server is looking for a `model.plan` file, can I simply rename my `end2end.engine` to `model.plan`? Or are these different?

**Comment by zerollzeng** [comment]
Yes they are the same, actually, you can name it any name you want :-)
