### ISSUE TITLE
trtexec error Cuda Error in findFastestTactic: 700

### ISSUE THREAD

**Issue by vuminhduc97** [NVIDIA/TensorRT#1976]
## Environment

**TensorRT Version**: 7.1.3
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 11
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

Hi Nvidia team!
 I rebuild TensorRT with a custom layer. I use trtexec to convert ONNX model into TensorRT model. On GPU 1650 It's successful but isn't on GPU 1080. This is error I get:
``
[05/11/2022-02:42:27] [E] [TRT] ../builder/cudnnBuilderUtils.cpp (426) - Cuda Error in findFastestTactic: 700 (an illegal memory access was encountered)
delete plugin class      IN destroy
[05/11/2022-02:42:27] [E] [TRT] ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 700 (an illegal memory access was encountered)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
``

**Comment by mk-nvidia** [comment]
@vuminhduc97 Can you please try this with the [latest 8.2 TensorRT release](https://developer.nvidia.com/tensorrt-getting-started)?
If it's still not fixed, please attach a representative model that we can use to reproduce the problem.

**Comment by nvpohanh** [comment]
Closing due to no response for >14 days. Please feel free to reopen if the issue still exists. Thanks
