### ISSUE TITLE
quickstart\SemanticSegmentation\tutorial-runtime.ipynb. This file can't get the right result.

### ISSUE THREAD

**Issue by oneoneling** [NVIDIA/TensorRT#1984]
ValueError: cannot reshape array of size 1 into shape (1026,1282)

output_buffer = cuda.pagelocked_empty(size, dtype)
output_memory = cuda.mem_alloc(output_buffer.nbytes)
bindings.append(int(output_memory))

**Comment by liujf69** [comment]
Hello! I met the same problem, how did you solve it?
