### ISSUE TITLE
TensorRT onnx parser 解析优先级

### ISSUE THREAD

**Issue by WhatGhost** [NVIDIA/TensorRT#1985]
修改skipLayerNormPlugin后（未修改PluginName和Version）编译成so文件后，通过--plugin=xxx.so引入，但是paser依然使用的是默认的skipLayerNormPlugin而非自己改过重新编译的so文件，请问这个parser的优先级是什么呢如果遇到自己编译的plugin与原有的重名的话

**Comment by jackwish** [comment]
@WhatGhost Thanks for reporting this issue!

How do you use plugin?
What does "paser依然使用的是默认的skipLayerNormPlugin而非自己改过重新编译的so文件" mean in practice?

In general, if you load it as an _additional_ plugin (similar to your `--plugin=xx.so` case), you need to bump the version and adjust the code which bridges the model and the plugin.

**Comment by WhatGhost** [comment]
@[jackwish](https://github.com/jackwish)
谢谢您的解答

我是通过--plugin=SkipLayerNorm.so 来引入的，需要升级到哪个版本呢？您说的 bridges the model and the plugin.具体是指？

**Comment by jackwish** [comment]
@WhatGhost Could you share a bit more detail of your use case? For example, are you using `trtexec` directly or a modified version. And how do you confirm that it's using _the old one_, if any logs?

By _bridges the model and the plugin_ I mean the code that parses the original model and creates the plugin layer. You might need to update the plugin version (say `5`), and adjust the parser code like [this](https://github.com/onnx/onnx-tensorrt/blob/e9456d57605c883cdf985e634ab483e2c1500bb1/builtin_op_importers.cpp#L2228). In this way, the plugin can be used.

To be noted, the plugin of the same type+version can be registered only once. So you need to change either the name or the version of the plugin using a modified one together the original one.

**Comment by WhatGhost** [comment]
@[jackwish](https://github.com/jackwish)
我是直接使用的trtexec
trtexec --onnx=/target/decoder.onnx --saveEngine=/target/decoder.plan \
    --minShapes=xxxxx \
    --optShapes=xxxxx \
    --maxShapes=xxxxx\
  --workspace=$workspace --verbose --fp16 \
    --plugins=/target/SkipLayerNorm.so

SkipLayerNorm.so是我修改TensorRT/plugin/SkipLayerNormPlugin 并重新编译生成的（并未更改name和version），因为我在其中增加了几条debug调试输出信息但是并未按照预期打印所以发现的，在修改了name和version后便可以按照预期输出了。

所以您的意思是如果我想修改原来TensorRT自带的plugin并重新编译使用的话需要更改下plugin的name或者是version是吗

**Comment by jackwish** [comment]
Yes. As described, two changes are needed:
* Update the plugin name or version
* Adjust the ONNX parser code like [this](https://github.com/onnx/onnx-tensorrt/blob/e9456d57605c883cdf985e634ab483e2c1500bb1/builtin_op_importers.cpp#L2228).

Does your model contains a SkipLayerNorm operator? I think the default ONNX parser cannot handle a SkipLayerNorm operator...

**Comment by WhatGhost** [comment]
好的明白，谢谢您的解答
我还有另外一个问题，就是如果我定义了一个与原有的相同name与version的plugin（例如上文所述的SkipLayerNormPlugin）,trtexec会默认读取原有的plugin而不是通过--plugin=xxx.so方式引入的plugin是吗

SkipLayerNorm operator是改了下网络生成的

**Comment by jackwish** [comment]
It depenens on which one is the first try to register. Others won't be registered. In your case, `--plugin` will be registered later.

**Comment by WhatGhost** [comment]
那这个注册的顺序我在哪里能够查阅到呢，通过何种方式引入的plugin的注册顺序优先级更高呢

**Comment by jackwish** [comment]
It's not about priority, there is no such concept. There is only one plugin of name/version can be registered, which is not about priority. The behavior is undefined when using customized plugins with the same name and version of the already provided ones.

As metioned above, the name or version need to be changed to be distinguished from the _official_ ones. If you don't want to change the name or version, you can change the behavior of the original plugin, and then recompile the plugin library to replace the Nvidia released one (but I think this might cause even more chaos...).

Here is some related resoures that can be helpful:
* [The plugin doc](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending)
* https://github.com/NVIDIA/TensorRT/issues/784
* [How the plugin is used in demoBert](https://github.com/NVIDIA/TensorRT/blob/main/demo/BERT/builder.py#L59)

Please try to use libraries as they are designed for if possible.

**Comment by WhatGhost** [comment]
@jackwish 
好的明白，十分感谢您的耐心解答

**Comment by jackwish** [comment]
@WhatGhost I am going to close this issue as it's like a QA issue. Feel free to reopen if you encounter any further failure.
