### ISSUE TITLE
Does FullyConnect == tf.add( tf.matmul ( input, weight~t ), bias) ? 

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#199]
## Description

when transfering a Tensorflow model to TensorRT model,  result of `tf.add(tf.matmul(input, W~t) , bias)`  is not equal to `trt.fully_connected`

## Environment

**TensorRT Version**:  6.0.1
**GPU Type**:  titan xp
**Nvidia Driver Version**:  410.56
**CUDA Version**:  10.1
**CUDNN Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Operating System + Version**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @taomiao,

Can you please provide a small example of code **that I can run** to see this inequality between TF and TRT? Please see this blog post for tips on reproducible examples: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by taomiao** [comment]
Hi , @rmccorm4 , my problem was solved,  W should not transpose， thanks any way.
