### ISSUE TITLE
Valgrind detected TensorRT(7.1.3) memory leak when running trtexec on Jetson Xavier NX with JetPack 4.5.1

### ISSUE THREAD

**Issue by caufrank** [NVIDIA/TensorRT#1991]
command: valgrind --tool=memcheck --leak-check=full /usr/src/tensorrt/bin/trtexec --loadEngine=xx.bin
 definitely lost memory are detected by valgrind, below is part of output:
HEAP SUMMARY:
==20862==     in use at exit: 549,750,836 bytes in 310,895 blocks
==20862==   total heap usage: 1,086,806 allocs, 775,911 frees, 1,564,456,808 bytes allocated
==20862==
==20862== 440 bytes in 110 blocks are possibly lost in loss record 2 of 9
==20862==    at 0x4845BFC: malloc (in /usr/lib/valgrind/vgpreload_memcheck-arm64-linux.so)
==20862==
==20862== 5,965 (128 direct, 5,837 indirect) bytes in 2 blocks are definitely lost in loss record 4 of 9
==20862==    at 0x4845BFC: malloc (in /usr/lib/valgrind/vgpreload_memcheck-arm64-linux.so)
==20862==
==20862== 600,448 bytes in 4,410 blocks are possibly lost in loss record 7 of 9
==20862==    at 0x4847B0C: calloc (in /usr/lib/valgrind/vgpreload_memcheck-arm64-linux.so)
==20862==
==20862== LEAK SUMMARY:
==20862==    definitely lost: 128 bytes in 2 blocks
==20862==    indirectly lost: 5,837 bytes in 2 blocks
==20862==      possibly lost: 600,888 bytes in 4,520 blocks
==20862==    still reachable: 549,143,983 bytes in 306,371 blocks
==20862==                       of which reachable via heuristic:
==20862==                         stdstring          : 8,760 bytes in 151 blocks
==20862==         suppressed: 0 bytes in 0 blocks
==20862== Reachable blocks (those to which a pointer was found) are not shown.
==20862== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==20862==
==20862== For counts of detected and suppressed errors, rerun with: -v
==20862== Use --track-origins=yes to see where uninitialised values come from
==20862== ERROR SUMMARY: 39 errors from 6 contexts (suppressed: 0 from 0)

**Comment by nvpohanh** [comment]
@caufrank Could you share which TRT version, which GPU, and which ONNX file you used to build the engine? Thanks

**Comment by caufrank** [comment]
> @caufrank Could you share which TRT version, which GPU, and which ONNX file you used to build the engine? Thanks
TRT version:7.1.3, GPU;

**Comment by caufrank** [comment]
> @caufrank Could you share which TRT version, which GPU, and which ONNX file you used to build the engine? Thanks
TensorRT version:7.1.3; GPU: 384-core NVIDIA Volta™ GPU with 48 Tensor Cores on Jetson Xavier NX 16GB with JetPack  4.5.1; ONNX file has been attached. Thanks!
[mobilenetv2-7.onnx.tar.gz](https://github.com/NVIDIA/TensorRT/files/8906322/mobilenetv2-7.onnx.tar.gz)

**Comment by nvpohanh** [comment]
@caufrank I cannot repro the memory leak using TRT 8.2. Could you try TRT 8.2 or 8.4 and see if the issue still exists? Thanks

**Comment by caufrank** [comment]
> @caufrank I cannot repro the memory leak using TRT 8.2. Could you try TRT 8.2 or 8.4 and see if the issue still exists? Thanks

Hi, I have tried on TRT 8.0.1.6, and this memory leak issue was reported. Could you try it on TRT 7.1.3? Thanks.

**Comment by caufrank** [comment]
> @caufrank I cannot repro the memory leak using TRT 8.2. Could you try TRT 8.2 or 8.4 and see if the issue still exists? Thanks

Hi, I have tried on TRT 8.0.1.6, and this memory leak issue was not reported. Could you try it on TRT 7.1.3? Thanks.

**Comment by nvpohanh** [comment]
We don't plan to fix issues in TRT 7.x anymore.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
