### ISSUE TITLE
The problem about Resnet structure in explicit quantization model

### ISSUE THREAD

**Issue by yeliang2258** [NVIDIA/TensorRT#1992]
![image](https://user-images.githubusercontent.com/30516196/169048103-065ee787-d9ea-48ba-ae66-651aa086dcba.png)
I would like to know if the direct connection of resnet needs extra Q and DQ in explicit quantization, that is, whether the position of the red box needs Q and DQ.
Looking forward to your answer, thank you

**Comment by yeliang2258** [comment]
https://github.com/NVIDIA/TensorRT/issues/1293

**Comment by nvpohanh** [comment]
@yeliang2258 Yes, you need to add Q/DQ pair in the residual add branch to get the best performance by running it in INT8. If not, the "Add" will have to perform in FP16/FP32 which can lead to bad performance.

**Comment by yeliang2258** [comment]
Hi, thank you for your answer.  where can I find an example script that quantize the model and evaluates the quantized model accuracy ?

**Comment by nvpohanh** [comment]
Maybe you can follow the instructions in these links?
https://developer.nvidia.com/blog/achieving-fp32-accuracy-for-int8-inference-using-quantization-aware-training-with-tensorrt/
https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s31653/
