### ISSUE TITLE
TensorRT add_constant output type is Float even though input type is float16

### ISSUE THREAD

**Issue by frank-wei** [NVIDIA/TensorRT#1993]
Here is a question regarding the add_constant. The output type should align with input. 
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_network_definition.html#abc2efbce2179ca650e0efc48108d42b1

constant = network.add_constant(value.shape, to_numpy(value))
(Pdb)  constant.get_output(0).dtype
<DataType.FLOAT: 0>
(Pdb) value
tensor([[ 0.3374,  1.0107, -1.4355],
        [ 0.9775,  0.5220,  1.2383],
        [-0.8647,  0.2991,  0.4192],
        [-0.0798,  0.9263,  0.8159]], dtype=torch.float16)

Why I am seeing the output dtype is FLOAT even if input is float16.

 
## Environment

**TensorRT Version**: 8.2.18
**NVIDIA GPU**: A100
**NVIDIA Driver Version**: 470.57.02  
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by nvpohanh** [comment]
In TensorRT, the precision is decided after the autotuning. TensorRT will try all kind of precisions: FP32/FP16/INT8 (as long as you enable them) and decide which one to use for best performance. Therefore, don't worry about the `dtype` that TensorRT reports when you are constructing the INetworkDefinition. 

If you really want to force that tensor to have specific dtype, you can override the dtype and enable OBEY_PRECISION_CONSTRAINTS / PREFER_PRECISION_CONSTRAINTS 

Let me know if you have more questions. Thanks

**Comment by nvpohanh** [comment]
Why do you require the inputs to the Einsum/Concat to be in the same type? TRT will choose the dtypes for you and convert them between dtypes if needed.

**Comment by frank-wei** [comment]
> Why do you require the inputs to the Einsum/Concat to be in the same type? TRT will choose the dtypes for you and convert them between dtypes if needed.

TRT will throw an error:
[05/20/2022-09:55:16] [TRT] [E] 4: [layers.cpp::validate::5680] Error Code 4: Internal Error ((Unnamed Layer* 0) [Einsum]: einsum input tensors 0 and 1 have incompatible types Half and Float)

**Comment by nvpohanh** [comment]
@frank-wei I checked internally and that issue has been fixed as of TensorRT 8.4 EA (TRT 8.4.0.11). Could you give it a try with TensorRT 8.4 EA? Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
