### ISSUE TITLE
Cannot run SSD Mobilenet V2 FPNLite 320x320 as TRT engine on Jetson Nano

### ISSUE THREAD

**Issue by franferraz98** [NVIDIA/TensorRT#1994]
## Description

Hi,

I’ve been trying to run a retrained model from the Tensorflow Object Detection model zoo, the [SSD Mobilenet V2 FPNLite 320x320](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz). I’ve trained it with my own dataset and converted it to ONNX and TRT on my computer sucessfully.

Now I’m trying to run this model as a TRT engine on my Jetson Nano. I’ve sucessfully converted the ONNX model to TRT via `trtexec --onnx=<model>`, but when I try to run it I get the following error:

![image](https://user-images.githubusercontent.com/48053914/169322535-7a2a6ec4-331b-490b-bea8-fac597e28dc1.png)

This happens both with trtexec and the inference.py script provided [here](https://github.com/NVIDIA/TensorRT/blob/main/samples/python/tensorflow_object_detection_api/infer.py).

Any clues on why this might be happening?
Thanks a lot.

## Environment

**TensorRT Version**: 8.0.1
**NVIDIA GPU**: NVIDIA Maxwell architecture with 128 NVIDIA CUDA® cores
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 8.2.1
**Operating System**: Jetson JetPack 4.6
**Python Version (if applicable)**: 3.6
**Tensorflow Version (if applicable)**: 2.3.1 
**PyTorch Version (if applicable)**: -
**Baremetal or Container (if so, version)**: -

## Relevant Files

Here is the ONNX file: 
[onnx_model.zip](https://github.com/NVIDIA/TensorRT/files/8730329/onnx_model.zip)

## Steps To Reproduce

Run `/usr/src/tensorrt/bin/trtexec --onnx=<model.onnx>` to compress the model to a .trt engine and then run `python3 -e <model.trt>` with whichever parameters.

**Comment by azhurkevich** [comment]
@franferraz98 you tried to build en engine on Jetson from ONNX right (not transferring the same engine build on your computer to Jetson)?

**Comment by azhurkevich** [comment]
I think #1538 might be a potential solution, instructions listed by @wraveane. Please reach out if we can further help you.

**Comment by azhurkevich** [comment]
@franferraz98 Great! Please reach out if you encounter any other issues.
