### ISSUE TITLE
Question about Layer Fuse

### ISSUE THREAD

**Issue by QinganZhang** [NVIDIA/TensorRT#1996]
When I run Swin Transformer in TensorRT, I use nsight system to record time line as following.
![image](https://user-images.githubusercontent.com/72648020/169652369-ebc393a9-7834-48fe-a558-b7577b61fbba.png)

I want to know what it is inside the foreign node, so I want to disable layse fusing in foreign node. Foreign node is the part of 
multi-head self attention approximately.

I mark some layers in foreign node as output as [someone](https://zhuanlan.zhihu.com/p/360843851) did likewise

I try two ways:
1. When I get ONNX file, I parse it and mark output as following:
![image](https://user-images.githubusercontent.com/72648020/169652238-44239a5e-8aad-4656-9246-db34bb7ef1fd.png)
then I serialize the network , deserialize it into engine  and use nsight system to record
However, Foreign nodes are still there and time line not change.

2. I think there are something wrong when I marking outputs, so I try to mark outputs in ONNX file using [onnx_graphsurgeon](https://github.com/NVIDIA/TensorRT/tree/main/tools/onnx-graphsurgeon/onnx_graphsurgeon) in TensorRt. 
I successfully mark outputs in ONNX file as following:
![image](https://user-images.githubusercontent.com/72648020/169654430-d4e37e4d-8ccd-42cf-9147-ee725c747c3a.png)
I use this ONNX file to convert into engine and try again. However, Foreign nodes are still there and not changed except more outputs I marked.
![image](https://user-images.githubusercontent.com/72648020/169652805-2f389260-20b1-4eff-8811-84c1b7db0e90.png)

So I wander how to  disable layse fusing in foreign node. Thanks~

**Comment by talebolano** [comment]
did you solve this problem? i also want to disable foreign node
