### ISSUE TITLE
model size not change after quantize

### ISSUE THREAD

**Issue by gary88christie** [NVIDIA/TensorRT#1998]
## Description
After I follow calibrate_quant_resnet50.ipynb to quantize and calibrate a model, the model I saved has the same model size as origin.
Is it abnormal?

## Environment

**TensorRT Version**: 8.2.4.2
**NVIDIA GPU**: 3080Ti
**NVIDIA Driver Version**: 465.31
**CUDA Version**: 11.3
**CUDNN Version**: 8.2.1
**Operating System**: 
**Python Version (if applicable)**: 3.8
**PyTorch Version (if applicable)**: 1.10.2

**Comment by zerollzeng** [comment]
Yes, it's expected. you may refer to https://github.com/NVIDIA/TensorRT/issues/1690

**Comment by jackwish** [comment]
@zerollzeng Thank you for the support.
@gary88christie Please let me know if any further issue.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
