### ISSUE TITLE
TensorRT implement of MaskRCNN?

### ISSUE THREAD

**Issue by mengjiexu** [NVIDIA/TensorRT#20]
How to improve performance of maskrcnn using TensorRT?

**Comment by rajeevsrao** [comment]
Can you elaborate the request. We will be introducing new plugins to support MaskRCNN and FasterRCNN in upcoming release.

**Comment by mengjiexu** [comment]
I have tried to use TensorRT to replace the backbone of maskrcnn_benchmark:
> 1. use torch.jit to trace the backnone
> 2. use onnx to dump the backbone model, and load it with TensorRT
> 3. use code like:  
   features = trtmodel.predict(img);
   result = maskrcnn.roi_head(torch.from_numpy(features).cuda())

 Most of the time when inference the model was spent on copy of data, data in cpu need copy to gpu, and the data is big.
  When just use the backbone model, the trtmodel's speed is twice faster than the implement of torch inference.

**Comment by jinfagang** [comment]
@mengjiexu  What backbone do you using and how much gain do you got turns inference using tensorrt？

**Comment by mengjiexu** [comment]
> @mengjiexu What backbone do you using and how much gain do you got turns inference using tensorrt？

https://blog.csdn.net/mengjiexu_cn/article/details/95619272

**Comment by jinfagang** [comment]
@mengjiexu  It's better make it e2e when inference.
BTW, I think python version tensorrt actually does not accelerate much when it needs largely copy data between GPU and CPU

**Comment by mengjiexu** [comment]
Yes, I also think so. Use C++ maybe faster.

**Comment by zimenglan-sysu-512** [comment]
i use trt to accelerate the backbone of resnet-50 (w/o fpn), and find that it consumes much time for copying data between cpu and gpu (e.g. transfer the output from trt to fpn), which makes it slower  down the inference speed. is there possible to avoid these ops?
