### ISSUE TITLE
How to disable logger so that there is no output on the screen when initializing?

### ISSUE THREAD

**Issue by a954217436** [NVIDIA/TensorRT#2002]
![111](https://user-images.githubusercontent.com/42532862/169999406-20d7ac04-8301-474c-990e-147bca26fd93.jpg)

**Comment by nvpohanh** [comment]
@a954217436 Just set the verbosity level of the logger to kERROR: https://github.com/NVIDIA/TensorRT/blob/main/samples/trtexec/trtexec.cpp#L149

**Comment by a954217436** [comment]
> @a954217436 Just set the verbosity level of the logger to kERROR: https://github.com/NVIDIA/TensorRT/blob/main/samples/trtexec/trtexec.cpp#L149

OK, it works. Thanks a lot~
