### ISSUE TITLE
Serialization and deserialization are normal, the dimension and the input dimension in the onnx file are different during inference

### ISSUE THREAD

**Issue by scuizhibin** [NVIDIA/TensorRT#2006]
## Description

I wrote a GatherElements plugin and registered it with onnx-tensorrt. However, the serialization can be successful when the ./trtexec command is used, Serialization and deserialization are normal。But during inference, the input of the model is fixed, which is different from the input dimension in onnx.

## Environment
**TensorRT Version**:tensorrt 7.2.1 
**NVIDIA GPU**:  3060
**NVIDIA Driver Version**: 470
**CUDA Version**: 11.1
**CUDNN Version**: 8.0
**Operating System**: ubunu18.04
**onnx-tensorrt    7.2.1 

Currently I have only implemented the implementation of GatherElements axis=2 where the input is 3 dimensions and the output is 3 dimensions.

output during inference：
im_padded dim: (1, 64, 10692) 3 2737152 
x0_y0 dim: (1, 64, 10240) 3 2621440 
output dim: (1, 64, 10240) 3 2621440 
axis:::1791877336

axis is a random value instead of 2

The file download address is: 链接: https://pan.baidu.com/s/1862Dq8xSEFkjVVMWCX3FBA 提取码: n7b1

**Comment by jackwish** [comment]
@scuizhibin Could you please create a repo at GitHub to serve these code? It will be helpful for us to navigate through and discuss per-line. Thanks!

**Comment by jackwish** [comment]
@scuizhibin Thanks for the update! I mean create a GitHub repo like https://github.com/NVIDIA/TensorRT. With such repo, we can share what changes is needed with a particular line by a simple link.

Here is the doc of creating a repo: https://docs.github.com/en/get-started/quickstart/create-a-repo

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
