### ISSUE TITLE
The compatible problme between Cuda11.6 and TensorRT8.4.0.6/TensorRT8.2.4.2

### ISSUE THREAD

**Issue by Xinchengzelin** [NVIDIA/TensorRT#2007]
## 
When I use trtexec to convert onnx model to trt engine, it shows the error: ```Assertion `!transp_src_ten->is_mod()’ failed while building TensorRT engine with batch = 1```
The error is like [here]([Assertion `!transp_src_ten->is_mod()’ failed while building TensorRT engine with batch = 1](https://forums.developer.nvidia.com/t/assertion-transp-src-ten-is-mod-failed-while-building-tensorrt-engine-with-batch-1/203158))

I tried:
1.  Cuda11.4 + TensorRT8.2.4.2,  passed
2.  Cuda11.5 + TensorRT8.4.0.6,  passed
3.  Cuda11.6 + TensorRT8.2.4.2,  failed
4.  Cuda11.6 + TensorRT8.4.0.6,  failed

TensorRT8.4.0.6
```
trtexec: /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/tactic.cpp:1892: bool myelin::ir::tactic_selection_t::global_tactic_constraint_analysis(): Assertion `!transp_src_ten->is_mod()' failed.
[1]    12741 abort (core dumped)  /home/ninazhou/Downloads/TensorRT-[8.4.0.6/bin/trtexec](http://8.4.0.6/bin/trtexec)
```
TensorRT8.2.4.2
```
trtexec: /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/tactic.cpp:1892: bool myelin::ir::tactic_selection_t::global_tactic_constraint_analysis(): Assertion `!transp_src_ten->is_mod()' failed.
[1]    40200 abort (core dumped)  /home/ninazhou/Downloads/TensorRT-[8.2.4.2/bin/trtexec](http://8.2.4.2/bin/trtexec)
```

## Environment

**TensorRT Version**: TensorRT8.2.4.2
**NVIDIA GPU**:  Quadro RTX4000
**NVIDIA Driver Version**: 510.68.02
**CUDA Version**:  11.6
**CUDNN Version**: 8.4.0
**Operating System**:  ubuntu2004
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

Sorry，I could't upload the model here, so I upload to Baidu Netdisk

link：https://pan.baidu.com/s/1UGtLx9rZBobLvtg5tgAsdg 
code：8uca

**Comment by nvpohanh** [comment]
@Xinchengzelin Could you share your ONNX model so that we can try to repro the issue? Thanks

**Comment by nvpohanh** [comment]
@Xinchengzelin It asked me to log in to Baidu but I don't have an account

**Comment by Xinchengzelin** [comment]
@nvpohanh 
Please find the model in the below repo(Sorry I couldn't upload the model in issues): 
https://github.com/Xinchengzelin/model

**Comment by nvpohanh** [comment]
@Xinchengzelin I can see the model now. Thanks!

However, I am not able to repro this error. It works for me in my CUDA-11.6 environment. Could you tell me about which container you used? If you do not use the container, how did you install CUDA/CUBLAS/CUDNN/TensorRT? Also, could you show the verbose logs? Thanks

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin I can see the model now. Thanks!
> 
> However, I am not able to repro this error. It works for me in my CUDA-11.6 environment. Could you tell me about which container you used? If you do not use the container, how did you install CUDA/CUBLAS/CUDNN/TensorRT? Also, could you show the verbose logs? Thanks

I didn't use container,  how to make sure if I install  CUDA/CUBLAS/CUDNN/TensorRT correctly?

[log.md](https://github.com/NVIDIA/TensorRT/files/8778135/log.md)

**Comment by nvpohanh** [comment]
The log says:
```
[05/26/2022-17:53:19] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.8.0 but loaded cuBLAS/cuBLAS LT 110.9.2
```
Could you try using and older version of CUDA-11.6 toolkit that contains cuBLAS-11.8 instead of cuBLAS-11.9?

**Comment by Xinchengzelin** [comment]
> The log says:
> 
> ```
> [05/26/2022-17:53:19] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.8.0 but loaded cuBLAS/cuBLAS LT 110.9.2
> ```
> 
> Could you try using and older version of CUDA-11.6 toolkit that contains cuBLAS-11.8 instead of cuBLAS-11.9?

This warning really matters?  But why batch_size =10 , this warning is still, but the trt engine could be converted?

**Comment by nvpohanh** [comment]
Yes, the warning matters. TRT is only tested with the CUDA/CUDNN/CUBLAS versions we specify in release docs. Using an incompatible CUBLAS may lead to issues.

**Comment by Xinchengzelin** [comment]
> Yes, the warning matters. TRT is only tested with the CUDA/CUDNN/CUBLAS versions we specify in release docs. Using an incompatible CUBLAS may lead to issues.

Could you have the docker which include CUDA/CUBLAS/CUDNN/TensorRT?  I only find this image: https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.4.3
 I am tired of the environment configuration

**Comment by nvpohanh** [comment]
We recommend using the TRT container in NVIDIA NGC: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt

22.06 still has TRT 8.2.5. 22.07 will use TRT 8.4.1.

**Comment by Xinchengzelin** [comment]
> We recommend using the TRT container in NVIDIA NGC: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt
> 
> 22.06 still has TRT 8.2.5. 22.07 will use TRT 8.4.1.

How can I know which version has TRT 8.2.4？ Which Cuda version and OS version does it use? I couldn't tell it from the tag

**Comment by ttyio** [comment]
Closing since no response for more than 3 weeks, please reopen if you still have question, thanks!
