### ISSUE TITLE
torch/tf custom op to trt

### ISSUE THREAD

**Issue by wanduoz** [NVIDIA/TensorRT#2008]
I'm just getting started with trt and wonder if there are some complete instructions or examples about converting pytorch/tf model, which has custom op/layer to tensorrt . I find a closed issue (https://github.com/NVIDIA/TensorRT/issues/6), but those links are invalid. Thank you.

**Comment by jackwish** [comment]
@wanduoz You might be interested in this doc: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending

It serves as a all-in-one doc for custom layer.

**Comment by azhurkevich** [comment]
@wanduoz I would also suggest checking out our samples ([tensorflow object detection](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) or [detectron 2](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/detectron2)). Most common layers/ops in object detection/vision that are not supported in TRT natively yet are Non-maximum Suppression and ROI Align. Samples above show how we incorporate plug-ins as a replacement for currently unsupported framework ops/layers. For unsupported op/layer typically you'll have to go [plug-in way](https://github.com/NVIDIA/TensorRT/tree/main/plugin). [EfficientNMS](https://github.com/NVIDIA/TensorRT/tree/main/plugin) for NMS and [pyramidROIAlignPlugin](https://github.com/NVIDIA/TensorRT/tree/main/plugin/pyramidROIAlignPlugin) for ROIAlign. @jackwish suggested a great doc that summarizes how to do it, I also suggest checking out those plug-ins listed above for reference. Creating a custom plug-in requires some CUDA knowledge, but it is very doable. Hope it helps.

**Comment by wanduoz** [comment]
> @wanduoz You might be interested in this doc: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending
> 
> It serves as a all-in-one doc for custom layer.

Thanks for your reply. I will check the doc later. There are still some questions need to be confirmed. First of all, for torch model which contains custom op/layer, I need to deal with custom op in onnx and then custom op in tensorrt. Therefore, I need to follow onnx custom op doc so that my pth can convert to onnx successfully. Then follow your instructions so that my onnx model can convert to tensorrt.

Since tf model can convert to tensorrt using tf-trt backend, I only need to follow the developer guide and create custom op.

Am I right?

**Comment by wanduoz** [comment]
> 

Thank you so much. 
Hopefully the already existing plugins will meet the demand and I can just focus on the model itself. I barelly know about CUDA so it do take time to study.

**Comment by wanduoz** [comment]
> @wanduoz I would also suggest checking out our samples ([tensorflow object detection](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) or [detectron 2](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/detectron2)). Most common layers/ops in object detection/vision that are not supported in TRT natively yet are Non-maximum Suppression and ROI Align. Samples above show how we incorporate plug-ins as a replacement for currently unsupported framework ops/layers. For unsupported op/layer typically you'll have to go [plug-in way](https://github.com/NVIDIA/TensorRT/tree/main/plugin). [EfficientNMS](https://github.com/NVIDIA/TensorRT/tree/main/plugin) for NMS and [pyramidROIAlignPlugin](https://github.com/NVIDIA/TensorRT/tree/main/plugin/pyramidROIAlignPlugin) for ROIAlign. @jackwish suggested a great doc that summarizes how to do it, I also suggest checking out those plug-ins listed above for reference. Creating a custom plug-in requires some CUDA knowledge, but it is very doable. Hope it helps.

Thank you so much.
Hopefully the already existing plugins will meet the demand and I can just focus on the model itself. I barelly know about CUDA so it do take time to study.

**Comment by azhurkevich** [comment]
@wanduoz I am not an expert on TF-TRT hence won't lay out a step by step guide for you. However, for TF-TRT you are correct, you can go straight from tensorflow to tensorrt. We have a similar project for pytorch called [Torch-TensorRT](https://pytorch.org/TensorRT/). Back to TF-TRT, some tensorflow specific ops will be left as is and rest that are convertable into tensorrt will be able to convert into tensorrt. Speedups might vary but will not be as big as going the pathway that I did for [tensorflow object detection](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) , where the process is tensorflow -> tf2onnx -> graph surging onnx graph -> tensorrt engine. This conversion is more involved, but you will be rewarded with significantly faster inference, because in TF-TRT - tensorflow specific ops might be a bottleneck. 

What is the custom op you are using, if you don't mind sharing this information?

**Comment by wanduoz** [comment]
> @wanduoz I am not an expert on TF-TRT hence won't lay out a step by step guide for you. However, for TF-TRT you are correct, you can go straight from tensorflow to tensorrt. We have a similar project for pytorch called [Torch-TensorRT](https://pytorch.org/TensorRT/). Back to TF-TRT, some tensorflow specific ops will be left as is and rest that are convertable into tensorrt will be able to convert into tensorrt. Speedups might vary but will not be as big as going the pathway that I did for [tensorflow object detection](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) , where the process is tensorflow -> tf2onnx -> graph surging onnx graph -> tensorrt engine. This conversion is more involved, but you will be rewarded with significantly faster inference, because in TF-TRT - tensorflow specific ops might be a bottleneck.
> 
> What is the custom op you are using, if you don't mind sharing this information?

Thank you for your reply. Your reply completely solves my doubts. I think torch-trt is applying trt acceleration in torch. But I will focus on using triton to deploy my model. Currentlly, I don't use any custom op. My boss ask me to do some research about this. I do hope that released plugins can cover all ops I need.

You guys can close this issue. Thank you both for your answers.

**Comment by jackwish** [comment]
Thanks! Closing this issue. Feel free to reopen if any further questions.
