### ISSUE TITLE
use fp16 input for the network only

### ISSUE THREAD

**Issue by c90mkl** [NVIDIA/TensorRT#2011]
I was using trt 7.2, and with the setting `network->addInput(inputname, DataType::kHALF, ...)`, because my input data is in fp16, I can feed data with half precision to my network properly. However, I upgraded my trt to 8.0.1.6, with the same code I got the wrong result. After reviewing, I found if I change it to `network->addInput(inputname, DataType::kFLOAT, ...)` and convert my fp16 input to fp32 manually, then the network works. This is meaningless to me because my network input is in fp16 naturally. How to feed fp16 data directly to my network without any fp32 conversion? Thanks! 

And my network only supports fp16 of course.

trt: 8.0.1.6
cuda: 11.3
ubuntu 18.04

**Comment by nvpohanh** [comment]
@c90mkl Could you try `network->getInput(index)->setType(DataType::kHALF)` and see if that works? If it still doesn't work, please try TensorRT 8.2 or attach verbose logs so that we can investigate it. Thanks

**Comment by c90mkl** [comment]
> @c90mkl Could you try `network->getInput(index)->setType(DataType::kHALF)` and see if that works? If it still doesn't work, please try TensorRT 8.2 or attach verbose logs so that we can investigate it. Thanks

How to activate verbose logs in trt? Do we have a demo? Thanks!

**Comment by c90mkl** [comment]
I tried the code you mentioned with trt 8.2.1.8, it didn't work. The log is 
`
Layer(Reformat): Reformatting CopyNode for Input Tensor 0 to (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 1) [Scale] + (Unnamed Layer* 2) [Activation], Tactic: 1002, net_inout_fp16[Half(1,256,128,150)] -> Reformatted Input Tensor 0 to (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 1) [Scale] + (Unnamed Layer* 2) [Activation][Half(1,256,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 1) [Scale] + (Unnamed Layer* 2) [Activation], Tactic: 1832046141070096030, Reformatted Input Tensor 0 to (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 1) [Scale] + (Unnamed Layer* 2) [Activation][Half(1,256,128,150)] -> (Unnamed Layer* 2) [Activation]_output[Half(1,64,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 3) [Convolution] + (Unnamed Layer* 4) [Scale] + (Unnamed Layer* 5) [Activation], Tactic: 8839784824303350101, (Unnamed Layer* 2) [Activation]_output[Half(1,64,128,150)] -> (Unnamed Layer* 5) [Activation]_output[Half(1,64,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 6) [Convolution] + (Unnamed Layer* 7) [Scale] + (Unnamed Layer* 8) [Activation], Tactic: 8839784824303350101, (Unnamed Layer* 5) [Activation]_output[Half(1,64,128,150)] -> (Unnamed Layer* 8) [Activation]_output[Half(1,64,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 9) [Convolution] + (Unnamed Layer* 10) [Scale] + (Unnamed Layer* 11) [Activation], Tactic: 8839784824303350101, (Unnamed Layer* 8) [Activation]_output[Half(1,64,128,150)] -> (Unnamed Layer* 11) [Activation]_output[Half(1,64,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 12) [Convolution] + (Unnamed Layer* 13) [Scale] + (Unnamed Layer* 14) [Activation], Tactic: 1723736032573714698, (Unnamed Layer* 11) [Activation]_output[Half(1,64,128,150)] -> (Unnamed Layer* 14) [Activation]_output[Half(1,128,64,75)]
Layer(CaskConvolution): (Unnamed Layer* 15) [Convolution] + (Unnamed Layer* 16) [Scale] + (Unnamed Layer* 17) [Activation], Tactic: 1832046141070096030, (Unnamed Layer* 14) [Activation]_output[Half(1,128,64,75)] -> (Unnamed Layer* 17) [Activation]_output[Half(1,128,64,75)]
Layer(CaskConvolution): (Unnamed Layer* 18) [Convolution] + (Unnamed Layer* 19) [Scale] + (Unnamed Layer* 20) [Activation], Tactic: 1832046141070096030, (Unnamed Layer* 17) [Activation]_output[Half(1,128,64,75)] -> (Unnamed Layer* 20) [Activation]_output[Half(1,128,64,75)]
Layer(CaskConvolution): (Unnamed Layer* 21) [Convolution] + (Unnamed Layer* 22) [Scale] + (Unnamed Layer* 23) [Activation], Tactic: 1832046141070096030, (Unnamed Layer* 20) [Activation]_output[Half(1,128,64,75)] -> (Unnamed Layer* 23) [Activation]_output[Half(1,128,64,75)]
Layer(GemmDeconvolution): (Unnamed Layer* 24) [Deconvolution] + (Unnamed Layer* 25) [Scale] + (Unnamed Layer* 26) [Activation], Tactic: 0, (Unnamed Layer* 11) [Activation]_output[Half(1,64,128,150)] -> (Unnamed Layer* 26) [Activation]_output[Half(1,128,128,150)]
Layer(GemmDeconvolution): (Unnamed Layer* 27) [Deconvolution] + (Unnamed Layer* 28) [Scale] + (Unnamed Layer* 29) [Activation], Tactic: 0, (Unnamed Layer* 23) [Activation]_output[Half(1,128,64,75)] -> (Unnamed Layer* 29) [Activation]_output[Half(1,128,128,150)]
Layer(Reformat): (Unnamed Layer* 26) [Activation]_output copy, Tactic: 1002, (Unnamed Layer* 26) [Activation]_output[Half(1,128,128,150)] -> (Unnamed Layer* 30) [Concatenation]_output[Half(1,128,128,150)]
Layer(Reformat): (Unnamed Layer* 29) [Activation]_output copy, Tactic: 1002, (Unnamed Layer* 29) [Activation]_output[Half(1,128,128,150)] -> (Unnamed Layer* 30) [Concatenation]_output[Half(1,128,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 31) [Convolution] + (Unnamed Layer* 32) [Scale] + (Unnamed Layer* 33) [Activation], Tactic: 1832046141070096030, (Unnamed Layer* 30) [Concatenation]_output[Half(1,256,128,150)] -> (Unnamed Layer* 33) [Activation]_output[Half(1,64,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation], Tactic: 8839784824303350101, (Unnamed Layer* 33) [Activation]_output[Half(1,64,128,150)] -> (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation][Half(1,320,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 37) [Convolution], Tactic: 4503233883285355107, (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation][Half(1,64,128,150)] -> Reformatted Output Tensor 0 to (Unnamed Layer* 37) [Convolution][Half(1,2,128,150)]
Layer(Reformat): Reformatting CopyNode for Output Tensor 0 to (Unnamed Layer* 37) [Convolution], Tactic: 0, Reformatted Output Tensor 0 to (Unnamed Layer* 37) [Convolution][Half(1,2,128,150)] -> final_out_0[Half(1,2,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 41) [Convolution], Tactic: 4503233883285355107, (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation][Half(1,64,128,150)] -> Reformatted Output Tensor 0 to (Unnamed Layer* 41) [Convolution][Half(1,1,128,150)]
Layer(Reformat): Reformatting CopyNode for Output Tensor 0 to (Unnamed Layer* 41) [Convolution], Tactic: 0, Reformatted Output Tensor 0 to (Unnamed Layer* 41) [Convolution][Half(1,1,128,150)] -> final_out_01[Half(1,1,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 45) [Convolution], Tactic: 4503233883285355107, (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation][Half(1,64,128,150)] -> Reformatted Output Tensor 0 to (Unnamed Layer* 45) [Convolution][Half(1,3,128,150)]
Layer(Reformat): Reformatting CopyNode for Output Tensor 0 to (Unnamed Layer* 45) [Convolution], Tactic: 0, Reformatted Output Tensor 0 to (Unnamed Layer* 45) [Convolution][Half(1,3,128,150)] -> final_out_02[Half(1,3,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 49) [Convolution], Tactic: 4503233883285355107, (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation][Half(1,64,128,150)] -> Reformatted Output Tensor 0 to (Unnamed Layer* 49) [Convolution][Half(1,2,128,150)]
Layer(Reformat): Reformatting CopyNode for Output Tensor 0 to (Unnamed Layer* 49) [Convolution], Tactic: 0, Reformatted Output Tensor 0 to (Unnamed Layer* 49) [Convolution][Half(1,2,128,150)] -> final_out_03[Half(1,2,128,150)]
Layer(CaskConvolution): (Unnamed Layer* 53) [Convolution], Tactic: 4503233883285355107, (Unnamed Layer* 34) [Convolution] + (Unnamed Layer* 35) [Scale] + (Unnamed Layer* 36) [Activation] || (Unnamed Layer* 38) [Convolution] + (Unnamed Layer* 39) [Scale] + (Unnamed Layer* 40) [Activation] || (Unnamed Layer* 42) [Convolution] + (Unnamed Layer* 43) [Scale] + (Unnamed Layer* 44) [Activation] || (Unnamed Layer* 46) [Convolution] + (Unnamed Layer* 47) [Scale] + (Unnamed Layer* 48) [Activation] || (Unnamed Layer* 50) [Convolution] + (Unnamed Layer* 51) [Scale] + (Unnamed Layer* 52) [Activation][Half(1,64,128,150)] -> Reformatted Output Tensor 0 to (Unnamed Layer* 53) [Convolution][Half(1,5,128,150)]
Layer(Reformat): Reformatting CopyNode for Output Tensor 0 to (Unnamed Layer* 53) [Convolution], Tactic: 0, Reformatted Output Tensor 0 to (Unnamed Layer* 53) [Convolution][Half(1,5,128,150)] -> final_out_04[Float(1,5,128,150)]
INFO: [MemUsageChange] TensorRT-managed allocation in building engine: CPU +2, GPU +4, now: CPU 2, GPU 4 (MiB)`

**Comment by c90mkl** [comment]
This log helps. I have 5 outputs in total, with trt 8, only one last output is right, and this log shows only `final_out_04 `is in float, others are in half, so outputting all 5 results without half->float conversion will have the result that I got. This is weird, I believe trt 7 set all outputs to float in default. @nvpohanh Why do we have such a divergence between 7 and 8? What solution do we have in this case?  like `network->getOutput(index)->setType(DataType::kHALF)` ?

**Comment by nvpohanh** [comment]
I don't think there should be any divergence, but anyway, could you try setting `network->getOutput(index)->setType(DataType::kHALF)` or `network->getOutput(index)->setType(DataType::kFLOAT)` depending on which dtype you want? Thanks

**Comment by c90mkl** [comment]
> I don't think there should be any divergence, but anyway, could you try setting `network->getOutput(index)->setType(DataType::kHALF)` or `network->getOutput(index)->setType(DataType::kFLOAT)` depending on which dtype you want? Thanks

After I manually set all outputs to float, the results are normal now in trt 8. I print the log of the same network  in trt 7, without `network->getOutput(index)->setType(DataType::kFLOAT)` , final output layers are as following:

> VERBOSE: Layer(Reformat): (Unnamed Layer* 37) [Convolution] output reformatter 0, Tactic: 0, (Unnamed Layer* 37) [Convolution] output to be reformatted 0[Half(2,128,150)] -> final_out_0[Float(2,128,150)]
> 
> VERBOSE: Layer(Reformat): (Unnamed Layer* 41) [Convolution] output reformatter 0, Tactic: 0, (Unnamed Layer* 41) [Convolution] output to be reformatted 0[Half(1,128,150)] -> final_out_01[Float(1,128,150)]
> 
> VERBOSE: Layer(Reformat): (Unnamed Layer* 45) [Convolution] output reformatter 0, Tactic: 0, (Unnamed Layer* 45) [Convolution] output to be reformatted 0[Half(3,128,150)] -> final_out_02[Float(3,128,150)]
> 
> VERBOSE: Layer(Reformat): (Unnamed Layer* 49) [Convolution] output reformatter 0, Tactic: 0, (Unnamed Layer* 49) [Convolution] output to be reformatted 0[Half(2,128,150)] -> final_out_03[Float(2,128,150)]
> 
> VERBOSE: Layer(Reformat): (Unnamed Layer* 53) [Convolution] output reformatter 0, Tactic: 0, (Unnamed Layer* 53) [Convolution] output to be reformatted 0[Half(5,128,150)] -> final_out_04[Float(5,128,150)]

all outputs are in float. 

So with half-precision net input and fp16 mode, in trt 7, all 5 output layers give me float result;  In trt 8, with fp16 input, only the last one output layer has float result. The other 4 layers are still in half-precision unless I use `network->getOutput(index)->setType(DataType::kFLOAT)`. This is the divergence I got from my case.

**Comment by nvpohanh** [comment]
Could you try TensorRT 8.2 and/or 8.4 EA to see if the issue still exists? If so, we can take a look

**Comment by c90mkl** [comment]
> Could you try TensorRT 8.2 and/or 8.4 EA to see if the issue still exists? If so, we can take a look

I tested it in 8.2.1.8, the problem is reproduced.  Sorry that I don't have time for 8.4 EA testing.

**Comment by nvpohanh** [comment]
@c90mkl could you share your ONNX file? Maybe the ONNX file already mark the output tensors' dtypes?

**Comment by c90mkl** [comment]
> @c90mkl could you share your ONNX file? Maybe the ONNX file already mark the output tensors' dtypes?

I didn't use ONNX. The network is built by using TRT C++ API like `addConvolutionNd`, `addActivation`, e.t.c.

**Comment by nvpohanh** [comment]
I see. Then could you provide the code for us to repro this issue? Or do you think the current workaround is sufficient?

The rules in TRT should be: By default, we assume all input and output tensors are in kFLOAT. If you want any of them to be kHALF, you should explicit set them. That said, I am not sure why in your case some outputs became kHALF automatically.

**Comment by c90mkl** [comment]
> I see. Then could you provide the code for us to repro this issue? Or do you think the current workaround is sufficient?
> 
> The rules in TRT should be: By default, we assume all input and output tensors are in kFLOAT. If you want any of them to be kHALF, you should explicit set them. That said, I am not sure why in your case some outputs became kHALF automatically.

Thanks, the methods are sufficient for my current. I'll provide the code once I have time.

**Comment by nvpohanh** [comment]
Closing this issue for now. Thanks
