### ISSUE TITLE
How to perform different models in different gpu simultaneously

### ISSUE THREAD

**Issue by zacario-li** [NVIDIA/TensorRT#2014]
Hi,
    I have 4 models, so I installed 4 GPUs(RTX3090). I loaded 4 models into different GPUs(I've checked it).
    Is there any way to perform 4 models in different GPUs simultaneously?

**Comment by nvpohanh** [comment]
Yes, you can. Just create an execution context on each gpu and run them in parallel. 

If you are still not sure how to do that, I recommend that you try Triton inference server, which does it for you: https://github.com/triton-inference-server/server

**Comment by zacario-li** [comment]
@nvpohanh
Thanks for your suggestion.
I use asyncio and concurrent.futures.ThreadPoolExecutor to try this, but always got 
```
"PyCUDA ERROR: The context stack was not empty upon module cleanup."
```
Is there any way to use python API to do this?

**Comment by nvpohanh** [comment]
@zacario-li Could you share your code?

**Comment by nvpohanh** [comment]
@zacario-li According to this: https://stackoverflow.com/questions/65416902/cupy-error-when-pushing-popping-pycuda-context

`make_context()` also pushes the context to stack, so currently you have 8 contexts pushed to stack but only call `pop()` 4 times.

**Comment by zacario-li** [comment]
@nvpohanh thank you very much, fixed it.
solution:
```
ctxlist = [cuda.Device(i).make_context() for i in range(torch.cuda.device_count())]# after this line code, add another line
# add pop
[ctxlist[I].pop() for I in range(torch.cuda.device_count())] # key point here
```

**Comment by nvpohanh** [comment]
cool! then I will close this.

**Comment by tongchangD** [comment]
what is  libcudart.so

**Comment by nvpohanh** [comment]
libcudart.so is CUDA runtime library (i.e. shared object). It should be installed when you install CUDA toolkit
