### ISSUE TITLE
/usr/bin/ld: cannot find -lnvinfer

### ISSUE THREAD

**Issue by EdwardVincentMa** [NVIDIA/TensorRT#2017]
[ 81%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin/common/kernels/kernel.cpp.o
[ 83%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin/cc_rcnn_plugin.cpp.o
[ 84%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin/plugin_common.cpp.o
[ 86%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin/cc_plugin_register.cpp.o
[ 87%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin_v2/nmsPlugin/nmsPlugin.cpp.o
[ 89%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin_v2/cc_cube_rcnn_plugin_v2.cpp.o
[ 90%] Building CXX object CMakeFiles/cc_plugin.dir/process/plugin_v2/cc_rproi_plugin_v2.cpp.o
[ 92%] Linking CXX static library libcc_plugin.a
[ 92%] Built target cc_plugin
[ 93%] Building NVCC (Device) object CMakeFiles/caffe2trt.dir/process/kernel/caffe2trt_generated_resize_and_shuffle.cu.o
[ 95%] Building NVCC (Device) object CMakeFiles/caffe2trt.dir/process/kernel/caffe2trt_generated_image_preprocess.cu.o
[ 96%] Building CXX object CMakeFiles/caffe2trt.dir/process/convert_process.cpp.o
[ 98%] Building CXX object CMakeFiles/caffe2trt.dir/caffe2trt.cpp.o
[100%] Linking CXX executable ../bin/caffe2trt
/usr/bin/ld: cannot find -lnvinfer
/usr/bin/ld: cannot find -lnvinfer_plugin
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/caffe2trt.dir/build.make:186: ../bin/caffe2trt] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/caffe2trt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by nvpohanh** [comment]
@EdwardVincentMa Where did you install `libnvinfer.so` at?

**Comment by EdwardVincentMa** [comment]
> 

i did not install libnvinfer.so, how to install libnvinfer?

**Comment by nvpohanh** [comment]
@EdwardVincentMa Please refer to the the README: https://github.com/NVIDIA/TensorRT#prerequisites

```
To build the TensorRT-OSS components, you will first need the following software packages.

TensorRT GA build
- [TensorRT](https://developer.nvidia.com/nvidia-tensorrt-download) v8.2.5.1
```

**Comment by nvpohanh** [comment]
Closing for now due to >14 days without response. Please reopen if the issue still exists. Thanks
