### ISSUE TITLE
Missing Data for the Samples

### ISSUE THREAD

**Issue by ismet-dagli** [NVIDIA/TensorRT#2018]
## Description

I'm currently using Xavier AGX and AGX Orin platforms with 7.1.3 and 8.4.0 versions respectively. Many of the samples can't run because they throw missing data errors. Here are some of the names from my attempts:

-sample_fasterRCNN
-sample_uff_ssd
-sample_int8
-sample_ssd
-sample_uff_mask_rcnn

## Environment

**TensorRT Version**:  8.4.0
**NVIDIA GPU**:  ORIN AGX with NVIDIA Ampere architecture 
**NVIDIA Driver Version**: 
**CUDA Version**:  11.4
**CUDNN Version**: 
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

$Go to <Tensorrt_directory>/samples
$make (compile all the samples)
$Go to <Tensorrt_directory>/bin
$Run the samples seperately

**Comment by zerollzeng** [comment]
there is a corresponding readme in each sample that contains the data preparation like https://github.com/NVIDIA/TensorRT/tree/main/samples/sampleFasterRCNN,  Perhaps that's what you are missing.

**Comment by nvpohanh** [comment]
Closing for now since there is not response for >14 days. Please reopen if the issue still exists. Thanks
