### ISSUE TITLE
Normalize_TRT Plugin runtime Error!!!

### ISSUE THREAD

**Issue by DataXujing** [NVIDIA/TensorRT#2020]
Input Data Dim: [ 20000,1,1,31], and I applied TensorRT 8.2.3 API ， When I use like :

```
def torch_normalize_plugin():
    '''调用了TensorRT 官方的版本，发现有问题

    '''
    plugin = None
    for plugin_creator in PLUGIN_CREATORS:
        if plugin_creator.name == "Normalize_TRT":
            acrossSpatial = trt.PluginField("acrossSpatial", np.array([1]),trt.PluginFieldType.INT32)
            channelShared  = trt.PluginField("channelShared", np.array([1]),trt.PluginFieldType.INT32)
            eps = trt.PluginField("eps", np.array([1e-14],dtype=np.float32) , trt.PluginFieldType.FLOAT32)
            weights = trt.PluginField("weights", np.array([1.0],dtype=np.float32) , trt.PluginFieldType.FLOAT32)
            nbweights = trt.PluginField("nbWeights", np.array([1],dtype=np.int32) , trt.PluginFieldType.INT32)
            plugin_version = trt.PluginField("plugin_version", np.array(["1"],dtype=np.string_), trt.PluginFieldType.CHAR)

            field_collection = trt.PluginFieldCollection([acrossSpatial,channelShared,eps,weights,nbweights,plugin_version])
            plugin = plugin_creator.create_plugin(name="Normalize_TRT", field_collection=field_collection)
    return plugin

norm = network.add_plugin_v2(inputs=[transpose_1.get_output(0)], plugin=torch_normalize_plugin())
```
to construct the network,

I build the engine successfull!!! but in runtime, I get an Error: 

```
Segmentation fault (core dumped)
```

Does the Normalize_TRT could't support TensorRT 8.2.3?

**Comment by nvpohanh** [comment]
@DataXujing Could you show your code about how to load the engine and run the inference? thanks

**Comment by nvpohanh** [comment]
@DataXujing Thanks for the code. We will try repro the issue.

Meanwhile, could you help us to figure out which function call caused the seg fault? Did it fail at `deserialize_cuda_engine()` or `cudaMemcpy()` or `execute_v2()`? Thanks

**Comment by DataXujing** [comment]
@nvpohanh `execute_v2()` caused the seg fault!

**Comment by nvpohanh** [comment]
I can repro this issue. I have filed internal tracker (id: 3668545) and we will debug/fix this. Will let you know when we fix it. Thanks for reporting this issue.

**Comment by DataXujing** [comment]
OK， Thank you for your reply！ @nvpohanh

**Comment by nvpohanh** [comment]
This has been fixed internally and the fix will be available in next release. Thanks for reporting this.

**Comment by ttyio** [comment]
The 8.5 is released, closing and thanks!
