### ISSUE TITLE
How to share weights between different engines?

### ISSUE THREAD

**Issue by RichardWooSJTU** [NVIDIA/TensorRT#2024]
In our application, we have to build two or more engines whose layers can use the same weights. However, when we build these engines directly, the device memory allocated for weights will be copied many times. So is there any methods to make these engines share device memory?

For example: 
```
std::vector<float> weights(4096*4096, 0.f);
nvinfer1::Weights w{nvinfer1::DataType::kFLOAT, weights.data(), static_cast<int64_t>(weights.size())};
IConvolutionLayer* conv1x1_layer = nullptr;
for (int i = 0; i < nlayers; ++i) {
      conv1x1_layer = network->addConvolutionNd(
          *x0, C, Dims{2, {1, 1}}, w, nvinfer1::Weights{});
      conv1x1_layer->setName(("conv1x1_layer_" + std::to_string(i)).c_str());
      weight->getOutput(0)->setDynamicRange(-1, 1);
      conv1x1_layer->getInput(0)->setDynamicRange(-1, 1);
      conv1x1_layer->getOutput(0)->setDynamicRange(-1, 1);
      conv1x1_layer->setPrecision(nvinfer1::DataType::kHALF);

      x0 = conv1x1_layer->getOutput(0);
}
network->markOutput(*conv1x1_layer->getOutput(0));

auto* engine = builder->buildEngineWithConfig(*network, *config);
auto* engine2 = builder->buildEngineWithConfig(*network, *config);
```

**Comment by zerollzeng** [comment]
If I understand correctly, the layers and weights are all the same across engines. Can you try to build 1 engine and create multiple ExecutionContext for the engine? It should satisfy your need. 

refer to https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_execution_context.html#details

**Comment by RichardWooSJTU** [comment]
In our real application, the two engines perform different tasks so that they have different layers except the convolution layers, . This example is just to reduce the differences between engines as much as possible. If two identical engines cannot share the weights,  we have to give up tensorrt.

**Comment by RichardWooSJTU** [comment]
@nvpohanh Thank you very much for your advice! I think I'm going to give that a try

**Comment by RichardWooSJTU** [comment]
Any updates?

**Comment by nvpohanh** [comment]
Let me check internally to see if there is any solution to this issue.

**Comment by nvpohanh** [comment]
There are two possible ways to do this:

(1) Use Concat at the beginning of the shared backbone part and Slice at the end of the shared part

```
inputA --v                              .-> different_layers_A -> outputA
         Concat -> common_convs -> Slice 
inputB --^                              `-> different_layers_B -> outputB
```

And set the `Start` and the `Size` field of the Slice layer to the shape of `inputA`. Then, you can set the shape of inputA and inputB at runtime to select which branch to run.

(2) Alternatively, an easier way is to break the network into three engines:

Engine A: `input -> common_convs -> common_output`
Engine B: `common_output -> different_layers_A -> outputA`
Engine C: `common_output -> different_layers_B -> outputB`

Then at runtime, you can choose to run engine A+B or engine A+C depending on which branch is desired.

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
