### ISSUE TITLE
!trtexec throughput higher than Torch_TensorRT

### ISSUE THREAD

**Issue by harishprabhala** [NVIDIA/TensorRT#2032]
Hi - When I run trtexec to calculate the throughput and latency, the numbers are much higher as compared to when I do the benchmarks using the below code

```
cudnn.benchmark = True

def benchmark(model, input_shape=(1024, 3, 512, 512), dtype='fp32', nwarmup=50, nruns=1000):
    input_data = torch.randn(input_shape)
    input_data = input_data.to("cuda")
    if dtype=='fp16':
        input_data = input_data.half()
        
    print("Warm up ...")
    with torch.no_grad():
        for _ in range(nwarmup):
            features = model(input_data)
    torch.cuda.synchronize()
    print("Start timing ...")
    timings = []
    with torch.no_grad():
        for i in range(1, nruns+1):
            start_time = time.time()
            pred_loc  = model(input_data)
            torch.cuda.synchronize()
            end_time = time.time()
            timings.append(end_time - start_time)
            if i%10==0:
                print('Iteration %d/%d, avg batch time %.2f ms'%(i, nruns, np.mean(timings)*1000))

    print("Input shape:", input_data.size())
    print('Average throughput: %.2f images/second'%(input_shape[0]/np.mean(timings)))

```
trtexec gives atleast 40% higher throughput than the above code. Why is that? Is there a way to compute the performance metrics in Python similar to how trtexec does?

**Comment by nvpohanh** [comment]
@harishprabhala Did you turn on FP16 when building Torch-TRT engine? something like:

```
trt_model_fp16 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((128, 3, 224, 224), dtype=torch.half)],
    enabled_precisions = {torch.half}, # Run with FP32
    workspace_size = 1 << 22
)
```

See: https://pytorch.org/TensorRT/_notebooks/Resnet50-example.html

**Comment by harishprabhala** [comment]
Hi @nvpohanh. Yes I have turned on FP16 while compiling in Torch-TRT.

**Comment by nvpohanh** [comment]
Could you share your code and model so that we can repro and debug the issue? Would be great if you can also attach verbose logs by enabling VERBOSE in TRT logger. Thanks

**Comment by harishprabhala** [comment]
This is how I compiled and below are the inference metrics.

```
trt_model = torch_tensorrt.compile(model, 
    inputs= [torch_tensorrt.Input((1, 3, 224, 224))],
    enabled_precisions= { torch_tensorrt.dtype.half} # Run with FP16
)

benchmark(trt_model, input_shape=(1, 3, 224, 224), nruns=100)

Warm up ...
Start timing ...
Iteration 10/100, avg batch time 0.83 ms
Iteration 20/100, avg batch time 0.83 ms
Iteration 30/100, avg batch time 0.83 ms
Iteration 40/100, avg batch time 0.83 ms
Iteration 50/100, avg batch time 0.83 ms
Iteration 60/100, avg batch time 0.83 ms
Iteration 70/100, avg batch time 0.83 ms
Iteration 80/100, avg batch time 1.02 ms
Iteration 90/100, avg batch time 1.01 ms
Iteration 100/100, avg batch time 1.01 ms
Input shape: torch.Size([1, 3, 224, 224])
Average throughput: 991.74 images/second
```

For trtexec, below are the inference for FP16
```
Throughput: 1382.42 qps
[06/06/2022-05:33:12] [I] Latency: min = 0.723724 ms, max = 2.06177 ms, mean = 0.771591 ms, median = 0.731445 ms, percentile(99%) = 0.973877 ms
[06/06/2022-05:33:12] [I] End-to-End Host Latency: min = 0.740112 ms, max = 2.60913 ms, mean = 1.35606 ms, median = 1.32202 ms, percentile(99%) = 1.91306 ms
[06/06/2022-05:33:12] [I] Enqueue Time: min = 0.151184 ms, max = 1.02441 ms, mean = 0.188849 ms, median = 0.177856 ms, percentile(99%) = 0.349609 ms
[06/06/2022-05:33:12] [I] H2D Latency: min = 0.050293 ms, max = 0.115723 ms, mean = 0.0537922 ms, median = 0.0529785 ms, percentile(99%) = 0.0754395 ms
[06/06/2022-05:33:12] [I] GPU Compute Time: min = 0.668091 ms, max = 2.00513 ms, mean = 0.714744 ms, median = 0.675293 ms, percentile(99%) = 0.914139 ms
[06/06/2022-05:33:12] [I] D2H Latency: min = 0.00219727 ms, max = 0.0319824 ms, mean = 0.00305397 ms, median = 0.00292969 ms, percentile(99%) = 0.00439453 ms
[06/06/2022-05:33:12] [I] Total Host Walltime: 3.00271 s
[06/06/2022-05:33:12] [I] Total GPU Compute Time: 2.9669 s
[06/06/2022-05:33:12] [I] Explanations of the performance metrics are printed in the verbose logs.
```

**Comment by nvpohanh** [comment]
Could you share the verbose logs (see: https://pytorch.org/TensorRT/py_api/logging.html ) and the model? Thanks

**Comment by nvpohanh** [comment]
For trtexec, add `--verbose --profilingVerbosity=detailed --dumpLayerInfo`

**Comment by harishprabhala** [comment]
> Could you share your code and model so that we can repro and debug the issue? Would be great if you can also attach verbose logs by enabling VERBOSE in TRT logger. Thanks

I used Pytorch ResNet50 and reproduced the code exactly in this link -> https://developer.nvidia.com/blog/accelerating-inference-up-to-6x-faster-in-pytorch-with-torch-tensorrt/

Fot trtexec, I took Pytorch Resnet50, converted to onnx and ran trtexec buildengine with fp16 flag.
```

import torchvision.models as models
import torch
import torch.onnx

# load the pretrained model
resnet50 = models.resnet50(pretrained=True, progress=False).eval()
BATCH_SIZE=1
dummy_input=torch.randn(BATCH_SIZE, 3, 224, 224)

torch.onnx.export(resnet50, dummy_input, "/workspace/TensorRT/samples/python/efficientnet/onnx/resnet50.onnx", verbose=False)
```

**Comment by nvpohanh** [comment]
I see. Thanks. Which GPU and which TRT version did you use?

**Comment by harishprabhala** [comment]
I am using RTX 2080Ti and TRT version is 8.2.4

**Comment by harishprabhala** [comment]
Basically I am looking to reproduce the same inference metrics as trtexec through a python script. With the above benchmark script, the metrics are lower as compared to trtexec.

Is trtexec faster because it runs the .engine file in C++?

**Comment by nvpohanh** [comment]
It's hard to tell without further information like verbose logs or Nsight Systems profiles as there are many possibilities of the performance gaps.

**Comment by harishprabhala** [comment]
Is there a way to export the verbose log into a txt file in trtexec? I am not able to copy the whole log into a text file.

**Comment by harishprabhala** [comment]
Also, can you replicate the same issue once at your end? Basically if you can take a .engine file and run it through a python inference code, you'll know if there is performance gap as compared to trtexec inference.

**Comment by harishprabhala** [comment]
Actually, I have figured out a python code to get the exact same throughput and latency metrics as trtexec. Thanks for your help. Cheers!

**Comment by nvpohanh** [comment]
Thanks! What did you do to fix it? Maybe we can improve our code or documentation better.

**Comment by harishprabhala** [comment]
I just took the inference code from here, removed the scoring part of the code (because we're just looking for throughput and latency) and added the below code at the end to calculate the throughput+latency

```
import time
import torch

input_shape = (1,3,224,224)

batch = input_shape
iterations = 100
times = []
for i in range(1000):  # GPU warmup iterations
    trt_infer.infer(batch)
with torch.no_grad():
    for i in range(iterations):
        start = time.time()
        trt_infer.infer(batch)
        torch.cuda.synchronize()
        end_time = time.time()
        times.append(end_time - start)
        print("Iteration {} / {}".format(i + 1, iterations), end="\r")
    print("Benchmark results include time for H2D and D2H memory copies")
    print("Average Latency: {:.3f} ms".format(
        1000 * np.average(times)))
    print("Average Throughput: {:.1f} ips".format(
    trt_infer.batch_size / np.average(times)))
```

**Comment by nvpohanh** [comment]
Thanks for sharing the solution. I am going to close this issue.
