### ISSUE TITLE
8.2.5 or 8.4 ?

### ISSUE THREAD

**Issue by deephog** [NVIDIA/TensorRT#2033]
Hi Developers,

I realized that the 8.2 version has been consistently updated while the 8.4 version stayed the same for several months already. And I believe that when I first used 8.4, there was a GA version instead of just EA version (maybe I am delusional). It looks to me that the 8.4 version is "abandoned" for some reason. The question I would like to ask is that, I know that 8.2 is the more stable version, but is 8.4 still the most advanced version feature-wise? In there still anything that 8.4 can do but 8.2 cannot? Thanks!

**Comment by nvpohanh** [comment]
@deephog TRT 8.4.0 is an EA release. We are still working on the GA release and it should be released soon (maybe in something like a few weeks). As you asked, TRT 8.4.0 has more bug fixes and newer features and may have solved some issues that appeared in TRT 8.2.x.

**Comment by deephog** [comment]
> @deephog TRT 8.4.0 is an EA release. We are still working on the GA release and it should be released soon (maybe in something like a few weeks). As you asked, TRT 8.4.0 has more bug fixes and newer features and may have solved some issues that appeared in TRT 8.2.
