### ISSUE TITLE
buildSerializedNetwork error

### ISSUE THREAD

**Issue by yuefanhao** [NVIDIA/TensorRT#2034]
Hi,

when I try to buildSerializedNetwork, some errors occured: 

[E] [TRT] 2: [elementWiseRunner.cpp::ElementWiseRunner::118] Error Code 2: Internal Error (Assertion z.d[i] == broadcast(x.d[i], y.d[i]) || isSlotReference(z.d[i]) failed. )
[E] [TRT] 2: [builder.cpp::buildSerializedNetwork::619] Error Code 2: Internal Error (Assertion engine != nullptr failed. )

**Comment by nvpohanh** [comment]
@yuefanhao Could you share the ONNX file you used so that we can best assist you? Thanks

**Comment by yuefanhao** [comment]
@nvpohanh the ONNX file size too big, could you leave your email so that I can send It to you?

**Comment by nvpohanh** [comment]
Could you upload it to https://drive.google.com/drive/folders/12_1Nk954FaN4WQp_iZ2W6a4KUkTcejfh?usp=sharing ? 

Please also fill in additional information following this template. Thanks

```
## Description

<!-- A clear and concise description of the bug or issue. -->


## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 


## Relevant Files

<!-- Please include links to any models, data, files, or scripts necessary to reproduce your issue. (Github repo, Google Drive/Dropbox, etc.) -->


## Steps To Reproduce

<!-- 
  Craft a minimal bug report following this guide - https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

  Please include:
  * Exact steps/commands to build your repro
  * Exact steps/commands to run your repro
  * Full traceback of errors encountered 
-->

```

**Comment by yuefanhao** [comment]
@nvpohanh
Hi,
I have uploaded all my models and code files to the address you provided.

Here is some additional information

> ```
> ## Description
> 
>My model contains multiple dynamic size inputs so the problem seems to be related to this.Because when the kOPT parameter in the setDimension function sets different values, it has different errors.
> 
> ## Environment
> 
> **TensorRT Version**:  8.4.0.6
> **NVIDIA GPU**: GTX2080
> **NVIDIA Driver Version**: 510.73.05
> **CUDA Version**: 11.6
> **Operating System**: Ubuntu 20.04
> **PyTorch Version (if applicable)**: 1.11
> 
> ## Relevant Files
> 
> Relevant files are uploaded to google drive, including how to reproduce this problem.

Thank you for your help.

**Comment by yuefanhao** [comment]
@nvpohanh Hi, is there any progress on this issue? Thank you.

**Comment by yuefanhao** [comment]
May be I should check the model output shape, thank you.
