### ISSUE TITLE
The gather operator produces a loss of precision

### ISSUE THREAD

**Issue by nanbatian119** [NVIDIA/TensorRT#2037]
tensorrt convert gather operator from onnx produces a loss of precison

TensorRT Version:  8.4.1.4
NVIDIA GPU: NVIDIA A10
NVIDIA Driver Version: 510.73.08
CUDA Version：11.6
CUDNN Version: 8.4
Operating System: Ubuntu 20.04.4 LTS
Python Version (if applicable): 3.8.10
PyTorch Version (if applicable): 1.11.0

please check this respository to reproduce this bug

[(https://github.com/nanbatian119/onehot2gather.git)]

when use this code to compare onnx output and trt output
`np.testing.assert_almost_equal(gather_onnx_out, trt_out, 5)`

the ouput is 
`Max absolute difference: 0.2328076 Max relative difference: 83.76954`

the loss is pretty much

**Comment by zerollzeng** [comment]
Can you kindly provide the onnx model to us so that we can reproduce it quickly?

**Comment by nanbatian119** [comment]
> Can you kindly provide the onnx model to us so that we can reproduce it quickly?

https://github.com/nanbatian119/onehot2gather/blob/main/onnx/gather_net.onnx

I have uploaded to this respository , [https://github.com/nanbatian119/onehot2gather.git](url), please check it.

**Comment by nvpohanh** [comment]
@nanbatian119 Could you check what is the `i.dtype.itemsize`? TRT doesn't support INT64, so you will have to convert `self.rel_pos` to INT32 first.

```
        inputs = [self.rel_pos]
        bindings = []
        for i in inputs:
            d_i = cuda.mem_alloc(i.size * i.dtype.itemsize)
            cuda.memcpy_htod(d_i, i)
            bindings.append(int(d_i))
```

**Comment by nanbatian119** [comment]
> @nanbatian119 Could you check what is the `i.dtype.itemsize`? TRT doesn't support INT64, so you will have to convert `self.rel_pos` to INT32 first.
> 
> ```
>         inputs = [self.rel_pos]
>         bindings = []
>         for i in inputs:
>             d_i = cuda.mem_alloc(i.size * i.dtype.itemsize)
>             cuda.memcpy_htod(d_i, i)
>             bindings.append(int(d_i))
> ```

Thanks very much. It solves my problem.
will all of the int64 type in the onnx graph  be converted to int32?

**Comment by nvpohanh** [comment]
Yes, TRT currently casts all INT64 values to INT32.

Closing this issue
