### ISSUE TITLE
what is the difference between demoBERT and a BERT engine converted by onnx-tensorrt?

### ISSUE THREAD

**Issue by Tengfei09** [NVIDIA/TensorRT#2038]
## Description

Under the same condition,
- BERT-Large model
- batch_size = 64
- seqlen=384
- data precision=fp16

using TF checkpoint as a source model(demoBERT), the total execution time of the converted TensorRT engine is **100.91**ms.
using ONNX as a source model, the total execution time of the converted TensorRT engine is **113.38**ms.

As I know, _demoBERT_ will use predefined plugins to fuse MHA or LayerNorm kernels, while _onnx-tensorrt_ will find the self-attention pattern and then fuse them. 

My question:
Why is there around a 10ms gap between the two methods? 
Does this mean that the self-attention pattern is not as good as the predefined kernel fusion(plugins)?

 
## Environment

**TensorRT Version**: 8.2.4
**NVIDIA GPU**: A100-40GB
**NVIDIA Driver Version**: 510.47
**CUDA Version**: 11.6
**CUDNN Version**: 8.4
**Operating System**: Ubuntu20.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: tensorrt:22.04-py3

## Steps To Reproduce

Followed by the provided [instructions](https://github.com/NVIDIA/TensorRT/tree/main/demo/BERT), I have built a bert_large_batchsize64_seqlen384_fp16.engine sucessfully.

After in-depth performance analysis, I dumped the avg execution time of each layer by adding the _--exportProfile_ flag, then found that the total execution time is **100.91ms**(due to word limitations, the detailed info could be downloaded from[bert_profile.csv](https://github.com/NVIDIA/TensorRT/files/8854686/bert.csv))
```

trtexec --loadEngine=engines/bert_large_batchsize64_seqlen384_fp16.engine --shapes=input_ids:64x384,segment_ids:64x384,input_mask:64x384 --workspace=4096 
cls_squad_logits --fp16 --verbose --exportProfile=FromTFcheckpoint_bert_large_perf.log
```

Then I found another bert_large model on the official Nvidia [website](https://catalog.ngc.nvidia.com/orgs/nvidia/models/bert_pyt_onnx_large_qa_squad11_amp), which is an onnx format. Then I used the _onnx-tensorrt_ to convert this model and dump the avg execution time of each layer. 

`trtexec --onnx=models/fine-tuned/bert_large_v1_1.onnx --saveEngine=bert_bs64_fp16.engine --shapes=input_ids:64x384,segment_ids:64x384,input_mask:64x384 --workspace=4096 --verbose --fp16   --exportProfile=FromOnnx_bert_large_perf.log `

As you can see, the total time is **113.38ms**

> [
>   { "count" : 31 }
> , { "name" : "node_of_412", "timeMs" : 1.24211, "averageMs" : **0.0400681**, "percentage" : 0.0353346 }
> , { "name" : "{ForeignNode[bert.embeddings.word_embeddings.weight...node_of_output_start_logits]}", "timeMs" : 3513.39, "averageMs" : **113.335**, "percentage" : 99.9461 }
> , { "name" : "Reformatting CopyNode for Output Tensor 1 to {ForeignNode[bert.embeddings.word_embeddings.weight...node_of_output_start_logits]}", "timeMs" : 0.410624, "averageMs" : **0.0132459**, "percentage" : 0.0116811 }
> , { "name" : "Reformatting CopyNode for Output Tensor 0 to {ForeignNode[bert.embeddings.word_embeddings.weight...node_of_output_start_logits]}", "timeMs" : 0.24064, "averageMs" : **0.00776258**, "percentage" : 0.00684553 }
> ]

**Comment by nvpohanh** [comment]
As of TRT 8.4, the ONNX-BERT does not have fully fused MHA yet. It only fuses it to a point that there three remaining kernels for MHA: batched-gemm+everything-else+batched-gemm. This is the main performance gap between demoBERT and ONNX-BERT.

We are fixing this issue so that they can be fully fused in future TRT version.

**Comment by Tengfei09** [comment]
Thanks for your quick reply. I get your point.
