### ISSUE TITLE
Trtexec : Static model does not take explicit shapes since the shape of inference tensors will be determined by the model itself 

### ISSUE THREAD

**Issue by HarrySm** [NVIDIA/TensorRT#2043]
## Description

I have ERROR when running ONNX model using trtexec CLI when adding the shapes options as done [here](https://github.com/NVIDIA/TensorRT/tree/main/samples/trtexec#example-4-running-an-onnx-model-with-full-dimensions-and-dynamic-shapes).

ERROR:

![image](https://user-images.githubusercontent.com/107109884/172603897-9c6ea3e1-6286-4e7f-a14a-b4e16676812f.png)

## Environment

**TensorRT Version**: trtexec command line interface
**GPU Type**: JEtson AGX ORIN
**Nvidia Driver Version**: 
**CUDA Version**: 11.4
**CUDNN Version**: 8.3.2.49
**Operating System + Version**: ubuntu 20.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: baremetal

## Relevant Files

resnet18 ONNX  model 
[resnet18-v1-7.onnx|attachment](upload://ArS5IRHisbdDvCWzZkwgO91eT7v.onnx) (44.7 MB)

## Steps To Reproduce
```
$ trtexec --onnx=resnet18-v1-7.onnx --explicitBatch --int8 --allowGPUFallback --useDLACore=1 --workspace=2048 --shapes=data:1x3x224x224
```

> **NOTE** : 
> -
> this error appears when adding the **--shapes** option, I am using this option to change the batch size in this command below I put 1x3x224x224 so batch=1 I know by default it is equal to one but my goal is to change it to like 8 or 16 but I put 1 just to show you an example.
***If you have other solutions that let me change the batch size using ONNX pretrained model feel free to suggest them to me.***

you can see the issue [here ](https://forums.developer.nvidia.com/t/trtexec-static-model-does-not-take-explicit-shapes-since-the-shape-of-inference-tensors-will-be-determined-by-the-model-itself/216911)as well on NVIDIA topics

Thank you in advance.

Best regard,
Harry

**Comment by zerollzeng** [comment]
To be more clear here: if a model has an input of shape 1x3x224x224, then the shape is determined. setting it with other shape will lead to an error. you can modify it to the shape like ?x3x224x224, and when build the engine, specify the min/opt/max shape for the engine. e.g. --minShapes=input:1x3x1088x1920 --optShapes=input:1x3x1088x1920 --maxShapes=input:1x3x1088x1920 --shapes=input:1x3x1088x1920

**Comment by HarrySm** [comment]
> To be more clear here: if a model has an input of shape 1x3x224x224, then the shape is determined. setting it with other shape will lead to an error. you can modify it to the shape like ?x3x224x224, and when build the engine, specify the min/opt/max shape for the engine. e.g. --minShapes=input:16x3x224x224 --optShapes=input:16x3x224x224 --maxShapes=input:16x3x224x224 --shapes=input:16x3x224x224

Thank you very much for your help. I find an other way as well and pretty much the same as you suggested you can see it [here](https://github.com/onnx/onnx/issues/2182#issuecomment-513888258)
