### ISSUE TITLE
best GPU hardware

### ISSUE THREAD

**Issue by dany137718** [NVIDIA/TensorRT#2049]
Hi, 
I want to know what the best GPU hardware is for running TensorRT?
what is the most important option in the GPU benchmark?
Thanks

**Comment by zerollzeng** [comment]
> I want to know what the best GPU hardware is for running TensorRT?
There is no correct answer to this question. TensorRT doesn't only optimize for one or some GPUs, TensorRT is highly optimized to run on all NVIDIA GPUs. for example when we run a model, TensorRT will do the graph optimization on the model like layer fusion, constant folding... etc., and for every optimized TRT layer, e.g. a conv+bn+relu layer(actually it's a conv layer after graph optimization). TRT will benchmark all available kernels(maybe a CASK kernel, a cuDNN kernel, a TRT native Kernel, or comes from other producers) on your current device. and then select the fasted kernel. So in summary, you should expect TRT get SOTA performance on every Nvidia GPU that is supported by TRT. you should choose the GPU base on your application requirement. Not TensorRT.

what is the most important option in the GPU benchmark?
> It's hard to answer this  question too. but for DL, TOPS is good metric to evaluate a GPU. @nvpohanh may have more insight here.

**Comment by nvpohanh** [comment]
Depending on what "best" mean. If it refers to best performance, then the current best GPU available in market would be NVIDIA A100: https://www.nvidia.com/en-us/data-center/a100/

**Comment by nvpohanh** [comment]
I am going to close this since the question is vague. Please feel free to reopen if you have follow-up questions. Thanks
