### ISSUE TITLE
Question about fast model loading time

### ISSUE THREAD

**Issue by AsiaCao** [NVIDIA/TensorRT#2061]
## Description

Hi team,

I just have a question to confirm. Please let me know if there is a better forum for such questions.
I did some preliminary benchmark in Python TensorRT APIs to see how fast it is to load a model into memory and make an inference.

I noticed that it took about 8 seconds to load a model into memory and make an inference. After that, if i load a different model into memory and make a single inference, it's really fast (as long as it's still the same python process/session). The entire process of loading a model and making one inference only took less than 0.5s, even the model is completely different.

I was wondering is this behavior normal or expected? if so, what happened internally that makes the subsequent load-and-inference so fast, even it's a different model? and also curious why the first load-and-inference takes 8 seconds.

The benchmark was set up as follows: 
1. prepared 4 compiled TensorRT models (engine files). they are object detection models with different architectures. each model is around 100MB.
2. i copied each model 50 times on disk, each one has a different name. now i have a model pool of 200 models.
3. then i ran the following operations repeatedly and measure the time:
  a. randomly pick an image
  b. randomly pick a model on disk
  c. load the the selected model into memory
  d. make a prediction and print the result

E.g. a+b+c+d took a total of 8s in the first time, then the subsequent a+b+c+d only took around 0.5 second consistently.

## Environment

**TensorRT Version**: 8.4.0.6
**NVIDIA GPU**: Tesla V100
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**: cuda_11.2.r11.2/compiler.29618528_0
**CUDNN Version**: 8.3.2
**Operating System**: ubuntu 20.04
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.10.1
**Baremetal or Container (if so, version)**: Baremetal

**Comment by nvpohanh** [comment]
@AsiaCao It is hard to say the root cause, but I think at the very first engine loading, TRT needs to initialize a lot of stuff (like CUDA context, CUDNN/cuBLAS handles, allocate memories, etc.). Do you think this may be the cause?

**Comment by AsiaCao** [comment]
Thank you @nvpohanh, that's helpful.
Just a follow up question: the subsequent model loading time is super fast, is that normal from your experience?

**Comment by nvpohanh** [comment]
I think that is possible. Setting up a new CUDA context, CUDNN/cuBLAS handles, and allocating memories are all costly operations.

**Comment by AsiaCao** [comment]
thanks @nvpohanh
