### ISSUE TITLE
Qdq model int8 is much slower than fp16 on Orin

### ISSUE THREAD

**Issue by leemengxing** [NVIDIA/TensorRT#2067]
Does Orin platform not support qdq mode？tensorrt8.0.1.6

**Comment by zerollzeng** [comment]
qdq means explicit quantization(https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#explicit-implicit-quantization). all the precision is controlled by the user.
btw what model you are running on Orin and can you try the latest version of TRT?

**Comment by leemengxing** [comment]
TensorRT version 8.0.1.6 , 
The same model performs well on xavier.  this is my onnx model, thks
[my_model.onnx.zip](https://github.com/NVIDIA/TensorRT/files/8937103/my_model.onnx.zip)

**Comment by leemengxing** [comment]
Upgrading to the latest version does not solve the problem

**Comment by leemengxing** [comment]
build with INT8, What should I do?

**Comment by zerollzeng** [comment]
you can run your model with trtexec and enable --verbose --dumpLayerInfo --separateProfileRun --dumpProfile --profilingVerbosity=detailed and compare the verbose log. you will see the layer profile at the end of the log and also you can check the Engine Layers Information to see the difference between 2 engines.

**Comment by leemengxing** [comment]
![1](https://user-images.githubusercontent.com/24696984/174598790-53f97e46-6521-48e9-a9cf-4f368fb7a677.png)
More op before entering the activation function on orin, why?

**Comment by nvpohanh** [comment]
@leemengxing Could you try removing the Q/DQ ops between the BatchNorm and the Sigmoid?

**Comment by leemengxing** [comment]
@nvpohanh Yes, I found that Xavier and Orin did not handle this consistently. Are there any other optimization suggestions?
