### ISSUE TITLE
switch between "Compute cores" and "Cuda cores"

### ISSUE THREAD

**Issue by dany137718** [NVIDIA/TensorRT#2071]
Hi,
How can I switch between "Compute cores" and "Cuda cores"?
I have two PC. one of them has a GTX 750ti Graphics card and the other has RTX 3070.
GTX750 ti doesn't have any "Cuda core" and all of the compute usage is set on "Compute cores".
On the other hand, RTX 3070 has one Cuda core and two "Compute cores", and all of the compute usage is set on "Cuda cores".

![image](https://user-images.githubusercontent.com/37046269/174472555-d7c67ff0-f6b6-4983-85a4-f0f4a8d222b1.png)

I want to know how to switch between these cores

**Comment by zerollzeng** [comment]
Sorry this question is offtopic here, can you ask in somewhere else? thx.

**Comment by nvpohanh** [comment]
I would recommend that you don't use Windows task manager to check utility. Please use `nvidia-smi` tool which gives you more accurate utilization information.
