### ISSUE TITLE
i save an engine, then load and deserialize it on the same computer. But still raise an version not match

### ISSUE THREAD

**Issue by Fuzhiyuan** [NVIDIA/TensorRT#2072]
## Description
Here is the detail got from cmd:
[06/20/2022-11:10:38] [TRT] [E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::40] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 213, Serialized Engine Version: 205)
[06/20/2022-11:10:38] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)

## Environment

**TensorRT Version**:  8.4.1
**NVIDIA GPU**: 1660 
**NVIDIA Driver Version**: 465.89
**CUDA Version**: 11.3
**CUDNN Version**: 8.4.0
**Operating System**: win 10 professional 
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: NO
**PyTorch Version (if applicable)**: 1.11.0+cu113
**Baremetal or Container (if so, version)**: 

## Relevant Files

I just save a built engine, then load and deserialize it on the same computer.
Core code below:

```
with open("sample.engine","wb")as f:
    f.write(engine)
f.close()

with open("sample.engine","rb") as fb:
    serialized_engine = fb.read()
fb.close()

#my command line will throw above error, when run this two lines in jupyter
runtime = trt.Runtime(logger)
de_engine_ = runtime.deserialize_cuda_engine(serialized_engine)

```

**Comment by zerollzeng** [comment]
A similar issue: https://github.com/NVIDIA/TensorRT/issues/2041

**Comment by Fuzhiyuan** [comment]
> please check the LD_LIBRARY_PATH on your environment. perhaps there are multiple tensorrt libs installed on your system.

I have checked it, and In my PATH there is one tensorrt version

**Comment by Fuzhiyuan** [comment]
> A similar issue: #2041

This issue seems to depend on Linux command, is there any solution on Win10?

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by nvpohanh** [comment]
`echo $PATH` in powershell? or `echo %PATH%` in cmd

**Comment by Fuzhiyuan** [comment]
> `echo $PATH` in powershell? or `echo %PATH%` in cmd

E:\lib\python\Scripts\;
E:\lib\python\;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
%E:\anconda\Scripts;
E:\lib\libtorch\lib;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
E:\cmake\bin;
E:\ide_env\gcc\gcc\bin;
E:\ide_env\gcc\gcc\lib;
E:\Git\cmd;E:\opencv\opencv\build\x64\vc14\bin;
E:\lib\openssh\bin;
E:\lib\openssh;
E:\anconda\bin;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
E:\lib\libtorch-win-shared-with-deps-debug-1.11.0+cu113\libtorch\lib;
E:\lib\itk\InsightToolkit-5.2.1\build_;
E:\lib\itk\InsightToolkit-5.2.1\build_\bin\Debug;
E:\lib\itk\InsightToolkit-5.2.1\bin_\bin;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.1.1\;
C:\Program Files\NVIDIA Corporation\NVSMI;
E:\lib\TensorRT-8.4.1.5\bin;E:\lib\TensorRT-8.4.1.5\lib;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
E:\Microsoft VS Code\bin;
C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;
E:\pycharm\PyCharm Community Edition 2021.3.3\bin;
;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;

**Comment by nvpohanh** [comment]
@Fuzhiyuan Did you build the engine and load the engine both in Python? Could you try building the engine and loading the engine in the same python script?

**Comment by Fuzhiyuan** [comment]
> @Fuzhiyuan Did you build the engine and load the engine both in Python? Could you try building the engine and loading the engine in the same python script?

In fact, I did build and load engine both in Python. And, as you can see, I just have one version for Python.

**Comment by nvpohanh** [comment]
Could you try this? (using python, not jupyter)

```

# .... the code to build the engine and serialize it.

orig_serialized_engine = engine.serialize()

with open("sample.engine","wb")as f:
    f.write(orig_serialized_engine)

with open("sample.engine","rb") as fb:
    new_serialized_engine = fb.read()

runtime = trt.Runtime(logger)

orig_de_engine = runtime.deserialize_cuda_engine(orig_serialized_engine) 
assert orig_de_engine 

new_de_engine = runtime.deserialize_cuda_engine(new_serialized_engine) 
assert new_de_engine 
```

**Comment by Fuzhiyuan** [comment]
ERROR：'tensorrt.tensorrt.IHostMemory' object has no attribute 'serialize'  when i run **orig_serialized_engine = engine.serialize()** 
but it will work if directly deserialize_cuda_engine(engine) without the process of f.write() and f.read.

**Comment by nvpohanh** [comment]
oh sorry, your engine is already serialized. Then try this:

```
with open("sample.engine","wb")as f:
    f.write(engine)

with open("sample.engine","rb") as fb:
    new_serialized_engine = fb.read()

runtime = trt.Runtime(logger)

orig_de_engine = runtime.deserialize_cuda_engine(engine) 
assert orig_de_engine 

new_de_engine = runtime.deserialize_cuda_engine(new_serialized_engine) 
assert new_de_engine 
```

**Comment by Fuzhiyuan** [comment]
Ohhhh,  Work!!!. 
But I have tried this idea before. Sometimes it would fail.
