### ISSUE TITLE
Building on Visual Studio for Windows

### ISSUE THREAD

**Issue by rlewkowicz** [NVIDIA/TensorRT#2085]
## Description

Unresolved externals, but in general just a ton of esoteric issues on windows with compilation. Trying to include even the official releases doesn't work. 

Ultimately, I'd like to just include some headers, include some libs and compile some code.  If you want to start from scratch in a native widows environment, I don't want to use cmake. In theory, you would add the include and lib dirs of both cuda toolkit and tensorrt and call it a day, but it doesn't seem that simple. The linker just isn't picking up something. 

Then I want to build this from source. That's how I could generate my own libs, yeah? I open this root folder in visual studio, which has cmake support and it's just a sea of red and more esoteric issues.  

Is this supposed to not be easy? Or is this linux only? This is all just super painful. I'm trying to integrate this in a native windows app, so I can't even use the containers, but it doesn't really work there either. WSL setup is super esoteric and I couldn't get that working. The python stuff all works, but that's all handled by conda. Maybe I should go dig at whatever that creates. It's all cbindings under the hood. 

## Environment

**TensorRT Version**: 8.4.1
**NVIDIA GPU**: 2080ti
**NVIDIA Driver Version**: 512.95
**CUDA Version**: 11.6
**CUDNN Version**: 8.4
**Operating System**: Windows 10

## Steps To Reproduce
Build this in visual studio on windows 

Overall the dll's exist so there has to be a build process for this that works on windows yeah?

**Comment by rlewkowicz** [comment]
```
#include <iostream>
#include <string>
#include <fstream>
#include <iomanip>
#include <memory.h>
#include <string.h>
#include <vector>
#include <sstream>     
#include "NvInfer.h"
#include <cassert>
using namespace nvinfer1;

using namespace std;

#pragma warning(disable: 4996)
#pragma warning(disable: 2694)


int main()
{
    class Logger : public ILogger
    {
        void log(Severity severity, const char* msg) noexcept override
        {
            // suppress info-level messages
            if (severity <= Severity::kWARNING)
                std::cout << msg << std::endl;
        }
    } logger;

    IRuntime* runtime = createInferRuntime(logger);
    assert(runtime != nullptr);

    std::vector<char> trtModelStream_;
    size_t size{ 0 };
    std::ifstream file(R"(C:\best.engine)"); // this is not my file, this is just for show
    if (file.good())
    {
        file.seekg(0, file.end);
        size = file.tellg();
        file.seekg(0, file.beg);
        trtModelStream_.resize(size);
        std::cout << "size" << trtModelStream_.size() << std::endl;
        file.read(trtModelStream_.data(), size);
        file.close();
    }
    file.seekg(0, std::ios::end);
    std::streampos          length = file.tellg();
    file.seekg(0, std::ios::beg);
    std::vector<char>       buffer(length);
    file.read(&buffer[0], length);
    file.close();
    std::stringstream gieModelStream;
    gieModelStream.rdbuf()->pubsetbuf(&buffer[0], length);

    ICudaEngine* engine = runtime->deserializeCudaEngine(trtModelStream_.data(), size, nullptr);

}

**Comment by nvpohanh** [comment]
@kevinch-nv Could you check how we could help @rlewkowicz for Windows building steps?

**Comment by rlewkowicz** [comment]
This is just my misunderstanding of the environment I think. I don't think visual studio automatically picks up .lib files.
