### ISSUE TITLE
[Question||Feature] Running in INT8 with FP16 fallback

### ISSUE THREAD

**Issue by BCJuan** [NVIDIA/TensorRT#2086]
Dear TensorRT developers,

Thank you for your amazing work.

I have one question. Is it possible to run a quantized network in INT8 with fallback to FP16 by setting both flags during conversion?

```
config.set_flag(trt.BuilderFlag.FP16)
config.set_flag(trt.BuilderFlag.INT8)
```

I have been unable to obtain clear information from the documentation with regards to this matter.

Thank you very much.

**Comment by zerollzeng** [comment]
If your INT8 model is quantized with PTQ, then the answer is YES, you can set both flags and TRT will pick the fastest precision. If your INT8 model is quantized with QAT, then the answer is NO. all the precision in QAT is explicit. 

you can refer to https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#working-with-int8 for more information

**Comment by nvpohanh** [comment]
>  If your INT8 model is quantized with QAT, then the answer is NO. all the precision in QAT is explicit.

@zerollzeng This is not 100% correct. For QAT model, it is correct that all the precision is explicit, either floating-point or INT8. But if FP16 is enabled, then for the layers that must run in floating-point, TRT will try both FP32 and FP16 and select the faster one. So in this sense, FP16 fallback is available.

**Comment by nvpohanh** [comment]
And short answer for @BCJuan 's original question: Yes, enabling both INT8 and FP16 is allowed (and encouraged)

**Comment by nvpohanh** [comment]
> @nvpohanh what you mean is for a QAT network, enabling FP16 for the FP32 layer is doable, what I want to express here is for an INT8 layer with Q/DQ. the precision is explicit, the user can not fallback this layer to FP16 or FP32.

This is 100% correct. Thanks for clarifying this :)

**Comment by zerollzeng** [comment]
> Is latency the only criteria to follow when doing the selection of FP16 or INT8? Or is there a way to choose between latency and accuracy?

INT8 usually has higher performance while FP16 usually has better accuracy. My suggestion is to enable both INT8 and FP16 first, then TRT will choose the precision(for each layer) automatically that has the best performance.  then check the accuracy, if the accuracy is bad. you can try to fall back some layers to FP16(usually it also means an accuracy bug in TRT, please also file an issue to us) until you get a good trade-off between accuracy and performance.

**Comment by BCJuan** [comment]
Thank you very much for your answer @zerollzeng! Closing the issue.
