### ISSUE TITLE
Precision BUG

### ISSUE THREAD

**Issue by byjswr** [NVIDIA/TensorRT#2091]
## Description

After adding nodes that are not related to out1 and out2，the fusion strategy leads to problems with the accuracy of out1 and out2

## Environment

TensorRT Version: 8.4.0
NVIDIA GPU: GTX
NVIDIA Driver Version: 465.19.01
CUDA Version: 11.3
Operating System: ubuntu
Python Version: 3.8.10
PyTorch Version: 1.11.0
onnxruntime Version: 1.11.0

## Relevant Files

test script in this respository: https://github.com/byjswr/TRT_fusion/tree/main ,please help me solve this problem

<img width="248" alt="企业微信截图_16560529436631" src="https://user-images.githubusercontent.com/53067559/175478042-8080090f-9981-4013-ab1c-ea52068ee00c.png">

The output portion of out1 and out2 is 0

**Comment by BowenFu** [comment]
Self assigned this bug during TRT-hackathon-2022.

**Comment by BowenFu** [comment]
I have reproduced the issue. This may be fixed in later version.

**Comment by ttyio** [comment]
@BowenFu  is this fixed? thanks!

**Comment by BowenFu** [comment]
> @BowenFu is this fixed? thanks!

Yes, this has been fixed in 2022.

**Comment by ttyio** [comment]
closing, thanks!
