### ISSUE TITLE
inconsistent inference results for yolov5s-3.0 in C++ and python

### ISSUE THREAD

**Issue by firrice** [NVIDIA/TensorRT#2092]
## Description

I trained a model based yolov5s-3.0 and i don't do any modify to network structure. Then I transfer the pth model to .engine.  And I use the same input  and the same engine to inference in C++ and python, but result appears inconsistent. But I try resnet50 model successfully. Any body meet similar problem?

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**: 1660 Supper
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
Which output is correct? and how big the gap is? usually, it's caused by the inconsistency in your codes. can you make sure the way your process the inputs and outputs are the same in both c++ and python?

**Comment by firrice** [comment]
@zerollzeng Thanks for reply. The problem has been solved, the reason is mainly due to the inconsistent input which is a little diffcult to discover related to cv::Mat. Tensorrt is OK itself, thanks again!
