### ISSUE TITLE
Myelin error when load ONNX model,myelin::cask_gemm_tactics(const myelin::ir::compile_options_t&, const myelin::ir::operation_t&, myelin::targetSm_t, myelin::logs_t&, bool): Assertion `false && "fused op cannot be implemented by CASK"' failed.

### ISSUE THREAD

**Issue by bilibiliGO283** [NVIDIA/TensorRT#2101]
## Description

I am going to use tensorRT 8.2.5.1 to boost the performance of my model,but it failed when build_serialized_network. Error occurred in myelin which is close-sourced, we’ve gotten stuck here for days and had no clue where to start debugging, so ask for your help.
I feel that the problem lies in the last Gemm operator, but I took out this operator and ran it without error.

![image](https://user-images.githubusercontent.com/52642928/176340202-9a21949d-4ea6-48a6-920b-fe6335ac0fda.png)

The error message is as follows:
python3: /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/cask_impl.cpp:1039: std::vector<myelin::ir::tactic_attribute_t> myelin::cask_gemm_tactics(const myelin::ir::compile_options_t&, const myelin::ir::operation_t&, myelin::targetSm_t, myelin::logs_t&, bool): Assertion `false && "fused op cannot be implemented by CASK"' failed.

## Environment

**TensorRT Version**: 8.2.5.1
**NVIDIA GPU**: GTX 3090
**NVIDIA Driver Version**: 515.48.07
**CUDA Version**: 11.7
**CUDNN Version**: 
**Operating System**: linux

**Comment by nvpohanh** [comment]
Could you try TRT 8.4.1 + CUDA-11.6? If it still doesn't work, please provide verbose engine building log and the ONNX file so that we can repro the issue. Thanks

**Comment by DayDayupupupup** [comment]
Same issue

**Comment by DayDayupupupup** [comment]
I get a same issue.

**Comment by DayDayupupupup** [comment]
I got a same issue.
** Environment**
TensorRT Version: 8.2.1.8(21.12)
NVIDIA GPU: A30
NVIDIA Driver Version: 510.68.02
CUDA Version: 11.6
Operating System: linux
** Description**
My onnx model's batchsize is dynamic,

**Comment by DayDayupupupup** [comment]
I got a same error.
**Environment**
TensorRT Version: 8.2.1.8(21.12)
NVIDIA GPU: A30
NVIDIA Driver Version: 510.68.02
CUDA Version: 11.5
Operating System: linux
**Description**
My onnx model's batch_size is dynamic,
with  TRT 8.2.1.8
when I set max_batch_size>=2, I get the same error;
when I set max_batch_size=1, the onnx could be converted to trt engine.

Then I  use TRT  8.4.1.5 + CUDA-11.6, 
I set max_batch_size=1024 : Min (1, 1) Opt (512, 1) Max (1024, 1)
It works fine.

**Comment by nvpohanh** [comment]
It's possible that this is already fixed in TRT 8.4.1.5

**Comment by bilibiliGO283** [comment]
Thanks a lot for your replies. Due to some environmental reasons, I could not change the version of TensorRT, but I replaced the Gemm operator with the cublas plugin, which also fixed the problem.
Now my computational graph is as follows：
![image](https://user-images.githubusercontent.com/52642928/176881715-53da9dda-a271-40a3-8ce4-ec06af64389b.png)

**Comment by Yebi1837** [comment]
hi @bilibiliGO283 
how do you do this - replaced the Gemm operator with the cublas plugin? 
I am stuck at the same issue and couldn't find a way to work around it.

Thanks!
