### ISSUE TITLE
dynamic slice Assertion sliceOutDims[i] > 0 failed. empty tensor not allowed

### ISSUE THREAD

**Issue by mdztravelling** [NVIDIA/TensorRT#2102]
## Description

For trt 8.0.3 ，the following code runs OK, BUT use trt 8.4 occurred error. 
```
    #     cu_seq_lens shape is (-1),  I want to get cu_seq_lens[:-1]
    cu_seq_shape = network.add_shape(cu_seq_lens).get_output(0)
    constant_layer_out = network.add_constant(shape=(1, ), weights=np.array([1, ], dtype=np.int32)).get_output(0)
    cu_seq_real_shape = network.add_elementwise(cu_seq_shape, constant_layer_out, trt.tensorrt.ElementWiseOperation.SUB).get_output(0)
    slice_layer = network.add_slice(cu_seq_lens, start=(0,), shape=(1, ), stride=(1,))
    slice_layer.set_input(2, cu_seq_real_shape)
    slice_cu_seq_len = slice_layer.get_output(0)
```
Use trt 8.4, error log follow.
```
...
[06/29/2022-14:35:34] [TRT] [E] 2: [myelinSliceLayer.cpp::addSlice::109] Error Code 2: Internal Error (Assertion sliceOutDims[i] > 0 failed. empty tensor not allowed)
...
```
How to solve this problem？

## Environment

**TensorRT Version**:  8.4
**NVIDIA GPU**:  A10
**NVIDIA Driver Version**:  465.19.01 
**CUDA Version**:  11.3
**CUDNN Version**:  8.3
**Operating System**:  centos 8.2
**Python Version (if applicable)**:  3.9
**Tensorflow Version (if applicable)**:  2.6
**PyTorch Version (if applicable)**:  1.7
**Baremetal or Container (if so, version)**:

**Comment by jackwish** [comment]
@mdztravelling Thank you for reporting this issue.

Could you help to check the input shape of Slice in your case?

**Comment by mdztravelling** [comment]
> @mdztravelling Thank you for reporting this issue.
> 
> Could you help to check the input shape of Slice in your case?

cu_seq_lens shape is  (-1,).

**Comment by mdztravelling** [comment]
> @mdztravelling Thank you for reporting this issue.
> 
> Could you help to check the input shape of Slice in your case?
@jackwish   can you confirm this problem? And how to resolve it?

**Comment by jackwish** [comment]
@mdztravelling By "the input shape of Slice", I mean the real shape - with input shape profile, what the shape of it should be. `-1` would just mean that the shape is unknown yet.

**Comment by mdztravelling** [comment]
> @mdztravelling By "the input shape of Slice", I mean the real shape - with input shape profile, what the shape of it should be. `-1` would just mean that the shape is unknown yet.
@jackwish 
Thanks for reminding. 
It's my code problem which must set input shape greater than 2 in profile.
The correct code is as follows, and it's i need.
```
profile.set_shape("cu_seqlens", min=(2,), opt=(max_batch_size+1,), max=(max_batch_size+1,))

```
Thanks again, solved my problem. @jackwish

**Comment by ttyio** [comment]
Closing since this is fixed, thanks!
