### ISSUE TITLE
Unable to run sample: TensorRT/samples/python/efficientnet/build_engine.py with INT8 on A100

### ISSUE THREAD

**Issue by go2sea** [NVIDIA/TensorRT#2104]
## Description
The official example does not work with INT8, but works well with FP32 & FP16.
My kick off command ：
```python
python3 build_engine.py \
    --onnx "/home/hailong.ma/convert_tools/efficientnet/net.onnx" \
    --engine "./engine.trt" \
    --precision int8 \
    --calib_input "/home/hailong.ma/convert_tools/trt_tools/data_calibration" \
    --calib_num_images 32 \
    --calib_batch_size 1
```
but got:
![image](https://user-images.githubusercontent.com/10369479/176431606-0bbbb6c0-f88e-4951-9ba7-ba3526bd89c1.png)

## How to reproduce：
① git pull nvcr.io/nvidia/tensorrt:22.03-py3 
② pip install -r TensorRT/samples/python/efficientnet/requirements.txt
③ To avoid this error, Add this 3 red boxes in build_engine.py:
![image](https://user-images.githubusercontent.com/10369479/176579834-21dcd607-f4b1-4890-822f-d9e61a4da4f3.png)
![image](https://user-images.githubusercontent.com/10369479/176433454-408febde-16d5-41f3-bddd-1159eefa8ef9.png)
④ create onnx model:
```python
python3 create_onnx.py \
    --saved_model "/home/xxx/convert_tools/efficientnetv2-s/saved_model" \
    --onnx "./net.onnx" \
    --batch_size 1 \
    --input_size 384
```

⑤ build engine:
```python
python3 build_engine.py \
    --onnx "/home/hailong.ma/convert_tools/efficientnet/net.onnx" \
    --engine "./engine.trt" \
    --precision int8 \
    --calib_input "/home/hailong.ma/convert_tools/trt_tools/data_calibration" \
    --calib_num_images 32 \
    --calib_batch_size 1
```

That's all.

## Environment

**TensorRT Version**:  8.2.3.0  (also test in 8.4.0, same error)
**NVIDIA GPU**: A100
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**: 11.6.112
**CUDNN Version**: 8.3.3
**Operating System**: Ubuntu 20.04.4 LTS (x86_64)
**Python Version (if applicable)**: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
**Tensorflow Version (if applicable)**: 2.9.1
**PyTorch Version (if applicable)**: 1.9.1+cu111
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:22.03-py3

**Comment by zerollzeng** [comment]
> ③ Add this 3 red boxes in build_engine.py

sorry, can you explain why do you need to add these code to our sample?

**Comment by go2sea** [comment]
> > ③ Add this 3 red boxes in build_engine.py
> 
> sorry, can you explain why do you need to add these code to our sample?

An error occurs without these code, screenshots of the error has been posted above.

**Comment by go2sea** [comment]
> > ③ Add this 3 red boxes in build_engine.py
> 
> sorry, can you explain why do you need to add these code to our sample?

An error occurs without these code, and the screenshot of the error has been posted above.

**Comment by ghostxsl** [comment]
Hello, I encountered the same problem as you, but I still reported an error after using your solution. Any suggestions?
