### ISSUE TITLE
TensorRT 8.4.0.6 fallback to 8.2.5 when using trtexec

### ISSUE THREAD

**Issue by deephog** [NVIDIA/TensorRT#2110]
It is a weird thing that even though I have installed a TensorRT of version 8.4.0.6, sometimes it falls back to 8.2.5 when compiling certain models. I don't know if it relates to the opset version I used for my ONNX model, or is it related to certain layers or operations I used in the model. It will be great if someone can explain the general rules to me. Thanks!

**Comment by deephog** [comment]
Ok I know where I am wrong. I need to rebuild the trtexec after I manually install the tensorrt.

**Comment by PrajwalCogniac** [comment]
I am facing the same issue .... What do you mean rebuild the trtexec ?

**Comment by deephog** [comment]
> I am facing the same issue .... What do you mean rebuild the trtexec ? @deephog @pranavm-nvidia

I was using the docker image released by Nvidia, basically they have trtexec pre-built in the docker image, when you just downgrade your tensorrt, and when you run trtexec, it is still running the pre-built trtexec which is another version. Basically you need to re-build the trtexec following their documentation.
