### ISSUE TITLE
More gpu memory is needed than pytorch for same model

### ISSUE THREAD

**Issue by lhao0301** [NVIDIA/TensorRT#2111]
## Description

Two of my trt-models in 8.4GA use more gpu memory than their pytorch counterparts. (In 8.2GA, it has not the problem)

model-a: trt-model=\~5GB, pytorch-model=~2GB
model-b(unet): trt-model=7.3GB, pytorch-model=4.4GB

And adjusting `--memPoolSize=workspace:2048` makes no sense.

## Environment

**TensorRT Version**: 8.4GA
**NVIDIA GPU**: Nvidia A10 (24GB)
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**: cuda-11.1
**CUDNN Version**: 8.4.1
**Operating System**: centos
**PyTorch Version (if applicable)**: 1.10

## Steps To Reproduce
```
###### build cmd
./trtexec --onnx=unet.onnx --saveEngine=unet.trt
###### infer pseudo-code
class TRTEngine(object):
    def __init__(self, trt_file):
        self.engine = build_engine(trt_file)
        self.context = self.engine.create_execution_context()
        self.stream = torch.cuda.Stream()

   def run(self, inputs):
        ......
        buffer = in_buffer + out_buffer
        self.context.execute_async_v2(
            bindings=buffer, stream_handle=self.stream.cuda_stream
        )
        self.stream.synchronize()

def run_pytorch():
    ......
    model.eval()
    with torch.no_grad():
        for i in range(100):
            out = model(torch.randn(1, 20, 1080, 1920).cuda())

def run_trt():
    engine = TRTEngine(trt_file=trt_file)
    for i in range(100):
        engine.run(torch.randn(1, 20, 1080, 1920).cuda())

run_pytorch()
run_trt()
```

**Comment by zerollzeng** [comment]
How's the memory usage if you run the engine with trtexec? e.g. `trtexec --loadEngine=unet.trt --durations=30`

also, can you try disabling some tactic sources? e.g. --tacticSources=-CUDNN,-CUBLAS,-CUBLAS_LT which will disable the cudnn and cublas. they might occupy some memory

**Comment by lhao0301** [comment]
I will try it.

I also found that `workspace` works for 8.2GA when build trt engin(the gpu memory is <= workspace) but not for 8.4GA.

**Comment by zerollzeng** [comment]
we don't need to set workspace since 8.4 anymore

**Comment by nvpohanh** [comment]
`workspace` is the scratch space that our tactics can use. It doesn't include the memory needed for necessary weights, activations, and pre-computed data. That said, we may want to debug why the memory consumption increased that much between TRT 8.4 and TRT 8.2

**Comment by lhao0301** [comment]
After I update the cuda-11.1 to cuda-11.7 and start to config the environment from scratch, both the two trt-models behave similar with pytorch in gpu consumption during inference. 

During buiding the engine with `trtexec`,  `the unet` also behaves ok but `the other one` still reach a large peek(e.g. 18G).  `--tacticSources=-CUDNN,-CUBLAS,-CUBLAS_LT` raises error `Internal Error (Could not find any implementation for node MatMul_595.)`.

**Comment by zerollzeng** [comment]
> After I update the cuda-11.1 to cuda-11.7 and start to config the environment from scratch, both the two trt-models behave similar with pytorch in gpu consumption during inference.

Looks like it's cause by cuda not TRT
