### ISSUE TITLE
About using cuda graph in model execution 

### ISSUE THREAD

**Issue by deephog** [NVIDIA/TensorRT#2112]
I've probably encountered an enqueue-bound model, which shows much faster inference when --usecudagraph flag is set when running trtexec benchmark. However, I don't quite understand how to actually implement the cuda graph when executing the generated engine. According to [this article](https://developer.nvidia.com/blog/cuda-graphs/), the implementation doesn't seem too difficult, but I just don't know how TensorRT APIs blend into this scheme.

It will be much appreciated if someone can show me a code snippet of how to do it. Thanks!

**Comment by nvpohanh** [comment]
@deephog We have an example in our doc: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#cuda-graphs

**Comment by nvpohanh** [comment]
And some additional explanation here: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#enqueue-bound-workload

**Comment by deephog** [comment]
So sad we didn't manage to find those, we tried to search for --usecudagraph, but the only thing relevent is it is so super clear. We eventually decided to go into the source code of trtexec and figured it out. Still big thanks for sharing those!
