### ISSUE TITLE
use onnx-graphsurgeon export onnx, while cant use in onnxruntime

### ISSUE THREAD

**Issue by CUGfred** [NVIDIA/TensorRT#2113]
# Describe
after use onnx-graphsurgeon adjust a layernorm model, fuse ops into one LayerNorm node,while cant be used in onnxruntime. i have wrote a Register_custom_ops shared library. after use session options load that, while opset doesnt match , how could i get this done. plus, onnxruntime unittest could load shared library, while i use cmake output a shared library, it doesnt work.
# Environment
TensorRT 8.4
onnx-graphsurgeon include in TRT
onnxruntime 1.11.1
# Step to Reproduce
use trt-hackthon-sample  cookbook parserandplugin layernorm to output a model which contains layernorm custom op 
use onnxruntime use custom operator to produce a layernorm shared library
after register_custom_ops_library done, get errorError No Op registered for LayerNorm with domain_version of 11

**Comment by zerollzeng** [comment]
Sorry I don't get what your problem is, can you make it more clear?

**Comment by CUGfred** [comment]
@zerollzeng sry, this is about onnxruntime custom op, it should not be posted in TensorRT. i will close this.
