### ISSUE TITLE
How to convert .engine to .plan?

### ISSUE THREAD

**Issue by KingCSer** [NVIDIA/TensorRT#2117]
We have converted the caffe model to .engine by trtexec tools, how to convert this engine file to plan file？

**Comment by nvpohanh** [comment]
An engine file is a plan file. We use these two words interchangeably.

**Comment by KingCSer** [comment]
yeah, but when we deploy it on the triton-server and launch it, it appears some errors as followed:
![1656910905781(1)](https://user-images.githubusercontent.com/48956659/177085778-9905e741-0a9b-4327-afe9-d583dc4d11c9.jpg)

**Comment by nvpohanh** [comment]
That means the TRT version you used to build the engine is not the same TRT version you used in deployment.

**Comment by ttyio** [comment]
Closing since no response for more than 3 weeks, please reopen if you still have question, thanks!
