### ISSUE TITLE
Output from TRT engine inference return ZERO matrix

### ISSUE THREAD

**Issue by salidw** [NVIDIA/TensorRT#2122]
Hello,

I had converted my *.pt file to onnx and validated its inference. Everything was OK.
When I converted my Onnx file to TRT Engine file and did inference it on Jetson Nano.
The predicted output was ZERO matrix like the below (Even my image input has values).

Predicted output:
[[ 0. 0. 0. …, 0. 0. 0.]
[ 0. 0. 0. …, 0. 0. 0.]
[ 0. 0. 0. …, 0. 0. 0.]
…,
[ 0. 0. 0. …, 0. 0. 0.]
[ 0. 0. 0. …, 0. 0. 0.]
[ 0. 0. 0. …, 0. 0. 0.]]

Image input (as Numpy): For example
[[[ 0.73339844 0.74121094 0.74121094 …, 0.1451416 0.11767578
0.12158203]
[ 0.73339844 0.73339844 0.73339844 …, 0.08233643 0.06274414
0.10198975]
[ 0.73730469 0.72558594 0.74121094 …, 0.07452393 0.05883789
0.10198975] ]]

This is my inference function:
def predict(img):
cuda.memcpy_htod_async(d_input, img, stream)
context.execute_async_v2(bindings, stream.handle, None)
cuda.memcpy_dtoh_async(output, d_output, stream)
stream.synchronize()
return output

Please advise why the inference result was ZERO matrix. Thanks.

**Comment by zerollzeng** [comment]
can you share the onnx model here? also using polygraphy(https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/polygraphy) to debug the accuracy issue is very useful

**Comment by salidw** [comment]
@zerollzeng  Thanks... let's try. This is my ONNX file. 

https://drive.google.com/file/d/1c4X4VHcsRj9XStUXbh3AjowznSocl0rg/view?usp=sharing

**Comment by zerollzeng** [comment]
Which TRT version you are using?

**Comment by salidw** [comment]
@zerollzeng  Sorry for your patient. Here is my system envir.

- Jetpack	: 	4.6 [L47 32.6.1]
- CUDA		: 	10.2.300
- OpenCV	:	4.1.1
- Complied CUDA :	NO
- TensorRT	: 	8.0.1.6
- cuDNN		: 	8.2.1.32
- Cuda ARCH	:	5.3

**Comment by zerollzeng** [comment]
I can't access to the onnx, request permission, can you check whether this can be reproduced on 8.4 or 8.2(latest jetson)

**Comment by salidw** [comment]
@zerollzeng  Sorry, I guessed :) that you have downloaded the file so I dropped it. However, I have shared my onnx file again at this link
https://drive.google.com/file/d/10jJdI8EjQoT5Sur2Rjx7GnqtqCTMiCTd/view?usp=sharing

**Comment by salidw** [comment]
@zerollzeng Thanks for your help. I had used the same TRT version (8.0.1.6) but changed the code to allocate memory size between host and device. The problem was gone....but fps is only 4 which I need more :). I may test on TRT 8.4 per your recommendation.
