### ISSUE TITLE
Does TensoRT support the fusion of leayrelu and conv?

### ISSUE THREAD

**Issue by pangr** [NVIDIA/TensorRT#2134]

**Comment by pangr** [comment]
> or create a case and run it with trtexec --verbose, you are able to see the final engine structure in the log. which will tell if TRT can support your case.

Ok, Thank you for your reply

**Comment by pangr** [comment]
Does TensorRT support leakyrelu quantization?

**Comment by nvpohanh** [comment]
Whether the fusion happens depends on whether TRT has tactics supporting that. The very rough guidelines are:

- Conv+LeakyReLU should be fused in FP16 or in INT8 on Turing and Ampere GPUs.
- Other precisions and older GPUs are not guaranteed. If TRT doesn't have a tactic supporting this fusion, TRT will fall back to two-kernel approach.
- If QAT (i.e. Q/DQ ops) is used, then Conv+LeakyReLU can only be fused if there are no Q/DQ ops between Conv and LeakyReLU and There are Q/DQ ops before Conv and after LeakyReLU. Basically, it will be fused if the pattern looks like: `...->Q->DQ->Conv->LeakyReLU->Q->DQ->...`

**Comment by pangr** [comment]
> Whether the fusion happens depends on whether TRT has tactics supporting that. The very rough guidelines are:
> 
> * Conv+LeakyReLU should be fused in FP16 or in INT8 on Turing and Ampere GPUs.
> * Other precisions and older GPUs are not guaranteed. If TRT doesn't have a tactic supporting this fusion, TRT will fall back to two-kernel approach.
> * If QAT (i.e. Q/DQ ops) is used, then Conv+LeakyReLU can only be fused if there are no Q/DQ ops between Conv and LeakyReLU and There are Q/DQ ops before Conv and after LeakyReLU. Basically, it will be fused if the pattern looks like: `...->Q->DQ->Conv->LeakyReLU->Q->DQ->...`

Thank you for your reply, I tried the above method, but the model inference dump profile is as follows, leakyrelu and conv do not seem to be fused
![image](https://user-images.githubusercontent.com/5838111/178495522-48d70c81-ad72-4ab8-b022-af27bd5b32ad.png)
![image](https://user-images.githubusercontent.com/5838111/178495625-c5337d44-fc81-4d69-8295-db9e564b57ee.png)

**Comment by ttyio** [comment]
@pangr  what's your GPU and have you tried latest 8.6GA? thanks!

**Comment by ttyio** [comment]
closing legacy issues, please reopen if you still have issue with latest TRT, thanks!
