### ISSUE TITLE
When run "python -m pip install colored polygraphy --extra-index-url https://pypi.ngc.nvidia.com", Can`t find install.ps1

### ISSUE THREAD

**Issue by Fuzhiyuan** [NVIDIA/TensorRT#2140]

**Comment by Fuzhiyuan** [comment]
@zerollzeng 
I just run that command, then can not find install.psl fiI le in polygraph document. So, I think I can not inform you more information.
The following is the tree which I get when the comman is finished.

`
|—python
|---|---lib
|     |    | site-package
|     |    |    |--colored
|     |    |    |--colored-1.4.3-py3.8.egg-info
|     |    |    |--polygraphy-0.36.2.dist-info
|     |    |    |--polygraphy
`
This polygraph tree :


`│  config.py
│  constants.py
│  __init__.py
│
├─backend
│  │  trt_legacy.py
│  │  __init__.py
│  │
│  ├─base
│  │  │  loader.py
│  │  │  runner.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          loader.cpython-38.pyc
│  │          runner.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─common
│  │  │  loader.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          loader.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─onnx
│  │  │  loader.py
│  │  │  util.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          loader.cpython-38.pyc
│  │          util.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─onnxrt
│  │  │  loader.py
│  │  │  runner.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          loader.cpython-38.pyc
│  │          runner.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─pluginref
│  │  │  references.py
│  │  │  runner.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          references.cpython-38.pyc
│  │          runner.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─pyt
│  │  │  runner.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          runner.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─tf
│  │  │  loader.py
│  │  │  runner.py
│  │  │  util.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          loader.cpython-38.pyc
│  │          runner.cpython-38.pyc
│  │          util.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─trt
│  │  │  algorithm_selector.py
│  │  │  calibrator.py
│  │  │  loader.py
│  │  │  profile.py
│  │  │  runner.py
│  │  │  util.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          algorithm_selector.cpython-38.pyc
│  │          calibrator.cpython-38.pyc
│  │          loader.cpython-38.pyc
│  │          profile.cpython-38.pyc
│  │          runner.cpython-38.pyc
│  │          util.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  └─__pycache__
│          trt_legacy.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─common
│  │  interface.py
│  │  struct.py
│  │  __init__.py
│  │
│  └─__pycache__
│          interface.cpython-38.pyc
│          struct.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─comparator
│  │  comparator.py
│  │  compare.py
│  │  data_loader.py
│  │  postprocess.py
│  │  struct.py
│  │  util.py
│  │  __init__.py
│  │
│  └─__pycache__
│          comparator.cpython-38.pyc
│          compare.cpython-38.pyc
│          data_loader.cpython-38.pyc
│          postprocess.cpython-38.pyc
│          struct.cpython-38.pyc
│          util.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─cuda
│  │  cuda.py
│  │  __init__.py
│  │
│  └─__pycache__
│          cuda.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─exception
│  │  exception.py
│  │  __init__.py
│  │
│  └─__pycache__
│          exception.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─func
│  │  func.py
│  │  __init__.py
│  │
│  └─__pycache__
│          func.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─json
│  │  serde.py
│  │  __init__.py
│  │
│  └─__pycache__
│          serde.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─logger
│  │  logger.py
│  │  __init__.py
│  │
│  └─__pycache__
│          logger.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─mod
│  │  exporter.py
│  │  importer.py
│  │  util.py
│  │  __init__.py
│  │
│  └─__pycache__
│          exporter.cpython-38.pyc
│          importer.cpython-38.pyc
│          util.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─tools
│  │  registry.py
│  │  script.py
│  │  util.py
│  │  __init__.py
│  │
│  ├─args
│  │  │  base.py
│  │  │  comparator.py
│  │  │  data_loader.py
│  │  │  logger.py
│  │  │  model.py
│  │  │  trt_legacy.py
│  │  │  __init__.py
│  │  │
│  │  ├─onnx
│  │  │  │  loader.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          loader.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  ├─onnxrt
│  │  │  │  loader.py
│  │  │  │  runner.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          loader.cpython-38.pyc
│  │  │          runner.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  ├─pluginref
│  │  │  │  runner.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          runner.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  ├─tf
│  │  │  │  config.py
│  │  │  │  loader.py
│  │  │  │  runner.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          config.cpython-38.pyc
│  │  │          loader.cpython-38.pyc
│  │  │          runner.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  ├─tf2onnx
│  │  │  │  loader.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          loader.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  ├─trt
│  │  │  │  config.py
│  │  │  │  loader.py
│  │  │  │  runner.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          config.cpython-38.pyc
│  │  │          loader.cpython-38.pyc
│  │  │          runner.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  ├─util
│  │  │  │  util.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          util.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  └─__pycache__
│  │          base.cpython-38.pyc
│  │          comparator.cpython-38.pyc
│  │          data_loader.cpython-38.pyc
│  │          logger.cpython-38.pyc
│  │          model.cpython-38.pyc
│  │          trt_legacy.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─base
│  │  │  tool.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          tool.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─convert
│  │  │  convert.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          convert.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─data
│  │  │  data.py
│  │  │  __init__.py
│  │  │
│  │  ├─subtool
│  │  │  │  to_input.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          to_input.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  └─__pycache__
│  │          data.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─debug
│  │  │  debug.py
│  │  │  __init__.py
│  │  │
│  │  ├─subtool
│  │  │  │  artifact_sorter.py
│  │  │  │  base.py
│  │  │  │  build.py
│  │  │  │  diff_tactics.py
│  │  │  │  precision.py
│  │  │  │  reduce.py
│  │  │  │  repeat.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          artifact_sorter.cpython-38.pyc
│  │  │          base.cpython-38.pyc
│  │  │          build.cpython-38.pyc
│  │  │          diff_tactics.cpython-38.pyc
│  │  │          precision.cpython-38.pyc
│  │  │          reduce.cpython-38.pyc
│  │  │          repeat.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  └─__pycache__
│  │          debug.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─inspect
│  │  │  inspect.py
│  │  │  __init__.py
│  │  │
│  │  ├─subtool
│  │  │  │  capability.py
│  │  │  │  data.py
│  │  │  │  model.py
│  │  │  │  tactics.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          capability.cpython-38.pyc
│  │  │          data.cpython-38.pyc
│  │  │          model.cpython-38.pyc
│  │  │          tactics.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  └─__pycache__
│  │          inspect.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─run
│  │  │  run.py
│  │  │  __init__.py
│  │  │
│  │  └─__pycache__
│  │          run.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─surgeon
│  │  │  surgeon.py
│  │  │  __init__.py
│  │  │
│  │  ├─subtool
│  │  │  │  base.py
│  │  │  │  extract.py
│  │  │  │  insert.py
│  │  │  │  sanitize.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          base.cpython-38.pyc
│  │  │          extract.cpython-38.pyc
│  │  │          insert.cpython-38.pyc
│  │  │          sanitize.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  └─__pycache__
│  │          surgeon.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  ├─template
│  │  │  template.py
│  │  │  __init__.py
│  │  │
│  │  ├─subtool
│  │  │  │  trt_config.py
│  │  │  │  trt_network.py
│  │  │  │  __init__.py
│  │  │  │
│  │  │  └─__pycache__
│  │  │          trt_config.cpython-38.pyc
│  │  │          trt_network.cpython-38.pyc
│  │  │          __init__.cpython-38.pyc
│  │  │
│  │  └─__pycache__
│  │          template.cpython-38.pyc
│  │          __init__.cpython-38.pyc
│  │
│  └─__pycache__
│          registry.cpython-38.pyc
│          script.cpython-38.pyc
│          util.cpython-38.pyc
│          __init__.cpython-38.pyc
│
├─util
│  │  format.py
│  │  util.py
│  │  __init__.py
│  │
│  └─__pycache__
│          format.cpython-38.pyc
│          util.cpython-38.pyc
│          __init__.cpython-38.pyc
│
└─__pycache__
        config.cpython-38.pyc
        constants.cpython-38.pyc
        __init__.cpython-38.pyc`

**Comment by pranavm-nvidia** [comment]
@Fuzhiyuan Are you trying to build from source, or use the pre-built wheels? For the pre-built wheels, all you need to do is:
```
python -m pip install colored polygraphy --extra-index-url https://pypi.ngc.nvidia.com
```

**Comment by ttyio** [comment]
Closing since no response for more than 3 weeks, please reopen if you still have question, thanks!
