### ISSUE TITLE
ONNX -> TRT Error Code 1 and 2: Cask (isConsistent) and Internal Error (Assertion enginePtr != nullptr failed.)

### ISSUE THREAD

**Issue by Pawel842** [NVIDIA/TensorRT#2141]
## Description

Hello, 

I'm trying to deploy ONNX model using TensorRT, but errors occours.
![image](https://user-images.githubusercontent.com/89902894/178472152-766ec09c-eddc-4474-810d-7ac45e3421d7.png)

Used command: 
`./trtexec --onnx=/home/nvidia/trt_conversion/build-yolo-tensorrt/model/tfmodel_lin_19_batchsize.onnx --saveEngine=test.trt --verbose`

The model was converted to ONNX from 'SavedModel' format on target Device and check with `onnx.checker.check_model(model).` do not return any error.

I tried conversion with and without set an explicit batch size in the ONNX file.

The attempt was made also with onnx==1.4.1.
The attempts were also made when convert model on host machine with different opset (9, 11, 12).

## Environment

JP Version: 4.6.0
TensorRT Version: 8.0.1.6
Device Type: Jetson Xavier
Nvidia Driver Version:
CUDA Version: 10.2.460-1
Python Version (if applicable): 3.6.9
Tensorflow Version (if applicable):tensorflow==2.6.2+nv21.12

## Relevant Files

Link to ONNX model (without set an explicit batch size- the error is the same for both cases) - https://dttusa-my.sharepoint.com/:u:/g/personal/pmaciolek_dttusa_onmicrosoft_com/EfXcHNvZruBGuuDS2OC1EkwB97NCgnTRVtP-kQfr_QcOfg?e=h9kl1H

## Steps To Reproduce

Commands in description.

**Comment by zerollzeng** [comment]
Can you try TRT 8.4?

**Comment by Pawel842** [comment]
> 

The newest Xavier I got have tensorrt==8.2.1.8
and the same error showed up.

**Comment by zerollzeng** [comment]
```
&&&& PASSED TensorRT.trtexec [TensorRT v8410] # /usr/src/tensorrt/bin/trtexec --onnx=tfmodel_lin_19.onnx
```
looks like the issue has been fixed in 8.4, can you upgrade your jetpack version?

**Comment by Pawel842** [comment]
> 

So it is required to install JP5.0 or 5.1?
Is it possible to only upgrade tensorrt to 8.4?

**Comment by zerollzeng** [comment]
I would suggest installing the latest Jetpack, there are other dependencies that will need to upgrade too.

**Comment by Pawel842** [comment]
Thanks, before upgrade I tried with adding input shape flag and explicit batch `--shapes=input_1:1x416x416x3 --explicitBatch` which solved the issue.

**Comment by zerollzeng** [comment]
Thanks, I'm gonna close this
