### ISSUE TITLE
Compiling TensorRT for python3.9 in Jetson Nano

### ISSUE THREAD

**Issue by kennethgomez01** [NVIDIA/TensorRT#2145]
I am just wondering how to compile TensorRT for python3.9, the tensor comes with Jetpack is for python3.6. 

Operating System. Ubuntu 18.04.6 LTS (GNU/Linux 4.9.253-tegra aarch64)
Module: Jetson Nano Developer (4GB)

**Comment by kennethgomez01** [comment]
@d57montes Can you elaborate to how to accomplish this? Because whenever I run the ./build.sh I am getting the "no Make File"

**Comment by d57montes** [comment]
If you look inside build.sh, there's some environment variables that have to be set. Did you set those all correctly?

**Comment by kennethgomez01** [comment]
Yes, I set them accordingly to settings. But since I am not an expert or experienced in compiling TensorRT directly from the source, it confused me. It would be better if you could provide some steps to support your ideas for accomplishing this. But I thank you for your help.

**Comment by d57montes** [comment]
There are no additional steps other than the ones provided in TensorRT/python/README.md. If you're receiving any errors, it might help to share the commands you ran and the output.

From the issue I linked above (#1670):
```
# Create a directory for external sources and download pybind11 into it.
export EXT_PATH=~/external

mkdir -p $EXT_PATH && cd $EXT_PATH
git clone https://github.com/pybind/pybind11.git

# Add Main Headers
wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz
tar -xvf Python-3.9.9.tgz
mkdir -p $EXT_PATH/python3.9/include
cp -r Python-3.9.9/Include/* $EXT_PATH/python3.9/include/

# Add PyConfig.h
wget http://ftp.jp.debian.org/debian/pool/main/p/python3.9/libpython3.9-dev_3.9.9-1_arm64.deb
ar x libpython3.9-dev_3.9.9-1_arm64.deb
tar -xvf data.tar.xz
cp -r ./usr/include/aarch64-linux-gnu/python3.9/pyconfig.h $EXT_PATH/python3.9/include/

# Build Python bindings
cd $TRT_OSSPATH/python
PYTHON_MAJOR_VERSION=3 PYTHON_MINOR_VERSION=9 TARGET_ARCHITECTURE=aarch64-linux-gnu ./build.sh
```
If you do the above (with the new links), and recursively clone this repo (`git clone --recursive https://github.com/NVIDIA/TensorRT.git`), it should be good to go.

**Comment by kennethgomez01** [comment]
Thanks for your reply. The issues occur when I enter the following command as follow.
`cd $TRT_OSSPATH/python
PYTHON_MAJOR_VERSION=3 PYTHON_MINOR_VERSION=9 TARGET_ARCHITECTURE=aarch64-linux-gnu ./build.sh`

The cd $TRT_OSSPATH/python  directory has no build.sh only folder name build.

**Comment by kennethgomez01** [comment]
This solved the problem by changing the build.sh /workspace/TensorRT to the location of TensorRT(Clone from Github)

**Comment by kennethgomez01** [comment]
This solved the problem by changing the build.sh /workspace/TensorRT to the location of TensorRT(Clone from Github)

**Comment by Zephyr69** [comment]
I'm following the same instructions trying to build tensorrt for python3.8 but got a bunch of the same type of error:

In file included from /home/jetson/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/jetson/external/pybind11/include/pybind11/cast.h:13,
                 from /home/jetson/external/pybind11/include/pybind11/attr.h:13,
                 from /home/jetson/external/pybind11/include/pybind11/pybind11.h:45,
                 from /home/jetson/TensorRT/python/include/ForwardDeclarations.h:29,
                 from /home/jetson/TensorRT/python/src/infer/pyAlgorithmSelector.cpp:18:
/home/jetson/external/pybind11/include/pybind11/detail/common.h:124:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.


Jetson Xavier NX developer kit
Jetpack 4.6.2
CUDA 10.2
Python3.6.9 and 3.8.0 are both working normally.
