### ISSUE TITLE
How to add QDQ before LeakyRelu

### ISSUE THREAD

**Issue by pangr** [NVIDIA/TensorRT#2147]
## Environment

**TensorRT Version 8.4: 
**NVIDIA GPU p40: 
**NVIDIA Driver Version 470: 
**CUDA Version 11.0: 
**CUDNN Version 8.1: 
**Operating System linux: 
**Python Version (if applicable) 3.6: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

How to add QDQ before LeakyRelu

**Comment by ttyio** [comment]
Closing since I see Q/DQ is already inserted in #2162, thanks!
