### ISSUE TITLE
For any input TensorRT model output is all zero 

### ISSUE THREAD

**Issue by li2508264** [NVIDIA/TensorRT#2151]
## Description

Generate a trt model by onnx ,but the output of trt is all zero ,just a zeros array, even different input.
This is the onnx model: https://drive.google.com/file/d/1CgVeSOk51NdZtSwQjO2kJ6u5oc8NyiLe/view?usp=sharing
my trt file : https://drive.google.com/file/d/17MF_M2BzTb7qvtoGKxmChsbUM0dVKhvI/view?usp=sharing
the code of onnx to trt:
```
    onnx_file_path = "model_128.onnx"
    engine_file_path = "model.trt"
    image = np.zeros((32,3,128,128),dtype='float32')+0.3
    with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
        inputs, outputs, bindings = common.allocate_buffers(engine,context)
        # Do inference
        # Set host input to the image. The common.do_inference function will copy the input to the GPU before executing.
        inputs[0].host = image
        trt_outputs = common.do_inference_v2(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=cuda.Stream())
    print(trt_outputs[0].shape)
    print(trt_outputs)
```
the code of get_engine：
```
def get_engine(onnx_file_path, engine_file_path=""):
    def build_engine():
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network(
            common.EXPLICIT_BATCH
        ) as network, builder.create_builder_config() as config, trt.OnnxParser(
            network, TRT_LOGGER
        ) as parser, trt.Runtime(
            TRT_LOGGER
        ) as runtime:
            config.max_workspace_size = 1 << 32  # 256MiB
            builder.max_batch_size =32
            #builder.fp16_mode = True
            # Parse model file
            with open(onnx_file_path, "rb") as model:
                print("Beginning ONNX file parsing")
                if not parser.parse(model.read()):
                    print("ERROR: Failed to parse the ONNX file.")
                    for error in range(parser.num_errors):
                        print(parser.get_error(error))
                    return None
            # The actual yolov3.onnx is generated with batch size 64. Reshape input to batch size 1
            network.get_input(0).shape = [32, 3, 128,128]
            print("Completed parsing of ONNX file")
            plan = builder.build_serialized_network(network, config)
            engine = runtime.deserialize_cuda_engine(plan)
            print("Completed creating Engine")
            with open(engine_file_path, "wb") as f:
                f.write(plan)
            return engine
    if os.path.exists(engine_file_path):
        # If a serialized engine exists, use it instead of building an engine.
        print("Reading engine from file {}".format(engine_file_path))
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
    else:
        return build_engine()
```
the code of  do_inference_v2 and allocate:
```
def allocate_buffers(engine, context):
    dtype = trt.nptype(engine.get_binding_dtype('input'))
    assert trt.nptype(engine.get_binding_dtype('output')) == dtype
    bindings = []

    dims_in = context.get_binding_shape(0)
    hmem_in = cuda.pagelocked_empty(trt.volume(dims_in), dtype)
    dmem_in = cuda.mem_alloc(hmem_in.nbytes)
    bindings.append(int(dmem_in))
    inputs = [HostDeviceMem(hmem_in, dmem_in)]

    dims_out = context.get_binding_shape(1)
    hmem_out = cuda.pagelocked_empty(trt.volume(dims_out), dtype)
    dmem_out = cuda.mem_alloc(hmem_out.nbytes)
    bindings.append(int(dmem_out))
    outputs = [HostDeviceMem(hmem_out, dmem_out)]
    return inputs, outputs,bindings
```
```
def do_inference_v2(context, bindings, inputs, outputs, stream):
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    stream.synchronize()
    return [out.host for out in outputs]
```
## Environment

**TensorRT Version**: 8.4.0.6
**NVIDIA GPU**:  3090 
**NVIDIA Driver Version**:  470.57.02
**CUDA Version**: 11.4
**CUDNN Version**: 8.2.4
**Operating System**: ubuntu 20.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files
This is the onnx model: https://drive.google.com/file/d/1CgVeSOk51NdZtSwQjO2kJ6u5oc8NyiLe/view?usp=sharing
trt file : https://drive.google.com/file/d/17MF_M2BzTb7qvtoGKxmChsbUM0dVKhvI/view?usp=sharing

## Steps To Reproduce

can use trt file and input a random matrix

**Comment by zerollzeng** [comment]
I can reproduce it using polygraphy.
```
[I] onnxrt-runner-N0-07/15/22-09:26:31
    ---- Inference Input(s) ----
    {input [dtype=float32, shape=(32, 3, 128, 128)]}
[I] onnxrt-runner-N0-07/15/22-09:26:31
    ---- Inference Output(s) ----
    {output [dtype=float32, shape=(32, 10)]}
[I] onnxrt-runner-N0-07/15/22-09:26:31  | Completed 1 iteration(s) in 99.72 ms | Average inference time: 99.72 ms.
[I] Accuracy Comparison | trt-runner-N0-07/15/22-09:26:31 vs. onnxrt-runner-N0-07/15/22-09:26:31
[I]     Comparing Output: 'output' (dtype=float32, shape=(32, 10)) with 'output' (dtype=float32, shape=(32, 10))
[I]     Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
[I]         trt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378
[I]         onnxrt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378
[I]         Error Metrics: output
[I]             Minimum Required Tolerance: elemwise error | [abs=1.3784e-07] OR [rel=8.0147e-06] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=3.1714e-08, std-dev=2.4764e-08, var=6.1325e-16, median=2.9802e-08, min=0 at (0, 6), max=1.3784e-07 at (17, 4), avg-magnitude=3.1714e-08
[I]             Relative Difference | Stats: mean=1.0946e-06, std-dev=1.4925e-06, var=2.2274e-12, median=4.3466e-07, min=0 at (0, 6), max=8.0147e-06 at (11, 7), avg-magnitude=1.0946e-06
[I]         PASSED | Difference is within tolerance (rel=1e-05, abs=1e-05)
[I]     PASSED | All outputs matched | Outputs: ['output']
[I] PASSED | Command: /home/zeroz/.local/bin/polygraphy run model_128.onnx --trt --onnxrt
```
[I]         trt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378
[I]         onnxrt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378

**Comment by li2508264** [comment]
> I can reproduce it using polygraphy.
> 
> ```
> [I] onnxrt-runner-N0-07/15/22-09:26:31
>     ---- Inference Input(s) ----
>     {input [dtype=float32, shape=(32, 3, 128, 128)]}
> [I] onnxrt-runner-N0-07/15/22-09:26:31
>     ---- Inference Output(s) ----
>     {output [dtype=float32, shape=(32, 10)]}
> [I] onnxrt-runner-N0-07/15/22-09:26:31  | Completed 1 iteration(s) in 99.72 ms | Average inference time: 99.72 ms.
> [I] Accuracy Comparison | trt-runner-N0-07/15/22-09:26:31 vs. onnxrt-runner-N0-07/15/22-09:26:31
> [I]     Comparing Output: 'output' (dtype=float32, shape=(32, 10)) with 'output' (dtype=float32, shape=(32, 10))
> [I]     Tolerance: [abs=1e-05, rel=1e-05] | Checking elemwise error
> [I]         trt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378
> [I]         onnxrt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378
> [I]         Error Metrics: output
> [I]             Minimum Required Tolerance: elemwise error | [abs=1.3784e-07] OR [rel=8.0147e-06] (requirements may be lower if both abs/rel tolerances are set)
> [I]             Absolute Difference | Stats: mean=3.1714e-08, std-dev=2.4764e-08, var=6.1325e-16, median=2.9802e-08, min=0 at (0, 6), max=1.3784e-07 at (17, 4), avg-magnitude=3.1714e-08
> [I]             Relative Difference | Stats: mean=1.0946e-06, std-dev=1.4925e-06, var=2.2274e-12, median=4.3466e-07, min=0 at (0, 6), max=8.0147e-06 at (11, 7), avg-magnitude=1.0946e-06
> [I]         PASSED | Difference is within tolerance (rel=1e-05, abs=1e-05)
> [I]     PASSED | All outputs matched | Outputs: ['output']
> [I] PASSED | Command: /home/zeroz/.local/bin/polygraphy run model_128.onnx --trt --onnxrt
> ```
> 
> [I] trt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378 [I] onnxrt-runner-N0-07/15/22-09:26:31: output | Stats: mean=-0.0028956, std-dev=0.094472, var=0.008925, median=-0.013166, min=-0.17494 at (26, 3), max=0.1333 at (24, 5), avg-magnitude=0.07378

Thx your reply @zerollzeng . So it means the inference code of python is too old？Sorry, polygraphy means the output not zeros?

**Comment by zerollzeng** [comment]
Sorry, polygraphy means the output not zeros?
-> yes

**Comment by SunflowerAries** [comment]
@li2508264 hi, I meet the same problems, did you figure out how to deal with this? should we use things like polygraphy? Hope for your reply
