### ISSUE TITLE
addFullyConnected will be  replaced by  addMatrixMultiply  + addElementWise?

### ISSUE THREAD

**Issue by zhoutianzi666** [NVIDIA/TensorRT#2152]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/39978853/179146538-cd130d0f-def6-41d4-a6d8-7d9c834001db.png">

**Comment by zerollzeng** [comment]
It should still work in 8.4 but will be deprecated in the future. more info: https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-0-EA
