### ISSUE TITLE
How to compile tensorrt in safety runtime on GTX 30* series.

### ISSUE THREAD

**Issue by JackSnowWolf** [NVIDIA/TensorRT#2156]
When I used GA version for 8.4.1 on GTX 3090 (installed with deb), I want to convert a simple resetnet50 onnx model to trt engine with trtexec in safety model. With using `--safe` flag, it said I didn't have safety runtime. I'm not sure about how to get an engine in safety mode on GTX 3090. I saw TensorRT had already provide `safe` runtime header in include folder.

Do you provide safe runtime `.so` lib file, Or I need to figure out how to compile a safe runtime lib on GTX 3090.

**Comment by zerollzeng** [comment]
Safety is only for the Drive Platform(QNX).  @nvpohanh should we remove this flag in standard build?

**Comment by JackSnowWolf** [comment]
Thanks!
So, if I want to get a serialized engine plan in safety, I have to dump model on Drive Platform(QNX)?

**Comment by zerollzeng** [comment]
> So, if I want to get a serialized engine plan in safety, I have to dump model on Drive Platform(QNX)?

Yes

**Comment by ZhenshengLee** [comment]
> Safety is only for the Drive Platform(QNX).

I am a DriveAGX Orin developer, could you provide any online doc/material about tensorrt safety runtime/mode?

I've searched a lot with google, and found a little.

Thanks. @zerollzeng

**Comment by zerollzeng** [comment]
It should be shipped with the DOS SDK.
