### ISSUE TITLE
TopK layer bug

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#216]
## Description

`softmax_layer.get_output(0).shape`  -----> ( 4, 128, 21128, 1, 1 ) this layer's output is correct.

`topk_layer = network.add_topk(input=softmax_layer.get_output(0),op=trt.tensorrt.TopKOperation.MAX,k=20,axes=4)`

 I get results like:
```
[[[[[nan]]

   [[nan]]

   [[nan]]

   ...

   [[nan]]

   [[nan]]

   [[nan]]]
```

## Environment

**TensorRT Version**: 6.0.1
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by taomiao** [comment]
some new find-outs, set topk_layer's K=10，it works well.

**Comment by taomiao** [comment]
K=20 is still a issue

**Comment by rmccorm4** [comment]
Hi @taomiao,

Can you verify this issue still happens on TensorRT 7.0?  If so, please provide a script to reproduce the error.

**Comment by rmccorm4** [comment]
Closing since no response
