### ISSUE TITLE
‘cudaGraph_t’ was not declared in this scope

### ISSUE THREAD

**Issue by allenling** [NVIDIA/TensorRT#217]
build in x86_64

`cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.1 -DCUDNN_VERSION=7.6  -DBUILD_SAMPLES=OFF`

could not find cudaGraph_t,cudaGraphExec_t..

**Comment by allenling** [comment]
well, reinstall cuda, and download cudnn, copy libs and include into cuda install dir, get rid of this

**Comment by rmccorm4** [comment]
This was probably just an issue with linked libraries / paths. 

I'm glad reinstalling solved your issue, this is frequently the easiest route compared to installing/updating individual components :slightly_smiling_face:
