### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005): trt.volume(engine.get_binding_shape(binding))

### ISSUE THREAD

**Issue by WangRuixin93** [NVIDIA/TensorRT#2171]
os： win10
cuda: 11.0
cudnn: 8.0.4
Tensorrt: 8.2.1.8
API: python
IDE: pycharm

when I run the code:
'''''''''''''''''''''''''''''''''''''''''''''''''''''
for binding in engine:
    size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size
    dtype = trt.nptype(engine.get_binding_dtype(binding))
    host_mem = cuda.pagelocked_empty(size, dtype)
    device_mem = cuda.mem_alloc(host_mem.nbytes)
    bindings.append(int(device_mem))
    if engine.binding_is_input(binding):
        inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))
'''''''''''''''''''''''''''''''''''''''''''''''''''''''
it was stuck in the line "size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size" for about one/two mins, then broke with "Process finished with exit code -1073741819 (0xC0000005)" in pycharm. When I run the code in the command line, it returns nothing and finshed.

Strangely, I can get:
x = engine.get_binding_shape(binding) is (1,3,640,640) with type  <class 'tensorrt.tensorrt.Dims'> and
when I change this line to "size = trt.volume((1,3,640,640)) * engine.max_batch_size", 
it passed where (1,3,640,640) is my input shape. 
It is a bug or I missed something?

**Comment by pranavm-nvidia** [comment]
@WangRuixin93 I think this should be fixed already in TensorRT 8.4

**Comment by WangRuixin93** [comment]
@pranavm-nvidia  do I need to low my cudnn version if using TensorRT 8.4?

**Comment by WangRuixin93** [comment]
@pranavm-nvidia Thanks, solved.

**Comment by zerollzeng** [comment]
close
