### ISSUE TITLE
ThreadSafeLogger Internal Error (Assertion mRefCount > 0 failed. )

### ISSUE THREAD

**Issue by CarlPoirier** [NVIDIA/TensorRT#2172]
## Description

Hi, I'm trying to load my TensorRT serialized engine in C++. I am greeted with the following error:
`2: [logging.cpp::nvinfer1::'anonymous-namespace'::ThreadSafeLogger::decRefCount::61] Error Code 2: Internal Error (Assertion mRefCount > 0 failed. )`
Do you know what can cause this error? I did not find anything about it.

## Environment

**TensorRT Version**: 8.4.1.5
**NVIDIA GPU**: GTX 1050Ti
**NVIDIA Driver Version**: 472.50
**CUDA Version**: 11.4
**CUDNN Version**: 8.2.4
**Operating System**: Windows 10
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

If need be, I can work on a serialized engine I can share, but you would need the same GPU.

## Steps To Reproduce

Based on the examples (Was running fine before with TRT 7.2.3.4. I did recreate the engine with 8.4.1.5), I use the following code:

```
// Class to log errors, warnings, and other information during the build and inference phases
class Logger : public nvinfer1::ILogger
{
public:
	void log(Severity severity, const char* msg) noexcept override {
		// remove this 'if' if you need more logged info
		if ((severity == Severity::kERROR) || (severity == Severity::kINTERNAL_ERROR)) {
			std::cout << msg << "\n";
		}
	}
} gLogger;

int main()
{
	std::ifstream file("model.trt", std::ios::binary);
	file.seekg(0, file.end);
	size_t size = file.tellg();
	file.seekg(0, file.beg);
	std::vector<char> modelStream(size);
	file.read(modelStream.data(), size);
	file.close();

	nvinfer1::IRuntime* runtime = nvinfer1::createInferRuntime(gLogger);
	nvinfer1::ICudaEngine* engine = runtime->deserializeCudaEngine(modelStream.data(), modelStream.size());
	nvinfer1::IExecutionContext* context = engine->createExecutionContext();

	auto nbBindings = engine->getNbBindings();

	return 0;
}
```

**Comment by zerollzeng** [comment]
I guess this is related to the resource lifetime of ILogger. Can you try below?
1. check whether trtexec can reproduce this error.

```
trtexec --loadEngine=model.trt
```
2. if (1 works well, then try free the object after using it
```
        nvinfer1::IRuntime* runtime = nvinfer1::createInferRuntime(gLogger);
	nvinfer1::ICudaEngine* engine = runtime->deserializeCudaEngine(modelStream.data(), modelStream.size());
	nvinfer1::IExecutionContext* context = engine->createExecutionContext();

	auto nbBindings = trtEngine->getNbBindings();
        delete runtime;
        delete engine ;
        delete context ;
```
3. if (1 and (2 both failed, can your provide the whole sample that I can reproduce on my side?

**Comment by zerollzeng** [comment]
@pranavm-nvidia for viz

**Comment by CarlPoirier** [comment]
Hi @zerollzeng,

1. works well. For 2, I guess you meant ->destroy() instead of delete, because the destructor is inaccessible.

But actually, it looks like it's the call to engine->createExecutionContext() which returns 0x1 instead of a valid pointer. So it explains why I get the original error when I call engine->getNbBindings(). What does this 0x1 mean? I could not find anything in the documentation.

Thanks

**Comment by zerollzeng** [comment]
Perhaps check whether `modelStream.data(), modelStream.size()' is valid.

**Comment by CarlPoirier** [comment]
Yes, they are. Size corresponds exactly to the file size on disk, and the chars are valid, too.

The exact same code was working with TensorRT 7.2.3.4. I'll compare with the trtexec source code to try to find out the issue.

**Comment by CarlPoirier** [comment]
It turns out I was still using a header from 7.2.3.4, but was loading 8.4.1.5 at runtime. Everything works now. Thanks for your help.
