### ISSUE TITLE
README erro

### ISSUE THREAD

**Issue by Wyatthy** [NVIDIA/TensorRT#2173]
## In TensorRT/samples/sampleDynamicReshape/README.md file

When building engines, the code `auto preprocessorConfig = makeUnique(builder->createNetworkConfig());` should be `auto preprocessorConfig = makeUnique(builder->createBuilderConfig());`

**Comment by zerollzeng** [comment]
Thanks for report this, we will fix it

**Comment by zerollzeng** [comment]
Internal MR filed, close this.
