### ISSUE TITLE
The engine plan file is generated on an incompatible device,but I've rebuild it already.

### ISSUE THREAD

**Issue by aixinbei** [NVIDIA/TensorRT#2177]
## Description
I met a error says that: 
`6: The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 8.6, please rebuild.
4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
`
but I have built my trt file from onnx file on my device like this:
`trtexec --onnx=voxel0711_B.onnx --saveEngine=voxel_fp16.rt`

usually it should solve my problem but this time it doesnt work for me,and it shows very clear that my compute capability
is 6.1,so i dont understand why i got a compute 8.6:

`[07/22/2022-13:25:12] [I] === Device Information ===
[07/22/2022-13:25:12] [I] Selected Device: NVIDIA GeForce GTX 1050 Ti
[07/22/2022-13:25:12] [I] Compute Capability: 6.1
[07/22/2022-13:25:12] [I] SMs: 6
[07/22/2022-13:25:12] [I] Compute Clock Rate: 1.392 GHz
[07/22/2022-13:25:12] [I] Device Global Memory: 4037 MiB
[07/22/2022-13:25:12] [I] Shared Memory per SM: 96 KiB
[07/22/2022-13:25:12] [I] Memory Bus Width: 128 bits (ECC disabled)
[07/22/2022-13:25:12] [I] Memory Clock Rate: 3.504 GHz
`
I want to know how to fix this,thx

## Environment

**TensorRT Version 8.0.1.6: 
**NVIDIA GPU : GeForce GTX 1050 Ti
**NVIDIA Driver Version**: 470.129.06
**CUDA Version**: 11.3.1
**CUDNN Version**: 8.2
**Operating System**: ubuntu 20.04

**Comment by zerollzeng** [comment]
When you deserialize the engine, the GPU you are using is not 1050ti. try using CUDA_VISIBLE_DEVICES=correct_device trtexec --loadEngine=model.trt

**Comment by aixinbei** [comment]
> When you deserialize the engine, the GPU you are using is not 1050ti. try using CUDA_VISIBLE_DEVICES=correct_device trtexec --loadEngine=model.trt

I have only one GPU on my computer and that is 1050ti.To avoid the influence of Intel integrated graphics card,I tried both CUDA_VISIBLE_DEVICES=0 and CUDA_VISIBLE_DEVICES=1.
when i use CUDA_VISIBLE_DEVICES=0 ,the same error like i posted.
and when I use CUDA_VISIBLE_DEVICES=1,it says that
`Unable to determine GPU memory usage
Unable to determine GPU memory usage
[runtime.cpp::isCudaInstalledCorrectly::41] Error Code 6: Internal Error (CUDA initialization failure with error 100. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)
`

**Comment by aixinbei** [comment]
I've found the problem and fix it.Thanks!

**Comment by zerollzeng** [comment]
@aixinbei What's the reason? Can you share it here? other people may run into this too.

**Comment by aixinbei** [comment]
> @aixinbei What's the reason? Can you share it here? other people may run into this too.

I am so shame for it's qutie stupid!So here is the problem:I load 2 engines in my program,the first one is from a trt file and the second one is directly loaded from an onnx file.It goes wrong when I go to the second file.There's never a problem whih my trt file from the very beginning.

**Comment by zerollzeng** [comment]
Thanks for the sharing, perhaps we can improve our error log for this case.

**Comment by zerollzeng** [comment]
on 8.4 if I load the onnx model as engine the error looks like
```
[03/22/2022-00:41:37] [E] Error[1]: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == magicTag failed.Magic tag does not match)
[03/22/2022-00:41:37] [E] Error[4]: [runtime.cpp::deserializeCudaEngine::49] Error Code 4: Internal Error (Engine deserialization failed.)
```
I thinks it's better now.
