### ISSUE TITLE
where can i find more examples(c++) of onnx dynamic input?

### ISSUE THREAD

**Issue by w1005444804** [NVIDIA/TensorRT#2179]
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment]
closing legacy issues. 
all the official samples are in https://github.com/NVIDIA/TensorRT/tree/release/10.0/samples, thanks!
