### ISSUE TITLE
[TensorRT] WARNING: Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#218]
## Description

what does this mean?

## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @taomiao,

Only certain hardware platforms support FP16 acceleration, see the support matrix here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#hardware-precision-matrix

You can compare your GPU's compute capability to the tables here (https://developer.nvidia.com/cuda-gpus#compute) with the support matrix to see if yours is supported.
