### ISSUE TITLE
Can't set GPU ID for buildEngineWithConfig? (or even if I can limit compute capability to 7.5) 

### ISSUE THREAD

**Issue by rlewkowicz** [NVIDIA/TensorRT#2185]
I'm running an implementation of yolo and it has two phases. The first is that it converts an onnx file to a tensor engine, the second that it runs inference. All of this worked until I put a 2nd gpu in the box. 

For run time, I can define the gpu id. But for building, it seems I cannot? It complains:
```
The engine plan file is generated on an incompatible device, expecting compute 7.5 got compute 8.6, please rebuild.
```
7.5 is my 2080ti, and 8.6 is my 3090ti. 

Poking around at the api, I saw this: 
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a0a816406cdb5bff7c1ab299d8e58e8d2

But it wasn't what I expected. Can I tell the builder to use a specific gpu?

**Comment by pranavm-nvidia** [comment]
@rlewkowicz You should be able to set the environment variable `CUDA_VISIBLE_DEVICES` or use the [`cudaSetDevice`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g159587909ffa0791bbe4b40187a4c6bb) CUDA API to do that.

**Comment by rlewkowicz** [comment]
I tried CUDA_VISIBLE_DEVICES, but it didn't seem to respect that. I don't know if that's an implementation thing, or the builder just ignores it. cudaSetDevice did it though, ty!
