### ISSUE TITLE
No speedup between fp16 and int8 precisions

### ISSUE THREAD

**Issue by senysenyseny16** [NVIDIA/TensorRT#2197]
## Description

TensorRT inference has no acceleration between FP16 and INT8 precision for YOLOv5 and MobileNetV3 networks.

Interestingly, MobileNetV3 is fully quantized -- all layers in INT8 precision, but this does not give a performance boost.
Backbone of YOLOv5 is also fully quantized.

Are these expected results?

**Visualized engines:**
[YOLOv5 FP16](https://user-images.githubusercontent.com/82811840/182115866-01e1470a-a9dd-4cff-b324-81cdbf7e9a95.svg)
[YOLOv5 FP16+INT8](https://user-images.githubusercontent.com/82811840/182116408-9154957d-feac-4e2f-92e4-92b56a0aaf8d.svg)
[MobileNetV3 FP16](https://user-images.githubusercontent.com/82811840/182115452-af13a906-e733-47bd-81b6-e84fc6e05d12.svg)
[MobileNetV3 FP16+INT8](https://user-images.githubusercontent.com/82811840/182114946-0ccfd6c9-ae18-4de1-98b0-be554fa4972c.svg)
 

| net \ throughput (trtexec, qps) | FP16 | FP16+INT8 |
| :---: | :---: | :---: |
| YOLOv5 | 83.06 | 89.04 |
| MobileNetV3 | 1286.08 | 1279.64 |

___
Visualization from **trex** (trt-engine-explorer)

<div align="center">YOLOv5 latency per layer type distribution</div>

<div align="center">FP16</div>

![yolo_fp16](https://user-images.githubusercontent.com/82811840/182112134-2a5c66f2-e6e2-480c-945f-95c781c64082.png)

<div align="center">FP16+INT8</div>

![yolo_int8](https://user-images.githubusercontent.com/82811840/182112173-75397175-b6b4-4de3-8d52-5409d48096a6.png)

___
<div align="center">MobileNetV3 latency per layer type distribution</div>

<div align="center">FP16</div>

![mbv3_fp16](https://user-images.githubusercontent.com/82811840/182113065-8804af6f-137a-4efc-8630-7c48b55da5a1.png)

<div align="center">FP16+INT8</div>

![mbv3_int8](https://user-images.githubusercontent.com/82811840/182113102-80936e20-9812-49e1-a8cb-7c489a4755df.png)

## Environment

**TensorRT Version**: 8.4.1.5
**NVIDIA GPU**: RTX 3080 Ti
**NVIDIA Driver Version**: 510.73.08
**CUDA Version**: 11.4.148
**CUDNN Version**: 8.2.4.15
**Operating System**: Ubuntu 20.04.3 LTS

## Relevant Files

[yolov5s.onnx.tar.gz](https://github.com/NVIDIA/TensorRT/files/9232663/yolov5s.onnx.tar.gz)
[mobilenetv3.onnx.tar.gz](https://github.com/NVIDIA/TensorRT/files/9232669/mobilenetv3.onnx.tar.gz)

## Steps To Reproduce

```bash
trtexec --onnx=yolov5s.onnx --fp16 --avgRuns=100000
trtexec --onnx=yolov5s.onnx --fp16 --int8 --avgRuns=100000

trtexec --onnx=mobilenetv3.onnx --fp16 --avgRuns=100000
trtexec --onnx=mobilenetv3.onnx --fp16 --int8 --avgRuns=100000
```

**Comment by zerollzeng** [comment]
I can't reproduce it using RTX 8000
[mobilenetv3_fp16.txt](https://github.com/NVIDIA/TensorRT/files/9251138/mobilenetv3_fp16.txt)
[mobilenetv3_int8.txt](https://github.com/NVIDIA/TensorRT/files/9251139/mobilenetv3_int8.txt)
[yolov5s_fp16.txt](https://github.com/NVIDIA/TensorRT/files/9251140/yolov5s_fp16.txt)
[yolov5s_int8.txt](https://github.com/NVIDIA/TensorRT/files/9251141/yolov5s_int8.txt)

**Comment by senysenyseny16** [comment]
Hehe 8000 :), Could you try to reproduce these measurements on RTX 30xx series?

**Comment by zerollzeng** [comment]
Will do, seeking the 3080Ti card now :)

**Comment by zerollzeng** [comment]
Results on 3090:
```
# cat *.txt | grep -E "PASSED | GPU Compute Time: min"
[08/04/2022-13:33:01] [I] GPU Compute Time: min = 0.562164 ms, max = 0.58374 ms, mean = 0.570549 ms, median = 0.570374 ms, percentile(99%) = 0.577576 ms
&&&& PASSED TensorRT.trtexec [TensorRT v8401] # trtexec --onnx=mobilenetv3.onnx --fp16 --profilingVerbosity=detailed --verbose --dumpProfile --dumpLayerInfo --separateProfileRun --noDataTransfers
[08/04/2022-13:36:52] [I] GPU Compute Time: min = 0.430908 ms, max = 0.455566 ms, mean = 0.434 ms, median = 0.434082 ms, percentile(99%) = 0.441528 ms
&&&& PASSED TensorRT.trtexec [TensorRT v8401] # trtexec --onnx=mobilenetv3.onnx --fp16 --profilingVerbosity=detailed --verbose --dumpProfile --dumpLayerInfo --separateProfileRun --noDataTransfers --int8
[08/04/2022-13:49:19] [I] GPU Compute Time: min = 4.91724 ms, max = 5.01453 ms, mean = 4.97035 ms, median = 4.97668 ms, percentile(99%) = 4.99609 ms
&&&& PASSED TensorRT.trtexec [TensorRT v8401] # trtexec --onnx=yolov5s.onnx --fp16 --profilingVerbosity=detailed --verbose --dumpProfile --dumpLayerInfo --separateProfileRun --noDataTransfers --int8
[08/04/2022-13:42:59] [I] GPU Compute Time: min = 7.07275 ms, max = 7.13623 ms, mean = 7.11493 ms, median = 7.1178 ms, percentile(99%) = 7.13113 ms
&&&& PASSED TensorRT.trtexec [TensorRT v8401] # trtexec --onnx=yolov5s.onnx --fp16 --profilingVerbosity=detailed --verbose --dumpProfile --dumpLayerInfo --separateProfileRun --noDataTransfers
```

**Comment by zerollzeng** [comment]
> p.s. for mobilenet, x1.35 speedup is ok?

Yes I thinks it's expected, I can see the final engine structure is different between FP16 and INT8, also the GPU memory bandwidth will affect the throughput, and mobilenet should be a memory-bound network.

**Comment by senysenyseny16** [comment]
@zerollzeng ok, thanks for your help.

**Comment by Susan19900316** [comment]
@senysenyseny16 [yolov5_fp16](https://user-images.githubusercontent.com/82811840/182115866-01e1470a-a9dd-4cff-b324-81cdbf7e9a95.svg) which tool did you use to get this image. Looking for your reply!

**Comment by senysenyseny16** [comment]
> @senysenyseny16 [yolov5_fp16](https://user-images.githubusercontent.com/82811840/182115866-01e1470a-a9dd-4cff-b324-81cdbf7e9a95.svg) which tool did you use to get this image. Looking for your reply!

https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/experimental/trt-engine-explorer

**Comment by Susan19900316** [comment]
> > @senysenyseny16 [yolov5_fp16](https://user-images.githubusercontent.com/82811840/182115866-01e1470a-a9dd-4cff-b324-81cdbf7e9a95.svg) which tool did you use to get this image. Looking for your reply!
> 
> https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/experimental/trt-engine-explorer

Thanks a lot!
