### ISSUE TITLE
Not possible to declare pytorch-quantization as a dependency

### ISSUE THREAD

**Issue by pommedeterresautee** [NVIDIA/TensorRT#2199]
## Description

Currently, the only compiled version is for python 3.8: 
https://developer.download.nvidia.com/compute/redist/pytorch-quantization/

Moreover, the setup.py imports Pytorch without try / catch.
https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/setup.py#L23

Therefore, it is impossible to declare this package as a dependency of another one: 
- on the compiled version the support is limited to an old version of Python (which is not by default on an updated Ubuntu for instance);
- if one try to declare it as a Git dependency, there is crash risk during compilation if Pytorch is not already installed (e.g. blank virtual env, docker, etc.).

The solution would be to offer pre-compiled version at least for recent Python version, so something like >= 3.8.

## Environment

**TensorRT Version**: 8.4
**NVIDIA GPU**: 3090
**NVIDIA Driver Version**: 515.48
**CUDA Version**: 11.7
**CUDNN Version**: 
**Operating System**: Ubuntu 22.04
**Python Version (if applicable)**: 3.9
**Tensorflow Version (if applicable)**: NA 
**PyTorch Version (if applicable)**: 1.12.0
**Baremetal or Container (if so, version)**: both

## Relevant Files
 N/A

## Steps To Reproduce

N/A

**Comment by zerollzeng** [comment]
![image](https://user-images.githubusercontent.com/38289304/182507239-aa7c7575-467c-4eb3-af7b-6956b66e6ed2.png)
See this error with python 3.9, I will check if we can improve this.

**Comment by ttyio** [comment]
@pommedeterresautee , prebuild package for 3.x provided, thx!

https://developer.download.nvidia.cn/compute/redist/pytorch-quantization/pytorch_quantization-2.1.2-py3-none-any.whl
