### ISSUE TITLE
tensorrt 6.0.1.5 torch1.3 onnx, build engine from onnx file fail, Network must have at least one out...

### ISSUE THREAD

**Issue by allenling** [NVIDIA/TensorRT#220]
```
def simple_conv1d():
    class TestNet(torch.nn.Module):
        def __init__(self):
            super(TestNet, self).__init__()
            self.conv = torch.nn.Conv1d(2, 4, kernel_size=(1,))
            return
        def forward(self, x):
            res = self.conv(x)
            return res
    x = torch.randn(3, 2, 10)
    net = TestNet()
    onnx_file_path = "simple_conv1d.onnx"
    torch.onnx.export(net, x, onnx_file_path, export_params=True, verbose=True, input_names=["data"])
    TRT_LOGGER = trt.Logger(trt.Logger.INFO)
    with trt.Builder(TRT_LOGGER) as builder:
        with builder.create_network() as network:
            with trt.OnnxParser(network,TRT_LOGGER) as parser:
                with open(onnx_file_path, 'rb') as model:
                    parser.parse(model.read())
                builder.max_workspace_size = 1<<30
                builder.fp16_mode = False
                builder.max_batch_size = 32
                builder.strict_type_constraints = False
                engine = builder.build_cuda_engine(network)
                with open("simple_conv1d.trt", "wb") as f:
                    f.write(engine.serialize())
    return
```
even such simple conv1d still fail...
got error `[TensorRT] ERROR: Network must have at least one output`

**Comment by rmccorm4** [comment]
Hi @allenling,

You need to mark the output nodes somehow.

You can either try using the `output_names` argument to `torch.onnx.export`, or you can try something like `network.mark_output(network.get_layer(network.num_layers-1).get_output(0))` using the TensorRT API after parsing the model.

**Comment by allenling** [comment]
@rmccorm4 
but the network.num_layers is 0!

```
def simple_conv1d():
    class TestNet(torch.nn.Module):
        def __init__(self):
            super(TestNet, self).__init__()
            self.conv = torch.nn.Conv1d(2, 4, kernel_size=(1,))
            return
        def forward(self, x):
            res = self.conv(x)
            return res
    onnx_file_path = "simple_conv1d.onnx"
#     x = torch.randn(3, 2, 10)
#     net = TestNet()
#     torch.onnx.export(net, x, onnx_file_path, export_params=True, verbose=True, input_names=["data"])
    TRT_LOGGER = trt.Logger(trt.Logger.INFO)
    with trt.Builder(TRT_LOGGER) as builder:
        with builder.create_network() as network:
            with trt.OnnxParser(network,TRT_LOGGER) as parser:
                with open(onnx_file_path, 'rb') as model:
                    parser.parse(model.read())
                builder.max_workspace_size = 1<<30
                builder.fp16_mode = False
                builder.max_batch_size = 32
                builder.strict_type_constraints = False
                # ===============here, no layer!!!!!! network.num_layers is 0
                print(network.num_layers)
                network.mark_output(network.get_layer(network.num_layers-1).get_output(0))
                engine = builder.build_cuda_engine(network)
                with open("simple_conv1d.trt", "wb") as f:
                    f.write(engine.serialize())

```

**Comment by rmccorm4** [comment]
For the ONNX parser, `parser.parse()` returns True or False for whether it was able to parse the model. 

If the network num_layers is 0, then it probably failed to parse (returned False).

I can look into this model a bit further tomorrow when I'm back at a computer.

**Comment by allenling** [comment]
thanks so much!

indeed, parser.parse return False...

maybe i install wrong library?

looking forward to your reply.

**Comment by rmccorm4** [comment]
I don't think you installed the wrong library. 

It may be an issue with the ONNX model.

You can view your ONNX model in the browser with: https://lutzroeder.github.io/netron/ to examine and see if anything seems wrong about the model.

**Comment by rmccorm4** [comment]
Also sorry just noticed that in the title it mentions Pytorch 1.3 (in the future it will be easier for my to notice if you include the Environment section that the bug template asks for)

Pytorch 1.3 ONNX isn't supported by TensorRT 6.x, I think it's because the ONNX opset used in PyTorch 1.3 is higher than what TRT 6.x supports (up to opset 10).

If you downgrade to PyTorch 1.2 I think you'll be able to parse the model successfully.

**Comment by allenling** [comment]
sry for skipping env section

and yes, conv1d works after i downgrade to PyTorch 1.2

and  what i really want is lstm, and  start from a simple net


```
def simple_lstm():
    class TestNet(torch.nn.Module):
        def __init__(self):
            super(TestNet, self).__init__()
            self.lstm = torch.nn.LSTM(256,
                                256 // 2, 2,
                                batch_first=True, bidirectional=True)
            return
        def forward(self, x):
            self.lstm.flatten_parameters()
            res = self.lstm(x)
            return res
    x = torch.randn(30, 61, 256)
    net = TestNet()
    onnx_file_path = "simple_lstm.onnx"
    torch.onnx.export(net, x, onnx_file_path, export_params=True, verbose=True, input_names=["data"])
    TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
    with trt.Builder(TRT_LOGGER) as builder:
        with builder.create_network() as network:
            with trt.OnnxParser(network,TRT_LOGGER) as parser:
                with open(onnx_file_path, 'rb') as model:
                    suc = parser.parse(model.read())
                    print(suc)
                builder.max_workspace_size = 1<<30
                builder.fp16_mode = False
                builder.max_batch_size = 32
                builder.strict_type_constraints = False
                print(network.num_layers)
    return
```
 
and parser.parse return False, here are console output

```
  return (%131, %132, %133)

[TensorRT] VERBOSE: 17:Constant -> 
[TensorRT] VERBOSE: 18:Shape -> (3)
WARNING: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Successfully casted down to INT32.
False
2
```
 why casted down weights to INT32? weights should be float32..

**Comment by rmccorm4** [comment]
Hi @allenling,

It seems this issue is coming from the fact that LSTM isn't currently supported by the ONNX parser: https://github.com/onnx/onnx-tensorrt/blob/master/operators.md

Currently, it only supports LSTM by building the network directly through the API: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Graph/Layers.html#tensorrt.RNNOperation

**Comment by allenling** [comment]
@rmccorm4 

sad about lstm support, but thanks so much!

**Comment by rmccorm4** [comment]
Marking this as RFE for LSTM support

**Comment by rmccorm4** [comment]
Also, for users that are using a compatible version of Pytorch and experience the following related error:

```
[TensorRT] ERROR: Unused Input: data
```

A current work-around is to add some dummy layer (like `Identity`) and mark that as an output so that the input is considered "used"

**Comment by rmccorm4** [comment]
Hi @allenling,

TensorRT 7 should be released within the next few days with added RNN support and expanded ONNX op support. Check out https://developer.nvidia.com/tensorrt for more info, there's a TRT7 description at the bottom of the page.

Hopefully this will solve your issues! If not, please open a new issue, thanks!

**Comment by rmccorm4** [comment]
Update, it was released today 🙂

https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html#rel_7-0-0

https://developer.nvidia.com/nvidia-tensorrt-download

**Comment by allenling** [comment]
@rmccorm4 

trt7 seems does not works for #273 ...

**Comment by RizhaoCai** [comment]
> Update, it was released today 🙂
> 
> https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html#rel_7-0-0
> 
> https://developer.nvidia.com/nvidia-tensorrt-download

Hopefully, TensorRt 7 for jetpack will also come soon

**Comment by ioekg** [comment]
Hi, @rmccorm4 :
I encountered this problem, but I dont understand your resolution clearly. can you please give an example about this? thank you.

> Also, for users that are using a compatible version of Pytorch and experience the following related error:
> [TensorRT] ERROR: Unused Input: data
> 
> A current work-around is to add some dummy layer (like Identity) and mark that as an output so that the input is considered "used"
