### ISSUE TITLE
Polygraphy run results

### ISSUE THREAD

**Issue by oreo-lp** [NVIDIA/TensorRT#2205]
## Description
When I run `polygraphy run --onnxrt ./my_onnx.onnx  --save-inputs onnx_inputs.json` to save the inputs data of my onnx model, I am very puzzled by this onnx_inputs.json

The content of onnx_inputs.json is:
`
[
{
"input":{
    "array":"k05VTVBZAQB2AHsan"
}
}
]
`
how to conver the value to float?

**Comment by pranavm-nvidia** [comment]
You can load it like so:
```py
from polygraphy.json import load_json

inputs = load_json("onnx_inputs.json")
```
then, `inputs["array"]` should be a NumPy array

**Comment by ttyio** [comment]
Closing since no response for more than 3 weeks, please reopen if you still have question, thanks!
