### ISSUE TITLE
Dynamic dimensions required for input: x, but no shapes were provided. Automatically overriding shape to: 1x3x1x1

### ISSUE THREAD

**Issue by XL634663985** [NVIDIA/TensorRT#2208]
## Description
trtexec --onnx=model.onnx --minShapes=input:1x3x416x416 --optShapes=input:1x3x960x960 --maxShapes=input:1x3x1024x1024 --saveEngine=mnist.trt --workspace=2048

Still prompt：Dynamic dimensions required for input: x, but no shapes were provided. Automatically overriding shape to: 1x3x1x1

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
looks like the input name you specify is not correct, please check the input name of your onnx, 

Perhaps it should be
```
trtexec --onnx=model.onnx --minShapes=x:1x3x416x416 --optShapes=x:1x3x960x960 --maxShapes=x:1x3x1024x1024 --saveEngine=mnist.trt --workspace=2048
```

**Comment by XL634663985** [comment]
Thank you.I solved this problem

**Comment by zerollzeng** [comment]
Thanks, closed
