### ISSUE TITLE
Opencv compute graph, TensorRT support

### ISSUE THREAD

**Issue by oak-tree** [NVIDIA/TensorRT#2212]
Hey, 

## Background
Opencv introduce Compute graph, which every Opencv operation can be describe as graph op code. They took it further and, introduces the ability to use inference on DNN module as on item in the graph ( in-graph inference). 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/667153/182826844-f57d0222-63f5-4f04-954a-e3d61b94341b.png">
 

An example

<img width="603" alt="image" src="https://user-images.githubusercontent.com/667153/182826675-50e3e510-583e-47ab-82db-2e6c6e2dc761.png">

https://docs.opencv.org/4.0.0/d3/d7a/tutorial_gapi_anisotropic_segmentation.html

## Question

Is it possible to use `TensorRT` as `in-graph` inference? 

Thanks!

## sources:
https://github.com/opencv/opencv/wiki/files/2020-09-04-GAPI_Overview.pdf
https://github.com/opencv/opencv/wiki/Graph-AP

https://github.com/opencv/opencv/tree/4.x/modules/gapi

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by nvpohanh** [comment]
This is not on the roadmap.

**Comment by oak-tree** [comment]
is there a public roadmap of TensorRT?

**Comment by ttyio** [comment]
Sorry there is no public roadmap.
