### ISSUE TITLE
Can int be used as input?

### ISSUE THREAD

**Issue by 980202006** [NVIDIA/TensorRT#2213]
There is int type data in my inputs for indexing other data, how can I set the int type data as input, with set_input?

**Comment by zerollzeng** [comment]
I don't quite get your point, can you elaborate on your question?

Perhaps https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_tensor.html#a577d9c58f9f66282e7239e44c035749a can be helpful to you

**Comment by 980202006** [comment]
Thank you!
