### ISSUE TITLE
Is QAT (quantization-aware training) model obtained by pytorch-quantization compatible with DLA (Deep Learning Accelerator) ?

### ISSUE THREAD

**Issue by WeixiangXu** [NVIDIA/TensorRT#2222]
I am tring to obtain a QAT model with official [pytorch-quantization](https://github.com/NVIDIA/TensorRT/tree/master/tools/pytorch-quantization).

However, I notice that 
 (1) the quantization function used in DLA is 'roundWithTiesAwayFromZero' while it is 'roundWithTiesToEven' in pytorch-quantization.
 (2) DLA only supports 'IInt8EntropyCalibrator2' in PTQ.

My question is whether QAT model obtained by pytorch-quantization compatible with DLA?

Thanks!

**Comment by zerollzeng** [comment]
Currently, DLA doesn't support QAT yet, but there is some work we are doing on this.

**Comment by zerollzeng** [comment]
@pranavm-nvidia for viz

**Comment by WeixiangXu** [comment]
Is the reason why DLA does not support QAT that DLA does not support explicit quantization?

If I manually convert the explicit the explicit quantization into implicit quantization by manually merging the Q and DQ nodes in onnx graph, can it be supported by DLA?

Thanks.

**Comment by pranavm-nvidia** [comment]
Yes, if you convert it to implicit quantization, it would work with DLA.

**Comment by WeixiangXu** [comment]
Thanks for your reply!

For DLA deployment, besides implicit quantization, are there any other changes needed when using pytorch-quantization? (e.g. quantization function from roundWithTiesToEven to roundWithTiesAwayFromZero?)
@pranavm-nvidia
