### ISSUE TITLE
how to use sampleUffMaskRCNN with my own dataset and backbone

### ISSUE THREAD

**Issue by hwh-hit** [NVIDIA/TensorRT#223]
@rmccorm4 ## Description

## Steps To Reproduce

I have converted my trained weight to uff, i also change some params in two config.h, and i only get part of masks in gt. anything else should i change?

**Comment by Programmakememad** [comment]
Have you tried converting initial coco weight to uff before you started to deal with your weight? Whether the masks in gt are only parts?

**Comment by hwh-hit** [comment]
Yes, I hvae finished that, since the mask_rcnn_coco.h5 is a pretrained model, the masks are not so precious, but most of the instances in the test pic can be found. In my own trained weight, there are only two or three instances can be found ,though there are nearly 10 instances when inferred by h5.

**Comment by Programmakememad** [comment]
Whether you run the inference network using the converted uff weights in fp16 or int8? If your dataset is not large, inference by the uff in fp16 mode will remarkably loss precision comparing with that by h5 in fp32 mode.

**Comment by hwh-hit** [comment]
No, run the command line without param --fp16 or int8.

**Comment by rmccorm4** [comment]
Hi, please see here for more details on using a custom backbone: https://github.com/NVIDIA/TensorRT/issues/240
