### ISSUE TITLE
Tensorrt Multi Model Management

### ISSUE THREAD

**Issue by prnvjb** [NVIDIA/TensorRT#224]
What would be a better way to deploy multi models (tensorrt enngines) manually instead of tensorrt serving engine on a edge hardware like jetson nano?

**Comment by rmccorm4** [comment]
Hi @prnvjb,

Generally TensorRT Inference Server is the solution for multi-model management. If you're looking to use something else, or something specifically for edge hardware, maybe look into EGX: https://www.nvidia.com/en-us/data-center/products/egx-edge-computing/, though I don't know many details on it.
