### ISSUE TITLE
AttributeError:'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by chegnyanjun** [NVIDIA/TensorRT#225]
Hi,I am trying to use convert the ONNX model to tensorrt engine, but i met the problem above.And I saw some issues, it looks like my ONNX model have unsupported layer ,but actually, my ONNX model is a sample pytorch model (it is a unet++ model, I trained it in pytorch),and i use the nearest  mode(I saw it was supported in tensorrt6.0.1.5) to achieve upsample,so in unet++, there has no unsupported layer,but it indicated such problem, I look inside and I found the parser.parse() return False,so I was very werid and i hope you can help me.At last, my environment is pytorch 1.2, tensorrt 6.0.1.5,python3.7.I hope for your reply.tks.

**Comment by chegnyanjun** [comment]
1.

**Comment by xuhuaze707313** [comment]
Hi, have you solved this problem ?

**Comment by chegnyanjun** [comment]
look at this:https://github.com/onnx/onnx-tensorrt/issues/192
