### ISSUE TITLE
cannot convert 'const char*' to 'LPCWSTR in common.h

### ISSUE THREAD

**Issue by spacewalk01** [NVIDIA/TensorRT#2263]
## Description

Got the following error when using `common.h` library in samples.
ERROR:
`const char * is incompatible with parameter type of lpcwstr`

CODE:
``` 
inline void loadLibrary(const std::string& path)
{
#ifdef _MSC_VER
    void* handle = LoadLibrary(path.c_str());
#else
    int32_t flags{RTLD_LAZY};
```

## Environment

**TensorRT Version**: 8
**NVIDIA GPU**: 3070
**NVIDIA Driver Version**: 
**CUDA Version**: CUDA 11
**CUDNN Version**: 
**Operating System**: Windows 10
**Visual studio 2019**

**Comment by spacewalk01** [comment]
fixed the problem by making it as follows:
`inline void loadLibrary(const std::string& path)` -> `inline void loadLibrary(const std::wstring& path)`

**Comment by zerollzeng** [comment]
codes: https://github.com/NVIDIA/TensorRT/blob/87f3394404ff9f9ec92c906cd4c39b5562aea42e/samples/common/common.h#L893

Not sure if it's a bug since I know nothing about the windows platform. @oxana-nvidia @rajeevsrao for viz

**Comment by oxana-nvidia** [comment]
@spacewalk01 Is my understanding right that you are using Visual Studio? Could you please check `Project -> Properties -> Advanced (or. General for older versions) -> Character Set` option is set to `Use Multi-Byte Character Set` ?

**Comment by spacewalk01** [comment]
@oxana-nvidia, thank you for your suggestion, I cannot change it as you suggested because other source in my code uses `Unique character set`.

**Comment by oxana-nvidia** [comment]
I've added an internal bug to investigate how we can support both settings by default.

Tracking number: 3766800

**Comment by spacewalk01** [comment]
Closing it for now.
