### ISSUE TITLE
TRT PluginCan it support multiple outputs?

### ISSUE THREAD

**Issue by jacker-whh** [NVIDIA/TensorRT#2270]
## Description
TRT PluginCan it support multiple outputs ,I have implemented a multi-output plugin myself, but it will report an error in the next op node。

-------------------------SgnetAnchorsVpDynamic::getOutputDimensions-----------0
outputIndex:0
ret.d[0]:1539
ret.d[1]:77
ret.d[0]:0x2b5267c0
ret.d[1]:0x2b526a00
-------------------------SgnetAnchorsVpDynamic::getOutputDimensions-----------1index:0
index_type:0
[08/22/2022-22:03:19] [V] [TRT] Registering tensor: onnx::Reshape_571 for ONNX tensor: onnx::Reshape_571
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Aborted (core dumped)

Environment
**TensorRT Version :tensorrt 8.4
**GPU Type :v100
**Nvidia Driver Version :515
**CUDA Version :11.4
**CUDNN Version :8.2

**Comment by zerollzeng** [comment]
close since it's duplicate.
