### ISSUE TITLE
Where do Plugin determine whether fuse qdq or not?

### ISSUE THREAD

**Issue by Jiang-Stan** [NVIDIA/TensorRT#2283]
Thanks for your help in advance!

I wrote a custom plugins to support int8 input, but the log of ` trtexec --verbose `shows that a dq->my_op->q combination, which is expected to be fused as a my_op_int, is not fused together. The toy onnx model and trt model after fusion is shown below.
![2022-08-31 10-50-30 的屏幕截图](https://user-images.githubusercontent.com/74638604/187584481-30e7f73a-f473-4af9-84d9-557468f50980.png)

![2022-08-31 10-48-55 的屏幕截图](https://user-images.githubusercontent.com/74638604/187583671-7740df41-51fa-402e-8f75-1659bdd2548a.png)

It is said that custom plugins can't be fused with other operators. I am wondering whether the custom plugins can be fused with qdq to construct a custom int8 operator. If so, how can I create a custom qdq fusion? Or if there's any way telling tensorrt whether fuse a qdq operator with custom plugin or not?

Thank you!

**Comment by zerollzeng** [comment]
@ttyio Any suggestion here? I'm also interested in the answer :-)

**Comment by Jiang-Stan** [comment]
Hi, is there any suggestions for us?
