### ISSUE TITLE
Graphviz requirement for trt-engine-explorer

### ISSUE THREAD

**Issue by olivetom** [NVIDIA/TensorRT#2287]
Hi everyone, in the docs, at least in the [README.md](https://github.com/NVIDIA/TensorRT/blob/main/tools/experimental/trt-engine-explorer/README.md) file for Trex tool, there's no mention to graphviz as a requirement for generating the network graph svg file.
Cheers,
Mauricio

**Comment by zerollzeng** [comment]
It's in https://github.com/NVIDIA/TensorRT/blob/main/tools/experimental/trt-engine-explorer/requirements.txt

**Comment by zerollzeng** [comment]
@pranavm-nvidia maybe we should add a `pip install -r requirements.txt' in https://github.com/NVIDIA/TensorRT/tree/main/tools/experimental/trt-engine-explorer#installation

**Comment by netaz** [comment]
Thanks @olivetom, you are correct.

In TREX 0.1.4 I've added graphviz installation instructions to the README and also an installation script (`install.sh`) for the lazy ;-).
TREx 0.1.4 should be released soon (within the next couple of weeks). BTW, I've added a lot more options when rendering graphs so you will be able to choose which information to render and which not to.

@zerollzeng I think Mauricio is referring to the installation of the graphviz binary application, not the graphviz Python package.
@olivetom please correct me if I'm wrong.

**Comment by olivetom** [comment]
@netaz You're right. Binary package should be on the system for the python wrapper to work.
Thanks both of you @netaz @zerollzeng for the prompt response!

**Comment by ttyio** [comment]
closing since this is already solved, thanks all!
