### ISSUE TITLE
tensorrt test time is not stable

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [NVIDIA/TensorRT#2289]
Hello, when I use c++ to infer the engine file, when the nvidia driver version is a new version, the inference time is not stable(16-200ms)
![image](https://user-images.githubusercontent.com/55009436/187899026-9243a7df-b528-4718-884f-c3eeaec9aa38.png)

But inference time is stable（16ms） when nvidia driver version is old. For example, nvGameS.dll is 27 

I also tested different cuda version and trt version, I want to ask what is the reason for this, thanks for your answer.

**Comment by nvpohanh** [comment]
could you set your GPU to Performance mode?

**Comment by jiaqizhang123-stack** [comment]
Where should this be modified?

**Comment by jiaqizhang123-stack** [comment]
By modifying the parameters of the nvidia control panel, the test time is still unstable. What is the reason for this?

**Comment by nvpohanh** [comment]
Could be a driver bug...

**Comment by ttyio** [comment]
Closing since this seems not TRT bug, also for Windows I believe the OS and other app also try to use the GPU resource. Might need enable Windows TCC mode to make the perf stable.
