### ISSUE TITLE
cpu memory leak when change batch with setDeviceMemory

### ISSUE THREAD

**Issue by qq332982511** [NVIDIA/TensorRT#2290]
## Description

cpu memory leak when change batch with setDeviceMemory

## Environment

**TensorRT Version**:  7.2.2.3
**NVIDIA GPU**:  T4
**NVIDIA Driver Version**:  470.57.02
**CUDA Version**: 11.4
**CUDNN Version**: 8.2.1
**Operating System**: Ubuntu 18.04.5 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files
<img width="792" alt="lQLPJxakk_93mvjNAbrNBjCwlu0y_K9jWT8DDrYJ8wBuAA_1584_442" src="https://user-images.githubusercontent.com/12827094/187911956-3d5f8bb8-e1dd-45d2-a829-eaed4275da8d.png">

![image](https://user-images.githubusercontent.com/12827094/187912052-1f503928-92fe-4c38-b619-625bf8d066eb.png)

## Steps To Reproduce

instance context with createExecutionContextWithoutDeviceMemory  
call setDeviceMemory to set pointer when batch changed
asan and tcmalloc show that `setDeviceMemory` -> `cudnnCreatePoolingDescriptor`  lead to memory leak

**Comment by zerollzeng** [comment]
Can you provide a reproduce code? cc @jhalakp-nvidia for viz

**Comment by qq332982511** [comment]
> Can you provide a reproduce code? cc @jhalakp-nvidia for viz
Reproduce code in here
https://github.com/qq332982511/TensorRTIssue/tree/main/pooling_memleak

**Comment by zerollzeng** [comment]
I notice you are using TRT 7.2, can you do a test with the latest TRT 8.4? if there are still memory leaks I will take a look at it.

Thanks!

**Comment by qq332982511** [comment]
> I notice you are using TRT 7.2, can you do a test with the latest TRT 8.4? if there are still memory leaks I will take a look at it.
> 
> Thanks!

no leak on TensorRT-8.4.3.1
