### ISSUE TITLE
Invalid workspace buffer in custom plugin enqueue

### ISSUE THREAD

**Issue by Jsy0220** [NVIDIA/TensorRT#2291]
Hi, I have implemented a custom plugin inherited from nvinfer1::IPluginV2DynamicExt and this layer need some runtime cuda memory, so `getWorkspaceSize` returns non-zero. But when calling `enquue`, the pointer to workspace is still nullptr. Is there anything wrong ? Following are the example codes:
![WeChatWorkScreenshot_b55aa844-1441-4019-9f34-e164545be059](https://user-images.githubusercontent.com/6188672/187914800-a6543fa2-3154-4e85-b6c1-a251274f42ab.png)

TensorRT 8.4.0.6

**Comment by Jsy0220** [comment]
It is wired but `getWorkspaceSize` seems never be called. So how can i request the cuda memory ?

**Comment by zerollzeng** [comment]
I'm checking this with plugin expert, will come back to you when I have an answer :)

**Comment by zerollzeng** [comment]
I did an experiment on my plugin code, I can't reproduce this error. @Jsy0220 does your `getWorkspaceSize` function signature end with `noexcept`?

More info about the workspace:
A layer's workspace memory is not managed by the user. It is managed by TensorRT and reused across layers. getWorkspaceSize tells TensorRT how much workspace memory a layer needs during the engine building stage (which can be zero). TensorRT allocates the maximum size of workspace memory among all layers during the inference stage. void* workspace is the allocated workspace memory that is passed by TensorRT to a layer.

**Comment by Jsy0220** [comment]
Yes, thank you for your answer. I have known the reason.

**Comment by zerollzeng** [comment]
May I know what's the reason?

**Comment by demuxin** [comment]
After modifying the getWorkspaceSize function, if not rebuild the model engine, the workspace is still nullptr.
@zerollzeng
