### ISSUE TITLE
Quiz: you remove demo/BERT，can I convert a tensorflow bert to tensorrt bert directly ?

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#230]
## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by lapolonio** [comment]
the demo only shows squad. https://github.com/NVIDIA/TensorRT/tree/release/6.0/demo/BERT

**Comment by taomiao** [comment]
@lapolonio In the earlier demo，we build custom transformer layers , now the plugins are moved to default plugin dir. I tried the old "bert_builder.py" script, and I failed to build a bert engine.
"nm -D libnvinfer_plugin.so" shows no bert/plugins compiled in.

**Comment by lapolonio** [comment]
yeah those are created when you execute the instructions here: https://github.com/NVIDIA/TensorRT/tree/release/6.0/demo/BERT#4-build-and-run-the-example
or made available in docker image from instructions here: https://github.com/NVIDIA/TensorRT/blob/release/6.0/demo/BERT/python/build_examples.sh#L57

**Comment by rmccorm4** [comment]
Related to https://github.com/NVIDIA/TensorRT/issues/295
