### ISSUE TITLE
How to quantize concat and element-wise operators (add, mul, etc.) by pytorch_quantization?

### ISSUE THREAD

**Issue by shuo-ouyang** [NVIDIA/TensorRT#2305]
Hi guys, I quantized all conv2d/transposeconv2d/gemm/maxpooling ops in my pytroch model using pytorch_quantization and obtained a well-performed int8 model. Now I want to quantize concat and element-wise ops to improve inference performance, so is there any approach to implement quantized concat/add/mul, etc. in pytroch_quantization tools? Thank you~

It is noticed that the quantized modules are derived from`torch.nn.module` and `_utils.QuantInputMixin`, such as the following `QuantMaxPool2d` class. But concat/add/mul are not implemented as a module in pytorch, so I do not know how to quantize them...

```python
class QuantMaxPool2d(pooling.MaxPool2d, _utils.QuantInputMixin):
    """Quantized 2D maxpool"""
    def __init__(self, kernel_size, stride=None, padding=0, dilation=1,
                 return_indices=False, ceil_mode=False, **kwargs):
        super(QuantMaxPool2d, self).__init__(kernel_size, stride, padding, dilation,
                                             return_indices, ceil_mode)
        quant_desc_input = _utils.pop_quant_desc_in_kwargs(self.__class__, input_only=True, **kwargs)
        self.init_quantizer(quant_desc_input)

    def forward(self, input):
        quant_input = self._input_quantizer(input)
        return super(QuantMaxPool2d, self).forward(quant_input)
```

**Comment by zerollzeng** [comment]
@ttyio do we document those somewhere? I'm confused about those issues sometimes ^ ^.

**Comment by ttyio** [comment]
@shuo-ouyang , could you follow this sample to explicit insert Q/DQ pairs: https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py#L155

Thanks!

**Comment by shuo-ouyang** [comment]
Thanks for your response, the code you provided is what I want. By the way, can we do this insertion automatically?

**Comment by ttyio** [comment]
@shuo-ouyang , currently this monkey patch way cannot be inserted automatically. The correspond explain for the code link that I pasted is in https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html#further-optimization, hope it helps, thanks!

**Comment by shuo-ouyang** [comment]
Thanks, this doc is helpful~we can close this issue:)

**Comment by ttyio** [comment]
Thanks, closing

**Comment by Christian-lyc** [comment]
> https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html#further-optimization

Hi, could you share the link again, it doesn't exist now.
