### ISSUE TITLE
How to use trtexec with multiple inputs model

### ISSUE THREAD

**Issue by catalwaysright** [NVIDIA/TensorRT#2324]
Hi! I am coverting my onnx model to trt engine using trtexec. However, my model have 5 inputs with different names and dynamic shapes. How should deal with this use trtexec command?

**Comment by nvpohanh** [comment]
`trtexec --shapes=<input1>:<input1_shape>,<input2>:<input2_shape>,<input3>:<input3_shape>` etc.

**Comment by catalwaysright** [comment]
> 

so the dynamic dimension will be -1 in `<input_shape>` or we still have something like `minshape maxshape`?

**Comment by zerollzeng** [comment]
`trtexec --minShapes=<input1>:<input1_shape>,<input2>:<input2_shape>,<input3>:<input3_shape> --optShapes=<input1>:<input1_shape>,<input2>:<input2_shape>,<input3>:<input3_shape> --maxShapes=<input1>:<input1_shape>,<input2>:<input2_shape>,<input3>:<input3_shape>`
please refer to `trtexec -h`

**Comment by catalwaysright** [comment]
> 

So I ran the command `trtexec --onnx=encoder-temp_rnnt.onnx \
--saveEngine=encoder-trtexec.trt \
--minShapes=audio_signal:[1,80,1],length:[1] \
—optShapes=audio_signal:[1,80,1000],length:[1] \
—maxShapes=audio_signal:[1,80,10000],length:[1] `
and
`trtexec onnx=decoder_joint-temp_rnnt.onnx \
--saveEngine=decoder-trtexec.trt \
--shapes=encoder_outputs:[1,1024,1],targets:[1,1],target_length:[1],input-states-1:[2,1,640],input-states-2:[2,1,640]`
Both of them ended with `[E] stoi`
Did I miss something?

**Comment by jedivova** [comment]
Try this
trtexec --onnx=decoder_joint-temp_rnnt.onnx \ --saveEngine=decoder-trtexec.trt \ --shapes=encoder_outputs:1x1024x1, targets:1x1,target_length:1,input-states-1:2x1x640,input-states-2:2x1x640

**Comment by catalwaysright** [comment]
Thanks a lot! It works fine.
