### ISSUE TITLE
feature request: support pytorch torchdynamo

### ISSUE THREAD

**Issue by Jack47** [NVIDIA/TensorRT#2329]
Torch-TensorRT acts as an extension to TorchScript.  But there are models that are not supported by pytorch jit tracing, see [warning in jit tracing doc](https://pytorch.org/docs/stable/generated/torch.jit.trace.html). Would you guys have plan to support [torchDynamo](https://github.com/pytorch/torchdynamo) to get torch.fx.GraphModule instead of [jit.ScriptModule](https://pytorch.org/docs/stable/generated/torch.jit.ScriptModule.html#torch.jit.ScriptModule)?

>torchDynamo creates this FX Graph through bytecode analysis and is designed to mix Python execution with compiled backends to get the best of both worlds: usability and performance.

**Comment by zerollzeng** [comment]
@kevinch-nv for viz

**Comment by ttyio** [comment]
@Jack47  maybe https://github.com/pytorch/TensorRT this is the right place to ask this feature? since the tool is not owned by TensorRT, thanks!
