### ISSUE TITLE
Move `onnx-graphsurgeon` into a separate repo

### ISSUE THREAD

**Issue by KOLANICH** [NVIDIA/TensorRT#2341]
## Description

`onnx-graphsurgeon` is an extremily helpful tool used as a dependency in multiple other tools But it is unfortunately not available in pypi. Also I prefer to install pure python deps from source, and it is inconvenient to download whole TensorRT just to get `onnx-graphsurgeon`.

It is proposed to:
1. extract `graphsurgeon` into a separate git repo.
2. publish it on `pypi`.
3. setup CI publishing wheels to `pypi`

**Comment by KOLANICH** [comment]
P.S. `pypi` has a package with such a name, but it looks like a stub left by NVidia to reserve the name.

**Comment by pranavm-nvidia** [comment]
You can install it from the NVIDIA repo as [mentioned in the README](https://github.com/NVIDIA/TensorRT/tree/main/tools/onnx-graphsurgeon#using-prebuilt-wheels):
> python3 -m pip install onnx_graphsurgeon --index-url https://pypi.ngc.nvidia.com

**Comment by KOLANICH** [comment]
>You can install it from the NVIDIA PyPI as mentioned in the README:

I know, but I prefer to install from git.

**Comment by KOLANICH** [comment]
Also I'm not sure that `PEP 508` allows to specify `--index-url` to use it in package dependencies (not `requirements.txt`, but `PEP 621`-compliant `pyproject.toml`).

**Comment by KOLANICH** [comment]
It surely allows to specify whole this repo (with a subdir within it), but it will result in fetching the whole repo, since neither `pip`, nor `GitHub` support partial fetches.

**Comment by pranavm-nvidia** [comment]
Does a URL to the wheel work? https://developer.download.nvidia.com/compute/redist/onnx-graphsurgeon/onnx_graphsurgeon-0.3.20-py2.py3-none-any.whl

**Comment by KOLANICH** [comment]
It should work, but pinning to an exact version is highly undesireable.

**Comment by zhiqwang** [comment]
I guess you can try
```
python3 -m pip install -U 'git+https://github.com/NVIDIA/TensorRT.git#subdirectory=tools/onnx-graphsurgeon'
```

**Comment by ttyio** [comment]
closing since there is already solution, thanks all!
