### ISSUE TITLE
Onnx file of 2mb the file size increases to 25 mb in trt.

### ISSUE THREAD

**Issue by yshvrdhn** [NVIDIA/TensorRT#235]
## Description

Hi I have created a unet model in pytorch which has a size of 2 mb  in the onyx file. However if I convert it to trt file the size increases to 25 mb. 

## Environment

**TensorRT Version**: 5.0.3
**GPU Type**: xavier
**Nvidia Driver Version**: cuda 7
**CUDA Version**: 
**CUDNN Version**: cuDNN 7.5.0
**Operating System + Version**: ubuntu + 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.0.0
**Baremetal or Container (if container which image + tag)**: https://docs.nvidia.com/jetson/archives/jetpack-archived/jetpack-421/release-notes/index.html

**Comment by rmccorm4** [comment]
Hi @yshvrdhn,

Does this still happen in TensorRT 6.0 for you?

Jetpack 4.3 beta is available with TensorRT 6 to try out.

**Comment by rmccorm4** [comment]
Closing since no response. Feel free to update and I can reopen
