### ISSUE TITLE
trtexec log

### ISSUE THREAD

**Issue by ygygyeah** [NVIDIA/TensorRT#2350]
## Description

When I run trtexec, can verbose be saved directly to a log.txt? What parameters should I set?

## Environment

**TensorRT Version**: 8.2.1
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
`trtexec --onnx=model.onnx --verbose > log.txt` 

https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file
