### ISSUE TITLE
There is some questions about pytorch_quantization

### ISSUE THREAD

**Issue by Meize0729** [NVIDIA/TensorRT#2352]
When I use **def"_export_onnx_"** to save a onnx model, such as Resnet50 after quantization, I followed the example in the official documentation. But, it is a pity, the following problems arise：

D:\Object_d\TensorRT-main\tools\pytorch-quantization\pytorch_quantization\nn\modules\tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  c = amax.item() / bound

D:\Object_d\TensorRT-main\tools\pytorch-quantization\pytorch_quantization\nn\modules\tensor_quantizer.py:293: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])

When I use def"export_onnx" to export a model quantized ,like Resnet50, I think the scale of Quantizelinear operator maybe fixed just like the weights of Conv2d.

But when I use different dummy_input. The scale of Quantizelinear is not fixed. Is it Right?
How to solve this problem?

Thanks!!!
Thank you very much
It is very important for me!!!

**Comment by Meize0729** [comment]
"torch.fake_quantize_per_channel_affine" need scale=float, but amax is a tensor. When a tensor convert to an float，it can not record the data flow of Python values.
These are my thoughts on this issue. But there is no solution in mind

**Comment by zerollzeng** [comment]
@ttyio ^ ^
