### ISSUE TITLE
The difference of plugin method between sample "faster_rcnn" and "sample-ssd"?

### ISSUE THREAD

**Issue by SSSSER1994** [NVIDIA/TensorRT#236]
I find that tensorRT has already support the following layers to plugin: 
    RPROI_TRT
    Normalize_TRT
    PriorBox_TRT
    GridAnchor_TRT
    NMS_TRT
    LReLU_TRT
    Reorg_TRT
    Region_TRT
    Clip_TRT

sample "**faster-rcnn**" have a RPROI layer to plugin, and sample "**ssd**" have three layers to plugin (e.g. Normalize). They both use _**initLibNvInferPlugins**_ to link the _libnvinfer_plugin.so_.
However, why does "**faster-rcnn**" need a IPluginFactoryV2 class while "**ssd**" doesn't?

(I also tried to cancel the IPluginFactorV2 in  "**faster-rcnn**" and modify the the layer type from "IPlugin" to "RPROI", but it doesn't work.)

**Comment by SSSSER1994** [comment]
Besides, I also find that in "_**sampleuffssd**_" , things is different again, it write a IPluginV2 class and  IPluginCreator class, then use the REGISTER_TENSORRT_PLUGIN function. So where is the _IPluginFactoryV2_ ? 
I think the official developer guide is not detailed enough, I can't make it clear.

**Comment by rajeevsrao** [comment]
@SSSSER1994 going forward, we will only support plugins that implement the IPluginV2Ext and derivative interfaces (IPluginV2DynamicExt, IPluginV2IOExt). With these interfaces, the implementation is only required to provide the Plugin and Creator class implementations. The REGISTER macro registers the plugin creator with the global plugin registry from with the corresponding plugin can be queried. Please see sampleUffPluginV2Ext for example and let me know if you have more questions.
