### ISSUE TITLE
TypeError: deserialize_cuda_engine(): incompatible function arguments.

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/TensorRT#2362]
## Description

hi , bro.
@elezar @lukeyeager @zerollzeng
When ONNX transforms into Tensorrt model，The following error will be reported。
[09/29/2022-06:21:05] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Completed parsing ONNX file
[09/29/2022-06:21:28] [TRT] [E] 1: [convolutionBuilder.cpp::writeGlob::1338] Error Code 1: Cask (canImplement)
[09/29/2022-06:21:28] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
Traceback (most recent call last):
  File "torch2onnx.py", line 264, in <module>
    main()
  File "torch2onnx.py", line 247, in main
    engine = lane_model.onnx_to_tensorrt(cfg.onnx_simp_path)
  File "torch2onnx.py", line 181, in onnx_to_tensorrt
    engine = runtime.deserialize_cuda_engine(plan)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7ffa39a893b0>, None

## Environment

**TensorRT Version**: 8.4.3.1
**NVIDIA GPU**: 3080ti
**NVIDIA Driver Version**: 515
**CUDA Version**: 11.6
**CUDNN Version**: 8.4
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.11
**Baremetal or Container (if so, version)**:

**Comment by ywfwyht** [comment]
> Looks like an API usage issue here, can you provide the full code snippet that can reproduce this error?

def onnx_to_tensorrt(self, onnx_file):
        # import pdb
        # pdb.set_trace()

        TRT_LOGGER = trt.Logger()
        EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        if os.path.exists(self.cfg.engine_file_path):
            # If a serialized engine exists, use it instead of building an engine.
            print("File already exists, Reading engine from file {}".format(self.cfg.engine_file_path))
            with open(self.cfg.engine_file_path, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime:
                return runtime.deserialize_cuda_engine(f.read())
        else:
            with trt.Builder(TRT_LOGGER) as builder, \
                builder.create_network(EXPLICIT_BATCH) as network, \
                builder.create_builder_config() as config, \
                trt.OnnxParser(network, TRT_LOGGER) as parser, \
                trt.Runtime(TRT_LOGGER) as runtime:
                # config.max_workspace_size = 1 << 32 # 4GB
                # builder.max_batch_size = 1
                config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 4096*(1 << 20)) # 4096M , syntax after TRT8.4
                
                # if trt_engine_datatype == trt.DataType.HALF:
                # config.set_flag(trt.BuilderFlag.FP16)
                if not os.path.exists(onnx_file):
                    print('ONNX file {} not found.'.format(onnx_file))
                    exit(0)
                print('Loading ONNX file from path {} ...'.format(onnx_file))
                with open(onnx_file, 'rb') as model:
                    print('Beginning ONNX file parsing')
                    if not parser.parse(model.read()):
                        print('ERROR: Failed to parse the onnx file.')
                        for e in range(parser.num_errors):
                            print(parser.get_error(e))
                        return None
                print("Completed parsing ONNX file")
                network.get_input(0).shape = [1, 3, 1152, 1152]
                # profile = builder.create_optimization_profile()
                # # Dynamic input setting
                # profile.set_shape('input',(1,3,1152,1152),(1,3,1152,1152),(1,3,1152,1152))
                # config.add_optimization_profile(profile)
                # 序列化模型
                plan = builder.build_serialized_network(network, config)
                # 反序列化
                engine = runtime.deserialize_cuda_engine(plan)
                # engine = builder.build_engine(network, config) # DeprecationWarning: Use build_serialized_network instead.
                print("Completed creating Engine")
                with open(self.cfg.engine_file_path, 'wb') as f:
                    f.write(plan)
                    # f.write(engine.serialize())
                    print('save trt success ...')
                return engine

**Comment by zerollzeng** [comment]
@pranavm-nvidia I think the usage here is correct, do you have any comments?

**Comment by pranavm-nvidia** [comment]
From the log, it looks like there's an issue when serializing the engine:
```
Completed parsing ONNX file
[09/29/2022-06:21:28] [TRT] [E] 1: [convolutionBuilder.cpp::writeGlob::1338] Error Code 1: Cask (canImplement)
[09/29/2022-06:21:28] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
```

Is the model valid? e.g. does it work with ONNX-Runtime?

**Comment by ywfwyht** [comment]
> From the log, it looks like there's an issue when serializing the engine:
> 
> ```
> Completed parsing ONNX file
> [09/29/2022-06:21:28] [TRT] [E] 1: [convolutionBuilder.cpp::writeGlob::1338] Error Code 1: Cask (canImplement)
> [09/29/2022-06:21:28] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
> ```
> 
> Is the model valid? e.g. does it work with ONNX-Runtime?

onnx model is valid, and validated to inference with ONNX-Runtime.

**Comment by pranavm-nvidia** [comment]
Seems like a bug then. Would you be able to share the model so we can debug?

**Comment by ywfwyht** [comment]
> Seems like a bug then. Would you be able to share the model so we can debug?

**https://github.com/ywfwyht/onnx_model/blob/main/0903_p28_t3_seg_simp.onnx**

**Comment by ywfwyht** [comment]
> Maybe related to the user's other issue: #2377. trtexec works fine for this model in TRT 8.4.

If without add the options `--best`, trtexec doesn't works fine for this model in TRT 8.4.  I suspect something is wrong with my environment。

**Comment by ywfwyht** [comment]
Hi, guys.
@pranavm-nvidia @zerollzeng 
`[convolutionBuilder.cpp::writeGlob::1338] Error Code 1: Cask (canImplement)`
What is the problem with this bug. How to solve it。

**Comment by pranavm-nvidia** [comment]
I haven't been able to reproduce this locally. Maybe an environment/setup issue?

**Comment by ywfwyht** [comment]
Maybe it's the environment，I suspect it is a cuda version issue

**Comment by ywfwyht** [comment]
> convolutionBuilder
@zerollzeng @pranavm-nvidia 
I'm distressed,  tried many ways, still have this problem. Including using your official mirror, and reconfiguring the environment

**Comment by ywfwyht** [comment]
> Does it make any difference if you omit the `--workspace` argument?

The same error. what's your driver version?

**Comment by pranavm-nvidia** [comment]
I'm using 510.85.02

**Comment by pebush** [comment]
I'm also encountering the same issue in python.
It works w/o calibration:
`       #config.max_workspace_size = common.GiB(1)
        #config.max_workspace_size = 1 << 28 # 256MiB
`
If i use calibration avobe (activate quantization process), I have the same error discussed above.

The calibration process in c++ works in my enviroment...

**Comment by ywfwyht** [comment]
> 
Yes, I fixed it. I modified the model。

**Comment by ywfwyht** [comment]
> Having the same error. @ywfwyht , did you fix it?

Yes, I fixed it. I modified the model。

**Comment by wanzhixiao** [comment]
If you use a tokenizer, the max_length param shoud set to a max_length value

```python
max_length = 512
encoded_input = tokenizer.batch_encode_plus(sentences,
                                        max_length=max_length,
                                        padding='max_length',
                                        truncation=True)
```

**Comment by yaobaishen** [comment]
> > Having the same error. @ywfwyht , did you fix it?
> 
> Yes, I fixed it. I modified the model。

@ywfwyht could you share some insights what's the modification you did, so that the issue is fixed? thanks a lot
