### ISSUE TITLE
How to supply dequantize layer result to addConvolutionNd for weights?

### ISSUE THREAD

**Issue by praveen-aurora** [NVIDIA/TensorRT#2366]
## Description

addConvolutionNd only seems to accept an object of type "Weights" for the convolution weights. However in the diagram below, it seems to suggest placing Q-DQ nodes after the weights, which would mean that addConvolutionNd would need to accept an ITensor for the weights, which doesn't seem possible. How can one realize the Q-DQ pattern for weights in the diagram?

Diagram is from: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#qdq-placement-recs

![](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/graphics/q-dq-placement1.PNG)

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by thancaocuong** [comment]
same issue as @praveen-aurora

**Comment by ttyio** [comment]
hi @praveen-aurora  @thancaocuong , could you take a try with `setInput` in `ILayer`? thanks!

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_convolution_layer.html#aa1eb8deb3192489196cb7884a4177de4

**Comment by thancaocuong** [comment]
@ttyio thanks. Just found that API. Then the problem has been solved. Thanks so much

**Comment by ttyio** [comment]
thank you @thancaocuong , closing

**Comment by thancaocuong** [comment]
@praveen-aurora [here](https://github.com/NVIDIA/TensorRT/issues/2428#issuecomment-1296498905) is my solution for conv2d, please take a look if this can help you

**Comment by praveen-aurora** [comment]
Hi - I ended up doing something similar - thanks.
