### ISSUE TITLE
about builtin_op_imports.cpp 

### ISSUE THREAD

**Issue by hitbuyi** [NVIDIA/TensorRT#2369]
I found some ops are imported in this file, but some ops not, if I want to implement a custom op, is it necessary to add contents of the op in this file?

in official document  8.1.x on custom plugin issue, it doesn't mention adding custom plugin content in this file
so what's exact purpose of builtin_op_imports.cpp? from its name of meaning,it is for importing builtin ops, when it is necessary for ops, and  when it is not necessary for ops
any help will appreciated

**Comment by zerollzeng** [comment]
1. most of onnx ops is imported to TRT layers, like Conv
2. some onnx ops is imported as TRT plugin, like https://github.com/onnx/onnx-tensorrt/blob/12eb0d69f124ad08dead32d100944bcb3b157c24/builtin_op_importers.cpp#L2128
3. Any ops that are not supported will attempt to import as plugins. https://github.com/onnx/onnx-tensorrt/blob/12eb0d69f124ad08dead32d100944bcb3b157c24/builtin_op_importers.cpp#L4886
4. some custom ops are imported as TRT native layer, like https://github.com/onnx/onnx-tensorrt/blob/12eb0d69f124ad08dead32d100944bcb3b157c24/builtin_op_importers.cpp#L5128
