### ISSUE TITLE
Tensor installation make "error: no match for ‘operator=’"

### ISSUE THREAD

**Issue by tymiao1220** [NVIDIA/TensorRT#237]
## Environment

**TensorRT Version**: 6.0.1.5
**GPU Type**: Tesla K80
**Nvidia Driver Version**: 418.39
**CUDA Version**: 10.1
**CUDNN Version**: 7.6.5
**Operating System + Version**: Centos7 
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 1.14.0
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

Hi, I encounter an installation issue when I am trying to `make`

> ``[ 96%] Building CXX object samples/opensource/trtexec/CMakeFiles/trtexec.dir/__/__/common/sampleInference.cpp.o
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp: In function ‘void sample::{anonymous}::inferenceLoop(std::vector<sample::{anonymous}::IterStruct>&, sample::{anonymous}::SynchStruct&, int, int, float, float, std::vector<sample::InferenceTime>&)’:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:150:25: error: no match for ‘operator=’ (operand types are ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ and ‘std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}’)
             timingStart = std::chrono::high_resolution_clock::now();
                         ^
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:150:25: note: candidates are:
In file included from /usr/include/c++/4.8.2/bits/stl_vector.h:63:0,
                 from /usr/include/c++/4.8.2/vector:64,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/initializer_list:47:11: note: std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >& std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >::operator=(const std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&)
     class initializer_list
           ^
/usr/include/c++/4.8.2/initializer_list:47:11: note:   no known conversion for argument 1 from ‘std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}’ to ‘const std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&’
/usr/include/c++/4.8.2/initializer_list:47:11: note: std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >& std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >::operator=(std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&&)
/usr/include/c++/4.8.2/initializer_list:47:11: note:   no known conversion for argument 1 from ‘std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}’ to ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&&’
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:156:23: error: no match for ‘operator=’ (operand types are ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ and ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >’)
             timingEnd = iterEnd;
                       ^
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:156:23: note: candidates are:
In file included from /usr/include/c++/4.8.2/bits/stl_vector.h:63:0,
                 from /usr/include/c++/4.8.2/vector:64,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/initializer_list:47:11: note: std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >& std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >::operator=(const std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&)
     class initializer_list
           ^
/usr/include/c++/4.8.2/initializer_list:47:11: note:   no known conversion for argument 1 from ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >’ to ‘const std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&’
/usr/include/c++/4.8.2/initializer_list:47:11: note: std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >& std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >::operator=(std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&&)
/usr/include/c++/4.8.2/initializer_list:47:11: note:   no known conversion for argument 1 from ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >’ to ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >&&’
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:77: error: no match for ‘operator-’ (operand types are ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ and ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’)
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                             ^
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:77: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:65:0,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/bits/stl_bvector.h:208:3: note: std::ptrdiff_t std::operator-(const std::_Bit_iterator_base&, const std::_Bit_iterator_base&)
   operator-(const _Bit_iterator_base& __x, const _Bit_iterator_base& __y)
   ^
/usr/include/c++/4.8.2/bits/stl_bvector.h:208:3: note:   no known conversion for argument 1 from ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ to ‘const std::_Bit_iterator_base&’
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:67:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/bits/stl_iterator.h:1111:5: note: template<class _Iterator> decltype ((__x.base() - __y.base())) std::operator-(const std::move_iterator<_Iterator>&, const std::move_iterator<_Iterator>&)
     operator-(const move_iterator<_Iterator>& __x,
     ^
/usr/include/c++/4.8.2/bits/stl_iterator.h:1111:5: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::move_iterator<_Iterator>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:67:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/bits/stl_iterator.h:1104:5: note: template<class _IteratorL, class _IteratorR> decltype ((__x.base() - __y.base())) std::operator-(const std::move_iterator<_Iterator>&, const std::move_iterator<_IteratorR>&)
     operator-(const move_iterator<_IteratorL>& __x,
     ^
/usr/include/c++/4.8.2/bits/stl_iterator.h:1104:5: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::move_iterator<_Iterator>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:67:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/bits/stl_iterator.h:379:5: note: template<class _IteratorL, class _IteratorR> decltype ((__y.base() - __x.base())) std::operator-(const std::reverse_iterator<_Iterator>&, const std::reverse_iterator<_IteratorR>&)
     operator-(const reverse_iterator<_IteratorL>& __x,
     ^
/usr/include/c++/4.8.2/bits/stl_iterator.h:379:5: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::reverse_iterator<_Iterator>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:67:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/bits/stl_iterator.h:327:5: note: template<class _Iterator> typename std::reverse_iterator<_Iterator>::difference_type std::operator-(const std::reverse_iterator<_Iterator>&, const std::reverse_iterator<_Iterator>&)
     operator-(const reverse_iterator<_Iterator>& __x,
     ^
/usr/include/c++/4.8.2/bits/stl_iterator.h:327:5: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::reverse_iterator<_Iterator>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:18:0:
/usr/include/c++/4.8.2/chrono:649:7: note: template<class _Clock, class _Dur1, class _Dur2> constexpr typename std::common_type<_Duration1, _Duration2>::type std::chrono::operator-(const std::chrono::time_point<_Clock, _Duration1>&, const std::chrono::time_point<_Clock, _Duration2>&)
       operator-(const time_point<_Clock, _Dur1>& __lhs,
       ^
/usr/include/c++/4.8.2/chrono:649:7: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::chrono::time_point<_Clock, _Duration1>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:18:0:
/usr/include/c++/4.8.2/chrono:638:7: note: template<class _Clock, class _Dur1, class _Rep2, class _Period2> constexpr std::chrono::time_point<_Clock, typename std::common_type<_Dur1, std::chrono::duration<_Rep2, _Period2> >::type> std::chrono::operator-(const std::chrono::time_point<_Clock, _Duration1>&, const std::chrono::duration<_Rep2, _Period2>&)
       operator-(const time_point<_Clock, _Dur1>& __lhs,
       ^
/usr/include/c++/4.8.2/chrono:638:7: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::chrono::time_point<_Clock, _Duration1>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:18:0:
/usr/include/c++/4.8.2/chrono:392:7: note: template<class _Rep1, class _Period1, class _Rep2, class _Period2> constexpr typename std::common_type<std::chrono::duration<_Rep1, _Period1>, std::chrono::duration<_Rep2, _Period2> >::type std::chrono::operator-(const std::chrono::duration<_Rep1, _Period1>&, const std::chrono::duration<_Rep2, _Period2>&)
       operator-(const duration<_Rep1, _Period1>& __lhs,
       ^
/usr/include/c++/4.8.2/chrono:392:7: note:   template argument deduction/substitution failed:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:167:79: note:   ‘std::initializer_list<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ is not derived from ‘const std::chrono::duration<_Rep1, _Period1>’
     float totalLatency = std::chrono::duration<float, std::milli>(timingEnd - timingStart).count();
                                                                               ^
In file included from /usr/include/c++/4.8.2/vector:62:0,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:17:
/usr/include/c++/4.8.2/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = sample::BindingBuffers; _Args = {const sample::BindingBuffers&}]’:
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const sample::BindingBuffers*, std::vector<sample::BindingBuffers> >; _ForwardIterator = sample::BindingBuffers*; bool _TrivialValueTypes = false]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:117:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const sample::BindingBuffers*, std::vector<sample::BindingBuffers> >; _ForwardIterator = sample::BindingBuffers*]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:258:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const sample::BindingBuffers*, std::vector<sample::BindingBuffers> >; _ForwardIterator = sample::BindingBuffers*; _Tp = sample::BindingBuffers]’
/usr/include/c++/4.8.2/bits/stl_vector.h:316:32:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = sample::BindingBuffers; _Alloc = std::allocator<sample::BindingBuffers>]’
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleUtils.h:83:7:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:117:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = sample::Bindings*; _ForwardIterator = sample::Bindings*]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:258:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = sample::Bindings*; _ForwardIterator = sample::Bindings*; _Tp = sample::Bindings]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:281:69:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = sample::Bindings*; _ForwardIterator = sample::Bindings*; _Allocator = std::allocator<sample::Bindings>]’
/usr/include/c++/4.8.2/bits/vector.tcc:556:42:   required from ‘void std::vector<_Tp, _Alloc>::_M_default_append(std::vector<_Tp, _Alloc>::size_type) [with _Tp = sample::Bindings; _Alloc = std::allocator<sample::Bindings>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/4.8.2/bits/stl_vector.h:667:41:   required from ‘void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = sample::Bindings; _Alloc = std::allocator<sample::Bindings>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:46:43:   required from here
/usr/include/c++/4.8.2/bits/stl_construct.h:75:7: error: use of deleted function ‘sample::BindingBuffers::BindingBuffers(const sample::BindingBuffers&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:28:0:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleUtils.h:61:7: note: ‘sample::BindingBuffers::BindingBuffers(const sample::BindingBuffers&)’ is implicitly deleted because the default definition would be ill-formed:
 class BindingBuffers
       ^
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleUtils.h:61:7: error: use of deleted function ‘sample::TrtCudaBuffer<A, D>::TrtCudaBuffer(const sample::TrtCudaBuffer<A, D>&) [with A = sample::HostAllocator; D = sample::HostDeallocator]’
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleUtils.h:28:0,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:28:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleDevice.h:156:5: error: declared here
     TrtCudaBuffer(const TrtCudaBuffer&) = delete;
     ^
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:28:0:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleUtils.h:61:7: error: use of deleted function ‘sample::TrtCudaBuffer<A, D>::TrtCudaBuffer(const sample::TrtCudaBuffer<A, D>&) [with A = sample::DeviceAllocator; D = sample::DeviceDeallocator]’
 class BindingBuffers
       ^
In file included from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleUtils.h:28:0,
                 from /home/miaot2/libraries/TensorRTOSS/samples/common/sampleInference.cpp:28:
/home/miaot2/libraries/TensorRTOSS/samples/common/sampleDevice.h:156:5: error: declared here
     TrtCudaBuffer(const TrtCudaBuffer&) = delete;
     ^
make[2]: *** [samples/opensource/trtexec/CMakeFiles/trtexec.dir/__/__/common/sampleInference.cpp.o] Error 1
make[1]: *** [samples/opensource/trtexec/CMakeFiles/trtexec.dir/all] Error 2
make: *** [all] Error 2

Another question I have is, I have successfully by switching CUDA10.0 to convert Mask_RCNN model to .uff, and switch by to CUDA10.1 to `make and make install` although I got error above but I still can run `./out/sample_uff_maskRCNN` successfully. After that I am trying to builld engine using python instead I got

> [TensorRT] ERROR: UffParser: Validator error: mrcnn_detection: Unsupported operation _DetectionLayer_TRT

so I check registry

> RnRes2Br1Br2c_TRT
> CgPersistentLSTMPlugin_TRT
> RnRes2Br2bBr2c_TRT
> SingleStepLSTMPlugin
> FancyActivation
> ResizeNearest
> Split
> InstanceNormalization
> GridAnchor_TRT
> NMS_TRT
> Reorg_TRT
> Region_TRT
> Clip_TRT
> LReLU_TRT
> PriorBox_TRT
> Normalize_TRT
> RPROI_TRT
> BatchedNMS_TRT
> FlattenConcat_TRT

detectionLayer_TRT is not registered successfully while some of plugins(e.g. ResizeNearest)
register well. Is this all because I did not complete Tensor components installation? if that is the case why `./out/sample_uff_maskRCNN` is runable? 

Thanks for help.

**Comment by rmccorm4** [comment]
Hey @tymiao1220,

Haven't seen this before, but thinking it might be just a version issue with g++/make/cmake. What're your versions of `make` and `cmake`?

**Comment by tymiao1220** [comment]
Thank you for your response.
gcc: 4.8.5
cmake: 3.15.2
make: I tried 4.2/3.82 all get same error.

**Comment by tymiao1220** [comment]
And same error happens using docker centos7 version.

**Comment by rmccorm4** [comment]
Are you able to build successfully in one of the NGC containers?

https://github.com/NVIDIA/TensorRT/issues/190#issuecomment-550037253

**Comment by tymiao1220** [comment]
I think it will work because I have tried ubuntu18 docker, it works well but get no luck on Centos. 
We are using Centos and there is a change that docker is not allowed to be installed on the server which is the reason I want to figure out how to fix this issue.

And when I successfully install everything using ubuntu docker and play with Mask_RCNN I got one more question related to [1851](https://github.com/matterport/Mask_RCNN/issues/1851). I will open a new discussion if needed.

**Comment by XSeanLiu** [comment]
GCC 5.0+ can solve it

**Comment by nlqq** [comment]
> GCC 5.0+ can solve it

and add a qiuck tip to install gcc 5.1
vim /etc/yum.repos.d/Fedora-Core23.repo
```
[warning:fedora]
name=fedora
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=fedora-23&arch=$basearch
enabled=1
gpgcheck=0
```
yum install gcc

That is all.

**Comment by meloncolie** [comment]
same problem!
gcc 4.8.5 should work, since the official released SDK can be run on CentOS7

**Comment by samhodge** [comment]
I encountered this today using official instructions.
