### ISSUE TITLE
long time between `executionContext.enqueue()`

### ISSUE THREAD

**Issue by frankxyy** [NVIDIA/TensorRT#2370]
I profile a tensorrt plan using nsight sys. The result shows that the time between consecutive calls of `executionContext.enqueue()` is highly higher than the execution time for `executionContext.enqueue()`.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/6971044/193779478-79422972-1b15-4e31-b57c-cc9513092c9c.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/6971044/193780079-2c753ee2-6572-4cb3-b532-58e435d8991c.png">

The profile command is: nsys profile --stats=true --force-overwrite true -o profile_noplugin trtexec --loadEngine=encoder_noplugin.plan --warmUp=0 --duration=0 --iterations=50  --shapes=x:16x3x32x600

**Comment by nvpohanh** [comment]
You are looking at the CPU activities. Please expand the "CUDA HW" rows to find out what GPU is doing while CPU is waiting.

**Comment by frankxyy** [comment]
Thank you, i think i understand it

**Comment by brilliant-soilder** [comment]
> You are looking at the CPU activities. Please expand the "CUDA HW" rows to find out what GPU is doing while CPU is waiting.
similiar questions at "multiple streams parallel inference engine, but failed with serial inference #2353". Could you help with some suggestions?

**Comment by nvpohanh** [comment]
closing this
