### ISSUE TITLE
Unexpected output shape for bertQKVToContext plugin with var_seqlen

### ISSUE THREAD

**Issue by frankxyy** [NVIDIA/TensorRT#2375]
![image](https://user-images.githubusercontent.com/6971044/194577791-c12bb95f-cbfd-4447-b16d-8baea613eb95.png)

As the picture showed，the input shape of the custom qkvToContext plugin is `(-1, -1, 1536, 1, 1)`, and the output shape is still `(-1, -1, 1536, 1, 1)`. However, as i speculate from the doc, the output shape is expected to be `(-1, -1, 512, 1, 1)`. Why does this happen? What is the exact input layout to use when using variable sequence length?

**Comment by frankxyy** [comment]
Plus：When i donnot use varseq in v2 plugin，the running also meets an error:
![image](https://user-images.githubusercontent.com/6971044/194594083-315d14ae-ace6-493b-b849-038c62dd6748.png)

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
Hi @frankxyy , for the output dimension, yes the input is `3xhiddensize` and output `hiddensize`, https://github.com/NVIDIA/TensorRT/blob/main/plugin/bertQKVToContextPlugin/qkvToContextPlugin.cpp#L690, not sure if this is log issue, did you see shape mismatch in the final network output?

for the 2nd question, the initial plan is to support both varseq and fix seq in v2, but we are in short of resource, so we just throw out unimplemented error. If you check the demoBERT, v1 is used for fixed seq.

**Comment by frankxyy** [comment]
@ttyio hi, for the 1st question, i think it may not be the logging issue. From the code 
![image](https://user-images.githubusercontent.com/6971044/197582523-a1dc09be-8647-409f-ade9-6b95e46a5f70.png)
It can say that this var seqlen plugin have more than 2 inputs which the number of it is not consistent with number of input 2 in the readme file.

**Comment by frankxyy** [comment]
![image](https://user-images.githubusercontent.com/6971044/197586630-079950a0-083a-4020-8738-a0c6373e9e78.png)
Hi @ttyio ，For 1st question，it seems that the input number for var seqlen plugin is more than 2, which is inconsistent with the doc.

**Comment by frankxyy** [comment]
![image](https://user-images.githubusercontent.com/6971044/197588013-2a580da8-1d22-4080-bd73-236f87d99821.png)
From the supportsFormatCombination func，it seems that for varseq, there exists two additional inputs.

**Comment by ttyio** [comment]
@frankxyy , the doc is for fixed len mha (v1), we have not update the variable seq mha (v2) and interleave int8 mha (v3) doc yet.

yes there are more input for it, the input batch is stitch into single batch, so we the 2nd input `cu_seqlens` to break it info pieces. and the 3rd input `max_seq` is a hint to the mha plugin on which kernel should we choose.

**Comment by ttyio** [comment]
closing due to no response for more than 3 weeks, please reopen if you still have question, thanks!
