### ISSUE TITLE
Error: 'nvidia/bert_tf_ckpt_large_qa_squad2_amp_128:19.03.1' could not be found.

### ISSUE THREAD

**Issue by frankxyy** [NVIDIA/TensorRT#2376]
I run the bert demo. However，when executing the `scripts/download_model.sh`，the error 'nvidia/bert_tf_ckpt_large_qa_squad2_amp_128:19.03.1' could not be found. occured. It seems that this model no long exists in the ngc？

**Comment by directmemory** [comment]
It looks like download service was closed.
Now I get same error when implementing "scripts/download_model.sh" or "scripts/download_model.sh base", whereas, a few days ago, I can download them successfully..

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by zerollzeng** [comment]
@frankxyy Can you download it now?

**Comment by frankxyy** [comment]
@zerollzeng I can download it now. Thanks a lot!
