### ISSUE TITLE
QAT example

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2381]
Hi, I'm looking at the example which I believe is supposed to explain QAT. but I can't seem to find QAT related code snippet? Can anyone explain which part in this file is QAT related?

https://github.com/NVIDIA/TensorRT/blob/master/tools/pytorch-quantization/examples/finetune_quant_resnet50.ipynb

**Comment by munhou** [comment]
``` python
from pytorch_quantization import quant_modules
quant_modules.initialize()
```
Some nn layers of pytorch are replaced and qdq is added，You can train as usual

**Comment by shuyuan-wang** [comment]
> ```python
> from pytorch_quantization import quant_modules
> quant_modules.initialize()
> ```
> 
> Some nn layers of pytorch are replaced and qdq is added，You can train as usual

I can also see these two lines of codes in calibrate_quant_resnet50.ipynb, which I believe explains post training quantization? So, exactly what's the difference between the two examples other than the extra one epoch training?

**Comment by munhou** [comment]
As I understand it quant_modules.initialize() replaces torch nns in the way of monkey patches to add qdq nodes, which participate in the training of the network to make it more suitable for quantization。

I'm not a professional and may need additional corrections from other people
