### ISSUE TITLE
About "Q/DQ Layer-Placement Recommendations" in the manual

### ISSUE THREAD

**Issue by deephog** [NVIDIA/TensorRT#2383]
In the manual, I found two recommendations that are confusing to me. 

1. "Quantize all inputs of weighted-operations"
2. "By default, don’t quantize the outputs of weighted-operations"

By definition, I can understand every word these two recommendations are saying. But how do you actually carry out explicitly following these two recommendations when you have cascaded weighted-operations? Where should you put the Q/DQ layers if you have multiple cascaded Conv-BN-Relu layers? Or does it only mean you should leave the last output of the sequence un-quantized? 

And is there any kind of "stopper" layer that I can put in the model to prevent the automatic "Q/DQ propagation process" to propagate to the layers that I definitely don't want them to be quantized? 

Thanks!

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
Hi @deephog , this best practice come from the automatic rules, for automatic patch, the Q/DQ insertion is ruled by this. For monkey patch code, you can place Q/DQ anywhere, e.g, if you use reformat-free IO, and the network output is mark as INT8, it is better to insert Q/DQ at the end of the network, and use graph surgeon to remove the last DQ in the network.

For the stop layer question, we have:
DQ -> Conv :  INT8-IN-FP32-OUT
DQ -> Conv -> Q: INT8-IN-INT8-OUT
And we will commute Q/DQ with other nodes when TRT supports, more details in check https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-qat-networks, hope this helps. Thanks!

**Comment by deephog** [comment]
> Hi @deephog , this best practice come from the automatic rules, for automatic patch, the Q/DQ insertion is ruled by this. For monkey patch code, you can place Q/DQ anywhere, e.g, if you use reformat-free IO, and the network output is mark as INT8, it is better to insert Q/DQ at the end of the network, and use graph surgeon to remove the last DQ in the network.
> 
> For the stop layer question, we have: DQ -> Conv : INT8-IN-FP32-OUT DQ -> Conv -> Q: INT8-IN-INT8-OUT And we will commute Q/DQ with other nodes when TRT supports, more details in check https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-qat-networks, hope this helps. Thanks!

Thank you for the reply! For the stopping layer question, what you are suggesting is that if I manually place a DQ before a Conv without placing a following Q, the automatic commute won't affect the output of the Conv layer, so it will stay fp32 no matter what?

**Comment by ttyio** [comment]
@deephog sorry for the delay response.
yes you are right, and `Q` can commute with node like activation, pooling, slice... if none of the `Q` after this Conv node, then the output stay fp32.

**Comment by deephog** [comment]
> @deephog sorry for the delay response. yes you are right, and `Q` can commute with node like activation, pooling, slice... if none of the `Q` after this Conv node, then the output stay fp32.

Thank you for the answer!

**Comment by ttyio** [comment]
Thank you and close the issue.
