### ISSUE TITLE
spconv modules

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2384]
I'm trying to quantize the voxelnet which according to mmdetection code, requires spconv modules. When I try to quantize the model with quant_modules.initialize(), the spconv module doesn't change at all, it remains SubMConv3d. What can I do with this issue?

**Comment by munhou** [comment]
```
_DEFAULT_QUANT_MAP = [_quant_entry(torch.nn, "Conv1d", quant_nn.QuantConv1d),
                      _quant_entry(torch.nn, "Conv2d", quant_nn.QuantConv2d),
                      _quant_entry(torch.nn, "Conv3d", quant_nn.QuantConv3d),
                      _quant_entry(torch.nn, "ConvTranspose1d", quant_nn.QuantConvTranspose1d),
                      _quant_entry(torch.nn, "ConvTranspose2d", quant_nn.QuantConvTranspose2d),
                      _quant_entry(torch.nn, "ConvTranspose3d", quant_nn.QuantConvTranspose3d),
                      _quant_entry(torch.nn, "Linear", quant_nn.QuantLinear),
                      _quant_entry(torch.nn, "LSTM", quant_nn.QuantLSTM),
                      _quant_entry(torch.nn, "LSTMCell", quant_nn.QuantLSTMCell),
                      _quant_entry(torch.nn, "AvgPool1d", quant_nn.QuantAvgPool1d),
                      _quant_entry(torch.nn, "AvgPool2d", quant_nn.QuantAvgPool2d),
                      _quant_entry(torch.nn, "AvgPool3d", quant_nn.QuantAvgPool3d),
                      _quant_entry(torch.nn, "AdaptiveAvgPool1d", quant_nn.QuantAdaptiveAvgPool1d),
                      _quant_entry(torch.nn, "AdaptiveAvgPool2d", quant_nn.QuantAdaptiveAvgPool2d),
                      _quant_entry(torch.nn, "AdaptiveAvgPool3d", quant_nn.QuantAdaptiveAvgPool3d),]
```
These should be layers that will be replaced when quant_modules.initialize() is used You may need to add the qdq node manually ，You can look at the code of quant_modules.initialize()
A tip from me that is not particularly professional

**Comment by zerollzeng** [comment]
I'm not sure whether we support spconv for QAT, it's really special. @ttyio may have some insight here.

**Comment by ttyio** [comment]
@shuyuan-wang , all the supported layers is already listed in https://github.com/NVIDIA/TensorRT/issues/2384#issuecomment-1274477304, for other layers, you need monkey patch your code, by explicitly insert the Q/DQ node. 

You could follow https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py#L139 this as example, thanks!
