### ISSUE TITLE
IExecutionContext::enqueue An error occurred ：terminate called without an active exception

### ISSUE THREAD

**Issue by qilinhu** [NVIDIA/TensorRT#2386]
## Description

When I use the queue interface to reason, the program can run normally for a period of time, but after a while, it will crash. The error is terminate called without an active exception.I don't know why this problem occurs. I hope someone can help me solve this problem. Thanks！

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: GTX 1080Ti
**NVIDIA Driver Version**: 470.1411.03
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
Can you provide a reproduce?

**Comment by daohu527** [comment]
update 

I print out the kernel grid and block, There are 2 doubts
1. grid size is 0, I know grid is a dim3, but In my case the grid is 1-d array and is 0. Will this cause this problem, I blocked it but the problem is still not solved
2. I check my card is **compute capability 6.1**, and the max grid * block is 288,512, will this be the error?

**Comment by zerollzeng** [comment]
I can't give any advice without a reproduce on my own, this is kind of weird.

**Comment by zerollzeng** [comment]
7.2 is pretty old, can you try the latest 8.4? and also try to reproduce with trtexec

**Comment by daohu527** [comment]
I find the error, **it cause by grid size is 0**. I only blocked one place before

Although I know to reproduce the problem, I clearly stated my problem point, thank you for your help

**Comment by daohu527** [comment]
yes it has been resolved
