### ISSUE TITLE
QDQ recommendation

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2387]
I'm looking at the Q/DQ recommendation ppt content like "don't quantize operator outputs", and am wondering are these recommendations for manual adding of fake quantization or do I need to twist things when I use pytorch_quantization. I though pytorch_quantization can automatically do fake quantization and I don't need to do anything?

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
Hi @shuyuan-wang , which ppt are you refer to?

we have QAT toolkit document in https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html

and TRT implementation detail in https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-qat-networks

Thanks!

**Comment by shuyuan-wang** [comment]
I'm actually referring to the pdf file on this page:
https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s31653/
on page 48
