### ISSUE TITLE
When will onnx ScatterElements with reduction=add be supported?

### ISSUE THREAD

**Issue by leimeng86** [NVIDIA/TensorRT#2396]
@jianye0428 , could you upgrade TRT to 8.2+ to get the native `ScatterElement` support? thanks!

_Originally posted by @ttyio in https://github.com/NVIDIA/TensorRT/issues/1805#issuecomment-1067746564_

**Comment by leimeng86** [comment]
Hi there,

I need onnx `ScatterElemts` with reduction=add supported in TensorRT. The onnx op [ScatterElemensts](https://xadupre.github.io/draft/onnx/onnx_doc_folder/onnx__ScatterElements.html#id6) has several reduction options, e.g. add and multiply. However, I found that [`nvinfer1::IScatterLayer`](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_scatter_layer.html) only supports reduction="none", i.e. _indices should not have duplicate entries_, even with [`ScatterMode::kELEMENT`](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#adc93e7837f6cdf216aeff85f7c7528dba62bac088ca0993341cd1ad731da36aa2).

Regards

**Comment by ttyio** [comment]
@leimeng86 , this `reduction` field is new added in opset 16, it is not supported when we added the `ScatterElements`. 

Created internal feature request 3851649 to track this, thanks!

**Comment by stupiding** [comment]
Hi @ttyio,  is there any progress on the reduction=add?

**Comment by borisfom** [comment]
Hi @ttyio - this feature (and, ideally, more reductions that are now available in torch.scatter_reduce_(), like 'mean') are needed for BioNemo. Any plans to implement those soon ?

**Comment by ttyio** [comment]
Sorry I have just checked it's in backlog currently, and the management team will assign them in order of priority. Thanks!

**Comment by ttyio** [comment]
@borisfom could you ping management to prioritize this in the internal feature request page. Let's track it internally, and I will close this, thanks!
