### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator FakeTensorQuantFunction

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2398]
I'm experience the error below when exporting calibrated pytorch model, not sure what happened:
```
torch.onnx.export(model.reader, (example["voxels"],example["num_voxels"],example["coordinates"]),"onnx_model/pfe.onnx",opset_version=13, enable_onnx_checker=False)
```
![截屏2022-10-18 13 03 45](https://user-images.githubusercontent.com/104115572/196339835-6d35ae11-d431-450e-b8b7-549530c656e5.png)

**Comment by happygds** [comment]
@shuyuan-wang Hi, how do you solve this problem?

**Comment by Francis235** [comment]
@happygds Hi, I also encountered this problem, did you solve it?

**Comment by happygds** [comment]
@Francis235 , I use pytorch's native fake quantization instead. Just add this line `quant_nn.TensorQuantizer.use_fb_fake_quant=True` to your code.
