### ISSUE TITLE
The engine outputs become zero after Conv2d

### ISSUE THREAD

**Issue by HowLii** [NVIDIA/TensorRT#2401]
## Description

Hi, Team. I have trouble in converting a simple model to engine. The onnx model runs normally while the engine output values are all zero. So I compare the two using the polygraphy.As a result I found the output turns zero after the Conv2D layer. 

```
[I] onnxrt-runner-N0-10/19/22-09:28:23  | Completed 1 iteration(s) in 1692 ms | Average inference time: 1692 ms.
[I] Accuracy Comparison | trt-runner-N0-10/19/22-09:28:23 vs. onnxrt-runner-N0-10/19/22-09:28:23
[I]     Comparing Output: 'input.3' (dtype=float32, shape=(1, 128, 200, 200)) with 'input.3' (dtype=float32, shape=(1, 128, 200, 200)) | Tolerance: [abs=0.001, rel=0.001] | Checking elemwise error
[I]         trt-runner-N0-10/19/22-09:28:23: input.3 | Stats: mean=0, std-dev=0, var=0, median=0, min=0 at (0, 0, 0, 0), max=0 at (0, 0, 0, 0), avg-magnitude=0
[I]             ---- Histogram ----
                Bin Range          |  Num Elems | Visualization
                (-0.967 , -0.773 ) |          0 | 
                (-0.773 , -0.579 ) |          0 | 
                (-0.579 , -0.385 ) |          0 | 
                (-0.385 , -0.191 ) |          0 | 
                (-0.191 , 0.00245) |    5120000 | ########################################
                (0.00245, 0.196  ) |          0 | 
                (0.196  , 0.39   ) |          0 | 
                (0.39   , 0.584  ) |          0 | 
                (0.584  , 0.778  ) |          0 | 
                (0.778  , 0.972  ) |          0 | 
[I]         onnxrt-runner-N0-10/19/22-09:28:23: input.3 | Stats: mean=0.012237, std-dev=0.18888, var=0.035676, median=0.0096648, min=-0.96694 at (0, 19, 83, 157), max=0.97184 at (0, 48, 132, 126), avg-magnitude=0.15045
[I]             ---- Histogram ----
                Bin Range          |  Num Elems | Visualization
                (-0.967 , -0.773 ) |         37 | 
                (-0.773 , -0.579 ) |       3484 | 
                (-0.579 , -0.385 ) |      78492 | #
                (-0.385 , -0.191 ) |     627482 | #############
                (-0.191 , 0.00245) |    1771906 | #######################################
                (0.00245, 0.196  ) |    1802390 | ########################################
                (0.196  , 0.39   ) |     705858 | ###############
                (0.39   , 0.584  ) |     121068 | ##
                (0.584  , 0.778  ) |       9081 | 
                (0.778  , 0.972  ) |        202 | 
[I]         Error Metrics: input.3
[I]             Minimum Required Tolerance: elemwise error | [abs=0.97184] OR [rel=1]
[I]             Absolute Difference | Stats: mean=0.15045, std-dev=0.11485, var=0.013191, median=0.12632, min=6.7055e-08 at (0, 72, 92, 37), max=0.97184 at (0, 48, 132, 126), avg-magnitude=0.15045
[E]         FAILED | Difference exceeds tolerance (rel=0.001, abs=0.001)
[!] FAILED | Command: /home/hli/anaconda3/envs/inr/bin/polygraphy run SR.onnx --trt --onnxrt --trt-outputs input.3 --onnx-outputs input.3 --atol 1e-3 --rtol 1e-3 --fail-fast
```

the input.3 is the output of the conv2d layer. And the input of the layer has no problem. I would like to know how to fix it. I have struggled for a few days. It will be very nice if any reple. Thank you very much!

![image](https://user-images.githubusercontent.com/58170781/196580804-1bc2135d-1f0b-4d68-8031-013e30a9844d.png)

## Environment

**TensorRT Version**: 8.4.3.1
**NVIDIA GPU**: NVIDIA GeForce RTX 3080 Ti
**NVIDIA Driver Version**: 510.85
**CUDA Version**: 11.3
**CUDNN Version**: 8.4.0
**Operating System**: linux
**Python Version (if applicable)**: 3.8.13
**PyTorch Version (if applicable)**: 1.12.1

## Relevant Files

my onnx file is available here: https://drive.google.com/file/d/1EkmxZBQs9y5tyU_VGEvSJHlK6HZzCawS/view?usp=sharing

**Comment by HowLii** [comment]
I found it doesn't  work even on the model that just contains a conv2d layer. So maybe it's a environment problem?

**Comment by zerollzeng** [comment]
Maybe, the result with official docker 22.09
```
[I] Accuracy Comparison | trt-runner-N0-10/20/22-11:48:04 vs. onnxrt-runner-N0-10/20/22-11:48:04
[I]     Comparing Output: 'input.3' (dtype=float32, shape=(1, 128, 200, 200)) with 'input.3' (dtype=float32, shape=(1, 128, 200, 200))
[I]     Tolerance: [abs=0.001, rel=0.001] | Checking elemwise error
[I]         trt-runner-N0-10/20/22-11:48:04: input.3 | Stats: mean=0.012237, std-dev=0.18888, var=0.035676, median=0.0096648, min=-0.96694 at (0, 19, 83, 157), max=0.97184 at (0, 48, 132, 126), avg-magnitude=0.15045
[I]         onnxrt-runner-N0-10/20/22-11:48:04: input.3 | Stats: mean=0.012237, std-dev=0.18888, var=0.035676, median=0.0096648, min=-0.96694 at (0, 19, 83, 157), max=0.97184 at (0, 48, 132, 126), avg-magnitude=0.15045
[I]         Error Metrics: input.3
[I]             Minimum Required Tolerance: elemwise error | [abs=4.7684e-07] OR [rel=0.25] (requirements may be lower if both abs/rel tolerances are set)
[I]             Absolute Difference | Stats: mean=2.2171e-08, std-dev=2.2423e-08, var=5.0277e-16, median=1.4901e-08, min=0 at (0, 0, 0, 0), max=4.7684e-07 at (0, 125, 173, 155), avg-magnitude=2.2171e-08
[I]             Relative Difference | Stats: mean=1.2063e-06, std-dev=0.00018732, var=3.5089e-08, median=1.4582e-07, min=0 at (0, 0, 0, 0), max=0.25 at (0, 123, 177, 66), avg-magnitude=1.2063e-06
[I]         PASSED | Difference is within tolerance (rel=0.001, abs=0.001)
[I]     PASSED | All outputs matched | Outputs: ['input.3']
[I] PASSED | Command: /usr/local/bin/polygraphy run SR.onnx --trt --onnxrt --trt-outputs input.3 --onnx-outputs input.3 --atol 1e-3 --rtol 1e-3 --fail-fast

```

**Comment by HowLii** [comment]
> Maybe, the result with official docker 22.09
> 
> ```
> [I] Accuracy Comparison | trt-runner-N0-10/20/22-11:48:04 vs. onnxrt-runner-N0-10/20/22-11:48:04
> [I]     Comparing Output: 'input.3' (dtype=float32, shape=(1, 128, 200, 200)) with 'input.3' (dtype=float32, shape=(1, 128, 200, 200))
> [I]     Tolerance: [abs=0.001, rel=0.001] | Checking elemwise error
> [I]         trt-runner-N0-10/20/22-11:48:04: input.3 | Stats: mean=0.012237, std-dev=0.18888, var=0.035676, median=0.0096648, min=-0.96694 at (0, 19, 83, 157), max=0.97184 at (0, 48, 132, 126), avg-magnitude=0.15045
> [I]         onnxrt-runner-N0-10/20/22-11:48:04: input.3 | Stats: mean=0.012237, std-dev=0.18888, var=0.035676, median=0.0096648, min=-0.96694 at (0, 19, 83, 157), max=0.97184 at (0, 48, 132, 126), avg-magnitude=0.15045
> [I]         Error Metrics: input.3
> [I]             Minimum Required Tolerance: elemwise error | [abs=4.7684e-07] OR [rel=0.25] (requirements may be lower if both abs/rel tolerances are set)
> [I]             Absolute Difference | Stats: mean=2.2171e-08, std-dev=2.2423e-08, var=5.0277e-16, median=1.4901e-08, min=0 at (0, 0, 0, 0), max=4.7684e-07 at (0, 125, 173, 155), avg-magnitude=2.2171e-08
> [I]             Relative Difference | Stats: mean=1.2063e-06, std-dev=0.00018732, var=3.5089e-08, median=1.4582e-07, min=0 at (0, 0, 0, 0), max=0.25 at (0, 123, 177, 66), avg-magnitude=1.2063e-06
> [I]         PASSED | Difference is within tolerance (rel=0.001, abs=0.001)
> [I]     PASSED | All outputs matched | Outputs: ['input.3']
> [I] PASSED | Command: /usr/local/bin/polygraphy run SR.onnx --trt --onnxrt --trt-outputs input.3 --onnx-outputs input.3 --atol 1e-3 --rtol 1e-3 --fail-fast
> ```

OK. Thank you very much!
I will try to change my environment.

**Comment by HowLii** [comment]
@zerollzeng  Thank you again! The problem disappear when I change GPU to 3090 with TensorRT 8.2.5.1.

**Comment by zerollzeng** [comment]
You are welcome, can we close this issue?

**Comment by HowLii** [comment]
Sure
