### ISSUE TITLE
TensorRT locked doing inference thread when the backup thread  loading myelingraph

### ISSUE THREAD

**Issue by Galaxygray** [NVIDIA/TensorRT#2402]
## Description

There is two thread doing inference in front and one backup thread loading trt engine, but when the backup thread was loading myelingraph, Doing inference thread had been locked 300ms+, In normal the inference thread cost 1-2ms do once inference including memcpy.
Is there have some bug?
![image](https://user-images.githubusercontent.com/15278582/196583856-d2f0c822-66ad-48b8-b643-99d58a40a510.png)

## Environment

TensorRT Version: 8.2.2.1
NVIDIA GPU: T4
NVIDIA Driver Version: 450.102.04
CUDA Version: 10.2
CUDNN Version: 8.2.4
Operating System: centos7.2
Python Version (if applicable): 3.8
Tensorflow Version (if applicable): No
PyTorch Version (if applicable): No

**Comment by zerollzeng** [comment]
@nvpohanh @zhenhuaw-me do you have any idea about this?

**Comment by zhenhuaw-me** [comment]
@Galaxygray Thank you for reporting this issue. If there is any dependecy between these two threads?

**Comment by Galaxygray** [comment]
@zhenhuaw-me two inference thread has't dependecy, load thread also hasn't dependecy with inference thread.
Now we use mulit-cuda_context to fix this problem, but mulit-cuda context cause use more memory to load the engine, and it's time-sliced in multi-cuda context.

**Comment by nvpohanh** [comment]
I think the the engine loading process requires loading some cuda kernels which may cause device-wide synchronizations and affect other threads. I don't see an easy fix for this. The workaround would be to load all engines at the beginning of the app.

**Comment by Galaxygray** [comment]
@nvpohanh OK,Thanks, why load some cud kernels need device-wide synchronizations and what It's, I check my engine whether contains the kernel. becase Not all model has this problem.

**Comment by nvpohanh** [comment]
In TRT, some kernels (especially for pointwise fusions) are compiled with NVRTC during engine building time and are saved as part of the engine. Then, when the engine is loaded, TRT will need to load those kernel binaries to driver via cuLoadModuleData() cuda APIs.

**Comment by Galaxygray** [comment]
@nvpohanh OK,Thanks!

**Comment by nvpohanh** [comment]
I think you can try multi-cucontext. It may help.

I don't think the refitting the weights would cause any device-wide syncs. If it does, please let us know. Thanks

**Comment by Galaxygray** [comment]
OK, Thanks, I try multi-cucontext  not solve it, and I try to load engine just once, and update model by refit weights, And Would the second way can slove it?

**Comment by ttyio** [comment]
closing inactive threads, thanks all!
