### ISSUE TITLE
Tensorrt  Bert Demo Error

### ISSUE THREAD

**Issue by pobei** [NVIDIA/TensorRT#241]
## Description

I can serialize the engine，when run the bert_inference.py ,errors occur.
message is:

python: /home/daniel.lch/TensorRT/demo/BERT/plugins/qkvToContextPlugin.cu:256: bert::QKVToContextPlugin::QKVToContextPlugin(std::__cxx11::string, int, int, int, bool): Assertion `hiddenSize % numHeads == 0' failed.

And i print the hiddenSize and numHeads in .cu file, the log is like:

hiddenSize: 0  numHeads :12
hiddenSize:1203708544  numHeads :12

Environment

TensorRT Version:  6.0.15
GPU Type:  v100
Nvidia Driver Version: 410.48
CUDA Version: 10.0
CUDNN Version: 7.6
Operating System + Version: centos
Python Version (if applicable): 3.6.9

**Comment by pobei** [comment]
I have found the error may be caused byt the deserialization function，all the
variables read from the file is wrong.

**Comment by rmccorm4** [comment]
Hi @pobei,

Did you ever figure out the root cause of this issue? Did you alter anything in the sample? It should work as-is for TensorRT 6.

**Comment by rmccorm4** [comment]
Closing since no response

**Comment by QingliangMeng** [comment]
@pobei Have you solved this problem?

**Comment by RicardoLeeV5** [comment]
I solve this problem by downgrading trt from 6.0 to 5.1.5 @QingliangMeng
