### ISSUE TITLE
using pytorch_quantization to quantize mmdetection3d model

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2411]
I'm trying to use pytorch_quantizationi to quantize a mmdetection3d pointpillar model. I use the lastest repo and added lines below at the tools/test.py file
```
from pytorch_quantization import nn as quant_nn
from pytorch_quantization import calib
from pytorch_quantization.tensor_quant import QuantDescriptor
quant_desc_input = QuantDescriptor(calib_method='histogram')
quant_nn.QuantConv2d.set_default_quant_desc_input(quant_desc_input)
quant_nn.QuantConvTranspose2d.set_default_quant_desc_input(quant_desc_input)
quant_nn.QuantLinear.set_default_quant_desc_input(quant_desc_input)

from pytorch_quantization import quant_modules
quant_modules.initialize()
```

The command I used was 
```
python tools/test.py configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py ./hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d_20210826_104936-fca299c1.pth --eval nuscenes
```

However, when I printed the model, only the feature extraction and head was quantized, backbone and neck was not quantized. Why is this?

head:
![image](https://user-images.githubusercontent.com/104115572/197393789-fc1b884c-cbdc-4a51-8acd-97e85006dbcc.png)

neck:
![image](https://user-images.githubusercontent.com/104115572/197393822-ba97c597-22e3-4395-924a-9895d2423b67.png)

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
@shuyuan-wang , this line: 

          quant_modules.initialize()

guarantee that all the `nn.*` called after this, is replaced with `nn.Quant*`, could you check how and when the backbone and neck is constructed? thanks!
