### ISSUE TITLE
how to disable per-channel quantization

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2414]
I'm using onnx opset 11 which is required since squeeze is different in 13. How do i disable default per-channel quantization?

**Comment by zerollzeng** [comment]
And I don't think we have such an option for the user, @ttyio to confirm.

**Comment by shuyuan-wang** [comment]
I thought per-channel quantization is only available for opset 13?

**Comment by ttyio** [comment]
@shuyuan-wang , could you try below lines?

       per_tensor_quant_desc_input = QuantDescriptor(num_bits=8, unsigned=True)
       quant_nn.QuantConv2d.set_default_quant_desc_input(per_tensor_quant_desc_input )
       quant_nn.QuantLinear.set_default_quant_desc_input(per_tensor_quant_desc_input )

We have more predefined quant desc in https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/pytorch_quantization/tensor_quant.py#L222, thanks!

**Comment by shuyuan-wang** [comment]
Hi, since per-channel is only supported for opset 13, if there is squeeze() in the model which squeezes multiple dimensions, do you have any suggestions on how to efficiently deal with this squeeze?

**Comment by ttyio** [comment]
> Hi, since per-channel is only supported for opset 13, if there is squeeze() in the model which squeezes multiple dimensions, do you have any suggestions on how to efficiently deal with this squeeze?

We do not quant squeeze in the automatic flow. Are you using the automatic flow or the monkey patch way?

**Comment by shuyuan-wang** [comment]
> > Hi, since per-channel is only supported for opset 13, if there is squeeze() in the model which squeezes multiple dimensions, do you have any suggestions on how to efficiently deal with this squeeze?
> 
> We do not quant squeeze in the automatic flow. Are you using the automatic flow or the monkey patch way?

wait, what is automatic flow?

I might not explained the issue very well. my issue is when I use the initialize() at the top and leave everything as it was, and then I export to opset 13 onnx. if I want to export the onnx to tensort engine, it will say squeeze() requires dim and throws error, which I believe is a feature of opset 13.

**Comment by ttyio** [comment]
@shuyuan-wang , could you share the onnx file if the error come from onnx to trt path? thanks!
