### ISSUE TITLE
What does "LayerType": "CaskConvolution" mean？

### ISSUE THREAD

**Issue by B-201** [NVIDIA/TensorRT#2418]
# Description

After I converted my model to TRT engine using trtexec, I noticed that there are some  layers of type "CaskConvolution" and "CaskPooling". What does "Cask" mean here, and what is the difference compared to ordinary convolution and pooling?

The graph information I output using trtexec is as follows:

    {
      "Name": "GlobalAveragePool_5",
      "LayerType": "CaskPooling",
      "Inputs": [
      {
        "Name": "input.12",
        "Location": "Device",
        "Dimensions": [1,64,540,960],
        "Format/Datatype": "Channel major FP16 format where channel % 8 == 0"
      }],
      "Outputs": [
      {
        "Name": "input.16",
        "Location": "Device",
        "Dimensions": [1,64,1,1],
        "Format/Datatype": "Channel major FP16 format where channel % 8 == 0"
      }],
      "ParameterType": "Pooling",
      "PoolingType": "AVERAGE",
      "WindowSize": [540,960],
      "PaddingMode": "kEXPLICIT_ROUND_DOWN",
      "PrePadding": [0,0],
      "PostPadding": [0,0],
      "Stride": [1,1],
      "BlendFactor": 0,
      "AverageCountExcludesPadding": 1,
      "TacticName": "sm50_xmma_pooling_fw_4d_FP16FP32NHWC_Average_FastDiv_GenericWindowWidth_CAlign4",
      "TacticValue": "0xe6818811f865a21a"
    },{
      "Name": "Conv_6 + Relu_7",
      "LayerType": "CaskConvolution",
      "Inputs": [
      {
        "Name": "input.16",
        "Location": "Device",
        "Dimensions": [1,64,1,1],
        "Format/Datatype": "Channel major FP16 format where channel % 8 == 0"
      }],
      "Outputs": [
      {
        "Name": "onnx::Conv_1640",
        "Location": "Device",
        "Dimensions": [1,4,1,1],
        "Format/Datatype": "Channel major FP16 format where channel % 8 == 0"
      }],
      "ParameterType": "Convolution",
      "Kernel": [1,1],
      "PaddingMode": "kEXPLICIT_ROUND_DOWN",
      "PrePadding": [0,0],
      "PostPadding": [0,0],
      "Stride": [1,1],
      "Dilation": [1,1],
      "OutMaps": 4,
      "Groups": 1,
      "Weights": {"Type": "Half", "Count": 256},
      "Bias": {"Type": "Half", "Count": 4},
      "HasSparseWeights": 0,
      "Activation": "RELU",
      "HasBias": 1,
      "HasReLU": 1,
      "TacticName": "sm80_xmma_fprop_implicit_gemm_f16f16_f16f16_f16_nhwckrsc_nhwc_tilesize64x64x64_stage4_warpsize2x2x1_g1_tensor16x8x16_t1r1s1",
      "TacticValue": "0xbb4ac900a7be8b4c"
    },

# Environment

TensorRT Version: 8.4.1.5

**Comment by zerollzeng** [comment]
@nvpohanh @pranavm-nvidia Do we have some official answer to this question?^ ^

**Comment by pranavm-nvidia** [comment]
It's the name of one our internal components that provides CUDA kernels. It's just an implementation detail and, e.g., CaskConvolution is semantically the same as Convolution provided by any other source.

**Comment by jeejeeli** [comment]
> It's the name of one our internal components that provides CUDA kernels. It's just an implementation detail and, e.g., CaskConvolution is semantically the same as Convolution provided by any other source.

Thanks for your reply, by the way, what's  "dupe layer removal"?

**Comment by pranavm-nvidia** [comment]
It means removing duplicate layers. e.g. if you have:
```
       input
      /     \
Reshape     Reshape
    |          |
   ...        ...  
```
If the `Reshape`s are identical, then you can write this as:
```
        input
          |
       Reshape   
          |
         ...
```

**Comment by jeejeeli** [comment]
> It means removing duplicate layers. e.g. if you have:
> 
> ```
>        input
>       /     \
> Reshape     Reshape
>     |          |
>    ...        ...  
> ```
> 
> If the `Reshape`s are identical, then you can write this as:
> 
> ```
>         input
>           |
>        Reshape   
>           |
>          ...
> ```

That's kind of you. Does it sound like common subexpression elimination？

**Comment by pranavm-nvidia** [comment]
Yup, similar idea.

**Comment by yanqzhao** [comment]
what's "LayerType": "TrainStation" mean?

**Comment by nvpohanh** [comment]
It means TensorRT need to wait for other layers' execution before we can move on. This usually happen when the tensor shape depends on activation computation results from previous layer(s)

**Comment by yanqzhao** [comment]
> It means TensorRT need to wait for other layers' execution before we can move on. This usually happen when the tensor shape depends on activation computation results from previous layer(s)

my graph.json is started with following content:
since the traistation is the first level, I can't figure out what this level is waiting for? or how can I know what is waiting for of the trainstation level?
{"Layers": [{
  "Name": "[trainStation1]",
  **"LayerType": "TrainStation",**
  "Inputs": [],
  "Outputs": [],
  "TacticValue": "0x0000000000000000",
  "StreamId": 0,
  "Metadata": ""
},{
  "Name": "{ForeignNode[Slice_416...Reshape_490]}",
  "LayerType": "Myelin",
  "Inputs": [
  {
    "Name": "set_voxel_masks_tensor_shift_0",
    "Location": "Device",
    "Dimensions": [2,200,36],
    "Format/Datatype": "Row major linear BOOL"
  }],
  "Outputs": [
  {
    "Name": "key_padding_mask",
    "Location": "Device",
    "Dimensions": [200,36],
    "Format/Datatype": "Row major linear BOOL"
  },
  {
    "Name": "onnx::NonZero_934",
    "Location": "Device",
    "Dimensions": [7200],
    "Format/Datatype": "Row major linear BOOL"
  }],
  "TacticValue": "0x0000000000000000",
  "StreamId": 0,
  "Metadata": ""
},{
  "Name": "[ShapeHostToDeviceCopy 0]",
  "LayerType": "ShapeHostToDevice",
  "Inputs": [],
  "Outputs": [
  {
    "Name": "(Unnamed Layer* 1416) [Gather]_output",
    "Location": "Device",
    "Dimensions": [],
    "Format/Datatype": "Row major linear Int32"
  },

**Comment by yanqzhao** [comment]
my onnx is the following one:

[Uploading onnx_202312211240_sim.zip…]()


> @yanqzhao Could you share your ONNX file so that we can check which op caused it? Thanks

**Comment by yanqzhao** [comment]
> @yanqzhao Could you share your ONNX file so that we can check which op caused it? Thanks

[onnx_202312211240_sim.zip](https://github.com/NVIDIA/TensorRT/files/13881877/onnx_202312211240_sim.zip)
my onnx is this one, thanks

**Comment by nvpohanh** [comment]
Thanks. The TrainStation layers are because of the "NonZero" ops

**Comment by yanqzhao** [comment]
> Thanks. The TrainStation layers are because of the "NonZero" ops

thank you for your reply, I can understand that "NonZero" ops cause the trainstation, but why the first level is trainstation?
I commit a issue about trt-engine-explorer in this link https://github.com/NVIDIA/TensorRT/issues/3585, since the trainstation has no output, the trt-engine-explorer cannot work well.
