### ISSUE TITLE
Need example for Ilooplayer

### ISSUE THREAD

**Issue by charliedream1** [NVIDIA/TensorRT#2421]
## Description

I haven't found any example of Ilooplayer, how to loop to make two tensor keep adding, please give an example of usage

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-loops

**Comment by charliedream1** [comment]
thanks

**Comment by zerollzeng** [comment]
closed
