### ISSUE TITLE
<onnx_graphsurgeon>what is the useage of graph.nodes

### ISSUE THREAD

**Issue by Lee-ray-a** [NVIDIA/TensorRT#2427]
## Description

```python
graph = gs.import_onnx(onnx.load(onnx_file))
for node in graph.nodes:
    print(node.op)
```

**Apart from the node.op, what other functions of node I can use?**
**Since I want to remove certain layers**

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by nvpohanh** [comment]
You can refer to the source code here: https://github.com/NVIDIA/TensorRT/blob/master/tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/node.py#L25

**Comment by Lee-ray-a** [comment]
Thanks for your help
