### ISSUE TITLE
Manually load int8 weight from QAT model (quantized with pytorch-quantization-tool)

### ISSUE THREAD

**Issue by thancaocuong** [NVIDIA/TensorRT#2429]
After done QAT, I save state dict of the quantized model and found in the state dict, the weight for a simple conv2d consists of ```_input_quantizer._amax``` and ```_weight_quantizer._amax```. So I want to create Conv2d with TensorRT python API and manually load the weight. So how can I do that? I would appreciate that you can help me. thanks

**Comment by zerollzeng** [comment]
@ttyio Is it possible to achieve this?

**Comment by ttyio** [comment]
@thancaocuong , check demobert, we load `amax` from checkpoint and use `setDynamicRange` to set the int8 max.

https://github.com/NVIDIA/TensorRT/blob/main/demo/BERT/builder_utils.py#L218
https://github.com/NVIDIA/TensorRT/blob/main/demo/BERT/builder.py#L116

Thanks!

**Comment by thancaocuong** [comment]
@ttyio  thanks for you comment. But one thing still makes me confused is that ```_weight_quantizer._amax``` of the convolution layers is a tensor, not a float value. So I can not use setDynamicRange. How can I do that?

**Comment by ttyio** [comment]
@thancaocuong , the `setDynamicRange` is used for PTQ, and the weights are quantize by TRT internally. only need call `setDynamicRange` for activations, they are per tensor. Thanks!

**Comment by thancaocuong** [comment]
@ttyio  Yeah, I have found the document to do that. So I need to convert _amax to scale then construct a network with quantize and dequantize node (Q/DQ). Then now the problem has been solved. I will check the accuracy of the serialized engine. Thanks.
