### ISSUE TITLE
transformer support

### ISSUE THREAD

**Issue by 2020zyc** [NVIDIA/TensorRT#243]
hi, can tensorrt support transformer directly(translation, not bert just an encoder)?

or I should implement the tensorrt decoder myself.

**Comment by pobei** [comment]
can you run the bert demo?

**Comment by 2020zyc** [comment]
hi, @pobei 
I have not run the bert demo myself. But I think tensorrt is good at dealing with models without recurrent units or control flow, like encoders(bert/Albert/...) and image model(ResNet/...).

So what your mean is I can use TRT in the transformer model like the demo bert? 

thanks.

**Comment by rmccorm4** [comment]
Hi @2020zyc,

TensorRT 7.0 was released recently and added more support for RNNs. Check out the release notes: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html#rel_7-0-0
