### ISSUE TITLE
[polygraphy] [W] Missing scale and zero-point for tensor 

### ISSUE THREAD

**Issue by Lee-ray-a** [NVIDIA/TensorRT#2430]
## Description

**I was using this command line to get trt_int8 from onnx, but I got some warning as follows**
```python
polygraphy convert identity. onnx --int8 \
    --data-loader-script ./data_loader.py \
    -o identity.engine
```

![image](https://user-images.githubusercontent.com/71243853/198250748-d67b27ef-4931-4759-ac8b-66c1279c39c9.png)
 **Dose this warning affect the int8 engine?**
## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
Is it a QAT model? looks like it's due the missing scale in the tensor, so TRT just fallback those layers to FP16/FP32. @ttyio for more info.

**Comment by ttyio** [comment]
@Lee-ray-a , not all layers has scale, e.g, for identity layer there is not scale, need check the op that generates those tensors. 
thanks!

**Comment by ttyio** [comment]
closing due to no response for more than 3 weeks, please reopen if you still have question, thanks!
