### ISSUE TITLE
Unstable latency

### ISSUE THREAD

**Issue by Javacr** [NVIDIA/TensorRT#2431]
I got the mask rcnn fp16 engine and used c++ version tensorrt for inference. When I tested a video, I found that the latency was erratic. The average delay is 28ms, but every 12 frames,  one frame takes 200ms±. How to solve this problem?
![图片1](https://user-images.githubusercontent.com/44012990/198253979-46364370-11ca-4bf0-8f43-2a6ec473e4c6.png)

**Comment by Javacr** [comment]
I have solve this problem by using a subthread.

**Comment by zerollzeng** [comment]
closed, feel free to reopen if you have any further questions.
