### ISSUE TITLE
Open source license of libmyelin.so.1

### ISSUE THREAD

**Issue by tetrasai** [NVIDIA/TensorRT#2439]
Hello, everyone!

![info](https://user-images.githubusercontent.com/82380518/198557045-8a85dfae-7642-4e0c-a2f1-b25a9f80caf3.png)

As shown in the image, **libnvinfer.so** is depend on **libmyelin.so.1.**

May I ask what's the Open Source License of the **libmyelin.so.1**? 

I couldn't get this answer from google search, that is why I post this issue in here.

I would appreciate it if you can share some information about **libmyelin.so.1** with me.

Looking forward to your reply!

Thank you!

**Comment by zerollzeng** [comment]
@zhenhuaw-me ^ ^

**Comment by zhenhuaw-me** [comment]
@tetrasai Thank you for your questions.

`libmyelin.so.1` is not an open source project, so please don't include it in your project. We don't provide support of it. But you can use TensorRT.

Closing this issue now. Please let me know if any further questions. Thanks!
