### ISSUE TITLE
EmbLayerNormPlugin, inconsistency in the output layout in the code with that specified in the doc

### ISSUE THREAD

**Issue by frankxyy** [NVIDIA/TensorRT#2440]
![image](https://user-images.githubusercontent.com/6971044/198576582-b49b4526-e038-41c9-804c-f06c8f53c593.png)
In the code, if the `(mUseFullMask || (isSmOK && isPrecisionOK)` condition goes true, the second output of EmbLayerNormPlugin will return a tensor of second dim `combinedMaskSize`. While in the doc, it specifies that the second dim equals 1:
![image](https://user-images.githubusercontent.com/6971044/198576949-ad055555-09f8-471c-920c-3089bd086a08.png)

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
thanks @frankxyy , yes for unfused the output is [B, 1], for fused it depends on the layout requirement in mha kernel. we will update the doc.

**Comment by ttyio** [comment]
will updated in next release, close and thanks!
