### ISSUE TITLE
How to create a calibration dataset in Python and use it with trtexec to convert onnx model to trt engine

### ISSUE THREAD

**Issue by SM1991CODES** [NVIDIA/TensorRT#2446]
Hi,

I would want to:
1) Generate my own calibration data in Python
2) Use it with trtexec --int8 --calib.... to convert my onnx model to trt engine

My end goal is int8 inference.
I could not find any simple and clear example for this.
Please help.

Best Regards

**Comment by zerollzeng** [comment]
An easy way with polygraphy: https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert/01_int8_calibration_in_tensorrt

**Comment by SM1991CODES** [comment]
Hey, thanks a lot. This will help!!

Best Regards
Sambit

**Comment by SM1991CODES** [comment]
Yes please. I will try it out and reopen an issue if something doesn't work.

Best Regards
Sambit
