### ISSUE TITLE
Are src/tensor_quant.cu and .cpp files still used? or deprecated? 

### ISSUE THREAD

**Issue by chaeunl** [NVIDIA/TensorRT#2448]
Hello,

like as what I mentioned in the title, I am wondering whether these files are still used or not.

In the `pytorch-quantization/pytorch-quantization/tensor_quant.py`  file, all the functionality of `fake_quantization` are implemented and it seems that `src/tensor_quant.cu` and `src/tensor_quant.cu` are not used anywhere.

Are these files going to be deprecated in the near future? and if so, for the case of custom number format (e.g., exp_bits=6 and mantissa=1 based FP8), I hope to know your plan (if planned to support).

Thanks.

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
@chaeunl , the `*.cu` are cuda extension for fake quant, we will use these to replace current python implementation in the long term.
For the FP8, we are evaluation it but might not commit in the next release.

**Comment by chaeunl** [comment]
@zerollzeng @ttyio  thanks to your reply.

So far as I understand, `*.cu` files are supposed to accelerate some operations like type-casting from float to integer or floating point to block point (or maybe customized number format) with CUDA kernel, whose approach is similar to `QPyTorch`.

Related with this issue, is there any way to accumulate the multiplication of two scalar values whose number format is customized? For instance, I am trying to make a custom format FP10 which has 1 bit assigned for sign, 2 bits for mantissa and 7bit for exponent, and multiply them with FP10 multiplier. The multiplication might be quite simple, but dealing with the accumulation of FP10 (i.e., accumulation using custom accumulator), it doesn't look simple task. Could you let me know if there is any good reference for this issue?

**Comment by ttyio** [comment]
@chaeunl sorry I have no recommandation for the acceleration on customized quantization bits.

closing and thanks!
