### ISSUE TITLE
Can dynamic shape be used for image segmentation？How do I realize dynamic graph segmentation using onnx？

### ISSUE THREAD

**Issue by Kn1417** [NVIDIA/TensorRT#245]
## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by Kn1417** [comment]
In the sampleDynamicReshape，it builds one engine that resizes a given input to the correct size，then how to understand dynamic shape？Thx.

**Comment by rmccorm4** [comment]
Hi @Kn1417,

Please see the developer guide for more info on dynamic shape: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes
