### ISSUE TITLE
QAT recommendation

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2451]
In the document [docs](https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html#quantization-aware-training), It recommends not change quantization representation (scale) during training, at least not too frequently. How exactly do I not change scale during QAT training?

**Comment by ttyio** [comment]
@shuyuan-wang , 
see https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L387, the scale is changed during calibration.

    for name, module in model.named_modules():
        if isinstance(module, quant_nn.TensorQuantizer):
            if module._calibrator is not None:
                module.disable_quant()
                module.enable_calib()
            else:
                module.disable()

**Comment by shuyuan-wang** [comment]
Thanks

**Comment by zsh4614** [comment]
> [@shuyuan-wang](https://github.com/shuyuan-wang) , see https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L387, the scale is changed during calibration.
> 
> ```
> for name, module in model.named_modules():
>     if isinstance(module, quant_nn.TensorQuantizer):
>         if module._calibrator is not None:
>             module.disable_quant()
>             module.enable_calib()
>         else:
>             module.disable()
> ```
> 
> By call
> 
> ```
>    module.disable_calib()
> ```
> 
> The calibration is turned off, and you can call
> 
> ```
>    module.enable_quant()
> ```
> 
> to do fine-tuning without change scale.

Sorry, I have a question. During the fine-tuning process of QAT, the model weights will change. If the scale of the weights remains unchanged, is the scale calculated during calibration still reasonable? Should the scale never be updated during fine-tuning? If it can be updated, how should the scale be updated during training? Are there any recommended update strategies?
