### ISSUE TITLE
Query about buffer[] for trt inference input

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/TensorRT#2452]
## Description
```
// Run TensorRT inference
void* bindings[] = {input_mem, output_mem};
bool status = context->enqueueV2(bindings, stream, nullptr);
if (!status)
{
    gLogError << "ERROR: TensorRT inference failed" << std::endl;
    return false;
}
```
Can this `input_mem` be a one-dimensional array?

https://github.com/NVIDIA/TensorRT/issues/2452#tasklist-block-1838b62c-4fd9-41a4-96ab-246dcdd376a6

**Comment by zerollzeng** [comment]
Yes, bindings are just an array of buffers, no matter what its dims or datatype, just make sure the size is enough.

**Comment by ywfwyht** [comment]
> Yes, bindings are just an array of buffers, no matter what its dims or datatype, just make sure the size is enough.

Can `input_mem` be a one-dimensional array? If it is the input of rgb three-channel {1, 3, 480, 640}, how can it be written as a one-dimensional array?

**Comment by zerollzeng** [comment]
in memory, it's a 1 dimensional array.

**Comment by ywfwyht** [comment]
ok, thanks.
