### ISSUE TITLE
How to assign a torch tensor to inputs.device directly?

### ISSUE THREAD

**Issue by CCOSerika** [NVIDIA/TensorRT#2456]
Hi, 
I write following code to speed up the inference of transformer from PyTorch.
```
    logger = trt.Logger(trt.Logger.ERROR)
    trt.init_libnvinfer_plugins(logger, namespace="")
    with open("./test.engine", 'rb') as fr, trt.Runtime(logger) as runtime:
        engine = runtime.deserialize_cuda_engine(fr.read())
    
    inputs, outputs, bindings, stream = common.allocate_buffers(engine)

    ### input is a torch tensor on gpu
    inputs[0].host = input.cpu().numpy()
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]

    ### it failed for different type between torch.tensor and pycuda._driver.DeviceAllocation
    # inputs[0].device = input

    context = engine.create_execution_context()
    context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)

    cuda.memcpy_dtoh_async(outputs[0].host, outputs[0].device, stream)
    # stream.synchronize()
    output = torch.from_numpy(outputs[0].host).reshape((-1, 3))
```
Evidently, I have a torch tensor on gpu as input. 
To adapt the interface, I have to transfer it to cpu and assign it to inputs[0].host, and then it is transferred to gpu again, which is just so superfluous.
So I'd like to ask how to assign it to inputs[0].device directly?

**Comment by zerollzeng** [comment]
@pranavm-nvidia ^ ^

**Comment by pranavm-nvidia** [comment]
The `bindings` argument is just a list of pointers. With torch, you should be able to do `tensor.data_ptr` to get the device pointer.

**Comment by akaraca-czm** [comment]
I have attempted same way by altering bindings elements with I acquired pointer that returned from x.ptr_data() which is torch cuda tensor. context.execute_async_v2() function returns false, so all of my outputs are zero. I dedugged part of code but I did not see anything.
