### ISSUE TITLE
[question] the implementation of allClassNMS.cu 

### ISSUE THREAD

**Issue by twmht** [NVIDIA/TensorRT#246]
Hi,

I am looking into the implementation of allClassNMS.cu

https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/kernels/allClassNMS.cu#L154

where you make the element of `beforeNMS_index_array` to -1?

**Comment by rajeevsrao** [comment]
@twmht it comes from input0 (locData) in `BatchedNMSDynamicPlugin::enqueue`
