### ISSUE TITLE
python api documents error

### ISSUE THREAD

**Issue by jeejeeli** [NVIDIA/TensorRT#2461]
## Environment

**TensorRT Version**: 
TensorRT 8.5.1.7

As [TRT python api](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html#tensorrt.IGridSampleLayer) described , IGridSampleLayer has  variable named ` padding_mode`,but this variable is `sample_mode` rather than `padding_mode`. The detail as follow:

```python
dir(tensorrt.IGridSampleLayer)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'align_corners', 'get_input', 'get_output', 'get_output_type', 'interpolation_mode', 'name', 'num_inputs', 'num_outputs', 'output_type_is_set', 'precision', 'precision_is_set', 'reset_output_type', 'reset_precision', 'sample_mode', 'set_input', 'set_output_type', 'type']
```

**Comment by zerollzeng** [comment]
@pranavm-nvidia Can you help check it? thanks!

**Comment by pranavm-nvidia** [comment]
Thanks for letting us know, fixing that now.

**Comment by nvpohanh** [comment]
@pranavm-nvidia has this been fixed?

**Comment by pranavm-nvidia** [comment]
Yup, should be resolved when we publish the docs again.

**Comment by zerollzeng** [comment]
closed
