### ISSUE TITLE
Does fused DeQuant node still convert to FP32?

### ISSUE THREAD

**Issue by david-macleod** [NVIDIA/TensorRT#2476]
Not a bug, but wasn't clear where I could ask more general question so apologies if this is the wrong place. 

The docs show that DeQuant ops get "fused" with other nodes, but doesn't make clear whether the fused op is still dequantizing internally before performing the matmul. Which is correct?

1. Dequant still takes place before the matmul and so the matmul is at FP32 and the perf gains comes from faster data loads into SRAM, but INT8 tensorcores are **not** used
2. Dequant becomes a no-op and perf gains are _both_ from faster data loaded **and** INT8 tensorcores

Thanks!

<img width="603" alt="image" src="https://user-images.githubusercontent.com/17232877/201190656-6e6087d4-3cf9-4d28-a4e8-757f8a085210.png">

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/17232877/201190736-21a69ca2-5e1a-4b20-9ede-1751a0111ff1.png">

**Comment by zerollzeng** [comment]
> 2\. Dequant becomes a no-op and perf gains are _both_ from faster data loaded **and** INT8 tensorcores

I think this is correct but I don't understand it well too, @ttyio can you put some insight here ^ ^

**Comment by ttyio** [comment]
Yes, we use INT8 tensorcores after DQ fused into conv.
