### ISSUE TITLE
How to know the model after int8 quantization, which layers are quantized？

### ISSUE THREAD

**Issue by shhn1** [NVIDIA/TensorRT#2485]
## Environment

**TensorRT Version**: 8.4.1
**NVIDIA GPU**: A10
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**: 11.6: 

After int8 quantization of the model, I found that the model speed is basically the same as fp16. I want to know which layers of the model are quantized by int8. Or is there any other reason that can explain this phenomenon?

**Comment by zerollzeng** [comment]
if you enable verbose log. you can see the final engine layers and its precision.

**Comment by shhn1** [comment]
In fact, after the model is quantized by int8, there is almost no loss of accuracy. In the process of int8 quantization, which operators will be quantized? I found that the speed of int8 conv is indeed doubled, but the backbone of my model is a swin transformer, and I found that the entire backbone network does not have any acceleration.

**Comment by zerollzeng** [comment]
What you mean is PTQ right? currently we don't support PTQ for transformer-based networks. so it will be running in FP16. To use INT8 for transformer, you will nedd QAT.

**Comment by shhn1** [comment]
I did quantify with PTQ. Thank you for your reply that answered my doubts.  : )

**Comment by zerollzeng** [comment]
@ttyio @zhenhuaw-me  Do we have such plan? thanks!

**Comment by ttyio** [comment]
@shhn1 , currently there is no plan to support PTQ for transformer based models. From our previous experiments on BERT, F1 loss is larger than 1 for PTQ on SQuAD, which might not meet the accuracy requirement.
