### ISSUE TITLE
How to use default plugin layers in TensorRT OSS lib while building network with C++ API?

### ISSUE THREAD

**Issue by nan0755** [NVIDIA/TensorRT#249]
## Description
The sample [samplePlugin](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/samplePlugin) use `caffeParser` to specify the layer `ip2` to be changed, and the sample [sampleMNISTAPI](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleMNISTAPI) use TRT C++ API to build the network. I wonder how can we use C++ API to build the network while there is a plugin layer in it.

The default layers like `convolution` can be added to network using C++ API  `INetworkDefinition::addConvolution()`. How about the plugin layer to be added to network, like [grelu](https://github.com/NVIDIA/TensorRT/tree/master/plugin/geluPlugin), in such a way?

**Comment by nan0755** [comment]
I found it `addPluginV2`.

**Comment by rmccorm4** [comment]
Hi @nan0755,

Does this sample help answer your question?

https://github.com/NVIDIA/TensorRT/blob/07ed9b57b1ff7c24664388e5564b17f7ce2873e5/parsers/caffe/caffeParser/caffeParser.cpp#L546-L556
