### ISSUE TITLE
OCR recognition returns nan value in INT8

### ISSUE THREAD

**Issue by naeunhub** [NVIDIA/TensorRT#2490]
I'm currently trying to convert the OCR model to tensorrt.
We have confirmed that both the normal operation of the existing model and the conversion to FP16 have good results, and even for INT8, the detector has good results. However, there is a problem that the nan value is returned continuously only in the recognition of INT8.
My recognition is using the Transformer. Is there a problem with this when converting to INT8 or is there anything that needs to be set additionally unlike other precision modes?

**Comment by zerollzeng** [comment]
Looks like a bug, can you provide a reproduce? thanks!

**Comment by naeunhub** [comment]
settings_ = tf.experimental.tensorrt.ConversionParams(precision_mode='INT8',
                                                            minimum_segment_size=mss,
                                                            maximum_cached_engines=mce,
                                                            use_calibration=True)
converter = tf.experimental.tensorrt.Converter(
        input_saved_model_dir=dir_, conversion_params=settings_)
converter.convert(calibration_input_fn=calibration_input_fn)

I'm using this code to convert tensorrt model and same calibration function with FP16.

**Comment by zerollzeng** [comment]
I would suggest to file TF-TRT issues to https://github.com/tensorflow/tensorrt
cc @ncomly-nvidia

**Comment by naeunhub** [comment]
Thanks!
