### ISSUE TITLE
May release stable diffusion plugins where sm < 80 like T4 device?

### ISSUE THREAD

**Issue by jike-algorithm-zhangxiao** [NVIDIA/TensorRT#2491]
I want to use tensorrt to accelerate stable diffusion inference. 
just find tensorrt release stable diffusion plugins, So happy! 
But i want to deploy it in T4 device,  like crossattention or flashattention plugin doesn't support.
Will release this plugin can perform on T4 device later ?

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by nvpohanh** [comment]
I am not sure about the timeline for that support. But meanwhile, you can try disabling those plugins and run it with TRT natively. It should still work.

**Comment by nvpohanh** [comment]
Internal discussion shows that we are already working on this and will add the SM75 support soon.

**Comment by jike-algorithm-zhangxiao** [comment]
greate!

**Comment by rajeevsrao** [comment]
@jike-algorithm-zhangxiao Turing (SM75) support added in this branch: [release/8.5-demodiffusion](https://github.com/NVIDIA/TensorRT/tree/release/8.5-demodiffusion) (will be merged to release/8.5 in a few days)
