### ISSUE TITLE
Error Code 2: Internal Error (Assertion validateCaskKLibSize(buffer.size) failed. 

### ISSUE THREAD

**Issue by geoexploring** [NVIDIA/TensorRT#2496]
When I changed the version of TensorRT from `8.0.1.6` to `8.4.2.4`, got an error:
```
2: [builder.cpp::nvinfer1::builder::createCaskKernelLibraryImpl::137] Error Code 2: Internal Error (Assertion validateCaskKLibSize(buffer.size) failed. )
```
But it ran on `8.0.1.6` without any problems.

thanks.

**Comment by geoexploring** [comment]
The problem has been resolved because the corresponding dependent library version of TensorRT does not match.

**Comment by wang11wei** [comment]
> The problem has been resolved because the corresponding dependent library version of TensorRT does not match.

hi, i got the same issue, what do you mean "corresponding dependent library version"? how did you find the right version?
