### ISSUE TITLE
scaleAllPositive && "Scale coefficients must all be positive" Error Converting onnx quantized model from pytorch-quantization 

### ISSUE THREAD

**Issue by 0hkw0n** [NVIDIA/TensorRT#2498]
## Description

seems like 0 scale produced during calibration with pytorch-quantization.

this is onnx model visualized by neutron
![image](https://user-images.githubusercontent.com/117965898/203458010-13749fc1-db26-4206-9a3e-e83b24fa4c9b.png)

and when I try to convert this onnx to tensorRT engine. It says..

![image](https://user-images.githubusercontent.com/117965898/203458112-48a2dda5-1426-4cf2-b434-e383c6127b57.png)

## Environment

**TensorRT Version**: 8.5.1.7
**NVIDIA GPU**: 3090ti
**NVIDIA Driver Version**: 520
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0
**Operating System**: ubuntu18.04
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: X
**PyTorch Version (if applicable)**: 1.13
**Baremetal or Container (if so, version)**: NGC nvcr.io/nvidia/pytorch:22.10-py3 Container

## Relevant Files

example pth model(HRNet Trained with MMPose):
https://drive.google.com/file/d/1Iwr1DNfvY0ibvSHgVmKxcABYyPaTgvHs/view?usp=sharing

calibration Code Nodebook:
https://drive.google.com/file/d/1DghVTdxwv4q2cZGrPfZ_4QLJYU_Prbr9/view?usp=sharing

calibrated pth model:
https://drive.google.com/file/d/1uIG8PIxtXAWBOrbe6tAqm7eZA-I9mCWI/view?usp=sharing

onnx converted from above pth:
https://drive.google.com/file/d/12GNuuSyYJHcwQeUNSnzMUvnEJvypNvUg/view?usp=share_link

code to conver onnx to tensorRT Engine:
https://drive.google.com/file/d/1KOEakHceGtje5PfALfiUUlMMgnTXk7LI/view?usp=sharing

## Steps To Reproduce

download example pth model and calibrated it with notebook( I installed mmpose inside nvcr.io/nvidia/pytorch:22.10-py3 container in NGC ).

then I converted this pth to tensorRT after converting to onnx.

**Comment by zerollzeng** [comment]
Duplicate issue of https://github.com/NVIDIA/TensorRT/issues/2267

**Comment by jiaerwang0328** [comment]
I have encountered the same problem, how to solve it？

**Comment by jamh00** [comment]
how to solve

**Comment by zerollzeng** [comment]
Could you please provide a reproduce with the latest pytorch-quantization? cc @ttyio
