### ISSUE TITLE
Rules about dynamic range setting and quantization

### ISSUE THREAD

**Issue by Tracin** [NVIDIA/TensorRT#25]
We try to figure out how Trt actually do quantization，so we build some simple models using pytorch and convert to .onnx and do test. We set ranges using statistics coming from our tools. We found something confusing about setting ranges:
1. For some tensors, the ranges we set are not actually working. Such as combination Conv+Relu, the tensor of Conv's output actually do not need ranges(different ranges get the same outputs).
2. Some reshape layers(shuffle) need for ranges, which is unreasonable, while other reshape layers do need, we can't tell the difference between them.
3. We found if any tensors marked as the outputs of network, will not be quantized(neither that layer).
4. Fully connected layer in .onnx will be converted with extra shuffle layers in Trt.
5. Do ranges for Int8 quantization of layers simply set to the max values in weights? Our experiments show it is may not that simple in Trt. And how about the bias?
   
We need to know if  the result above is correct, and we want to know the specific method of range setting.
We use Tensorrt 5.1.2.2 and run sample_int8_api for test.
Thank you very much!

**Comment by DilipSequeira** [comment]
Hmm, where to start... OK, let's take these in order:

1. TensorRT only uses dynamic range values when it converts from higher precision to INT8. When it fuses layers (such as Conv and ReLU) the dynamic range of the Conv will be ignored.

2. reshapes can be elided if they're effectively the Identity. Again, dynamic range would be ignored.;

3. right - TensorRT 5 does not have the capability to use inputs and outputs in INT8, so this will override even the use of strict type constraints to control precision.

4. don't know about this one, sorry. Possibly the ONNX parser source might be your best lead.

5. No, ranges simply instruct TensorRT to scale the higher precision value by 127/range and clamp to int8 range. Weight quantization is independent of anything that can be expressed using the TensorRT 5 API.

**Comment by Tracin** [comment]
> Hmm, where to start... OK, let's take these in order:
> 
> 1. TensorRT only uses dynamic range values when it converts from higher precision to INT8. When it fuses layers (such as Conv and ReLU) the dynamic range of the Conv will be ignored.
> 2. reshapes can be elided if they're effectively the Identity. Again, dynamic range would be ignored.;
> 3. right - TensorRT 5 does not have the capability to use inputs and outputs in INT8, so this will override even the use of strict type constraints to control precision.
> 4. don't know about this one, sorry. Possibly the ONNX parser source might be your best lead.
> 5. No, ranges simply instruct TensorRT to scale the higher precision value by 127/range and clamp to int8 range. Weight quantization is independent of anything that can be expressed using the TensorRT 5 API.

Thank you very much for your reply! We have figured out that all confusing matters come from layer fusion, and the fact that weight is quantized per channel. Now we are pretty familiar with TensorRT, thanks again!
