### ISSUE TITLE
trtexec failed to handle slice op when converting onnx model to tensorrt model.

### ISSUE THREAD

**Issue by scse-l** [NVIDIA/TensorRT#2509]
## Description
When I try to us trtexec to conver an onnx model to tensorrt model with dynamic shapes, I got an error message: 
[E] Error[2]: [myelinBuilderUtils.cpp::operator()::544] Error Code 2: Internal Error (PartitionedCall/model/tf.strided_slice/StridedSlice requires bool or uint8 I/O but node can not be handled by Myelin. Dynamic shapes are not equal for slice params.)

## Environment
**I use image from ngc: nvcr.io/nvidia/tritonserver:22.10-py3**
**TensorRT Version**:  8.5.0-1
**NVIDIA GPU**:  v100-32g
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0.163-1
**Operating System**: ubuntu 20.04
**Python Version (if applicable)**: python 3.8
**Tensorflow Version (if applicable)**:  2.11.0
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: container

## Relevant Files
code to build the model in tf:
```python
def build_simple_tf_model():
    input = tf.keras.Input(shape=(None,), name='input', dtype=tf.float32)
    eq_out = tf.math.equal(input, 0)
    not_out = tf.math.logical_not(eq_out)
    slice_out = tf.strided_slice(not_out, (0, 1), (3, 3))

    model = tf.keras.Model(inputs=input, outputs=slice_out)
    tf.saved_model.save(model, "fail/1")
```
tf2onnx: https://github.com/onnx/tensorflow-onnx

## Steps To Reproduce
1. Run code snippet to get a pb model
2. Use tf2onnx to convert the model to onnx: `python -m tf2onnx.convert --saved-model ./fail/1/ --output /model.onnx`
3. Use trtexec to convert onnx model to tensorrt model with dynamic shapes: `trtexec --onnx=/model.onnx --saveEngine=fail.plan --minShapes=input:1x1 --optShapes=input:4x4 --maxShapes=input:8x8 --verbose `

**Comment by zerollzeng** [comment]
can you try it with `--preview=fasterDynamicShapes0805`? if not work can you upload the onnx model here? thanks!

**Comment by scse-l** [comment]
> can you try it with `--preview=fasterDynamicShapes0805`? if not work can you upload the onnx model here? thanks!

THANKS! It works with `--preview=**+**fasterDynamicShapes0805`.  So is this a experimental feature ? When should I use it?

There is another problem. It seems that engine is built successfully with the option, but can not be saved to file. Here is the log:

[12/01/2022-07:15:44] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +512, now: CPU 0, GPU 512 (MiB)
[12/01/2022-07:15:45] [E] Saving engine to file failed.
[12/01/2022-07:15:45] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8500] # trtexec --onnx=/model.onnx --saveEngine=/model.plan --preview=+fasterDynamicShapes0805 --minShapes=input:1x1 --optShapes=input:1x1 --maxShapes=input:8x1 --verbose

FYI, I tried python api and it worked.

**Comment by zerollzeng** [comment]
> It seems that datatypes of inputs is not set properly.

Yes

**Comment by scse-l** [comment]
> > There is another problem. It seems that engine is built successfully with the option, but can not be saved to file.
> 
> No write permission?

Can't be. I checked & tried other models, there is no such problem.

**Comment by scse-l** [comment]
> > It seems that datatypes of inputs is not set properly.
> 
> Yes

THANKS a lot ! I checked my script and found out that I used "FLOAT32" instead of "FP32".
