### ISSUE TITLE
uff genererated for mask rcnn not working with trtexec

### ISSUE THREAD

**Issue by manga22** [NVIDIA/TensorRT#251]
I followed the steps mentioned in sampleUffMaskRCNN to generate the uff. The uff file was generated successfully with the following log.
`The output names of tensorflow graph nodes: ['mrcnn_mask/Reshape_1']
WARNING:tensorflow:From mrcnn_to_trt_single.py:137: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/graph_util_impl.py:270: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From /usr/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py:231: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

NOTE: UFF has been tested with TensorFlow 1.12.0. Other versions are not guaranteed to work
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.3
[name: "input_image"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: 3
      }
      dim {
        size: 1024
      }
      dim {
        size: 1024
      }
    }
  }
}
]

Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_mask_trt as custom op: PyramidROIAlign_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p5upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p4upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p3upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: SpecialSlice_TRT yet.
Converting mrcnn_detection_bboxes as custom op: SpecialSlice_TRT
Warning: No conversion function registered for layer: DetectionLayer_TRT yet.
Converting mrcnn_detection as custom op: DetectionLayer_TRT
Warning: No conversion function registered for layer: ProposalLayer_TRT yet.
Converting ROI as custom op: ProposalLayer_TRT
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_classifier as custom op: PyramidROIAlign_TRT
No. nodes: 3044
UFF Output written to ../mrcnn_nchw.uff
UFF Text Output written to ../mrcnn_nchw.pbtxt
`
**But running this file using trtexec throws the following error. Is there any way to check if the file is converted to uff correctly? Any inputs to fix the following error?**

`sudo /usr/src/tensorrt/bin/trtexec --avgRuns=100 --uffInput=input_image,3,1024,1024 --output=mrcnn_detection --fp16 --batch=1 --iterations=60 --output=cls_prob --useSpinWait --useDLACore=1 --allowGPUFallback --uff=/usr/src/tensorrt/samples/sampleUffMaskRCNN/converted/mrcnn_nchw.uff
&&&& RUNNING TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --avgRuns=100 --uffInput=input_image,3,1024,1024 --output=mrcnn_detection --fp16 --batch=1 --iterations=60 --output=cls_prob --useSpinWait --useDLACore=1 --allowGPUFallback --uff=/usr/src/tensorrt/samples/sampleUffMaskRCNN/converted/mrcnn_nchw.uff
[I] avgRuns: 100
[I] uffInput: input_image,3,1024,1024
[I] output: mrcnn_detection
[I] fp16
[I] batch: 1
[I] iterations: 60
[I] output: cls_prob
[I] useSpinWait
[I] useDLACore: 1
[I] allowGPUFallback
[I] uff: /usr/src/tensorrt/samples/sampleUffMaskRCNN/converted/mrcnn_nchw.uff
[E] [TRT] UffParser: Unsupported number of graph 0
[E] Engine could not be created
[E] Engine could not be created
&&&& FAILED TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --avgRuns=100 --uffInput=input_image,3,1024,1024 --output=mrcnn_detection --fp16 --batch=1 --iterations=60 --output=cls_prob --useSpinWait --useDLACore=1 --allowGPUFallback --uff=/usr/src/tensorrt/samples/sampleUffMaskRCNN/converted/mrcnn_nchw.uff
`

Thanks

**Comment by rmccorm4** [comment]
Hi @manga22,

Just a guess, but you might need to specify the necessary plugins for the model with `--plugins <path/to/plugin.so file>`

```
$ trtexec --help
...
  --plugins                   Plugin library (.so) to load (can be specified multiple times)
```

**Comment by rmccorm4** [comment]
Closing, I'll reopen if you're still having issues
