### ISSUE TITLE
Failed to build on DRIVE AGX ORIN

### ISSUE THREAD

**Issue by white-galaxy** [NVIDIA/TensorRT#2511]
I install build via below commad:

cmake --DTRT_OUT_DIR=/home/nvidia/TensorRT/build/out -DTRT_PLATFORM_ID=aarch64 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DTRT_LIB_DIR=/lib/aarch64-linux-gnu/ ..

but got below error:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDNN_LIB
    linked by target "nvinfer_plugin" in directory /home/nvidia/TensorRT/plugin
    linked by target "sample_algorithm_selector" in directory /home/nvidia/TensorRT/samples/sampleAlgorithmSelector
    linked by target "sample_char_rnn" in directory /home/nvidia/TensorRT/samples/sampleCharRNN
    linked by target "sample_dynamic_reshape" in directory /home/nvidia/TensorRT/samples/sampleDynamicReshape
    linked by target "sample_fasterRCNN" in directory /home/nvidia/TensorRT/samples/sampleFasterRCNN
    linked by target "sample_googlenet" in directory /home/nvidia/TensorRT/samples/sampleGoogleNet
    linked by target "sample_int8" in directory /home/nvidia/TensorRT/samples/sampleINT8
    linked by target "sample_int8_api" in directory /home/nvidia/TensorRT/samples/sampleINT8API
    linked by target "sample_mnist" in directory /home/nvidia/TensorRT/samples/sampleMNIST
    linked by target "sample_mnist_api" in directory /home/nvidia/TensorRT/samples/sampleMNISTAPI
    linked by target "sample_nmt" in directory /home/nvidia/TensorRT/samples/sampleNMT
    linked by target "sample_onnx_mnist" in directory /home/nvidia/TensorRT/samples/sampleOnnxMNIST
    linked by target "sample_reformat_free_io" in directory /home/nvidia/TensorRT/samples/sampleReformatFreeIO
    linked by target "sample_ssd" in directory /home/nvidia/TensorRT/samples/sampleSSD
    linked by target "sample_uff_fasterRCNN" in directory /home/nvidia/TensorRT/samples/sampleUffFasterRCNN
    linked by target "sample_uff_maskRCNN" in directory /home/nvidia/TensorRT/samples/sampleUffMaskRCNN
    linked by target "sample_uff_mnist" in directory /home/nvidia/TensorRT/samples/sampleUffMNIST
    linked by target "sample_uff_plugin_v2_ext" in directory /home/nvidia/TensorRT/samples/sampleUffPluginV2Ext
    linked by target "sample_uff_ssd" in directory /home/nvidia/TensorRT/samples/sampleUffSSD
    linked by target "sample_onnx_mnist_coord_conv_ac" in directory /home/nvidia/TensorRT/samples/sampleOnnxMnistCoordConvAC
    linked by target "trtexec" in directory /home/nvidia/TensorRT/samples/trtexec
TENSORRT_LIBRARY_INFER
    linked by target "nvonnxparser_static" in directory /home/nvidia/TensorRT/parsers/onnx
    linked by target "nvonnxparser" in directory /home/nvidia/TensorRT/parsers/onnx
TENSORRT_LIBRARY_INFER_PLUGIN
    linked by target "nvonnxparser_static" in directory /home/nvidia/TensorRT/parsers/onnx
    linked by target "nvonnxparser" in directory /home/nvidia/TensorRT/parsers/onnx

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/TensorRT/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/TensorRT/build/CMakeFiles/CMakeError.log".

So I want to konw how to build on DRIVE AGX ORIN

**Comment by zerollzeng** [comment]
@kevinch-nv ^ ^

**Comment by nvpohanh** [comment]
Where did you install CUDNN? After you install CUDNN, you can then add `-DCUDNN_LIB=/path/to/cudnn/lib`

**Comment by white-galaxy** [comment]
> Where did you install CUDNN? After you install CUDNN, you can then add `-DCUDNN_LIB=/path/to/cudnn/lib`

@nvpohanh  CUDNN and TensorRT are pre-install by Drive OS.
I tried below command,
`cmake -DTRT_LIBPATH=/home/nvidia/TensorRT/ --DTRT_OUT_DIR=./out -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DTRT_PLATFORM_ID=aarch64 -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/cmake_aarch64.toolchain -DCUDA_VERSION=11.4 -DTRT_LIB_DIR=/lib/aarch64-linux-gnu/ -DCUDNN_LIB=/lib/aarch64-linux-gnu/libcudnn.so -DTENSORRT_LIBRARY_INFER=/lib/aarch64-linux-gnu/libnvinfer.so -DTENSORRT_LIBRARY_INFER_PLUGIN=/lib/aarch64-linux-gnu/libnvinfer_plugin.so ..`
And got another error.
`Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
Compiler: /usr/local/cuda/bin/nvcc 
Build flags: -I/usr/local/cuda-11.4/targets/aarch64-linux/include;-Xcompiler="-fPIC;"
Id flags:  -v;--keep;--keep-dir;tmp;-ccbin=/usr/bin/aarch64-linux-gnu-g++

The output was:
1
nvcc fatal   : Stray '"' character


Performing C++ SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_99126/fast && /usr/bin/make -f CMakeFiles/cmTC_99126.dir/build.make CMakeFiles/cmTC_99126.dir/build
make[1]: Entering directory '/home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_99126.dir/src.cxx.o
/usr/bin/aarch64-linux-gnu-g++    -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -DCMAKE_HAVE_LIBC_PTHREAD   -std=c++14 -o CMakeFiles/cmTC_99126.dir/src.cxx.o -c /home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_99126
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_99126.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-g++  -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_99126.dir/src.cxx.o  -o cmTC_99126 
/usr/bin/ld: CMakeFiles/cmTC_99126.dir/src.cxx.o: in function `main':
src.cxx:(.text+0x48): undefined reference to `pthread_create'
/usr/bin/ld: src.cxx:(.text+0x50): undefined reference to `pthread_detach'
/usr/bin/ld: src.cxx:(.text+0x5c): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_99126.dir/build.make:87: cmTC_99126] Error 1
make[1]: Leaving directory '/home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_99126/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_e3bc8/fast && /usr/bin/make -f CMakeFiles/cmTC_e3bc8.dir/build.make CMakeFiles/cmTC_e3bc8.dir/build
make[1]: Entering directory '/home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_e3bc8.dir/CheckFunctionExists.cxx.o
/usr/bin/aarch64-linux-gnu-g++    -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -DCHECK_FUNCTION_EXISTS=pthread_create   -std=c++14 -o CMakeFiles/cmTC_e3bc8.dir/CheckFunctionExists.cxx.o -c /home/nvidia/TensorRT/build/CMakeFiles/CheckLibraryExists/CheckFunctionExists.cxx
Linking CXX executable cmTC_e3bc8
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e3bc8.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-g++  -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_e3bc8.dir/CheckFunctionExists.cxx.o  -o cmTC_e3bc8  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_e3bc8.dir/build.make:87: cmTC_e3bc8] Error 1
make[1]: Leaving directory '/home/nvidia/TensorRT/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_e3bc8/fast] Error 2
`
Seemingly it need -lpthreads (not -lpthread), however, Orin Drive OS on have /lib/aarch64-linux-gnu/libpthread.so.0.
