### ISSUE TITLE
demodiffusion - fMHA_0: could not find any supported formats consistent with input/output data types

### ISSUE THREAD

**Issue by harishprabhala** [NVIDIA/TensorRT#2512]
## demodiffusion engine creation fails

Trying to reproduce the same steps as demodiffusion on the same container mentioned in the repo.

## Environment 

**TensorRT Version**: 8.5.1.7
**NVIDIA GPU**: 2080Ti
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

![WhatsApp Image 2022-11-30 at 2 44 52 PM](https://user-images.githubusercontent.com/26444096/204760593-ebb4f80a-57d0-4880-8e8a-d58717158969.jpeg)

**Comment by harishprabhala** [comment]
Tagging @rajeevsrao

**Comment by jike-algorithm-zhangxiao** [comment]
fMHA plugin only support SM  > 80 device

**Comment by harishprabhala** [comment]
So, there is no support to RTX 20xx, T4, V100 GPUs then? Will you be adding support?

**Comment by jike-algorithm-zhangxiao** [comment]
sorry, I am not tensorrt developer, i'm just a product user

**Comment by rajeevsrao** [comment]
The new fMHA plugins currently only support Ampere GPUs and RTX4090. Support for other SMs is TBD at the moment.

**Comment by rajeevsrao** [comment]
@harishprabhala SM75 support is added in this branch: [release/8.5-demodiffusion](https://github.com/NVIDIA/TensorRT/tree/release/8.5-demodiffusion) (will be merged to release/8.5 in a few days). Give it a spin and let us know!

**Comment by harishprabhala** [comment]
> @harishprabhala SM75 support is added in this branch: [release/8.5-demodiffusion](https://github.com/NVIDIA/TensorRT/tree/release/8.5-demodiffusion) (will be merged to release/8.5 in a few days). Give it a spin and let us know!

Hi Rajeev. Initial testing looks good. But there was one hiccup. After the unet.plan file was created, it showed out of memory error to create the next one, vae.plan. When I ran the compiler again, it could then create the vae.plan. Looks like a memory flush is needed between each plan creation or some other technique to manage the memory. This is on 2080Ti GPU.

![Screenshot from 2022-12-03 09-11-31](https://user-images.githubusercontent.com/26444096/205421409-0931433c-a808-4e59-b928-cb5a0b487513.png)

**Comment by rajeevsrao** [comment]
> > @harishprabhala SM75 support is added in this branch: [release/8.5-demodiffusion](https://github.com/NVIDIA/TensorRT/tree/release/8.5-demodiffusion) (will be merged to release/8.5 in a few days). Give it a spin and let us know!
> 
> Hi Rajeev. Initial testing looks good. But there was one hiccup. After the unet.plan file was created, it showed out of memory error to create the next one, vae.plan. When I ran the compiler again, it could then create the vae.plan. Looks like a memory flush is needed between each plan creation or some other technique to manage the memory. This is on 2080Ti GPU.
> 
> ![Screenshot from 2022-12-03 09-11-31](https://user-images.githubusercontent.com/26444096/205421409-0931433c-a808-4e59-b928-cb5a0b487513.png)

Thanks for sharing that - we are evaluating options to help reduce the GPU memory usage during engine builds. I will reply here once we have further guidance.

**Comment by harishprabhala** [comment]
@rajeevsrao The number of output images per prompt is only 1 for now. But there is a --num-images flag, which when changed to >1, still gives only one image as output. Will you be adding support to multiple images per prompt?

**Comment by rajeevsrao** [comment]
> @rajeevsrao The number of output images per prompt is only 1 for now. But there is a --num-images flag, which when changed to >1, still gives only one image as output. Will you be adding support to multiple images per prompt?

@harishprabhala you can achieve the same by repeating the prompt using the `--repeat-prompt` switch (generates separate images unless seed is specifies). `--num-images` allows generating the same image multiple times (identical to num-repeats with seed), and is fixed to 1 - we will remove it.

**Comment by harishprabhala** [comment]
Hi @rajeevsrao. Any update on the memory management issue when creating multiple engine files?
