### ISSUE TITLE
Faster way to handle duplicated OptimizationProfiles?

### ISSUE THREAD

**Issue by mozooon** [NVIDIA/TensorRT#2516]
Hello!

I am working on dynamic shape model with multiple contexts which run concurrently.
The dynamic range (min/opt/max) is the same for all contexts, so I added the same OptimizationProfile N times to the BuilderConfig.

```python
 profile = builder.create_optimization_profile()
 profile.set_shape(name, shape_min, shape_opt, shape_max)
 
 config = builder.create_builder_config()
 for _ in range(num_profiles):
     config.add_optimization_profile(profile)
```

I found that the profiles are built sequentially, is there any optimized way to do this?
It would be great if I can make duplicated profile from existing one in the serialized model.

I am using TensorRT 8.2.1.8 now.

Thank you in advance!

**Comment by nvpohanh** [comment]
currently, this is the only way to do this. In TRT, we have the so-called "TimingCache", so building the second profile should not take as long as building the first profile. 

We are currently working on profile-sharing context feature (i.e. allowing multiple contexts to share the same profile) and it should be ready in next or next-next TRT version.

**Comment by mozooon** [comment]
I see, thank you very much!
