### ISSUE TITLE
When the same model is loaded with different weights, different performance is obtained using trtexec

### ISSUE THREAD

**Issue by mxjecho** [NVIDIA/TensorRT#2517]
## command:

**trtexec --onnx=model.onnx --shapes=input:1x3x299x299**

## Issue:
I got different' Throughput' numbers when the same model is loaded with different weights. And the difference is not negligible.
For example, for Inception V3:
a) random initialization - Throughput: 220.133 qps
b) load pre-trained weights- Throughput: 208.012 qps

I'm curious as to why this is. Is this a normal phenomenon?

Is there a relationship between throughput and FPS?

**Comment by nvpohanh** [comment]
It is possible. For example, if all the weights are zeros, then many bits in the DRAM will be 0s and do not need to toggle between 0s and 1s. This generates less heat, allowing GPU to run at a higher clock frequency under the same power capacity.

To verify this, could you try loading weights with all zeros and see if the throughput increases?

**Comment by mxjecho** [comment]
Yes, when I load all-0 and all-1 weights, the throughput increases to 225. 
BTW, when the input is images, is throughput equal to FPS?

**Comment by nvpohanh** [comment]
Well, it depends on the ONNX input shape. In your case, the input shape is 1x3x299x299, so yes, throughput is equal to FPS.

**Comment by mxjecho** [comment]
Got it. Thanks a lot.
