### ISSUE TITLE
layer not fusion when use trtexec

### ISSUE THREAD

**Issue by lk137095576** [NVIDIA/TensorRT#2518]
I try trtexec with resnet50.onnx  int8 or fp16.the cmd like:
python process_engine.py resnet50.onnx output/  fp16 shapes=input:1x3x224x224 profilingVerbosity=detailed --monitor -b -p -d 
python process_engine.py resnet50.onnx output/  int8  shapes=input:1x3x224x224 profilingVerbosity=detailed --monitor -b -p -d 

txtexec  resnet50.onnx    --shapes=input:1x3x224x224  --int8
I got result, but at the start of resnet50: conv  bn maxpooling:
int8  get Conv_0 + Relu_1 + MaxPool_2
fp16 get Conv_0 + Relu_1  ,      Maxpool_2 in another layer
why int8 fused all , fp16 not:
I read the doc: [https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#fusion-types](url)
_Convolution and Pooling
The Convolution and Pooling layers **must have the same precision**. The Convolution layer may already have a fused activation operation from a previous fusion._
I don't realy understand THE SAME PRECISION?

**Comment by zerollzeng** [comment]
It's expected. the reason why you see this is that TensorRT only supports ConvActPool fusion for INT8(try to grep ConvActPoolFusion in the INT8 verbose log you should find it), and some fusions may have requirements for precision. But I don't know why we don't support the ConvActPool for FP16 too, @nvpohanh may know more about it.

**Comment by lk137095576** [comment]
> 

Yes，I just want to know why Fp16 not support ConvActPool, @nvpohanh , precision matter? speed matter? or it may support in future version?

**Comment by nvpohanh** [comment]
We didn't have bandwidth to develop the ConvActPool FP16 kernels

**Comment by lk137095576** [comment]
> 

In other words, ConvActPool FP16 is feasible in theory, but limited by GPU bandwidth?

**Comment by zerollzeng** [comment]
I think Po-Han meant engineer bandwidth.

**Comment by lk137095576** [comment]
> I think Po-Han meant engineer bandwidth.

haha. I get it
