### ISSUE TITLE
exporting half() model having torch.clamp() -> causes zeroed output

### ISSUE THREAD

**Issue by jedivova** [NVIDIA/TensorRT#2521]
## Description

My model has few torch.clamp() func in it. 
Exporting half-precision pytorch model (via path Pytorch-> ONNX -> TRT) then output of my model is zeroed.
Exporting non-halfed model work as expected.

## Environment

**TensorRT Version**: 8.5.1.7
**NVIDIA GPU**: NVIDIA GeForce RTX 3080 Ti Laptop GPU
**NVIDIA Driver Version**: 515.65.01
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0.163-1+cuda11.8
**Operating System**: ubuntu 20.4
**Python Version (if applicable)**: 3.8.10
**PyTorch Version (if applicable)**: 1.12.1+cu116

## Relevant Files

github repo: https://github.com/jedivova/trt_export_torch_clamp_bug

## Steps To Reproduce

just launch the code from jupyter notebook.
You can change "HALF=True" to False -> output will not be zeroed (as expected).

**Comment by zerollzeng** [comment]
Hi I tried to export the onnx with you code and I met `RuntimeError: "avg_pool2d" not implemented for 'Half'`. maybe env issue on my side, can you upload the FP16 and FP32 onnx in here so that I can take a quick check? thanks!

**Comment by jedivova** [comment]
Hello! I've uploaded onnx models to [git_repo](https://github.com/jedivova/trt_export_torch_clamp_bug) , please check.

**Comment by zerollzeng** [comment]
I can reproduce the issue, will take a look further.

Thanks for reporting this.

**Comment by zerollzeng** [comment]
This has been fixed in the latest branch, and should be in the next release. closed

**Comment by zerollzeng** [comment]
This has been fixed in the latest branch and should be in the next release. closed.
