### ISSUE TITLE
what is  '+'   '||'   ','  in trt name

### ISSUE THREAD

**Issue by lk137095576** [NVIDIA/TensorRT#2525]
I profile engine by process_engine.py ,I get the name of fused node like :
`Conv_8 + Add_9 + Relu_10    
`Conv_68 || Conv_72"`
 `Conv_531 + PWN(LeakyRelu_532)` 

I Guess  "+ " mean fuse ,  but I don't understand   **'||'   ','  'pwd'**  , what is it?

**Comment by zerollzeng** [comment]
"+" means layer fused by graph optimization, PWN means "point-wise node". but I'm not sure about the "||". @pranavm-nvidia can you shed some light here? Thanks!

**Comment by pranavm-nvidia** [comment]
The `||` indicates horizontal fusion while `+` is vertical fusion.

**Comment by lk137095576** [comment]
> The `||` indicates horizontal fusion while `+` is vertical fusion.

Thanks，I get.
