### ISSUE TITLE
How to specify priority for streams used by myelin inside TensorRT

### ISSUE THREAD

**Issue by lai-kevin-lai** [NVIDIA/TensorRT#2528]
## Description

We have a multi model environment, they infer on same gpu concurrently but have different priority

For model without myelin, this priority can be specific by enqueueV2 with a pre-created stream
TensorRT then run ops on this stream, with priority we want

But for model with myelin, ops may also run on internal streams managed by myelin
these internal streams seem create with default priority, and seems no public API can change that

So, do we have any method to help priority works for model with myelin?
or can we disable myelin concurrency support, to run ops all on the pre-created stream?

## Environment

**TensorRT Version**: 8.4.3
**NVIDIA GPU**: A10
**NVIDIA Driver Version**: 470.82.01
**CUDA Version**: 11.4
**Operating System**: Ubuntu 20.04

**Comment by zerollzeng** [comment]
@zhenhuaw-me @nvpohanh ^ ^

**Comment by nvpohanh** [comment]
It is not possible with TRT 8.4, but this is on the roadmap. In the best case, this control will be allowed in TRT 8.6.

**Comment by lai-kevin-lai** [comment]
great, looking forward to it

**Comment by zerollzeng** [comment]
Any further questions? Can we close this?

**Comment by lai-kevin-lai** [comment]
ok
