### ISSUE TITLE
Error Code 4: Internal Error (Layer xxx failed DriveOS 6.0 safety scope validation)

### ISSUE THREAD

**Issue by hanin97** [NVIDIA/TensorRT#2533]
Hi,
I have written a plugin based on TensorRT-8.2.3, after building and replacing lib* and trtexec, i ran `trtexec --onnx=my.onnx --restricted`, Error Code 4: Internal Error (Layer xxx failed DriveOS 6.0 safety scope validation) raised. I want to known what `safety scope validation` do and how to fix it.
Thanks!

**Comment by zerollzeng** [comment]
You are using safety right? some layers can not be running under safety due to safety limitations. does xxx mean your plugin?

**Comment by zerollzeng** [comment]
If yes then you should use IPluginV2IOExt, are you using the IPluginV2DynamicExt?

**Comment by hanin97** [comment]
Yes, xxx means my plugin, and I'm using IPluginV2DynamicExt. As you suggested, using IPluginV2IOExt works. Thanks.
