### ISSUE TITLE
Does crossAttentionPlugin support seq_len is 1500?

### ISSUE THREAD

**Issue by jike-algorithm-zhangxiao** [NVIDIA/TensorRT#2541]
when i use a crossAttentionPlugin called 'fMHCA' to implement a cross attention process:
q is (1, 1, 12, 64)
kv is (1, 1500, 12, 2, 64)
plugin's output is error!
but when i set 
q is (1, 1, 12, 64)
kv is (1, 4, 12, 2, 64)
plugin's output is correct!
how to explain that? and what the maximize seq length to get the correct answer?

**Comment by nekorobov** [comment]
Hi, the seqlen for KV is limited to 128. It explains the failure in the first case (1500 > 128) and success in the second (4 < 128).
