### ISSUE TITLE
EnqueueV3 example

### ISSUE THREAD

**Issue by eduardatmadenn** [NVIDIA/TensorRT#2558]
Hi, as I understand it, EnqueueV2 is deprecated. At the same time, I cannot seem to find a simple working example that uses EnqueueV3. Can anyone help with this? Thank you

**Comment by azhurkevich** [comment]
@pranavm-nvidia Maybe you can help out with this?

**Comment by eduardatmadenn** [comment]
@azhurkevich @zerollzeng thank you

**Comment by cyrusbehr** [comment]
Feel free to also check out my [project](https://github.com/cyrusbehr/tensorrt-cpp-api) which demonstrates the use of `EnqueueV3` and is easier to follow than the NVIDIA example linked above. As of right now, use of `EnqueueV3` is only in the `v3.0` branch, available [here](https://github.com/cyrusbehr/tensorrt-cpp-api/tree/v3.0), but I will be merging into main once I finish some other upgrades.

**Comment by eduardatmadenn** [comment]
That's great, tyvm
