### ISSUE TITLE
Depreciated MNIST Sample

### ISSUE THREAD

**Issue by Kinshukg04** [NVIDIA/TensorRT#256]
## Description
In the new release(6.0.1) sampleMNIST has been depreciated as the PGM files for the MNIST samples have been removed. I wasn't able to find the steps to generate these images in this repo. But there is a script: generate_pgms.py in the data folder which I believe is for generating the PGM files.  
How can we generate the pgm files for this sample?

## Environment

**TensorRT Version**: 6.0.1.5 
**GPU Type**: Nvidia 1060 Max-Q
**Nvidia Driver Version**:  440.36
**CUDA Version**:  10.1
**CUDNN Version**: 7.6
**Operating System + Version**: Ubuntu 18.04
**Python Version**: 3.6.9

**Comment by rmccorm4** [comment]
Hi @Kinshukg04,

This depecration was noted in the "Deprecated Features" section on the TRT 6.0 release notes here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html

> The PGM files for the MNIST samples have been removed. A script, called generate_pgms.py (or download_pgms.py for CUDA 10.2), has been provided in the samples/mnist/data directory to generate the images using the dataset.

You need to download the mnist dataset train data (or val/test) + labels. Then you can run the scri0t and pass the paths to the data/labels/output_dir. 

For example:
```
# This will generate one .pgm file for each label 0, 1, 2, 3, ..., 9 to the specified output directory
python generate_pgms.py -d /opt/tensorrt/data/mnist/train-images-idx3-ubyte -l /opt/tensorrt/data/mnist/train-labels-idx1-ubyte -o /opt/tensorrt/data/mnist
```

Then you should be able to specify the above output directory as an argument to the sampleMNIST binary, and it will randomly select a digit 0-9 to read (`<digit>.pgm`) and classify: https://github.com/NVIDIA/TensorRT/blob/daacf1537c9310ab9d4a7e8a7b33cb3739289a32/samples/opensource/sampleMNIST/sampleMNIST.cpp#L179

For example:
```
# Pass the path to the directory containing the *.pgm files
./sample_mnist -d /opt/tensorrt/data/mnist
```

Related to: https://github.com/NVIDIA/TensorRT/issues/165

**Comment by wavesCHJ** [comment]
Hi, @rmccorm4 , I can not find generate_pgms.py in the samples/mnist/data directory . In the whole TensorRT project, I also can't find the generate_pgms.py. Can you tell me where can i find that ? Thanks!

**Comment by rmccorm4** [comment]
Hi @wavesCHJ,

I'm not at a computer to look into it for TRT7 as I'm on holiday - it may have been missed. But if you need it now, I think you can copy it out of one of the earlier releases, you could do that easily with a docker container from NGC. Something like this:

```
$ nvidia-docker run -it -v ${PWD}:/mnt nvcr.io/nvidia/tensorrt:19.10-py3
$ cp /opt/tensorrt/samples/data/mnist/generate_pgms.py /mnt
$ exit
# Now the file should be in your current directory
```

The path may not be totally right, just guessing off the top of my head in case you're in a hurry.

**Comment by wavesCHJ** [comment]
Hi @rmccorm4 , thank you very much for your reply!
By running the download_pgms.py in the /TensorRT-7.0.0.11/data/mnist, I can  already get the *.pgm files.

**Comment by yjiangling** [comment]
> Hi @Kinshukg04,
> 
> This depecration was noted in the "Deprecated Features" section on the TRT 6.0 release notes here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html
> 
> > The PGM files for the MNIST samples have been removed. A script, called generate_pgms.py (or download_pgms.py for CUDA 10.2), has been provided in the samples/mnist/data directory to generate the images using the dataset.
> 
> You need to download the mnist dataset train data (or val/test) + labels. Then you can run the scri0t and pass the paths to the data/labels/output_dir.
> 
> For example:
> 
> ```
> # This will generate one .pgm file for each label 0, 1, 2, 3, ..., 9 to the specified output directory
> python generate_pgms.py -d /opt/tensorrt/data/mnist/train-images-idx3-ubyte -l /opt/tensorrt/data/mnist/train-labels-idx1-ubyte -o /opt/tensorrt/data/mnist
> ```
> 
> Then you should be able to specify the above output directory as an argument to the sampleMNIST binary, and it will randomly select a digit 0-9 to read (`<digit>.pgm`) and classify:
> 
> https://github.com/NVIDIA/TensorRT/blob/daacf1537c9310ab9d4a7e8a7b33cb3739289a32/samples/opensource/sampleMNIST/sampleMNIST.cpp#L179
> 
> For example:
> 
> ```
> # Pass the path to the directory containing the *.pgm files
> ./sample_mnist -d /opt/tensorrt/data/mnist
> ```
> 
> Related to: #165

Sorry, But when I run the generate_pgms.py to download the test data, It gives the following error:
**FileNotFoundError: [Errno 2] No such file or directory: '/media/huaxin/tcl1/asr//yujiangling/TensorRT/data/mnist/train-images-idx3-ubyte'
**
What' wrong？ How Can I solve it? Thank U.

**Comment by yjiangling** [comment]
> Hi @Kinshukg04,
> 
> This depecration was noted in the "Deprecated Features" section on the TRT 6.0 release notes here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html
> 
> > The PGM files for the MNIST samples have been removed. A script, called generate_pgms.py (or download_pgms.py for CUDA 10.2), has been provided in the samples/mnist/data directory to generate the images using the dataset.
> 
> You need to download the mnist dataset train data (or val/test) + labels. Then you can run the scri0t and pass the paths to the data/labels/output_dir.
> 
> For example:
> 
> ```
> # This will generate one .pgm file for each label 0, 1, 2, 3, ..., 9 to the specified output directory
> python generate_pgms.py -d /opt/tensorrt/data/mnist/train-images-idx3-ubyte -l /opt/tensorrt/data/mnist/train-labels-idx1-ubyte -o /opt/tensorrt/data/mnist
> ```
> 
> Then you should be able to specify the above output directory as an argument to the sampleMNIST binary, and it will randomly select a digit 0-9 to read (`<digit>.pgm`) and classify:
> 
> https://github.com/NVIDIA/TensorRT/blob/daacf1537c9310ab9d4a7e8a7b33cb3739289a32/samples/opensource/sampleMNIST/sampleMNIST.cpp#L179
> 
> For example:
> 
> ```
> # Pass the path to the directory containing the *.pgm files
> ./sample_mnist -d /opt/tensorrt/data/mnist
> ```
> 
> Related to: #165

It seems that we need to download the MNIST data manually, and the use gunzip to unzip the file to get train-labels-idx1-ubyte file. Finally, run generate_pgms.py file to get the picture file.

**Comment by pepijnko** [comment]
@rmccorm4 I am trying to run the download_pgms.py file, but I get an HTTP Error 403. I modified the file so that you can download the .pgms files. 

New main()

**Comment by pepijnko** [comment]
`def main():
    parser = argparse.ArgumentParser(description="Extracts 10 PGM files from the MNIST dataset", formatter_class$
    parser.add_argument("-o", "--output", help="Path to the output directory.", default=os.getcwd())
    args, _ = parser.parse_known_args()

    user_agent = 'Mozilla/5. (Windows; U; Windows NT 5.1; en-US; rv1.9.0.7) Gecko/2009021910 Firefox/3.0.7'
    url = "http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz"
    url1 = "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz"
    headers={'User-Agent':user_agent,}

    request=urllib.request.Request(url,None,headers)
    with urllib.request.urlopen(request) as res:
        data = load_mnist_data(gzip.decompress(res.read()))

    request1=urllib.request.Request(url1,None,headers)
    with urllib.request.urlopen(request1) as res:
        labels = load_mnist_labels(gzip.decompress(res.read()))

    output_dir = args.output

    # Find one image for each digit.
    for i in range(10):
        index = labels.index(i)
        image = Image.fromarray(data[index], mode="L")
        path = os.path.join(output_dir, "{:}.pgm".format(i))
        image.save(path)

if __name__ == '__main__':
    main()`

**Comment by fei4xu** [comment]
[mnist_0-9.pgm.zip](https://github.com/NVIDIA/TensorRT/files/7271166/mnist_0-9.pgm.zip)
to make life easier, the 0-9.pgm files (result or running `python download_pgms.py`) are uploaded here.
