### ISSUE TITLE
what is  the true bs of calibrator when i use dynamic shape in ptq int8?

### ISSUE THREAD

**Issue by tigerzjh** [NVIDIA/TensorRT#2561]
## Environment

**TensorRT Version**: 8.4
**NVIDIA GPU**: P40
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#int8-calib-dynamic-shapes
https://github.com/meituan/YOLOv6/blob/main/deploy/TensorRT/calibrator.py

## Steps To Reproduce

i code below to set dynamic batch

profile = builder.create_optimization_profile()
c, h, w = 3, 640, 640
profile.set_shape("images", (1, c, h, w), (4, c, h, w), (8, c, h, w))  # 这里的输入名可以在onnx 文件看到
config.add_optimization_profile(profile)

i dont use config.set_calibration_profile(profile), so the optimization_profile will be used as calibration_profile. when i build trt int8 calibrator.cache file, i load file with bs=128 refer https://github.com/meituan/YOLOv6/blob/main/deploy/TensorRT/calibrator.py

it will still work,  but the true bs of calibrator is 128 or 4?

**Comment by zerollzeng** [comment]
Per https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#int8-calib-dynamic-shapes
```
To run INT8 calibration for a network with dynamic shapes, a calibration optimization profile must be set. Calibration is performed using kOPT values of the profile. Calibration input data size must match this profile.
```

**Comment by tigerzjh** [comment]
@zerollzeng i have seen this developer guide, as it say the infer bs for the example before will be 4, even though the dalaloder bs=128, and it still run well. so, i dont understand the bs can be set difference between  set_calibration_profile and  add_optimization_profile?
profile.set_shape("images", (1, c, h, w), (4, c, h, w), (8, c, h, w)) # 这里的输入名可以在onnx 文件看到
config.add_optimization_profile(profile)
profile.set_shape("images", (1, c, h, w), (128, c, h, w), (128, c, h, w)) # 这里的输入名可以在onnx 文件看到
config. set_calibration_profile(profile)
then the calibrate will use bs 128, and the engine finally bs is  (1, c, h, w), (4, c, h, w), (8, c, h, w))?

**Comment by ttyio** [comment]
>> bs can be set difference between set_calibration_profile and add_optimization_profile?
the int8 engine build has 2 pass, first pass is the calibration, the batch size in calibrator should match the set_calibration_profile, the second pass is the int8 engine build pass, and the batch size is configured from add_optimization_profile.

Closing this old thread and thanks all!
