### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by nrakltx** [NVIDIA/TensorRT#2567]
To reproduce, run the following sample:
```Python
import tensorrt
tensorrt.nptype(tensorrt.DataType.HALF)
```
I have done some research and reached the following conclusions:
[TensorRT/python/packaging/tensorrt/__init__.py:L166](https://github.com/NVIDIA/TensorRT/blob/ef7713ca67435690f0b28dc9a50ee4021ae3651d/python/packaging/tensorrt/__init__.py#L166) calls `__getattr__` on `np`, looking for `np.bool`. This raises a warning and then an error, originating from [these lines](https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/__init__.py#L266) in `numpy`'s source code.

Either L166 needs to be changed to regular `bool` (or `np.bool_`?), or there should be an upper bound on the package's `numpy` dependency. Note this occurs only with `numpy>=1.24`.

**Comment by zerollzeng** [comment]
dup of https://github.com/NVIDIA/TensorRT/issues/2557

You can use numpy < 1.24 or apply the fix to the source code.

**Comment by nrakltx** [comment]
whoops didn't notice its a dup, sorry!

**Comment by grizzlybearg** [comment]
downgrading to numpy 1.23 still doesn't work



> dup of #2557
> 
> You can use numpy==1.23 or apply the fix to the source code.

**Comment by MahdiehEbrahimii** [comment]
I have same problem but because of version of theano I can't use numpy 1.23 and I just can use numpy 1.24.1 , What should I do? Thak you very much
@zerollzeng

**Comment by zerollzeng** [comment]
@MahdiehEbrahimii   You can rebuild the python package as I said in https://github.com/NVIDIA/TensorRT/issues/2557. Thanks!

**Comment by nayariml** [comment]
> dup of #2557
> 
> You can use numpy==1.23 or apply the fix to the source code.

I was having the same issue to call **tf_agents.**
So, I reinstalled numpy 1.24 and installed numpy 1.23, and it worked!

**Comment by MahdiehEbrahimii** [comment]
@zerollzeng @nayariml  Its worked thank you very much
