### ISSUE TITLE
mAPs of TensorRT engine are higher than mAPs of TF ckpt

### ISSUE THREAD

**Issue by kimwj94** [NVIDIA/TensorRT#2568]
## Description

I compared mAPs between TF ckpt and TensorRT engine (FP32).
But I can't figure out why mAPs of the TensorRT engine are higher.
Why TRT engine is better than TF ckpt?

| nms score thresh | 0.01  | 0.2   | 0.4   | 0.6   | 0.8   | 1.0 |
|-----------------|-------|-------|-------|-------|-------|-----|
| TensorFlow ckpt (FP32)            | 0.401 | 0.378 | 0.328 | 0.249 | 0.129 | 0.0 |
| TensorRT engine (FP32)            | 0.4 | 0.381 |0.334  |0.268  |0.195  |0.0  |

- Model: **efficientdet-d1**
- Dataset: **COCO 2017** (val2017)
- I changed nms score thresholds of TF ckpt using argument `hparams="nms_configs.score_thresh=0.01"` in [here](https://github.com/google/automl/tree/master/efficientdet#7-eval-on-coco-2017-val-or-test-dev).
- I made different nms score thresholds of ONNX models using argument `--nms_threshold [...]`. I checked each onnx models have different nms score thresholds by using Netron. And then, I converted each onnx models to TRT engines with precision FP32 using below commands.
  ```
  python3 build_engine.py \
    --onnx /path/to/model_${THRESHOLD}.onnx \
    --engine /path/to/engine_${THRESHOLD}.trt \
    --precision fp32
  ```
- I wrote values from ` Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ]`

## Environment

**TensorRT Version**: 8.5.1.7

**Comment by zerollzeng** [comment]
I think it's expected if the MAP is slightly different between TensorRT and other frameworks even under FP32. Because FP32 will also introduce numerical errors. different compute order(A+B+C != A+(B+C)) and rounding method will lead to some numerical difference. but if the accuracy is good then it's not a bug.

**Comment by kimwj94** [comment]
Thank you for answer!
