### ISSUE TITLE
How to compare precision layer by layer through the python api of Polygraphy

### ISSUE THREAD

**Issue by sterben25** [NVIDIA/TensorRT#2571]
I use the polygraphy to compare the precision of trt model with it's  onnx version, here is the code.
```python
onnx_runner = OnnxrtRunner(SessionFromOnnx(_onnx_model_path))
trt_runner = TrtRunner(engine)
run_results = Comparator.run([onnx_runner, trt_runner])
accuracy = Comparator.compare_accuracy(run_results)
```
I want to compare the precision layer by layer, but the run_results only has the final output,  how can I get the precision for each layer through the python api?

**Comment by zerollzeng** [comment]
`--mark all`? but it's not a good practice since it will break all TRT fusion. cc @pranavm-nvidia

**Comment by pranavm-nvidia** [comment]
Right, you would be able to use `ModifyNetworkOutputs` and `ModifyOnnxOutputs` with the special constant `constants.MARK_ALL` to modify the TRT network and ONNX outputs respectively. But as @zerollzeng mentioned, this would block fusions. 

You can see an example script for this with:
```bash
polygraphy run model.onnx --trt --onnxrt --trt-outputs mark all --onnx-outputs mark all --gen -
```

**Comment by sterben25** [comment]
> Right, you would be able to use `ModifyNetworkOutputs` and `ModifyOnnxOutputs` with the special constant `constants.MARK_ALL` to modify the TRT network and ONNX outputs respectively. But as @zerollzeng mentioned, this would block fusions.
> 
> You can see an example script for this with:
> 
> ```shell
> polygraphy run model.onnx --trt --onnxrt --trt-outputs mark all --onnx-outputs mark all --gen -
> ```

Thanks, that solves my problem

**Comment by zerollzeng** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
