### ISSUE TITLE
can I appoint fuse order？

### ISSUE THREAD

**Issue by lk137095576** [NVIDIA/TensorRT#2572]
Happy New Year
when use trtexec get engine, I find the fuse order may not reasonable，
in the demo:
<img width="176" alt="onnx" src="https://user-images.githubusercontent.com/26320143/210042285-d492673f-2d2b-43e8-abca-7528d61a1c67.png">
in the log file, softplus tanh mul add fuse together, but the conv not.
_"name" : "Conv_0",
 "name" : "PWN(PWN(PWN(PWN(Softplus_1), PWN(Tanh_2)), Mul_3), onnx::Add_7 + (Unnamed Layer* 5) [Shuffle] + Add_5)"_
it is better to fuse all conv+softplus+tanh+mul+and.
I review the log ,  GenericConvActFusion after PointWiseFusion, if it cause the problem? that not very efficient.
Q:  may I can change the fuse order? use GenericConvActFusion before PointWiseFusion.

**Comment by nvpohanh** [comment]
`conv+softplus+tanh+mul+add` this fusion is very aggressive and is only supported on a few platforms and precisions. Which TRT version and which GPU are you using? Could you try TRT 8.5.2 on Ampere or Hopper GPUs and enable FP16 and INT8?

**Comment by lk137095576** [comment]
> `conv+softplus+tanh+mul+add` this fusion is very aggressive and is only supported on a few platforms and precisions. Which TRT version and which GPU are you using? Could you try TRT 8.5.2 on Ampere or Hopper GPUs and enable FP16 and INT8?

Selected Device: NVIDIA A100 80GB PCIe
TensorRT version: 8.2.5
I try fp16, all  'conv+softplus+tanh+mul+add' fused
but when use int8, it not fuse.

**Comment by nvpohanh** [comment]
Did you mean 8.5.2 or 8.2.5? 8.2.5 does not have this fusion, so you have to use 8.5.1 or 8.5.2

**Comment by nvpohanh** [comment]
With INT8, please also add `--outputIOFormats=int8:chw32`. Otherwise, TRT assumes that the output will be in FP32, so it won't use INT8 kernels for the pointwise part.

**Comment by lk137095576** [comment]
> Did you mean 8.5.2 or 8.2.5? 8.2.5 does not have this fusion, so you have to use 8.5.1 or 8.5.2

Thansk ,my tensorrt is 8.2.5,  I will install 8.5.2 and try again.

**Comment by lk137095576** [comment]
> With INT8, please also add `--outputIOFormats=int8:chw32`. Otherwise, TRT assumes that the output will be in FP32, so it won't use INT8 kernels for the pointwise part.

I try with 8.5.2, it all fused. Thanks
