### ISSUE TITLE
Too many onnx files when converting mt5-xxl with t5.ipynb 

### ISSUE THREAD

**Issue by drxmy** [NVIDIA/TensorRT#2573]
## Description
I try to use t5.ipynb to convert mt0-xxl(https://huggingface.co/bigscience/mt0-xxl-mt, basically it is a fine-tuned mt5-xxl). I added its info in the T5ModelConfig.py. When converting to ONNX, it generated so much files(127GB) like this
![image](https://user-images.githubusercontent.com/39789137/210054324-281387cb-2ae9-41d0-9ca5-9881fe2e695a.png)

This did not happen with t5-large or small. And it fail when converting to TRT with "OutOfMemory" msg. 

I can not figure out why there are so much onnx files. Any suggestion to fix this? Or any explanation?

Thank you
## Environment

**TensorRT Version**:  8.5.2.2 (ONNX 1.12.0)
**NVIDIA GPU**:  32G v100
**NVIDIA Driver Version**:  460.73.01 
**CUDA Version**: 11.2
**CUDNN Version**: 
**Operating System**: CentOS Linux release 7.6.1810
**Python Version (if applicable)**: 3.8.13
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.11.0
**Baremetal or Container (if so, version)**:

**Comment by nvpohanh** [comment]
The "many" file is normal because ONNX format (which is based on protobuf) has 2GB filesize limitation, so it will store the weights in separate files to bypass that limit. So this part is not TRT's fault but a natural ONNX behavior.

See: https://github.com/onnx/onnx/blob/main/docs/ExternalData.md

> And it fail when converting to TRT with "OutOfMemory" msg.

The model seems to have 13B parameters, which means your GPU must have at least 52GB of memory to hold the model. But your GPU only has 32GB.

**Comment by drxmy** [comment]
But the msg came form converting the encoder
`

    t5_trt_encoder_engine = T5EncoderONNXFile(os.path.join(onnx_model_path, encoder_onnx_model_fpath), metadata).as_trt_engine(
        encoder_engine_name,
        profiles=[encoder_profile],
        preview_features=preview_features)`
By the way, why does it convert onnx on cpu?
`
t5_encoder = T5EncoderTorchFile(t5_model.to('cpu'), metadata)
`

**Comment by ttyio** [comment]
Now we have T5 sample in TRT-LLM https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/enc_dec, I will close this one ,thanks all!
