### ISSUE TITLE
[demo/BERT] Unable to achieve accelerated optimization results in reports

### ISSUE THREAD

**Issue by macanv** [NVIDIA/TensorRT#258]
## Description
I followed the contents of the readme to test the squad acceleration on the T4gpu, and it was impossible to achieve the 2.xms when batch_size=1, max_seq_length=384, **I get inference result used 10ms about.**

First, I follow the https://github.com/NVIDIA/TensorRT install TensorRT 5.1 
Than, I follow the https://github.com/NVIDIA/TensorRT/demo/BERT Compile the project

after compiled, in the build dir , I get such file 
![image](https://user-images.githubusercontent.com/16610116/70405362-e5612200-1a77-11ea-8c2e-8726af96a95c.png)

and then run `python python/bert_builder.py -m /workspace/models/fine-tuned/bert_tf_v2_base_fp16_384_v2/model.ckpt-8144 -o bert_base_384.engine -b 1 -s 384 -c /workspace/models/fine-tuned/bert_tf_v2_base_fp16_384_v2`
I get follow output:
[TensorRT] INFO: Adding reformat layer: (Unnamed Layer* 98) [Fully Connected] output to be reformatted 0 (cls_dense) from Float(1,1,1,2,768) to Half(1,1,1,2,768)
[TensorRT] INFO: Formats and tactics selection completed in 149.989 seconds.
[TensorRT] INFO: After reformat layers: 99 layers
[TensorRT] INFO: Block size 5242880000
[TensorRT] INFO: Block size 2359296
[TensorRT] INFO: Block size 2359296
[TensorRT] INFO: Block size 589824
[TensorRT] INFO: Block size 589824
[TensorRT] INFO: Block size 512
[TensorRT] INFO: Total Activation Memory: 5248778752
[TensorRT] INFO: Detected 3 input and 1 output network tensors.
[TensorRT] INFO: Data initialization and engine generation completed in 1.08537 seconds.
[TensorRT] INFO: Serializing the engine....
[TensorRT] INFO: Saving the engine....
[TensorRT] INFO: Done.

than I run 

```
python python/bert_inference_batch.py -e bert_base_384.engine -p "TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs. It includes parsers to import models, and plugins to support novel ops and layers before applying optimizations for inference. Today NVIDIA is open sourcing parsers and plugins in TensorRT so that the deep learning community can customize and extend these components to take advantage of powerful TensorRT optimizations for your apps." -q "What is TensorRT?" -v /workspace/models/fine-tuned/bert_tf_v2_base_fp16_384_v2/vocab.txt -b 1
```

output:
![image](https://user-images.githubusercontent.com/16610116/70405175-40dee000-1a77-11ea-8ca5-12510f438832.png)

## Environment

**TensorRT Version**:  5.1.5.0
**GPU Type**: T4 16G
**Nvidia Driver Version**: 410.104
**CUDA Version**: 10.0
**CUDNN Version**: 7.5
**Operating System + Version**:  nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04 docker image env
**Python Version (if applicable)**: 2.7.5
**TensorFlow Version (if applicable)**: 1.13.2
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @macanv,

What if you run it with TRT 6.0? 

I also believe newest CuDNN versions generally can offer a performance increase.

**Comment by macanv** [comment]
thanks, now I use docker images nvcr.io/nvidia/tensorrt:19.11-py3, but i found this image CUDA version is 10.2, Does this affect compilation?

**Comment by macanv** [comment]
thanks @rmccorm4 , now I use docker images nvcr.io/nvidia/tensorrt:19.11-py3, but i found this image CUDA version is 10.2, Does this affect compilation?

**Comment by yicracks** [comment]
https://github.com/NVIDIA/TensorRT/demo/BERT shows "page not found". What's wrong with that?
And another question: Is that impossible to first convert .pb model to uff model for bert? Since when I'm debugging, I found in node with name "bert/encoder/layer_0/intermediate/dense/Pow", there're some operations that tensorRT does not support.
Any other document for that?

**Comment by rmccorm4** [comment]
@macanv not sure, I generally try to use the same container image for both conversion and inference to avoid any possible environment configuration mismatch issues

@yicracks you can check out the release/6.0 branch for a sample of how to run BERT with TensorRT, though I think there will eventually be one for TensorRT 7.0 as well

**Comment by rmccorm4** [comment]
Closing since no response.
