### ISSUE TITLE
Can not convert auto-regression model to TensorRT engine

### ISSUE THREAD

**Issue by yjiangling** [NVIDIA/TensorRT#2582]
TensorRT Version:  8.2.3.0

When I convert an auto-regression with while_loop operator model to tensorrt engine with trtexec, it gives the following error:

[01/03/2023-08:43:00] [E] [TRT] parsers/onnx/ModelImporter.cpp:783: --- End node ---
[01/03/2023-08:43:00] [E] [TRT] parsers/onnx/ModelImporter.cpp:785: ERROR: parsers/onnx/ModelImporter.cpp:166 In function parseGraph:
[6] Invalid Node - generic_loop_Loop__352
[graphShapeAnalyzer.cpp::processCheck::581] Error Code 4: Internal Error ((Unnamed Layer* 3582) [Recurrence]: inputs to IRecurrenceLayer have different dimensions. First input has dimensions [3,1] and second input has dimensions [3,2].
)
[graphShapeAnalyzer.cpp::processCheck::581] Error Code 4: Internal Error ((Unnamed Layer* 3582) [Recurrence]: inputs to IRecurrenceLayer have different dimensions. First input has dimensions [3,1] and second input has dimensions [3,2].
)
[01/03/2023-08:43:00] [E] Failed to parse onnx file
[01/03/2023-08:43:00] [E] Parsing model failed
[01/03/2023-08:43:00] [E] Failed to create engine from model.
[01/03/2023-08:43:00] [E] Engine set up failed

It seems that the input to the while_loop must be constant shape? How can I solve this problem?

**Comment by zerollzeng** [comment]
Can you try the latest TRT release? not sure if we add this support.

**Comment by yjiangling** [comment]
@zerollzeng I have tried the latest TRT release, unfortunately it still not add this support. Is there any other solution? Thanks a lot in advance.

**Comment by zerollzeng** [comment]
> First input has dimensions [3,1] and second input has dimensions [3,2].

Can you share the onnx here so that I can debug it? I think we can try to extend the dimension of the first input to [3,2] to WAR this issue.

**Comment by yjiangling** [comment]
> > First input has dimensions [3,1] and second input has dimensions [3,2].
> 
> Can you share the onnx here so that I can debug it? I think we can try to extend the dimension of the first input to [3,2] to WAR this issue.

@zerollzeng Thanks a lot, here is the ONNX model: https://github.com/yjiangling/Temp_Model/releases/tag/2.0 , and I use trtexec to convert onnx model to tensorrt engine like:

trtexec \
    --onnx=./onnx_model/model.onnx \
    --minShapes=xs:1x1120,xlen:1 \
    --optShapes=xs:1x160000,xlen:1 \
    --maxShapes=xs:1x480000,xlen:1 \
    --workspace=10240 \
    --saveEngine=./trt_model/model-FP32.plan \
    --device=0 \
    --verbose \
    --buildOnly \
    > result-FP32.txt
exit

I tried to extend the dimension of the first input to [3, 2] such as [[1, 0], [1, 0], [1, 0]] and replace the padding with the decode result to keep the dimension of the second input as [3, 2] like [[y1, 1], [y2, 1], [y3, 1]] , but it gives the error like: 

**[6] Invalid Node - while/strided_slice
[graph.cpp::computeInputExecutionUses::553] Error Code 9: Internal Error ((Unnamed Layer* 2971) [Recurrence]: IRecurrenceLayer cannot be used to compute a shape tensor)**

I think maybe tensorrt do not support slice in while_loop ?

**Comment by yjiangling** [comment]
@oxana-nvidia Sorry for bothering (I think maybe your partener is on dayoff this week? So, I'm looking for your help) , could you please help to look this problem for me ? I have been confused with it for a few weeks , and still have no ideal to solve it . Thanks a lot .

**Comment by oxana-nvidia** [comment]
@yjiangling have you tried preview feature for dynamic shapes? you can check `trtexec -h` for which parameters to use to run it. 
I'll try you model to see if I can repro it on my side.

**Comment by oxana-nvidia** [comment]
I can repro it on my local machine. Looking at the API file, it explicitly says dims expected to be the same: 

```
class IRecurrenceLayer : public ILoopBoundaryLayer
{
public:
    //!
    //! \brief Append or replace an input of this layer with a specific tensor
    //!
    //! \param index the index of the input to modify.
    //! \param tensor the new input tensor
    //
    //! Sets the input tensor for the given index.
    //!
    //! For a recurrence layer, the values 0 and 1 are valid.
    //! The indices are as follows:
    //!
    //! - 0: The initial value of the output tensor. The value must come from outside the loop.
    //! - 1: The next value of the output tensor. The value usually comes from inside the loop, and must have the same
    //! dimensions as input 0.
```
you can try to replace dims to be the same and try to run trtexec with --preview=+fasterDynamicShapes0805 (supported since TRT 8.5)

**Comment by yjiangling** [comment]
> I can repro it on my local machine. Looking at the API file, it explicitly says dims expected to be the same:
> 
> ```
> class IRecurrenceLayer : public ILoopBoundaryLayer
> {
> public:
>     //!
>     //! \brief Append or replace an input of this layer with a specific tensor
>     //!
>     //! \param index the index of the input to modify.
>     //! \param tensor the new input tensor
>     //
>     //! Sets the input tensor for the given index.
>     //!
>     //! For a recurrence layer, the values 0 and 1 are valid.
>     //! The indices are as follows:
>     //!
>     //! - 0: The initial value of the output tensor. The value must come from outside the loop.
>     //! - 1: The next value of the output tensor. The value usually comes from inside the loop, and must have the same
>     //! dimensions as input 0.
> ```
> 
> you can try to replace dims to be the same and try to run trtexec with --preview=+fasterDynamicShapes0805 (supported since TRT 8.5)

Thanks you very much for the help, I will try it. I see the offical reply for **IRecurrenceLayer cannot be used to compute a shape tensor** error said "TRT does not support shapes that are computed using loops/recurrences." in 2019(link: https://forums.developer.nvidia.com/t/irecurrencelayer-cannot-be-used-to-compute-a-shape-tensor/186944), have it been supported with preview feature? I'wll try to keep the input dims same and use trtexec with --preview=+fasterDynamicShapes0805 covert trt engine again, thanks again for the help!!!

![image](https://user-images.githubusercontent.com/42861880/211985375-9073e90a-09d5-46af-9ff1-6ebbc230b767.png)

**Comment by oxana-nvidia** [comment]
I don't know if it is supported, need to test with recent code changes. Would be good to have an example with same dims to try it.

**Comment by yjiangling** [comment]
> I don't know if it is supported, need to test with recent code changes. Would be good to have an example with same dims to try it.

OK，thank you，I'm tring with same dims model，and I'will tell you the result later. @oxana-nvidia

**Comment by yjiangling** [comment]
@oxana-nvidia Unfortunately，it still can not be convert to trt engine，but it give different error message for different tensorrt version for the same model.

For trt 8.2.3.0，
**[6] Invalid Node - while/strided_slice
[graph.cpp::computeInputExecutionUses::555] Error Code 9: Internal Error ((Unnamed Layer* 3575) [Recurrence]: IRecurrenceLayer cannot be used to compute a shape tensor)
[01/12/2023-07:35:13] [E] Failed to parse onnx file
[01/12/2023-07:35:13] [E] Parsing model failed
[01/12/2023-07:35:13] [E] Failed to create engine from model.
[01/12/2023-07:35:13] [E] Engine set up failed**

For trt 8.5.1.7，
**[01/12/2023-08:10:26] [W] [TRT] parsers/onnx/onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[01/12/2023-08:10:42] [E] Error[9]: [myelinBuilderUtils.cpp::getMyelinSupportType::1105] Error Code 9: Internal Error (while/SequenceMask/Less requires foreign node optimizations incompatible with data-dependent shapes, so treating as error.)
[01/12/2023-08:10:42] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[01/12/2023-08:10:42] [E] Engine could not be created from network
[01/12/2023-08:10:42] [E] Building engine failed
[01/12/2023-08:10:42] [E] Failed to create engine from model or file.
[01/12/2023-08:10:42] [E] Engine set up failed**

What's the meaning of "requires foreign node optimizations incompatible with data-dependent shapes"？

But I find another less elegent solution for auto-regression model like Conformer.  I convert two different sperate trt engine for Encoder and Decoder，and in predict process，the Encoder engine will be called for once，and the Decoder engine will be called for many times until decode finished（the end sign occured）. This solution will abandon while_loop operator to avoid lots of new problem. It's regret this model can not be converted with one trt engine，hope TensorRT will be more compatible with this kind models. Thank you again for the help.

**Comment by oxana-nvidia** [comment]
@yjiangling thanks for follow up. I'm gad you were able to find a workaround. for your case. Could you please share the same dims model that you are running? I want to try if it is supported in our prelease build. 
foreign node means graph compiler that TRT is using. The message suppose to say that data-dependent shape approach is not compatible with the current version on graph compiler optimizations.

**Comment by yjiangling** [comment]
@oxana-nvidia OK，here is onnx model with same input dims（link：https://github.com/yjiangling/Temp_Model/releases/tag/3.0），you can try with it. Thanks a lot for your explanation and I'm sorry for the late reply.

**Comment by oxana-nvidia** [comment]
@yjiangling Thanks for provided model! With prerelease I'm getting the same error as you have in 8.5.1
```
[01/12/2023-21:02:52] [E] Error[9]: [myelinBuilderUtils.cpp::getMyelinSupportType::1271] Error Code 9: Internal Error (while/SequenceMask/Less requires foreign node optimizations incompatible with data-dependent shapes, so treating as error.)
[01/12/2023-21:02:52] [E] Engine could not be created from network
```
I've filed an internal feature request to investigate if we can support it. Reference number 3940792

**Comment by yjiangling** [comment]
> @yjiangling Thanks for provided model! With prerelease I'm getting the same error as you have in 8.5.1
> 
> ```
> [01/12/2023-21:02:52] [E] Error[9]: [myelinBuilderUtils.cpp::getMyelinSupportType::1271] Error Code 9: Internal Error (while/SequenceMask/Less requires foreign node optimizations incompatible with data-dependent shapes, so treating as error.)
> [01/12/2023-21:02:52] [E] Engine could not be created from network
> ```
> 
> I've filed an internal feature request to investigate if we can support it. Reference number 3940792

@oxana-nvidia Wow, that's great! Thank you so much, I'm looking forward to your good news in future. Anyway, my problem have been sloved. It can been speed up by 5~6 times with two engines.

**Comment by kshabibi** [comment]
Any update on this?

**Comment by ttyio** [comment]
Closing since according to last comment, this issue can be WAR by using 2 engines, thanks all!

**Comment by demuxin** [comment]
> > @yjiangling Thanks for provided model! With prerelease I'm getting the same error as you have in 8.5.1
> > ```
> > [01/12/2023-21:02:52] [E] Error[9]: [myelinBuilderUtils.cpp::getMyelinSupportType::1271] Error Code 9: Internal Error (while/SequenceMask/Less requires foreign node optimizations incompatible with data-dependent shapes, so treating as error.)
> > [01/12/2023-21:02:52] [E] Engine could not be created from network
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've filed an internal feature request to investigate if we can support it. Reference number 3940792
> 
> @oxana-nvidia Wow, that's great! Thank you so much, I'm looking forward to your good news in future. Anyway, my problem have been sloved. It can been speed up by 5~6 times with two engines.

Hi @yjiangling, could you please tell me how to use two engines? or tell me  if you have any information on it.
