### ISSUE TITLE
Excess VRAM usage TRT vs PT

### ISSUE THREAD

**Issue by harishprabhala** [NVIDIA/TensorRT#2590]
Hi - I have converted stable diffusion into TensorRT plan files. Although the inference is much faster, the TRT model takes up more than 2X of the VRAM than PT version. I'm not able to load multiple models on my 2080Ti GPU with TRT. 

Any way I can limit the excess VRAM usage during inference?

**Comment by zerollzeng** [comment]
@nvpohanh Is this a known issue? thanks! cc @rajeevsrao

**Comment by harishprabhala** [comment]
When we run the demo_diffusion.py, we see that a TRT model is taking about 10GB, and PyTorch is taking about 4.3GB.

**Comment by harishprabhala** [comment]
Below are how many stable diffusion models we can fit with different frameworks on A10. These are all FP16

AITemplate - 4
PyTorch - 7 
XFormers - 8
TRT - 2 

TensorRT is occupying way too much VRAM.

**Comment by nvpohanh** [comment]
@zerollzeng Could you repro this? If you can repro this, please file an internal bug to track this. Thanks

**Comment by zerollzeng** [comment]
@harishprabhala Can you share the detailed repro steps here so that I can take a look? Thanks!

**Comment by kamalkraj** [comment]
@zerollzeng
Following the exact step mentioned here -> https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion
successfully converted model on `Quadro RTX 8000`. While running the inference, the TRT model takes around `10092 MiB` . On the same GPU Pytorch FP16 runs on less than 5GB Memory

**Comment by lazy-nurd** [comment]
Facing the same issue @zerollzeng 
While pytorch takes 5-6 GB, trt is taking 13GB for Stable Diffusion 1.5.
And the engine is built with fp16 precision.
This is a big blocker to run this model.

**Comment by zerollzeng** [comment]
@nvpohanh I can reproduce the issue and I've filed an internal bug 3979473 to track this.

**Comment by hnsywangxin** [comment]
I have the same problem, Pytorch FP16 model runs on about 5GB Memory, but stable diffusion demo_txt2img.py takes around 20G，terrible

**Comment by zerollzeng** [comment]
Internal bug to track this: 3979473

**Comment by WudiJoey** [comment]
Me too. The graphics memory used by trt is really larger than that used by pytorch. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11254#issuecomment-1596390400
The command to convert the sd models:
"/hostdir/project/stable_diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt/TensorRT-8.6.1.6/bin/trtexec" --onnx="models/Unet-onnx/test.onnx" --saveEngine="/hostdir/project/stable_diffusion/stable-diffusion-webui/models/Unet-trt/test.trt" --minShapes=x:2x4x64x64,context:2x77x768,timesteps:2 --maxShapes=x:2x4x64x64,context:2x77x768,timesteps:2 --fp16

**Comment by zerollzeng** [comment]
Please try using `--build-static-batch`, I can see the maximum memory usage drop from 13GB to 6GB.

e.g. python3 demo_txt2img.py "a beautiful photograph of Mt. Fuji during cherry blossom" --hf-token=$HF_TOKEN -v --build-static-batch

**Comment by WudiJoey** [comment]
您好，您的来信我已经收到，会尽快回复。

**Comment by ttyio** [comment]
see lastest comment, pls try `--build-static-batch`, closing and thanks all!
