### ISSUE TITLE
Tensorrt container build failed

### ISSUE THREAD

**Issue by Levi-zhan** [NVIDIA/TensorRT#2591]
## Description

I want to build a container of Tensorrt 8.4+cuda11.4 according to this tutorial https://github.com/NVIDIA/TensorRT/tree/8.4.1。
Then I get the following error.

Step 19/28 : RUN if [ "${CUDA_VERSION}" = "10.2" ] ; then     v="${TRT_VERSION%.*}-1+cuda${CUDA_VERSION}" &&    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&    apt-get update &&    sudo apt-get install libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v}         libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v}         python3-libnvinfer=${v}; else     v="${TRT_VERSION%.*}-1+cuda${CUDA_VERSION%.*}" &&    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&    apt-get update &&    sudo apt-get install libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v}         libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v}         python3-libnvinfer=${v}; fi
 ---> Running in 1a2fd308bb55
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.0Z4XcLaQfG/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
gpg: requesting key from 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub'
gpg: key A4B469963BF863CC: "cudatools <cudatools@nvidia.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:6 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '8.4.1-1+cuda11.4' for 'libnvinfer8' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvonnxparsers8' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvparsers8' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvinfer-plugin8' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvinfer-dev' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvonnxparsers-dev' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvparsers-dev' was not found
E: Version '8.4.1-1+cuda11.4' for 'libnvinfer-plugin-dev' was not found
E: Version '8.4.1-1+cuda11.4' for 'python3-libnvinfer' was not found
The command '/bin/bash -c if [ "${CUDA_VERSION}" = "10.2" ] ; then     v="${TRT_VERSION%.*}-1+cuda${CUDA_VERSION}" &&    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&    apt-get update &&    sudo apt-get install libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v}         libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v}         python3-libnvinfer=${v}; else     v="${TRT_VERSION%.*}-1+cuda${CUDA_VERSION%.*}" &&    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&    apt-get update &&    sudo apt-get install libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v}         libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v}         python3-libnvinfer=${v}; fi' returned a non-zero code: 100

My command is ：./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.6 --cuda 11.4.2
and it show ：
 docker build -f docker/ubuntu-20.04.Dockerfile --build-arg CUDA_VERSION=11.4.2 --build-arg uid=0 --build-arg gid=0 --tag=tensorrt-ubuntu20.04-cuda11.6 .

Does Tensorrt8.4 not support cuda11.4, but only 11.6? The same error occurred when I first used tensor 8.5
Please give me some suggestions. My GPU driver limits me to using cuda11.4 at most, and I cannot update the driver. thank you

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
> ./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.6 --cuda 11.4.2
> and it show ：

maybe you should use `./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.4 --cuda 11.4`?


> Does Tensorrt8.4 not support cuda11.4, but only 11.6?

No, it support cuda 11.4

**Comment by Levi-zhan** [comment]
> > ./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.6 --cuda 11.4.2
> > and it show ：
> 
> maybe you should use `./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.4 --cuda 11.4`?
> 
> > Does Tensorrt8.4 not support cuda11.4, but only 11.6?
> 
> No, it support cuda 11.4

I executed your command at release/8.5 branch。
./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.4 --cuda 11.4
Then an error is reported as follows：

Step 3/28 : FROM nvidia/cuda:${CUDA_VERSION}-cudnn8-devel-ubuntu${OS_VERSION}
manifest for nvidia/cuda:11.4-cudnn8-devel-ubuntu20.04 not found: manifest unknown: manifest unknown

Then I made the following modifications（add “.2” in ubuntu-20.04.Dockerfile）:
-FROM nvidia/cuda:${CUDA_VERSION}-cudnn8-devel-ubuntu${OS_VERSION}
+FROM nvidia/cuda:${CUDA_VERSION}.2-cudnn8-devel-ubuntu${OS_VERSION}
But still report the above error：
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
^[[91mE: Version '8.5.2-1+cuda11.4' for 'libnvinfer8' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvonnxparsers8' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvparsers8' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvinfer-plugin8' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvinfer-dev' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvonnxparsers-dev' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvparsers-dev' was not found
E: Version '8.5.2-1+cuda11.4' for 'libnvinfer-plugin-dev' was not found
E: Version '8.5.2-1+cuda11.4' for 'python3-libnvinfer' was not found
^[[0mThe command '/bin/bash -c if [ "${CUDA_VERSION}" = "10.2" ] ; then     v="${TRT_VERSION%.*}-1+cuda${CUDA_VERSION}" &&    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&    apt-get update &&    sudo apt-get install libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v}         libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v}         python3-libnvinfer=${v}; else     v="${TRT_VERSION%.*}-1+cuda${CUDA_VERSION%.*}" &&    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub &&    apt-get update &&    sudo apt-get install libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v}         libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v}         python3-libnvinfer=${v}; fi' returned a non-zero code: 100
Is there anything I haven't done right? thank you

**Comment by ttyio** [comment]
checked https://github.com/NVIDIA/TensorRT/tree/8.4.1, cuda11.6 is supported, but not 11.4.

closing legacy threads, thanks all
