### ISSUE TITLE
Error Building 22.02. "GREATER_EQUAL" "70", Unknown argument specified

### ISSUE THREAD

**Issue by orjano-max** [NVIDIA/TensorRT#2610]
## Description
Trying to build TensorRT OSS 22.02 on Nvidia Jetson AGX Xavier, Jetpack 5.02.

**I get this error code at the "cmake .. -DCUDA..." command:**
```console
@ubuntu:~/TensorRT/build$ cmake .. -DCUDA_VERSION=$CUDA_VERSION -DGPU_ARCHS=$GPU_ARCHS
```
Building for TensorRT version: 8.2.3, library version: 8
-- The CXX compiler identification is GNU 9.4.0
-- The CUDA compiler identification is NVIDIA 11.4.239
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Targeting TRT Platform: x86_64
-- CUDA version set to 
-- cuDNN version set to 8.2
-- Protobuf version set to 3.0.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'zlib'
-- Found CUDA: /usr/local/cuda-11.4 (found version "") 
-- Setting up another Protobuf build for cross compilation targeting aarch64-Linux
-- Using libprotobuf /home/xavier2/TensorRT/build/third_party.protobuf_aarch64/lib/libprotobuf.a
-- ========================= Importing and creating target nvinfer ==========================
-- Looking for library nvinfer
-- Library that was found /usr/lib/aarch64-linux-gnu/libnvinfer.so
-- ==========================================================================================
-- ========================= Importing and creating target nvuffparser ==========================
-- Looking for library nvparsers
-- Library that was found /usr/lib/aarch64-linux-gnu/libnvparsers.so
-- ==========================================================================================
-- GPU_ARCHS defined as . Generating CUDA code for SM 
CMake Error at CMakeLists.txt:176 (list):
  list GET given empty list

CMake Error at CMakeLists.txt:178 (if):
  if given arguments:

    "GREATER_EQUAL" "70"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/xavier2/TensorRT/build/CMakeFiles/CMakeOutput.log".
See also "/home/xavier2/TensorRT/build/CMakeFiles/CMakeError.log".

## Environment

**TensorRT Version**: 8.4.1.5
**NVIDIA GPU**: tegra194
**NVIDIA Driver Version**: 
**CUDA Version**: 11.4.239
**CUDNN Version**: 8.4.1.50
**Operating System**: L4T: 35.1.0, Jetpack 5.0.2 GA
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

Following guide on the ros2_tao_pointpillars github repo, link: https://github.com/NVIDIA-AI-IOT/ros2_tao_pointpillars

## Steps To Reproduce

Following guide on the ros2_tao_pointpillars github, link: https://github.com/NVIDIA-AI-IOT/ros2_tao_pointpillars

The guide is tellimg me to do the following:

```console
git clone -b 22.02 https://github.com/NVIDIA/TensorRT.git TensorRT

cd TensorRT

git submodule update --init --recursive

mkdir -p build && cd build

cmake .. -DCUDA_VERSION=$CUDA_VERSION -DGPU_ARCHS=$GPU_ARCHS

make nvinfer_plugin -j$(nproc)

make nvinfer_plugin_static -j$(nproc)

cp libnvinfer_plugin.so.8.2.* /usr/lib/$ARCH-linux-gnu/libnvinfer_plugin.so.8.2.3

cp libnvinfer_plugin_static.a /usr/lib/$ARCH-linux-gnu/libnvinfer_plugin_static.a
```

**Comment by zerollzeng** [comment]
What's the `-DCUDA_VERSION=$CUDA_VERSION -DGPU_ARCHS=$GPU_ARCHS` setting?

**Comment by orjano-max** [comment]
Assuming that $CUDA_VERSION is set to the current cuda version, which would be cuda 11.4.239. As for GPU_ARCHS, im not quite sure.

The following information was given for hardware according to jtop:

MODEL: Jetson-AGX
P-Number: p288-0001
Module: NVIDIA Jetson AGX Xavier (16Gb ram)
SoC: tegra194
CUDA Arch BIN: 7.2
Codename: Galen
L4T: 35.1.0
Jetpack: 5.0.2 GA

**Comment by zerollzeng** [comment]
try -DGPU_ARCHS=72?
