### ISSUE TITLE
onnx graphsurgeon ir node

### ISSUE THREAD

**Issue by inisis** [NVIDIA/TensorRT#2615]
Hi, onnx graphsurgeon is a great tool, it helped me in many ways. 

Here, [node index ](https://github.com/NVIDIA/TensorRT/blob/release/8.5/tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/node.py#L73), 

```
    def i(self, tensor_idx=0, producer_idx=0):
        """
        Convenience function to get a producer node of one of this node's input tensors.
        Note that the parameters are swapped compared to the o() function; this is because tensors are likely to have only a single producer
        For example:
        ::
            assert node.i() == node.inputs[0].inputs[0]
            assert node.i(1, 2) == node.inputs[1].inputs[2]
        Args:
            tensor_idx (int): The index of the input tensor of this node. Defaults to 0.
            producer_idx (int): The index of the producer of the input tensor, if the tensor has multiple producers. Defaults to 0
        Returns:
            Node: The specified producer (input) node.
        """
        return self.inputs[tensor_idx].inputs[producer_idx]
```

if one node is directly connected to the input variable, like below:
![image](https://user-images.githubusercontent.com/46103969/215314784-78a359fc-20b3-49fe-bdd0-2f8ebfa63caa.png)
then, we iterate over the nodes in graph like below:
```
for node in graph.nodes:
    print(node.i())
```
it will rasie an error *onnx_graphsurgeon/ir/node.py:74: IndexError: list index out of range*, can we return None instead of throwing an IndexError, this way, user can better handle situation where node is  directly connected to the input variable, or they have to check len(node.inputs[0].inputs), this is somewhat ugly.

I thinke a better solution is:
```
    def i(self, tensor_idx=0, producer_idx=0):
        """
        Convenience function to get a producer node of one of this node's input tensors.
        Note that the parameters are swapped compared to the o() function; this is because tensors are likely to have only a single producer

        For example:
        ::

            assert node.i() == node.inputs[0].inputs[0]
            assert node.i(1, 2) == node.inputs[1].inputs[2]

        Args:
            tensor_idx (int): The index of the input tensor of this node. Defaults to 0.
            producer_idx (int): The index of the producer of the input tensor, if the tensor has multiple producers. Defaults to 0

        Returns:
            Node: The specified producer (input) node.
        """

        try:
            return self.inputs[tensor_idx].inputs[producer_idx]
        except IndexError:
            return None    
```

**Comment by zerollzeng** [comment]
@pranavm-nvidia I think it's reasonable, can we improve this? Thanks!

**Comment by pranavm-nvidia** [comment]
Breaking API changes are always hard to make. What about:
```py
for node in graph.nodes:
    with contextlib.suppress(IndexError):
        print(node.i())
```
?

**Comment by inisis** [comment]
> Breaking API changes are always hard to make. What about:
> 
> ```python
> for node in graph.nodes:
>     with contextlib.suppress(IndexError):
>         print(node.i())
> ```
> 
> ?

This is not that good, because we want *node.i()* return, instead of nothing. print is a simple example.  
For graph fusion purpose, like below:
```
def find_gelu_nodes(graph):
    out_nodes = []
    for node in graph.nodes:
        if node.op == "Mul":
            if (
                node.i(0) is not None
                and node.i(0).op == "Mul"
                and node.i(0).i(1).op == "Add"
                and node.i(0).i(1).i(0).op == "Erf"
                and node.i(0).i(1).i(0).i(0).op == "Div"
            ):
                out_nodes += [
                    {
                        "inps": [node.i(0).i(1).i(0).i(0).inputs[0].name],
                        "outs": [node.outputs[0].name],
                    }
                ]

    return out_nodes
```
we have to make sure the Mul node is not directly connected to the input variable, currently, there is no api to do it.

**Comment by inisis** [comment]
> Then a wrapper might be the best way in the short-term:
> 
> ```python
> def i(node, *args, **kwargs):
>     try:
>         return node.i(*args, **kwargs)
>     except IndexError:
>         return None
> ```

How to use it... This seems a little big wired.

**Comment by pranavm-nvidia** [comment]
You would just do, e.g.: `i(node, 0)` instead of `node.i(0)`. For the specific example you gave, a slightly different wrapper might work better:
```py
def i(node, indices):
    try:
        for index in indices:
            node = node.i(index)
        return node
    except IndexError:
        return None
```

Then you'd be able to write:
```py
def find_gelu_nodes(graph):
    out_nodes = []
    for node in graph.nodes:
        if node.op == "Mul":
            if (
                i(node, [0]) is not None
                and i(node, [0]).op == "Mul"
                and i(node, [0, 1]).op == "Add"
                and i(node, [0, 1, 0]).op == "Erf"
                and i(node, [0, 1, 0, 0]).op == "Div"
            ):
                out_nodes += [
                    {
                        "inps": [i(node, [0, 1, 0, 0]).inputs[0].name],
                        "outs": [node.outputs[0].name],
                    }
                ]

    return out_nodes
```

Although it's still unclear to me why you can't just wrap the whole condition in a try-except (or equivalent `contextlib.suppress`). If `i()` returns None instead of throwing, then you would need to check every intermediate node too (which the example doesn't currently do). It's possible, for example, that `node.i(0).i(0)` would be None, in which case you'd end up with an `AttributeError` when you tried to access the `op` attribute.

**Comment by inisis** [comment]
> You would just do, e.g.: `i(node, 0)` instead of `node.i(0)`. For the specific example you gave, a slightly different wrapper might work better:
> 
> ```py
> 
> def i(node, indices):
> 
>     try:
> 
>         for index in indices:
> 
>             node = node.i(index)
> 
>         return node
> 
>     except IndexError:
> 
>         return None
> 
> ```
> 
> 
> 
> Then you'd be able to write:
> 
> ```py
> 
> def find_gelu_nodes(graph):
> 
>     out_nodes = []
> 
>     for node in graph.nodes:
> 
>         if node.op == "Mul":
> 
>             if (
> 
>                 i(node, [0]) is not None
> 
>                 and i(node, [0]).op == "Mul"
> 
>                 and i(node, [0, 1]).op == "Add"
> 
>                 and i(node, [0, 1, 0]).op == "Erf"
> 
>                 and i(node, [0, 1, 0, 0]).op == "Div"
> 
>             ):
> 
>                 out_nodes += [
> 
>                     {
> 
>                         "inps": [i(node, [0, 1, 0, 0]).inputs[0].name],
> 
>                         "outs": [node.outputs[0].name],
> 
>                     }
> 
>                 ]
> 
> 
> 
>     return out_nodes
> 
> ```
> 
> 
> 
> Although it's still unclear to me why you can't just wrap the whole condition in a try-except (or equivalent `contextlib.suppress`). If `i()` returns None instead of throwing, then you would need to check every intermediate node too (which the example doesn't currently do). It's possible, for example, that `node.i(0).i(0)` would be None, in which case you'd end up with an `AttributeError` when you tried to access the `op` attribute.

Exactly, the code that I presented is buggy... I was trying to find an elegant way to do this, but struggles a little bit.

**Comment by pranavm-nvidia** [comment]
You can do:
```py
def find_gelu_nodes(graph):
    out_nodes = []
    for node in graph.nodes:
        with contextlib.suppress(IndexError):
            if (
                node.op == "Mul"
                and node.i(0).op == "Mul"
                and node.i(0).i(1).op == "Add"
                and node.i(0).i(1).i(0).op == "Erf"
                and node.i(0).i(1).i(0).i(0).op == "Div"
            ):
                out_nodes += [
                    {
                        "inps": [node.i(0).i(1).i(0).i(0).inputs[0].name],
                        "outs": [node.outputs[0].name],
                    }
                ]
    return out_nodes
```

IMO this is easier than checking whether each node is `None`.

**Comment by inisis** [comment]
Thanks!
