### ISSUE TITLE
Support dynamic input shape (Height x Width) and dynamic batch size at the same time

### ISSUE THREAD

**Issue by lazylazypig** [NVIDIA/TensorRT#262]
Hi, all.
Does TensorRT support dynamic input shape (Height x Width) and dynamic batch size at the same time? thanks :)

**Comment by rmccorm4** [comment]
Hi @lazylazypig,

I believe it does, however I think it depends on the layers you are using. There are some restrictions listed here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#rest_dynamic_shapes

**Comment by dongqixu** [comment]
> Hi @lazylazypig,
> 
> I believe it does, however I think it depends on the layers you are using. There are some restrictions listed here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#rest_dynamic_shapes

Hi @rmccorm4,

Regarding the dynamic shape issue, I would like to enquire whether the dynamic output is supported or is able to be replaced by another method.

In `nvinfer1::IPluginV2DynamicExt::getOutputDimensions`, the output dimension could be derived from inputs dynamically. However, the output dimension could only be linear proportional to the input shape or calculated by the provided DimensionOperation (kSUM, kPROD, etc..). Is there a possible way to produce a dynamic output dimension during inference time?

For example, ONNX Slice operation produces a slice of the input tensor with starting indices and ending indices. If the starting indices and ending indices are known only during the inference time, does TensorRT support this feature or could it be implemented?

Thanks for your time.

**Comment by rmccorm4** [comment]
> In nvinfer1::IPluginV2DynamicExt::getOutputDimensions, the output dimension could be derived from inputs dynamically. However, the output dimension could only be linear proportional to the input shape or calculated by the provided DimensionOperation (kSUM, kPROD, etc..). Is there a possible way to produce a dynamic output dimension during inference time?
>
> For example, ONNX Slice operation produces a slice of the input tensor with starting indices and ending indices. If the starting indices and ending indices are known only during the inference time, does TensorRT support this feature or could it be implemented?

@pranavm-nvidia do you know more details on this?

**Comment by pranavm-nvidia** [comment]
You should be able to do that using the max/min operations

**Comment by rajeevsrao** [comment]
Closing stale issue based on last response. @lazylazypig please note (from documentation) that `getOutputDimensions` is only "called by the implementations of IBuilder during analysis of the network."
