### ISSUE TITLE
Support of optimized BERT in TensorRT latest versions

### ISSUE THREAD

**Issue by churinga** [NVIDIA/TensorRT#2623]
Hi, we have a BERT model fine-tuned with Tensorflow, and saved as a Tensorflow checkpoint file. We followed the optimizations described in https://developer.nvidia.com/blog/nlu-with-tensorrt-bert/ and the example in https://github.com/NVIDIA/TensorRT/tree/release/5.1/demo/BERT/python, and reproduced the optimized BERT model inference results on triton inference server 20.09. We are currently trying to upgrade the triton inference server to newer versions, namely 22.xx, but I'm having trouble finding the same BERT optimization example anywhere for the latest versions. Any advice is appreciated. 

Thanks!

**Comment by zerollzeng** [comment]
I don't know much about this but can https://github.com/NVIDIA/TensorRT/tree/main/demo/BERT help? I we should support demoBERT to the latest public version.

cc @nvpohanh

**Comment by churinga** [comment]
Thanks! That's what I was looking for. Somehow, I kept looking in other repos... 

Follow-up question - because this optimization requires custom plugins, will this be able to run on AWS SageMaker? If so, are there instructions on how to do that? Thanks again!

**Comment by nvpohanh** [comment]
The demoBERT plugins are shipped with TRT releases, so if TRT is installed, the plugins should also exist.

While demoBERT workflow still works, the alternative workflow is to export the model to ONNX and then load the ONNX into TRT.

**Comment by churinga** [comment]
Thanks for the reply! So, on SageMaker, we should be able to use the official triton inference server container? I remember that we needed to do some DO preloading when starting the triton inference server process for the plugins. Has this been changed and the plugins always preloaded in newer triton inference servers?

**Comment by nvpohanh** [comment]
could you give it a try? If it doesn't work, please try preloading the `libnvinfer_plugin.so`, which should be in the same directory as the TRT library (`libnvinfer.so`)

**Comment by churinga** [comment]
Ok, let me give it a try and update here. Thanks.

**Comment by churinga** [comment]
@nvpohanh I have tested with triton inference server 22.12, and it automatically loads `libnvinfer*.so` plugins, and there is no need to do any preloading any more. Thanks!
