### ISSUE TITLE
TensortRT version compatibility rules

### ISSUE THREAD

**Issue by mbechard** [NVIDIA/TensorRT#2624]
## Description

I'm trying to use TensorRT 8.5.3.1 and cuDNN 8.6.0.163 in my application with the Maxine SDKs. When the binaries from those version are used, the AR and Video Effects SDKs report an error "there was a problem deserializing the inference runtime engine." Things work fine if I use the version that the Maxine SDKs come with, 8.4.2.2. I've also tried 8.4.3.1, and that fails as well.
With more and more tools requiring TensorRT (Stereolabs ZED, Kinect Azure for example), I need to be able to move to a higher TensorRT/cuDNN version to accommodate dependencies that newer SDKs require (as well as if I upgrade AR, but not Video Effects, for example).

What is the expected version compatibility rules for TensorRT? I didn't have any luck finding any documentation on that.

Thanks

## Environment

**TensorRT Version**:  8.5.3.1 
**NVIDIA GPU**: 3080ti
**NVIDIA Driver Version**: 528.24
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0.163
**Operating System**: Windows 10
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by mbechard** [comment]
Thanks for the quick answer. If the binaries are strict on compatibility, is there a reason why they aren't named in a way the differentiates them by version number, so different SDKs will link against different versions can exist in the same application?
For example Kinect Azure uses TensorRT 8.0.3.4. How should I go about shipping an application that supports Kinect Azure and Maxine?

**Comment by zerollzeng** [comment]
Sorry I don't quite understand your question, could you please elaborate on it? 

Correct me if I'm wrong, Let's say you have a program, and you want to integrate both of  Kinect Azure(TRT 8.0) and Maxine(TRT 8.4) into your program, then for the model deployed with Kinect Azure, you will have to build the engine with TRT 8.0.3.4, and for the model deployed with Maxine, you need to build the engine with TRT 8.4.2.2. you can use both of two versions simutaneously in your program although you will have to load extra libs(TRT and its dependency).

I think the better solution is to try to make the 2 SDKs use the same version of TRT if you can build them from source.

**Comment by mbechard** [comment]
The tricky part comes because both TRT 8.0 and TRT 8.4 are sitting in a binary called nvinfer.dll. So my process will only be able to load one copy of that .dll. I assume this may be fixable with some .manifest trickiness, although I've never done that. What workflow are you suggesting where you could load two version simultaneously?

I don't think with either Azure or Maxine I have the source required to rebuild them. Arn't the models included with the Maxine SDK (*.engine.trtpkg files), already serialized and locked into a specific TRT version? If there is a way for me to re-serialize them into a new version, then that could do the trick.

**Comment by zerollzeng** [comment]
> Arn't the models included with the Maxine SDK (*.engine.trtpkg files), already serialized and locked into a specific TRT version?

If an engine has been generated, then it must be loaded with the same version otherwise it will fail to deserialize. 

> If there is a way for me to re-serialize them into a new version, then that could do the trick.

I think you will need to build the SDK with the requested TRT version. Maybe you can reach out to the Maxine SDK or Kinect Azure to see if they can help.

**Comment by mbechard** [comment]
Ok thanks, sounds like I have my answers. Appreciate all the help!

**Comment by oxana-nvidia** [comment]
@mbechard @zerollzeng,
In TensorRT 8.6 we are planning to release version compatibility feature. This feature will allow you to build engines with one version and run them with another version of TensorRT.

Please join our talk about this feature on GTC 2023
https://www.nvidia.com/gtc/session-catalog/?tab.catalogallsessionstab=16566177511100015Kus&search=tensorRT#/session/1666632585772001nPD0
