### ISSUE TITLE
No importer registered for op: grid_sampler. Attempting to import as plugin

### ISSUE THREAD

**Issue by pedroHuang123** [NVIDIA/TensorRT#2625]
## Description

What can I do to resolve this bug

![image](https://user-images.githubusercontent.com/72126736/215930952-283c24a2-cabb-4e79-a9e7-7b4ccb895748.png)

**Comment by zerollzeng** [comment]
dup of https://github.com/NVIDIA/TensorRT/issues/2612. So I'm closing this
