### ISSUE TITLE
Stable Diffusion UNet optimize failed, "SeqLen2Spatial" plugin got error!

### ISSUE THREAD

**Issue by StudentZhangxu** [NVIDIA/TensorRT#2626]
## Description
I want to accelerate my "**unet.onnx**" model of Stable Diffusion with TensorRT plugin.

First, modify the onnx model (**"unet.onnx --> unet_opt.onnx"**) by the optimize [script](https://github.com/NVIDIA/TensorRT/blob/main/demo/Diffusion/models.py) .

Second, convert the modified onnx model "**unet_opt.onnx**" to TensorRT engine with the command.
```/usr/local/TensorRT-8.5.2.2/bin/trtexec --onnx=unet_opt.onnx --fp16 --workspace=81251```

Then got error "**plugin Attribute height not found in SeqLen2Spatial node**"!
 (If "SeqLen2Spatial" plugin is not added in **unet_opt.onnx**, engine will build success)

<img width="1266" alt="截屏2023-02-01 下午4 25 54" src="https://user-images.githubusercontent.com/27423436/215989903-e84f862c-56da-487a-8e45-0f0f8711450a.png">

## Environment

**TensorRT Version**:  8.5.2
**NVIDIA GPU**: A100
**onnx 1.12.0**
**onnx-graphsurgeon 0.3.25**
**onnxruntime 1.13.1**
**polygraphy 0.43.1**

**Comment by zerollzeng** [comment]
@jdemouth-nvidia Can you help here?

**Comment by zerollzeng** [comment]
This just a warning,the error is `Invalid Node -Conv_300` and "image size is smaller than filter size"

What's the network input dimension?

**Comment by StudentZhangxu** [comment]
> This just a warning,the error is `Invalid Node -Conv_300` and "image size is smaller than filter size"
> 
> What's the network input dimension?

The network dimension is [2,4,64,64]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/27423436/216053028-702711f3-035f-44e1-910a-9902c4350a56.png">

Without "SeqLen2Spatial" plugin, engine build success. But with "SeqLen2Spatial" plugin, it gives above warning, so i think it 's might be the cause. 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/27423436/216054950-16c9584f-a53d-4470-907a-2a071674dfaf.png">
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/27423436/216053774-b127ead9-85b7-4c27-93b5-d9edf3012ac1.png">

**Comment by samurdhikaru** [comment]
@StudentZhangxu Thanks for reporting this. Are you using a pre-built plugin lib from 8.5 GA? Note that to get the latest SD pipeline to work with the SeqLen2Spatial plugin enabled, you'll need to build the plugin library from source (you can find the instruction [here](https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion#build-tensorrt-plugins-library)). 

If you absolutely must use a pre-built GA version of the plugin library, a workaround is to revert the changes to `demo/Diffusion/models.py` from https://github.com/NVIDIA/TensorRT/commit/85f59aa72b764bef07efe8a93d2e58ca8a087940   (i.e. use [this version](https://github.com/NVIDIA/TensorRT/blob/64c0ef2d662cfbc98ed7841144355e1c275a4975/demo/Diffusion/models.py) of `demo/Diffusion/models.py`), regenerate the UNet ONNX, and then retry the engine build.

Hope this helps!

**Comment by ttyio** [comment]
Closing since this is solved, thanks!
