### ISSUE TITLE
Why pth->onnx , the onnx model's input quantizeliner's y_scale/x_scale is NaN？ than failed to onnx->trt

### ISSUE THREAD

**Issue by jiegeng321** [NVIDIA/TensorRT#2628]
totally follow this tutorial https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/tutorials/quant_resnet50.html
save the PTQ and QAT model, pth->onnx->trt, trt report this error:
 
![emobile_2023-02-02_10-03-53](https://user-images.githubusercontent.com/32951460/216215764-420a3f69-5a3c-49c4-be46-71f552525125.png)

than i check the onnx file, find the onnx model's input quantizeliner's y_scale/x_scale is NaN:
![image](https://user-images.githubusercontent.com/32951460/216215987-2ab203b0-ec97-400e-8010-f916c45104dc.png)
I have tried a lot, onnx's y_scale/x_scale is always NaN.
Does anyone encounter the same situation? How was it resolved？

**Comment by jiegeng321** [comment]
@ttyio @zerollzeng @nvpohanh Have you ever appeared in this situation

**Comment by nvpohanh** [comment]
@jiegeng321 Did you do calibration? How did you do the calibration? 

I think this is most likely caused by some NaNs in the calibration input data.

**Comment by jiegeng321** [comment]
@nvpohanh I have did calibration.
my code is very simple just like:
`from pytorch_quantization import quant_modules`
 `quant_modules.initialize()`
`model=my_model()`
`def calibrate(model, data_loader, model_func, num_batches=2, **kwargs):`
    `model.eval()`
    `with torch.no_grad():`
        `collect_stats(model, data_loader, model_func, num_batches)#same as tutorial`
        `compute_amax(model, **kwargs)#same as tutorial`
    `model.train()`
`calibrate(model, train_loader, model_func=model_fn_decorator(),num_batches=2, method="percentile", percentile=99.99)`
input data is checked,no NaNs,is normal
no error message. it's log look like no problem too:
![emobile_2023-02-03_17-27-54](https://user-images.githubusercontent.com/32951460/216563804-57a4984d-5d5f-4206-b0f2-c7cf485f0728.png)
![emobile_2023-02-03_17-28-18](https://user-images.githubusercontent.com/32951460/216563837-685435c5-9ce8-4c96-85d5-86f84f915d05.png)
It's so strange！

**Comment by nvpohanh** [comment]
@rajeevsrao @jhalakp-nvidia Any ideas why the ONNX model would have NaNs for the scales?

@jiegeng321 Could you show how you exported the ONNX file from PyTorch? Also, which ONNX version and which PyTorch version did you use? Thanks

**Comment by jiegeng321** [comment]
@nvpohanh 
save pth:
`ckpt_name = ckpt_dir / ('checkpoint_epoch_PTQ.pth')`
`torch.save({'model_state': model.state_dict()}, ckpt_name)`
export onnx:
`model = build_network(model_cfg=cfg.MODEL,)`
 `model.load_params_from_file(filename=args.ckpt)`
`torch.onnx.export(model, dummy_input,save_name.split(".pth")[0]+"_raw.onnx", export_params=True, opset_version=13,input_names = ['voxels', 'voxel_num', 'voxel_idxs'],  output_names = ['cls_preds', 'box_preds', 'dir_cls_preds'],  )`
i find my train env torch version is different with export env
train env is:
no onnx
torch:1.8.0+cu111
export env is:
onnx:1.11.0
torch:1.11.0+cu113
i will try using the same env to export, thanks very mush!

**Comment by jiegeng321** [comment]
it is fixed,it is mainly torch version's problem. thanks @nvpohanh @zerollzeng very mush

**Comment by zerollzeng** [comment]
Glad to hear that, does it get fixed in the latest pytorch version?

**Comment by huihui6666** [comment]
> @nvpohanh save pth: `ckpt_name = ckpt_dir / ('checkpoint_epoch_PTQ.pth')` `torch.save({'model_state': model.state_dict()}, ckpt_name)` export onnx: `model = build_network(model_cfg=cfg.MODEL,)` `model.load_params_from_file(filename=args.ckpt)` `torch.onnx.export(model, dummy_input,save_name.split(".pth")[0]+"_raw.onnx", export_params=True, opset_version=13,input_names = ['voxels', 'voxel_num', 'voxel_idxs'], output_names = ['cls_preds', 'box_preds', 'dir_cls_preds'], )` i find my train env torch version is different with export env train env is: no onnx torch:1.8.0+cu111 export env is: onnx:1.11.0 torch:1.11.0+cu113 i will try using the same env to export, thanks very mush!

Hi ，I miss the problem too,I also use  in pointpillars. Would you share me how to deal with the problem?
