### ISSUE TITLE
Custom Plugin: INVALID_ARGUMENT: getPluginCreator could not find plugin Prelu_TRT version 1

### ISSUE THREAD

**Issue by zerollzeng** [NVIDIA/TensorRT#263]
## Environment

**TensorRT Version**: 6.0.1.5
**GPU Type**: 2080ti
**Nvidia Driver Version**:418.39 
**CUDA Version**: 10.0
**CUDNN Version**: 7.6
**Operating System + Version**:ubuntu 16.04 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

https://github.com/zerollzeng/tiny-tensorrt/tree/master/plugin/PreluPlugin

## Steps To Reproduce

you can refer to readme of tensorrt-zoo(https://github.com/zerollzeng/tensorrt-zoo), but it might take a long times. so let me describe it simple here:
I am testing a openpose demo since it need a custom prelu layer,  so I write one, at the end of the PreluPlugin.cu I add REGISTER_TENSORRT_PLUGIN(PreluPluginCreator); then I run sample which create an engine file and the produce correct result, but when I try to deserialize from engine file, it report error:
INVALID_ARGUMENT: getPluginCreator could not find plugin Prelu_TRT version 1
safeDeserializationUtils.cpp (259) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
INVALID_STATE: std::exception
INVALID_CONFIG: Deserialize the cuda engine failed.

can you give some advise or hints about this error? I google and search in developer forum but I didn't find information that is helpful to me.

thanks

**Comment by rmccorm4** [comment]
Hi @zerollzeng,

I think when deserializing an engine that contains plugins, you first need to setup your plugins similarly to the way you did when building/serializing the engine, so that the plugins can be looked up during derialization.

> When combined with IPluginCreator it provides a mechanism to register plugins and look up the Plugin Registry during de-serialization.

I see this supporting info in the docs: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Plugin/IPluginV2.html

**Comment by zerollzeng** [comment]
thanks for your quick reply @rmccorm4 
I think I already setup my plugins correctly, this error happen when I refactor my prelu plugin implementation, old version was ok, after compare the difference carefully, I still can't get the reason why it reports this error. I might omit something when refactor implementation. I want to know more information about the error message, what does it mean? did I register the plugin successfully or other cause. here is a snippet of deserialization function, I think it's correct.
```
bool Trt::DeserializeEngine(const std::string& engineFile) {
    std::ifstream in(engineFile.c_str(), std::ifstream::binary);
    if(in.is_open()) {
        spdlog::info("deserialize engine from {}",engineFile);
        auto const start_pos = in.tellg();
        in.ignore(std::numeric_limits<std::streamsize>::max());
        size_t bufCount = in.gcount();
        in.seekg(start_pos);
        std::unique_ptr<char[]> engineBuf(new char[bufCount]);
        in.read(engineBuf.get(), bufCount);
        initLibNvInferPlugins(&mLogger, "");
        mRuntime = nvinfer1::createInferRuntime(mLogger);
        mEngine = mRuntime->deserializeCudaEngine((void*)engineBuf.get(), bufCount, nullptr);
        assert(mEngine != nullptr);
        mBatchSize = mEngine->getMaxBatchSize();
        spdlog::info("max batch size of deserialized engine: {}",mEngine->getMaxBatchSize());
        mRuntime->destroy();
        return true;
    }
    return false;
}
```
by the way, I found a similiar issue in #171

**Comment by zerollzeng** [comment]
thanks @rmccorm4 , this problem has been solved, although I still don't know the exact reason. here is the solution.
the solution is change this funtion from 
```
const char* PReLUPluginCreator::getPluginName() const {
    std::string plugin_type{G_PRELU_TYPE}; 
    std::string plugin_namespace{G_PLUGIN_NAMESPACE};
    return (plugin_type+plugin_namespace).c_str();
}
```
To
```
static const char* G_PRELU_NAME = "PReLU_TRT";
const char* PReLUPluginCreator::getPluginName() const {
    return G_PRELU_NAME;
}
```
I am a little confused, does any one knows the reason?

**Comment by iamsuryan** [comment]
@zerollzeng I am able to successfully desearialize when I test tensorrt engine file. But when I do it inside deepstream 5.0 docker container providing the lib.so for the plugin file because deepstream does deserialize automatically. There it throws this error and I haven't find any help in the forums. Any help would be great.

**Comment by makaveli10** [comment]
@zerollzeng I am able to successfully desearialize when I test tensorrt engine file. But when I do it inside deepstream 5.0 docker container providing the lib.so for the plugin file because deepstream does deserialize automatically. There it throws this error and I haven't find any help in the forums. Any help would be great.

**Comment by zerollzeng** [comment]
@makaveli10 sorry I still don't know the exact reason, too. but perhaps you can take a look at my project tiny-tensorrt and see if it can help you.

**Comment by jinfagang** [comment]
@zerollzeng I am try deserialize a official tensorrt plugin got this error as well. My trt engine generate from onnx2trt, but when try deserialize it back, error occurs

**Comment by zerollzeng** [comment]
@jinfagang Are you using tiny-tensorrt?

**Comment by jinfagang** [comment]
@zerollzeng I am using onnx-tensorrt generates engine, and try deserialize in a simple project which loads tensorrt engine and do forward. Same as tiny-tensorrt does. But that engine involves an official plugin. I don't know how to make it found by my project, Do u got a solution on this? Not plugin implemented self, but official one such as InstanceNormalizationPlugin.

**Comment by zerollzeng** [comment]
Maybe it's related to the IPluginCreator, take a look at https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_plugin_creator.html. btw if it can't find the plugin, most likely it's the name or namespace is not compatible with your model's node.

**Comment by scuizhibin** [comment]
I also meet this  error,when i  deserialize my file of trt。my plugin is DCNv2。How to slove it 。

**Comment by zhangjinsong3** [comment]
@zerollzeng @jinfagang I also meet this error,when i deserialize my engine file. I have no costum pulgin. Did u get a solution?

**Comment by scuizhibin** [comment]
你需要加入一条代码，initlibNvinfer......，


---Original---
From: ***@***.***&gt;
Date: Wed, May 12, 2021 15:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/TensorRT] Custom Plugin: INVALID_ARGUMENT: getPluginCreator could not find plugin Prelu_TRT version 1 (#263)




 
@zerollzeng @jinfagang I also meet this error,when i deserialize my engine file. I have no costum pulgin. Did u get a solution?
 
&mdash;

**Comment by zhangjinsong3** [comment]
@scuizhibin 感谢回复,C++里面增加 initlibNvinferPlugins(),对应python里面应该如何初始化呢

**Comment by scuizhibin** [comment]
好想也有这么一个函数，你找找看


---Original---
From: ***@***.***&gt;
Date: Wed, May 12, 2021 19:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/TensorRT] Custom Plugin: INVALID_ARGUMENT: getPluginCreator could not find plugin Prelu_TRT version 1 (#263)




 
@scuizhibin 感谢回复,C++里面增加 initlibNvinferPlugins(),对应python里面应该如何初始化呢
 
&mdash;

**Comment by zhangjinsong3** [comment]
多谢老哥



---Original---
From: ***@***.***&gt;
Date: Wed, May 12, 2021 19:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/TensorRT] Custom Plugin: INVALID_ARGUMENT: getPluginCreator could not find plugin Prelu_TRT version 1 (#263)




 好想也有这么一个函数，你找找看 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Wed, May 12, 2021 19:26 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [NVIDIA/TensorRT] Custom Plugin: INVALID_ARGUMENT: getPluginCreator could not find plugin Prelu_TRT version 1 (#263) 
 
 
 
 
   
 @scuizhibin 感谢回复,C++里面增加 initlibNvinferPlugins(),对应python里面应该如何初始化呢 
   
 &amp;mdash;
