### ISSUE TITLE
Add SM90 kernels for Stable Diffusion on H100

### ISSUE THREAD

**Issue by skirsten** [NVIDIA/TensorRT#2638]
Currently the `fMHCA` and `fMHA_V2` plugins (and maybe others as well) used by the Stable Diffusion demo only include kernels up to SM89.
It would be great if the SM90 kernels could be added as well so that the NVIDIA H100 is supported.

**Comment by zerollzeng** [comment]
Will check this internally, thanks!

**Comment by rajeevsrao** [comment]
@skirsten there are no plans to update these plugins/kernels for Hopper support. However TensorRT will have out-of-box support for diffusion models in the coming release.

**Comment by skirsten** [comment]
Awesome, thanks for letting me know!
