### ISSUE TITLE
onnx Conv convert error to tensorrt

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#264]
```
In function importConv:
[8] Assertion failed: (nbSpatialDims == 2 && kernel_weights.shape.nbDims == 4) || (nbSpatialDims == 3 && kernel_weights.shape.nbDims == 5)
```

this Conv node has a shape of [64, 64, 1, 1]

![image](https://user-images.githubusercontent.com/21303438/70516440-fc843a80-1b71-11ea-8055-18a5249de8d8.png)

but using an older onnx-tensorrt version, it can going through the assertions.

Does this assertion really valid?

**Comment by rmccorm4** [comment]
What if you specify `explicitBatch`?

**Comment by rmccorm4** [comment]
@jinfagang any update? Or can you share a sample model that reproduces the issue?

**Comment by rmccorm4** [comment]
Closing since no response.

**Comment by QQJayden** [comment]
Excuce me, has the problem been solved?
