### ISSUE TITLE
There is no speed up with trt model compared with pytorch,while the model contains GRU

### ISSUE THREAD

**Issue by jinec** [NVIDIA/TensorRT#2641]
## Description

my model contains CNN modules and bi-gru ,as as follows:

**
x = x.permute(0, 2, 1)
x, _ = self.rnn(x)
**
**
self.rnn = nn.GRU(128, 64, num_layers=2, batch_first=True, bidirectional=True)
**
i test it by codes in the following:
**
trtexec --onnx=model_bline_200.onnx --workspace=4096 --minShapes=input:1x12x3200 --optShapes=input:16x12x3200 --maxShapes=input:16x12x3200 --saveEngine=engine_bline_200.trt --useCudaGraph --dumpProfile --profilingVerbosity=detailed
**
the result is :
![648b56b6f959bb4cafece4933fc4e2c](https://user-images.githubusercontent.com/39627475/216990269-7c9b73e0-c2e6-4830-a0c3-fa9f3a028926.png)

**
trtexec --loadEngine=engine_bline_200.trt --shapes=input:16x12x3200 --useCudaGraph --verbose --dumpProfile
**
the result is :
![b55c3c57109d6120412cc93b48fbf83](https://user-images.githubusercontent.com/39627475/216990485-cd960221-dffe-4f3a-826b-2a4598ee88f0.png)

it shows：the consuming time is the same，that is，There is no speed up with trt model compared with pytorch，the GRU consuming time is 85%+。

my problem is the same as  There is no speed up with trt model compared with pytorch. #1925 @

can you help me ?

## Environment

**TensorRT Version**: 8.5.2.2
**NVIDIA GPU**: 3060
**NVIDIA Driver Version**: 
**CUDA Version**: 11.6
**CUDNN Version**: 8.6
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by jinec** [comment]
the onnx graph is ：
![d68c155040003e9d8288e2ae1d08be1](https://user-images.githubusercontent.com/39627475/216991722-1fd90fea-e666-40ef-991c-6ac24c1c3352.png)

**Comment by jinec** [comment]
the model is here: 
[model_bline_200.zip](https://github.com/NVIDIA/TensorRT/files/10663815/model_bline_200.zip)

**Comment by jinec** [comment]
After I tried these methods, I found：
FP16 can reduced time consumption，form 18.4ms to 14ms
The acceleration  effect of onnx and tensorRT has not been realized， with no more than they ever had before.

**Comment by jinec** [comment]
@zerollzeng Should I remove the nodes in the onnx figure，for example，shape node，Gather node，Unsqeenze node，concat node.

**Comment by zerollzeng** [comment]
You don't need to do this for most of the time, but it does help sometimes if you fixed the onnx input shape and then do constant folding.

**Comment by ttyio** [comment]
closing since no activitity for more than 3 weeks, thanks!
