### ISSUE TITLE
One execution context per optimization profile with dynamic shapes results in broken output (no errors)

### ISSUE THREAD

**Issue by skirsten** [NVIDIA/TensorRT#2648]
## Description

When trying to use one ExecutionContext per optimization profile, after the first reuse e.g.
1. Create context 0, set profile 0
2. Use context 0
3. Create context 1, set profile 1
4. Use context 1
5. Use context 0 <- _broken_

the output is broken. See below for more info.

## Environment

**TensorRT Version**: 8.5.3.1
**NVIDIA GPU**: RTX 3090
**NVIDIA Driver Version**: 520.61.07
**CUDA Version**: 11.8
**CUDNN Version**: 8.7.0.84
**Operating System**: Ubuntu 22.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

This simplified code showcases the problem. Its based off of the https://github.com/NVIDIA/TensorRT/blob/b0c259a749aab1486ed3b4458e7176555b003497/tools/Polygraphy/polygraphy/backend/trt/runner.py#L302 and works basically the same, except that there is one context per optimization profile. This is recommended by the documentation and would allow me to remove the overhead of the optimization profile switching.

```py
def infer(self, profile_index, stream_handle):
    if profile_index in self.contexts:
        context = self.contexts[profile_index]
    else:
        context = self.engine.create_execution_context()

        assert context.set_optimization_profile_async(
            profile_index=profile_index,
            stream_handle=stream_handle,
        )

        self.contexts[profile_index] = context

    for idx in range(self.engine.num_io_tensors):
        name = self.engine.get_tensor_name(idx)

        assert not self.engine.is_shape_inference_io(
            name
        ), "shape inference is not supported"

        assert (
            self.engine.get_tensor_format(name) == trt.TensorFormat.LINEAR
        ), "only linear tensors are supported"

        mode = self.engine.get_tensor_mode(name)

        if mode == trt.TensorIOMode.INPUT:
            shape = ...

            assert context.set_input_shape(name, shape)

            tensor_ptr = ...

            assert context.set_tensor_address(name, tensor_ptr)

        elif mode == trt.TensorIOMode.OUTPUT:
            shape = tuple(context.get_tensor_shape(name))

            tensor_ptr = ...

            assert context.set_tensor_address(name, tensor_ptr)

        else:
            raise RuntimeError(f"Unexpected mode: {mode}")


    assert context.execute_async_v3(stream_handle=stream_handle)

```

```py
engine.infer(0, stream_handle)
engine.infer(1, stream_handle)
engine.infer(0, stream_handle) # output is broken

```

One thing to note is that the methods used should be the v3 variant (e.g. [no profile specific names](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#:~:text=You%20can%20skip%20this%20section%20if%20using%20enqueueV3%20instead%20of%20the%20deprecated%20enqueueV2%2C%20because%20the%20name%2Dbased%20methods%20such%20as%20IExecutionContext%3A%3AsetTensorAddress%20expect%20no%20profile%20suffix.)) yet I still get this warning:
```
[TRT] [W] ICudaEngine::getProfileDimensions: bindingIndex 0 is not in profile 1. Using bindingIndex = 4 instead.
```
Considering I did not call `getProfileDimensions` I would guess that its called internally with the wrong index. Regardless that should not be the problem, just annoying, as the documentation states that this is automatically corrected.

Replacing the start of the example with a single context
```py
if self.context:
    context = self.context

    if context.active_optimization_profile != profile_index:
        assert context.set_optimization_profile_async(
            profile_index=profile_index,
            stream_handle=stream_handle,
        )

else:
    context = self.engine.create_execution_context()

    assert context.set_optimization_profile_async(
        profile_index=profile_index,
        stream_handle=stream_handle,
    )

    self.context = context
```
fixes the problem. **This leads me to believe that there is some additional state outside of the execution context that is changed when calling `set_optimization_profile_async` (e.g. a global symbol?) and causes the output to be broken.**

Also yes, I am aware of this limitation:
> A current exception to this is when using dynamic shapes, when each optimization profile can only have one execution context.
[docs](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#:~:text=used%20for%20multiple%20overlapping%20inference%20tasks.-,(A%20current%20exception%20to%20this%20is%20when%20using%20dynamic%20shapes%2C%20when%20each%20optimization%20profile%20can%20only%20have%20one%20execution%20context.),-To%20perform%20inference%2C%20you%20must%20pass)

This is not the case here as there is a 1to1 mapping between optimization profile <-> execution context.

**Comment by pranavm-nvidia** [comment]
Two questions:

1. Are you doing a `stream.synchronize()` at some point before you return from `infer()`? If not, then it's a non-blocking call and will return before the outputs have been computed and written - so if you try to read them immediately, you might see uninitialized memory instead of the real outputs. 

2. Are you running with optimizations disabled? The reason is that `assert` statements are [optimized out](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement) so you'd never end up running, e.g. `context.set_optimization_profile_async`. One way to mitigate this is to split the call and check:
```py
success = context.set_optimization_profile_async(
            profile_index=profile_index,
            stream_handle=stream_handle,
        )
assert success
```

**Comment by skirsten** [comment]
> Are you doing a stream.synchronize() at some point before you return from infer()

Yes, I left that out as well as the allocation logic.
> Are you running with optimizations disabled?

Just checked, yes: `__debug__ == True`

Thanks for the resource, I will try to write a standalone reproducible using the TrtRunner. Also I forgot to mention, I am using the fMHCA and fMHA_V2 plugins.

**Comment by skirsten** [comment]
I replaced my custom logic above with the TrtRunner and its still the same problem:
```py
if should_reproduce_broken:
    if profile_index in self.runners:
        runner = self.runners[profile_index]
    else:
        runner = TrtRunner(
            self.engine.create_execution_context(),
            optimization_profile=profile_index,
        )
        runner.activate()

        self.runners[profile_index] = runner

else: # working
    if "default" in self.runners:
        runner = self.runners["default"]

        runner.set_profile(profile_index) # Interestingly it also works without this call even when the profile should be != the one in the context. Also the runner.optimization_profile is not update when calling set_profile.
    else:
        runner = TrtRunner(
            self.engine.create_execution_context(),
            optimization_profile=profile_index,
        )
        runner.activate()

        self.runners["default"] = runner

return runner.infer(feed_dict)
```

At the same time I also tried to reproduce it in a similar self-contained example like linked above but I was unable to reproduce it there... This is very strange. I will continue investigating tomorrow.

**Comment by skirsten** [comment]
After a lot of debugging I managed to track down the problem:
```py
import copy

import numpy as np
import requests
from numpy.random import default_rng
from polygraphy.backend.common import bytes_from_path
from polygraphy.backend.trt import (
    CreateConfig,
    Profile,
    TrtRunner,
    engine_from_bytes,
    engine_from_network,
    network_from_onnx_bytes,
)

engine_test = "unet"
should_reproduce = True

if engine_test == "unet":
    engine = engine_from_bytes(bytes_from_path("unet-2-64.plan"))

    def get_input(seed):
        return {
            "sample": default_rng(seed).standard_normal(
                (2, 4, 64, 64), dtype=np.float32
            ),
            "timestep": default_rng(seed).standard_normal((1,), dtype=np.float32),
            "encoder_hidden_states": default_rng(seed)
            .standard_normal((2, 77, 768), dtype=np.float32)
            .astype(np.float16),
        }

    def get_output(output):
        return copy.deepcopy(output["latent"])

elif engine_test == "vae":
    engine = engine_from_bytes(bytes_from_path("vae-1-64.plan"))

    def get_input(seed):
        return {
            "latent": default_rng(seed).standard_normal(
                (1, 4, 64, 64), dtype=np.float32
            ),
        }

    def get_output(output):
        return copy.deepcopy(output["images"])

elif engine_test == "identity":
    # From https://github.com/NVIDIA/TensorRT/blob/b0c259a749aab1486ed3b4458e7176555b003497/tools/Polygraphy/examples/api/07_tensorrt_and_dynamic_shapes/example.py
    profiles = [
        # The low-latency case. For best performance, min == opt == max.
        Profile().add("X", min=(1, 3, 28, 28), opt=(1, 3, 28, 28), max=(1, 3, 28, 28)),
        # The dynamic batching case. We use `4` for the opt batch size since that's our most common case.
        Profile().add("X", min=(1, 3, 28, 28), opt=(4, 3, 28, 28), max=(32, 3, 28, 28)),
        # The offline case. For best performance, min == opt == max.
        Profile().add(
            "X", min=(128, 3, 28, 28), opt=(128, 3, 28, 28), max=(128, 3, 28, 28)
        ),
    ]

    url = "https://github.com/NVIDIA/TensorRT/raw/b0c259a749aab1486ed3b4458e7176555b003497/tools/Polygraphy/examples/api/07_tensorrt_and_dynamic_shapes/dynamic_identity.onnx"
    engine = engine_from_network(
        network_from_onnx_bytes(requests.get(url).content),
        config=CreateConfig(profiles=profiles),
    )

    def get_input(seed):
        return {
            "X": default_rng(seed).standard_normal((1, 3, 28, 28), dtype=np.float32),
        }

    def get_output(output):
        return copy.deepcopy(output["Y"])


runner = TrtRunner(engine.create_execution_context(), optimization_profile=0)

if not should_reproduce:
    engine.create_execution_context()

    # If running before any inference, its okay
    # TrtRunner(engine.create_execution_context(), optimization_profile=1)

first = []
with runner:
    for i in range(10):
        first.append(get_output((runner.infer(get_input(i)))))

if should_reproduce:
    # If you now create a new context it will break the previous context.
    
    # This is enough to break it:
    engine.create_execution_context()
    
    # You don't even have to create a Runner / set_profile etc:
    # TrtRunner(engine.create_execution_context(), optimization_profile=1)

second = []
with runner:
    for i in range(10):
        second.append(get_output(runner.infer(get_input(i))))

for i in range(len(first)):
    diff = np.sum(np.abs(first[i] - second[i])) / second[i].size
    print(i, diff)

```

The problem is apparently:
1. create a context
2. run some inference on it
3. create another context (no need to use it or even change the optimization profile)
4. run more inference on first context. Its broken.

I was able to reproduce this only on the unet from the diffusion demo. The vae and the "identity" network work fine.
"Its broken." means that the average difference per element is ~0.5.
Also I am not so sure anymore if this has anything to do with optimization profiles, or if the bug is just in the create_execution_context logic.

Luckily the workaround was easy for me. Just create all the contexts before any inference. Still lost a lot of time on this bug :(

**Comment by pranavm-nvidia** [comment]
Thanks for investigating! Given that it's only happening in this network, I strongly suspect there's a bug in the plugin implementation (as opposed to a more fundamental issue in TensorRT). I've filed a bug internally so we can track this.

**Comment by rajeevsrao** [comment]
@skirsten TensorRT 8.6 supports SD pipelines out-of-box (without need for plugins) and this issue is not applicable/reproducible. Let us know if you are still facing issues.
