### ISSUE TITLE
Is it supporting to quantize all the layers of diffusion model instead of only quantizing the linear layer.

### ISSUE THREAD

**Issue by Christianqling2** [NVIDIA/TensorRT#2652]
## Description

Same as title

## Environment

**TensorRT Version**: 
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by rajeevsrao** [comment]
@Christianqling2 we do not support quantization of diffusion model. The plugins only support float/half precision.

**Comment by ttyio** [comment]
closing since no activitity for more than 3 weeks, thanks!
