### ISSUE TITLE
set --int8 in trtexec , but the kernel use fp16/fp32 kernel

### ISSUE THREAD

**Issue by lk137095576** [NVIDIA/TensorRT#2658]
I do :
1. I generate BERT(huggingface, onnx ) engine using trtexec with --int8 
2. profile the model with  'ncu xxx.ncu-rep  trtexec  .... --outputIOFormats=int8:chw --int8'

GPU: A100   TRT: v8502

I see the kernel in nsight computer, I find though I set --int8, but the kernel also use FFMA , sgemm.
I want to know:
1. why not use kernel with int8 ?
2. Can I use int8 kernel force ?
3. The result show: --int8 is slow than --fp16, How can I get the most Fastest config？

**Comment by zerollzeng** [comment]
Currently we don't support OOTB INT8 PTQ for transformer-based networks due to accuracy, so it will fallback to FP16/FP32 internally. 

You can try our [demoBERT](https://github.com/NVIDIA/TensorRT/tree/main/demo/BERT)

**Comment by lk137095576** [comment]
> Currently we don't support OOTB INT8 PTQ for transformer-based networks due to accuracy, so it will fallback to FP16/FP32 internally.
> 
> You can try our [demoBERT](https://github.com/NVIDIA/TensorRT/tree/main/demo/BERT)

I got it, thanks.
