### ISSUE TITLE
Q: is there a layer that can do "select by index ?"

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#266]
## Description

assume :
X = [ 2, 3, 4, 5, 6, 7, 8]
idx = [ 2, 3 ]
S_X = X[idx]   ===> S_X = [4, 5]

## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by 1-800-BAD-CODE** [comment]
I'll second that it would be useful to have in a future release an `IIndexSelectLayer` that mimics `torch.index_select`. It would provide a key part of some beam search algorithms.

**Comment by rmccorm4** [comment]
@pranavm-nvidia Can this be achieve with a Select layer or some other workaround?

**Comment by 1-800-BAD-CODE** [comment]
Although the documentation is limited, it looks like an `IGatherLayer` is essentially an `index_select`. I'll try it this week.

**Comment by rmccorm4** [comment]
> it looks like an IGatherLayer is essentially an index_select. I'll try it this week.

In case it helps: https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleNMT/model/softmaxLikelihood.cpp#L75-L79

**Comment by pranavm-nvidia** [comment]
Yeah, Gather is what you want here

**Comment by rmccorm4** [comment]
@1-800-BAD-CODE did it work out for you?

**Comment by 1-800-BAD-CODE** [comment]
> @1-800-BAD-CODE did it work out for you?

Yes it seems to be the correct solution here.
