### ISSUE TITLE
How to use INT8 quantization in plugin while saving GPU memory?

### ISSUE THREAD

**Issue by LitLeo** [NVIDIA/TensorRT#2661]
## Environment

**TensorRT Version**:  TensorRT 7.2.x
**NVIDIA GPU**: T4
**NVIDIA Driver Version**:  Driver Version: 450.119.03
**CUDA Version**: CUDA10.2

I want to use INT8 quantization in MoE plugin to save GPU memory. The MoE plugin has a lot of weights.
There are two ways to pass weight into plugin, (1)quantize weights first and add_constant(like onnx parser) and plugin's  member variable(like embLayerNormPlugin in TRTOOS)

**The first way**, add_constant dose not support INT8 weights because TRT performs the weights quantization itself. (https://forums.developer.nvidia.com/t/unable-to-load-parse-onnx-network-with-int8-operations/170582/2)

**The second way** has the problem of not releasing the GPU memory in time.
The plugins provided in TensorRT-OSS (such as embLayerNormPlugin, fcPlugin), resource (GPU memory, handle, etc.) , in 7.x, are placed in the constructor func, like
```
EmbLayerNormVarSeqlenPlugin::EmbLayerNormVarSeqlenPlugin(const std::string& name, const DataType type,
    const Weights& beta, const Weights& gamma, const Weights& wordEmb, const Weights& posEmb, const Weights& tokEmb)
    : mLayerName(name)
    , mLd(beta.count)
    , mType(type)
{
    mBeta.convertAndCopy(beta, nvinfer1::DataType::kFLOAT);
    mGamma.convertAndCopy(gamma, nvinfer1::DataType::kFLOAT);
   ...
```
In the build phase, the calling order of each function of trt plugin is as follows
```
// build 阶段
1. Plugin::Plugin
2. Plugin::clone
3. Plugin::Plugin
4. Plugin::destroy
5. Plugin::clone
6. Plugin::Plugin
7. Plugin::clone
8. Plugin::Plugin
9. Plugin::clone
10. Plugin::Plugin
11. Plugin::destroy
12. Plugin::initialize
13. Plugin::destroy
14. Plugin::terminate
15. Plugin::destroy
16. Plugin::destroy

```

1. It is expected that only one copy of the resources in the plugin will be kept during the build or infer phase.
2. The resource application is placed in the constructor. Every time a plugin class is cloned, a resource will be applied.
3. According to the above function call sequence, it can be found that in the build phase, before step 11 destroy, there are four resources stored in the GPU memory.

So what should i do now

**Comment by zerollzeng** [comment]
@ttyio Do you have any suggestions here?

**Comment by ttyio** [comment]
@LitLeo , could you try 8.5? we support `constant(int8) -> DQ -> ...`, thanks!

**Comment by LitLeo** [comment]
OK, it seems that there is no good solution, thx.

**Comment by ttyio** [comment]
closing old issues that is inactive for long time, thanks all!
