### ISSUE TITLE
Tensorrt Conversion For stable diffusion 2.1 is not working 

### ISSUE THREAD

**Issue by mabdullahrafique** [NVIDIA/TensorRT#2667]
Hello,
Tensorrt Conversion for stable diffusion 1.5 is working fine. But when we are trying to convert stable diffusion 2.1, first of all it doesn't compile with unsupported operands. But upon further working we were able to compile it successfully but now it's producing black images only.
Can you please give us detailed guidelines for conversion of sd2.1 which works ?

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by rajeevsrao** [comment]
@mabdullahrafique there is a known issue with plugin support for SD v2.1. v2.1-base should work. The upcoming release of TensorRT 8.6 EA will support newer SD versions out-of-box (without plugins). Stay tuned.

**Comment by mabdullahrafique** [comment]
Expected ETA for TensorRt 8.6 release?

**Comment by Jack47** [comment]
any updates? we really need this~

**Comment by rajeevsrao** [comment]
@mabdullahrafique  @Jack47 the new `demoDiffusion` code in `release/8.6` branch supports SD v2.1 pipeline.

**Comment by yuxgis** [comment]
It still have this problem with `release/8.6` in A100 GPU.

**Comment by lucasjinreal** [comment]
@rajeevsrao  Please reopen this, I still can not get 2.1 work on 8.6.1. Just black images.
