### ISSUE TITLE
Version 99.0.0 on PyPI

### ISSUE THREAD

**Issue by matan-feldman** [NVIDIA/TensorRT#2668]
Hey 🙂
I had just noticed there's a new version for `pip install` on PyPI - 99.0.0 .
However, I couldn't find a release note for this version or any explanation regarding what's its equivalent version in your "regular" version count (e.g. 8.5.3).

Could you please shed some light on this version?
Thanks a lot in advance! 🙏

**Comment by zhiqwang** [comment]
https://pypi.org/project/tensorrt/ I guess we can use `pip install tensorrt` now on Linux platform.

**Comment by pranavm-nvidia** [comment]
Right, the `nvidia-tensorrt` package is now just a placeholder package which redirects to `tensorrt`. The version is set to 99.0.0 so that it will always overwrite previous versions of the `nvidia-tensorrt` package.

**Comment by matan-feldman** [comment]
Got it, thanks a lot!
