### ISSUE TITLE
When I run the trex with process_engine.py, it said pynvml.nvml.NVMLError_NotSupported: Not Supported

### ISSUE THREAD

**Issue by songkq** [NVIDIA/TensorRT#2669]
@SimengLiu-nv Hi, could you please give some advice for this error.
`process_engine.py`
```
mem_clks = pynvml.nvmlDeviceGetSupportedMemoryClocks(handle)
pynvml.nvml.NVMLError_NotSupported: Not Supported
```
myenv: TensorRT 8.5.3.1, RTX3090, python3.8.13, cuda11.1

**Comment by SimengLiu-nv** [comment]
Hi @songkq, would you like to try if [this ](https://github.com/pytorch/serve/issues/1722) discussion solves the problems? If not, would you like to share the steps to repro the error?

**Comment by songkq** [comment]
@SimengLiu-nv Thanks. I've solve the problem following #1722
