### ISSUE TITLE
Unable to convert Stable Diffusion 2.1

### ISSUE THREAD

**Issue by MuhammadArham-43** [NVIDIA/TensorRT#2670]
I worked on converting Stable Diffusion 2.1 to a TensorRT engine for faster inference. 

I had to change the embedding dimensions of the model from 768 to 1024. The model was generated without errors after this but it is generating only black images.

Can you add support for Stable Diffusion 2.1 or help solve this issue?

**Comment by zerollzeng** [comment]
Please refer to  https://github.com/NVIDIA/TensorRT/issues/2667

**Comment by ttyio** [comment]
closing since no activitity for more than 3 weeks, thanks!

**Comment by lucasjinreal** [comment]
@ttyio Please reopen it, am also facing same issue, the engine generated, but images are black for 2.1 model (1.5 normal)

**Comment by ttyio** [comment]
@lucasjinreal  are you using release/8.6 branch with TRT8.6GA?

**Comment by lucasjinreal** [comment]
@ttyio Am using 8.6.1 which I think can not be more fresh
