### ISSUE TITLE
TRTExec Conversion memory exceeds workspace size

### ISSUE THREAD

**Issue by FabianSchuetze** [NVIDIA/TensorRT#2679]
## Description

I am interesting in performing a onnx-trt conversion with as little GPU memory as possible. At the moment, I  use the following command for trtexec:
```
trtexec --onnx=model.onnx --saveEngine=model.plan --fp16 --workspace=500
```
When log the memory consumption, I however see that sometimes gpu memory used by trtexe exceeds 500 mb, up to ~1.5gb. 

- Is there a way I can restrict total memory consumption during conversion with workspace size?
- Are there any other suggestions I could use to limit conversion memory? 

## Environment

**TensorRT Version**: NVIDIA TensorRT Version 8.5.0
**NVIDIA GPU**: NVIDIA GeForce RTX 2080 Ti
**NVIDIA Driver Version**: 470.161.03
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
`--workspace=500` is deprecated. you can try `--memPoolSize`

**Comment by ttyio** [comment]
closing since no activitity for more than 3 weeks, thanks!
