### ISSUE TITLE
How to use IPluginCreator with caffe?

### ISSUE THREAD

**Issue by twmht** [NVIDIA/TensorRT#268]
Hi,

In tensorRT there is a createClipPlugin (https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/_nv_infer_plugin_8h.html) which can give me a RELU6 layer.

it's based on IPuginV2, but IPluginFactoryV2 don't support deserialization.

The only way to support deserialization is to use IPluginFactory.

```
virtual IPlugin* nvinfer1::IPluginFactory::createPlugin | ( | const char * | layerName,
  |   | const void * | serialData,
  |   | size_t | serialLength
  | )
```

I see some suggestions is to use IPluginCreator, but I can't find any usage of IPluginCreator in caffe parser (https://github.com/NVIDIA/TensorRT/blob/master/parsers/caffe/caffeParser/caffeParser.cpp).

The only way to work with caffe parser is to use IPluginFactory (https://github.com/NVIDIA/TensorRT/blob/master/parsers/caffe/caffeParser/caffeParser.cpp#L446) or IPluginFactoryV2 (https://github.com/NVIDIA/TensorRT/blob/master/parsers/caffe/caffeParser/caffeParser.cpp#L482)

And I think you should add more built-in plugins here (https://github.com/NVIDIA/TensorRT/blob/master/parsers/caffe/caffeParser/caffeParser.cpp#L514)

Does IPluginCreator support caffe? Where is the line of the parser?

**Comment by twmht** [comment]
ok.. I find the line https://github.com/NVIDIA/TensorRT/blob/master/parsers/caffe/caffeParser/caffeParser.cpp#L375

but it only stores the plugin name in mPluginRegistry, and the parsing part is https://github.com/NVIDIA/TensorRT/blob/master/parsers/caffe/caffeParser/caffeParser.cpp#L541

but this part can only support `Normalize`, `PriorBox`, `DetectionOutput` and  `RPROI`, not the user-defined plugin name.

```
                std::string pluginName;
                nvinfer1::PluginFieldCollection fc;
                std::vector<nvinfer1::PluginField> f;
                if (layerMsg.type() == "Normalize")
                {
                    pluginName = "Normalize_TRT";
                    f = parseNormalizeParam(layerMsg, weights, *mBlobNameToTensor);
                }
                else if (layerMsg.type() == "PriorBox")
                {
                    pluginName = "PriorBox_TRT";
                    f = parsePriorBoxParam(layerMsg, weights, *mBlobNameToTensor);
                }
                else if (layerMsg.type() == "DetectionOutput")
                {
                    pluginName = "NMS_TRT";
                    f = parseDetectionOutputParam(layerMsg, weights, *mBlobNameToTensor);
                }
                else if (layerMsg.type() == "RPROI")
                {
                    pluginName = "RPROI_TRT";
                    f = parseRPROIParam(layerMsg, weights, *mBlobNameToTensor);
                }

                if (mPluginRegistry.find(pluginName) != mPluginRegistry.end())

```

any idea?

**Comment by rmccorm4** [comment]
Hi @twmht,

Please see this sample for adding custom layers with the Caffe parser: https://github.com/NVIDIA/TensorRT/tree/release/7.0/samples/opensource/samplePlugin
