### ISSUE TITLE
Support FMHA kernels for training

### ISSUE THREAD

**Issue by tanyokwok** [NVIDIA/TensorRT#2684]
## Description

Hi, all. I can speed up the SD 1.5 exceeding 66it/s on A100 Nv GPU with TensorRT. The performance delivered by TensorRT is impressive.

I'm curious if we will support fmha kernel for the training workloads. Because I am doing some interesting work to accelerate training with TensorRT(or its fancy kernels). But I found the fmha doesn't return log(sum(exp)) intermediate outputs that will be required by backward propagation of the flash attention. The fmha backward propagation kernel was not provided as well.

I appreciate that if the fmha can support kernel interface in something like xformers: https://github.com/facebookresearch/xformers/blob/main/xformers/ops/fmha/__init__.py#L41

**Comment by zerollzeng** [comment]
TensorRT is only targeted for inference, we don't support training.
