### ISSUE TITLE
Set Permissions for Github Actions

### ISSUE THREAD

**Issue by joycebrum** [NVIDIA/TensorRT#2686]
## Description

Github Workflow by default set all permissions to write, which could be a vulnerability to be explored in case of the workflow got compromised. 

Using credentials that are minimally scoped is also a recommendation from the OpenSSF Scorecard ([Token-Permission Check](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)) and the Github ([Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)).

Can I suggest a PR setting the permission to the project's workflows?

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by rajeevsrao** [comment]
Updated the workflow permissions to read-only. @joycebrum thanks for the tip!
