### ISSUE TITLE
How to write trt verbose information to the log file?

### ISSUE THREAD

**Issue by shhn1** [NVIDIA/TensorRT#2687]
## Environment

**TensorRT Version**: 8.5.1.7
**NVIDIA GPU**: V100
**CUDA Version**: 11.8

I have tried the following two ways to write verbose to a log file and it worked.

`1. trtexec --onnx=model.onnx --saveEngine=model.engine --verbose ＞ log.txt`
`2. python trt_builder.py > log.txt`

Howerver, I want to  write verbose to a log file just when I run the `trt_builder.py` script. What should I do if I want to do this? Should I inherit the trt.ILogger class? It would be great if you can provide me with a related demo script.

ps. I wrote `trt_builder.py` with reference to this script `TensorRT/samples/python/efficientdet/build_engine.py`

**Comment by zerollzeng** [comment]
Yes you can inherit and rewrite the trt.ILogger class to write the verbose log to file.

**Comment by ttyio** [comment]
closing since no activitity for more than 3 weeks, thanks!
