### ISSUE TITLE
Unpooling and Pooling with indices.

### ISSUE THREAD

**Issue by bpinaya** [NVIDIA/TensorRT#27]
Hi there, any timelines or updates on unpooling? And also pooling with indices?
Pooling with indices and unpooling have been on ONNX since 1.3 and there are many segmentation models that could benefit from it, specially for segmentation applications.

I plan to look into it and now that TRT is OS, any similar layers I can check as samples? I think the interesting part would be the storage of those indices. Any help is appreciated!

**Comment by rmccorm4** [comment]
Hi @bpinaya,

It seems these aren't yet supported, Hopefully, they'll be added in the future.

I believe you can track this list for an up-to-date version of what ONNX ops are supported by the ONNX parser: https://github.com/onnx/onnx-tensorrt/blob/master/operators.md
