### ISSUE TITLE
[Jetson Nano] TensorRT-5.1.5.0/lib/libnvinfer.so:  error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by FXRer** [NVIDIA/TensorRT#270]
I followed the guide in the README.md for building the Plugins or Parsers : 
# 1. Build Plugins
$ cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out  \
-DBUILD_PLUGINS=ON -DBUILD_PARSERS=OFF -DBUILD_SAMPLES=OFF \
-DCUDA_VERSION=10.0
$ make -j$(nproc)

And I got following error : 
[ 50%] Linking CXX shared library ../out/libnvinfer_plugin.so
~/Downloads/TensorRT-5.1.5.0/lib/libnvinfer.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
plugin/CMakeFiles/nvinfer_plugin.dir/build.make:754: recipe for target 'out/libnvinfer_plugin.so.5.1.5.0' failed
make[2]: *** [out/libnvinfer_plugin.so.5.1.5.0] Error 1
CMakeFiles/Makefile2:195: recipe for target 'plugin/CMakeFiles/nvinfer_plugin.dir/all' failed
make[1]: *** [plugin/CMakeFiles/nvinfer_plugin.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

# 2. Build Parsers
cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out \
         -DBUILD_PLUGINS=OFF -DBUILD_PARSERS=ON -DBUILD_SAMPLES=OFF \
-DCUDA_VERSION=10.0
$ make -j$(nproc)

And I got following error : 
~/Downloads/TensorRT-5.1.5.0/lib/libnvinfer.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
parsers/onnx/CMakeFiles/getSupportedAPITest.dir/build.make:141: recipe for target 'parsers/onnx/getSupportedAPITest' failed
make[2]: *** [parsers/onnx/getSupportedAPITest] Error 1
CMakeFiles/Makefile2:428: recipe for target 'parsers/onnx/CMakeFiles/getSupportedAPITest.dir/all' failed
make[1]: *** [parsers/onnx/CMakeFiles/getSupportedAPITest.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

My system : 
Jetson Nano + Ubuntu-18.04  + Cuda-10.0 + cuDNN-7.5 + TensorRT-5.1.5

Could you give me some hint please ?

Thanks in advance,

**Comment by FXRer** [comment]
I found myself the root cause : Since I built the plugins and parsers within Jetson Nano but $TRT_RELEASE/lib points to the  x86 based libraries.

Sorry for this inconvenience.

**Comment by j-o-d-o** [comment]
But how is this solved? I cant find any TensorRT binary release for the ARM. What path did you put the $TRT_RELEASE to on the Jetson Nano?

**Comment by rmccorm4** [comment]
Hi @j-o-d-o,

TensorRT is released for Jetson via Jetpack: https://developer.nvidia.com/embedded/jetpack

TRT6 is available in Jetpack 4.3, TRT7 hasn't been  .

 This thread might also help: https://github.com/NVIDIA/TensorRT/issues/244#issuecomment-561031150. See the devtalk thread in last comment
