### ISSUE TITLE
About TensorRT on multiple GPUs

### ISSUE THREAD

**Issue by Jsy0220** [NVIDIA/TensorRT#2702]
I have read the suggestions about running `tensorrt` on multiple GPUs on [https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#faq](url), and I have a little question that does it need to call `cudaSetDevice()` before `IExecutionContext::setBindingDimensions` when using dynamic dimensions input?

**Comment by zerollzeng** [comment]
Just "ensure that the thread is associated with the correct device by calling cudaSetDevice() if necessary." when deserializing the engine in a thread, if you already call `cudaSetDevice()` to bind the GPU, I think you don't need to call it again.
