### ISSUE TITLE
Encountered known unsupported method torch.randn/torch.Tensor.get_device/torch.Tensor.cuda 

### ISSUE THREAD

**Issue by kshamaramesh** [NVIDIA/TensorRT#271]
## Environment

**TensorRT Version**: 5.1.5 GA
**GPU Type**: 
**Nvidia Driver Version**: 410
**CUDA Version**: 10.0
**CUDNN Version**: 
**Operating System + Version**: UBUNTU 16/04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.3.1
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @kshamaramesh,

Please provide code and commands to reproduce this issue as described in the issue template.

**Comment by rmccorm4** [comment]
Closing since no response.
