### ISSUE TITLE
The output of plugin is correct but changed by TRT, which thus delivers wrong results for downstreaming

### ISSUE THREAD

**Issue by SakuraRiven** [NVIDIA/TensorRT#2710]
## Description

Hi, we have a customed plugin and found that the outputs in its ```kernel.cu``` is correct by saving outputs into .bin for comparison. However, the outputs of tensorrt from corresponding nodes have been heavily changed, so the final results are wrong. It seems like the output memory of plugin is occupied and polluted by other operations.

We add onnx-node for plugin as final outputs of entire model to protect memory from changing by TRT and it works for FP32 model. 

However, when it comes to FP16 model, the above problem appears again. So how could we prevent the outputs of plugin from changing by TRT? Are there some official codes rather than onnx-node things?

BTW our plugin contains __atomic operations__. Does it matter?

Thanks for your help : )

## Environment

**TensorRT Version**: 8.4.3.1
**NVIDIA GPU**: GA102 [GeForce RTX 3080 Ti]
**NVIDIA Driver Version**: 510.85.02
**CUDA Version**: 11.4
**CUDNN Version**: 8.0.5
**Operating System**: linux
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
Can you provide a reproduce for this? cc @ttyio @samurdhikaru

**Comment by zerollzeng** [comment]
How can I reproduce your error? please describe the reproduce steps, I think we would need real inputs to check.

**Comment by ttyio** [comment]
@SakuraRiven 
Could you also try adding the check for output `inOut[3]` data type and layout in function `supportsFormatCombination` ?

**Comment by SakuraRiven** [comment]
@ttyio @zerollzeng The problem is successfully solved! OTZ

As you mentioned above, we add the check for inOut[3] which is proved to protect the output of plugin. Our model could thus produce the correct results finally.

Thanks : )
