### ISSUE TITLE
The issue of GPU usage in tensorrt dla inference models

### ISSUE THREAD

**Issue by jacker-whh** [NVIDIA/TensorRT#2711]
Please provide the following info (tick the boxes after creating this topic):
Software Version
 DRIVE OS 6.0.5
 DRIVE OS 6.0.4 (rev. 1)
[*] DRIVE OS 6.0.4 SDK
 other

Target Operating System
[*] Linux
 QNX
 other

Hardware Platform
 DRIVE AGX Orin Developer Kit (940-63710-0010-D00)
 DRIVE AGX Orin Developer Kit (940-63710-0010-C00)
 DRIVE AGX Orin Developer Kit (not sure its number)
[*] other

SDK Manager Version
 1.9.1.10844
[*] other

Host Machine Version
 native Ubuntu Linux 20.04 Host installed with SDK Manager
 native Ubuntu Linux 20.04 Host installed with DRIVE OS Docker Containers
 native Ubuntu Linux 18.04 Host installed with DRIVE OS Docker Containers
[*] other

When I ran our deep learning model using tensorrt’s DLA0 and DLA1, it was clear that only a few operators were running on the GPU, and we found that GR3D_FREQ 40% when we tested with tegrastats.

However, using Nsight Systems analysis, we found that GPU resources take up very little resources and time, as shown in the figure below.
![image](https://user-images.githubusercontent.com/59286797/221777031-699e7be6-9525-4aab-bc0b-a9bde48b6cc6.png)

What is this phenomenon and how is tegrastats’ GPU share calculated?

**Comment by zerollzeng** [comment]
Okay, this is not related to TRT, but I can give some input here.

The usage you see in tegrastats is sample from the time series. and it only query whether the GPU is busy or not. e.g. in 1 second, tegrastats sample the GPU for 1000 times, and 400 times the GPU return "I'm busy(some works one me)". then you will see the usage is 40%.

**Comment by jacker-whh** [comment]
@zerollzeng Thank you so much

**Comment by jacker-whh** [comment]
@zerollzeng  Is there a better tool on Drive Orin to count GPU usage, like NVIDIA-SMI?

**Comment by zerollzeng** [comment]
I don't think there are any realtime tools like tegrastats, but nsight system and nsight compute can give more information.

**Comment by jacker-whh** [comment]
> I don't think there are any realtime tools like tegrastats, but nsight system and nsight compute can give more information.

OK
