### ISSUE TITLE
Missing API call for getting exact TensorRT version

### ISSUE THREAD

**Issue by balazon** [NVIDIA/TensorRT#2713]
NvInferVersion.h has these macro defines:
NV_TENSORRT_MAJOR
NV_TENSORRT_MINOR
NV_TENSORRT_PATCH
NV_TENSORRT_BUILD

for example for TensorRT version 8.5.2.2 I would have 
#define NV_TENSORRT_MAJOR 8 //!< TensorRT major version.
#define NV_TENSORRT_MINOR 5 //!< TensorRT minor version.
#define NV_TENSORRT_PATCH 2 //!< TensorRT patch version.
#define NV_TENSORRT_BUILD 2 //!< TensorRT build number.

My main issue is currently I haven't found a simple call that would return these values.

I can just use these macros directly from cpp sure, but that means after compiling, the exact version numbers will be compiled into the executable.
But when deploying the executable on another machine (in another container for example) which might have a slightly different TensorRT version, my executable will be run, and a different TensorRT is used for the run. So the libnvinfer.so.8 will point to a different version then when compiling, and I can't easily tell from my code which version I'm using at runtime.

This matters because according to the documentation, an engine file is dependent on TensorRT version, and also gpu type:
https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-853/developer-guide/index.html#report-functional-issue
"
Since the TensorRT engine is specific to a specific TensorRT version and a specific GPU type, do not build the engine in one environment and use it to run it in another environment with different GPUs or dependency software stack, such as TensorRT version, CUDA version, cuDNN version, and so on. Also, ensure that the application is linked to the correct TensorRT and cuDNN shared object files by checking the environment variable LD_LIBRARY_PATH (or %PATH% on Windows).
"

More specifically it says engine files are dependent on:
 - major, minor, patch, and build versions of TensorRT
 - compute capability (major and minor versions)
https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-853/developer-guide/index.html#compatibility-serialized-engines

So I might have code that builds an engine file, with TensorRT and compute cabability versions included in the filename. When initializing I want to check already built engine files if I can skip rebuilding the engine. But I can only check the statically compiled version from the code with the NV_TENSORRT_* macros. I have no simple way of telling which dynamically linked version is used against my code. 
For example I can have an engine file built for TensorRT 8.5.2.2, for some compute capability, but on a cloud/k8s maybe there is only TensorRT 8.2.4.2 installed. This means some functions might not even be available, like config->setMemoryPoolLimit, or context->setTensorAddress, which are new. But putting that aside if even if I use code compatible with both of them, I can't fall back to building the engine file on the spot, for a slightly different engine file, unless I first try to deserialize the engine file which might crash my whole application, and which might not be so easy to catch and handle, instead of a simple check of what version I have available at runtime.

I tried to do this and of course what happened was I had an engine file for 8.2.4.2, and the compiled app inside the container was checking the Tensor RT version from the macros, and it said it had 8.2.4.2 version, even though it was using 8.5.2.2. So it found the engine file for 8.2.4.2, and tried to deserialize it, and of course deserialization dropped something like:
1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 205)

Now I'm trying to work around the problem, since I found some functions that return the version:
https://github.com/NVIDIA/TensorRT/blob/ad932f72126f875392a4336d9ee45b2756d934a0/include/NvInferRuntimeCommon.h#L1107-L1110
IPluginCreator has a function like that, and some other plugin extension classes have similar functions.
But it's not a static member function, which means I have to get the list of plugin creators, and if I'm lucky there will be at least one, and then I can use the first plugin creator's getTensorRTVersion function to get the (hopefully) dynamic version.
My problem with this approach is it does not even include the build number, only major, minor, and patch numbers are included in this:

```
static constexpr int32_t kNV_TENSORRT_VERSION_IMPL
    = (NV_TENSORRT_MAJOR * 1000) + (NV_TENSORRT_MINOR * 100) + NV_TENSORRT_PATCH; // major, minor, patch
```

So what I propose is it would be nice to have a function inside one of the headers, which returns the whole version, something like this:
```
int getTensorRTVersion()
{
    return NV_TENSORRT_MAJOR * 1000) + (NV_TENSORRT_MINOR * 100) + NV_TENSORRT_PATCH * 10 + NV_TENSORRT_BUILD;
}
```

I know according to the documentation I should have the same Tensor RT versions, same compute capabilities everywhere, and then I wouldn't run into issues like this. But that is a very simplified view of it all , and it does not justify the lack of being able to query the exact runtime version of TensorRT being used.

What do you think? Is this a reasonable request?
Thanks

**Comment by zerollzeng** [comment]
1. Difference build number usually means internal bug fix. Usually we don't release 2 version that has only difference in build number unless there are some critical bugs that need to be fixed. So I think major, minor, and patch should be enough for most of the use cases.
2. If you really need the full version number, maybe just parse and read the header file in your code, or you can read it from the TRT libraries: 
```$ nm -D libnvinfer.so.* | grep tensorrt_version
00000000abcd1234 B tensorrt_version_#_#_#_#
```

**Comment by oxana-nvidia** [comment]
Hi @balazon,
We are planning to introduce such function in TensorRT 8.6. (EA release is planned very soon). Work name `getInferLibVersion` (subject to change as there is no official release yet :) )
But I guess, you would like more an option called version compatibility of plan files that we also introducing in TensorRT 8.6. This feature will allow you to build engines with one version and run them with another version of TensorRT. 

Please join our talk about this feature on GTC 2023
https://www.nvidia.com/gtc/session-catalog/?tab.catalogallsessionstab=16566177511100015Kus&search=tensorRT#/session/1666632585772001nPD0

I'm closing this request. Please check TensorRT 8.6 when it is released.

**Comment by balazon** [comment]
I tried the plugincreator's getter function and it's working, but looking forward to this new function, or the compatibility feature could make this even better.
Thank you

**Comment by pwuertz** [comment]
@oxana-nvidia Although the TensorRT C API now has `getInferLib[Major|Minor|Patch|Build]Version()` for obtaining the version of the loaded trt library, the [TensorRT Python bindings](https://github.com/NVIDIA/TensorRT/blob/release/10.7/python/src/infer/pyCore.cpp) don't export those functions yet.

As a workaround we could probably call the functions via `ctypes`, but including them in the official Python API as well would be nice.

**Comment by oxana-nvidia** [comment]
@pwuertz Thank you for your suggestion. There are currently no plans to implement such python bindings as they are more .so/.dll file properties and ctypes is an intended way to use them:
```
handle = ctypes.CDLL(lib_file)
print(handle.getInferLibMajorVersion())
```

I've filed an internal feature request for API team to consider.
