### ISSUE TITLE
TypeError when trying to load a 'quantized' model

### ISSUE THREAD

**Issue by AdrianoSimonetto** [NVIDIA/TensorRT#2714]
## Description

Hi, I am using the module for Quantization Aware Training and I have some issues.
I am saving a model after adding the QDQ nodes (and before the actual conversion to int8), and I am getting an error when trying to load it again.
Given a trained float32 keras functional model called `model`, the workflow is the following:
```
import tensorflow as tf
from tensorflow_quantization import quantize_model
from tensorflow_quantization.quantize_wrappers import Conv2DQuantizeWrapper

q_model = quantize_model(model)
tf.keras.models.save_model(q_model,'C:\workspace\q_model.hdf5')
q1_model = tf.keras.models.load_model('C:\workspace\q_model.hdf5', custom_objects={'Conv2DQuantizeWrapper': Conv2DQuantizeWrapper})
```
Running the code above gives me the following error when loading the model:

![error](https://user-images.githubusercontent.com/123370831/221816450-fd76d6a9-f5a0-4ce0-bcef-da4a02d4f4f3.PNG)

Could you help me with this?

I also have an additional question. I have seen that when the command `q_model = quantize_model(model)` is run, the original `model` gets destroyed. What is the reason behind this implementation choice?

## Environment

**TensorRT Version**: 8.5.1.7 
**NVIDIA GPU**: NVIDIA Quadro T1000 
**NVIDIA Driver Version**: 517.66
**CUDA Version**: 11.2
**CUDNN Version**: 8.7
**Operating System**: Windows 10
**Python Version**: 3.8.10
**Tensorflow Version**: 2.8.0

**Comment by zerollzeng** [comment]
Looks like an API compatibility issue to me, @ttyio any suggestions?

**Comment by ttyio** [comment]
Adding @gcunhase for help^^

**Comment by AdrianoSimonetto** [comment]
Hi @gcunhase, 

That solved the issue. 
Thanks for the help!

**Comment by gcunhase** [comment]
Regarding the comment that the original model is being "destroyed" after the `quantize_model(model)` call, that was not intentional and will be fixed soon. Thank you!
