### ISSUE TITLE
fMHCA plugin restriction

### ISSUE THREAD

**Issue by 1049451037** [NVIDIA/TensorRT#2732]
## Description

Hi, when I use fMHCA plugin, it seems runtime error occurred.

```
Validation failed: Not support q buffer sequence length not multiple of 64 when head size < 64 for plugin fMHCA
```

Could you provide efficient cross-attention without restriction like [flash-attention](https://github.com/HazyResearch/flash-attention)?

## Environment

nvidia docker container 22.12

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by ttyio** [comment]
fMHCA is removed in 8.6 OSS, now we recommend using ONNX parser, it is OOTB way, thanks and closing!
