### ISSUE TITLE
Internal Error (Could not find any implementation for node {ForeignNode[ReduceMax_1513...ReduceMax_1525]}

### ISSUE THREAD

**Issue by Levi-zhan** [NVIDIA/TensorRT#2734]
## Environment

**TensorRT Version**:   8.4.1
**NVIDIA GPU**: NVIDIA GeForce GTX 1660 SUPER、  NVIDAI Xavier
**NVIDIA Driver Version**: Driver Version: 470.129.06
**CUDA Version**:    11.4
**CUDNN Version**: 
**Operating System**:  Ubuntu 20.4
**Python Version (if applicable)**:   3.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**:   12
**Baremetal or Container (if so, version)**: 

Hello, I encountered the following error when transferring the onnx model to Tensorrt：
TensorRT VERBOSE =============== Computing costs for 
TensorRT VERBOSE *************** Autotuning format combination: Half(40000,1:8,200,1), Half(40000,1:8,200,1), Half(40000,1:8,200,1), Half(40000,1:8,200,1), Half(40000,1:8,200,1), Half(10000,1:8,100,1), Half(10000,1:8,100,1), Half(2500,1:8,50,1), Half(2500,1:8,50,1), Half(2500,1:8,50,1) -> Half(40000,200,1), Half(40000,200,1), Half(40000,200,1), Half(40000,200,1), Half(40000,200,1), Half(10000,100,1), Half(10000,100,1), Half(2500,50,1), Half(2500,50,1), Half(2500,50,1) ***************
TensorRT VERBOSE --------------- Timing Runner: {ForeignNode[ReduceMax_1513...ReduceMax_1525]} (Myelin)
TensorRT WARNING: Skipping tactic 0x0000000000000000 due to Myelin error: tensor "2933'" has an unitialized dimension.
TensorRT VERBOSE Fastest Tactic: 0xd15ea5edd15ea5ed Time: inf
TensorRT VERBOSE Deleting timing cache: 1526 entries, served 3447 hits since creation.
TensorRT ERROR: 10: [optimizer.cpp::computeCosts::3628] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[ReduceMax_1513...ReduceMax_1525]}.)
TensorRT ERROR: TensorRT: failed to create engine

This is an onnx model containing QDQ nodes. I want to convert it to tensorrRT int8 engine。However, it is strange that the original  model (not have QDQ nodes) can be successfully transferred to the tensorrt engine of fp16. In addition to whether to include QDQ nodes, other operators, such as network structure, use the same version of pytorch and opset. What's more, there was a previous version of the QDQ model (also including the ReduceMax node.) that was successfully converted to int8 engine, but later we changed the model structure and now it failed. However, the corresponding common model (not have QDQ nodes) can still be successfully converted to fp16 engine.

The following two pictures are part of the common model on the left and part of the QDQ node model on the right. The wrong operator is ReduceMax。

![image](https://user-images.githubusercontent.com/30153920/223034918-f6a533f8-c007-4cba-aee2-d6c0c2886a8a.png)
![image](https://user-images.githubusercontent.com/30153920/223034983-b714b258-2768-42c4-8ef0-0f08cb265b90.png)

I also tried to use setMemoryPoolLimit to increase the workspace, but still reported an error。The code is as follows
      networkConfig->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE, size_t(1) << 34);

This puzzled me for a long time. Do you have any suggestions? Thank you

**Comment by Levi-zhan** [comment]
@ttyio

**Comment by zerollzeng** [comment]
Could you try the latest TRT release? if it still does not work then can you provide the onnx model to us? Thanks!

**Comment by Levi-zhan** [comment]
> Could you try the latest TRT release? if it still does not work then can you provide the onnx model to us? Thanks!

When I upgraded the version of Tensorrt to 8.5.2, the engine was successfully generated. What's more, I can succeed in the original environment（Tensorrt 8.4） after simplifying the model structure. Why?  
Thanks！

**Comment by zerollzeng** [comment]
> I can succeed in the original environment（Tensorrt 8.4） after simplifying the model structure

It indeed does help sometimes.

Looks like this is is a fixed issue, so I'm closing this, feel free to reopen if you have any further questions.
