### ISSUE TITLE
How do I use the same tensorrt as the system version in Jetpack 5.1 python

### ISSUE THREAD

**Issue by lifan123-tech** [NVIDIA/TensorRT#2737]
## Description

When I update jetpack from 5.0.1 to 5.1, the Tensorrt folder and Tensorrt.so that were originally located in python3.8/lib/site-packages are missing. dpkg - l | grep TensorRT shows that the version of Tensorrt is 8.5.2-1, which cannot be found on the official website. How can I use Tensorrt in python on jetpack5.1

## Environment

**TensorRT Version**: 8.5.2-1
**NVIDIA GPU**: jetson Agx Xavier
**NVIDIA Driver Version**: jetpack5.1
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: aarch64
**Python Version (if applicable)**: 3.8
**PyTorch Version (if applicable)**: 1.11.0
**Baremetal or Container (if so, version)**: archiconda

**Comment by zerollzeng** [comment]
Sorry I don't quite get what's the problem here, could you describe the expected behavior vs actual behavior in more detailedly? Thanks!

**Comment by lifan123-tech** [comment]
Hello, thank you very much for trying to help me solve the problem. Next, I will describe the difficulties I encountered in detail.
I want to use tensorrt in python
When I use the Jetson agx xavier with jetpack5.0.1 installed, in the default python 3.8 of the system, I can directly use Tensorrt because the system has automatically installed (the path of Tensorrt package in python:/usr/lib/python3.8/dist-packages/Tensorrt)
![1](https://user-images.githubusercontent.com/106086324/223594514-89b7b718-bb51-4a99-96e7-2bbf413e135d.png)

However, for some reasons, I have to update the jetpack version. When I use the jetpack 5.1 version of jetson agx xavier, I open python 3.8 and enter the command: import Tensorrt, but it displays "ModuleNotFoundError: No module named Tensorrt".
So I opened/usr/lib/python3.8/dist-packages and found that there was no package for Tensorrt. Is it possible that python in jetpack5.1 does not install Tensorrt by default?
![2](https://user-images.githubusercontent.com/106086324/223594617-ed7203d1-50c5-4f26-9983-6ec7c0f37969.png)

Do I need to manually install Tensorrt into python？

**Comment by lifan123-tech** [comment]
In addition, I can find trtexec in/usr/src/tensorrt/bin：
![3](https://user-images.githubusercontent.com/106086324/223596183-2ea457d1-48af-4e37-a394-b2639655f2c0.png)


When I use "dpkg - l | grep TensorRT" to obtain the version of Tensorrt installed in the system, I get the following results:
![4](https://user-images.githubusercontent.com/106086324/223596538-efe0448d-3aa8-4768-8479-ab5fca24436d.png)



So I tried to install the same version of Tensorrt in python 3.8 manually, but I didn't find it on the official website, which only has TensorRT-8.5.1.7, TensorRT-8.5.2.2, TensorRT-8.5.3.1.
Should I give up installing the same version of TensorRT?

**Comment by lifan123-tech** [comment]
Hi，Just now, the moderator of nvidia forum sent me an email explaining the problem I encountered.，This is a system problem that will be fixed in the next version, and provides a manual installation method for this version. I hope it can help people who encounter this problem:
`sudo apt install python3-libnvinfer*`

**Comment by zerollzeng** [comment]
So glad we had a WAR now.

**Comment by RajUpadhyay** [comment]
I am sorry but I don't quite get what the problem was.
I upgraded my jetpack version too last week from 5.02 to 5.1.
My jetson xavier had tensorrt (8.5.2.1).

It could be the case that it may have not upgraded successfully.
Maybe check sdk manager one more time?

Also I recommend using l4t docker version 23.03 on jetson so that you can make changes accordingly in your docker image.

**Comment by lifan123-tech** [comment]
Thanks for your attention. Jetpack 5.1 has been upgraded to a new version, which is no problem. I will upgrade my Jetpack version soon.

**Comment by ttyio** [comment]
Closing inactive issues, thanks all!
