### ISSUE TITLE
trt sampleUffMaskrcnn has a different result with maskrcnn implemented in keras 

### ISSUE THREAD

**Issue by hwh-hit** [NVIDIA/TensorRT#274]
Hi， I have used samleUffMaskrcnn for my own dataset, it worked, but the results are different. The result of trt samleUffMaskrcnn depends much on anchor scales and anchor ratios, i set the same params in both test codes. The keras one performs better, as it can show more object(instances), but some object in trt maskrcnn can't be detected, especially Slender object, like a pole. Thanks for help

**Comment by Tyler-D** [comment]
Did you change the model's architecture (or backbone)?  Did you change the FPN's hyperparameters (the mapping of feature maps and RPN proposals)? If the answer is yes, then you may have to modify some arguments in config.py and plugins (or even the kernels) as they are hard-coded for Matterports model's backbones (resnet101 and resnet50) with 1024*1024 input. 

Sharing the detailed steps of your experiments will be better.

**Comment by hwh-hit** [comment]
@Tyler-D Thanks for your reply.
Yes,I have change the backbone, but i test with the bachbone resnet101 and resnet50, i also make below changes in Mask_RCNN/mrcnn/config.py, and i also add these changes to mrcnn_to_trt_single.py

> NUM_CLASSES = 1 + 7
IMAGE_MIN_DIM = 640
IMAGE_MAX_DIM = 640
RPN_ANCHOR_SCALES = (10, 20, 40, 80, 160)\n
RPN_ANCHOR_RATIOS = [0.07, 1, 2]      "0.07->since i have a lot of long thin objects"
MAX_GT_INSTANCES = 50
PRE_NMS_LIMIT=512
POST_NMS_ROIS_TRAINING=500
POST_NMS_ROIS_INFERENCE=500
DETECTION_MAX_INSTANCES = 30
> 

and i also make some changes in TensorRT:
TensorRT/samples/opensource/sampleUffMaskRCNN/mrcnn_config.h &&
TensorRT/plugin/proposalLayerPlugin/mrcnn_config.h

> static const nvinfer1::DimsCHW IMAGE_SHAPE{3, 384, 384};
static const int DETECTION_MAX_INSTANCES = 30;
static const int NUM_CLASSES = 1 + 7;
static const std::vector<float> RPN_ANCHOR_SCALES = {10, 20, 40, 80, 160}
static const float RPN_ANCHOR_RATIOS[] = {0.07, 1, 2};
static const int POST_NMS_ROIS_INFERENCE = 500;
> 

and also
0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch

> change
shape=[config.IMAGE_SHAPE[2], 1024, 1024 ], name="input_image")
to
shape=[config.IMAGE_SHAPE[2], 640, 640 ], name="input_image")

> 
last part 
TensorRT/samples/opensource/sampleUffMaskRCNN/converted/config.py

> roi = gs.create_plugin_node("ROI", op="ProposalLayer_TRT", prenms_topk=512, keep_topk=500, iou_threshold=0.7)
mrcnn_detection = gs.create_plugin_node("mrcnn_detection", op="DetectionLayer_TRT", num_classes=8, keep_topk=30, score_threshold=0.7,  iou_threshold=0.3)

> 
thoes are all the changes i have made. I also doubt that there are some hard code for Matterports model,
but i tried may times, nothing change in the result, any suggestions?

**Comment by Tyler-D** [comment]
Thanks for the details you provided !
Previously I was guessing you may change the mapping between FPN feature maps and ROIs of different sizes [here](https://github.com/Tyler-D/Mask_RCNN/blob/master/mrcnn/model.py#L389). So I said that you may also need to modify the [plugin](https://github.com/NVIDIA/TensorRT/blob/master/plugin/pyramidROIAlignPlugin/pyramidROIAlignPlugin.cpp#L84) and [kernel](https://github.com/NVIDIA/TensorRT/blob/master/plugin/common/kernels/maskRCNNKernels.cu#L1361). But it seems you didn't do that and mapped all your ROIs to P2 and P3 (P4 && P5 feature maps will not work in your RPN_ANCHORS_SCALES setting). This may effect your model's accuracy --- but it should have nothing to do with the gap between keras and TensorRT here.    

For your problem here, I cannot draw a conclusion from current information. But I highly recommend you to analysis the layer output's difference between Keras and TensorRT:
- First, make sure all the layers argumments are the same in Keras and TensorRT (besides the arguments you provided here, you could also check if hard-coded arguments I mentioned above and generated anchors coordinates are the same. ) .
- Then dump the output of Keras and TensorRT's layers and compare. I suggest to start from ProposalLayer and pay more attention to the plugin layers. I think the root cause may come from the plugin implementation.
 
That would be better if you could kindly paste your results here, then we could cooperate to settle down this problem.

**Comment by hwh-hit** [comment]
@Tyler-D Thanks for your sugesstion.
sorry, I'm a little confused. According to 
https://github.com/NVIDIA/TensorRT/blob/daacf1537c9310ab9d4a7e8a7b33cb3739289a32/plugin/common/kernels/maskRCNNKernels.cu#L1405
 ROIs still can be mapped to P4 and P5, can't they？
then，

1. I check all the params in mrcnn_config.h， exactly same as in keras,is there any else params may effect the result?

2. I print all the anchors generated by get_anchors in keras and proposalLayerPlugin.cpp in tensorrt, they are same，-0.010552～-0.010552093，
![anchors](https://user-images.githubusercontent.com/34235323/71080225-b52c2880-21c7-11ea-9adf-a1e216bc7589.png)
it's wired, anything else should i do to settle down this?
And I will paste the detection results here soon later.

**Comment by Tyler-D** [comment]
>> ROIs still can be mapped to P4 and P5, can't they？
Your biggest anchor scale is 160 * 160 , and the sample maps 224*224 ROIs to P4. So It is probable to map ROIs to P4 and P5 if the offest is large enough, but I think it is more like to map them to P2 and P3.

>> anything else should i do to settle down this ?
I think proposals and final detections can help a lot.

**Comment by hwh-hit** [comment]
Thanks, @Tyler-D I spent some time to get the proposals generated by trt code and keras code, they are not same , i get the proposals generated by trt in  https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1251 and add 

> printf("%f,%f,%f,%f\n",bbox_out[blockOffset + cur_id].y1,bbox_out[blockOffset + cur_id].x1, 
                                        bbox_out[blockOffset + cur_id].y2,bbox_out[blockOffset + cur_id].x2);

> 
after  https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1304
to get te refined proposals.
Then i get the proposals generated in keras by ran 

> rpn = model.run_graph

> 
with the same picture. 
And below are some detection results with 384 x 384 pictures ,left one comes from keras, right one comes from trt.
![diff](https://user-images.githubusercontent.com/34235323/71160515-af474d80-2282-11ea-817c-a7cfb3027a02.png)
![diff2](https://user-images.githubusercontent.com/34235323/71160541-be2e0000-2282-11ea-9792-21e00d7b5e2a.png)

**Comment by Tyler-D** [comment]
> BTW, is there other ways to set params RPN_ANCHOR_SACLES and RPN_ANCHOR_RATIOS to make them more suitble for my own dataset.

I think it depends on the ratio of the object area and the image area in your own dataset.  I can only say --- in this sample, the model maps 224*224 ROIs (in 1024 * 1024 image ) to P4. And it is the same as Keras implementation. The previous saying "P4 && P5 will not work" is actually not quite precise. Sorry for confusion.    

As for the difference between Keras and TRT,  if I understand your description correctly, you tried to compare the output of "RPN", right?  I suggest you not to print in the kernel but to print after the kernel execution, for example here:
https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1327 

And make sure the input to keras and to TRT should be the same. I remember you mentioned that the input shape is 640*640 previously. 

But to be honest, I believe RPN is not the point . You could paste more detailed results (the output directly) here.

**Comment by hwh-hit** [comment]
@Tyler-D Thanks for your reply.
Okay, i see. Actually i want to compare the outputs of proposalLayer from keras and trt, Maybe rpn_roi is more precise. But their outputs are not same(same input shape).
And i will print the output as your suggestion. 
I know exactly what your meaning about the input shape, i will keep them to be the same one, all are 384x384 or 640x640 according to the trainning input shape.

> But to be honest, I believe RPN is not the point . You could paste more detailed results (the output directly) here.

> 
detailed results: bbox coordinate and class label and something else?

**Comment by Tyler-D** [comment]
> Actually i want to compare the outputs of proposalLayer from keras and trt

If you print in `ApplyDelta2Bboxes`, you won't get the proposalLayer's output. You could check the code in https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1115

I think you may compare the output of RPN firstly (before NMS stuff), make sure they are the same here (I believe they will be the same considering it is just output of a naive convolution network). Then compare the output of proposalLayer.

**Comment by hwh-hit** [comment]
I'm so sorry for late reply. Please forgive me. Something else troubled me last few days. 
I still have a question here. I have printed the output of proposalLayer from trt and keras.
![proposal_diff](https://user-images.githubusercontent.com/34235323/71567136-bdedfa00-2af7-11ea-85cf-a4fabf7ca038.png)

**Comment by hwh-hit** [comment]
@Tyler-D @rmccorm4 Even more strange is that the rpn outputs are same neither. I print the rpn output in https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1146 after https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1144 and before https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/common/kernels/maskRCNNKernels.cu#L1148
![rpn_diff](https://user-images.githubusercontent.com/34235323/71573956-564ca480-2b21-11ea-9b10-f5b559b4a6d6.png)

**Comment by Tyler-D** [comment]
@hwh-hit . Considering RPN is just output of a simple convolution layers stack (with some nearset-neighbor resizing and concatenation), I highly suspect that your input to network in TensorRT is different from in Keras. Could you double check the input after preprocess in TensorRT sample ?
https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/samples/opensource/sampleUffMaskRCNN/sampleUffMaskRCNN.cpp#L434

And compare it with `molded_images` here:
https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L2581

**Comment by hwh-hit** [comment]
Thanks for your reply again. I also have such doubts. I have printed the input to trt by adding
`for (int i =0; i < img_w * img_h * img_c; i++)`
      `     print("%f,\n", hostDataBuffer[p]);`
in https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/samples/opensource/sampleUffMaskRCNN/sampleUffMaskRCNN.cpp#L517
and it differs from the input to keras just in orders, 
![pixel_diff](https://user-images.githubusercontent.com/34235323/71793831-8e9c3780-3079-11ea-9557-97f1072af0a3.png)

**Comment by hwh-hit** [comment]
Hello，I have tried one more time with other h5 file , and the same problem, the same input, but as for rpn ,only the first number is the same one.1.442790~1.4427874. this time I only change the imae size and dataset, nothing else .
![rpn_other](https://user-images.githubusercontent.com/34235323/71800943-67069880-3094-11ea-800f-6d1b6942dfb6.png)

**Comment by Tyler-D** [comment]
> But i think thant when the input passed to keras, the input should have the same shape as the input to trt.

No , I don't think so. As there is no `transpose` in the model, the format of input data in Keras will stay `NHWC`. But in TensorRT, the input format will be `NCHW`. 

> only the first number is the same one

I think the first element of data blob in `HWC` and `CHW` will be the same.

Could you provide the log when you export model from .h5 to .uff? 

PS: 
I'm not sure how you conduct your training. But if I'm going to train on my own dataset, I will train with the original Matterport's training code and then patch it with [NCHW-conversion](https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/samples/opensource/sampleUffMaskRCNN/converted/0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch) and do the model exportation.

**Comment by hwh-hit** [comment]
Ok, i see,thanks for reply. but do you mean that NHWC or NCHW may have a different result?
And I  am not exactly clear why the first element is same .
I will try to train my dataset with the patched code.
[mrcnn_trt.txt](https://github.com/NVIDIA/TensorRT/files/4025060/mrcnn_trt.txt)
this is my log, thanks.

**Comment by Tyler-D** [comment]
> I will try to train my dataset with the patched code.
You don't need to train your dataset with the patched code (And I think the train cannot work well with patched code). You can just update that patch and then verify the inference results. The weights trained with `NHWC` can be loaded in `NCHW` by keras automatically. 

Then you can compare `RPN`, `Proposal` between Keras and TensorRT as before.

**Comment by hwh-hit** [comment]
OK, I hvae tried many times with different version of tf and keras, it doesn't work,
`Traceback (most recent call last):
  File "test_tmd.py", line 69, in <module>
    model = modellib.MaskRCNN(mode="inference", config=config , model_dir=MODEL_DIR)
  File "/data/hwh/Mask_RCNN/mrcnn/model.py", line 1849, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/data/hwh/Mask_RCNN/mrcnn/model.py", line 1952, in build
    len(config.RPN_ANCHOR_RATIOS), 256)
  File "/data/hwh/Mask_RCNN/mrcnn/model.py", line 904, in build_rpn_model
    outputs = rpn_graph(input_feature_map, anchors_per_location, anchor_stride)
  File "/data/hwh/Mask_RCNN/mrcnn/model.py", line 860, in rpn_graph
    name='rpn_conv_shared')(feature_map)
  File "/home/test/anaconda3/envs/hwh/lib/python3.5/site-packages/keras/engine/topology.py", line 590, in __call__
    self.build(input_shapes[0])
  File "/home/test/anaconda3/envs/hwh/lib/python3.5/site-packages/keras/layers/convolutional.py", line 129, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
`
I am working on it. And is there any problem with the 'mrcnn_trt.txt'?

**Comment by hwh-hit** [comment]
@Tyler-D @Hi,Hi，finally i get the result,you are right, the TensorRT rpn output is the same as the output of keras with NCHW format, but not the training NHWC format. 
![NCHW](https://user-images.githubusercontent.com/34235323/71862861-1c3d5d00-3136-11ea-80b9-97ada8981ea1.png)
But the result is really bad as TensorRT.
Does that mean that I also need to train the model with the patched code with NCHW format?
@rmccorm4 Any suggestion?

**Comment by Tyler-D** [comment]
@hwh-hit I think you don't need to train in NCHW format. You can just keep doing the layer-by-layer analysis to locate the root cause of difference.
 
Could you compare the output of proposal layers ?

**Comment by hwh-hit** [comment]
Okay, thanks, there's still some bugs in my test code, I can get the rpn output , but the proposals are all zeros when I print them with run_graph()
> rpn = model.run_graph([image], 
         [("rpn_bbox", model.keras_model.get_layer("rpn_bbox").output),
          ("proposals", model.keras_model.get_layer("ROI").output)])
> 
It's wired. 
But as to the final result, the one in NCHW format is similar with tensorRT, especially the bbox. so I guess that the final proposals are very likely be same as proposals in tensorRT, not proposals in keras with NHWC format.

**Comment by hwh-hit** [comment]
@kevinch-nv Hi，i have disscussed the problem with  @Tyler-D for a long time, saw that you are the contributor of the NHWC->NCHW code. So I turn to both of you for help, when the NHWC model is converted to NCHW model, the performance is not so good. It turned out that NCHW model have the similar result with TensorRT, worse than NHWC model in keras, Is there any possible to get a better result or update the patch so that i can retrain the model with NCHW format?

**Comment by hwh-hit** [comment]
@Tyler-D I have double check the whole process, the output of keras NCHW format and TensorRT are more likely to be same , so may be the process of converting NHWC to NCHW leads to the difference ?Do you think so?

**Comment by Tyler-D** [comment]
@hwh-hit That also makes me confused. IMO, the NHWC or NCHW will not have such big difference as this sample itself has proved with the pretrained coco model. 

And I think the reason `run_graph` cannot work well is that you feed `NHWC` to model. There is no `transpose` in `run_graph` as in `detect` even with patched code. 

https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffMaskRCNN/converted/0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch#L210

BTW, Did you set `K.set_image_data_format('channels_first')` in model.py ? I think this may also have effect when you do inference. 

Looking forward your update on layer-per-layer analysis.

**Comment by Tyler-D** [comment]
@hwh-hit I mean layer per layer analysis between keras of `NHWC` and `NCHW`  : )

**Comment by hwh-hit** [comment]
@Tyler-D Thanks for your patience. I have added
`molded_images = np.transpose(molded_images, (0, 3, 1, 2))` in run_graph, 
and I also added  `K.set_image_data_format('channels_first')` in my test.py and model.py
this problem nearly drived me mad,` layer per layer analysis between keras of NHWC and NCHW` means: input_image(NHWC & NCHW),rpn_output(NHWC and NCHW),detection_bbox(NHWC and NCHW) and so on?

**Comment by Tyler-D** [comment]
The analysis strategy depends on you. You can start with the first convolution to make sure `NCHW` keras load `NHWC` weights corretly. Their output should be same if you align the data order by `transpose`.

Then you can go to RPN, ProposalLayer, PyramidROIAlign, DetectionLayer. Once you find the significant difference then go into it. I guess the difference may come from these customed layers, but not sure.

BTW you can also file issue here https://github.com/matterport/Mask_RCNN/issues . It turns out this is not TensorRT problem now.

**Comment by hwh-hit** [comment]
@Tyler-D I have fixed the run_graph() bug, it turns out that the output final proprosals of NCHW format in keras is same as TensorRT. So maybe I can draw the conclusion that tensorrt maskrcnn part is not the cause of the problem. 
Then here are layer_by_layer analysis:
the molded_images[1,3,384,384] and [1,384,384,3]
conv1 layer;NCHW format, shape[1, 64, 192, 192]
conv1 layer:NHWC format, shape[1, 192, 192, 64]
b1_conv1 aslo have the same problem, channel_first and channel_last
bn_conv1 layer;NCHW format, shape[1, 64, 192, 192]
bn_conv1 layer:NHWC format, shape[1, 192, 192, 64]
![conv1](https://user-images.githubusercontent.com/34235323/72043280-ba265880-32eb-11ea-8175-b37e60d8f0b3.png)

**Comment by hwh-hit** [comment]
@Tyler-D Thanks for your help, I print the output layer by layer . finally I solved the problem, There is a bug in the patched code. @kevinch-nv  @rmccorm4 , we should add `x = KL.Permute((2,3,1))(x)`  in https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L867 before `rpn_bbox = KL.Reshape((-1, 4))(x)`. If not, the output of rpn_bbox is wrong. so we can't get the exactly same result with keras in NHWC format. thanks again for @Tyler-D

**Comment by Tyler-D** [comment]
Thanks @hwh-hit It seems like a bug in https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffMaskRCNN/converted/0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch.  `x=KL.Permute((2,3,1))(x)` in the wrong place. It should be put right before https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffMaskRCNN/converted/0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch#L136 

@hwh-hit How about the final results of TensorRT ? I think it should align with NHWC keras now right ?

**Comment by hwh-hit** [comment]
@Tyler-D Yes, you are right. And the results is exactly same as keras ,Thanks for your help. A good chance to study maskrcnn again.

**Comment by Tyler-D** [comment]
@hwh-hit Have you tried with pretrained coco model? Are the results looks okay?

**Comment by hwh-hit** [comment]
@Tyler-D At the beginning, I tried with pretrained coco model, it's just ok, but not so accurate. but I only tested two pictures, and there are only one or two objects in the picures. And I didn't test the pictures in keras, so I don't think it's convincing.

**Comment by HKun1997** [comment]
@hwh-hit Hi，I also wanna use samleUffMaskrcnn for my own dataset. And I have got the Mask RCNN trained model .h5 file(reference mattport Mask RCNN). Would you like to share your solution how to convert h5 model to uff model and inference in TensorRT?

**Comment by hwh-hit** [comment]
@HKun1997 please refer to https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN

**Comment by HKun1997** [comment]
> @HKun1997 please refer to https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN

Thanks. I tried it but failed. My environment is Windows, and I'm unfamiliar with Linux.

**Comment by pra-dan** [comment]
@hwh-hit @Tyler-D Can you guys shed some light on how to run inference on images using the UFF file (obtained using TensorRT) ? 


https://github.com/NVIDIA/TensorRT/issues/274#issuecomment-567403752

I build my model just as the docs of MaskRCNN says in the TensorRT docs and obtained the UFF file. But I cannot figure out how to run inference on this ?
