### ISSUE TITLE
How much kind of convolutions does the tensort supports?

### ISSUE THREAD

**Issue by chegnyanjun** [NVIDIA/TensorRT#275]
I am trying to use tensortt for some segmentation works, but there are many different  types convolutions in segemntation works(such as dialated conv, depthwise conv, pointwise conv,depthwise separable convolution and so on),and i am using  pytorch framework.I just want to know does the tensrort6.0.1.5 supports  these convs or there has any plan about it?Hope for your reply, tkx.

**Comment by rmccorm4** [comment]
Hi @chegnyanjun,

I don't know too much about this, but I would think various types of convolutions can be supported using the FullyConnected and Convolution layers with different parameters. The quickest way to check would probably be to export your model to ONNX and try using `trtexec` or the ONNX parser through the API - see some examples here: https://github.com/NVIDIA/TensorRT/issues/283#issuecomment-567532079

I would also recommend upgrading to TensorRT 7.0 which was just released: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html#rel_7-0-0

**Comment by chegnyanjun** [comment]
@rmccorm4,thanks for your reply, and I will have a try.

**Comment by rmccorm4** [comment]
Any update @chegnyanjun ?
