### ISSUE TITLE
Error during convertion: graphShapeAnalyzer  Assertion src.d[i].value() failed.

### ISSUE THREAD

**Issue by frankxyy** [NVIDIA/TensorRT#2754]
```
[03/11/2023-01:15:31] [E] [TRT] parsers/onnx/ModelImporter.cpp:775: input: "matmul_0.tmp_0"
output: "transpose_3.tmp_0"
name: "Transpose_3"
op_type: "Transpose"
attribute {
  name: "perm"
  ints: 0
  ints: 3
  ints: 1
  ints: 2
  type: INTS
}

[03/11/2023-01:15:31] [E] [TRT] parsers/onnx/ModelImporter.cpp:776: --- End node ---
[03/11/2023-01:15:31] [E] [TRT] parsers/onnx/ModelImporter.cpp:778: ERROR: parsers/onnx/ModelImporter.cpp:180 In function parseGraph:
[6] Invalid Node - Transpose_3
[graphShapeAnalyzer.cpp::updateExtent::1062] Error Code 2: Internal Error (Assertion src.d[i].value() failed. )
```

The tensorrt version I use is in docker 22.07. The command is: ` trtexec --onnx=/home/xuyangyang/mseqa.onnx  --workspace=4096 --explicitBatch --minShapes=input_ids:1x100 --optShapes=input_ids:1x500 --maxShapes=x:1x2000 --shapes=input_ids:1x500 --saveEngine=mseqa.plan --plugins=/home/xuyangyang/TPAT/python/trt_plugin/lib/tpat_OneHot.so --fp16`

The originial onnx file and my customed onehot plugin(made with tpat) is uploaded to google drive: https://drive.google.com/drive/folders/1leDv1lhaxBkPSDY1aPWhb-frLLy2OSPK?usp=share_link

I currently have no idea how to deal with this error and wanna to ask if anyone can help.

**Comment by frankxyy** [comment]
what can i do for this error? thank you

**Comment by zerollzeng** [comment]
![image](https://user-images.githubusercontent.com/38289304/224725283-56f44b78-8916-43bd-89fa-eed41145f595.png)
I would highly suspect the input of `Transpose_3` is 2d and the perm is 4d.

**Comment by zerollzeng** [comment]
Does it work with onnxruntime?
