### ISSUE TITLE
Is the TensorRT 8.5.3 compatible with CUDA 11.6?

### ISSUE THREAD

**Issue by YouSenRong** [NVIDIA/TensorRT#2759]
## Description
Is the TensorRT 8.5.3 compatible with CUDA 11.6? Or can the TensorRT 8.5.3 run on the CUDA 11.6, is there any potential problem？
From this page https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/, it can be seen that the TensorRT 8.5.3 is compatible with 10.2. 
![image](https://user-images.githubusercontent.com/21186538/224589469-17429427-4ae4-4d06-8ccf-4e25771badff.png)

For some reason, the CUDA 11.8 is not compatible on my machine, therefore I wonder if I can run TensorRT 8.5.3 on CUDA 11.6？
Or it is better to run TensorRT 8.5.3 on 10.2？
Thanks a lot for any suggestion.

## Environment

**TensorRT Version**: 8.5.3
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: 460.91
**CUDA Version**: 11.8, 11.6, 10.2
**CUDNN Version**: 
**Operating System**: 16.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment]
https://developer.nvidia.com/nvidia-tensorrt-8x-download
![image](https://user-images.githubusercontent.com/38289304/224739234-6685ce99-5f74-4202-ba5c-fdda28af51aa.png)

**Comment by YouSenRong** [comment]
Thanks a lot for your response!

**Comment by zerollzeng** [comment]
I'm closing this if you don't have other questions, feel free to reopen it :-)

**Comment by YouSenRong** [comment]
I have found the compatible version from this link https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-5-3.
