### ISSUE TITLE
GPU usage high on Win11 but not on Win10

### ISSUE THREAD

**Issue by LHyang9527** [NVIDIA/TensorRT#2762]
## Description

We develop a CUDA application to do eye-tracking. It works fine on PC with Win10 OS but with low performance with Win11 OS.

We test the issue on the same PC.

PC hardware:

CPU: Intel i5-9500

Mem: 8GB

Graphics: Nvidia Geforce GTX 1660. Latest driver: 531.18

The CUDA application is based on CUDA 11.1 + TensorRT 7.2 + cuDNN 11.2.

PC installed Win10 64bit:

The GPU usage is about 5%-15% when only the CUDA application running.

And we can run CUDA application and other 3D programs (like Unit3D game) at the same time with fine performance.

![win10占用情况](https://user-images.githubusercontent.com/30061064/224884205-15ebec89-efd7-4c9a-85ae-97ebd0800509.jpeg)

The same PC installed Win11 64bit:

The GPU usage is about 70%-100% when only the CUDA application running.

Unfortunately, at this situation, we cannot run any other 3D program otherwise get bad performance.

![win11占用情况](https://user-images.githubusercontent.com/30061064/224884438-074afd1d-6f71-4975-81bd-782da2868605.jpeg)

## Environment
**TensorRT Version**: TensorRT 7.2
**NVIDIA GPU**: GeForce GTX 1660
**NVIDIA Driver Version**: 531.18
**CUDA Version**: V11.1
**CUDNN Version**: V11.2
**Operating System**: Win11
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by LHyang9527** [comment]
Anyone help ?

**Comment by zerollzeng** [comment]
@nvpohanh @oxana-nvidia any idea? Thanks!

**Comment by nvpohanh** [comment]
@zerollzeng Sadly, I don't think this is caused by TensorRT, but caused by CUDA driver. Maybe we should contact cuda driver team about this question.

One naive question is: how does driver know how much GPU utilization you want to use? I think there are other applications where someone hopes that the CUDA application can utilize GPU as much as possible for the best performance.

**Comment by nvpohanh** [comment]
@LHyang9527 Is it possible to add sleeps in your CUDA application so that it doesn't use GPUs as much?

**Comment by LHyang9527** [comment]
> @LHyang9527 Is it possible to add sleeps in your CUDA application so that it doesn't use GPUs as much?

Thanks for the reply, We have tried to add sleeps to our CUDA application and the GPU usage  go down, but I don't think this is a good solution. add sleep will affect the performance of our application and user experience.
