### ISSUE TITLE
`tensorrt==8.6.0` Python package does not work on CUDA 11 (in demo diffusion example)

### ISSUE THREAD

**Issue by skirsten** [NVIDIA/TensorRT#2773]
## Description

The official `tensorrt==8.6.0` python package seems to be build with CUDA 12, as can be seen by the dependencies:
```
nvidia-cublas-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12
```
This results in the following error on CUDA 11 (e.g. 11.8.0) during the diffusion example:
```
Building TensorRT engine for onnx/clip.opt.onnx: engine/clip.plan
[W] Unable to determine GPU memory usage
[W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
```
note that the builder check
```py
import tensorrt
print(tensorrt.__version__)
assert tensorrt.Builder(tensorrt.Logger())
```
works correctly.

If I experimentally upgrade to CUDA 12 it works as expected. Unfortunately I cannot do that.

It would be great if a cuda 11 wheel could be provided, e.g.
```requirements.txt
tensorrt==8.6.0+cu11
# or more specific (not sure if required)
tensorrt==8.6.0+cu118
```

## Environment

**TensorRT Version**: 8.6.0
**NVIDIA GPU**: RTX 3090
**NVIDIA Driver Version**: 520.61.07
**CUDA Version**: 11.8.0
**CUDNN Version**: 
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by skirsten** [comment]
Thanks that worked. I installed the components via apt:

```sh
apt-get update && apt-get --no-install-recommends install \
  python3-libnvinfer=8.6.0.12-1+cuda11.8 \
  libnvinfer8=8.6.0.12-1+cuda11.8 \
  libnvinfer-plugin8=8.6.0.12-1+cuda11.8 \
  libnvinfer-vc-plugin8=8.6.0.12-1+cuda11.8 \
  libnvparsers8=8.6.0.12-1+cuda11.8 \
  libnvonnxparsers8=8.6.0.12-1+cuda11.8 \
  libcudnn8=8.8.1.3-1+cuda11.8
```

I had to specify each depending package and version separately for some reason, but at least it worked.

**Comment by nrakltx** [comment]
@rajeevsrao Thanks for the fix! The installation works, but my python code thinks I have no `tensorrt` python package. Except for `apt-get install tensorrt` do I need to need to install something else for it to work in python?

Thanks in advance!

**Comment by kmpape** [comment]
Hi there,

I have a similar issue. However, I am using a Python venv, and I don't think that the above will work as the venv will not see the tensorrt installation. Any advice for this particular situation? Thank you very much.

**Comment by nrakltx** [comment]
You can copy the `tensorrt` directory that apt creates when installing `python3-libnvinfer` (find it using `dpkg -L python3-libnvinfer`) and copy it into your venv's `dist-packages` directory.
I Hope this helps!
