### ISSUE TITLE
Is building from source necessary for availability of trtexec command?

### ISSUE THREAD

**Issue by Godofnothing** [NVIDIA/TensorRT#2780]
TensorRT has an option of installation of TensorRT python package via pip. 
However, in order to convert the model into `trt` format, i.e TensorRT runtime, one has to run `trtexec` command that doesn't come together with the package. My TensorRT python installation is valid, I can import `trt` and use the python API. However, without `trtexec` one is unable to convert models and run any benchmark. 

Is building from source necessary for one to use  trtexec?

**Comment by rajeevsrao** [comment]
@Godofnothing you can get the trtexec binary prebuilt if you download the TensorRT binary release package from our Developer Zone (https://developer.nvidia.com/tensorrt) or if you install libnvinfer-bin from the NVidia network repo: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#maclearn-net-repo-install
`sudo apt-get install libnvinfer-bin`

**Comment by Godofnothing** [comment]
Thanks a lot!

**Comment by ralbertazzi** [comment]
@rajeevsrao any chance to see the `trtexec` executable in the Python releases too?

**Comment by 631068264** [comment]
E: Unable to locate package libnvinfer-bin  @rajeevsrao 

I support you @ralbertazzi

**Comment by ntakouris** [comment]
> E: Unable to locate package libnvinfer-bin [@rajeevsrao](https://github.com/rajeevsrao)
> 
> I support you [@ralbertazzi](https://github.com/ralbertazzi)
> 
> Or how to use Python api run as `trtexec ` I can't find any example about that.

update apt before
