### ISSUE TITLE
Simple question, possible to install TensorRT directly on docker ?

### ISSUE THREAD

**Issue by Stephenfang51** [NVIDIA/TensorRT#280]
Dear Sir

Since I only have cloud machine, and I usually work in my cloud docker, I just want to make sure if I can directly install TensorRT in my container？

Thanks ！

**Comment by rmccorm4** [comment]
Hi @Stephenfang51,

Yes you should be able to install it similarly to how you would on the host. If your container is based on Ubuntu/Debian, then follow those instructions, if it's based on RHEL/CentOS, then follow those. Let me know if you have any specific issues.
