### ISSUE TITLE
ONNX Graphsurgeon graph.fold_constants() fails without explicit onnxruntime providers

### ISSUE THREAD

**Issue by donrax** [NVIDIA/TensorRT#2804]
## Description

When calling `fold_constants` on a loaded onnx model:
```
graph = gs.import_onnx(model)
graph.fold_constants()
```
Constant folding is not performed and the following warning is raised:
`[W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)`

The solution is to add explicit `providers` to the following two lines in `onnx_graphsurgeon\ir\graph.py`:

  `777    sess = rt.InferenceSession(export_onnx(part, do_type_check=False).SerializeToString(), providers=['CPUExecutionProvider', 'CUDAExecutionProvider'])`

  `825    sess = rt.InferenceSession(export_onnx(graph_clone, do_type_check=False).SerializeToString(), providers=['CPUExecutionProvider', 'CUDAExecutionProvider'])`

## Environment

**TensorRT Version**:  8.5.3.1
**Graphsurgeon Version**:  0.4.6
**ONNX Graphsurgeon Version**: 0.3.12
**Polygraphy Version**: 0.44.2
**NVIDIA GPU**: TITAN RTX
**NVIDIA Driver Version**: 531.41
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0
**Operating System**: Windows 10

## Steps To Reproduce

As per instructions https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip install via:
```
python3 -m pip install <installpath>\python\tensorrt-8.5.3.1-cp310-none-win_amd64.whl
python3 -m pip install <installpath>\graphsurgeon\graphsurgeon-0.4.6-py2.py3-none-any.whl
python3 -m pip install <installpath>\uff\uff-0.6.9-py2.py3-none-any.whl
python3 -m pip install <installpath>\onnx_graphsurgeon\onnx_graphsurgeon-0.3.12-py2.py3-none-any.whl
```
Reproduce via:
```
import onnx
import onnx_graphsurgeon as gs
model = onnx.load('model.onnx')
graph = gs.import_onnx(model)
graph.fold_constants()
```

**Comment by pranavm-nvidia** [comment]
This was fixed a while ago - see [this line](https://github.com/NVIDIA/TensorRT/blob/main/tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py#L864). Can you try updating your version of ONNX-GS?

**Comment by donrax** [comment]
Upgrading onnx-graphsurgeon (version 0.3.26) solves the issue. The version with the issue packaged with TensorRT is an older version (0.3.12).
