### ISSUE TITLE
How to pass more than 1 element np.array() from python to c++ API IPluginV2 *createPlugin?

### ISSUE THREAD

**Issue by zeyu-hello** [NVIDIA/TensorRT#281]
For example, the plugin sample in [fcplugin] (https://github.com/NVIDIA/TensorRT/blob/master/plugin/fcPlugin/fcPlugin.cu#L673-680), the `W` has member params: `values` and `count`, whcih are get from `fc->fields[i].data` and `fc->fields[i].length` seperatly. 
Since I want to use the TensorRT python api, I built this plugin into a dynamic lib `libfcplugin.so`, then I in python scripts like this:
```python
import tensorrt as trt

import ctypes
ctypes.CDLL("libfcplugin.so")

def get_plugin():
    PLUGIN_NAME = 'CustomFCPluginDynamic'
    registry = trt.get_plugin_registry()
    creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME][0]
    interpolate_size_field = trt.PluginField("out_dims", np.array([240], dtype=np.int32), trt.PluginFieldType.INT32)
    interpolate_mode_field = trt.PluginField("type_id", np.array(0, dtype=np.int32), trt.PluginFieldType.INT32)
    interpolate_aligncorners_field = trt.PluginField("W", np.ascontiguousarray([3, 4], dtype=np.int32), trt.PluginFieldType.INT32)   #<<<<<<<<<<<<<<<<<<<<<<<<< HERE
    field_collection = trt.PluginFieldCollection([interpolate_size_field, interpolate_mode_field, interpolate_aligncorners_field])
    return creator.create_plugin(name=PLUGIN_NAME, field_collection=field_collection)
```

The TRT PluginFieldType only have some [basic type]
(https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-601/tensorrt-api/python_api/infer/Plugin/IPluginCreator.html?highlight=deserialize_plugin#tensorrt.PluginFieldType)
So how do I pass the `W` from python api to c++ api which the `tensorrt.PluginFieldType` dont have?

Also, if np.array([1, 2, 3]) and such a like array more than one element how to pass to C++ API?

Thanks for your reply in advance!

**Comment by rmccorm4** [comment]
Hi @nan0755,

I think this script might be a good reference for using Plugin API, though this sample is from an older release: https://github.com/NVIDIA/TensorRT/blob/release/6.0/demo/BERT/python/bert_builder.py

**Comment by rmccorm4** [comment]
Hi @zeyu-hello,

Any luck with the sample above?

**Comment by rmccorm4** [comment]
Closing since no response
