### ISSUE TITLE
convert  to uff issue

### ISSUE THREAD

**Issue by liupengkd** [NVIDIA/TensorRT#282]
## Environment

**TensorRT Version**: 6.0.1.5
**GPU Type**: 2080Ti
**Nvidia Driver Version**: 430
**CUDA Version**: 9.0
**CUDNN Version**: 7.6
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**: 3.5
**TensorFlow Version (if applicable)**: 1.9
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce
```
convert-to-uff xxxx.pb
```
I use tf.slice in tensorflow, but when I convert tensorflow to uff, it shows "No conversion function registered for layer: Slice yet", but I think tenosort 6 supports slice layer

**Comment by liupengkd** [comment]
the same problem that Interpolation mode such as Nearest  are supported for the resize operation--IResizeLayer，how to convert tf.image.resize_nearest_neighbor to IResizeLayer

**Comment by rmccorm4** [comment]
Hi @liupengkd,

Can you try to use `tf2onnx` (https://github.com/onnx/tensorflow-onnx) and use the ONNX parser instead? That is currently a better supported route.

Also, TRT 7.0 just came out which has expanded support for the ONNX parser and a few other features as well, so upgrading may help solve your issue: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html#rel_7-0-0

**Comment by liupengkd** [comment]
@rmccorm4 If I want to solve this problem in a custom way, how to establish the parameter correspondence between layers of tensorflow and nodes of uff in tensorflow when tensorflow is converted to uff。for example convert:
```
tf.slice(inputs, [0, 0, 0, 0], shapes, name=names)
```
to
uff node by gs
```
gs.create_node("slice", op="Slice",........)
```

**Comment by liupengkd** [comment]
@rmccorm4 I want I want to solve this problem by pb-> uff-> tensorrt。
I found tensorrt 7 supports operation of ResizeNearestNeighbor
![image](https://user-images.githubusercontent.com/15835439/71885836-241cf180-3176-11ea-88b4-944173344f04.png)
I found in sampleUffSSD of tensorrt 7 that the pb node was modified by using graphsurgeon to use the operations in rt.
![image](https://user-images.githubusercontent.com/15835439/71886186-b91fea80-3176-11ea-8e70-de0b9e989065.png)
can I replace the tf.image.resize_nearest_neighbor node of tensorflow in my pb with ResizeNearestNeighbor this way，
![image](https://user-images.githubusercontent.com/15835439/71886452-2fbce800-3177-11ea-85ea-5ba7fb4de91c.png)

**Comment by yuanzhedong** [comment]
Hi @liupengkd does `ResizeNearestNeighbor` works in TensorRT 7? Also do you know is there any workaround in TensorRT 5.0? Thanks!

**Comment by liupengkd** [comment]
@yuanzhedong ResizeNearestNeighbor is provided the official custom implementation in trt 7. You can use it in config.py. 
![image](https://user-images.githubusercontent.com/15835439/72307683-17d4ef00-36b6-11ea-99cf-6931d24776f3.png)

If you want to use it in trt5, you can copy the ResizeNearestNeighbor'implementation provided in the official website and use it for the implementation of custom operations.
![image](https://user-images.githubusercontent.com/15835439/72307762-5bc7f400-36b6-11ea-8011-e2aeb2d39b1b.png)

**Comment by yuanzhedong** [comment]
That's nice, thank you!! @liupengkd

**Comment by rmccorm4** [comment]
Looks like this was solved per https://github.com/NVIDIA/TensorRT/issues/282#issuecomment-573965632. Closing.
