### ISSUE TITLE
Requset for the samples about Tensorrt Layer test

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#2821]
Does TensorRT have any test cases for different ILayers? While looking through the documentation, I saw many layers with corresponding add methods, which included parameter and basic input/output information. However, I would like to know what a specific actual array would look like after going through a TensorRT layer. This would help me with testing and deepen my understanding of TensorRT layers.
 Do you have any recommended resources? Thank you very much.

**Comment by zerollzeng** [comment]
We didn't public those tests but I think you can do it on your own by referring to our API docs, make your hand dirty and you will get a better understanding :-)

**Comment by sanbuphy** [comment]
> We didn't public those tests but I think you can do it on your own by referring to our API docs, make your hand dirty and you will get a better understanding :-)

OK,  I get it. I will come back again if I encounter any issues, XD

**Comment by zerollzeng** [comment]
> But I have another question - can I turn writing this test into a open source public project?

I don't quite know about the details of the oss licence, but I think the answer is yes.
