### ISSUE TITLE
multiple models for parallel processing on tensorRT

### ISSUE THREAD

**Issue by zranguai** [NVIDIA/TensorRT#2822]
## Description

hello, how to use multiple models for parallel processing on tensorRT, using streams or MPS. can you give a demo?

**Comment by zerollzeng** [comment]
A simple solution is use multiple thread running simultaneously and each thread had a stream for a model. trtexec has an option `--infStreams` you can refer to.

**Comment by zranguai** [comment]
If gpu resources are sufficient, can we make the inference time of multiple models (including pre-processing and post-processing) comparable to the inference time of one model? Are there cases how to use multiple streams?

**Comment by zerollzeng** [comment]
> If gpu resources are sufficient, can we make the inference time of multiple models (including pre-processing and post-processing) comparable to the inference time of one model?

It's case-to-case, gpu resource contains lots of things, register, l1, l2, memory bandwidth, compute core etc. just do an experiment.


> Are there cases how to use multiple streams?

It's a common usage. you can refer to our cuda guide.
