### ISSUE TITLE
Does TensorRT consider parallel layers internally?

### ISSUE THREAD

**Issue by OYCN** [NVIDIA/TensorRT#2828]
Hi, There are two cases in my setting:
 1. There are many tiny `head` constructed by basic block such as `conv+relu` in one onnx
 2. There are many tiny network which have same struct merged in one onnx by script (extreme version of case1)

To maximize resource utilization, maybe we can parallel some head(case1) or network(case2) by multi-stream when enqueued. So I created a simple onnx(case2) and hope TensorRT will parallel some operators internally.

My onnx is :
![image](https://user-images.githubusercontent.com/34306806/228484672-9fe32a7f-1020-471f-9ccb-7031a75c3208.png)

TensorRT fused:

```
Conv_0           0.004ms
Conv_2           0.004ms
Conv_3           0.004ms
Conv_5           0.004ms
Conv_1 + Add_6   0.006ms
Conv_4 + Add_7   0.006ms
```

After build the onnx, in Nsight System I get all of kernels was on `Stream 16`:
![image](https://user-images.githubusercontent.com/34306806/228485282-1b2b4f84-2024-4c05-baf3-9f976647720f.png)

Confusion:
 - Does TensorRT consider parallel layers internally?
 - I also found the issue about Myelin #2733, it looks like some parallel optimization in Myelin? 

System Env:
OS: Ubuntu 20.04.3
TensorRT: 8.4.3
Cudnn: 8.2.1
Cuda: 11.2.152

**Comment by nvpohanh** [comment]
In TRT 8.6, you can add `--maxAuxStreams=7` to your trtexec command

**Comment by OYCN** [comment]
@nvpohanh Thanks for your response! I will try the TRT8.6 in development environment.

Change TRT version will difficute in production environment. Maybe we will split the network and enqueue on multi-stream manually when the version is lower than 8.6. 😢

**Comment by laurenlong** [comment]
Hi @OYCN , 
Have you tried anything that works for TRT 8.5 or below? I have the same problem. Can you give me some advice? Thanks.
