### ISSUE TITLE
Tensorrt7.0 OnnxParser Error

### ISSUE THREAD

**Issue by pobei** [NVIDIA/TensorRT#283]
## Description
Using onnx=1.6.0 can generate the .onnx model, when using Tensorrt-6.0 i can successfully export the engine., when using tensorrt7 , the network.number_layers is zero

## Environment

**TensorRT Version**: 7
**GPU Type**: v100
**Nvidia Driver Version**: 410.48
**CUDA Version**: 10.0
**CUDNN Version**: 7.6
**Operating System + Version**: centos
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 1.14
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by dhkim0225** [comment]
Maybe it's because of onnx-tensorrt package (onnx parser)
This module is basically build with ir_version 3, opset 7. 
You can find default onnx-parser defined version in [here](https://github.com/onnx/onnx-tensorrt/blob/master/onnx_trt_backend.cpp)

I have a same issue with you and try to build module with ir_version 4, opset 11.

**Comment by pobei** [comment]
> What is the version of your onnx model?
> 
> If you are not using opset 7, maybe it's because of onnx-tensorrt package (onnx parser)
> This module is basically built with ir_version 3, opset 7.
> You can find default onnx-parser defined version in [here](https://github.com/onnx/onnx-tensorrt/blob/master/onnx_trt_backend.cpp)
> 
> I have a same issue with you and try to build module with ir_version 4, opset 11.

hi ,have you solved the problem?
 i create a topic on 
[the formus ]( https://devtalk.nvidia.com/default/topic/1068661/tensorrt/tensorrt7-parse-error/?offset=3#5413251), and it is not convenient for me to upload anyfile to the website,,,,emm i wonder if it is convenient to upload file...

**Comment by dhkim0225** [comment]
I'm so sorry. I misunderstood your question. Please just ignore my reply above

**Comment by rmccorm4** [comment]
Hi @pobei,

If I were to guess I would think maybe using the `Explicit Batch` flag would solve your issue. I believe it was optional for ONNX in TRT6, but now required for ONNX in TRT7.

> The ONNX parser supports full-dimensions mode only. Your network definition must be created with the explicitBatch flag set (when using ONNX parser)

TRT7 release notes supports that: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html.

That would be `--trtexec --onnx=model.onnx --explicitBatch`, or using the Python API, something like this:

```python
import tensorrt as trt
TRT_LOGGER = trt.Logger()
network_flags = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

with trt.Builder(TRT_LOGGER) as builder, builder.create_network(network_flags) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
    # Other builder config flags
    # ...
    # Fill network atrributes with information by parsing model
    with open("model.onnx", "rb") as f:
        parsed = parser.parse(f.read())

        # Check error if parsing fails
        if not parsed:
            print(parser.get_error(0))
```

**Comment by pobei** [comment]
> Hi @pobei,
> 
> If I were to guess I would think maybe using the `Explicit Batch` flag would solve your issue. I believe it was optional for ONNX in TRT6, but now required for ONNX in TRT7.
> 
> > The ONNX parser supports full-dimensions mode only. Your network definition must be created with the explicitBatch flag set (when using ONNX parser)
> 
> TRT7 release notes supports that: https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html.
> 
> Using `trtexec` that would be something like:
> 
> ```
> trtexec --onnx=model.onnx --explicitBatch
> ```
> 
> Or using the Python API, something like this:
> 
> ```python
> import tensorrt as trt
> TRT_LOGGER = trt.Logger()
> network_flags = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
> 
> with trt.Builder(TRT_LOGGER) as builder, builder.create_network(network_flags) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
>     # Other builder config flags
>     # ...
>     # Fill network atrributes with information by parsing model
>     with open("model.onnx", "rb") as f:
>         parsed = parser.parse(f.read())
> 
>         # Check error if parsing fails
>         if not parsed:
>             print(parser.get_error(0))
> ```
thanks! thesolution  works for me

**Comment by santhoshnumberone** [comment]
Hi @rmccorm4 

I am facing a similar issue. Could you please guide me on how to resolve it?

**Comment by KellyZhang2020** [comment]
> thanks!
> The solution works for me

I also encountered this problem. After solving this problem, there was a problem during inference. 

`After CreateTrtModel, status: input 'input.1' dims [1,3,224,224,0,0,0,0] don't match configuration dims [3,224,224] for resnet50_0_gpu0`

But I have no problem with TensorRT 6, I don't know what the extra dimensions are.

**Comment by rmccorm4** [comment]
Hi @KellyZhang2020 ,

If you share the model and code that reproduces the problem, I can take a look when I get a chance.
