### ISSUE TITLE
Pageable cudaMemcpyAsync in IfConditional

### ISSUE THREAD

**Issue by OYCN** [NVIDIA/TensorRT#2836]
Hi, I have a problem when using IfConditional.

As the Nsight system profiled, It seems like TRT will copy the condition input from the device to a **pageable** memory when inference.(I alos try to passing the page-pocked memory pointer, it also have a cudaMemcpy)

![YNCBCWqMsx](https://user-images.githubusercontent.com/34306806/229015120-171201b3-bee7-4110-ae1e-3335a59b83bc.png)

q1: Maybe the pageable cuda memcpy will cause performance issues? Is it fixed in the new version?

q2: After I capture the inference by Cuda Graph, I also find the CudaMemcpy Node. Did Cuda Graph make the graph fixed or can we switch the branch in IfConditional by changing the condition input?

q3: Is it feasible or safe to remove the cuda memcpy node by cuda graph api to avoid the cuda memcpy?

My System Env:
OS: Ubuntu 20.04.3
TensorRT: 8.4.3
Cudnn: 8.2.1
Cuda: 11.2.152

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by nvpohanh** [comment]
In general, networks with `IfConditional` will not be graph-capturable because TensorRT has to do a device-to-host memcpy and launch the subsequent kernels depending on the host-side value. However, cuda graph is not able to capture host-side activity.

**Comment by nvpohanh** [comment]
So short answer for your questions:

> q1: Maybe the pageable cuda memcpy will cause performance issues? Is it fixed in the new version?

You either need a `device->pageable` memcpy OR a `device->pinned + cudaStreamSynchronize()`. I don't think they are very different in perf.

> q2: After I capture the inference by Cuda Graph, I also find the CudaMemcpy Node. Did Cuda Graph make the graph fixed or can we switch the branch in IfConditional by changing the condition input?

Cuda graph does not work well with `IfConditional`

> q3: Is it feasible or safe to remove the cuda memcpy node by cuda graph api to avoid the cuda memcpy?

Not possible unless you remove the `IfConditional` node

**Comment by OYCN** [comment]
Hi @nvpohanh 

I'm sorry for the delayed response. Thanks for your explanation. 

I understood the answers. I will close the issue.
