### ISSUE TITLE
How to configure BatchedNMSPlugin at runtime

### ISSUE THREAD

**Issue by LukeAI** [NVIDIA/TensorRT#2840]
My workflow is the standard:

- (1) I export from pytorch to ONNX, registering default params (eg. confidence threshold) with BatchedNMSPlugin.
- (2) For execution the ONNX is loaded, the TRT engine is built and then ran

My question is, is it possible (and if so, how?) to change the BatchedNMSPlugin configuration (eg. confidence threshold) in stage 2? ie. without having to reexport and rebuild the entire model from pytorch?

(I have also asked here, but no useful responses https://forums.developer.nvidia.com/t/how-to-set-parameters-of-batchednmsplugin/247692)

**Comment by zerollzeng** [comment]
I think it can be done on the [configurePlugin](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_plugin_v2_dynamic_ext.html#acac4692dd8653d1fd428d282697b50ee), You can add some log in the function and deserialize an engine, it should be called then you can do something in this function.

**Comment by LukeAI** [comment]
thanks for reply! Do you mean https://github.com/NVIDIA/TensorRT/blob/96e23978cd6e4a8fe869696d3d8ec2b47120629b/plugin/batchedNMSPlugin/batchedNMSPlugin.h#L63

That method doesn't appear to take any parameters like confidence threshold? It's also not clear to me how I would call it. Would you mind giving me an example?

**Comment by LukeAI** [comment]
to be clear - this is not a plugin I have written, it's part of Tensorrt https://github.com/NVIDIA/TensorRT/tree/main/plugin/batchedNMSPlugin

I don't quite understand what "You can put it in the class member variable. Then you can serialize it and deserialize it." this means - but it sounds like you are suggesting editing the source code of the plugin? Does that mean that it can't be configured unless I were to modify and distribute my own TensorRT?

**Comment by zerollzeng** [comment]
> My question is, is it possible (and if so, how?) to change the BatchedNMSPlugin configuration (eg. confidence threshold) in stage 2? ie. without having to reexport and rebuild the entire model from pytorch?

Oh I think you need to reexport the onnx then rebuild the engine. if you need to set different attributes during inference(NOT THE BUILDING PHASE), then you need to hack into the plugin code to do some modifications and it's doable.

**Comment by LukeAI** [comment]
ok, thanks, so in conclusion - no, it's not possible

**Comment by phelogges** [comment]
It seems that tensorrt just build plugin with static params into engine file, so there is no way to config these params at runtime.
But there is another way to make params dynamic. At runtime, you can split plugin layer out from network, and define a new network only contains this plugin layer with dynamic params, for nms, for example score, iou thresholds, then deserialize this network into an engine. To do this, you might pre-calculate your base model outputs and nms network inputs for compatibility， including dynamic shape profiles if your base model use dynamic shapes
