### ISSUE TITLE
chatglm model convert to tensorrt error

### ISSUE THREAD

**Issue by zhaohb** [NVIDIA/TensorRT#2849]
## Environment

**TensorRT Version**:  22.12
**NVIDIA GPU**:  A30

## Relevant Files
this is my model : [https://github.com/wangzhaode/ChatGLM-MNN/releases/download/v0.4/glm_block_0.onnx](url)

## Steps To Reproduce
I use onnx-simplifier tools optimizer that glm_block_0.onnx model,  [https://github.com/daquexian/onnx-simplifier](url):
```shell
onnxsim glm_block_0.onnx glm_block_0_sim.onnx
```
we can get glm_block_0_sim.onnx model file.

then I use trtexec tool to convert model:
```shell
trtexec --onnx=glm_block_0_sim.onnx --saveEngine=glm_block_0_sim.plan 
```

but I met error:
```shell
[04/04/2023-02:33:03] [I] [TRT] ----------------------------------------------------------------
[04/04/2023-02:33:04] [W] [TRT] parsers/onnx/onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[04/04/2023-02:33:04] [W] [TRT] parsers/onnx/onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[04/04/2023-02:33:04] [E] [TRT] parsers/onnx/ModelImporter.cpp:726: While parsing node number 34 [Squeeze -> "cos"]:
[04/04/2023-02:33:04] [E] [TRT] parsers/onnx/ModelImporter.cpp:727: --- Begin node ---
[04/04/2023-02:33:04] [E] [TRT] parsers/onnx/ModelImporter.cpp:728: input: "onnx::Squeeze_460"
output: "cos"
name: "Squeeze_102"
op_type: "Squeeze"
doc_string: "  File \"/home/yanxing/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/2449bdc9d85103734ae987bdc94eafa7fec2145d/modeling_chatglm.py\", line 196\ndef apply_rotary_pos_emb_index(q, k, cos, sin, position_id):\n    # position_id: [sq, b], q, k: [sq, b, np, hn], cos: [sq, 1, hn] -> [sq, b, 1, hn]\n    cos = torch.squeeze(cos)\n          ~~~~~~~~~~~~~ <--- HERE\n    sin = torch.squeeze(sin)\n    cos = F.embedding(position_id, cos).unsqueeze(2)\n"

[04/04/2023-02:33:04] [E] [TRT] parsers/onnx/ModelImporter.cpp:729: --- End node ---
[04/04/2023-02:33:04] [E] [TRT] parsers/onnx/ModelImporter.cpp:731: ERROR: parsers/onnx/builtin_op_importers.cpp:4793 In function importSqueeze:
[8] Assertion failed: !isDynamic(shape) && "Cannot infer squeeze dimensions from a dynamic shape! Please re-export your model with the Squeeze axes input set."
[04/04/2023-02:33:04] [E] Failed to parse onnx file
[04/04/2023-02:33:04] [I] Finish parsing network model
[04/04/2023-02:33:04] [E] Parsing model failed
[04/04/2023-02:33:04] [E] Failed to create engine from model or file.
[04/04/2023-02:33:04] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8501] # trtexec --onnx=glm_block_0_sim.onnx --saveEngine=glm_block_0_sim.plan
```

how to fix that? thank you very much.

**Comment by vanewu** [comment]
@zhaohb  chatglm should use the glm6b model. The implementation structure of this model they published cannot be directly translated to TRT. Such as 2D rotary embedding and other calculations implemented by himself. You need to manually modify some torch implementations of this model before converting. This may take some time on your part.

**Comment by zerollzeng** [comment]
> ```shell
> [8] Assertion failed: !isDynamic(shape) && "Cannot infer squeeze dimensions from a dynamic shape! Please re-export your model with the Squeeze axes input set."
> ```

check the `Squeeze_102` in Netron. looks like your model is exported with dynamic shapes but it only supports fixed shape for some operator.

**Comment by zhaohb** [comment]
@vanewu @zerollzeng yes, have some op that tensorrt can not support, will tensorrt support chatglm in the future？

**Comment by vanewu** [comment]
@zhaohb Currently, the operators provided by ONNX and TensorRT are sufficient to support GLM conversion. I think a better way is to modify the source code of GLM Torch. In fact, that code also needs to be modified more, although your ONNX conversion is successful. But I guess there should be problems with numerical calculations, because many of chatglm's forward calculations pass in python built-in types, which will be converted to constants.

**Comment by zhaohb** [comment]
@vanewu modify source code of GLM Torch may be not a good solution, this means we need to change the training code.

@zerollzeng 
>check the Squeeze_102 in Netron. looks like your model is exported with dynamic shapes but it only supports fixed shape for some operator.

Can we also understand that tensorrt's squeeze operator does not support dynamic input, can we fix it?

**Comment by nvpohanh** [comment]
Or try const-folding the ONNX file after you have exported it: https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/surgeon/02_folding_constants

**Comment by vanewu** [comment]
@zhaohb It only needs to modify part of the code implementation of inference(not training) with supported operations. This does not affect the calculation results, what you probably need to modify is the position calculated by the 2D rotary embedding. If you do not modify their inference code, your ONNX calculation results should also be wrong （Even if you can convert out an onnx model). Because if you look closely at their infer code, you will find that many of the input are not tensor, and some variable values will be traced as constant values ​​for the first transmission after ONNX conversion.

**Comment by jinluyang** [comment]
> @vanewu modify source code of GLM Torch may be not a good solution, this means we need to change the training code.
> 
> @zerollzeng
> 
> > check the Squeeze_102 in Netron. looks like your model is exported with dynamic shapes but it only supports fixed shape for some operator.
> 
> Can we also understand that tensorrt's squeeze operator does not support dynamic input, can we fix it?

I saw your message in a Wechat group that we share, let me explain to you why this isn't a Tensorrt bug. When you use cos.squeeze(1)， （that is the part of the chatglm code)， the meaning of squeeze() is it checks the 1st dimenstion, if it is 1, the dimenstion will be squeezed. otherwise it will be saved. In our case, with dynamic shape considered, the ONNX parser cannot decide if this dimension is 1 or not. So it asks you to re-export. I have also encountered this problem. You should rewrite the code as:
`cos = torch.flatten(cos,start_dim=1, end_dim=2)`
 Maybe some day I have time, I shall open a PR for those codes to the THU code..

**Comment by jinluyang** [comment]
But maybe from another perspective, there are some enhancement that can be done by TRT ONNX parser. Since the onnxruntime CPU EP does not complain about this particular issue. If TRT can deduce that this dimension is always 1 through more effective shape inferencing, it would save us a lot of time.

**Comment by zhaohb** [comment]
@jinluyang Thank you very much for your answer. I have modified the code according to what you said, and now the onnx parser  is normal, but there is an error in the process of generating engine:
```shell
...
[05/11/2023-08:19:20] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[05/11/2023-08:19:21] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[05/11/2023-08:19:22] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[05/11/2023-08:19:34] [I] Finish parsing network model
[05/11/2023-08:19:34] [W] Dynamic dimensions required for input: input_ids, but no shapes were provided. Automatically overriding shape to: 1x1
[05/11/2023-08:19:34] [W] Dynamic dimensions required for input: position_ids, but no shapes were provided. Automatically overriding shape to: 1x2x1
[05/11/2023-08:19:34] [W] Dynamic dimensions required for input: attention_mask, but no shapes were provided. Automatically overriding shape to: 1x1x1x1
[05/11/2023-08:19:59] [E] Error[9]: [myelinBuilderUtils.cpp::getMyelinSupportType::1106] Error Code 9: Internal Error (Gather_84 requires foreign node optimizations incompatible with data-dependent shapes, so treating as error.)
[05/11/2023-08:19:59] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[05/11/2023-08:19:59] [E] Engine could not be created from network
[05/11/2023-08:19:59] [E] Building engine failed
[05/11/2023-08:19:59] [E] Failed to create engine from model or file.
[05/11/2023-08:19:59] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8503] # trtexec --onnx=model6b_modify/model.onnx --saveEngine=model6b_trt/model_6b.plan --fp16
```

I am using 8.5.3, I will test in 8.6

**Comment by xikakera** [comment]
> @jinluyang Thank you very much for your answer. I have modified the code according to what you said, and now the onnx parser is normal, but there is an error in the process of generating engine:
> 
> ```shell
> ...
> [05/11/2023-08:19:20] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> [05/11/2023-08:19:21] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> [05/11/2023-08:19:22] [W] [TRT] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> [05/11/2023-08:19:34] [I] Finish parsing network model
> [05/11/2023-08:19:34] [W] Dynamic dimensions required for input: input_ids, but no shapes were provided. Automatically overriding shape to: 1x1
> [05/11/2023-08:19:34] [W] Dynamic dimensions required for input: position_ids, but no shapes were provided. Automatically overriding shape to: 1x2x1
> [05/11/2023-08:19:34] [W] Dynamic dimensions required for input: attention_mask, but no shapes were provided. Automatically overriding shape to: 1x1x1x1
> [05/11/2023-08:19:59] [E] Error[9]: [myelinBuilderUtils.cpp::getMyelinSupportType::1106] Error Code 9: Internal Error (Gather_84 requires foreign node optimizations incompatible with data-dependent shapes, so treating as error.)
> [05/11/2023-08:19:59] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
> [05/11/2023-08:19:59] [E] Engine could not be created from network
> [05/11/2023-08:19:59] [E] Building engine failed
> [05/11/2023-08:19:59] [E] Failed to create engine from model or file.
> [05/11/2023-08:19:59] [E] Engine set up failed
> &&&& FAILED TensorRT.trtexec [TensorRT v8503] # trtexec --onnx=model6b_modify/model.onnx --saveEngine=model6b_trt/model_6b.plan --fp16
> ```
> 
> I am using 8.5.3, I will test in 8.6

I have the same problem in 8.5.3, did you finish it?

**Comment by zhaohb** [comment]
@xikakera yes, 8.6.1 is ok

**Comment by xikakera** [comment]
@zhaohb 
I got an error

```
symbolic_global_padding.cpp:1287: DCHECK(use->is_use_only()) failed. 
[E] 10: Could not find any implementation for node {ForeignNode[Cast_2...Transpose_4635]}.
[E] 10: [optimizer.cpp::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Cast_2...Transpose_4635]}.)
[!] Invalid Engine. Please ensure the engine was built correctly
```

can you upload a sample?  Thank you.

**Comment by xikakera** [comment]
@zhaohb use python api , I use `pip install tensorrt` ，can't make trtexec.

**Comment by zhaohb** [comment]
ok, I will sort out the script recently and submit it for you to use in tensorrt

**Comment by xikakera** [comment]
@zhaohb This is my first time using tensorRT.

so I didn't know that all outputs should be added to bindings

Now after I add all outputs to bindings， it work！

Thank you very very much

**Comment by vanewu** [comment]
Here is a converted chatglm6b trt model, the corresponding c++ inference and python bindings.  KV-Cache is supported. You can try: https://huggingface.co/TMElyralab/lyraChatGLM 
@zhaohb @xika

**Comment by zhaohb** [comment]
@vanewu Great thing, but I think what this project is doing is supporting glm in fastertransformer and then building a pipeline that calls the ft library, right?

**Comment by zhaohb** [comment]
@vanewu and I don't know what kind of role tensorrt plays in it， can you explain it? 
thank you very much

**Comment by vanewu** [comment]
@zhaohb This repository should now be fully tensorrt 8.6 based.

**Comment by zhaohb** [comment]
@vanewu but I don't see any conversion to trt.  I think glm6b-bs8.ftm is an ft model file, not a tensorrt engine
maybe i am wrong

**Comment by xikakera** [comment]
@vanewu @zhaohb  Maybe run in [tensorrt docker image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt/tags) nvcr.io/nvidia/tensorrt:23.04-py3 , cuda 12.1, tensorrt 8.6

in file glm6b-bs8.ftm:
how to change ChatGLMForConditionalGeneration.forward to 
```python
        if past_key_values is not None:
            inputs_values = inputs_values + past_key_values

        computed = self.kernel.infer(inputs_values)
```

or  glm6b-bs8.ftm is a simple has past_key_values inputs tensorrt engine

**Comment by bulubulu-Li** [comment]
这个issue真牛逼

**Comment by vanewu** [comment]
@Tlntin @xikakera @zhaohb  The [repository](https://huggingface.co/TMElyralab/lyraChatGLM) has been updated, and the first version was optimized using TensorRT. The new version includes optimizations for ChatGLM6B based on FasterTransformer. Many optimizations have been made at the source code level, resulting in better performance, ease of use, and GPU compatibility. Please update and try it out at your convenience.
