### ISSUE TITLE
About reusing execution context

### ISSUE THREAD

**Issue by Jsy0220** [NVIDIA/TensorRT#2856]
In my application, I want to reuse one execution context to inference frames in different sizes synchronously to save memory,
and `IExecutionContext::setBindingDimensions` needs to be called before every `IExecutionContext::enqueueV2`. 
So is `IExecutionContext::setBindingDimensions` time consuming ? if so, is there any way to save memory when inferencing in different sizes in single thread?

**Comment by zerollzeng** [comment]
> So is `IExecutionContext::setBindingDimensions` time consuming ?

Shape inference will take a small amount of time.

> if so, is there any way to save memory when inferencing in different sizes in single thread?

I don't think so. Or you can build multiple engines and each has static input shapes.

**Comment by vanewu** [comment]
I have had a similar use case, and finally found that creating contexts with different profiles is the best performance. But this will require more video memory.

**Comment by ttyio** [comment]
closing since there is answer already, thanks all!
