### ISSUE TITLE
polygraphy hardcodes python runtime path inside executable

### ISSUE THREAD

**Issue by mafiosnik777** [NVIDIA/TensorRT#2859]
## Description

When building an environment with Conda and moving it to another system, I noticed that Polygraphy hardcodes the Python runtime inside its executable, that was used to install it with. This causes polygraphy to not work after moving the Python environment somewhere else or to another system.

## Steps To Reproduce

- Create a new Conda environment or Python Venv
- Install polygraphy using:
```
pip install nvidia-pyindex
pip install polygraphy
```
- Move the environment somewhere else or to another system
- Activate the environment inside CLI
- Calling polygraphy in CLI results in this:
```
(base) C:\Users\Mafio>polygraphy
Fatal error in launcher: Unable to create process using '"C:\Users\Mafio\polygraphy-conda\python.exe"  "C:\Users\Mafio\Desktop\polygraphy-conda\Scripts\polygraphy.exe" ': The system cannot find the file specified.
```

This is because the path of the python runtime gets hardcoded into polygraphy.exe.

![](https://i.imgur.com/m5sBKKd.png)

## Environment

**TensorRT Version**:  8.6
**NVIDIA GPU**: RTX A4000
**NVIDIA Driver Version**: 531.41
**CUDA Version**: 12.1
**CUDNN Version**: 8.8.1
**Operating System**: Windows 11
**Python Version (if applicable)**:  3.10.6
**Polygraphy Version**:  polygraphy-0.46.2-py2.py3-none-any

**Comment by pranavm-nvidia** [comment]
This is caused by `setuptools` and I don't think it's unique to Polygraphy. According to [this SO answer](https://stackoverflow.com/a/17329493) we can specify a different path in our setup script, but it would still be a static path. On Linux, this is fairly easy to work around as we can use `/usr/bin/env python` but I don't know if there's an equivalent on Windows. 

I'm curious about the use-case though. Does Conda support moving environments like this? I imagine that would break any package that uses `setuptools`'s `console_scripts` API. From [this blog post](https://www.anaconda.com/blog/moving-conda-environments) it sounds like `conda-pack` is the suggested method of moving environments.

**Comment by mafiosnik777** [comment]
> This is caused by `setuptools` and I don't think it's unique to Polygraphy. According to [this SO answer](https://stackoverflow.com/a/17329493) we can specify a different path in our setup script, but it would still be a static path. On Linux, this is fairly easy to work around as we can use `/usr/bin/env python` but I don't know if there's an equivalent on Windows.
> 
> I'm curious about the use-case though. Does Conda support moving environments like this? I imagine that would break any package that uses `setuptools`'s `console_scripts` API. From [this blog post](https://www.anaconda.com/blog/moving-conda-environments) it sounds like `conda-pack` is the suggested method of moving environments.

My bad, I should have specified that I used Miniconda in particular. Not sure about normal Conda. Miniconda and Venv indeed support moving around environments, without issues.

I haven't encountered any other package yet, where I would have needed to use the CLI interface instead of the python module itself. Looking through the polygraphy docs, I just couldn't find any easy way to inspect a TensorRT Engine, like you can do with the onnx python module, so I just used the CLI Interface instead, where it's just `polygraphy inspect model <model>`.

**Comment by mafiosnik777** [comment]
Nevermind, I'm just blind. Exactly what I needed was [get_input_metadata()](https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/backend/trt/runner.html#polygraphy.backend.trt.runner.TrtRunner.get_input_metadata) in the TRT Runner, thus bypassing the CLI Interface.

As this is caused by setuptools, I guess this is #wontfix?

**Comment by pranavm-nvidia** [comment]
Yeah, unfortunately I don't think we have a good way to fix this for now. The workaround would be to reinstall Polygraphy in such cases which hopefully shouldn't be too bad given that it's a very small package (on the order of KB).
