### ISSUE TITLE
How to convert onnx(Quantified model) to tensorrt using python api?

### ISSUE THREAD

**Issue by wytszhuzhu** [NVIDIA/TensorRT#2863]
I follow this [https://github.com/NVIDIA/TensorRT/blob/release/8.6/quickstart/quantization_tutorial/qat-ptq-workflow.ipynb](url) converted q_model() to onnx format, I want use python api convert onnx to tensorrt instead of (trtexec --onnx=models/mobilenetv2_ptq.onnx --int8 --saveEngine=models/mobilenetv2_ptq.trt) because I can't install tensorrt,But I don't how to config the args? thanks.

`
def build_engine(onnx_file_path, engine_file_path, max_batch_size=1, fp16_mode=False, save_engine=False):

    if os.path.exists(engine_file_path):
        print("Reading engine from file: {}".format(engine_file_path))
        with open(engine_file_path, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())  

    EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

    with trt.Builder(TRT_LOGGER) as builder, \
        builder.create_network(EXPLICIT_BATCH) as network, \
        builder.create_builder_config() as config, trt.OnnxParser(network, TRT_LOGGER) as parser:

        builder.max_batch_size = max_batch_size     

        config.max_workspace_size = 1 << 30           

        profile = builder.create_optimization_profile()
        profile.set_shape("input", (1, 3, 224, 224), (8, 3, 224, 224), (8, 3, 224, 224))
        config.add_optimization_profile(profile)

        if not os.path.exists(onnx_file_path):
            quit("ONNX file {} not found!".format(onnx_file_path))
        print('loading onnx file from path {} ...'.format(onnx_file_path))
        with open(onnx_file_path, 'rb') as model:
            print("Begining onnx file parsing")
            if not parser.parse(model.read()):        
                print('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print(parser.get_error(error))    
                return None

        last_layer = network.get_layer(network.num_layers - 1)
        if not last_layer.get_output(0):
            network.mark_output(last_layer.get_output(0))
        print("Completed parsing of onnx file")
        print("Building an engine from file{}' this may take a while...".format(onnx_file_path))
        engine=builder.build_engine(network, config)  
        print("Completed creating Engine")
        if save_engine:
            with open(engine_file_path, 'wb') as f:
                f.write(engine.serialize())
        return engine`

**Comment by zerollzeng** [comment]
I think you can use [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert) and then you can just install the tensorrt python package with pip.

**Comment by zerollzeng** [comment]
BTW install tensorrt should be easy, what block the installation?
