### ISSUE TITLE
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'get_plugin_registry'

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/TensorRT#2867]
Hi.  
    How to use Plugin Shared Libraries?
```
builder = trt.Builder(TRT_LOGGER)
builder.get_plugin_registry().load_library(cfg.plugin_lib)
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'get_plugin_registry'
```
I convert with trtexec, The error message is as follows.
`/opt/TensorRT-8.4.3.1/bin/trtexec --onnx=../../pth-onnx/onnx_simp_0410.onnx --plugins=./build/lib/libvit_plugin.so`

```
[04/13/2023-08:11:40] [I] [TRT] No importer registered for op: TransformerPlugin. Attempting to import as plugin.
[04/13/2023-08:11:40] [I] [TRT] Searching for plugin: TransformerPlugin, plugin_version: 1, plugin_namespace: 
```

**Comment by SolDogLi** [comment]
> 
TensorRT 8.2
LibFile = "xxx.so"
ctypes.cdll.LoadLibrary(LibFile)
logger = trt.Logger(trt.Logger.ERROR)
trt.init_libnvinfer_plugins(logger, '')

There are certain differences between different versions.

**Comment by ywfwyht** [comment]
> > 
> 
> TensorRT 8.2 LibFile = "xxx.so" ctypes.cdll.LoadLibrary(LibFile) logger = trt.Logger(trt.Logger.ERROR) trt.init_libnvinfer_plugins(logger, '')
> 
> There are certain differences between different versions.
Thanks for your reply.  
I want to export a complete engine with trt.OnnxParser and plugin shared libraries. and the plugin needs to load weights.

**Comment by zerollzeng** [comment]
How do you register your plugin?

+ @pranavm-nvidia for the python api usage :-)

**Comment by ywfwyht** [comment]
> How do you register your plugin?
> 
> + @pranavm-nvidia for the python api usage :-)

yeah, Register the plugin with python api.

**Comment by zerollzeng** [comment]
I'm not an expert about the python api, but you can put the weights in the plugin attributes or make it an input of your plugin.

**Comment by zerollzeng** [comment]
I believe this is a usage issue but without the reproduce and plugin code I can't give any further suggestions.

**Comment by ywfwyht** [comment]
@zerollzeng bro, 
How to infer plugin shared library with C++ api.

**Comment by zerollzeng** [comment]
https://github.com/NVIDIA/TensorRT/blob/b55c4710ce01f076c26710a48879fcb2661be4a9/samples/common/common.h#L893

You can take this as reference. it's how `trtexec --plugins=xx.so` work.

**Comment by zerollzeng** [comment]
> ERROR: 8: [helpers.h::numericCast::45] Error Code 8: Integer Overflow (cast failure due to overflow with value 18446744071562068479 and upper bound 9223372036854775807)

Looks like an invalid cast node in your onnx model.

**Comment by ywfwyht** [comment]
> > ERROR: 8: [helpers.h::numericCast::45] Error Code 8: Integer Overflow (cast failure due to overflow with value 18446744071562068479 and upper bound 9223372036854775807)
> 
> Looks like an invalid cast node in your onnx model.

I use the plugin shared library, but it working use python API.
