### ISSUE TITLE
How to use IOptimizationProfile::setDimensions in dynamic shape tensors?

### ISSUE THREAD

**Issue by nan0755** [NVIDIA/TensorRT#287]
The docmeantation of `IOptimizationProfile::setDimensions` :
> Set the minimum / optimum / maximum dimensions for a dynamic **input tensor**. This function must be called three times (for the minimum, optimum, and maximum) for any **network input tensor** ...

My questions are:
1. it's for `network input tensor`, but is it also available for other network layer (not the input layer)?
2. how to set a dynamic `output tensor`?

**Comment by gcp** [comment]
As for 2, if the output has a dynamic size, it is automatically computed from the input size and you don't need to set it manually. You can't call setDimensions on outputs (it will assert).

**Comment by rmccorm4** [comment]
Hi @nan0755,

For (1), I'm not sure if it makes much sense to set an optimization profile for an intermediate layer of the network. After the input layer, the shapes are calculated by the intermediate layers/ops in your network. If for some reason you need/expect a certain shape at some point in the middle of the network, I would think you could calculate what the input shape has to be to achieve that.

For (2) it's basically the same answer as (1) and like @gcp said.
