### ISSUE TITLE
Converting SavedModel to TensorRT directly with Polygraphy

### ISSUE THREAD

**Issue by rakandhiya** [NVIDIA/TensorRT#2876]
I can convert my TensorFlow models to TensorRT by first converting it into ONNX and then use Polygraphy to convert it into TensorRT. Is it possible to convert from SavedModel directly without converting into ONNX first? I know there's the `--model-type` option that has the option `keras` and `frozen` among others. but I got an error saying that it can only work in TF < 2.0. I'm using TF 2.7 currently on Jetson Nano. Is this deprecated or not?

**Comment by pranavm-nvidia** [comment]
Polygraphy doesn't currently support TF2/SavedModels so for now you'd have to convert to TensorRT via ONNX.

**Comment by rakandhiya** [comment]
got it, thank you!
