### ISSUE TITLE
enqueueV3 is slower than enqueueV2

### ISSUE THREAD

**Issue by DZADSL72-00558** [NVIDIA/TensorRT#2877]
## enqueueV3 is slower than enqueueV2, is this normal? 

I get the following number when I ran inference with various enqueue versions:

enqueue_V3 average latency 10.193520ms among 100 iters
enqueue_V2 average latency 8.305722ms among 100 iters

## Environment

**TensorRT Version**: 8.6.0.12
**NVIDIA GPU**:  A10G 
**NVIDIA Driver Version**: 12.1
**CUDA Version**: 530.30.02
**CUDNN Version**: 8.8.0.121_1.0
**Operating System**: Ubuntu 20.04 
**Python Version (if applicable)**: N/A
**Tensorflow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: N/A
**Baremetal or Container (if so, version)**: N/A

## Relevant Files

Sorry, I can not provide any detail of my model for some security issue. 

It is a 1B model, and the input data size pretty large, with more than 50 input chunk and 50 output chunk. For each chunk, size is around 270KiB. 

To copy data between pinned RAM and device RAM for enqueue_V2, I utilized a single cuda stream by running "cudaMemcpyAsync."

For enqueue_V3, I used `setTensorAddress` to pinned RAM.

Data transit time between host and device is taken into account while measuring inference latency. 

So is this normal that enqueV3 is slower than enqueV2?

## Steps To Reproduce

You can pick a model at random with lots of input data and try to reproduce it.

**Comment by zerollzeng** [comment]
@DZADSL72-00558 Could you please provide the nsys report if you can't share the model with us? 

@nvpohanh Is it a known issue and do you have any insight here?

**Comment by nvpohanh** [comment]
> For enqueue_V3, I used setTensorAddress to pinned RAM.

For enqueueV3, could you still use `cudaMemcpyAsync` to first transfer the data to device buffer and then call `setTensorAddress` with the device address?

**Comment by DZADSL72-00558** [comment]
Hi @nvpohanh , after I did this 

pseudocode:
```
void inference()
{
cudaMemcpyAsync(device,pinned,cudaMemcpyHostToDevice);
m_context->setTensorAddress(device);
m_context->enqueueV3(stream);
cudaMemcpyAsync(pinned,device,cudaMemcpyDeviceToHost);
}
```
The inference latency is nearly equal to the equeneV2 latency.  I really value your suggestions.

Just a quick query about this. What distinguishes version 3 from version 2? (To me, the delay makes absolutely no difference.
)

**Comment by DZADSL72-00558** [comment]
One more question I had. 

I noticed that there is a safe namespace under the `nvinfer1`. For example [nvinfer1::safe::IExecutionContext](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1safe_1_1_i_execution_context.html#details). So, will you kindly explain to me the distinction between safe and unsafe API?

**Comment by nvpohanh** [comment]
> Just a quick query about this. What distinguishes version 3 from version 2?

The main difference is that V3 supports data-dependent-shapes. That means, if the output tensor size depends on the input values, then V2 cannot be used because it requires the output size to be known.

**Comment by nvpohanh** [comment]
> I noticed that there is a safe namespace under the nvinfer1. For example [nvinfer1::safe::IExecutionContext](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1safe_1_1_i_execution_context.html#details). So, will you kindly explain to me the distinction between safe and unsafe API?

The safety-certified APIs are meant for applications that require strict safety requirements like autonomous vehicles, but it has limited support on the ops and tensor shapes. In contrast, the standard APIs include all the most advanced features of TensorRT.

**Comment by DZADSL72-00558** [comment]
> > Just a quick query about this. What distinguishes version 3 from version 2?
> 
> The main difference is that V3 supports data-dependent-shapes. That means, if the output tensor size depends on the input values, then V2 cannot be used because it requires the output size to be known.

I appreciate your explanation. Just one more query about this.  

I must explicitly allot the device buffer and pinned RAM before doing inference. How do I allocate such buffers if the output data form relies on the input data value? 

In order to execute cudaMemcpyAsync() before and after enqueueV3(), I must define the size of each chuck.

**Comment by nvpohanh** [comment]
Please refer to the docs: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#dynamic-shaped-output

In short, use `getTensorShape()` to get the tensor shape.

**Comment by DZADSL72-00558** [comment]
Thanks, learned a lot from it. ^>^

**Comment by zerollzeng** [comment]
Can we close this issue? Thanks!

**Comment by DZADSL72-00558** [comment]
Yes, feel free to close it.  Thank you.
@zerollzeng

**Comment by zerollzeng** [comment]
Thanks, closed.
