### ISSUE TITLE
How to cycle inference?

### ISSUE THREAD

**Issue by aininot260** [NVIDIA/TensorRT#288]
I would like to do inference in a function with real time called.It should be fast.I wonder how to modify the code.Thanks.

This is the function I would like to cycle.
```
def work(images):
    # Do inference with TensorRT
    trt_outputs = []
    # with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
    #     inputs, outputs, bindings, stream = common.allocate_buffers(engine)
    onnx_file_path = 'crossnet.onnx'
    engine_file_path = "crossnet.trt"
    engine=get_engine(onnx_file_path, engine_file_path)
    context=engine.create_execution_context()
    inputs, outputs, bindings, stream = common.allocate_buffers(engine)
    inputs[0].host = images.numpy().flatten()
    trt_outputs = common.do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
    return trt_outputs
```
This is the get_engine function:
```
def get_engine(onnx_file_path, engine_file_path=""):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""
    def build_engine():
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
            builder.max_workspace_size = 1 << 28 # 256MiB
            builder.max_batch_size = 1
            # Parse model file
            if not os.path.exists(onnx_file_path):
                print('ONNX file {} not found, please run yolov3_to_onnx.py first to generate it.'.format(onnx_file_path))
                exit(0)
            print('Loading ONNX file from path {}...'.format(onnx_file_path))
            with open(onnx_file_path, 'rb') as model:
                print('Beginning ONNX file parsing')
                parser.parse(model.read())
            print('Completed parsing of ONNX file')
            print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
            engine = builder.build_cuda_engine(network)
            print("Completed creating Engine")
            with open(engine_file_path, "wb") as f:
                f.write(engine.serialize())
            return engine

    if os.path.exists(engine_file_path):
        # If a serialized engine exists, use it instead of building an engine.
        print("Reading engine from file {}".format(engine_file_path))
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
    else:
        return build_engine()
```
This is  common.allocate_buffers:
```
# Allocates all buffers required for an engine, i.e. host/device inputs/outputs.
def allocate_buffers(engine):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()
    for binding in engine:
        size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size
        dtype = trt.nptype(engine.get_binding_dtype(binding))
        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))
        # Append to the appropriate list.
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))
    return inputs, outputs, bindings, stream
```
This is common.do_inference:
```
# This function is generalized for multiple inputs/outputs.
# inputs and outputs are expected to be lists of HostDeviceMem objects.
def do_inference(context, bindings, inputs, outputs, stream, batch_size=1):
    # Transfer input data to the GPU.
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    # Run inference.
    context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    # Synchronize the stream
    stream.synchronize()
    # Return only the host outputs.
    return [out.host for out in outputs]
```

**Comment by aininot260** [comment]
If I modify like this,I will throw an error:

```
onnx_file_path = 'crossnet.onnx'
engine_file_path = "crossnet.trt"
engine=get_engine(onnx_file_path, engine_file_path)
context=engine.create_execution_context()
inputs, outputs, bindings, stream = common.allocate_buffers(engine)

def work(images):
    # Do inference with TensorRT
    trt_outputs = []
    # with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
    #     inputs, outputs, bindings, stream = common.allocate_buffers(engine)

    global engine,context,inputs,outputs,bindings,stream

    inputs[0].host = images.numpy().flatten().copy()
    trt_outputs = common.do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
    return trt_outputs
```
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (245) - Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception

**Comment by Eric-Zhang1990** [comment]
@aininot260  Do you solve the problem? I reference @jkjung-avt's code, but it have the same isuue.

**Comment by aininot260** [comment]
Not yet.It may be something wrong with multi threads or network structure.
https://github.com/NVIDIA/TensorRT/issues/301
@Eric-Zhang1990

**Comment by jkjung-avt** [comment]
Check out how I implemented the TrtYOLOv3 class here: https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/yolov3.py#L370

And this is how it's called:
https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_yolov3.py#L82
https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_yolov3.py#L56

**Comment by Eric-Zhang1990** [comment]
@jkjung-avt  My code is similar to yours, and I can run it correctly just loading trt model, but when I create class object in one .py file, and use it to inference in another .py file, the results are not right, like this:
![Screenshot from 2020-01-04 11-19-49](https://user-images.githubusercontent.com/24602893/71759183-2700b380-2ee4-11ea-8ece-d12de319a665.png)
it is a classifier, but its results are others (means class 0).
Do you know why it is like that?
Tnak you.

**Comment by Eric-Zhang1990** [comment]
@jkjung-avt  When not using thread, can you run tensorrt correctly? Thanks.

**Comment by Eric-Zhang1990** [comment]
@jkjung-avt  Can you load detection model and classify model (using tensorrt) on one gpu and run correctly? Thanks.

**Comment by jkjung-avt** [comment]
> Do you know why it is like that? (Classification result is incorrect?)

With the information provided, I have no idea what the problem might be.  I think it's likely due to bugs in the code.

> When not using thread, can you run tensorrt correctly?

Yes.  In fact, I tested TensorRT optimized SSD models in both single-threaded and multi-threaded cases. Reference:

- [TensorRT UFF SSD](https://jkjung-avt.github.io/tensorrt-ssd/)
- [Speeding Up TensorRT UFF SSD](https://jkjung-avt.github.io/speed-up-trt-ssd/)

> Can you load detection model and classify model (using tensorrt) on one gpu and run correctly?

Do you mean object detection models or image classification models?  Anyway, I have tested both (SSD and GoogLeNet) and shared my code at [jkjung-avt/tensorrt_demos](https://github.com/jkjung-avt/tensorrt_demos)

**Comment by lijie2160** [comment]
@jkjung-avt  I can load detection and classification models, but error happens when do infer.
for example, I use mtcnn and googlenet for face recognition. I need to load two models at the same time. tensorrt can loads two these models, but when do infer, error happens:
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (290) - Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception


But single model is normal.

**Comment by CptK1ng** [comment]
@lijie2160 Running in exactly the same issue. Appreaciate to hear if you are able to find a solution. 

Using mtcnn from JKJung as face detector and a resnet with onnx-tensorrt for recognition.

**Comment by rajeevsrao** [comment]
Please refer to [trtexec ](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/trtexec/trtexec.cpp#L193) for reference on how to run inference in a loop. Moving additional D2H and H2D copies or stream synchronizations can add overhead but should be safe to do.

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by leoluopy** [comment]
@ttyio  i meet the problem at the version of 7.2.3.4 . can you reopen this issue  , and give an simple solution  ? do any one have a suggestion ?  my code is like below : 
```


    with build_engine_caffe(model_info.MODEL_PATH, model_info.DEPLOY_PATH) as engine:
        xxxxxx = allocate_buffers()
        with engine.create_execution_context() as context:
            
            im1 = cv2.imread(im1)
            ......
            h_input = preprocess(im1)
            cuda.memcpy_htod_async(d_input, h_input, stream)
            context.execute_async_v2()
            cuda.memcpy_dtoh_async(h_output[0], d_output[0], stream)
            ......
            
            im2 = cv2.imread(im2)
            ......
            h_input = preprocess(im2)
            cuda.memcpy_htod_async(d_input, h_input, stream)
            context.execute_async_v2()
            cuda.memcpy_dtoh_async(h_output[0], d_output[0], stream)
            ......

            im3 = cv2.imread(im3)
            ......
            h_input = preprocess(im3)
            cuda.memcpy_htod_async(d_input, h_input, stream)
            context.execute_async_v2()
            cuda.memcpy_dtoh_async(h_output[0], d_output[0], stream)
            ......
```
when inference the first image , everything is oK . but some errors occurs at the second image , and never returns OK ! error is below:
```

[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (376) - Cask Error in allocateContextResources: 11 ( Failed to update runtime arguments.)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (376) - Cask Error in allocateContextResources: 11 ( Failed to update runtime arguments.)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
inference done : 0.002886533737182617
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (376) - Cask Error in allocateContextResources: 11 ( Failed to update runtime arguments.)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
```

**Comment by ttyio** [comment]
Hello @leoluopy , are you using dynamic shape? are the images has the same size? If the image size changed, we need `context.set_binding_shape` to update the size before `enqueue` new images.

https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/ExecutionContext.html#tensorrt.IExecutionContext.set_binding_shape

**Comment by leoluopy** [comment]
@ttyio yes i set the binding_shape everytime , and use the image matched dimension . and i use the default profile 0

**Comment by leoluopy** [comment]
Hi , @ttyio  @jkjung-avt  , as i changed to static shape mode, the problem still occurs , any simple solution ?

**Comment by ttyio** [comment]
@leoluopy , have you tried trtexec?
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec

**Comment by leoluopy** [comment]
@ttyio  thanks for replying in such a short time . and the problem is solved . my process of inference is OK , and i ported my model and postprocess code from pytorch , therefore , there are some ".cuda() " like code . maybe  pytorch style code ".cuda()" will damage the cuda environment .  after i removed the ".cuda()" code  , doing the postprocess code all in cpu environment. then the problem is solved . record this issue , and maybe this will do some help for the pytorch users who's on the way of porting tensorRT.
