### ISSUE TITLE
How to understand the layer weights in engine(which generated by PTQ) ？

### ISSUE THREAD

**Issue by lixhk** [NVIDIA/TensorRT#2887]
## Description   

When I do PTQ for model.onnx and build an engine, I  think the `calib scales` are pulled in operation(mul with weights) , take no account of fusions and layout transform, for int8 precision layer, like conv2d, the `weight` has `scale` (a vector type, per channel quant) not in calibtable.   

## Question  
Is my understanding correct ?    
Is it in this way `new_weight = int8(weight * scale)`  in plan file ?  

Thanks !  

@pbridger @aaronp24 @ttyio @lukeyeager

**Comment by zerollzeng** [comment]
Yes, if you open a TRT generated calibration cache file, you will find there are only scales for tensors. 

> Is it in this way `new_weight = int8(weight * scale)` in plan file ?

Yes

**Comment by lixhk** [comment]
Thanks ! Now closed.
