### ISSUE TITLE
cudaErrorStreamCaptureUnsupported in cudagraph in multi-threads

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#2888]
## Description

When I use cudagraph in multi-threads(CPU threads),  each thread has `preprocess` (default stream, with `cudaDeviceSynchronize`), and `infer`(create stream, not default stream), cudagraph only capture `enqueueV2` .

Now it report error: `cuda error  code=900 cudaErrorStreamCaptureUnsupported.  cudaDeviceSynchronize()`     

------------------------------------------------------
## Question  

In the case of 1 GPU and multiple CPU threads, if I call cudaDeviceSynchronize() from one CPU thread, will it wait for other CPU threads to complete their work on the GPU device ?

And A-thread(CPU) `cudaDeviceSynchronize` will break the B-thread(CPU)  graph, so it report error code=900 ?

Thanks !

**Comment by lixhk** [comment]
@nvpohanh  yes I has set
GpuErrChk(cudaStreamBeginCapture(mStream, cudaStreamCaptureModeThreadLocal));  or  
GpuErrChk(cudaStreamBeginCapture(mStream, cudaStreamCaptureModeGlobal));   both error

**Comment by nvpohanh** [comment]
I see... then it seems that cudaDeviceSynchronize() will break cuda stream capture regardless of the modes.

Is it possible to replace the cudaDeviceSynchronize() with something else?

**Comment by lixhk** [comment]
@nvpohanh Now I use `cudaStreamSynchronize(0)` replace of `cudaDeviceSynchronize()`

**Comment by lix19937** [comment]
@nvpohanh   sometimes, error still exist, ` cuda error  code=900 cudaErrorStreamCaptureUnsupported.  cudaStreamSynchronize(0)`

**Comment by lix19937** [comment]
Fixed, closed.
