### ISSUE TITLE
What is the reason we don't use the tensorflow serving?

### ISSUE THREAD

**Issue by sihanwang-pinterest** [NVIDIA/TensorRT#290]
Hi,
I am learning the TensorRT code, i find that TensorRT gets rid of the tensorflow serving in v1.3.0, could someone help to explain what is the technical reason that the backend need to be rebuilt? Any limitations in tensorflow serving?

Thank you
Sihan

**Comment by rmccorm4** [comment]
Hi @sihanwang-pinterest,

I think you have this mistaken for https://github.com/nvidia/tensorrt-inference-server
