### ISSUE TITLE
Conversion fails with `[weightsPtr.h::setCount::144] Error Code 2: Internal Error (Assertion count >= 0 failed.)`

### ISSUE THREAD

**Issue by howieyoo** [NVIDIA/TensorRT#2904]
## Description

While converting one of our models to TensorRT, it fails with the following error:

```
[X] Merging conv layers: Gemm_27 || Gemm_30
[weightsPtr.h::setCount::144] Error Code 2: Internal Error (Assertion count >= 0 failed. )
```

## Environment

**TensorRT Version**: 8.6.0
**NVIDIA GPU**: 4090
**NVIDIA Driver Version**: 520.61.05
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0
**Operating System**: Ubuntu 22.04
**Python Version (if applicable)**: 3.8

## Relevant Files

Attached is a script that will generate a minimal ONNX model which passes the model checker, but fails to convert to TensorRT and produces the above error.

https://gist.github.com/howieyoo/fc26f8fd78332c22fac4568b34ffe08a

## Steps To Reproduce

```bash
pip install onnx numpy tensorrt polygraphy
python main.py
polygraphy convert -vvvv --convert-to trt --output trt-bug.trt trt-bug.onnx
```

**Comment by zerollzeng** [comment]
1. Could you please share the onnx here directly? thanks!
2. Does the model work with onnxruntime?

**Comment by zerollzeng** [comment]
I can reproduce the issue, will check later.

**Comment by zerollzeng** [comment]
File internal bug 4088913 to track, I think the error may come from the very big gemm size.

**Comment by zerollzeng** [comment]
Is it a real case in your model that you need to use such big GEMM? it might be triggered by integer overflow.

**Comment by howieyoo** [comment]
Yes, this is from a production model we are training and plan to run inference on.

**Comment by ttyio** [comment]
this will be fixed in next release, thanks

**Comment by ttyio** [comment]
FYI, 9.0A available in:
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.0.1/tars/tensorrt-9.0.1.4.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.0.1/tars/tensorrt-9.0.1.4.linux.x86_64-gnu.cuda-12.2.tar.gz

we will update the OSS release/9.0 branch soon.

**Comment by ttyio** [comment]
Closing since now we have https://github.com/NVIDIA/TensorRT/tree/release/9.0, thanks all!
