### ISSUE TITLE
[question] why unet-trt-int8’s inference is much slower than fp16

### ISSUE THREAD

**Issue by handoku** [NVIDIA/TensorRT#2905]
## Description
I have implemented a stable diffusion img2img pipeline using tensorrt fp16. It's good but we are seeking for a faster deployment solution because the whole pipeline's latency is still a little bit unbearable. 

Then I tried int8, according to my test result, I found that running unet with int8 precision is much slower than fp16.

unet onnx is exported from stable diffusion v2.1, then converted into tensorrt plan
test with image's input size：512x512
latency results are as follow：
fp16 ：`42.872 ms`

int8 ：`111.368 ms`

My guess is that only fused fp16 attention implementation (like flash attention) are provided by tensorrt. If working with int8, lots of attention layers are broken into many plain matmul ops. which results in slow inference. Is that right?

Is it possible accelerate stable diffusion with int8 quantization? I am wondering whether somebody has tried to quantize stable diffusion model. Does it hurt the quality of result?

Or, it would be great that someone share any viable accelerattion solutions (with better performance, indeed).

## Environment

**TensorRT Version**:  tensorrt 8.6 EA
**NVIDIA GPU**:  A10
**NVIDIA Driver Version**:  470.161.03
**CUDA Version**:  11.7
**CUDNN Version**:  
**Operating System**:  
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce
```
# build int8 plan
./TensorRT-8.6.0.12/bin/trtexec --onnx=unet.onnx --minShapes=\'sample\':2x4x8x8,\'encoder_hidden_states\':2x77x1024 --optShapes=\'sample\':2x4x64x64,\'encoder_hidden_states\':2x77x1024 --maxShapes=\'sample\':4x4x96x96,\'encoder_hidden_states\':4x77x1024  --buildOnly --saveEngine=unet-int8.plan --memPoolSize=workspace:13888 --device=1 --int8

# build fp16 plan
./TensorRT-8.6.0.12/bin/trtexec --onnx=unet.onnx --minShapes=\'sample\':2x4x8x8,\'encoder_hidden_states\':2x77x1024 --optShapes=\'sample\':2x4x64x64,\'encoder_hidden_states\':2x77x1024 --maxShapes=\'sample\':4x4x96x96,\'encoder_hidden_states\':4x77x1024  --buildOnly --saveEngine=unet-int8.plan --memPoolSize=workspace:13888 --device=1 --fp16

# run inference with trtexec
./TensorRT-8.6.0.12/bin/trtexec --loadEngine=./unet-int8.plan --device=2 --iterations=100 --warmUp=500 --shapes='sample':2x4x64x64,'encoder_hidden_states':2x77x1024

./TensorRT-8.6.0.12/bin/trtexec --loadEngine=./unet.plan --device=2 --iterations=100 --warmUp=500 --shapes='sample':2x4x64x64,'encoder_hidden_states':2x77x1024
```

**Comment by zerollzeng** [comment]
> # build int8 plan
> ./TensorRT-8.6.0.12/bin/trtexec --onnx=unet.onnx --minShapes=\'sample\':2x4x8x8,\'encoder_hidden_states\':2x77x1024 --optShapes=\'sample\':2x4x64x64,\'encoder_hidden_states\':2x77x1024 --maxShapes=\'sample\':4x4x96x96,\'encoder_hidden_states\':4x77x1024  --buildOnly --saveEngine=unet-int8.plan --memPoolSize=workspace:13888 --device=1 --int8
> 
> # build fp16 plan
> ./TensorRT-8.6.0.12/bin/trtexec --onnx=unet.onnx --minShapes=\'sample\':2x4x8x8,\'encoder_hidden_states\':2x77x1024 --optShapes=\'sample\':2x4x64x64,\'encoder_hidden_states\':2x77x1024 --maxShapes=\'sample\':4x4x96x96,\'encoder_hidden_states\':4x77x1024  --buildOnly --saveEngine=unet-int8.plan --memPoolSize=workspace:13888 --device=1 --fp16

run it with --verbose you will see the final engine layer information. I guess the 'int8 engine' will fallback most of the layer to FP32, because we don't support int8 ptq for transformer network now. 

To get the best perf, use `--best`

**Comment by handoku** [comment]
@zerollzeng I notice that the generated int8 plan file is only half size of fp16 engine. But how can I know whether int8 precision really has been used? 
building logs are vague for me.
[build_00.log](https://github.com/NVIDIA/TensorRT/files/11339427/build_00.log)
[build_01.log](https://github.com/NVIDIA/TensorRT/files/11339566/build_01.log)

And, I have tried to use `polygraphy` to inspect layer attrs, however, got a error:
```
root@pod-volc:~# polygraphy inspect model unet-int8.plan --show layers attrs > log.log
Traceback (most recent call last):
  File "/usr/local/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/inspect/subtool/model.py", line 146, in run_impl
    func()
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/inspect/subtool/model.py", line 102, in inspect_trt
    engine_str = trt_util.str_from_engine(
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/util.py", line 674, in str_from_engine
    layer_info = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
```

**Comment by zerollzeng** [comment]
> I exported engine with `--best` before, inference performance is same as engine built with `--fp16`

Then it should be the reason I mentioned. 

You log is incomplete, at the end of the log there should be a `Engine Layer Info(mation)` section.

**Comment by handoku** [comment]
@zerollzeng please check [build_01.log](https://github.com/NVIDIA/TensorRT/files/11339566/build_01.log) (I split full log into two parts, github has max size limit for uploading file).I see a lots of `Int8[dim_0, dim_1, dim_2]` as well as `Float[dim_0, dim_1, ...]` at the end of build_01.log. 

you mean that even weights are stored in int8 format, but engine still possible run in fp32 precision? how to force the engine just choose int8 or fp16 implementation. 

And, I am a little confused. if export engine with `--best`, then the engine is expected to be faster than fp16 engine, isn't it? After all，there must exist some int8 layers.

**Comment by handoku** [comment]
Previous benchmark result has a mistake. New benchmark result on A10 is :

`unet-fp16.plan` : `44.8303 ms`
`unet-int8.plan` : `113.007 ms`
`unet-best.plan` : `81.7388 ms`

Still is not as expected.

**Comment by zerollzeng** [comment]
1. The precision in TRT in by "enable" but not "set", by default the FP32 precision is enabled, if you enable other precision like int8 or fp16 then trt will also profile those kernels and find the best performance kernel in global.
2. TRT has some heuristic inside for precision select, e.g. for some transformer structure int8 will produce very bad accuracy, so TRT will use FP16/FP32 for those layers even INT8 is enabled.
3. I can see lot of Cast layer in the log which set the precision explicitly from user's side.
4. `--best` means `--int8 --fp16`

**Comment by zerollzeng** [comment]
> `unet-fp16.plan` : `44.8303 ms`
> `unet-int8.plan` : `113.007 ms`
> `unet-best.plan` : `81.7388 ms`

Does the result reproduce with trtexec?

**Comment by handoku** [comment]
> 1. The precision in TRT in by "enable" but not "set", by default the FP32 precision is enabled, if you enable other precision like int8 or fp16 then trt will also profile those kernels and find the best performance kernel in global.
> 2. TRT has some heuristic inside for precision select, e.g. for some transformer structure int8 will produce very bad accuracy, so TRT will use FP16/FP32 for those layers even INT8 is enabled.
> 3. I can see lot of Cast layer in the log which set the precision explicitly from user's side.
> 4. `--best` means `--int8 --fp16`

Yes, I noticed `--int8 --fp16` has same performance as `--best`.
I unstand that trt use mixed-precision, but why not fallback to fp16 precision. I was expecting `--int8 --fp16` to be better than `--fp16`, at least

**Comment by zerollzeng** [comment]
This looks like a bug, could you please share the onnx model with us? Thanks!

**Comment by handoku** [comment]
@zerollzeng sorry，the model size is a little large, I can't find a convenient way to share it right now.
but I exported onnx file from `stable-diffusion-2.1-base` following `demo/Diffusion`, here is the code:
```python
import torch
from diffusers import StableDiffusionImg2ImgPipeline

def export_unet(model):
    model.eval()
    sample = torch.randn(2, 4, 96, 54, dtype=torch.float16, device=model.device)
    timestep = torch.tensor([1.], dtype=torch.float32, device=model.device)
    encoder_hidden_states = torch.randn(2, 77, 1024, dtype=torch.float16, device=model.device)
    inputs = (sample, timestep, encoder_hidden_states)
    for i in range(0):
        out = model(*inputs)
    import time
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    cnt = 0
    for i in range(cnt):
        out = model(*inputs)
    end.record()
    torch.cuda.synchronize()
    # print("unet avg time : ", start.elapsed_time(end) / 1000 / cnt)
    # print(out.sample.shape, out.sample.dtype)
    dynamic_axes = {
                'sample': {0: '2B', 2: '8H', 3: '8W'},
                'encoder_hidden_states': {0: '2B'},
                'latent': {0: '2B', 2: 'H', 3: 'W'}
            }
    with torch.inference_mode(), torch.autocast("cuda"):
        torch.onnx.export(model,
                        inputs,
                        "unet.onnx",
                        export_params=True,
                        opset_version=12,
                        do_constant_folding=True,
                        input_names=['sample', 'timestep', 'encoder_hidden_states'],
                        output_names=['latent'],
                        dynamic_axes=dynamic_axes,
                )
    '''
    ./TensorRT-8.6.0.12/bin/trtexec --onnx=unet.onnx --minShapes=\'sample\':2x4x8x8,\'encoder_hidden_states\':2x77x1024 --optShapes=\'sample\':4x4x64x64,\'encoder_hidden_states\':4x77x1024 --maxShapes=\'sample\':8x4x96x96,\'encoder_hidden_states\':8x77x1024  --buildOnly --saveEngine=unet.plan --memPoolSize=workspace:13888 --device=1 --fp16

    ./TensorRT-8.6.0.12/bin/trtexec --loadEngine=./unet.plan --device=2 --iterations=100 --warmUp=200 --shapes='sample':2x4x96x54,'encoder_hidden_states':2x77x1024
    '''
    print("export unet done")


model_id = "stabilityai/stable-diffusion-2-1-base"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
export_unet(pipe.unet)
```

**Comment by zerollzeng** [comment]
1.Could you build the engine with static shapes? e.g. `--optShapes='sample':2x4x96x54,'encoder_hidden_states':2x77x1024` 
2. Could you build and load the engine in the same device? e.g. device 1?

**Comment by zerollzeng** [comment]
BTW by pytorch env is kind of broken now, so I would appreciate if you can upload the onnx to google drive or upload to github us git lfs. Many thanks!

**Comment by handoku** [comment]
please download onnx file from this [here](https://drive.google.com/file/d/1zTledennE9JN6tA5ysdnduqdseIDw842/view?usp=share_link)

**Comment by zerollzeng** [comment]
I can't reproduce the issue.
int8 + fp16
```
[05/14/2023-04:31:44] [I] === Performance summary ===
[05/14/2023-04:31:44] [I] Throughput: 30.8434 qps
[05/14/2023-04:31:44] [I] Latency: min = 31.198 ms, max = 33.0905 ms, mean = 32.1222 ms, median = 32.0154 ms, percentile(90%) = 32.916 ms, percentile(95%) = 32.9651 ms, percentile(99%) = 33.0905 ms
[05/14/2023-04:31:44] [I] Enqueue Time: min = 27.7755 ms, max = 29.4277 ms, mean = 28.5828 ms, median = 28.4602 ms, percentile(90%) = 29.3256 ms, percentile(95%) = 29.3436 ms, percentile(99%) = 29.4277 ms
[05/14/2023-04:31:44] [I] H2D Latency: min = 0.0251465 ms, max = 0.0323486 ms, mean = 0.026692 ms, median = 0.0265503 ms, percentile(90%) = 0.0273438 ms, percentile(95%) = 0.0282593 ms, percentile(99%) = 0.0323486 ms
[05/14/2023-04:31:44] [I] GPU Compute Time: min = 31.1654 ms, max = 33.0587 ms, mean = 32.0889 ms, median = 31.9817 ms, percentile(90%) = 32.8837 ms, percentile(95%) = 32.9319 ms, percentile(99%) = 33.0587 ms
[05/14/2023-04:31:44] [I] D2H Latency: min = 0.00537109 ms, max = 0.00866699 ms, mean = 0.00656883 ms, median = 0.00634766 ms, percentile(90%) = 0.00749207 ms, percentile(95%) = 0.00756836 ms, percentile(99%) = 0.00866699 ms
[05/14/2023-04:31:44] [I] Total Host Walltime: 3.08008 s
[05/14/2023-04:31:44] [I] Total GPU Compute Time: 3.04845 s
[05/14/2023-04:31:44] [W] * Throughput may be bound by Enqueue Time rather than GPU Compute and the GPU may be under-utilized.
[05/14/2023-04:31:44] [W]   If not already in use, --useCudaGraph (utilize CUDA graphs where possible) may increase the throughput.
[05/14/2023-04:31:44] [W] * GPU compute time is unstable, with coefficient of variance = 1.81891%.
[05/14/2023-04:31:44] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[05/14/2023-04:31:44] [I] Explanations of the performance metrics are printed in the verbose logs.
[05/14/2023-04:31:44] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8601] # trtexec --loadEngine=unet-best.plan --shapes='sample':2x4x64x64,'encoder_hidden_states':2x77x1024
```
fp16
```
[05/14/2023-04:32:20] [I] === Performance summary ===
[05/14/2023-04:32:20] [I] Throughput: 23.401 qps
[05/14/2023-04:32:20] [I] Latency: min = 41.2711 ms, max = 43.8199 ms, mean = 42.1853 ms, median = 42.0254 ms, percentile(90%) = 42.7623 ms, percentile(95%) = 43.0861 ms, percentile(99%) = 43.8199 ms
[05/14/2023-04:32:20] [I] Enqueue Time: min = 37.4642 ms, max = 39.7625 ms, mean = 38.2745 ms, median = 38.1261 ms, percentile(90%) = 38.8303 ms, percentile(95%) = 39.1207 ms, percentile(99%) = 39.7625 ms
[05/14/2023-04:32:20] [I] H2D Latency: min = 0.0253906 ms, max = 0.032959 ms, mean = 0.0278485 ms, median = 0.027832 ms, percentile(90%) = 0.0286865 ms, percentile(95%) = 0.0292969 ms, percentile(99%) = 0.032959 ms
[05/14/2023-04:32:20] [I] GPU Compute Time: min = 41.2354 ms, max = 43.7862 ms, mean = 42.1507 ms, median = 41.9922 ms, percentile(90%) = 42.7274 ms, percentile(95%) = 43.052 ms, percentile(99%) = 43.7862 ms
[05/14/2023-04:32:20] [I] D2H Latency: min = 0.00537109 ms, max = 0.00866699 ms, mean = 0.00670592 ms, median = 0.00646973 ms, percentile(90%) = 0.00805664 ms, percentile(95%) = 0.00817871 ms, percentile(99%) = 0.00866699 ms
[05/14/2023-04:32:20] [I] Total Host Walltime: 3.11953 s
[05/14/2023-04:32:20] [I] Total GPU Compute Time: 3.077 s
[05/14/2023-04:32:20] [W] * Throughput may be bound by Enqueue Time rather than GPU Compute and the GPU may be under-utilized.
[05/14/2023-04:32:20] [W]   If not already in use, --useCudaGraph (utilize CUDA graphs where possible) may increase the throughput.
[05/14/2023-04:32:20] [W] * GPU compute time is unstable, with coefficient of variance = 1.16616%.
[05/14/2023-04:32:20] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[05/14/2023-04:32:20] [I] Explanations of the performance metrics are printed in the verbose logs.
[05/14/2023-04:32:20] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8601] # trtexec --loadEngine=unet-fp16.plan --shapes='sample':2x4x64x64,'encoder_hidden_states':2x77x1024
```

**Comment by handoku** [comment]
> I can't reproduce the issue. int8 + fp16
> 
> ```
> [05/14/2023-04:31:44] [I] === Performance summary ===
> [05/14/2023-04:31:44] [I] Throughput: 30.8434 qps
> [05/14/2023-04:31:44] [I] Latency: min = 31.198 ms, max = 33.0905 ms, mean = 32.1222 ms, median = 32.0154 ms, percentile(90%) = 32.916 ms, percentile(95%) = 32.9651 ms, percentile(99%) = 33.0905 ms
> [05/14/2023-04:31:44] [I] Enqueue Time: min = 27.7755 ms, max = 29.4277 ms, mean = 28.5828 ms, median = 28.4602 ms, percentile(90%) = 29.3256 ms, percentile(95%) = 29.3436 ms, percentile(99%) = 29.4277 ms
> [05/14/2023-04:31:44] [I] H2D Latency: min = 0.0251465 ms, max = 0.0323486 ms, mean = 0.026692 ms, median = 0.0265503 ms, percentile(90%) = 0.0273438 ms, percentile(95%) = 0.0282593 ms, percentile(99%) = 0.0323486 ms
> [05/14/2023-04:31:44] [I] GPU Compute Time: min = 31.1654 ms, max = 33.0587 ms, mean = 32.0889 ms, median = 31.9817 ms, percentile(90%) = 32.8837 ms, percentile(95%) = 32.9319 ms, percentile(99%) = 33.0587 ms
> [05/14/2023-04:31:44] [I] D2H Latency: min = 0.00537109 ms, max = 0.00866699 ms, mean = 0.00656883 ms, median = 0.00634766 ms, percentile(90%) = 0.00749207 ms, percentile(95%) = 0.00756836 ms, percentile(99%) = 0.00866699 ms
> [05/14/2023-04:31:44] [I] Total Host Walltime: 3.08008 s
> [05/14/2023-04:31:44] [I] Total GPU Compute Time: 3.04845 s
> [05/14/2023-04:31:44] [W] * Throughput may be bound by Enqueue Time rather than GPU Compute and the GPU may be under-utilized.
> [05/14/2023-04:31:44] [W]   If not already in use, --useCudaGraph (utilize CUDA graphs where possible) may increase the throughput.
> [05/14/2023-04:31:44] [W] * GPU compute time is unstable, with coefficient of variance = 1.81891%.
> [05/14/2023-04:31:44] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
> [05/14/2023-04:31:44] [I] Explanations of the performance metrics are printed in the verbose logs.
> [05/14/2023-04:31:44] [I]
> &&&& PASSED TensorRT.trtexec [TensorRT v8601] # trtexec --loadEngine=unet-best.plan --shapes='sample':2x4x64x64,'encoder_hidden_states':2x77x1024
> ```
> 
> fp16
> 
> ```
> [05/14/2023-04:32:20] [I] === Performance summary ===
> [05/14/2023-04:32:20] [I] Throughput: 23.401 qps
> [05/14/2023-04:32:20] [I] Latency: min = 41.2711 ms, max = 43.8199 ms, mean = 42.1853 ms, median = 42.0254 ms, percentile(90%) = 42.7623 ms, percentile(95%) = 43.0861 ms, percentile(99%) = 43.8199 ms
> [05/14/2023-04:32:20] [I] Enqueue Time: min = 37.4642 ms, max = 39.7625 ms, mean = 38.2745 ms, median = 38.1261 ms, percentile(90%) = 38.8303 ms, percentile(95%) = 39.1207 ms, percentile(99%) = 39.7625 ms
> [05/14/2023-04:32:20] [I] H2D Latency: min = 0.0253906 ms, max = 0.032959 ms, mean = 0.0278485 ms, median = 0.027832 ms, percentile(90%) = 0.0286865 ms, percentile(95%) = 0.0292969 ms, percentile(99%) = 0.032959 ms
> [05/14/2023-04:32:20] [I] GPU Compute Time: min = 41.2354 ms, max = 43.7862 ms, mean = 42.1507 ms, median = 41.9922 ms, percentile(90%) = 42.7274 ms, percentile(95%) = 43.052 ms, percentile(99%) = 43.7862 ms
> [05/14/2023-04:32:20] [I] D2H Latency: min = 0.00537109 ms, max = 0.00866699 ms, mean = 0.00670592 ms, median = 0.00646973 ms, percentile(90%) = 0.00805664 ms, percentile(95%) = 0.00817871 ms, percentile(99%) = 0.00866699 ms
> [05/14/2023-04:32:20] [I] Total Host Walltime: 3.11953 s
> [05/14/2023-04:32:20] [I] Total GPU Compute Time: 3.077 s
> [05/14/2023-04:32:20] [W] * Throughput may be bound by Enqueue Time rather than GPU Compute and the GPU may be under-utilized.
> [05/14/2023-04:32:20] [W]   If not already in use, --useCudaGraph (utilize CUDA graphs where possible) may increase the throughput.
> [05/14/2023-04:32:20] [W] * GPU compute time is unstable, with coefficient of variance = 1.16616%.
> [05/14/2023-04:32:20] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
> [05/14/2023-04:32:20] [I] Explanations of the performance metrics are printed in the verbose logs.
> [05/14/2023-04:32:20] [I]
> &&&& PASSED TensorRT.trtexec [TensorRT v8601] # trtexec --loadEngine=unet-fp16.plan --shapes='sample':2x4x64x64,'encoder_hidden_states':2x77x1024
> ```

Confirmed.

This performance issue has been resolved after upgrading to TensorRT 8.6.1.6 from 8.6.0.12. Thus, I am closing this issue

**Comment by handoku** [comment]
@bigmover 
With tensorrt 8.6, int8 precision hurts model performance indeed. I didn't use int8 in production.

According to [this](https://developer.nvidia.com/blog/tensorrt-accelerates-stable-diffusion-nearly-2x-faster-with-8-bit-post-training-quantization/), latest trt developed a better quantization toolkit to preserve image quality, you can have a try.

**Comment by bigmover** [comment]
> @bigmover With tensorrt 8.6, int8 precision hurts model performance indeed. I didn't use int8 in production.
> 
> According to [this](https://developer.nvidia.com/blog/tensorrt-accelerates-stable-diffusion-nearly-2x-faster-with-8-bit-post-training-quantization/), latest trt developed a better quantization toolkit to preserve image quality, you can have a try.

Appreciate for your kind reply!  Maybe new tensorrt toolkit will be a good choice for calibration SD. But I don't know how to make it for img2img that init noise from real image.  Thanks for your reply again!
