### ISSUE TITLE
4090 is slower than 1080

### ISSUE THREAD

**Issue by MacieJayDaaaaa** [NVIDIA/TensorRT#2907]
## Description

I have implemented instance segmentation using the Solov2 model. The inference time for 832 * 256 images is 25-35ms, the gpu is 1080, the  driver version is 496.49, the Tensorrt version is 7.2.3.4, and the Cuda version is 11.1. Now I have a 4090, I have to upgrade the driver version to 531.61, but the previous code reported an error, so I upgraded Tensorrt to 8.6.0.12, and the Cuda version is still 11.1. I replaced some outdated interfaces and modified some programs to make the code compileable. My program can be run again, but to my disappointment, the  inference time for 832 * 256 images has changed to 25-55ms. Why is this situation happening? How can I modify the code to ensure that I improve the inference speed?
## Environment
old:
**TensorRT Version**: 7.2.3.4
**NVIDIA GPU**: 1080
**NVIDIA Driver Version**: 496.49
**CUDA Version**: 11.1
**CUDNN Version**: 8.1.0
**Operating System**: win10

new:
**TensorRT Version**: 8.6.0.12
**NVIDIA GPU**: 4090
**NVIDIA Driver Version**: 531.61
**CUDA Version**: 11.1
**CUDNN Version**: 8.1.0
**Operating System**: win10

```[tasklist]
```

**Comment by MacieJayDaaaaa** [comment]
25-35ms is a time-consuming process that includes preprocessing, inference, and post-processing. The increased time consumption of 25-55ms should come from the inference.

**Comment by MacieJayDaaaaa** [comment]
25-35ms is a time-consuming process that includes preprocessing, inference, and post-processing. The increased time consumption of 25-55ms should come from the inference.

**Comment by zerollzeng** [comment]
I think you can analysis the reason with Nsight System, too see where is the bottleneck.

Also I would suggest using CUDA 12 for 4090 and TRT 8.6, good to know that you've upgraded the driver.

**Comment by MacieJayDaaaaa** [comment]
> I think you can analysis the reason with Nsight System, too see where is the bottleneck.
> 
> Also I would suggest using CUDA 12 for 4090 and TRT 8.6, good to know that you've upgraded the driver.

![image](https://user-images.githubusercontent.com/102528658/236601205-2ec17f79-52e8-4e73-a5ef-3c36aab43066.png)
I upgraded to cuda12.1, but the issue of time fluctuations still exists. I put my Tensorrt8 code on another 1080 computer and it didn't experience any time fluctuations, and it only took 25ms. I think the reason for the fluctuation in time consumption is not in the 4090, but in the driver, because I have previously experimented with higher versions of drivers (500+), which have the problem of time consumption fluctuation on the 2070. I used  Nsight System to analyze the time consumption situation, and the time consumption on the GPU seems to fluctuate. Do you know how to solve such a problem?

**Comment by MacieJayDaaaaa** [comment]
A driver version that does not fluctuate cannot recognize 4090

**Comment by zerollzeng** [comment]
Yeah that looks like a driver issue, to confirm this, could you try running your model with trtexec(a tool proviced by TRT that use for perf check). it should come with your TRT package under the sample. a simple usage would be like `trtexec --onnx=model.onnx`, you can check more option with `trtexec -h`.

**Comment by zerollzeng** [comment]
See https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#trtexec

**Comment by MacieJayDaaaaa** [comment]
![image](https://user-images.githubusercontent.com/102528658/236721009-dee48a80-ee3b-4c06-bb57-67b0c3ca8398.png)
![image](https://user-images.githubusercontent.com/102528658/236721070-391e37d8-8bc3-4f91-bed2-6f68e1e4c768.png)
![image](https://user-images.githubusercontent.com/102528658/236721116-f94fff83-0872-4e92-9f7d-9ed756552e83.png)
![image](https://user-images.githubusercontent.com/102528658/236721147-fecbcbee-71c8-440b-a07f-f0ee55e82505.png)
![image](https://user-images.githubusercontent.com/102528658/236721182-01e5d37f-be39-4c6e-8e11-5ae3b2664d10.png)
![image](https://user-images.githubusercontent.com/102528658/236721213-72f48ae9-079f-4b06-8e02-12650838c7ae.png)





> Yeah that looks like a driver issue, to confirm this, could you try running your model with trtexec(a tool proviced by TRT that use for perf check). it should come with your TRT package under the sample. a simple usage would be like `trtexec --onnx=model.onnx`, you can check more option with `trtexec -h`.

thank you,I run my model with trtexec,and here is the result:

![image](https://user-images.githubusercontent.com/102528658/236721009-dee48a80-ee3b-4c06-bb57-67b0c3ca8398.png)
![image](https://user-images.githubusercontent.com/102528658/236721070-391e37d8-8bc3-4f91-bed2-6f68e1e4c768.png)
![image](https://user-images.githubusercontent.com/102528658/236721116-f94fff83-0872-4e92-9f7d-9ed756552e83.png)
![image](https://user-images.githubusercontent.com/102528658/236721147-fecbcbee-71c8-440b-a07f-f0ee55e82505.png)
![image](https://user-images.githubusercontent.com/102528658/236721182-01e5d37f-be39-4c6e-8e11-5ae3b2664d10.png)
![image](https://user-images.githubusercontent.com/102528658/236721213-72f48ae9-079f-4b06-8e02-12650838c7ae.png)

**Comment by MacieJayDaaaaa** [comment]
> Yeah that looks like a driver issue, to confirm this, could you try running your model with trtexec(a tool proviced by TRT that use for perf check). it should come with your TRT package under the sample. a simple usage would be like `trtexec --onnx=model.onnx`, you can check more option with `trtexec -h`.

thank you,I run my model with trtexec and here is the result:

![image](https://user-images.githubusercontent.com/102528658/236721009-dee48a80-ee3b-4c06-bb57-67b0c3ca8398.png)
![image](https://user-images.githubusercontent.com/102528658/236721070-391e37d8-8bc3-4f91-bed2-6f68e1e4c768.png)
![image](https://user-images.githubusercontent.com/102528658/236721116-f94fff83-0872-4e92-9f7d-9ed756552e83.png)
![image](https://user-images.githubusercontent.com/102528658/236721147-fecbcbee-71c8-440b-a07f-f0ee55e82505.png)
![image](https://user-images.githubusercontent.com/102528658/236721182-01e5d37f-be39-4c6e-8e11-5ae3b2664d10.png)
![image](https://user-images.githubusercontent.com/102528658/236721213-72f48ae9-079f-4b06-8e02-12650838c7ae.png)

**Comment by MacieJayDaaaaa** [comment]
![image](https://user-images.githubusercontent.com/102528658/236981265-0d5d6bf4-a2ec-4c91-82d8-5f7e78eff338.png)
![image](https://user-images.githubusercontent.com/102528658/236983134-58252ac3-70a0-43fa-ad2d-7594a1ba09be.png)
![image](https://user-images.githubusercontent.com/102528658/236983174-daee968e-1b0a-41ac-97c8-9a95d0b284cf.png)

I have noticed an increase in time consumption. I used a pic to loop through executeV2, and through the printing time, I found that the initial time consumption was about 2.9ms(hhhh:2.9048), which is close to the 3.48ms measured by trtexec. However, as the loop runs, the time consumption will significantly increase to 10ms

**Comment by MacieJayDaaaaa** [comment]
> the median latency is 3.48633ms for single inference.
> 
> Can you compare the latency between old and new env?

In version 7.2.3.4, I used execute, but after switching to version 8.6, I changed to executev2

**Comment by MacieJayDaaaaa** [comment]
![image](https://user-images.githubusercontent.com/102528658/237002526-8df4256b-4bd9-4134-a536-aff446853ff3.png)
![image](https://user-images.githubusercontent.com/102528658/237002580-791ecb4c-52f7-4674-bb0b-c9af30b4206f.png)
![image](https://user-images.githubusercontent.com/102528658/237002619-55289fcc-2e3d-4af6-8dd7-dda3789b35fe.png)

In addition, buffermanager ->copyOutputToHost also has this issue, and I believe that the increase in time consumption for these two items is the key to fluctuations

**Comment by MacieJayDaaaaa** [comment]
After my testing, I found that the matrix multiplication (*) and minAreaRect of opencv used in the post-processing code can have an impact on the aforementioned operations of Tensorrt! When I delete minAreaRect and rewrite the matrix multiplication with a loop, the copyOutputToHost will not increase the time consumption, which makes me more confused. Why do these operations of opencv affect the tensorrt?

**Comment by zerollzeng** [comment]
I would suggest using enqueueV3 and explicit stream synchronize. execute_v2() will use the default cuda stream and may have impact on other component that use GPU.

**Comment by zerollzeng** [comment]
see https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html#stream-sync-behavior__default-stream

**Comment by zerollzeng** [comment]
And I can see the time in trtexec is stable.

**Comment by MacieJayDaaaaa** [comment]
I used enqueueV3, but post-processing still has an impact on Tensorrt. By searching for information, I locked the clock frequency of 4090 to 3120mhz. At this point, the time fluctuation of my program disappeared, and a picture took 20ms, which is faster than 1080. I think there is still room for optimization in my code, as currently 4090 is only 20% faster than 1080. thank you

**Comment by zerollzeng** [comment]
Sorry I forget to mention fixing the GPU clocks, can we close this issue? Fell free to reopen it if you have any further questions.

**Comment by MacieJayDaaaaa** [comment]
ok，thank you

**Comment by zerollzeng** [comment]
You can check the freq by `nvidia-smi dmon -s pcuv`

**Comment by MacieJayDaaaaa** [comment]
I seem to have found the problem. Through nvidia-smi, I found that my gpu's Performance State is running in P8 mode. How can I change it to P0?

**Comment by zerollzeng** [comment]
Acutually I don't know the answer so I ask chatgpt :-) `nvidia-smi -pm 1` is his answer.

**Comment by ttyio** [comment]
closing since there is answer in the last comment, thanks all!
