### ISSUE TITLE
Error when upgrade TensorRT 6 to TensorRT 7

### ISSUE THREAD

**Issue by zerollzeng** [NVIDIA/TensorRT#291]
## Environment

**TensorRT Version**:  TensorRT 7
**GPU Type**: 2080ti
**Nvidia Driver Version**: 418.39
**CUDA Version**: 10.0
**CUDNN Version**:  7.6
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

when I upgrade TensorRT 6 to TensorRT 7 for my open source project [tiny-tensorrt](https://github.com/zerollzeng/tiny-tensorrt),  every thing is fine during building. but when I test it with openpose. these errors occur while parsing caffe model.
```
[2019-12-23 16:05:13.762] [info] build caffe engine with ../models/openpose/pose_deploy.prototxt and ../models/openpose/pose_iter_584000.caffemodel
(Unnamed Layer* 22) [Constant]: constant weights has count 512 but 60 was expected
testopenpose: ./parserHelper.h:99: nvinfer1::DimsCHW parserhelper::getCHW(const nvinfer1::Dims&): Assertion `d.nbDims >= 3' failed.
Aborted (core dumped)
```
here is the link of [caffe prototxt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/models/pose/body_25/pose_deploy.prototxt)
I read the change log that TensorRT 7 has official Parametric ReLU layer support, so I delete my own PReLU plugin implementation, if I use my plugin, everything is just fine.
Does anybody knows the reason? or there are bugs in PReLU.

**Comment by rmccorm4** [comment]
Hi @zerollzeng,

The Release Notes mention PReLU Op as a built-in op for the ONNX parser. They also mention that the Caffe/UFF parsers are being deprecated in the future, so ONNX is the way to go: 

```
Deprecation of Caffe Parser and UFF Parser - We are deprecating Caffe Parser and UFF Parser in TensorRT 7. They will be tested and functional in the next major release of TensorRT 8, but we plan to remove the support in the subsequent major release. Plan to migrate your workflow to use tf2onnx, keras2onnx or TensorFlow-TensorRT (TF-TRT) for deployment.
```

You can also see the PReLU op is not listed under the supported Caffe ops here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#supported-ops.

So if you plan to use Caffe, you'll have to continue to use your own plugin. But I would recommend moving to using ONNX for the future.

**Comment by zerollzeng** [comment]
Thanks for your reply  @rmccorm4, I will focus on onnx parser  for my project from now

**Comment by Raven888888** [comment]
@zerollzeng 
Hi, would be interested to know how do you implement the plugin for prelu op. Will it work on tensorrt 5?

**Comment by zerollzeng** [comment]
@Raven888888 I write an tutorial about how to implement a custom plugin,see [here](https://github.com/zerollzeng/tiny-tensorrt/blob/master/docs/CustomPlugin.md), and if you want a implementation of tensorrt5, you can clone this project and reset to tensorrt5 commit, then you can copy my implementation
