### ISSUE TITLE
TensorRT 7 for Jetson / Jetpack

### ISSUE THREAD

**Issue by j-o-d-o** [NVIDIA/TensorRT#292]
While the TensorRT is now at v7, the cross compile for the Jetson Platforms is still at v6. I had issues on the ONNX parser on v6 which are fixed on the new release and now my code only works on the host machine but not on the Jetson.

Is it planned to update the TensorRT version on the Docker images anytime soon? In my book it would be important to always have the same versions on all the platforms available, cause otherwise you can run into problems that your code only works on one side. But then again, I don't know all the system restrictions.

**Comment by rmccorm4** [comment]
Hi @j-o-d-o,

TRT7 for Jetpack hasn't been released yet, sorry but you'll have to stay tuned 🤞

**Comment by un-knight** [comment]
> Hi @j-o-d-o,
> 
> TRT7 for Jetpack hasn't been released, sorry but you'll have to stay tuned

How long will it takes for Jetpack TRT7 to release? I am really hoping to use TRT7 on TX2 as early as possible.

**Comment by maaft** [comment]
TRT7 would be very useful indeed!

**Comment by PythonImageDeveloper** [comment]
Is it possible to convert the onnx model to TensorRT 7 on the host PC computer and then use the converted model on jetson nano with TensorRT 6?

**Comment by depthwise** [comment]
@PythonImageDeveloper apparently not: 

```
[TensorRT] ERROR: ../rtSafe/coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
```

**Comment by PythonImageDeveloper** [comment]
@depthwise 
you converted with TensorRT7 on host PC and run on jetson nano with TensorRT 6, you get this errors?

**Comment by depthwise** [comment]
I tried it on Jetson Xavier, but yes, this is an attempt to run TRT7 model on TRT6.

**Comment by rmccorm4** [comment]
TensorRT engines are currently not portable across versions, even on the same machine. A TensorRT engine built with one version should expect to see this error `Serialization Error in verifyHeader: 0 (Version tag does not match)` if used in another version.

**Comment by hyperfraise** [comment]
I'm very interested in this too. Trying to deploy tensorrt 3D conv models on jetsons.

**Comment by j-o-d-o** [comment]
@rmccorm4 Any updates on the timeline when we might seen TensorRT 7 ready on the Jetson Nano?

**Comment by rmccorm4** [comment]
@j-o-d-o Unfortunately, I can't share that information 😕

**Comment by jinfagang** [comment]
@rmccorm4 So it's 2020, tensorrt 7 will ported to jetson nano?

**Comment by mirecta** [comment]
so nvidia ignore it , they not need to sell jetson boards

**Comment by jinfagang** [comment]
@mirecta No, they just sold jetson boards and stop software upgrading then you have to buy next generation.

**Comment by hyperfraise** [comment]
> @mirecta No, they just sold jetson boards and stop software upgrading then you have to buy next generation.

Such cynicism. I don't think that's the matter here. TensorRT was only just released. I do think it'll be compatible in the future. And you know that currently, no "next generation" jetson supports it, so they don't have anything to push you toward...

**Comment by glenosborne** [comment]
I would like an indication of a release date, approximate it if you have too, we are waiting on this release and would help if we could schedule work around this release. Please give a month or months range so we can at least plan our development. Thanks

**Comment by Smankusors** [comment]
I saw that there's [JetPack 4.4 Developer Preview](https://docs.nvidia.com/jetson/jetpack/release-notes/) which have TensorRT 7.1.0 Developer Preview, might you guys want to try it out.

**Comment by glenosborne** [comment]
Hi Antony,


Thank you very much for letting me know,
How can i get into the developer preview or where do i download
the Jetpack 4.4 developer preview.

This is fantastic, thank you for the email i am really looking forward to
this.

Regards Glen


Glen Osborne

Web Developer



Head Office: PO Box 12-236, Penrose, Auckland 1642, New Zealand

T: +64 (09) 253 9141   |   M: +21 830 811  |   E: gleno@asgtech.co.nz<mailto:matthewp@asgtech.co.nz>   |   W: www.asgtechnologies.co<http://www.asgtechnologies.co/>

[cid:00b603ea-2b46-4790-8aa4-9592ebaeff6e]
________________________________

**Comment by Smankusors** [comment]
You can download the Jetpack developer preview via [this page](https://developer.nvidia.com/jetson-nano-sd-card-image) :slightly_smiling_face:

**Comment by gasparramoa** [comment]
I already test **_TensorRT 7.1_**  in Jetson Nano and it's **not compatible** with **_TensorRT 7.0.0.11_** for the desktop computer.

I tried to use a _TensorRT_ model in Jetson Nano and the same error appeared when I built the engine:
```
[TensorRT] ERROR: ../rtSafe/coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed
```

For the context, I was trying to convert a _Pytorch_ model into a _TensorRT_ model. 
I first converted the _Pytorch_ to an _ONNX_ model and then converted it to _TensorRT_ in the desktop computer.
```
[Torch Model] -> [ONNX model] -> [TensorRT model]
```

The **solution** was to convert the _ONNX_ model in the Jetson Nano instead of using the _TensorRT_ model converted in the desktop computer. If you convert the _ONNX_ model in Jetson Nano to _TensorRT_, the model will be a _TensorRT 7.1_ and you will be able to built the engine.

**Comment by depthwise** [comment]
@gasparramoa IIRC that's by design. When TRT launches a model it first profiles it directly on the device to establish which algorithms have the best performance. This can't be done on another device.

**Comment by PythonImageDeveloper** [comment]
@gasparramoa, 
You told, **TensorRT 7.1 in Jetson Nano**, which jetpack version? 4.4?
Is it possible to share you codes for converting pytorch model to onnx model and then TensorRT model?

**Comment by gasparramoa** [comment]
I used the **JetPack 4.4**.
To convert the _Torch model_ to _ONNX model_ I used this function of Pytorch: [Check here](https://pytorch.org/docs/stable/onnx.html)
```
torch.onnx.export()
```
I used the **_opset_version 11_** in the _ONNX_ model.

To convert the ONNX to TensorRT I used the _**onnx2trt**_: [Here](https://github.com/onnx/onnx-tensorrt)

**Comment by PythonImageDeveloper** [comment]
Thanks,
Whta's exactly **opset_version 11**? for each model this should be changable?

**Comment by beizhengren** [comment]
> > Hi @j-o-d-o,
> > TRT7 for Jetpack hasn't been released, sorry but you'll have to stay tuned
> 
> How long will it takes for Jetpack TRT7 to release? I am really hoping to use TRT7 on TX2 as early as possible.

@rmccorm4 @un-knight Hi, does TRT7 support with TX2? 
Thanks!

**Comment by rajeevsrao** [comment]
Folks, please check the Jetpack 4.4 SDK with TensorRT 7.1.3 and support for TX2: https://developer.nvidia.com/embedded/jetpack
