### ISSUE TITLE
how would do you specify your bindings now that enqueueV3 only accepts a stream as argument?

### ISSUE THREAD

**Issue by ervgan** [NVIDIA/TensorRT#2930]
## Description

Hi, how would do you specify your bindings now that enqueueV3 only accepts a stream as argument? In EnqueueV2, it was still pretty clear since we use Explicit batch mode so we do not have to specify the batch size anymore in EnqueueV2 but for EnqueueV3, how does TensorRT know where the gpu buffers are for input/ouput if we don't specify the bindings?

Do I now need to use context->setTensorAddress() to set input and output device buffers?

Thanks!

**Comment by adujardin** [comment]
Hi, you need to use `nvinfer1::IExecutionContext::setTensorAddress` (or `setInputTensorAddress`) function for each bindings https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_execution_context.html#a96ecfa1a2fdcc7219155b065c8bd0ea2

**Comment by ervgan** [comment]
Thanks!
