### ISSUE TITLE
plugin supporting int8 input and output 

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2935]
I'm trying to create a plugin with one input and one output with kint8 type using onnx-trt. When I build the engine using c++, it checks supportsFormatCombination function. It shows the input which supposed to have kint8 type has kFLOAT type. Do I need to set the input type anywhere?

**Comment by zerollzeng** [comment]
Try this: https://github.com/NVIDIA-AI-IOT/tensorrt_plugin_generator

**Comment by shuyuan-wang** [comment]
Hi, I Tried it, but during the building process, the type I got from inOut in supportsFormatCOmbination is still kint8. Why is this happening?

**Comment by zerollzeng** [comment]
> the type I got from inOut in supportsFormatCombination is still kfloat. Why is this happening?

Please read our api doc and developer guide. e.g. https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_plugin_v2_dynamic_ext.html#aea845140b27ee59c08f6304b84addc72

`nvinfer1::IPluginV2DynamicExt::supportsFormatCombination` is used for query all available format combination for your plugins, return true mean the format combination is supported by your plugin implementation.

**Comment by shuyuan-wang** [comment]
> > the type I got from inOut in supportsFormatCombination is still kfloat. Why is this happening?
> 
> Please read our api doc and developer guide. e.g. https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_plugin_v2_dynamic_ext.html#aea845140b27ee59c08f6304b84addc72
> 
> `nvinfer1::IPluginV2DynamicExt::supportsFormatCombination` is used for query all available format combination for your plugins, return true mean the format combination is supported by your plugin implementation.

If the function is to query all available format combination for my plugin, does it mean I need to configure my plugin to explicitly support kint8 input? For instance, set the input tensordesc  type to kint8? I can't exactly use the code generated from your plugin generator since I am inheriting from other classes written by us. However, when I check the code, the kint8 type is only used when chekcing supportsformatcombination. So, I guess there's something I'm missing here.

Here's a link to my onnx which I'm trying to use onnx-trt to trace and build, can you please take a look at it and give me some suggestions on how to deal with it?
https://drive.google.com/file/d/1Qk7cSRnBvTIEsc1LYZNlSs-bv732DLoH/view?usp=sharing

**Comment by shuyuan-wang** [comment]
If so, what might go wrong and not letting the network building process not recognizing the input tensor desc not kint8 but kfloat?

**Comment by zerollzeng** [comment]
I have a simple solution for you: Let the plugin take FP32 and INT32 IO, and do the int8 quantize inside the plugin, it will add 2 extra IO reformats, but the influence should be very small, pros is you don't need to bother the int8 issue.
