### ISSUE TITLE
Onnx-outputs mark all leads to sigmoid node outputs none in output results.

### ISSUE THREAD

**Issue by salt-fisher** [NVIDIA/TensorRT#2938]
## Description
  I am recording the output of onnx model, which has some sigmoid nodes in the graph. With the following command:
polygraphy run model.onnx  --onnxrt --onnx-outputs mark all --input-shapes images:[1,3,1280,1280].
Get error like this:
![image](https://user-images.githubusercontent.com/43306141/236616921-fffde1c6-96ee-499b-80f5-bee46518dcf7.png)
I try to locate the point leading the error, and find that sigmoid nodes output is None.
Is there anything wrong I process ?
How can I fix it.

**Comment by zerollzeng** [comment]
Does it work if you don't use `--mark all`? we don't recommend using it since it will break all the layer fusion inside TRT.

**Comment by salt-fisher** [comment]
@zerollzeng it works well if i don't use `--onnx-outputs mark all` , because it won't save sigmoid node output which is None and trigger an error for `None.dtype.`
