### ISSUE TITLE
Diffusion demo doesn't work on H100

### ISSUE THREAD

**Issue by alexeigor** [NVIDIA/TensorRT#2939]
## Description
Now Diffusion demo use torch < 2.0.0, but it doesn't support H100 GPU's.

**Comment by zerollzeng** [comment]
@rajeevsrao @nvpohanh ^ ^

**Comment by rajeevsrao** [comment]
Hi @alexeigor, TensorRT supports H100, but public torch 1.x releases do not. We limited the torch version to 1.x to work around ONNX export issues in torch 2.0.0. While we work on a fix for that, can you please give our NGC pytorch container a try? Specifically, `nvcr.io/nvidia/pytorch:23.02-py3` has a custom torch 1.14 build that supports H100.

Thanks.

**Comment by alexeigor** [comment]
nice, now it works https://github.com/alexeigor/sd-benchmarks/blob/main/tensorrt/Dockerfile
