### ISSUE TITLE
create_execution_context() doesn't release GIL (TensorRT 8.2)

### ISSUE THREAD

**Issue by Fred-Erik** [NVIDIA/TensorRT#2945]
## Description

create_execution_context() doesn't release the Python GIL, see the pybind code [here](https://github.com/NVIDIA/TensorRT/blob/master/python/src/infer/pyCore.cpp#L654). Would it be possible to add a `py::call_guard<py::gil_scoped_release>{}` there? On a Jetson TX2, for my model, it takes about 7.5 seconds to create the execution context. This makes my semi-realtime program unresponsive during this period, and it would be nicer if the Python interpreter kept functioning.

**Comment by zerollzeng** [comment]
@pranavm-nvidia ^ ^

**Comment by ttyio** [comment]
This is fixed in 9.0, see https://github.com/NVIDIA/TensorRT/blob/release/9.0/python/src/infer/pyCore.cpp#L1041
closing and thanks all!
