### ISSUE TITLE
Problem about NHWC8 layout

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#2947]
## Description

For `NC/xHWx` layout format:     
Only the channel dimension, C, is grouped into x channels each.
When x = 1, each group has only one channel, the elements of one channel (that is, one group) are arranged contiguously (in the row-major order), before proceeding to the next group (that is, next channel). The same as `NCHW` format.

For `NHWC8`  layout format:       
In TRT,  `Channel major FP16 format where channel % 8 == 0`  map to `NHWC8`,   

if C % 8 == 0,  it(NHWC8) equal NHWC ?   `NHWC8 == NHWC `      

Thanks for NV-er reply in advance.

**Comment by zerollzeng** [comment]
See https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#ac3e115b1a2b1e578e8221ef99d27cd45

I think only when C<=8, NHWC8 is equal to NC/8HW8(although we don't have this tensor format in the above link), you can take the kCHW16 and kHWC16 as example, they are the same if C<=16. @ttyio @nvpohanh please correct me if I'm wrong.

**Comment by lix19937** [comment]
> if C % 8 == 0, it(NHWC8) equal NHWC ?  NHWC8 == NHWC    

@zerollzeng  Here I assume `C >= 8`

**Comment by zerollzeng** [comment]
Oh sorry, I misread as HWC8 and CHW8. When C >= 8 and C % 8 == 0. NHWC8 is the same as NHWC, you are correct.

**Comment by lix19937** [comment]
@zerollzeng  Thanks for your reply.   Now  closed.
