### ISSUE TITLE
L4T docker container release for TensorRT 8.6.1 on NGC? (Jetson Orin)

### ISSUE THREAD

**Issue by niqbal996** [NVIDIA/TensorRT#2949]
## Description

I have a model that I can successfully export to TensorRT engine file via TensorRT 8.6.1 on my laptop. I used the TensorRT docker container on the NGC for that. Now I want to deploy it on the Jetson Orin but there are no L4T docker containers provided for 8.6.1 version so far. I cannot use any earlier version of TensorRT because then the ONNX to TRT conversion will fail due to this issue https://github.com/NVIDIA/TensorRT/issues/2721 and https://github.com/NVIDIA/TensorRT/issues/2678. Are there any plans to release it in the near future (roughly when)? Or will I have to build the containers myself. I have never done that. If so, please guide me.  

## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: RTX 2070 and Jetson Orin

**CUDA Version**: 11.4

**CUDNN Version**: 

Operating System: Ubuntu 20.04 

Baremetal or Container (if so, version): nvcr.io/nvidia/tensorrt:23.04-py3

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: Yes. 

**Can this model run on other frameworks?** My model export works successfully on my laptop with the TensorRT 8.6.1 and I can generate and load the engine files. But these files are not transferrable to Jetson Orin since they are GPU specific (correct me if I am wrong.)

**Comment by ttyio** [comment]
closing since there is already solution in last comment, thanks all!
