### ISSUE TITLE
TensorRT 7 for BERT

### ISSUE THREAD

**Issue by lingjiew** [NVIDIA/TensorRT#295]
Hi,

Will the BERT based on tensorrt 7 be released soon? 
I'm very interested in the int8 performance for bert.

**Comment by taomiao** [comment]
emmm, I am thinking the same thing.

**Comment by rajeevsrao** [comment]
@lingjiew @taomiao you can get demoBERT w/ TensorRT 7 support here: https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT
