### ISSUE TITLE
TensorRT Python Bindings for CUDA11.8 and Python3.9: Missing setup.py

### ISSUE THREAD

**Issue by kmpape** [NVIDIA/TensorRT#2950]
Hi,

I am trying to obtain TensorRT for Python3.9 and CUDA11.8 using branch release/8.6. I read this [post](https://forums.developer.nvidia.com/t/tensorrt-on-jetson-with-python-3-9/196131/9) I have followed the readme to build the [TensorRT OSS](https://github.com/NVIDIA/TensorRT/blob/release/8.6/README.md), which worked fine, and I followed the readme for the [Python bindings](https://github.com/NVIDIA/TensorRT/blob/release/8.6/python/README.md). For the latter, I have replaced 3.8 with 3.9 throughout and called it as
`PYTHON_MAJOR_VERSION=3 PYTHON_MINOR_VERSION=9 TARGET_ARCHITECTURE=x86_64 EXT_PATH=/home/external ./build.sh`
where `/home/external ` is mounted in the docker and contains folder `python3.9`. I have two issues:

1. CMakeLists throws the an error:
```
CMake Error at CMakeLists.txt:68 (if):
  if given arguments:

    "STREQUAL" "tensorrt"
```
I fixed this by adding `-DTENSORRT_MODULE="tensorrt"` to build.sh. Is it correct to do so?

2. After fixing the first error, it seems to build fine but the last line of build.sh, which is
`python3 setup.py -q bdist_wheel --python-tag=cp${PYTHON_MAJOR_VERSION}${PYTHON_MINOR_VERSION} --plat-name=linux_${TARGET}`
cannot find the file setup.py. Shouldn't this file be somewhere on the repository here, or is it automatically generated at some step?

<details>
PYTHON_MAJOR_VERSION=3 PYTHON_MINOR_VERSION=9 TARGET_ARCHITECTURE=x86_64 EXT_PATH=/home/external ./build.sh
/workspace/TensorRT/python/build /workspace/TensorRT/python
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/TensorRT/python/build
Scanning dependencies of target tensorrt
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyAlgorithmSelector.cpp.o
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyCore.cpp.o
[ 25%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyFoundationalTypes.cpp.o
[ 33%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyGraph.cpp.o
[ 41%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o
[ 50%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyPlugin.cpp.o
[ 58%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyCaffe.cpp.o
[ 66%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyOnnx.cpp.o
[ 75%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyUff.cpp.o
[ 83%] Building CXX object CMakeFiles/tensorrt.dir/src/pyTensorRT.cpp.o
[ 91%] Building CXX object CMakeFiles/tensorrt.dir/src/utils.cpp.o
[100%] Linking CXX shared library tensorrt/tensorrt.so
[100%] Built target tensorrt
Generating python 3.9 bindings for TensorRT 8.6.1.5
/workspace/TensorRT/python/packaging /workspace/TensorRT/python/build /workspace/TensorRT/python
/workspace/TensorRT/python/build /workspace/TensorRT/python
python3: can't open file 'setup.py': [Errno 2] No such file or directory
</details>

PS: I guess that I need to re-run the problematic line with `python3.9` at some point?

Thank you very much for your help.

GNU Make: 4.2.1
Cmake: 3.16.3
Cudnn: 8.9
CUDA: 11.8

**Comment by kmpape** [comment]
Hi there, just tried building it with python3.8 again, but no success. This are the steps I followed:
```
mkdir v2_tensorrt_build && cd v2_tensorrt_build
git clone -b main https://github.com/nvidia/TensorRT TensorRT
cd TensorRT
git submodule update --init --recursive
sudo ./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.8 --cuda 11.8.0
cd TensorRT
export TRT_OSSPATH=`pwd`
mkdir -p build && cd build
cmake .. -DTRT_LIB_DIR=$TRT_LIBPATH -DTRT_OUT_DIR=`pwd`/out -DCUDA_VERSION=11.8 -DCUDNN_VERSION=8.9
make -j$(nproc)
export EXT_PATH=~/external
mkdir -p $EXT_PATH && cd $EXT_PATH
git clone https://github.com/pybind/pybind11.git
wget https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
tar xvf Python-3.9.1.tar.xz Python-3.9.1/
wget http://ftp.us.debian.org/debian/pool/main/p/python3.9/libpython3.9-dev_3.9.2-1_amd64.deb
ar x libpython3.9-dev_3.9.2-1_amd64.deb
tar -xvf data.tar.xz 
cp  usr/include/x86_64-linux-gnu/python3.9/pyconfig.h python3.9/include/
cd /workspace/TensorRT/python/
```
Add this point, I need to set TENSORRT_MODULE in CMakeLists.txt, otherwise `STREQUAL` throws an error. I am using cmake 3.14.4. I believe that this might be an issue? Without defining this, there is a if-else in the CMakeLists.txt. I continue with 
`PYTHON_MAJOR_VERSION=3 PYTHON_MINOR_VERSION=9 TARGET_ARCHITECTURE=x86_64 EXT_PATH=~/external ./build.sh`
and it throws the error about setup.py. Log attached.

Thanks for your help!

[complete_log.txt](https://github.com/NVIDIA/TensorRT/files/11441366/complete_log.txt)

**Comment by zerollzeng** [comment]
@pranavm-nvidia Can you help here? Thanks！

**Comment by ilyasher** [comment]
@kmpape Thank you for pointing out this issue. Can you please try again with the latest `release/8.6` branch? The steps should be the same up to the point where you run `build.sh`.

**Comment by kmpape** [comment]
@ilyasher Thank you very much for this, including for adding python3.9 to the guide! Works perfectly fine now. I think that in the guide, line `cp -r Python-3.9.16/Include/ $EXT_PATH/python3.9/include` is meant to be `cp -r Python-3.9.16/Include/* $EXT_PATH/python3.9/include`.
