### ISSUE TITLE
Can the best calib method only be selected through experiments for specific model?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#2957]
## Description

When I do ptq calib,  there are some calib methods, `max,  hist(percentile,  mse,  entropy)`,  Can the best calib method only should be selected through experiments for specific model ?

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#enable_int8_c Is it helpful?

**Comment by lix19937** [comment]
thanks, now closed.
