### ISSUE TITLE
There might be memory leak in instanceNormalizationPlugin 

### ISSUE THREAD

**Issue by NHZlX** [NVIDIA/TensorRT#296]
There are two places that can cause leaks

First, every enqueue calls cudamalloc without releasing

https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/instanceNormalizationPlugin/instanceNormalizationPlugin.cpp#L211

Second,  cudnn_handle will also be created every time

https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/plugin/instanceNormalizationPlugin/instanceNormalizationPlugin.cpp#L217

**Comment by rmccorm4** [comment]
May be related: https://devtalk.nvidia.com/default/topic/1068998/memory-leak-in-tensorrt-instancenormalization/?offset=2

CC @rajeevsrao

**Comment by nietras** [comment]
Not sure if this is the same, but I have observed a memory leak in OnnxRuntime using TensorRT as can be seen https://github.com/microsoft/onnxruntime/issues/2773
Although this model uses BatchNormalization and not InstanceNormalization.

**Comment by rmccorm4** [comment]
Fixed per #315
