### ISSUE TITLE
uff in 8.6.0.12

### ISSUE THREAD

**Issue by MacieJayDaaaaa** [NVIDIA/TensorRT#2969]
## Description

![image](https://github.com/NVIDIA/TensorRT/assets/102528658/569ff441-7df1-4d9c-9d22-7e8e23ab54ba)

After upgrading Tensorrt from 7.2.3 to 8.6.0, I need to make modifications to the UFF model project, such as replacing DimsCHW with Dims3, engine ->execute with engine ->executev2, and createNetwork with createNetworkV2 (explicit batch). But after the replacement, the code cannot run normally. I tried to find examples of UFF in the sample, but I found that they have already been deleted. How can I deploy the UFF model and complete inference in Tensorrt 8.6.0 version?

## Environment

**TensorRT Version**:8.6.0.12

**NVIDIA GPU**:4090

**NVIDIA Driver Version**:531.61

**CUDA Version**:12.1

**CUDNN Version**:8.9

Operating System:win10

**Comment by MacieJayDaaaaa** [comment]
![image](https://github.com/NVIDIA/TensorRT/assets/102528658/f5bdf334-7131-4555-9af4-e824a0107d67)

**Comment by zerollzeng** [comment]
From the log your model has implicit batch dims, please keep using execute() or enqueue(). 

FYI we are plan to deprecate uff support in the future, so we recommend moving to onnx-tensorrt.

**Comment by MacieJayDaaaaa** [comment]
ok,thank you

**Comment by MacieJayDaaaaa** [comment]
![image](https://github.com/NVIDIA/TensorRT/assets/102528658/08f034c1-7cbe-475b-b2de-12be16e4b3ff)
I have discovered another issue. After modification, my 4090 was able to run the program, but when I replaced it with 1080, it no longer ran. This is an error message

> precate uff support in the future, so we recommend moving to onnx-tensorrt.

**Comment by zerollzeng** [comment]
Did you recompile the plugin? Does the engine build pass?

**Comment by MacieJayDaaaaa** [comment]
I have found the reason. 4090 Compiled using compute_ 80,sm_ 80 instructions. I forgot to make changes when using 1080. When I modify to compute_ 52，sm_ 52，no error will occur.

**Comment by zerollzeng** [comment]
Good to know, can we close this issue? Thanks!

**Comment by MacieJayDaaaaa** [comment]
ok
