### ISSUE TITLE
Question about anonymous namespace in logging.h

### ISSUE THREAD

**Issue by keineahnung2345** [NVIDIA/TensorRT#297]
In `logging.h`, there is an anonymous namespace:

https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/samples/common/logging.h#L437-L501

But according to [Header files should not contain unnamed namespaces](https://rules.sonarsource.com/cpp/RSPEC-1000), it says that it's not encouraged to put unnamed namespace in a header file, because it may cause unexpected behavior. So what's the reason behind this design?

**Comment by rajeevsrao** [comment]
Its a nested namespace (under enclosing namespace "sample")
