### ISSUE TITLE
[Demo] Issue to export DeBERTa model with plugin

### ISSUE THREAD

**Issue by jplu** [NVIDIA/TensorRT#2970]
## Description

Impossible to create an ONNX DeBERTa model with the TRT plugin.

## Environment

**TensorRT Version**: 8.6.0.1

**NVIDIA GPU**: NVIDIA GeForce RTX 3080 Laptop

**NVIDIA Driver Version**: 531.79

**CUDA Version**: 12.1.66

**CUDNN Version**: 8.5.0.0

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 2.0.1

Baremetal or Container (if so, version): Container

## Steps To Reproduce
Here the following steps to reproduce the error from the  DeBERTa demo folder. First run a container:
```
docker run -it --gpus all nvcr.io/nvidia/tritonserver:23.04-py3-min bash
```
Next, install python and the needed packages:
```
apt update
apt install python3 python3-pip
pip install nvidia-pyindex
pip install optimum[onnxruntime-gpu] onnx-graphsurgeon
git clone https://github.com/NVIDIA/TensorRT
cd TensorRT/demo/DeBERTa
```
Next, export the model into ONNX:
```
python3 deberta_pytorch2onnx.py --filename deberta/model.onnx --variant microsoft/deberta-v3-base
```
Then, running the modify script with the plugin option:
```
python3 deberta_onnx_modify.py ./deberta/model.onnx --plugin
```
Gives the error below:
```
Fusing layer 0
Traceback (most recent call last):
  File "deberta_onnx_modify.py", line 192, in <module>
    graph = insert_disentangled_attention_all(graph)
  File "deberta_onnx_modify.py", line 115, in insert_disentangled_attention_all
    factor = left.o().inputs[1].inputs[0].attrs["value"].values.item()
KeyError: 'value'
```
Anything I did that is wrong or is it a bug?

Thanks in advance.

**Comment by zerollzeng** [comment]
@nvpohanh @rajeevsrao ^ ^

**Comment by nvpohanh** [comment]
Looks like the ONNX structure has changed and that broke the onnx graphsurgeon script. @zerollzeng Could you file an internal tracker for this and assign to @kevinch-nv 's team? Thanks

**Comment by zerollzeng** [comment]
Try to reproduce it as description but I met
```
root@a1fca041a1da:/TensorRT/demo/DeBERTa# python3 deberta_pytorch2onnx.py --filename deberta/model.onnx --variant microsoft/deberta-v3-base
Traceback (most recent call last):
  File "deberta_pytorch2onnx.py", line 134, in <module>
    export()
  File "deberta_pytorch2onnx.py", line 79, in export
    deberta_model = DebertaV2ForSequenceClassification.from_pretrained(model_variant)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2473, in from_pretrained
    raise EnvironmentError(
OSError: microsoft/deberta-v3-base does not appear to have a file named pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True` to load this model from those weights.
```

**Comment by jplu** [comment]
It works with the versions suggested in the requirements.txt and in downgrading numpy to 1.20.

It would be interesting to update to a more updated DeBERTa implementation once it is possible. I would avoid the fact to create a dedicated Python env just for this.
