### ISSUE TITLE
TensorRT QAT not support resize op in int8 ?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#2976]
## Description

How to solve `resize(upsample)` op in int8 by QAT(tools/pytorch-quantization) ?  Except use `ConvTranspose `      

## Environment

**TensorRT Version**:8.4

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
@lix19937 , could you elaborate more on your issue? no need to insert Q/DQ before resize, we should run resize in INT8 automatically for patterns like `resize -> Q/DQ -> conv`. Thanks!

**Comment by lix19937** [comment]
@ttyio   
![qat](https://github.com/NVIDIA/TensorRT/assets/38753233/d671416b-e4e4-41ec-bb71-61a883b6a949)
 
![qat](https://github.com/NVIDIA/TensorRT/assets/38753233/9f8c3082-4e50-4d00-8266-6d3d419f7888)

the first `resize` not quant with int8

**Comment by Monoclinic** [comment]
I have similar problem here.
It seems that the input tensor of resize layer (nn.upsample) will be automatically rescaled to fp16/fp32, which takes some time thus the network could be even slower than fp16.
In my experiment deconv (ConvTranspose) meets the same problem. Deconv itself will operate in int8, while bn and relu are fp32.

**Comment by lix19937** [comment]
@Monoclinic  @ttyio   If you move all scales of quant.onnx(the onnx described above), mark as `unquant.onnx`, then use  `trtexec  --best  --onnx=unquant.onnx` , will the first `resize` op will run in int8.

**Comment by Monoclinic** [comment]
@lix19937 Hello, thanks for your reply. May I ask how to remove the scale layer?

**Comment by ttyio** [comment]
I tried 8.6GA with a toy resize + q/dq + conv model, the resize is running in INT8 precision. Not sure what's corner case you hit here for your 1st resize. Are you using 8.6GA? could you share the onnx file for debug? @lix19937  thank you!

![image](https://github.com/NVIDIA/TensorRT/assets/365590/dc2ea1f0-6c94-49ab-9c14-6fdf1b1f3e76)

**Comment by lix19937** [comment]
@Monoclinic Hi,  You can remove Q-DQ nodes of quant.onnx by  `onnx_graphsurgeon` or onnx apis, as well as save scales.    
It just indicates that unquant onnx can be  it can better fusion by TRT PTQ, like `resize` will run in int8; but by QAT,  `resize` op run in fp32.

**Comment by lix19937** [comment]
@ttyio  My TRT version is v8410,  the **quant.onnx** in quant.zip , you can unzip it,    thanks  
[quant.zip](https://github.com/NVIDIA/TensorRT/files/11509632/quant.zip)

**Comment by lix19937** [comment]
Hi, @ttyio Thanks, it works in v8510 in Orin X 6060,   
![image](https://github.com/NVIDIA/TensorRT/assets/38753233/9436b0db-11d4-4a05-8449-6148c452887a)

**Comment by Monoclinic** [comment]
@lix19937 Hello, sorry for disturbing and reopening this issue.
I also use a Jetson Orin, I wonder how did you install / upgrade your TRT?
I tried to install TRT 8.6/8.5 on my Orin (my current version is 8.4.0.1), but the released version are based on x86_64 or ARM SBSA, which are not suitable for Jetson devices.
Is it necessary to reinstall the whole Jetson pack with a higher version of TRT?

// 或者看中文更方便一点。
我现在的TRT版本是8.4，早上尝试尝试装了8.6（x86）和8.5（arm SBSA），安装倒是没什么问题，demo也能跑，但是onnx转trt的时候会直接segmentation fault，原因搞不太清楚。
我想问下您是怎么用的8.5，是机器重新刷了一次jetson pack还是用deb从8.4升级上去的。

**Comment by lix19937** [comment]
@Monoclinic     `segmentation fault`  maybe due to version compatibility issues of cuda-X   

In Orin , TRT v8510 means  TRT v860, I just change another orin devkit which has been installed drive os 6060( map to TRT v8510).  

You can install `nv-driveos-repo-sdk-linux-6.0.6.0-32441545_6.0.6.0_amd64.deb` as  follow:    
```
1. Clean previous installation; 
2. Installing host components on p3710;
3. Flash DRIVE OS Linux;
4. Install CUDA/CUDNN/TENSORRT,  nv-tensorrt-repo-ubuntu2004-cuda11.4-trt8.5.10.4-d6l-target-ga-20221229_1-1_arm64.deb   

```

**Comment by Monoclinic** [comment]
@lix19937 Thanks for your kind advices. I will have a try.

**Comment by wenqibiao** [comment]
> 

Hi, What this sentences means: "In Orin , TRT v8510 means TRT v860"? And, where you get this information?
Thank You Very Much!

**Comment by wenqibiao** [comment]
@ttyio 
Hi, is that right? "In Orin , TRT v8510 means TRT v860"? I get DL model metric drop

**Comment by lix19937** [comment]
> @lix19937
> 
> Hi, What this sentences means: "In Orin , TRT v8510 means TRT v860"? And, where you get this information? Thank You Very Much!

You can ref `NVIDIA-TensorRT-8.5.10-API-Reference-for-DRIVE-OS.pdf`,  if you want to find correct version you can fine in `NvInferVersion.h`.  Btw, Drive os 6060 frequently update.

**Comment by lix19937** [comment]
> I try to use Ampere 4:2 sparse. But, I saw DL model metric large drop problem if I use tensorrt 8.5.3.1. In tensorrt 8.6.1.6, the problem disappeared.   

You can compare the build tactics between v8531 and v8616 on your model, check the fusion state and sparse layer chose.   @wenqibiao

**Comment by wenqibiao** [comment]
@lix19937 many thanks!
