### ISSUE TITLE
Is there an example of real-time target detection using python api？

### ISSUE THREAD

**Issue by aininot260** [NVIDIA/TensorRT#298]
I would like to use python API to inference videos but fail.Only C++ API can make it well.
This is my demo code from TensorRT's python samples:
https://github.com/NVIDIA/TensorRT/issues/288
Thanks!

**Comment by jkjung-avt** [comment]
@aininot260, I have shared this [jkjung-avt/tensorrt_demos](https://github.com/jkjung-avt/tensorrt_demos) repository which contains code doing TensorRT inferencing with python.  The demo scripts could take either file (video/image) or camera as input.

I'm working the 4th demo 'yolov3_onnx' and hopefully will add it into the repository in a couple of weeks.

**Comment by aininot260** [comment]
Very helpful! @jkjung-avt 
Let me try.

**Comment by rmccorm4** [comment]
Closing per @jkjung-avt's code. Will reopen if new issues arise
