### ISSUE TITLE
Python version of TensorRT is too low to load the engine exported by trtexec.

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#2983]
## Description

Hello, I used the trtexec tool from the latest tar package (version 8.6) and compiled it myself. I used the "--saveEngine" option to save an engine file. However, when I tried to load this file using TensorRT in Python, I received an error message saying that the version is not compatible. Can you please advise me on how to handle this issue? Thank you very much.

## Environment

**TensorRT Version**:8.6.1.6

**NVIDIA GPU**:3060

**NVIDIA Driver Version**:

**CUDA Version**:11.8

**CUDNN Version**:

Operating System:ubuntu20.04

Python Version (if applicable): 3.8

PyTorch Version (if applicable): 1.13

Baremetal or Container (if so, version):

## Steps To Reproduce

--saveEngine   and  use this script to read:

```python
import tensorrt as trt
import pycuda.autoinit
import pycuda.driver as cuda
import numpy as np

def load_engine(trt_engine_path):
    TRT_LOGGER = trt.Logger(trt.Logger.INFO)
    trt.init_libnvinfer_plugins(TRT_LOGGER, '')
    runtime = trt.Runtime(TRT_LOGGER)
    with open(trt_engine_path, 'rb') as f:
        buf = f.read()
        engine = runtime.deserialize_cuda_engine(buf)
    return engine

engine = load_engine("dynamic_esrgan.trt")

print(engine)
```
[05/18/2023-05:54:47] [TRT] [E] 6: The engine plan file is not compatible with this version of TensorRT, expecting library version 8.6.1.6 got 8.6.1.2, please rebuild.
![image](https://github.com/NVIDIA/TensorRT/assets/96160062/f441fd97-9fbd-4db3-bd6a-bd100129d678)

**Comment by zerollzeng** [comment]
Could you try uninstalling the tensorrt python package and reinstalling it with `pip3 install tensorrt==8.6.1`?

**Comment by sanbuphy** [comment]
> I think we didn't release 8.6.1.2, how do you install this version? can you attach (附加) the log of `ldd trtexec` and `nm -D libnvinfer.so.* | grep tensorrt_version` for the linked libnvinfer?

I have found a solution. I can simply install whl from the tar archive. Thank you

**Comment by Lzhang-hub** [comment]
@zerollzeng I got the same error, I install tensorrt according to :
https://github.com/NVIDIA/TensorRT/tree/release/8.6/demo/Diffusion
![image](https://github.com/NVIDIA/TensorRT/assets/57925599/ca096036-8c43-4954-9942-2ef1ec74b8ca)
then then convert onnx model to trt model ,and run triton server with 23.05-py3
