### ISSUE TITLE
How to set the inner layer`s format ?   

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#2985]
## Description

It seems trtexec only support   `--inputIOFormats=spec     --outputIOFormats=spec    --layerPrecisions=spec   --layerOutputTypes=spec ` , but no   `--layerIOFormats` option.   

I think TRT not allow developer set `layer io format`,  how to set the inner layer`s format except user custom plugin ?   

## Environment

**TensorRT Version**: TensorRT v8510    

**NVIDIA GPU**: Orin X  

**NVIDIA Driver Version**:drive agx orin, p3710, 530.00

**CUDA Version**:11.4

**CUDNN Version**:8.6.0

**Comment by zerollzeng** [comment]
We allow user to select the inner format, but it may cause performance degradation. see [setPrecision](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_layer.html#a1db7e4d17afc29950145514fd7744f74), [setOutputType](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_layer.html#ad0b6623245e60aaa8235e5100c782a24) and [setFlag](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#ac9821504ae7a11769e48b0e62761837e)

**Comment by zerollzeng** [comment]
Anything you can do with trtexec means you can do with TRT's API, it's open-source.

**Comment by lix19937** [comment]
@zerollzeng   Thanks for your reply,   but it seems there is no api to set layer`s in or out format like `hwc8` or `c/32hw32`

**Comment by zerollzeng** [comment]
You can.
see https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#ac3e115b1a2b1e578e8221ef99d27cd45
and
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_tensor.html#a177fa58116c06c0b49f38f023c76e60c
