### ISSUE TITLE
SM61: no instance of overloaded function "atomicAdd" matches the argument list

### ISSUE THREAD

**Issue by Tumb1eweed** [NVIDIA/TensorRT#2992]
TensorRT version: 8.2.5.1
The error log:
```
/data/.data/tensorrt/8.2.5/_/_/source/plugin/voxelPoolingPlugin/voxel_pooling_forward_cuda.cu(45): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (half *, const half)
          detected during instantiation of "void nvinfer1::plugin::voxel_pooling_forward_kernel(int, int, int, int, int, int, const int *, const T *, T *, int *) [with T=half]"
(81): here
```
The question is，when I compile for sm75, sm 80, sm86, it's fine. But after i add sm61 then get this error. I check the cudatoolkit document, it's said:
![image](https://github.com/NVIDIA/TensorRT/assets/27768261/17f68ba8-caca-44b1-82fb-3e07e2449de2)

But I add sm 61 (for GTX 1060), obviously larger than compute capability 6.0. I am confused right now.

**Comment by zerollzeng** [comment]
> argument types are: (half *, const half)

Which cuda version you are using? This is not our official plugin right? I would suggest to ask question in our CUDA developer forum.

**Comment by Tumb1eweed** [comment]
> > argument types are: (half *, const half)
> 
> Which cuda version you are using? This is not our official plugin right? I would suggest to ask question in our CUDA developer forum.

thanks for answering, i am using cudatoolkit 12.1.1 to build this.

**Comment by zerollzeng** [comment]
I would check the atomicAdd in the corresponding header file and check whether it supports (half *, const half).

**Comment by ttyio** [comment]
closing since this is not tensorrt specific issue, we can move to CUDA developer forum. Thanks!
