### ISSUE TITLE
NO KERNEL? NO FUSED OPTIMIZATION?

### ISSUE THREAD

**Issue by lcxywfe** [NVIDIA/TensorRT#3]

**Comment by BowieHsu** [comment]
"Included are the sources for TensorRT plugins and parsers (Caffe and ONNX)", yep, you are right, no kernel, no fused optimization.

**Comment by lcxywfe** [comment]
> "Included are the sources for TensorRT plugins and parsers (Caffe and ONNX)", yep, you are right, no kernel, no fused optimization.

T_T
