### ISSUE TITLE
Does TensorRT's python interface support SSD layers?

### ISSUE THREAD

**Issue by Knownx** [NVIDIA/TensorRT#30]
Hi experts,

I'm a beginner, and I want to know if TensorRT's **python interface** can parse SSD layers?

Thanks a lot.

**Comment by zeruniverse** [comment]
If you use TF version SSD (https://github.com/tensorflow/models/tree/master/research/object_detection), the model should directly be supported and a **python sample inference script** is provided in 5.1.2.2 RC version here (download the tar and sample should be in `/samples/python/uff_ssd`): https://developer.nvidia.com/compute/machine-learning/tensorrt/5.1/rc/tars/TensorRT-5.1.2.2.Ubuntu-18.04.1.x86_64-gnu.cuda-10.1.cudnn7.5.tar.gz

**Comment by Knownx** [comment]
Got it. thanks @zeruniverse for the detail.

**Comment by Ram-Godavarthi** [comment]
Hello,
Have you successfully converted Tensorflow SSD  model to uff and then tensorRT?

What versions have yo used?
Tensorflow version = 
Object detection api version =
Tensorlfow version on jetson nano = 

Could you please let me know these. 
Thank you
