### ISSUE TITLE
Custom ops usage

### ISSUE THREAD

**Issue by DaraOrange** [NVIDIA/TensorRT#3005]
Hi! I have built static plugins with custom ops as .so library. How to make them visible to TensorRT in C++ API?

**Comment by DaraOrange** [comment]
But how to load plugin from already built .so file? I don't see something about it in this tutorial

**Comment by zerollzeng** [comment]
Check https://github.com/NVIDIA/TensorRT/blob/b55c4710ce01f076c26710a48879fcb2661be4a9/samples/common/common.h#L893

this is how `trtexec --plugins=xxx.so` work

**Comment by DaraOrange** [comment]
It works, thank you
