### ISSUE TITLE
The diff between nv whl with nv github 

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#3012]
## Description

I found there's a slight difference between the source of  https://developer.download.nvidia.cn/compute/redist/pytorch-quantization/pytorch_quantization-2.1.2-cp38-cp38-linux_x86_64.whl  (pip install pytorch_quantization-2.1.2-cp38-cp38-linux_x86_64.whl , and then get source from python envs)  

with  the source of  https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/pytorch-quantization/pytorch_quantization  
(from https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/pytorch-quantization/VERSION  is v2.1.2)

**both version are 2.1.2**   

the diff as follow:   
![whl-github](https://github.com/NVIDIA/TensorRT/assets/38753233/78065b73-190d-488f-b38f-f1a19c12cf1a)

I try install whl, and get better result than nv github source version (My onnx has `ConvTranspose`). There are different treatments for `ConvTranspose`,  Why nv whl is not match nv github release ?  

## Environment

**TensorRT Version**:8.6

**NVIDIA GPU**:3090

**Comment by zerollzeng** [comment]
Looks like a patch fix, see https://github.com/NVIDIA/TensorRT/commit/e34b33ef748d8a24fa6a0716225d09b23c9880c3

@ttyio for viz.

**Comment by lix19937** [comment]
@ttyio  Thanks.  
But when I try quant **axis 1** for deconv and then do qat (calib + fintune)     
```
     QUANT_DESC_8BIT_CONVTRANSPOSE2D_WEIGHT_PER_CHANNEL = QuantDescriptor(num_bits=8, axis=(1))
```
it gets better result than**axis 0** for deconv      
```
     QUANT_DESC_8BIT_CONVTRANSPOSE2D_WEIGHT_PER_CHANNEL = QuantDescriptor(num_bits=8, axis=(0))
```

**Comment by ttyio** [comment]
We revert back to axis 0 in latest code https://github.com/NVIDIA/TensorRT/blob/release/10.0/tools/pytorch-quantization/pytorch_quantization/tensor_quant.py#L246

I will close this, thanks @lix19937 !
