### ISSUE TITLE
Detectron2 documentation missing hardware information

### ISSUE THREAD

**Issue by fumin** [NVIDIA/TensorRT#3013]
The [documentation ](https://github.com/NVIDIA/TensorRT/tree/release/8.6/samples/python/detectron2)on detectron2 presents the following latencies in the table below,
but it does not explain on what hardware these figures are recorded.

For example, for int8 inference, the speed is 9.90ms, but is this on a V100, RTX 3060, or a Jetson Orin?
Please be more specific on how this benchmark is done, especially on the hardware side.
This will make it easier for people like me to determine which GPU card to buy that will suit our needs.

<html>
<body>

Precision | Latency | bbox COCO mAP | segm COCO mAP
-- | -- | -- | --
fp32 | 34.48 ms | 0.402 | 0.368
fp16 | 17.26 ms | 0.402 | 0.368
int8 | 9.90 ms | 0.398 | 0.366

</body>
</html>

**Comment by zerollzeng** [comment]
@nvpohanh Could you please help? Thanks!

**Comment by nvpohanh** [comment]
@zerollzeng Let's file an internal tracker for this. Thanks

**Comment by fumin** [comment]
@zerollzeng @nvpohanh thanks for bringing this back to Nvidia, looking forward to your information.

**Comment by zerollzeng** [comment]
File internal bug 4138079 to track this. Thanks!

**Comment by zerollzeng** [comment]
@fumin From what we know the perf number mainly demonstrated the FP16 and INT8 speed-up and the engineer who do the test doesn't remember what device is used at that time, you can test on your own if you are interested in the exact number in your device. Sorry for the confusion.

I might be able to re-test the perf when I have spare time but this would be in low-priority due to other tasks now.

**Comment by fumin** [comment]
@zerollzeng Thanks for your info.
I am able to get 12 fps for fp32 on a RTX 3060 12G.
I don't have numbers for fp16 and int8 yet.
However, from the specs, it seems that for the 3060, fp16:fp32 is 1:1, so maybe there might not be much speedup?
Anyways, these numbers are already good for us, but still if you guys happen to retest the perf with more hardware info that would be fantastic.

**Comment by ttyio** [comment]
closing since this number is already good, thanks all!

**Comment by zerollzeng** [comment]
Fix in https://github.com/NVIDIA/TensorRT/pull/3213
