### ISSUE TITLE
Support UINT8 input / output and casting from UINT8 to FP16 and back

### ISSUE THREAD

**Issue by MatthieuTPHR** [NVIDIA/TensorRT#3026]
Hello, 

Thanks for the great work, 

I am currently having trouble serving TensorRT models that take very large image inputs and return very large image outputs in Triton Inference Server  as I need to send them as Float16. 

Ideally I would like to send them as UINT8 as that is what my image decoder outputs. 

The only way around I have find is to have an INT8 input / output and do the conversion to Float16 inside the model.
To account for the UINT8 -> INT8 signed bit I need to run: 

```
# Torch
image = image.to(torch.float16)
image[image <= -1] = image[image <= -1] + 255 + 1
```
and for the output:
```
result[result >= 128] = result[result>=128] - (255+1)
result = result.to(torch.int8)
```

But this is not compatible with TensorRT due to an error in ScatterND. 

We've found a way around this by implementing a plugin in CUDA that does these transformations for us, however we think it would make sense supporting UINT8 inputs and outputs as that is what image decoders outputs usually. 
It would also make sense supporting casting UINT8 to FP16 and FP16 to UINT8. 

On a side note, it would be great to be able to use int8 only for inputs / outputs without expanding the set of available tactics to int8 based tactics.

**Comment by zerollzeng** [comment]
I think we support UINT8 casting since TRT 8.5, see https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29 and https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_cast_layer.html#aa0e3a2bc657c7bd0c73f586d6dca5da2

**Comment by david-PHR** [comment]
The `trtexec` program doesn't indicate any UINT8 datatype. 

I've tried with `--inputIOFormats=uint8:chw                 --outputIOFormats=uint8:chw ` but it returns this issue : `[05/31/2023-15:35:54] [E] Invalid DataType uint8`

**Comment by MatthieuTPHR** [comment]
I think it's just that Nvidia didn't update trtexec after updating tensorrt. Even the documentation of trtexec does not include uint8 among the valid input / output types.

**Comment by MatthieuTPHR** [comment]
@zerollzeng could we make sure the trtexec CLI is updated and conforms to the supported types in TensorRT ? 
This is really not the best developer experience to be honest.

**Comment by zerollzeng** [comment]
Let's me check this internally and see if we can improve this :-)

**Comment by MatthieuTPHR** [comment]
Maybe we should label this issue as a bug ? The CLI is clearly not behaving as it should, right ?

**Comment by zerollzeng** [comment]
Filed internal bug 4146128 to support uint8 in trtexec.

To WAR this you can try polygraphy, we should support it in polygraphy tools.

**Comment by MatthieuTPHR** [comment]
Thank you, to be more precise, you can use uint8 with trtexec if the onnx graph as uint8 inputs and or outputs but adding the following arguments in trtexec: `--inputIOFormats=uint8:chw                 --outputIOFormats=uint8:chw` triggers the following error: `[E] Invalid DataType uint8`.

**Comment by zerollzeng** [comment]
we added support for `--inputIOFormats=uint8:chw                 --outputIOFormats=uint8:chw`, it will be shipped in the next release.

I'm closing this now, feel free to reopen if you have any further questions.

**Comment by onurtore** [comment]
Is this shipped yet?

**Comment by zerollzeng** [comment]
Yes, it should be in the latest 8.6 or 9.0 release.

**Comment by onurtore** [comment]
@zerollzeng  Thanks

**Comment by hyperf0cus** [comment]
How to do this in Python API?

**Comment by zerollzeng** [comment]
Check https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/LayerBase.html#itensor

**Comment by zerollzeng** [comment]
You can also take the polygraphy source code as reference as it's open-source.

**Comment by jax11235** [comment]
> I think we support UINT8 casting since TRT 8.5, see https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29 and https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_cast_layer.html#aa0e3a2bc657c7bd0c73f586d6dca5da2

Good job to the developers!
