### ISSUE TITLE
parse failure of TensorRT 8.4.3 when parsing the Equal operator with bool inputs

### ISSUE THREAD

**Issue by YouSenRong** [NVIDIA/TensorRT#3037]
## Description

I tried to run model on TensorRT 8.4.3, but it fails with the error bellow:
![image](https://github.com/NVIDIA/TensorRT/assets/21186538/0a0670ec-bc05-4865-8a29-4094386eb113)
It seems that the Equal op doesn't support bool inputs.

The subgraph is as bellow:
![image](https://github.com/NVIDIA/TensorRT/assets/21186538/8c48c1f4-ecbb-419d-91db-28316eac8ea3)

Does the Equal operator of TensorRT support bool inputs? How can I fixed this problem except inserting a cast(to INT32) op?

## Environment

**TensorRT Version**:8.4.3

**NVIDIA GPU**:T4

**NVIDIA Driver Version**:510.108.03

**CUDA Version**:11.6

**CUDNN Version**:

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
See https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#aacd7b0a3338921b2a0c87570295beef4 and https://github.com/onnx/onnx-tensorrt/blob/6ba67d3428e05f690145373ca87fb8d32f98df45/builtin_op_importers.cpp#L1424

The parser is open-source.

**Comment by YouSenRong** [comment]
@zerollzeng Thanks a lot!

**Comment by zerollzeng** [comment]
I assume you've solved the problem so I'm closing this now, feel free to reopen it if you have any further questions :-)
