### ISSUE TITLE
TensorRT QAT model is slower than PTQ  model !!!

### ISSUE THREAD

**Issue by tp111222** [NVIDIA/TensorRT#3038]
## Description
 Yolov8m TensorRT QAT model is slower than PTQ  model

## Environment

**TensorRT Version**:
8.4.1.5
**NVIDIA GPU**:
RTX2080
**NVIDIA Driver Version**:

**CUDA Version**:
CUDA11.1
**CUDNN Version**:

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

PTQ inter time:
![69d1c9f9d5548dfe1462bfb3cc30ba5](https://github.com/NVIDIA/TensorRT/assets/12984410/44783959-6cb5-4254-91de-6840b6c7e405)

QAT infer time:
![70bd9864e94965abedf1f716116ef2f](https://github.com/NVIDIA/TensorRT/assets/12984410/e6181236-e89c-45c2-bc92-038816e3ef50)

**Comment by tp111222** [comment]
this is QAT onnx model:

**Comment by lix19937** [comment]
It is quite common that TensorRT QAT model is slower than PTQ model .  Maybe Q-DQ not set right, so fusion bad.

**Comment by zerollzeng** [comment]
Yes.

**Comment by tp111222** [comment]
How to set Q-DQ correctly?

**Comment by tp111222** [comment]
this is yolov8m qunat model： 

https://pan.baidu.com/s/1MC7BYxs71wzLdEqXBHmF-Q?pwd=ysha

**Comment by tp111222** [comment]
How to set Q-DQ correctly?

**Comment by tp111222** [comment]
this is yolov8m qunat model：

https://pan.baidu.com/s/1MC7BYxs71wzLdEqXBHmF-Q?pwd=ysha

How to set Q-DQ correctly?

**Comment by tp111222** [comment]
@zerollzeng this is generate svg file,Can you give u
![yolov8m_qat2_layer json](https://github.com/NVIDIA/TensorRT/assets/12984410/5ba6becb-6b1a-4837-a01b-6f1e877de513)
s some guidance on which nodes to optimize

**Comment by tp111222** [comment]
@zerollzeng this is yolov8 quant svg file
![yolov8m_qat2_layer json](https://github.com/NVIDIA/TensorRT/assets/12984410/725075b2-972e-4562-a903-287964d14ad9)
 Can you give us some guidance on which nodes to optimize

**Comment by tp111222** [comment]
Can you give me some guidance on which nodes to optimize?

**Comment by zerollzeng** [comment]
Well it's hard to analyze through the image...

A way to check with the log:
Build a PTQ engine(e.g. with trtexec --int8 --fp16) and compare the final engine(in the verbose log) with the QAT engine. check the different between them, e.g. layer precision(some layer may still running in FP16 in the QAT model) and layer fusions(redundant Q/DQ may break the layer fusion)

**Comment by tp111222** [comment]
@zerollzeng What should I do after I find out that PTQ engine and QAT engine are different?

**Comment by tp111222** [comment]
@zerollzeng 还是用中文交流吧，我的意思是，对比了PTQ engine 和 QAT engine 不同后，接下来该怎样去优化QAT engine ，使其到达PTQ engine的性能

**Comment by zerollzeng** [comment]
最终的目标是：让你的qat model build出来的engine结构和ptq的一样（有可能会导致精度下降，需要自己权衡），奔着这个目标去调整优化Q/DQ节点（pytorch-quantization）的摆放

**Comment by yuanjiechen** [comment]
Based on my result, I guess PTQ has full int8 but less performence on yolo.
QAT has many reformat layer consume too many times (INT8-FP32/FP16), you can use engine profiler to get similar result.
Replace SiLU to ReLU and re-train the model, then add Q/DQ and finetune the model again.
The model has larger chance to INT8, otherwise, use full fp16 will get best inference time.

**Comment by WeixiangXu** [comment]
借个楼. Do TRT have any suggestions for the quantization deployment of **transformer** architecture with int8? (considering both speed and precision, with PTQ by calibration or pytorch-QAT or anything else?) @zerollzeng  Thanks!

**Comment by zerollzeng** [comment]
There are some progress and effort about this, I'll let @ttyio to answer the question.

**Comment by WeixiangXu** [comment]
thanks! where will it be released? @ttyio

**Comment by ttyio** [comment]
Now the TensorRT-LLM is released in https://github.com/NVIDIA/TensorRT-LLM
closing and thanks all!

**Comment by J-xinyu** [comment]
> @zerollzeng this is yolov8 quant svg file ![yolov8m_qat2_layer json](https://private-user-images.githubusercontent.com/12984410/244301795-725075b2-972e-4562-a903-287964d14ad9.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTU0NTEsIm5iZiI6MTcxMjg5NTE1MSwicGF0aCI6Ii8xMjk4NDQxMC8yNDQzMDE3OTUtNzI1MDc1YjItOTcyZS00NTYyLWE5MDMtMjg3OTY0ZDE0YWQ5LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA0MTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmM2NWE3NmVlN2FiYTRhY2JlZTIxMmNjY2JmMTc1ZDVjMWVkNmVlNWZlMDk1ZDBmYzI2ZWU1NjRjOTg5NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H_dHSWR-cQBxCd9Irkc2fi8JspZ44zsQi94VT3jx3tw) Can you give us some guidance on which nodes to optimize

Hey bro, how did you get this svg image?
