### ISSUE TITLE
Support QAT for the plugin layer ?

### ISSUE THREAD

**Issue by OYCN** [NVIDIA/TensorRT#3055]
## Description

I have a graph likes below (unit test):

input -> Q -> DQ -> Plugin -> Q -> DQ -> output

The plugin can be a noop in enqueue

Actually there are many inputs in the plugin, and only int8 can be used in the `supportsFormatCombination` function. When I start build then engine, the error was raised:

```
WARNING: IPluginV2IOExt/IPluginV2DynamicExt ignores some format combinations because combination limit of 100 was reached
ERROR: 2: Assertion !n->candidateRequirements.empty() failed. All of the candidates were removed, which points to the node being incorrectly marked as an int8 node.
ERROR: 2: [optimizer.cpp::filterQDQFormats::4670] Error Code 2: Internal Error (Assertion !n->candidateRequirements.empty() failed. All of the candidates were removed, which points to the node being incorrectly marked as an int8 node.)
```

> combination limit of 100 was reached

It seems like there are many candidates?

## Environment

**TensorRT Version**: 8.5.3.1 & 8.6.0.12

**NVIDIA GPU**: 3090

**NVIDIA Driver Version**: 520.61.05

**CUDA Version**: 11-2

**CUDNN Version**: 8-2-1

**Comment by zerollzeng** [comment]
Try input -> Q -> plugin -> DQ -> output.

**Comment by OYCN** [comment]
@zerollzeng It worked ! Thanks a million !

**Comment by zerollzeng** [comment]
Glad to help :-)
