### ISSUE TITLE
Unable to open library: libnvinfer_plugin.so.8 due to libcublas.so.11

### ISSUE THREAD

**Issue by yuvraj108c** [NVIDIA/TensorRT#3061]
Getting this error on ubuntu 20:

`
Unable to open library: libnvinfer_plugin.so.8 due to libcublas.so.11: cannot open shared object file: No such file or directory
`

**Comment by zerollzeng** [comment]
Your CUDA installation is not complete. try reinstalling it. Or you can use our official docker image.
