### ISSUE TITLE
ONNX GraphSurgeon fails to import correctly using external data

### ISSUE THREAD

**Issue by FL33TW00D** [NVIDIA/TensorRT#3065]
## Description

Firstly, thank you for ONNX GraphSurgeon, it is an excellent tool.

It seems that ONNX GraphSurgeon is not currently able to handle models which have been imported using external data.

I have created a MRE here: https://github.com/FL33TW00D/ogs_repro

The reproduction uses an example from the ONNX Runtime repository to export the T5 large model using external data, this is then loaded using GraphSurgeon and then reexported.

This results in:

```shell
Fatal Python error: Segmentation fault

Current thread 0x00000001f8111b40 (most recent call first):
line 130 in CopyFrom
line 288 in make_model
line 178 in export_onnx
line 14 in export_external
line 26 in <module>
```

## Environment

Operating System: MacOS

Python Version (if applicable): 3.10.6

PyTorch Version (if applicable): 2.0.1

ONNX Version: 1.14.0

ONNX GraphSurgeon Version: 0.3.27

**Comment by zerollzeng** [comment]
@pranavm-nvidia ^ ^

**Comment by skirsten** [comment]
I just ran into this problem as well.
What is strange is that downgrading GraphSurgeon to `0.3.26` (where I believe it worked before) did not fix the problem. So I guess it has something to do with the other libraries like onnx.

**Comment by skirsten** [comment]
> Can you try downgrading `onnx` to 1.13 or 1.12? IIRC there's a bug in 1.14 causing this.

Yes, downgrading to `onnx==1.13.1` and `onnxruntime==1.14.1` fixed it for me. Thanks

**Comment by zerollzeng** [comment]
I'm closing this as it's been fixed. Thanks!

Feel free to reopen it if you have any further questions.
