### ISSUE TITLE
What is the strategy for accessing memory

### ISSUE THREAD

**Issue by FrankyTang** [NVIDIA/TensorRT#3066]
## Description

I try to optimize split node(split the input tensor to output tensors with specify axis)
Eg. a tensor [1,3,19,30,29], split axis= -1, but the memory discontinuity
so I transpose the tensor to [1,29,3,19,30], and than split axis = 1, in this case the memory [3,19,30] is continuity.
But, this two split node have the same latency.
I'm confused, what is the strategy for accessing memory?  thanks!!!

![image](https://github.com/NVIDIA/TensorRT/assets/32587916/b2b646e5-28ba-4d3f-bff4-a71d8e1c4e2f)
![image](https://github.com/NVIDIA/TensorRT/assets/32587916/c81c0c49-4373-42a5-b8a5-161f3ad87f84)

**Comment by zerollzeng** [comment]
> But, this two split node have the same latency.

Well then I think you don't need to worry about this, TRT graph optimizer already handle it, is there any other issue you see?

**Comment by FrankyTang** [comment]
no problem, thanks.
