### ISSUE TITLE
Any way to get the tensorrt version & platform by the single engine file ?

### ISSUE THREAD

**Issue by OYCN** [NVIDIA/TensorRT#3073]
greetings!

In our project, we will keep different tensorrt versions on different platforms.

TensorRT will raise an error with "Serialize Version" when I deserialize an engine file with the wrong tensorrt version. Also I found the "Serialize Version" is in the 9th byte in the engine file. By the "Serialize Version", we can't identify the verbose version in the corresponding tensorrt version.

Is there some way we can get the engine file version or platform and don't need to deserialize ?

**Comment by nvpohanh** [comment]
We currently does not have an API to do so. Would that be useful? If it would, we can consider adding an API to that

**Comment by OYCN** [comment]
@zerollzeng @nvpohanh Thanks for your reply. :smile: 

Does the "TRT version encoded in the first few bytes" means "Serialized Engine Version" ? Is there a map between them and the TensorRT version ? :thinking: 

After testing, I found a map but not sure if it's robust. And it seems like just a minor level verison.

```
{
"8.5.3.1": 232,
"8.4.3.1": 213,
"8.2.1.8": 205
}
```

> We currently do not have an API to do so. Would that be useful? If it would, we can consider adding an API for that

In my case,  my original goal was to read the engine file in binary and judge the version without the trt library. But he doesn't seem to be able to implement patch level version checks (using "Serialized Engine Version"). :crying_cat_face:

**Comment by oxana-nvidia** [comment]
In the next version we've added an option to trtexec to get creation version without deserializing the engine. It works for engines created with TRT 8.6 and forward. 

simplified related code: 

```
    auto const blob = static_cast<uint8_t*>(env.engine.getBlob().data);
    sample::gLogInfo << "Plan was created with TensorRT version " << static_cast<int32_t>(blob[24])
        << "." << static_cast<int32_t>(blob[25]) << "." << static_cast<int32_t>(blob[26])
        << "." << static_cast<int32_t>(blob[27]) << std::endl;
```

**Comment by OYCN** [comment]
@oxana-nvidia  Thank you for providing a solution. I'm looking forward to its implementation ~

I will close this issue ~

**Comment by onurtore** [comment]
| IIRC we encode the TRT version into the engine file in the fiirst few bytes, does read it work for you? cc @nvpohanh

@zerollzeng do you know which type of casting you guys like to use while reading first few bytes

**Comment by zerollzeng** [comment]
https://github.com/NVIDIA/TensorRT/issues/3073#issuecomment-1599934548 Have you try this?

**Comment by onurtore** [comment]
No that requires minimum of 8.6, so I came up with my own.

**Comment by zerollzeng** [comment]
Okay, this is subject to change until we provide the API.

**Comment by jpfleischer** [comment]
> In the next version we've added an option to trtexec to get creation version without deserializing the engine. It works for engines created with TRT 8.6 and forward.
> 
> simplified related code:
> 
> ```
>     auto const blob = static_cast<uint8_t*>(env.engine.getBlob().data);
>     sample::gLogInfo << "Plan was created with TensorRT version " << static_cast<int32_t>(blob[24])
>         << "." << static_cast<int32_t>(blob[25]) << "." << static_cast<int32_t>(blob[26])
>         << "." << static_cast<int32_t>(blob[27]) << std::endl;
> ```

please give the exact trtexec command to find the version of a trt file

**Comment by OYCN** [comment]
> please give the exact trtexec command to find the version of a trt file

Hi @jpfleischer 

It just reads the engine file generated by TRT as binary after version 8.6. You can use these bash commands to print the specified bytes:

```
dd if=/path/to/trt_file bs=1 skip=23 count=4 2>/dev/null | od -An -t u1 -v
```

**Comment by oxana-nvidia** [comment]
the trtexec option is called `--getPlanVersionOnly`.  It was added to trtexec since in TRT 9.0 version. So the full command will be something like:
```
trtexec --loadEngine=engine.trt --getPlanVersionOnly
```

please use trtexec help to see more information.

**Comment by fr0zenrain** [comment]
Nvida's hardware is really awesome, and its software design is a piece of shit, with no regard for compatibility.

**Comment by onurtore** [comment]
> Nvida's hardware is really awesome, and its software design is a piece of shit, with no regard for compatibility.

But don't forget buying their stocks :D At least they might pay your next meal :D

**Comment by zerollzeng** [comment]
Sorry about the inconvenience and we are trying to improve it, but unfortunately it's hard to maintain a "good compatibility" due to the fast changing world :-(
