### ISSUE TITLE
tensorrt sdist install fails

### ISSUE THREAD

**Issue by ddelange** [NVIDIA/TensorRT#3078]
Hi 👋

tensorrt sdist install [runs `pip install` inside `pip install`](https://github.com/NVIDIA/TensorRT/blob/v8.6.1/python/packaging/frontend_sdist/setup.py#L32), which is undefined/unsupported behaviour from the PyPA side (just like running multiple concurrent pip commands).

On my local machine (and probably on many other machines), it happens to work, but it is not robust and does not comply with the PyPA index url mechanic design.

The proper way to employ external index urls (see e.g. pytorch), is by having the user set the `--extra-index-url` flag on the top level installation command, or exporting `PIP_EXTRA_INDEX_URL` before running top level installation command.

Here is an example where this hack fails in the wild:

- tensorrt install [errors](https://github.com/autogluon/autogluon/actions/runs/5309652350/jobs/9610616186?pr=3190#step:4:1006) with `/home/ci/opt/venv/bin/python3: No module named pip`
  - command `['/home/ci/opt/venv/bin/python3', '-m', 'pip', 'install', 'tensorrt_libs==8.6.1', '--index-url', 'https://pypi.nvidia.com/']`
- yet autogluon ci [runs](https://github.com/autogluon/autogluon/actions/runs/5309652350/jobs/9610616186?pr=3190#step:4:154) `python3 -m pip install --upgrade pip`
  - which upgrades `/home/ci/opt/venv/lib/python3.8/site-packages`
- the venv in question is set up and activated properly, as can be seen from the environment variables in the logs linked: `VIRTUAL_ENV` env var is set and `VIRTUAL_ENV/bin` is prepended to the `PATH` env var.

full error log for future reference: [logs.txt](https://github.com/NVIDIA/TensorRT/files/11864018/logs.txt)

_Originally posted by @ddelange in https://github.com/NVIDIA/TensorRT/issues/2933#issuecomment-1596780432_

**Comment by ddelange** [comment]
Hi @zeroepoch :wave:

I've opened #3080 to switch to the best practice implementation (similar to how torchvision 0.15.2 pins `torch==2.0.1` and allows the end user to pick the cuda/cpu flavour using `--extra-index-url`).

How does that look to you?

**Comment by zerollzeng** [comment]
@pranavm-nvidia ^ ^

**Comment by ddelange** [comment]
closed in #3080
