### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr.

### ISSUE THREAD

**Issue by chegnyanjun** [NVIDIA/TensorRT#308]
Hi,i am  use tensorrt7.0.0.11 and cuda10.1 ubuntu16.04 pytorch1.3.1 python3.6.But i faced above problem when i was using it.It indices the problem from this line:

```python
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as 
 network, trt.OnnxParser(network,TRT_LOGGER) as parser:  #<--- this line got above problem.
```
The code can be use in the tensorrt6.0.1.5,but got problem in the tensorrt7.0.0.11.

What's problem of my code?

**Comment by rmccorm4** [comment]
Hi @chegnyanjun,

I don't think there's anything wrong with that code snippet, I use it all the time. However, I notice you're using CUDA 10.1, and I believe TRT7 only supports 9.0, 10.0, and 10.2 per the support matrix: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html

Please try again after changing to a supported CUDA version or use a container if you don't want to change your host install

**Comment by chegnyanjun** [comment]
＠rmccorm4,thanks for your help,i will try it.

**Comment by chegnyanjun** [comment]
＠rmccorm4,Hi,i have tried your suggestion, and i change my cuda10.1 to cuda10.0, but it still has such problem,the whole problem is:
[TensorRT] ERROR: CUDA initialization failure with error 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
master/scripts/Pytorch2ONNX.py", line 53, in ONNX2Engine
    with trt.Builder(TRT_LOGGER) as builder:
TypeError: pybind11::init(): factory function returned nullptr
Can you help me? tkx.

**Comment by taomiao** [comment]
met the same problem. @rmccorm4 
Titan xp
nvidia-driver 418.56 
cuda 10.0

**Comment by ligonzheng** [comment]
met the same problem.
cuda 10.2 
tensorrt 7.0.0.11

**Comment by hyperfraise** [comment]
Same problem and same version as @ligonzheng . 
```
[TensorRT] ERROR: CUDA initialization failure with error 1. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
[2020-02-04 11:54:00,016] PID : 5850 : CRITICAL : 
Traceback (most recent call last):
  File "file.py", line 278, in get_engine
    with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
 Uncaught exception: pybind11::init(): factory function returned nullptr
```

**Comment by rmccorm4** [comment]
@chegnyanjun @taomiao @ligonzheng @hyperfraise 

You all got this error:

> [TensorRT] ERROR: CUDA initialization failure with error 35. Please check your CUDA installation: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

1. Did you verify that your CUDA install is good as the error suggests? 
    * Can you run `nvidia-smi` successfully?
    * Can you run any sample GPU apps in PyTorch/TensorFlow?

2. Does your TensorRT installation actually match your current CUDA installation? For example @chegnyanjun you mention that you downgraded from CUDA 10.1 to CUDA 10.0, but did you also switch to the TensorRT CUDA 10.0 release as well? Or did you install the TensorRT CUDA 10.2 release?

Example: 
* CUDA 10.0 .tar.gz package for Ubuntu: https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/7.0/7.0.0.11/tars/TensorRT-7.0.0.11.Ubuntu-18.04.x86_64-gnu.cuda-10.0.cudnn7.6.tar.gz 

vs.

* CUDA 10.2 .tar.gz package for Ubuntu: https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/7.0/7.0.0.11/tars/TensorRT-7.0.0.11.Ubuntu-18.04.x86_64-gnu.cuda-10.2.cudnn7.6.tar.gz

**Comment by rawar** [comment]
I've got the same error with Google Colab. 

!dpkg -l | grep TensorRT

`ii  graphsurgeon-tf                                              7.0.0-1+cuda10.2                                  amd64        GraphSurgeon for TensorRT package
ii  libnvinfer-bin                                               7.0.0-1+cuda10.2                                  amd64        TensorRT binaries
ii  libnvinfer-dev                                               7.0.0-1+cuda10.2                                  amd64        TensorRT development libraries and headers
ii  libnvinfer-doc                                               7.0.0-1+cuda10.2                                  all          TensorRT documentation
ii  libnvinfer-plugin-dev                                        7.0.0-1+cuda10.2                                  amd64        TensorRT plugin libraries
ii  libnvinfer-plugin7                                           7.0.0-1+cuda10.2                                  amd64        TensorRT plugin libraries
ii  libnvinfer-samples                                           7.0.0-1+cuda10.2                                  all          TensorRT samples
ii  libnvinfer7                                                  7.0.0-1+cuda10.2                                  amd64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                                         7.0.0-1+cuda10.2                                  amd64        TensorRT ONNX libraries
ii  libnvonnxparsers7                                            7.0.0-1+cuda10.2                                  amd64        TensorRT ONNX libraries
ii  libnvparsers-dev                                             7.0.0-1+cuda10.2                                  amd64        TensorRT parsers libraries
ii  libnvparsers7                                                7.0.0-1+cuda10.2                                  amd64        TensorRT parsers libraries
ii  python3-libnvinfer                                           7.0.0-1+cuda10.2                                  amd64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev                                       7.0.0-1+cuda10.2                                  amd64        Python 3 development package for TensorRT
ii  tensorrt                                                     7.0.0.11-1+cuda10.2                               amd64        Meta package of TensorRT
ii  uff-converter-tf                                             7.0.0-1+cuda10.2                                  amd64        UFF converter for TensorRT package`

!nvidia-smi

`Sun May  3 16:56:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

When I run 

`with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
  builder.max_workspace_size = 1 << 28
  builder.max_batch_size = 1
  builder.fp16_mode = True`

I've got 

`TypeError                                 Traceback (most recent call last)
<ipython-input-18-b739a5fa47f7> in <module>()
----> 1 with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
      2   builder.max_workspace_size = 1 << 28
      3   builder.max_batch_size = 1
      4   builder.fp16_mode = True

TypeError: pybind11::init(): factory function returned nullptr`

**Comment by WillJStone** [comment]
I got this error while using the official tensorrt docker file from the nvidia container repository.

nvcr.io/nvidia/tensorrt:20.03-py3

**Comment by rmccorm4** [comment]
Hi @WillJStone ,

Can you share the exact script you're running inside the NGC container that reproduces your error?

**Comment by tip3x** [comment]
got the same error on ngc image: nvcr.io/nvidia/l4t-ml

**Comment by vaibhawvipul** [comment]
To the guys who are facing this issue in docker container, make sure - 

1. You have CUDA 10.2 with tensorRT 7+
2. You have attached gpu to your container. `--gpus all`

**Comment by Akshaysharma29** [comment]
Hi @rawar have you checked that your `!nvidia-smi ` command is still showing CUDA Version: 10.1.
- I am facing the same issue. 
- This might be possible that Cuda is not change properly.
- If you have solved the issue can you share your approach? 

Thanks

**Comment by Akshaysharma29** [comment]
`!nvcc --version`    is showing 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

whereas 

`!nvidia-smi` is showing 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    33W / 250W |    263MiB / 16280MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
```
Hi, @rmccorm4  
I want to ask whether this can be the issue as the Cuda version is different in both the commands?

**Comment by copaah** [comment]
Facing same issue with the the `nvcr.io/nvidia/tensorrt:20.01-py2` container.

**Comment by MRHZBSJ** [comment]
> 
> 
> ＠rmccorm4,Hi,i have tried your suggestion, and i change my cuda10.1 to cuda10.0, but it still has such problem,the whole problem is:
> [TensorRT] ERROR: CUDA initialization failure with error 35. Please check your CUDA installation: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
> Traceback (most recent call last):
> master/scripts/Pytorch2ONNX.py", line 53, in ONNX2Engine
> with trt.Builder(TRT_LOGGER) as builder:
> TypeError: pybind11::init(): factory function returned nullptr
> Can you help me? tkx.

I am facing the same issue.
Jetson TX2
CUDA 10.0
TensorRT 5.0.6

**Comment by sksenthilkumar** [comment]
For all those facing this error with nvidia docker like `nvcr.io/nvidia/tensorrt:20.01-py2` `nvcr.io/nvidia/tensorrt:20.03-py3` 
try running the docker as `nvidia-docker run` instead of `docker run`. This solved the issue for me.

**Comment by lfernandes** [comment]
I had the same issue with other dockers versions too. Then I just noticed another message few lines above: `ERROR: CUDA initialization failure with error 222. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html`.

To fix, I had to update the NVIDIA driver on the host machine (from `450.102.04` to 460.x` which had updated CUDA Version from `11.0` to `11.2`).

**Comment by gioipv** [comment]
Helllo, I am newbie
In my case, i think my user was not in docker group for user docker on nvidia.
I use aws and GPU is Tesla T4. Tensorrt use docker on nvidia.
Because, after I added my user account into [docker group](https://docs.docker.com/engine/install/linux-postinstall/) with  `sudo usermod -aG docker $USER` 
I have to  activate the changes to groups with 'newgrp docker` every time to use Tensorrt. Maybe after reboot my aws, i dont have to command `newgrp docker`, but for now, I had to do it for fix this issues

**Comment by gioipv** [comment]
```
[TensorRT] ERROR: CUDA initialization failure with error 222. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "tensorrt_convert2trt.py", line 54, in <module>
    main(args)
  File "tensorrt_convert2trt.py", line 35, in main
    model_trt = torch2trt(model, [input_], max_workspace_size=1 << 30)
  File "/home/gioipv/workspaces/miniconda3/envs/eye_state/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 519, in torch2trt
    builder = trt.Builder(logger)
TypeError: pybind11::init(): factory function returned nullptr
```

Helllo, I am newbie
In my case, i think my user was not in docker group for user docker on nvidia.
I use aws and GPU is Tesla T4. Tensorrt use docker on nvidia.
Because, after I added my user account into [docker group](https://docs.docker.com/engine/install/linux-postinstall/) with  `sudo usermod -aG docker $USER` 
I have to  activate the changes to groups with `newgrp docker` every time to use Tensorrt. Maybe after reboot my aws, i dont have to command `newgrp docker`, but for now, I had to do it for fix this issues

**Comment by Lamply** [comment]
> ```
> [TensorRT] ERROR: CUDA initialization failure with error 222. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
> Traceback (most recent call last):
>   File "tensorrt_convert2trt.py", line 54, in <module>
>     main(args)
>   File "tensorrt_convert2trt.py", line 35, in main
>     model_trt = torch2trt(model, [input_], max_workspace_size=1 << 30)
>   File "/home/gioipv/workspaces/miniconda3/envs/eye_state/lib/python3.7/site-packages/torch2trt-0.3.0-py3.7.egg/torch2trt/torch2trt.py", line 519, in torch2trt
>     builder = trt.Builder(logger)
> TypeError: pybind11::init(): factory function returned nullptr
> ```
> 
> Helllo, I am newbie
> In my case, i think my user was not in docker group for user docker on nvidia.
> I use aws and GPU is Tesla T4. Tensorrt use docker on nvidia.
> Because, after I added my user account into [docker group](https://docs.docker.com/engine/install/linux-postinstall/) with `sudo usermod -aG docker $USER`
> I have to activate the changes to groups with `newgrp docker` every time to use Tensorrt. Maybe after reboot my aws, i dont have to command `newgrp docker`, but for now, I had to do it for fix this issues

I met the similar problem with yours, but sometimes it magically disappeared when I called `torch.cuda.current_device()` before that code.

**Comment by wikiwen** [comment]
@chegnyanjun @taomiao @ligonzheng @hyperfraise@Lamply@rmccorm4 
Hello, I met the same problem. I guess it may be caused by `import  torch` as pytorch shipped with it's own cuda and cudnn lib. If the cuda version of pytorch is mismatched with your tensorrt, this problem will show.

**Two solutions:** 
1. Don't use pytorch when you use tensorrt
2. Install pytorch with same cuda version with cuda used by current tensorrt

In my situation, I use `cuda10.1-cudnn7-devel-ubuntu18.04` container from nvidia and install the correct tensorrt5.1.5. I found the problem will show  if i use pytorch and tensorrt together and disappear if no pytorch. I check cuda of pytorch by
``` python
import torch
torch.version.cuda
# it shows: 9.0.176, which may make tensorrt built with cuda10.1 crashed
```
Thank @Lamply, your comment gives me some inspiration.

**Comment by kopyl** [comment]
So you guys did not fix it over 2 years?

**Comment by binbin-w** [comment]
TypeError: pybind11::init(): factory function returned nullptr
I encountered the same error, has anyone already solved this problem

**Comment by jianye0428** [comment]
I am also looking for a solution with this same issue.

**Comment by timf34** [comment]
Will add another voice that I'm also facing this issue

**Comment by Jellie122** [comment]
is anybody solve this problem, please let me know, thx!

**Comment by Jellie122** [comment]
solved by moving dependencies of tensorrt to the bin file of cuda
