### ISSUE TITLE
Multi-threaded inference with TensorRT dynamic shape model

### ISSUE THREAD

**Issue by Noobzm** [NVIDIA/TensorRT#3088]
Can you provide sample or reference for C++ Multi-threaded inference with TensorRT dynamic shape model, I am confused about this，thanks a lot!

**Comment by zerollzeng** [comment]
@samurdhikaru @ttyio for viz.

**Comment by ttyio** [comment]
@Noobzm , it the `trtexec` source code helpful? 
https://github.com/NVIDIA/TensorRT/tree/release/8.6/samples/trtexec
some of the code is in 
https://github.com/NVIDIA/TensorRT/tree/release/8.6/samples/common

**Comment by Noobzm** [comment]
@ttyio thanks, but it didn't solve my problem. I want to build multi-threaded dynamic shape inference with c++ api, here is a similar problem -->
https://forums.developer.nvidia.com/t/tensorrt-parallel-inference-when-most-input-shapes-locate-in-the-same-optimization-profile/178405

**Comment by ttyio** [comment]
Hi @Noobzm  , just readed the thread link, are you looking for `kPROFILE_SHARING_0806` ?

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a78e8d461b39b52904335d005506b009eaf70eb17ce2a8e8804e1672fdf3562a9a

**Comment by Noobzm** [comment]
@ttyio Yes, this new flag solve my problem perfectly,  thanks a lot !

**Comment by ttyio** [comment]
Thank you @Noobzm for confirm, closing.
