### ISSUE TITLE
Engine build failure of TensorRT 8.6 when Normalization Layer has more than 1 group and scale tensor is of size channel

### ISSUE THREAD

**Issue by haijieg** [NVIDIA/TensorRT#3094]
## Description

I am trying to use the new Normalization layer in 8.6 for group normalization. In PyTorch, the scale and bias tensors are of shape (C,) where C is the number of channels. However, when group is greater than 1, engine cannot build with scale tensor of shape (C,).

Example
```
input # ITensor shape (1, 4, 16, 16)
scale # ITensor shape (1, 4, 1, 1)
bias # ITensor shape (1, 4, 1, 1)

mask =  (1 << 2) |  (1 << 3)
layer = network.add_normalization(input, scale, bias, mask)
layer.num_groups = 2
output = layer.get_output(0)
```

When building engine with the layer above, the error message is

```
[06/28/2023-23:16:16] [TRT] [E] 4: [graphShapeAnalyzer.cpp::processCheck::862] Error Code 4: Internal Error ([NORMALIZATION]-[unknown_ir_ops.group_norm.default]-[group_norm_default]: scale dimensions not compatible for normalization)
```

This prevents Normalization layer to natively support GroupNorm definition from PyTorch. Similar to issue: https://github.com/NVIDIA/TensorRT/issues/1277

**Comment by zerollzeng** [comment]
I'm not sure whether this is a bug or not, I would suggest to export the group norm to onnx and use our onnx parser first. if it's work then please refer to how we import the op(https://github.com/onnx/onnx-tensorrt/blob/6ba67d3428e05f690145373ca87fb8d32f98df45/builtin_op_importers.cpp#L1719C47-L1719C47), if it fails then would be good if you can share the onnx model here, then we can take a further check.

**Comment by haijieg** [comment]
Thanks for the pointer. Now I see that ONNX's GroupNormalization definition assumes `scale` and `bias` per group while PyTorch's GroupNormalization assumes `scale` and `bias` per channel, which is why it cannot be directly specified using TRT's Normalization API.
