### ISSUE TITLE
Is there a tool to detect which layers are not supported by TRT?

### ISSUE THREAD

**Issue by Eloring** [NVIDIA/TensorRT#31]
As the title said, is there a direct tool to detect which layers in the model (either Caffe, TF, or ONNX) are not supported by TRT?
To accelerate a new model using TRT is hard to know where to start.

**Comment by zeruniverse** [comment]
I know there's a webpage for supported layers/ops: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html
