### ISSUE TITLE
XXX failure of TensorRT X.Y when running XXX on GPU XXX

### ISSUE THREAD

**Issue by lingl-space** [NVIDIA/TensorRT#3100]
## Description

Hello, I would like to ask about the sampleint8api sample. 
When I use the directive "--write_tensors" to generate the tensorrt dynamic range, the results obtained are somewhat different from the network hierarchy reasoned using onnxruntime, lacking some "Unnamed Layer"". 

How should I solve it? 
Or is there a statistical method implementation in the project that provides dynamic range?

## Environment

**TensorRT Version**: 7.2.3.4

**NVIDIA GPU**: GTX1080

**CUDA Version**: 11.1

**CUDNN Version**: 8.1

## These are part of my instructions for using the onnxruntime

```
    for i, input_ele in enumerate(ort_session.get_inputs()):
        ort_inputs[input_ele.name] = image

    outputs = [x.name for x in ort_session.get_outputs()]
    ort_outputs = ort_session.run(outputs, ort_inputs)
```

**Comment by zerollzeng** [comment]
I don't get what's the issue here? could you please provide a detailed explanation? Thanks!

**Comment by zerollzeng** [comment]
dup of https://github.com/NVIDIA/TensorRT/issues/3102, close this.
