### ISSUE TITLE
Layer (Unnamed Layer* 798) [PluginV2Ext] failed validation of TensorRT 7.2 when running on GPU RTX2070

### ISSUE THREAD

**Issue by Egorundel** [NVIDIA/TensorRT#3106]
## Description
Hello, I have the following error when I try to convert my onnx model to a trt file using trtexec:

(Unnamed Layer* 798) [PluginV2Ext]: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
Layer (Unnamed Layer* 798) [PluginV2Ext] failed validation

![Screenshot from 2023-07-04 10-29-19](https://github.com/NVIDIA/TensorRT/assets/65890558/15542f46-e33e-48ba-aa97-4c4edd2671d4)

What could be the problem?

When checking the onnx model via check_onnx.py an error comes out:
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for BatchedNMS_TRT with domain_version of 12
==> Context: Bad node spec for node. Name:  OpType: BatchedNMS_TRT

![Screenshot from 2023-07-04 10-37-31](https://github.com/NVIDIA/TensorRT/assets/65890558/1d881804-0edc-4341-b518-3b47a57d2cd0)

The graph of my model in netron looks like this:

![Screenshot from 2023-07-04 10-44-09](https://github.com/NVIDIA/TensorRT/assets/65890558/209662a4-2084-4252-b16c-d62303a5c8ce)

I use this instruction of export .pt to .onnx
https://github.com/DataXujing/YOLOv7/ of @DataXujing

**I will be grateful for your help!**

## Environment

**TensorRT Version**: 7.2.1.6.

**NVIDIA GPU**: RTX 2070

**CUDA Version**: 11.1

## Operating System:

**Python Version**: 3.7

**Operationg System**: Ubuntu 20.04

**Comment by zerollzeng** [comment]
Your model has dynamic shapes input?

**Comment by Egorundel** [comment]
The problem was solved by the fact that the simplify operation was performed before adding the NMS module. Before that I didn't use the simplify operation at all.
