### ISSUE TITLE
Error Code 2: Internal Error(Assertion !n->candidateRequirements.empty() failed. 

### ISSUE THREAD

**Issue by Wooho-Moon** [NVIDIA/TensorRT#3107]
When I am converting custom onnx model to trt using trtexec, I encountered follow error.
I researched for this error in this gihub, and found the one solution. That solution recommand to use the trt version 8.6 EA. But I cannot use the trt version because the jetson platform can't support that version yet. So, I need your help!
## Description

[07/04/2023-17:31:03] [E] Error[2]: [optimizer.cpp::getFormatRequirements::3103] Error Code 2: Internal Error (Assertion !n->candidateRequirements.empty() failed. No supported formats for Reshape_5218)
[07/04/2023-17:31:03] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[07/04/2023-17:31:03] [E] Engine could not be created from network
[07/04/2023-17:31:03] [E] Building engine failed
[07/04/2023-17:31:03] [E] Failed to create engine from model or file.
[07/04/2023-17:31:03] [E] Engine set up failed

## Environment

**TensorRT Version**: 8.5.2.2

**NVIDIA GPU**: Nvidia NX xavier orin

**NVIDIA Driver Version**: 

**CUDA Version**: 11.4

**CUDNN Version**: 8.6.0

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable): 

PyTorch Version (if applicable): 1.13

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

https://drive.google.com/drive/u/0/folders/14UnBCV2P6W1MLA77F2JdOkc9GQasrFEx
## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
Could you please also provide how you build the engine? like the trtexec command?

**Comment by zerollzeng** [comment]
Have you try 8.6 on x86? I wonder it may still not work.

**Comment by Wooho-Moon** [comment]
> Could you please also provide how you build the engine? like the trtexec command?

I build engine following command line.
trtexec --onnx=test.onnx --saveEngine=test.engine --verbose

That model successfully work on 8.6 EA!

**Comment by zerollzeng** [comment]
Ah so looks like a fixed version, I think all you can do is wait for the new jetpack release has 8.6. shouldn't be so long.

Sorry about the inconvenience.

**Comment by ttyio** [comment]
thanks all, closing!
