### ISSUE TITLE
Difference of Myelin optimization and FusedMHA plugin

### ISSUE THREAD

**Issue by gillbam** [NVIDIA/TensorRT#3108]
It appears that MHA is optimized using the Myelin backend. I would like to know if Myelin optimization is faster than the provided FusedMHA plugin. Also, when deploying MHA, do you recommend using the plugin or the original ONNX model exported by Torch?

**Comment by zerollzeng** [comment]
I recommend use native TRT, and we will keep optimizing the performance to give better OOTB performance.
