### ISSUE TITLE
Support of PACT quantization

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [NVIDIA/TensorRT#3122]
Hello

I'm trying PACT quantization by using your [clip function](https://github.com/NVIDIA/TensorRT/blob/a167852705d74bcc619d8fad0af4b9e4d84472fc/tools/pytorch-quantization/pytorch_quantization/nn/__init__.py), I want know if TensorRT support deployment it ?

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
Sorry @Oh-Cest-la-vie , we have no official optimization for PACT, could you share a simple onnx that contains PACT quantization? thanks!

**Comment by yuanjiechen** [comment]
Pytorch quantization contains PACT module, just enable learn_amax flag to enable it. 
You may want to use one learnable amax not two that default in pytorch quantization.

**Comment by ttyio** [comment]
@yuanjiechen  the learnt amax is exported as `x_scale` in QDQ node, and TRT support these onnx operators.
