### ISSUE TITLE
Unable to fuse gelu with int8 input 

### ISSUE THREAD

**Issue by ShiyangZhang** [NVIDIA/TensorRT#3127]
tensorrt version : 8.6.1
network: Layernorm-conv-gelu-conv  
QAT tool : pytorch-quantization
machine: 1080TI

if tensrrot's native ptq are used, the gelu can be fused into a single node with int8 in and int8 out.
However, for QAT,  when QDQ node inserted before gelu, this will not happen(fp32 in)

**tensorrt's native ptq:**
![image](https://github.com/NVIDIA/TensorRT/assets/15400364/b28f46a6-3cd2-4d4e-ac63-7e2b54b67fae)

**QDQ inserted:**

![image](https://github.com/NVIDIA/TensorRT/assets/15400364/df523628-b536-46ce-8516-a830918cb165)

How can I achive the same result？I would appreciate it if you could give me some guidance.

**Comment by ttyio** [comment]
@ShiyangZhang ,could you retry without q/dq between conv and gelu? thanks!

**Comment by ShiyangZhang** [comment]
> Q/DQ -> conv -> gelu -> Q/DQ
That does not work either.

> could you retry without q/dq between conv and gelu?
for both int8 and fp32, gelu can be fused into one node. For fp32, input and output are type of float.

**Comment by yuanjiechen** [comment]
Hello @ShiyangZhang :
Could I ask what's the engine viewer you used?
Is it the trex lib?

**Comment by ShiyangZhang** [comment]
> Hello @ShiyangZhang : Could I ask what's the engine viewer you used? Is it the trex lib?

Yes, is trex

**Comment by ttyio** [comment]
@ShiyangZhang , there is no INT8 tensorcore for Pascal, we did not have fused kernel for it.

**Comment by ShiyangZhang** [comment]
> @ShiyangZhang , there is no INT8 tensorcore for Pascal, we did not have fused kernel for it.

I understand. With tensorrt's native int8 Quantization for Pascal, gelu is a node with input and output type of int8. 
 With pytorch's ptq Quantization for Pascal, gelu is a node with input  type of float. 
But it seems not affect the speed very match.
Thanks for your time
