### ISSUE TITLE
Caffe model is faster than tensorflow's during inference, when the logical network structure is the same.

### ISSUE THREAD

**Issue by FashengChen0622** [NVIDIA/TensorRT#313]
## Description
Tensorflow's network structure definition is relatively redundant compared to Caffe. I wish TensorRT can remove these redundancies for inference acceleration.
 For example, with the same logical network structure in our test, the Caffe model has only 30+ layers after parsing, but the Tensorflow model has 80+ layers after parsing. This cost 100ms
on Caffe model inference, and 130ms on tensorflow model inference. By the way, the tested model is fully constitutional network, It has been converted to dynamic shape model when testing.
Specifically, I found that each Caffe constitutional layer is parsed to one <IConvolutionLayer> but each constitutional layer in Tensorflow is parsed to a combination of two <IConstantLayer>and one <IConvolutionLayer> ,since tensorflow splits convolutional layers into lower-level operations.
By the way, I'm not sure if this problem exists in other layers as well.

## Environment

**TensorRT Version**: TensorRT-6.0.1.5
**GPU Type**: m40
**Nvidia Driver Version**:   396.26
**CUDA Version**: 9.0
**CUDNN Version**: cudnn-v7.6
**Operating System + Version**:  3.10.107-1-tlinux2-0046
**Python Version (if applicable)**:  3.5
**TensorFlow Version (if applicable)**:  
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by gcp** [comment]
>Specifically, I found that each Caffe constitutional layer is parsed to one but each constitutional layer in Tensorflow is parsed to a combination of two and one ,since tensorflow splits convolutional layers into lower-level operations.

TensorRT should re-fuse the layers during the engine building. Do you have any more details about the network structure and what you're doing? Your post is very vague to give concrete advice.

**Comment by rmccorm4** [comment]
Closing for now since no response on details/repro.
