### ISSUE TITLE
Is trt support parallel execution? 

### ISSUE THREAD

**Issue by yuanjiechen** [NVIDIA/TensorRT#3133]
## Description
Assuming the following simple model: 
![Screenshot from 2023-07-14 17-36-02](https://github.com/NVIDIA/TensorRT/assets/43607076/b14c4d1d-b4a1-413a-b2c8-dcc30a2349f1)

If GPU resource is enough, how can I compute A, B, C and X, Y, Z at the same time? and then compute D (In one onnx model).
Tensorrt will auto optimize this or not?
Is the set_aux_streams or buildconfig infStream work in this situation?

Thanks !

## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: RTX 3090

**NVIDIA Driver Version**: 530

**CUDA Version**: 12.1.1

**CUDNN Version**: 8.9.0

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: Yes

**Comment by yuanjiechen** [comment]
I know the answer.

**Comment by shubharajkharel** [comment]
Hi @yuanjiechen,
I am trying to do the same. Could you share your answer?

**Comment by laurenlong** [comment]
Same question. Could you share your answer?
