### ISSUE TITLE
Cannot converted the mask-rcnn model to uff in the sampleUffMaskRCNN sample

### ISSUE THREAD

**Issue by chiehpower** [NVIDIA/TensorRT#314]
## Description

I tried to convert the mask-rcnn model to uff at 
`TensorRT-7.0.0.11/samples/sampleUffMaskRCNN/converted`.

My command is 
```
python3 mrcnn_to_trt_single.py -w ../../../data/mask_rcnn_coco.h5 -o ../../../data/mask_rcnn_coco.uff -p ./config.py 
```
First, I met the error about setting a channel dimension.
```
raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```
I already [solved this problem](https://github.com/matterport/Mask_RCNN/issues/30#issuecomment-571050709).

However, when I tried it again, I met a new error message below.
```
The output names of tensorflow graph nodes: ['mrcnn_mask/Reshape_1']
WARNING:tensorflow:From mrcnn_to_trt_single.py:142: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /home/chieh/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:270: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From /home/chieh/.local/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py:227: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From /home/chieh/.local/lib/python3.6/site-packages/graphsurgeon/_utils.py:2: The name tf.NodeDef is deprecated. Please use tf.compat.v1.NodeDef instead.

Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 169, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 128, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 162, in convert_model
    debug_mode = False
  File "/home/chieh/.local/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/chieh/.local/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 106, in from_tensorflow
    pre.preprocess(dynamic_graph)
  File "./config.py", line 145, in preprocess
    dynamic_graph.remove(timedistributed_remove_list)
  File "/home/chieh/.local/lib/python3.6/site-packages/graphsurgeon/DynamicGraph.py", line 470, in remove
    nodes = self._force_to_nodes(nodes)
  File "/home/chieh/.local/lib/python3.6/site-packages/graphsurgeon/DynamicGraph.py", line 324, in _force_to_nodes
    buf = self._force_to_names(buf)
  File "/home/chieh/.local/lib/python3.6/site-packages/graphsurgeon/DynamicGraph.py", line 307, in _force_to_names
    assert False, "The name %s does not exist" % el
AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist
```
Even I got rid of those not existing name from the config.py.
```

timedistributed_remove_list = [
        "mrcnn_class_conv1/Reshape/shape", "mrcnn_class_conv1/Reshape", "mrcnn_class_conv1/Reshape_1/shape", "mrcnn_class_conv1/Reshape_1",
        "mrcnn_class_bn1/Reshape/shape", "mrcnn_class_bn1/Reshape",
        "mrcnn_class_conv2/Reshape/shape", "mrcnn_class_conv2/Reshape", "mrcnn_class_conv2/Reshape_1/shape", "mrcnn_class_conv2/Reshape_1",
        "mrcnn_class_bn2/Reshape/shape", "mrcnn_class_bn2/Reshape", 
        "mrcnn_class_logits/Reshape/shape", "mrcnn_class_logits/Reshape","mrcnn_class_logits/Reshape_1/shape", "mrcnn_class_logits/Reshape_1",
        "mrcnn_class/Reshape/shape", "mrcnn_class/Reshape","mrcnn_class/Reshape_1/shape", "mrcnn_class/Reshape_1",
        "mrcnn_bbox_fc/Reshape/shape", "mrcnn_bbox_fc/Reshape","mrcnn_bbox_fc/Reshape_1/shape", "mrcnn_bbox_fc/Reshape_1",

        "mrcnn_mask_conv1/Reshape/shape", "mrcnn_mask_conv1/Reshape", "mrcnn_mask_conv1/Reshape_1/shape", "mrcnn_mask_conv1/Reshape_1",
        "mrcnn_mask_bn1/Reshape/shape", "mrcnn_mask_bn1/Reshape", 
        "mrcnn_mask_conv2/Reshape/shape", "mrcnn_mask_conv2/Reshape", "mrcnn_mask_conv2/Reshape_1/shape", "mrcnn_mask_conv2/Reshape_1",
        "mrcnn_mask_bn2/Reshape/shape", "mrcnn_mask_bn2/Reshape", 
        "mrcnn_mask_conv3/Reshape/shape", "mrcnn_mask_conv3/Reshape", "mrcnn_mask_conv3/Reshape_1/shape", "mrcnn_mask_conv3/Reshape_1",
        "mrcnn_mask_bn3/Reshape/shape", "mrcnn_mask_bn3/Reshape", 
        "mrcnn_mask_conv4/Reshape/shape", "mrcnn_mask_conv4/Reshape", "mrcnn_mask_conv4/Reshape_1/shape", "mrcnn_mask_conv4/Reshape_1",
        "mrcnn_mask_bn4/Reshape/shape", "mrcnn_mask_bn4/Reshape", 
        "mrcnn_mask_deconv/Reshape/shape", "mrcnn_mask_deconv/Reshape", "mrcnn_mask_deconv/Reshape_1/shape", "mrcnn_mask_deconv/Reshape_1",
        "mrcnn_mask/Reshape/shape", "mrcnn_mask/Reshape", "mrcnn_mask/Reshape_1/shape", "mrcnn_mask/Reshape_1"
# "mrcnn_class_bn1/Reshape_5/shape" "mrcnn_class_bn1/Reshape_5" "mrcnn_class_bn2/Reshape_5/shape", "mrcnn_class_bn2/Reshape_5",
# "mrcnn_mask_bn1/Reshape_5/shape", "mrcnn_mask_bn1/Reshape_5" "mrcnn_mask_bn2/Reshape_5/shape", "mrcnn_mask_bn2/Reshape_5",
# "mrcnn_mask_bn3/Reshape_5/shape", "mrcnn_mask_bn3/Reshape_5", "mrcnn_mask_bn4/Reshape_5/shape", "mrcnn_mask_bn4/Reshape_5"
]
```
I still got the strange error.
```
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 169, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 128, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 162, in convert_model
    debug_mode = False
  File "/home/chieh/.local/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/chieh/.local/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 106, in from_tensorflow
    pre.preprocess(dynamic_graph)
  File "./config.py", line 149, in preprocess
    connect(dynamic_graph, timedistributed_connect_pairs)
  File "./config.py", line 139, in connect
    if node_a_name not in dynamic_graph.node_map[node_b_name].input:
KeyError: 'mrcnn_mask_bn4/batchnorm/mul_1'
```
I don't think so that I should get rid of those names from config.py actually.
Is there any solution or thought about this problem?

Thank  you.

## Environment
- TensorRT version: 7.0.0.11 (Downloaded the tar file from NVIDIA website.)
- Cuda version: 10.2
- TensorFlow-gpu: 1.14.0
- Cudnn version: 7.6.5
- GPU: GTX1060
- Ubuntu: 18.04
- Keras : 2.3.1

PS　I didn't use the NVidia docker and NGC.

**Comment by Tyler-D** [comment]
Maybe you could try with keras 2.1.3 ? There may be difference in implementation of BatchNormalization between versions.

**Comment by chiehpower** [comment]
> Maybe you could try with keras 2.1.3 ? There may be difference in implementation of BatchNormalization between versions.

Thanks for your suggestion!
I am sorry about that I haven't updated the latest situation.

1. I already changed to keras 2.1.3 which was requested in requirement.txt. 
2. Eventually I found the problem which is the step of keras converting from .h5 to .pb.

Q: How can I find this problem?
A: This case on Windows worked very well. So I took the .pb model which was converted on Windows to linux. And then, I used this file to convert from .pb to uff model. It didn't get any error. 

I have set as same documents and setting as windows; however, it still got wrong if my pb file was produced on linux.
I cannot find where the problem is. I compared whole executing files between on windows and on Linux, but there are no any difference.

# Conclusion 
The step of converting .h5 to .pb of keras is not completely correct.

PS I was following the instruction of `README.md`.
---
My env info:
- python 3.6.9
- keras 2.1.3

**Comment by rmccorm4** [comment]
Closing as it seems to be solved. Will re-open if others experience this issue.

**Comment by boredomed** [comment]
I am also getting the same error as following:

> Traceback (most recent call last):
>   File "mrcnn_to_trt_single.py", line 166, in <module>
>     main()
>   File "mrcnn_to_trt_single.py", line 115, in main
>     model = modellib.MaskRCNN(mode="inference", model_dir=LOG_DIR, config=config).keras_model
>   File "/usr/local/lib/python3.6/dist-packages/mrcnn/model.py", line 1832, in __init__
>     self.keras_model = self.build(mode=mode, config=config)
>   File "/usr/local/lib/python3.6/dist-packages/mrcnn/model.py", line 1896, in build
>     stage5=True, train_bn=config.TRAIN_BN)
>   File "/usr/local/lib/python3.6/dist-packages/mrcnn/model.py", line 180, in resnet_graph
>     x = KL.Conv2D(64, (7, 7), strides=(2, 2), name='conv1', use_bias=True)(x)
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 463, in __call__
>     self.build(unpack_singleton(input_shapes))
>   File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 132, in build
>     raise ValueError('The channel dimension of the inputs '
> ValueError: The channel dimension of the inputs should be defined. Found `None`.`
> 

The command that i am using is <br>
`python3 mrcnn_to_trt_single.py -w /root/Mask_RCNN/mask_rcnn_cafe_0006.h5 -o /root/Mask_RCNN/mrcnn_nchw.uff -p ./config.py`

**Comment by chiehpower** [comment]
> I am also getting the same error as following:
> 
> > Traceback (most recent call last):
> > File "mrcnn_to_trt_single.py", line 166, in 
> > main()
> > File "mrcnn_to_trt_single.py", line 115, in main
> > model = modellib.MaskRCNN(mode="inference", model_dir=LOG_DIR, config=config).keras_model
> > File "/usr/local/lib/python3.6/dist-packages/mrcnn/model.py", line 1832, in **init**
> > self.keras_model = self.build(mode=mode, config=config)
> > File "/usr/local/lib/python3.6/dist-packages/mrcnn/model.py", line 1896, in build
> > stage5=True, train_bn=config.TRAIN_BN)
> > File "/usr/local/lib/python3.6/dist-packages/mrcnn/model.py", line 180, in resnet_graph
> > x = KL.Conv2D(64, (7, 7), strides=(2, 2), name='conv1', use_bias=True)(x)
> > File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 463, in **call**
> > self.build(unpack_singleton(input_shapes))
> > File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 132, in build
> > raise ValueError('The channel dimension of the inputs '
> > ValueError: The channel dimension of the inputs should be defined. Found `None`.`
> 
> The command that i am using is
> 
> `python3 mrcnn_to_trt_single.py -w /root/Mask_RCNN/mask_rcnn_cafe_0006.h5 -o /root/Mask_RCNN/mrcnn_nchw.uff -p ./config.py`

Hi @boredomed,
Did you try my [method](https://github.com/matterport/Mask_RCNN/issues/30#issuecomment-571050709 )?  From matterport/Mask_RCNN#30

**Comment by boredomed** [comment]
Hi @chiehpower 
Once i try your method the following issue was resolved but it created another error which i am unable to resolve did you got this error ?

> Traceback (most recent call last):
>   File "mrcnn_to_trt_single.py", line 211, in <module>
>     main()
>   File "mrcnn_to_trt_single.py", line 170, in main
>     text=True, list_nodes=list_nodes)
>   File "mrcnn_to_trt_single.py", line 204, in convert_model
>     debug_mode = False
>   File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
>     return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 106, in from_tensorflow
>     pre.preprocess(dynamic_graph)
>   File "./config.py", line 119, in preprocess
>     dynamic_graph.remove(timedistributed_remove_list)
>   File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 470, in remove
>     nodes = self._force_to_nodes(nodes)
>   File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 324, in _force_to_nodes
>     buf = self._force_to_names(buf)
>   File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 307, in _force_to_names
>     assert False, "The name %s does not exist" % el
> AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist
>

**Comment by chiehpower** [comment]
> Hi @chiehpower
> Once i try your method the following issue was resolved but it created another error which i am unable to resolve did you got this error ?
> 
> > Traceback (most recent call last):
> > File "mrcnn_to_trt_single.py", line 211, in 
> > main()
> > File "mrcnn_to_trt_single.py", line 170, in main
> > text=True, list_nodes=list_nodes)
> > File "mrcnn_to_trt_single.py", line 204, in convert_model
> > debug_mode = False
> > File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
> > return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
> > File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 106, in from_tensorflow
> > pre.preprocess(dynamic_graph)
> > File "./config.py", line 119, in preprocess
> > dynamic_graph.remove(timedistributed_remove_list)
> > File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 470, in remove
> > nodes = self._force_to_nodes(nodes)
> > File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 324, in _force_to_nodes
> > buf = self._force_to_names(buf)
> > File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 307, in _force_to_names
> > assert False, "The name %s does not exist" % el
> > AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist

Yes, I met the same issue before!! 
I spent a lot of time on Maskrcnn sample.
As my experience, eventually I found that the main problem is the pb file.
The pb model which is converted from h5 is not complete correct, even we can see that the file size is quite close.

(The MRCNN sample can be succeeded to run on Windows.) 
However, if I took the pb file which was generated from windows to try on linux, I could pass. 
So I suspect that probably your pb file is not correct as well.
Of course, I was just sharing my experience for you. 
Cannot guarantee that my situation is totally as same as yours.

**Comment by HKun1997** [comment]
@chiehpower Hi!  I had the same problem and tried your method. But it still raised the same error"ValueError: The channel dimension of the inputs should be defined. Found `None`.".  Would you like to give some advices?
My env info:anaconda3, keras2.1.3, Tensorflow-gpu1.9.0, Windows 10 , Python3.6.5

**Comment by chiehpower** [comment]
> @chiehpower Hi! I had the same problem and tried your method. But it still raised the same error"ValueError: The channel dimension of the inputs should be defined. Found `None`.". Would you like to give some advices?
> My env info:anaconda3, keras2.1.3, Tensorflow-gpu1.9.0, Windows 10 , Python3.6.5

Hi @HKun1997, I am sorry that I haven't tested on Windows system before. However, according to my colleague's experience, he could build successfully without any error on Win system before. Make sure your TensorRT version which is corresponded to CUDA version, and your environment paths also setup correctly. I have no further advice on this issue because I was not solving this issue by amending some codes. I solved this issue by reinstalling from scratch.

Thanks.

**Comment by HKun1997** [comment]
> > @chiehpower Hi! I had the same problem and tried your method. But it still raised the same error"ValueError: The channel dimension of the inputs should be defined. Found `None`.". Would you like to give some advices?
> > My env info:anaconda3, keras2.1.3, Tensorflow-gpu1.9.0, Windows 10 , Python3.6.5
> 
> Hi @HKun1997, I am sorry that I haven't tested on Windows system before. However, according to my colleague's experience, he could build successfully without any error on Win system before. Make sure your TensorRT version which is corresponded to CUDA version, and your environment paths also setup correctly. I have no further advice on this issue because I was not solving this issue by amending some codes. I solved this issue by reinstalling from scratch.
> 
> Thanks.

Thanks. Would you like to share your env info which you converted the model sucessfully?

**Comment by chiehpower** [comment]
> > > @chiehpower Hi! I had the same problem and tried your method. But it still raised the same error"ValueError: The channel dimension of the inputs should be defined. Found `None`.". Would you like to give some advices?
> > > My env info:anaconda3, keras2.1.3, Tensorflow-gpu1.9.0, Windows 10 , Python3.6.5
> > 
> > 
> > Hi @HKun1997, I am sorry that I haven't tested on Windows system before. However, according to my colleague's experience, he could build successfully without any error on Win system before. Make sure your TensorRT version which is corresponded to CUDA version, and your environment paths also setup correctly. I have no further advice on this issue because I was not solving this issue by amending some codes. I solved this issue by reinstalling from scratch.
> > Thanks.
> 
> Thanks. Would you like to share your env info which you converted the model sucessfully?

# My environment information: 
### Desktop
- CUDA: `10.0`
- Nvidia driver version: `440.33.01`
- GPU models and configuration:  `GeForce GTX 1060 6GB`
- cudnn: `7.6.5`
- PyTorch version: `1.3.1`
- TensorRT version: `7.0.0.11`
- Ubuntu: `18.04`
- Python: `3.6.9 `

### AGX Xavier [Jetson device]
- Jetpack: 4.3 [L4T 32.3.1]
- GPU-Arch: 7.2
- CUDA: 10.0.326
- cuDNN: 7.6.3.28-1+cuda10.0
- TensorRT: 6.0.1.10-1+cuda10.0

I all succeeded to implement the sampleUffMaskRCNN sample without any error in the end. I have tried cuda 10.2 in my desktop, but I met the error as what I mentioned in the beginning. (Of course, I don't think so cuda `10.2` which was the main factor in this issue.) 

Hope my information can help you.  :)

**Comment by HKun1997** [comment]
> > > > @chiehpower Hi! I had the same problem and tried your method. But it still raised the same error"ValueError: The channel dimension of the inputs should be defined. Found `None`.". Would you like to give some advices?
> > > > My env info:anaconda3, keras2.1.3, Tensorflow-gpu1.9.0, Windows 10 , Python3.6.5
> > > 
> > > 
> > > Hi @HKun1997, I am sorry that I haven't tested on Windows system before. However, according to my colleague's experience, he could build successfully without any error on Win system before. Make sure your TensorRT version which is corresponded to CUDA version, and your environment paths also setup correctly. I have no further advice on this issue because I was not solving this issue by amending some codes. I solved this issue by reinstalling from scratch.
> > > Thanks.
> > 
> > 
> > Thanks. Would you like to share your env info which you converted the model sucessfully?
> 
> # My environment information:
> ### Desktop
> * CUDA: `10.0`
> * Nvidia driver version: `440.33.01`
> * GPU models and configuration:  `GeForce GTX 1060 6GB`
> * cudnn: `7.6.5`
> * PyTorch version: `1.3.1`
> * TensorRT version: `7.0.0.11`
> * Ubuntu: `18.04`
> * Python: `3.6.9 `
> 
> ### AGX Xavier [Jetson device]
> * Jetpack: 4.3 [L4T 32.3.1]
> * GPU-Arch: 7.2
> * CUDA: 10.0.326
> * cuDNN: 7.6.3.28-1+cuda10.0
> * TensorRT: 6.0.1.10-1+cuda10.0
> 
> I all succeeded to implement the sampleUffMaskRCNN sample without any error in the end. I have tried cuda 10.2 in my desktop, but I met the error as what I mentioned in the beginning. (Of course, I don't think so cuda `10.2` which was the main factor in this issue.)
> 
> Hope my information can help you. :)

Thanks! Why does the env info include PyTorch without Tensorflow and Keras?

**Comment by chiehpower** [comment]
> Thanks! Why does the env info include PyTorch without Tensorflow and Keras?

Hi @HKun1997,

You are right. I didn't notice this. 
```
Tensorflow: 1.14
Keras: 2.1.3
```

**Comment by HKun1997** [comment]
> Hi @HKun1997,
> 
> You are right. I didn't notice this.
> 
> ```
> Tensorflow: 1.14
> Keras: 2.1.3
> ```
Thanks! I solved the error"ValueError: The channel dimension of the inputs should be defined. Found `None`.".But another error occurd"AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist". I didn't got the solution from above information.

**Comment by chiehpower** [comment]
> > Hi @HKun1997,
> > You are right. I didn't notice this.
> > ```
> > Tensorflow: 1.14
> > Keras: 2.1.3
> > ```
> 
> Thanks! I solved the error"ValueError: The channel dimension of the inputs should be defined. Found `None`.".But another error occurd"AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist". I didn't got the solution from above information.

Exactly. So that's why I didn't persist in solving this issue. To be honest, I thought we shouldn't try to solve this error because it was not a normal error. In general, the process should like the `README.md` that we can successfully build/ make it without the error which is relevant with the content of `config.py` or main file. 

I also asked on NVIDIA forum about this issue. However, I got the solution mostly like using the NVIDIA NGC and nvidia-docker. It can confirm your environment setting which is as same as them, and you don't need to setup anything from scratch.

**Comment by HKun1997** [comment]
> Exactly. So that's why I didn't persist in solving this issue. To be honest, I thought we shouldn't try to solve this error because it was not a normal error. In general, the process should like the `README.md` that we can successfully build/ make it without the error which is relevant with the content of `config.py` or main file.
> 
> I also asked on NVIDIA forum about this issue. However, I got the solution mostly like using the NVIDIA NGC and nvidia-docker. It can confirm your environment setting which is as same as them, and you don't need to setup anything from scratch.

Got it. I think you are right. I have focoused on deploying Matterport's Mask RCNN in C++ environment for months. And I have tried depoly it with Open CV and TensorflowRT, but both failed. Did you have any experience about depolying it in C++? Or would you like to share some ideas?

**Comment by chiehpower** [comment]
> Got it. I think you are right. I have focoused on deploying Matterport's Mask RCNN in C++ environment for months. And I have tried depoly it with Open CV and TensorflowRT, but both failed. Did you have any experience about depolying it in C++? Or would you like to share some ideas?

Unfortunately, mainly I focus on developing in Python. 
I have also tried to develop TensorFlow with TensorRT for few month. However, TensorRT announced that they will deprecate `uff parser` in the future, and you knew that TensorFlow is mainly using `UFF parser` to generate a TRT engine in TensorRT. Even I thought to use Tensorflow `.pb` to `.onnx` then `.onnx` to `.trt`, but you will find there are many unsupported operations in those converting tools. Too complicated and it will take a lot of time.  
![Screenshot at 14-33-16](https://user-images.githubusercontent.com/32332200/82292858-2de51a00-99de-11ea-855f-51373641235d.png)
Hence, I was changing to use `Pytorch` this way. Pytorch is using `onnx parser`. Sometimes Pytorch is more kind than TensorFlow. Anyway it is just my choice and strategy on TensorRT.

If your goal is only using Matterport's MRCNN, I think it is not a hard thing. Probably you can consider to try this. [tensorrt-utils
](https://github.com/rmccorm4/tensorrt-utils/tree/master/OSS)

**Comment by HKun1997** [comment]
> Unfortunately, mainly I focus on developing in Python.
> I have also tried to develop TensorFlow with TensorRT for few month. However, TensorRT announced that they will deprecate `uff parser` in the next TRT version, and you knew that TensorFlow is mainly using `UFF parser` to generate a TRT engine in TensorRT. Even I thought to use Tensorflow `.pb` to `.onnx` then `.onnx` to `.trt`, but you will find there are many unsupported operations in those converting tools. Too complicated and it will take a lot of time.
> ![Screenshot at 14-33-16](https://user-images.githubusercontent.com/32332200/82292858-2de51a00-99de-11ea-855f-51373641235d.png)
> Hence, I was changing to use `Pytorch` this way. Pytorch is using `onnx parser`. Sometimes Pytorch is more kind than TensorFlow. Anyway it is just my choice and strategy on TensorRT.
> 
> If your goal is only using Matterport's MRCNN, I think it is not a hard thing. Probably you can consider to try this. [tensorrt-utils ](https://github.com/rmccorm4/tensorrt-utils/tree/master/OSS)

OK! Thanks a lot!

**Comment by zf921022** [comment]
> > Hi @chiehpower
> > Once i try your method the following issue was resolved but it created another error which i am unable to resolve did you got this error ?
> > > Traceback (most recent call last):
> > > File "mrcnn_to_trt_single.py", line 211, in
> > > main()
> > > File "mrcnn_to_trt_single.py", line 170, in main
> > > text=True, list_nodes=list_nodes)
> > > File "mrcnn_to_trt_single.py", line 204, in convert_model
> > > debug_mode = False
> > > File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
> > > return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
> > > File "/usr/local/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 106, in from_tensorflow
> > > pre.preprocess(dynamic_graph)
> > > File "./config.py", line 119, in preprocess
> > > dynamic_graph.remove(timedistributed_remove_list)
> > > File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 470, in remove
> > > nodes = self._force_to_nodes(nodes)
> > > File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 324, in _force_to_nodes
> > > buf = self._force_to_names(buf)
> > > File "/usr/local/lib/python3.6/dist-packages/graphsurgeon/DynamicGraph.py", line 307, in _force_to_names
> > > assert False, "The name %s does not exist" % el
> > > AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist
> 
> Yes, I met the same issue before!!
> I spent a lot of time on Maskrcnn sample.
> As my experience, eventually I found that the main problem is the pb file.
> The pb model which is converted from h5 is not complete correct, even we can see that the file size is quite close.
> 
> (The MRCNN sample can be succeeded to run on Windows.)
> However, if I took the pb file which was generated from windows to try on linux, I could pass.
> So I suspect that probably your pb file is not correct as well.
> Of course, I was just sharing my experience for you.
> Cannot guarantee that my situation is totally as same as yours.

Hi， i met the same issue as "AssertionError: The name mrcnn_class_bn1/Reshape_5/shape does not exist"
So did you finally find a way to solve this problem on linux?

**Comment by Tyler-D** [comment]
@zf921022 , Try this:

1) nvcr.io/nvidia/tensorflow:18.12-py3
2) install uff, graphsugeon, keras==2.1.3
3) Modify uff's transpose convolution
4) Export:
NOTE: UFF has been tested with TensorFlow 1.14.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.5
=== Automatically deduced input nodes ===
[name: "input_image"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: 3
      }
      dim {
        size: 1024
      }
      dim {
        size: 1024
      }
    }
  }
}
]
=========================================

Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_mask_trt as custom op: PyramidROIAlign_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p5upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p4upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p3upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: SpecialSlice_TRT yet.
Converting mrcnn_detection_bboxes as custom op: SpecialSlice_TRT
Warning: No conversion function registered for layer: DetectionLayer_TRT yet.
Converting mrcnn_detection as custom op: DetectionLayer_TRT
Warning: No conversion function registered for layer: ProposalLayer_TRT yet.
Converting ROI as custom op: ProposalLayer_TRT
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_classifier as custom op: PyramidROIAlign_TRT
DEBUG [/usr/local/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py:96] Marking ['mrcnn_detection', 'mrcnn_mask/Sigmoid'] as outputs
No. nodes: 3049

**Comment by zf921022** [comment]
>     1. nvcr.io/nvidia/tensorflow:18.12-py3

Thanks for your reply! I will try it.

**Comment by batselem** [comment]
I got the exact same error `KeyError: 'mrcnn_class_conv1/Reshape/shape'` Did anyone solve this?

My Env:
tensorflow==1.13.1
keras==2.2.4
