### ISSUE TITLE
TensorRT slower than ONNX with for-loop

### ISSUE THREAD

**Issue by chiaitian** [NVIDIA/TensorRT#3142]
## Description

My model has a mutiple decoder steps for-loop. I exported the pytorch model to ONNX  and TensorRT with for-loop successfully.
But the TensorRT model is slower than ONNX model, even slower than onnx-cpu.

## Environment

**TensorRT Version**:  TensorRT-8.4.3.1

**NVIDIA GPU**:  Tesla T4

**NVIDIA Driver Version**: 515.65.01

**CUDA Version**: 11.1

**CUDNN Version**: 8.4.1

Operating System:  Ubuntu 7.5.0-3ubuntu1~18.04

PyTorch Version (if applicable): 1.13.1

onnx                     1.13.1
onnxoptimizer            0.3.13
onnxruntime-gpu          1.14.1
onnxsim                  0.4.19
opset_version=14

## Relevant Files

**Model link**: 

onnx model: https://drive.google.com/file/d/19X3eq_y4M2N12N9F653-1m9x1KmAEurV/view?usp=sharing

## Reproduce steps:

```
polygraphy convert --model-type onnx --trt-min-shapes images:[1,1,32,32] images_masks:[1,1,32,32] --trt-opt-shapes imag
es:[1,1,160,320] images_masks:[1,1,160,320] --trt-max-shapes images:[8,1,320,640] images_masks:[8,1,320,640] -o test.engine test.onnx

polygraphy run test.onnx --onnxrt  --input-shapes images:[1,1,160,320] images_masks:[1,1,160,320] --iters 50

polygraphy run test.engine --trt  --input-shapes images:[1,1,160,320] images_masks:[1,1,160,320] --iters 50
```

**Comment by zerollzeng** [comment]
Will check and reply, but I had some issue when try to use polygraphy with onnxruntime-gpu, could you tell me how to setup?

Also could you please try latest TRT 8.6 first? Thanks!

**Comment by chiaitian** [comment]
Thank your reply. I also had issue when use polygraphy with onnxruntime-gpu, but using python `onnxruntime.InferenceSession`  with cuda provider is ok.
I tested in the latest docker image tensorrt:23.06-py3. The result now is normal, the TensorRT fp32 model time is 1/3 of onnxruntime-gpu time.

Another question about GPU driver compatibility. My host T4 driver version is 450.203.08,  the cuda version of docker image tensorrt:23.06-py3 is 12.1. Are they compatible? From my init test, i run successfully the `polygraph convert/run` in the docker container.

**Comment by chiaitian** [comment]
Ok, thank you again!
