### ISSUE TITLE
How to set some layer run in the specified precision

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3144]
## Description

Hello, I would like to have certain layers in the network run at a specified precision. For example, when some layers are uniformly converted to an fp16 engine, there is a significant loss in precision. I would like to keep some layers at fp32. How can I do that? Thank you very much.
## Environment

ubuntu 20.04

**Comment by zerollzeng** [comment]
You can set the layer precision. A quick try is to use `trtexec --layerPrecisions=xxx --precisionConstraints=xxx`, please check the `trtexec -h` for more information.

API way please search our API doc. e.g.
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_layer.html#a1db7e4d17afc29950145514fd7744f74
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#abdc74c40fe7a0c3d05d2caeccfbc29c1ae5ffc0f6c7f67f043461c7b9d95113b9

Seach in the TensorRT repo to see the usage is also helpful.

**Comment by sanbuphy** [comment]
> You can set the layer precision. A quick try is to use `trtexec --layerPrecisions=xxx --precisionConstraints=xxx`, please check the `trtexec -h` for more information.
> 
> API way please search our API doc. e.g. https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_layer.html#a1db7e4d17afc29950145514fd7744f74 https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#abdc74c40fe7a0c3d05d2caeccfbc29c1ae5ffc0f6c7f67f043461c7b9d95113b9
> 
> Seach in the TensorRT repo to see the usage is also helpful.

Thank you very much ! 

and here comes the another question.
I need to traverse the graph and find the specified name node. one way is that i can use graphsurgeon .I don't know if i can do it in tensorrt api when i use a onnx file to build the engine.

**Comment by zerollzeng** [comment]
> I don't know if i can do it in tensorrt api when i use a onnx file to build the engine.

Yes you can.

**Comment by zerollzeng** [comment]
Just take our trtexec source code as an example.

**Comment by sanbuphy** [comment]
> Just take our trtexec source code as an example.

OK, I will check the examples in NGC docker /workspace
