### ISSUE TITLE
How to obtain the tops of engine in the inference process by TRT(trtexec) ?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#3146]
My idea: 

get  `Total GPU Compute Time` by trtexec , mark  t; 
then get total flop of whole kernel by ncu,  mark total_flop;    
`tops = total_flop /t * 1.e-12`  ?

**Comment by zerollzeng** [comment]
It's wrong:
1. FLOPS in your case is model-specific, and TRT will do a lot of optimization on it, the correct way is to compute MACs of each layer and sum then up.
2. TOPS is a GPU property, it depends on the number of SMs, freq, etc, it's shown in our GPU specs, but it's not related to the model.

**Comment by lix19937** [comment]
@zerollzeng  Thanks,  Can I understand it this: we cannot say how many TOPS  of a model occupies on the orin in inference phase ?

**Comment by zerollzeng** [comment]
Correct.

**Comment by lix19937** [comment]
> Correct.

thanks
