### ISSUE TITLE
diffusion demo failure of TensorRT 8.5 when running demo_txt2img.py on GPU A100 80G

### ISSUE THREAD

**Issue by kisisjrlly** [NVIDIA/TensorRT#3150]
when I run 
`CUDA_MODULE_LOADING=LAZY CUDA_VISIBLE_DEVICES=0  python3 demo_txt2img.py "a beautiful photograph of Mt. Fuji during cherry blossom" --build-dynamic-shape --onnx-opset=16`
 some error occured:
<img width="772" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/34215214/5c39cad9-4108-4dfa-b561-6d1f89919898">
We can see that the max_device_memory is 80G(86909512704),  this is all the GPU memory capacity.
How can I solve this problem

**Comment by keddyjin** [comment]
How about using the latest TRT8.6 version?
And are you using in a container, if so, you can set a large `--shm-size`

**Comment by zerollzeng** [comment]
Agree.

**Comment by kisisjrlly** [comment]
> 
thanks for your reply, however when I upgraded to 8.6 according to your suggestion, a new error occurred again:
https://github.com/NVIDIA/TensorRT/issues/3155

**Comment by kisisjrlly** [comment]
> How about using the latest TRT8.6 version? And are you using in a container, if so, you can set a large `--shm-size`

TRT8.6 is ok，thanks！
