### ISSUE TITLE
how to install python after build from source and get trtexec?

### ISSUE THREAD

**Issue by dragen1860** [NVIDIA/TensorRT#3151]
Dear all
   I succed to build from source and get `trtexec` worked normally.  Currently I use Anaconda python environment and want call tensorrt from anaconda python interpreter. However, I found the python binding tutorial here:[https://github.com/NVIDIA/TensorRT/tree/release/8.6/python](https://github.com/NVIDIA/TensorRT/tree/release/8.6/python) is very complex and seemly not work for Anaconda. Does anyone can tell me how to install python binding after building? Thank you very much.

**Comment by zerollzeng** [comment]
You can use `pip3 install tensorrt`

**Comment by ttyio** [comment]
closing, thanks all!
