### ISSUE TITLE
diffusion demo failure of TensorRT 8.6.1 when running demo_txt2img.py on GPU A100 80G

### ISSUE THREAD

**Issue by kisisjrlly** [NVIDIA/TensorRT#3155]
Command I run:
CUDA_MODULE_LOADING=LAZY CUDA_VISIBLE_DEVICES=0  python3 demo_txt2img.py "a beautiful photograph of Mt. Fuji during cherry blossom" --build-dynamic-shape --onnx-opset=17 --build-preview-features

result:
<img width="687" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/34215214/cfb20363-591c-4096-937f-22536689388d">

Error is:
[E] 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)

I built the engine and deserialized it in one process, Why did such an error occur?

**Comment by Davinci52** [comment]
Hello, I have also encountered this problem now. How did you solve this problem
