### ISSUE TITLE
How can i study to write my tensorrt plugin code ?

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3156]
## Description

Hello, I want to learn how to write a plugin. I am looking for a tutorial that covers the basics of plugin creation, registration, and how to invoke it from both Python and C++ (preferably with examples of inserting the plugin node into an ONNX model and evaluating the results, or constructing the plugin using inv layers and performing inference). Can you recommend any good tutorials as references? 
Thank you very much.

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending is a good reference, also we public a tool https://github.com/NVIDIA-AI-IOT/tensorrt_plugin_generator that can generate the plugin code, then you can add the kernel implementation.

**Comment by sanbuphy** [comment]
> https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending is a good reference, also we public a tool https://github.com/NVIDIA-AI-IOT/tensorrt_plugin_generator that can generate the plugin code, then you can add the kernel implementation.

Thank you very much !  I will Try to take a look.
