### ISSUE TITLE
trtexec inference quant model failed  whith error QuantizeLayer/DequantizeLayer layers require hardware with Int8 support.

### ISSUE THREAD

**Issue by yank666** [NVIDIA/TensorRT#3157]
This is my quant model
![image](https://github.com/NVIDIA/TensorRT/assets/79586188/1eb78af0-ed2c-447f-b958-6dd03ce1cbb4)

when i exec command :
./trtexec --onnx=test9.onnx  --verbose  --saveEngine=test9.trt --int8
i got error 
[standardEngineBuilder.cpp::buildEngine::2072] Error Code 9: Internal Error (Networks with QuantizeLayer/DequantizeLayer layers require hardware with Int8 support.)
![image](https://github.com/NVIDIA/TensorRT/assets/79586188/31ee98a3-ef73-45ad-a01b-7d725c84399c)

my version:
trt version 8.6
cuda 12.0

**Comment by zerollzeng** [comment]
Which GPU you are using? Looks like it doesn't support INT8?

**Comment by yank666** [comment]
p100

**Comment by zerollzeng** [comment]
Pascal does not natively support INT8 computation. You need Turing+ GPU.
