### ISSUE TITLE
[bug][polygraphy] onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1,1,180}, requested shape:{1,1,16,180,16,180}

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3159]
## Description

I use Polygraphy for troubleshooting accuracy loss issues. However, during the troubleshooting process, I encountered the following problem with the execution:

```
2023-07-26 01:41:10.123188616 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/layers.0/residual_group/blocks.0/Reshape_2' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1,1,180}, requested shape:{1,1,16,180,16,180}

Traceback (most recent call last):
  File "/usr/local/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 37, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/comparator/comparator.py", line 132, in execute_runner
    outputs = active_runner.infer(feed_dict=feed_dict)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/runner.py", line 177, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/onnxrt/runner.py", line 73, in infer_impl
    inference_outputs = self.sess.run(None, feed_dict)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/layers.0/residual_group/blocks.0/Reshape_2' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1,1,180}, requested shape:{1,1,16,180,16,180}
```

But when I run onnxruntime separately, it can run normally.
![image](https://github.com/NVIDIA/TensorRT/assets/96160062/b5d8b5e9-ad4d-4765-8b06-cfa07ec07e48)

## Environment

**TensorRT Version**: 
nvcr.io/nvidia/tensorrt   23.04-py3  NGC
**NVIDIA GPU**: 3060

**NVIDIA Driver Version**:
nvcr.io/nvidia/tensorrt   23.04-py3  NGC
**CUDA Version**:
nvcr.io/nvidia/tensorrt   23.04-py3  NGC
**CUDNN Version**:
nvcr.io/nvidia/tensorrt   23.04-py3  NGC

Operating System:
nvcr.io/nvidia/tensorrt   23.04-py3  NGC
Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

**Comment by zerollzeng** [comment]
Can you also share you polygraphy command? Did you set the input shapes?

**Comment by sanbuphy** [comment]
> Can you also share you polygraphy command? Did you set the input shapes?

yes:
```bash
polygraphy run dynamic_graph.onnx \
    --onnxrt --trt \
    --save-engine=model_FP16.plan \
    --atol 1e-3 --rtol 1e-3 \
    --fp16 \
    --verbose \
    --trt-min-shapes 'input:[1,3,400,400]' \
    --trt-opt-shapes 'input:[1,3,400,400]' \
    --trt-max-shapes 'input:[1,3,400,400]' \
    --input-shapes 'input:[1,3,400,400]' \
    > result-run-FP16.txt

```

**Comment by zerollzeng** [comment]
> ```
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/layers.0/residual_group/blocks.0/Reshape_2' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1,1,180}, requested shape:{1,1,16,180,16,180}
> ```

The error is comes from onnxruntime but not TRT, it complains about mismatch reshape shapes. Can you run it with
```
polygraphy run dynamic_graph.onnx \
    --onnxrt --trt \
    --save-engine=model_FP16.plan \
    --atol 1e-3 --rtol 1e-3 \
    --fp16 \
    --verbose \
    --trt-min-shapes 'input:[1,3,400,400]' \
    --trt-opt-shapes 'input:[1,3,400,400]' \
    --trt-max-shapes 'input:[1,3,400,400]' \
    --input-shapes 'input:[1,3,400,400]' \
    > result-run-FP16.txt
```
to comfirm?

**Comment by sanbuphy** [comment]
> > ```
> > onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/layers.0/residual_group/blocks.0/Reshape_2' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1,1,180}, requested shape:{1,1,16,180,16,180}
> > ```
> 
> The error is comes from onnxruntime but not TRT, it complains about mismatch reshape shapes. Can you run it with
> 
> ```
> polygraphy run dynamic_graph.onnx \
>     --onnxrt \
>     --verbose \
>     --input-shapes 'input:[1,3,400,400]' \
>     > result-run-FP16.txt
> ```
> 
> to comfirm?

It's some problem with my param (we need use some specied shape to input ) , I got it.
