### ISSUE TITLE
When I set the op precision to fp16, does it mean the output? 

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3171]
## Description

Hello, I have successfully used the method of layer.precision to set the precision of the layer. However, I am curious whether this setting applies to the weights only, or it also affects the output values and computation process. If the precision is restored to 32 while the rest of the computation remains at 16 bits, will the output of this layer mismatch with the required input precision of the next layer? Thank you.

**Comment by zerollzeng** [comment]
> If the precision is restored to 32 while the rest of the computation remains at 16 bits, will the output of this layer mismatch with the required input precision of the next layer?

If what you mean is the precision of the weights is FP32 while the layer compute precision is FP16, then TRT will convert the FP32 weights to FP16, so the output precision is FP16 or the output precision you set(may add extra reformat)
