### ISSUE TITLE
Could tensorrt use bfloat16 infer?

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3174]
As the title saying. Thank you very much

**Comment by zerollzeng** [comment]
I think it will be supported in the next release since it's popular now, @ttyio please correct me if I'm wrong.

**Comment by styler00dollar** [comment]
I am really looking forward to this feature, since transformers tend to not work with fp16, but work with bf16. For now I am using fp32 to have stuff working.

**Comment by ttyio** [comment]
the EA access can be requested from https://developer.nvidia.com/tensorrt-llm-early-access. closing and thanks all!
