### ISSUE TITLE
It should be a mistake in the official documentation

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3178]
## Description

Hi , I am reading the official c++ api documentation:
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#c_topics
but i find:
```
[3.1.2. Importing a Model Using the ONNX Parser](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#import_onnx_c)
Now, the network definition must be populated from the ONNX representation. The ONNX parser API is in the file NvOnnxParser.h, and the parser is in the nvonnxparser C++ namespace.
#include “NvOnnxParser.h”

using namespace nvonnxparser;
You can create an ONNX parser to populate the network as follows:
IParser* parser = createParser(*network, logger);
Then, read the model file and process any errors.
parser->parseFromFile(modelFile, 
    static_cast<int32_t>(ILogger::Severity::kWARNING));
for (int32_t i = 0; i < parser.getNbErrors(); ++i)
{
std::cout << parser->getError(i)->desc() << std::endl;
}
An important aspect of a TensorRT network definition is that it contains pointers to model weights, which are copied into the optimized engine by the builder. Since the network was created using the parser, the parser owns the memory occupied by the weights, and so the parser object should not be deleted until after the builder has run.
```

```
parser->parseFromFile(modelFile, 
    static_cast<int32_t>(ILogger::Severity::kWARNING));
for (int32_t i = 0; i < parser.getNbErrors(); ++i)
{
```

should we use parser->getNbErrors()?  parser is a point which type is IParser* .

In addition, is there any way(complete example) that can learn  how to parse a onnx model to tensorrt engine? (c++ api),Thank you very much.

**Comment by zerollzeng** [comment]
> for (int32_t i = 0; i < parser.getNbErrors(); ++i)

Yes, I will report and fix this.

**Comment by zerollzeng** [comment]
> In addition, is there any way(complete example) that can learn how to parse a onnx model to tensorrt engine? (c++ api),Thank you very much.

check trtexec as a reference, it's under samples/

**Comment by sanbuphy** [comment]
> check trtexec as a reference, it's under samples/

**Comment by sanbuphy** [comment]
> > In addition, is there any way(complete example) that can learn how to parse a onnx model to tensorrt engine? (c++ api),Thank you very much.
> 
> check trtexec as a reference, it's under samples/

IT use :
```
nvonnxparser::IParser* createONNXParser(INetworkDefinition& network)
{
    if (!initNvonnxparser())
    {
        return {};
    }
    ASSERT(pCreateNvOnnxParserInternal != nullptr);
    return static_cast<nvonnxparser::IParser*>(
        pCreateNvOnnxParserInternal(&network, &gLogger.getTRTLogger(), NV_ONNX_PARSER_VERSION));
}

```

```
bool initNvonnxparser()
{
#if !TRT_STATIC
    static LibraryPtr libnvonnxparserPtr{};
    auto fetchPtrs = [](DynamicLibrary* l) {
        pCreateNvOnnxParserInternal = l->symbolAddress<void*(void*, void*, int)>("createNvOnnxParser_INTERNAL");
    };
    return initLibrary(libnvonnxparserPtr, kNVONNXPARSER_LIBNAME, fetchPtrs);
#else
    pCreateNvOnnxParserInternal = createNvOnnxParser_INTERNAL;
    return true;
#endif // !TRT_STATIC
}

```
 
But I don't know what is the  `"createNvOnnxParser_INTERNAL"` ....

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tiny-tensorrt/blob/7dfb55834868b626a660c27249fa324bb184d045/src/Trt.cpp#L231

This is a a bit out-dated, but you can take as a reference.

**Comment by sanbuphy** [comment]
> https://github.com/zerollzeng/tiny-tensorrt/blob/7dfb55834868b626a660c27249fa324bb184d045/src/Trt.cpp#L231
> 
> This is a a bit out-dated, but you can take as a reference.
> 
> 这个有点过时了，但是你可以作为参考。关闭

Thanks, I am indeed copying your code lol
