### ISSUE TITLE
Performance T4 VS 2080Ti

### ISSUE THREAD

**Issue by cmstudyscode** [NVIDIA/TensorRT#3179]
## Description

 I tried to deploy ASR model based transformer on T4 and 2080Ti. But I foud the performace on T4 is much lower than 2080TI, even T4 has a more brilliant CPU than 2080Ti.
- model：transformer
- datatype：mix precision（layernorm fp32，other ops computed by fp16）
- command：trtexec --loadEngine=tensorRT_fp16.engine --shapes=input:1x1000x80 --iterations=100

| GPU |  qps |
|----|----|
|2080Ti | 183 | 
|T4| 98 | 

![image](https://github.com/NVIDIA/TensorRT/assets/43026059/c93eb2e4-1790-4ac1-abda-e0ab20ea5288)

![image](https://github.com/NVIDIA/TensorRT/assets/43026059/e6ee8ef5-a5dc-49da-915c-fbadbeda3c3d)

## Environment

**TensorRT Version**:8.5.0

**NVIDIA GPU**: 2080Ti VS Tesla T4

**CPU Version**: Gold 6230CPU @ 2.10GHz(2080Ti)，Gold 6424R CPU@2.10GHz(T4)

**CUDA Version**: 11.8

**Comment by cmstudyscode** [comment]
I have tried trt version 8.5.0, 8.5.1 and 8.6.0, same  performance regression.

**Comment by cmstudyscode** [comment]
@zerollzeng @pranavm-nvidia

**Comment by zerollzeng** [comment]
Agree.
