### ISSUE TITLE
Result incorrect issue on TensorRT 8.6.1.6-1+cuda12.0 when running Huggingface Roberta Model on GPU T4

### ISSUE THREAD

**Issue by bugzyz** [NVIDIA/TensorRT#3180]
## Description

Hi there, I was trying to optimized the huggingface Roberta model to gain latency improvement on tensorRT. But I found that the result from tensorRT is very different from the original Pytorch one. Plus, I tried the onnxruntime inference on lower version of pytorch NCG image, the result looks very similar to the original Pytorch one as expected. So I believe there may be some misconfiguration on tensorRT from our side. Could you provide some suggestion on using tensorRT to get reasonable result? Thanks!

**Details:**
I tested with torch.allclose to compare the result between tensorRT and pytorch.
For onnxruntime implementation, the result is **true** on rtol=1e-03, atol=1e-05
But for tensorRT implementation, the result is **false** on rtol=1e-03, atol=1e-05. The result is not even closed to the original pytorch one

## Environment

**GPU:** T4

**image:** nvcr.io/nvidia/pytorch:23.07-py3

**TensorRT & cuda version:**
dpkg -l | grep nvinfer && nvcc -V
ii  libnvinfer-bin                  8.6.1.6-1+cuda12.0                         amd64        TensorRT binaries
ii  libnvinfer-dev                  8.6.1.6-1+cuda12.0                         amd64        TensorRT development libraries
ii  libnvinfer-dispatch-dev         8.6.1.6-1+cuda12.0                         amd64        TensorRT development dispatch runtime libraries
ii  libnvinfer-dispatch8            8.6.1.6-1+cuda12.0                         amd64        TensorRT dispatch runtime library
ii  libnvinfer-headers-dev          8.6.1.6-1+cuda12.0                         amd64        TensorRT development headers
ii  libnvinfer-headers-plugin-dev   8.6.1.6-1+cuda12.0                         amd64        TensorRT plugin headers
ii  libnvinfer-lean-dev             8.6.1.6-1+cuda12.0                         amd64        TensorRT lean runtime libraries
ii  libnvinfer-lean8                8.6.1.6-1+cuda12.0                         amd64        TensorRT lean runtime library
ii  libnvinfer-plugin-dev           8.6.1.6-1+cuda12.0                         amd64        TensorRT plugin libraries
ii  libnvinfer-plugin8              8.6.1.6-1+cuda12.0                         amd64        TensorRT plugin libraries
ii  libnvinfer-vc-plugin-dev        8.6.1.6-1+cuda12.0                         amd64        TensorRT vc-plugin library
ii  libnvinfer-vc-plugin8           8.6.1.6-1+cuda12.0                         amd64        TensorRT vc-plugin library
ii  libnvinfer8                     8.6.1.6-1+cuda12.0                         amd64        TensorRT runtime libraries

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.1

**Operating System:**

Python Version (if applicable): 
`3.10.6`

Package may help:
```
transformers              4.31.0
onnx                      1.12.0
onnxruntime-gpu           1.14.1
torch                     2.1.0a0+b5021ba
```

## Relevant Files

**Model link**: [robert-base](https://huggingface.co/roberta-base)

## Steps To Reproduce

You can used the provided script below to reproduce my test result by using:
`python two_steps_convert.py`

This script contains:
1. export to onnx
2. convert to tensorRT
3. benchmark on onnx (Currently, I disable this since there're some incompatible issue. But this part of code is workable on nvcr.io/nvidia/pytorch:22.03-py3)
4. benchmark on tensorRT

**Commands or scripts**:
```
import logging
import pdb

from transformers.modeling_outputs import BaseModelOutputWithPoolingAndCrossAttentions

logging.basicConfig(level=logging.INFO)

import onnxruntime
import torch
import tensorrt
import sys
from functools import wraps
from time import time

device = torch.device("cuda")
import logging
import torch
import torch.nn as nn

loop = 1000

# Load model directly
from transformers import AutoTokenizer, RobertaModel

tokenizer = AutoTokenizer.from_pretrained("roberta-base")
roberta_model = RobertaModel.from_pretrained("roberta-base")
roberta_model.eval()


def get_input(data):
    inputs = tokenizer(data, return_tensors="pt")
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    return input_ids, attention_mask


def export_to_onnx():
    input_ids, attention_mask = get_input(get_test_cases()[0])

    torch.onnx.export(
        roberta_model.cpu(),  # model being run
        (input_ids.cpu(), attention_mask.cpu()),  # model input (or a tuple for multiple inputs)
        "roberta_opset_18.onnx",  # where to save the model (can be a file or file-like object)
        export_params=True,  # store the trained parameter weights inside the model file
        opset_version=13,  # the ONNX version to export the model to
        do_constant_folding=True,  # whether to execute constant folding for optimization
        input_names=['input_ids',  # filled
                     'attention_mask',  # filled
                     # 'token_type_ids',
                     # 'position_ids',
                     # 'head_mask',
                     # 'inputs_embeds',
                     # 'output_attentions',
                     # 'output_hidden_states',
                     ],
        output_names=['last_hidden_state',  # returned
                      'pooler_output',  # returned
                      # 'hidden_states',
                      # 'past_key_values',
                      # 'attentions',
                      # 'cross_attentions',
                      ],
        dynamic_axes={
            'input_ids': {0: 'batch_size', 1: 'seq_length'},  # variable length axes
            'attention_mask': {0: 'batch_size', 1: 'seq_length'},
            'last_hidden_state': {0: 'batch_size', 1: 'seq_length'},
            'pooler_output': {0: 'batch_size'},
        },
    )

    logging.info("onnx exported")


def export_to_trt():
    cmd = "trtexec --onnx=./roberta_opset_18.onnx --saveEngine=./roberta_opset_18.trt \
    --noTF32 \
    --minShapes=input_ids:1x5,attention_mask:1x5 \
    --optShapes=input_ids:1x20,attention_mask:1x20 \
    --maxShapes=input_ids:2x32,attention_mask:2x32 --workspace=8192 --shapes=input_ids:2x32,attention_mask:2x32 --verbose --exportLayerInfo=x.json --profilingVerbosity=detailed"

    import subprocess
    # Execute the command
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

    # Check the command execution status
    if result.returncode == 0:
        # Command executed successfully
        output = result.stdout
        logging.info("Command output:")
        logging.info(output)
        logging.info("tensorrt exported")
    else:
        # Command execution failed
        error = result.stderr
        logging.error("Command execution failed with error:")
        logging.error(error)
        exit(5)


class OnnxModelGPU(nn.Module):
    def __init__(self, model_file_path):
        super().__init__()
        self.ort_sess = onnxruntime.InferenceSession(model_file_path, providers=["CUDAExecutionProvider"])
        self.io_binding = self.ort_sess.io_binding()

    def forward(self, local_input_ids: torch.Tensor, local_attention_mask: torch.Tensor):
        input_ids = local_input_ids.cpu()
        attention_mask = local_attention_mask.cpu()
        last_hidden_state = torch.zeros((input_ids.size(dim=0), input_ids.size(dim=1), 768), dtype=torch.float32).cpu()
        pooler_output = torch.zeros((input_ids.size(dim=0), 768), dtype=torch.float32).cpu()

        input_ids_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(input_ids.numpy(), 'cuda', 0)
        attention_mask_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(attention_mask.numpy(), 'cuda', 0)
        last_hidden_state_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(last_hidden_state.numpy(), 'cuda', 0)
        pooler_output_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(pooler_output.numpy(), 'cuda', 0)

        self.io_binding = self.ort_sess.io_binding()
        self.io_binding.bind_ortvalue_input('input_ids', input_ids_ortvalue)
        self.io_binding.bind_ortvalue_input('attention_mask', attention_mask_ortvalue)
        self.io_binding.bind_ortvalue_output('last_hidden_state', last_hidden_state_ortvalue)
        self.io_binding.bind_ortvalue_output('pooler_output', pooler_output_ortvalue)

        self.ort_sess.run_with_iobinding(self.io_binding)
        res = self.io_binding.get_outputs()
        last_hidden_state_ortvalue = res[0]
        pooler_output_ortvalue = res[1]
        return BaseModelOutputWithPoolingAndCrossAttentions(
            last_hidden_state=torch.from_numpy(last_hidden_state_ortvalue.numpy()),
            pooler_output=torch.from_numpy(pooler_output_ortvalue.numpy()),
            # past_key_values=encoder_outputs.past_key_values,
            # hidden_states=encoder_outputs.hidden_states,
            # attentions=encoder_outputs.attentions,
            # cross_attentions=encoder_outputs.cross_attentions,
        )


class TensorrtModelV3(nn.Module):
    def __init__(self, model_file_path):
        super().__init__()
        tensorrt_logger = tensorrt.Logger()
        tensorrt_logger.min_severity = tensorrt.Logger.VERBOSE

        with open(model_file_path, "rb") as f:
            self.tensorrt_runtime = tensorrt.Runtime(tensorrt_logger)
            self.tensorrt_engine = self.tensorrt_runtime.deserialize_cuda_engine(f.read())
            self.tensorrt_context = self.tensorrt_engine.create_execution_context()

    def forward(self, local_input_ids: torch.Tensor, local_attention_mask: torch.Tensor):
        input_ids = local_input_ids.to(device)
        attention_mask = local_attention_mask.to(device)
        last_hidden_state = torch.zeros((input_ids.size(dim=0), input_ids.size(dim=1), 768), dtype=torch.float32).to(
            device)
        pooler_output = torch.zeros((input_ids.size(dim=0), 768), dtype=torch.float32).to(device)

        self.bindings = [None] * self.tensorrt_engine.num_bindings

        input_idx = self.tensorrt_engine.get_binding_index('input_ids')
        self.tensorrt_context.set_input_shape('input_ids', tensorrt.tensorrt.Dims(input_ids.shape))
        self.bindings[input_idx] = input_ids.data_ptr()

        input_idx = self.tensorrt_engine.get_binding_index('attention_mask')
        self.tensorrt_context.set_input_shape('attention_mask', tensorrt.tensorrt.Dims(attention_mask.shape))
        self.bindings[input_idx] = attention_mask.data_ptr()

        output_idx = self.tensorrt_engine.get_binding_index('last_hidden_state')
        self.bindings[output_idx] = last_hidden_state.data_ptr()

        output_idx = self.tensorrt_engine.get_binding_index('pooler_output')
        self.bindings[output_idx] = pooler_output.data_ptr()

        self.tensorrt_context.execute_async_v2(self.bindings,
                                               torch.cuda.current_stream().cuda_stream)
        torch.cuda.current_stream().synchronize()

        return BaseModelOutputWithPoolingAndCrossAttentions(
            last_hidden_state=last_hidden_state,
            pooler_output=pooler_output,
        )


def get_test_cases():
    return ["Hi, there! This is superman speaking",]


def timeit(f):
    @wraps(f)
    def wrap(*args, **kw):
        ts = time()
        result = f(*args, **kw)
        te = time()

        sys.stdout.flush()
        logging.info(f'func:{f.__qualname__} took: {te - ts} sec')
        sys.stdout.flush()
        return result

    return wrap


def benchmark(use_tensorrt=True):
    with torch.no_grad():
        base_model = roberta_model.to(device)
        if use_tensorrt:
            aiml_model = TensorrtModelV3("roberta_opset_18.trt")
        else:
            aiml_model = OnnxModelGPU("roberta_opset_18.onnx")

        input_ids, attention_mask = get_input(get_test_cases()[0])
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)

        # warmup
        aiml_model(input_ids, attention_mask)
        base_model(input_ids, attention_mask)

        # benchmarking
        for text in get_test_cases():
            logging.info(f"========= benchmark() - text: {text}, loop: {loop} =========")

            input_ids, attention_mask = get_input(text)
            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)

            base_outputs = base_model(input_ids, attention_mask)
            aiml_outputs = aiml_model(input_ids, attention_mask)


            base_last_hidden_state, base_pooler_output = base_outputs['last_hidden_state'], base_outputs['pooler_output']
            aiml_last_hidden_state, aiml_pooler_output = aiml_outputs['last_hidden_state'], aiml_outputs['pooler_output']
            print(f"base_pooler_output: {base_pooler_output}")
            print(f"aiml_pooler_output: {aiml_pooler_output}")

            logging.info(f"last_hidden_state: rtol=1e-03, atol=1e-05: {torch.allclose(aiml_last_hidden_state.cuda(), base_last_hidden_state.cuda(), rtol=1e-03, atol=1e-05)}")
            logging.info(f"pooler_output: rtol=1e-03, atol=1e-05: {torch.allclose(aiml_pooler_output.cuda(), base_pooler_output.cuda(), rtol=1e-03, atol=1e-05)}")


if __name__ == '__main__':
    export_to_onnx()

    export_to_trt()

    # logging.info("testing onnx")
    # benchmark(use_tensorrt=False)

    logging.info("testing tensorrt")
    benchmark(use_tensorrt=True)



```

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: I'm using the latest pytorch NGC image - nvcr.io/nvidia/pytorch:23.07-py3

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):
Yes. Onnxruntime related inference looks good on image: nvcr.io/nvidia/pytorch:22.03-py3 . The related code is also included in the script provided above.

**Comment by zerollzeng** [comment]
Hi I'm on vacation this week with very limited network access, I would appreciate if you can  upload the onnx model to Google Drive and share a link here.

FYI normally I would check it with polygraphy first, you can also do this step on your own, you will see the diff analysis.
see https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/run/01_comparing_frameworks

**Comment by bugzyz** [comment]
@zerollzeng Thanks for the advice! I tried with the `polygraphy run ` to compare between the original onnx and the converted tensorrt engine and the result shows that the results are pretty closed (--atol 0.001 --rtol 0.001). And I also tried the polygraphy.backend.trt.TrtRunner, it can produce correct result compared with pytorch. 

So, I think, maybe I didn't implement my TensorrtModelV3 properly? Any further advice?

**Comment by zerollzeng** [comment]
> Thanks for the advice! I tried with the `polygraphy run ` to compare between the original onnx and the converted tensorrt engine and the result shows that the results are pretty closed (--atol 0.001 --rtol 0.001). And I also tried the polygraphy.backend.trt.TrtRunner, it can produce correct result compared with pytorch.

It means the onnx and TRT engine is good, so the problem might happens when you export the onnx or bugs in your inference code.

**Comment by bugzyz** [comment]
@zerollzeng  Thanks. Yeah, I can confirm that onnx result is same as the pytorch one. So I believe I didn't implement the inference code properly. Could you please take a look at the script I shared in the description previously and give us some advice on the implementation? Thanks!

**Comment by DayDayupupupup** [comment]
Is there any progress？ I had a similar problem with Trt 23.07. 
When use `polygraphy run`, the result shows `Difference is within tolerance (rel=0.001, abs=0.001)`
But use my script(trt infer part is basically the same as @bugzyz ), the difference is a little bit big 😂

**Comment by bugzyz** [comment]
Hi @zerollzeng . We were trying to understand the implementation difference between polygraphy api and our code. But still no idea about the root cause. As there is similar issue reported by other user, could you provide any thought or suggestion on this issue?

**Comment by DayDayupupupup** [comment]
@bugzyz @zerollzeng The problem is with my **build engine script**, not the infer script, both use trt python api.

I saved the **engine generated by polygraphy** like the following command,  use my **infer script** to verify the results,  and difference is within tolerance (rel=1e-4, abs=1e-4)
`polygraphy run model.onnx --onnxrt --trt --atol 1e-4 --rtol 1e-4 --pool-limit workspace:10G --providers CUDAExecutionProvider --save-engine model.plan`
and there is an info during `polygraphy run`
```
[I] Building engine with configuration:
    Flags                  | []
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 10240.00 MiB, TACTIC_DRAM: 24068.25 MiB]
    Tactic Sources         | [CUBLAS, CUBLAS_LT, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
```

Then i use polygraph's trt_util.str_from_config() to print trt.BuilderConfig in my **build engine script**:
```
Flags                  | [TF32]
Engine Capability      | EngineCapability.DEFAULT
Memory Pools           | [WORKSPACE: 24576.00 MiB, TACTIC_DRAM: 24068.25 MiB]
Tactic Sources         | [CUBLAS, CUBLAS_LT, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
Profiling Verbosity    | ProfilingVerbosity.DETAILED
Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
```

I found the difference was TF32. When I disable tf32 in **build engine script**, `config.clear_flag(trt.BuilderFlag.TF32)` the difference is also within tolerance (rel=1e-4, abs=1e-4).

In my case, **build engine script** is equal to  `trtexec --onnx=model.onnx --saveEngine=model.plan --noTF32`.

**Comment by bugzyz** [comment]
Hi both, my problem is solved now. It's because tensorrt only support int32 and the input I tried to infer is int64. After converting to int32, the result is pretty closed to pytorch one. 

Thanks. Closing the issue.

**Comment by DayDayupupupup** [comment]
@bugzyz When I use `--noTF32`, trt engine's infer speed  is slower than TFserving(TF-ONNX-TRT).  
Have you compared the infer speed of pytorch and trt（no tf32）？
In addition, my model needs dynamic shapes. When I turn off `FASTER_DYNAMIC_SHAPES_0805` and turn on `TF32`,  which can ensure that the trt result is close to TF.

One more question, have you tried to use `--fp16`,  infer error after using fp16 is very big for roberta.
