### ISSUE TITLE
Does TensorRT support LLAMA2 deployment？If yes, is there any conversion example?

### ISSUE THREAD

**Issue by dongjinxin123** [NVIDIA/TensorRT#3188]
## Environment

**TensorRT Version**:

**NVIDIA GPU**:

**NVIDIA Driver Version**:

**CUDA Version**:

**CUDNN Version**:

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by phamkhactu** [comment]
Hi @dongjinxin123 

Have you any information?

**Comment by dongjinxin123** [comment]
> 

No I don't.

**Comment by zerollzeng** [comment]
I'll let @nvpohanh to answer this question ^ ^

**Comment by nvpohanh** [comment]
We are working on this but it is not complete yet.

**Comment by dongjinxin123** [comment]
@nvpohanh Thanks for your reply. Do you have any timeline for it?

**Comment by ttyio** [comment]
closing since this is solved, thanks all!
