### ISSUE TITLE
explicit Int8 is slower than fp16

### ISSUE THREAD

**Issue by Nusselder9** [NVIDIA/TensorRT#3197]
The fp16 model is as below:
 
![image](https://github.com/NVIDIA/TensorRT/assets/71872790/be6d791f-7104-4936-b5bd-952840a25ae4)

After using pytorch-quantization, Q and DQ are inserted before all conv nodes, and the explicit quantization int8 onxx is as below:

![image](https://github.com/NVIDIA/TensorRT/assets/71872790/8c9ee9a3-a4a3-4445-b72b-a1852e3e5d9a)

I use trtexec to compare speed between fp16 and explicit int8. Explicit int8 (about 4 ms) is slower than fp16 (about 2ms).

Then I use [trt-engine-explorer](https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/experimental/trt-engine-explorer) to draw the engine.

The explicit int8 engine is as below:
![image](https://github.com/NVIDIA/TensorRT/assets/71872790/1ce1a084-eaf5-4614-abed-aa9b49fcad17)

it seems that although Q and DQ are inserted before conv, all conv is still fp32-in-fp32-out. How can I solve it?

**Comment by qinyage** [comment]
hello，i meet the same question with you , did you solve it?
