### ISSUE TITLE
Inconsistent documentation on max_workspace_size

### ISSUE THREAD

**Issue by gcp** [NVIDIA/TensorRT#320]
## Description

According to the TensorRT documentation: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#build_engine_python
you have to set the max_workspace_size on the ```builder``` object.

However, empirically, when using ONNX networks, I see in the verbose TensorRT logging that strategies aren't tried because there is 0 workspace available. Despite it being set to 2**31.

Now, if you look at other TensorRT docs: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Core/NetworkConfig.html

You see that there's a "new" max_workspace_size on the config object of the builder. 

Empirically, setting that one *does* work. The documentation seems inconsistent and wrong here. It's somewhat likely people are going to get performance regressions with TensorRT 7 because they're accidentally building engines with no workspace?

## Environment

**TensorRT Version**:  7.0.0.11
**GPU Type**:  GTX 1060
**Nvidia Driver Version**:  440.36
**CUDA Version**:  10.2
**CUDNN Version**:  7.6.0.3
**Operating System + Version**:  Ubuntu 18.04
**Python Version (if applicable)**:  3.6
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**:  1.3 stable
**Baremetal or Container (if container which image + tag)**:  bare

## Relevant Files

https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#build_engine_python
https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Core/NetworkConfig.html

**Comment by rmccorm4** [comment]
Hi @gcp,

I believe these combinations are valid:
* Set attributes on `builder` object (`builder.max_workspace_size`) and use `build_cuda_engine(network)`
* Set attributes on `builder_config` object (`builder_config.max_workspace_size`) and use `build_engine(network, builder_config)`

I think if you mix/match those two, then it will not work as expected, though not 100% sure. I agree the documentation could probably use some tweaks. If you could propose some specific changes you'd like to see, that would be helpful to me 🙂

**Comment by gcp** [comment]
>https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#build_engine_python

I would change this to use ```builder_config``` and ```build_engine```, instead of ```build_cuda_engine```, which is consistent with the C++ version. It looks like that's the direction you want to go API-wise anyway?

**Comment by rmccorm4** [comment]
I put in these suggestions to the documentation folks, thanks @gcp
