### ISSUE TITLE
TensorRT 8.6 allocates on device 0 after changing device with `cudaSetDevice`

### ISSUE THREAD

**Issue by gerwin3** [NVIDIA/TensorRT#3201]
## Description

When trying to get TensorRT to bind to a different device, I used the method described here:

https://github.com/NVIDIA/TensorRT/issues/1050

i.e., using `cudaSetDevice` before calling any TensorRT API functions.

TensorRT will utilize the selected device, but still allocate around 158MiB on GPU 0 (or the default GPU) regardless. Note that for some reason `trtexec` with `--device 1` **does** work (so there must be a way to do it).

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: 4x RTX A4000

**NVIDIA Driver Version**: 530.30.02

**CUDA Version**: 12.1

**CUDNN Version**: 8.9.1.23

Operating System: Ubuntu Server 22.04

Baremetal or Container (if so, version): baremetal

**Comment by zerollzeng** [comment]
> but still allocate around 158MiB on GPU 0

This is not expected, can it be the display service like xorg?

What does nvidia-smi show?

**Comment by gerwin3** [comment]
You're right. I used Nsight to trace the cause and found that it was an issue with some NPPI code elsewhere. Removing that fixed it.
