### ISSUE TITLE
"On the Windows platform, the dynamic libraries generated from compiling TensorRT from source have missing dependencies."

### ISSUE THREAD

**Issue by lizexu-nreal** [NVIDIA/TensorRT#3214]
![image](https://github.com/NVIDIA/TensorRT/assets/134259938/b1ce5f6c-f6b6-4ddb-99ac-e8c4602fd165)
"This diagram represents the linkage items of the dynamic libraries provided by TensorRT-8.6GA."
![image](https://github.com/NVIDIA/TensorRT/assets/134259938/a9a0ab46-e6bc-4356-b880-9f1f04eab51e)
This is the linkage of the dynamic libraries I generated for TensorRT-8.6.1 version

**Comment by zerollzeng** [comment]
@oxana-nvidia Can you kindly help here ^ ^ I know nothing about Windows...

**Comment by lizexu-nreal** [comment]
I am currently using TensorRT for the master branch and using Visual Studio 2017 on Windows, following the 
 cmake .. `
>> -G "Visual Studio 15 2017 Win64" `
>> -DTRT_LIB_DIR="D:/TensorRT-8.2.0.6/lib" `
>> -DTRT_OUT_DIR="$(Get-Location)\out" `
>> -DCMAKE_CUDA_COMPILER="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/bin/nvcc.exe" `
>> -DCUBLASLT_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cublasLt.lib" `
>> -DCUBLAS_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cublas.lib" `
>> -DCUDART_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cudart.lib" `
>> -DCUDNN_LIB="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/lib/x64/cudnn.lib" `
>> -DCMAKE_CXX_FLAGS="/WX-"
the command，then   msbuild ALL_BUILD.vcxproj  but D:\TensorRT-master\build\third_party.protobuf\include\google/protobuf/repeated_ptr_field.h(752): error C2220: 警告被视为错误 -
 没有生成“object”文件 (编译源文件 D:\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx\onnx-data_onnx2trt_onnx.pb.cc) [D:\T
ensorRT-master\build\parsers\onnx\third_party\onnx\onnx_proto.vcxproj]  
我搜遍了全网，目前还未找到解决方案，恳切希望解决
I have searched the entire network and have not found a solution yet. I sincerely hope for a solution。If possible, I have only made some changes to the master branch of TensorRT, such as replacing. a with. lib in protbuf.cmake and turning off add_ The custom (caffe) branch has not made much changes to the rest

**Comment by lizexu-nreal** [comment]
![image](https://github.com/NVIDIA/TensorRT/assets/134259938/32515cf3-3ef0-410f-b3d6-e91ecfcbf8f5)
“D:\TensorRT-master\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“D:\TensorRT-master\build\parsers\onnx\getSupportedAPITest.vcxproj”(默认目标) (4) ->
“D:\TensorRT-master\build\parsers\onnx\nvonnxparser_static.vcxproj”(默认目标) (5) ->
“D:\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx_proto.vcxproj”(默认目标) (6) ->
(ClCompile 目标) ->
  D:\TensorRT-master\build\third_party.protobuf\include\google/protobuf/repeated_ptr_field.h(752): error C2220: 警告被视为错误
 - 没有生成“object”文件 (编译源文件 D:\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx\onnx-data_onnx2trt_onnx.pb.cc) [D:
\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx_proto.vcxproj]
  D:\TensorRT-master\build\third_party.protobuf\include\google/protobuf/repeated_ptr_field.h(752): error C2220: 警告被视为错误
 - 没有生成“object”文件 (编译源文件 D:\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx\onnx-operators_onnx2trt_onnx-ml.pb
.cc) [D:\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx_proto.vcxproj]
  D:\TensorRT-master\build\third_party.protobuf\include\google/protobuf/repeated_ptr_field.h(752): error C2220: 警告被视为错误
 - 没有生成“object”文件 (编译源文件 D:\TensorRT-master\build\parsers\onnx\third_party\onnx\onnx\onnx_onnx2trt_onnx-ml.pb.cc) [D:\T
ensorRT-master\build\parsers\onnx\third_party\onnx\onnx_proto.vcxproj]

**Comment by ttyio** [comment]
Sorry we have no official windows build support yet, closing since this is inactive for more than 3 weeks.
