### ISSUE TITLE
CgPersistentLSTMPlugin not available in opensource repo

### ISSUE THREAD

**Issue by rjknight** [NVIDIA/TensorRT#323]
## Description
While testing out [this code ](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#persistent-lstm-plugin) code from the users guide I encountered the following error:

[E] [TRT] INVALID_ARGUMENT: getPluginCreator could not find plugin CgPersistentLSTMPlugin_TRT version 1

## Environment
ppc64le container 

**TensorRT Version**: 7.0.0.11 
**GPU Type**: T4
**Nvidia Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 7.6
**Operating System + Version**: RHEL7.6 
**Python Version (if applicable)**: py36
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce
compile this repo and check the contents of libnvinfer_plugin.so, the plugin does not exist in the generated lib

However, I took a look at the libnvinfer_plugin.so shipped in the TensorRT.7.0.0.11 tarfile and it does include the plugin:
```
(base) [xxxx<myhost.x.y.z>/lib]$ objdump -TC  libnvinfer_plugin.so  | grep CgPersistentLSTMPlugin
00000000000804d0 g    DF .text	00000000000001e5  Base        nvinfer1::plugin::CgPersistentLSTMPlugin::initialize()
000000000005f0c0 g    DF .text	00000000000001ba  Base        nvinfer1::plugin::CgPersistentLSTMPlugin::clone() const
000000000005eba0 g    DF .text	0000000000000060  Base        nvinfer1::plugin::CgPersistentLSTMPlugin::getWorkspaceSize(int) const
000000000005fa00 g    DF .text	00000000000001d8  Base        nvinfer1::plugin::CgPersistentLSTMPluginCreator::createPlugin(char const*, nvinfer1::PluginFieldCollection const*)
000000000005fbe0 g    DF .text	0000000000000261  Base        nvinfer1::plugin::CgPersistentLSTMPluginCreator::CgPersistentLSTMPluginCreator()
000000000007f1c0 g    DF .text	0000000000001308  Base        nvinfer1::plugin::CgPersistentLSTMPlugin::_createCubin()
00000000000806c0 g    DF .text	000000000000001a  Base        nvinfer1::plugin::CgPersistentLSTMPlugin::destroy()
```
Can we get the source for that plugin added to the repo?

**Comment by rmccorm4** [comment]
Hi @rjknight,

Does that code sample work if you **don't** build the OSS components, and just use the TRT 7 release as is?

**Comment by rjknight** [comment]
Yes, the plugin seems to work if I use the TRT-7 release as is.

**Comment by rajeevsrao** [comment]
CgPersistentLSTMPlugin_TRT is exclusive to the GA releases (closed source) and not included in the OSS release. The snippet in the developer guide  is for illustration.
