### ISSUE TITLE
FasterTransformer plugins for TensorRT | add_residual+LayerNorm not being matched by plugin

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/TensorRT#3230]
We are seeing a not very fused LayerNorm's in a trex output, e.g. it does two-pass for mean-var compared to possible [one-pass impl](https://oneflow2020.medium.com/how-to-implement-an-efficient-layernorm-cuda-kernel-oneflow-performance-optimization-731e91a285b8)

So I wondered if FasterTransformer separate kernels exist in form of plugins for TensorRT?

I noticed at https://github.com/nvidia/FasterTransformer/blob/dev/v5.0_beta/docs/bert_guide.md#standard-bert-and-effective-fastertransformer that in reverse, FT can use TRT kernels for MHA, but I'm wondering in reverse if TRT can use FT's `add_bias_input_layernorm`? 

https://github.com/NVIDIA/FasterTransformer/#advanced suggests that `    |--/tensorrt_plugin: encapluate FasterTransformer into TensorRT plugin.` is supported, but on the other side in the README somewhere it says `Remove the TensorRT plugin supporting.`. So I am confused if by `TensorRT plugin` they mean a `FT-kernels packaged as TRT-plugin` or `Being able to use TRT-optimized-code-path from FT`.

Does it make sense at all? Or should TRT be always faster than FT?

Our graph is a regular pytorch LayerNorm exported to ONNX, so it should be pattern-matched easily. Shouldn't https://github.com/NVIDIA/TensorRT/tree/release/8.6/plugin/skipLayerNormPlugin get matched? This is exactly our case: adding a residual + layernorm.

<img width="230" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/1041752/c17384af-f63e-493c-abf3-18dca7874677">

**Comment by zerollzeng** [comment]
@nvpohanh @samurdhikaru ^ ^

**Comment by nvpohanh** [comment]
@vadimkantorov Which TRT version are you using? If you are using TRT 8.6, we should have detected the LayerNorm patterns and fuse this part into one kernel. No plugin is needed

**Comment by vadimkantorov** [comment]
8.6.1.6

**Comment by nvpohanh** [comment]
Hmm that's weird. Could you share your ONNX file and the trtexec command you used? Also, if possible, could you try re-exporting the ONNX file using opset=17 or above. With opset>=17, there should be "LayerNormalization" ops in the ONNX file and they help TRT to recognize the LayerNorm more easily.

**Comment by WoodieDudy** [comment]
Hi, I'm working with vadimkantorov. You were right, opset 17 gathers it in the LayerNorm block.

<img width="665" alt="SCR-20230818-orqm" src="https://github.com/NVIDIA/TensorRT/assets/55787608/1bf043e0-68de-41b1-96af-0ae87e0265a6"></br>
## There is our model code

```python
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        d_model = 512
        d_ff = 2048
        dropout = 0.1
        self.fc_factor = 0.5

        self.feed_forward1 = FeedForward(d_model=d_model, d_ff=d_ff, dropout=dropout)
        self.norm_self_att = torch.nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

        self.feed_forward1_scale = ScaleBiasLayer(d_model)

    def forward(self, x):
        residual = x
        x = self.feed_forward1_scale(x)
        x = self.feed_forward1(x)

        x = self.norm_self_att(residual + self.dropout(x) * self.fc_factor)
        return x

class ScaleBiasLayer(torch.nn.Module):
    def __init__(self, d_model: int) -> None:
        super().__init__()
        self.scale = nn.Parameter(torch.ones(d_model))
        self.bias = nn.Parameter(torch.zeros(d_model))

    def forward(self, x):
        scale = self.scale.view(1, 1, -1)
        bias = self.bias.view(1, 1, -1)
        return x * scale + bias
    
class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff, dropout, activation=torch.nn.SiLU()) -> None:
        super().__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.activation = activation
        self.dropout = nn.Dropout(p=dropout)
        self.linear2 = nn.Linear(d_ff, d_model)

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.dropout(x)
        x = self.linear2(x)
        return x
```

## Then I feed ops17 onnx into trex and got this big fuse.
![model_fp16_ops17](https://github.com/NVIDIA/TensorRT/assets/55787608/f714020a-d3b5-4a12-bc1f-a259e4ab5b63)

## Here is ops16 onnx in trex:
![model_fp16_op16](https://github.com/NVIDIA/TensorRT/assets/55787608/41177e12-22f9-4423-88af-f532c3bcafcf)


[onnx_weights.zip](https://github.com/NVIDIA/TensorRT/files/12378832/onnx.zip)

**Comment by WoodieDudy** [comment]
Does this myelin node fuse the whole mlp and layernorm? Does it use fp16 ops inside the mlp or int8 ops?
I don't see that in the block description.
![telegram-cloud-document-4-5978915000851369863](https://github.com/NVIDIA/TensorRT/assets/55787608/5cc59c6b-6654-4e9b-96de-0dce432c9b02)

**Comment by nvpohanh** [comment]
Yes, if you see the ForeignNode, than means the LayerNorms have been fused.

The ForeignNode does not support INT8 implicit quantization, so it uses FP16. If you want to use INT8, you will need to insert Q/DQ ops into the network to make it explicitly quantized.

**Comment by vadimkantorov** [comment]
As you can see, the decomposed LayerNorm is not matched by TRT. Is it a bug? Need to file a separate issue?

Also, it would be nice if the ForeignNode included all the node names that it fused together.

Regarding FT kernels/plugins: is this setup working somehow? This is important also because FT development is stopped. So would be nice to have emphasis on reusability of those kernels in other contexts (TRT or even hare PyTorch)

**Comment by nvpohanh** [comment]
We recommend users to use opset>=17 to ensure LayerNorm fusion.

> Also, it would be nice if the ForeignNode included all the node names that it fused together.

This is in progress and will gradually be rolled out in the next couple of TRT versions.

**Comment by vadimkantorov** [comment]
It's still fishy that basic LayerNorm could not be matched :) I assume there's plenty of such opset_version=16 onnx files lying around, especially given that pytorch docs are buggy and say that only max opset 16 is supported. And default opset is 14 :(

**Comment by nvpohanh** [comment]
Yeah, in theory TRT should match it. Could you share the ONNX file so that we can repro this issue? Thanks

**Comment by WoodieDudy** [comment]
Onnx files are at the bottom of this [comment](https://github.com/NVIDIA/TensorRT/issues/3230#issuecomment-1683798724)
Also here are trtexec logs
[model_fp16_op16.onnx.engine.build.log](https://github.com/NVIDIA/TensorRT/files/12395933/model_fp16_op16.onnx.engine.build.log)
[model_fp16_op17.onnx.engine.build.log](https://github.com/NVIDIA/TensorRT/files/12395934/model_fp16_op17.onnx.engine.build.log)

**Comment by nvpohanh** [comment]
@WoodieDudy Could you disable int8 and see if LayerNorm is fused as a ForeignNode? As I mentioned, that code path does not support INT8 implicit quantization as of now.

**Comment by nvpohanh** [comment]
Thanks. @zerollzeng Could you repro this and file an internal tracker? The pattern looks like a legit LayerNorm and I don't know why TRT 8.6.1.6 didn't detect it as a LayerNorm and trigger the ForeignNode fusion.

**Comment by zerollzeng** [comment]
Filed internal tracker 4254793 for this.

**Comment by zhenhuaw-me** [comment]
The fix will be included in the next release.

**Comment by vadimkantorov** [comment]
Cool, thanks @zhenhuaw-me :) Feel free to close this issue when you roll it out!

**Comment by zerollzeng** [comment]
closed.
