### ISSUE TITLE
Multi-layer MLP fusion conditions

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/TensorRT#3232]
https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-803/best-practices/index.html#mlp-fusions
says:
`
The initial creation of a dedicated MLP layer comes from a MatrixMultiply layer fused with an Activation layer. The MatrixMultiply layer must be a 2D multiplication. The size of the matrices `**must be small enough**` to use hardware shared memory to store temporary weights; for the untransposed case, this means the product of the widths of both matrices must be limited (heights if transposed).`

What are exact conditions for the shapes / sizes?

SiLU activation is not supported, right? https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a4806465e7c2bba8afc3f0388f538d2da

Is it targeting only dims like 32/64 akin to https://github.com/NVlabs/tiny-cuda-nn? Or can it work for inner dims like 128/256/512/1024 often found in transformer feed-forward MLPs? What are size conditions depending on dtype? One would imagine that it can work with larger hidden dims in fp16 compared to fp32 and with even larger hidden dims for int8

Thanks :) 

Thank you!

**Comment by zerollzeng** [comment]
@nvpohanh Can you help here, actually I think the layer fusion inside TRT is really subject to change...

**Comment by nvpohanh** [comment]
> What are exact conditions for the shapes / sizes?

It is hard to spell it in details, but roughly speaking: if the intermediate tensors can fit into the shared memory on GPU. 

Note that the MLP-fusion was only enabled for Volta GPUs because we later found that unfused gemm kernels perform much better (thanks to TensorCores) than the fused kernels on Turing+ GPUs. I think this fusion was also removed in later TRT releases.

**Comment by nvpohanh** [comment]
> SiLU activation is not supported, right? https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a4806465e7c2bba8afc3f0388f538d2da

There is no SiLU in the activation type, but you can build it with SIGMOID + an Elementwise PROD. TRT will automatically fuse these two into the same kernel.

**Comment by nvpohanh** [comment]
> Is it targeting only dims like 32/64 akin to https://github.com/NVlabs/tiny-cuda-nn? Or can it work for inner dims like 128/256/512/1024 often found in transformer feed-forward MLPs? What are size conditions depending on dtype? One would imagine that it can work with larger hidden dims in fp16 compared to fp32 and with even larger hidden dims for int8

The MLP-fusion was targeting very small inner dims, like 100. Transformers are all too big. And when the inner dims are large, using TensorCores is a much better choice than the fused MLP kernels, so we removed those fused MLP kernels later on.

**Comment by vadimkantorov** [comment]
Thank you for your help! I guess for the new version of TRT would be nice to have this expanded info in docs :)
