### ISSUE TITLE
Tensorrt Stablediffusion XL support 

### ISSUE THREAD

**Issue by sanbuphy** [NVIDIA/TensorRT#3248]
Hello, I would like to ask when TensorRT will be able to support the pipeline of StableDiffusion XL. Thank you very much.

**Comment by nvpohanh** [comment]
It is already supported on release/9.0 branch for Early Access: https://github.com/NVIDIA/TensorRT/tree/release/9.0/demo/Diffusion#generate-an-image-with-stable-diffusion-xl-guided-by-a-single-text-prompt

**Comment by sanbuphy** [comment]
> It is already supported on release/9.0 branch for Early Access: https://github.com/NVIDIA/TensorRT/tree/release/9.0/demo/Diffusion#generate-an-image-with-stable-diffusion-xl-guided-by-a-single-text-prompt

Thanks a lot!
