### ISSUE TITLE
There is a bug in  TensorRT/samples/opensource/sampleUffMaskRCNN/converted/0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch 

### ISSUE THREAD

**Issue by hwh-hit** [NVIDIA/TensorRT#325]
## Description

First i find that trt sampleUffMaskrcnn has a different result with maskrcnn implemented in keras. I print the output layer by layer . finally I find and solved the problem, There is a bug in the patched code. @kevinch-nv @rmccorm4 , we should add x = KL.Permute((2,3,1))(x) in https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L867 before rpn_bbox = KL.Reshape((-1, 4))(x). If not, the output of rpn_bbox is wrong. so we can't get the exactly same result with keras in NHWC format

**Comment by liangjiecn** [comment]
Your efforts are appreciated! I follow your suggestion and it gave the same results.  To be specific, we should move "x = KL.Permute((2,3,1))(x)"  at line 869 (after rpn_class_logits = KL.Reshape((-1, 2))(x))  to the place before rpn_bbox = KL.Reshape((-1, 4))(x). In addition, this is only applied to the maskrcnn for converting the model. The original model for training should be kept unchanged.

**Comment by hwh-hit** [comment]
Thanks, https://github.com/NVIDIA/TensorRT/issues/274 this is the complete debug process ,painful experience. If you are interested in it, you can take a look
