### ISSUE TITLE
Basic cuBlas(Lt) tracing

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/TensorRT#3251]
In PyTorch we can use `CUBLAS_LOGINFO_DBG=1 CUBLAS_LOGDEST_DBG=cublas.log CUDNN_LOGINFO_DBG=1  CUDNN_LOGDEST_DBG=cudnn.log python3 -c 'import torch; a = torch.rand(512, 1024, device = "cuda"); b = torch.rand(1024, 2048, device = "cuda"); print((a@b).sum())'`

For `trtexec --loadEngine` perf testing this seems not working. Could you please advise how to get basic cublasLt tracing / descriptors trace for studying memory layouts picked by `--int8`: 
- https://github.com/NVIDIA/TensorRT/issues/3233

Any of the flags https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#trtexec-flags can achieve the same?

**Comment by zerollzeng** [comment]
We don't have such option in TensorRT or trtexec. But I think you can search in the CUBLAS documentation to see if there is such env var.

**Comment by zerollzeng** [comment]
> Could you please advise how to get basic cublasLt tracing / descriptors trace for studying memory layouts picked by `--int8`

I think TRT verbose log should have such information. e.g. in the layer information or engine layer information section.

**Comment by vadimkantorov** [comment]
Th
