### ISSUE TITLE
TensorRT engine build failure, but can infer with onnxruntime

### ISSUE THREAD

**Issue by linghu8812** [NVIDIA/TensorRT#3255]
## Description

Hello!

I have generated an onnx model, and with onnxruntime can get the correct inference results, but with TensorRT I cannot generate an correct engine, and the following error will be reported:
**command**:
```
/usr/src/tensorrt/bin/trtexec --onnx=adet_2x_checkpoint0023.onnx --verbose
```
**error**:
```
[08/23/2023-02:33:25] [E] Error[7]: [shapeMachine.cpp::executeContinuation::864] Error Code 7: Internal Error ((Unnamed Layer* 1400) [Slice]: ISliceLayer has out of bounds access on axis 1 Condition '<' violated: 0 >= 0. Instruction: CHECK_LESS 0 0.)
```

May I ask how to modify my ONNX model?

My ONNX model can be downloaded through the following link：
[https://drive.google.com/file/d/1sPCht0UO6KAoGxyeDnar2bEcyRjVNURp/view?usp=sharing](https://drive.google.com/file/d/1sPCht0UO6KAoGxyeDnar2bEcyRjVNURp/view?usp=sharing)

my onnxruntime inference code is:
```
import onnx
import onnxruntime
import numpy as np

onnx_model = onnx.load('adet_2x_checkpoint0023.onnx')
ort_session = onnxruntime.InferenceSession(
        'weights/checkpoint.onnx', providers=["CUDAExecutionProvider"]
    )
ort_inputs = {ort_session.get_inputs()[0].name: np.random.randn(1, 3, 800, 800).astype(np.float32)}
ort_outs = ort_session.run(None, ort_inputs)
print(ort_outs[0].shape)
```

## Environment

**TensorRT Version**: 8.6.1.2

**NVIDIA GPU**: NVIDIA A10

**NVIDIA Driver Version**: 525.89.02

**CUDA Version**: 12.1

**CUDNN Version**: 8.9.0.131

Operating System: ubuntu

Python Version (if applicable): 3.8.10

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 2.0.1

Baremetal or Container (if so, version):

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: yes

**Comment by zerollzeng** [comment]
issue fixed in TRT 10, closed.
