### ISSUE TITLE
Gemm+bias+activation / MLP int8+fp16 performance of TensorRT compared to FasterTransformer kernels / cublasLt

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/TensorRT#3259]
Hi! Are there anywhere examples / perf comparison of int8-quantized Linear layers implemented in TensorRT versus FasterTransformer / cublasLt?

I read https://www.speechmatics.com/company/articles-and-news/fast-and-accurate-gpu-quantization-for-transformers, and it seems that cublasLt tried to speed up things by using funny custom memory layouts such as COL32/4R4. I wonder how does this approach compare to the kernels in TensorRT perf-wise.

**Comment by vadimkantorov** [comment]
Related:
- https://github.com/NVIDIA/TensorRT/issues/3233#issuecomment-1689532096

In reverse, FT seems to use cublasLt/cutlass.

But having benchmarks would be nice. Ideally both should achieve peak perf

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by zerollzeng** [comment]
> Are there anywhere examples / perf comparison of int8-quantized Linear layers implemented in TensorRT versus FasterTransformer / cublasLt?

AFAIK no


> I read https://www.speechmatics.com/company/articles-and-news/fast-and-accurate-gpu-quantization-for-transformers, and it seems that cublasLt tried to speed up things by using funny custom memory layouts such as COL32/4R4. I wonder how does this approach compare to the kernels in TensorRT perf-wise.

I think memory layout that a kernel used is highly bounding with the exact GPU architecture or HW, so there is know golden rules that what's the best memory layout is for a kernel, it depends how it compute, the reformat cost(data need to commute with adjacent layers), accelerators, memory bandwidth, L1/L2/sharedMem size etc... so TensorRT just time all available kernels and reformat kernels to find the globally best performance combination.

**Comment by zerollzeng** [comment]
I also want to hear @nvpohanh's insight on this :-D

**Comment by nvpohanh** [comment]
> Hi! Are there anywhere examples / perf comparison of int8-quantized Linear layers implemented in TensorRT versus FasterTransformer / cublasLt?

TRT and cuBLASLt use the same underlying internal library for gemm kernels, so I would expect the same perf if done correctly. Please let us know if you find any case where TRT is slower than cuBLASLt.

**Comment by nvpohanh** [comment]
> I read https://www.speechmatics.com/company/articles-and-news/fast-and-accurate-gpu-quantization-for-transformers, and it seems that cublasLt tried to speed up things by using funny custom memory layouts such as COL32/4R4. I wonder how does this approach compare to the kernels in TensorRT perf-wise.

TRT already uses this for INT8 gemm kernels.

**Comment by vadimkantorov** [comment]
Btw, which FT kernels proved to be useful in TRT-LLM? Given that in FT, one of later recommended ways was using TRT for attention itself:
<img width="349" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/1041752/523fbec8-7248-44ed-aedb-98546f923473">
