### ISSUE TITLE
fcPlugin.h TensorRT Open Source Release/6.0 ：too old to let me know how to use in trt version7.0

### ISSUE THREAD

**Issue by sumagic** [NVIDIA/TensorRT#326]
## fcPlugin.h, the file in sample/samplePlugin is still version6.0, while now trt is release version 7.0, could you please update that as latest in handbook?

**Comment by rmccorm4** [comment]
Hi @sumagic,

Do you have a specific error that you can reproduce? Just because the file wasn't updated since TensorRT 6.0 doesn't necessarily mean that it won't work in TensorRT 7.0.

**Comment by rmccorm4** [comment]
Closing since no response.
