### ISSUE TITLE
where is imagenet_pytorch data?

### ISSUE THREAD

**Issue by wutheringcoo** [NVIDIA/TensorRT#3264]
hello， when i run tools/pytorch-quantization/examples/calibrate_quant_resnet50.ipynb, below:
data_path = "/raid/data/imagenet/imagenet_pytorch"
batch_size = 512
so how to download imagenet_pytorch data?
thanks

**Comment by zerollzeng** [comment]
@ttyio I think we need to fix this.

**Comment by ttyio** [comment]
imagenet is not property of Nvidia, could you download it from the official site https://www.image-net.org/download.php? thanks!

**Comment by ttyio** [comment]
closing since this is no issue, thanks all!
