### ISSUE TITLE
How to specify inputIOFormat flag for Linear input in trtexec

### ISSUE THREAD

**Issue by WoodieDudy** [NVIDIA/TensorRT#3265]
I have a MLP block that takes a tensor of size (10240, 512) i.e. (batch, channel) as input. 
```python
class MLP(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        d_model, d_ff = 512, 2048
        self.lin1 = nn.Linear(d_model, d_ff)
        self.activation = nn.ReLU()
        self.lin2 = nn.Linear(d_ff, d_model)

    def forward(self, x):
        x = self.lin1(x)
        x = self.activation(x)
        x = self.lin2(x)
        return x
```
I export it to ONNX using explicit quantization with `pytorch_quantization`. 

```python
import torch
from pytorch_quantization import nn as quant_nn
from pytorch_quantization import quant_modules

quant_nn.TensorQuantizer.use_fb_fake_quant = True
quant_modules.initialize()
model = MLP().eval()
    
torch.onnx.export(
    model.cuda(),
    torch.rand(10240, 512).cuda(),
    "MLP_explicit_quant_fp32.onnx",
    verbose=False,
    input_names=["x"],
    opset_version=17
)
```
To build and visualize model
```
python TensorRT/tools/experimental/trt-engine-explorer/utils/process_engine.py MLP_explicit_quant_fp32.onnx temp int8 fp16
```
Output with trtexec commands to build same engine:
```
Building the engine:
trtexec --verbose --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=onnx/MLP_explicit_quant_fp32.onnx --saveEngine=temp/MLP_explicit_quant_fp32.onnx.engine --timingCacheFile=./timing.cache --int8 --fp16

Successfully built the engine.

Engine building metadata: generated output file temp/MLP_explicit_quant_fp32.onnx.engine.build.metadata.json
Profiling the engine:
trtexec --verbose --noDataTransfers --useCudaGraph --separateProfileRun --useSpinWait --nvtxMode=verbose --loadEngine=temp/MLP_explicit_quant_fp32.onnx.engine --exportTimes=temp/MLP_explicit_quant_fp32.onnx.engine.timing.json --exportProfile=temp/MLP_explicit_quant_fp32.onnx.engine.profile.json --exportLayerInfo=temp/MLP_explicit_quant_fp32.onnx.engine.graph.json --timingCacheFile=./timing.cache --int8 --fp16
WARNING:root:Could not lock clocks (Insufficient Permissions).
	Try running as root or locking the clocks from the commandline:
		sudo nvidia-smi --lock-gpu-clocks=1410,1410
		sudo nvidia-smi --applications-clocks=1215,1410
WARNING:root:Could not unlock clocks (Insufficient Permissions).
	Try running as root or unlocking the clocks from the commandline:
		sudo nvidia-smi --reset-gpu-clocks
		sudo nvidia-smi --reset-applications-clocks

Successfully profiled the engine.

Profiling metadata: generated output file temp/MLP_explicit_quant_fp32.onnx.engine.profile.metadata.json
Generating graph diagram: temp/MLP_explicit_quant_fp32.onnx.engine.graph.json
/root/projects/TensorRT/tools/experimental/trt-engine-explorer/trex/engine_plan.py:90: UserWarning:

Profiling data was not provided.

Created file:///root/projects/TensorRT/tools/experimental/trt-engine-explorer/temp/MLP_explicit_quant_fp32.onnx.engine.graph.json.svg
Artifcats directory: temp
```
Build logs:
[MLP_explicit_quant_fp32_whyfp32.onnx.engine.build.log](https://github.com/NVIDIA/TensorRT/files/12431339/MLP_explicit_quant_fp32_whyfp32.onnx.engine.build.log)

![MLP_explicit_quant_fp32 onnx engine graph json](https://github.com/NVIDIA/TensorRT/assets/55787608/6bc1671f-82ab-4883-a8ed-cbb31e768602)

### So I attempted to set the input format (and output format) using --inputIOFormats=fp16:chw32
```
python utils/process_engine.py onnx/MLP_explicit_quant_fp32.onnx temp int8 fp16 inputIOFormats=fp16:chw32 outputIOFormats=fp16:chw32
```
Output:
```
Building the engine:
trtexec --verbose --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=onnx/MLP_explicit_quant_fp32.onnx --saveEngine=temp/MLP_explicit_quant_fp32.onnx.engine --timingCacheFile=./timing.cache --int8 --fp16 --inputIOFormats=fp16:chw32 --outputIOFormats=fp16:chw32

Failed to build the engine.
See logfile in: temp/MLP_explicit_quant_fp32.onnx.engine.build.log

Troubleshooting:
1. Make sure that you are running this script in an environment which has trtexec built and accessible from $PATH.
2. If this is a Jupyter notebook, make sure the  trtexec is in the $PATH of the Jupyter server.
Artifcats directory: temp
```
But I encountered the following error in `temp/MLP_explicit_quant_fp32.onnx.engine.build.log`:
```
08/24/2023-10:25:35] [W] [TRT] x: formats with vectorized dimension require at least 3 dimensions, but dimensions are [10240,512]. Ignoring format CHW32 for type Half.
08/24/2023-10:25:35] [E] Error[4]: [buildLoweredGraph.cpp::checkUserI0FormatsViableHelper::196] Error Code 4: Internal Error (x: no formats available.)
```
Build logs:
[MLP_explicit_quant_fp32_failed.onnx.engine.build.log](https://github.com/NVIDIA/TensorRT/files/12431341/MLP_explicit_quant_fp32_failed.onnx.engine.build.log)

### Then I tried to pass (10240, 512, 1, 1) as example input to onnx and reshape it in forward
```
torch.onnx.export(
    model.cuda(),
    torch.rand(10240, 512, 1, 1).cuda(),
    "MLP_explicit_quant_fp32.onnx",
    verbose=False,
    input_names=["x"],
    opset_version=17
)
```
```
    def forward(self, x):
        x = x.view(10240, 512)
        x = self.lin1(x)
        x = self.activation(x)
        x = self.lin2(x)
        x = x.view(10240, 512, 1, 1)
        return x
```
```
python utils/process_engine.py onnx/MLP_explicit_quant_fp32.onnx temp int8 fp16 inputIOFormats=fp16:chw32 outputIOFormats=fp16:chw32
```
Output:
```
Building the engine:
trtexec --verbose --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=onnx/MLP_explicit_quant_fp32.onnx --saveEngine=temp/MLP_explicit_quant_fp32.onnx.engine --timingCacheFile=./timing.cache --int8 --fp16 --inputIOFormats=fp16:chw32 --outputIOFormats=fp16:chw32

Successfully built the engine.

Engine building metadata: generated output file temp/MLP_explicit_quant_fp32.onnx.engine.build.metadata.json
Profiling the engine:
trtexec --verbose --noDataTransfers --useCudaGraph --separateProfileRun --useSpinWait --nvtxMode=verbose --loadEngine=temp/MLP_explicit_quant_fp32.onnx.engine --exportTimes=temp/MLP_explicit_quant_fp32.onnx.engine.timing.json --exportProfile=temp/MLP_explicit_quant_fp32.onnx.engine.profile.json --exportLayerInfo=temp/MLP_explicit_quant_fp32.onnx.engine.graph.json --timingCacheFile=./timing.cache --int8 --fp16 --inputIOFormats=fp16:chw32 --outputIOFormats=fp16:chw32
WARNING:root:Could not lock clocks (Insufficient Permissions).
	Try running as root or locking the clocks from the commandline:
		sudo nvidia-smi --lock-gpu-clocks=1410,1410
		sudo nvidia-smi --applications-clocks=1215,1410
WARNING:root:Could not unlock clocks (Insufficient Permissions).
	Try running as root or unlocking the clocks from the commandline:
		sudo nvidia-smi --reset-gpu-clocks
		sudo nvidia-smi --reset-applications-clocks

Successfully profiled the engine.

Profiling metadata: generated output file temp/MLP_explicit_quant_fp32.onnx.engine.profile.metadata.json
Generating graph diagram: temp/MLP_explicit_quant_fp32.onnx.engine.graph.json
/root/projects/TensorRT/tools/experimental/trt-engine-explorer/trex/engine_plan.py:90: UserWarning:

Profiling data was not provided.

Created file:///root/projects/TensorRT/tools/experimental/trt-engine-explorer/temp/MLP_explicit_quant_fp32.onnx.engine.graph.json.svg
Artifcats directory: temp
```
Build logs:
[MLP_explicit_quant_fp32_inputioformats.onnx.engine.build.log](https://github.com/NVIDIA/TensorRT/files/12431249/MLP_explicit_quant_fp32_inputioformats.onnx.engine.build.log)

### Input and output changed type to fp16, thats good, but now Reformat node returns Unknown format. I want it to return NC/32HW32.
![MLP_explicit_quant_fp32 onnx engine graph json](https://github.com/NVIDIA/TensorRT/assets/55787608/ee88e311-b514-4663-ae1d-df5177819b06)

### How can I configure properly the input to be in the fp16 without reshaping and Unknown format in Reformat node output?
Thanks

**Comment by zerollzeng** [comment]
> trtexec --verbose --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=onnx/MLP_explicit_quant_fp32.onnx --saveEngine=temp/MLP_explicit_quant_fp32.onnx.engine --timingCacheFile=./timing.cache --int8 --fp16 --inputIOFormats=fp16:chw32 --outputIOFormats=fp16:chw32

could you please try `trtexec --verbose --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=onnx/MLP_explicit_quant_fp32.onnx --saveEngine=temp/MLP_explicit_quant_fp32.onnx.engine --timingCacheFile=./timing.cache --int8 --fp16 --inputIOFormats=int8:chw32 --outputIOFormats=int8:chw32`?

**Comment by zerollzeng** [comment]
see https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#ac3e115b1a2b1e578e8221ef99d27cd45

**Comment by WoodieDudy** [comment]
I'm getting error
```
[E] Error[1]: [qdqGraphOptimizer.cpp::quantizePaths::3943] Error Code 1: Internal Error (Node /lin1/_input_quantizer/QuantizeLinear cannot be quantized by x. You might want to add a DQ node before /lin1/_input_quantizer/QuantizeLinear)
```
[MLP_explicit_quant_fp32_(int8_chw32).onnx.engine.build.log](https://github.com/NVIDIA/TensorRT/files/12450902/MLP_explicit_quant_fp32_.int8_chw32.onnx.engine.build.log)

**Comment by WoodieDudy** [comment]
So I have 2 questions.
1. What does "unknown format" mean? What are the implications of it?
2. How can I use fp16 in input, without reshaping?

**Comment by zerollzeng** [comment]
> ```
> [E] Error[1]: [qdqGraphOptimizer.cpp::quantizePaths::3943] Error Code 1: Internal Error (Node /lin1/_input_quantizer/QuantizeLinear cannot be quantized by x. You might want to add a DQ node before /lin1/_input_quantizer/QuantizeLinear)
> ```

Wrong Q/DQ replacement. does it work with onnxruntime?



> 1. What does "unknown format" mean? What are the implications of it?

You are seeing this when some errors happen?

> 2\. How can I use fp16 in input, without reshaping?

`--inputIOFormats=fp16:linear --outputIOFormats=fp16:linear`, TRT will do other reformat for you

**Comment by WoodieDudy** [comment]
- The error above appears because I am trying to pass int8 to Q. That's to be expected
- I didn't see any errors [here](https://github.com/NVIDIA/TensorRT/files/12431249/MLP_explicit_quant_fp32_inputioformats.onnx.engine.build.log) when "unknown format" came up.
- I changed format to
`--inputIOFormats=fp16:dla_linear --outputIOFormats=fp16:dla_linear`
And input became fp16 as I wanted
![MLP_layernorm_explicit_quant_fp32_2 onnx engine graph json](https://github.com/NVIDIA/TensorRT/assets/55787608/968d5c77-160e-4f94-9697-c8aedf0a1b5f)
Thanks

**Comment by vadimkantorov** [comment]
@zerollzeng The question remains of how to get NC32HW/32 entering both conv modules without "unknown format" mystery (and what "unknown format" means)

Basically, the quesion from https://user-images.githubusercontent.com/55787608/262955098-ee88e311-b514-4663-ae1d-df5177819b06.svg is still open...

**Comment by zerollzeng** [comment]
I kind of feel like the "unknown format" is a bug of our engine layer profile. @nvpohanh do you aware of this?

BTW which TRT version you are using?

**Comment by WoodieDudy** [comment]
8.6.1.6

**Comment by nvpohanh** [comment]
> I kind of feel like the "unknown format" is a bug of our engine layer profile. @nvpohanh do you aware of this?_

I remember seeing this bug in TRT 8.6 but it should have been fixed in TRT 9.0

**Comment by vadimkantorov** [comment]
Oh, is there a new GA release? :)

**Comment by nvpohanh** [comment]
https://github.com/NVIDIA/TensorRT/tree/release/9.0#optional---if-not-using-tensorrt-container-specify-the-tensorrt-ga-release-build-path

**Comment by vadimkantorov** [comment]
Very cool, thanks :) The official release on the page https://github.com/NVIDIA/TensorRT/releases and NGC container coming soon too, right?
