### ISSUE TITLE
createInferRefitter failure of TensorRT 8.5.1.7 when running with multi profiles

### ISSUE THREAD

**Issue by huwatermelon** [NVIDIA/TensorRT#3268]
createInferRefitter return nullptr when engine has multi profiles. But running ok for single profile.
[TRT]2: [refit.cpp::initialize::95] Error Code 2: Internal Error (Assertion p.second failed. ground expressions with duplicate layer names and role)
So when we can support multi profile refit, and do we have trick solutions presently?

**Comment by BowenFu** [comment]
> createInferRefitter return nullptr when engine has multi profiles. But running ok for single profile. [TRT]2: [refit.cpp::initialize::95] Error Code 2: Internal Error (Assertion p.second failed. ground expressions with duplicate layer names and role) So when we can support multi profile refit, and do we have trick solutions presently?

Can you try TensorRT 9.0 / 8.6? I guess the issue has been fixed in these versions.

**Comment by huwatermelon** [comment]
check with 8.6.1, it support multi profile refit
