### ISSUE TITLE
link error createRPNROIPlugin

### ISSUE THREAD

**Issue by dbrazey** [NVIDIA/TensorRT#327]
Hello, 

When I download TensorRT 5.1.5.0 from Nvidia website, the result of the command 
`nm -gD libnvinfer_plugin.so | grep createRPNROIPlugin`
is
`000000000001c150 T createRPNROIPlugin`

which means that the function exists in the file. 
When I compile this repo to generate libnvinfer_plugin.so, the result of my command is empty, which means that the function createRPNROIPlugin "disappeared". 

I therefore get an error link in my C++ program. 
Should I set a specific option in te CMakelists ? 

Another point, it seems that the sample sampleFasterRCNN located in this directory is different than the sample provide in the tar file downloaded from Nvidia website, is it normal ? 

Thanks for your help

**Comment by litaotju** [comment]
I think that API is deprecated, you could use the `RPROIPluginCreator` directly or just use the following code to get the plugin creator stored into `roiPluginCreator`, and then use the creator to create plugin for you.

```
IPluginCreator * roiPluginCreator = getPluginRegistry()->getPluginCreator("RPROI_TRT", "1");
//prepare parameter, see the IPluginCreator::createPlugin api.
auto roiPlugin = roiPluginCreator->createPlugin(...);
```

See doc from: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#migrating-plugins-6xx-7xx

**Comment by dbrazey** [comment]
Thanks

**Comment by rmccorm4** [comment]
Thanks for helping @litaotju, much appreciated!
