### ISSUE TITLE
Quantizing Add layer with residual connections in tensorflow_quantization toolkit

### ISSUE THREAD

**Issue by kari-jg** [NVIDIA/TensorRT#3270]
## Description

I'm trying to quantize a Unet-like model with residual connections as Add layers in tensorflow, in order to later convert it to onnx and then build a tensorRT engine. 
The parts of my unquantized model with residual connections look like this: 
![image](https://github.com/NVIDIA/TensorRT/assets/74316409/19b1b0da-c7a1-44f7-9efe-639ae5fadb43)

I'm following this guide for optimal fusion: https://docs.nvidia.com/deeplearning/tensorrt/tensorflow-quantization-toolkit/docs/docs/add_custom_qdq_cases.html

And quantizing the model like this:

```
qspec = QuantizationSpec()
qspec.add(name="Conv2D", is_keras_class=True)
qspec.add(name="Conv2DTranspose", is_keras_class=True)
qspec.add(name="Add", is_keras_class=True)
residual_connections_case = custom_qdq_cases.ResidualConnectionQDQCase()
quant_aware_model = quantize_model(model=model, quantization_mode='partial', quantization_spec=qspec, custom_qdq_cases=[residual_connections_case]) 
```

This is quantizing my Add layers, but in the way that is said to be suboptimal for layer fusion, since there are not supposed to be quant/dequant layers after the convs as input to the Add layer:

![image](https://github.com/NVIDIA/TensorRT/assets/74316409/1d6bd755-05d4-472c-9726-ed514a01866b)

I also tried this, since the inputs to my Add layer are the output of  Maxpool layers, but there are still quant/dequants after conv and before Add:

```
qspec = QuantizationSpec()
qspec.add(name="Conv2D", is_keras_class=True)
qspec.add(name="Conv2DTranspose", is_keras_class=True)
qspec.add(name="Add", is_keras_class=True)
residual_connections_case = custom_qdq_cases.ResidualConnectionQDQCase()
maxpool_case = custom_qdq_cases.MaxPoolQDQCase()
quant_aware_model = quantize_model(model=model, quantization_mode='partial', quantization_spec=qspec, custom_qdq_cases=[residual_connections_case, maxpool_case]) 
```

What am I doing wrong with this? The example didn't pass a QuantizationSpec to quantize_model(), but I need to make sure that  the convs, and conv transpose are quantized.

**Comment by zerollzeng** [comment]
@ttyio  ^ ^

**Comment by ttyio** [comment]
Adding @gcunhase for help, thanks!

**Comment by gcunhase** [comment]
Hi @kari-jg, can you please try adding Q/DQ nodes on the skip-connection (left-side branch of Add) and check how it affects TRT runtime? Thanks.

**Comment by gcunhase** [comment]
@kari-jg Does the performance improve if you remove the QDQ nodes between Conv-Relu and Add? The left-side branch of Add in the above image. Thanks.

**Comment by gcunhase** [comment]
@ttyio please consider this issue as stale since it's been 3 weeks without updates. Thanks.

**Comment by ttyio** [comment]
Closing, thanks @gcunhase !
