### ISSUE TITLE
How to use IPluginV2DynamicExt plugin in python code?

### ISSUE THREAD

**Issue by sky-fun** [NVIDIA/TensorRT#3272]
## Description

If i create a plugin class inherit from IPluginV2DynamicExt , i can use configurePlugin and enqueue directly from c++ code;
but when i use it in python code, error show:
```bash
AttributeError: 'tensorrt.tensorrt.IPluginV2' object has no attribute 'configure_plugin'
```
So is there any examples to create IPluginV2DynamicExt  plugin and use configurePlugin、enqueue in python codes?

**Comment by zerollzeng** [comment]
The plugin is still written in c++, am I correct? Currently we don't support write plugins in python. the `configurePlugin` and `enqueue` should be called by TRT internally, why you call it explicitly in your code?

**Comment by sky-fun** [comment]
Yes, the plugin is written in c++;
There is "configure_plugin" in binding code: https://github.com/NVIDIA/TensorRT/blob/release/8.6/python/src/infer/pyPlugin.cpp#L185
i thought i can config or excute the plugin directly in python code;

**Comment by pranavm-nvidia** [comment]
Might need to cast it first:
```py
plugin.__class__ = trt.IPluginV2DynamicExt

plugin.configure_plugin(...)
```
But like @zerollzeng said, this is supposed to be called by TRT. Why do you need to call it yourself?

**Comment by sky-fun** [comment]
@pranavm-nvidia I want to [create a plugin](https://github.com/NVIDIA/TensorRT/blob/release/8.6/python/src/infer/pyPlugin.cpp#L244) ,then [config the shape](https://github.com/NVIDIA/TensorRT/blob/release/8.6/python/src/infer/pyPlugin.cpp#L185) and [execute](https://github.com/NVIDIA/TensorRT/blob/release/8.6/python/src/infer/pyPlugin.cpp#L174) this plugin without create a network.

**Comment by zerollzeng** [comment]
> without create a network.

No, you can't do this If you want to run through TensorRT, maybe just write the kernel and export via pybind11 so that you can call it with python?

**Comment by sky-fun** [comment]
Ok，i will try "write the kernel and export via pybind11"
Thanks。
