### ISSUE TITLE
uff parser，Dimension mismatch

### ISSUE THREAD

**Issue by liupengkd** [NVIDIA/TensorRT#328]
## Environment

**TensorRT Version**: trt 7
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 430
**CUDA Version**: 10
**CUDNN Version**: 7.6
**Operating System + Version**:ubuntu 16.04 
**Python Version (if applicable)**:3.5 
**TensorFlow Version (if applicable)**:1.9 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

The input of my tensorflow model is NHWC. In order to make the input become NCHW, I changed it to NCHW, and then added the transpose operation. Other operations are unchanged. After modification my tensorflow can run normally。Then I solidified the model into a pb file and converted it into a uff file.
![image](https://user-images.githubusercontent.com/15835439/72205676-01b20d80-34c1-11ea-9393-e543cca5646f.png)

After parsing, there was a dimensional mismatch problem, but the previous convolution And bn gave no error。
![image](https://user-images.githubusercontent.com/15835439/72205699-31611580-34c1-11ea-8ac6-c49a4a11ffea.png)
error
![image](https://user-images.githubusercontent.com/15835439/72205709-4d64b700-34c1-11ea-9923-358d882bcfb2.png)
Why does the dimension mismatch occur?After inputting NCHW, it is converted to NCHW. The subsequent operations are also NHWC. Why is there a tensor of NCHW dimension?

**Comment by rmccorm4** [comment]
Hi @liupengkd,

Per this link: https://devtalk.nvidia.com/default/topic/1046103/tensorrt/tensorrt-uff-tensorflow-nhwc-channels-last-to-nchw-channels-first-conversion-buggy/post/5308492/#5308492

I believe TensorRT/UFF handles transposing NHWC -> NCHW for you, so if you manually inserted a Transpose op, that is probably undoing the automatically inserted Transpose, and causing a shape mismatch.
