### ISSUE TITLE
fused attention kernel

### ISSUE THREAD

**Issue by superpigforever** [NVIDIA/TensorRT#3280]
Hi:
are these kernels only for bert or are they usable for models like swin transformer? The content length seems different from the one in FasterTransformer?
![image](https://github.com/NVIDIA/TensorRT/assets/26158127/50fbf83f-e1ed-4981-83d8-6dce5bce2529)

**Comment by nvpohanh** [comment]
No, those kernels do not work for SwinTransformer. The current recommended way to get fused attention is by exporting the SwinT model to ONNX file and load the ONNX file into TRT. If you want to run INT8, please insert Q/DQ ops before each gemm, each MatMul, and each ResidualAdd.

**Comment by shuyuan-wang** [comment]
> No, those kernels do not work for SwinTransformer. The current recommended way to get fused attention is by exporting the SwinT model to ONNX file and load the ONNX file into TRT. If you want to run INT8, please insert Q/DQ ops before each gemm, each MatMul, and each ResidualAdd.

does tensorrt already support fused attention? I thought gelu, layernorm and attention in onnx are all fragmented. Do I need to upgrade to latest tensorrt or can I use tensorrt 8.4?

**Comment by nvpohanh** [comment]
You will need TensorRT 8.6 to get those fusions.

**Comment by Oh-Cest-la-vie** [comment]
@nvpohanh I want to ask if Deformable attention is also supported in TensorRT 8.6 ?

**Comment by nvpohanh** [comment]
Not yet, but there is a plugin for that: https://github.com/NVIDIA/TensorRT/tree/release/8.6/plugin/multiscaleDeformableAttnPlugin

**Comment by Oh-Cest-la-vie** [comment]
Yes, thanks for your reply.

**Comment by ttyio** [comment]
closing since this is solved, thanks all!
