### ISSUE TITLE
custom plugin

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#3284]
May I ask where do I setup memory that is required for initialize()? I am currently working on my own tensorrt plugin. I am trying to allocate some large tensors at initialize(), however, the engine constantly sends me cuda error. Such error won't appear if I allocate the tensors at enqueue(). I figured it could be memory problem?

**Comment by zerollzeng** [comment]
Perhaps https://github.com/NVIDIA-AI-IOT/tensorrt_plugin_generator can help you.

**Comment by shuyuan-wang** [comment]
> Perhaps https://github.com/NVIDIA-AI-IOT/tensorrt_plugin_generator can help you.

I'm already using this. I thought getWorkspaceSize is the place to give the size for initialize()? Does this size needs to be exactly the same as the the tensor size in initialize() or can it be larger?

**Comment by shuyuan-wang** [comment]
I don't think the error actually appears in my custom plugin, this is the error:
```
[09/04/2023-03:32:13] [TRT] [E] 1: [reformatRunner.cpp::execute::603] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
```
My plugin is right after the quantize layer. I found that the quantize layer is a reformat layer? But I'm not sure why this happens, anyone has any idea?

**Comment by shuyuan-wang** [comment]
I find a wield bug. I my code, I use cudamalloc to allocate space, 
this->tensor_padded is int*
```
cudaMalloc(&this->tensor_padded, sizeof(tv::int32)*(kv*tensor_size))
```
Then, in enqueue, I use torch::from_blob to load one tensor from input, let's call it tensor_b,
after a closed sourced function which does not work on tensor_b, but on this->tensor_padded, the content in tensor_b changed to something random, but the shape is the same. Not sure what happened.

**Comment by zerollzeng** [comment]
> I thought getWorkspaceSize is the place to give the size for initialize()?

No, this is not correct, please refer to our api doc.

> But I'm not sure why this happens,

I feel the input or output buffer of the reformat kernel is problematic, which is the input/output buffer of you plugin.

**Comment by shuyuan-wang** [comment]
> I know it's a bit of tedious, but I would highly suggest reading our api doc and developer guide first to understand how the plugin works. and in https://github.com/NVIDIA-AI-IOT/tensorrt_plugin_generator, I provide a debug micro that can print each api call, also make use it to understand how the apis are called by TRT.

I read the api doc, but I think my problem is a bit more complicated. I allocated some device buffer at initialize(), after that, in clone, when I tried to memcpy it back to cpu, it has memory error. I can memcpy it in initialize() though.
