### ISSUE TITLE
The accuracy is degraded and very unstable

### ISSUE THREAD

**Issue by M15-3080** [NVIDIA/TensorRT#3285]
Hi, I have a question for you. I converted the pt model in YOLOv5 into engine, and found that the confidence level of the target decreased (higher than 3 points) when I used the engine file for detection, but the confidence level of some targets was higher than that of the pt model detection. May I ask why?

In some cases, the results of tensorrt were more than 10 points higher than the results of YOLOv5（YOLOv5 on the left, tensorrt on the right）
![b00af0b65519a009062cba4b76df95b](https://github.com/NVIDIA/TensorRT/assets/91411583/f5fa49cd-d43e-49c6-a42b-f0ca0e3d61f4)

**Comment by M15-3080** [comment]
I use cuda11.3,tensorrt8.2.5.1 version

**Comment by zerollzeng** [comment]
Please provide more details. I have following questions/suggestion for you:
1. Does the onnx model has the same accuracy as the original pytorch model?
2. Did you enable FP16 or INT8, is there any other special build config you are using?
3. You can debug the onnx model accuracy with polygraphy, see https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/run/01_comparing_frameworks
4. Please use latest release. we don't fix bugs on TRT 8.2 now.
