### ISSUE TITLE
Run the Tacotron2 meet the problem

### ISSUE THREAD

**Issue by liuchangready** [NVIDIA/TensorRT#329]
cuda 10.0
cudnn 7.6.5
tensorrt 7.0.11
gpu:p4
hi now I change the Tacotron2 with the Tensorrt code.I sucessed to generate onnx and engine,but when I run the Encoder model.it output the error code like that:
|||| binding 0
|||| binding_is_input True
|||| get_binding_dtype DataType.INT32
|||| get_binding_name sequences
|||| get_binding_shape (-1, -1)
|||| get_binding_vectorized_dim -1
|||| binding 1
|||| binding_is_input True
|||| get_binding_dtype DataType.INT32
|||| get_binding_name sequence_lengths
|||| get_binding_shape (-1,)
|||| get_binding_vectorized_dim -1
|||| binding 2
|||| binding_is_input False
|||| get_binding_dtype DataType.FLOAT
|||| get_binding_name memory
|||| get_binding_shape (-1, -1, 512)
|||| get_binding_vectorized_dim -1
|||| binding 3
|||| binding_is_input False
|||| get_binding_dtype DataType.INT32
|||| get_binding_name lens
|||| get_binding_shape (-1,)
|||| get_binding_vectorized_dim -1
|||| binding 4
|||| binding_is_input False
|||| get_binding_dtype DataType.FLOAT
|||| get_binding_name processed_memory
|||| get_binding_shape (-1, -1, 128)
|||| get_binding_vectorized_dim -1
|||| all_binding_shapes_specified True
|||| all_shape_inputs_specified True
[TensorRT] ERROR: ../rtSafe/cuda/cudaConvolutionRunner.cpp (362) - Cudnn Error in execute: 7 (CUDNN_STATUS_MAPPING_ERROR)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception

**Comment by rmccorm4** [comment]
Hi @liuchangready, it looks like this issue is being tracked here: https://devtalk.nvidia.com/default/topic/1069713/tensorrt/run-the-tacotron2-meet-the-problem
