### ISSUE TITLE
Does TensorRT support variable sequence length inputs in a batch  in BERT like models?

### ISSUE THREAD

**Issue by DamonsJ** [NVIDIA/TensorRT#3298]
In an old tensorrt version [blog](https://www.ccoderun.ca/programming/doxygen/tensorrt/md_TensorRT_demo_BERT_README.html#bert-base-1), variable sequence length inputs will be supported in future, I want to know is it supported now?
Do I need to explicit set something?

By the way, BERT demo do not support seq len except 128 and 384, how can I do benchmark of other seq len?

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
We have command line to run the variable sequence length https://github.com/NVIDIA/TensorRT/tree/release/8.6/demo/BERT#variable-sequence-length

For the fixed sequence length, the mha plugin support: 64, 96, 128, 384, 512, head size == 64.
For the variable sequence length, the mha plugin support any sequence <= 512, head size <=64

**Comment by DamonsJ** [comment]
Thanks very much!

**Comment by ttyio** [comment]
closing and thanks!
