### ISSUE TITLE
Tensorrt run slower than ONNX （fairseq wav2vec2 model）

### ISSUE THREAD

**Issue by firdota** [NVIDIA/TensorRT#3300]
## Description
I converted the Fairseq-provided wav2vec2 model into ONNX format, and then converted it into a TRT.Engine using trtexec.
Comparing the speed of both, I found that TRT was twice as slow as ONNX.

## Environment

GPU：A100
driver version：525.105.17
docker image: nvcr.io/nvidia/tensorrt:23.08-py3  (install onnx onnxruntime-gpu in the container) 

## Relevant Files
The model is quite large（1.2G）

## Steps To Reproduce
1. onnx to trt:
./trtexec --onnx=wav2vec.onnx --minShapes=input:1x1600 --optShapes=input:8x160000 --maxShapes=input:16x1600000 --saveEngine=wav2vec.engine

2. inference code
```
import tensorrt as trt
import torch
import time
from typing import Union, Optional, Sequence,Dict,Any
import onnxruntime

trt_path = 'wav2vec.engine'
onnx_name = 'wav2vec.onnx'

class TRTWrapper(torch.nn.Module):
    def __init__(self, engine: Union[str, trt.ICudaEngine],
                 output_names: Optional[Sequence[str]] = None) -> None:
        super().__init__()
        self.engine = engine
        if isinstance(self.engine, str):
            with trt.Logger() as logger, trt.Runtime(logger) as runtime:
                with open(self.engine, mode='rb') as f:
                    engine_bytes = f.read()
                self.engine = runtime.deserialize_cuda_engine(engine_bytes)
        self.context = self.engine.create_execution_context()
        names = [_ for _ in self.engine]
        input_names = list(filter(self.engine.binding_is_input, names))
        self._input_names = input_names
        self._output_names = output_names

        if self._output_names is None:
            output_names = list(set(names) - set(input_names))
            self._output_names = output_names

    def forward(self, inputs: Dict[str, torch.Tensor]):
        bindings = [None] * (len(self._input_names) + len(self._output_names))
        for input_name, input_tensor in inputs.items():
            idx = self.engine.get_binding_index(input_name)
            self.context.set_binding_shape(idx, tuple(input_tensor.shape))
            bindings[idx] = input_tensor.contiguous().data_ptr()

        outputs = {}
        for output_name in self._output_names:
            idx = self.engine.get_binding_index(output_name)
            dtype = torch.float32
            shape = tuple(self.context.get_binding_shape(idx))
            device = torch.device('cuda')
            output = torch.empty(size=shape, dtype=dtype, device=device)
            outputs[output_name] = output
            bindings[idx] = output.data_ptr()
        t0 = time.time()
        for i in range(20):
            self.context.execute_async_v2(bindings, torch.cuda.current_stream().cuda_stream)
        t1 = time.time()
        print('trt model time: ', t1 - t0)
        return outputs

def trt_infer(input):
    model = TRTWrapper(trt_path, ['output'])
    output = model(dict(input=input))

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

def onnx_infer(input):
    providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
    ort_session = onnxruntime.InferenceSession(onnx_name, providers=providers)
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input)}
    t0 = time.time()
    for i in range(20):
        ort_outs = ort_session.run(None, ort_inputs)
    t1 = time.time()
    total_time = t1-t0
    print('onnx time: ', total_time)
    return ort_outs

if __name__ == '__main__':
    input = torch.randn(8, 320000).float().cuda()
    trt_infer(input)
    onnx_infer(input)

```

output：

```
trt model time:  12.641133785247803
onnx time:  5.080618858337402
```

**Comment by zerollzeng** [comment]
> * ./trtexec --onnx=wav2vec.onnx --minShapes=input:1x1600 --optShapes=input:8x160000 --maxShapes=input:16x1600000 --saveEngine=wav2vec.engine
> *

This should give you a perf summary at the end, what's the GPU computing time in mean?

**Comment by zerollzeng** [comment]
Also a more fair comparison is build the TRT engine with static shapes. e.g. `--minShapes=input:8x320000 --optShapes=input:8x320000 --maxShapes=input:8x320000`

**Comment by InitialState9** [comment]
> ## Description
> I converted the Fairseq-provided wav2vec2 model into ONNX format, and then converted it into a TRT.Engine using trtexec. Comparing the speed of both, I found that TRT was twice as slow as ONNX.
> 
> ## Environment
> GPU：A100 driver version：525.105.17 docker image: nvcr.io/nvidia/tensorrt:23.08-py3 (install onnx onnxruntime-gpu in the container)
> 
> ## Relevant Files
> The model is quite large（1.2G）
> 
> ## Steps To Reproduce
> 1. onnx to trt:
>    ./trtexec --onnx=wav2vec.onnx --minShapes=input:1x1600 --optShapes=input:8x160000 --maxShapes=input:16x1600000 --saveEngine=wav2vec.engine
> 2. inference code
> 
> ```
> import tensorrt as trt
> import torch
> import time
> from typing import Union, Optional, Sequence,Dict,Any
> import onnxruntime
> 
> trt_path = 'wav2vec.engine'
> onnx_name = 'wav2vec.onnx'
> 
> class TRTWrapper(torch.nn.Module):
>     def __init__(self, engine: Union[str, trt.ICudaEngine],
>                  output_names: Optional[Sequence[str]] = None) -> None:
>         super().__init__()
>         self.engine = engine
>         if isinstance(self.engine, str):
>             with trt.Logger() as logger, trt.Runtime(logger) as runtime:
>                 with open(self.engine, mode='rb') as f:
>                     engine_bytes = f.read()
>                 self.engine = runtime.deserialize_cuda_engine(engine_bytes)
>         self.context = self.engine.create_execution_context()
>         names = [_ for _ in self.engine]
>         input_names = list(filter(self.engine.binding_is_input, names))
>         self._input_names = input_names
>         self._output_names = output_names
> 
>         if self._output_names is None:
>             output_names = list(set(names) - set(input_names))
>             self._output_names = output_names
> 
>     def forward(self, inputs: Dict[str, torch.Tensor]):
>         bindings = [None] * (len(self._input_names) + len(self._output_names))
>         for input_name, input_tensor in inputs.items():
>             idx = self.engine.get_binding_index(input_name)
>             self.context.set_binding_shape(idx, tuple(input_tensor.shape))
>             bindings[idx] = input_tensor.contiguous().data_ptr()
> 
>         outputs = {}
>         for output_name in self._output_names:
>             idx = self.engine.get_binding_index(output_name)
>             dtype = torch.float32
>             shape = tuple(self.context.get_binding_shape(idx))
>             device = torch.device('cuda')
>             output = torch.empty(size=shape, dtype=dtype, device=device)
>             outputs[output_name] = output
>             bindings[idx] = output.data_ptr()
>         t0 = time.time()
>         for i in range(20):
>             self.context.execute_async_v2(bindings, torch.cuda.current_stream().cuda_stream)
>         t1 = time.time()
>         print('trt model time: ', t1 - t0)
>         return outputs
> 
> def trt_infer(input):
>     model = TRTWrapper(trt_path, ['output'])
>     output = model(dict(input=input))
> 
> def to_numpy(tensor):
>     return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
> 
> def onnx_infer(input):
>     providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
>     ort_session = onnxruntime.InferenceSession(onnx_name, providers=providers)
>     ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input)}
>     t0 = time.time()
>     for i in range(20):
>         ort_outs = ort_session.run(None, ort_inputs)
>     t1 = time.time()
>     total_time = t1-t0
>     print('onnx time: ', total_time)
>     return ort_outs
> 
> if __name__ == '__main__':
>     input = torch.randn(8, 320000).float().cuda()
>     trt_infer(input)
>     onnx_infer(input)
> ```
> 
> output：
> 
> ```
> trt model time:  12.641133785247803
> onnx time:  5.080618858337402
> ```

hi, can I ask how you transfer this model to onnx? I tired to transfer a translation transformer to onnx but I haven't figured out where should I start, can you give some hints? Thanks!
