### ISSUE TITLE
skip shape_graph_insert_copies for DS

### ISSUE THREAD

**Issue by Egorundel** [NVIDIA/TensorRT#3302]
## Description

 Hello! What is "skip shape_graph_insert_copies for DS" ? This is an endless loading of this phrase in the terminal.

![Screenshot from 2023-09-07 17-19-19](https://github.com/NVIDIA/TensorRT/assets/65890558/8e499303-67e2-4e7b-90b6-a23c1e5e3a63)

command:
`/home/egorundel/soft/TensorRT-9-0/build/out/trtexec --onnx=YOLOv8.onnx --saveEngine=YOLOv8.trt --minShapes=images:1x3x1x1 --optShapes=images:6x3x512x512 --maxShapes=images:12x3x640x640 --useCudaGraph --useSpinWait --memPoolSize=workspace:3000 --noTF32 --fp16`

## Environment

**TensorRT Version**: 9.0.0

**NVIDIA GPU**: 3060

**NVIDIA Driver Version**: 535

**CUDA Version**: 11.1

**CUDNN Version**: 8.0.4

Operating System: Ubuntu 20.04

Python Version (if applicable): 3.8

**Comment by zerollzeng** [comment]
Could you please share the onnx model with us? We can take a further investigation.

**Comment by Egorundel** [comment]
[Google Drive - YOLOv8-dbs-dbd.onnx](https://drive.google.com/file/d/1vkAocljbZds2OOii8j1Bki4sndbSdA84/view?usp=drive_link)

**Comment by Egorundel** [comment]
@zerollzeng [Google Drive - YOLOv8-dbs-dbd.onnx](https://drive.google.com/file/d/1vkAocljbZds2OOii8j1Bki4sndbSdA84/view?usp=drive_link)

**Comment by zerollzeng** [comment]
I cannot reproduce the issue on my machine with TRT 9.0 and CUDA 12.0. My GPU is L4.

Could you please try CUDA 12?

**Comment by Egorundel** [comment]
@zerollzeng Everything worked for me on TensorRT version 9.0.1, but thank you for taking the time!
