### ISSUE TITLE
Internal cuTensor permutate execute fails on TensorRT 8.2.1 when running C++ Code Written for Inference With TensorRT on Jetson Nano

### ISSUE THREAD

**Issue by mericgeren** [NVIDIA/TensorRT#3308]
## Description

Hello,

i got this error: 

```

1: [reformat.cpp::executeCutensor::385] Error Code 1: CuTensor (Internal cuTensor permutate execute failed)

```
When compiling and then, running a cpp code i wrote for doing inference with TensorRT engine using yolov4 model.

## Environment

**TensorRT Version**: 8.2.1

**NVIDIA GPU**: Tegra X1

**NVIDIA Driver Version**: 23.0

**CUDA Version**: V10.2.300

**CUDNN Version**: 8.2.1

**L4T Version:** 32.7.4

**Jetpack Version:** 4.6.4-b39

Operating System: L4T 32.7.4 (Based on linux 18.04)

Python Version (if applicable): 3.6.9

Tensorflow Version (if applicable): N/A

PyTorch Version (if applicable): 1.10.2

Baremetal or Container (if so, version): N/A

## Steps To Reproduce

1. Right under '~' create a folder.

2. Create a ".cpp" file at the root of the folder you have created.

3. Inside the ".cpp" file write a C++ code to load a TensorRT engine, filter a certain class and show live feed with detected objects inside boxes with these lines: 

```

#include needed libraries here...

const int batchSize = 1;
const int numClasses = 80;
const int numBoxesPerCell = 3;
const int numElementsPerBox = 5 +numClasses;
const float confidenceThreshold = 0.5;

const int gridHeight = 13;
const int gridWidth = 13;
const int stride = 32;

void drawBoundingBox(cv::Mat& frame, const float* detection){

	for(int y = 0; y < gridHeight; y++){
	
		for(int x = 0; x < gridWidth; x++){
		
			for(int box = 0; box < numBoxesPerCell; box++){
			
				const int offset = (y * gridWidth + x) * numBoxesPerCell * numElementsPerBox;
				float confidence = detection[offset + box * numElementsPerBox +4];
				std::vector<float> classScores;
				
				for(int cls = 0; cls < numClasses; cls++){
				
					classScores.push_back(detection[offset + box * numElementsPerBox + 5 + cls]);
				
				}
				
				int theClassIndex = -1;
				float maxClassScore = -1.0;

				for(int cls = 0; cls < numClasses; cls++){
				
					if(classScores[cls] >maxClassScore){
					
						maxClassScore = classScores[cls];
						theClassIndex = cls;
					
					}
				
				}
				
				if(confidence >= confidenceThreshold){
				
					float centerX = (x + detection[offset + box * numElementsPerBox]) * stride;
					float centerY = (y + detection[offset + box * numElementsPerBox + 1]) * stride;
					float width = detection[offset + box *numElementsPerBox +2] * stride;
					float height = detection[offset + box *numElementsPerBox + 3] * stride;
					
					cv::Point pt1(centerX - width/2, centerY - height/2);
					cv::Point pt2(centerX + width/2, centerY + height/2);
					cv::rectangle(frame, pt1, pt2, cv::Scalar(0,255,0), 2);					

				}
				
			}
		
		}
	
	}

}

```

and inside the main:

```	
	
nvinfer1::IRuntime* runtime = nvinfer1::createInferRuntime(gLogger);
nvinfer1::ICudaEngine* engine = runtime->deserializeCudaEngine(tensorrtEngine.data(), sizeOfFile);
nvinfer1::IExecutionContext* context = engine->createExecutionContext();

cv::VideoCapture cap(2, cv::CAP_V4L2);

if(!cap.isOpened()){
	
	std::cerr << "Error: Couldn't open the camera..." << std::endl;
	return -1;
	
}
	
cv::Size inputSize(416,416);	

size_t inputSizeBytes = inputSize.width * inputSize.height * 3;
void* inputImageData;
cudaMalloc(&inputImageData,inputSizeBytes);

float* outputData;
size_t outputSizeBytes = gridHeight * gridWidth * numBoxesPerCell * numElementsPerBox;
	
cudaMallocHost(reinterpret_cast<void**>(&outputData), outputSizeBytes);

std::vector<void*> buffers;
buffers.push_back(inputImageData);
buffers.push_back(outputData);

while(true){
	
	cv::Mat frame;
	cap >> frame;
	cv::Mat resizedFrame;
	cv::resize(frame, resizedFrame, inputSize);
		
	cudaMemcpy(inputImageData, resizedFrame.ptr<float>(), inputSizeBytes, cudaMemcpyHostToDevice);

	context->executeV2(buffers.data());
		
	drawBoundingBox(frame, outputData);

	cv::imshow("Infer", frame);

}

# Freeing resource with cudaFree, cudaFreeHost and destroy() functions here...
#return 0;

```

4. Create a CMakeLists.txt file at the root of your folder.

5. Inside the CMakeLists.txt, write these lines:

```

cmake_minimum_required(VERSION 3.08)
cmake_policy(VERSION 3.09)

project(yolov4_onnx_tensorrt)

find_package(OpenCV REQUIRED)
find_package(CUDA REQUIRED)

include_directories("${CUDA_INCLUDE_DIRS}")

set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -std=c++11)

add_executable(tensorrt_infer tensorrt_infer.cpp)

target_link_libraries(tensorrt_infer PRIVATE ${OpenCV_LIBS})
target_link_libraries(tensorrt_infer PRIVATE ${CUDA_LIBRARIES})
target_link_libraries(tensorrt_infer PRIVATE nvinfer)

find_library(tensorrt_infer libnvinfer.so 
HINTS /usr/lib/aarch64-linux-gnu/)

link_directories(/usr/lib/aarch64-linux-gnu)
link_directories(/usr/include/aarch64-linux-gnu)
link_directories(/usr/lib/aarch64-linux-gnu/tegra)

``` 

6. At the root of your folder, enter these commands one by one:

``` 

mkdir build
cd build
cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda ..
make

``` 

7. After make is successful, copy and paste your ".engine" file into build folder you have created.

8. Run your executable created inside build folder.

9. See that a window showing your live camera feed opens and detects nothing. Also, see these two errors on the terminal:

``` 

1: [reformat.cpp::executeCutensor::385] Error Code 1: CuTensor (Internal cuTensor permutate execute failed)

``` 
and

``` 

1: [context.cpp::setStream::121] Error Code 1: Cudnn (CUDNN_STATUS_MAPPING_ERROR)

``` 

**Note:** The second error repeats constantly.

## Other Things i have tried

**1) Changing `context->executeV2(buffers.data());` to `context->enqueue(batchSize, buffers.data(), 0, nullptr);`**

I got only `3: [executionContext.cpp::enqueueInternal::328] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::328, condition: bindings[x] != nullptr
)` error repeating instead. 

**2) Writing `context->setOptimizationProfile(0);` just before `context->executeV2(buffers.data());`**

I got the same errors.

**3) Rewriting some parts of code to accommodate for 3 output bindings with different sizes and for that using 3 different output datas and calling drawBoundingBox() function 3 times with another parameter specifying outputIndex of output binding and in the function changing gridHeight, gridWidth and stride in regards with output Index given.***

I got: `1: [executionContext.cpp::executeInternal::652] Error Code 1: Cuda Runtime (unspecified launch failure)
Segmentation fault (core dumped)` error and in contrast to previous attempts, it didn't open the window showing the live camera feed and terminated right after the first occurence of the error instead of constantly repeating errors.

**Comment by zerollzeng** [comment]
1. Can you reproduce with trtexec? e.g. `/usr/src/tensorrt/bin/trtexec --onnx=yolov4.plan --fp16`
2. If you can reproduce with (1, could you please try the latest JP release? Because we don't fix bug on old release now.

**Comment by mericgeren** [comment]
It have failed. From the output it gave, i see that it could not open yolov4.plan and thus, failed to parse onnx file. But strangely when i run `trtexec --loadEngine=yolov4.engine` at the root directory of the folder i have created, it passes (it's also the directory where yolov4.engine file resides).

**Comment by zerollzeng** [comment]
> 1. Can you reproduce with trtexec? e.g. `/usr/src/tensorrt/bin/trtexec --onnx=yolov4.plan --fp16`

Sry I mean 'trtexec --onnx=yolov4.onnx --fp16'

**Comment by mericgeren** [comment]
Here is the output of "trtexec --onnx=yolov4.onnx --fp16"  at the root directory of the folder i have created (the directory where yolov4.onnx file also resides):

[trtexec_onnx_output_log.txt](https://github.com/NVIDIA/TensorRT/files/12645245/trtexec_onnx_output_log.txt)
