### ISSUE TITLE
Failed to convert LSTM layer with dynamic batch size with TensorRT 8.6 when running torch_tensorrt on GeForce RTX 3090

### ISSUE THREAD

**Issue by AlexanderSlav** [NVIDIA/TensorRT#3310]
# Description

I am trying to convert a CRNN model with a dynamic batch size and width, but I encountered an error during the conversion process. After some debugging, I was able to localize the problem: the conversion fails when it reaches the LSTM layer using Torch-TensorRT with a dynamic batch size setup.

To further investigate, I created a separate script to convert just the LSTM layer and encountered a runtime error during the compilation process. Specifically, the process fails with the following message:

` Trying to create tensor with negative dimension -1: [1, -1, 256].`

Is dynamic batch size not supported for LSTM models or maybe i do something incorrect ?
It seems that LSTM by itself  is supported with torch_tensorrt or am i wrong ?

## Code to Reproduce

Here is the code snippet that I used for conversion:

```

import torch
import torch_tensorrt
import torch.nn as nn

class RecurrentLayer(nn.Module):
    def __init__(self, input_channels: int, output_channels: int):
        super(RecurrentLayer, self).__init__()
        self._rnn = nn.LSTM(input_channels, output_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y, _ = self._rnn(x)
        return y


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = RecurrentLayer(256, 256)
    model = model.eval().to(device)

    input_data = torch.randn(32, 20, 256).to(device)
    model = torch.jit.trace(model, input_data)

    # L, N, H_in the input shape match LSTM input description
    # N - batch size 
    # L - sequence length
    # H_in - input_size
    
    min_shape=[32, 20, 256]
    opt_shape=[64, 40, 256]
    max_shape=[128, 60, 256]

    fp16 = False

    trt_model = convert_with_torch_tensorrt(model, min_shape, opt_shape, max_shape, fp16)
    _ = trt_model(input_data)
    torch.jit.save(trt_model, "/workdir/rnn_separately.pt")

def convert_with_torch_tensorrt(model, min_input_shape, opt_input_shape, max_input_shape, fp16):
    enabled_precisions = torch.float16 if fp16 else torch.float32

    # Dynamic shapes for the input
    input_spec = torch_tensorrt.Input(
        min_shape=min_input_shape,
        opt_shape=opt_input_shape,
        max_shape=max_input_shape,
        dtype=enabled_precisions,
    )

    with torch_tensorrt.logging.debug():
        trt_model = torch_tensorrt.compile(
            module=model,
            inputs=[input_spec],
            enabled_precisions=[enabled_precisions],
            truncate_long_and_double=True,
        )
    return trt_model

if __name__ == "__main__":
    main()
```

Error log after running the script in the attachment

[error_log_traced_model.txt](https://github.com/NVIDIA/TensorRT/files/12577066/error_log_traced_model.txt)

I also tried replace `torch.jit.trace` with `torch.jit.script ` and it gives me:

`WARNING: [Torch-TensorRT] - Didn't generate any TensorRT engines, the compiler did nothing`

Error log also in attachment.
[error_log_scripted_model.txt](https://github.com/NVIDIA/TensorRT/files/12577065/error_log_scripted_model.txt)

## Environment

For developing i use following docker image [dokai:23.05-pytorch](https://github.com/osai-ai/dokai#pytorch)

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: GeForce RTX 3090

**NVIDIA Driver Version**: 530.30.02

**CUDA Version**:  12.1

**CUDNN Version**:  release 11.8, V11.8.89

## Operating System:

Python Version: Python 3.10.6

PyTorch Version:  2.0.0a0+gite9ebda2

Baremetal or Container: docker image [dokai:23.05-pytorch](https://github.com/osai-ai/dokai#pytorch)

### Expected Behavior
I expect the code to successfully convert the LSTM model with dynamic batch sizes

### Actual Behavior
I get a runtime error with the message `Trying to create tensor with negative dimension -1: [1, -1, 256].`

**Comment by zerollzeng** [comment]
Unfortunately we can't help here since we don't maintain torch-tensorrt. could you please file issue against torch-tensorrt repo? Thanks!

If you think it's a bug of TensorRT, you can export the model to onnx and try with trtexec, if it still fails then we can take a further check.

Sorry about the inconvenience :-)
