### ISSUE TITLE
Tensorrt 8.6 GA : C++ Inference gives diffrence results compared to onnx || pt model python inference

### ISSUE THREAD

**Issue by smyang03** [NVIDIA/TensorRT#3312]
## Description

Hi there

i got a saved model converted to onnx in order to run inference using Tensorrt 8.6 c++ API.
The model is a virtual model from the openai clips model.
(https://clip-as-service.s3.us-east-2.amazonaws.com/models-436c69702d61732d53657276696365/onnx/ViT-B-32/visual.onnx)

checking the embedded value of the image in the model.

but output results are diffrence compared to python
infrence(pt or onnx runtime) to trt in tensorrt c++ api

I checked and found that python inference is correct and tensorrt c++ api is incorrect. (both fp32)

The next log is trtexec verbose log after onnx check. You can check it (
https://drive.google.com/file/d/1carAjQ_oP2xEkia48J0tNztQ5meukaqZ/view?usp=drive_link)

## Environment

**TensorRT Version**:8.6.1GA

**NVIDIA GPU**:GTX3090

**NVIDIA Driver Version**:

**CUDA Version**:12.0

**CUDNN Version**:8.9.4.25

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files
model
(https://clip-as-service.s3.us-east-2.amazonaws.com/models-436c69702d61732d53657276696365/onnx/ViT-B-32/visual.onnx)
log
(https://drive.google.com/file/d/1carAjQ_oP2xEkia48J0tNztQ5meukaqZ/view?usp=drive_link)

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by smyang03** [comment]
python or onnx runtime reuslt is 512 output is correct 

but onnx->trt thre result is Among the 512 output data, only 128 exist and the rest are displayed as 0 values.

What to check 
-- sample test image is black image 
trt and python, onnxruntime engine input image same
-- normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))

##In the case of cuda 11.6 and tensorrt 8.4.1.6, there are 512 output data from trt, but the values ​​do not match the onnxruntime and python output data, so it was updated to tensorrt 8.6.1 and cuda 12.0.


1. sample onnxruntime or python run output 
[ 5.7281e-02,  5.9082e-02, -2.5806e-01,  1.0229e-01,  6.6553e-01,
          3.3496e-01,  9.0179e-03,  6.0156e-01, -1.5430e-01,  1.6296e-01,
          1.6492e-01, -5.4596e-02,  8.6328e-01, -1.6089e-01,  3.5461e-02,
          2.7390e-02, -3.6035e-01,  6.5381e-01,  2.8125e-01,  5.6396e-01,
          5.1172e-01,  1.9135e-02, -9.6436e-02, -1.3391e-01, -2.0642e-01,
         -1.7651e-01,  2.3535e-01, -2.1149e-02, -1.7749e-01, -3.6816e-01,
         -4.9829e-01,  1.2646e-01,  1.4954e-01,  2.6318e-01, -5.9863e-01,
          3.3398e-01, -3.7524e-01,  2.1118e-01,  3.1982e-01,  5.8350e-01,
         -9.8511e-02,  1.1102e-01, -7.3929e-03, -1.1273e-01,  3.4277e-01,
         -1.3242e+00,  2.4597e-01,  2.0569e-01,  2.6196e-01,  3.0029e-01,
         -4.1895e-01, -2.9932e-01,  1.1279e-01,  3.3643e-01, -1.2367e-02,
          1.8506e-01, -1.1340e-01,  9.9121e-02, -4.0131e-02, -6.4941e-02,
         -7.1289e-01, -3.6011e-01, -2.8931e-01, -1.6577e-01, -6.5369e-02,
         -1.5320e-01, -1.8567e-01,  2.8662e-01, -9.9670e-02,  2.7197e-01,
         -3.4424e-01, -1.1804e-01,  2.7319e-01,  2.1594e-01, -3.1665e-01,
          5.7190e-02, -1.6833e-01, -1.3818e-01, -3.5962e-01, -2.7344e-01,
          7.4951e-01,  1.3782e-01, -5.1178e-02, -2.0935e-01,  7.5623e-02,
          1.9861e-01,  5.5322e-01, -2.0776e-01,  3.8306e-01, -2.0715e-01,
          1.3074e-01,  3.1647e-02, -6.7344e+00,  5.4657e-02, -7.8613e-02,
          2.0325e-01, -2.3206e-01,  1.1261e-01, -1.7810e-01, -1.6553e+00,
          1.3130e-02,  5.0568e-02, -3.7183e-01,  4.6600e-02,  4.9756e-01,
         -2.0129e-01, -2.7734e+00, -1.2756e-01, -6.4026e-02, -4.8999e-01,
         -4.5874e-01, -2.5952e-01, -2.4060e-01, -1.4954e-01,  9.4421e-02,
         -3.8916e-01, -2.3828e-01, -2.2034e-02,  3.6768e-01, -2.3779e-01,
         -2.1338e-01,  5.2783e-01, -5.2704e-02, -4.9585e-01, -5.1953e-01,
         -3.2056e-01, -1.9922e-01,  1.8335e-01, -2.4146e-01,  3.0472e-02,
         -1.4062e-01, -1.6443e-01,  2.0007e-01,  8.1885e-01,  8.0859e-01,
         -5.3101e-02, -1.1909e-02,  1.7249e-01, -4.0894e-01, -8.2947e-02,
          7.6294e-02, -1.4160e-01, -1.0974e-01,  3.9307e-01, -3.0228e-02,
          1.1829e-01,  5.9448e-02,  7.5989e-02, -2.9199e-01,  2.2778e-01,
          1.4648e-01, -4.9780e-01,  9.1699e-01,  1.4587e-01,  1.0913e-01,
         -3.0029e-01,  1.4392e-01, -3.3862e-01,  2.2986e-01,  3.2739e-01,
         -4.0161e-01,  5.9906e-02,  1.8579e-01, -2.9028e-01, -3.2617e-01,
          4.1504e-02, -2.6074e-01,  2.1622e-02, -9.3201e-02, -1.6504e-01,
          1.2646e-01, -5.0850e-03,  1.1823e-01, -4.1919e-01, -3.8208e-01,
          8.6121e-02, -4.6216e-01,  2.0459e-01,  4.6558e-01, -6.6040e-02,
          5.5859e-01,  6.7871e-02,  1.4771e-01,  8.5815e-02, -4.0137e-01,
          2.3364e-01,  2.1289e-01,  2.2812e-02, -2.5806e-01,  1.9934e-01,
          6.9336e-01,  8.4351e-02, -5.7275e-01, -1.0596e-01, -1.2803e+00,
         -1.7041e-01,  4.2755e-02, -1.1578e-01, -2.3059e-01, -4.2871e-01,
          3.9160e-01, -6.4941e-02,  4.2163e-01, -1.5796e-01,  2.7783e-01,
         -6.2109e-01, -6.9458e-02, -2.1863e-01, -1.3123e-02,  8.2886e-02,
          1.2048e-01, -4.7559e-01, -3.0371e-01,  3.2397e-01, -4.5239e-01,
         -3.6108e-01,  3.2642e-01,  3.6914e-01, -9.7839e-02,  1.4783e-01,
         -3.1592e-01,  3.0151e-01,  1.9141e-01, -1.4429e-01,  3.0884e-01,
         -3.2440e-02,  6.5063e-02, -1.5112e-01, -5.2429e-02, -2.3422e-02,
          4.9469e-02,  5.3650e-02,  5.4834e-01,  1.0000e+00, -7.5073e-02,
         -2.1045e-01,  3.1372e-01, -1.6431e-01, -1.9272e-02,  9.0103e-03,
          2.9956e-01,  3.2544e-01,  4.5947e-01, -2.0142e-01,  2.9663e-01,
         -8.1055e-01,  2.1255e-02, -6.2354e-01, -3.4399e-01,  7.5684e-01,
         -4.1968e-01,  3.1494e-01,  1.1798e-01,  4.6387e-02,  3.0493e-01,
         -9.0942e-02,  2.7588e-02,  1.4319e-01,  1.8779e+00, -6.0352e-01,
         -7.0984e-02, -1.4087e-01,  3.2275e-01,  5.5176e-01,  2.5293e-01,
         -4.8682e-01, -9.3567e-02, -6.2134e-02, -2.6489e-01, -4.9512e-01,
          2.1069e-01,  3.1104e-01, -2.5073e-01,  1.3025e-01, -3.9380e-01,
          4.0601e-01, -1.5662e-01, -3.9160e-01, -5.1562e-01, -9.6130e-02,
          1.8054e-01,  4.8309e-02, -5.2783e-01,  1.3330e-01,  3.4180e-01,
          1.9080e-01, -1.2891e+00,  1.6464e-02,  1.1603e-01,  5.1086e-02,
          2.6855e-01, -7.3425e-02,  4.0308e-01,  9.7595e-02, -1.1987e-01,
          3.5919e-02, -4.4092e-01, -8.7830e-02, -8.2825e-02,  3.8013e-01,
         -5.2490e-02,  6.0791e-01,  3.0151e-01, -1.8457e-01,  1.3147e-01,
          2.0105e-01, -1.1786e-01,  5.5078e-01,  9.6313e-02,  3.2935e-01,
         -5.0323e-02,  4.7211e-02,  8.1689e-01, -1.6235e-01, -4.9469e-02,
         -3.9368e-02,  4.2334e-01,  1.6556e-02,  2.4719e-01,  3.8843e-01,
          5.1855e-01, -7.1973e-01, -3.0273e-01, -1.9727e-01,  4.0161e-02,
          4.2725e-01,  1.7590e-01,  2.1118e-01, -4.9756e-01, -1.5552e-01,
          1.3440e-01, -3.3545e-01, -1.1719e-01, -1.7920e-01, -5.9662e-02,
         -5.3369e-01, -1.1035e-01,  1.5698e-01,  5.2686e-01, -8.6243e-02,
         -3.5645e-01, -6.0400e-01,  3.6597e-01,  2.0898e-01, -1.7493e-01,
         -9.0881e-02,  5.8301e-01, -6.1188e-02, -1.5649e-01, -1.1255e-01,
         -9.9951e-01, -7.3792e-02,  2.0117e-01,  2.4811e-02,  1.6919e-01,
          7.8320e-01, -4.1650e-01, -2.1375e-01, -1.0681e-01, -1.1151e-01,
          2.0554e-02, -1.7822e-02,  2.7563e-01, -1.6113e-01,  6.6504e-01,
          1.3745e-01, -4.7339e-01, -3.7012e-01,  1.8494e-01,  1.8457e-01,
          1.5515e-01,  9.7809e-03,  1.1086e-02,  1.8750e-01,  2.1692e-01,
          1.2610e-01,  9.5215e-01,  1.8250e-01,  6.1230e-01,  7.1338e-01,
          1.0376e-01, -2.8589e-01, -1.2408e-01, -2.9199e-01,  3.3569e-01,
          8.3154e-01, -1.9019e-01,  2.0532e-01, -1.6003e-03, -9.9414e-01,
          9.1309e-02,  1.5552e-01, -3.7061e-01,  6.3416e-02,  1.9043e-01,
          2.0496e-01, -4.1626e-01, -8.5889e-01, -2.6489e-01,  2.2607e-01,
         -1.2683e-01,  2.4731e-01, -4.3945e-01,  1.1493e-01, -1.1554e-01,
         -1.8970e-01, -8.9478e-02,  2.5122e-01,  6.4941e-02,  1.3306e-01,
         -1.0547e-01,  1.3586e-01, -8.2245e-03, -2.8418e-01, -4.1089e-01,
         -2.9810e-01,  9.6252e-02, -1.6138e-01, -3.5791e-01, -2.2852e-01,
          2.6840e-02, -3.9136e-01,  3.1470e-01, -7.9590e-01, -1.0980e-01,
         -1.9678e-01, -5.1758e-01,  3.9209e-01, -3.5273e+00,  1.9495e-01,
          2.0410e-01,  2.9175e-01, -9.1992e-01, -1.2140e-01, -4.4409e-01,
         -7.2205e-02,  8.4766e-01,  3.6957e-02, -8.6670e-02, -1.0303e-01,
         -1.2299e-01,  3.0591e-01,  1.8909e-01,  3.3105e-01,  4.7974e-01,
          7.4524e-02, -4.6906e-02, -1.1200e-01,  1.0968e-01, -4.6899e-01,
         -2.8491e-01,  2.2339e-01,  2.9224e-01, -1.0474e-01, -1.5369e-01,
         -4.6436e-01,  1.1328e+00, -4.1138e-01, -3.3374e-01, -1.9995e-01,
         -2.3035e-01, -4.1235e-01, -1.5723e-01, -1.7786e-01,  7.5391e-01,
          6.4990e-01, -1.5686e-01,  1.7725e-01, -6.0272e-02,  1.9177e-01,
          1.3171e-01,  6.7529e-01, -1.1371e-01, -3.8794e-01, -3.3643e-01,
          1.7188e-01,  1.8555e-01, -1.4197e-01,  2.1875e-01,  1.3037e-01,
          1.2585e-01, -5.0098e-01,  4.2847e-02,  1.2415e-01, -6.3019e-03,
          2.0581e-01, -2.0532e-01,  2.4988e-01, -2.1594e-01, -2.2266e-01,
          3.7598e-01, -1.1688e-01,  7.1472e-02, -3.3716e-01,  9.2957e-02,
         -1.6797e-01,  5.1331e-02, -9.8389e-02, -2.1545e-01, -2.4109e-01,
          3.3252e-01, -7.8552e-02, -1.1908e-01,  4.6436e-01, -4.5685e-02,
          5.1660e-01, -7.7271e-02, -5.2948e-02, -1.0516e-01,  4.8828e-01,
         -3.1616e-01,  1.4502e-01]], device='cuda:0', dtype=torch.float16)

1. trt  run output (Likewise, the textual model also shows the same results.)
2. 0 231 textual value over 1 = 0.000000000
0 232 textual value over 1 = 0.000000000
0 233 textual value over 1 = 0.000000000
0 234 textual value over 1 = 0.000000000
0 235 textual value over 1 = 0.000000000
0 236 textual value over 1 = 0.000000000
0 237 textual value over 1 = 0.000000000
0 238 textual value over 1 = 0.000000000
0 239 textual value over 1 = 0.000000000
0 240 textual value over 1 = 0.000000000
0 241 textual value over 1 = 0.000000000
0 242 textual value over 1 = 0.000000000
0 243 textual value over 1 = 0.000000000
0 244 textual value over 1 = 0.000000000
0 245 textual value over 1 = 0.000000000
0 246 textual value over 1 = 0.000000000
0 247 textual value over 1 = 0.000000000
0 248 textual value over 1 = 0.000000000
0 249 textual value over 1 = 0.000000000
0 250 textual value over 1 = 0.000000000
0 251 textual value over 1 = 0.000000000
0 252 textual value over 1 = 0.000000000
0 253 textual value over 1 = 0.000000000
0 254 textual value over 1 = 0.000000000
0 255 textual value over 1 = 0.000000000
0 256 textual value over 1 = 0.000000000
0 257 textual value over 1 = 0.000000000
0 258 textual value over 1 = 0.000000000
0 259 textual value over 1 = 0.000000000
0 260 textual value over 1 = 0.000000000
0 261 textual value over 1 = 0.000000000
0 262 textual value over 1 = 0.000000000
0 263 textual value over 1 = 0.000000000
0 264 textual value over 1 = 0.000000000
0 265 textual value over 1 = 0.000000000
0 266 textual value over 1 = 0.000000000
0 267 textual value over 1 = 0.000000000
0 268 textual value over 1 = 0.000000000
0 269 textual value over 1 = 0.000000000
0 270 textual value over 1 = 0.000000000
0 271 textual value over 1 = 0.000000000
0 272 textual value over 1 = 0.000000000
0 273 textual value over 1 = 0.000000000
0 274 textual value over 1 = 0.000000000
0 275 textual value over 1 = 0.000000000
0 276 textual value over 1 = 0.000000000
0 277 textual value over 1 = 0.000000000
0 278 textual value over 1 = 0.000000000
0 279 textual value over 1 = 0.000000000
0 280 textual value over 1 = 0.000000000
0 281 textual value over 1 = 0.000000000
0 282 textual value over 1 = 0.000000000
0 283 textual value over 1 = 0.000000000
0 284 textual value over 1 = 0.000000000
0 285 textual value over 1 = 0.000000000
0 286 textual value over 1 = 0.000000000
0 287 textual value over 1 = 0.000000000
0 288 textual value over 1 = 0.000000000
0 289 textual value over 1 = 0.000000000
0 290 textual value over 1 = 0.000000000
0 291 textual value over 1 = 0.000000000
0 292 textual value over 1 = 0.000000000
0 293 textual value over 1 = 0.000000000
0 294 textual value over 1 = 0.000000000
0 295 textual value over 1 = 0.000000000
0 296 textual value over 1 = 0.000000000
0 297 textual value over 1 = 0.000000000
0 298 textual value over 1 = 0.000000000
0 299 textual value over 1 = 0.000000000
0 300 textual value over 1 = 0.000000000
0 301 textual value over 1 = 0.000000000
0 302 textual value over 1 = 0.000000000
0 303 textual value over 1 = 0.000000000
0 304 textual value over 1 = 0.000000000
0 305 textual value over 1 = 0.000000000
0 306 textual value over 1 = 0.000000000
0 307 textual value over 1 = 0.000000000
0 308 textual value over 1 = 0.000000000
0 309 textual value over 1 = 0.000000000
0 310 textual value over 1 = 0.000000000
0 311 textual value over 1 = 0.000000000
0 312 textual value over 1 = 0.000000000
0 313 textual value over 1 = 0.000000000
0 314 textual value over 1 = 0.000000000
0 315 textual value over 1 = 0.000000000
0 316 textual value over 1 = 0.000000000
0 317 textual value over 1 = 0.000000000
0 318 textual value over 1 = 0.000000000
0 319 textual value over 1 = 0.000000000
0 320 textual value over 1 = 0.000000000
0 321 textual value over 1 = 0.000000000
0 322 textual value over 1 = 0.000000000
0 323 textual value over 1 = 0.000000000
0 324 textual value over 1 = 0.000000000
0 325 textual value over 1 = 0.000000000
0 326 textual value over 1 = 0.000000000
0 327 textual value over 1 = 0.000000000
0 328 textual value over 1 = 0.000000000
0 329 textual value over 1 = 0.000000000
0 330 textual value over 1 = 0.000000000
0 331 textual value over 1 = 0.000000000
0 332 textual value over 1 = 0.000000000
0 333 textual value over 1 = 0.000000000
0 334 textual value over 1 = 0.000000000
0 335 textual value over 1 = 0.000000000
0 336 textual value over 1 = 0.000000000
0 337 textual value over 1 = 0.000000000
0 338 textual value over 1 = 0.000000000
0 339 textual value over 1 = 0.000000000
0 340 textual value over 1 = 0.000000000
0 341 textual value over 1 = 0.000000000
0 342 textual value over 1 = 0.000000000
0 343 textual value over 1 = 0.000000000
0 344 textual value over 1 = 0.000000000
0 345 textual value over 1 = 0.000000000
0 346 textual value over 1 = 0.000000000
0 347 textual value over 1 = 0.000000000
0 348 textual value over 1 = 0.000000000
0 349 textual value over 1 = 0.000000000
0 350 textual value over 1 = 0.000000000
0 351 textual value over 1 = 0.000000000
0 352 textual value over 1 = 0.000000000
0 353 textual value over 1 = 0.000000000
0 354 textual value over 1 = 0.000000000
0 355 textual value over 1 = 0.000000000
0 356 textual value over 1 = 0.000000000
0 357 textual value over 1 = 0.000000000
0 358 textual value over 1 = 0.000000000
0 359 textual value over 1 = 0.000000000
0 360 textual value over 1 = 0.000000000
0 361 textual value over 1 = 0.000000000
0 362 textual value over 1 = 0.000000000
0 363 textual value over 1 = 0.000000000
0 364 textual value over 1 = 0.000000000
0 365 textual value over 1 = 0.000000000
0 366 textual value over 1 = 0.000000000
0 367 textual value over 1 = 0.000000000
0 368 textual value over 1 = 0.000000000
0 369 textual value over 1 = 0.000000000
0 370 textual value over 1 = 0.000000000
0 371 textual value over 1 = 0.000000000
0 372 textual value over 1 = 0.000000000
0 373 textual value over 1 = 0.000000000
0 374 textual value over 1 = 0.000000000
0 375 textual value over 1 = 0.000000000
0 376 textual value over 1 = 0.000000000
0 377 textual value over 1 = 0.000000000
0 378 textual value over 1 = 0.000000000
0 379 textual value over 1 = 0.000000000
0 380 textual value over 1 = 0.000000000
0 381 textual value over 1 = 0.000000000
0 382 textual value over 1 = 0.000000000
0 383 textual value over 1 = 0.000000000
0 384 textual value over 1 = 0.000000000
0 385 textual value over 1 = 0.000000000
0 386 textual value over 1 = 0.000000000
0 387 textual value over 1 = 0.000000000
0 388 textual value over 1 = 0.000000000
0 389 textual value over 1 = 0.000000000
0 390 textual value over 1 = 0.000000000
0 391 textual value over 1 = 0.000000000
0 392 textual value over 1 = 0.000000000
0 393 textual value over 1 = 0.000000000
0 394 textual value over 1 = 0.000000000
0 395 textual value over 1 = 0.000000000
0 396 textual value over 1 = 0.000000000
0 397 textual value over 1 = 0.000000000
0 398 textual value over 1 = 0.000000000
0 399 textual value over 1 = 0.000000000
0 400 textual value over 1 = 0.000000000
0 401 textual value over 1 = 0.000000000
0 402 textual value over 1 = 0.000000000
0 403 textual value over 1 = 0.000000000
0 404 textual value over 1 = 0.000000000
0 405 textual value over 1 = 0.000000000
0 406 textual value over 1 = 0.000000000
0 407 textual value over 1 = 0.000000000
0 408 textual value over 1 = 0.000000000
0 409 textual value over 1 = 0.000000000
0 410 textual value over 1 = 0.000000000
0 411 textual value over 1 = 0.000000000
0 412 textual value over 1 = 0.000000000
0 413 textual value over 1 = 0.000000000
0 414 textual value over 1 = 0.000000000
0 415 textual value over 1 = 0.000000000
0 416 textual value over 1 = 0.000000000
0 417 textual value over 1 = 0.000000000
0 418 textual value over 1 = 0.000000000
0 419 textual value over 1 = 0.000000000
0 420 textual value over 1 = 0.000000000
0 421 textual value over 1 = 0.000000000
0 422 textual value over 1 = 0.000000000
0 423 textual value over 1 = 0.000000000
0 424 textual value over 1 = 0.000000000
0 425 textual value over 1 = 0.000000000
0 426 textual value over 1 = 0.000000000
0 427 textual value over 1 = 0.000000000
0 428 textual value over 1 = 0.000000000
0 429 textual value over 1 = 0.000000000
0 430 textual value over 1 = 0.000000000
0 431 textual value over 1 = 0.000000000
0 432 textual value over 1 = 0.000000000
0 433 textual value over 1 = 0.000000000
0 434 textual value over 1 = 0.000000000
0 435 textual value over 1 = 0.000000000
0 436 textual value over 1 = 0.000000000
0 437 textual value over 1 = 0.000000000
0 438 textual value over 1 = 0.000000000
0 439 textual value over 1 = 0.000000000
0 440 textual value over 1 = 0.000000000
0 441 textual value over 1 = 0.000000000
0 442 textual value over 1 = 0.000000000
0 443 textual value over 1 = 0.000000000
0 444 textual value over 1 = 0.000000000
0 445 textual value over 1 = 0.000000000
0 446 textual value over 1 = 0.000000000
0 447 textual value over 1 = 0.000000000
0 448 textual value over 1 = 0.000000000
0 449 textual value over 1 = 0.000000000
0 450 textual value over 1 = 0.000000000
0 451 textual value over 1 = 0.000000000
0 452 textual value over 1 = 0.000000000
0 453 textual value over 1 = 0.000000000
0 454 textual value over 1 = 0.000000000
0 455 textual value over 1 = 0.000000000
0 456 textual value over 1 = 0.000000000
0 457 textual value over 1 = 0.000000000
0 458 textual value over 1 = 0.000000000
0 459 textual value over 1 = 0.000000000
0 460 textual value over 1 = 0.000000000
0 461 textual value over 1 = 0.000000000
0 462 textual value over 1 = 0.000000000
0 463 textual value over 1 = 0.000000000
0 464 textual value over 1 = 0.000000000
0 465 textual value over 1 = 0.000000000
0 466 textual value over 1 = 0.000000000
0 467 textual value over 1 = 0.000000000
0 468 textual value over 1 = 0.000000000
0 469 textual value over 1 = 0.000000000
0 470 textual value over 1 = 0.000000000
0 471 textual value over 1 = 0.000000000
0 472 textual value over 1 = 0.000000000
0 473 textual value over 1 = 0.000000000
0 474 textual value over 1 = 0.000000000
0 475 textual value over 1 = 0.000000000
0 476 textual value over 1 = 0.000000000
0 477 textual value over 1 = 0.000000000
0 478 textual value over 1 = 0.000000000
0 479 textual value over 1 = 0.000000000
0 480 textual value over 1 = 0.000000000
0 481 textual value over 1 = 0.000000000
0 482 textual value over 1 = 0.000000000
0 483 textual value over 1 = 0.000000000
0 484 textual value over 1 = 0.000000000
0 485 textual value over 1 = 0.000000000
0 486 textual value over 1 = 0.000000000
0 487 textual value over 1 = 0.000000000
0 488 textual value over 1 = 0.000000000
0 489 textual value over 1 = 0.000000000
0 490 textual value over 1 = 0.000000000
0 491 textual value over 1 = 0.000000000
0 492 textual value over 1 = 0.000000000
0 493 textual value over 1 = 0.000000000
0 494 textual value over 1 = 0.000000000
0 495 textual value over 1 = 0.000000000
0 496 textual value over 1 = 0.000000000
0 497 textual value over 1 = 0.000000000
0 498 textual value over 1 = 0.000000000
0 499 textual value over 1 = 0.000000000
0 500 textual value over 1 = 0.000000000
0 501 textual value over 1 = 0.000000000
0 502 textual value over 1 = 0.000000000
0 503 textual value over 1 = 0.000000000
0 504 textual value over 1 = 0.000000000
0 505 textual value over 1 = 0.000000000
0 506 textual value over 1 = 0.000000000
0 507 textual value over 1 = 0.000000000
0 508 textual value over 1 = 0.000000000
0 509 textual value over 1 = 0.000000000
0 510 textual value over 1 = 0.000000000
0 511 textual value over 1 = 0.000000000

**Comment by smyang03** [comment]
Found the problem. Something went wrong in preprocessing. 224 224 This problem occurred because the padding value was entered when performing cudamemcpy on the image. thanks for your kind

**Comment by PhilChina** [comment]
Cudamemcpy  is migrating data from host to device, what is the specific cause of the error? And how to solve it? Can give some solutions
