### ISSUE TITLE
TensorRT return wrong ouputs which contain custom plugin, but return correctly when add custom plugin extraly as model output

### ISSUE THREAD

**Issue by yank666** [NVIDIA/TensorRT#3313]
I'm facing some correctness problems using my model which include sevaral custom plugin layer,and trt run inference produce a strange phenomenon:
if my return layers don't have  custom plugin layer,  the return ouputs  all have wrong results which different with torch result, but when i add custom plugin layer extraly as return outputs,  all return ouputs coincident with torch result 

What causes this phenomenon？

my version
cuda:11.7
trt :8.6.1GA

```
import os
import numpy as np
from polygraphy.backend.trt.loader import LoadPlugins
from polygraphy.backend.trt import (
    TrtRunner, EngineFromNetwork, NetworkFromOnnxPath,
    CreateConfig, Profile, SaveEngine
)


config = CreateConfig(max_workspace_size=10 * (1 << 30), builder_optimization_level=0)

def load_trt_plugin(plugin_path):
    if not os.path.exists(plugin_path):
        raise ValueError("Trt plugin {path} not exist! Please check".format(path = plugin_path))
    return LoadPlugins(plugins=[plugin_path])()

def generate_engine(onnx_path, engin_path=None):
    if not os.path.exists(onnx_path):
       raise ValueError("Onnx model {path} not exist! Please check".format(path = onnx_path))
    engine = EngineFromNetwork(NetworkFromOnnxPath(onnx_path), config=config)
    if engin_path != None:
        engine = SaveEngine(engine=engine, path=engine_path)
    return engine

def run_trt(onnx_path, plugin_path, input_list):
    plugin = load_trt_plugin(plugin_path)
    trt_engine = generate_engine(onnx_path)
    input_dict = {}
    for i in range(len(input_list)):
        input_dict["input"+str(i)] = input_list[i]

    #print(input_dict)
    output = {}
    with TrtRunner(engine=trt_engine) as trt:
        output = trt.infer(feed_dict=input_dict)
    return output
```

**Comment by yank666** [comment]
![Uploading image.png…]()

**Comment by yank666** [comment]
i mean I need add these middle custom plugin in 
nn.mudule's return extraly，then all outputs correct，if middle custom plugin not acting as outputs，the convs after these custom plugin will wrong

**Comment by yank666** [comment]
if i want to got correct，i must put custom plugin as extraly output node，otherwise the next layer always produce nan element

**Comment by ttyio** [comment]
@yank666 , are you building the FP32 engine? which GPU are you working on? thanks!

**Comment by yank666** [comment]
yes ,i use fp32 engine, GPU is P100

**Comment by yank666** [comment]
i use another V100  GPu,  the phenomenon  reproduce

**Comment by ttyio** [comment]
@yank666 have you checked the plugin `supportsFormatCombination` ? does the plugin support different data layout?

**Comment by yank666** [comment]
i got ,the plugin did't traversal all elements of ouputs ,  i use cumemset to set plugin ouput to 0, resolve it
