### ISSUE TITLE
Fp16 engine（generate on windows with TRT861） get stuck on linux (TRT 861)

### ISSUE THREAD

**Issue by BaofengZan** [NVIDIA/TensorRT#3317]
## Description

The fp16 engine generated on windows is stuck when infer in the linux（same environment）. But the fp32 model generated on window runs normally on linux. In addition, the fp16 engine generated on linux also works fine on linux.

## Environment

**TensorRT Version**:  8.6.1

**NVIDIA GPU**:    3070

**NVIDIA Driver Version**:  573.13

**CUDA Version**:    12.1

**CUDNN Version**: 8.9.1

Operating System:    windows11   linux22.02

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

**Comment by zerollzeng** [comment]
We don't support engine compatibility between Windows and Linux(if it work in some case just mean you are lucky), is there any specific reason you need to do this?
