### ISSUE TITLE
buildEngineWithConfig(network, config); failure of TensorRT 8.4 when running CPP onnx2i8trt on GPU 3060

### ISSUE THREAD

**Issue by YaoJiawei329** [NVIDIA/TensorRT#3322]
## Description

I tried to convert onnx to int8 trtengine via CPP API, but it fails in buildEngineWithConfig();
It has 2 uncertain error result: one error is, after all calibrate pictures:
D:\xxx\out\build\x64-Release\Longi_popian_quant.exe (进程 34192)已退出，代码为 -1073740940
and another error is in calibration, 
![企业微信截图_16950240494145](https://github.com/NVIDIA/TensorRT/assets/56985607/dc5933af-a1f1-44c7-8308-16158a301238)

## Environment

**TensorRT Version**: 8.4.1.5

**NVIDIA GPU**: 3060

**NVIDIA Driver Version**: 536.23

**CUDA Version**: 11.7

**CUDNN Version**: cudnn-windows-x86_64-8.4.1.50_cuda11.6

Operating System: win10

Python Version (if applicable): -

Tensorflow Version (if applicable): -

PyTorch Version (if applicable): -

Baremetal or Container (if so, version): -

## Relevant Files

https://github.com/YaoJiawei329/onnx2int8trt/blob/main/Longi_popian_quant.cpp
https://github.com/YaoJiawei329/onnx2int8trt/blob/main/CMakeLists.txt
**Model link**: https://github.com/YaoJiawei329/onnx2int8trt/blob/main/2023-8-19-popian_15.onnx

## Steps To Reproduce

**Commands or scripts**: -

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: I have tried v8.6.1.6, the same error occured.

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): fp16 engine can run.
trtexec --onnx=xxx.onnx --saveEngine=xxx_i8.engine --int8 can also PASS.

**Comment by zerollzeng** [comment]
You description is broken. 

BTW to calibrate an onnx model, you can use our polygraphy tools. see https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert/01_int8_calibration_in_tensorrt

**Comment by YaoJiawei329** [comment]
![1695013677374](https://github.com/NVIDIA/TensorRT/assets/56985607/c4f09e06-22fb-46fc-8371-9617746bd907)
Thank you, but polygraphy does not work either. I have test 2 onnx model, the same error occurs.

> You description is broken.
> 
> BTW to calibrate an onnx model, you can use our polygraphy tools. see https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert/01_int8_calibration_in_tensorrt

**Comment by YaoJiawei329** [comment]
![1695015737221](https://github.com/NVIDIA/TensorRT/assets/56985607/6e9cead1-ca58-4b7d-853e-051edcbdb300)
And on my another computer, it shows a different ERROR.

**Comment by YaoJiawei329** [comment]
Besides, when I use cpp API to convert onnx to int8 engine, if the calibration data folder has less than 70 pictures, it worked, but if I put more than 90 pictures in calibration data folder, it died like this: 
![1695016402954](https://github.com/NVIDIA/TensorRT/assets/56985607/2f55084d-6871-4997-8628-694f50b48d2d)

**Comment by YaoJiawei329** [comment]
I have solve the problem, the reason is there has another nvinfer.dll in envirment varible PATH above the correct nvinfer.dll in CUDA.
