### ISSUE TITLE
Could not parse ONNX correctly failure of TensorRT 8.6.1 when running SDXL on GPU A30

### ISSUE THREAD

**Issue by LSC527** [NVIDIA/TensorRT#3324]
## Description
After export my SDXL model to onnx, when build trt engine, error occurred:
```
[Matrix Multiply]_output: tensor volume exceeds (2^31)-1, dimensions are [2,5,16384,16384])
[!] Could not parse ONNX correctly
```

## Environment

**TensorRT Version**: 8.6.1 

**NVIDIA GPU**: A30

**NVIDIA Driver Version**: 525.85.12

**CUDA Version**: 12.2

**CUDNN Version**: 8904

Operating System: centos 7.3

Python Version (if applicable): 3.10

Tensorflow Version (if applicable):

PyTorch Version (if applicable): ngc pytorch 23.08

Baremetal or Container (if so, version): ngc pytorch 23.08

## Relevant Files

**Model link**:

## Steps To Reproduce

following https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_tensorrt_img2img.py

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by ttyio** [comment]
It is limitation of TRT that we support max tensor volume 2G elements.

**Comment by LSC527** [comment]
Thanks for your reply.
