### ISSUE TITLE
Gemm dim error Onnx file parse

### ISSUE THREAD

**Issue by renhaosw** [NVIDIA/TensorRT#333]
## Description
When I use Gemm In a Onnx file ： DEFINE_BUILTIN_OP_IMPORTER(Gemm)
Here 
```cpp
bool canUseFC = inputs.at(0).is_tensor() && inputs.at(1).is_weights() && inputs.at(2).is_weights()....  
```

`canUseFc` is true,but below error happen:
```
(Unnamed Layer* 2) [Fully Connected]: at least 4 dimensions are required for input
```

## Environment

**TensorRT Version 6.0.15**: 
**GPU Type P100**: 
**Nvidia Driver Version **: 
**CUDA Version 10.0**: 
**CUDNN Version 6.7.5**: 
**Operating System + Version ubuntu 16.04**:

**Comment by rmccorm4** [comment]
Hi @renhaosw,

How are you parsing your ONNX model? What commands did you run to get the error?

Can you share a simple ONNX model that reproduces this error so I can better debug?

**Comment by rmccorm4** [comment]
Closing since no response.
