### ISSUE TITLE
graphOptimizer.cpp::calcSliceGroupSize::2724

### ISSUE THREAD

**Issue by ForestWang** [NVIDIA/TensorRT#3338]
ENV:

3090, TRT8.6.1.6, cuda11.6
get the error : [E] [TRT] 2: [graphOptimizer.cpp::calcSliceGroupSize::2724] Error Code 2: Internal Error (Assertion slice->inputs.size() == 1 failed. )

but the same codes can run with xavier NX with jetpack5.12(cuda11.4+TRT5.2)

**Comment by zerollzeng** [comment]
> jetpack5.12(cuda11.4+TRT5.2)

typo here?

Could you please provide more details or provide a reproduce here? Your slice layer has more than 1 input?

**Comment by ForestWang** [comment]
https://github.com/pcb9382/StereoAlgorithms/tree/main/HitNet 
using this repo with the onnx model attached can reproduce this issue.(3090, TRT8.6.1.6, cuda11.6)
[HintNet_float.zip](https://github.com/NVIDIA/TensorRT/files/12744816/HintNet_float.zip)

**Comment by zerollzeng** [comment]
I've filed internal bug 4308838 to track this.

**Comment by usama-baloch** [comment]
Hi @zerollzeng, I also got the same error on my model using tensorrt, I debugged it multiple times and found out that when the slice layer gets called two times respectively with the same input shape then it raises an error else it works fine. maybe some kind of caching it is doing internally.

**Comment by zerollzeng** [comment]
@usama-baloch  We are checking this internally. would be great if you can provide your minimal reproduce. Many thanks!

**Comment by usama-baloch** [comment]
@zerollzeng Not sure this is the required way to use tensorrt, but I was using torch2trt on `google/mobilebert-uncased` model and it calls the converter of the pad function which uses slice_layer: [Slice Layer](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-852/operators/docs/Slice.html) to slice out the `input_trt` data with a given `start`, `stride` and `size` indices.  The problem appears when the same slice layer gets called twice with the same shape: `shape=(1,7,128)` and `start`, `stride`, and `size` indices at a time.

After the above point then I tried to reshape the second time called slice layer into some other shape like: `shape=(1,8,129)` then it works fine. Maybe my assumptions are wrong but this could help us to find the exact problem and a better solution for this.

**Comment by phoenixfury** [comment]
Hello, I am having the same exact problem with the same exact onnx model. Any updates on this issue?

**Comment by zerollzeng** [comment]
This issue has been fixed in TRT 9.2. please wait for the release and try again. Thanks!

I'm closing this issue.
