### ISSUE TITLE
[Matrix Multiply]: only activation types allowed as input to this layer

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/TensorRT#334]
## Description
I use onnx parser to parse a model. It failed with this kind of error.

Why matrix multiply need a activation as input ? I can't understand.

## Environment

**TensorRT Version**:  Tensorrt7
**GPU Type**:  geforce 1080
**Nvidia Driver Version**:  nvidia 413
**CUDA Version**:  10.0
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @ligonzheng ,

Please provide a minimal code example + an ONNX model that can reproduce this error so I can better debug.

**Comment by rmccorm4** [comment]
Closing since no response.

**Comment by zhouyuangan** [comment]
@ligonzheng Had you solved the problem? I met the same problem.

**Comment by zhouyuangan** [comment]
Here is my code example, I had solved this problem. The problem occurs at `createEngine` function.
```
void APIToModel(unsigned int maxBatchSize, IHostMemory** modelStream)
{
    // Create builder
    IBuilder* builder = createInferBuilder(gLogger);

    // Create model to populate the network, then set the outputs and create an engine
    ICudaEngine* engine = createEngine(maxBatchSize, builder, DataType::kINT);
    assert(engine != nullptr);

    // Serialize the engine
    (*modelStream) = engine->serialize();

    // Close everything down
    engine->destroy();
    builder->destroy();
}
```
So the `data` will be kINT type，the `IConvolutionLayer` should accept `kFLOAT` type data.
```
// Create the engine using only the API and not any parser.
ICudaEngine* createEngine(unsigned int maxBatchSize, IBuilder* builder, DataType dt)
{
    INetworkDefinition* network = builder->createNetwork();
    // Create input tensor of shape {} name INPUT_BLOB_NAME
    ITensor* data = network->addInput(INPUT_BLOB_NAME, dt, Dims4{ 1, 1, INPUT_H, INPUT_W });
    assert(data);
    print_tensor_shape(data, "data");

    // 加载权重
    std::map<std::string, Weights> weightMap = loadWeights("../crnn.wts");
    Weights emptywts{ DataType::kFLOAT, nullptr, 0 };
    
    IConvolutionLayer* conv0_1 = network->addConvolution(*data, 32, DimsHW{3, 3}, 
    weightMap["FeatureExtraction.ConvNet.conv0_1.weight"], emptywts);
    assert(conv0_1);
    conv0_1->setName("conv0_1");
    conv0_1->setStride(DimsHW{ 1, 1 });
    conv0_1->setPadding(DimsHW{ 1, 1 });
    std::cout << "conv0_1" << std::endl;
    print_tensor_shape(conv0_1->getOutput(0), "conv0_1->getOutput(0)");
    // ........
    // ........
    // ........
    // ........
}
```

## solution

change `ICudaEngine* engine = createEngine(maxBatchSize, builder, DataType::kINT);`
into `ICudaEngine* engine = createEngine(maxBatchSize, builder, DataType::kFLOAT);`

> It's my mistake that I had written another text-classification model using `IConstantLayer` for gathering embedding vectors.

**Comment by Sidx-sys** [comment]
@zhouyuangan Thanks for the highligting the data_type issue! Similarly solved the issue for me.

**Comment by alxmamaev** [comment]
Was really confuse with this issue, but actually I had wrong data types too
