### ISSUE TITLE
enqueueV2 failure of TensorRT 8.5 when running YOLOv6 on GPU 2080Ti

### ISSUE THREAD

**Issue by jy00161yang** [NVIDIA/TensorRT#3341]
## Environment

**TensorRT Version**: 8.5.3.1

**NVIDIA GPU**: 2080Ti

**NVIDIA Driver Version**: 455.45.01

**CUDA Version**: 11.1

**CUDNN Version**: 8.6

Operating System: linux

## Relevant Files

**Model link**: 
https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6l6.pt
https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6l.onnx

## Steps To Reproduce

git clone https://github.com/meituan/YOLOv6.git
pip install -r requirement.txt
cd ./deploy/TensorRT
python onnx_to_trt.py --model ../../yolov6l.onnx --dtype fp16  ==== > get yolov6l.trt
 following the step here: https://github.com/meituan/YOLOv6/tree/main/deploy/TensorRT， 
main cpp file: https://github.com/meituan/YOLOv6/blob/main/deploy/TensorRT/yolov6.cpp
After build cpp exacautable file , and run it with command:

./yolov6 ./yolov6l.trt -i test.png

shows :

[E] [TRT] 2: [fusedConvActRunner.cpp::execute::420] Error Code 2: Internal Error (Assertion !mParams.actParams.isGeneric() failed. )

![Snipaste_2023-09-22_15-22-24](https://github.com/NVIDIA/TensorRT/assets/89822923/c6849ee2-f747-4919-8e4d-4a442353f2bb)
I changed enqueue to enqueueV2，but got the same error.
![Snipaste_2023-09-22_15-22-43](https://github.com/NVIDIA/TensorRT/assets/89822923/fdf16708-ce2c-4a11-a4b9-c27a88511552)

**Comment by jy00161yang** [comment]
Use trtexec instead of the python script. Problem solved.

**Comment by zerollzeng** [comment]
> Use trtexec instead of the python script. Problem solved.

I think it's a user side issue, so I'm closing this.
