### ISSUE TITLE
[onnx-graphsurgeon] Pad Operator folding pads

### ISSUE THREAD

**Issue by inisis** [NVIDIA/TensorRT#3353]
Hi, when doing constant folding, only nodes with constant will be folded, but for graph like below, it won't be folded.
![image](https://github.com/NVIDIA/TensorRT/assets/46103969/fb35f3e2-fcae-40f8-9022-2bd0d4b65a32)

Should we add logic [here](https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py#L664-L692) to deal such case.

I have achieved such by adding such logic
```
            def is_constant_pad(node):
                if node.op == 'Pad':
                    return True
                else:
                    return False

            # Walks along the outputs of graph_constants to see if they can also be computed statically.
            # Since the graph is topologically sorted, this should find all constant nodes in the graph.
            for node in graph_clone.nodes:
                if is_foldable(node):
                    graph_constants.update({out.name: out for out in node.outputs})
                if is_constant_pad(node):
                    graph_constants.update({node.inputs[1].name: node.inputs[1]})
            return graph_constants
```

@pranavm-nvidia Can you take a look. Thanks!

**Comment by pranavm-nvidia** [comment]
But isn't this operating on a non-constant input? How would we fold it?

**Comment by inisis** [comment]
Since the input shape of the model is fixed, then the shape of the add layer is fixed, so the pad can be calculated and fixed.

**Comment by pranavm-nvidia** [comment]
Only the shape of the output could be calculated though, not the contents.

**Comment by inisis** [comment]
Not really, you can see my affliated picture, the pad input of the Pad node can be pre-calculated, since the subgraph inputs are fixed.

**Comment by inisis** [comment]
Wow, can you paste your code here, since I cannot reproduce it in my code base.

**Comment by pranavm-nvidia** [comment]
I used Polygraphy:
```bash
polygraphy surgeon sanitize --fold-constants tf_efficientnetv2_s.onnx -o folded.onnx
```

**Comment by inisis** [comment]
Polygraphy depends on [onnxruntime](https://github.com/microsoft/onnxruntime/blob/1bc115719c0d07ad658a9bb458ddf8f1bf379a41/onnxruntime/python/tools/symbolic_shape_infer.py), but should we reimplement that in graphsurgeon.

**Comment by inisis** [comment]
That seems resonable, thanks for your elabration.
