### ISSUE TITLE
Conv2DTranspose layers don't run on DLA on Orin

### ISSUE THREAD

**Issue by kari-jg** [NVIDIA/TensorRT#3365]
## Description
I am trying to build an engine from a simple UNET-like onnx with DLA on the Jetson Orin.

This is my trtexec call: 

`trtexec --verbose --onnx=.../pre_trained.onnx --saveEngine=.../pre_trained.onnx.engine --timingCacheFile=./timing.cache --int8 --fp16 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --shapes=input_0:32x3x128x128 --useDLACore=0 --allowGPUFallback --separateProfileRun > pre_trained.log `

This builds an engine, but pre_trained.log outputs that the deconv layers are running on GPU and not DLA:

![image](https://github.com/NVIDIA/TensorRT/assets/74316409/f3429fdd-be7d-4ec9-a94b-c2e04eca2597)

The dec_deconv layers are all built in tensorflow like this: 

```
    layers['dec_deconv_1'] = Conv2DTranspose(
        filters=32, kernel_size=3, padding='same', use_bias=True, kernel_regularizer=regularizer, strides=2,
        name='dec_deconv_1', data_format=data_format)
```

Do you know why they can't run on the DLAs? From what I read in [the dla layer documentation](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#dla_layers) they should fulfill the requirements. Although I'm not sure what "TensorRT has disabled deconvolution square kernels" means? Or is the problem somehow related to my channels first shape? 

![image](https://github.com/NVIDIA/TensorRT/assets/74316409/c3a5a91c-7412-4d4a-899a-679b3e37a596)

**Comment by zerollzeng** [comment]
Which TRT version you are using? There should be a warning before the "-----Layer running on DLA----" that can tell you why it fallback.
