### ISSUE TITLE
Empty Tensor Support

### ISSUE THREAD

**Issue by 1-800-BAD-CODE** [NVIDIA/TensorRT#337]
## Description

I have a network that takes as input a tensor that may have a little as zero elements in one dimension, therefore the optimization profile must have a minimum of zero. But profile dimensions must be strictly positive:

```
[E] [TRT] Parameter check failed at: optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int x) { return x > 0; })
```

Therefore it seems impossible to implement a network that takes as input a tensor with possibly zero elements. But this does happen in practice.

## Environment

**TensorRT Version**:  7.0.0.11
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

```
nvinfer1::IOptimizationProfile profile;
profile.setDimensions("foo", OptProfileSelector::kMIN, Dims{2, 1, 0});
```

**Comment by rmccorm4** [comment]
Hi @1-800-BAD-CODE,

RFE for empty tensor support noted, thanks - stay tuned.

**Comment by rajeevsrao** [comment]
@1-800-BAD-CODE closing the RFE. Will notify if there are any updates on this in future releases.

**Comment by fxmarty** [comment]
Hi @rajeevsrao , are empty shapes supported in TensorRT?

**Comment by CaprYang** [comment]
> Hi @rajeevsrao , are empty tensors supported in TensorRT?

https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#empty-tensors
