### ISSUE TITLE
[Question] Myelin use AITemplate/cutlass or normal compiler?

### ISSUE THREAD

**Issue by muzhailong** [NVIDIA/TensorRT#3371]
## Description
Does Myelin use AITemplate/cutlass or normal compiler?

**Comment by muzhailong** [comment]
@zerollzeng can you help me?

**Comment by zerollzeng** [comment]
It's not open-source so I can't disclose such information :-( Why do you want to know this?

cc @zhenhuaw-me

**Comment by zhenhuaw-me** [comment]
Thank you for the interest in TensorRT implementation. Unfortunately, it's not information that we can disclose currently. Close this issue now.
