### ISSUE TITLE
 Error Code 2: Internal Error (ForeignNode does not support data-dependent shape for now.) 

### ISSUE THREAD

**Issue by Egorundel** [NVIDIA/TensorRT#3372]
## Description

Hello!
My task is to train RetinaNet (backbone: resnet50, keras). 

**RetinaNet**:
https://github.com/fizyr/keras-retinanet

After training, I got the weights **.h5**. Next, I need to convert weights into ONNX model **with dynamic batch_size**.

Code for converting weights .h5 in ONNX-the model I took from here: [keras2onnx](https://github.com/onnx/tensorflow-onnx/blob/main/tutorials/keras-resnet50.ipynb)
![006a3f39c6873a5276f82d15d8dacf371c97c3c9](https://github.com/NVIDIA/TensorRT/assets/65890558/2e564215-03e1-47ac-8a5c-b1c5e7508880)

And then I want to convert ONNX-model to TensorRT Engine using *trtexec*. I have an ONNX model, but further conversion to TensorRT Engine does not work.

When I run the command:
`trtexec --onnx=retinanet-bbox.onnx --saveEngine=retinaNet.trt --minShapes=images:1x512x512x3 --optShapes=images:6x512x512x3 --maxShapes=images:12x512x512x3 --useCudaGraph --memPoolSize=workspace:3000 --noTF32 --fp16`

I get an error:
**Error[2]: [myelinBuilderUtils.cpp::getMyelinSupportType::1270] Error Code 2: Internal Error (ForeignNode does not support data-dependent shape for now.)**
![17d90b314f521a701394a847733ef4578fbf3d16](https://github.com/NVIDIA/TensorRT/assets/65890558/a9a52c30-3cbb-4f2a-922e-271fbc1f3942)

My ONNX-model is correct. I checked it with code: **check_onnx_model.py**
![95096a7caec4f3f9c5f69d396b451cf7d14ab74f](https://github.com/NVIDIA/TensorRT/assets/65890558/696e7916-d13e-4a94-88d7-cec3a15b31ad)

Maybe I'm creating the ONNX model incorrectly...  
<h2> I can't understand why this is happening? Could you help me solve this problem? </h2> 
P.S. An Internet search did not provide answers to this problem. 
I have attached my ONNX model in the attachment below.  

## Environment  
**TensorRT Version**: 8.6 
**GPU Type**: RTX3060 
**Nvidia Driver Version**: nvidia-driver-535 (proprietary) 
**CUDA Version**: 11.1 
**CUDNN Version**: 8.0.4 
**Operating System + Version**: Ubuntu 20.04 
**Python Version (if applicable)**: 3.8 
**TensorFlow Version (if applicable)**: 2.4.0    

## Relevant Files
model.h5: 
https://drive.google.com/file/d/1LnM5j7HTzIKOXkHM546vxQPj2rJQdQZ2/view?usp=sharing

retinanet-bbox.onnx: 
https://drive.google.com/file/d/1Tg7xYzWzyfRvIu3DhMNz5D2yrGviZTeM/view?usp=sharing

**Comment by Egorundel** [comment]
@ttyio Hello! Can you help me, please?

**Comment by zerollzeng** [comment]
Checking this internally

**Comment by zerollzeng** [comment]
We still don't support this, but it's in our plan and there are some effort on it.
