### ISSUE TITLE
Batch infer failure of TensorRT 8.6 when running yolov5 inference on GPU A4000

### ISSUE THREAD

**Issue by DrLecter-57** [NVIDIA/TensorRT#3375]
## Description
Hello, I am doing tensorrt inference for dynamic batch of yolov5, after the first batch of images finished inference and post-processing steps, the second batch of inference has the following problem: `AttributeError: 'numpy.ndarray' object has no attribute 'host'` in the code  `[cuda_call(cudart.cudaMemcpyAsync(out.host, out.device, out.nbytes, kind, stream)) for out in outputs]` Please let me know where is the problem, thanks!

## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: A4000

**NVIDIA Driver Version**: 470.82.01

**CUDA Version**:11.4

**CUDNN Version**: 8.9.3

Operating System: Linux

**Comment by zerollzeng** [comment]
> out.host

This looks like a numpy error and not releate to TRT.

**Comment by DrLecter-57** [comment]
> > out.host
> 
> This looks like a numpy error and not releate to TRT.

Thank you very much for your answers, I finished my project according to the official documentation.

**Comment by zerollzeng** [comment]
Okay, good to know that, I assume no problem for this so I'm closing this, feel free to reopen if you have any further questions.
