### ISSUE TITLE
How to reduce the size of TensorRT8.5.3.1 served to the client

### ISSUE THREAD

**Issue by MTManis** [NVIDIA/TensorRT#3376]
## Description
Our Windows client needs to rely on the cudnn and TensorRT8.5 libraries, but these two libraries are too large. If they are packaged together and provided to the client, the client's installation package will take up too much space. If the library is not provided to the client, the client will need to install it manually, which is not very convenient and appropriate. Is there any good solution?

## Environment

**TensorRT Version**: TensorRT-8.5.3.1

**NVIDIA GPU**: GeForce GTX 1080 Ti

**NVIDIA Driver Version**: 12.2

**CUDA Version**: 11.3

**CUDNN Version**: cudnn-windows-x86_64-8.9.4.25_cuda11

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:
No, the latest release of the library has a larger footprint

**Comment by zerollzeng** [comment]
We remove cuDNN and cuBLAS dependencies for TRT core lib in TRT 8.6. although our pre-built plugin still rely on cuDNN(if you don't use it, then it's all good).

**Comment by chrjxj** [comment]
Helped this customer with following solution. 

Issue summary: 
- customer used TRT plugin; already replaced calling cudnn API part to self implemented ops
- goal: reduce runtime package size

Solution:

1. disable tacticSources during build time, and remove cudnn/cublas library in runtime. 

    -  set_preview_feature(), DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html?highlight=tactic_sources#tensorrt.PreviewFeature
    - setTacticSources(0U);

2. remove libnvinfer_builder_resource.so from runtime: this library is not required when runtime load a prebuild engine. This library is required when building an engine. 

Please close.

**Comment by zerollzeng** [comment]
Thanks, closed
