### ISSUE TITLE
onnx-graphsurgeon: fix constant folding bug when input is empty

### ISSUE THREAD

**Issue by inisis** [NVIDIA/TensorRT#3380]
for some onnx operator, node inputs must be empty in order to be optional, [resize-roi-input](https://onnx.ai/onnx/operators/onnx__Resize.html#inputs), but in onnx-graphsurgeon, this empty input is treated as [empty variable](https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/onnx-graphsurgeon/onnx_graphsurgeon/importers/onnx_importer.py#L196-L199),  so when folding constant, [this](https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py#L671) will return False if empty variable exists.  [model](http://120.224.26.73:15030/aifarm/onnx/dinov2_vit_small.onnx_torch.onnx)

![before](https://github.com/NVIDIA/TensorRT/assets/46103969/884945a9-b073-44af-b13b-ffd1e1438e80)

![after](https://github.com/NVIDIA/TensorRT/assets/46103969/6c4026ea-9f94-4430-bb1e-388e1df48fb3)

**Comment by inisis** [comment]
@pranavm-nvidia

**Comment by pranavm-nvidia** [comment]
This was already fixed: https://github.com/NVIDIA/TensorRT/blob/release/9.0/tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py#L673

**Comment by inisis** [comment]
so should we merge this into 8.6 branch, btw my implementation is better, only one for loop is needed, should we replace it?

**Comment by pranavm-nvidia** [comment]
Yeah, sounds good.

**Comment by inisis** [comment]
Close since merged.
