### ISSUE TITLE
support Intel Iris Xe Graphics ?

### ISSUE THREAD

**Issue by foxnight2** [NVIDIA/TensorRT#3389]
My Graphics is Intel Iris Xe Graphics
Does tensorRT support the card Intel Iris Xe Graphics ?

**Comment by nvpohanh** [comment]
TensorRT only support NVIDIA GPUs

**Comment by foxnight2** [comment]
Can I only install TensorRT with cpu?

**Comment by nvpohanh** [comment]
TensorRT also does not support running inference on CPU
