### ISSUE TITLE
[Enhancement request] No modulo operator in tensorrt

### ISSUE THREAD

**Issue by 1-800-BAD-CODE** [NVIDIA/TensorRT#340]
## Description

There is no modulo operator in TensorRT, I expected to find it in the `ElementWiseOperation` enum. Three layers are required to perform mod operations with what is currently available. It would be useful to have it available as an operation in an `IElementWiseLayer`.

E.g.,

```
network->addElementWise(*input, *mod_val, ElementWiseOperation::kMOD);
```

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @1-800-BAD-CODE,

I'll look into this. In the meantime, would something like this be equivalent?

```
remainder = num - divisor * (num / divisor)
```
Which I think would translate to something like this, but you might need to check my math:
```python
floor = network->addElementWise(*input, *mod_val, ElementWiseOperation::kFLOOR_DIV)
prod = network->addElementWise(*floor, *mod_val, ElementWiseOperation::kPROD)
mod = network->addElementWise(*input, prod, ElementWiseOperation::kSUB)
```

**Comment by 1-800-BAD-CODE** [comment]
Thanks... that's exactly how I implemented it and it does work the same as a kMOD operator would.

**Comment by rmccorm4** [comment]
Actually it turns out for floats, fmod rounds toward zero, not necessarily floor division (if result is negative), so this might not be totally correct depending on your needs

**Comment by rajeevsrao** [comment]
@1-800-BAD-CODE filed this as a feature request for TensorRT core library. Closing the ticket here since we have a workaround for now.
