### ISSUE TITLE
Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096)

### ISSUE THREAD

**Issue by Egorundel** [NVIDIA/TensorRT#3405]
Hello, I have a problem and maybe it happens even at the moment of converting the weights.pt after training YOLO-GOLD (https://github.com/huawei-noah/Efficient-Computing) to the TensorRT model.

My command to convert to ONNX looked like this:
`python3 Efficient-Computing/Detection/Gold-YOLO/deploy/ONNX/export_onnx.py --weights /home/egorundel/projects/Efficient-Computing/Detection/Gold-YOLO/runs/train/gold_yolo-l1/weights/best_ckpt.pt --img-size 512 512 --dynamic-batch --end2end --with-preprocess --topk-all 100 --iou-thres 0.65 --conf-thres 0.35`

After I transferred the weights after training the model to the ONNX model, then I ran the trtexec command:
`trtexec --onnx=Efficient-Computing/Detection/Gold-YOLO/runs/train/gold_yolo-l1/weights/best_ckpt.onnx --saveEngine=yolo_gold.trt --minShapes=images:1x3x512x512 --optShapes=images:6x3x512x512 --maxShapes=images:12x3x512x512 --useCudaGraph --memPoolSize=workspace:3000 --noTF32 --fp16`

I have an error when converting ONNX model to TensorRT Engine:
`Error[4]: kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096`

`Error[4]: [shapeCompiler.cpp::evaluateShapeChecks::1276] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096)`

![Screenshot from 2023-10-24 11-12-11](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/f708dd65-b8c5-4749-affd-736a51baa51e)

In Netron.App I found the node Reshape_552, but I didn't understand what was wrong.
![Screenshot from 2023-10-24 11-52-18](https://github.com/huawei-noah/Efficient-Computing/assets/65890558/ebdce2c5-de8b-4aa2-9087-002881d3d444)

What could be the problem?

@zerollzeng Maybe you can help me, please?

**Comment by zerollzeng** [comment]
> Error[4]: [shapeCompiler.cpp::evaluateShapeChecks::1276] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: IShuffleLayer Reshape_552: reshaping failed for tensor: 1860 reshape would change volume 24576 to 4096)

The `Reshape_552` reshape a tensor to 1x8x8x84, which means the size of its input must have a size 4096, in you case, this onnx model can not be built with dynamic shape, it's actually a static shapes mode.

**Comment by Egorundel** [comment]
@zerollzeng How do I fix this node so that everything works with dynamic forms?

**Comment by zerollzeng** [comment]
You need to fix it in the source model code, e.g. pytorch, let the export onnx can actually handle the dynamic shape.

**Comment by Egorundel** [comment]
@zerollzeng Thanks for help! By the way, this tool, which is available in TensorRT, helped me: https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/onnx-graphsurgeon/examples/10_dynamic_batch_size
