### ISSUE TITLE
NameError caused by typo in onnx_graphsurgeon-0.4.0

### ISSUE THREAD

**Issue by georgeliu95** [NVIDIA/TensorRT#3406]
## Description

There is a typo in the function `get_onnx_tensor_dtype`, where `onnx_type` should be `onnx_dtype` instead.

## Environment

**TensorRT Version**: 9.1.0

**NVIDIA GPU**: A100

**NVIDIA Driver Version**: 535.104.05

**CUDA Version**: 12.2

## Relevant Files

**Code link**:
https://github.com/NVIDIA/TensorRT/blob/v9.1.0/tools/onnx-graphsurgeon/onnx_graphsurgeon/importers/onnx_importer.py#L127

## Steps To Reproduce

**Commands or scripts**:
Just run the [inpainting example](https://github.com/NVIDIA/TensorRT/blob/v9.1.0/demo/Diffusion/README.md#generate-an-inpainted-image-guided-by-an-image-mask-and-a-text-prompt) of diffusion models under path `demo/Diffusion`.

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:  Yes

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
@pranavm-nvidia ^ ^

**Comment by pranavm-nvidia** [comment]
This is fixed internally already.

**Comment by zerollzeng** [comment]
closed this.
