### ISSUE TITLE
Profiling failure of TensorRT 9.1 when running stable diffusion xl on H100-sxm5

### ISSUE THREAD

**Issue by BugFreeee** [NVIDIA/TensorRT#3407]
## Description

Followed the exact instruction to run stable diffusion xl demo:
https://github.com/NVIDIA/TensorRT/blob/release/9.1/demo/Diffusion/README.md

First I ran:
 `python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --hf-token=$HF_TOKEN --version=xl-1.0 --enable-refiner --onnx-refiner-dir=onnx-refiner --engine-refiner-dir=engine-refiner --build-static-batch --batch-count 1 --use-cuda-graph --force-engine-build`
The above command ran normally and produced desired ouput. However, when I tried to profile the program using:
`nsys profile -o test python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --hf-token=$HF_TOKEN --version=xl-1.0 --enable-refiner --onnx-refiner-dir=onnx-refiner --engine-refiner-dir=engine-refiner --build-static-batch --batch-count 1 --use-cuda-graph`

It threw segementation fault:

> root@b8bd52f36f02:/workspace/demo/Diffusion# nsys profile -o test python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --hf-token=$HF_TOKEN --version=xl-1.0 --enable-refiner --onnx-refiner-dir=onnx-refiner --engine-refiner-dir=engine-refiner --build-static-batch --batch-count 1 --use-cuda-graph
[b8bd52f36f02:33660:0:33660] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)
==== backtrace (tid:  33660) ====
 0 0x00000000004e1806 NSYS_DL_dlopen()  ???:0
 1 0x0000000000042520 __sigaction()  ???:0
 2 0x00000000001495e9 cuptiEnumMetrics()  ???:0
 3 0x00000000000fec06 cuptiGetRecommendedBufferSize()  ???:0
 4 0x00000000001087b8 cuptiGetRecommendedBufferSize()  ???:0
 5 0x0000000000253f16 cuEGLApiInit()  ???:0
 6 0x0000000000342fc4 cuVDPAUCtxCreate()  ???:0
 7 0x00000000003433ba cuVDPAUCtxCreate()  ???:0
 8 0x000000000036332a cuVDPAUCtxCreate()  ???:0
 9 0x000000000038fca2 cuVDPAUCtxCreate()  ???:0
10 0x0000000000278977 cuEGLApiInit()  ???:0
11 0x00000000004fb039 cudbgMain()  ???:0
12 0x000000000013b116 cuMemGetAttribute_v2()  ???:0
13 0x000000000013b529 cuMemGetAttribute_v2()  ???:0
14 0x000000000013c8b7 cuMemGetAttribute_v2()  ???:0
15 0x00000000003292f1 cuStreamQuery()  ???:0
16 0x0000000000048111 __cudaRegisterUnifiedTable()  ???:0
17 0x00000000000187d2 ???()  /usr/local/lib/python3.10/dist-packages/tensorrt_libs/../nvidia/cuda_runtime/lib/libcudart.so.12:0
18 0x0000000000071538 cudaMemcpyAsync()  ???:0
19 0x00000000014ec568 at::native::copy_device_to_device()  ???:0
20 0x00000000014cac04 at::native::copy_impl()  Copy.cpp:0
21 0x00000000014cbdfc at::native::copy_()  ???:0
22 0x00000000048ec749 c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool), &torch::ADInplaceOrView::copy_>, at::Tensor&, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool> >, at::Tensor& (c10::DispatchKeySet, at::Tensor&, at::Tensor const&, bool)>::call()  VariableTypeManual.cpp:0
23 0x00000000020aa959 at::_ops::copy_::call()  ???:0
24 0x00000000003fc1be torch::autograd::THPVariable_copy_()  python_variable_methods.cpp:0
25 0x00000000001615c9 _PyObject_GetDictPtr()  ???:0
26 0x0000000000148f52 _PyEval_EvalFrameDefault()  ???:0
27 0x000000000016e4e1 PyMethod_New()  ???:0
28 0x000000000014a0d1 _PyEval_EvalFrameDefault()  ???:0
29 0x000000000016070c _PyFunction_Vectorcall()  ???:0
30 0x0000000000148f52 _PyEval_EvalFrameDefault()  ???:0
31 0x000000000016e4e1 PyMethod_New()  ???:0
32 0x000000000016f192 PyObject_Call()  ???:0
33 0x000000000014b2c1 _PyEval_EvalFrameDefault()  ???:0
34 0x000000000016e4e1 PyMethod_New()  ???:0
35 0x000000000014a0d1 _PyEval_EvalFrameDefault()  ???:0
36 0x000000000016e4e1 PyMethod_New()  ???:0
37 0x000000000016f192 PyObject_Call()  ???:0
38 0x000000000014b2c1 _PyEval_EvalFrameDefault()  ???:0
39 0x0000000000239e56 PyEval_EvalCode()  ???:0
40 0x0000000000239cf6 PyEval_EvalCode()  ???:0
41 0x00000000002647d8 PyUnicode_Tailmatch()  ???:0
42 0x000000000025e0bb PyInit__collections()  ???:0
43 0x0000000000264525 PyUnicode_Tailmatch()  ???:0
44 0x0000000000263a08 _PyRun_SimpleFileObject()  ???:0
45 0x0000000000263653 _PyRun_AnyFileObject()  ???:0
46 0x000000000025641e Py_RunMain()  ???:0
47 0x000000000022ccad Py_BytesMain()  ???:0
48 0x0000000000029d90 __libc_init_first()  ???:0
49 0x0000000000029e40 __libc_start_main()  ???:0
50 0x000000000022cba5 _start()  ???:0
=================================
The target application terminated. One or more process it created re-parented.
Waiting for termination of re-parented processes.
Use the `--wait` option to modify this behavior.
Generating '/tmp/nsys-report-f450.qdstrm'
[1/1] [========================100%] test.nsys-rep
Generated:
    /workspace/demo/Diffusion/test.nsys-rep

## Environment

**TensorRT Version**: 9.1

**NVIDIA GPU**: H100-SXM5

**NVIDIA Driver Version**: 535.54.03

**CUDA Version**: 12.2

**CUDNN Version**:

Operating System: Linux

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

Step1: python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --hf-token=$HF_TOKEN --version=xl-1.0 --enable-refiner --onnx-refiner-dir=onnx-refiner --engine-refiner-dir=engine-refiner --build-static-batch --batch-count 1 --use-cuda-graph --force-engine-build

Step2: nsys profile -o test python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --hf-token=$HF_TOKEN --version=xl-1.0 --enable-refiner --onnx-refiner-dir=onnx-refiner --engine-refiner-dir=engine-refiner --build-static-batch --batch-count 1 --use-cuda-graph

**Commands or scripts**:

**Comment by BugFreeee** [comment]
Tried with A100-80GB pcie, the exact same issue persists.

**Comment by zerollzeng** [comment]
> 0 0x00000000004e1806 NSYS_DL_dlopen() ???:0
> 1 0x0000000000042520 __sigaction() ???:0 2 0x00000000001495e9 cuptiEnumMetrics() ???:0 3 0x00000000000fec06 cuptiGetRecommendedBufferSize() ???:0 4 0x00000000001087b8 cuptiGetRecommendedBufferSize() ???:0__

The crash happens in Nsys, please report this to our nsys team, which nsys version you are using?

**Comment by BugFreeee** [comment]
> > 0 0x00000000004e1806 NSYS_DL_dlopen() ???:0
> > 1 0x0000000000042520 **sigaction() ???:0 2 0x00000000001495e9 cuptiEnumMetrics() ???:0 3 0x00000000000fec06 cuptiGetRecommendedBufferSize() ???:0 4 0x00000000001087b8 cuptiGetRecommendedBufferSize() ???:0**
> 
> The crash happens in Nsys, please report this to our nsys team, which nsys version you are using?

Tested with 23.2 and 23.3, same issue. I did some debugging, the problem seems relating to cuda grah. Once it's enable, profiling will show the aboved erros. When disabled, everything works fine.  It looks to me, when cuda graph is enabled, nsys somehow produces large messge, which results in the issue.

**Comment by zerollzeng** [comment]
There is nothing we can do on TRT, but I help file an internal bug 4364435 against our nsys team to track this.

**Comment by zerollzeng** [comment]
@nvpohanh for viz.

**Comment by chengzeyi** [comment]
@BugFreeee 
Hi, friend！I know you are suffering great pain from using `TRT` with `diffusers`.

So why choose my totally **open-sourced** alternative: [`stable-fast`?](https://github.com/chengzeyi/stable-fast)
It's on par with `TRT` on inference speed, faster than `torch.compile` and `AITemplate`, and is super dynamic and flexible, supporting **ALL** SD models and **LoRA** and **ControlNet** out of the box!

[![](https://mermaid.ink/img/pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1?type=png)](https://mermaid.live/edit#pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1)

**Comment by zerollzeng** [comment]
issue fixed in our nsys main, close this bug.

**Comment by yyccli** [comment]
Hi, I encountered the same problem as described above, but when profiling in vllm. Problem solved when i closed CUDA graph.
You mentioned above that nsys solved this issue, has the current release version (2024.1) solved it or do i need to wait for the next release?
Thanks
