### ISSUE TITLE
How to setBindingDimensions for dynamic batch of dynamic input shapes.

### ISSUE THREAD

**Issue by osirisQdt** [NVIDIA/TensorRT#3409]
Hi guys, I'm new to TensorRT and trying to deploy a simple network definition from scratch using C++ API. As far as I know, if I want to define inputs as dynamic batch with dynamic shapes. When creating input layer, I could use wildcard -1:
```
nvinfer1::ITensor* input = network->addInput("image", nvinfer1::DataType::kFLOAT, nvinfer1::Dims4(-1, 3, -1, -1));
```
After that, I must define `IOptimizationProfile`:
```
    auto profile = builder->createOptimizationProfile();
    profile->setDimensions(input->getName(), nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims4(1, 3, 3, 3));
    profile->setDimensions(input->getName(), nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims4(1, 3, 3, 3));
    profile->setDimensions(input->getName(), nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims4(maxBatchSize, 3, 5, 5));
    config->addOptimizationProfile(profile);
```
And then, before running `enqueueV2`, I must call the `setBindingDimensions` API for specifying the dynamic batch and input shape.
```
int ib = 2, ih = 3, iw = 3;
context->setBindingDimensions(0, nvinfer1::Dims4(ib, 3, ih, iw));
```
But what happens if I want the input shape is different from each other in one batch? Like example, batch includes 2 input with 2 type of shapes (3, 3, 3) and (3, 3, 4). What should I do in this case?
Thanks for reading my post and it's my pleasure to hear response from you guys.

**Comment by luxiaozheng** [comment]
From my experience, it is impossible and impractical to have different shapes for different batch. The idea of batching is to put together objects of the SAME dimensions together and compute together, so you may need to consider using padding to force them together if possible. If padding is impossible, and you require the processing of different shapes at the same time, you need to separate as 2 inputs and treat them differently.

**Comment by osirisQdt** [comment]
> From my experience, it is impossible and impractical to have different shapes for different batch. The idea of batching is to put together objects of the SAME dimensions together and compute together, so you may need to consider using padding to force them together if possible. If padding is impossible, and you require the processing of different shapes at the same time, you need to separate as 2 inputs and treat them differently.

Yea thanks for replying me. So I will try to deal the problem by separating as 2 inputs.
