### ISSUE TITLE
trtexec transform onnx model to engine error! failure of TensorRT 8.5 when running crnn on Jetson Xavier NX。

### ISSUE THREAD

**Issue by quanzhang2020** [NVIDIA/TensorRT#3419]
CUDA Driver Version: 11.4
CUDA Runtime Version: 11.4
TensorRT Version: 8.5.2
cuDNN Version: 8.6
crnn onnx model input dim=(1,1,32,160),output dim=(41,1,11).use trtexec transform the onnx model to engine. comand: /usr/src/tensorrt/bin/trtexec --workspace=1024 --onnx=./crnn.onnx --fp16 --saveEngine=crnn.engine --explicitBatch
The transformation PASSED.

But when I test image inference，the network output dim is error,like this:

0:00:08.027370064 2393586 0xaaaaab51fa30 INFO                 nvinfer gstnvinfer.cpp:680:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 10]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 10]: deserialized trt engine from :/opt/nvidia/deepstream/deepstream-6.2/sources/apps/sample_apps/deepstream-preprocess-test/crnn.engine
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT input           1x32x160        
1   OUTPUT kFLOAT output          1x11    

So, I get the network  output buffer is error!

**Comment by RajUpadhyay** [comment]
Is this a tensorrt error or deepstream error?
Can you post the image of entire screen?

**Comment by zerollzeng** [comment]
Looks like a DS error, please report this to DS forum.
