### ISSUE TITLE
stable diffusion XL  GPU memory keeps accumulating, maybe memory leak

### ISSUE THREAD

**Issue by cjt222** [NVIDIA/TensorRT#3421]
Hello, I'm trying to run stable diffusion XL using TensorRT (TensorRT/demo/Diffusion/demo_txt2img_xl.py). When the batch size is set to 4 and the batch count is set to 50, I noticed that the GPU memory keeps accumulating, which leads to an error on the second run: torch.cuda.OutOfMemoryError: CUDA out of memory. I would like to know what could be causing this issue. (I'm using the official image in my environment, with TensorRT version T9.0.1)

**Comment by cjt222** [comment]
The issue has been identified to be in the decode_latent function, not in the TensorRT layer. It appears that new GPU memory is being repeatedly allocated here.

**Comment by zerollzeng** [comment]
Checking this internally

**Comment by cjt222** [comment]
Hi，Have you reproduced the results? @zerollzeng
