### ISSUE TITLE
memory used by MHA with dynamic range of input is too huge

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT#3422]
for part of layers from MHA(Llama),  when I set 
```
# s=sp=2048, s<=sp
# atttion_mask, k, q, v,
"max": f"1x1x{s}x{sp},1x32x{sp}x128,1x32x{s}x128,1x32x{sp}x128", 
"min": "1x1x1x1,1x32x1x128,1x32x1x128,1x32x1x128",
```
, the model uses too much GPU memory. Is there any way to reduce GPU memory usage in this situation?

**Comment by zerollzeng** [comment]
@nvpohanh do we any improvement on this?

**Comment by nvpohanh** [comment]
@tp-nan Could you try TRT-LLM repo? https://github.com/NVIDIA/TensorRT-LLM

**Comment by tp-nan** [comment]
> @nvpohanh do we any improvement on this?

Sure，but might later.

I have temporarily found a solution, which is to cut the no-parameters-subgraphs out, so there is no need to rebuild them 32 times. In addition, it seems that using multiple small-range inputs is more memory-efficient than using one large-range input

**Comment by tp-nan** [comment]
> @tp-nan Could you try TRT-LLM repo? https://github.com/NVIDIA/TensorRT-LLM

Sure，but might later.

I have temporarily found a solution, which is to cut the no-parameters-subgraphs out, so there is no need to rebuild them 32 times. In addition, it seems that using multiple small-range inputs is more memory-efficient than using one large-range input
