### ISSUE TITLE
How to use tensorrt_dispatch and tensorrt_lean?

### ISSUE THREAD

**Issue by triple-Mu** [NVIDIA/TensorRT#3427]
## Description

Here is error:
module 'tensorrt_dispatch' has no attribute 'Builder'

## Environment

**TensorRT Version**:

**NVIDIA GPU**:

**NVIDIA Driver Version**:

**CUDA Version**:

**CUDNN Version**:

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
Check https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#runtime-options

**Comment by ttyio** [comment]
closing, thanks all!
