### ISSUE TITLE
Support of Maxpool3D

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [NVIDIA/TensorRT#3428]
Hello,

I want to ask if Tensorrt 8.5.1 or the latest version has supported MaxPool3D, I saw it was not supported last year. 

Thanks in advance.

**Comment by zerollzeng** [comment]
From https://github.com/onnx/onnx-tensorrt/blob/main/docs/operators.md it's supported. please check the latest release.

**Comment by Oh-Cest-la-vie** [comment]
Got it.
