### ISSUE TITLE
TensorRT ONNX conversion renames input variable from 'x' to '__y'

### ISSUE THREAD

**Issue by hongliyu0716** [NVIDIA/TensorRT#3429]
## Description

I am encountering a bug while using TensorRT to run an ONNX model. It seems that TensorRT is renaming the input variable 'x' to '__y', causing a KeyError when trying to pass the input tensor.

## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: NVIDIA GeForce MX330

**NVIDIA Driver Version**: 470.182.03

**CUDA Version**: 11.4

**CUDNN Version**: 8.9.5

Operating System: Ubuntu 18.04

Python Version: 3.8

## Relevant Files

**Model link**: https://github.com/hongliyu0716/onnx_model/blob/main/dropout_crash.onnx
The model structure is as below:
![dropout_crash onnx](https://github.com/NVIDIA/TensorRT/assets/149884162/5312b26b-18e1-4e5f-91fd-119e3f8db152)

## Steps To Reproduce

**Commands or scripts**:
```python
import onnx
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np

onnx_path = 'dropout_crash.onnx'
model = onnx.load(onnx_path)
onnx.checker.check_model(model)
input_data = {}
input_data['x'] = np.random.rand(*[3, 4, 5]).astype(np.float32)

builder = trt.Builder(trt.Logger(trt.Logger.WARNING))
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
config = builder.create_builder_config()
config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 2 << 30)
parser = trt.OnnxParser(network, trt.Logger(trt.Logger.WARNING))
    
with open(onnx_path, 'rb') as f:
    if not parser.parse(f.read()):
        error_msg = ""
        for error in range(parser.num_errors):
            error_msg += str(parser.get_error(error))
        raise RuntimeError(error_msg)

engine_bytes = builder.build_serialized_network(network, config)
engine = trt.Runtime(trt.Logger(trt.Logger.WARNING)).deserialize_cuda_engine(engine_bytes)

inputs = []
outputs = []
bindings = []
stream = cuda.Stream()
onames = []
name2idx = {}

for idx, binding in enumerate(engine):
    print(idx, binding)
    name2idx[binding] = idx
    size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size
    dtype = trt.nptype(engine.get_binding_dtype(binding))

    host_mem = cuda.pagelocked_empty(size, dtype)
    device_mem = cuda.mem_alloc(host_mem.nbytes)

    bindings.append(int(device_mem))

    if engine.binding_is_input(binding):
        inputs.append((host_mem, device_mem))
    else:
        outputs.append((host_mem, device_mem))
        onames.append(binding)

context = engine.create_execution_context()

for iname in input_data:
    np.copyto(
        inputs[name2idx[iname]][0],
        inputs[iname].astype(trt.nptype(engine.get_binding_dtype(iname))).ravel()
    )
```

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): yes
![dropout](https://github.com/NVIDIA/TensorRT/assets/149884162/a92400fd-19d3-442f-b68a-2891c1a220c6)

**Comment by nvpohanh** [comment]
@zerollzeng I remember seeing a very similar bug. Could you try if the issue still exists in TRT 9.1? Thanks

**Comment by zerollzeng** [comment]
The issue has been fixed in the latest internal TRT.

**Comment by hongliyu0716** [comment]
Thank you for your response :)
