### ISSUE TITLE
It was observed through nsightSystem that stall failure of TensorRT 8.4 when running doInference on GPU orin

### ISSUE THREAD

**Issue by SolDogLi** [NVIDIA/TensorRT#3432]
I’m seeing some strange stalls when running doInference on GPU orin
![image](https://github.com/NVIDIA/TensorRT/assets/33997872/6114cf92-ea10-41f1-addc-272646cb54f2)
During these 1.99ms,the GPU is completely idle and no kernel calculations and memory copy.

**Comment by zerollzeng** [comment]
Check other threads to see if there are operations block the host. Would be great if you can share the nsys report here and tell use which nsys version you are using.

**Comment by SolDogLi** [comment]
> Check other threads to see if there are operations block the host. Would be great if you can share the nsys report here and tell use which nsys version you are using.

I checked the code and found no blocking of the host.
The nsys version is 2021.5.4(target-linux-tegra-armv8).
you can get the nsys report by https://drive.google.com/file/d/1YgAHvT3CB5oWt54km9Ozo0uFt9Q0CjCQ/view?usp=drive_link

thanks

**Comment by zerollzeng** [comment]
@nvpohanh I can see the hole as the bug description. But I cannot see the  possible reason for this, looks like the GPU context just switch out, do you know?

**Comment by nvpohanh** [comment]
I checked the Nsys profile but it seems that the bubbles appear randomly and do not always appear in the same position in each iteration. This makes me wonder if they are just caused by random nsys profiling overheads.

Does the bubble exist when the app runs without Nsys? i.e. are the "doInference" durations stable when running without Nsys?

**Comment by zerollzeng** [comment]
FYI it can be caused by other process/service in the system which take over the CPU.
