### ISSUE TITLE
Cannot build "trtexec" in TensorRT 8.0.1.6

### ISSUE THREAD

**Issue by wangj1ngyan** [NVIDIA/TensorRT#3434]
## Description
I have installed **TensorRT-8.0.1.6** with the tar file from this [link]([Download](https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/8.0.1/tars/tensorrt-8.0.1.6.linux.x86_64-gnu.cuda-11.3.cudnn8.2.tar.gz)).

**TensorRT-8.0.1.6** was installed and extracted to /home/${my_usrname}, and I tried this:
```
my_usrname:~$ cd TensorRT-8.0.1.6/samples/trtexec && make CUDA_INSTALL_DIR=/usr/local/cuda-11.2
```
Then, I got the following error
```
../Makefile.config:16: CUDNN_INSTALL_DIR variable is not specified, using /usr/local/cuda-11.2 by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
../Makefile.config:29: TRT_LIB_DIR is not specified, searching ../../lib, ../../lib, ../lib by default, use TRT_LIB_DIR=<trt_lib_directory> to change.
if [ ! -d ../../bin/chobj/trtexec/trtexec/../common ]; then mkdir -p ../../bin/chobj/trtexec/trtexec/../common; fi; :
Compiling: ../common/sampleEngines.cpp
../common/sampleEngines.cpp: In function ‘bool sample::setupNetworkAndConfig(const sample::BuildOptions&, const sample::SystemOptions&, nvinfer1::IBuilder&, nvinfer1::INetworkDefinition&, nvinfer1::IBuilderConfig&, std::ostream&, std::vector<std::vector<char> >&)’:
../common/sampleEngines.cpp:751:74: error: ‘kDLA_STANDALONE’ is not a member of ‘nvinfer1::EngineCapability’
  751 |         config.setEngineCapability(sys.DLACore != -1 ? EngineCapability::kDLA_STANDALONE : EngineCapability::kSAFETY);
      |                                                                          ^~~~~~~~~~~~~~~
../common/sampleEngines.cpp:751:110: error: ‘kSAFETY’ is not a member of ‘nvinfer1::EngineCapability’
  751 | neCapability(sys.DLACore != -1 ? EngineCapability::kDLA_STANDALONE : EngineCapability::kSAFETY);
      |                                                                                        ^~~~~~~

../common/sampleEngines.cpp:756:37: error: ‘kSAFETY_SCOPE’ is not a member of ‘nvinfer1::BuilderFlag’
  756 |         config.setFlag(BuilderFlag::kSAFETY_SCOPE);
      |                                     ^~~~~~~~~~~~~
make: *** [../Makefile.config:335: ../../bin/chobj/trtexec/trtexec/../common/sampleEngines.o] Error 1

```

## Environment

**TensorRT Version**: 8.0.1.6

**NVIDIA GPU**: GeForce RTX 3090

**NVIDIA Driver Version**: 535.54.03 

**CUDA Version**: 11.2

**CUDNN Version**: 8.9.5.30

Operating System: Ubuntu 20.04 LTS

Python Version (if applicable): 3.10.13

## Steps To Reproduce

- Install TensorRT 8.0.1.6 with tar file, following [link]([Download](https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/8.0.1/tars/tensorrt-8.0.1.6.linux.x86_64-gnu.cuda-11.3.cudnn8.2.tar.gz))
- Extract the downloaded package: `~$ tar -xvf TensorRT-8.0.1.6.Linux.x86_64-gnu.cuda-11.8.tar.gz`
- Build trtexec: `cd ${TENSORRT_EXTRACT_DIR}/samples/trtexec && make CUDA_INSTALL_DIR=/usr/local/cuda-11.2` and fail to do so.

**Comment by zerollzeng** [comment]
> ../Makefile.config:29: TRT_LIB_DIR is not specified, searching ../../lib, ../../lib, ../lib by default, use TRT_LIB_DIR=<trt_lib_directory> to change.

Specify correct TRT_LIB_DIR, In you case I think it's ${TENSORRT_EXTRACT_DIR}/lib

**Comment by ttyio** [comment]
closing since there is already answer, thanks all!
