### ISSUE TITLE
multiple IExecutionContext  for getDeviceMemorySize

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT#3437]
I have multiple IExecutionContexts, each with an different OptimizationProfile. 
```
virtual size_t nvinfer1::ICudaEngine::getDeviceMemorySize() const

      Return the amount of device memory required by an execution context.
```
Is ICudaEngine's getDeviceMemorySize  unrelated to OptimizationProfile?

**Comment by zerollzeng** [comment]
I think the OptimizationProfile was determined when you build the engine, so each each engine has its own OptizationProfile.

> I have multiple IExecutionContexts, each with an different OptimizationProfile.

In this case I think What you mean is multiple ICudaEngine with different IOptimizationProfile?

> Is ICudaEngine's getDeviceMemorySize unrelated to OptimizationProfile?

I think the answer it's no, IOptimizationProfile can affect the size returned by getDeviceMemorySize.

These are just my understanding, @ttyio @pranavm-nvidia  please correct if I made any mistake :-)

**Comment by tp-nan** [comment]
Hi, thanks for your reply.
I build one ICudaEngine with multiple `IOptimizationProfile` and multiple `IExecutionContext`, and get  Device Memory by ICudaEngine.getDeviceMemorySize, then I call IExecutionContext's setDeviceMemory.  So I'm wonder this device memory  size is sum of all IExecutionContexts(IOptimizationProfiles), or is only for one IExecutionContext?

**Comment by zerollzeng** [comment]
> or is only for one IExecutionContext?

I think it's this.


> does IExecutionContext with different IOptimizationProfile range need the same device memory size?

I think the memory size should be different(but not always, it depends on kernel tactics), you can verified this by experiment.

**Comment by tp-nan** [comment]
> > or is only for one IExecutionContext?
> 
> I think it's this.
> 
> > does IExecutionContext with different IOptimizationProfile range need the same device memory size?
> 
> I think the memory size should be different(but not always, it depends on kernel tactics), you can verified this by experiment.

Thx for your reply.  If so, I would suggest getDeviceMemorySize should be a method of IExecutionContext/IOptimizationProfile, not ICudaEngine. It is quite strange and I donot quite understand...

**Comment by zerollzeng** [comment]
@oxana-nvidia @nvpohanh any comments here ^ ^

**Comment by oxana-nvidia** [comment]
We are currently discussing possible API changes in this area for the next major release.

**Comment by nvpohanh** [comment]
> I think the answer it's no, IOptimizationProfile can affect the size returned by getDeviceMemorySize.

@zerollzeng I don't think this is correct. I think `engine->getDeviceMemorySize()` returns the maximum of the device mem sizes from all optimization profiles. So the value is a fixed value, regardless of which profile(s) the contexts are set to.

**Comment by zerollzeng** [comment]
Oh my understanding is wrong. sorry.

**Comment by nvpohanh** [comment]
No worries! As Oxana said, we are discussing some improvements on these APIs in next TRT version. Hopefully things will be improved in the future
