### ISSUE TITLE
convert DLA model error, must with --allowGPUfallback

### ISSUE THREAD

**Issue by Bobo-y** [NVIDIA/TensorRT#3438]
I need convert a trt model running on DLA. 
without allowGPUFallback, convert failed
![image](https://github.com/NVIDIA/TensorRT/assets/9928596/a791c0f8-29a4-487f-b0b5-c17fecc01ca5).

But according to build INFO, all layer running on DLA , No layer is running on GPU. 
I doubt that when "No layer is running on GPU", but must build DLA model with allowGPUFallback flag, does this mean that  model actually  run on DLA

**Comment by zerollzeng** [comment]
![image](https://github.com/NVIDIA/TensorRT/assets/38289304/b6a2cdb3-2c0c-4e09-ab3e-ac34b9e66d14)

Extra reformats is needed for input and outputs, which require GPU fallback, that is why it fail. Try specify the `--inputIOFormats` and `--outputIOFormats` that use DLA compatible IO formats.

**Comment by zerollzeng** [comment]
PS: DLA has its own format, which has stride and alignment requirement. sometimes you have to modify you onnx to be compatible with those format.

**Comment by zerollzeng** [comment]
See https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#ac3e115b1a2b1e578e8221ef99d27cd45

and our developer guide on TRT-DLA

**Comment by Bobo-y** [comment]
thanks
