### ISSUE TITLE
Jetson AGX Orin support tensorrt >=9.0?

### ISSUE THREAD

**Issue by johnnynunez** [NVIDIA/TensorRT#3446]
I tried to compile with jetson agx orin with cuda 12.2 and cudnn 8.9 but I can't compile.

Python compilation is working

**Comment by zerollzeng** [comment]
We don't officially support TRT9 on Jetson now, it's only for X86.

**Comment by ttyio** [comment]
closing, thanks all!

**Comment by johnnynunez** [comment]
> We don't officially support TRT9 on Jetson now, it's only for X86.

tensorRT 10 will be published here or from developer page?
