### ISSUE TITLE
how do I install tensorrt8.6 on jetson agx , my jetpack is 5.12

### ISSUE THREAD

**Issue by Ddd195** [NVIDIA/TensorRT#3454]
how do I install tensorrt8.6 on jetson agx , my jetpack is 5.12

**Comment by Data-Iab** [comment]
Tensorrt comes pre-installed with Jetpack. The most recent version you can have is TensorRT 8.5.2 (JetPack 5.1.2
). upgrading is not possible, you should wait for next jetpack releases

**Comment by zerollzeng** [comment]
Correct. I'm closing this. Please wait for the new JP release comes out.
