### ISSUE TITLE
How to get runtime dims from getOutputDimensions?

### ISSUE THREAD

**Issue by Sanster** [NVIDIA/TensorRT#347]
I am using TensorRT python api to create a FPN model. Currently `IResizeLayer` only support `linear` and `nearest` mode, so I implemented  a `interpolate` plugin(using IPluginV2DynamicExt) to support other mode(`bilinear`/`area`). The plugin works fine when set fixed output size, I can return a desired output dimensions in `getOutputDimensions`

```c++
  nvinfer1::DimsExprs getOutputDimensions(int outputIndex,
                                          const nvinfer1::DimsExprs* inputs,
                                          int nbInputs,
                                          nvinfer1::IExprBuilder& exprBuilder) override {
    nvinfer1::DimsExprs output(inputs[0]);
    output.d[2] = exprBuilder.constant(out_h);
    output.d[3] = exprBuilder.constant(out_w);
    return output;
```

But when I want to get output dimensions by `inputs dimensions and a scale_factor`, I can't get runtime dims of inputs in `getOutputDimensions` because the input tensor's height and width is dynamic.

```python
# In python code, a dynamic inputs is add by marking the dynamic dim `-1`
trt_tensor = self.network.add_input(
                        name="input",
                        shape=(1,3,-1,-1),
                        dtype=trt.float32,
                    )
print(trt_tensor.shape) # [1, 3, -1, -1]
```

Any suggestions?

**Comment by rmccorm4** [comment]
Hi @Sanster,

I believe you have to compute what the dimensions would be at runtime and return that.

From the docs: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_plugin_v2_dynamic_ext.html#ad4ed0a21d021ff864aaa162e1f38f502

Example 1: A plugin has a single output that transposes the last two dimensions of the plugin's single input. The body of the override of getOutputDimensions can be:
```cpp
DimsExprs output(inputs[0]);
std::swap(output.d[output.nbDims-1], output.d[output.nbDims-2]);
return output;
```

Example 2: A plugin concatenates its two inputs along the first dimension. The body of the override of getOutputDimensions can be:
```cpp
DimsExprs output(inputs[0]);
output.d[0] = exprBuilder.operation(DimensionOperation::kSUM, inputs[0].d[0], inputs[1].d[0]);
return output;
```

**Comment by Sanster** [comment]
@rmccorm4 Thanks for your reply. I have tried two methods, but none of them meet my
demand: `get output DimsExprs by inputs DimsExprs and double type scale_factor`

**method one**: Get output DimExprs use `DimensionOperation`. This method only works with a `int` scale_factor because `exprBuilder.constant` only accept `int` type.
```c++
  nvinfer1::DimsExprs getOutputDimensions(int outputIndex,
                                          const nvinfer1::DimsExprs* inputs,
                                          int nbInputs,
                                          nvinfer1::IExprBuilder& exprBuilder) override {
    // Input is n*c*h*w, output should be n*c*new_h*new_w
    nvinfer1::DimsExprs output(inputs[0]);
    auto input_dimsexprs = inputs[0];

    int scale_factor = 2;
    output.d[2] = exprBuilder.operation(DimensionOperation::kPROD, *input_dimsexprs.d[2], *exprBuilder.constant(scale_factor));
    output.d[3] = exprBuilder.operation(DimensionOperation::kPROD, *input_dimsexprs.d[3], *exprBuilder.constant(scale_factor));
    return output;
  }
  }
```

**method two**: To use a `double` scale_factor, I tried get output DimExprs by `getConstantValue()`

```c++
  nvinfer1::DimsExprs getOutputDimensions(int outputIndex,
                                          const nvinfer1::DimsExprs* inputs,
                                          int nbInputs,
                                          nvinfer1::IExprBuilder& exprBuilder) override {
    // Input is n*c*h*w, output should be n*c*new_h*new_w
    nvinfer1::DimsExprs output(inputs[0]);
    auto input_dimsexprs = inputs[0];
    std::cout << "try to get in_channel" << std::endl;
    int in_channel = input_dimsexprs.d[1]->getConstantValue();
    std::cout << "in_channel:" << in_channel << std::endl;

    std::cout << "try to get in_h" << std::endl;
    int in_h = input_dimsexprs.d[2]->getConstantValue();  // This line will cause segmentation fault
    std::cout << "in_h:" << in_h << std::endl;
    int in_w = input_dimsexprs.d[3]->getConstantValue();

    double scale_factor = 2.5;
    int out_h = (int)floor(scale_factor * in_h);
    int out_w = (int)floor(scale_factor * in_w);
    output.d[2] = exprBuilder.constant(out_h);
    output.d[3] = exprBuilder.constant(out_h);
    return output;
  }
```

Run the python code using the plugin get following output:

```shell
try to get in_channel
in_channel:8
try to get in_h
[1]    148626 segmentation fault (core dumped)  python3 plugin_demo.py
```

I have tried method in [segmentation-fault-core-dump-in-python-c-extension](https://stackoverflow.com/questions/29396600/segmentation-fault-core-dump-in-python-c-extension) to find core dump file, but not find core file :( 

P.S The code of `Example 2` seems wrong, we should add `*` operation before `inputs`
```c++
DimsExprs output(inputs[0]);
output.d[0] = exprBuilder.operation(DimensionOperation::kSUM, *inputs[0].d[0], *inputs[1].d[0]);
return output;
```

**Comment by zldrobit** [comment]
@Sanster  I once had the same problem.
I find out that dynamic dimensions of DimExprs cannot be retrieved in function getOutputDimensions. 
The actual dynamic dimension value can be obtained in function enqueue.
According to [2nd last phrase in Section 4.1.3 of TensorRT Developer Guide](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-700/tensorrt-developer-guide/index.html#example3_add_custlay_dynamic)

**Comment by rajeevsrao** [comment]
@Sanster double values are not supported in DimExprs yet.

**Comment by Ehrich-wen** [comment]
if you use IPluginV2DynamicExt, you have to set:
`
if (inputs[0].d[0]->isConstant()) {
  ...
  output.d[2] = exprBuilder.constant(out_h);
  output.d[3] = exprBuilder.constant(out_w);
  ...
}
`
