### ISSUE TITLE
Outputs of torch.cos abnormally mismatch on GPU when adding an intermediate result as output

### ISSUE THREAD

**Issue by Azyka** [NVIDIA/TensorRT#3474]
## Description

When outputting an intermediate result of `torch.sum` in this model:
<img width="145" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/74590664/24b763f0-8bfa-48d6-b168-d06a25439683">

New:
<img width="169" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/74590664/d1908142-ae91-4a09-9d59-6df30d07170d">

The output of `torch.cos` is expected to be the same for the same input in this 2 graphs. However, it mismatched bewteew the 2 models.

## Environment

**TensorRT Version**: 9.1.0.post12.dev4

**NVIDIA GPU**: RTX 1660

**NVIDIA Driver Version**: 525.147.05

**CUDA Version**: 12.0

**CUDNN Version**: 8.9.4.25

Operating System: Ubuntu 22.04.3 LTS (x86_64)

Python Version (if applicable): 3.10.12

Tensorflow Version (if applicable): 2.13.0

PyTorch Version (if applicable): 2.1.0+cu118

## Relevant Files

**Model link**: 
[model.zip](https://github.com/NVIDIA/TensorRT/files/13413274/model.zip)

## Steps To Reproduce

**Script**:
```python
import numpy as np
from numpy import testing
import torch
from polygraphy.backend.trt import EngineFromNetwork, NetworkFromOnnxPath, TrtRunner

DEVICE='cuda'

class Model0(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, *args):
        _args = args
        getitem = _args[0]
        sum_1 = getitem.sum(0)
        cos = torch.cos(sum_1)
        return (cos,)

model_0 = Model0()
output_names_0 = ['v5_0']
data_0 = np.random.normal(5, 1, size=(27, 63, 35, 1)).astype(np.float16)
input_dict_0 = {'v0_0': data_0}
inputs_0 = tuple(torch.from_numpy(v).to(DEVICE) for _, v in input_dict_0.items())
torch.onnx.export(model_0, inputs_0, '0.onnx', verbose=False, input_names=['v0_0'], output_names=output_names_0, opset_version=14, do_constant_folding=False)

class Model1(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, *args):
        _args = args
        getitem = _args[0]
        sum_1 = getitem.sum(0)
        cos = torch.cos(sum_1)
        return (cos, sum_1)

model_1 = Model1()
output_names_1 = ['v5_0', 'v4_0']
input_dict_1 = input_dict_0
inputs_1 = tuple(torch.from_numpy(v).to(DEVICE) for _, v in input_dict_1.items())
torch.onnx.export(model_1, inputs_1, '1.onnx', verbose=False, input_names=['v0_0'], output_names=output_names_1, opset_version=14, do_constant_folding=False)

engine_0 = EngineFromNetwork(NetworkFromOnnxPath('0.onnx'))
with TrtRunner(engine_0) as runner:
    output_0 = runner.infer(input_dict_0)

engine_1 = EngineFromNetwork(NetworkFromOnnxPath('1.onnx'))
with TrtRunner(engine_1) as runner:
    output_1 = runner.infer(input_dict_1)
output_name_dict = {'v5_0': 'v5_0'}

print('=========================')
try:
    for tensor_name_0, tensor_name_1 in output_name_dict.items():
        testing.assert_allclose(output_0[tensor_name_0], output_1[tensor_name_1], rtol=1, err_msg=f'at {tensor_name_0}, {tensor_name_1}')
    print("tensorRT does not trigger assertion")
except AssertionError as e:
    print("tensorRT triggers assertion")
    print(e)
print('=========================')

```

Steps to repro:
1. Run the script

Output assertion:
```
=========================
tensorRT triggers assertion

Not equal to tolerance rtol=1, atol=0
at v5_0, v5_0
Mismatched elements: 51 / 2205 (2.31%)
Max absolute difference: 0.06247
Max relative difference: 51.34
 x: array([[[ 0.315  ],
        [ 0.9746 ],
        [-0.3054 ],...
 y: array([[[ 0.2644 ],
        [ 0.964  ],
        [-0.3499 ],...
=========================
```

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: Yes

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Yes

**Comment by zerollzeng** [comment]
Filed internal bug 4392119 for this.

**Comment by zerollzeng** [comment]
This is a FP16 precision issue and the diff is expected.

BTW because all tensors in this model is FP16 precision, so in onnxruntime it will be infer with fp16, while TRT would still infer with FP32 if no fp16 enabled.
