### ISSUE TITLE
Quantization calibration error due to missing `method` argument when using pytorch-quantization

### ISSUE THREAD

**Issue by jonasdieker** [NVIDIA/TensorRT#3481]
## Description

I am using `tools/pytorch-quantization` to perform post-training quantization. When attempting to calibrate my model using instructions from [here](https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/index.html#document-tutorials/quant_resnet50), I get the following error:
```
  File "scripts/quantization.py", line 211, in test_nvidia
    module.load_calib_amax()
  File "/home/jonas/Documents/TensorRT/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py", line 244, in load_calib_amax
    calib_amax = self._calibrator.compute_amax(*args, **kwargs)
TypeError: compute_amax() missing 1 required positional argument: 'method'
```
When I then change my call and pass `"mse"` into `load_calib_amax` I get the following error:
```
  File "scripts/quantization.py", line 211, in test_nvidia
    module.load_calib_amax("mse")
  File "/home/jonas/Documents/TensorRT/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py", line 244, in load_calib_amax
    calib_amax = self._calibrator.compute_amax(*args, **kwargs)
TypeError: compute_amax() takes 1 positional argument but 2 were given
```
Looking at the methods which are being called:

https://github.com/NVIDIA/TensorRT/blob/3aaa97b91ee1dd61ea46f78683d9a3438f26192e/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py#L219-L230

and 

https://github.com/NVIDIA/TensorRT/blob/3aaa97b91ee1dd61ea46f78683d9a3438f26192e/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L126-L127

I cannot really figure out how two positional arguments are suddenly passed to `compute_amax`. Even when running the debugger or printing I can see that args only contains one string which is `"mse"`.

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: RTX 3090

**NVIDIA Driver Version**: 470.161.03

**CUDA Version**: 11.3

**CUDNN Version**: 8.2.0

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 11.3

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: yes

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Not, tried yet.

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by Data-Iab** [comment]
replace `module.load_calib_amax("mse")` with `module.load_calib_amax(method="mse")`

**Comment by jonasdieker** [comment]
I also tried that already, the problem is that `method` is expected to be a positional argument and not a keyword argument:

```
  File "scripts/quantization.py", line 103, in ptq
    module.load_calib_amax(method="mse")
  File "/home/jonas/Documents/TensorRT/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py", line 244, in load_calib_amax
    calib_amax = self._calibrator.compute_amax(*args, **kwargs)
TypeError: compute_amax() got an unexpected keyword argument 'method'
```

For now I just hard-coded "mse" in `compute_amax` but obviously this problem should be fixed properly, hence the issue. :)

**Comment by ttyio** [comment]
Hi @jonasdieker ,  did you use `histogram` or `max` when you create the `QuantDescriptor` ? thanks!

**Comment by jonasdieker** [comment]
Hi again @ttyio, I used `histogram`.

**Comment by ttyio** [comment]
I will close this since pytorch_quantization is deprecated, and we released new https://github.com/NVIDIA/TensorRT-Model-Optimizer, thanks all!
