### ISSUE TITLE
TensorRT 6 vs 5

### ISSUE THREAD

**Issue by PythonImageDeveloper** [NVIDIA/TensorRT#349]
I tested the ssd detection models like ssd_mobilenet_v2_coco and ssd_mobilenet_v1_coco on jetson nano. why v5 is faster than v6?
I get 20 FPS and 26 FPS with v6, v5 respectively, for same model.

**Comment by rmccorm4** [comment]
Hi @PythonImageDeveloper,

If you could share a model and script that can reproduce this issue repeatedly, please share it per the Issue Template.

**Comment by PythonImageDeveloper** [comment]
jetson : **nano**
jetpack : **4.3 (32.3.1)**
Tensorflow : **1.15.0 build from source**
TensorRT: **6**
I used [this repository](https://github.com/jkjung-avt/tensorrt_demos) for converting the model to tensorrt format and run the **ssd_trt.py** and **ssd_trt_aysyn.py**,

**Comment by rajeevsrao** [comment]
@PythonImageDeveloper please let us know if this is still and issue and attach a standalone repro, unless the sample is part of an NVIDIA project. Thanks.

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
