### ISSUE TITLE
NaN output when TensorRT 8.6 with hardware compatibility config

### ISSUE THREAD

**Issue by busyyang** [NVIDIA/TensorRT#3496]
## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: RTX 3070

**NVIDIA Driver Version**: 516.94

**CUDA Version**: 11.7

**CUDNN Version**: 8.6

Operating System: Windows

Python Version (if applicable): Na

Tensorflow Version (if applicable): Na

PyTorch Version (if applicable): 1.11.0 +cuda

Baremetal or Container (if so, version): Na

## Relevant Files

I trained a pytorch model with custom Op DCN from [mmdeploy/deform_conv](https://github.com/open-mmlab/mmdeploy/tree/main/csrc/mmdeploy/backend_ops/tensorrt/deform_conv). Model is converted by `.pth -> .onnx -> .trt` successfully. When I enable the hardware compatibility as `ampere+`, the output of the model will be all NaN. But If I set the hardware compatibility as none, the output of the model will be correct. Can anyone have a suggest for this issue?

I just find cublas was used in the custom op [trt_deform_conv.hpp](https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/backend_ops/tensorrt/deform_conv/trt_deform_conv.hpp) and docmentation have mentioned that cublas, cudnn will be disabled. And the information from log when model convertion mentioned that also:
~~~
[11/28/2023-11:40:56] [W] [TRT] Disabling external tactic sources (e.g. cuDNN, cuBLAS, cuBLAS LT) because either version compatibility or hardware compatibility is enabled.
~~~

Should I remove functions from cublas or cudnn for hardware compatibility inference? Or any other solution for this?

**Comment by zerollzeng** [comment]
This looks like a bug, could you please provide a reproduce for us? If possible could you please try the latest TRT 9.1/9.2 release?

@oxana-nvidia for viz.

**Comment by pranavm-nvidia** [comment]
Yes, you'd need to avoid using cuBLAS in this case.

**Comment by busyyang** [comment]
> Yes, you'd need to avoid using cuBLAS in this case.

@pranavm-nvidia  Thanks for your quick response. I wrote some cuda kernel function to replace cuBLAS library, then the output of model will be correct but performance is so much worse.
And I am curious if users can get an error when compiling or runtime when cuBLAS or cuDNN lib are used in custom op in newer version. Then, users will be able to find a solution quickly in this case.
