### ISSUE TITLE
How do I implement R-FCN in TensorRT

### ISSUE THREAD

**Issue by chunfengshiliburuni** [NVIDIA/TensorRT#35]
As I know, TensorRT provides sample of Faster R-CNN. In the sample of Faster R-CNN, Proposal and RoI Pooling are combined into one plugin. I want to ask how to use the proposal layer  exception ROI Pooling.How I can get the output of  the proposal layer?Do I need to fuse the proposal and PsRoiPooling layer? If so,how should  I to do?
Any advice is appreciated.Thank you

**Comment by PeterHuang2015** [comment]
Hi, personally, I do not really understand the question, @chunfengshiliburuni Sample code of the R-FCN/layer in Caffe/TF/MXNet/PyTorch might help you explain stuff to increase the probability to get help.

**Comment by rmccorm4** [comment]
Hi @chunfengshiliburuni,

It seems like the proposal plugin is separated out here: https://github.com/NVIDIA/TensorRT/tree/release/6.0/plugin/proposalPlugin

Hopefully this helps.
