### ISSUE TITLE
release of TensorRT v7 for jetson nano

### ISSUE THREAD

**Issue by PythonImageDeveloper** [NVIDIA/TensorRT#350]
Hi,
I correctly converted the onnx model to TensoRT v7 on host PC, but I can't convert with version 6 both on jetson nano and PC,
How long will v7 release for jetson nano?

**Comment by rmccorm4** [comment]
Hi @PythonImageDeveloper,

Sorry, but I can't release the roadmap for future releases. Stay tuned.

**Comment by rmccorm4** [comment]
Closing as duplicate of https://github.com/NVIDIA/TensorRT/issues/292, please track there.
