### ISSUE TITLE
load_calib_amax() and compute_amax() raise strange errors

### ISSUE THREAD

**Issue by talcs** [NVIDIA/TensorRT#3500]
## Description

I'm following the `pytorch_quantization` documentation.

When I call `module.load_calib_amax()`, I get this error:

```
--> 133 		module.load_calib_amax()
    134 		module.disable_calib()
    135 		module.enable_quant()

File D:\Anaconda3\lib\site-packages\pytorch_quantization\nn\modules\tensor_quantizer.py:229, in TensorQuantizer.load_calib_amax(self, *args, **kwargs)
    227 if getattr(self, '_calibrator', None) is None:
    228     raise RuntimeError("Calibrator not created.")
--> 229 calib_amax = self._calibrator.compute_amax(*args, **kwargs)
    230 #calib_amax = self._calibrator.compute_amax(method)
    231 if calib_amax is None:

TypeError: compute_amax() missing 1 required positional argument: 'method'
```

So I provided that argument to `load_calib_amax`, and **got this contradicting problem**:

```
--> 133 		module.load_calib_amax('mse')
    134 		module.disable_calib()
    135 		module.enable_quant()

File D:\Anaconda3\lib\site-packages\pytorch_quantization\nn\modules\tensor_quantizer.py:229, in TensorQuantizer.load_calib_amax(self, *args, **kwargs)
    227 if getattr(self, '_calibrator', None) is None:
    228     raise RuntimeError("Calibrator not created.")
--> 229 calib_amax = self._calibrator.compute_amax(*args, **kwargs)
    230 #calib_amax = self._calibrator.compute_amax('mse')
    231 if calib_amax is None:

TypeError: compute_amax() takes 1 positional argument but 2 were given
```

So, I edited the code at the site packages and replaced `calib_amax = self._calibrator.compute_amax(*args, **kwargs)` by `calib_amax = self._calibrator.compute_amax('mse')`  , and got the samae problem:

```
File D:\Anaconda3\lib\site-packages\pytorch_quantization\nn\modules\tensor_quantizer.py:230, in TensorQuantizer.load_calib_amax(self, *args, **kwargs)
    228     raise RuntimeError("Calibrator not created.")
    229 #calib_amax = self._calibrator.compute_amax(*args, **kwargs)
--> 230 calib_amax = self._calibrator.compute_amax('mse')
    231 if calib_amax is None:
    232     err_msg = "Calibrator returned None. This usually happens when calibrator hasn't seen any tensor."

TypeError: compute_amax() takes 1 positional argument but 2 were given
```

The problem raises from the fact that some of the module's calibrators are `HigtogramCalibrator`, which expect a `method` argument, while others are `MaxCalibrator`, which do not expect any arguments. 

## Environment

**TensorRT Version**:

**NVIDIA GPU**:

**NVIDIA Driver Version**:

**CUDA Version**:

**CUDNN Version**:

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by talcs** [comment]
You should allow the argument `method` in `MaxCalibrator`.

**Comment by zerollzeng** [comment]
dup of https://github.com/NVIDIA/TensorRT/issues/3481?

**Comment by ttyio** [comment]
fyi, the pytorch quantization will be deprecated in near future, replaced with ammo, which is already widely used in tensorrt-llm.

**Comment by ttyio** [comment]
https://github.com/NVIDIA/TensorRT-Model-Optimizer is released, I will close this, thanks all!
