### ISSUE TITLE
tensorrt 9.2 for Tensorrt llm 0.6?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/TensorRT#3514]
Hi,
I need the 9.2 equivalent of:
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz
for Tensorrt LLM 0.6..
thanks..

**Comment by zerollzeng** [comment]
Check
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.ubuntu-22.04.aarch64-gnu.cuda-12.2.tar.gz

**Comment by oscarbg** [comment]
thanks!

**Comment by zerollzeng** [comment]
Above are all available packages for TRT 9.2. We only support Linux for TRT 9, Windows and other OS support will be in TRT 10.

Reference: https://github.com/NVIDIA/TensorRT/blob/release/9.2/docker/ubuntu-22.04.Dockerfile
