### ISSUE TITLE
Invalid Node failure of TensorRT 8.6 when running a ONNX model with Squeeze Operator

### ISSUE THREAD

**Issue by hongliyu0716** [NVIDIA/TensorRT#3515]
## Description

I encountered a similar error with #3425, I appreciate the response I received acknowledging this as a limitation in TensorRT.
I wanted to inquire about the possibility of future improvements or updates that might address this limitation. As the Squeeze and CumSum operator is commonly used in deep learning models, it would be beneficial for the TensorRT community if this issue could be resolved in a future release.

## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: NVIDIA GeForce MX330

**NVIDIA Driver Version**: 470.182.03

**CUDA Version**: 11.4

**CUDNN Version**: 8.9.5

Operating System: Ubuntu 18.04

Python Version: 3.8

## Relevant Files

**Model link**: https://github.com/hongliyu0716/onnx_model/blob/main/squeeze.onnx

## Steps To Reproduce

**Commands or scripts**:
```python
import onnx
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np

onnx_path = 'squeeze.onnx'
model = onnx.load(onnx_path)
onnx.checker.check_model(model)

builder = trt.Builder(trt.Logger(trt.Logger.WARNING))
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
config = builder.create_builder_config()
config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 2 << 30)
parser = trt.OnnxParser(network, trt.Logger(trt.Logger.WARNING))
    
with open(onnx_path, 'rb') as f:
    if not parser.parse(f.read()):
        error_msg = ""
        for error in range(parser.num_errors):
            error_msg += str(parser.get_error(error))
        raise RuntimeError(error_msg)
```

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): yes

**Comment by zerollzeng** [comment]
It's a know limitation:
```
[12/07/2023-12:40:51] [E] [TRT] ModelImporter.cpp:882: While parsing node number 0 [Squeeze -> "y"]:
[12/07/2023-12:40:51] [E] [TRT] ModelImporter.cpp:883: --- Begin node ---
input: "x"
input: "axes"
output: "y"
op_type: "Squeeze"

[12/07/2023-12:40:51] [E] [TRT] ModelImporter.cpp:884: --- End node ---
[12/07/2023-12:40:51] [E] [TRT] ModelImporter.cpp:887: ERROR: ModelImporter.cpp:166 In function parseNode:
[6] Invalid Node - node_of_y
Squeeze axes input must be an initializer! Try applying constant folding on the model using Polygraphy: https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/cli/surgeon/02_folding_constants
```
@ttyio for viz.

**Comment by ttyio** [comment]
Yes, we only support constant axes for squeeze, could try polygraphy to do constant folding when see this failure: 

     polygraphy surgeon sanitize model.onnx --fold-constants --output model_folded.onnx

closing, thanks all!
