### ISSUE TITLE
CUDA Out of Memory with TensorRT 8.6.1.6 while running U2Net TRT model Inference on GPU A2000

### ISSUE THREAD

**Issue by AnushaManila** [NVIDIA/TensorRT#3526]
## Description

I'm able to run U2Net TRT Model Inference on a video for about a minute and half only
Then I see CUDA Runtime Error2 (Out of Memory)

## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: A2000

**NVIDIA Driver Version**: 510.39.01

**CUDA Version**: 11.6

**CUDNN Version**: 8.9.4

Operating System: Ubuntu 20.04

Python Version : 3.8.10

## Relevant Files

[https://github.com/NobuoTsukamoto/tensorrt-examples/blob/main/python/u2net/trt_u2net.py](url)

**Model link**:
[ONNX Model](https://drive.google.com/drive/folders/1TqFb-0XTLCuXbKvXQ0W7vOnkhOi7rT-n)

## Steps To Reproduce

**Commands or scripts**: 

Step1: Download the ONNX file from Sky-Segmentation and Post processing Git Repo or the link [here](https://drive.google.com/drive/folders/1TqFb-0XTLCuXbKvXQ0W7vOnkhOi7rT-n)

Step2: Convert ONNX to TRT using the repo [TensorRT-Alpha](https://github.com/FeiYull/TensorRT-Alpha)

Step3: Run inference on a video using the script [U2-Net TensorRT](https://github.com/NobuoTsukamoto/tensorrt-examples/blob/main/python/u2net/trt_u2net.py) 

Error Encountered after approx. 90 seconds:
![image](https://github.com/NVIDIA/TensorRT/assets/12676003/152532ec-e54f-425f-8fba-2682ff6db14d)

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: Yes using 8.6.1.6

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Yes

**Comment by zerollzeng** [comment]
Memory leak/unrelease in your code?

**Comment by zerollzeng** [comment]
Or just simply indicates that the GPU memory is insufficient for this app.

**Comment by zerollzeng** [comment]
About TRT, you can confirm this by use trtexec to build and load the engine.

**Comment by AnushaManila** [comment]
> Or just simply indicates that the GPU memory is insufficient for this app.

This can't be the case I suppose.
Because, the app runs for about 90 seconds and then throws the error.
Seems like Memory leak but I'm not sure where it is happening.

**Comment by AnushaManila** [comment]
> About TRT, you can confirm this by use trtexec to build and load the engine.

I have used trtexec to build and load the engine.
I can load the engine and start inference on a video. 
The input video is 5 minutes long but the inference stops after 1 minute and 30 seconds. 
Issue is that It never completes inference for the entire 5 minute input video.

**Comment by AnushaManila** [comment]
Found out that Generating the TensorRT Model using [this ](https://github.com/NobuoTsukamoto/tensorrt-examples/blob/main/python/detection/convert_onnxgs2trt.py) script works all fine
Not sure what is wrong with the model generated using /Tensorrt-8.6.1.6/trtexec as in [here ](https://github.com/FeiYull/TensorRT-Alpha/tree/main/u2net) though
Closing this issue
