### ISSUE TITLE
Same model 8616/8522 performance slower than 8016/8431

### ISSUE THREAD

**Issue by Oldpan** [NVIDIA/TensorRT#3529]
## Description

Hello, 
I have tested the same model using four versions: 8.0.1.6, 8.4.3.1, 8.5.2.2, and 8.6.1.6, with the same conversion script. 
The speeds were 130qps, 139qps, 100qps, and 89qps, respectively. 
I would like to know why there is such a significant difference in performance between version 8.6.1.6 and 8.0.1.6. 
Here are the nsys performance metrics for 8.0.1.6 and 8.6.1.6

8616 89qps
![8616](https://github.com/NVIDIA/TensorRT/assets/9389127/23fa63a2-6dc2-498d-9c5e-63762f8ef6ac)

8016 130qps
![8016](https://github.com/NVIDIA/TensorRT/assets/9389127/5c1fcd98-fa21-41e2-a261-0318606a3bd3)

Sorry I can't provide onnx model at the moment.

Also tried --preview=+disableExternalTacticSourcesForCore0805 , didn't work

## Environment

**TensorRT Version**: 8.0.1.6 and 8.6.1.6

**NVIDIA GPU**: 3080

**NVIDIA Driver Version**:  525.105.7

**CUDA Version**: 11.8

**CUDNN Version**: 8.7 or 8.9 

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
Which precision you are using? Does it reproduce with trtexec?

If you can public the onnx here, is it possible to share with us only? you can upload it to Gdrive and share a private link here and I'll ask for access.

**Comment by Oldpan** [comment]
@zerollzeng  I used the flag --preview=-disableExternalTacticSourcesForCore0805 --builderOptimizationLevel=4, and the performance gap disappeared, Thanks~
