### ISSUE TITLE
How to connect Proposal plugin and PyramidROIAlign_TRT plugin in python api

### ISSUE THREAD

**Issue by sunmac** [NVIDIA/TensorRT#353]
## Environment

**TensorRT Version**: 6
**GPU Type**: Tesla V100
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**Operating System + Version**: 16.04

I want to use 2 plugin that is Proposal and PyramidROIAlign_TRT. But the Proposal layer output shape is (number of box, 4, 1). Next if i use PyramidROIAlign_TRT plugin, it will :
[TensorRT] ERROR: engine.cpp (165) - Cuda Error in ~ExecutionContext: 700 (an illegal memory access was encountered)
[TensorRT] ERROR: INTERNAL_ERROR: std::exception
[TensorRT] ERROR: Parameter check failed at: ../rtSafe/safeContext.cpp::terminateCommonContext::165, condition: cudaEventDestroy(context.start) failure.
[TensorRT] ERROR: Parameter check failed at: ../rtSafe/safeContext.cpp::terminateCommonContext::170, condition: cudaEventDestroy(context.stop) failure.
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 700 (an illegal memory access was encountered)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception

The PyramidROIAlign_TRT plugin input shape is (number of box, 4). I don't know which plugin or layer can queeze the dim.

The code is:
```python
roi_box=network.add_plugin_v2(inputs=[fpn_clprob.get_output(0),fpn_bbox.get_output(0)],
                 plugin=get_trt_roi_Proposal("Proposal",fpn_clprob))
box=network.add_plugin_v2(inputs=[roi_.get_output(0),fpn.get_output(0)],
                 plugin=get_trt_roi_plugin("PyramidROIAlign_TRT",7))
```

**Comment by rmccorm4** [comment]
Hi @sunmac,

If you're asking how to reshape the output to match the expected input shape, see this comment: https://github.com/NVIDIA/TensorRT/issues/166.  I think you should be able to use a Shuffle layer as an intermediate layer to reshape the output.

**Comment by rmccorm4** [comment]
Closing since no response.
