### ISSUE TITLE
Dose the result running on DLA and GPU is different?

### ISSUE THREAD

**Issue by distant1219** [NVIDIA/TensorRT#3531]
When I run a model in GPU, I found the result is better than running on DLA.
Why there are difference between GPU and DLA  in result?
Btw, they are all int8 precision.

**Comment by zerollzeng** [comment]
It's expected. mainly 2 reasons:
1. There are little difference in the actual implementation of kernels.
2. GPU use FP32 internally while DLA use TF32, this may introduce diff and the diff will propagate through networks.

**Comment by zerollzeng** [comment]
We are putting effort to decrease/eliminate the diff, but it's not a short-term work.

**Comment by distant1219** [comment]
Thanks. I got that
