### ISSUE TITLE
why the add_normalization reutrn the bias?

### ISSUE THREAD

**Issue by dawenxi-only** [NVIDIA/TensorRT#3535]
the input is
the layer define
input = network.add_normalization(input=input, scale=ln0_scale.get_output(0), bias=ln0_bias.get_output(0), axesMask=3)
input.get_output(0).name = 'output'
network.mark_output(input.get_output(0))

and input is:
[[[[ 7.41268921e+00  1.48250774e-01  2.70819688e+00 -2.80817223e+00
    -8.45749378e+00 -8.43311027e-02 -1.11668073e-01 -2.27065578e-01
     3.36974478e+00  5.05212784e+00 -7.94141293e-01  3.88546896e+00
    -3.71683352e-02  5.16399908e+00 -2.78297520e+00 -6.77349806e+00
    -1.54891336e+00 -3.56845051e-01 -8.80371952e+00 -3.05220461e+00
     6.44236803e+00  1.58602495e+01 -4.99212313e+00  3.84769964e+00
     8.53733730e+00  1.07976519e-01  4.08217847e-01  4.27787811e-01
     1.58355117e+00  5.17913151e+00  1.12195417e-01 -6.06961012e+00
    -9.87952888e-01 -1.12338152e+01  7.65770483e+00  3.36844683e+00
    -1.30702610e+01 -4.37156916e+00 -3.31314540e+00  1.62747860e+01
     7.96933699e+00  2.70421696e+00 -1.51025832e-01  1.89020604e-01
     6.31470919e+00  2.03039065e-01  8.02962780e-02 -5.30955648e+00
    -1.19657302e+00  2.30376148e+00  5.01531506e+00  6.97232533e+00
    -4.83035374e+00 -4.04675245e+00 -2.43388748e+00  1.37593842e+02
    -3.74619484e+00  1.08682954e+00  2.14890599e+00 -3.68321304e+01
    -5.88479662e+00 -2.30427355e-01 -2.77288842e+00 -6.14078474e+00
    -4.97144747e+00  6.65623546e-01  3.71633798e-01  6.67572618e-01
    -2.59941928e-02  7.32951307e+00  1.77273810e-01  1.04990304e-01
    -6.64487410e+00  3.60566266e-02  2.09649913e-02  2.77258930e+01
    -5.24332404e-01 -4.68342733e+00 -6.32665753e-01 -6.82154894e+00
    -6.40121269e+00 -3.49891424e+00 -8.49487066e-01  1.85719633e+00
    -5.32212183e-02  3.38183701e-01  3.58467603e+00 -3.97437625e-02
     6.90435696e+00  5.08469492e-02 -4.54263163e+00  9.19479847e+00
     6.93752468e-01  3.23857188e+00 -3.08989334e+00  3.65567303e+00
    -2.45437694e+00 -5.25088198e-02 -4.35818815e+00  8.71860832e-02
    -2.19998431e+00  4.54780149e+00  8.34520435e+00 -1.60256989e+02
     2.87539035e-01 -7.80277491e-01 -5.24170017e+00  5.59020042e-01
    -5.22071409e+00  6.38641119e+00 -2.11526799e+00  2.41623926e+00
     8.29134083e+00  3.87369323e+00  1.31746531e-01  1.33281398e+00
     1.17674181e-02  6.31992340e+00 -5.95352113e-01 -3.85608792e+00
    -1.59050599e-01 -1.01514816e+00 -8.58397543e-01  5.08226871e+00
     4.11402136e-01 -1.87855411e+00  5.20211697e-01  8.49944770e-01]]]]

scale is:
[[[[2.1711438  1.3660227  2.4883137  2.1303587  2.1809692  0.22526547
    0.36813828 1.1579709  2.5885208  0.02047615 2.3828313  2.3853962
    1.0497981  2.2664516  0.7297466  1.8499018  2.4754     0.84071714
    2.1806061  1.1276053  1.7938843  1.1986002  2.617354   2.3014066
    0.31356442 0.29694778 2.2003798  2.6101105  0.45786226 2.039148
    0.87161344 1.9309956  0.20453687 2.5041225  2.8374822  2.2702785
    2.6849666  1.8816245  0.8750521  1.2129633  1.4922106  0.939676
    0.18953459 0.23297186 2.0847952  1.1714027  0.2502663  2.667998
    2.295568   2.2604644  2.5553696  0.29459128 1.4493515  0.52105826
    1.044301   0.51403135 1.5217582  0.22769503 0.90576696 0.7038607
    2.1821704  1.1949143  2.2313607  2.2655735  2.038552   1.9497161
    0.28973457 0.2990876  0.41134605 1.6694067  2.1410158  2.1075008
    2.4570506  1.4869037  0.278504   0.8429893  0.20677327 1.6731763
    0.26666707 2.012681   2.518151   1.41918    2.8632073  2.2214043
    1.3843447  0.17936073 1.7831633  1.3517555  1.3700161  0.26118279
    2.3225105  2.6062236  1.5845283  0.8507109  0.89536685 2.5371363
    1.9935356  0.29770452 0.66711503 0.3083243  2.3100476  0.43475068
    2.1940994  0.7231672  2.1916656  0.98489606 2.3340242  1.8618846
    2.518878   2.2044303  1.9662923  2.148494   1.4681808  0.5690154
    2.2960446  0.4121461  1.739394   2.4496963  2.5592504  0.3587532
    0.37108606 1.760537   2.230048   2.902408   1.0330127  2.0780737
    0.93423706 2.6385722 ]]]]

bias is:
[[[[-1.77818611e-01 -2.95781605e-02  6.19085729e-02 -1.51263550e-01
    -1.54297948e-01 -4.96161640e-01 -8.37663282e-03 -5.25287502e-02
    -2.14633599e-01  4.75525826e-01 -5.94393611e-02  1.50728196e-01
    -5.56353554e-02  7.40169734e-02 -4.42338884e-02  7.48280287e-02
     1.22455193e-03 -1.88907295e-01 -2.30181478e-02 -1.41078234e-01
    -9.71161574e-03  1.51445642e-02  7.55147412e-02 -1.54070675e-01
     8.16462860e-02 -9.89050642e-02  7.09320605e-02 -1.05683580e-01
    -2.12370843e-01 -2.32754186e-01 -2.91629471e-02 -4.84478362e-02
     1.06803522e-01 -5.05556911e-02  1.46228550e-02 -2.07343906e-01
    -1.60402209e-01  1.04218878e-01 -1.49474114e-01 -6.47074759e-01
    -1.73247084e-01 -1.20121263e-01 -3.90003949e-01  6.88643605e-02
     6.54073358e-02 -1.46660641e-01 -7.98739791e-02  1.49979129e-01
    -1.42482489e-01  2.26350985e-02 -1.16419103e-02 -1.41113907e-01
    -2.16386884e-01  1.31508395e-01  7.50228688e-02 -1.04582822e+00
    -9.68023017e-02 -1.67886019e-01 -1.65648963e-02 -2.11853221e-01
    -2.68818706e-01  6.79713092e-04 -4.87699844e-02 -9.82294884e-03
     5.85029013e-02  4.33376357e-02  3.48218717e-02 -3.26604217e-01
     4.19536233e-02 -8.95517841e-02  2.16239735e-01  1.16766049e-02
    -1.89406782e-01  5.14436029e-02 -5.74770309e-02 -4.30494696e-01
    -5.36756478e-02 -3.83570865e-02  8.91358852e-02 -1.81856796e-01
     4.28784937e-02 -4.39757295e-02  3.36893760e-02 -3.16393282e-03
    -6.54275268e-02 -4.42608386e-01 -1.89842775e-01 -1.12135619e-01
     2.09610793e-03 -1.18973024e-01  2.52080351e-01 -4.37795371e-02
     4.39370759e-02 -1.05522804e-01 -3.40976380e-02 -4.47944961e-02
    -1.19824275e-01  6.94491249e-03 -1.23847120e-01 -1.72686532e-01
    -2.13555112e-01 -1.45914704e-02  1.48358524e-01  8.07621300e-01
    -4.49280180e-02 -3.51034433e-01 -1.13924146e-02 -1.33492872e-01
     1.30137488e-01  1.26713723e-01 -9.89039838e-02  3.00403088e-02
    -1.42781496e-01  2.26346906e-02  6.80153891e-02 -3.30966324e-01
     1.25949718e-02  6.31756410e-02 -1.51101172e-01  1.58199161e-01
    -1.82484120e-01  2.11345516e-02  1.30954504e-01 -1.87583757e-03
    -1.08387299e-01  3.43073793e-02 -1.71056747e-01  1.81938365e-01]]]]

the output is same with bias.
Please give me some suggestions.Thanks.

**Comment by zerollzeng** [comment]
@dawenxi-only Can we close this?

**Comment by dawenxi-only** [comment]
sure. Thank you



---- Replied Message ----
| From | Zero ***@***.***> |
| Date | 12/09/2023 18:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [NVIDIA/TensorRT] why the add_normalization reutrn the bias? (Issue #3535) |

@dawenxi-only Can we close this?
