### ISSUE TITLE
Does TensorRT have plans to launch the C API?

### ISSUE THREAD

**Issue by guojin-yan** [NVIDIA/TensorRT#3541]
Hello, I am a user of TensorRT. The TensorRT inference model is currently the fastest in the field of model inference under the acceleration of graphics cards. With the rapid development of deep learning models, more and more developers are starting to use TensorRT inference to accelerate their models. I believe that more developers will join in the future.

 As we can see, TensorRT currently only supports C++and Python APIs and has not been extended to other APIs, including the C API. In current development, there is also a demand for the C API, and as a bridge, the C API can be used to extend interfaces such as the C # API and Java API, which will greatly help promote TensorRT in the future. Therefore, I would like to inquire if the TensorRT team has any plans to develop C API interfaces?

Thank you very much TensorRT and the developer team! I will continue to pay attention to the development of TensorRT in the future, and TensorRT has not made its own contribution.

**Comment by zerollzeng** [comment]
Closed.
