### ISSUE TITLE
Pytorch Quantization Toolkit userguide doc link error

### ISSUE THREAD

**Issue by liqikai9** [NVIDIA/TensorRT#3561]
## Description

Doc link error in here： https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization#resources 
Pytorch Quantization Toolkit [userguide](https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/userguide.html),  the link should be https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/index.html

**Comment by ttyio** [comment]
internally fixed, wait for next integration to public, thanks all, I will close this!
