### ISSUE TITLE
About pytorch quantification tools

### ISSUE THREAD

**Issue by jhl13** [NVIDIA/TensorRT#3564]
How can I replace certain convolutions with quantized versions? Using quant_modules.initialize() will replace the whole modules(e.g. all convolutions) with their quantized versions.

**Comment by Data-Iab** [comment]
in this case avoid using initialize() and replace layer per layer. part of how I do it :
(I didn't test this code but I hope the idea is clear)
```python

import pytorch_quantization.nn as quant_nn
from copy import deepcopy


LAYER2REPLACE = [
    # layer_name1,
    # layer_name2,
    # layer_name3,
    # ...
]

def set_module(model, submodule_key, module):
    tokens = submodule_key.split('.')
    sub_tokens = tokens[:-1]
    cur_mod = model
    for s in sub_tokens:
        cur_mod = getattr(cur_mod, s)
    setattr(cur_mod, tokens[-1], module)


def reload_weights(func):
    """Reloads weights after replacing an instance of quantized class"""
    def wrap(module):
        weights = deepcopy(module.state_dict())
        result = func(module)
        result.load_state_dict(weights)
        return result
    
    return wrap


@reload_weights
def _2quant_conv2d(oldb):
    """Replaces instance of torch.nn.Conv2d with instance of quant_nn.QuantConv2d"""
    newb = quant_nn.QuantConv2d(
        stride=oldb.stride,
        groups=oldb.groups,
        padding=oldb.padding,
        dilation=oldb.dilation,
        bias=oldb.bias is not None,
        in_channels=oldb.in_channels,
        kernel_size=oldb.kernel_size,
        out_channels=oldb.out_channels,
        padding_mode=oldb.padding_mode,
        )

    return newb


model = MyModel()
for name, child in model.named_modules():
    if name in LAYER2REPLACE:
        set_module(model, name, _2quant_conv2d(child).to(child.device))


```

**Comment by jhl13** [comment]
> in this case avoid using initialize() and replace layer per layer. part of how I do it : (I didn't test this code but I hope the idea is clear)
> 
> ```python
> import pytorch_quantization.nn as quant_nn
> from copy import deepcopy
> 
> 
> LAYER2REPLACE = [
>     # layer_name1,
>     # layer_name2,
>     # layer_name3,
>     # ...
> ]
> 
> def set_module(model, submodule_key, module):
>     tokens = submodule_key.split('.')
>     sub_tokens = tokens[:-1]
>     cur_mod = model
>     for s in sub_tokens:
>         cur_mod = getattr(cur_mod, s)
>     setattr(cur_mod, tokens[-1], module)
> 
> 
> def reload_weights(func):
>     """Reloads weights after replacing an instance of quantized class"""
>     def wrap(module):
>         weights = deepcopy(module.state_dict())
>         result = func(module)
>         result.load_state_dict(weights)
>         return result
>     
>     return wrap
> 
> 
> @reload_weights
> def _2quant_conv2d(oldb):
>     """Replaces instance of torch.nn.Conv2d with instance of quant_nn.QuantConv2d"""
>     newb = quant_nn.QuantConv2d(
>         stride=oldb.stride,
>         groups=oldb.groups,
>         padding=oldb.padding,
>         dilation=oldb.dilation,
>         bias=oldb.bias is not None,
>         in_channels=oldb.in_channels,
>         kernel_size=oldb.kernel_size,
>         out_channels=oldb.out_channels,
>         padding_mode=oldb.padding_mode,
>         )
> 
>     return newb
> 
> 
> model = MyModel()
> for name, child in model.named_modules():
>     if name in LAYER2REPLACE:
>         set_module(model, name, _2quant_conv2d(child).to(child.device))
> ```

Thank you! It works.
