### ISSUE TITLE
the pth  and onnx resout is the same ,but the trt resout is different,why?

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/TensorRT#3565]
trt8.6 version,p3.9.
the trt model is got from the onnx model.

**Comment by zerollzeng** [comment]
1. What precision you are using?
2. How big is the diff?
3. Could you please provide a reproduce?

**Comment by henbucuoshanghai** [comment]
trt8.6 version，the output  like : 
its fp16 presion.
 trt out tensor([1.8105, 1.6924, 1.6201, 1.6309, 1.7002, 1.7480, 1.7363, 1.7207, 1.6885,
        1.6387, 1.6553, 1.5928, 1.6172, 1.6455, 1.5723, 1.6094, 1.6875, 1.7061,
        1.6660, 1.6699, 1.6973, 1.6641, 1.6738, 1.7051, 1.6484, 1.6885, 1.7139,
        1.6914, 1.6475, 1.5664, 1.5684, 1.6074, 1.5654, 1.5596, 1.6201, 1.6445,
        1.6133, 1.6289, 1.6094, 1.5479, 1.5908, 1.6221, 1.6689, 1.7471, 1.7686,
        1.7461, 1.7832, 1.8232, 1.7812, 1.6523])
pth out tensor([1.7094, 1.7481, 1.7582, 1.7630, 1.7692, 1.8539, 1.9239, 1.8820, 1.7632,
        1.7459, 1.7277, 1.6817, 1.6298, 1.5764, 1.6278, 1.6670, 1.6893, 1.6823,
        1.7146, 1.7058, 1.6632, 1.6209, 1.5932, 1.5746, 1.6548, 1.7445, 1.7886,
        1.8301, 1.9130, 1.9107, 1.8714, 1.8876, 1.8196, 1.6821, 1.5758, 1.5747,
        1.6745, 1.7967, 1.7406, 1.6620, 1.6265, 1.6051, 1.6892, 1.7275, 1.6392,
        1.5003, 1.5267, 1.6268, 1.6894, 1.7013])

**Comment by zerollzeng** [comment]
Could you please provide the onnx? would be great if you can also provide a real input data that can reproduce the issue.

**Comment by henbucuoshanghai** [comment]
thank u for your help?when i use fp16 or int8,the precision is  a little big,its right?

**Comment by zerollzeng** [comment]
I cannot get any conclusion at this moment, we need to check the diff between TRT and onnxruntime first. sometimes the issues happens when exporting onnx. so an ONNX model is very helpful to debug this.

**Comment by zerollzeng** [comment]
You can also check this with polygraphy very quickly, see https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/run/01_comparing_frameworks

**Comment by henbucuoshanghai** [comment]
tky，I solve this .
