### ISSUE TITLE
enqueueV2 return error  

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#3567]
## Description   
enqueueV2 return error  ， What situation will cause this ?

## Environment

**TensorRT Version**: TRT8510

**NVIDIA GPU**:ORIN-X

**NVIDIA Driver Version**:

**CUDA Version**:11.4

**Comment by zerollzeng** [comment]
What error did you see and can you reproduce it with trtexec?

**Comment by lix19937** [comment]
@zerollzeng   I use mutli-pthread to run plan (each thread run a different plan), when a plan (on dla device)  
```
[12/24/2023-14:48:13] [I] Starting inference
[12/24/2023-14:48:13] [E] Error[1]: [cudlaUtils.cpp::submit::95] Error Code 1: DLA (Failed to submit program to DLA engine.)
[12/24/2023-14:48:13] [E] Error occurred during inference
```

**Comment by lix19937** [comment]
I think drive os 6060 maybe have some bug of DLA

**Comment by lix19937** [comment]
> could you please try latest 6080/6090?

Our OTA version is drive os 6060

**Comment by zerollzeng** [comment]
I remember we have some improvement on this since 6.0.8.0(DLA 3.14), and if you need a patch on 6.0.6 then you need to request help from your company's Tier-1 or other supporters.

**Comment by lix19937** [comment]
ok, thanks.
