### ISSUE TITLE
Cast_1702: cannot use precision Float for IIdentityLayer that converts from booleans to booleans

### ISSUE THREAD

**Issue by matrix97317** [NVIDIA/TensorRT#3570]
## Description
ONNX：
![image](https://github.com/NVIDIA/TensorRT/assets/76250408/79d9cad4-fcc3-491a-ab8a-13fe8e85efca)

TRT Command:
`trtexec --onnx=xxxx.onnx --precisionConstraints=obey --layerPrecisions='*':'fp32' ,'xxxx_layer':'fp16' --fp16`

Error:
![image](https://github.com/NVIDIA/TensorRT/assets/76250408/71899305-9d26-4d82-b48e-0f269f05e7d2)

## Environment

**TensorRT Version**: 8.5.10

**NVIDIA GPU**:  A10

**NVIDIA Driver Version**: 470.199.02

**CUDA Version**: "11.8.0.065"
**CUDNN Version**: "8.7.0.84"

Operating System: ubuntu1~20.04.1

Python Version (if applicable): 3.8

PyTorch Version (if applicable): 1.13

**Comment by Data-Iab** [comment]
As the logs say, you're forcing the precision to fp16 (`--precisionConstraints=obey`) while you have a layer that runs on booleans.
Either change the `--precisionConstraints` to `prefer` or replace your `where` with float operations to avoid the cast. my favorite way to do it :
```python
mask_value = 199
replace_value = -1
mask = torch.abs(output - mask_value).ceil()
mask = torch.clip(mask, 0, 1)
# replace all 199s with -1
output = output * mask + replace_value * (1 - mask)
```

**Comment by matrix97317** [comment]
Great!
