### ISSUE TITLE
Need help optimizing Bert model inference with LayerNormPlugin in TensorRT

### ISSUE THREAD

**Issue by Nusselder9** [NVIDIA/TensorRT#3573]
I've been working on accelerating the inference of a Bert model recently. By using the original ONNX build engine without any modifications, I was able to achieve a speed of 0.75ms. 

However, when I replaced the LayerNorm layer in the network with the Oneflow version of LayerNormPlugin, the speed actually decreased. 

I have a feeling that the inserted plugin might be interfering with TensorRT's automatic optimization. I'm currently unsure about the next steps to take. Any suggestions or insights would be greatly appreciated.

**Comment by zerollzeng** [comment]
> However, when I replaced the LayerNorm layer in the network with the Oneflow version of LayerNormPlugin, the speed actually decreased.

Check layer profile result, e.g. with `trtexec --dumpProfile`, I suspect it's cause by the plugin.
