### ISSUE TITLE
I NEED  CUDA 12.2、orin arm64  TensorRT 9.2.0.5

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT#3574]
I need CUDA 12.2、orin arm64,   TensorRT 9.2.0.5 . where can i download. thanks
i run 'git submodule update --init --recursive' withour error, but i do not find the target file (pip list | grep tensorrt  is null).

![image](https://github.com/NVIDIA/TensorRT/assets/17873056/4668ced9-1c0b-4c1b-bd91-bd64241a3df5)

**Comment by zerollzeng** [comment]
TRT 9 doesn't support aarch64 platform officially, you have to wait for TRT 10.

**Comment by whk6688** [comment]
when does TRT10 release? thanks! Is there any not offcial method?  so depressed!

**Comment by johnnynunez** [comment]
> TRT 9 doesn't support aarch64 platform officially, you have to wait for TRT 10.

why 10?

**Comment by zerollzeng** [comment]
Please wait for the official announcement :-)

TRT 9 is a special release for LLM on x86, and we didn't release it publicly in dev zone. full platform support is planned in TRT 10.

**Comment by johnnynunez** [comment]
> Please wait for the official announcement :-)
> 
> TRT 9 is a special release for LLM on x86, and we didn't release it publicly in dev zone. full platform support is planned in TRT 10.

Thanks for this.
