### ISSUE TITLE
Attention did not use mha kernel (muti head attention) on orin TRT8.6.10

### ISSUE THREAD

**Issue by Nusselder9** [NVIDIA/TensorRT#3575]
My model has an attention module like this:
<img width="960" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/71872790/675d2b03-ecad-4010-bed3-b1841998449f">

It did **not** use mha kernel on my orin with **TensorRT8.6.10 (os 6.0.7.0)**:
<img width="2005" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/71872790/168e1666-9287-44c9-918b-dd0b8942b41e">

However, on **x86 TensorRT 8.6.1**, it can use mha kernel:
<img width="480" alt="image (2)" src="https://github.com/NVIDIA/TensorRT/assets/71872790/be487738-a546-4ff2-afcf-164486cca60e">

I would like to use mha on orin. What can I do? Thanks!

**Comment by Nusselder9** [comment]
To avoid uncertain influence, I export a toy attention with seq_length=128, batchsize=1, emd_dim=256 like this:
<img width="482" alt="1" src="https://github.com/NVIDIA/TensorRT/assets/71872790/83e752a2-6145-466f-8074-62937323e40c">

However, it still can NOT use mha kernel on orin TRT8.6.10:
<img width="888" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/71872790/4a4aab94-4490-4777-916f-81c35b99cc6a">

Please give some help. Thanks very much!

**Comment by zerollzeng** [comment]
@nvpohanh I have a vague memory that this is expected(I've seen a internal bug before) that the fused mha kernel doens't enable in TRT 8.6, am I correct?

**Comment by nvpohanh** [comment]
Is it possible to try TRT 9.2? https://github.com/NVIDIA/TensorRT/blob/release/9.2/docker/ubuntu-22.04.Dockerfile#L92-L95

**Comment by Nusselder9** [comment]
Sorry but our business scenario won't be able to upgrade TRT within the near future. 

Is there a way to fix or avoid the bug and enable fused mha on TRT 8.6? @zerollzeng @nvpohanh 

thx!

**Comment by nvpohanh** [comment]
Could you try adding a LayerNorm into the network? That will encourage TRT 8.6 to trigger the Transformer-specific fusions.

**Comment by Nusselder9** [comment]
Thanks for your reply.@nvpohanh  I have tried adding LN after attention, but it does not work.
<img width="468" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/71872790/8e27e24f-6989-4c9b-a13a-52824f11f267">

<img width="1362" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/71872790/36060c13-4947-40b0-9eca-5f9bb34d1b11">

**Comment by nvpohanh** [comment]
@Nusselder9 could you share the ONNX with the LayerNorm? TRT 8.6 has quite restricted MHA pattern matching code and we need to find out why it didn't trigger the fusion. TRT 9.2 has much looser checking.

I would also try to make the MHA looks like:

```
[B, S, H] -MatMul-> [B, S, H] -Reshape-> [B, S, N, h] -Transpose-> [B, N, S, h] -> MatMul -> [B, N, S, S] -> MatMul -> [B, N, S, h] -Transpose-> [B, S, N, h] -Reshape-> [B, S, H] -LayerNorm->...
[B, S, H] -MatMul-> [B, S, H] -Reshape-> [B, S, N, h] -Transpose-> [B, N, h, S] ---^                                        ^
[B, S, H] -MatMul-> [B, S, H] -Reshape-> [B, S, N, h] -Transpose-> [B, N, S, h] ---------------------------------
```

where B=1, S=128, H=256, N=8, h=32

**Comment by Nusselder9** [comment]
Thanks for your kind reply. The attachment is my attention.
[attention.zip](https://github.com/NVIDIA/TensorRT/files/13810286/attention.zip)
The zip file has two type of attention and both of them can not use fmha.

**Comment by nvpohanh** [comment]
@Nusselder9 Could you share the ONNX files **with the LayerNorm**? Thanks!

**Comment by Nusselder9** [comment]
Here is attention with LN. @nvpohanh 
[attention_ln.zip](https://github.com/NVIDIA/TensorRT/files/13815256/attention_ln.zip)

**Comment by nvpohanh** [comment]
Filed internal tracker 4438093 . Will let you know if we have some findings. Thanks

**Comment by nvpohanh** [comment]
Internal investigation shows that TRT 8.6.10 did not have any MHA fusion support on Orin. Could you try TRT 8.6.11?

**Comment by Nusselder9** [comment]
thanks, I will try.

**Comment by lix19937** [comment]
@nvpohanh  I think the question `mha kernel` is not inaccurate description. 

> Internal investigation shows that TRT 8.6.10 did not have any MHA fusion support on Orin. Could you try TRT 8.6.11?   

If an onnx include stdand transformer struct(like ViT decoder),  TRT 8.6.11 can open MHA fusion ? 

In my opinion, `CustomQKVToContextPluginDynamic` can do some fusion but it need match some conditions if user use plugin.

**Comment by XuDeshengCat** [comment]
Did TRT 8.6.13 have any MHA fusion support？

**Comment by Feynman1999** [comment]
Did TRT 9.2 have any MHA fusion support？ and how to make them work
