### ISSUE TITLE
Mobilenet onnx model parsing fails with TensorRT 7

### ISSUE THREAD

**Issue by svnoesis** [NVIDIA/TensorRT#358]
## Description

I am trying to run inference with Mobilenetv1 using onnx model file. But the `trt.OnnxParser` call fails on TensorRT 7.0.0.11 with the following error. The same model works fine with TensorRT 6.0.1.

Below is the error I see
```raise RuntimeError("MobileNet onnx model parsing failed! Error: {:}".format(parser.get_error(0).desc()))

RuntimeError: MobileNet onnx model parsing failed! 
Error: Assertion failed: !_importer_ctx.network()->hasImplicitBatchDimension() &&
"This version of the ONNX parser only supports TensorRT INetworkDefinitions
with an explicit batch dimension.

Please ensure the network was created using the EXPLICIT_BATCH NetworkDefinitionCreationFlag."
```

Is there a way to avoid the explicit_batch definition ?

Also I noticed that if I use `onnx2trt` to parse the model, it succeeds without any errors.

Can anyone please explain this ?

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: T4
**Nvidia Driver Version**:  440.33.01
**CUDA Version**:  10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: RHEL 7.6
**Python Version (if applicable)**: Python 3.7
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

I used the model file [mobilenet_sym_no_bn.onnx](https://github.com/mlperf/inference_results_v0.5/blob/master/closed/NVIDIA/code/mobilenet/tensorrt/mobilenet_sym_no_bn.onnx)
The inference code was from [here](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/NVIDIA/code/mobilenet/tensorrt).

**Comment by rmccorm4** [comment]
Hi @svnoesis,

As the error says, TensorRT 7 requires that you create the network with the EXPLICIT_BATCH flag when parsing ONNX models. If you wanted to edit the existing code you referenced, it's a simple one line add: https://github.com/mlperf/inference_results_v0.5/blob/master/closed/NVIDIA/code/mobilenet/tensorrt/MobileNet.py#L57-L58

```python
            network_creation_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_PRECISION)
            network_creation_flag |= 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
            self.network = self.builder.create_network(network_creation_flag)
```

If you wanted the code to work for both TRT6 and TRT7, you could add an if statement based on the version:
```python
            network_creation_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_PRECISION)
            major, minor, patch = trt.__version__.split('.')
            if int(major) >= 7:            
                network_creation_flag |= 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
            self.network = self.builder.create_network(network_creation_flag)
```

**Comment by svnoesis** [comment]
@rmccorm4 Thanks for the clarification.
I had edited the code to use the EXPLICIT_BATCH flag while creating the network. That got past the ONNX parsing step, but landed into another error as below:

```[TensorRT] ERROR: (Unnamed Layer* 0) [Convolution] cannot have int8 output in explicit precision mode. All weighted layers running in int8 should have output in FP32. This layer should be followed by a quantizing scale layer to scale fp32 output to int8 range.
```
As per the documentation EXPLICIT_PRECISION flag is supported in TensorRT 6 and the code was working fine with TensorRT6. Only with the introduction of the above change (for EXPLICIT_BATCH) seeing this error. Hence was the question on avoiding explicit batch definition.
Or is this a new check introduced in TensorRT 7 ? And is there a way to get rid of this error in TensorRT 7 ?
