### ISSUE TITLE
compile the sample failed.

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/TensorRT#3582]
make[1]: 进入目录“/home/xxx/TensorRT-8.5.1.7/samples/sampleAlgorithmSelector”
../Makefile.config:13: CUDA_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDA_INSTALL_DIR=<cuda_directory> to change.
../Makefile.config:18: CUDNN_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
../Makefile.config:38: TRT_LIB_DIR is not specified, searching , ../../lib, ../lib by default, use TRT_LIB_DIR=<trt_lib_directory> to change.
../Makefile.config:43: PROTOBUF_INSTALL_DIR variable is not specified, use PROTOBUF_INSTALL_DIR=<protobuf_directory> to change. Using default value: /usr/lib/x86_64-linux-gnu
Linking: ../../bin/sample_algorithm_selector_debug
g++ -o ../../bin/sample_algorithm_selector_debug  -L"/usr/local/cuda/lib64" -Wl,-rpath-link="/usr/local/cuda/lib64" -L"/usr/local/cuda/lib64" -Wl,-rpath-link="/usr/local/cuda/lib64" -L"../lib" -L"../../lib" -L"" -Wl,-rpath-link=""  -L"/usr/lib/x86_64-linux-gnu/lib" -Wl,-rpath-link="/usr/lib/x86_64-linux-gnu/lib" -L"" -Wl,-rpath-link="" -L../../bin  -Wl,--start-group -lnvinfer -lnvparsers -lnvinfer_plugin -lnvonnxparser -lcudart -lcublas -lcudnn -lrt -ldl -lpthread  ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/sampleAlgorithmSelector.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleInference.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleUtils.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleOptions.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/logger.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/getOptions.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleReporting.o ../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleEngines.o -Wl,--end-group
../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleEngines.o：在函数‘sample::(anonymous namespace)::CaffeBufferShutter::~CaffeBufferShutter()’中：
/home/xxx/TensorRT-8.5.1.7/samples/sampleAlgorithmSelector/../common/sampleEngines.cpp:59：对‘nvcaffeparser1::shutdownProtobufLibrary()’未定义的引用
../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleEngines.o：在函数‘sample::(anonymous namespace)::UffBufferShutter::~UffBufferShutter()’中：
/home/xxx/TensorRT-8.5.1.7/samples/sampleAlgorithmSelector/../common/sampleEngines.cpp:67：对‘nvuffparser::shutdownProtobufLibrary()’未定义的引用
../../bin/dchobj/sampleAlgorithmSelector/sampleAlgorithmSelector/../common/sampleEngines.o：在函数‘sample::modelToNetwork(sample::ModelOptions const&, nvinfer1::INetworkDefinition&, std::ostream&)’中：
/home/xxx/TensorRT-8.5.1.7/samples/sampleAlgorithmSelector/../common/sampleEngines.cpp:208：对‘nvcaffeparser1::createCaffeParser()’未定义的引用
/home/xxx/TensorRT-8.5.1.7/samples/sampleAlgorithmSelector/../common/sampleEngines.cpp:234：对‘nvuffparser::createUffParser()’未定义的引用
../../lib/libnvonnxparser.so：对‘initLibNvInferPlugins’未定义的引用
collect2: error: ld returned 1 exit status
../Makefile.config:345: recipe for target '../../bin/sample_algorithm_selector_debug' failed
make[1]: *** [../../bin/sample_algorithm_selector_debug] Error 1
make[1]: 离开目录“/home/xxx/TensorRT-8.5.1.7/samples/sampleAlgorithmSelector”
Makefile:82: recipe for target 'all' failed
make: *** [all] Error 2

when i change the tensorrt to 8.0 edition, the sample can compile successfully.
the cuda is 11.8.

**Comment by zerollzeng** [comment]
Looks like an env issue, you can try our official TRT docker image, e.g. https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel-22-12.html#rel-22-12

also it's encouraged to use latest release.

**Comment by GeneralJing** [comment]
thank you.
