### ISSUE TITLE
Stable Diffusion XL and controlnet support

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [NVIDIA/TensorRT#3586]
TensorRT branch  9.2 

Now only SD1.5+controlnet 
Is there any plan to support SDXL+controlnet

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
@rajeevsrao  ^ ^

**Comment by ttyio** [comment]
Sorry I will close this since no response, I read this as no plan to add this in the near plan.
