### ISSUE TITLE
Unable to build model for TensorRT 9.2.0.5 for TensorRT-LLM when running trtllm-build on GPU 

### ISSUE THREAD

**Issue by K-L-Chen** [NVIDIA/TensorRT#3591]
## Description
I'm running into an issue where I am unable to generate a model for OPT-125M and Bloom-560M using the trtllm-build function, receiving a CPP error message "Assertion validateCaskKLibSize(buffer.size) failed" with Error Code 2.
![image](https://github.com/NVIDIA/TensorRT/assets/78221899/89262e6b-a8f9-4b94-a778-dc18e051d335)

## Environment

**TensorRT Version**: 9.2.0.post12.dev5

**NVIDIA GPU**: RTX 3050 Laptop

**NVIDIA Driver Version**: 546.33

**CUDA Version**: 12.2

**CUDNN Version**: 8.9.7

Operating System: Windows 11 Pro ver. 10.0.22621

Python Version (if applicable): 3.10.11

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version): Baremetal

## Relevant Files
**TensorRT 9.2.0.5**: https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.windows10.x86_64.cuda-12.2.llm.beta.zip
**Model link**: https://huggingface.co/facebook/opt-125m

## Steps To Reproduce

1. Build TensorRT-LLM Bare-metal from source following the Windows guide at https://github.com/NVIDIA/TensorRT-LLM/blob/main/windows/README.md#building-from-source

2. Clone https://huggingface.co/facebook/opt-125m and follow build guide at https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/opt

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Comment by zerollzeng** [comment]
@nvpohanh I don't know about Windows, could you please help assign someone to help take a look? Thanks!

**Comment by K-L-Chen** [comment]
To anyone who still has concerns over this issue and is on Windows, it seems that installing *WSL* and following the *Linux* installation guide works.
