### ISSUE TITLE
When running polygraphy with --trt-outputs mark all I get and error even though --trt runs without error

### ISSUE THREAD

**Issue by ninono12345** [NVIDIA/TensorRT#3596]
## Description

When running polygraphy on my onnx model like so:
`polygraphy run tomp101_head_latest3.onnx --trt`
I get no error (but the model has major accuracy issues), but when running like this:
`polygraphy run tomp101_head_latest3.onnx --trt --trt-outputs mark all`
I get this error:

[E] 2: [myelinBuilderUtils.cpp::nvinfer1::builder::`anonymous-namespace'::getMyelinSupportTypeNoConstraints::<lambda_c8c5dc80e412fe409ae2905ffac0b6a0>::operator ()::752] Error Code 2: Internal Error ([ShapeHostToDeviceCopy 0] requires bool or uint8 I/O but node can not be handled by Myelin. Operation is not supported.)
[!] Invalid Engine. Please ensure the engine was built correctly
[E] FAILED | Runtime: 8.102s | Command: C:\Users\Tomas\AppData\Local\Programs\Python\Python310\Scripts\polygraphy run tomp101_head_latest3.onnx --trt --trt-outputs mark all

if i sanitize the model with:
`polygraphy surgeon sanitize tomp101_head_latest3.onnx --fold-constants -o folded.onnx`
the same error still occurs

Can this be the root cause of my accuracy issues?

the onnx model was generated with this code:

`input_names = ['sample_x', 'train_samples', 'target_labels', 'train_ltrb']`
`output_names = ['target_scores', 'bbreg_test_feat_enc', 'bbreg_weights']`

`torch.onnx.export(model,

                model_inputs,
                "tomp101_head_latest3.onnx",
                verbose=False,
                export_params=True,
                do_constant_folding=True,
                opset_version=16,
                input_names=input_names,
                output_names=output_names,
                dynamic_axes={'sample_x':{0:'batch_size'},
                            'train_samples':{0:'batch_size'},
                            'target_labels':{0:'batch_size'},
                            'train_ltrb':{0:'batch_size'},
                            'target_scores':{0:'batch_size'},
                            'bbreg_test_feat_enc':{0:'batch_size'},
                            'bbreg_weights':{0:'batch_size'}})`

By the way, if I remove the dynamic_axes, this error is returned, even though I made sure that everything is on cuda, or on 2nd export attempt, on cpu:
`params_dict = _C._jit_pass_onnx_constant_fold(`
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

ALSO

onnxruntime cannot run this model, when attempting to run:
`polygraphy run tomp101_head_latest3.onnx --onnxrt`
getting this error:

return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_7' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:30 onnxruntime::ReshapeHelper::ReshapeHelper i < input_shape.NumDimensions() was false. The dimension with value zero exceeds the dimension size of the input tensor.

Any help is appreciated, if any more info is needed, please let me know!!!!!!

Thank you

---------------------------------------------------------------------------------------

Update fixed this:

[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_7' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:30 onnxruntime::ReshapeHelper::ReshapeHelper i < input_shape.NumDimensions() was false. The dimension with value zero exceeds the dimension size of the input tensor.

by changing the onnx with graph surgeon the /Reshape_7 from allowzero = 0 to allowzero = 1

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: GTX 1660 Ti

**NVIDIA Driver Version**: 546.01

**CUDA Version**: 12.1

**CUDNN Version**: 8.9.7

Operating System: Windows 10

Python Version: 3.10.13

PyTorch Version: 2.1.2+cu121

Baremetal or Container (if so, version): No environment, run on straight Windows 10

## Relevant Files

**ONNX model link**: https://drive.google.com/file/d/1-itEFkapRXvYkKbknpFczqPFHyb3OrjK/view?usp=drive_link
**trtexec Verbose log.txt (without warnings)** [lognew.txt](https://github.com/NVIDIA/TensorRT/files/13924898/lognew.txt)

**Comment by ninono12345** [comment]
Hello @zerollzeng and @pranavm-nvidia. Thank you for your answers, and I apologize for a late reply.
I've been at this project for a very long time, and I just keep failing to make it work right...

If you have some time, could you please give me suggestions on how should I approach the accuracy issue?
I cannot understand where the problem could be, the only warning I get is that some int64 weights are being clamped to int32. I have tried a lot of different scenarios, but nothing seems to work

Please can you point me to the right direction. Maybe I need to quantize the pytorch model to int8, then convert it  to TensorRT?
Or maybe I can use some other polygraphy tools?

Thank you very much for your help

**Comment by pranavm-nvidia** [comment]
Does [this guide](https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/Polygraphy/how-to/debug_accuracy.md) help? Unfortunately, accuracy issues are pretty hard to debug and there's no silver bullet.

**Comment by ninono12345** [comment]
Thank you @pranavm-nvidia, @zerollzeng, I have tried some of these out, the mark-all gave me hope, but it if you say it is unreliable, then I tried `polygraphy debug build my_in.onnx --save-tactics replay.json --artifacts-dir replays --artifacts replay.json --until=10 --check polygraphy run my_out.engine --trt --load-outputs golden.json`, got 2 bad and 8 good tactics, but to be honest, I don't know what to do with these files and how to put them to use

**Comment by ninono12345** [comment]
perhaps somehow I need to specify, that my accuracy constraints should be tougher (should be an even smaller difference when comparing outputs) so only the most accurate ones are defined as good? In that case haw could I use those tactics to generate my engine based on them

I perhaps I completely misunderstood the meaning of --save tactics option?

**Comment by ninono12345** [comment]
@pranavm-nvidia, @zerollzeng I apologize for my last response. It seems that I didn't pay enough attention to [this guide](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/debug/02_reducing_failing_onnx_models). I've followed the instructions, the model has been reduced to the part where the accuracy starts to fail.

Here is a NETRON graph of a model reduced in bisect mode:
![filter_predictor_op17_mod_sanitized_reduced](https://github.com/NVIDIA/TensorRT/assets/116962708/839892d1-07af-4caf-8511-997ebb084c66)

and here is a NETRON graph of a model further reduced in layer mode:
![filter_predictor_op17_mod_sanitized_reduced_linear](https://github.com/NVIDIA/TensorRT/assets/116962708/548e6bff-bcb7-491d-9f57-6c59b0a7918c)

Here, if you compare the graphs, because the first element of MultiheadAttention MatMul is already failing, I am assuming that there are more failing elements inside MultiheadAttention.
This MultiheadAttention is part of a transformers encoder/decoder.

the full code of the transformer in use (MultiheadAttention highlighted); the accuracy error happens in self.multihead_attn variable:

`    import copy
    import torch
    import torch.nn.functional as F
    from torch import nn

    class TransformerDecoderInstance(nn.Module):
        def __init__(self, d_model=512, nhead=8, num_decoder_layers=6, dim_feedforward=2048,
                     dropout=0.1, activation="relu", normalize_before=False, return_intermediate_dec=False):
            super().__init__()

            decoder_layer = TransformerDecoderLayer(d_model, nhead, dim_feedforward, dropout, activation, normalize_before)
            decoder_norm = nn.LayerNorm(d_model)
            self.decoder = TransformerDecoder(decoder_layer, num_decoder_layers, decoder_norm,
                                              return_intermediate=return_intermediate_dec)

            self._reset_parameters()

            self.d_model = d_model
            self.nhead = nhead

        def _reset_parameters(self):
            for p in self.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p)

        def forward(self, src, mask, query_embed, pos_embed):
            if query_embed.dim() == 2:
                query_embed = query_embed.unsqueeze(1).repeat(1, src.shape[1], 1)

            tgt = torch.zeros_like(query_embed)
            hs = self.decoder(tgt, src, memory_key_padding_mask=mask, pos=pos_embed, query_pos=query_embed)
            return hs.transpose(1, 2)


    class TransformerEncoderInstance(nn.Module):
        def __init__(self, d_model=512, nhead=8, num_encoder_layers=6, dim_feedforward=2048,
                     dropout=0.1, activation="relu", normalize_before=False):
            super().__init__()

            encoder_layer = TransformerEncoderLayer(d_model, nhead, dim_feedforward, dropout, activation, normalize_before)
            encoder_norm = nn.LayerNorm(d_model) if normalize_before else None
            self.encoder = TransformerEncoder(encoder_layer, num_encoder_layers, encoder_norm)

            self._reset_parameters()

            self.d_model = d_model
            self.nhead = nhead

        def _reset_parameters(self):
            for p in self.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p)

        def forward(self, src, mask, pos_embed):
            memory = self.encoder(src, src_key_padding_mask=mask, pos=pos_embed)
            return memory


    class Transformer(nn.Module):
        def __init__(self, d_model=512, nhead=8, num_encoder_layers=6, num_decoder_layers=6, dim_feedforward=2048,
                     dropout=0.1, activation="relu", normalize_before=False, return_intermediate_dec=False):
            super().__init__()

            encoder_layer = TransformerEncoderLayer(d_model, nhead, dim_feedforward, dropout, activation, normalize_before)
            encoder_norm = nn.LayerNorm(d_model) if normalize_before else None
            self.encoder = TransformerEncoder(encoder_layer, num_encoder_layers, encoder_norm)

            decoder_layer = TransformerDecoderLayer(d_model, nhead, dim_feedforward, dropout, activation, normalize_before)
            decoder_norm = nn.LayerNorm(d_model)
            self.decoder = TransformerDecoder(decoder_layer, num_decoder_layers, decoder_norm,
                                              return_intermediate=return_intermediate_dec)

            self._reset_parameters()

            self.d_model = d_model
            self.nhead = nhead

        def _reset_parameters(self):
            for p in self.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p)

        def forward(self, src, mask, query_embed, pos_embed):
            query_embed = query_embed.unsqueeze(1).repeat(1, src.shape[1], 1)

            tgt = torch.zeros_like(query_embed)
            memory = self.encoder(src, src_key_padding_mask=mask, pos=pos_embed)
            hs = self.decoder(tgt, memory, memory_key_padding_mask=mask, pos=pos_embed, query_pos=query_embed)
            return hs.transpose(1, 2), memory


    class TransformerEncoder(nn.Module):
        def __init__(self, encoder_layer, num_layers, norm=None):
            super().__init__()
            self.layers = _get_clones(encoder_layer, num_layers)
            self.num_layers = num_layers
            self.norm = norm

        def forward(self, src, mask=None, src_key_padding_mask=None, pos=None):
            output = src

            for layer in self.layers:
                output = layer(output, src_mask=mask, src_key_padding_mask=src_key_padding_mask, pos=pos)

            if self.norm is not None:
                output = self.norm(output)

            return output


    class TransformerDecoder(nn.Module):

        def __init__(self, decoder_layer, num_layers, norm=None, return_intermediate=False):
            super().__init__()
            self.layers = _get_clones(decoder_layer, num_layers)
            self.num_layers = num_layers
            self.norm = norm
            self.return_intermediate = return_intermediate

        def forward(self, tgt, memory, tgt_mask=None, memory_mask=None, tgt_key_padding_mask=None,
                    memory_key_padding_mask=None, pos=None, query_pos=None):
            output = tgt

            intermediate = []

            for layer in self.layers:
                output = layer(output, memory, tgt_mask=tgt_mask, memory_mask=memory_mask, pos=pos, query_pos=query_pos,
                               tgt_key_padding_mask=tgt_key_padding_mask, memory_key_padding_mask=memory_key_padding_mask)

                if self.return_intermediate:
                    intermediate.append(self.norm(output))

            if self.norm is not None:
                output = self.norm(output)
                if self.return_intermediate:
                    intermediate.pop()
                    intermediate.append(output)

            if self.return_intermediate:
                return torch.stack(intermediate)

            return output.unsqueeze(0)


    class TransformerEncoderLayer(nn.Module):

        def __init__(self, d_model, nhead, dim_feedforward=2048, dropout=0.1, activation="relu", normalize_before=False):
            super().__init__()
            self.self_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout)
            # Implementation of Feedforward model
            self.linear1 = nn.Linear(d_model, dim_feedforward)
            self.dropout = nn.Dropout(dropout)
            self.linear2 = nn.Linear(dim_feedforward, d_model)

            self.norm1 = nn.LayerNorm(d_model)
            self.norm2 = nn.LayerNorm(d_model)
            self.dropout1 = nn.Dropout(dropout)
            self.dropout2 = nn.Dropout(dropout)

            self.activation = _get_activation_fn(activation)
            self.normalize_before = normalize_before

        def with_pos_embed(self, tensor, pos):
            return tensor if pos is None else tensor + pos

        def forward_post(self, src, src_mask=None, src_key_padding_mask=None, pos=None):
            q = k = self.with_pos_embed(src, pos)
            src2 = self.self_attn(q, k, value=src, attn_mask=src_mask, key_padding_mask=src_key_padding_mask)[0]
            src = src + self.dropout1(src2)
            src = self.norm1(src)
            src2 = self.linear2(self.dropout(self.activation(self.linear1(src))))
            src = src + self.dropout2(src2)
            src = self.norm2(src)
            return src

        def forward_pre(self, src, src_mask=None, src_key_padding_mask=None, pos=None):
            src2 = self.norm1(src)
            q = k = self.with_pos_embed(src2, pos)
            src2 = self.self_attn(q, k, value=src2, attn_mask=src_mask, key_padding_mask=src_key_padding_mask)[0]
            src = src + self.dropout1(src2)
            src2 = self.norm2(src)
            src2 = self.linear2(self.dropout(self.activation(self.linear1(src2))))
            src = src + self.dropout2(src2)
            return src

        def forward(self, src, src_mask=None, src_key_padding_mask=None, pos=None):
            if self.normalize_before:
                return self.forward_pre(src, src_mask, src_key_padding_mask, pos)
            return self.forward_post(src, src_mask, src_key_padding_mask, pos)


    class TransformerDecoderLayer(nn.Module):

        def __init__(self, d_model, nhead, dim_feedforward=2048, dropout=0.1,
                     activation="relu", normalize_before=False):
            super().__init__()
            self.self_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout)
            ###########################################################
            self.multihead_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout) # accuracy error happens using this!!!!!
            ###########################################################3
            # Implementation of Feedforward model
            self.linear1 = nn.Linear(d_model, dim_feedforward)
            # print(linear1.dtype)
            self.dropout = nn.Dropout(dropout)
            self.linear2 = nn.Linear(dim_feedforward, d_model)

            self.norm1 = nn.LayerNorm(d_model)
            self.norm2 = nn.LayerNorm(d_model)
            self.norm3 = nn.LayerNorm(d_model)
            self.dropout1 = nn.Dropout(dropout)
            self.dropout2 = nn.Dropout(dropout)
            self.dropout3 = nn.Dropout(dropout)

            self.activation = _get_activation_fn(activation)
            self.normalize_before = normalize_before

        def with_pos_embed(self, tensor, pos=None):
            return tensor if pos is None else tensor + pos

        def forward_post(self, tgt, memory, tgt_mask=None, memory_mask=None, tgt_key_padding_mask=None,
                         memory_key_padding_mask=None, pos=None, query_pos=None):
            q = k = self.with_pos_embed(tgt, query_pos)
            tgt2 = self.self_attn(q, k, value=tgt, attn_mask=tgt_mask,
                                  key_padding_mask=tgt_key_padding_mask)[0]
            tgt = tgt + self.dropout1(tgt2)
            tgt = self.norm1(tgt)
            tgt2 = self.multihead_attn(query=self.with_pos_embed(tgt, query_pos), key=self.with_pos_embed(memory, pos),
                                       value=memory, attn_mask=memory_mask, key_padding_mask=memory_key_padding_mask)[0]
            tgt = tgt + self.dropout2(tgt2)
            tgt = self.norm2(tgt)
            tgt2 = self.linear2(self.dropout(self.activation(self.linear1(tgt))))
            tgt = tgt + self.dropout3(tgt2)
            tgt = self.norm3(tgt)
            return tgt

        def forward_pre(self, tgt, memory, tgt_mask=None, memory_mask=None, tgt_key_padding_mask=None,
                        memory_key_padding_mask=None, pos=None, query_pos=None):
            tgt2 = self.norm1(tgt)
            q = k = self.with_pos_embed(tgt2, query_pos)
            tgt2 = self.self_attn(q, k, value=tgt2, attn_mask=tgt_mask,
                                  key_padding_mask=tgt_key_padding_mask)[0]
            tgt = tgt + self.dropout1(tgt2)
            tgt2 = self.norm2(tgt)
            tgt2 = self.multihead_attn(query=self.with_pos_embed(tgt2, query_pos), key=self.with_pos_embed(memory, pos),
                                       value=memory, attn_mask=memory_mask, key_padding_mask=memory_key_padding_mask)[0]
            tgt = tgt + self.dropout2(tgt2)
            tgt2 = self.norm3(tgt)
            tgt2 = self.linear2(self.dropout(self.activation(self.linear1(tgt2))))
            tgt = tgt + self.dropout3(tgt2)
            return tgt

        def forward(self, tgt, memory, tgt_mask=None, memory_mask=None, tgt_key_padding_mask=None,
                    memory_key_padding_mask=None, pos=None, query_pos=None):
            if self.normalize_before:
                return self.forward_pre(tgt, memory, tgt_mask, memory_mask,
                                        tgt_key_padding_mask, memory_key_padding_mask, pos, query_pos)
            return self.forward_post(tgt, memory, tgt_mask, memory_mask,
                                     tgt_key_padding_mask, memory_key_padding_mask, pos, query_pos)


    def _get_clones(module, N):
        return nn.ModuleList([copy.deepcopy(module) for i in range(N)])


    def build_transformer(args):
        return Transformer(
            d_model=args.hidden_dim,
            dropout=args.dropout,
            nhead=args.nheads,
            dim_feedforward=args.dim_feedforward,
            num_encoder_layers=args.enc_layers,
            num_decoder_layers=args.dec_layers,
            normalize_before=args.pre_norm,
            return_intermediate_dec=True,
        )


    def _get_activation_fn(activation):
        """Return an activation function given a string"""
        if activation == "relu":
            return F.relu
        if activation == "gelu":
            return F.gelu
        if activation == "glu":
            return F.glu
        raise RuntimeError(F"activation should be relu/gelu/glu, not {activation}.")`

I tried to provide as much info as possible, thank you or helping me so far, if you have any suggestions, or if you need any more info, please let me know!

**Comment by pranavm-nvidia** [comment]
How large is the error of these subgraphs? Also, how large is the error of the whole model?
I think this is a fundamentally hard problem since there isn't a straightforward way to determine what degree of error is tolerable in intermediate layers without materially affecting the final model outputs. Having said that, since you're running everything in FP32, I would've expected very low error in intermediate layers. Maybe setting a large threshold like `1e-3` will let you catch obvious functional issues without giving you false positives from accumulated rounding errors.

**Comment by ninono12345** [comment]
Hello @pranavm-nvidia, thank you for your answer. I am using polygraphy for engine inference and I fixed the accuracy issue by making all input tensors to("cpu"). I don't know if this is supposed to happen like this, but now the accuracy is just fine, so it seems that the problem is fixed...

Now I have my last problem https://github.com/NVIDIA/TensorRT/issues/3623 perhaps you have a better understanding at what is the problem there?
