### ISSUE TITLE
Windows support for TensorRT OSS

### ISSUE THREAD

**Issue by dflamand** [NVIDIA/TensorRT#36]
After some cmake tweaks I was able to make some progress building this library on windows. But I ran into a linking error where the external symbols for "find_divisor" and "nmsInference" are unable to be resolved. I ran dumpbin on nvinfer.lib/dll and I do not see those symbols being exported; however, with nm on linux I am able to see those symbols in libnvinfer.so.

Is there a way to get around this problem and successfully build on windows? I only require building the plugins, nothing else.

I have attached a patch of the tweaks I made, and the cmake commands I used are:
`cmake .. -DTRT_LIB_DIR=D:/tmp/TensorRT-5.1.5.0/lib -DTRT_BIN_DIR=D:/tmp/TensorRT/build/out -DCUB_ROOT_DIR=D:/tmp/cub-1.8.0/ -DBUILD_SAMPLES=OFF -DBUILD_PARSERS=OFF -DCUDA_TOOLKIT_ROOT_DIR='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1' -DCMAKE_CUDA_COMPILER='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe' -G 'Visual Studio 15 2017 Win64' -DCUDA_NVCC_FLAGS='nvcc;--std;c++11'`
`cmake --build . --config Release`

[TensorRT-OSS-Win.patch.txt](https://github.com/NVIDIA/TensorRT/files/3399543/TensorRT-OSS-Win.patch.txt)

**Comment by rajeevsrao** [comment]
Windows builds not yet supported for OSS release. We are treating this as an RFE.

**Comment by guods** [comment]
@rajeevsrao Can Uff files generated on Ubuntu be used in Windows?

**Comment by rajeevsrao** [comment]
> @rajeevsrao Can Uff files generated on Ubuntu be used in Windows?

Yes, UFF models are portable across OS.

**Comment by rajeevsrao** [comment]
@dflamand can you pleae check if the newly added Windows [makefile ](https://github.com/NVIDIA/TensorRT/blob/master/cmake/toolchains/cmake_x64_win.toolchain) and [instructions](https://github.com/NVIDIA/TensorRT#building-the-tensorrt-oss-components)  work for you? Will close the issue, but feel free to reopen if you face issues.
