### ISSUE TITLE
bug found in TensorRT when doing int8 calibration with polygraphy

### ISSUE THREAD

**Issue by ninono12345** [NVIDIA/TensorRT#3603]
## Description

When I execute this code:

`polygraphy convert latest4_sanitized.onnx -o latest4_sanitized.engine --int8 --data-loader-script data_loader.py`

data_loader.py:

`def load_data():

    for i in range(len(calset)):
        # TIP: If your calibration data is already on the GPU, you can instead provide GPU pointers
        # (as `int`s) or Polygraphy `DeviceView`s instead of NumPy arrays.
        #
        # For details on `DeviceView`, see `polygraphy/cuda/cuda.py`.
        yield {"sample_x": calset[i][0],
                "train_samples": calset[i][1],  # Totally real data
                "target_labels": calset[i][2],  # Totally real data
                "train_ltrb": calset[i][3]}  # Totally real data`

I get this error:

[E] 1: Unexpected exception invalid unordered_map<K, T> key
[!] Invalid Engine. Please ensure the engine was built correctly

the full output:

[W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[W] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[W] Input tensor: sample_x (dtype=DataType.FLOAT, shape=(-1, 1024, 18, 18)) | No shapes provided; Will use shape: [1, 1024, 18, 18] for min/opt/max in profile.
[W] This will cause the tensor to have a static shape. If this is incorrect, please set the range of shapes for this input tensor.
[W] Input tensor: train_samples (dtype=DataType.FLOAT, shape=(-1, 1024, 18, 18)) | No shapes provided; Will use shape: [1, 1024, 18, 18] for min/opt/max in profile.
[W] Input tensor: target_labels (dtype=DataType.FLOAT, shape=(-1, 1, 18, 18)) | No shapes provided; Will use shape: [1, 1, 18, 18] for min/opt/max in profile.
[W] Input tensor: train_ltrb (dtype=DataType.FLOAT, shape=(-1, 4, 18, 18)) | No shapes provided; Will use shape: [1, 4, 18, 18] for min/opt/max in profile.
[I] Configuring with profiles:[
        Profile 0:
            {sample_x [min=[1, 1024, 18, 18], opt=[1, 1024, 18, 18], max=[1, 1024, 18, 18]],
             train_samples [min=[1, 1024, 18, 18], opt=[1, 1024, 18, 18], max=[1, 1024, 18, 18]],
             target_labels [min=[1, 1, 18, 18], opt=[1, 1, 18, 18], max=[1, 1, 18, 18]],
             train_ltrb [min=[1, 4, 18, 18], opt=[1, 4, 18, 18], max=[1, 4, 18, 18]]}
    ]
[I] Using calibration profile: {sample_x [min=[1, 1024, 18, 18], opt=[1, 1024, 18, 18], max=[1, 1024, 18, 18]],
     train_samples [min=[1, 1024, 18, 18], opt=[1, 1024, 18, 18], max=[1, 1024, 18, 18]],
     target_labels [min=[1, 1, 18, 18], opt=[1, 1, 18, 18], max=[1, 1, 18, 18]],
     train_ltrb [min=[1, 4, 18, 18], opt=[1, 4, 18, 18], max=[1, 4, 18, 18]]}
[I] Building engine with configuration:
    Flags                  | [INT8]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 6143.69 MiB, TACTIC_DRAM: 6143.69 MiB]
    Tactic Sources         | [CUBLAS, CUBLAS_LT, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
    Calibrator             | Calibrator(<generator object load_data at 0x0000025B5E682CE0>, BaseClass=<class 'tensorrt.tensorrt.IInt8EntropyCalibrator2'>)
[W] BuilderFlag::kENABLE_TACTIC_HEURISTIC has been ignored in this builder run. This feature is only supported on Ampere and beyond.
[E] 1: Unexpected exception invalid unordered_map<K, T> key
[!] Invalid Engine. Please ensure the engine was built correctly

link to onnx model (constalnts folded with polygraphy surgeon sanitize): https://drive.google.com/file/d/1y1fH_R-ZKuUzN3MhSTY4FwgGUkdFGx54/view?usp=sharing

If any more info is needed please ask

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: GTX 1660 Ti

**NVIDIA Driver Version**: 546.01

**CUDA Version**: 12.1 update 1

**CUDNN Version**: 8.9.7

Operating System: Winodws 10

Python Version (if applicable): 3.10.13

PyTorch Version (if applicable): 2.1.2+cu121

Baremetal or Container (if so, version): No environment, run on windows 10

**Comment by zerollzeng** [comment]
Could you please try TRT 9.2 on Linux(we don't support Windows for TRT 9 now)? I can convert the engine successfully with `polygraphy convert latest4_sanitized.onnx -o /tmp/model.plan --int8`. Looks like a fix issue.

You can download it from
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.ubuntu-22.04.aarch64-gnu.cuda-12.2.tar.gz

**Comment by ninono12345** [comment]
@zerollzeng thank you for your reply. Is there an option to run this from a docker: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

**Comment by zerollzeng** [comment]
You can install it to docker manually, we didn't release this in TensorRT docker.
