### ISSUE TITLE
setAllowedFormats does not work for inner  layers in TensorRT 8.6 when running on GPU T4

### ISSUE THREAD

**Issue by daaguirre** [NVIDIA/TensorRT#3604]
## Description
Hi,

I'm trying to reduce the engine building time of a transformer-based network in FP16 by using setPrecision method and by setting the flag kOBEY_PRECISION_CONSTRAINTS. This is to prevent tensorrt from profiling float and half tactics and only profile one (float or half). Then, I noticed that most of the engine build time is spent profiling Myelin nodes. And for each myelin node, 3 format combinations are profiled:
1) Float(...) -> Float(...)
2) Half(...) -> Half(...)
3) Half(...(kHWC8)) -> Float(...) or Half(...(kHWC8)) -> Half(....(kHWC8)) 

For example for node {ForeignNode[/layers.3/blocks.1/Reshape_1 + /layers.3/blocks.1/Transpose_1...(Unnamed Layer* 1183) [ElementWise]]} in attached model the following formats are profiled:
1) Float(15680,49,7,1) -> Float(1000,1)
2) Half(15680,49,7,1) -> Half(1000,1)
3) Half(1960,1:8,280,40) -> Float(1000,1) 

For the moment, I have been successful disabling the first format by setting to FP16 some attention layers using setPrecision and now I would like to disable second format so that Tensorrt only profiles the third one which is the one selected in the final engine.

is there some way to set the allowed IO formats for myelin nodes?
I have tried the following with no success:
```
                    // cur_layer is /layers.3/blocks.1/Transpose_1
                    cur_layer->setPrecision(nvinfer1::DataType::kHALF);
                    const int num_inputs = cur_layer->getNbInputs();
                    for (int i = 0; i < num_inputs ; i++) {
                         cur_layer->getInput(i)->setAllowedFormats(1 << static_cast<int>(nvinfer1::TensorFormat::kHWC8));
                    }
```

```
                    //cur_layer is (Unnamed Layer* 1183) [ElementWise]
                    cur_layer->setPrecision(nvinfer1::DataType::kHALF);
                    const int num_outputs = cur_layer->getNbOutputs();
                    for (int i = 0; i < num_outputs; i++) {
                        cur_layer->setOutputType(i, nvinfer1::DataType::kFLOAT);
                        cur_layer->getOutput(i)->setType(nvinfer1::DataType::kFLOAT);
                    }
```

In above code, I'm trying to set the input of the myelin node to only allow TensorFormat::kHWC8 and the output to be float so that during engine building only third option is run.

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: T4

**NVIDIA Driver Version**: 525

**CUDA Version**: 11.7

**CUDNN Version**: 8

Operating System: ubuntu 20

## Relevant Files

**Model link**:
https://drive.google.com/file/d/1G8rtZbh9AFshhflmbqzX8xvhHZEzAdtf/view?usp=sharing

**Comment by zerollzeng** [comment]
So the main purpose is to reduce build time, I think we have some optimization on this in TRT 9.2, could you please take a try?

You can download it from 
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.ubuntu-22.04.aarch64-gnu.cuda-12.2.tar.gz


About the precision/format setting, @zhenhuaw-me do you have any comments? Thanks!

**Comment by zhenhuaw-me** [comment]
- `setAllowedFormats()` only works for network IO tensors.
- Setup tensor dtype and node precision is sufficient to control how TensorRT does the math, but not necessarily accelerate engine building.
- You may try [`nvinfer1::IBuilderConfig::setBuilderOptimizationLevel()`](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#af51d2c96a3dcc98c345141ff93562e42) to speed up your engine building. To be noted, the engine inference time may increase.

**Comment by daaguirre** [comment]
I have tried out the 9.2 version and indeed the engine building time for transformer-based models has been improved significantly and now it is usable from my side. Thank you!
One more thing, is this 9.2 version a beta or early access version? because that version does not appear [here](https://developer.nvidia.com/tensorrt-download). If so, when this version will be "official"?

**Comment by zhenhuaw-me** [comment]
@daaguirre I am Glad to hear that!

9.2 is for LLM, and is not full platform support. We are in the process of preparing the 10.0 release.

Closing this as the issue has been resolved.

**Comment by daaguirre** [comment]
> @daaguirre I am Glad to hear that!
> 
> 9.2 is for LLM, and is not full platform support. We are in the process of preparing the 10.0 release.
> 
> Closing this as the issue has been resolved.

What do you mean by "is not full platform support"? not all GPUs are supported? are there any details about what GPUs are not supported?

**Comment by zhenhuaw-me** [comment]
It's only tested on Ampere+. You should be able to run on the same GPU matrix as 8.6. If any bug, please report back.

**Comment by Feynman1999** [comment]
> @daaguirre I am Glad to hear that!
> 
> 9.2 is for LLM, and is not full platform support. We are in the process of preparing the 10.0 release.
> 
> Closing this as the issue has been resolved.

Looking forward to version 10.0. Can we see it in Q1 2024？
