### ISSUE TITLE
enqueueV3 failure of TensorRT 8.6.1.6 when running model.onnx on GPU A30

### ISSUE THREAD

**Issue by lizexu123** [NVIDIA/TensorRT#3605]
## Environment

**TensorRT Version**:
TensorRT-8.6.1.6
**NVIDIA GPU**:
A30
**NVIDIA Driver Version**:

**CUDA Version**:

**CUDNN Version**:

Operating System:
centos-release-7-9.2009.1.el7.centos.x86_64
Python Version (if applicable):
python3.8
Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files
```ruby
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
import logging
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np

logger = trt.Logger(trt.Logger.WARNING)
builder = trt.Builder(logger)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, logger)

model_path = "./PPHumanMatting.onnx"
precision = "fp16"

success = parser.parse_from_file(model_path)
config = builder.create_builder_config()
if precision == "fp16":
   config.set_flag(trt.BuilderFlag.FP16)
elif precision == "bf16":
    config.set_flag(trt.BuilderFlag.BF16)

config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 35)
profile = builder.create_optimization_profile()


input_shape = [1, 3, 1024, 1024]
input1_shape=[2]
input_value=[512,512]

profile.set_shape("img", input_shape, input_shape, input_shape)
profile.set_shape("cast_3.tmp_0",input1_shape,input1_shape,input1_shape)
profile.set_shape_input("cast_3.tmp_0",input_value,input_value,input_value)
profile.set_shape("cast_4.tmp_0",input1_shape,input1_shape,input1_shape)
profile.set_shape_input("cast_4.tmp_0",input_value,input_value,input_value)

config.add_optimization_profile(profile)
config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED

engine_file_path = "engine_file_path_" + precision
if os.path.exists(engine_file_path):
    with open(engine_file_path, "rb") as f, trt.Runtime(logger) as runtime:
        engine = runtime.deserialize_cuda_engine(f.read())
else:
    serialized_engine = builder.build_serialized_network(network, config)
    runtime = trt.Runtime(logger)
    engine = runtime.deserialize_cuda_engine(serialized_engine)
    print("save engine for later use.")
    with open(engine_file_path, "wb") as f:
        f.write(engine.serialize())

# logging.debug("create execution context")
context = engine.create_execution_context()
# tensor_names = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)]
# for tensor in tensor_names:

context.set_input_shape("img",input_shape)
context.set_input_shape("cast_3.tmp_0",input1_shape)
context.set_input_shape("cast_4.tmp_0",input1_shape)

h_input0 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("img")),dtype=np.float32)
h_input0 = np.zeros(h_input0.shape).astype(np.float32)
h_input1 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("cast_3.tmp_0")),dtype=np.int32)
h_input1 = np.zeros(h_input1.shape).astype(np.int32)
h_input2 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("cast_4.tmp_0")),dtype=np.int32)
h_input2 = np.zeros(h_input2.shape).astype(np.int32)
h_output =cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("save_infer_model/scale_0.tmp_0")),dtype=np.float32)


d_input0 = cuda.mem_alloc(h_input0.nbytes)
d_input1 = cuda.mem_alloc(h_input1.nbytes)
d_input2 = cuda.mem_alloc(h_input2.nbytes)
d_output = cuda.mem_alloc(h_output.nbytes)
context.set_tensor_address("img",int(d_input0))
context.set_tensor_address("cast_3.tmp_0",int(d_input1))
context.set_tensor_address("cast_4.tmp_0",int(d_input2))
context.set_tensor_address("save_infer_model/scale_0.tmp_0",int(d_output))

stream = cuda.Stream()
for i in range(10):
    cuda.memcpy_htod_async(d_input0, h_input0, stream)
    cuda.memcpy_htod_async(d_input1,h_input1,stream)
    cuda.memcpy_htod_async(d_input2,h_input2,stream)
    context.execute_async_v3(stream_handle=stream.handle)
    cuda.memcpy_dtoh_async(h_output, d_output, stream)
stream.synchronize()


import datetime
import time

stream.synchronize()
starttime = datetime.datetime.now()

for i in range(10):
    cuda.memcpy_htod_async(d_input0, h_input0, stream)
    cuda.memcpy_htod_async(d_input1,h_input1,stream)
    cuda.memcpy_htod_async(d_input2,h_input2,stream)
    context.execute_async_v3(stream_handle=stream.handle)
    cuda.memcpy_dtoh_async(h_output, d_output, stream)

stream.synchronize()
endtime = datetime.datetime.now()
duringtime = endtime - starttime
print (duringtime.seconds * 1000 + duringtime.microseconds / 1000.0)# 单位是毫

print(np.std(h_output), np.mean(h_output))
```
```ruby
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
import logging
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np

logger = trt.Logger(trt.Logger.WARNING)
builder = trt.Builder(logger)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, logger)

model_path = "./PPHumanMatting.onnx"
precision = "fp16"

success = parser.parse_from_file(model_path)
config = builder.create_builder_config()
if precision == "fp16":
   config.set_flag(trt.BuilderFlag.FP16)
elif precision == "bf16":
    config.set_flag(trt.BuilderFlag.BF16)

config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 35)
profile = builder.create_optimization_profile()


input_shape = [1, 3, 1024, 1024]
input1_shape=[2]
input_value=[512,512]

profile.set_shape("img", input_shape, input_shape, input_shape)
profile.set_shape("cast_3.tmp_0",input1_shape,input1_shape,input1_shape)
profile.set_shape_input("cast_3.tmp_0",input_value,input_value,input_value)
profile.set_shape("cast_4.tmp_0",input1_shape,input1_shape,input1_shape)
profile.set_shape_input("cast_4.tmp_0",input_value,input_value,input_value)

config.add_optimization_profile(profile)
config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED

engine_file_path = "engine_file_path_" + precision
if os.path.exists(engine_file_path):
    with open(engine_file_path, "rb") as f, trt.Runtime(logger) as runtime:
        engine = runtime.deserialize_cuda_engine(f.read())
else:
    serialized_engine = builder.build_serialized_network(network, config)
    runtime = trt.Runtime(logger)
    engine = runtime.deserialize_cuda_engine(serialized_engine)
    print("save engine for later use.")
    with open(engine_file_path, "wb") as f:
        f.write(engine.serialize())


context = engine.create_execution_context()

context.set_input_shape("img",input_shape)
context.set_input_shape("cast_3.tmp_0",input1_shape)
context.set_input_shape("cast_4.tmp_0",input1_shape)

context.set_binding_shape(0, input_shape)
context.set_binding_shape(1,input1_shape)
context.set_binding_shape(2,input1_shape)


h_input0 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("img")),dtype=np.float32)
h_input0 = np.zeros(h_input0.shape).astype(np.float32)
h_input1 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("cast_3.tmp_0")),dtype=np.int32)
h_input1 = np.zeros(h_input1.shape).astype(np.int32)
h_input2 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("cast_4.tmp_0")),dtype=np.int32)
h_input2 = np.zeros(h_input2.shape).astype(np.int32)
h_output =cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("save_infer_model/scale_0.tmp_0")),dtype=np.float32)


d_input0 = cuda.mem_alloc(h_input0.nbytes)
d_input1 = cuda.mem_alloc(h_input1.nbytes)
d_input2 = cuda.mem_alloc(h_input2.nbytes)
d_output = cuda.mem_alloc(h_output.nbytes)
# context.set_tensor_address("img",int(d_input0))
# context.set_tensor_address("cast_3.tmp_0",int(d_input1))
# context.set_tensor_address("cast_4.tmp_0",int(d_input2))
# context.set_tensor_address("save_infer_model/scale_0.tmp_0",int(d_output))

stream = cuda.Stream()
for i in range(10):
    cuda.memcpy_htod_async(d_input0, h_input0, stream)
    cuda.memcpy_htod_async(d_input1,h_input1,stream)
    cuda.memcpy_htod_async(d_input2,h_input2,stream)
    context.execute_async_v2(bindings=[int(d_input0),int(d_input1),int(d_input2),int(d_output)],stream_handle=stream.handle)
    # context.execute_async_v3(stream_handle=stream.handle)
    cuda.memcpy_dtoh_async(h_output, d_output, stream)
stream.synchronize()


import datetime
import time

stream.synchronize()
starttime = datetime.datetime.now()

for i in range(10):
    cuda.memcpy_htod_async(d_input0, h_input0, stream)
    cuda.memcpy_htod_async(d_input1,h_input1,stream)
    cuda.memcpy_htod_async(d_input2,h_input2,stream)
    context.execute_async_v2(bindings=[int(d_input0),int(d_input1),int(d_input2),int(d_output)],stream_handle=stream.handle)
    cuda.memcpy_dtoh_async(h_output, d_output, stream)

stream.synchronize()
endtime = datetime.datetime.now()
duringtime = endtime - starttime
print (duringtime.seconds * 1000 + duringtime.microseconds / 1000.0)# 单位是毫

print(np.std(h_output), np.mean(h_output))
```

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by lizexu123** [comment]
> ## Description
> ## Environment
> **TensorRT Version**: TensorRT-8.6.1.6 **NVIDIA GPU**: A30 **NVIDIA Driver Version**:
> 
> **CUDA Version**:
> 
> **CUDNN Version**:
> 
> Operating System: centos-release-7-9.2009.1.el7.centos.x86_64 Python Version (if applicable): python3.8 Tensorflow Version (if applicable):
> 
> PyTorch Version (if applicable):
> 
> Baremetal or Container (if so, version):
> 
> ## Relevant Files
> `import os os.environ["CUDA_VISIBLE_DEVICES"] = "1" import logging import tensorrt as trt import pycuda.driver as cuda import pycuda.autoinit import numpy as np
> 
> logger = trt.Logger(trt.Logger.WARNING) builder = trt.Builder(logger) network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)) parser = trt.OnnxParser(network, logger)
> 
> model_path = "./PPHumanMatting.onnx" precision = "fp16"
> 
> success = parser.parse_from_file(model_path) config = builder.create_builder_config() if precision == "fp16": config.set_flag(trt.BuilderFlag.FP16) elif precision == "bf16": config.set_flag(trt.BuilderFlag.BF16)
> 
> config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 35) profile = builder.create_optimization_profile()
> 
> input_shape = [1, 3, 1024, 1024] input1_shape=[2] input_value=[512,512]
> 
> profile.set_shape("img", input_shape, input_shape, input_shape) profile.set_shape("cast_3.tmp_0",input1_shape,input1_shape,input1_shape) profile.set_shape_input("cast_3.tmp_0",input_value,input_value,input_value) profile.set_shape("cast_4.tmp_0",input1_shape,input1_shape,input1_shape) profile.set_shape_input("cast_4.tmp_0",input_value,input_value,input_value)
> 
> config.add_optimization_profile(profile) config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED
> 
> engine_file_path = "engine_file_path_" + precision if os.path.exists(engine_file_path): with open(engine_file_path, "rb") as f, trt.Runtime(logger) as runtime: engine = runtime.deserialize_cuda_engine(f.read()) else: serialized_engine = builder.build_serialized_network(network, config) runtime = trt.Runtime(logger) engine = runtime.deserialize_cuda_engine(serialized_engine) print("save engine for later use.") with open(engine_file_path, "wb") as f: f.write(engine.serialize())
> 
> # logging.debug("create execution context")
> context = engine.create_execution_context()
> 
> # tensor_names = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)]
> # for tensor in tensor_names:
> # print("tensor的名字",tensor)
> # dtype=trt.nptype(engine.get_tensor_dtype(tensor))
> # print("tensor的dtype",dtype)
> # if engine.get_tensor_mode(tensor)==trt.TensorIOMode.INPUT:
> # if engine.is_shape_inference_io(tensor):
> # context.set_input_shape(tensor,)
> context.set_input_shape("img",input_shape) context.set_input_shape("cast_3.tmp_0",input1_shape) context.set_input_shape("cast_4.tmp_0",input1_shape)
> 
> # context.set_binding_shape(0, input_shape)
> # context.set_binding_shape(1,input1_shape)
> # context.set_binding_shape(2,input1_shape)
> h_input0 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("img")),dtype=np.float32) h_input0 = np.zeros(h_input0.shape).astype(np.float32) h_input1 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("cast_3.tmp_0")),dtype=np.int32) h_input1 = np.zeros(h_input1.shape).astype(np.int32) h_input2 = cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("cast_4.tmp_0")),dtype=np.int32) h_input2 = np.zeros(h_input2.shape).astype(np.int32) h_output =cuda.pagelocked_empty(trt.volume(engine.get_tensor_shape("save_infer_model/scale_0.tmp_0")),dtype=np.float32)
> 
> d_input0 = cuda.mem_alloc(h_input0.nbytes) d_input1 = cuda.mem_alloc(h_input1.nbytes) d_input2 = cuda.mem_alloc(h_input2.nbytes) d_output = cuda.mem_alloc(h_output.nbytes) context.set_tensor_address("img",int(d_input0)) context.set_tensor_address("cast_3.tmp_0",int(d_input1)) context.set_tensor_address("cast_4.tmp_0",int(d_input2)) context.set_tensor_address("save_infer_model/scale_0.tmp_0",int(d_output))
> 
> stream = cuda.Stream() for i in range(10): cuda.memcpy_htod_async(d_input0, h_input0, stream) cuda.memcpy_htod_async(d_input1,h_input1,stream) cuda.memcpy_htod_async(d_input2,h_input2,stream) context.execute_async_v3(stream_handle=stream.handle) cuda.memcpy_dtoh_async(h_output, d_output, stream) stream.synchronize()
> 
> import datetime import time
> 
> stream.synchronize() starttime = datetime.datetime.now()
> 
> for i in range(10): cuda.memcpy_htod_async(d_input0, h_input0, stream) cuda.memcpy_htod_async(d_input1,h_input1,stream) cuda.memcpy_htod_async(d_input2,h_input2,stream) context.execute_async_v3(stream_handle=stream.handle) cuda.memcpy_dtoh_async(h_output, d_output, stream)
> 
> stream.synchronize() endtime = datetime.datetime.now() duringtime = endtime - starttime print (duringtime.seconds * 1000 + duringtime.microseconds / 1000.0)# 单位是毫
> 
> print(np.std(h_output), np.mean(h_output)) `
> 
> **Model link**:
> 
> ## Steps To Reproduce
> **Commands or scripts**:
> 
> **Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:
> 
> **Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by leo0519** [comment]
The segmentation fault is due to wrong API usage.
Shape tensors should be on CPU memory, not GPU memory.

**Comment by zerollzeng** [comment]
What error did you see? does it work with `trtexec --loadEngine=model.plan`? I suspect it's a usage issue.

**Comment by leo0519** [comment]
Hi @zerollzeng, this issue is due to wrong API usage. The reporter will close this issue sooner.

**Comment by lizexu12** [comment]
ok，thank you，done

**Comment by zerollzeng** [comment]
Good to known， I‘m closing this.

**Comment by OswaldoBornemann** [comment]
@leo0519 Why shape tensors should be on CPU memory, not GPU memory ?

**Comment by leo0519** [comment]
@OswaldoBornemann It's TensorRT's setting.
FYI, the value of the shape tensor influences the configuration of grid and block sizes when launching a GPU kernel. It’s generally more efficient to calculate the shape tensor in host memory before launching the kernel.
