### ISSUE TITLE
is an RPM for TensorRT for RedHat 9 not available?

### ISSUE THREAD

**Issue by gmabey** [NVIDIA/TensorRT#3613]
I'm just trying to install TensorRT from https://developer.nvidia.com/tensorrt-download but I don't see an .rpm package for RedHat 9, whereas CUDA, cuDNN, and (it seems) all other NVIDIA libraries support RedHat 9.
Additionally, I don't see any TensorRT 9.x releases included there.
I see that this is the OSS version, but am I missing something (big) or is the nvidia webpage actually not up-to-date?

**Comment by zerollzeng** [comment]
TRT 9 is a limited release so we didn't public in dev zone, and there is only tar package for used.

Check
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.ubuntu-22.04.aarch64-gnu.cuda-12.2.tar.gz

**Comment by gmabey** [comment]
Ok, that's fair -- it's not GA.
What about the 8.6 release for RedHat 9?

**Comment by zerollzeng** [comment]
![image](https://github.com/NVIDIA/TensorRT/assets/38289304/c90466d0-161c-4bfa-acf2-427660ff3f14)
Looks like we haven't support it yet, but it should be supported in the future. How about just use the Linux x86_64 tar package?

**Comment by gmabey** [comment]
The RedHat 8 rpm "works" on RedHat 9 but there's a big difference between "works" and "supported", especially as I'm trying to justify to my management the value in basing our new product on RedHat 9, which will make other aspects of the product a lot easier, and implies a longer run before hitting EOL.
So, I'm "squeaking".

**Comment by zerollzeng** [comment]
Checking internally.

**Comment by zeroepoch** [comment]
@gmabey, The next major release of TensorRT will support RedHat 9 and have RPMs specifically for RHEL 9. It's just not supported officially yet for TRT 8.x and 9.x.

**Comment by zeroepoch** [comment]
> Ok, that's great news. Any forecast for when the next _major_ release of TensorRT will be? And -- would that be 9.3.0 or is that a "minor" release?

The next major release in this regard will be 10.0 and will be available roughly March/April time frame.
