### ISSUE TITLE
TensorRT 8.5 deprecated functions

### ISSUE THREAD

**Issue by lioriz1** [NVIDIA/TensorRT#3621]
I updated my TensorRT version to 8.5 and got warnings about deprecated functions, opened question on NVIDIA developer forums [tensorrt-8-5-depecated-functions](https://forums.developer.nvidia.com/t/tensorrt-8-5-depecated-functions/278907).

I used [void nvinfer1::IRuntime::destroy()](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-801/api/c_api/classnvinfer1_1_1_i_runtime.html#ab07e802f58331e0c7e215e58422bd936) and it `Deprecated interface will be removed in TensorRT 10.0.`
 Is this function not needed and can I remove it from my code?

Code:
```
IRuntime *runtime = createInferRuntime(gLogger);
ICudaEngine *engine = runtime->deserializeCudaEngine(trtModelStream_.data(), trtModelStream_.size(), nullptr);
runtime->destroy();
```
Should convert to:
```
IRuntime *runtime = createInferRuntime(gLogger);
ICudaEngine *engine = runtime->deserializeCudaEngine(trtModelStream_.data(), trtModelStream_.size());
```
Just remove `runtime->destroy();`?

**Comment by zerollzeng** [comment]
> Deprecated interface will be removed in TensorRT 10.0.

it means if you compile the code with TRT 10.0, you will get compile error.
