### ISSUE TITLE
how to download dataset from https://yann.lecun.com/exdb/mnist/?

### ISSUE THREAD

**Issue by Daniel-ChenJH** [NVIDIA/TensorRT#3626]
I met an error downloading the dataset provided by https://yann.lecun.com/exdb/mnist/, it looks like a username and a password is acquired. How can I download the dataset, or, what's the username and password for the webside?

**Comment by zerollzeng** [comment]
Not related to TRT so I'm closing this.

Just register an account to google the mnist dataset?
