### ISSUE TITLE
Running flash attention on Orin NX failed

### ISSUE THREAD

**Issue by miraiaroha** [NVIDIA/TensorRT#3643]
## Description
1. I want to deploy VIT-like model on Orin NX 16G, with flash attention instead of standard attention to increase the inference speed.
2. I try to use the multiHeadFlashAttentionPlugin in Tensorrt-8.5, but found that it doesn't supply SM87!
3. Do the tensorrt-8.6 or the later vesions supply flash attention on Orin NX 16G? or is there any other methods work？

## Environment

Orin NX 16G
TensorRT Version: 8.5.2
NVIDIA Driver Version:
CUBIN: SM87
CUDA Version: 11.4
Operating System: Ubuntu 20.04

**Comment by zerollzeng** [comment]
@nvpohanh Do you know about this? Thanks!

**Comment by nvpohanh** [comment]
Orin fused MHA kernels were added in TensorRT 8.6.11/12, I think. TRT 8.6.1 does not have it.

**Comment by miraiaroha** [comment]
oh! i found a docker (dustynv/l4t-pytorch:r36.2.0) with TRT 8.6.2 in NVIDIA forum can satisfy my need, and successfully built a model engine with flash attentions.
