### ISSUE TITLE
pytorch-quantization2.2.1 version update problem

### ISSUE THREAD

**Issue by xpww** [NVIDIA/TensorRT#3651]
## Description

Currently at https://pypi.org/project/pytorch-quantization/, the latest version of pytorch-quantization is 2.2.1, so use the command pip install --no-cache-dir --extra-index-url in the warehouse https://pypi.nvidia.com pytorch-quantization to install it, pointing to version 2.2.1, and an error will occur during the installation.

However, when building from source code in the github repository, the installed version is actually version 2.1.3, so use pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization== 2.1.3 or source code construction: python setup.py install can be successful.

Is it because pytorch-quantization has actually been updated to version 2.2.1, but the corresponding https://github.com/NVIDIA/TensorRT/tree/master/tools/pytorch-quantization warehouse still contains the old files of version 2.1.3? What caused the error when installing the latest version of pytorch-quantization?::

pip install pytorch-quantization==2.2.1

Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting pytorch-quantization==2.2.1
  Using cached pytorch-quantization-2.2.1.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dsb92h3c/pytorch-quantization_4534ffe9c59042b88b92b666b3c09114/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

## Environment

ubuntu2004

NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3

## Relevant Files

pytorch-quantization-2.2.1.tar.gz from https://pypi.org/project/pytorch-quantization/

## Steps To Reproduce

**Commands or scripts**:pip install pytorch-quantization==2.2.1

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:yes

**Comment by zerollzeng** [comment]
Could you please try `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization`?

**Comment by xpww** [comment]
> Could you please try `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization`?

This command runs correctly and installs version 2.1.3 of pytorch-quantization. I now suspect that version 2.2.1 of pytorch-quantization in https://pypi.org/project/pytorch-quantization does not actually exist

**Comment by zerollzeng** [comment]
`pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization==2.2.1` works for me

**Comment by xpww** [comment]
> `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization==2.2.1` works for me

I successfully changed the virtual environment again. It seems that this is related to environment conflict. Thanks!

**Comment by zerollzeng** [comment]
NP, close this.

**Comment by Raj-vivid** [comment]
> pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization==2.2.1

Facing the same issue. I tried this but it still does not work.

**Comment by xpww** [comment]
> > pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization==2.2.1
> 
> Facing the same issue. I tried this but it still does not work.

It seems that pip can only install 2.1.3 correctly. If you want to use the latest (2.2.1), git clone the latest tensorrt repository and compile and install it locally.

**Comment by Raj-vivid** [comment]
> > > pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization==2.2.1
> > 
> > 
> > Facing the same issue. I tried this but it still does not work.
> 
> It seems that pip can only install 2.1.3 correctly. If you want to use the latest (2.2.1), git clone the latest tensorrt repository and compile and install it locally.

Yup can attest, got it (2.2.1) to work after compiling and installing locally.
