### ISSUE TITLE
How to implement a tensorrt plugin for "Unique" op?

### ISSUE THREAD

**Issue by BobLiu20** [NVIDIA/TensorRT#3655]
I want to implement a plug-in for the operator Unique. But I don’t know how to determine its output dimension, because it cannot be determined directly based on the input (must be determined after calculation? )

```
nvinfer1::DataType UniquePlugin::getOutputDataType(int index, const nvinfer1::DataType* inputTypes, int nbInputs) const
    noexcept
{
    ?????????????
}
```

Numpy "Unuqie": https://numpy.org/doc/stable/reference/generated/numpy.unique.html

Any idea to implement it?

**Comment by zerollzeng** [comment]
Currently we don't support data dependent plugin. @samurdhikaru for viz.

**Comment by ttyio** [comment]
closing as duplicate with https://github.com/NVIDIA/TensorRT/issues/3521, we need DDS plugin support.
