### ISSUE TITLE
System throttled due to over-current warning using TensorRT 8.5 when running infer.py from detectron samples in the repo on Jetson Orin NX

### ISSUE THREAD

**Issue by Nil69420** [NVIDIA/TensorRT#3663]
Running infer.py from https://github.com/NVIDIA/TensorRT/tree/release/8.6/samples/python/detectron2 on my custom dataset. Inference is being done correctly. However getting system throttled due to over current. This doesn't happen when running other tensorrt samples. Please help.

**Comment by RajUpadhyay** [comment]
I dont think that It affects your performance though, Detectron2 is quite heavy so the system throttles.
Also if you try int8, maybe, emphasis on **maybe**, you may not get that system throttle notification.

**Comment by zerollzeng** [comment]
Yes, more like a loading issue. NX doesn't have much source.
