### ISSUE TITLE
Follow up on Issue#3319

### ISSUE THREAD

**Issue by rishucoding** [NVIDIA/TensorRT#3664]
Hi, 

I would like to follow-up on the previous issue: [#3319](https://github.com/NVIDIA/TensorRT/issues/3319).

Could you share the source code for TRT implementation of Gather Kernel used in Embedding Stage for DLRMs? Also, could you point the main differences between the TRT gather kernel and the [Vanilla PyTorch Embedding Stage CUDA kernel](https://github.com/pytorch/pytorch/blob/7315ec7505401476c80a2a7fb34046f1f22682f2/aten/src/ATen/native/cuda/EmbeddingBag.cu#L145C18-L145C29) ([link](https://github.com/pytorch/pytorch/blob/7315ec7505401476c80a2a7fb34046f1f22682f2/aten/src/ATen/native/cuda/EmbeddingBag.cu#L145C18-L145C29))

Thanks,
Rishabh Jain

**Comment by zerollzeng** [comment]
Let's go back to #3319 and I'll reopen it.

Close this.
