### ISSUE TITLE
demo in demo/difuusion,support lora and contorlnet?

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/TensorRT#3680]
[demo](https://github.com/NVIDIA/TensorRT/tree/release/8.6/demo)
/Diffusion/

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by henbucuoshanghai** [comment]
how to load my onw llm?like chillout  or anything?in demo/diffusion

**Comment by ttyio** [comment]
@henbucuoshanghai  could you check the source code see how the onnx is exported and trt engine is built from those onnx? thanks!
