### ISSUE TITLE
[Question]:How to add a Dropout layer

### ISSUE THREAD

**Issue by zhuziaho** [NVIDIA/TensorRT#3686]
## Description

How to add Dropout layer

## Environment

**TensorRT Version**:8.6.1.6

## Question

I added a Dropout operation in the VGG16 network layer,.

After generate .wts, I want to build engine files , but I couldn't find any relevant methods to add dropout layer in TensorRT API and Tensorrtx projects.

How can I add a Dropout layer in my c++ projects?

**Comment by zerollzeng** [comment]
Dropout is disabled during inference so I don't think you need it.

**Comment by zhuziaho** [comment]
> Dropout is disabled during inference so I don't think you need it.

Yes, even after ignoring the Dropout operation, I still successfully generated the engine and implemented the classification function I wanted.Although some warnings were generated.
