### ISSUE TITLE
 assert len(prompt) == len(negative_prompt)

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/TensorRT#3696]
https://github.com/NVIDIA/TensorRT/blob/93b6044fc106b69bce6751f27aa9fc198b02bddc/demo/Diffusion/stable_diffusion_pipeline.py#L768

 assert len(prompt) == len(negative_prompt)
why? prompt and negative should be same length?

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by akhilg-nv** [comment]
@henbucuoshanghai `prompt` and `negative_prompt` are lists containing the prompts, the check is that the same number of prompts are provided. Closing as this is not an issue.
