### ISSUE TITLE
convert pytorch model to tensorrt

### ISSUE THREAD

**Issue by xxy90** [NVIDIA/TensorRT#37]
Firstly, I convert pytorch model resnet50 to onnx,which can be inferenced. Then,i convert the onnx file to trt file,but when it run the engine = builder.build_cuda_engine(network), got a None Engine.And I got [TensorRT] ERROR: Network must have at least one output.Can you tell me what cause this error? 
Any response is appreciate.Thank you!

**Comment by JimKlingshirn** [comment]
You might take a look at the internal structure of your onnx file, and verify the number of intputs using Netron:
[https://electronjs.org/apps/netron](url)

**Comment by xxy90** [comment]
Thank you for your advice. I had tried this method, and confirmed that the input of resnet50 is (3,224,224),but it still not work....

**Comment by rmccorm4** [comment]
Hi @xxy90 and @ruyijidan,

Sometimes if the model's metadata isn't setup correctly in PyTorch before exporting, the parser may not recognize the output. This can usually be fixed on the TensorRT side of things after calling `parser.parse()` with something like:

```python
last_layer = network.get_layer(network.num_layers - 1)
network.mark_output(last_layer.get_output(0))
```

See this related issue: https://github.com/NVIDIA/TensorRT/issues/183

**Comment by xxy90** [comment]
Thank you very much! I have sloved my problem by you method!
