### ISSUE TITLE
Optimization profile with dynamic batches doesn't behave the same as setMaxBatchSize

### ISSUE THREAD

**Issue by fran6co** [NVIDIA/TensorRT#370]
## Description

Trying to migrate from tensorRT 5 to 7 and I can't get it to use explicit batching and keep the same performance. Where originally I was using `setMaxBatchSize` with a predefined `maxBatchSize`, now I set the optimization profile for every input to:
- the batch dimension to `-1`
- `nvinfer1::OptProfileSelector::kMIN` to `1`
- `nvinfer1::OptProfileSelector::kOPT` to `maxBatchSize`
- `nvinfer1::OptProfileSelector::kMAX` to `maxBatchSize`

and then call `setBindingDimensions` with the input batch size. This generates a much smaller and less performant serialized engine than just using `setMaxBatchSize`

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: Geforce 2060
**Nvidia Driver Version**: 441.66
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5.32
**Operating System + Version**: Windows 10

## Steps To Reproduce

```
        const auto config = builder->createBuilderConfig();
	const auto profile = builder->createOptimizationProfile();
	for (int i = 0; i < network->getNbInputs(); ++i) {
		auto input = network->getInput(i);
		auto dims = input->getDimensions();
		dims.d[0] = -1;
		input->setDimensions(dims);

		auto minDims = dims;
		minDims.d[0] = 1;

		auto optDims = dims;
		optDims.d[0] = maxBatchSize;

		auto maxDims = dims;
		maxDims.d[0] = maxBatchSize;

		profile->setDimensions(input->getName(), nvinfer1::OptProfileSelector::kMIN, minDims);
		profile->setDimensions(input->getName(), nvinfer1::OptProfileSelector::kOPT, optDims);
		profile->setDimensions(input->getName(), nvinfer1::OptProfileSelector::kMAX, maxDims);
	}

	config->addOptimizationProfile(profile);
```

**Comment by fran6co** [comment]
If it helps, when logging with verbose I see that the main difference is that I get this message when using dynamic batching but not with implicit batching:

```
FusedConvActConvolution has no valid tactics for this config, skipping
```

**Comment by rmccorm4** [comment]
Hi @fran6co,

As far as performance goes, I would guess that having a single optimization profile with a wide range of input shapes will be less performant than having several optimization profiles with smaller (or even singular) ranges of input shapes.

For example, if your use case is to accept maybe 3 possible input shapes (batch size 1, 8, 16), then I would maybe look into creating 3 optimization profiles, one for each batch size where min=opt=max and select the profile as necessary during inference.

If your use case has to support a wide range of batch sizes, maybe it's better segment it out into a few profiles of non-overlapping ranges of batch sizes and select the profile as necessary during inference.

Though take all of this with a grain of salt because I'm just speculating here, I haven't really dived into this or benchmarked this myself. I'll see if I can get a more educated answer from someone else on this topic.

**Comment by fran6co** [comment]
@rmccorm4 I tried fixing the batch size with min=opt=max to the one I cared about and still the performance was a lot worse, going from 750ms to 3000ms. I also tried multiple profiles, but nothing works. I think that the problem is that with dynamic batches there is some optimization that TensorRT is not doing for some reason. I just wanted to reproduce the same behaviour of implicit batches but with dynamic ones.

1. I'm testing performance with NSight
2. I can't use implicit batch in TRT7 because the ONNX parser doesn't support it anymore (making it really hard to upgrade). When using `setMaxBatchSize` with explicit batches instead of dynamic batch size, TRT7 performs a bit better than TRT 5 but I lose the ability to change the batch size of the input.
3. I'll try to create simple use case using a public model, I'm sure this is not specific to our model or code

**Comment by fran6co** [comment]
In any case the point of this issue is that there is a performance drop going from implicit batch sizes to dynamic batch sizes when it should behave the same. You can make even better by adding multiple optimization profiles, but it should at least behave the same as the other mode.

**Comment by ZimingLu** [comment]
> @rmccorm4 I tried fixing the batch size with min=opt=max to the one I cared about and still the performance was a lot worse, going from 750ms to 3000ms. I also tried multiple profiles, but nothing works. I think that the problem is that with dynamic batches there is some optimization that TensorRT is not doing for some reason. I just wanted to reproduce the same behaviour of implicit batches but with dynamic ones.
> 
> 1. I'm testing performance with NSight
> 2. I can't use implicit batch in TRT7 because the ONNX parser doesn't support it anymore (making it really hard to upgrade). When using `setMaxBatchSize` with explicit batches instead of dynamic batch size, TRT7 performs a bit better than TRT 5 but I lose the ability to change the batch size of the input.
> 3. I'll try to create simple use case using a public model, I'm sure this is not specific to our model or code

same problem. In trt5 I could use dynamic batchsize, but when I use dynamic batchsize in trt7, the outputs varies.  And how about the enqueue() this method? When I use enqueue with batchsize in trt7, warning occurs which implies that I have to use explicit batchsize. But I have to use explict batchsize in onnxparser. I am really confused.

**Comment by rmccorm4** [comment]
@ZimingLu I believe the error you're talking about is because you're using `enqueue` (implicit batch) instead of `enqueue_v2` (explicit batch). Please let me know if that helps your performance at all. The same applies for `execute` vs `execute_v2`. I believe the only difference is that you remove the batch size argument from the function call, but the docs should explain that.

**Comment by ZimingLu** [comment]
@rmccorm4 For example, in trt5 I can export onnx file with batchsize 5 and serialize trt model with batchsize 5. But in implementation I can set any batchsize(<=5) in inference.  The enqueue interface can tell the trt engine the batchsize of input. I also want to set variable batchsize in trt7. So I wonder whether in trt7 the batchsize dimension is included in dynamic input shape? In other words, I have to set batchsize in dynamic shape. Because the  enqueue_v2 interface does not have the batchsize info.
Another problem I met is that when I use lstm in my model, the result is different from python model. The trt precison is lower.

**Comment by rmccorm4** [comment]
Ah, the difference there is now that with explicit batch (TRT 7), the batch size is the one used in the ONNX model itself (probably a fixed batch size value, you can view this in Netron). To make use of a variable batch size, you need to export your ONNX model with a dynamic batch dimension (batch size == -1) from your original DL framework, and then use optimization profiles to set the batch size for given execution contexts at runtime (or just before inference).  

There's a simple example of generating a fixed vs. dynamic shape ONNX from PyTorch here: https://gist.github.com/rmccorm4/b72abac18aed6be4c1725db18eba4930. You can use tf2onnx similarly for tensorflow.

As for the lstm issue, may be related to: https://github.com/NVIDIA/TensorRT/issues/371. If you have a simple script for reproducing that error/difference, that may be helpful.

**Comment by ZimingLu** [comment]
> Ah, the difference there is now that with explicit batch (TRT 7), the batch size is the one used in the ONNX model itself (probably a fixed batch size value, you can view this in Netron).
> 
> To make use of a variable batch size for explicit batch models, you need to export your ONNX model with a dynamic batch dimension (batch size == -1) from your original DL framework, and then use optimization profiles to set the batch size for given execution contexts at runtime (or just before inference). This will require a bit of work to convert to at the moment.
> 
> There's a simple example of generating a fixed vs. dynamic shape ONNX from PyTorch here: https://gist.github.com/rmccorm4/b72abac18aed6be4c1725db18eba4930. You can use tf2onnx similarly for tensorflow.
> 
> As for the lstm issue, may be related to: #371. If you have a simple script for reproducing that error/difference, that may be helpful.

Oh it is pretty complex in trt7. How about enqueue interface? Can we still use enqueue with variable batchsize in trt7? Or enqueue is deprecated in trt7?  As for lstm model, could you provide an email address. It is not convenient for me to publish my model here...

**Comment by MuyangDu** [comment]
> Ah, the difference there is now that with explicit batch (TRT 7), the batch size is the one used in the ONNX model itself (probably a fixed batch size value, you can view this in Netron).
> 
> To make use of a variable batch size for explicit batch models, you need to export your ONNX model with a dynamic batch dimension (batch size == -1) from your original DL framework, and then use optimization profiles to set the batch size for given execution contexts at runtime (or just before inference). This will require a bit of work to convert to at the moment.
> 
> There's a simple example of generating a fixed vs. dynamic shape ONNX from PyTorch here: https://gist.github.com/rmccorm4/b72abac18aed6be4c1725db18eba4930. You can use tf2onnx similarly for tensorflow.
> 
> As for the lstm issue, may be related to: #371. If you have a simple script for reproducing that error/difference, that may be helpful.

Hi, Could you provide an example of generating dynamic batch size ONNX file using tf2onnx? I'm trying to export a TensorFlow model to ONNX in order to use explicit batch in TRT7 but didn't find out how to use tf2onnx to generate dynamic batch axes. Thanks!

**Comment by rajeevsrao** [comment]
@MuyangDu  Specify `None` in the dynamic dimension(s). Ex: https://github.com/onnx/tensorflow-onnx/issues/1112
@ZimingLu you can post the model/repro test on a shared drive and email me at rajeevrao at nvidia.

@fran6co as you observed it looks like we are not picking a certain optimal tactic in the dynamic batch case. This is not expected and we would like to debug further. Please provide the repro when you have it ready. Thanks.

**Comment by DuckJ** [comment]
> > Ah, the difference there is now that with explicit batch (TRT 7), the batch size is the one used in the ONNX model itself (probably a fixed batch size value, you can view this in Netron).
> > To make use of a variable batch size for explicit batch models, you need to export your ONNX model with a dynamic batch dimension (batch size == -1) from your original DL framework, and then use optimization profiles to set the batch size for given execution contexts at runtime (or just before inference). This will require a bit of work to convert to at the moment.
> > There's a simple example of generating a fixed vs. dynamic shape ONNX from PyTorch here: https://gist.github.com/rmccorm4/b72abac18aed6be4c1725db18eba4930. You can use tf2onnx similarly for tensorflow.
> > As for the lstm issue, may be related to: #371. If you have a simple script for reproducing that error/difference, that may be helpful.
> 
> Oh it is pretty complex in trt7. How about enqueue interface? Can we still use enqueue with variable batchsize in trt7? Or enqueue is deprecated in trt7? As for lstm model, could you provide an email address. It is not convenient for me to publish my model here...

hi, did you have a conclusion? In trt7, I used explicit batch.
1.  I tried convert the pytorch model into onnx  model with batch dimension dynamic only， but when I set the optimization profile only change the  batchsize, the model  serialization is failed. 
2. I also tried  convert the pytorch model into onnx  model with width dimension dynamic only and changed the width in optimization profile, the model  serialization  succeed.
3.  Another try， I convert the pytorch model into onnx  model with batch dimension dynamic only and  not set optimization profile. the error is model input is dynamic shape, and  should set optimization profil

**Comment by Sixkplus** [comment]
Any update for this issue?
Recently, I'm trying to generate a trt engine from a pytorch model.
In my case, I have tried the following two ways.
1. torch -> caffe -> tensorrt  (maxBatchSize=16)
2. torch -> onnx -> tensorrt  (maxBatchSize=optBatchSize=16)
I found the model generated with caffe is much faster(about 3x) than that from onnx, and the batch size really matters.

**Comment by nvpohanh** [comment]
@Sixkplus Is it possible to share the Caffe model and the ONNX model with repro commands so that we can debug why there is perf discrepancy? Thanks

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
