### ISSUE TITLE
Question about difference between ammo.torch.quantization and pytorch_quantization

### ISSUE THREAD

**Issue by zhexinli** [NVIDIA/TensorRT#3701]
## Description

The nvidia 9.3 add int8 quantizaition for the diffusion demo, using ammo.torch.quantization to do calibration and export to onnx. I was wondering what's the difference between ammo.torch.quantization and pytorch_quantization? Why do TensorRTLLM and diffusion demo both use nvidia-ammo instead of pytorch_quantization. Is there some limitation about pytorch_quantion that it can not apply to the transforme-based model, for example, it can't not activate the int8 MHA kernel? Or ammo is just simple wrap and intergration for pytorch_quantizion for easier usage? I googled nvidia-ammo and find no official docs or explanation about this tool.  I'll apprexiate it if someone could cast some insight.

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
Yes, currently we are in the stage to move all the pytorch-quanitzation function to ammo, now the new features will only be added to ammo, and in the near future we will deprecate pytorch-quantization, announce the AMMO with full documentation. Thanks!

**Comment by zhexinli** [comment]
> Yes, currently we are in the stage to move all the pytorch-quanitzation function to ammo, now the new features will only be added to ammo, and in the near future we will deprecate pytorch-quantization, announce the AMMO with full documentation. Thanks!
sounds great! looking foward to your future work

**Comment by zerollzeng** [comment]
Can we close this ^ ^ or do you have any further questions? Thanks!

**Comment by zhexinli** [comment]
Of course, thx

**Comment by bigmover** [comment]
> deprecate


Hi guys！ what new features AMMO  add beyond pytorch_quantization? Any reply will be appreciated.

**Comment by bigmover** [comment]
> Yes, currently we are in the stage to move all the pytorch-quanitzation function to ammo, now the new features will only be added to ammo, and in the near future we will deprecate pytorch-quantization, announce the AMMO with full documentation. Thanks!

Hi guys！ what new features AMMO add beyond pytorch_quantization? Any reply will be appreciated.

**Comment by ttyio** [comment]
> > Yes, currently we are in the stage to move all the pytorch-quanitzation function to ammo, now the new features will only be added to ammo, and in the near future we will deprecate pytorch-quantization, announce the AMMO with full documentation. Thanks!
> 
> Hi guys！ what new features AMMO add beyond pytorch_quantization? Any reply will be appreciated.

All the investigation on FP8, INT4, WoQ, etc. are in ModelOpt (renamed from AMMO), https://github.com/NVIDIA/TensorRT-Model-Optimizer for more detail, thanks!
