### ISSUE TITLE
cannot import name 'cuda_ext' from 'pytorch_quantization'

### ISSUE THREAD

**Issue by miraiaroha** [NVIDIA/TensorRT#3702]
## Description

  I install pytorch-quantization from source code

 ```
git clone https://github.com/NVIDIA/TensorRT.git
 cd tools/pytorch-quantization
 python setup.py install
```

  but cannot import cuda_ext, as below

```
$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> from pytorch_quantization import cuda_ext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'cuda_ext' from 'pytorch_quantization' (/disk1/cyr/TensorRT/tools/pytorch-quantization/pytorch_quantization/__init__.py)
\>>>
```

## Environment

**CUDA Version**: 11.8

**pytorch-quantization Version**: 2.1.3

**pytorch Version**: 2.0.1

**Comment by Fritskee** [comment]
How did you solve this? 

I also keep getting issues with `cuda_ext`

**Comment by MandeepSingh396** [comment]
Any update on this? I am also getting the same error.

**Comment by sushant-97** [comment]
I am getting same error of circular import. help plz!

**Comment by miraiaroha** [comment]
> I am getting same error of circular import. help plz!

It's been quite some time now, I've forgotten a bit. But I think is related to version, release/8.6 TensorRT can work in my environment.

**Comment by miraiaroha** [comment]
> Any update on this? I am also getting the same error.

It's been quite some time now, I've forgotten a bit. But I think is related to version, release/8.6 TensorRT can work in my environment.

**Comment by miraiaroha** [comment]
> How did you solve this?
> 
> I also keep getting issues with `cuda_ext`, I tried both building from source and installing pip. In either case I get the same issue. I also made sure to have clean environments when installing from source or installing from pip.

It's been quite some time now, I've forgotten a bit. But I think is related to version, release/8.6 TensorRT can work in my environment.
