### ISSUE TITLE
I have a problem.

### ISSUE THREAD

**Issue by chuyhu** [NVIDIA/TensorRT#372]
ERROR: /data/yh/onnx-tensorrt/ModelImporter.cpp:537 In function importModel:
[5] Assertion failed: tensors.count(input_name)

**Comment by rmccorm4** [comment]
Hi @chuyhu,

Please follow the issue template. I can't do much to help with just this information. I need more info about your environment, versions, and a reproducible example to test.

**Comment by dhkim0225** [comment]
@chuyhu Please visualize your onnx file with netron.

**Comment by rmccorm4** [comment]
Closing until more details are given
