### ISSUE TITLE
Error Code 4:Internal Error (/encoder/layers.10/Conv: number of kernel weights does not match tensor dimensions)

### ISSUE THREAD

**Issue by Liupei1101** [NVIDIA/TensorRT#3720]
onnx convert to trt model failed .
commend ./trtexec --onnx=/RAID5/user/liupei/ProPainter/E2FGVI/release_model/E2FGVI-HQ-CVPR22_LIUPEI.onnx --saveEngine=/RAID5/user/liupei/ProPainter/E2FGVI/release_model/E2FGVI-HQ-CVPR22_LIUPEI.trt --explicitBatch

/encoder/layers.10/Conv /encoder/layers.10/Conv:kernel weights has count 1474560 but 737280 was expected /encoder/layers.10/Conv: count of 1474560 weights in kernel, but kernel dimensions (3,3) with 320 input channels, 512 output channels and 2 groups were specified. Expected Weights count is 320 * 3*3 * 512 / 2 = 737280

**Comment by Liupei1101** [comment]
![1a355f9e-abe8-4526-a1b2-1778f07b4126](https://github.com/NVIDIA/TensorRT/assets/49631172/e4796cf9-8574-4647-b7ef-37ab715642f1)
![Uploading 5697b40b-4294-4c57-8c32-7f48afb12ba4.png…]()

**Comment by Liupei1101** [comment]
![Uploading 5697b40b-4294-4c57-8c32-7f48afb12ba4.png…]()

**Comment by Liupei1101** [comment]
![download](https://github.com/NVIDIA/TensorRT/assets/49631172/38bd63a9-ee07-4c8e-8b59-e0ba6362ebc3)

**Comment by Liupei1101** [comment]
the error code in here:
def forward(self, x):
        bt, c, _, _ = x.size()
        # h, w = h//4, w//4
        out = x
        for i, layer in enumerate(self.layers):
             if i == 8:
                  x0 = out
                  _, _, h, w = x0.size()
              if i > 8 and i % 2 == 0:
                  g = self.group[(i - 8) // 2]
                  x = x0.view(bt, g, -1, h, w)
                  o = out.view(bt, g, -1, h, w)
                  out = torch.cat([x, o], 2).view(bt, -1, h, w)
              out = layer(out)
        return out

**Comment by Liupei1101** [comment]
`def forward(self, x):
        bt, c, _, _ = x.size()
        # h, w = h//4, w//4
        out = x
        for i, layer in enumerate(self.layers):
             if i == 8:
                  x0 = out
                  _, _, h, w = x0.size()
              if i > 8 and i % 2 == 0:
                  g = self.group[(i - 8) // 2]
                  x = x0.view(bt, g, -1, h, w)
                  o = out.view(bt, g, -1, h, w)
                  out = torch.cat([x, o], 2).view(bt, -1, h, w)
              out = layer(out)
        return out`

**Comment by Liupei1101** [comment]
def forward(self, x):
        bt, c, _, _ = x.size()
        # h, w = h//4, w//4
        out = x
        for i, layer in enumerate(self.layers):
             if i == 8:
                  x0 = out
                  _, _, h, w = x0.size()
              if i > 8 and i % 2 == 0:
                  g = self.group[(i - 8) // 2]
                  x = x0.view(bt, g, -1, h, w)
                  o = out.view(bt, g, -1, h, w)
                  out = torch.cat([x, o], 2).view(bt, -1, h, w)
              out = layer(out)
        return out

**Comment by zerollzeng** [comment]
1. does it work with onnx runtime?
2. I guess you are feeding incompatible input shapes.

**Comment by Liupei1101** [comment]
> 1. does it work with onnx runtime?
> 2. I guess you are feeding incompatible input shapes.

![image](https://github.com/NVIDIA/TensorRT/assets/49631172/0e95426a-a968-484b-95d8-eb61968b157e)
/encoder/layers.10/Conv /encoder/layers.10/Conv:kernel weights has count 1474560 but 737280 was expected /encoder/layers.10/Conv: count of 1474560 weights in kernel, but kernel dimensions (3,3) with 320 input channels, 512 output channels and 2 groups were specified. Expected Weights count is 320 * 3*3 * 512 / 2 = 737280

when static_axes  onnx convert to tensorRT model, it works well, when convert  dynamic_axes onnx model to tensorRT, the error oappear again. i do not know why?

**Comment by zerollzeng** [comment]
Could you please share the onnx here? Maybe a bug.

**Comment by zerollzeng** [comment]
I quickly create a minimal reproduce but cannot repro:
```
$ ls
conv.onnx  make_conv.py
(base) zeroz @ ipp2-2325 2024/04/13-02:31:32 ~/scratch.zeroz_sw/github_bug/3720
$ cat make_conv.py
import torch

class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()
        self.conv = torch.nn.Conv2d(640, 512, (3,3), stride=1, padding=1, groups=2)

    def forward(self, x):
        x = self.conv(x)
        return x

dummy_input = torch.randn(1, 640, 14, 14, device="cpu")
model = TinyModel()

input_names = [ "input" ]
output_names = [ "output" ]

# dynamic_axes={'input' : {0 : 'bs'}, 'output' : {0 : 'bs'}}
# export(..., dynamic_axes = dynamic_axes)
torch.onnx.export(model, dummy_input, "conv.onnx", opset_version=13, verbose=True, input_names=input_names, output_names=output_names)
```

**Comment by Liupei1101** [comment]
i find the error,because 
![image](https://github.com/NVIDIA/TensorRT/assets/49631172/fd3fa8a6-d30c-480b-b357-f26644bc2152)
when group>1,reshape node can not know the shape, when i convert to 
![image](https://github.com/NVIDIA/TensorRT/assets/49631172/8a7174cc-6e24-4111-8d06-6a28f7e44d20)
it solved. thanks

**Comment by Liupei1101** [comment]
> I quickly create a minimal reproduce but cannot repro:
> 
> ```
> $ ls
> conv.onnx  make_conv.py
> (base) zeroz @ ipp2-2325 2024/04/13-02:31:32 ~/scratch.zeroz_sw/github_bug/3720
> $ cat make_conv.py
> import torch
> 
> class TinyModel(torch.nn.Module):
> 
>     def __init__(self):
>         super(TinyModel, self).__init__()
>         self.conv = torch.nn.Conv2d(640, 512, (3,3), stride=1, padding=1, groups=2)
> 
>     def forward(self, x):
>         x = self.conv(x)
>         return x
> 
> dummy_input = torch.randn(1, 640, 14, 14, device="cpu")
> model = TinyModel()
> 
> input_names = [ "input" ]
> output_names = [ "output" ]
> 
> # dynamic_axes={'input' : {0 : 'bs'}, 'output' : {0 : 'bs'}}
> # export(..., dynamic_axes = dynamic_axes)
> torch.onnx.export(model, dummy_input, "conv.onnx", opset_version=13, verbose=True, input_names=input_names, output_names=output_names)
> ```

thanks,i solved.

**Comment by zerollzeng** [comment]
Ok, I'm closing this.
