### ISSUE TITLE
How to get closer accuracy with FP16 in demo/Diffusion 8-bits PTQ?

### ISSUE THREAD

**Issue by TheBge12138** [NVIDIA/TensorRT#3723]
Hello, notice that tensorrt 9.3 had updated the 8-bit quantization to accelerate diffusion models, it's excellent !
But when running the demo, i can't get the same result with fp16, I have modified the get_pipeline in model.py to my own model, and used over 1000 prompts for calibration, there is a big gap under some prmopts, and some prmopts are close but still not completely similar.

my sdxl model pipeline has 30steps, I compared the cosine similarity of the unet output tensor. In 60 prompt tests, compared with fp16, the similarity fluctuated between 89% and 97%.

in https://developer.nvidia.com/blog/tensorrt-accelerates-stable-diffusion-nearly-2x-faster-with-8-bit-post-training-quantization/
I saw you can get images that are nearly identical to original FP16 precision. 
Is there anything I can do to improve the accuracy of my in8 model？

Thanks!
```[tasklist]
### Tasks
```

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by jingyu-ml** [comment]
The team is working on updating the calibration code. Current code is outdated, its different from the blog. 
After we released release/10.0 you can have another try, thanks! @TheBge12138

**Comment by TheBge12138** [comment]
Hi,
thanks for your reply!
Can I ask when release/10.0 will be released?




陈冰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVIDIA/TensorRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月22日(星期五) 晚上8:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVIDIA/TensorRT] How to get closer accuracy with FP16 in demo/Diffusion 8-bits PTQ? (Issue #3723)





 
The team is working on updating the calibration code. Current code is outdated, its different from the blog.
 After we released release/10.0 you can have another try, thanks! @TheBge12138

**Comment by TheBge12138** [comment]
@jingyu-ml
thanks for your reply! i saw it on email
Can I ask when release/10.0 will be released?

**Comment by jingyu-ml** [comment]
> @jingyu-ml thanks for your reply! i saw it on email Can I ask when release/10.0 will be released?

I don't have the release date, but I would say its in the near future and the team is working on it.

**Comment by zerollzeng** [comment]
TRT 10 EA has been released.

**Comment by TheBge12138** [comment]
> TRT 10 EA has been released.

Excellent, thanks for your work!

**Comment by jingyu-ml** [comment]
@TheBge12138 please check the GA release instead of the EA release
https://github.com/NVIDIA/TensorRT/commit/d3107c885ae40085dca4543e75da72bbe18d824c

**Comment by TheBge12138** [comment]
> @TheBge12138 please check the GA release instead of the EA release [d3107c8](https://github.com/NVIDIA/TensorRT/commit/d3107c885ae40085dca4543e75da72bbe18d824c)

thanks!
