### ISSUE TITLE
cannot import name 'PreviewFeature' from 'tensorrt' 

### ISSUE THREAD

**Issue by DuyTa506** [NVIDIA/TensorRT#3738]
I'm trying to reimplement a NMT module by tensorrt but when i run the example code, in trl.py file it told me that 
ImportError: cannot import name 'PreviewFeature' from 'tensorrt' (/usr/local/lib/python3.8/dist-packages/tensorrt/__init__.py)

Environment : python 3.8 , CUDA 11.5 , tensort  8.2.5.1

**Comment by lix19937** [comment]
You need to update tensorrt 8.5.1 or later .

**Comment by DuyTa506** [comment]
okay i'll try it , thanks for advices
