### ISSUE TITLE
one bash is not correct of quickstart/deploy_to_triton/README.md

### ISSUE THREAD

**Issue by wendashi** [NVIDIA/TensorRT#3745]
## Description

  In  Step 1 of quickstart/deploy_to_triton/README.md.  , here is a bash: `polygraphy inspect model model.plan --mode=basic`

and a error come out as following:

`polygraphy inspect model: error: argument --model-type: invalid choice: 'basic' (choose from 'frozen', 'keras', 'ckpt', 'onnx', 'engine', 'uff', 'trt-network-script', 'caffe')
`
## Solution

change the --mode=**basic** into --mode=**engine**, then we can see the details of the .plan model 

    [W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
    [I] Loading bytes from /trt_optimize/model.plan
    [I] ==== TensorRT Engine ====
    Name: Unnamed Network 0 | Explicit Batch Engine
    
    ---- 1 Engine Input(s) ----
    {input [dtype=float32, shape=(1, 3, 224, 224)]}
    
    ---- 1 Engine Output(s) ----
    {output [dtype=float32, shape=(1, 1000)]}
    
    ---- Memory ----
    Device Memory: 7325696 bytes
    
    ---- 1 Profile(s) (2 Tensor(s) Each) ----
    - Profile: 0
        Tensor: input           (Input), Index: 0 | Shapes: min=(1, 3, 224, 224), opt=(1, 3, 224, 224), max=(1, 3, 224, 224)
        Tensor: output         (Output), Index: 1 | Shape: (1, 1000)
    
    ---- 87 Layer(s) ----

**Comment by lix19937** [comment]
Ref Polygraphy/polygraphy/tools/args/model.py   
```
    EXT_MODEL_TYPE_MAPPING = {
        ".hdf5": "keras",
        ".uff": "uff",
        ".prototxt": "caffe",
        ".onnx": "onnx",
        ".engine": "engine",
        ".plan": "engine",
        ".graphdef": "frozen",
        ".py": "trt-network-script",
    }
```

`--mode=basic` maybe typo .

**Comment by zerollzeng** [comment]
I didn't see this option, are you using an old version of polygraphy?
```
  --model-type {frozen,keras,ckpt,onnx,engine,uff,trt-network-script,caffe}
                        The type of the input model: {{'frozen': TensorFlow frozen graph; 'keras': Keras model; 'ckpt': TensorFlow checkpoint directory; 'onnx': ONNX model; 'engine': TensorRT engine; 'trt-network-script': A Python
                        script that defines a `load_network` function that takes no arguments and returns a TensorRT Builder, Network, and optionally Parser. If the function name is not `load_network`, it can be specified after the
                        model file, separated by a colon. For example: `my_custom_script.py:my_func`; 'uff': UFF file [deprecated]; 'caffe': Caffe prototxt [deprecated]}}
```

**Comment by zerollzeng** [comment]
Okay looks like we need to update the README.

**Comment by zerollzeng** [comment]
Filed internal MR to fix this.
