### ISSUE TITLE
getBindingIndex() is DEPRECATED

### ISSUE THREAD

**Issue by Egorundel** [NVIDIA/TensorRT#3746]
## Description

Hello!
I want to find out the BindingIndex by the tensor name. 
How can I do this, provided that the getBindingIndex() method is deprecated in 8.5.

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: RTX 3060

**NVIDIA Driver Version**: 545.23.06

**CUDA Version**: 11.1

**CUDNN Version**: 8.0.4

Operating System:

Python Version (if applicable): 3.8

PyTorch Version (if applicable): 10.1

**Comment by lix19937** [comment]
If you just want to get shape(dims) of tensor(binding), use `getTensorShape(char const * tensorName)`, when TensorRT Version is 8.6

**Comment by DeepLearnerYe** [comment]
`getTensorShape(char const * tensorName)` requires tensorName. If I want to get the name automatically instead of specifying the name, `getBindingName(int32_t)` is provided. But it is also deprecated in 8.5, what can I do?

**Comment by lix19937** [comment]
@DeepLearnerYe 
Use 
```
int32_t nvinfer1::ICudaEngine::getNbIOTensors()	
char const * nvinfer1::ICudaEngine::getIOTensorName(int32_t index) const
``` 
ref in https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-853/api/index.html
