### ISSUE TITLE
[pytorch-quantization] it seems that `_normalize_distr` function does not work

### ISSUE THREAD

**Issue by thb1314** [NVIDIA/TensorRT#3752]
https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L191

the `_normalize_distr` function
```python
def _normalize_distr(distr):
    summ = np.sum(distr)
    if summ != 0:
        distr = distr / summ
```

It can not modidy the value of the argument `distr`.
Maybe return the `distr` or use other motheds to  normalize the input distribution ?

**Comment by lix19937** [comment]
I think  
https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L234   and   
https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L244   can be commented.   

This routine of `entropy(reference_density, new_density)` will normalize reference_density and new_density if they don’t sum to 1

**Comment by thb1314** [comment]
> I think https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L234 and https://github.com/NVIDIA/TensorRT/blob/release/8.6/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L244 can be commented.
> 
> NOTE: The routine of `entropy(P, Q)` will normalize `P` and `Q` if they don’t sum to 1.

@lix19937 I think you are right

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by ttyio** [comment]
FYI, the pytorch-quantization will be deprecated soon, we will move to ammo toolkit which is already widely used in tensorrt-llm.

**Comment by ttyio** [comment]
Now we have release https://github.com/NVIDIA/TensorRT-Model-Optimizer, I will close this, thanks all!
