### ISSUE TITLE
fail to install tensorrt package using pip

### ISSUE THREAD

**Issue by Kuchchi12** [NVIDIA/TensorRT#3759]
![Screenshot 2024-04-01 161104](https://github.com/NVIDIA/TensorRT/assets/56125522/3fc6107b-7364-4f2f-ab73-ba5e113a32f3)

Operating System:Win11

Python Version :3.8.10

**Comment by lix19937** [comment]
ERROR: NO matching distribution found for tensorrt_libs==8.6.1     
you can change download-source of pip  by `-i`

**Comment by zerollzeng** [comment]
We don't support install tensorrt via in windows before TRT 10.

**Comment by zerollzeng** [comment]
Try `pip install tensorrt==10.0.0b6`

**Comment by Kuchchi12** [comment]
> Try `pip install tensorrt==10.0.0b6`

Alright its done I found alternate converting method
Thank you @zerollzeng @lix19937

**Comment by Alxah** [comment]
> > Try `pip install tensorrt==10.0.0b6`
> 
> Alright its done I found alternate converting method Thank you @zerollzeng @lix19937

can I ask what is your method？ I`ve stock into the same problem @Kuchchi12
