### ISSUE TITLE
bad format of trt user guide 

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#3764]
See follow jpg   

![image](https://github.com/NVIDIA/TensorRT/assets/38753233/778adea5-e91b-4f6c-81c7-a9560a6e3cb4)

ref https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#memory-runtime-phase

**Comment by zerollzeng** [comment]
Thanks, we will fix it in the next release.
