### ISSUE TITLE
onnx_graphsurgeon enhancement for subgraph replacement

### ISSUE THREAD

**Issue by peterkisfaludi** [NVIDIA/TensorRT#3767]
## Description

In /home/pkisfaludi/git/oss/tools/onnx-graphsurgeon/examples/08_replacing_a_subgraph, the subgraph replacement script does not work for every scenario.

The `replace_with_clip` method specifies the subgraph to be replaced by listing input and output tensors.
There could be nodes whose input tensor(s) are coming from the `inputs` list, but have other inputs as well.
These nodes will still get removed, which is not the desired behavior.
The desired behavior is to remove _only_ the nodes whose inputs _all_ appear in the `inputs` list

## Environment

**TensorRT Version**:
10.0.0.6

**NVIDIA GPU**:
N/A

**NVIDIA Driver Version**:
N/A

**CUDA Version**:
N/A

**CUDNN Version**:
N/A

Operating System:
N/A

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by zerollzeng** [comment]
Well, I think the purpose of the samples is to demonstrate a basic way of how to do a subgraph replacement so the code was written for https://github.com/NVIDIA/TensorRT/blob/release/10.0/tools/onnx-graphsurgeon/examples/08_replacing_a_subgraph/generate.py

**Comment by zerollzeng** [comment]
Please point me out if I misunderstand you issue :-)

**Comment by peterkisfaludi** [comment]
OK so would you recommend creating a different example with a complex graph?
My point is that the replacement script is not generic ie. it will not work for every scenario, wouldn't we want a generic solution or it is up to the users to come up with a replacement script that matches their use-case?

**Comment by zerollzeng** [comment]
It would be great if you can improve the sample and file a PR for us, I'll ask some people to review :-)

(I guess we just don't have a clear scope of what this sample should provided when we write it, since other samples are also very simple. Just want the user know: you can do this, and here is a sample for reference :-D
