### ISSUE TITLE
Does BiLSTM support dynamic shapes

### ISSUE THREAD

**Issue by float123** [NVIDIA/TensorRT#377]
I need to input a picture of unknown shape(HxWx1) to BiLSTM. If I set create_network (1), the following will happen:
  lstm.direction = trt.RNNDirection.BIDIRECTION
AttributeError: 'NoneType' object has no attribute 'direction'
![viewfile](https://user-images.githubusercontent.com/39334643/74413186-e77d9d80-4e79-11ea-9fc4-b9c2eec1b680.png)
tensorrt7.0

**Comment by rmccorm4** [comment]
In the future please produce a full reproducible code snippet.

This error is happening because whatever function call you made to create `lstm` failed, returning None. 

Most/all of the `add_*` functions return None if they failed, ex: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Graph/Network.html#tensorrt.INetworkDefinition.add_rnn_v2

I don't have enough information here to know why that failed.

**Comment by float123** [comment]
@rmccorm4 Thanks,I don't have a complete model yet, but I found that I might be missing int (trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

**Comment by float123** [comment]
Hi,@rmccorm4 ,I tried to connect lstm behind VGG16, but I still failed. If the input shape of lstm is [-1, -1, C], it will fail to create.This is part of my code.

`import tensorrt as trt
import numpy as np
import tensorflow as tf
import pycuda.autoinit
import pycuda.driver as cuda
import os
cuda.Device(0).make_context()

b_fp16 = True
max_time_step = 75
logger = trt.Logger(trt.Logger.INFO)


class model:
    def __init__(self, b_fp16):
        self.b_fp16 = b_fp16

        trt_file_path = "ctpn_1.trt"
        if os.path.isfile(trt_file_path):
            with open(trt_file_path, 'rb') as f:
                engine_str = f.read()
        else:
            engine_str = self.build_engine_str(b_fp16)
            print("create new trt engine: ", trt_file_path)
            with open(trt_file_path, 'wb') as f:
                f.write(engine_str)

        with trt.Runtime(logger) as runtime:
            self.engine = runtime.deserialize_cuda_engine(engine_str)
        self.context = self.engine.create_execution_context()

    def __del__(self):
        self.context = None
        self.engine = None

    def create_engine(self, builder, b_fp16):
        params = np.load('tf_args.npz')
        bag = []
        network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
        data = network.add_input("data", trt.DataType.FLOAT, (1, 3, -1, -1))

        # VGG16....
        w = params['conv1_1/weights:0'].transpose((3, 2, 0, 1)).reshape(-1)
        b = params['conv1_1/biases:0']
        bag += [w, b]
        conv1_1 = network.add_convolution(data, 64, (3, 3), w, b)
        conv1_1.stride = (1, 1)
        print('conv1_1', conv1_1.get_output(0).shape)
        actv1_1 = network.add_activation(conv1_1.get_output(0), trt.ActivationType.RELU)

        w = params['conv1_2/weights:0'].transpose((3, 2, 0, 1)).reshape(-1)
        b = params['conv1_2/biases:0']
        bag += [w, b]
        conv1_2 = network.add_convolution(actv1_1.get_output(0), 64, (3, 3), w, b)
        conv1_2.stride = (1, 1)
        actv1_2 = network.add_activation(conv1_2.get_output(0), trt.ActivationType.RELU)
        print('conv1_2', conv1_2.get_output(0).shape)

        pool1 = network.add_pooling(actv1_2.get_output(0), trt.PoolingType.MAX, (2, 2))
        pool1.stride = (2, 2)
        # ......

        # [N, C, H, W]->[NH, W, C]
        shape0 = network.add_shape(pool1.get_output(0)).get_output(0)
        n0 = network.add_slice(shape0, (0,), (1,), (1,)).get_output(0)
        c0 = network.add_slice(shape0, (1,), (1,), (1,)).get_output(0)
        h0 = network.add_slice(shape0, (2,), (1,), (1,)).get_output(0)
        w0 = network.add_slice(shape0, (3,), (1,), (1,)).get_output(0)
        Nh0 = network.add_elementwise(n0, h0, trt.ElementWiseOperation.PROD).get_output(0)
        shape1 = network.add_concatenation([Nh0, w0, c0]).get_output(0)

        shuf0 = network.add_shuffle(pool1.get_output(0))
        shuf0.first_transpose = (0, 2, 3, 1)
        shuf0.set_input(1, shape1)
        print('shuf0: ', shuf0.get_output(0).shape)

        n_input = 512
        n_hidden = 128
        lstm = network.add_rnn_v2(shuf0.get_output(0), 1, n_hidden, 75, trt.RNNOperation.LSTM)
        lstm.direction = trt.RNNDirection.BIDIRECTION
        zero_bias = np.zeros(128, dtype=np.float32)
        for i in range(4):
            layer = i // 2
            iW = i % 2
            isW = True if iW == 0 else False
            param_name = 'lstm_o/bidirectional_rnn/{}/lstm_cell/'.format("fw" if layer % 2 == 0 else "bw")
            all_w = [w.transpose((1, 0)).reshape(-1) for w in
                    np.split(np.split(params[param_name + 'kernel:0'], [n_input])[iW], 4, axis=1)]
            all_b = [w if isW else zero_bias for w in np.split(params[param_name + 'bias:0'], 4)]
            for t, w, b in zip(
                    [trt.RNNGateType.INPUT, trt.RNNGateType.CELL, trt.RNNGateType.FORGET, trt.RNNGateType.OUTPUT],
                    all_w, all_b):
                lstm.set_weights_for_gate(layer, t, isW, w)
                lstm.set_bias_for_gate(layer, t, isW, b)
        print('lstm', lstm.get_output(0).shape)

        network.mark_output(lstm.get_output(0))
        op = builder.create_optimization_profile()
        op.set_shape('data', (1, 3, 16, 16), (1, 3, 600, 600), (1, 3, 1200, 1200))
        config = builder.create_builder_config()
        config.add_optimization_profile(op)

        builder.max_workspace_size = 1 << 30
        builder.fp16_mode = b_fp16
        return builder.build_engine(network, config)

    def build_engine_str(self, b_fp16):
        with trt.Builder(logger) as builder, self.create_engine(builder, b_fp16) as engine:
            return engine.serialize()

    def infer(self, input_shape, d_input, d_output):
        bindings = [int(d_input), int(d_output)]
        self.context.set_binding_shape(0, input_shape)
        self.context.execute_async_v2(bindings, 0)


if __name__ == '__main__':
    # config = tf.ConfigProto()
    # config.gpu_options.per_process_gpu_memory_fraction = 0.08
    # with tf.Session() as sess:
    #     # saver = tf.train.Saver()
    #     new_saver = tf.train.import_meta_graph('./data/model.ckpt.meta')
    #     new_saver.restore(sess, "./data/model.ckpt")
    #
    #     tf_args = {}
    #     for i in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES):
    #         tf_args[i.name] = sess.run(i)
    #         print(i.name)
    #         np.savez('tf_args.npz', **tf_args)

    model1 = model(b_fp16)
`

**Comment by float123** [comment]
Hi,@rmccorm4 ,I tried to connect lstm behind VGG16, but I still failed. If the input shape of lstm is [-1, -1, C], it will fail to create.This is part of my code.

`
import tensorrt as trt
import numpy as np
import tensorflow as tf
import pycuda.autoinit
import pycuda.driver as cuda
import os
cuda.Device(0).make_context()

b_fp16 = True
max_time_step = 75
logger = trt.Logger(trt.Logger.INFO)


class model:
    def __init__(self, b_fp16):
        self.b_fp16 = b_fp16

        trt_file_path = "ctpn_1.trt"
        if os.path.isfile(trt_file_path):
            with open(trt_file_path, 'rb') as f:
                engine_str = f.read()
        else:
            engine_str = self.build_engine_str(b_fp16)
            print("create new trt engine: ", trt_file_path)
            with open(trt_file_path, 'wb') as f:
                f.write(engine_str)

        with trt.Runtime(logger) as runtime:
            self.engine = runtime.deserialize_cuda_engine(engine_str)
        self.context = self.engine.create_execution_context()

    def __del__(self):
        self.context = None
        self.engine = None

    def create_engine(self, builder, b_fp16):
        params = np.load('tf_args.npz')
        bag = []
        network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
        data = network.add_input("data", trt.DataType.FLOAT, (1, 3, -1, -1))

        # VGG16....
        w = params['conv1_1/weights:0'].transpose((3, 2, 0, 1)).reshape(-1)
        b = params['conv1_1/biases:0']
        bag += [w, b]
        conv1_1 = network.add_convolution(data, 64, (3, 3), w, b)
        conv1_1.stride = (1, 1)
        print('conv1_1', conv1_1.get_output(0).shape)
        actv1_1 = network.add_activation(conv1_1.get_output(0), trt.ActivationType.RELU)

        w = params['conv1_2/weights:0'].transpose((3, 2, 0, 1)).reshape(-1)
        b = params['conv1_2/biases:0']
        bag += [w, b]
        conv1_2 = network.add_convolution(actv1_1.get_output(0), 64, (3, 3), w, b)
        conv1_2.stride = (1, 1)
        actv1_2 = network.add_activation(conv1_2.get_output(0), trt.ActivationType.RELU)
        print('conv1_2', conv1_2.get_output(0).shape)

        pool1 = network.add_pooling(actv1_2.get_output(0), trt.PoolingType.MAX, (2, 2))
        pool1.stride = (2, 2)
        # ......

        # [N, C, H, W]->[NH, W, C]
        shape0 = network.add_shape(pool1.get_output(0)).get_output(0)
        n0 = network.add_slice(shape0, (0,), (1,), (1,)).get_output(0)
        c0 = network.add_slice(shape0, (1,), (1,), (1,)).get_output(0)
        h0 = network.add_slice(shape0, (2,), (1,), (1,)).get_output(0)
        w0 = network.add_slice(shape0, (3,), (1,), (1,)).get_output(0)
        Nh0 = network.add_elementwise(n0, h0, trt.ElementWiseOperation.PROD).get_output(0)
        shape1 = network.add_concatenation([Nh0, w0, c0]).get_output(0)

        shuf0 = network.add_shuffle(pool1.get_output(0))
        shuf0.first_transpose = (0, 2, 3, 1)
        shuf0.set_input(1, shape1)
        print('shuf0: ', shuf0.get_output(0).shape)

        n_input = 512
        n_hidden = 128
        lstm = network.add_rnn_v2(shuf0.get_output(0), 1, n_hidden, 75, trt.RNNOperation.LSTM)
        lstm.direction = trt.RNNDirection.BIDIRECTION
        zero_bias = np.zeros(128, dtype=np.float32)
        for i in range(4):
            layer = i // 2
            iW = i % 2
            isW = True if iW == 0 else False
            param_name = 'lstm_o/bidirectional_rnn/{}/lstm_cell/'.format("fw" if layer % 2 == 0 else "bw")
            all_w = [w.transpose((1, 0)).reshape(-1) for w in
                     np.split(np.split(params[param_name + 'kernel:0'], [n_input])[iW], 4, axis=1)]
            all_b = [w if isW else zero_bias for w in np.split(params[param_name + 'bias:0'], 4)]
            for t, w, b in zip(
                    [trt.RNNGateType.INPUT, trt.RNNGateType.CELL, trt.RNNGateType.FORGET, trt.RNNGateType.OUTPUT],
                    all_w, all_b):
                lstm.set_weights_for_gate(layer, t, isW, w)
                lstm.set_bias_for_gate(layer, t, isW, b)
        print('lstm', lstm.get_output(0).shape)

        network.mark_output(lstm.get_output(0))
        op = builder.create_optimization_profile()
        op.set_shape('data', (1, 3, 16, 16), (1, 3, 600, 600), (1, 3, 1200, 1200))
        config = builder.create_builder_config()
        config.add_optimization_profile(op)

        builder.max_workspace_size = 1 << 30
        builder.fp16_mode = b_fp16
        return builder.build_engine(network, config)

    def build_engine_str(self, b_fp16):
        with trt.Builder(logger) as builder, self.create_engine(builder, b_fp16) as engine:
            return engine.serialize()

    def infer(self, input_shape, d_input, d_output):
        bindings = [int(d_input), int(d_output)]
        self.context.set_binding_shape(0, input_shape)
        self.context.execute_async_v2(bindings, 0)


if __name__ == '__main__':
    # config = tf.ConfigProto()
    # config.gpu_options.per_process_gpu_memory_fraction = 0.08
    # with tf.Session() as sess:
    #     # saver = tf.train.Saver()
    #     new_saver = tf.train.import_meta_graph('./data/model.ckpt.meta')
    #     new_saver.restore(sess, "./data/model.ckpt")
    #
    #     tf_args = {}
    #     for i in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES):
    #         tf_args[i.name] = sess.run(i)
    #         print(i.name)
    #         np.savez('tf_args.npz', **tf_args)

    model1 = model(b_fp16)

`
![图片](https://user-images.githubusercontent.com/39334643/74705313-63972d00-524e-11ea-884c-68aefa5217f7.png)

**Comment by huliang2016** [comment]
@float123 have you fixed your problem yet?

**Comment by Sanster** [comment]
I'm having the same problem

**Comment by leaf918** [comment]
Any progress more?

**Comment by cqray1990** [comment]
@leaf918 have you solver it?

**Comment by leaf918** [comment]
> @leaf918 have you solver it?

I'm working on it,can you work with me together(wechat zizizi191)
