### ISSUE TITLE
[Question] [TRT 10.0] WEIGHTLESS versus STRIP_PLAN

### ISSUE THREAD

**Issue by ethnzhng** [NVIDIA/TensorRT#3775]
Hi, I see that in TRT 10.0, the `WEIGHTLESS` BuilderFlag is being deprecated for `STRIP_PLAN`. Is there any functional difference in this change or is it simply a rename? Thank you

**Comment by ttyio** [comment]
It's the same feature, renamed because the previous name is confusing, our implementation cannot drop all the weights for performance consideration, there might still around 5% weights remaining depends on which model are used.

**Comment by ethnzhng** [comment]
I see, thank you for the clarification
