### ISSUE TITLE
Tensor-RT 10.0.0 Release Note: _about gemm_mha_v2

### ISSUE THREAD

**Issue by HaisongDing** [NVIDIA/TensorRT#3777]
The official Tensor-RT 10.0.0 Release Note mentions that **"If the _gemm_mha_v2 operation is used, the outputs will mismatch the output of PyTorch or the CPU executor. This problem may show up only when building engines with FP16 precision, as _gemm_mha_v2 has an implementation only for FP16."**  [https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html#rel-10-0-0-EA](url)

Can you elaborate more about this issue? For example, when the issue can happen? How to avoid or bypass the use of _gemm_mha_v2 operation when building FP16 engines? If the issue happens, should I use Tensor-RT 9.x instead?

**Comment by zerollzeng** [comment]
@nvpohanh ^ ^

**Comment by nvpohanh** [comment]
This will be fixed in TRT 10.0 GA. For now, if you run into accuracy issue and _gemm_mha_v2 is used, please roll back to TRT 9.3 for now. Thanks

**Comment by HaisongDing** [comment]
Thansk. I tried TRT 9.3 (also 9.2 and 9.1), this error happens: **MultiscaleDeformableAttnPlugin_TRT: could not find any supported formats consistent with input/output data types**. The model can be built and run successfully with TRT 8.6.1.

 I will try again when TRT 10.0 GA comes out.

**Comment by HaisongDing** [comment]
> This will be fixed in TRT 10.0 GA. For now, if you run into accuracy issue and _gemm_mha_v2 is used, please roll back to TRT 9.3 for now. Thanks

Thanks. The issue has been resolved with the newly released TRT-10.0.1.6.
