### ISSUE TITLE
How to get TensorRT-9.2.0.4?

### ISSUE THREAD

**Issue by tricky61** [NVIDIA/TensorRT#3793]
the tensorrt in the tritonserver is 9.2.0.4, but when I convert the model by tensorrt-llm which build with TensorRT-9.2.0.5, so get this error: The engine plan file is not compatible with this version of TensorRT, expecting library version 9.2.0.5 got 9.2.0.4, please rebuild.
so I want to rebuild tensorrt-llm. but how can I get TensorRT-9.2.0.4?
I only find TensorRT-9.2.0.5 In this page https://github.com/NVIDIA/TensorRT/tree/release/9.2
and I cannot find version9.2.0.5 in neither git's branch nor Tags

**Comment by lix19937** [comment]
You can use https://github.com/NVIDIA/TensorRT/tree/v9.1.0, convert the model by tensorrt-llm which build with TensorRT-9.1.0 

> TensorRT engines built with TensorRT 8 will also be compatible with TensorRT 9 and TensorRT 10 runtimes, but not vice versa.
