### ISSUE TITLE
TRT8.4 building with relocation error R_X86_64_TPOFF32 against hidden symbol when making a shared object.

### ISSUE THREAD

**Issue by wutheringcoo** [NVIDIA/TensorRT#3795]
## Environment
**TensorRT Version**: release/8.4
**NVIDIA GPU**: release 11.6
**NVIDIA Driver Version**: Driver Version: 470.239.06  
**CUDA Version**: release 11.6
**CUDNN Version**:
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 0
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

## Steps To Reproduce
STEP1:
cmake .. \
-DTRT_LIB_DIR=/mnt/data/env_cfg/TensorRT-8.4.3.1.Linux.x86_64-gnu.cuda-11.6.cudnn8.4/TensorRT-8.4.3.1/lib/ \
-DTRT_OUT_DIR=`pwd`/out \
-DRT_LIB=/lib/x86_64-linux-gnu/librt.so.1 \
-DCUDNN_ROOT_DIR=/mnt/data/env_cfg/cudnn-linux-x86_64-8.4.0.27_cuda11.6-archive \
-DCUDNN_LIB=/mnt/data/env_cfg/cudnn-linux-x86_64-8.4.0.27_cuda11.6-archive/lib/libcudnn.so 

STEP2:
make -j8

## Log Is Below
1)
[ 67%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/sortScoresPerImage.cu.o
[ 67%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/voxelGeneratorKernels.cu.o
[ 68%] Linking CXX shared library ../../out/libnvcaffeparser.so
/usr/bin/ld: ../../third_party.protobuf/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN14google_private8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object
/usr/bin/ld: CMakeFiles/nvcaffeparser.dir/proto/trtcaffe.pb.cc.o: relocation R_X86_64_PC32 against symbol `descriptor_table_trtcaffe_2eproto' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [parsers/caffe/CMakeFiles/nvcaffeparser.dir/build.make:502: out/libnvcaffeparser.so.8.4.3] Error 1
make[1]: *** [CMakeFiles/Makefile2:1699: parsers/caffe/CMakeFiles/nvcaffeparser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/bertQKVToContextPlugin/qkvToContext.cu.o
2)
[ 72%] Linking CXX shared library ../out/libnvinfer_plugin.so
[ 72%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/bertQKVToContextPlugin/zeroPadding2d.cu.o
/usr/bin/ld: CMakeFiles/nvinfer_plugin.dir/batchTilePlugin/batchTilePlugin.cpp.o: relocation R_X86_64_PC32 against symbol `_ZN8nvinfer16plugin22BatchTilePluginCreator3mFCE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [plugin/CMakeFiles/nvinfer_plugin.dir/build.make:2776: out/libnvinfer_plugin.so.8.4.3] Error 1
make[1]: *** [CMakeFiles/Makefile2:1561: plugin/CMakeFiles/nvinfer_plugin.dir/all] Error 2
[ 72%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/embLayerNormPlugin/embLayerNormKernel.cu.o
3)
[ 74%] Linking CXX static library ../out/libnvinfer_plugin_static.a
[ 74%] Built target nvinfer_plugin_static
make: *** [Makefile:169: all] Error 2

**Comment by lix19937** [comment]
> /usr/bin/ld: CMakeFiles/nvinfer_plugin.dir/batchTilePlugin/batchTilePlugin.cpp.o: relocation R_X86_64_PC32 against symbol `_ZN8nvinfer16plugin22BatchTilePluginCreator3mFCE' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value  

recompile with `-fPIC`
