### ISSUE TITLE
TensorRT 10 Availability in NGC PyTorch Container

### ISSUE THREAD

**Issue by david-PHR** [NVIDIA/TensorRT#3796]
Hello,

TensorRT 10 has been rolled out and that's great news as it comes with a lot of nice features! However, this version is not available in NGC PyTorch :/
I am reaching out to inquire about the plans for integrating TensorRT 10 into the NVIDIA GPU Cloud (NGC) PyTorch container.

Could you please provide any available information or timeline regarding when TensorRT 10 might be expected to be available in the NGC PyTorch container?

Thanks a lot !

**Comment by zerollzeng** [comment]
Checking internally.

**Comment by zerollzeng** [comment]
TRT 10 will be in the 24.05 docker image.
