### ISSUE TITLE
Build engine failure of TensorRT 10.0 when running trtexec with fp16 on GPU NVIDIA 3060 series

### ISSUE THREAD

**Issue by roxanacincan** [NVIDIA/TensorRT#3800]
## Description

I tried building a TRT engine using trtexec and `fp16 precision`, but the process fails without any errors. The TRT model is never generated. For fp32 the TRT model is correctly generated.

## Environment

**TensorRT Version**: 10.0.0.6EA

**NVIDIA GPU**: NVIDIA GeForce RTX 3060

**NVIDIA Driver Version**: 551.86

**CUDA Version**: 11.8

**CUDNN Version**: 8.9.7

Operating System: Windows10

## Relevant Files

**Model link**: https://drive.google.com/file/d/1JjA_9Ea4oTf-jnn41pYOMolpWOGYoWay/view?usp=drive_link
**Build log**: [build.log](https://github.com/NVIDIA/TensorRT/files/14978993/build.log)

## Steps To Reproduce

**Commands or scripts**: `trtexec --onnx=best_model.onnx --saveEngine=best_model_fp16.plan --fp16 --verbose`
I also tried using the **build_engine.py** script from the python samples directory of TensorRT10 but it returns exactly the same output as trtexec. No errors or warnings, just the process stopping abruptly.

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: yes

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): yes it can run with Polygraphy

**Comment by RajUpadhyay** [comment]
Can you trying running the command with additional option of --useCudaGraph.
`trtexec --onnx=model.onnx --saveEngine=engine_fp16.engine --fp16 --useCudaGraph --verbose`

**Comment by roxanacincan** [comment]
i tried using  the option --useCudaGraph, but there were no changes.
I was still not able to build the model even though i don't get any errors.
Also, the build log file looks the same as the previous one i uploaded: [build_with_useCudaGraph.log](https://github.com/NVIDIA/TensorRT/files/14987503/build_with_useCudaGraph.log)

**Comment by zerollzeng** [comment]
Just requested access to the model.

**Comment by zerollzeng** [comment]
Thanks for reporting this, filed internal bug 4609232 to track.

**Comment by akhilg-nv** [comment]
The bug for this issue has been fixed and should be included in the latest minor release, closing this issue.
