### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by Vincent9797** [NVIDIA/TensorRT#381]
Downloaded TensorRT on Windows 10 as per the instructions on https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html#installing-zip.

Got stuck on Step 5: "To verify that your installation is working you should open a Visual Studio Solution file from one of the samples, such as “Hello World” For TensorRT (sampleMNIST)" with the following error:

![image](https://user-images.githubusercontent.com/42912553/74510688-42c59380-4f3f-11ea-9658-c6c0426f1def.png)

**Comment by rmccorm4** [comment]
Hi,

I believe the key is this:

> you should open a Visual Studio Solution file from one of the samples

I don't have much experience with Windows / Visual Studio, but I think you can create a project with the `sample_mnist.vcxproj` file, and build the project for the sample in Visual Studio with the `sample_mnist.sln` solution file.

See these: 
1. https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project?view=vs-2019#using-msbuild-to-build-your-project
2. https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2019

@ttdd11 might have some experience with building these on Windows.

**Comment by ttdd11** [comment]
@rmccorm4 @Vincent9797 I'm not sure what the error you are referring to. You don't need to be running make from the command prompt to check the installation.

After downloading TensorRT open one of the samples in Visual Studio (there are project files within the directory you tried to run make in) and compile it. Choose the sample most closely related to what you are trying to do and it's pretty straight forward. After this, start modifying the sample to meet the requirements of your project. Make sense?

**Comment by rajeevsrao** [comment]
@Vincent9797 please try the new Windows build instructions (using Powershell) in the [Quickstart guide](https://github.com/NVIDIA/TensorRT#building-the-tensorrt-oss-components). Reopen this ticket if you see issues.

**Comment by vaibhav-OG** [comment]
@ayushgupta9198 
Please provide link.
