### ISSUE TITLE
tensorrt 10 Python package on https://pypi.ngc.nvidia.com

### ISSUE THREAD

**Issue by jchia** [NVIDIA/TensorRT#3811]
TensorRT 10.0 has been released for quite a while. The latest Python package from https://pypi.ngc.nvidia.com is only 10.0.0b6. Presumably the 'b' means beta. When will there be a 10.0 release of the Python package on https://pypi.ngc.nvidia.com?

**Comment by zerollzeng** [comment]
We just release TRT 10.0 GA today: https://pypi.org/project/tensorrt/
