### ISSUE TITLE
Can’t detect face when I convert PB to trt

### ISSUE THREAD

**Issue by tmyh123** [NVIDIA/TensorRT#382]
## Environment

**TensorRT Version**: 7
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 430
**CUDA Version**: 10
**CUDNN Version**: 7.6
**Operating System + Version**: Ubuntu  14.04

## Steps To Reproduce

my trained pb detection model can detect the face, but when i convert the pb to uff and then to the trt model, the trt model cannot detect any face for the same picture, but there is no error during the conversion. (C++)

**Comment by rmccorm4** [comment]
Hi,

Can you try tf2onnx to convert your TF model to ONNX, and then try ONNX parser?
```
tf2onnx <model, inputs, outputs, etc.> ... --output model.onnx

trtexec --explicitBatch --onnx=model.onnx --saveEngine=model.engine

# Test inference on model.engine
``` 

ONNX is a better supported path. This should work if your model doesn't contain plugins.

**Comment by rajeevsrao** [comment]
@tmyh123 please let us know if the ONNX workflow works for you, or provide the UFF repro case. Thanks.

**Comment by ttyio** [comment]
I will close this issue since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by AmirYeganesahab** [comment]
Using ONNX path to convert to TRT worked.
