### ISSUE TITLE
The issue of using TensorRT API for PTQ  in multi input models

### ISSUE THREAD

**Issue by xiao-lin-hub** [NVIDIA/TensorRT#3823]
Hello，I want to implement int8 quantization for a model with three inputs, but the following error occurred during calibration. I suspect that the calibrator may have written it incorrectly. Perhaps TensorRT does not support such multi input model quantization?
[04/25/2024-10:28:34] [TRT] [E] 1: [calibrator.cu::cuCalibrator::absTensorMax::146] Error Code 1: Cuda Runtime (invalid resource handle)
[04/25/2024-10:28:34] [TRT] [E] 1: [calibrator.cu::cuCalibrator::absTensorMax::146] Error Code 1: Cuda Runtime (invalid resource handle)
[04/25/2024-10:28:34] [TRT] [E] 1: [calibrator.cu::cuCalibrator::absTensorMax::146] Error Code 1: Cuda Runtime (invalid resource handle)
[04/25/2024-10:28:34] [TRT] [E] 1: [reformatRunner.cpp::nvinfer1::rt::cuda::ReformatRunner::execute::613] Error Code 1: Cuda Runtime (invalid resource handle)
[04/25/2024-10:28:34] [TRT] [E] 3: [engine.cpp::nvinfer1::rt::Engine::~Engine::307] Error Code 3: API Usage Error (Parameter check failed at: engine.cpp::nvinfer1::rt::Engine::~Engine::307, condition: mObjectCounter.use_count() == 1. Destroying an engine object before destroying objects it created leads to undefined behavior.
)
[04/25/2024-10:28:34] [TRT] [E] 2: [calibrator.cpp::nvinfer1::builder::calibrateEngine::1181] Error Code 2: Internal Error (Assertion context->executeV2(&bindings[0]) failed. )

**Comment by lix19937** [comment]
> Perhaps TensorRT does not support such multi input model quantization?

No, it support.

**Comment by xiao-lin-hub** [comment]
```
class Calibrator(trt.IInt8EntropyCalibrator):
    def __init__(self, stream, cache_file=""): 
        trt.IInt8EntropyCalibrator.__init__(self)
        self.stream = stream
        self.d_inputs = [cuda.mem_alloc(data.nbytes) for data in self.stream.calibration_data_dict.values()]
        self.cache_file = cache_file
        stream.reset()

    def get_batch_size(self):
        return self.stream.batch_size

    def get_batch(self, names):
        batch = self.stream.next_batch()
        if not batch:
            return None

        for idx, data in enumerate(batch.values()):
            cuda.memcpy_htod(self.d_inputs[idx], data)
    
        return [int(d_input) for d_input in self.d_inputs]

    def read_calibration_cache(self):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                logger.info("Using calibration cache to save time: {:}".format(self.cache_file))
                return f.read()

    def write_calibration_cache(self, cache):
        with open(self.cache_file, "wb") as f:
            logger.info("Caching calibration data for future use: {:}".format(self.cache_file))
            f.write(cache)
```
This is my Calibrator code, could you please give me some advice? I suspect it's a problem with the output of get_batch

**Comment by xiao-lin-hub** [comment]
@lix19937

**Comment by lix19937** [comment]
You can debug your function of `get_batch(self, names)`.

**Comment by zerollzeng** [comment]
Maybe you can just use polygraphy: https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert/01_int8_calibration_in_tensorrt

**Comment by xiao-lin-hub** [comment]
> You can debug your function of `get_batch(self, names)`.
> 
> The simplest method is to put multiple inputs into **continuous memory space**, so this can be seen as only one input.

I  agree with your point of view. Very fortunate, I solved the transformation of the multi input model using polygraphy.  Thank you very much ! !@zerollzeng

**Comment by xiao-lin-hub** [comment]
> Maybe you can just use polygraphy: https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert/01_int8_calibration_in_tensorrt

Thank you for your guidance. I have successfully completed my work.

**Comment by zerollzeng** [comment]
You are welcome, closing this.

**Comment by mydy2024** [comment]
> > Maybe you can just use polygraphy: https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/convert/01_int8_calibration_in_tensorrt
> 
> Thank you for your guidance. I have successfully completed my work.

I have encountered a similar issue as well. Could you please provide your email address so we can communicate in detail?
