### ISSUE TITLE
Result of  FP16 TensorRT model is NOT correct

### ISSUE THREAD

**Issue by AndreWanga** [NVIDIA/TensorRT#3827]
## Description

I tried to convert onnx to trt in FP16, the infering result of trt and onnx are so different

## Environment

**TensorRT Version**: 8.6

**NVIDIA GPU**: RTX 3070

**NVIDIA Driver Version**:  531.18

**CUDA Version**: 12.1

**CUDNN Version**:

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**: https://huggingface.co/BAAI/bge-reranker-large/tree/main

## Steps To Reproduce

 1. convert pytorch.bin to onnx:
 `optimum-cli export onnx -m bge-reranker-large output_bge --task text-classification --opset 17`
 2. convert onnx to trt:
 `trtexec --onnx=model.onnx --minShapes="input_ids":1x1,"attention_mask":1x1 --optShapes="input_ids":16x16,"attention_mask":16x16 --maxShapes="input_ids":32x32,"attention_mask":32x32 --fp16 --saveEngine=model.plan`
 3. use polygraphy to compare the results of onnx and trt model, the code is:

```
import tensorrt as trt
import numpy as np
from polygraphy.logger import G_LOGGER
G_LOGGER.module_severity = {'': G_LOGGER.VERBOSE}
from polygraphy.backend.onnxrt import OnnxrtRunner, SessionFromOnnx
from polygraphy.backend.trt import TrtRunner
from polygraphy.common import TensorMetadata
from polygraphy.comparator import Comparator, CompareFunc, DataLoader
from polygraphy.exception import PolygraphyException

data = TensorMetadata()
dtype = np.dtype(np.int32)
data.add('input_ids', dtype=dtype, shape=(4, 16))
data.add('attention_mask', dtype=dtype, shape=(4, 16))

data_loader = DataLoader(
    input_metadata=data
)
new_onnx_path = r"output_bge/model.onnx"
trt_path = r"output_bge/model.plan"
build_onnx_rt_session = SessionFromOnnx(new_onnx_path)
trt_logger = trt.Logger(trt.Logger.ERROR)
with open(trt_path, "rb") as f:
    engine_str = f.read()
deserialize_engine = trt.Runtime(trt_logger).deserialize_cuda_engine(engine_str)
runners = [
    OnnxrtRunner(build_onnx_rt_session),
    TrtRunner(deserialize_engine),
]

results = Comparator.run(runners, data_loader=data_loader)

success = True
compare_func = CompareFunc.simple(rtol={'': 5e-2}, atol={'': 5e-2})
success &= bool(Comparator.compare_accuracy(results, compare_func=compare_func))

if not success:
    raise PolygraphyException('FAILED')
```
4. result:
![捕获](https://github.com/NVIDIA/TensorRT/assets/114132971/4a4156e0-7a41-4e98-9bc2-1112d72f8090)

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by lix19937** [comment]
You can upload the full result img, see the result of ` Error Metrics: output` and `Relative Difference`

**Comment by lix19937** [comment]
You can upload the full result img, see the result of ` Error Metrics: output` and `Relative Difference`

**Comment by AndreWanga** [comment]
> You can upload the full result img, see the result of ` Error Metrics: output` and `Relative Difference`

[log.txt](https://github.com/NVIDIA/TensorRT/files/15137439/log.txt)

**Comment by lix19937** [comment]
Max abs diff is 1.0019.   

You can use  fp32 compare to see `max abs diff`        
```shell  
polygraphy run model.onnx --trt --onnxrt                   \
--trt-min-shapes input_ids:[1,1]   attention_mask:[1,1]    \
--trt-opt-shapes input_ids:[16,16] attention_mask:[16,16]  \
--trt-max-shapes input_ids:[32,32] attention_mask:[32,32]
```

then check fp16     
```shell
polygraphy run model.onnx --trt --onnxrt  --fp16           \
--trt-min-shapes input_ids:[1,1]   attention_mask:[1,1]    \
--trt-opt-shapes input_ids:[16,16] attention_mask:[16,16]  \
--trt-max-shapes input_ids:[32,32] attention_mask:[32,32]
```

**Comment by AndreWanga** [comment]
I check the FP32 model, and found out the same problem! So it meas the reason is not FP16. 
![捕获](https://github.com/NVIDIA/TensorRT/assets/114132971/16585fa8-21b9-4245-a1fd-aacccd862443)
please check this. FYI
@lix19937

**Comment by AndreWanga** [comment]
> use the follow, set the batch size is 4
> 
> ```shell
> polygraphy run model.onnx --trt --onnxrt                   \
> --trt-min-shapes input_ids:[1,1]   attention_mask:[1,1]    \
> --trt-opt-shapes input_ids:[16,16] attention_mask:[16,16]  \
> --trt-max-shapes input_ids:[32,32] attention_mask:[32,32]  \
> --input-shapes   input_ids:[4,4]   attention_mask:[4,4]
> ```

The result is still failed, same as my script @lix19937

**Comment by AndreWanga** [comment]
Is there any solution about this issue? FYI @lix19937 @zerollzeng

**Comment by lix19937** [comment]
Just fixed shape to debug   
```shell
polygraphy run model.onnx --trt --onnxrt                   \
--trt-min-shapes input_ids:[4,4]   attention_mask:[4,4]    \
--trt-opt-shapes input_ids:[4,4]   attention_mask:[4,4]  \
--trt-max-shapes input_ids:[4,4]   attention_mask:[4,4]  \
--input-shapes   input_ids:[4,4]   attention_mask:[4,4]
```

if not expected, compare each layer  
```shell   
polygraphy run model.onnx --trt --onnxrt --fp16 \
     --trt-outputs mark all \
     --onnx-outputs mark all
```

**Comment by AndreWanga** [comment]
> Just fixed shape to debug
> 
> ```shell
> polygraphy run model.onnx --trt --onnxrt                   \
> --trt-min-shapes input_ids:[4,4]   attention_mask:[4,4]    \
> --trt-opt-shapes input_ids:[4,4]   attention_mask:[4,4]  \
> --trt-max-shapes input_ids:[4,4]   attention_mask:[4,4]  \
> --input-shapes   input_ids:[4,4]   attention_mask:[4,4]
> ```
> 
> if not expected, compare each layer
> 
> ```shell
> polygraphy run model.onnx --trt --onnxrt --fp16 \
>      --trt-outputs mark all \
>      --onnx-outputs mark all
> ```

I try your cmd, using mark all, but error occur while running:
![屏幕截图 2024-05-28 152822](https://github.com/NVIDIA/TensorRT/assets/114132971/5889e88f-721e-499c-86e3-a0dfe495602b)

@lix19937

**Comment by AndreWanga** [comment]
could you please try to convert this bge model and compare the results? I try all the ways I know but cant fix this issue. I think maybe tensorrt cant handle this crossencoder model now. FYI @lix19937 @zerollzeng

**Comment by AndreWanga** [comment]
I use Tensorrt 10 and the issue has been dealed with, thanks for your time. @lix19937 @zerollzeng

**Comment by AndreWanga** [comment]
tensorrt 10 can handle this issue
