### ISSUE TITLE
load F.interpolate error

### ISSUE THREAD

**Issue by syshensyshen** [NVIDIA/TensorRT#383]
![image](https://user-images.githubusercontent.com/13030181/74702423-f59a3800-5244-11ea-97a7-53f1ef9a10c6.png)

**Comment by rmccorm4** [comment]
Hi @syshensyshen,

Please follow the issue template, post env info, steps to reproduce, etc. 

Also, please don't screenshot text, that makes it harder for other users with similar problems to find the thread. Just copy and paste the error text instead.
