### ISSUE TITLE
Unexpected exception _Map_base::at during of TensorRT 8.6.3 when running INT8-calibration on GPU RTX 4090

### ISSUE THREAD

**Issue by bernardrb** [NVIDIA/TensorRT#3837]
## Description

```
[05/02/2024-13:11:13] [TRT] [I] Starting Calibration.
[05/02/2024-13:11:13] [TRT] [I]   Post Processing Calibration data in 9.32e-07 seconds.
[05/02/2024-13:11:13] [TRT] [V] Assigning tensor scales: /image_encoder/backbone/stages.4/op_list.1/context_module/main/Concat_output_0 using /image_encoder/backbone/stages.4/op_list.1/context_module/main/Concat_output_0 [
[05/02/2024-13:11:13] [TRT] [E] 1: Unexpected exception _Map_base::at
```

We are trying to quantize a specific layer-type for an engine:
{trt.LayerType.CONVOLUTION : trt.DataType.INT8}

In the log.txt, we show that we identify and set the precision of layers with convolution type. In this way:
   

```
self.config.set_flag(trt.BuilderFlag.PREFER_PRECISION_CONSTRAINTS)

if layer.type in calibration.layers.keys():
                logger.debug(f"Found layer in calibration: {layer.type}, with type {layer.precision}")
                logger.debug(f"Setting layer {layer.name} to {calibration.layers[layer.type]}")
                self.network.get_layer(i).precision = calibration.layers[layer.type]
```

Our previous mixed-precision strategy when considering "blocks" of the network did not stumble upon this error. Only when we did mixed-precision based on the layer type.

## Environment

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
| 40%   32C    P8              7W /  450W |      11MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1469      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
```

Baremetal or Container (if so, version): tensorrt-24.0.3py

## Relevant Files

[log.txt](https://github.com/NVIDIA/TensorRT/files/15188855/log.txt)

**Comment by lix19937** [comment]
> [05/02/2024-13:11:13] [TRT] [I]   Post Processing Calibration data in 9.32e-07 seconds.  

You do ptq so little time ?   
How many calib data you prepare ?   
And calib data enter the `get_batch` api ?

**Comment by bernardrb** [comment]
No, the PTQ calibration usually takes around 40s. Here is an example log:

[2024-05-02_13-42-10.txt](https://github.com/NVIDIA/TensorRT/files/15210590/2024-05-02_13-42-10.txt)

Calibration data consists of 4500 images with a calibration batch size of 500.

In this case, we simply want to try to benchmark our model when we quantize only one type layer type at a time. In our case, Convolutional and Point-wise. We got these layer types from profiling the layers using trtexec, and then analysing the latency using trt-engine explorer.

I've linked a Google Drive folder https://drive.google.com/drive/folders/1MJAP7NDO7zzRJlUJFexpTcxKVWT9tnuP?usp=drive_link with the files that are concerned.

**Comment by zerollzeng** [comment]
I think you can calibrate without set the layer precision, just generate scale for all layers and get the calibration cache, then use the calibration cache, fallback some layers to FP32/FP16.

Or use QAT, you can control the layer precision with Q/DQ pairs explicitly.

**Comment by bernardrb** [comment]
> I think you can calibrate without set the layer precision, just generate scale for all layers and get the calibration cache, then use the calibration cache, fallback some layers to FP32/FP16.

I'm not sure if I am following. Our current approach is a modified version of the sample script: [https://github.com/NVIDIA/TensorRT/blob/release/10.0/samples/python/efficientdet/build_engine.py](url). 

If I want to control the precision of layers based on their type, can I use implicit quantization while setting layer precision as done in my code?
