### ISSUE TITLE
Non-exisiting commands in sampleInt8API README

### ISSUE THREAD

**Issue by spadacesco** [NVIDIA/TensorRT#3839]
## Description

The [sample INT8 API README](https://github.com/NVIDIA/TensorRT/tree/28733f0fdccde2967fed395b06ca491af3a561a9/samples/sampleINT8API) gives a walkthrough on how to setup the builder for INT8 Neural Network Quantization. Nevertheless, the examples refer to non-existing function calls (e.g setInt8Mode(true)). When following the rest of the example on "Configuring the builder to use INT8 without the INT8 calibrator"

## Environment

**TensorRT Version**: 10.0.0

**NVIDIA GPU**: NVIDIA GeForce RTX 3050 Ti Laptop GPU

**NVIDIA Driver Version**: 550

**CUDA Version**: 12.0

**CUDNN Version**: 8.9.7

Operating System: Ubuntu 22.04 LTS

Python Version (if applicable):  - 

Tensorflow Version (if applicable): - 

PyTorch Version (if applicable): - 

Baremetal or Container (if so, version): - 

## Relevant Files

https://github.com/NVIDIA/TensorRT/tree/28733f0fdccde2967fed395b06ca491af3a561a9/samples/sampleINT8API

## Steps To Reproduce

Follow the instructions [here](https://github.com/NVIDIA/TensorRT/tree/28733f0fdccde2967fed395b06ca491af3a561a9/samples/sampleINT8API) on `Configuring the builder to use INT8 without the INT8 calibrator` and it will not start to quantize to INT8. Especially the call `builder->setInt8Mode(true);` does not even exist.

**Comment by spadacesco** [comment]
Propesed a solution to this issue in https://github.com/NVIDIA/TensorRT/pull/3840

**Comment by zerollzeng** [comment]
Thanks, I'll check it internally.

**Comment by spadacesco** [comment]
Closed since changes are now merged, see [here](https://github.com/NVIDIA/TensorRT/pull/3845)
