### ISSUE TITLE
ERROR: UFFParser: Parser error: rpn_model/Reshpe_1/Reshape: Reshape: -1 dimension specified more than 1 time

### ISSUE THREAD

**Issue by hwh-hit** [NVIDIA/TensorRT#384]
I want to use maskrcnn with trt4, and I have modify the code in C++ and python according to trt4, I converted the keras h5 file to uff with uff 0.4 successfully, when run 
    `auto parsed = parser->parse(......);`
  rasied the error 
  `ERROR: UFFParser: Parser error: rpn_model/Reshpe_1/Reshape: Reshape: -1 dimension specified more than 1 time`,
the reason is here

```python
    def rpn_graph(feature_map, anchors_per_location, anchor_stride):
        shared = KL.Conv2D(512, (3, 3), padding='same', activation='relu',
            strides=anchor_stride, name='rpn_conv_shared')(feature_map)
        x = KL.Conv2D(2 * anchors_per_location, (1, 1), padding='valid',
            activation='linear', name='rpn_class_raw')(shared)
        x = KL.Permute((2,3,1))(x)
        rpn_class_logits = KL.Reshape((-1, 2))(x)      ######remove -1
        rpn_probs = KL.Activation(
            "softmax", name="rpn_class_xxx")(rpn_class_logits)
        x = KL.Conv2D(anchors_per_location * 4, (1, 1), padding="valid",
	    activation='linear', name='rpn_bbox_pred')(shared)
        x = KL.Permute((2,3,1))(x)
        rpn_bbox = KL.Reshape((-1, 4))(x)   
        return [rpn_class_logits, rpn_probs, rpn_bbox]

    def build_rpn_model(anchor_stride, anchors_per_location, depth):
        input_feature_map = KL.Input(shape=[depth, None, None], 
	    name="input_rpn_feature_map") 
        outputs = rpn_graph(input_feature_map, anchors_per_location, anchor_stride)
        return KM.Model([input_feature_map], outputs, `name="rpn_model")

    class XXXX():
        rpn_feature_maps = [P2, P3, P4, P5, P6]
        rpn = build_rpn_model(config.RPN_ANCHOR_STRIDE,
            len(config.RPN_ANCHOR_RATIOS), config.TOP_DOWN_PYRAMID_SIZE)
        layer_outputs = []  # list of lists
        for p in rpn_feature_maps:
            layer_outputs.append(rpn([p]))
```

who can help me with the tensorrt4 problem or modify the maskrcnn code,thans a lot .

**Comment by hwh-hit** [comment]
@rmccorm4  Any updates?

**Comment by rmccorm4** [comment]
Hi,

TensorRT 4 is quite old, and I'm not very familiar. But something may have been fixed for this since then.

Based on just the error:
```
ERROR: UFFParser: Parser error: rpn_model/Reshpe_1/Reshape: Reshape: -1 dimension specified more than 1 time
```

It looks accurate since you have -1 in more than one reshape in your sample.

Can you try using TRT 7? If not, then TRT 6?

**Comment by Ram-Godavarthi** [comment]
What version of tensorflow and object detection api must be used to to train and run the inference in TensorRT using sampleUffSSD.cpp script?

I want to use ssd inception v2 model.
standard model works perfectly. but not working with custom trained model.

So wanted to know the version to replicate the same.

I hope i get an answer.

I have posted in forums, github. and everywhere. but nobody responded.

**Comment by rajeevsrao** [comment]
@hwh-hit the original issue you reported is fixed as Ryan mentioned. Please confirm.

@Ram-Godavarthi please see Aasta's response on the forum here for details on re-training SSD-InceptionV2-COCO17 for TensorRT:
https://forums.developer.nvidia.com/t/how-to-retrain-ssd-inception-v2-coco-2017-11-17-from-the-tensorrt-samples/76851/15
Please create a separate ticket for any issues you encounter.
