### ISSUE TITLE
Only 3x3 conv can use 2:4 sparsity?

### ISSUE THREAD

**Issue by WeixiangXu** [NVIDIA/TensorRT#3849]
I use nsys to profile the resnet34.
<img width="687" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/23165645/f91b09be-2139-4fb1-9da3-0eb40289727c">

And I find that only 3x3 conv use 2:4 sparsity, while 1x1 conv does not. (Furthermore, I find that Linear in transformers also does **not** use sparsity.)

Why?

**Comment by nvpohanh** [comment]
TRT tries both sparse and dense tactics and choose a faster one. Based on our experiments, sparse conv kernels are faster than dense conv kernels if C and K are large enough (>256). Could you try increase C and K for the 1x1 Conv and see if sparse conv tactic is chosen?

3x3 Conv effectively increases the C by 9x so it favors sparse kernels.

**Comment by WeixiangXu** [comment]
> Could you try increase C and K for the 1x1 Conv

Thanks for your reply! 

Does C stand for C_in or C_out? And does K stands for kernel size? @nvpohanh

**Comment by nvpohanh** [comment]
Sorry, should have been clearer: C = C_in, K = C_out

**Comment by WeixiangXu** [comment]
thanks!
