### ISSUE TITLE
Not able to install tensorrt in python 3.12

### ISSUE THREAD

**Issue by manswad** [NVIDIA/TensorRT#3860]
## Environment

**TensorRT Version**:10.0.1

**NVIDIA GPU**:RTX 4060 Laptop

**NVIDIA Driver Version**:535.171.04

**CUDA Version**:12.2

**CUDNN Version**:9.1.1

Operating System:Ubuntu 24.04 LTS

Python Version (if applicable):3.12.3

Tensorflow Version (if applicable):2.16.1

PyTorch Version (if applicable):N/A

Baremetal or Container (if so, version):

## Steps To Reproduce

sudo apt install tensorrt (After doing all formalities)

## Traceback report

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  python3-libnvinfer : Depends: python3 (< 3.11) but 3.12.3-0ubuntu1 is to be installed
>  python3-libnvinfer-dispatch : Depends: python3 (< 3.11) but 3.12.3-0ubuntu1 is to be installed
>  python3-libnvinfer-lean : Depends: python3 (< 3.11) but 3.12.3-0ubuntu1 is to be installed
> E: Unable to correct problems, you have held broken package

s.

**Commands or scripts**:sudo apt install tensorrt

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:yes

**Comment by zerollzeng** [comment]
Looks like the required python version is not as new as the one your package manager provided, you can install tensorrt by using the deb package, and then install the python package manually.

**Comment by manswad** [comment]
> Looks like the required python version is not as new as the one your package manager provided, you can install tensorrt by using the deb package, and then install the python package manually.

I have now switched to windows and installed tensorflow 2.10. It works

**Comment by zerollzeng** [comment]
Glad to see that, can we close this?

**Comment by manswad** [comment]
> Glad to see that, can we close this?

Ya sure

**Comment by scottkerr-dataseer** [comment]
I have the same problem but would prefer to stay on Ubuntu.

**Comment by manswad** [comment]
> I have the same problem but would prefer to stay on Ubuntu.

Install miniconda3

> conda env create -n tf python=3.10
> conda activate tf
> conda config --add channels conda-forge
> conda config --set channel_priority flexible
> conda install cudatoolkit=12.3.2
> conda install cudnn=8.9
> pip install wheel
> pip install --upgrade tensorrt
> pip install --upgrade pip
> pip install tensorflow[and-cuda]


TensorFlow and TensorRT are now installed installed with GPU support.

Verify by:
> python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
