### ISSUE TITLE
Does the repo has some source code about NN Quantization(PTQ) of TensorRT?

### ISSUE THREAD

**Issue by pineforest2** [NVIDIA/TensorRT#3867]
I want to learn some details about quantization of TensorRT.

**Comment by lix19937** [comment]
ref https://on-demand.gputechconf.com/gtc/2017/presentation/s7310-8-bit-inference-with-tensorrt.pdf

**Comment by zerollzeng** [comment]
You may also want to check our developer guide.

**Comment by pineforest2** [comment]
@zerollzeng @lix19937 What should I do when I use TensorRT and the output is significantly different from what I expected? Thank you very much.
