### ISSUE TITLE
tensorrt version 7.x has more forward inference time than version 5.x

### ISSUE THREAD

**Issue by dtiny** [NVIDIA/TensorRT#387]
## Description

ubuntu16.04, cuda9, cudnn7, resnet caffemodel, 1080tigpu.
I upgrade tensorrt5.x code to 7.x. Testing with same image, same net model, same preprocess, But inference time cost was very different. 5.x cost about 8ms, 7.x cost about 400ms, What's the reason?

## Environment

**TensorRT Version**: 5.x and 7.0.0.11
**GPU Type**: 1080ti
**Nvidia Driver Version**: 410.79
**CUDA Version**: 9.0
**CUDNN Version**: 7.6
**Operating System + Version**: ubuntu16.04
c++

**Comment by rajeevsrao** [comment]
@dtiny can you please shed some light on your usecase. Perhaps a proxy model or description of the layers that are slow?

**Comment by ttyio** [comment]
I will close this issue since no response for more than 3 weeks, please reopen if you still have question, thanks!
