### ISSUE TITLE
Using PyTorch through ONNX

### ISSUE THREAD

**Issue by adeljalalyousif** [NVIDIA/TensorRT#3878]
The link to '4. Using PyTorch through ONNX.ipynb' in IntroNotebooks does not work.

**Comment by brb-nv** [comment]
Notebook being referred to is here: https://github.com/NVIDIA/TensorRT/tree/main/quickstart/IntroNotebooks

Preview doesn't work but code is definitely there. I'm also able to open it on github.dev here:
https://github.dev/NVIDIA/TensorRT/blame/main/quickstart/IntroNotebooks/4.%20Using%20PyTorch%20through%20ONNX.ipynb

Kindly use that to unblock yourself while investigate why the preview doesn't work.

**Comment by brb-nv** [comment]
The preview does work for me after a couple of attempts to reload. This seems to be a popular issue on Github:
https://github.com/jupyter/notebook/issues/3035

One of the proposed alternatives is to copy-paste the Github URL at http://nbviewer.jupyter.org/ which also works for me.

**Comment by adeljalalyousif** [comment]
thanks
