### ISSUE TITLE
What runtime will I use?

### ISSUE THREAD

**Issue by ForkedInTime** [NVIDIA/TensorRT#3898]
## Description

 I am doing the quickstart/Intronotebooks and while it's 3+ years old I am able to update the notebooks a bit on my own with some help. I noticed that no matter how much code I change, I cannot perform the runtime.
  

## Environment
[4. Using Pytorch through ONNX.txt](https://github.com/NVIDIA/TensorRT/files/15434370/4.Using.Pytorch.through.ONNX.txt)

**TensorRT Version**: 10.0.1

**NVIDIA GPU**: RTX 2080

**NVIDIA Driver Version**: 550.67

**CUDA Version**: 12.4

**CUDNN Version**: 12.3

Operating System:

Python Version (if applicable): 3.10.9

Tensorflow Version (if applicable): 2.16.1

PyTorch Version (if applicable):2.3.0+cu121

Baremetal or Container (if so, version): baremetal (laptop)

## Relevant Files

4. Using PyTorch through ONNX.ipynb  (change it from .txt to .ipynb)

**Model link**:
See attached notebook (from  quickstart/IntroNotebooks)

## Steps To Reproduce

0) Only one version of Tensorrt is installed.
1) After building resnet_engine_pytorch.trt  with trtexec I tried running the runtime.
2) Runtime failed because of the following: "05/24/2024-20:07:15] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReaderInitCommon::46] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 236, Serialized Engine Version: 237)"

Possible chatGPT explanation: "The error you're encountering suggests that there is a mismatch between the serialized engine version and the TensorRT runtime version. This can happen if there are multiple versions of TensorRT installed, or if the serialized engine was created with a different version than the runtime is using"

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: yes.

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Have not tried this yet.

**Comment by lix19937** [comment]
You should ensure that build and run the engine in the same enviroment.

**Comment by ForkedInTime** [comment]
Not entirely sure in what context is "ensure that build" and/or "engine in the same environment".  The environment as I understand it is the OS? If that's the case: Ubuntu 22.04 and using tensorrt in a virtual env. One tensorrt installed: 

`(tensorflow_env) ➜  Video2Speech git:(main) ✗ dpkg -l | grep nvinfer

ii  libnvinfer-dev                                              10.0.1.6-1+cuda12.4                                               amd64        TensorRT development libraries
ii  libnvinfer-dispatch-dev                                     10.0.1.6-1+cuda12.4                                               amd64        TensorRT development dispatch runtime libraries
ii  libnvinfer-dispatch10                                       10.0.1.6-1+cuda12.4                                               amd64        TensorRT dispatch runtime library
ii  libnvinfer-headers-dev                                      10.0.1.6-1+cuda12.4                                               amd64        TensorRT development headers
ii  libnvinfer-headers-plugin-dev                               10.0.1.6-1+cuda12.4                                               amd64        TensorRT plugin headers
ii  libnvinfer-lean-dev                                         10.0.1.6-1+cuda12.4                                               amd64        TensorRT lean runtime libraries
ii  libnvinfer-lean10                                           10.0.1.6-1+cuda12.4                                               amd64        TensorRT lean runtime library
ii  libnvinfer-plugin-dev                                       10.0.1.6-1+cuda12.4                                               amd64        TensorRT plugin libraries
ii  libnvinfer-plugin10                                         10.0.1.6-1+cuda12.4                                               amd64        TensorRT plugin libraries
ii  libnvinfer-vc-plugin-dev                                    10.0.1.6-1+cuda12.4                                               amd64        TensorRT vc-plugin library
ii  libnvinfer-vc-plugin10                                      10.0.1.6-1+cuda12.4                                               amd64        TensorRT vc-plugin library
ii  libnvinfer10                                                10.0.1.6-1+cuda12.4                                               amd64        TensorRT runtime libraries
ii  python3-libnvinfer                                          10.0.1.6-1+cuda12.4                                               amd64        Python 3 bindings for TensorRT standard runtime
ii  python3-libnvinfer-dev                                      10.0.1.6-1+cuda12.4                                               amd64        Python 3 development package for TensorRT standard runtime
ii  python3-libnvinfer-dispatch                                 10.0.1.6-1+cuda12.4                                               amd64        Python 3 bindings for TensorRT dispatch runtime
ii  python3-libnvinfer-lean                                     10.0.1.6-1+cuda12.4                                               amd64        Python 3 bindings for TensorRT lean runtime
(tensorflow_env) ➜  Video2Speech git:(main) ✗ 

`
FYI: TF 2.16.1 is not built with TRT (not using dockerized version with TF-TRT vs 2.15). If using dockerized version then the above works ok.

**Comment by zerollzeng** [comment]
> 1\. Runtime failed because of the following: "05/24/2024-20:07:15] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReaderInitCommon::46] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 236, Serialized Engine Version: 237)"

You may have TRT installed with python and system. basically it means more than 1 trt in your env.

**Comment by ForkedInTime** [comment]
> > 1. Runtime failed because of the following: "05/24/2024-20:07:15] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReaderInitCommon::46] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 236, Serialized Engine Version: 237)"
> 
> You may have TRT installed with python and system. basically it means more than 1 trt in your env.

Thank you. I cleaned out my system and indeed I had tensorrt 8.6 on base and 10.1.0 on my virtualenv.  I believe the linked libraries on my .bashrc pointed to 10.1. and I sourced my env correctly. In any event, I am only using 10.1 version now and it works ok.
