### ISSUE TITLE
Any particular reason int8 quantization is only supported on xl models?

### ISSUE THREAD

**Issue by qingswu** [NVIDIA/TensorRT#3899]
As the code checks, stable diffusion quantization only supports on SDXL models, does it work in SD1.4 or 1.5?

https://github.com/NVIDIA/TensorRT/blob/6d2fa4df7fa3e3f4bf5dd27586ba053b4ae57cd5/demo/Diffusion/utilities.py#L476

**Comment by brb-nv** [comment]
Hi, thanks for checking here. Looks like a few things have changed since and support has been added for SD1.5 in TensorRT Model Optimizer [here](https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main/diffusers). Please check that out.
