### ISSUE TITLE
nvinfer.dll 

### ISSUE THREAD

**Issue by Jasonfinish** [NVIDIA/TensorRT#390]
## Description

i run the sampleUffMNIST by VS2017 ,But it does not work ,and reports that can not find nvinfer.dll.
i want to kown somgthing about the Reason,thanks!

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 
**Nvidia Driver Version**: 411
**CUDA Version**: 10.0
**CUDNN Version**: 7.56
**Operating System + Version**: win10
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by jerryshih1106** [comment]
How did you solve this problem?!
