### ISSUE TITLE
TensorRT getBindingVectorizedDim API

### ISSUE THREAD

**Issue by Phoenix8215** [NVIDIA/TensorRT#3901]
## Description

halo,I wonder if getBindingVectorizedDim API is properly named,it only returns the index of vectorized buffer.So why not name it ```getBindingVectorizedIndex```.__When i first saw the code below(from ```samples/buffer.h```)__, I was puzzled for a long time.

```c
auto dims = context ? context->getBindingDimensions(i) : mEngine->getBindingDimensions(i);
            size_t vol = context || !mBatchSize ? 1 : static_cast<size_t>(mBatchSize);
            nvinfer1::DataType type = mEngine->getBindingDataType(i);
            int vecDim = mEngine->getBindingVectorizedDim(i);
            if (-1 != vecDim) // i.e., 0 != lgScalarsPerVector
            {
                int scalarsPerVec = mEngine->getBindingComponentsPerElement(i);
                dims.d[vecDim] = divUp(dims.d[vecDim], scalarsPerVec);
                vol *= scalarsPerVec;
            }
```
![图片](https://github.com/NVIDIA/TensorRT/assets/37546779/3f25cd37-86a7-4d70-8acb-053b4a9eac2a)

## Environment

![图片](https://github.com/NVIDIA/TensorRT/assets/37546779/df2ee7c0-3bb1-4170-8470-3803a3c83f08)

**Comment by zerollzeng** [comment]
It's deprecated, use `getTensorVectorizedDim()` instead.

The function name looks good to me.

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_cuda_engine.html#a9a8aae0d118d1c5dfe53e2bf24ffaf97

Dim is equal to "dimension index"(while Dims is different.)

**Comment by Phoenix8215** [comment]
i understand，thank you very much for your answers😬
