### ISSUE TITLE
INT8 engine have no efficient improvement on TensorRT 8.4 when running with GPU A100

### ISSUE THREAD

**Issue by yjiangling** [NVIDIA/TensorRT#3902]
Hi, @brb-nv , I have tried two ways to conduct int8 calibration and quantilize. First, I tried to use polygraphy in TensorRT API like this:

    polygraphy convert onnx_model/model.onnx \
        --trt-min-shapes xs:[1,1120] xlen:[1] \
        --trt-opt-shapes xs:[1,160000] xlen:[1] \
        --trt-max-shapes xs:[1,480000] xlen:[1] \
        --int8 \
        --data-loader-script data_loader.py \
        --calibration-cache entropy_calib.cache \
        --calib-base-cls IInt8EntropyCalibrator2 \
        --output trt_model/model-INT8.plan

And it succed finish the in8 calibration and generate the calibration cache file and the quantilized TensorRT engine. But the enige size is quite werid. It's 95M for IInt8MinMaxCalibrator and 106M for IInt8EntropyCalibrator2, Howevre, the original FP32 TensorRT engine size is 156M, Why the INT8 quantilized engine size is not 1/4 of the FP32 engine? What's more, I test the inference speed of this two engines, the INT8 engine nearly have no acceleration compared to FP32 engine. Although, the GPU memory usage have a little decrease (from 1681M to 1169M), but the GPU GPU utilization rate increase quite a lot (from 20% to 25%).

In order to confirm the test result, I use the trtexec tools to conduct the INT8 calibration and quantilization again, the calibration cache use the file generated with polygraphy API before, the code is displayed as below:

    trtexec \
        --onnx=onnx_model/model.onnx \
        --minShapes=xs:1x1120,xlen:1 \
        --optShapes=xs:1x160000,xlen:1 \
        --maxShapes=xs:1x480000,xlen:1 \
        --minShapesCalib=xs:1x1120,xlen:1 \
        --optShapesCalib=xs:1x160000,xlen:1 \
        --maxShapesCalib=xs:1x480000,xlen:1 \
        --workspace=10240 \
        --int8 \
        --calib=entropy_calib.cache \
        --saveEngine=trt_model/model-INT8.plan \
        --verbose \
        --buildOnly

And the result is the same as before. But when I use the trtexec tool to generate INT8 engine directly with no calibration, the file size become 51M. So, 1. Why the quantilized engine with calibration is muc large than the one without? Beacause there are much Q/DQ layers saved in it?  2. Why the INT8 quantilized engine is not 1/4 of the FP32 engine? 3. Why the INT8 engine have no efficient improvement compared with the FP32 engine? I'm looking forward to your help, thanks a lot!

**Comment by yjiangling** [comment]
@lix19937 May I have your help? Many thanks.

**Comment by lix19937** [comment]
> But when I use the trtexec tool to generate INT8 engine directly with no calibration, the file size become 51M.   

What is your trtexec generate INT8 engine cmd ? 

> 2. Why the INT8 quantilized engine is not 1/4 of the FP32 engine?   

Not all layers will run with int8, another way, some paras do not need quant, like int/bool.   

> 3. Why the INT8 engine have no efficient improvement compared with the FP32 engine?    

You can compare the layer-fusion-case and tactics choice by trtexec and trex.

**Comment by yjiangling** [comment]
> > But when I use the trtexec tool to generate INT8 engine directly with no calibration, the file size become 51M.
> 
> What is your trtexec generate INT8 engine cmd ?
> 
> > 2. Why the INT8 quantilized engine is not 1/4 of the FP32 engine?
> 
> Not all layers will run with int8, another way, some paras do not need quant, like int/bool.
> 
> > 3. Why the INT8 engine have no efficient improvement compared with the FP32 engine?
> 
> You can compare the layer-fusion-case and tactics choice by trtexec and trex.

Thank you for the help! The trtexec generate INT8 engine with calibration cmd are here (the engine size is 95M):

    trtexec \
        --onnx=onnx_model/model.onnx \
        --minShapes=xs:1x1120,xlen:1 \
        --optShapes=xs:1x160000,xlen:1 \
        --maxShapes=xs:1x480000,xlen:1 \
        --minShapesCalib=xs:1x1120,xlen:1 \
        --optShapesCalib=xs:1x160000,xlen:1 \
        --maxShapesCalib=xs:1x480000,xlen:1 \
        --workspace=10240 \
        --int8 \
        --calib=entropy_calib.cache \
        --saveEngine=trt_model/model-INT8.plan \
        --verbose \
        --buildOnly

And the trtexec generate INT8 engine without calibration cmd are here (the engine size is 51M):

    trtexec \
        --onnx=onnx_model/model.onnx \
        --minShapes=xs:1x1120,xlen:1 \
        --optShapes=xs:1x160000,xlen:1 \
        --maxShapes=xs:1x480000,xlen:1 \
        --workspace=10240 \
        --int8 \
        --saveEngine=trt_model/model-INT8.plan \
        --verbose \
        --buildOnly

And how to compare the layer-fusion-case and tactics choice by trtexec and trex? Is there any example? Thanks again for the help!

**Comment by lix19937** [comment]
> And how to compare the layer-fusion-case and tactics choice by trtexec and trex?  

Like follow    
```shell    
trtexec \
    --onnx=onnx_model/model.onnx   \
    --minShapes=xs:1x1120,xlen:1   \
    --optShapes=xs:1x160000,xlen:1 \
    --maxShapes=xs:1x480000,xlen:1 \
    --workspace=10240 \
    --int8            \
    --saveEngine=trt_model/model-INT8.plan \
    --verbose \
    --dumpProfile \
    --separateProfileRun  \
    --useSpinWait   \
    --dumpLayerInfo \
    --profilingVerbosity=detailed  \
    2>&1 | tee build-infer.log

```

The last part begin from line "=== Profile "    is the fusion-layer info

**Comment by lix19937** [comment]
> And how to compare the layer-fusion-case and tactics choice by trtexec and trex?  

Like follow    
```shell    
trtexec \
    --onnx=onnx_model/model.onnx   \
    --minShapes=xs:1x1120,xlen:1   \
    --optShapes=xs:1x160000,xlen:1 \
    --maxShapes=xs:1x480000,xlen:1 \
    --workspace=10240 \
    --int8            \
    --saveEngine=trt_model/model-INT8.plan \
    --verbose \
    --dumpProfile \
    --separateProfileRun  \
    --useSpinWait   \
    --dumpLayerInfo \
    --profilingVerbosity=detailed  \
    2>&1 | tee build-infer.log

```

The last part begin from line "=== Profile "    is the fusion-layer info

**Comment by yjiangling** [comment]
> > And how to compare the layer-fusion-case and tactics choice by trtexec and trex?
> 
> Like follow
> 
> ```shell
> trtexec \
>     --onnx=onnx_model/model.onnx   \
>     --minShapes=xs:1x1120,xlen:1   \
>     --optShapes=xs:1x160000,xlen:1 \
>     --maxShapes=xs:1x480000,xlen:1 \
>     --workspace=10240 \
>     --int8            \
>     --saveEngine=trt_model/model-INT8.plan \
>     --verbose \
>     --dumpProfile \
>     --separateProfileRun  \
>     --useSpinWait   \
>     --dumpLayerInfo \
>     --profilingVerbosity=detailed  \
>     2>&1 | tee build-infer.log
> ```
> 
> The last part begin from line "=== Profile " is the fusion-layer info

Thanks a lot for the detail descriptions. Maybe it depends on the GPU type, I change it to GTX 3080, get a reasonable result.
