### ISSUE TITLE
Is there any gpu memory difference when using different context in TensorRT 8.4.0.6 ?

### ISSUE THREAD

**Issue by Jsy0220** [NVIDIA/TensorRT#3907]
Hi, I have a further question about difference between `createExecutionContext` and `createExecutionContextWithoutDeviceMemory`,  Is there have any gpu memory difference when using the corresponding context ?

**Comment by lix19937** [comment]
An engine, on deserialization, allocates device memory to store the model weights. Since the serialized engine is almost all weights, its size is a good approximation to the amount of device memory the weights require.

An ExecutionContext uses two kinds of device memory:     
+ Persistent memory required by some layer implementations - for example, some convolution implementations use edge masks, and this state cannot be shared between contexts as weights are, because its size depends on the layer input shape, which may vary across contexts. This memory is allocated on creation of the execution context, and lasts for its lifetime.

+ Scratch memory, used to hold intermediate results while processing the network. This memory is used for intermediate activation tensors. It is also used for temporary storage required by layer implementations, the bound for which is controlled by IBuilderConfig::setMaxWorkspaceSize().

You may optionally create an execution context without scratch memory using ICudaEngine::createExecutionContextWithoutDeviceMemory() and provide that memory yourself for the duration of network execution. This allows you to share it between multiple contexts that are not running concurrently, or for other uses while inference is not running.

**Comment by lix19937** [comment]
> Is the total memory (Persistent + Scratch) the same no matter what execution context used (createExecutionContextWithoutDeviceMemory or createExecutionContext)？

Yes when you only use one ctx.

**Comment by Jsy0220** [comment]
okay, what if use more than one ctx ?

**Comment by lix19937** [comment]
For createExecutionContextWithoutDeviceMemory in multi-ctxs    
Persistent memorys in each ctx + the share memory between multiple contexts = total device memory

**Comment by Jsy0220** [comment]
okay, @lix19937  thank you

**Comment by HuangYison** [comment]
I have a question. If I want to manually allocate scratch memory for each context, how do I calculate the minimum size I need to apply for? @lix19937

**Comment by HuangYison** [comment]
I am using multithreading for parallel inference, but the inference time is still long. I consulted the documentation and found that the default memory application strategy for creating a context is KSTATIC, which will apply for the maximum size in all configuration files. Observing the running output, I found that when I set the batch of maxShapes to 128, 4150M of device memory will be allocated. If I create multiple threads, it will quickly exhaust the GPU's dedicated memory and then apply for shared memory. I think it is because the calculation on shared memory makes the entire inference very slow, so I want to know if I can calculate the actual memory size required?
My test environment is: GPU 4090 24G, 
TensorRT version 10.1
model: yolov8-seg, shape is 3x640x640
Thanks.

**Comment by HuangYison** [comment]
shape 32x3x640x640 with ~1G memory allocated per context
![image](https://github.com/user-attachments/assets/675ad42d-741b-42a0-bf09-d34a912141d5)

**Comment by lix19937** [comment]
> I have a question. If I want to manually allocate scratch memory for each context, how do I calculate the minimum size I need to apply for? @lix19937

ref https://github.com/NVIDIA/TensorRT/issues/3907#issuecomment-2135012117,  the minimum size = Persistent + Scratch    Scratch size maybe need do some experiment with multi size.

**Comment by lix19937** [comment]
For Scratch size, usually affects the choice of strategy.

**Comment by HuangYison** [comment]
> For Scratch size, usually affects the choice of strategy.  

ok, thanks. I will test it.

**Comment by HuangYison** [comment]
> > I have a question. If I want to manually allocate scratch memory for each context, how do I calculate the minimum size I need to apply for? @lix19937
> 
> ref [#3907 (comment)](https://github.com/NVIDIA/TensorRT/issues/3907#issuecomment-2135012117), the minimum size = Persistent + Scratch, Scratch size maybe need do some experiment with multi size.

I created execution context with `nvinfer1::ExecutionContextAllocationStrategy::kUSER_MANAGED` strategy, and tried to assign less device memory use `setDeviceMemoryV2`, but error happen,:
`IExecutionContext::setDeviceMemoryV2: Error Code 3: API Usage Error (Parameter check failed, condition: size >= expectedSize. setDeviceMemoryV2: The provided memory size is too small. Provided 1073741824, but expected at least 4351590400 bytes.)`
And 4351590400 bytes is the max size of profiles(128x3x640x640), which is the same as the returns of `getDeviceMemorySizeForProfileV2`

**Comment by lix19937** [comment]
getDeviceMemorySizeForProfileV2: The amount of device memory required by an [IExecutionContext](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/ExecutionContext.html#tensorrt.IExecutionContext). The return value depends on the **weight streaming budget** if enabled.

**Comment by lix19937** [comment]
You can disable the tactics of `CUBLAS, CUBLAS_LT, CUDNN` to decrease the mem use.  Another way, if use the share device ctx, you add mutex.

**Comment by HuangYison** [comment]
Thank you for you reply, does disabling these three tactics will degrade inference performance or accuracy? And what should I do to disabled these strategies? I'm not actually sure how to do that. Can you give a more detailed step-by-step or is there a section of the official documentation that include this part? Thank you.

**Comment by HuangYison** [comment]
I think i found it, but in tensorrt 10.1, it already disabled by default?
![image](https://github.com/user-attachments/assets/966c30f8-ae8c-47f2-8f4d-51de333f9e5a)

**Comment by lix19937** [comment]
Usually, not degrade inference performance or accuracy, you can compare.    

Follow code snippet is disable the tactis.   
```cpp 
// IBuilderConfig  config 
   
        TacticSources tacticSources = config.getTacticSources();        
        nvinfer1::TacticSources disabledTactics{0};
        
        {
          uint32_t sourceBit = 1U << static_cast<uint32_t>(nvinfer1::TacticSource::kCUBLAS);
          disabledTactics |= sourceBit;
        }
        
        {
          uint32_t sourceBit = 1U << static_cast<uint32_t>(nvinfer1::TacticSource::kCUBLAS_LT);
          disabledTactics |= sourceBit;
        }

        {
          uint32_t sourceBit = 1U << static_cast<uint32_t>(nvinfer1::TacticSource::kCUDNN);
          disabledTactics |= sourceBit;
        }

        tacticSources &= ~disabledTactics;
        config.setTacticSources(tacticSources);
```

include/NvInfer.h      
```h  
    //!
    //! \brief Set tactic sources.
    //!
    //! This bitset controls which tactic sources TensorRT is allowed to use for tactic
    //! selection.
    //!
    //! Multiple tactic sources may be combined with a bitwise OR operation. For example,
    //! to enable cublas and cublasLt as tactic sources, use a value of:
    //!
    //! 1U << static_cast<uint32_t>(TacticSource::kCUBLAS) | 1U <<
    //! static_cast<uint32_t>(TacticSource::kCUBLAS_LT)
    //!
    //! \see getTacticSources
    //!
    //! \return true if the tactic sources in the build configuration were updated.
    //!         The tactic sources in the build configuration will not be updated if the provided value is invalid.
    //!
    bool setTacticSources(TacticSources tacticSources) noexcept
    {
        return mImpl->setTacticSources(tacticSources);
    }
```

ref   
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a9e1d81e5a8bfeb38b86e22a66d5f836a

**Comment by HuangYison** [comment]
I have tried it, got the same result, the new engine which disabled these three policies use the same amount of memory for each context as the old engine, not less

**Comment by lix19937** [comment]
How did you generate the plan/engine file ?

**Comment by HuangYison** [comment]
Use trtexec command line and c++ api，the trtexec command is 
```
trtexec --onnx=v1-n-seg-dynamic.onnx --saveEngine=v1-n-seg-1-128-128.engine --memPoolSize=workspace:24G --tacticSources=-CUBLAS,-CUBLAS_LT,-CUDNN --minShapes=images:1x3x640x640 --optShapes=images:128x3x640x640 --maxShapes=images:128x3x640x640 --fp16 --verbose
```
C++ API is the same, just add the code snippet you posted to disable the tactis.

**Comment by HuangYison** [comment]
Hi, I see that the comments in your repository code are in Chinese, do you know Chinese? Is it ok for me to express my current problem in Chinese? Maybe I didn't express it accurately in English before.😊 @lix19937

**Comment by HuangYison** [comment]
我现在的目的是同时推理大量图片，输入由一张大图切片为多张小图获得，类似[SAHI切片推理库](https://github.com/obss/sahi)。
我最开始使用动态形状和批量推理，但是发现批量推理随着批大小的增长推理延时也线性增加，只有当批大小设到64以上会有稍明显的加速效果。
  因为批处理加速效果不好，所以又采用多线程多个context的方式并行推理，这样的问题是创建每个context所需的GPU内存太多，必须限制并发线程数量以防止GPU专用内存被耗尽后申请系统共享内存而导致推理变慢，所以我想尝试是否能减少创建每个context所需的内存，目前我测试的pt模型是yolov8实例分割模型，对于导出的最大尺寸为128x3x640x640的动态形状的engine，似乎使用该engine创建一个context所需的最小内存确实需要大约4g，无法减少它需要申请的GPU内存。

**Comment by HuangYison** [comment]
现在我尝试使用yolo-seg系列更小尺寸的模型，这可以显著减小所需的内存，另外我现在尝试使用固定batch静态形状的引擎，我使用trtexec对不同batch的引擎进行性能测试，测试结果对比我的程序的测试结果，我的延时比trtexec的慢了很多倍，运行trtexec时我发现不管batch是多少，16或256，GPU利用率都能到达70%-80%，而我的程序运行时GPU利用率只有个位数，我想知道是我使用批处理的方式有问题还是trtexec对推理做了特定的处理？我查看很多示例，批量推理似乎只需要自行构建符合批大小*单个输入大小的输入数据，然后传输给GPU计算就可以了，tensorrt计算时会自动进行批处理？还是我遗漏了什么。另外我查看了trtexec的源码，许多功能似乎是调用common包下的sampleXXX执行的，但由于代码太多了，我也不清楚实际是否trtexec做了特定处理。下面是我推理部分的代码：
```c++
// 更新实际bs
batch_size = images.size();
cout << endl << "当前批次大小为" << batch_size << endl;
 
// 创建当前context的cuda流
cudaStream_t temp_stream;
cudaStreamCreate(&temp_stream);

void* temp_buffers[3];
// GPU缓冲区内存申请
//cudaHostAlloc(&temp_buffers[IDX_INPUT], input_size * batch_size * sizeof(float), cudaHostAllocMapped); // 零内存 Host Pinned Memory CPU GPU都能访问
//cudaMallocHost(&temp_buffers[IDX_INPUT], input_size * batch_size * sizeof(float));
//cudaMallocHost(&temp_buffers[IDX_OUTPUT0], output0_size * batch_size * sizeof(float));
//cudaMallocHost(&temp_buffers[IDX_OUTPUT1], output1_size * batch_size * sizeof(float));
cudaMalloc(&temp_buffers[IDX_INPUT], input_size * batch_size * sizeof(float));
cudaMalloc(&temp_buffers[IDX_OUTPUT0], output0_size * batch_size * sizeof(float));
cudaMalloc(&temp_buffers[IDX_OUTPUT1], output1_size * batch_size * sizeof(float));

//context->setOptimizationProfileAsync(0, temp_stream); // 默认选择0
// 设置输入输出Tensor地址以及形状
context->setTensorAddress("images", temp_buffers[IDX_INPUT]);
context->setTensorAddress("output0", temp_buffers[IDX_OUTPUT0]);
context->setTensorAddress("output1", temp_buffers[IDX_OUTPUT1]);
// dynamic 需要 explicit batch
context->setInputShape("images", nvinfer1::Dims4(batch_size, input_c, input_h, input_w));

// 创建临时缓存输出（接收）
vector<float> output0_data(output0_size * batch_size);
vector<float> output1_data(output1_size * batch_size);
//output0_data.resize(output0_size * batch_size);
//output1_data.resize(output1_size * batch_size);

int64 start = cv::getTickCount();
vector<Mat> input_datas;
vector<float> factors;

// 预处理
tie(input_datas, factors) = batchPreProcess(images);

cout << "预处理：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;

int64 start1 = cv::getTickCount();

start = cv::getTickCount();
// 将分散的多个输入Mat数据分配到内存连续的区域中，以构建batch_size大小的输入数据匹配模型batch shape
vector<float> batch_input_data(input_size * batch_size);
for (int i = 0; i < input_datas.size();i++) {
	if (input_datas[i].isContinuous())
		//memcpy(batch_input_data.data() + i * input_size, input_datas[i].ptr<float>(), input_size * sizeof(float));
		cudaMemcpyAsync((float*)temp_buffers[IDX_INPUT] + i*input_size, input_datas[i].ptr<float>(), input_size * sizeof(float), cudaMemcpyHostToDevice, temp_stream); // 异步
}
cout << "内存分配：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;

start = cv::getTickCount();
//cudaMemcpyAsync(temp_buffers[IDX_INPUT], batch_input_data.data(), input_size * batch_size * sizeof(float) , cudaMemcpyHostToDevice, temp_stream);
//cudaMemcpy(temp_buffers[IDX_INPUT], batch_input_data.data(), input_size * batch_size * sizeof(float), cudaMemcpyHostToDevice); // 同步
cout << "H2D：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;
start = cv::getTickCount();

context->enqueueV3(temp_stream);
//context->executeV2(temp_buffers); // 同步
cout << "enqueue：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;
start = cv::getTickCount();

cudaMemcpyAsync(output0_data.data(), temp_buffers[IDX_OUTPUT0], output0_size * batch_size * sizeof(float), cudaMemcpyDeviceToHost, temp_stream);
//cudaMemcpy(output0_data.data(), temp_buffers[IDX_OUTPUT0], output0_size * batch_size * sizeof(float), cudaMemcpyDeviceToHost); // 同步
cout << "D2H 0：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl; // 不准确，会被enqueue后GPU计算影响，准确测量可以使用cudaEvent?

start = cv::getTickCount();
cudaMemcpyAsync(output1_data.data(), temp_buffers[IDX_OUTPUT1], output1_size * batch_size * sizeof(float), cudaMemcpyDeviceToHost, temp_stream);
//cudaMemcpy(output1_data.data(), temp_buffers[IDX_OUTPUT1], output1_size * batch_size * sizeof(float), cudaMemcpyDeviceToHost); // 同步
cout << "D2H 1：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;

cudaStreamSynchronize(temp_stream);

cout << "Latency is ：" << (cv::getTickCount() - start1) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;

start = cv::getTickCount();
// 后处理
vector<vector<InferResult>> results;
for (int i = 0; i < input_datas.size(); i++) {
	vector<float> output0(output0_data.begin() + i * output0_size , output0_data.begin() + (i + 1) * output0_size );
	vector<float> output1(output1_data.begin() + i * output1_size , output1_data.begin() + (i + 1) * output1_size );
	results.emplace_back(batchPostProcess(images[i], factors[i], output0, output1));

}
cout << "后处理：" << (cv::getTickCount() - start) / static_cast<float>(cv::getTickFrequency()) * 1000.f << "ms" << endl;

auto ret = cudaFree(temp_buffers[0]);
cudaFree(temp_buffers[1]);
cudaFree(temp_buffers[2]);
cout << std::this_thread::get_id() << ": GPU临时缓冲区显存释放" << ret << endl;

cudaStreamDestroy(temp_stream);
//cudaFree(&context);

return results;
```

**Comment by lix19937** [comment]
> 发现批量推理随着批大小的增长推理延时也线性增加，只有当批大小设到64以上会有稍明显的加速效果。   

It usually does not increase proportionally.

> 似乎使用该engine创建一个context所需的最小内存确实需要大约4g   

How did you get it ? 

https://github.com/NVIDIA/TensorRT/issues/3907#issuecomment-2277579658   Obviously, the code is not efficient enough.

If possible, would it be convenient to provide onnx file here ?

**Comment by HuangYison** [comment]
of course, here the onnx file: 
1. https://drive.google.com/file/d/1o1Ov6zqu6jgRx2390Bm6qqGLLh5IR08i/view?usp=sharing
2. https://drive.google.com/file/d/1T4ibSX9V8BsbzU0KLnGnPTPeKrIsoZ-D/view?usp=drive_link

**Comment by HuangYison** [comment]
> 似乎使用该engine创建一个context所需的最小内存确实需要大约4g

observed through the output like 
```
Allocated activation device memory of size xxxxx
[MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +xxx, now: CPU 0, GPU xxx(MiB)
``` 
For yolov8m-seg model with 128x3x640x640 input shape, the size is 4150M, and yolov8s-seg is about 60% of yolov8m-seg

>https://github.com/NVIDIA/TensorRT/issues/3907#issuecomment-2277579658 Obviously, the code is not efficient enough.

Yes, still testing, and is batch inference being used correctly in the code? How can i get the high GPU utilization like trtexec? Can you give me some suggestions, much appreciated.
