### ISSUE TITLE
Failing to install TensorRT 10 on Jetson Orin NX

### ISSUE THREAD

**Issue by talcs** [NVIDIA/TensorRT#3912]
## Description

I tried to install the new TensorRT version, which seemed to be successful. However, when running `/usr/src/tensorrt/bin/trtexec`, I still see the old version: `[TensorRT v8502]`.

-  I downloaded the new TensorRT version from [here](https://developer.nvidia.com/tensorrt/download/10x). Since it is Jetson (with JetPack) that uses Ubuntu, I tried to install one of the DEB packages from the JetPack list:

![image](https://github.com/NVIDIA/TensorRT/assets/17887687/2dd1c5de-dd19-4c36-95c8-9a1b506c4d13)

- The behavior was consistent for the 2 DEB packages:

  - When trying to install using `apt install`, I got an explicit error:
```
$ sudo apt install nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb
```

  - On the other hand, when trying to install using `dpkg -i`, it seemed to be successful. However, as stated at the beginning, nothing is actually installed and the **trtexec** version remains the old one:
```
$ sudo dpkg -i nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb 
(Reading database ... 162568 files and directories currently installed.)
Preparing to unpack nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb ...
Unpacking nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4 (1.0-1) over (1.0-1) ...
Setting up nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4 (1.0-1) ...
```

I later followed the instructions from [here](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html?_gl=1*1jblafb*_gcl_au*MzE0NjIwMDM0LjE3MTI1MTk1OTI.), but still have errors:

```
$ sudo cp /var/nv-tensorrt-local-repo-l4t-10.0.1-cuda-12.4_1.0-1_arm64/*-keyring.gpg /usr/share/keyrings/
$ sudo apt-get update
$ sudo apt-get install tensorrt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tensorrt : Depends: libnvinfer-samples (= 10.0.1.6-1+cuda12.4) but it is not going to be installed
            Depends: python3-libnvinfer-dev (= 10.0.1.6-1+cuda12.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

How can I make the new version work?

**Comment by lix19937** [comment]
Download `nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb` at local, then 
`sudo dpkg -i install nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb`

**Comment by zerollzeng** [comment]
> Download `nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb` at local, then
> `sudo dpkg -i install nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb`

No, `cross-aarch64` is for cross compilation, TRT is bundled with Jetpack on embedded platform for user. Please wait for the new JP release.

**Comment by zerollzeng** [comment]
Other usage is not verified by QA.

**Comment by lix19937** [comment]
> > Download `nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb` at local, then
> > `sudo dpkg -i install nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb`
> 
> No, `cross-aarch64` is for cross compilation, TRT is bundled with Jetpack on embedded platform for user. Please wait for the new JP release.

Yes, `cross-aarch64` is for cross compilation, I just means loacl/host machine to compile.

**Comment by ttyio** [comment]
closing since there is already answer in the thread, thanks all!

**Comment by krishnarajk** [comment]
Does tensorrt 10 will work with jetson orin nano jetpack 6?

**Comment by lix19937** [comment]
No, @krishnarajk   more to see  https://forums.developer.nvidia.com/t/upgrade-tensorrt-and-cuda-on-agx-orin-without-jetpack-6-0/280066

**Comment by quanfeifan** [comment]
> > > Download `nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb` at local, then
> > > `sudo dpkg -i install nv-tensorrt-local-repo-cross-aarch64-l4t-10.0.1-cuda-12.4_1.0-1_all.deb`
> > 
> > 
> > No, `cross-aarch64` is for cross compilation, TRT is bundled with Jetpack on embedded platform for user. Please wait for the new JP release.
> 
> Yes, `cross-aarch64` is for cross compilation, I just means loacl/host machine to compile.

not work, the same as [https://github.com/NVIDIA/TensorRT/issues/3912#issue-2322734647](url). Any more solutions?
