### ISSUE TITLE
Failed to predict bbox after calibrating mobilenetv1_ssd using trt v7.0.0.1

### ISSUE THREAD

**Issue by peyer** [NVIDIA/TensorRT#392]
## Description
After using trt v7.0.0.1(commit starting with 090231a) to calibrate mobilenet_v1_ssd (trained from VOC0712 train set), the calibrated tensorRT engine could not predict correct bboxes,
The calibration images I use are subset of VOC2007 validation set.
I found that the generate Calibration table only contain one sacle parameter for depthwise_convolution operator, did trt v7.0.0.1 return just one scale after computing KL divergence of depthwise_convolution operator?

## Environment

**TensorRT Version**: v7.0.0.1
**GPU Type**:  GTX1080
**Nvidia Driver Version**: 430
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu16.04

## Steps To Reproduce
1. git clone trt
2. download voc 
3. run sampleSSD (just modify the vgg17_ssd.caffemodel to mbnv1_ssd.caffemodel)

**Comment by rajeevsrao** [comment]
@peyer can you please attach the weights you used: `mbnv1_ssd.caffemodel`?

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
