### ISSUE TITLE
Does enqueueV3 require the stream synchronization before the call?

### ISSUE THREAD

**Issue by fortminors** [NVIDIA/TensorRT#3925]
I am reading the description of the [enqueueV3](https://github.com/NVIDIA/TensorRT/blob/release/10.0/include/NvInferRuntime.h#L3994) function, it states
```
Modifying or releasing memory that has been registered for the tensors before stream
synchronization or the event passed to setInputConsumedEvent has been being triggered results in undefined
behavior
```
Does that mean that after I preprocess my data, making it ready for the inference, I have to invoke cudaStreamSynchronize before I call enqueueV3?
I expect that I need **no** synchronization because all the preprocessing followed by inference is done asynchronously on the same cudaStream_t, however I just wanted to make sure that my understanding is correct and there will be no undefined behavior if I have no synchronization in this case

P.S. I am aware that I would need to cudaStreamSynchronize _after_ inference before I move data to host and get results

**Comment by lix19937** [comment]
Yes.

**Comment by lix19937** [comment]
> Does enqueueV3 require the stream synchronization before the call? #3925

No, if use the same stream from preprocess to infer.
