### ISSUE TITLE
what different about libmyelin? Do I need to link them all in my code?

### ISSUE THREAD

**Issue by jlygit** [NVIDIA/TensorRT#393]
what different about libmyelin: -lmyelin_compiler_static -lmyelin_executor_static -lmyelin_pattern_library_static -lmyelin_pattern_runtime_static

Do I need to link them all in my code?

**Comment by JingyuQian** [comment]
These are static libraries. Only when you want a static link will you need to link them. Otherwise, dynamic link is enough: `-lmyelin`
