### ISSUE TITLE
Inference example for latest tensorrt 10.1

### ISSUE THREAD

**Issue by aliencaocao** [NVIDIA/TensorRT#3931]
## Description
The example in https://github.com/NVIDIA/TensorRT/blob/release/10.0/quickstart/IntroNotebooks/onnx_helper.py seem outdated as exec_async_v2 is gone and only v3 is there, but v3 does not have a binding argument. I am not sure how to run inference with the latest tensorrt python api.

## Environment

**TensorRT Version**: 10.0.1

**NVIDIA GPU**: RTX 3080Ti

**NVIDIA Driver Version**: r555

**CUDA Version**: 12.4

**CUDNN Version**: 9.1

Operating System: Windows 10

Python Version (if applicable): 3.9

**Comment by lix19937** [comment]
use `set_tensor_address`, `execute_async_v3`     
see https://github.com/NVIDIA/TensorRT/blob/release/10.0/demo/BERT/inference.ipynb

**Comment by aliencaocao** [comment]
Thanks
