### ISSUE TITLE
SD3 scripts and compatibility missing from release/sd3 branch

### ISSUE THREAD

**Issue by lxe** [NVIDIA/TensorRT#3939]
## Description

Following the [steps on huggingface](https://huggingface.co/stabilityai/stable-diffusion-3-medium-tensorrt#usage-example) requires `git checkout release/sd3` and then running `python3 demo/Diffusion/demo_txt2img_sd3.py` which is missing from this repo. 

Using demo_txt2img.py also shows that SD3 is not compatible:

```
demo_txt2img.py: error: argument --version: invalid choice: 'sd3' (choose from '1.4', '1.5', 'dreamshaper-7', '2.0-base', '2.0', '2.1-base', '2.1', 'xl-1.0', 'xl-turbo')
```

Can someone (@ttyio maybe) commit the necessary files?

**Comment by ttyio** [comment]
@rajeevsrao ^^

**Comment by deforum** [comment]
lol

**Comment by larsoncs** [comment]
watching

**Comment by ttyio** [comment]
@asfiyab-nvidia ^^

**Comment by asfiyab-nvidia** [comment]
The branch will be updated soon. I'll add the MR here as a comment when it's up for folks to track

**Comment by asfiyab-nvidia** [comment]
addressed by https://github.com/NVIDIA/TensorRT/pull/3942

**Comment by asfiyab-nvidia** [comment]
Closing as addressed in previous comment
