### ISSUE TITLE
plugin: there are no enqueued operations pending in this context prior to switching profiles

### ISSUE THREAD

**Issue by sunmac** [NVIDIA/TensorRT#394]
## Environment

**TensorRT Version**:7 
**GPU Type**: nvidia V100
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**Operating System + Version**: ubuntu `8.04
**Python Version (if applicable)**: 3.6

## Relevant Files
I write a plugin, but I found some issue which i don't know to solve it. 
[W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
When the code run, tensorrt will have a warning. I have found data not fully loaded in the GPU memory. I don't know how to solve it.

**Comment by xiazi-yu** [comment]
I also met, how to solve it？
