### ISSUE TITLE
api failure of TensorRT 10.0.1.6 when running trt_infer on GPU any

### ISSUE THREAD

**Issue by hch-baobei** [NVIDIA/TensorRT#3948]
## Description

--> [163](vscode-notebook-cell:?execution_count=4&line=163) input_names = list(filter(self.engine.binding_is_input, names))

AttributeError: 'tensorrt.tensorrt.ICudaEngine' object has no attribute 'binding_is_input'

## Environment

**TensorRT Version**:  10.0.1.6

**NVIDIA GPU**: A2

**NVIDIA Driver Version**: 12.2

**CUDA Version**:  11.7

new version use what api ?

**Comment by hch-baobei** [comment]
give me new document website, please. i not find

**Comment by lix19937** [comment]
ICudaEngine.binding_is_input() is removed; use ICudaEngine.get_tensor_mode()

**Comment by hch-baobei** [comment]
ok， thanks。 i try it。
