### ISSUE TITLE
ssd-sample on other model

### ISSUE THREAD

**Issue by PaulZhangIsing** [NVIDIA/TensorRT#395]
## Description

I followed the instructions on sample_ssd page and the model is able to run and the result is correct.
However, when i change the model to https://github.com/chuanqi305/MobileNet-SSD, and change its prototxt accordingly, it gives me the failed result.
May I know what I can do?

## Environment

**TensorRT Version**: 5.1.5.0 
**GPU Type**: TitanXP
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: ubuntu16.04
**Python Version (if applicable)**:2.7 
**TensorFlow Version (if applicable)**:NA 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
> it gives me the failed result.

Please provide more details. What is the full error traceback, etc.

**Comment by PaulZhangIsing** [comment]
It simply show this:
`&&&& RUNNING TensorRT.sample_ssd # ../../bin/sample_ssd [-h] $ $
[I] Begin parsing model...
[I] FP32 mode running...
[I] End parsing model...
[I] Begin building engine...
[I] End building engine...
[I] *** deserializing
`

**Comment by rajeevsrao** [comment]
@PaulZhangIsing please test with a more recent version of TensorRT (7.x) and let us know if this still fails.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
