### ISSUE TITLE
how to use use_int8_scale_max in bertQKVToContextPlugin? 

### ISSUE THREAD

**Issue by Andy0422** [NVIDIA/TensorRT#3951]
could someone explain the below introduction in bertQKVToContextPlugin README?
"Expose `use_int8_scale_max` plugin attribute (for versions 2 and 3 of the plugin). This allows users to enable/disable the usage of INT8 scale factors to optimize softmax MAX reduction.This optimization is applied always when `type_id==2` by default."

I just confused that how it works? How the scale factors can optimize the MAX reduction?

**Comment by lix19937** [comment]
For you ref    

```py
import numpy as np

def softmax(x):
   e_x = np.exp(x - np.max(x)) #  
   return e_x / np.sum(e_x, axis=0)   
```

If **x** is int8 type,  max(x_int8) is efficient than max(x_fp32) in gpu.     
```cpp
val_int8 = max(x_int8);
val_fp32 = val_int8 * scale;
``` 
equal  follow   

```cpp
x_fp32 = x_int8 * scale;
val_fp32 = max(x_fp32);
```

**Comment by lix19937** [comment]
For you ref    

```py
import numpy as np

def softmax(x):
   e_x = np.exp(x - np.max(x)) #  
   return e_x / np.sum(e_x, axis=0)   
```

If **x** is int8 type,  max(x_int8) is efficient than max(x_fp32) in gpu.     
```cpp
val_int8 = max(x_int8);
val_fp32 = val_int8 * scale;
``` 
equal  follow   

```cpp
x_fp32 = x_int8 * scale;
val_fp32 = max(x_fp32);
```

**Comment by lix19937** [comment]
For you ref    

```py
import numpy as np

def softmax(x):
   e_x = np.exp(x - np.max(x)) #  
   return e_x / np.sum(e_x, axis=0)   
```

If **x** is int8 type,  max(x_int8) is efficient than max(x_fp32) in gpu.  Please be aware of one thing：      
```cpp
val_int8 = max(x_int8);
val_fp32 = val_int8 * scale;
``` 
equal  follow   

```cpp
x_fp32 = x_int8 * scale;
val_fp32 = max(x_fp32);
```
