### ISSUE TITLE
TensorRT 10.1 and TensorRT 8.6 api update

### ISSUE THREAD

**Issue by hch-baobei** [NVIDIA/TensorRT#3954]
tensorrt.ICudaEngine.get_binding_index(tensor name:str)

The above is the usage before version 8.6. I want to know which API can be used in 10.1 to achieve the same effect. The warning in 8.6 suggests get_tensor_name, but after checking the API documentation, I found that it cannot be equivalently replaced.

Then I found that direct [] can be equivalent in 8.6, but an error is reported in 10.1.

so which API equivalent should I use in 10.1?

**Comment by lix19937** [comment]
No name-based equivalent replacement, you should use multi apis set.

**Comment by hch-baobei** [comment]
I checked the API documentation and it seems that I can only get a dict of index and name through **get_tensor_name**. Which APIs do you think can be used to achieve this?

**Comment by lix19937** [comment]
For you ref   
```python 
    for i in range(engine.num_io_tensors):
        tensor_name = engine.get_tensor_name(i)
        size = trt.volume(engine.get_tensor_shape(tensor_name))
        dtype = trt.nptype(engine.get_tensor_dtype(tensor_name))
        
        ...
       # Append to the appropriate input/output list.
        if engine.get_tensor_mode(tensor_name) == trt.TensorIOMode.INPUT:
            ...
        else:
            ...
```

**Comment by RuiXing123** [comment]
Hello, I have encountered similar problems. I understand that it may be related to the new version of TensorRT. New versions of TensorRT may remove this API. Maybe a reduced version would work, but I haven't tried it yet. Have you solved the problem?
Thank you!
![微信图片编辑_20240724134346](https://github.com/user-attachments/assets/d3f1c798-bb50-4257-8923-e772202652b0)
