### ISSUE TITLE
Install Question

### ISSUE THREAD

**Issue by ZeroLelouch1205** [NVIDIA/TensorRT#3955]
If I want users to install our software without extra operation to install TensorRT and configuring environment variables. Because TensorRT is automatically installed and environment variables are configured during our software installation. What can I do to achieve this effect when packaging the installation package?

**Comment by lix19937** [comment]
Include all nvinfer related libraries in your pack libs.

**Comment by ttyio** [comment]
closing since there is answer, thanks all!
