### ISSUE TITLE
Question about TensorRT 8.6

### ISSUE THREAD

**Issue by Jsy0220** [NVIDIA/TensorRT#3971]
Hi, I have two question about TensorRT usage and adaption with cuda.
1. From [this link](https://developer.nvidia.com/nvidia-tensorrt-8x-download), it seems that TensorRT 8.6 is not adapted with cuda 12.4, but actually it can run in my test. So Is cuda 12.4 adapted to TensorRT 8.6.1.6 ?
2. For serialized engine, is `setBindingDimensions` time consuming ? There is a case that the input shape is dynamically changed, so it need to be called  before inference every time, does it affect real-time performance ？

Thank you！！

**Comment by lix19937** [comment]
> This TensorRT release supports CUDA®:
> [12.0 update 1](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.8](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.7 update 1](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.6 update 2](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.5 update 2](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.4 update 4](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.3 update 1](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.2 update 2](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.1 update 1](https://developer.nvidia.com/cuda-toolkit-archive)
> [11.0 update 1](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-whats-new-11Upd1)

**Comment by lix19937** [comment]
I think `setBindingDimensions` spends very little time.

**Comment by Jsy0220** [comment]
@lix19937 Thank you!!  And about Q1, I still have a question that I saw this 
<img width="1111" alt="WeChatWorkScreenshot_1f387d3f-a2dd-4f79-b09a-94eaf31165c2" src="https://github.com/NVIDIA/TensorRT/assets/6188672/de56085d-e589-44a5-99c8-46d878ce0fe9">
Does it mean that a higher cuda version which not in the supported list as above is also supported ？ like 12.4 ?

**Comment by lix19937** [comment]
I think cuda12.4 will support trt8.6. @Jsy0220

**Comment by Jsy0220** [comment]
@lix19937  okay. Thank you !!
