### ISSUE TITLE
ICudaEngine API error

### ISSUE THREAD

**Issue by hch-baobei** [NVIDIA/TensorRT#3973]
![image](https://github.com/NVIDIA/TensorRT/assets/75716695/86371064-499d-46c2-abb1-354f082f4f31)

I saw this in the API documentation, but when I actually used it I found
![image](https://github.com/NVIDIA/TensorRT/assets/75716695/2d1a77c3-cd65-46d3-9cb8-3941851ab20d)

**Comment by lix19937** [comment]
Can you upload your full code ?

**Comment by hch-baobei** [comment]
I am leaving my job now, thanks for your reply. Good luck
