### ISSUE TITLE
[Question] Is 'NonMaxSuppression' running on CPU?

### ISSUE THREAD

**Issue by jskimn** [NVIDIA/TensorRT#3977]
I am developing the inference module for Yolov7 using TensorRT 8 version.
**I wonder that "NonMaxSuppression" node is running on CPU, maybe I think so..**

When I tested my inference module based on TensorRT, the CPU usage reaches approximately 8-10%.
The module does not include any CPU operation to pre-process input image.

**Comment by lix19937** [comment]
`H2D`, `D2H`, `enqueue` will use cpu.

**Comment by jskimn** [comment]
> `H2D`, `D2H`, `enqueue` will use cpu.

Yes, I see that HostToDevice, DeviceToHost and enqueue use CPU.
**If so, NMS node is running on GPU?**

My test module includes only Enqueue and D2H.
In this case, my processor has 8~10% CPU usage. My CPU is a i5 processor as low tier.
Do you think that the CPU usage is normal case?

**Comment by lix19937** [comment]
> If so, NMS node is running on GPU?   

This depends on you, if you export this module to onnx, then run on gpu.  
CPU util also depends on your fps setting.

**Comment by jskimn** [comment]
Not TensorRT issue and I think that it depends on module architecture...
