### ISSUE TITLE
Slice mode attribute is not exposed to Python.

### ISSUE THREAD

**Issue by jxchenus** [NVIDIA/TensorRT#3979]
## Description

  slice has 4 attributes, but the `add_slice` function only takes the first 3, leaving out `mode`.  If the 4th input `fill_value` is specified, the following error is thrown:
  
  [sliceLayer.cpp::validate::190] Error Code 2: Internal Error (Assertion params.mode == SampleMode::kFILL || inputForms.size() <= 4 failed. Fill input should only be provided when SampleMode is kFILL)

## Environment

AWS p3.3xlarge

**TensorRT Version**: 10.0.1

**NVIDIA GPU**: Tesla V100-SXM2-16GB

**NVIDIA Driver Version**: 535.161.07

**CUDA Version**: 12.2

**CUDNN Version**:

Operating System:

Python Version (if applicable): Python 3.10.12

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

...
    ndim = input.rank()
    layer = default_trtnet().add_slice(
        input.trt_tensor,
        start=[0 for _ in range(ndim)],
        shape=[1 for _ in range(ndim)],  # unused dummy value
        stride=[1 for _ in range(ndim)]  # unused dummy value
    )

    # The stride is either:
    #   0 for dimensions of size 1 (i.e. shape(input, i) - 1 == 1 - 1 == 0) or,
    #   1 for dimensions of size > 1 since minimum(value >= 1, 1) == 1.
    stride_tensor = concat(
        [minimum((shape(input, i) - 1), 1) for i in range(ndim)])

    layer.set_input(2, expand_shape.trt_tensor)
    layer.set_input(3, stride_tensor.trt_tensor)
    if fill_value is not None:
        layer.set_input(4, fill_value.trt_tensor)
    return _create_tensor(layer.get_output(0), layer)
...

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: no

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by lix19937** [comment]
For you ref, Slice Fill mode       
```python 
in1 = network.add_input("input1", dtype=trt.float32, shape=(2, 2))
layer = network.add_slice(in1, start=(0, 0), shape=(3, 3), stride=(1, 1))
fill_constant = network.add_input("fill_constant", dtype=trt.float32, shape=())
layer.mode = trt.SampleMode.FILL
layer.set_input(4, fill_constant)
network.mark_output(layer.get_output(0))

inputs[in1.name] = np.zeros(shape=(2, 2))
inputs[fill_constant.name] = np.array([1.0])

outputs[layer.get_output(0).name] = layer.get_output(0).shape
expected[layer.get_output(0).name] = np.array([[0, 0, 1], [0, 0, 1], [1, 1, 1]])
```

**Comment by jxchenus** [comment]
That worked!  Thank you @lix19937 !

When you get a chance, can you take a look at [this one](https://github.com/NVIDIA/TensorRT-LLM/issues/1887) too?
