### ISSUE TITLE
where to download TRT5.1.5 on jetson

### ISSUE THREAD

**Issue by xiehaoina** [NVIDIA/TensorRT#40]
There is only TRT 5.1.5 for x86 in the official link  [NVidia Developer Zone](https://developer.nvidia.com/nvidia-tensorrt-5x-download). But I 'd like to build source code on  my xavier. Where can I get TRT 5.1.5 tar  on jetson?

**Comment by RAYKALI** [comment]
Did you redo the operating system?...I remember xaviar have TensorRT

**Comment by PeterHuang2015** [comment]
TRT on Jetson should be contained in JetPack, no specific source code for jetson platform released yet. https://devtalk.nvidia.com/default/topic/1039112/tensorrt/jetson-tx2-set-up-/
