### ISSUE TITLE
it takes a lot of time when i build a onnx model which consists of 75 convolutions?

### ISSUE THREAD

**Issue by jlygit** [NVIDIA/TensorRT#400]
hi,all
it takes a lot of time when i build a onnx model which consists of 75 convolutions?
about 6 mins.
Is there an optimized way here ?

**Comment by rtrobin** [comment]
I'm facing the same trouble too. How many nodes does your onnx model have? @jlygit

**Comment by rajeevsrao** [comment]
@jlygit 6mins for 75 convs is a bit excessive. If you can share the model, I can take a look. Thanks.

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
