### ISSUE TITLE
Does TensorRT support lora and controlnet togehter?

### ISSUE THREAD

**Issue by psc0606** [NVIDIA/TensorRT#4001]
## Description
Does TensorRT support lora and controlnet togehter? Anyone can help me? eg: both use lora-A and controlnet-B.

**Comment by lix19937** [comment]
ref 
https://github.com/NVIDIA/TensorRT/blob/release/10.1/demo/Diffusion/demo_controlnet.py     
https://github.com/NVIDIA/TensorRT/blob/release/10.1/demo/Diffusion/stable_diffusion_pipeline.py

**Comment by psc0606** [comment]
demo_controlnet.py not support lora, I change some code, but the final output image still lost lora effect.

**Comment by psc0606** [comment]
I found the solution already.
