### ISSUE TITLE
[Issue still exists in TRT 10.1] Fail to build the engine if input tensor number > 2^31 

### ISSUE THREAD

**Issue by dzzhang96** [NVIDIA/TensorRT#4004]
## Description

The release note of 10.0.1 mentioned that the issue “UNets with tensors containing >2^31 elements may fail during the engine building step” was fixed. However, my model (nnUNet) has 1x32x512x512x512 input and it still failed to build the engine in TRT 10.1.

## Environment

**TensorRT Version**: 10.1

## Relevant Files

**Model link**: I uploaded a dummy model for testing [here](https://drive.google.com/file/d/1Z1bmMM9Mw7V33vkar6_GmC674RN1YRlO/view?usp=drive_link).

**Comment by lix19937** [comment]
Similar case https://github.com/NVIDIA/TensorRT/issues/3815

**Comment by dzzhang96** [comment]
any updates? :)

**Comment by moraxu** [comment]
Closing in favor of https://github.com/NVIDIA/TensorRT/issues/4123
