### ISSUE TITLE
Error Code 3: API Usage Error (Parameter check failed ...

### ISSUE THREAD

**Issue by HSDai** [NVIDIA/TensorRT#4011]
## Description
I was trying to use polygraphy to convert onnx to trt engine and inferred with real data.
![image](https://github.com/user-attachments/assets/280c84e9-8ae1-4b80-a767-e42611b81876)

But, i got following, while the onnx is correct with same input data.
![image](https://github.com/user-attachments/assets/55bf92d0-fc7c-44bd-86fc-d7567a1c7d8d)

inference with onnx:
![image](https://github.com/user-attachments/assets/17598540-02e2-46d3-b960-091ea44f6da6)

## Environment
![image](https://github.com/user-attachments/assets/27b0910e-a8e7-40e4-a87f-b616078bfd7f)

![image](https://github.com/user-attachments/assets/09dc276c-6005-410a-a73e-06a2e962b583)

## Relevant Files
script and log:
[script_log.zip](https://github.com/user-attachments/files/16202169/script_log.zip)
onnx model:
https://1drv.ms/u/c/cdcf187fc1477b67/EQqe_fFytQJDrmKQiICofVgB1q48XUPHiqSXS0J-qoMo4g?e=9X21wi
## Steps To Reproduce
unzip script_log.zip
download gmllm_dynamic.onnx
python comparing_onnx.py
python comparing_trt.py

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:
no

**Can this model run on other frameworks?
yes, onnx is correct

**Comment by lix19937** [comment]
Runtime dimension does not satisfy any optimization profile. Check the each input shape within the valid range.  

`For input: layout_lrindex, failed to set shape to: (1, 107, 3)`  exceed the max shape.

**Comment by HSDai** [comment]
> Runtime dimension does not satisfy any optimization profile. Check the each input shape within the valid range.
> 
> `For input: layout_lrindex, failed to set shape to: (1, 107, 3)` exceed the max shape (1, 64, 3).

Thank you for your help, it's all my fault. _(:з」∠)_
