### ISSUE TITLE
[Performance and Inference Related Issue] Why trtexec inferencing time is much faster than my inferencing code?

### ISSUE THREAD

**Issue by huzaifahshamim** [NVIDIA/TensorRT#4015]
I have a slightly modified onnx YOLO model which I convert to .trt/.engine using trtexec. At the same time, I get inference results in the 3-5ms range.

When I try to use my own inferencing python script [https://elinux.org/Jetson/L4T/TRT_Customized_Example#OpenCV_with_PLAN_model] using the converted model, I get inference results around 10-12ms. Please advise

**Comment by lix19937** [comment]
What is your python script ?

**Comment by huzaifahshamim** [comment]
It is below: 

`import argparse
import cv2
import time
import numpy as np
import tensorrt as trt
import pycuda.autoinit
import pycuda.driver as cuda
import preprocessing_funcs as pp
import os

EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
TRT_LOGGER = trt.Logger(trt.Logger.INFO)

batch = 1
host_inputs  = []
cuda_inputs  = []
host_outputs = []
cuda_outputs = []
bindings = []


def Inference(engine, image_path):
    image = cv2.imread(image_path)
    image = pp.full_preprocess(image)

    np.copyto(host_inputs[0], image.ravel())
    stream = cuda.Stream()
    context = engine.create_execution_context()

    start_time = time.time()
    cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
    context.execute_v2(bindings)
    cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
    stream.synchronize()
    #print("execute times "+str(time.time()-start_time))
    execution_time = time.time() - start_time
    output = host_outputs[0]
    
    return output, execution_time


def PrepareEngine(engine_path):
    with open(engine_path, 'rb') as f:
        serialized_engine = f.read()

    runtime = trt.Runtime(TRT_LOGGER)
    engine = runtime.deserialize_cuda_engine(serialized_engine)

    # create buffer
    for binding in engine:
        size = trt.volume(engine.get_tensor_shape(binding)) * batch
        host_mem = cuda.pagelocked_empty(shape=[size],dtype=np.float32)
        cuda_mem = cuda.mem_alloc(host_mem.nbytes)

        bindings.append(int(cuda_mem))
        if engine.get_tensor_mode(binding)==trt.TensorIOMode.INPUT:
            host_inputs.append(host_mem)
            cuda_inputs.append(cuda_mem)
        else:
            host_outputs.append(host_mem)
            cuda_outputs.append(cuda_mem)

    return engine

def png_list():
    directory = '/my/code/testing_opt/Images4Inferencing/'
    # Initialize an empty list to store PNG files
    png_files = []

    for filename in os.listdir(directory):
        if filename.endswith('.png'):
            filepath = os.path.join(directory, filename)
            png_files.append(filepath)
    return png_files

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Inference using TensorRT engine")
    parser.add_argument("--engine_path", type=str, help="Path to the .engine file")
    args = parser.parse_args()
    engine = PrepareEngine(args.engine_path)
    outputs = []
    execution_times = []
    inf_images = png_list()
    for image_path in inf_images:
        print("Inf Image "+str(image_path))
        output, execution_time = Inference(engine, image_path)
        print("Each Inf Image Exdc Time "+str(execution_time))
        execution_times.append(execution_time)
        outputs.append(output)
    average_time = sum(execution_times) / len(execution_times)
    print("Average execution time: ", average_time)

    engine = []
`

**Comment by lix19937** [comment]
You need set warmup for cuda, and you should distinguish enqueue time, compute kernel time and wall time. Your time calc is E2E time.

**Comment by huzaifahshamim** [comment]
How do I set warmup for cuda?

And regarding the distinguishing, im assuming thats as simple as just having different start and end times? 

I understand where to time for enqueue time and I believe for compute kernel time it is timing 'context.execute_v2(bindings)' this solely. 

What do you mean by wall time?

**Comment by lix19937** [comment]
```
=== Explanations of the performance metrics ===   
Total Host Walltime: the host walltime from when the first query (after warmups) is enqueued to when the last query is completed.   
GPU Compute Time: the GPU latency to execute the kernels for a query.    
Total GPU Compute Time: the summation of the GPU Compute Time of all the queries. If this is significantly shorter than Total Host Walltime, the GPU may be under-utilized because of host-side overheads or data transfers.    
Throughput: the observed throughput computed by dividing the number of queries by the Total Host Walltime. If this is significantly lower than the reciprocal of GPU Compute Time, the GPU may be under-utilized because of host-side overheads or data transfers.    
Enqueue Time: the host latency to enqueue a query. If this is longer than GPU Compute Time, the GPU may be under-utilized.    
H2D Latency: the latency for host-to-device data transfers for input tensors of a single query.
D2H Latency: the latency for device-to-host data transfers for output tensors of a single query.
Latency: the summation of H2D Latency, GPU Compute Time, and D2H Latency. This is the latency to infer a single query.
```

**Comment by huzaifahshamim** [comment]
Thank you. Final Question, what did you mean by set warmup for cuda? How can I achieve that?

**Comment by lix19937** [comment]
Like follow    
```py

    for image_path in inf_images:
        _, _ = Inference(engine, image_path)  
```

then  do  

```py   
    for image_path in inf_images:
        print("Inf Image "+str(image_path))
        output, execution_time = Inference(engine, image_path)
        print("Each Inf Image Exdc Time "+str(execution_time))
        execution_times.append(execution_time)
        outputs.append(output)
    average_time = sum(execution_times) / len(execution_times)
    print("Average execution time: ", average_time)
```
