### ISSUE TITLE
WAR to enable inference for H/W that are not multiples of 16?

### ISSUE THREAD

**Issue by echosyy** [NVIDIA/TensorRT#4017]
"If building with Dynamic Shapes: ensure image height and width are not multiples of 16 for ONNX export and TensorRT engine build"

Can you explain why it can't be a multiple of 16? Thanks

**Comment by lix19937** [comment]
@echosyy  Can you provide full log ?

**Comment by echosyy** [comment]
@lix19937 yeah, it's the comments of function get_input_profile and get_sample_input from file:https://github.com/NVIDIA/TensorRT/blob/release/10.2/demo/Diffusion/models.py,  you can find this comments from line 904, line 948

we just wonder why? Can you explain why it ? Thanks

**Comment by lix19937** [comment]
@echosyy  You need to clarify follow points：    
+ Dynamic Shapes have two case 
  + image height and width are not multiples of 16 but multiples of 8, like 408, 968      
  + image height and width are multiples of 16   

+ Static Shapes have one case  
  + image height and width are multiples of 8    

> Can you explain why it can't be a multiple of 16?   

It can be multiple of 16, so it be multiple of 8, intentionally shaping the data into a non-16 multiple, run method-x   
When it not multiple of 16, but it be multiple of 8, still run method-x, Here we using one method to handle dynamic and static shapes.   

> WAR to enable inference for H/W that are not multiples of 16   

means `when H/W that are not multiples of 16, how to use current code to handle it.`

**Comment by echosyy** [comment]
@lix19937  Ah, got it, thank you!

**Comment by ttyio** [comment]
closing since this is solved, thanks all!
