### ISSUE TITLE
TensorRT 9.3 Custom plugins appear to be strangely time-consuming

### ISSUE THREAD

**Issue by demuxin** [NVIDIA/TensorRT#4018]
## Description

I implemented a TensorRT plugin and found the plugin to be particularly time-consuming.

I am compiling the plugin as a separate library and then calling it using the C++ api.

``` C++
void* plugin_handle{ builder->getPluginRegistry().loadLibrary(pluginlib_path_.c_str()) };
// or
void* plugin_handle{ runtime->getPluginRegistry().loadLibrary(pluginlib_path_.c_str()) };
```

I used cudaStreamSynchronize for synchronization in the begin of enqueue function,  and measured it to take about 165ms.

``` C++
int32_t NmsdetaIPluginV2DynamicExt::enqueue(PluginTensorDesc const* inputDesc, PluginTensorDesc const* outputDesc, void const* const* inputs, void* const* outputs, void* workspace, cudaStream_t stream) IS_NOEXCEPT
{
    time_point<system_clock> m_begin = system_clock::now();

    cudaStreamSynchronize(stream);

    printf("--->> plugin: %ld, %d\n", duration_cast<microseconds>(system_clock::now() - m_begin).count(), __LINE__);
    m_begin = system_clock::now();

   ...
}
```

How can I solve this issue? please offer me some advice.

## Environment

**TensorRT Version**: 9.3

**NVIDIA GPU**: GeForce RTX 3090

**NVIDIA Driver Version**: 535.183.01

**CUDA Version**: 12.2

**CUDNN Version**: 8.9.6

Operating System: ubuntu 22.04

**Comment by lix19937** [comment]
How about use follow function to timing  ?   
    
std::chrono::high_resolution_clock::now();

**Comment by demuxin** [comment]
Hi @lix19937 , The results are the same, it shouldn't be a problem with the timing.

Do you have any other suggestions?

**Comment by demuxin** [comment]
And I can offer plugin code. 

[NmsdetaIPluginV2DynamicExt.h.txt](https://github.com/user-attachments/files/16318998/NmsdetaIPluginV2DynamicExt.h.txt)
[NmsdetaIPluginV2DynamicExt.cpp.txt](https://github.com/user-attachments/files/16318999/NmsdetaIPluginV2DynamicExt.cpp.txt)

![image](https://github.com/user-attachments/assets/065841c7-01d8-43f2-8b61-5321fb520b4c)

**Comment by lix19937** [comment]
From your plugin.cpp,  
1, need not sync stream, just use cudaMemcpyAsync with your local pinned-host ptr(which open a disk file in Init phase)    
2, your method of timing the CUDAStreamSynchronize function is wrong, the time-consuming you get is not CUDAStreamSynchronize call used.   
CUDAStreamSynchronize() is a CUDA function used to synchronize device execution. This function will block the execution of host code until all previous asynchronous operations in the specified stream have been completed. This ensures that all previous device operations have been completed before continuing to execute the host code.
3, how about the time from net-in node to NmsDeta node ?  You can try to metric.

**Comment by demuxin** [comment]
Thanks @lix19937  , I know CUDAStreamSynchronize is not necessary, I just want to metric time-consuming of this plugin.

According to your statement, the 165ms is actually the elapsed time of the node before NmsDeta, right?

And how to measure the time from net-in node to NmsDeta node, or how to measure the elapsed  time of every node of model?

Thank you again for your prompt reply.

**Comment by lix19937** [comment]
Use follow code replace your enqueue impl.  
```cpp

int32_t NmsdetaIPluginV2DynamicExt::enqueue(PluginTensorDesc const* inputDesc, PluginTensorDesc const* outputDesc, void const* const* inputs, void* const* outputs, void* workspace, cudaStream_t stream) IS_NOEXCEPT{

return 0;
}
 
```

then use  trt cmd , and upload the build.log.   

```shell  
    ./trtexec --onnx=$ONNX_filename \
    --saveEngine=$ONNX_filename.plan \
    --verbose \
    --dumpProfile \
    --noDataTransfers \
    --useCudaGraph \
    --useSpinWait  \
    --separateProfileRun \
    2>&1 | tee -a build.log
```

**Comment by demuxin** [comment]
This is build.log.

[build.log](https://github.com/user-attachments/files/16326945/build.log)

**Comment by demuxin** [comment]
Thanks.

**Comment by demuxin** [comment]
Thanks.

**Comment by demuxin** [comment]
Hi @lix19937 , can `polygraphy run`  specific custom plugin?

**Comment by lix19937** [comment]
It support, by  ` --plugins `
