### ISSUE TITLE
TensorRT Explicit Quantization and Fallback to FP16

### ISSUE THREAD

**Issue by leimao** [NVIDIA/TensorRT#4021]
## Description

It seems that using `--fp16` without `--int8` in `trtexec` for ONNX models that have explicit QDQ nodes will NOT have engines fall back to use FP16 only?

Please try the ONNX models attached. Thanks.

[resnet_quantized_cifar10_modified.zip](https://github.com/user-attachments/files/16325334/resnet_quantized_cifar10_modified.zip)

**Comment by lix19937** [comment]
For explicit Q-DQ onnx, you must at least set `--int8` flag to build, because some layer,like zero point data type is int8(Int8 precision has been set for a layer or layer output).

**Comment by leimao** [comment]
Then we should throw user an error if `--int8` is not specified for a model that contains QDQ nodes.
Mathematically, we can still use FP32/16 kernels to compute the INT8 math.

**Comment by lix19937** [comment]
You can use QAT2PTQ to get calib table and un-qdq onnx, then use int8/fp16/fp32/fp8 what you want.

**Comment by leimao** [comment]
Thanks.
