### ISSUE TITLE
TRT results are inconsistent with TF

### ISSUE THREAD

**Issue by float123** [NVIDIA/TensorRT#403]
Hi，sorry to disturb you。I encountered a strange problem. I'm trying to use TRT to implement TF code. But after BiLSTM, some parameters of tensor are very different.
![lstm](https://user-images.githubusercontent.com/39334643/75654763-699ffb80-5c9b-11ea-962a-39d618e76693.jpg)

This is the code of TF7.0:
input (37, 75, 512), weight(640, 512), bias(512,)
![YV@U`Q)A~5LDFW@4O19EU_2](https://user-images.githubusercontent.com/39334643/75654953-d1eedd00-5c9b-11ea-9a95-692595c32865.png)

This is the code of TRT:
```python
n_input = 512
n_hidden = 128
lstm = network.add_rnn_v2(shuf0.get_output(0), 1, n_hidden, 75, trt.RNNOperation.LSTM)
lstm.direction = trt.RNNDirection.BIDIRECTION
zero_bias = np.zeros(n_hidden, dtype=np.float32)

for i in range(4):
    layer = i // 2  # 0 ,0 , 1 ,1
    iW = i % 2
    isW = True if iW == 0 else False
    param_name = 'lstm_o/bidirectional_rnn/{}/lstm_cell/'.format("fw" if layer % 2 == 0 else "bw")
    all_w = [w.transpose((1, 0)).reshape(-1) for w in
             np.split(np.split(params[param_name + 'kernel:0'], [n_input])[iW], 4, axis=1)]  # (640, 512)
    all_b = [w if isW else zero_bias for w in np.split(params[param_name + 'bias:0'], 4)]  # (512,)
    for t, w, b in zip(
            [trt.RNNGateType.INPUT, trt.RNNGateType.CELL, trt.RNNGateType.FORGET, trt.RNNGateType.OUTPUT],all_w, all_b):
        lstm.set_weights_for_gate(layer, t, isW, w)
        lstm.set_bias_for_gate(layer, t, isW, b)
```
![45{QK5@~4M(CCIA Z_%E@94](https://user-images.githubusercontent.com/39334643/75655047-fe0a5e00-5c9b-11ea-9270-901c04c9810e.png)
The tensor and weights from the previous steps are correct. So what's wrong

**Comment by rmccorm4** [comment]
Hi,

Please copy/paste the full Tensorflow code so I don't have to re-type all of the code, so I can reproduce the mismatch.

**Comment by float123** [comment]
@rmccorm4 ：
Hello，I have uploaded the code to github: [demo_trt](https://github.com/float123/demo_trt).I can't solve this problem.If can't download, please contact me again.Thank you。

**Comment by float123** [comment]
Hello，I completed the model. In fact, although bilstm is different, it can still get usable results.

**Comment by haiderasad** [comment]
having the same issue, output for lstm layer are incorrect in trt engine, any fix found?
