### ISSUE TITLE
How do I get the model to Inference in a 2:4 sparse manner in code?

### ISSUE THREAD

**Issue by laurenlong** [NVIDIA/TensorRT#4030]
I see that the developer documentation says that you can use `trtexec --sparsity` in a way that makes the model reason in an N:M sparsity. I'd like to implement the same effect in my code. 
I only see sparsity described in one place in the developer documentation, which is `config.set_flag(trt.BuilderFlag.SPARSE_WEIGHTS)`. But it didn't work when I added this statement to build the engine. There is no difference in the size of the models before and after. 
I want to know what would be the right way to turn on N:M sparsity in code. Thank you!
My TensorRT version is 8.4.0.11.

**Comment by lix19937** [comment]
First use **apex.contrib.sparsity** to prune the model, https://github.com/NVIDIA/apex/tree/master/apex/contrib/sparsity 
 
Then use `trtexec  --sparsity=spec`.

**Comment by laurenlong** [comment]
Thank you for your answer. I have a sparse model. I would like to know if using the command line `trtexec  --sparsity=enable` to produce engine is the same effect as using `config.set_flag(trt.BuilderFlag.SPARSE_WEIGHTS)` in the code to produce engine.

**Comment by lix19937** [comment]
Yes.

**Comment by laurenlong** [comment]
Thank you.

**Comment by ttyio** [comment]
closing since this is solved, thanks all!
