### ISSUE TITLE
disabling operation&layer fusion failure of TensorRT 10.2 when running BERT-large on GPU RTX3090

### ISSUE THREAD

**Issue by yoon5862** [NVIDIA/TensorRT#4033]
## Description

Is there a way to disable operation&layer fusion in TensorRT 10.2? Disabling operation fusion would be useful when I compare tensorrt and pytorch which not using operation fusion.

## Environment

**TensorRT Version**: 10.2.0 

**NVIDIA GPU**: RTX3090

**NVIDIA Driver Version**: 535.183.01

**CUDA Version**: 11.4

**CUDNN Version**: 8.9.7

Operating System:

Python Version (if applicable): 3.8

Tensorflow Version (if applicable):

PyTorch Version (if applicable): 2.1.0

**Comment by lix19937** [comment]
You can use polygraphy like follow:     

```shell  
 polygraphy run dynamic_identity.onnx --trt --trt-outputs mark all   
```

**Comment by yoon5862** [comment]
thank you for reply. Does running polygraphy create a tensorRT engine?

**Comment by lix19937** [comment]
Yes,  add ` --save-engine test.plan`

**Comment by yoon5862** [comment]
thank you for reply.
can I use polygraph like this code?
[https://github.com/NVIDIA/TensorRT/blob/main/tools/Polygraphy/examples/api/00_inference_with_tensorrt/build_and_run.py](url)

I want to attach the engine generated by  polygraphy to tensorRT-LLM.

**Comment by lix19937** [comment]
Yes.

**Comment by yoon5862** [comment]
Thank you for reply!
I will try with tensorRT-LLM.

**Comment by ttyio** [comment]
closing since this is solved, thanks all!
