### ISSUE TITLE
QAT MaxCalibrator

### ISSUE THREAD

**Issue by AnnaTrainingG** [NVIDIA/TensorRT#4043]
## Description
default calib is MaxCalibrator, so this code will never use in QAT?
https://github.com/NVIDIA/TensorRT/blob/4575799a91f67c060cd34212a9a27d0264460071/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L628

**Comment by lix19937** [comment]
It depends on https://github.com/NVIDIA/TensorRT/blob/4575799a91f67c060cd34212a9a27d0264460071/tools/pytorch-quantization/examples/torchvision/classification_flow.py#L247
