### ISSUE TITLE
How to implement LSQ using pytorch_quant

### ISSUE THREAD

**Issue by AnnaTrainingG** [NVIDIA/TensorRT#4045]
Hi, Are there any documents or recommendations available?
I've found the implementation of [LSQuantConv ](https://github.com/ZouJiu1/LSQplus/blob/master/quantization/lsqplus_quantize_V2.py) in PyTorch, but I'm unsure how to integrate it with quant_nn.QuantConv

**Comment by lix19937** [comment]
Current quant method is not learning scale(Or in other words, step_size) and zero_point, but directly taking the corresponding parameters from PTQ, So, QAT only learns weight. If want to support LSQ, need modify  `pytorch-quantization/pytorch_quantization/tensor_quant.py`  and  `pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py`.

**Comment by ttyio** [comment]
@AnnaTrainingG , could you move the question to https://github.com/NVIDIA/TensorRT-Model-Optimizer? there are more quantization experts. thanks!

**Comment by AnnaTrainingG** [comment]
@ttyio ok thanks
