### ISSUE TITLE
TensorRT 10.2.0 trtexec unknown software exception(0xc0000094)

### ISSUE THREAD

**Issue by sdml0** [NVIDIA/TensorRT#4046]
When I try to convert [this](https://github.com/VinatG/Still-SR-GUI/tree/main/ONNX_models) models to trt engine I get above windows exception or just silent termination after line "[TRT] Local timing cache in use. Profiling results in this builder pass will not be stored".

## Environment
**TensorRT Version**: 10.2.0
**NVIDIA GPU**: 4090
**NVIDIA Driver Version**: 556.12
Operating System: Windows 10

**Model link**: https://github.com/VinatG/Still-SR-GUI/tree/main/ONNX_models
**Commands or scripts**: trtexec --onnx=new_RealworldSR-DiffIRS2-GANx4-V2.onnx --shapes=input:1x3x480x640 --useCudaGraph --noDataTransfers --useSpinWait --builderOptimizationLevel=3
Models works fine via DirectML backend.

**Comment by lix19937** [comment]
Can you upload full log with  
```shell  
trtexec --onnx=new_RealworldSR-DiffIRS2-GANx4-V2.onnx --shapes=input:1x3x480x640 --useCudaGraph --noDataTransfers --useSpinWait --builderOptimizationLevel=3 --verbose  2>&1 |tee log   
```

**Comment by sdml0** [comment]
[log.zip](https://github.com/user-attachments/files/16478597/log.zip)

**Comment by lix19937** [comment]
FROM LOG, NO `trtexec unknown software exception(0xc0000094)`

**Comment by sdml0** [comment]
That time it just exits...
Lets try to get exception...

**Comment by sdml0** [comment]
[trtexec_240803_111303.zip](https://github.com/user-attachments/files/16478706/trtexec_240803_111303.zip)
This with exception. It was run via python's subprocess.run, maybe it matters...

**Comment by sdml0** [comment]
It seems exception occures only via python. Via pure cmd it just exits without producing result.

**Comment by sdml0** [comment]
I captured exit code of trtexec: -1073741676
And google that it's the hex value 0xC0000094 - Integer division by zero exception code on Windows.
When being run via cmd trtexec just terminates with error code without window about exception.

**Comment by lix19937** [comment]
@My trt8510 x86 env, passed, with the same cmd.

![image](https://github.com/user-attachments/assets/253d5158-2384-42d0-b9d2-9438dea51c56)

**Comment by lix19937** [comment]
My hardware as follow:  
```

[08/04/2024-09:40:58] [I] === Device Information ===
[08/04/2024-09:40:58] [I] Selected Device: NVIDIA RTX 2000 Ada Generation Laptop GPU
[08/04/2024-09:40:58] [I] Compute Capability: 8.9
[08/04/2024-09:40:58] [I] SMs: 24
[08/04/2024-09:40:58] [I] Compute Clock Rate: 2.115 GHz
[08/04/2024-09:40:58] [I] Device Global Memory: 8187 MiB
[08/04/2024-09:40:58] [I] Shared Memory per SM: 100 KiB
[08/04/2024-09:40:58] [I] Memory Bus Width: 128 bits (ECC disabled)
[08/04/2024-09:40:58] [I] Memory Clock Rate: 8.001 GHz
[08/04/2024-09:40:58] [I] 
[08/04/2024-09:40:58] [I] TensorRT version: 8.5.10
```

**Comment by lix19937** [comment]
Maybe you try to use tensorrt 8.5 or 8.6.

**Comment by lix19937** [comment]
Maybe you can try to use tensorrt 8.5 or 8.6.
