### ISSUE TITLE
how to use C++ to generate tensorrt engine and inference

### ISSUE THREAD

**Issue by Zerocheng001** [NVIDIA/TensorRT#4047]
how to use C++ to generate tensorrt engine and inference

**Comment by lix19937** [comment]
Foy you ref https://github.com/lix19937/trt-samples-for-hackathon-cn/blob/master/cookbook/04-BuildEngineByONNXParser/pyTorch-ONNX-TensorRT/C%2B%2B/main.cpp

**Comment by ttyio** [comment]
closing since this is already answer, thanks all!
