### ISSUE TITLE
python example of dynamic shape

### ISSUE THREAD

**Issue by lxl910915** [NVIDIA/TensorRT#405]
## Description
According to this [doc](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes), there are 4 steps:
1. creates a first network with dynamic input dimensions to act as a preprocessor for the model
2. Parses your model that expects a fixed size input to create a second network
3. Builds engines for both networks
4. Runs the first engine to resize the input with dynamic dimensions of the first network to a size that the second engine can consume. Uses the output of the first engine as the input of the second engine to run your real model.

We have 2 questions:
1. Does the second network must have a fix input?
2. If the second network must have a fix input, all data must resize to the fix input size by the first engine.Does it affect the precison?

https://devtalk.nvidia.com/default/topic/1072334/tensorrt/working-with-dynamic-shape-example-/post/5432967/?offset=4#5434458

**Comment by lxl910915** [comment]
Our python example works, so close it.

**Comment by rmccorm4** [comment]
Hi @lxl910915 ,

Can you clarify what you're asking here? 

In the sampleDynamicReshape you're asking about, the goal of the dynamic shape engine seem to be to reshape an input of any shape between (1, 1, 1, 1) and (1, 1, 56, 56) into an output of shape (1, 1, 28, 28), since that's the expected input shape of a fixed-shape MNIST model, as described in the README: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleDynamicReshape

This is just a sample, these are not the general requirements for any engine with dynamic shape. You can do all sorts of things with dynamic shape engines.

**Comment by lxl910915** [comment]
> Hi @lxl910915 ,
> 
> Can you clarify what you're asking here?
> 
> > Does the second network must have a fix input?
> 
> In the sampleDynamicReshape you're asking about, the goal of the dynamic shape engine seem to be to reshape an input of any shape between (1, 1, 1, 1) and (1, 1, 56, 56) into an output of shape (1, 1, 28, 28), since that's the expected input shape of a fixed-shape MNIST model, as described in the README: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleDynamicReshape
> 
> This is just a sample, these are not the general requirements for any engine with dynamic shape. You can do all sorts of things with dynamic shape engines.

We want to known if our MNIST model is dynamic shape model, does tensorrt support our dynamic shape MNIST model ?

**Comment by rmccorm4** [comment]
Hi @lxl910915 ,

Sorry for the delayed response. 

> We want to known if our MNIST model is dynamic shape model, does tensorrt support our dynamic shape MNIST model ?

Yes, as long as your dynamic shape model fits within the restrictions here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#rest_dynamic_shapes

Then you can create an optimization profile for your desired range of runtime dimensions, and specify the input binding dimensions at runtime

**Comment by rajeevsrao** [comment]
@lxl910915 have your questions been addressed? Any further clarifications?

**Comment by ttyio** [comment]
I will close this issue since no response for more than 3 weeks, please reopen if you still have question, thanks!
