### ISSUE TITLE
The results of ONNX and tensorRT inference are inconsistent in FP32 precision of TensorRT 8.6.1.6 when running mobilenetV3 on GPU 3080ti

### ISSUE THREAD

**Issue by rememberBr** [NVIDIA/TensorRT#4052]
## Description

I have a dynamic batch onnx model. I exported the FP32 dynamic batch "A.engine" file by modifying "TensorRT-release-8.6\samples\python\efficientnet\build_engine.py", and performed inference following the method in "TensorRT-release-8.6\samples\python\efficientnet\infer.py", and found that there were differences from the onnxruntime results.
Through the verification of "polygraphy run model.onnx --onnxrt --trt --save-engine=B.engine --onnx-outputs mark all --trt-outputs mark all --atol 1e-5 --rtol 1e-5 --verbose", it was found that a large number of nodes failed the verification. According to the information of other issues, after removing "mark all", the verification passed, and the result of B.engine was also consistent with onnxruntime. However, B.engine seemed to be a static model. When performing multi-batch inference in C++, it would prompt: "When using static shape model, number of images[256] must be less than or equal to the maximum batch[1]."
This has caused me trouble. The dynamic batch model exported through build_engine.py cannot ensure consistent results, while the results of polygraphy run are consistent when not including mark all, but the saved model is static.
Could you please tell me what I can do to solve my problem? I need a dynamic batch model and ensure consistent results. I may also perform FP16 and INT8 quantization later. Is the dynamic batch setting method in build_engine.py incorrect?
The onnx model I used and build_engine.py are attached. If you need more information, please let me know. 

## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: 3080ti

**NVIDIA Driver Version**: 531.61

**CUDA Version**: 12.1

**CUDNN Version**: 8.9

Operating System:

Python Version (if applicable): 3.9

PyTorch Version (if applicable): 2.2.2

## Relevant Files

[trt.zip](https://github.com/user-attachments/files/16506394/trt.zip)

## Steps To Reproduce

Export A.ngine by build_engine.py and compare the results of model.onnx and A.ngine, input np.zeros((1,1,96,96)).astype(np.float32)

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: No

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): yes

**Comment by lix19937** [comment]
Use `trtexec  --onnx=spec --minShapes=spec  --optShapes=spec   --maxShapes=spec  --saveEngine=spec` to export a engine which support dyanmic shape, then at run time use the right shape to infer, make sure your script is right, like set right rt shape when enqueueV3.

**Comment by rememberBr** [comment]
@lix19937 Thanks, after verification, the model derived using trtexec still has errors. My conversion command is: trtexec --onnx=model.onnx --saveEngine=A.engine --explicitBatch --minShapes=input_name:1x1x96x96  --optShapes=input_name:128x1x96x96 --maxShapes=input_name:256x1x96x96
I used tensorrt to simplify the inference code as follows:
`// load engine
std::ifstream file("test.engine", std::ios::binary | std::ios::ate);
std::streamsize size = file.tellg();
file.seekg(0, std::ios::beg);

std::vector<char> buffer(size);
std::vector<char> engineData;
if (file.read(buffer.data(), size)) {
    engineData = buffer;
}
nvinfer1::IRuntime* mRuntime = nvinfer1::createInferRuntime(mLogger);
nvinfer1::ICudaEngine* engine = mRuntime->deserializeCudaEngine(engineData.data(), engineData.size(), nullptr);
nvinfer1::IExecutionContext* context = engine->createExecutionContext();

// input data
const int batch = 1;
const int inputC = 1;
const int inputW = 96;
const int inputH = 96;
const int outputSize = 1000;
cv::Mat img = cv::Mat::zeros(inputW, inputH, CV_32F);
static float data[batch * inputW * inputH];
static float output[batch * outputSize];
for (int i = 0; i < batch; ++i)
{
    std::memcpy(data, img.data, img.total() * sizeof(float));
}

// infer
nvinfer1::Dims inputDims = nvinfer1::Dims4(batch, inputC, inputH, inputW);
context->setBindingDimensions(0, inputDims);

void* buffers[2];
cudaMalloc(&buffers[0], batch * inputC * inputH * inputW * sizeof(float));
cudaMalloc(&buffers[1], batch * outputSize * sizeof(float));

cudaStream_t mCudaStream;
cudaStreamCreate(&mCudaStream);
cudaMemcpyAsync(buffers[0], data, batch * inputC * inputH * inputW * sizeof(float), cudaMemcpyHostToDevice, mCudaStream);
context->enqueueV2(buffers, mCudaStream, nullptr);
cudaMemcpyAsync(output, buffers[1], batch * outputSize * sizeof(float), cudaMemcpyDeviceToHost, mCudaStream);
cudaStreamSynchronize(mCudaStream);

//ouput
for (int ib = 0; ib < batch; ++ib)
{
    float* parray = output + ib * outputSize;

    int maxIndex = 0;
    float maxValue = parray[0];
    for (size_t i = 1; i < outputSize; ++i) {
        if (parray[i] > maxValue) {
            maxValue = parray[i];
            maxIndex = i;
        }
    }
    auto class_label = maxIndex;
    auto confidence = maxValue;
    std::cout << class_label << " " << confidence << std::endl;
}`
As it turns out, the maximum confidence level for the onnxruntime output is 0.016116047, using the conversion command you provided, tensorrt is 0.0159527, and if you add the --explicitBatch option, the result is: 0.0159512. Both are different from the onnxruntime

**Comment by lix19937** [comment]
The AbsDiff `|0.016116047 - 0.0159527| = 0.000163347`, usually was considered acceptable.    
You can try to disable tf32 precision by `--noTF32 ` in your trtexec cmd.

**Comment by rememberBr** [comment]
@lix19937 Thank you very much for your reply.      The conclusions of the inference using car.jpg with the latest test are as follows:
![car](https://github.com/user-attachments/assets/eb6e011f-5a12-4caf-bbc3-b92dfe266ae6)

1.      The maximum confidence of ONNX is:0.23867662
2.      The result of trtexec is:0.2389581(AbsDiff=0.0002814)
3.      The result of trtexec with --noTF32 added is:0.23867595(AbsDiff=0.00000067)
4.      The result using the Python code provided is:0.23893227(AbsDiff=0.00025565）
5.      When the line "self.config.clear_flag(trt.BuilderFlag.TF32)" is added to the Python code, the result is 0.238675555 (AbsDiff=0.001‬).
6.      The model saved by Polygraphy has a result of 0.23867525 (AbsDiff=0.001‬), it may be that Polygraphy defaults to disabling TF32.

The problem has been mostly resolved, it can be determined that the larger error is caused by TF32, although there are slight differences in the results when using different tools with the same setting of noTF32, but it is very small.
If I want to perform FP16 or INT8 quantization in the future, can I also try to block more types to maintain accuracy as much as possible (but inference speed may be affected)?
Finally, do you have any recommended ways for quantization?  using Python's API?   C++'s API?   generating calib. cache first and then using trtexec? Or other methods?
