### ISSUE TITLE
Nothing is detected at INT8

### ISSUE THREAD

**Issue by Egorundel** [NVIDIA/TensorRT#4074]
## Description

What should I do if, with "pure" `INT8` precision, the resulting TensorRT Engine does not detect anything?

screen:
![Screenshot from 2024-08-12 14-57-00](https://github.com/user-attachments/assets/068a8f7e-9f5c-4e48-909c-e50a4870e4e0)

But if you make the precision `FP16+INT8`, then everything is fine?

screen:
![Screenshot from 2024-08-12 14-55-54](https://github.com/user-attachments/assets/76dc39b4-fb23-44a0-ba33-d1f4db897887)

I tested the YOLOv10. I used this INT8 Calibrator: https://github.com/Egorundel/int8_calibrator_cpp

## Environment

**TensorRT Version**: 8.6.1.6
**NVIDIA GPU**: RTX3060
**NVIDIA Driver Version**: 555
**CUDA Version**: 11.1
**CUDNN Version**: 8.0.6

Operating System:

Python Version (if applicable): 3.8

**Comment by lix19937** [comment]
If PTQ not work, use QAT.

**Comment by Egorundel** [comment]
@lix19937 After QAT, I should also perform the conversion to TensorRT Engine with INT8 accuracy and check the detection again, right?

**Comment by lix19937** [comment]
@Egorundel Yes. Usually, the accuracy of QAT models trained on PyTorch is generally not significantly different from that on TRT.
