### ISSUE TITLE
FP8 Convolution has no speedup versus FP16 on 4090 with TRT10.3

### ISSUE THREAD

**Issue by lishicheng1996** [NVIDIA/TensorRT#4081]
## Description
I tried FP8 ConvNet on 4090 with trt10.3, which have no speedup versus FP16. Profiling with nsys, it shows that,  with different HWC, the fp8 kernels' duration is nearly euqal to fp16 ones respectively.

nsys profile
FP8
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/5cfc32fe-de40-4bd4-a72d-aed12b547cff">
FP16
<img width="810" alt="image" src="https://github.com/user-attachments/assets/7f6847fa-b745-4eca-b5b6-44d3bebbde41">

As for minimal reproducible snippet, I create a network consists of only one Conv layer.  
[fp8conv_versus_fp16conv.tar.gz](https://github.com/user-attachments/files/16623032/fp8conv_versus_fp16conv.tar.gz)

The attached file above contains the pytorch network, fp16 onnx , fp8 onnx generated by modelopt, layerInfo and profileInfo of TRT engine. 
![image](https://github.com/user-attachments/assets/d578fb12-954e-40ac-b7c1-f15932668a89)
FP16 LayerInfo
![image](https://github.com/user-attachments/assets/1d6b32d5-180d-446b-b88b-8df07ecc5913)
FP8 LayerInfo
![image](https://github.com/user-attachments/assets/e254ff50-ac4c-4dc9-901f-7064272fd418)

## Environment

**TensorRT Version**: 10.3

**NVIDIA GPU**: RTX4090

**NVIDIA Driver Version**: 535.171.04 

**CUDA Version**: 12.4

**Modelopt Version**:  0.15.1

### Quantize to fp8 onnx
python -m modelopt.onnx.quantization --onnx_path fp16_simple_conv.onnx  --quantize_mode fp8 --output_path fp8_simple_conv.onnx
### Build engine and export info
trtexec --onnx=fp8_simple_conv.onnx --fp16 --exportLayerInfo=fp8_layer.json --exportProfile=fp8_profile.json --useCudaGraph --profilingVerbosity=detailed --stronglyTyped

**Comment by lishicheng1996** [comment]
> python -m modelopt.onnx.quantization --onnx_path fp16_simple_conv.onnx --quantize_mode fp8 --output_path fp8_simple_conv.onnx

I double-checked on L40s, and got 1.7 perf improvement on Conv kernel.  It seems like fp8mul_fp32acc and int8mul_fp32acc gemm kernel have double perf against fp16mul_fp16acc on L40s. While on RTX 4090, only int8mul_fp32acc gemm kernel have double perf against fp16mul_fp16acc.

**Comment by Graham1025** [comment]
> On L40S, I can see 1.9x perf improvement for the Conv kernel between FP8 and FP16.
> 
> My commands:
> 
> * `trtexec --onnx=fp16_simple_conv.onnx --fp16 --profilingVerbosity=detailed --dumpProfile --separateProfileRun --useCudaGraph --noDataTransfers --useSpinWait --dumpLayerInfo`
> * `trtexec --onnx=fp8_simple_conv.onnx --stronglyTyped --profilingVerbosity=detailed --dumpProfile --separateProfileRun --useCudaGraph --noDataTransfers --useSpinWait --dumpLayerInfo`
> 
> I will check 4090 if I can find one...

@nvpohanh hi, recently on thorU env, I use modelopt.onnx.quantize tools to do fp8 quantization，it turns out that，conv and matmul have beed quantized to fp8，while others ops are all fp32 dtype, which cause worse performance than fp16 trt version. Here is my quantization  code and trtexec command, could tell me why?

# quantizem (Do i need use high_precision_dtype="fp16"? )
   print("\nStarting FP8 quantization...")
    moq.quantize(
        args.onnx_path,
        calibration_data=calibration_data,
        quantize_mode='fp8',
        calibration_method=args.calibration_method,
        trt_plugins=[args.plugin_path],
        output_path=args.output_path,
        op_types_to_quantize = ["Gemm", "MatMul"],
        # disable_mha_qdq=True,
        enable_gemv_detection_for_trt=False,
        dq_only=False,
        high_precision_dtype="fp32",
        # mha_accumulation_dtype="fp32",
        log_level='DEBUG'
    )

#trtexec command (does this "--fp16" works here ?
/usr/src/tensorrt/bin/trtexec --onnx=xxx.onnx --saveEngine=xxx.trt --fp16 --fp8 --stronglyTyped
