### ISSUE TITLE
IR version changed from 6 to 10 by graphsurgeon 

### ISSUE THREAD

**Issue by coryschillaci** [NVIDIA/TensorRT#4091]
## Description

I have an onnx model with opset 11 and IR version 6. When I load it with graphsurgeon, I get the following strange behavior:

```
(Pdb) onnx.load(onnx_model_path).ir_version
6
(Pdb) gs.export_onnx(gs.import_onnx(onnx.load(onnx_model_path))).ir_version
10
```

That is if I import and export, the ir_version gets changed from 6 to 10. When I try to run `fold_constants()` on the imported graph I get an error like
```
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 10, max supported IR version: 8
```

## Environment

Running in docker with nvcr.io/nvidia/tensorrt:24.02-py3 base image
Model was generated by mmdeploy 1.3.1
I see the same behavior with either onnx-graphsurgeon==0.5.2 or ==0.3.27
onnx-runtime==1.12.1

**Comment by lix19937** [comment]
> Unsupported model IR version: 10, max supported IR version: 8   

You can try to down the ir_version to 8.
