### ISSUE TITLE
Does trtexec have a way to test the performance of the Triton Plugin?

### ISSUE THREAD

**Issue by Beatlesso** [NVIDIA/TensorRT#4099]
Here is an example of FlashAttention for manual_plugin in TensorRT-LLM.
I can use this Plugin for inference as normal with the following code
```
import ctypes
import os
from pathlib import Path
import numpy as np
import tensorrt as trt
from cuda import cudart
import torch
from collections import OrderedDict  # keep the order of the tensors implicitly
from typing import List
import math

def datatype_trt_to_torch(datatype_trt):
    # Cast TensorRT data type into Torch
    if datatype_trt == trt.float32:
        return torch.float32
    if datatype_trt == trt.float16:
        return torch.float16
    if datatype_trt == trt.int8:
        return torch.int8
    if datatype_trt == trt.int32:
        return torch.int32
    if datatype_trt == trt.bool:
        return torch.bool
    if datatype_trt == trt.uint8:
        return torch.uint8
    if datatype_trt == trt.DataType.FP8:
        return torch.float8_e4m3fn
    if datatype_trt == trt.bf16:
        return torch.bfloat16
    if datatype_trt == trt.int64:
        return torch.int64
    if datatype_trt == trt.int4:
        return None  # only torch.uint4 is supported
    return None


TRT_LLM_PLUGIN_NAMESPACE = 'tensorrt_llm'
LAYER_NAME = 'TritonFlashAttentionLayer'
FMHA_KERNEL_BLOCK_SIZE = 128
'''
dim_range=OrderedDict([
                       ('batch_size', [bs_range]),
                       ('num_heads', [self.num_heads]),
                       ('seq_len', [max_len_range]),
                       ('head_size', [self.head_size]),
                   ]))
'''
soFile = "lib/libtrt_llm_custom_plugins.so"
q_shape = [16, 8, 512, 64]
k_shape = [16, 8, 512, 64]
v_shape = [16, 8, 512, 64]

input_tensor_name = ['q', 'k', 'v']
device = "cuda:1"
# inference input data
dtype = torch.float32
query = torch.randn(*q_shape, dtype=dtype, device=device)
key = torch.randn(*k_shape, dtype=dtype, device=device)
value = torch.randn(*v_shape, dtype=dtype, device=device)

def getPlugin(num_heads: int, head_size: int, softmax_scale: float,
                       inputs: List[trt.ITensor]):
    plugin_creator = trt.get_plugin_registry().get_plugin_creator(
        'TritonFlashAttention', '1', TRT_LLM_PLUGIN_NAMESPACE)
    assert plugin_creator is not None
    pfc = trt.PluginFieldCollection([
        trt.PluginField("num_heads", np.array([num_heads], np.int32),
                        trt.PluginFieldType.INT32),
        trt.PluginField("head_size", np.array([head_size], np.int32),
                        trt.PluginFieldType.INT32),
        trt.PluginField("softmax_scale", np.array([softmax_scale], np.float32),
                        trt.PluginFieldType.FLOAT32),
        trt.PluginField("type_id", np.array([int(inputs[0].dtype)], np.int32),
                        trt.PluginFieldType.INT32)
    ])
    return plugin_creator.create_plugin("flash_attention", pfc)

def _load_triton_plugin_lib():
    plugin_lib = 'lib/libtrt_llm_custom_plugins.so'
    handle = ctypes.CDLL(plugin_lib, mode=ctypes.RTLD_GLOBAL)
    if handle is None:
        raise ImportError('TensorRT-LLM Triton Plugin is unavailable')
    handle.initOpenAiTritonPlugins.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
    handle.initOpenAiTritonPlugins.restype = ctypes.c_bool
    assert handle.initOpenAiTritonPlugins(
        None, TRT_LLM_PLUGIN_NAMESPACE.encode('utf-8'))

def run():
    _load_triton_plugin_lib()
    trtFile = Path("llm_flash.trt")
    logger = trt.Logger(trt.Logger.ERROR)
    trt.init_libnvinfer_plugins(logger, '')
    ctypes.cdll.LoadLibrary(soFile)
    if os.path.isfile(trtFile):
        with open(trtFile, "rb") as f:
            engine = trt.Runtime(logger).deserialize_cuda_engine(f.read())
        if engine == None:
            print("Failed loading engine!")
            return
        print("Succeeded loading engine!")
    else:
        builder = trt.Builder(logger)
        network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
        profile = builder.create_optimization_profile()
        config = builder.create_builder_config()
        config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)
        config.add_optimization_profile(profile) 
        q = network.add_input("q", trt.float32, q_shape)
        k = network.add_input("k", trt.float32, k_shape)
        v = network.add_input("v", trt.float32, v_shape)

        pluginLayer = network.add_plugin_v2([q, k, v], getPlugin(
            num_heads=q_shape[1], 
            head_size=q_shape[-1],
            softmax_scale=math.sqrt(q_shape[-1]),
            inputs=[q, k, v]
            ))
        output_tensor = pluginLayer.get_output(0)
        output_tensor.name = "attn"
        network.mark_output(output_tensor)
        engineString = builder.build_serialized_network(network, config)
        if engineString == None:
            print("Failed building engine!")
            return
        print("Succeeded building engine!")
        with open(trtFile, "wb") as f:
            f.write(engineString)
        engine = trt.Runtime(logger).deserialize_cuda_engine(engineString)

    context = engine.create_execution_context()
    tensor_name_list = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)]
    output_name = None                 
    for name in tensor_name_list:                                               # Print information of input / output tensors
        mode = engine.get_tensor_mode(name)
        data_type = engine.get_tensor_dtype(name)
        buildtime_shape = engine.get_tensor_shape(name)
        runtime_shape = context.get_tensor_shape(name)
        print(data_type, buildtime_shape, runtime_shape)
        if mode != trt.TensorIOMode.INPUT:
            output_name = name
        print(f"{'Input ' if mode == trt.TensorIOMode.INPUT else 'Output'}->{data_type}, {buildtime_shape}, {runtime_shape}, {name}")

    buffer = OrderedDict()                                                      # prepare the memory buffer on host and device
    for name in tensor_name_list:
        data_type = engine.get_tensor_dtype(name)
        runtime_shape = context.get_tensor_shape(name)
        buffer[name] = torch.empty(tuple(runtime_shape), dtype=datatype_trt_to_torch(data_type), device=device)

    # set runtime data, MUST use contiguous, it is a SERIOUS lesson
    buffer[input_tensor_name[0]] = query.contiguous().to(device)   
    buffer[input_tensor_name[1]] = key.contiguous().to(device)
    buffer[input_tensor_name[2]] = value.contiguous().to(device)                 

    for name in tensor_name_list:
        context.set_tensor_address(name, buffer[name].data_ptr())               # bind address of buffer to context

    context.execute_async_v3(0)                                                 # do inference computation
    cudart.cudaDeviceSynchronize()
    return buffer['attn']

if __name__ == "__main__":
    os.system("rm -rf *.trt")
    out = run()
    print(out.shape)
    print(out)
    print("Test all finish!")
```
When I use the trt engine generated from the above code and perform a performance test on trtexec, the following error is reported:
```
&&&& RUNNING TensorRT.trtexec [TensorRT v100300] # trtexec --loadEngine=/home/lyc/attn/model/llm_flash.trt --staticPlugins=/home/lyc/attn/lib/libtrt_llm_custom_plugins.so --setPluginsToSerialize --device=1 --fp16 --noDataTransfers --useCudaGraph --useSpinWait=true --profilingVerbosity=detailed --verbose --separateProfileRun --dumpLayerInfo --exportProfile=flash_attn_info.json --exportLayerInfo=flash_attn_layerInfo.json
[08/28/2024-03:25:56] [I] === Model Options ===
[08/28/2024-03:25:56] [I] Format: *
[08/28/2024-03:25:56] [I] Model: 
[08/28/2024-03:25:56] [I] Output:
[08/28/2024-03:25:56] [I] 
[08/28/2024-03:25:56] [I] === System Options ===
[08/28/2024-03:25:56] [I] Device: 1
[08/28/2024-03:25:56] [I] DLACore: 
[08/28/2024-03:25:56] [I] Plugins: /home/lyc/attn/lib/libtrt_llm_custom_plugins.so
[08/28/2024-03:25:56] [I] setPluginsToSerialize: 
[08/28/2024-03:25:56] [I] dynamicPlugins:
[08/28/2024-03:25:56] [I] ignoreParsedPluginLibs: 0
[08/28/2024-03:25:56] [I] 
[08/28/2024-03:25:56] [I] === Inference Options ===
[08/28/2024-03:25:56] [I] Batch: Explicit
[08/28/2024-03:25:56] [I] Input inference shapes: model
[08/28/2024-03:25:56] [I] Iterations: 10
[08/28/2024-03:25:56] [I] Duration: 3s (+ 200ms warm up)
[08/28/2024-03:25:56] [I] Sleep time: 0ms
[08/28/2024-03:25:56] [I] Idle time: 0ms
[08/28/2024-03:25:56] [I] Inference Streams: 1
[08/28/2024-03:25:56] [I] ExposeDMA: Disabled
[08/28/2024-03:25:56] [I] Data transfers: Disabled
[08/28/2024-03:25:56] [I] Spin-wait: Enabled
[08/28/2024-03:25:56] [I] Multithreading: Disabled
[08/28/2024-03:25:56] [I] CUDA Graph: Enabled
[08/28/2024-03:25:56] [I] Separate profiling: Enabled
[08/28/2024-03:25:56] [I] Time Deserialize: Disabled
[08/28/2024-03:25:56] [I] Time Refit: Disabled
[08/28/2024-03:25:56] [I] NVTX verbosity: 2
[08/28/2024-03:25:56] [I] Persistent Cache Ratio: 0
[08/28/2024-03:25:56] [I] Optimization Profile Index: 0
[08/28/2024-03:25:56] [I] Weight Streaming Budget: 100.000000%
[08/28/2024-03:25:56] [I] Inputs:
[08/28/2024-03:25:56] [I] Debug Tensor Save Destinations:
[08/28/2024-03:25:56] [I] === Reporting Options ===
[08/28/2024-03:25:56] [I] Verbose: Enabled
[08/28/2024-03:25:56] [I] Averages: 10 inferences
[08/28/2024-03:25:56] [I] Percentiles: 90,95,99
[08/28/2024-03:25:56] [I] Dump refittable layers:Disabled
[08/28/2024-03:25:56] [I] Dump output: Disabled
[08/28/2024-03:25:56] [I] Profile: Disabled
[08/28/2024-03:25:56] [I] Export timing to JSON file: 
[08/28/2024-03:25:56] [I] Export output to JSON file: 
[08/28/2024-03:25:56] [I] Export profile to JSON file: flash_attn_info.json
[08/28/2024-03:25:56] [I] 
[08/28/2024-03:25:56] [I] === Device Information ===
[08/28/2024-03:25:56] [I] Available Devices: 
[08/28/2024-03:25:56] [I]   Device 0: "NVIDIA GeForce RTX 4090" UUID: GPU-3ce4025a-5aad-9ea7-d98e-4ab6a726475f
[08/28/2024-03:25:56] [I]   Device 1: "NVIDIA GeForce RTX 4090" UUID: GPU-8a0ba840-c40d-abfb-7daf-00c6f5c0a5f7
[08/28/2024-03:25:56] [I]   Device 2: "NVIDIA GeForce RTX 4090" UUID: GPU-728c18a2-a470-f4d0-e71c-4e2f8914e2a2
[08/28/2024-03:25:56] [I]   Device 3: "NVIDIA GeForce RTX 4090" UUID: GPU-e7646b7d-4894-c827-d72f-60dbd9f20b50
[08/28/2024-03:25:56] [I]   Device 4: "NVIDIA GeForce RTX 4090" UUID: GPU-a8292b4d-e8e1-7cf8-7a51-6afa927afa61
[08/28/2024-03:25:56] [I]   Device 5: "NVIDIA GeForce RTX 4090" UUID: GPU-ede2e0fa-bf5f-b2ef-f2eb-becd84056ad5
[08/28/2024-03:25:56] [I]   Device 6: "NVIDIA GeForce RTX 4090" UUID: GPU-55365942-a88d-15e4-8770-91f7245f7cb1
[08/28/2024-03:25:56] [I]   Device 7: "NVIDIA GeForce RTX 4090" UUID: GPU-c224cb39-150a-d0f3-08b6-323f227e9125
[08/28/2024-03:25:56] [I] Selected Device: NVIDIA GeForce RTX 4090
[08/28/2024-03:25:56] [I] Selected Device ID: 1
[08/28/2024-03:25:56] [I] Selected Device UUID: GPU-8a0ba840-c40d-abfb-7daf-00c6f5c0a5f7
[08/28/2024-03:25:56] [I] Compute Capability: 8.9
[08/28/2024-03:25:56] [I] SMs: 128
[08/28/2024-03:25:56] [I] Device Global Memory: 24217 MiB
[08/28/2024-03:25:56] [I] Shared Memory per SM: 100 KiB
[08/28/2024-03:25:56] [I] Memory Bus Width: 384 bits (ECC disabled)
[08/28/2024-03:25:56] [I] Application Compute Clock Rate: 2.52 GHz
[08/28/2024-03:25:56] [I] Application Memory Clock Rate: 10.501 GHz
[08/28/2024-03:25:56] [I] 
[08/28/2024-03:25:56] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
[08/28/2024-03:25:56] [I] 
[08/28/2024-03:25:56] [I] TensorRT version: 10.3.0
[08/28/2024-03:25:56] [I] Loading standard plugins
[08/28/2024-03:25:56] [V] [TRT] Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
......
[08/28/2024-03:25:56] [V] [TRT] Registered plugin creator - ::Split version 1
[08/28/2024-03:25:56] [V] [TRT] Registered plugin creator - ::VoxelGeneratorPlugin version 1
[08/28/2024-03:25:56] [I] Loading supplied plugin library: /home/lyc/attn/lib/libtrt_llm_custom_plugins.so
[08/28/2024-03:25:56] [I] [TRT] Loaded engine size: 0 MiB
[08/28/2024-03:25:56] [V] [TRT] Local registry did not find TritonFlashAttention creator. Will try parent registry if enabled.
[08/28/2024-03:25:56] [E] [TRT] IPluginRegistry::getPluginCreator: Error Code 4: API Usage Error (Cannot find plugin: TritonFlashAttentiontensorrt_llm, version: 1, namespace:tensorrt_llm.)
[08/28/2024-03:25:56] [E] Error[1]: IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[08/28/2024-03:25:56] [E] Engine deserialization failed
[08/28/2024-03:25:56] [E] Got invalid engine!
[08/28/2024-03:25:56] [E] Inference set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v100300] # trtexec --loadEngine=/home/lyc/attn/model/llm_flash.trt --staticPlugins=/home/lyc/attn/lib/libtrt_llm_custom_plugins.so --setPluginsToSerialize --device=1 --fp16 --noDataTransfers --useCudaGraph --useSpinWait=true --profilingVerbosity=detailed --verbose --separateProfileRun --dumpLayerInfo --exportProfile=flash_attn_info.json --exportLayerInfo=flash_attn_layerInfo.json
```
This looks like it's not registering the plugin, but the python code above registers the plugin, is there a way to get trtexec to work as well?
Thank you very much.

**Comment by scuizhibin** [comment]
> Here is an example of FlashAttention for manual_plugin in TensorRT-LLM. I can use this Plugin for inference as normal with the following code
> 
> ```
> import ctypes
> import os
> from pathlib import Path
> import numpy as np
> import tensorrt as trt
> from cuda import cudart
> import torch
> from collections import OrderedDict  # keep the order of the tensors implicitly
> from typing import List
> import math
> 
> def datatype_trt_to_torch(datatype_trt):
>     # Cast TensorRT data type into Torch
>     if datatype_trt == trt.float32:
>         return torch.float32
>     if datatype_trt == trt.float16:
>         return torch.float16
>     if datatype_trt == trt.int8:
>         return torch.int8
>     if datatype_trt == trt.int32:
>         return torch.int32
>     if datatype_trt == trt.bool:
>         return torch.bool
>     if datatype_trt == trt.uint8:
>         return torch.uint8
>     if datatype_trt == trt.DataType.FP8:
>         return torch.float8_e4m3fn
>     if datatype_trt == trt.bf16:
>         return torch.bfloat16
>     if datatype_trt == trt.int64:
>         return torch.int64
>     if datatype_trt == trt.int4:
>         return None  # only torch.uint4 is supported
>     return None
> 
> 
> TRT_LLM_PLUGIN_NAMESPACE = 'tensorrt_llm'
> LAYER_NAME = 'TritonFlashAttentionLayer'
> FMHA_KERNEL_BLOCK_SIZE = 128
> '''
> dim_range=OrderedDict([
>                        ('batch_size', [bs_range]),
>                        ('num_heads', [self.num_heads]),
>                        ('seq_len', [max_len_range]),
>                        ('head_size', [self.head_size]),
>                    ]))
> '''
> soFile = "lib/libtrt_llm_custom_plugins.so"
> q_shape = [16, 8, 512, 64]
> k_shape = [16, 8, 512, 64]
> v_shape = [16, 8, 512, 64]
> 
> input_tensor_name = ['q', 'k', 'v']
> device = "cuda:1"
> # inference input data
> dtype = torch.float32
> query = torch.randn(*q_shape, dtype=dtype, device=device)
> key = torch.randn(*k_shape, dtype=dtype, device=device)
> value = torch.randn(*v_shape, dtype=dtype, device=device)
> 
> def getPlugin(num_heads: int, head_size: int, softmax_scale: float,
>                        inputs: List[trt.ITensor]):
>     plugin_creator = trt.get_plugin_registry().get_plugin_creator(
>         'TritonFlashAttention', '1', TRT_LLM_PLUGIN_NAMESPACE)
>     assert plugin_creator is not None
>     pfc = trt.PluginFieldCollection([
>         trt.PluginField("num_heads", np.array([num_heads], np.int32),
>                         trt.PluginFieldType.INT32),
>         trt.PluginField("head_size", np.array([head_size], np.int32),
>                         trt.PluginFieldType.INT32),
>         trt.PluginField("softmax_scale", np.array([softmax_scale], np.float32),
>                         trt.PluginFieldType.FLOAT32),
>         trt.PluginField("type_id", np.array([int(inputs[0].dtype)], np.int32),
>                         trt.PluginFieldType.INT32)
>     ])
>     return plugin_creator.create_plugin("flash_attention", pfc)
> 
> def _load_triton_plugin_lib():
>     plugin_lib = 'lib/libtrt_llm_custom_plugins.so'
>     handle = ctypes.CDLL(plugin_lib, mode=ctypes.RTLD_GLOBAL)
>     if handle is None:
>         raise ImportError('TensorRT-LLM Triton Plugin is unavailable')
>     handle.initOpenAiTritonPlugins.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
>     handle.initOpenAiTritonPlugins.restype = ctypes.c_bool
>     assert handle.initOpenAiTritonPlugins(
>         None, TRT_LLM_PLUGIN_NAMESPACE.encode('utf-8'))
> 
> def run():
>     _load_triton_plugin_lib()
>     trtFile = Path("llm_flash.trt")
>     logger = trt.Logger(trt.Logger.ERROR)
>     trt.init_libnvinfer_plugins(logger, '')
>     ctypes.cdll.LoadLibrary(soFile)
>     if os.path.isfile(trtFile):
>         with open(trtFile, "rb") as f:
>             engine = trt.Runtime(logger).deserialize_cuda_engine(f.read())
>         if engine == None:
>             print("Failed loading engine!")
>             return
>         print("Succeeded loading engine!")
>     else:
>         builder = trt.Builder(logger)
>         network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
>         profile = builder.create_optimization_profile()
>         config = builder.create_builder_config()
>         config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)
>         config.add_optimization_profile(profile) 
>         q = network.add_input("q", trt.float32, q_shape)
>         k = network.add_input("k", trt.float32, k_shape)
>         v = network.add_input("v", trt.float32, v_shape)
> 
>         pluginLayer = network.add_plugin_v2([q, k, v], getPlugin(
>             num_heads=q_shape[1], 
>             head_size=q_shape[-1],
>             softmax_scale=math.sqrt(q_shape[-1]),
>             inputs=[q, k, v]
>             ))
>         output_tensor = pluginLayer.get_output(0)
>         output_tensor.name = "attn"
>         network.mark_output(output_tensor)
>         engineString = builder.build_serialized_network(network, config)
>         if engineString == None:
>             print("Failed building engine!")
>             return
>         print("Succeeded building engine!")
>         with open(trtFile, "wb") as f:
>             f.write(engineString)
>         engine = trt.Runtime(logger).deserialize_cuda_engine(engineString)
> 
>     context = engine.create_execution_context()
>     tensor_name_list = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)]
>     output_name = None                 
>     for name in tensor_name_list:                                               # Print information of input / output tensors
>         mode = engine.get_tensor_mode(name)
>         data_type = engine.get_tensor_dtype(name)
>         buildtime_shape = engine.get_tensor_shape(name)
>         runtime_shape = context.get_tensor_shape(name)
>         print(data_type, buildtime_shape, runtime_shape)
>         if mode != trt.TensorIOMode.INPUT:
>             output_name = name
>         print(f"{'Input ' if mode == trt.TensorIOMode.INPUT else 'Output'}->{data_type}, {buildtime_shape}, {runtime_shape}, {name}")
> 
>     buffer = OrderedDict()                                                      # prepare the memory buffer on host and device
>     for name in tensor_name_list:
>         data_type = engine.get_tensor_dtype(name)
>         runtime_shape = context.get_tensor_shape(name)
>         buffer[name] = torch.empty(tuple(runtime_shape), dtype=datatype_trt_to_torch(data_type), device=device)
> 
>     # set runtime data, MUST use contiguous, it is a SERIOUS lesson
>     buffer[input_tensor_name[0]] = query.contiguous().to(device)   
>     buffer[input_tensor_name[1]] = key.contiguous().to(device)
>     buffer[input_tensor_name[2]] = value.contiguous().to(device)                 
> 
>     for name in tensor_name_list:
>         context.set_tensor_address(name, buffer[name].data_ptr())               # bind address of buffer to context
> 
>     context.execute_async_v3(0)                                                 # do inference computation
>     cudart.cudaDeviceSynchronize()
>     return buffer['attn']
> 
> if __name__ == "__main__":
>     os.system("rm -rf *.trt")
>     out = run()
>     print(out.shape)
>     print(out)
>     print("Test all finish!")
> ```
> 
> When I use the trt engine generated from the above code and perform a performance test on trtexec, the following error is reported:
> 
> ```
> &&&& RUNNING TensorRT.trtexec [TensorRT v100300] # trtexec --loadEngine=/home/lyc/attn/model/llm_flash.trt --staticPlugins=/home/lyc/attn/lib/libtrt_llm_custom_plugins.so --setPluginsToSerialize --device=1 --fp16 --noDataTransfers --useCudaGraph --useSpinWait=true --profilingVerbosity=detailed --verbose --separateProfileRun --dumpLayerInfo --exportProfile=flash_attn_info.json --exportLayerInfo=flash_attn_layerInfo.json
> [08/28/2024-03:25:56] [I] === Model Options ===
> [08/28/2024-03:25:56] [I] Format: *
> [08/28/2024-03:25:56] [I] Model: 
> [08/28/2024-03:25:56] [I] Output:
> [08/28/2024-03:25:56] [I] 
> [08/28/2024-03:25:56] [I] === System Options ===
> [08/28/2024-03:25:56] [I] Device: 1
> [08/28/2024-03:25:56] [I] DLACore: 
> [08/28/2024-03:25:56] [I] Plugins: /home/lyc/attn/lib/libtrt_llm_custom_plugins.so
> [08/28/2024-03:25:56] [I] setPluginsToSerialize: 
> [08/28/2024-03:25:56] [I] dynamicPlugins:
> [08/28/2024-03:25:56] [I] ignoreParsedPluginLibs: 0
> [08/28/2024-03:25:56] [I] 
> [08/28/2024-03:25:56] [I] === Inference Options ===
> [08/28/2024-03:25:56] [I] Batch: Explicit
> [08/28/2024-03:25:56] [I] Input inference shapes: model
> [08/28/2024-03:25:56] [I] Iterations: 10
> [08/28/2024-03:25:56] [I] Duration: 3s (+ 200ms warm up)
> [08/28/2024-03:25:56] [I] Sleep time: 0ms
> [08/28/2024-03:25:56] [I] Idle time: 0ms
> [08/28/2024-03:25:56] [I] Inference Streams: 1
> [08/28/2024-03:25:56] [I] ExposeDMA: Disabled
> [08/28/2024-03:25:56] [I] Data transfers: Disabled
> [08/28/2024-03:25:56] [I] Spin-wait: Enabled
> [08/28/2024-03:25:56] [I] Multithreading: Disabled
> [08/28/2024-03:25:56] [I] CUDA Graph: Enabled
> [08/28/2024-03:25:56] [I] Separate profiling: Enabled
> [08/28/2024-03:25:56] [I] Time Deserialize: Disabled
> [08/28/2024-03:25:56] [I] Time Refit: Disabled
> [08/28/2024-03:25:56] [I] NVTX verbosity: 2
> [08/28/2024-03:25:56] [I] Persistent Cache Ratio: 0
> [08/28/2024-03:25:56] [I] Optimization Profile Index: 0
> [08/28/2024-03:25:56] [I] Weight Streaming Budget: 100.000000%
> [08/28/2024-03:25:56] [I] Inputs:
> [08/28/2024-03:25:56] [I] Debug Tensor Save Destinations:
> [08/28/2024-03:25:56] [I] === Reporting Options ===
> [08/28/2024-03:25:56] [I] Verbose: Enabled
> [08/28/2024-03:25:56] [I] Averages: 10 inferences
> [08/28/2024-03:25:56] [I] Percentiles: 90,95,99
> [08/28/2024-03:25:56] [I] Dump refittable layers:Disabled
> [08/28/2024-03:25:56] [I] Dump output: Disabled
> [08/28/2024-03:25:56] [I] Profile: Disabled
> [08/28/2024-03:25:56] [I] Export timing to JSON file: 
> [08/28/2024-03:25:56] [I] Export output to JSON file: 
> [08/28/2024-03:25:56] [I] Export profile to JSON file: flash_attn_info.json
> [08/28/2024-03:25:56] [I] 
> [08/28/2024-03:25:56] [I] === Device Information ===
> [08/28/2024-03:25:56] [I] Available Devices: 
> [08/28/2024-03:25:56] [I]   Device 0: "NVIDIA GeForce RTX 4090" UUID: GPU-3ce4025a-5aad-9ea7-d98e-4ab6a726475f
> [08/28/2024-03:25:56] [I]   Device 1: "NVIDIA GeForce RTX 4090" UUID: GPU-8a0ba840-c40d-abfb-7daf-00c6f5c0a5f7
> [08/28/2024-03:25:56] [I]   Device 2: "NVIDIA GeForce RTX 4090" UUID: GPU-728c18a2-a470-f4d0-e71c-4e2f8914e2a2
> [08/28/2024-03:25:56] [I]   Device 3: "NVIDIA GeForce RTX 4090" UUID: GPU-e7646b7d-4894-c827-d72f-60dbd9f20b50
> [08/28/2024-03:25:56] [I]   Device 4: "NVIDIA GeForce RTX 4090" UUID: GPU-a8292b4d-e8e1-7cf8-7a51-6afa927afa61
> [08/28/2024-03:25:56] [I]   Device 5: "NVIDIA GeForce RTX 4090" UUID: GPU-ede2e0fa-bf5f-b2ef-f2eb-becd84056ad5
> [08/28/2024-03:25:56] [I]   Device 6: "NVIDIA GeForce RTX 4090" UUID: GPU-55365942-a88d-15e4-8770-91f7245f7cb1
> [08/28/2024-03:25:56] [I]   Device 7: "NVIDIA GeForce RTX 4090" UUID: GPU-c224cb39-150a-d0f3-08b6-323f227e9125
> [08/28/2024-03:25:56] [I] Selected Device: NVIDIA GeForce RTX 4090
> [08/28/2024-03:25:56] [I] Selected Device ID: 1
> [08/28/2024-03:25:56] [I] Selected Device UUID: GPU-8a0ba840-c40d-abfb-7daf-00c6f5c0a5f7
> [08/28/2024-03:25:56] [I] Compute Capability: 8.9
> [08/28/2024-03:25:56] [I] SMs: 128
> [08/28/2024-03:25:56] [I] Device Global Memory: 24217 MiB
> [08/28/2024-03:25:56] [I] Shared Memory per SM: 100 KiB
> [08/28/2024-03:25:56] [I] Memory Bus Width: 384 bits (ECC disabled)
> [08/28/2024-03:25:56] [I] Application Compute Clock Rate: 2.52 GHz
> [08/28/2024-03:25:56] [I] Application Memory Clock Rate: 10.501 GHz
> [08/28/2024-03:25:56] [I] 
> [08/28/2024-03:25:56] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
> [08/28/2024-03:25:56] [I] 
> [08/28/2024-03:25:56] [I] TensorRT version: 10.3.0
> [08/28/2024-03:25:56] [I] Loading standard plugins
> [08/28/2024-03:25:56] [V] [TRT] Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
> ......
> [08/28/2024-03:25:56] [V] [TRT] Registered plugin creator - ::Split version 1
> [08/28/2024-03:25:56] [V] [TRT] Registered plugin creator - ::VoxelGeneratorPlugin version 1
> [08/28/2024-03:25:56] [I] Loading supplied plugin library: /home/lyc/attn/lib/libtrt_llm_custom_plugins.so
> [08/28/2024-03:25:56] [I] [TRT] Loaded engine size: 0 MiB
> [08/28/2024-03:25:56] [V] [TRT] Local registry did not find TritonFlashAttention creator. Will try parent registry if enabled.
> [08/28/2024-03:25:56] [E] [TRT] IPluginRegistry::getPluginCreator: Error Code 4: API Usage Error (Cannot find plugin: TritonFlashAttentiontensorrt_llm, version: 1, namespace:tensorrt_llm.)
> [08/28/2024-03:25:56] [E] Error[1]: IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> [08/28/2024-03:25:56] [E] Engine deserialization failed
> [08/28/2024-03:25:56] [E] Got invalid engine!
> [08/28/2024-03:25:56] [E] Inference set up failed
> &&&& FAILED TensorRT.trtexec [TensorRT v100300] # trtexec --loadEngine=/home/lyc/attn/model/llm_flash.trt --staticPlugins=/home/lyc/attn/lib/libtrt_llm_custom_plugins.so --setPluginsToSerialize --device=1 --fp16 --noDataTransfers --useCudaGraph --useSpinWait=true --profilingVerbosity=detailed --verbose --separateProfileRun --dumpLayerInfo --exportProfile=flash_attn_info.json --exportLayerInfo=flash_attn_layerInfo.json
> ```
> 
> This looks like it's not registering the plugin, but the python code above registers the plugin, is there a way to get trtexec to work as well? Thank you very much.



Can the flash atten2 version be used?
