### ISSUE TITLE
branch 20.02 not found

### ISSUE THREAD

**Issue by czs1886** [NVIDIA/TensorRT#410]
I pulled the latest tensorrt docker image from ngc and when I run the install_opensource.sh, it shows that fatal: Remote branch 20.02 not found in upstream origin.
When will branch 20.02 come out?

**Comment by rmccorm4** [comment]
Hi @czs1886,

Thanks for pointing this out. I'll see what I can do.

For now, you can change "20.02" to "20.01" for last stable branch or "master" for most up to date code.

**Comment by rmccorm4** [comment]
Fixed: https://github.com/NVIDIA/TensorRT/releases/tag/20.02
