### ISSUE TITLE
How to count the time spent on each operator with trtexec

### ISSUE THREAD

**Issue by demuxin** [NVIDIA/TensorRT#4110]
## Description

I am counting the elapsed time of each operator in the model using the following command:

```
trtexec --loadEngine=codetr_sim.trt --dumpProfile --noDataTransfers --useSpinWait --useCudaGraph --separateProfileRun --verbose 2>&1 | tee build.log
```

But I get the total elapsed time for multiple operators as shown below:

![Image](https://github.com/user-attachments/assets/0fbbca97-5669-45ef-a2a2-fb2c1b6d0624)

What is causing this? And how can I get the elapsed time for each operator?

This is the output file of the trtexec command:

[build.log](https://github.com/user-attachments/files/16887594/build.log)

**Comment by lix19937** [comment]
> What is causing this?   

**ForeignNode** is a node processed by Myelin(a un-open-source NN-DL compiler) or DLA. Usually it's NOT a node but contain many nodes/layers. Eg. Myelin will fuse lots of operators into a big operator(ForeignNode) to improve performance.   

> And how can I get the elapsed time for each operator?    

No, you can not.

**Comment by demuxin** [comment]
But I want to know which node is taking a lot of time in ForeignNode, so that I can perform targeted optimization.

You know a good way to do that?

**Comment by lix19937** [comment]
You can run with `nsys profile` when use trtexec build & infer engine.   Through `.qdrep` file to see which kernel/part  take up to much time.

**Comment by demuxin** [comment]
ok, thanks a lot.
