### ISSUE TITLE
Support ubuntu 24.04?

### ISSUE THREAD

**Issue by johnnynunez** [NVIDIA/TensorRT#4112]
I dind't find tensorrt for ubuntu 24.04:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/

**Comment by moraxu** [comment]
Please use https://developer.nvidia.com/tensorrt/download/10x



![Image](https://github.com/user-attachments/assets/589d5816-e987-42bf-9fd9-070d2cf5af61)

**Comment by johnnynunez** [comment]
Now it is via apt! Thank you
