### ISSUE TITLE
[FEATURE REQUEST] Support onnx's local function as custom plugin

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT#4113]
[Functions](https://github.com/gramalingam/onnx/blob/main/docs/IR.md#functions) is a feature in onnx, which can be thought of as an operator combined with an implementation of the operator using other, more primitive, ops, referred to as the function body. 

Right now TensorRT support this feature. However, onnxparser will first use the LocalFunctionImporter before FallbackPluginImporter : 

https://github.com/onnx/onnx-tensorrt/blob/706f02e74366b2cbaacf87be61de95df051a2788/ModelImporter.cpp#L159

So it is impossible to write a custom plugin to re-implement these local function.

I export an  [onnx](https://github.com/leimao/TensorRT-Custom-Plugin-Example/blob/main/scripts/export_identity_neural_network_new_opset.py) with local function node, Is there any way I can use custom plugin for this function?

**Comment by moraxu** [comment]
cc @kevinch-nv if this issue was ever discussed internally?

**Comment by tp-nan** [comment]
Hi, is there any update?

**Comment by kevinch-nv** [comment]
Yes, apologies for the late reply. It makes sense for TensorRT plugins with the same name as a local function to have high priority when parsing the ONNX model. An internal bug has been filed and we'll notify when it has been updated.
