### ISSUE TITLE
multi GPU

### ISSUE THREAD

**Issue by feizhouxiaozhu** [NVIDIA/TensorRT#412]
## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi,

Please fill in everything in the issue template. Closing until then. Thanks.
