### ISSUE TITLE
Does tensorrt 7.2.2.3 has python wheel ?

### ISSUE THREAD

**Issue by EmmaThompson123** [NVIDIA/TensorRT#4128]
My system infos:
windows 11
gpu: gtx 1660 ti
python 3.10.11
cuda:10.2
tensorrt version:7.2.2.3
tensorrt install method: zip

I saw `pip install tensorrt` in some TensorRT installation tutorials, but I found that there is no version 7.2.2 of TensorRT on [PyPI](https://pypi.org/project/tensorrt/#history). Can I still use TensorRT 7.2.2.3 through Python?

**Comment by lix19937** [comment]
From here https://developer.nvidia.com/nvidia-tensorrt-7x-download?form=submitted you can load 
TensorRT-7.2.2.3.Windows10.x86_64.cuda-10.2.cudnn8.0.zip 

TensorRT-7.2.2.3 is too old.

**Comment by EmmaThompson123** [comment]
I have download the TensorRT-7.2.2.3.Windows10.x86_64.cuda-10.2.cudnn8.0.zip, but there is not prebuilt tensort pyhton wheel.
I know tensorrt 7.x is old, but my computer and its environment are old too.

**Comment by lix19937** [comment]
Ohh, only linux os has python version of trt, you can use `nvcr.io/nvidia/tensorrt:21.03-py3` to install python trt    
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt/tags   

<html>
<body>

ENV TENSORRT_VERSION=7.2.2.3+cuda11.1.0.024
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by EmmaThompson123** [comment]
Fine, I'm gonna quit tensorrt 7.x, turn to using tensorrt 8.x ~
