### ISSUE TITLE
python error in colab: module 'tensorrt' has no attribute '__version__'

### ISSUE THREAD

**Issue by EmmaThompson123** [NVIDIA/TensorRT#4129]
## Description

I tried to install tensorrt and use it in colab, here is the [colab notebook link](https://colab.research.google.com/drive/1J_vMn_tT-0pNmngIZwJPKXynyx3QmsI8#scrollTo=xOjUgDLbGzKf), you can reproduce the error in it. The error is "AttributeError: module 'tensorrt' has no attribute '__version__'" when executes `print(tensorrt.__version__)`

## Environment

**TensorRT Version**: 10.4.0.26

**NVIDIA GPU**: Tesla T4 

**NVIDIA Driver Version**: 535.104.05

**CUDA Version**: 12.2

**CUDNN Version**: 9.4.0

Operating System: Ubuntu 22.04

Python Version (if applicable): 3.10

**Comment by lix19937** [comment]
Ref https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip   

>> import tensorrt
>> print(tensorrt.__version__)
>> assert tensorrt.Builder(tensorrt.Logger())

**Comment by EmmaThompson123** [comment]
Oh, my fault, I have to restart the coalb seesion.
