### ISSUE TITLE
"CUDA Failure: 1" failure of TensorRT 8.6 when running TransUNet on GPU 3080

### ISSUE THREAD

**Issue by Lemonononon** [NVIDIA/TensorRT#4146]
## Description

Sorry for the disturbance. Recently, I’ve been working on deploying the [TransUNet](https://github.com/Beckschen/TransUNet) model using TensorRT 8.6. The model conversion pipeline is: pt -> onnx -> trt_engine (using trtexec, specifically: trtexec --onnx=transunet_model.onnx --saveEngine=transunet.engine).

My issue arises after successfully loading the engine. During inference, the program crashes with only a "CUDA Failure: 1" error. Below is the code for loading the engine and performing inference.

## Environment

TensorRT version: 8.6.1
[09/24/2024-01:37:50] [I] [TRT] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 19, GPU 1622 (MiB)
[09/24/2024-01:37:58] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +1444, GPU +268, now: CPU 1540, GPU 1890 (MiB)
[09/24/2024-01:37:58] [I] Start parsing network model.
[09/24/2024-01:37:58] [I] [TRT] ----------------------------------------------------------------
[09/24/2024-01:37:58] [I] [TRT] Input filename:   transunet_model.onnx
[09/24/2024-01:37:58] [I] [TRT] ONNX IR version:  0.0.8
[09/24/2024-01:37:58] [I] [TRT] Opset version:    17
[09/24/2024-01:37:58] [I] [TRT] Producer name:    pytorch
[09/24/2024-01:37:58] [I] [TRT] Producer version: 2.4.0
[09/24/2024-01:37:58] [I] [TRT] Domain:           
[09/24/2024-01:37:58] [I] [TRT] Model version:    0

Operating System: Ubuntu 20.04

### Load engine
```

Segmentation::Segmentation() {

    auto enginePath = "xxx";
    auto inputBlobName = "input";
    auto outputBlobName = "output"

    runtime = std::shared_ptr<nvinfer1::IRuntime>(nvinfer1::createInferRuntime(nvinfer1::gLogger));

    // read file
    std::vector<char> trtModelStream;
    std::ifstream file(enginePath, std::ios::binary);
    if (!file.good())
    {
        LOG(error, "read engine file failed");
        std::cerr << "read engine file: " << enginePath << " failed" << std::endl;
        exit(-1);
    }

    file.seekg(0, std::ifstream::end);
    int size = file.tellg();
    file.seekg(0, std::ifstream::beg);

    trtModelStream.resize(size);
    file.read(trtModelStream.data(), size);
    file.close();

    initLibNvInferPlugins(&nvinfer1::gLogger, "");

    // engine
    engine = std::shared_ptr<nvinfer1::ICudaEngine>(runtime->deserializeCudaEngine(trtModelStream.data(), trtModelStream.size()));
    // context
    context = std::shared_ptr<nvinfer1::IExecutionContext>(engine->createExecutionContext());

    // Create stream
    CHECK(cudaStreamCreate(&stream));

    auto inputIndex = engine->getBindingIndex(inputBlobName.c_str());
    auto outputIndex = engine->getBindingIndex(outputBlobName.c_str());

    // Create GPU buffers on device
    CHECK(cudaMalloc(&buffers[inputIndex], batchSize * 3 * inputHeight * inputWidth * sizeof(float)));
    CHECK(cudaMalloc(&buffers[outputIndex], batchSize * 2 * inputHeight * inputWidth * sizeof(float)));

    LOG(info, "segmentation init success");
}
```

### inference
```

void Segmentation::run( const std::vector<float>& input, float* output, int dataSize ) {

    CHECK(cudaMemcpyAsync(buffers[0], input.data(), dataSize * 3 * inputHeight * inputWidth * sizeof(float), cudaMemcpyHostToDevice, stream));

    // Run inference
    CHECK(context->enqueueV2(buffers, stream, nullptr));

    CHECK(cudaMemcpyAsync(output, buffers[1], dataSize * 2 * 224 * 244 * sizeof(float), cudaMemcpyDeviceToHost, stream));

    CHECK(cudaStreamSynchronize(stream));

}
```

**Comment by lix19937** [comment]
Put follow calling   
```
CHECK(context->enqueueV2(buffers, 0, nullptr));
```
in your Segmentation::Segmentation() function before `return; ` to check dummy infer.   @Lemonononon

**Comment by Lemonononon** [comment]
> Put follow calling
> 
> CHECK(context->enqueueV2(buffers, 0, nullptr));
> in your Segmentation::Segmentation() function before `return; ` to check dummy infer. [@Lemonononon](https://github.com/Lemonononon)

Thank you very much! However, this did not solve my problem. The program crashes directly at the newly added line of code, with the same 'Cuda failure: 1'. @lix19937

**Comment by lix19937** [comment]
Maybe you need follow block  every paras are right ?
```cpp 
   // Create GPU buffers on device
    CHECK(cudaMalloc(&buffers[inputIndex], batchSize * 3 * inputHeight * inputWidth * sizeof(float)));
    CHECK(cudaMalloc(&buffers[outputIndex], batchSize * 2 * inputHeight * inputWidth * sizeof(float)));
```

Another you can modify my code https://github.com/lix19937/trt-samples-for-hackathon-cn/blob/master/cookbook/01-SimpleDemo/TensorRT8.5/main.cpp to impl your model inference.

**Comment by Lemonononon** [comment]
Ops, it's my fault. The CUDA interface returns a cudaError_t value, where 0 means no error, but TensorRT returns a boolean value, where 1 indicates no issues. However, the CHECK macro is used to validate cudaError_t. @lix19937 谢谢！
