### ISSUE TITLE
pytorch Conv3DTranspose output padding

### ISSUE THREAD

**Issue by copaah** [NVIDIA/TensorRT#415]
## Description

I am trying to convert a pytorch model that contains `Conv3DTranspose` layers with `output_padding=1`. If I understand the documentation for IDeconvolutionLayer correctly, it says that it supports 3D padding (https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#deconvolution-layer). However, the documentation for IPaddingLayer says it only support padding the two inner most dimensions. This also corresponds to the error I'm getting when converting the model to tensorrt:

```
Assertion failed: output_padding.nbDims == 2 || (output_padding.nbDims == 3 && output_padding.d[0] == 0)
```
Is there a way to use 3D output padding in the Conv3DTranspose layer?

## Environment

**TensorRT Version**: 7
**GPU Type**: Geforce GTX 1070
**Nvidia Driver Version**: 440.48.02
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5.32.1
**Operating System + Version**:  Ubuntu 18.04
**Python Version (if applicable)**: 2.7 or 3.x
**PyTorch Version (if applicable)**: 1.4.0

**Comment by rmccorm4** [comment]
Hi,

I believe 3D Padding standalone is not supported, but I think a workaround is to add the padding directly to the 3D Conv layer. See this thread: https://github.com/NVIDIA/TensorRT/issues/153#issuecomment-580984310

**Comment by rajeevsrao** [comment]
@copaah can you please confirm if the workaround suggested by Ryan works for you. Marking this an RFE for future consideration.

**Comment by copaah** [comment]
> @copaah can you please confirm if the workaround suggested by Ryan works for you. Marking this an RFE for future consideration.

I never tried the solution and went with other ops than `Conv3DTranspose`, so I cannot confirm if it works, unfortunately.

**Comment by rajeevsrao** [comment]
Closing as unresolved. Please reopen if necessary.
