### ISSUE TITLE
Unable to open library: nvinfer_plugin_10.dll

### ISSUE THREAD

**Issue by songhat** [NVIDIA/TensorRT#4159]
## Environment

**TensorRT Version**:

**NVIDIA GPU**: NVIDIA GeForce RTX 4060 Ti

**NVIDIA Driver Version**: 546.33

**CUDA Version**:11.8

**CUDNN Version**:8.9

Operating System: windwos

Python Version (if applicable): 3.10

when I run 
`trtexec.exe --onnx=data/mobile_sam_mask_decoder.onnx --saveEngine=data/mobile_sam_mask_decoder.engine --minShapes=point_coords:1x1x2,point_labels:1x1 --optShapes=point_coords:1x1x2,point_labels:1x1 --maxShapes=point_coords:1x10x2,point_labels:1x10`
come a error:
`Unable to open library: nvinfer_plugin_10.dll`
but I actually find  nvinfer_plugin_10.dll in my RELEASE foldor.
![Image](https://github.com/user-attachments/assets/dd032afb-8406-4234-bb53-3a376eadb73f)

**Comment by lix19937** [comment]
Add dll path in your env load path .

**Comment by samurdhikaru** [comment]
On Windows, check whether the location of `nvinfer_plugin_10.dll` is visible through `PATH`

**Comment by lix19937** [comment]
What is your trt vesrion ?   

like follow cmd to get version   
```shell  
trtexec |grep "PASSED TensorRT.trtexec"
```

**Comment by songhat** [comment]
@lix19937 in windows 11, I run this run:
```trtexec | findstr "PASSED TensorRT.trtexec"```
I got this result:
```
&&&& RUNNING TensorRT.trtexec [TensorRT v100001] # D:\all_codes\SAM\TensorRT\build\Release\trtexec.exe
&&&& PASSED TensorRT.trtexec [TensorRT v100001] # D:\all_codes\SAM\TensorRT\build\Release\trtexec.exe
```
and I am sure my path contains loaction  of  nvinfer_plugin_10.dll.
![Image](https://github.com/user-attachments/assets/d60fd2f2-2352-40b9-b022-b85de61d3311)

**Comment by lix19937** [comment]
Try to test follow in your `D:\all_codes\SAM\TensorRT\build\Release\` path   @songhat 

```cpp
#include <stdio.h>
#include <windows.h>

typedef char* (*gf_getCurrentLibraryVersion) ();

int main() {

    gf_getCurrentLibraryVersion getVersion;

    HINSTANCE hLib = LoadLibraryA("nvinfer_plugin_10.dll");
    if (hLib) {
        getVersion = (gf_getCurrentLibraryVersion)GetProcAddress(hLib, "gf_getCurrentLibraryVersion");
        printf("Version = %s\n", getVersion());
    }
    else {
        printf("Error loading dll: %d/n", GetLastError());
    }
    printf("Hit any key to continue\n");
    getchar();

    return 0;
}
```

**Comment by songhat** [comment]
@lix19937 I find a solution which copy all dll from tensorRT-10.4.0.26 to RELEASE specifically the nvinfer_10.dll. It's strange that the dynamic library is not automatically copied to RELEASE. And I got other problem...
```
[09/26/2024-11:20:23] [E] Error[4]: ITensor::getDimensions: Error Code 4: Internal Error (/OneHot: an IIOneHotLayer cannot be used to compute a shape tensor)
[09/26/2024-11:20:23] [E] [TRT] parsers\onnx\ModelImporter.cpp:828: While parsing node number 146 [Tile -> "/Tile_output_0"]:
[09/26/2024-11:20:23] [E] [TRT] parsers\onnx\ModelImporter.cpp:831: --- Begin node ---
input: "/Unsqueeze_3_output_0"
input: "/Reshape_2_output_0"
output: "/Tile_output_0"
name: "/Tile"
op_type: "Tile"

[09/26/2024-11:20:23] [E] [TRT] parsers\onnx\ModelImporter.cpp:832: --- End node ---
[09/26/2024-11:20:23] [E] [TRT] parsers\onnx\ModelImporter.cpp:836: ERROR: parsers\onnx\ModelImporter.cpp:194 In function parseNode:
[6] Invalid Node - /Tile
ITensor::getDimensions: Error Code 4: Internal Error (/OneHot: an IIOneHotLayer cannot be used to compute a shape tensor)
[09/26/2024-11:20:23] [E] Failed to parse onnx file
[09/26/2024-11:20:23] [I] Finished parsing network model. Parse time: 0.210484
[09/26/2024-11:20:23] [E] Parsing model failed
[09/26/2024-11:20:23] [E] Failed to create engine from model or file.
[09/26/2024-11:20:23] [E] Engine set up failed

```

**Comment by lix19937** [comment]
You has better to install one version of trt.
