### ISSUE TITLE
got different result when running INT8 with fixed calibration table

### ISSUE THREAD

**Issue by twmht** [NVIDIA/TensorRT#417]
I have tried both TensorRT6 and TensorRT7

Given a fixed calibration table, when generating two plan files with different max batch size, I got different inference result on the same image.

the calibration table is generated with max batch size 128 and the engine files are generated with max batch size 1 and 128

given the same image, both plan file gave different inference result.

there are other similar issues here 

https://github.com/NVIDIA/TensorRT/issues/10
https://devtalk.nvidia.com/default/topic/1041780/tensorrt/int8-inference-with-different-results/

not sure if this is a bug.

thank you

**Comment by rmccorm4** [comment]
Hi,

Can you share a simple model, calibration cache, and build/inference code to reproduce this issue?

**Comment by twmht** [comment]
@rmccorm4 

yeah. sure, I need to prepare these in a few days. 

thanks for your quick reply.

**Comment by rajeevsrao** [comment]
@twmht please share the repro test. It does sound like a bug.

**Comment by twmht** [comment]
@rajeevsrao 

closing this issue unitil I have time to prepare the testing report.
