### ISSUE TITLE
Notebook example out of date

### ISSUE THREAD

**Issue by davidrigie** [NVIDIA/TensorRT#4183]
This needs to be updated since some of these flags have been deprecated (e.g. `builder.max_workspace_size`)

https://github.com/NVIDIA/TensorRT/blob/08ad45bf3df848e722dfdc7d01474b5ba2eff7e9/quickstart/IntroNotebooks/onnx_helper.py#L72-L92

**Comment by yuanyao-nv** [comment]
@davidrigie Can you please provide more information? Which flag and which example are you referring to?

**Comment by davidrigie** [comment]
> [@davidrigie](https://github.com/davidrigie) Can you please provide more information? Which flag and which example are you referring to?

My apologies, I thought I had referenced the relevant lines. I updated the description. I guess this function isn't actually used anywhere, so maybe it can just be deleted

**Comment by lix19937** [comment]
|old | new|   
|--- | ---|   
|IBuilderConfig.max_workspace_size| BuilderConfig.set_memory_pool_limit() with MemoryPoolType.WORKSPACE </br>IBuilderConfig.get_memory_pool_limit() with MemoryPoolType.WORKSPACE |   

@davidrigie

**Comment by yuanyao-nv** [comment]
Please use the suggested workaround for now. We will fix the quickstart in the next release. Thanks!

**Comment by yuanyao-nv** [comment]
The update can be found on the 10.5 branch. Closing this for now. 
Thanks for bringing this up!
