### ISSUE TITLE
TRT parse onnx model and give a network with 0 layer

### ISSUE THREAD

**Issue by ycchanau** [NVIDIA/TensorRT#419]
## Description

I export a very simple model from PyTorch and try to use TRT to parse the model. However, after parsing, the number of layers is 0. I have tested the model with onnxruntime (Cuda support) and the onnx checker.

![model](https://user-images.githubusercontent.com/43056995/76158763-3f938100-6154-11ea-8f52-bfc0b74e7c88.png)

> 
> Loading ONNX file from path model.onnx...
> Beginning ONNX file parsing
> num_layers after parsing: 0
> python: ../builder/Network.cpp:1152: virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed.
> Aborted (core dumped)

## Environment

**TensorRT Version**: 7.0
**GPU Type**: T4
**Nvidia Driver Version**: 
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.4
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

[model.zip](https://github.com/NVIDIA/TensorRT/files/4302973/model.zip)

## Steps To Reproduce
```
import pycuda.autoinit
import numpy as np
import pycuda.driver as cuda
import tensorrt as trt
import torch
import os
import time
from PIL import Image
import cv2
import torchvision

filename = '/home/ubuntu/TM2/photo/4.png'
max_batch_size = 1
onnx_model_path = "model.onnx"
base_size=512

TRT_LOGGER = trt.Logger()  # This logger is required to build an engine

class HostDeviceMem(object):
    def __init__(self, host_mem, device_mem):
        """Within this context, host_mom means the cpu memory and device means the GPU memory
        """
        self.host = host_mem
        self.device = device_mem

    def __str__(self):
        return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)

    def __repr__(self):
        return self.__str__()


def allocate_buffers(engine):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()
    for binding in engine:
        size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size
        dtype = trt.nptype(engine.get_binding_dtype(binding))
        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))
        # Append to the appropriate list.
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem))
    return inputs, outputs, bindings, stream


def get_engine(max_batch_size=1, onnx_file_path="", engine_file_path="", \
               fp16_mode=False, int8_mode=False, save_engine=False,
               ):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""

    def build_engine(max_batch_size, save_engine):
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        with trt.Builder(TRT_LOGGER) as builder, \
                builder.create_network() as network, \
                trt.OnnxParser(network, TRT_LOGGER) as parser:

            builder.max_workspace_size = 1 << 30  # Your workspace size
            builder.max_batch_size = max_batch_size
            # pdb.set_trace()
            builder.fp16_mode = fp16_mode  # Default: False
            builder.int8_mode = int8_mode  # Default: False
            if int8_mode:
                # To be updated
                raise NotImplementedError

            # Parse model file
            if not os.path.exists(onnx_file_path):
                quit('ONNX file {} not found'.format(onnx_file_path))

            print('Loading ONNX file from path {}...'.format(onnx_file_path))
            with open(onnx_file_path, 'rb') as model:
                print('Beginning ONNX file parsing')
                parser.parse(model.read())

            print("num_layers after parsing: {}".format(network.num_layers))

            last_layer = network.get_layer(network.num_layers - 1)
            # Check if last layer recognizes it's output
            print("the shape of the output: {}".format(last_layer.get_output(0).shape))
            if not last_layer.get_output(0):
            # If not, then mark the output using TensorRT API
                network.mark_output(last_layer.get_output(0))

            print('Completed parsing of ONNX file')
            print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))

            engine = builder.build_cuda_engine(network)
            print("Completed creating Engine")

            if save_engine:
                with open(engine_file_path, "wb") as f:
                    f.write(engine.serialize())
            return engine

    if os.path.exists(engine_file_path):
        # If a serialized engine exists, load it instead of building a new one.
        print("Reading engine from file {}".format(engine_file_path))
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
    else:
        return build_engine(max_batch_size, save_engine)


def do_inference(context, bindings, inputs, outputs, stream, batch_size=1):
    # Transfer data from CPU to the GPU.
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    # Run inference.
    context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    # Synchronize the stream
    stream.synchronize()
    # Return only the host outputs.
    return [out.host for out in outputs]


def postprocess_the_outputs(h_outputs, shape_of_output):
    h_outputs = h_outputs.reshape(*shape_of_output)
    return h_outputs


image = Image.open(filename).convert('RGB')
if base_size:
    image = image.resize(size=(base_size, base_size), resample=Image.BILINEAR)
image = np.expand_dims(image, axis=0)

# These two modes are dependent on hardwares
fp16_mode = False
int8_mode = False
trt_engine_path = './model_fp16_{}_int8_{}.trt'.format(fp16_mode, int8_mode)
# Build an engine
engine = get_engine(max_batch_size, onnx_model_path, trt_engine_path, fp16_mode, int8_mode)
# Create the context for this engine
context = engine.create_execution_context()
# Allocate buffers for input and output
inputs, outputs, bindings, stream = allocate_buffers(engine) # input, output: host # bindings

# Do inference
shape_of_output = (max_batch_size, 4, 512, 512)
# Load data to the buffer
inputs[0].host = image.reshape(-1)

# inputs[1].host = ... for multiple input
t1 = time.time()
trt_outputs = do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream) # numpy data
t2 = time.time()
feat = postprocess_the_outputs(trt_outputs[0], shape_of_output)

print('TensorRT ok')

print("Inference time with the TensorRT engine: {}".format(t2-t1))

print('All completed!')
```

**Comment by ycchanau** [comment]
There are some issues that mention that TRT does not support the size arg( int64 ) of the resize op. Is it the reason why the number of layers is 0?

**Comment by rmccorm4** [comment]
Hi,

Please try building the OSS ONNX parser and then try parsing the model again. You should be able to build the OSS components with something like this:

```
wget https://raw.githubusercontent.com/rmccorm4/tensorrt-utils/master/OSS/build_OSS.sh
source build_OSS.sh
```

Then
```
trtexec --explicitBatch --onnx=model.onnx
```

**Comment by ycchanau** [comment]
@rmccorm4 Thanks for your reply. I failed to build the OSS components but I modified parts of my code according to the comments in other issues. As a result, I got this error. I noticed that there are some other issues about this problem, so is the ultimate solution building the OSS components?

Modification:
```
        network_creation_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_PRECISION)
        network_creation_flag |= 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        with trt.Builder(TRT_LOGGER) as builder, \
                builder.create_network(network_creation_flag) as network, \
                trt.OnnxParser(network, TRT_LOGGER) as parser:

            builder.max_workspace_size = 1 << 30  # Your workspace size
            builder.max_batch_size = max_batch_size
            # pdb.set_trace()
            builder.fp16_mode = fp16_mode  # Default: False
            builder.int8_mode = int8_mode  # Default: False
            if int8_mode:
                # To be updated
                raise NotImplementedError

            # Parse model file
            if not os.path.exists(onnx_file_path):
                quit('ONNX file {} not found'.format(onnx_file_path))

            print('Loading ONNX file from path {}...'.format(onnx_file_path))
            with open(onnx_file_path, 'rb') as model:
                print('Beginning ONNX file parsing')
                if not parser.parse(model.read()):
                    print('ERROR: Failed to parse the ONNX file.')
                    for error in range(parser.num_errors):
                        print(parser.get_error(error))
```

Error:
> (test) ubuntu@ip-172-31-46-148:~/FYP-Seg$ python test_tensorrt.py
> Loading ONNX file from path model.onnx...
> Beginning ONNX file parsing
> [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> ERROR: Failed to parse the ONNX file.
> In node 7 (parseGraph): INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)
> num_layers after parsing: 4
> the shape of the output: (4,)
> Completed parsing of ONNX file
> Building an engine from file model.onnx; this may take a while...
> [TensorRT] ERROR: Network must have at least one output
> [TensorRT] ERROR: Network validation failed.
> Completed creating Engine
> Traceback (most recent call last):
>   File "test_tensorrt.py", line 147, in <module>
>     context = engine.create_execution_context()
> AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by rmccorm4** [comment]
If I were to guess, I believe that dangling "Constant" node in your graph image is the issue. I think I've seen this in another issue and was fixed in OSS.

If OSS doesn't fix it, may be another issue.

**Comment by rmccorm4** [comment]
You can also try onnx-simplifier to see if it removes the bad node.

**Comment by ycchanau** [comment]
> 
> 
> You can also try onnx-simplifier to see if it removes the bad node.

@rmccorm4 Thanks for your suggestion. I have been stuck at the resize issue for two days but I still have no idea how to solve it. I optimized the model with 'extract_constant_to_initializer' in onnx.optimizer to remove the constant node, and now I get this error. I think the concat node give an int64 tensor to the resize node which leads to this error. So, is the only solution now trying OSS component?
![model](https://user-images.githubusercontent.com/43056995/76160989-f4846880-6169-11ea-8682-41cc31686df2.png)
[optimized_model.zip](https://github.com/NVIDIA/TensorRT/files/4303072/optimized_model.zip)


> (test) ubuntu@ip-172-31-46-148:~/FYP-Seg$ python test_tensorrt.py
> ONNX file optimizing_model.onnx not found
> (test) ubuntu@ip-172-31-46-148:~/FYP-Seg$ python test_tensorrt.py
> Loading ONNX file from path optimized_model.onnx...
> Beginning ONNX file parsing
> [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> ERROR: Failed to parse the ONNX file.
> In node -1 (parseGraph): UNSUPPORTED_NODE: Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
> num_layers after parsing: 0
> python: ../builder/Network.cpp:1152: virtual nvinfer1::ILayer* nvinfer1::Network::getLayer(int) const: Assertion `layerIndex >= 0' failed.
> Aborted (core dumped)

**Comment by ycchanau** [comment]
> 
> 
> If I were to guess, I believe that dangling "Constant" node in your graph image is the issue. I think I've seen this in another issue and was fixed in OSS.
> 
> If OSS doesn't fix it, may be another issue.

@rmccorm4 I tested OSS. It seems that I am facing the same error you mentioned here.[https://github.com/NVIDIA/TensorRT/issues/284#issuecomment-572835659](url) So, there is no way to solve the problem now?

> [03/08/2020-11:32:28] [W] [TRT] /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:235: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> While parsing node number 7 [Resize]:
> ERROR: /workspace/TensorRT/parsers/onnx/builtin_op_importers.cpp:2452 In function importResize:
> [8] Assertion failed: (transformationMode == "asymmetric") && "This version of TensorRT only supports asymmetric resize!"
> [03/08/2020-11:32:28] [E] Failed to parse onnx file
> [03/08/2020-11:32:28] [E] Parsing model failed
> [03/08/2020-11:32:28] [E] Engine creation failed
> [03/08/2020-11:32:28] [E] Engine set up failed
> &&&& FAILED TensorRT.trtexec # trtexec --explicitBatch --onnx=model.onnx
