### ISSUE TITLE
NaN issue of TensorRT 8.5.2.2 when performing inference on GPU 3090

### ISSUE THREAD

**Issue by Vegeshp** [NVIDIA/TensorRT#4190]
## Description

First of all, sorry for the absence of ONNX model and TensorRT engine since this can break the security policy in the company I work for.

I converted an engine with CUDA 11.6 CUDNN 8.6 TensorRT 8.5.2.2 GPU 3080 via tensorrt 8.5.2.2 Python API, and the inference result is expected on GPU 3080. But I always get NaNs in the same runtime environment but on GPU 3090.

And I just want to know if it's possible that we have some other plans _**but upgrading TensorRT**_ to make sure the engine is compatible on both 3080 and 3090.

Thanks!

## Environment

**TensorRT Version**: 8.5.2.2

**NVIDIA GPU**: 3090

**NVIDIA Driver Version**: 525.125.06

**CUDA Version**: 11.6

**CUDNN Version**: 8.6

Operating System: linux x86_64

Python Version (if applicable): 3.8.10

Tensorflow Version (if applicable): no

PyTorch Version (if applicable): no

Baremetal or Container (if so, version): Docker version 25.0.4, build 1a576c5

## Relevant Files

**Model link**: sorry but no

## Steps To Reproduce

Infer the 3080-GPU model with Polygraphy in GPU 3090

**Commands or scripts**:

Sorry but no

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: No

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`): Yes, on Polygraphy

**Comment by lix19937** [comment]
> But I always get NaNs in the same runtime environment but on GPU 3090.

can you upload the build log with `--verbose` ?

**Comment by Vegeshp** [comment]
> can you upload the build log with --verbose ?

Sorry, I'm not allowed to provide the verbose build log here because of our security policy. Thanks for the kindness anyway.

But I can provide the layer types here.

```
Layer(NoOp)
Layer(Constant)
Layer(Reformat)
Layer(PluginV2)
Layer(PointWise)
Layer(Shuffle)
Layer(ElementWise)
Layer(CaskConvolution)
Layer(Slice)
Layer(CaskPooling)
Layer(CudaSoftMax)
```

Is any layer type related to the TensorRT cross-device (even with the same compute capability) issues or not? Any help or advice is greatly appreciated.

**Comment by lix19937** [comment]
Hh, use binary method and control variable method for localization.

**Comment by Vegeshp** [comment]
Hmm, I think TensorRT did not guarantee the compatiblity between different GPU types with the same cc. And I think we need another workaround to make things compatible. Thanks anyway.
