### ISSUE TITLE
Engine built failure of TensorRT 10.5 when running kSTRONGLY_TYPED  model on GPU A10

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT#4228]
## Description

When weight streaming (kSTRONGLY_TYPED/setWeightStreamingBudgetV2) is on,  llama2-fp16 report: 

[error][10/29 07:16:27][: ]: 3: [builder.cpp::createNetworkBuildConfig::485] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::createNetworkBuildConfig::485, condition: !config.getFlag(BuilderFlag::kFP16) )

## Environment

 
**TensorRT Version**: 10.2/10.5

**NVIDIA GPU**: A10, 3080TI

What's the possible reason, and where should I start fixing it from?

**Comment by yuanyao-nv** [comment]
Can you please add more detailed repro instructions?

**Comment by tp-nan** [comment]
> Can you please add more detailed repro instructions?


I try to simplify the repro instructions but it is a little complicated.

I tried to remove the plugin inside the model and run with trtexec, it works well:

```
trtexec --stronglyTyped --weightStreamingBudget=1 --onnx=examples/llama2/model_files/batchful.onnx  --allowWeightStreaming --fp16 
```


The model is indeed exported with the following file and instruction:

https://github.com/torchpipe/torchpipe/blob/149030b081db29958b0286ad9ebc632543f0d364/examples/llama2/export_llama2.py#L197

```
    python export_llama2.py --model meta-llama/Llama-2-7b-chat-hf --output_dir model_files/ --export batchful --num_layers $2 --device cuda
```

So it may be impossible for you to directly run the onnx.

The plugin's c++ code is here:
https://github.com/torchpipe/torchpipe/blob/develop/examples/llama2/cpp/TorchPlugin.cpp

Thanks again for your attention.

**Comment by tp-nan** [comment]
After removing `config->setFlag(nvinfer1::BuilderFlag::kFP16);`, the issue was resolved. By the way, I'm wondering if weight streaming will no longer require strongly typed models in the future.
