### ISSUE TITLE
How to convert model.onnx and model.onnx_data to trt model

### ISSUE THREAD

**Issue by Sdamuu** [NVIDIA/TensorRT#4235]
I want to convert the onnx model to trt model, but the onnx model is larger than 2Gb, so it has two files,  'model.onnx' and 'model.onnx_data'，how can I convert the model to trt by using `trtexec` ? or python scripts ?  
onnx model like [multilingual-e5-large](https://huggingface.co/intfloat/multilingual-e5-large/tree/main/onnx)  

model like:  
![Image](https://github.com/user-attachments/assets/d8f5e45c-bcb4-49b7-94cb-3c5918986570)

thank a lot, looking forward to your reply!

**Comment by lix19937** [comment]
You can see https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#loading-an-onnx-model-with-external-data, or use polyagaphy to load model.onnx_data fusion to model.onnx, then get a new onnx.  

```py

graph = gs.import_onnx(onnx.load("model.onnx"))

model = gs.export_onnx(graph)

from onnx.external_data_helper import convert_model_to_external_data

convert_model_to_external_data(model, location="model.onnx_data")

onnx.save(model, "model_fusion.onnx")
```

then use trtexec as normal.

**Comment by Sdamuu** [comment]
> You can see https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#loading-an-onnx-model-with-external-data, or use polygraphy to load model.onnx_data fusion to model.onnx, then get a new onnx.
> 
> graph = gs.import_onnx(onnx.load("model.onnx"))
> 
> model = gs.export_onnx(graph)
> 
> from onnx.external_data_helper import convert_model_to_external_data
> 
> convert_model_to_external_data(model, location="model.onnx_data")
> 
> onnx.save(model, "model_fusion.onnx")
> then use trtexec as normal.

thanks a lot, it works!
