### ISSUE TITLE
dynamic shape with stepsize

### ISSUE THREAD

**Issue by linkedqueue** [NVIDIA/TensorRT#4247]
Hi, we get a problem where a torch model only support image shapes which are multiple of 16, and the input shape is dynamic. But tensorrt dynamic shape only support min, opt and max, and it seems to have a step-size of 1 in the range of [min,max], which would cause the illegal input for my network. I wonder how to deal with it, i search the nvidia document and google, no answer. 
Any suggestions? Thanks a lot

**Comment by lix19937** [comment]
Can you upload the dynamic onnx ?

**Comment by linkedqueue** [comment]
> Can you upload the dynamic onnx ?

Hi, I solve it by using shape operator in onnx，thanks for the advice.
