### ISSUE TITLE
[Request Request] SetTensorAddress for plugin's input/outputs

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT#4252]
Hi, Is it possible for a plugin to have a SetTensorAddress for the plugin's inputs/outputs? Or  to have an IPluginOutputAllocator to manage its input/output addresses?  Supporting this feature would be beneficial for users to manage the input/output memory locations of the plugin themselves.

**Comment by lix19937** [comment]
If plugin is inside of model, the address controled by trt, if plugin is at edge of model, user can control it.
