### ISSUE TITLE
TensorRT8.6 与cuDNN9.0，在部署时卷积存在差异

### ISSUE THREAD

**Issue by chyang0822** [NVIDIA/TensorRT#4264]
最近在对比C++ 和 Python版本的差异，发现了一个问题；
       在使用cudnn后，conv的结果精度差异较大，关闭cudnn后，基本和我手写的卷积没有差异；
       后面查看Pytorch源码，发现问题cudnn在选择卷积算法时默认CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM，当选择CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM，卷积结果和我手写的卷积没有差异。Tensorrt8.6也与我手写的卷积没有差异。问题来了：为什么CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM和CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM会有差异？理论上做优化，不能影响计算结果，这不是基本常识吗？由于cudnn不开源，无法知道内部细节。

**Comment by poweiw** [comment]
> User has a question about an accuracy gap in pytorch convolution between `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM` and `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM`. 

It's not uncommon to see accuracy gaps especially when running with optimizations, as long as the gap is acceptable. Since this repo is about TensorRT, you might get further help regarding cudnn in https://forums.developer.nvidia.com/c/ai-data-science/deep-learning/cudnn.
