### ISSUE TITLE
Native TensorFlow is >6 times faster than TensorRT

### ISSUE THREAD

**Issue by olesalscheider** [NVIDIA/TensorRT#427]
## Description

My neural network runs much faster with native TensorFlow compared to a TensorRT optimized model:

Images per second with native TF: 4.785973
Images per second with TRT: 0.712366

I get these numbers on a TITAN X, but I can observe the same effect on a Titan V.

## Environment

**TensorRT Version**: 7.0.0
**GPU Type**: TITAN X (Pascal)
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5.32
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: nightly/master (8869157e7f)
**PyTorch Version (if applicable)**: -
**Baremetal or Container (if container which image + tag)**: Baremetal

## Relevant Files

https://ft.fzi.de/d=e4fa141418484b9e94039230cd7560de

## Steps To Reproduce

Download the model and the test script from the link above, extract the archive and run `test.py`. Make sure that you have the libraries mentioned in the environment section.

**Comment by rmccorm4** [comment]
Hi, this is more of a TF-TRT question. Seems like the TF-TRT graph creates many (~17) subgraphs (TRT_EngineOps), rather than one or a couple larger subgraphs, which is probably related to how slow it is.

I would try asking this in https://github.com/tensorflow/tensorrt
