### ISSUE TITLE
Disable/Enable graph level optimizations

### ISSUE THREAD

**Issue by banu-narayana-dnjp** [NVIDIA/TensorRT#4275]
I have noticed that the several graph optimizations like operator fusions, etc are occured by default while inferencing in TensorRT. 
Is there any way to disable them or does TRT have levels of graph ops just as in ONNXRuntime?
Because I want to compare the performaces between before opt and after opt, for ex.

**Comment by lix19937** [comment]
mark all with polygrahy tool.

**Comment by asfiyab-nvidia** [comment]
@banu-narayana-dnjp Unfortunately, TensorRT API doesn't support disabling fusions at the moment.

**Comment by banu-narayana-dnjp** [comment]
Thank you @asfiyab-nvidia and @lix19937 for your clarifications. Just one question, does MARK_ALL with the polygraphy tool result in any change in the final score(considering it prevents the fusions)?

**Comment by lix19937** [comment]
Mainly to prevents the fusions.
