### ISSUE TITLE
Is there a plan to support more recent PTQ methods for INT8 ViT?

### ISSUE THREAD

**Issue by dedoogong** [NVIDIA/TensorRT#4276]
## Description

there is only traditional max, entropy calibrator but there are already so many PTQs like Adaround, Qdrop, FQ-ViT for int8 ViT PTQ.
wiil TRT support more recent PTQs for int8 ViT in future?

## Environment

**TensorRT Version**:

**NVIDIA GPU**:

**NVIDIA Driver Version**:

**CUDA Version**:

**CUDNN Version**:

Operating System:

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by lix19937** [comment]
see trt-llm
