### ISSUE TITLE
sampleUffFasterRCNN sample model for training and deployment

### ISSUE THREAD

**Issue by hashishoya** [NVIDIA/TensorRT#436]
Hello,

In the "sampleUffFasterRCNN" directory a faster_rcnn model was available in .pb format. I trained a similar model using Nvidia Transfer Learning Toolkit and got the model in .tlt format. Is it possible to convert this model to .pb format and then typically to .uff?

If not, how can I mimic the same architecture followed to deploy faster rcnn with TensorRT? Since it would be difficult to deploy a model trained with tensorflow object detection api with TensorRT, please provide a source code for the trianing of the frozen network used in this sample example. 

Thanks.

**Comment by facerless** [comment]
I have same question for how to convert faster rcnn tlt to pb.

**Comment by hashishoya** [comment]
@facerless simply you can't, check [my post](https://forums.developer.nvidia.com/t/nvidia-transfer-learning-toolkit-tlt-to-pb-uff-file-deployment/115611/11) on nvidia forum

**Comment by zhongjiahui1995** [comment]
I also need the source code to train faster rcnn ,please!

**Comment by zhongjiahui1995** [comment]
> Hello,
> In the "sampleUffFasterRCNN" directory a faster_rcnn model was available in .pb format. I trained a similar model using Nvidia Transfer Learning Toolkit and got the model in .tlt format. Is it possible to convert this model to .pb format and then typically to .uff?
> If not, how can I mimic the same architecture followed to deploy faster rcnn with TensorRT? Since it would be difficult to deploy a model trained with tensorflow object detection api with TensorRT, please provide a source code for the trianing of the frozen network used in this sample example.
> Thanks.

did you solve the problem? If you did , please could you give me the source code link? thanks!!

**Comment by facerless** [comment]
@zhongjiahui1995 ,I  abandon faster rcnn.
you can try sampleUFFMaskRCNN，you can train model  on keras, and conver hd5 to uff and trt engine.

**Comment by rajeevsrao** [comment]
@hashishoya AFAIK its not possible to convert the TLT model to tensorflow pb. You might want to ask in the [TLT forums ](https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/transfer-learning-toolkit/17) to be sure.

We don't have a sample to share for fasterRCNN based on TF-ObjDet API just yet (as of rel-7.2). Please watch the OSS releases for updates.

**Comment by overclock98** [comment]
> Hello,
> 
> In the "sampleUffFasterRCNN" directory a faster_rcnn model was available in .pb format. I trained a similar model using Nvidia Transfer Learning Toolkit and got the model in .tlt format. Is it possible to convert this model to .pb format and then typically to .uff?
> 
> If not, how can I mimic the same architecture followed to deploy faster rcnn with TensorRT? Since it would be difficult to deploy a model trained with tensorflow object detection api with TensorRT, please provide a source code for the trianing of the frozen network used in this sample example.
> 
> Thanks.

@hashishoya can you please share the location of "sampleUffFasterRCNN directory a faster_rcnn model was available in .pb format" mentioned above?

thanks.
