### ISSUE TITLE
dynamic shape for uffparser

### ISSUE THREAD

**Issue by Tsingjie89** [NVIDIA/TensorRT#438]
## Description

samples for dynamic shape are all on onnx models,  how can I use UffParser  to parse model which has dynamic shape? uffparser.parse will fail if shape of register_input is fixed!

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 418.56
**CUDA Version**: 10.0
**CUDNN Version**:  7.6.5.32
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**: 3.6.4
**TensorFlow Version (if applicable)**: 1.13.2

**Comment by rmccorm4** [comment]
Hi @Tsingjie89 ,

The UFF parser does not support dynamic shape or explicit batch. Please migrate to using ONNX parser if you'd like to take advantage of dynamic shape.
