### ISSUE TITLE
Different speed up ration with Half-precision

### ISSUE THREAD

**Issue by RizhaoCai** [NVIDIA/TensorRT#444]
Hello, 

I am using TensorRT 6.0 on TX2 to speed up my Object Detection model, especially with Half-Precision.

However, I got something strange.

I am using RFB-VGG-Net (VGG-16 as the backbone) for object detection. 
This RFB-VGG mode has Param=33.74 M  with MACs= 59.61 G.

To improve speed, I change the backbone from VGG-16 to the latest state-of-the-art light-weight backbone Ghost-Net (https://github.com/iamhankai/ghostnet.pytorch).  Let call this model 'RFB-GHOST' and this model has Param=22.74 M  with MACs= 23.84  G.

But the testing results are very strange.

For RFB-VGG, the speed is 2.9 FPS and 4.3 FPS with PyTorch 1.1 and TensorRT 6.0 respectively.  
For RFB-GHOST, the speed is 4.2 FPS and 4.9 FPS with PyTorch 1.1 and TensorRT 6.0 respectively.

It seems that RFB-GHOST is better.
However, when I enable  FP16 mode to build the engines, I got 6.7 FPS for RFB-VGG and 5.3 FPS for RFB-GHOST.

RFB-GHOST is slower than RFB-VGG? 
Is there something wrong?

The way I adapt GhostNet to my RFB-Net is to change every traditional convolutional layer in the VGG-16 backbone to a Ghost module.
The Ghost Module, somehow similar to MobileNet, includes the separable convolution (a sequence of a depth-wise conv and point-wise conv).

Previously, I tried to replace the traditional convolutional layer in the VGG-16 with a separable convolution module from Mobile-Net (Let's call the model RFB-MBN). The speed is 5.1 and 7.9 FPS with TensorRT and TensorRT-FP16, which was faster than the previous RFB-VGG.

How can I find out the reason why RFB-GHOST is slower than RFB-VGG under FP16 mode?
If the separable convolution (group conv) is slower than vanilla conv in implementation, why RFB-MBN can be faster than the other?

**Comment by rmccorm4** [comment]
Hi @RizhaoCai ,

The speed-up gained from FP16 is dependent on the network architecture. It's possible that the Ghostnet model contains more ops that don't support fast FP16 implementations, and therefore aren't chosen.

Can you parse both of your networks with VERBOSE logging on, and share the logs?

With `trtexec`, that would be as simple as something like this:

```
trtexec --onnx=model1.onnx --fp16 --verbose > model1.log
trtexec --onnx=model2.onnx --fp16 --verbose > model2.log
```

This might provide some more insight.

**Comment by RizhaoCai** [comment]
> Hi @RizhaoCai ,
> 
> The speed-up gained from FP16 is dependent on the network architecture. It's possible that the Ghostnet model contains more ops that don't support fast FP16 implementations, and therefore aren't chosen.
> 
> Can you parse both of your networks with VERBOSE logging on, and share the logs?
> 
> With `trtexec`, that would be as simple as something like this:
> 
> ```
> trtexec --onnx=model1.onnx --fp16 --verbose > model1.log
> trtexec --onnx=model2.onnx --fp16 --verbose > model2.log
> ```
> 
> This might provide some more insight.

Hello @rmccorm4 


I have parsed both the RFB-VGG and RFB-GHOST models in the way you suggested.
The log files are on [google drive](https://drive.google.com/drive/folders/1uBPRBQfpHLT6vMC9EsHmteKIWR4N-NrM). 

Thank you a lot

**Comment by RizhaoCai** [comment]
@rmccorm4 
For your information, these are some snapshots showing how I change the backbone from VGG-16 to GhostNet

The [Ghost Module](https://github.com/iamhankai/ghostnet.pytorch/blob/master/ghost_net.py) I employ is defined as : 

```class GhostModule(nn.Module):
    def __init__(self, inp, oup, kernel_size=1, ratio=2, dw_size=3, stride=1, relu=True):
        super(GhostModule, self).__init__()
        self.oup = oup
        init_channels = math.ceil(oup / ratio)
        new_channels = init_channels*(ratio-1)

        self.primary_conv = nn.Sequential(
            nn.Conv2d(inp, init_channels, kernel_size, stride, kernel_size//2, bias=False),
            nn.BatchNorm2d(init_channels),
            nn.ReLU(inplace=True) if relu else nn.Sequential(),
        )

        self.cheap_operation = nn.Sequential(
            nn.Conv2d(init_channels, new_channels, dw_size, 1, dw_size//2, groups=init_channels, bias=False),
            nn.BatchNorm2d(new_channels),
            nn.ReLU(inplace=True) if relu else nn.Sequential(),
        )

    def forward(self, x):
        x1 = self.primary_conv(x)
        x2 = self.cheap_operation(x1)
        out = torch.cat([x1,x2], dim=1)
        return out[:,:self.oup,:,:]```


This is the definition of the VGG backbone. I replace `torch.nn.Conv2d` with `GhostModule` 
```
def vgg(cfg, i, batch_norm=False):
    layers = []
    in_channels = i

    for v in cfg:
        if v == 'M': 
            layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
        elif v == 'C':
            layers += [nn.MaxPool2d(kernel_size=2, stride=2, ceil_mode=False)]
        else:
            # !!! Change torch.nn.Conv2d to GhostModule
            #conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1)
            conv2d = GhostModule(in_channels,v, kernel_size=3, padding=1, ratio=4,relu=False)
          
            if batch_norm:
                layers += [conv2d, nn.BatchNorm2d(v), nn.ReLU(inplace=True)]
            else:
                layers += [conv2d, nn.ReLU(inplace=True)]
            in_channels = v

    pool5 = nn.MaxPool2d(kernel_size=3, stride=1, padding=1)
    conv6 = nn.Conv2d(512, 1024, kernel_size=3, padding=6, dilation=6)
    conv7 = nn.Conv2d(1024, 1024, kernel_size=1)
    layers += [pool5, conv6, nn.ReLU(inplace=True), conv7, nn.ReLU(inplace=True)]

    return layers

```

**Comment by rmccorm4** [comment]
I wrote a quick script to parse the logs for what I think is the useful info. Just based on the logs, I see this:
```
ryan@volta1601:/tmp$ python3 parse_fp16.py rfb-vgg.txt 
Num FP16 Tactics chosen: 19
Num other tactics chosen: 340

ryan@volta1601:/tmp$ python3 parse_fp16.py rfb-ghost.txt 
Num FP16 Tactics chosen: 59
Num other tactics chosen: 1753
```

So for the VGG engine, there seems to be both [1] less overall ops (more fused ops?), and [2] a higher percentage of those ops are fp16. 

Though since there are less overall ops, I'm surprised the FP32 engine isn't faster. Maybe I'm misunderstanding the logs.

---

@RizhaoCai is it possible to share the ONNX models as well? Random weights are fine if you don't want to share the weights.

It'll probably help me get a better answer as to what's happening in between.

**Comment by RizhaoCai** [comment]
> I wrote a quick script to parse the logs for what I think is the useful info. It basically just looks for the lines containing "Fastest Tactic: %d", and then checks if that %d is one of the FP16 tactics also found in the log.
> 
> Just based on the logs, I see this:
> 
> ```shell
> $ python3 parse_fp16.py rfb-vgg.txt 
> Num FP16 Tactics chosen: 19
> Num other tactics chosen: 340
> 
> $ python3 parse_fp16.py rfb-ghost.txt 
> Num FP16 Tactics chosen: 59
> Num other tactics chosen: 1753
> ```
> 
> So for the VGG engine, there seems to be both [1] less overall ops (more fused ops?), and [2] a higher percentage of those ops are fp16.
> 
> Though since there are less overall ops, I'm surprised the FP32 engine isn't faster. Maybe I'm misunderstanding the logs.
> 
> @RizhaoCai is it possible to share the ONNX models as well? Random weights are fine if you don't want to share the weights.
> 
> It'll probably help me get a better answer as to what's happening in between.

Hello @rmccorm4 
The two ONNX models are updated to [google drive](https://drive.google.com/open?id=1uBPRBQfpHLT6vMC9EsHmteKIWR4N-NrM)

**Comment by RizhaoCai** [comment]
Hello @rmccorm4 
Sorry that I gave some wrong info in the problem [description](https://github.com/NVIDIA/TensorRT/issues/444#issue-585958700).

To make more comparisons, I also updated the [RFB-MBN](https://drive.google.com/open?id=1uBPRBQfpHLT6vMC9EsHmteKIWR4N-NrM), of which the params=20.70M and MACs = 17.14 G 

> RFB-VGG: Param=33.74M and  MACs= 59.61 G.
> RFB-GHOST:  Param=22.74M and MACs= 23.84 G.
On TX2, the FPS is 5.4, 8.4 and 9.8 for PyTorch, TRT-FP32 and TRT-FP16 respectively, not 5.1 and 7.9 as mentioned early.
> FPS evluated on TX2
> RFB-VGG: PyTorch=2.9, TRT-FP32=4.3,  TRT-FP16=6.7, 
> RFB-GHOST: PyTorch=4.2, TRT-FP32=4.9, TRT-FP16=5.3 

We can see that, although Param and MACs are close for RFB-GHOST, RFB-MBN, the gained from TRT-FP32 and TRT-FP16 are quite different. Does the way how GHOST module implemented matter?

The way I implement RFB-MBN is to replace nn.Conv2d with separable conv (MobileNet V1 block)
```python
# MBN module
def vgg(cfg, i, batch_norm=False):
    layers = []
    in_channels = i

    for v in cfg:
        if v == 'M': 
            layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
        elif v == 'C':
            layers += [nn.MaxPool2d(kernel_size=2, stride=2, ceil_mode=False)]
        else:
            #conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1)
            # !!! Separable convolution from MobileNet
            conv2d = nn.Sequential(
              nn.Conv2d(in_channels,in_channels, kernel_size=3, padding=1, bias=False, groups=in_channels), # Depth-Wise Conv
              nn.BatchNorm2d(in_channels),
              nn.ReLU(inplace=True),
              nn.Conv2d(in_channels, v, 1, 1, 0, bias=False), # Pixel-Wise Conv
            )
            if batch_norm:
                layers += [conv2d, nn.BatchNorm2d(v), nn.ReLU(inplace=True)]
            else:
                layers += [conv2d, nn.ReLU(inplace=True)]
            in_channels = v

    pool5 = nn.MaxPool2d(kernel_size=3, stride=1, padding=1)
    conv6 = nn.Conv2d(512, 1024, kernel_size=3, padding=6, dilation=6)
    conv7 = nn.Conv2d(1024, 1024, kernel_size=1)
    layers += [pool5, conv6, nn.ReLU(inplace=True), conv7, nn.ReLU(inplace=True)]

    return layers
```
.

**Comment by rmccorm4** [comment]
Hi @RizhaoCai ,

Sorry it's not immediately clear to me why VGG outperforms GHOST with FP16. I wouldn't necessarily be concerned this is a bug or something, it may just be that the larger layers of VGG benefit more from FP16 kernels than comparatively smaller ones like in GHOST.

If you want to find out more details, I would suggest learning how to use tools like `nvprof` and NSight systems. There are some pretty good blogs on it, such as: https://devblogs.nvidia.com/transitioning-nsight-systems-nvidia-visual-profiler-nvprof/ and https://devblogs.nvidia.com/migrating-nvidia-nsight-tools-nvvp-nvprof/

The simplest thing you could do is try starting with comparing the outputs of something like these:
```
nvprof trtexec --loadEngine=vgg-fp32.engine
nvprof trtexec --loadEngine=ghost-fp32.engine
nvprof trtexec --loadEngine=vgg-fp16.engine
nvprof trtexec --loadEngine=ghost-fp16.engine
```

You may also like using something more visual, so you could export the profiles above using `nvprof -o vgg-fp32.profile trtexec ...` and loading the profile into something like NVVP (NVidia Visual Profiler).

There are lots of tools for this kind of performance analysis.

**Comment by RizhaoCai** [comment]
> Hi @RizhaoCai ,
> 
> Sorry it's not immediately clear to me why VGG outperforms GHOST with FP16. I wouldn't necessarily be concerned this is a bug or something, it may just be that the larger layers of VGG benefit more from FP16 kernels than comparatively smaller ones like in GHOST.
> 
> If you want to find out more details, I would suggest learning how to use tools like `nvprof` and NSight systems. There are some pretty good blogs on it, such as: https://devblogs.nvidia.com/transitioning-nsight-systems-nvidia-visual-profiler-nvprof/ and https://devblogs.nvidia.com/migrating-nvidia-nsight-tools-nvvp-nvprof/
> 
> The simplest thing you could do is try starting with comparing the outputs of something like these:
> 
> ```
> nvprof trtexec --loadEngine=vgg-fp32.engine
> nvprof trtexec --loadEngine=ghost-fp32.engine
> nvprof trtexec --loadEngine=vgg-fp16.engine
> nvprof trtexec --loadEngine=ghost-fp16.engine
> ```
> 
> You may also like using something more visual, so you could export the profiles above using `nvprof -o vgg-fp32.profile trtexec ...` and loading the profile into something like NVVP (NVidia Visual Profiler).
> 
> There are lots of tools for this kind of performance analysis.

Hi, @rmccorm4 
Much appreciate your efforts. I will try to analyze the performance with those tools. Once I find out the reason, I will give the feedback here. And, would you mind sharing the quick script you worte that parses the log?

Thank you a lot.

**Comment by rmccorm4** [comment]
@RizhaoCai 

This was the script to parse verbose logs from TensorRT 6:
```python
import re

with open("fp16.log") as f:
    contents = f.read()

print(len(contents))
fp16_regex = re.compile("^.*Tactic Name:.*fp16.*\n(.*\n)", re.MULTILINE)
results = fp16_regex.findall(contents)
print(results)
if results:
    tokenized = [line.strip().split(" ") for line in results]
    fp16_tactics = set([tokens[4] for tokens in tokenized if len(tokens) >= 5])
    print(fp16_tactics)


with open("fp16.log") as f:
    num_fp16 = 0
    num_other = 0
    for line in f:
        line = line.lower()
        if "fastest tactic:" in line:
            tokens = line.strip().split(" ")
            if len(tokens) >= 5:
                tactic = tokens[5]
                if tactic in fp16_tactics:
                    num_fp16 += 1
                else:
                    num_other += 1

    print("Num FP16 Tactics chosen:", num_fp16)
    print("Num other tactics chosen:", num_other)
```

In TensorRT 7, the verbose logs have a section that starts with `Engine Layer Information`, which you can parse similarly with something like this:
```
# Num total engine layers in "vgg" fp16 engine
root@a08d589b3f17:/mnt# cat rfb-vgg-fp16.log | grep -e "Layer(.*(" | wc -l
147

# Num total engine layers using fp16 in "vgg" fp16 engine (could also be Float->Half, or Half->Float)
root@a08d589b3f17:/mnt# cat rfb-vgg-fp16.log | grep -e "Layer(.*Half(" | wc -l
123
```

These definitely aren't official ways to analyze the engine or anything, just my way of summarizing some of the info in the logs.

**Comment by rmccorm4** [comment]
Closing this as I don't believe it's a bug. Feel free to share your results when done analyzing 🙂

**Comment by RizhaoCai** [comment]
@rmccorm4 

Hi. I haven't found out the problem.

However, when I am reading the TensorRT docs, I find something interesting.

The [doc ](https://docs.nvidia.com/deeplearning/sdk/tensorrt-best-practices/index.html#optimize-layer) says that 
> Depthwise Separable Convolution
> A depthwise convolution with activation followed by a convolution with activation may sometimes be fused into a single optimized DepSepConvolution layer. The precision of both convolutions must be INT8 and the device computes capability must be 7.2 or later

Then, I check the TensorRT support matrix 
![image](https://user-images.githubusercontent.com/37952703/78874993-cb643a00-7a7f-11ea-8e98-af395d184cfc.png)

The CUDA Compute Capability of Jetson TX2 is 6.2, which is smaller than 7.2. 
Does mean that Depthwise separable convolution is not supported on TX2 as it requires CUDA Compute Capability > 7.2?

**Comment by rmccorm4** [comment]
Hi @RizhaoCai ,

I think that note is saying the layer fusion in that scenario is only supported for CC >= 7.2, but that's not a requirement for the op by itself. You would've likely got some kind of runtime error at worst case if the op wasn't supported at all, but more likely a build-time error.

**Comment by RizhaoCai** [comment]
> Hi @RizhaoCai ,
> 
> I think that note is saying the layer fusion in that scenario is only supported for CC >= 7.2, but that's not a requirement for the op by itself. You would've likely got some kind of runtime error at worst case if the op wasn't supported at all, but more likely a build-time error.

Hi @rmccorm4 

Yeah. So that I thought that, on TX2, the TensorRT did not fuse many depthwise layers for RFB-GHOST and thus I got less speed up gain than RFB-VGG. This is only my guess. 

![image](https://user-images.githubusercontent.com/37952703/78878882-affc2d80-7a85-11ea-9e09-ed9d883cffd4.png)

BTW, should we manually enable fusion? This note seems telling me that I can do the fusion by myself at somewhere to improve performance.

**Comment by rmccorm4** [comment]
In general I believe the builder will do layer fusion for you where possible. You can see some of this in the verbose logs from builder. Off the top of my head I think those links just offer suggestions/best practices of the types of layers to use and how to order them in your model to increase the odds of more layer fusions happening.
