### ISSUE TITLE
about batchedNMSPlugin

### ISSUE THREAD

**Issue by grimoire** [NVIDIA/TensorRT#448]
## Description

the clone() method in batchedNMSPlugin.cpp seems strange.

## Environment

**TensorRT Version**:7.0 
**GPU Type**: 2080ti
**Nvidia Driver Version**: 418
**CUDA Version**: 10.0
**CUDNN Version**: 
**Operating System + Version**: ubuntu18.04
**Python Version (if applicable)**: 3.7.5
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.4.0
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

I am working on transform a pytorch detection model to tensorrt engine.
every thing is fine before I save the engine and load it.
It randomly give me some error log like:
`getPluginCreator could not find plugin BatchedNMS_TRT▒(% version 1`

when I dig into the code , I found the clone() method in batchedNMSPlugin.cpp(177) 
```
IPluginV2Ext* BatchedNMSPlugin::clone() const
{
    auto* plugin = new BatchedNMSPlugin(param);
    plugin->boxesSize = boxesSize;
    plugin->scoresSize = scoresSize;
    plugin->numPriors = numPriors;
    plugin->setPluginNamespace(mNamespace.c_str());
    plugin->setClipParam(mClipBoxes);
    return plugin;
}
```

The clone() set the namespace with mNamespace.c_str(), but it seems that mNamespace has never been assigned before.  the real namespace field should be mPluginNamespace, right?

Did that means that the final plugin name used to search the creator is <plugin_name><name_space>?

**Comment by rmccorm4** [comment]
Hi @grimoire,

I don't know off the top of my head, but sounds related to this PR in case that confirms any suspicions: https://github.com/NVIDIA/TensorRT/pull/443/files

**Comment by grimoire** [comment]
> Hi @grimoire,
> 
> I don't know off the top of my head, but sounds related to this PR in case that confirms any suspicions: https://github.com/NVIDIA/TensorRT/pull/443/files

I got it. 
The clone() use mNamespace.c_str() as namespace, just like the PR you mentioned.
but setPluginNamespace() or getPluginNamespace() use mPluginNamespace instead.
When loading engine from disk  ,clone() will be invoked and corrupted memory in mNamespace will be send to namespace.

Seems a bug. May I send a PR?

**Comment by rmccorm4** [comment]
> May I send a PR?

Please do!
