### ISSUE TITLE
Strange time cost for pytorch and tensorrt.

### ISSUE THREAD

**Issue by ZimingLu** [NVIDIA/TensorRT#449]
Now I am working on CRNN with pytorch and want to use tensorrt7 for inference.
I found one interesting thing. In pytroch, when I use cnn part only, the time cost is for example 37ms. But when I add one layer Bi-lstm to the network, the cnn time cost will be 13ms, and rnn part is about 30ms. So the total time cost is about 43ms. When I use tensorrt7, the cnn part is about 23ms, which is accelerated compared to only cnn part(37ms), and lstm part is about 16ms. So total time cost for tensorrt7 is 39ms. From the final result, we feel that tensorrt does not accelerate the inference. 
It seems that pytorch has done some special accelerations in CRNN(cnn+lstm). So can anyone explain the reason for such phenomenon for me? Or anyone else has met the same problem?

**Comment by rmccorm4** [comment]
Hi @ZimingLu, have you tried to speed up the inference with TensorRT's FP16 builder flag?

**Comment by Hubert2102** [comment]
@rmccorm4 [TensorRT] WARNING: Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
it costs the same time.

**Comment by ZimingLu** [comment]
> Hi @ZimingLu, have you tried to speed up the inference with TensorRT's FP16 builder flag?

My GPU can not support FP16. My question is, why is the accelereation ratio of tenssort smaller than pytorch. Maybe the pytorch's optimization of lstm is better than tensorrt?

**Comment by ll490187880** [comment]
Have you solved the problem? I have also encountered this problem for crnn models. There is no acceleration for lstm module.

**Comment by shen865069799** [comment]
> Have you solved the problem? I have also encountered this problem for crnn models. There is no acceleration for lstm module.

hi, i trained a crnn model with pytorch,and torch.onnx.export to onnx,when i use onnx model to infer with onnxruntime,the result is right,but when i use tensorrt parse onnx model, the result is wrong, and the output of tensorrt parsed is [-1,-1,-1], i think that this is due to lstm，should i modify crnn's lstm layer? i want to now how you can run with tensorr ,thx very much

**Comment by kevinch-nv** [comment]
@ZimingLu @ll490187880 can you provide the models you are running?

**Comment by quietsmile** [comment]
> > Have you solved the problem? I have also encountered this problem for crnn models. There is no acceleration for lstm module.
> 
> hi, i trained a crnn model with pytorch,and torch.onnx.export to onnx,when i use onnx model to infer with onnxruntime,the result is right,but when i use tensorrt parse onnx model, the result is wrong, and the output of tensorrt parsed is [-1,-1,-1], i think that this is due to lstm，should i modify crnn's lstm layer? i want to know how you can convert model and run with tensorr ,thx very much

请问你这个问题解决了么？最后加速明显么？谢谢

**Comment by ttyio** [comment]
Closing since there is no repro provide for debug, please reopen if you still have question
