### ISSUE TITLE
Could IBuilder create multi INetworkDefinition?

### ISSUE THREAD

**Issue by lcxywfe** [NVIDIA/TensorRT#45]
Could IBuilder create multi INetworkDefinition? And could IBuilder build an ICudaEngine used an INetworkDefinition which createt by another IBuilder?

In the samples, it is one IBuilder corresponding one INetworkDefinition and one ICudaEngine,
but i used one IBuilder to create multi INetworkDefinition and deliver the networks to other builders, it seems to work fine.

**Comment by rajeevsrao** [comment]
Yes, you can generate multiple networks (and engines thereof) from a single builder object. Sharing a network across builders is not recommended.
