### ISSUE TITLE
Cudnn Error in execute: 8

### ISSUE THREAD

**Issue by FlYWMe** [NVIDIA/TensorRT#452]
./sample_mnist
Building and running a GPU inference engine for MNIST
ERROR: cuda/cudaConvolutionLayer.cpp (163) - Cudnn Error in execute: 8
ERROR: cuda/cudaConvolutionLayer.cpp (163) - Cudnn Error in execute: 8

it happen a cudnn error just as above when i run the examples in TITAN2080TI device.
GPU type - 2080 TI
CUDA version -9.0
CUDNN version - 7.3.1
TRT version - 5.0.2.6

what it heppen?
THANKS!

**Comment by hzq-zjm** [comment]
Hi,i met the same issue,could you tell me how to solve it . ths a lot!

**Comment by FlYWMe** [comment]
maybe version mismatch between Cudnn and TensorRT


发自我的iPhone

------------------ Original ------------------

**Comment by fantasyplus** [comment]
have you solved that?So it'a version mismatch problem,I met the same issue too.
