### ISSUE TITLE
Can't no get bert-tensorrt:latest

### ISSUE THREAD

**Issue by YongtaoHuang1994** [NVIDIA/TensorRT#456]
## Description

When I implement BERT/python/create_docker_container.sh, the log shows as: 
**unauthorized: authentication required
Unable to find image 'bert-tensorrt:latest' locally
docker: Error response from daemon: pull access denied for bert-tensorrt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.**
What are the username and pwd. Where can I get them? 
Where should I put my  the username and pwd in the script?

## Environment

**TensorRT Version**: 6.0
**GPU Type**: 1080TI
**Nvidia Driver Version**: 438
**CUDA Version**: 10.1
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by kevinch-nv** [comment]
You may have to run `docker/build.sh` in the demo/BERT folder first to generate the container locally.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
