### ISSUE TITLE
TensorRT cost more time than pytorch 

### ISSUE THREAD

**Issue by pageedward** [NVIDIA/TensorRT#458]
## Description
use tensorRt convert pytorch FPN，but tensorRT inference time more than pytorch , it is weird.
input tensor is float32 and dynamic size，time comparison way and result as followed:
![image](https://user-images.githubusercontent.com/26244036/77821718-54e24680-7127-11ea-9f35-3597ce80f831.png)
![image](https://user-images.githubusercontent.com/26244036/77821724-64618f80-7127-11ea-9c40-1f3181ae9df2.png)

![image](https://user-images.githubusercontent.com/26244036/77821858-5c561f80-7128-11ea-8bd4-91b9e4191064.png)

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080ti
**Nvidia Driver Version**: 384.130
**CUDA Version**: 9.0.176
**CUDNN Version**: 7.5.1
**Operating System + Version**: ubuntu16.04
**Python Version (if applicable)**: python3.5.2
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.1.0
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

https://github.com/pageedward/junecthe-126.com

**Comment by blacksailer** [comment]
Hi! Can you test your TensorRT inference on CUDA 10.1 or higher? Maybe it's the reason

**Comment by dhlrd** [comment]
have you solved this problem？i encounter this problem too.

**Comment by kevinch-nv** [comment]
@pageedward is it possible to provide the network you are running?

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
