### ISSUE TITLE
TensorRT verison support torch verision list?

### ISSUE THREAD

**Issue by Stephenfang51** [NVIDIA/TensorRT#463]
anyone can give a list about what verison of TensorRT support what version of torch

I only know TRT6 did not support torch1.3 up

**Comment by rmccorm4** [comment]
Aside from the issue with TensorRT 6 + PyTorch 1.3 - I don't think there is an official support matrix. It's mostly a matter of the ONNX graphs generated by PyTorch being supported by TensorRT. This can depend on the graph/ops used in your PyTorch model as well.

If you find any versions that don't seem to work, please share here to help others as well.
