### ISSUE TITLE
TensorRT7  infer time is too long with dynamic shape

### ISSUE THREAD

**Issue by sanggehouzhihoujue** [NVIDIA/TensorRT#466]
## Description
When using the dynamic shape for inference, the infer time is much longer in C++ interface compared with not using the dynamic shape.
Do I have to create the Preprocessor Engine before the Prediction Engine?
I only create the Prediction Engine with the onnx file from yolo-python-sample which is generated dynamically.
The code is followed the #437,and the infer result is right.Only the infer time is too long.

## Environment

**TensorRT Version**: 7
**GPU Type**: 1080ti
**Nvidia Driver Version**:  410.78
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**:  Ubuntu16.04

**Comment by rmccorm4** [comment]
Hi @sanggehouzhihoujue ,

Can you share your inference script so I can see if anything looks like a potential bottleneck, and how you're timing it?
