### ISSUE TITLE
How to deal with multiple outputs? Got core dump but with no core file.

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#468]
What changes should I make to add dump output in trt5.0.2 sample code trtexec.cpp like in the master branch trtexec.cpp?

**Comment by JingyuQian** [comment]
Hi @Edwardmark,
Can you be more specific about the problem of multiple outputs?

**Comment by Edwardmark** [comment]
@JingyuQian I solved the multiple outputs issue, but I have problem of converting input image to float16, could you tell me how to convert opencv mat data to float 16 to do half precision inference? Any code eample is appreciated. Thanks in advance.

**Comment by JingyuQian** [comment]
@Edwardmark from my experience (and correct me if I'm wrong) you don't need to explicitly convert input image to float16. Half-precision mode means 1) your hardware platform supports fp16; 2) the network uses fp16 during calculation. But you can still input float32/uint8 image as you like. 

Take a look at this: [https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#enable_fp16_c](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#enable_fp16_c) 

> Weights can be specified in FP16 or FP32, and they will be converted automatically to the appropriate precision for the computation.

**Comment by Edwardmark** [comment]
@JingyuQian I use the following code to do inference in FP16 model with engine file produced by torch2trt using python, but the output value is quite different and seems wrong or overflow, could you help me?  Thanks.   
`#include <algorithm>
#include <assert.h>
#include <cmath>
#include <cuda_runtime_api.h>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <sys/stat.h>
#include <time.h>
#include <opencv2/opencv.hpp>
#include <typeinfo>

#include "NvInfer.h"
#include "common.h"
#include "buffers.h"
#include "half.h"

#define DebugP(x) std::cout << "Line" << __LINE__ << "  " << #x << "=" << x << std::endl

using namespace nvinfer1;


static const int INPUT_H = 640;
static const int INPUT_W = 640;
static const int INPUT_C = 3;
static Logger gLogger;

const vector<string> inputTensorNames = {"input_0"};
const vector<string> OUTPUT_BLOB_NAMES = {"output_0", "output_1", "output_2", "output_3",
                                         "output_4", "output_5", "output_6", "output_7",
                                         "output_8", "output_9", "output_10", "output_11",
                                         "output_12", "output_13", "output_14", "output_15",
                                         "output_16", "output_17"};

const std::string engine_path = "/app/model/pbox_titanX.engine";
const int batchSize = 1;

std::map <std::string, Dims> tensor_dim;
std::map <std::string, int> tensor_size;

inline int volume(Dims dims) {
    return std::accumulate(dims.d, dims.d + dims.nbDims, 1, std::multiplies<int>());
}

void doInference(ICudaEngine& engine, float* input, float** outputs, int batchSize) {
    IExecutionContext* context = engine.createExecutionContext();
    std::shared_ptr<ICudaEngine> emptyPtr{};
    std::shared_ptr<ICudaEngine> aliasPtr(emptyPtr, &engine);
    samplesCommon::BufferManager buffers(aliasPtr, batchSize);
    // processInput, copy each pixel to hostDataBuffer
    float* hostDataBuffer = static_cast<float*>(buffers.getHostBuffer(inputTensorNames[0]));
    for (int i = 0; i < INPUT_H * INPUT_W; i++) {
        hostDataBuffer[i] = float(input[i]);
        std::cout << hostDataBuffer[i] << ",";
    }
    // Memcpy from host input buffers to device input buffers
    buffers.copyInputToDevice();
    bool status = context->execute(1, buffers.getDeviceBindings().data());
    assert(status);
    // Memcpy from device output buffers to host output buffers
    buffers.copyOutputToHost();
    int nbBindings = engine.getNbBindings();
    for (int i = 0; i < nbBindings; i++) {
        if (!engine.bindingIsInput(i)) {
            const char* tensorName = engine.getBindingName(i);
            Dims tensorDims = engine.getBindingDimensions(i);
            tensor_dim[tensorName] = tensorDims;
            tensor_size[tensorName] = volume(tensorDims);
            
            std::cout << "This output tensor is " << tensorName << ":" << std::endl;
            
            std::cout << "[" << 1;
            for (int i = 0; i < tensorDims.nbDims; i++)
                std::cout << ", " << tensorDims.d[i];
            std::cout << "]" << std::endl;
            std::cout << "size:" << tensor_size[tensorName] << std::endl;
            
            //buffers.dumpBuffer(std::cout, tensorName);
            std::cout << "inference data type" << int(engine.getBindingDataType(i)) << std::endl;
            float* output = static_cast<float*>(buffers.getHostBuffer(tensorName));
            for(int i = 0; i < tensor_size[tensorName]; ++i) 
                std::cout << output[i] << ",";
            std::cout << std::endl;
            outputs[i] = output;
        }
    }
}

void resize_image(cv::Mat im, cv::Mat& im_padding, vector<double>& ratios) {
    int h = im.size().height;
    int w = im.size().width;
    if(max(h, w) <= 600) {
        im_padding = im;
        ratios.push_back(0.0);
        ratios.push_back(0.0);
        return;
    }
    double ratio = INPUT_H * 1.0 / w;
    if(ratio * h  > INPUT_H) {
        ratio = INPUT_H * 1.0 / h;
    }
    
    int resized_w = (int)(ratio * w);
    int resized_h = (int)(ratio * h);
    
    cv::resize(im, im, cv::Size(resized_w, resized_h));
   
    im_padding = cv::Mat(INPUT_H, INPUT_W, CV_8UC3, cv::Scalar(0, 0, 0));
    
    // center resized image
    int x_padding = (INPUT_W - resized_w) / 2;
    int y_padding = (INPUT_H - resized_h) / 2;

    cv::Mat aux = im_padding.rowRange(y_padding, y_padding + resized_h).colRange(x_padding, x_padding + resized_w);
    //cv::imwrite("test.png", aux); 
    
    // you are pointing to roi region
    im.copyTo(aux);
    
    //cout << x_padding * 1.0 / input_geometry_.width << endl;
    //cout << y_padding * 1.0 / input_geometry_.height << endl;
    ratios.push_back(x_padding * 1.0 / INPUT_W);
    
    ratios.push_back(y_padding * 1.0 / INPUT_H);
    
}

// hwc to chw
float* normal(cv::Mat img) {
    float * data;
    ofstream myfile;
    myfile.open("img_norm.txt");
    data = (float*)calloc(img.rows*img.cols * 3, sizeof(float));
    for (int c = 0; c < 3; ++c) {
        for (int i = 0; i < img.rows; ++i) { 
            cv::Vec3f *p1 = img.ptr<cv::Vec3f>(i);
            for (int j = 0; j < img.cols; ++j)  {
                //cout << float(p1[j][c]) << ",";
                myfile << float(p1[j][c])<<",";
                data[c * img.cols * img.rows + i * img.cols + j] = float(p1[j][c]);  
            }
        }   
    }
    myfile << std::endl;
    myfile.close();
    return data;
}

static ICudaEngine* createEngine()
{
    ICudaEngine* engine;
    std::vector<char> trtModelStream;
    size_t size{0};
    std::ifstream file(engine_path, std::ios::binary);
    if (file.good()) {
        file.seekg(0, file.end);
        size = file.tellg();
        file.seekg(0, file.beg);
        trtModelStream.resize(size);
        file.read(trtModelStream.data(), size);
        file.close();
    }
    IRuntime* infer = createInferRuntime(gLogger);
    engine = infer->deserializeCudaEngine(trtModelStream.data(), size, nullptr);
    return engine;
}

int main(int argc, char** argv)
{
    cv::Mat this_img = cv::imread("/app/test/1.jpg", cv::IMREAD_COLOR);
    //cv::imwrite("img.png", image);
    //DebugP(image.size());
    cv::Mat sample;
    if (this_img.channels() == 4)
        cv::cvtColor(this_img, sample, CV_BGRA2BGR);
    else if (this_img.channels() == 1)
        cv::cvtColor(this_img, sample, CV_GRAY2BGR);
    else
        sample = this_img;
    cv::Mat sample_resized;
    vector<double> ratios;
    cv::imwrite("sample_img.png", sample);
    resize_image(sample, sample_resized, ratios);
    cv::imwrite("resize_img.png", sample_resized);
    cv::Mat sample_float, normalized_image;
    sample_resized.convertTo(sample_float, CV_32FC3);
    cv::subtract(sample_float, cv::Scalar(104, 117, 123), normalized_image);
    //cout << normalized_image << endl;
    cv::imwrite("img_norm.png", normalized_image);
    float* data = normal(normalized_image);

    //for(int i = 0; i < 12; ++i) {
    //    std::cout << data[i] << ",";
    //}
    //std::cout << std::endl;
    //cv::Vec3b bgrPixel = dst.at<cv::Vec3b>(0, 0);
    //std::cout << bgrPixel << std::endl;
    //bgrPixel = dst.at<cv::Vec3b>(0, 1);
    //std::cout << bgrPixel << std::endl;
    //bgrPixel = dst.at<cv::Vec3b>(0, 2);
    //std::cout << bgrPixel << std::endl;
    //bgrPixel = dst.at<cv::Vec3b>(0, 3);
    //std::cout << bgrPixel << std::endl;


    // deserialize the engine searilized by torch2trt
    ICudaEngine* engine = createEngine();
    
    float* outputs[18];
    typedef std::chrono::high_resolution_clock Time;
    typedef std::chrono::duration<double, std::ratio<1, 1000>> ms;
    typedef std::chrono::duration<float> fsec;

    // run inference and cout time
    for(int i = 0; i < 1; ++i) {
        auto t0 = Time::now();
        doInference(*engine, data, outputs, 1);
        auto t1 = Time::now();
        fsec fs = t1 - t0;
        ms d = std::chrono::duration_cast<ms>(fs);
        std::cout << std::endl << "Running time of one image is:" << d.count() << "ms" << std::endl;
    }
    return 0;
}



/*
mInput.deviceBuffer.resize(inputDims); 
CHECK(cudaMemcpy( 
    mInput.deviceBuffer.data(), mInput.hostBuffer.data(), mInput.hostBuffer.nbBytes(), cudaMemcpyHostToDevice)); 
  
// Set the input size for the preprocessor 
mPreprocessorContext->setBindingDimensions(0, inputDims); 
// We can only run inference once all dynamic input shapes have been specified. 
if (!mPreprocessorContext->allInputDimensionsSpecified()) { 
    return false; 
} 
  
// Run the preprocessor to resize the input to the correct shape 
std::vector<void*> preprocessorBindings = {mInput.deviceBuffer.data(), mPredictionInput.data()}; 
// For engines using full dims, we can use executeV2, which does not include a separate batch size parameter. 
bool status = mPreprocessorContext->executeV2(preprocessorBindings.data()); 
if (!status) { 
    return false; 
} 
  
// Next, run the model to generate a prediction. 
std::vector<void*> predicitonBindings = {mPredictionInput.data(), mOutput.deviceBuffer.data()}; 
status = mPredictionContext->executeV2(predicitonBindings.data()); 
if (!status) { 
    return false; 
} 
  
// Copy the outputs back to the host and verify the output. 
CHECK(cudaMemcpy(mOutput.hostBuffer.data(), mOutput.deviceBuffer.data(), mOutput.deviceBuffer.nbBytes(), 
     cudaMemcpyDeviceToHost)); 


bool read_TRT_File(const std::string& engineFile, IHostMemory*& trtModelStream) {
    std::fstream file;
    std::cout << "loading filename from:" << engineFile << std::endl;
    nvinfer1::IRuntime* trtRuntime;
    //nvonnxparser::IPluginFactory* onnxPlugin = createPluginFactory(gLogger.getTRTLogger());
    file.open(engineFile, std::ios::binary | std::ios::in);
    file.seekg(0, std::ios::end);
    int length = file.tellg();
    std::cout << "length:" << length << std::endl;
    file.seekg(0, std::ios::beg);
    std::unique_ptr<char[]> data(new char[length]);
    file.read(data.get(), length);
    file.close();
    std::cout << "load engine done" << std::endl;
    std::cout << "deserializing" << std::endl;
    trtRuntime = createInferRuntime(gLogger.getTRTLogger());
    //ICudaEngine* engine = trtRuntime->deserializeCudaEngine(data.get(), length, onnxPlugin);
    ICudaEngine* engine = trtRuntime->deserializeCudaEngine(data.get(), length, nullptr);
    std::cout << "deserialize done" << std::endl;
    assert(engine != nullptr);
    std::cout << "The engine in TensorRT.cpp is not nullptr" <<std::endl;
    trtModelStream = engine->serialize();
    return true;
}
*/`

**Comment by Edwardmark** [comment]
@JingyuQian I am new to tensorRT cpp api. My engine is created using torch2trt using fp16 builder, so I do not set any config to run an fp16 engine created by fp16 builder? Is that true? Thanks  for your kind reply.
Best, 
Edward.

**Comment by JingyuQian** [comment]
@Edwardmark The code you pasted is not well formatted. Perhaps upload your code file to the cloud and leave a shareable link here so it's easier to read.

**Comment by Edwardmark** [comment]
@JingyuQian And I tried using set input data to fp16 or fp32, and the inference result is quite different. OK, I will upload the code soon. Thanks.

**Comment by Edwardmark** [comment]
@JingyuQian This is my test code. Please help me out. Thanks in advance.
https://github.com/Edwardmark/dog_classification/blob/master/test.cpp

**Comment by JingyuQian** [comment]
Hi @Edwardmark,
If your model was built with `torch2trt` with fp16 builder then I think it is fp16 ready.

There's no need to enforce your data to be fp16 in your code. Just read in your image, pad/resize, convert to float32 is enough.

As shown in [torch2trt official demo](https://github.com/NVIDIA-AI-IOT/torch2trt/tree/master/notebooks/image_classification) they also used float32 data.

**Comment by Edwardmark** [comment]
@JingyuQian https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/notebooks/image_classification/conversion.ipynb
in line 2， they use data = data.half()

**Comment by JingyuQian** [comment]
@Edwardmark I see. I'm not familiar with PyTorch. It looks like in this way the data really needs to be passed in as half values. 
In your code, line 53, should it be `i < INPUT_H * INPUT*W * INPUT*C`? `normal` function does hwc2chw but channels is still 3 right? (correct me if wrong)

**Comment by Edwardmark** [comment]
@JingyuQian You are right, it was my typo. Thanks, man.

**Comment by Edwardmark** [comment]
@JingyuQian Yes, you correct my bug. Thans a lot.

**Comment by NikhilChowdary-MCW** [comment]
Hi @Edwardmark,
Can I know how to deal with multiple output engine file? Should I need to modify ONNX for that? Thanks.
