### ISSUE TITLE
How to set bias=None when add_convolution

### ISSUE THREAD

**Issue by RizhaoCai** [NVIDIA/TensorRT#472]
## Description

I am using TensorRT 6 Python API on TX2 to build a deep model
When I ran the tutorial example: /usr/src/tensorrt/samples/python/network_api_pytorch_mnist/sample.py

Everything is well.
However, when I did `bias=None`, an error came.
```python
def populate_network(network, weights):
    # Configure the network layers based on the weights provided.
    input_tensor = network.add_input(name=ModelData.INPUT_NAME, dtype=ModelData.DTYPE, shape=ModelData.INPUT_SHAPE)

    conv1_w = weights['conv1.weight'].numpy()
    #conv1_b = weights['conv1.bias'].numpy()
    conv1_b =  None#weights['conv1.bias'].numpy()
    conv1 = network.add_convolution(input=input_tensor, num_output_maps=20, kernel_shape=(5, 5), kernel=conv1_w, bias=conv1_b)
    conv1.stride = (1, 1)
```

The error is shown as
> Traceback (most recent call last):
  File "sample.py", line 147, in <module>
    main()
  File "sample.py", line 133, in main
    with build_engine(weights) as engine:
  File "sample.py", line 114, in build_engine
    populate_network(network, weights)
  File "sample.py", line 81, in populate_network
    conv1 = network.add_convolution(input=input_tensor, num_output_maps=20, kernel_shape=(5, 5), kernel=conv1_w, bias=conv1_b)
TypeError: add_convolution(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.INetworkDefinition, input: tensorrt.tensorrt.ITensor, num_output_maps: int, kernel_shape: tensorrt.tensorrt.DimsHW, kernel: tensorrt.tensorrt.Weights, bias: tensorrt.tensorrt.Weights) -> tensorrt.tensorrt.IConvolutionLayer
> Invoked with: <tensorrt.tensorrt.INetworkDefinition object at 0x7f4e6ef298>; kwargs: input=<tensorrt.tensorrt.ITensor object at 0x7f4e6ef308>, num_output_maps=20, kernel_shape=(5, 5), kernel=array([[[[-0.02327881, -0.14044845,  0.01555905, -0.00289726,

I compare API docs of [TensorRT 7](https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-700/tensorrt-api/python_api/infer/Graph/Network.html) and [TensorRT 6 ](https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-601/tensorrt-api/python_api/infer/Graph/Network.html?highlight=add_convo#tensorrt.INetworkDefinition.add_convolution)

For [TensorRT 7](https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-700/tensorrt-api/python_api/infer/Graph/Network.html), bias can be optional and the default is None
![image](https://user-images.githubusercontent.com/37952703/78127551-f11d8d80-7446-11ea-9c02-10453571d055.png)

But for [TensorRT 6 ](https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-601/tensorrt-api/python_api/infer/Graph/Network.html?highlight=add_convo#tensorrt.INetworkDefinition.add_convolution), bias should be provided. Otherwise, I will get this problem.
![image](https://user-images.githubusercontent.com/37952703/78127171-45743d80-7446-11ea-802b-60fff82e7323.png)

Therefore, with TensorRT 6, it seems that the only way to build a conv layer without bias is to provide a zero vector
```python
bias = np.zeros(num_neurons,).astype(np.float32)
```

## Environment

**TensorRT Version**: 6.0
**GPU Type**: Jetson TX2
**Nvidia Driver Version**: 
**CUDA Version**: 10.0
**CUDNN Version**: 7
**Operating System + Version** Ubuntu: 
**Python Version (if applicable)**: 3.6

## Steps To Reproduce
`python3 /usr/src/tensorrt/samples/python/network_api_pytorch_mnist/sample.py`

**Comment by rmccorm4** [comment]
Hi @RizhaoCai ,

Since the docs state the behavior correctly for both TRT6 and TRT7, and you found a workaround by using a vector of zeros for the bias, can I close this issue?

**Comment by RizhaoCai** [comment]
> Hi @RizhaoCai ,
> 
> Since the docs state the behavior correctly for both TRT6 and TRT7, and you found a workaround by using a vector of zeros for the bias, can I close this issue?

Yes. Thanks.
