### ISSUE TITLE
 ERROR:Assertion failed: _importer_ctx.tensors().at(output.name()).is_tensor()

### ISSUE THREAD

**Issue by daixiangzi** [NVIDIA/TensorRT#474]
## Environment

**TensorRT Version*7.0*: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)*3.7*: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)*1.4*: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

when i run 
/usr/src/tensorrt/bin/trtexec --onnx=xxx.onnx --avgRuns=1 --workspace=1024 --batch=1 --fp16

**Comment by daixiangzi** [comment]
pytorch：
       #preds.size(0) is constant
        preds_size = torch.IntTensor([preds.size(0)])
        return preds_size

**Comment by daixiangzi** [comment]
when i modify this code:
preds_size = preds.size(0)
this code is right

**Comment by rmccorm4** [comment]
> when i modify this code:
>
> preds_size = preds.size(0)
> this code is right

Hi @daixiangzi , Is your issue solved then?

**Comment by daixiangzi** [comment]
yes,but i don't know the reason



---Original---

**Comment by rmccorm4** [comment]
Sounds like something specific to PyTorch. You could try taking a look at the 2 ONNX models in Netron and see what's different between the working and non-working models to see if it gives any insight

**Comment by daixiangzi** [comment]
thank you.i try to do



---Original---

**Comment by daixiangzi** [comment]
i sovled this problem, 
right:
![right](https://user-images.githubusercontent.com/24811131/78526886-fcd5cf00-780d-11ea-9152-f0d123084283.jpg)
erro:
![erro](https://user-images.githubusercontent.com/24811131/78526889-02331980-780e-11ea-902e-df8deee9d7ca.jpg)

this node should in this graph,
