### ISSUE TITLE
ERROR:network->markOutput(*blobNameToTensor->find(s.c_str()));

### ISSUE THREAD

**Issue by sun-dr** [NVIDIA/TensorRT#476]
## Description
Dear all：
When I use the model from Pytorch2Caffe，the parser of the model is correct，but it‘s error when 
network->markOutput(*blobNameToTensor->find(s.c_str())). The model can run normally in caffe，
it's error in TensorRT as mentioned above. That's all. Thanks!

**Comment by kevinch-nv** [comment]
@sun-dr can you provide the model you are having trouble with? In addition have you tried the ONNX import path? The Caffe import path has been deprecated.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
