### ISSUE TITLE
TensorRT7.0 don't support cuda10.1 ？

### ISSUE THREAD

**Issue by mchl0203** [NVIDIA/TensorRT#478]
![image](https://user-images.githubusercontent.com/8417221/78759423-2c254100-79b2-11ea-8f5c-b10772682572.png)

Due to permissions, I can't install cuda10.0 or 10.2, How do i install TensorRT7.0 ?

**Comment by rmccorm4** [comment]
Hi @mchl0203,

If you have access to Docker on the system, then you should be able to run an NGC TensorRT container despite having CUDA 10.1. 

For installing TensorRT on the host, I believe you'll have to install one of the listed CUDA versions.

**Comment by mchl0203** [comment]
Thank you for replying me so quick. Things are like this, I want to install onnx-tensorrt7.0, and onnx-tensorrt depend on tensorrt7.0. If I use `TensorRT-7.0.0.11.CentOS-7.6.x86_64-gnu.cuda-10.2.cudnn7.6.tar.gz` , will get the following error: 
![image](https://user-images.githubusercontent.com/8417221/78768609-c12e3700-79be-11ea-8556-e7f6e0f9dd3a.png)

So, I guess if I have a pkg `TensorRT-7.0.0.11.CentOS-7.6.x86_64-gnu.cuda-10.1.cudnn7.6.tar.gz`, it will be right. Now, I don't know how to solve this question...... 
Do you know any way to solve it? looking forward to your reply, thank you~

**Comment by rmccorm4** [comment]
Sorry, I think you'll have to either use a container of some kind, or install CUDA 10.2 on your machine to resolve those issues. Containers are generally the easiest solution.

**Comment by mchl0203** [comment]
ok, I will try, thank you~

**Comment by flyingmrwang** [comment]
@mchl0203 same problem, how did you solved?
