### ISSUE TITLE
MaskRCNN  trained with other input shape, cannot detect anything

### ISSUE THREAD

**Issue by facerless** [NVIDIA/TensorRT#479]
I trained maskrcnn with input shape [1024,1024], then i convert model to tensorrt, everything is right.
Now,I trained maskrcnn with input shape [640,640], the model on tensorrt cannot detect anything, the model on python can detect object.
The cpp and python config:
static const nvinfer1::Dims3 IMAGE_SHAPE{ 3, 640, 640};

IMAGE_MIN_DIM = 640
IMAGE_MAX_DIM = 640

**Comment by JingyuQian** [comment]
Hi @facerless ,
Have you tried looking at outputs to see what they look like? Most likely bugs exist in your python config or cpp code.

**Comment by facerless** [comment]
@JingyuQian ，my code is right.
The error is in proposalLayerPlugin, proposalLayerPlugin.cpp --->

const auto image_dims = MaskRCNNConfig::IMAGE_SHAPE;
const auto& scales = MaskRCNNConfig::RPN_ANCHOR_SCALES;
const auto& ratios = MaskRCNNConfig::RPN_ANCHOR_RATIOS;
const auto& strides = MaskRCNNConfig::BACKBONE_STRIDES;
auto anchor_stride = MaskRCNNConfig::RPN_ANCHOR_STRIDE;

The proposalLayerPlugin.cpp used original config, I need to reset the config, and recompile the proposalLayerPlugin.

**Comment by bhusalsantosh** [comment]
Were you able to convert your custom trained model to UFF format and use it for inference?

**Comment by facerless** [comment]
@bhusalsantosh ，I convert pb to uff，next i test uff for inference on tensorrt code. It all works.

**Comment by bhusalsantosh** [comment]
@facerless  Great. What about when you change the input size?

**Comment by facerless** [comment]
When i change input size，the detect output is wrong！We need to change the&nbsp;image_dims&nbsp;in&nbsp;proposalLayerPlugin.cpp, and compile&nbsp;proposalLayerPlugin.cpp.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bhusalsantosh"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 上午10:36
收件人: "NVIDIA/TensorRT"<TensorRT@noreply.github.com&gt;; 
抄送: "星空"<573743392@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NVIDIA/TensorRT] MaskRCNN  trained with other input shape, cannot detect anything (#479)





 
@facerless  Great. What about when you change the input size?

**Comment by aunsid** [comment]
> When i change input size，the detect output is wrong！We need to change the image_dims in proposalLayerPlugin.cpp, and compile proposalLayerPlugin.cpp. Now code only works for input size(1024x1024).
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bhusalsantosh"<notifications@github.com&gt;; 发送时间: 2020年5月8日(星期五) 上午10:36 收件人: "NVIDIA/TensorRT"<TensorRT@noreply.github.com&gt;; 抄送: "星空"<573743392@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [NVIDIA/TensorRT] MaskRCNN trained with other input shape, cannot detect anything (#479) @facerless Great. What about when you change the input size? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@facerless Could you provide the steps to reproduce it?
