### ISSUE TITLE
undefined reference to `nvinfer1::plugin::createSSDPriorBoxPlugin(void const*, unsigned long)'

### ISSUE THREAD

**Issue by maiquanshen** [NVIDIA/TensorRT#48]
Hello, I compiled tensorrt 5.1.5 according to the tutorial, but found that:
Undefined reference to `nvinfer1::plugin::createSSDPriorBoxPlugin(void const*, unsigned long)';
After checking, include/NvInferPlugin.h has the declaration of this function, but it seems that the corresponding function implementation can not be found, and the call will give an error.
But I can directly use the official website compiled library is possible, there is the implementation of this function, is there a problem with my compilation?
（英文不好，附上中文：
你好，我按照教程编译了tensorrt 5.1.5，但是在使用时发现：
undefined reference to `nvinfer1::plugin::createSSDPriorBoxPlugin(void const*, unsigned long)'；
经检查，include/NvInferPlugin.h 里面是有这个函数的声明的，但好像找不到相应的函数实现，而导致调用时会报错。
但是我直接使用官网编译好的库是可以的，有这个函数的实现，请问是我的编译有问题吗？）

**Comment by rajeevsrao** [comment]
Please use the corresponding IPluginV2Ext implementation of this plugin (createPriorBoxPlugin). The legacy INvPlugin implementations have been removed for the open source release (although they are still supported, albeit deprecated, in the TensorRT binary releases).

I just submitted a change to remove references to the older plugins from the header file: https://github.com/NVIDIA/TensorRT/commit/65705bdfa0f6f72f4a7c0eaba9c5eb7d261559a2
