### ISSUE TITLE
How to get runtime output dims for dynamic input size?

### ISSUE THREAD

**Issue by CemalAker** [NVIDIA/TensorRT#481]
I have a CNN with dynamic input/output shapes. The batch size is not important for the case. However, I want to run inference for images of different sizes. I have exported ONNX model using PyTorch-ONNX exporter. When I run the model with onnx-runtime, it automatically detects the output shape and creates the output tensor.
Two different input shapes:
(1, 3, 500, 500)
(1, 3, 1000, 1000)
Corresponding output shapes:
(1, 512, 124, 124)
(1, 512, 249, 249)

How can I get the runtime output size in C++ API?

I have tried:
1. engine->getBindingDimensions
2. network->getOutput(0)->getDimensions()
Both resulted in (1,512,-1,-1)

Note: This is the feature extraction part of the network. Although output of this part can be computed using input shape and network layers, this will not be possible for the remaining part.

**Comment by pranavm-nvidia** [comment]
Once you [set the input dimensions](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_execution_context.html#a9f87003474bc387e17782292cc2ea613) on the context, TRT will compute the shapes of the outputs, which you can [get from that context](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_execution_context.html#af915b83bfe8f5f8c02115f4a85e418ca)

**Comment by apayne19** [comment]
@CemalAker  trying to do dynamic image resolution sizes as well. How did you set that? Would you just set the input shape to (1, 3, ?, ?) or (1, 3, None, None)?
