### ISSUE TITLE
How to use dynamic shape when I use onnx to trt

### ISSUE THREAD

**Issue by liupengkd** [NVIDIA/TensorRT#487]
The example of the dynamic shape given on the official website is the mnist network, two networks are constructed, and the first network is used to reshape the picture. If I want to use the dynamic shape feature in the detection network, can I not build two networks, because my detection network does not have a fully connected layer, and there is no requirement for the size of the input image, how can I build

**Comment by rmccorm4** [comment]
Hi,

If your ONNX model has dynamic shape (-1 in some dimensions), then you can parse it using the ONNX parser with the EXPLICIT_BATCH flag, and create some optimization profiles that define a range of acceptable input shapes at runtime.

Please see the docs on [dynamic shape](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes) and [optimization profiles](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#opt_profiles)

**Comment by liupengkd** [comment]
@rmccorm4  thx，But I encountered another problem:  error: no matching function for call to ‘nvonnxparser::IParser::parseFromFile(const char [28], nvinfer1::ILogger::Severity. the same interface with 
![image](https://user-images.githubusercontent.com/15835439/79692187-5b7f5c00-8296-11ea-802b-6b71d409cd82.png)

**Comment by liupengkd** [comment]
@rmccorm4  thx, I have solved this problem, The correct interface call is "static_cast<int>(ILogger::Severity::kWARNING)"
