### ISSUE TITLE
context->execute(batch_size,buffers) crashes, but executev2(buffers) is ok

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#489]
## Description
I am using tensorrt7.0.11, input is an ONNX model, it's ok when use executev2, but if I change it to execute(batch_size, buffers), it was crashed, what's the difference between those two infterface?

## Environment

**TensorRT Version**: 7.0.11
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 390.77 
**CUDA Version**: 9.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: ubuntu 16.04

## Relevant Files
![捕获](https://user-images.githubusercontent.com/7233091/79090164-4fb60600-7d7b-11ea-88c3-d6a52809b34a.PNG)

**Comment by rmccorm4** [comment]
Hi @HaoLiuHust ,

execute/enqueue are for implicit batch networks, and executeV2/enqueueV2 are for explicit batch networks. The V2 versions don't take a batch_size argument since it's taken from the explicit batch dimension of the network / or from the optimization profile if used.

**Comment by HaoLiuHust** [comment]
Thanks, so if my onnx model has an input with shape (1, c, h, w), it can't be used with batch size more than 1? and if I have an onnx model has input with shape (10,c,h,w), it can't be forward with batch size smaller than 10, is that right?

**Comment by rmccorm4** [comment]
If the ONNX model has fixed shape, for example, (10, C, H, W), then yes it will only accept input of this shape.

If the ONNX model has dynamic shape (represented by a -1 in a given dimension), for example (-1, C, H, W), you can create an optimization profile that defines a range of acceptable input shapes, such as `min=(1, C, H, W), opt=(10, C, H, W), max=(10, C, H, W)`, then this would accept inputs of any shape within this range (batch size between 1 and 10). But you'll have to set the binding dimensions to the actual input shape at runtime.

Some more details in this thread: https://forums.developer.nvidia.com/t/tensorrt-7-onnx-models-with-variable-batch-size/115302/6?u=nves_r

**Comment by HaoLiuHust** [comment]
thanks for your warmly reply, I will try it。if I convert a dynamic onnx model to an trt engine file, it is dynamic or fixed shape?

**Comment by rmccorm4** [comment]
If your ONNX model has dynamic shape, but you don't create an optimization profile, I think it defaults those dynamic dimensions to 1's.

If you do create an optimization profile(s), then your TensorRT engine will be "dynamic" within the range of those profiles you defined.

**Comment by HaoLiuHust** [comment]
Thanks, It helps a lot. I will try the dynamic shape then

**Comment by marsmiao** [comment]
> If your ONNX model has dynamic shape, but you don't create an optimization profile, I think it defaults those dynamic dimensions to 1's in the TensorRT engine, but I'm not totally sure off the top of my head.
> 
> If you do create an optimization profile(s), then your TensorRT engine will be "dynamic" within the range of those profiles you defined. And you'll have to set the desired profile and input shapes at runtime.

As far as I have observed, when using same context to infer different batch-size request, e.g. batch 10, batch 2, batch6 this pattern to infer, once the batch-2 request have executed inference, the next batch-6 will only have the first 2 batchs' results correct, with the last 4 batches appear incorrect.

**Comment by HaoLiuHust** [comment]
> > If your ONNX model has dynamic shape, but you don't create an optimization profile, I think it defaults those dynamic dimensions to 1's in the TensorRT engine, but I'm not totally sure off the top of my head.
> > If you do create an optimization profile(s), then your TensorRT engine will be "dynamic" within the range of those profiles you defined. And you'll have to set the desired profile and input shapes at runtime.
> 
> As far as I have observed, when using same context to infer different batch-size request, e.g. batch 10, batch 2, batch6 this pattern to infer, once the batch-2 request have executed inference, the next batch-6 will only have the first 2 batchs' results correct, with the last 4 batches appear incorrect.

We already used it in our products, it is correct

**Comment by HaoLiuHust** [comment]
> > If your ONNX model has dynamic shape, but you don't create an optimization profile, I think it defaults those dynamic dimensions to 1's in the TensorRT engine, but I'm not totally sure off the top of my head.
> > If you do create an optimization profile(s), then your TensorRT engine will be "dynamic" within the range of those profiles you defined. And you'll have to set the desired profile and input shapes at runtime.
> 
> As far as I have observed, when using same context to infer different batch-size request, e.g. batch 10, batch 2, batch6 this pattern to infer, once the batch-2 request have executed inference, the next batch-6 will only have the first 2 batchs' results correct, with the last 4 batches appear incorrect.

What's your device type?

**Comment by marsmiao** [comment]
> > > If your ONNX model has dynamic shape, but you don't create an optimization profile, I think it defaults those dynamic dimensions to 1's in the TensorRT engine, but I'm not totally sure off the top of my head.
> > > If you do create an optimization profile(s), then your TensorRT engine will be "dynamic" within the range of those profiles you defined. And you'll have to set the desired profile and input shapes at runtime.
> > 
> > 
> > As far as I have observed, when using same context to infer different batch-size request, e.g. batch 10, batch 2, batch6 this pattern to infer, once the batch-2 request have executed inference, the next batch-6 will only have the first 2 batchs' results correct, with the last 4 batches appear incorrect.
> 
> What's your device type?

We use two Tesla T4

**Comment by HaoLiuHust** [comment]
> > > > If your ONNX model has dynamic shape, but you don't create an optimization profile, I think it defaults those dynamic dimensions to 1's in the TensorRT engine, but I'm not totally sure off the top of my head.
> > > > If you do create an optimization profile(s), then your TensorRT engine will be "dynamic" within the range of those profiles you defined. And you'll have to set the desired profile and input shapes at runtime.
> > > 
> > > 
> > > As far as I have observed, when using same context to infer different batch-size request, e.g. batch 10, batch 2, batch6 this pattern to infer, once the batch-2 request have executed inference, the next batch-6 will only have the first 2 batchs' results correct, with the last 4 batches appear incorrect.
> > 
> > 
> > What's your device type?
> 
> We use two Tesla T4

you can try tensorrt 7.2
