### ISSUE TITLE
lose layers while parsing .onnx file.

### ISSUE THREAD

**Issue by siam7tong** [NVIDIA/TensorRT#49]
I have a weird problem： I use “trt.OnnxParser(network, TRT_LOGGER)" to parse my well-work onnx file(retinanet about object detection). I find that it seems to have forgotten to parse the whole regression part, so the output of produced-engine just have the classification output. But the process could finish successfully without error. Did anyone have the same problem？ what should I do...
![811751982](https://user-images.githubusercontent.com/31204550/61879384-83b77580-af25-11e9-8359-627f2075c5ce.jpg)
![1235271996](https://user-images.githubusercontent.com/31204550/61879386-83b77580-af25-11e9-864a-015db116669c.jpg)
my process code：
```python
def get_engine(onnx_file_path, engine_file_path=""):

    def build_engine():

        with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, trt.OnnxParser(network,TRT_LOGGER) as parser:
            builder.max_workspace_size = 1 << 30

            with open(onnx_file_path, 'rb') as model:
                parser.parse(model.read())

            print(network.mark_output(network.get_layer(network.num_layers - 1).get_output(0)))
            engine = builder.build_cuda_engine(network)

            with open(engine_file_path, "wb") as f:
                f.write(engine.serialize())
            return engine

    if os.path.exists(engine_file_path):
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
    else:
        return build_engine()
```

the info of the produced-engine：
```python
for binding in engine:
    print(binding)
```
————————————————
```
0
758
```

**Comment by DilipSequeira** [comment]
I'm going to hazard a guess that 812 is not marked as an output before invoking the builder , and thus TensorRT identifies those nodes as something it can prune away. Is that possible? Turning on verbose output in the logger would tell you whether this is the case.

**Comment by ztianlin** [comment]
@siam7tong Same here, have you solved this problem?

**Comment by rmccorm4** [comment]
Closing since no response, feel free to open a new issue or ask for this to be re-opened.
