### ISSUE TITLE
How to design bottleneck layers such as denseblock layer in tensorrt?

### ISSUE THREAD

**Issue by feitiandemiaomi** [NVIDIA/TensorRT#491]
I want to speed up the densenet network model in tensorrt, but when writing the custom layer denseblock layer, I thought of a problem. I used the caffe model as the input. The denseblock layer has only one layer in prototxt of caffe, but it contains 8 convolution layers, and other the operation of BN, then what should I do when defining plugin? Whether to define 8 plugins for 8 convolutional layer and the BN layer separately, or only one plugin include 8 convolutional and BN,  here is the example of prototxt.
Can you give some advice，thanks for your reply.

# DenseBlock 1
layer {
  name: "DenseBlock1"
  type: "**DenseBlock**"
  bottom: "conv1"
  top: "DenseBlock1"
  denseblock_param {
    numTransition: 8
    initChannel: 64
    growthRate: 8
    Filter_Filler {
      type: "msra"
    }
    BN_Scaler_Filler {
      type: "constant"
      value: 1
    }
    BN_Bias_Filler {
      type: "constant"
      value: 0
    }
    use_dropout: false
    dropout_amount: 0.2
  }
}

**Comment by rmccorm4** [comment]
Hi,

As of TensorRT 7, the Caffe parser is deprecated in favor of the ONNX parser. Please try converting your model to ONNX and using the ONNX parser.

There are some existing implementations of densenet in TensorFlow/PyTorch online that you could use as a reference: https://github.com/kentaroy47/pytorch-onnx-tensorrt-CIFAR10/blob/master/models/densenet.py

There also seems to be an existing DenseNet ONNX model in the ONNX model zoo here: https://github.com/onnx/models/tree/master/vision/classification/densenet-121

You can try to parse this model in TensorRT 7 using the Python/C++ APIs, or using the `trtexec` command-line tool.

**Comment by kevinch-nv** [comment]
@feitiandemiaomi it would be easier to write on plugin to handle that one custom denseblock layer in this case. As @rmccorm4 mentioned, we are deprecating the Caffe parser in favor of the ONNX parser. I will be closing this issue, feel free to re-open or create a new one if you have issues regarding this in the future.

**Comment by leosk-knight** [comment]
@kevinch-nv How do I define denseblock_param? in caffe.proto?
