### ISSUE TITLE
Can't run end_to_end_tensorflow_mnist sample

### ISSUE THREAD

**Issue by yjiangling** [NVIDIA/TensorRT#496]
## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

I have download test data to the TensorRT/data/mnist file:

```
asr@huaxin:/media/huaxin/tcl1/asr/yujiangling/TensorRT/data/mnist$ ls
0.pgm  6.pgm             LegacyCalibrationTable      mnistapi.wts            mnist.prototxt
1.pgm  7.pgm             lenet5_custom_pool.uff      mnist.caffemodel        README.md
2.pgm  8.pgm             lenet5_custom_pool.uff.txt  mnistgie.wts            t10k-images-idx3-ubyte
3.pgm  9.pgm             lenet5_mnist_frozen.pb      mnist_lenet.caffemodel  t10k-labels-idx1-ubyte
4.pgm  deploy.prototxt   lenet5.uff                  mnist_mean.binaryproto  train-images-idx3-ubyte
5.pgm  generate_pgms.py  lenet5.uff.txt              mnist.onnx              train-labels-idx1-ubyte
```

and convert pb model to the TensorRT/samples/python/end_to_end_tensorflow_mnist/models file, but when I run: python3 sample.py -d /media/huaxin/tcl1/asr/yujiangling/TensorRT/data, it still give error like this:

```
asr@huaxin:/media/huaxin/tcl1/asr/yujiangling/TensorRT/samples/python/end_to_end_tensorflow_mnist$ python3 sample.py -d /media/huaxin/tcl1/asr/yujiangling/TensorRT/data
WARNING: /usr/src/tensorrt/data/mnist does not exist. Trying /usr/src/tensorrt/data instead.
WARNING: /usr/src/tensorrt/data does not exist. Please provide the correct data path with the -d option.
[TensorRT] ERROR: ../rtSafe/cuda/cudaFullyConnectedRunner.cpp (105) - cuBLAS Error in rowMajorMultiply: 13 (CUBLAS_STATUS_EXECUTION_FAILED)
[TensorRT] ERROR: ../rtSafe/cuda/cudaFullyConnectedRunner.cpp (105) - cuBLAS Error in rowMajorMultiply: 13 (CUBLAS_STATUS_EXECUTION_FAILED)
Traceback (most recent call last):
  File "sample.py", line 112, in <module>
    main()
  File "sample.py", line 98, in main
    with build_engine(model_file) as engine:
AttributeError: __enter__
```

What's wrong? How can I solve it? Thank you!

**Comment by rmccorm4** [comment]
Hi,

This seems like a CUDA environment/setup issue, but you didn't provide any of the request environment information, so I can't really help.

Can you please try to run this sample inside of an nvidia-docker container, such as `nvcr.io/nvidia/tensorrt:20.03-py3`? If the sample works in the container, then it's an environment issue.

**Comment by yjiangling** [comment]
> Hi,
> 
> This seems like a CUDA environment/setup issue, but you didn't provide any of the requested environment information, so I can't really help.
> 
> Can you please try to run this sample inside of an nvidia-docker container, such as `nvcr.io/nvidia/tensorrt:20.03-py3`? If the sample works in the container, then it's an environment issue.

OK，Thank U very much for the response, I'll try it.

**Comment by kevinch-nv** [comment]
@yjiangling have you solved this issue? Can this be closed?

**Comment by yjiangling** [comment]
> @yjiangling have you solved this issue? Can this be closed?

Thank you very much for your time, I'm sorry to forget close it. I'll close it now!

**Comment by karenyun** [comment]
@yjiangling 
Hi, where did you download these .wts and .caffemodel files?
Could you give some download addresses?
