### ISSUE TITLE
how to change makefile in tensorRT'5.0.2.6' to cmakelist?

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#498]
how to change makefile in tensorRT'5.0.2.6' to cmakelist?

**Comment by Ram-Godavarthi** [comment]
Did you happen to do it successfully?? 
i am also looking for it. 

Please let me know if you know it

**Comment by Edwardmark** [comment]
@rajeevsrao sorry, I failed. But I changed other things in CMakelists to Makefile.

**Comment by kevinch-nv** [comment]
@Edwardmark closing this issue. We have CMake files for samples, parsers, and plugins in the repository, please use those to build.
