### ISSUE TITLE
TensorRT error merging 3D convolutions

### ISSUE THREAD

**Issue by qian256** [NVIDIA/TensorRT#501]
When using TensorRT to convert models with 3D inception module (e.g. I3D), it tried to merge 3D convolutions which should not be merged, resulting the following error:

`[TensorRT] ERROR: Internal error: could not find any implementation for node (Unnamed Layer* 3) [Convolution] + (Unnamed Layer* 5) [Activation] || (Unnamed Layer* 9) [Convolution] + (Unnamed Layer* 11) [Activation], try increasing the workspace size with IBuilder::setMaxWorkspaceSize()`

The 3D inception module looks like this:
![inception](https://user-images.githubusercontent.com/8185982/79618731-e3b80280-80d8-11ea-9ef4-838b7e726adb.png)
TensorRT tries to merge the center two 1x1x1 -> 3x3x3 path, which I think should not be done. When I change the kernel size of one of the path, TensorRT will not merge them. It happens when the kernel size are same. Is there a way to disable this "optimization".

I am using TensorRT 7.0.1 with torch2trt, Ubuntu 18.04, cuda 10.0

**Comment by ttyio** [comment]
Hello @qian256 , thanks for reporting

Can you call setMaxWorkspaceSize() with a larger memory? this merge can improve your performance.

If you are memory limited and cannot increase your memory, the workaround is to insert `Identity` layer before one of the `Conv`. thanks!

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!
