### ISSUE TITLE
sample_uff_fasterRCNN: UffParser: Parser error: MarkOutput_0: Order size is not matching the number dimensions of TensorRT

### ISSUE THREAD

**Issue by xinjialimath** [NVIDIA/TensorRT#503]
I am trying to run sample_uff_fasterRCNN and got the error like following:
[03/20/2020-11:33:21] [I] Building and running a GPU inference engine for FasterRCNN
[03/20/2020-11:33:22] [E] [TRT] UffParser: Parser error: MarkOutput_0: Order size is not matching the number dimensions of TensorRT
&&&& FAILED TensorRT.sample_uff_fasterRCNN # ./sample_uff_fasterRCNN --datadir ../../samples/opensource/sampleUffFasterRCNN/uff_faster_rcnn -W 480 -H 272 -I 2016_1111_185016_003_00001_night_000441.ppm -B 1

Some details:
TensorRT 6.0
Ubuntu 18.04
GTX1060 MQ 6GB
tensorflow-gpu=1.14

How can I solve it?

**Comment by ttyio** [comment]
Hello @xinjialimath , thanks for reporting.

Could you try with latest 7.2 release? thanks.

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!
