### ISSUE TITLE
https://stackoverflow.com/questions/61335004/how-to-simplifiled-the-following-tensorrt-makefile-the-makefile-seems-so-comple

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#505]
how to understand the makefile for tensorRT 0.5.2?
https://stackoverflow.com/questions/61335004/how-to-simplifiled-the-following-tensorrt-makefile-the-makefile-seems-so-comple

**Comment by mk-nvidia** [comment]
@Edwardmark TensorRT 7.x uses a cmake-based build system so it already contains `CMakeLists.txt`
See: https://github.com/NVIDIA/TensorRT/blob/master/CMakeLists.txt
