### ISSUE TITLE
Missing information to enable Cross Compile 

### ISSUE THREAD

**Issue by crelkins** [NVIDIA/TensorRT#508]
## Description

The information TensorRT/samples/README.md is not sufficient to set up the cross compile environment. Specifically the section "Install the TensorRT cross compilation debian packages for the corresponding target." needs to be expanded. I am trying to cross compile x86_64 Linux -> aarch64 Linux and I cannot install the libnvinfer-dev-cross-aarch64 or libnvinfer5-cross-aarch64 packages. 

I have tried...
`sudo apt-get install libnvinfer-dev-cross-aarch64 libnvinfer5-cross-aarch64  `
...but get the error...
`E: Unable to locate package libnvinfer-dev-cross-aarch64
E: Unable to locate package libnvinfer5-cross-aarch64 `

I am new to Jetson so I could be missing something simple. Thanks in advance!

## Environment
I am compiling on host machine for Jetson Xavier with Jetpack 4.3. My host CUDA and host CUDA cross compiler were installed by the Nvidia SDK manager. TensorRT was not managed by Nvidia SDK manager so I installed that manually on host using the same version as the target. 

**TensorRT Version**: 
libnvinfer-dev   6.0.1-1+cuda10.0
libnvinfer-bin    6.0.1-1+cuda10.0
**GPU Type**: None host has Intel Graphics 
**Nvidia Driver Version**: None host has Intel Graphics 
**CUDA Version**: 
cuda-compiler-10-0            10.0.326-1
cuda-cross-aarch64-10-0   10.0.326-1
**CUDNN Version**: 
libcudnn7          7.6.3.30-1+cuda10.0
libcudnn7-dev   7.6.3.30-1+cuda10.0
**Operating System + Version**: 
Ubuntu 18.04.4 LTS
**Cross compiler**: 
 g++-aarch64-linux-gnu 4:7.4.0-1ubuntu2.3

**Comment by mglucas** [comment]
Hello @crelkins! Did you succesfully cross compiled it? I'm trying it here to.

**Comment by oak-tree** [comment]
Hey, we are looking for a way to cross compiled our code with TensorRT as well. Any news about that?

**Comment by ttyio** [comment]
@crelkins @mglucas @oak-tree , thanks for reporting issues here

Have you tried the docker image https://github.com/NVIDIA/TensorRT/blob/master/docker/ubuntu-cross-aarch64.Dockerfile 

A more detailed doc is in https://github.com/NVIDIA/TensorRT#setting-up-the-build-environment

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!

**Comment by zifeis** [comment]
There is no cross compile packge of cuDNN/TensorRT from SDK Manager which makes ubuntu-cross-aarch64.Dockerfile not working anymore.

**Comment by ttyio** [comment]
@zifeis , could you elaborate more on issue `There is no cross compile packge of cuDNN/TensorRT from SDK Manager` ? thanks!

**Comment by zifeis** [comment]
@ttyio Sorry, the docker file is good to go. The difference of cross-compile between drive and jetson confused me. The Jetson just need download the target file which is enough. Thanks.
