### ISSUE TITLE
how to set device bindings in buffer managers? 

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#509]
I am working on a detection model. I change the backbone of it to tensorRT to do FP16 inference, and the detection code such as decode boxes and nms is done in libtorch and torchvisoin, so how to set device pointer in BufferManagers? I want to set the device buffer as the libtorch tensor pointer, so it can save the device to host or memcopy time.

Thanks in advance.

**Comment by rmccorm4** [comment]
Hi @Edwardmark ,

I know you're probably looking for a C++ example of this. Unfortunately I don't have one off the top of my head. I do have a simple example using the Python API, which I'm sure you could translate to C++.

Note that setting bindings to arbitrary device pointers should generally work, but there's an open issue with pytorch that may give you some CUDNN symbol errors: https://github.com/pytorch/pytorch/issues/32983

```python
import torch
import tensorrt as trt

# Deserialize engine file
with open("model.engine", 'rb') as f, trt.Runtime(trt.Logger(trt.Logger.WARNING)) as runtime:
    engine = runtime.deserialize_cuda_engine(f.read())

inputs = [torch.ones((1, 3, 256, 128), device="cuda:0")]
outputs = [torch.zeros((1, 512), device="cuda:0")]
bindings = [_input.data_ptr() for _input in inputs] + [_output.data_ptr() for _output in outputs]

# Create context, this can be re-used
context = engine.create_execution_context()

# Inference
results = []
for i in range(10):
    infer(context, bindings)
    results.append(outputs[0].cpu().numpy().copy())
```

**Comment by Edwardmark** [comment]
@rmccorm4 I am using the following code in cpp, how to change it to your python version? Thanks.
```
    buffers->copyInputToDevice();
    bool status = context->execute(1, buffers->getDeviceBindings().data());
    assert(status);
    buffers->copyOutputToHost();
```

**Comment by ttyio** [comment]
Hello @Edwardmark , 
have you solved the problem?  If not, what's the remaining issue? thanks!

**Comment by Edwardmark** [comment]
> Hello @Edwardmark ,
> have you solved the problem? If not, what's the remaining issue? thanks!

I just want to find out a cpp example, would you please provide one? Thanks.

**Comment by ttyio** [comment]
Hello @Edwardmark ,
trtexec is a cpp sample that show how to bind buffer as trt enqueue input.
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec

But it did not show how to interact with pytorch, you have to replace the buffer pointer with the device pointer retrieved from pytorch.

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by xjsxujingsong** [comment]
Hi @Edwardmark, I have the same question here. 
Have you found the solution?
