### ISSUE TITLE
Input parameters for batchedNMSPlugin

### ISSUE THREAD

**Issue by rgc183** [NVIDIA/TensorRT#510]
I am writing a layer in onnx-tensorrt backend for NMS op. From the documentation, https://github.com/onnx/onnx/blob/master/docs/Operators.md#nonmaxsuppression the inputs for onnx parser and input parameters expected by trt plugin doesn't match. 
I am trying to figure out how to derive some of the params from the input tensors. The params I am struggling with are:
`shareLocation` , 
`backgroundLabelId`,
 `topK` : Is it equal to `max_output_boxes_per_class` ?
 `keepTopK`,
 `isNormalized`.

I want to know how do I derive it from the inputs provided for:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#nonmaxsuppression

**Comment by ttyio** [comment]
Hello @rgc183 , thanks for reporting
the trt plugin implementation followed tf operators.
https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en 

so there is gaps not only the input parameters, also the return values (onnx return indices). 

Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them 


          if (pad_per_class) {
             top_k = std::min(max_size_per_class * num_classes, max_total_size);
          } else {
             top_k = max_total_size;
          }

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839

**Comment by ddlau** [comment]
> Hello @rgc183 , thanks for reporting
> the trt plugin implementation followed tf operators.
> https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
> 
> so there is gaps not only the input parameters, also the return values (onnx return indices).
> 
> Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them
> 
> ```
>       if (pad_per_class) {
>          top_k = std::min(max_size_per_class * num_classes, max_total_size);
>       } else {
>          top_k = max_total_size;
>       }
> ```
> 
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839

about "topK", I found something odd, of TensorRT ver7.2.16, when topK was greater than 4096, it will crash during inference, any suggestions?

**Comment by ttyio** [comment]
> > Hello @rgc183 , thanks for reporting
> > the trt plugin implementation followed tf operators.
> > https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
> > so there is gaps not only the input parameters, also the return values (onnx return indices).
> > Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them
> > ```
> >       if (pad_per_class) {
> >          top_k = std::min(max_size_per_class * num_classes, max_total_size);
> >       } else {
> >          top_k = max_total_size;
> >       }
> > ```
> > 
> > 
> > https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839
> 
> about "topK", I found something odd, of TensorRT ver7.2.16, when topK was greater than 4096, it will crash during inference, any suggestions?

Hello @ddlau , It is document as limitation, see
https://github.com/NVIDIA/TensorRT/tree/release/7.2/plugin/batchedNMSPlugin#known-issues

**Comment by ttyio** [comment]
> > > Hello @rgc183 , thanks for reporting
> > > the trt plugin implementation followed tf operators.
> > > https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
> > > so there is gaps not only the input parameters, also the return values (onnx return indices).
> > > Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them
> > > ```
> > >       if (pad_per_class) {
> > >          top_k = std::min(max_size_per_class * num_classes, max_total_size);
> > >       } else {
> > >          top_k = max_total_size;
> > >       }
> > > ```
> > > 
> > > 
> > > https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839
> > 
> > 
> > about "topK", I found something odd, of TensorRT ver7.2.16, when topK was greater than 4096, it will crash during inference, any suggestions?
> 
> Hello @ddlau , It is document as limitation, see
> https://github.com/NVIDIA/TensorRT/tree/release/7.2/plugin/batchedNMSPlugin#known-issues

Hello @ddlau , you can rebuild the opensource code with slight changes if you want to support more boxes, see https://github.com/NVIDIA/TensorRT/blob/release/7.2/plugin/common/kernels/allClassNMS.cu#L274
You can update the code like this (depends on your real topK size, you can change the number of template class you want to instance):

      void (*kernel[])(const int, const int, const int, const int, const float,
                      const bool, const bool, float*, T_SCORE*, int*, T_SCORE*,
                      int*, bool)
        = {
            P(1), P(2), P(3), P(4), P(5), P(6), P(7), P(8), P(9), P(10), P(11), P(12), P(13), P(14)
        };

**Comment by ddlau** [comment]
> > > Hello @rgc183 , thanks for reporting
> > > the trt plugin implementation followed tf operators.
> > > https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
> > > so there is gaps not only the input parameters, also the return values (onnx return indices).
> > > Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them
> > > ```
> > >       if (pad_per_class) {
> > >          top_k = std::min(max_size_per_class * num_classes, max_total_size);
> > >       } else {
> > >          top_k = max_total_size;
> > >       }
> > > ```
> > > 
> > > 
> > > https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839
> > 
> > 
> > about "topK", I found something odd, of TensorRT ver7.2.16, when topK was greater than 4096, it will crash during inference, any suggestions?
> 
> Hello @ddlau , It is document as limitation, see
> https://github.com/NVIDIA/TensorRT/tree/release/7.2/plugin/batchedNMSPlugin#known-issues

hello and thanks for ur replay
if as so, how should I handle postprocess of YOLO net? which outputs 10647 rectangles...?

**Comment by ddlau** [comment]
@ttyio OK, i'll give it shot, thank you

**Comment by ddlau** [comment]
> > > > Hello @rgc183 , thanks for reporting
> > > > the trt plugin implementation followed tf operators.
> > > > https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
> > > > so there is gaps not only the input parameters, also the return values (onnx return indices).
> > > > Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them
> > > > ```
> > > >       if (pad_per_class) {
> > > >          top_k = std::min(max_size_per_class * num_classes, max_total_size);
> > > >       } else {
> > > >          top_k = max_total_size;
> > > >       }
> > > > ```
> > > > 
> > > > 
> > > > https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839
> > > 
> > > 
> > > about "topK", I found something odd, of TensorRT ver7.2.16, when topK was greater than 4096, it will crash during inference, any suggestions?
> > 
> > 
> > Hello @ddlau , It is document as limitation, see
> > https://github.com/NVIDIA/TensorRT/tree/release/7.2/plugin/batchedNMSPlugin#known-issues
> 
> Hello @ddlau , you can rebuild the opensource code with slight changes if you want to support more boxes, see https://github.com/NVIDIA/TensorRT/blob/release/7.2/plugin/common/kernels/allClassNMS.cu#L274
> You can update the code like this (depends on your real topK size, you can change the number of template class you want to instance):
> 
> ```
>   void (*kernel[])(const int, const int, const int, const int, const float,
>                   const bool, const bool, float*, T_SCORE*, int*, T_SCORE*,
>                   int*, bool)
>     = {
>         P(1), P(2), P(3), P(4), P(5), P(6), P(7), P(8), P(9), P(10), P(11), P(12), P(13), P(14)
>     };
> ```



> > > > Hello @rgc183 , thanks for reporting
> > > > the trt plugin implementation followed tf operators.
> > > > https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
> > > > so there is gaps not only the input parameters, also the return values (onnx return indices).
> > > > Also we has `topK`, and only do IOU operation on the topK box in each class, it is not the same as `max_output_boxes_per_class`, you can check tf-trt code to see how do we do the mapping between them
> > > > ```
> > > >       if (pad_per_class) {
> > > >          top_k = std::min(max_size_per_class * num_classes, max_total_size);
> > > >       } else {
> > > >          top_k = max_total_size;
> > > >       }
> > > > ```
> > > > 
> > > > 
> > > > https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc#L5839
> > > 
> > > 
> > > about "topK", I found something odd, of TensorRT ver7.2.16, when topK was greater than 4096, it will crash during inference, any suggestions?
> > 
> > 
> > Hello @ddlau , It is document as limitation, see
> > https://github.com/NVIDIA/TensorRT/tree/release/7.2/plugin/batchedNMSPlugin#known-issues
> 
> Hello @ddlau , you can rebuild the opensource code with slight changes if you want to support more boxes, see https://github.com/NVIDIA/TensorRT/blob/release/7.2/plugin/common/kernels/allClassNMS.cu#L274
> You can update the code like this (depends on your real topK size, you can change the number of template class you want to instance):
> 
> ```
>   void (*kernel[])(const int, const int, const int, const int, const float,
>                   const bool, const bool, float*, T_SCORE*, int*, T_SCORE*,
>                   int*, bool)
>     = {
>         P(1), P(2), P(3), P(4), P(5), P(6), P(7), P(8), P(9), P(10), P(11), P(12), P(13), P(14)
>     };
> ```

@ttyio hello and sorry to bother you again

I'm heading some problems when cmaking the oss project...

environment; windows10, cuda11.1, cudnn8.0, tensorrt7.2.1

problem 1: what is the so called "RT_LIB" and how to set it up ?
problem 2: how to settle "empty CUDA_ARCHITECTURES"? 

here the Output:

`PS D:\TensorRT\build> cmake .. -DTRT_LIB_DIR='D:\\NVIDIA\\TensorRT-7.2.1.6\\lib' -DTRT_OUT_DIR='$(Get-Location)\\out' -DCMAKE_TOOLCHAIN_FILE=..\\cmake\\toolchains\\cmake_x64_win.toolchain
Building for TensorRT version: 7.2.1, library version: 7
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- Targeting TRT Platform: x86_64
-- CUDA version set to 11.1
-- cuDNN version set to 8.0
-- Protobuf version set to 3.0.0
-- Using libprotobuf D:/TensorRT/build/third_party.protobuf/lib/libprotobuf.a
-- ========================= Importing and creating target nvinfer ==========================
-- Looking for library nvinfer
-- Library that was found D:/NVIDIA/TensorRT-7.2.1.6/lib/nvinfer.lib !!!!!!!!!!!!!!!!!! D:\NVIDIA\TensorRT-7.2.1.6\lib @@@
-- ==========================================================================================
-- ========================= Importing and creating target nvuffparser ==========================
-- Looking for library nvparsers
-- Library that was found D:/NVIDIA/TensorRT-7.2.1.6/lib/nvparsers.lib !!!!!!!!!!!!!!!!!! D:\NVIDIA\TensorRT-7.2.1.6\lib @@@
-- ==========================================================================================
-- GPU_ARCHS defined as 75. Generating CUDA code for SM 75
-- Protobuf proto/trtcaffe.proto -> proto/trtcaffe.pb.cc proto/trtcaffe.pb.h
-- D:/TensorRT/build/parsers/caffe
Generated: D:/TensorRT/build/parsers/onnx/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.proto
Generated: D:/TensorRT/build/parsers/onnx/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx-ml.proto
--
-- ******** Summary ********
--   CMake version         : 3.18.4
--   CMake command         : D:/ASC/CMake/bin/cmake.exe
--   System                : Windows
--   C++ compiler          : d:/ASC/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
--   C++ compiler version  : 19.27.29112.0
--   CXX flags             : -Wno-deprecated-declarations /DWIN32 /D_WINDOWS /W3 /GR /EHsc -DBUILD_SYSTEM=cmake_oss /W4
--   Build type            : Release
--   Compile definitions   : _PROTOBUF_INSTALL_DIR=D:/TensorRT/build;ONNX_NAMESPACE=onnx2trt_onnx
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : $Env:TRT_RELEASE/lib/..
--   CMAKE_MODULE_PATH     :
--
--   ONNX version          : 1.6.0
--   ONNX NAMESPACE        : onnx2trt_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
--
--   Protobuf compiler     :
--   Protobuf includes     :
--   Protobuf libraries    :
--   BUILD_ONNX_PYTHON     : OFF
-- Found TensorRT headers at D:/TensorRT/include
-- Find TensorRT libs at D:/NVIDIA/TensorRT-7.2.1.6/lib/nvinfer.lib;D:/NVIDIA/TensorRT-7.2.1.6/lib/nvinfer_plugin.lib;D:/NVIDIA/TensorRT-7.2.1.6/lib/myelin64_1.lib
-- Adding new sample: sample_algorithm_selector
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_char_rnn
--     - Parsers Used: uff;caffe;onnx
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_dynamic_reshape
--     - Parsers Used: onnx
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_fasterRCNN
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_googlenet
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_int8
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_int8_api
--     - Parsers Used: onnx
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_mlp
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_mnist
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_mnist_api
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_movielens
--     - Parsers Used: uff
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_movielens_mps
--     - Parsers Used: uff
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_nmt
--     - Parsers Used: none
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_onnx_mnist
--     - Parsers Used: onnx
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_plugin
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_reformat_free_io
--     - Parsers Used: caffe
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_ssd
--     - Parsers Used: caffe
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_uff_fasterRCNN
--     - Parsers Used: uff
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_uff_maskRCNN
--     - Parsers Used: uff
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_uff_mnist
--     - Parsers Used: uff
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_uff_plugin_v2_ext
--     - Parsers Used: uff
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Adding new sample: sample_uff_ssd
--     - Parsers Used: uff
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: sample_onnx_mnist_coord_conv_ac
--     - Parsers Used: onnx
--     - InferPlugin Used: ON
--     - Licensing: opensource
-- Adding new sample: trtexec
--     - Parsers Used: caffe;uff;onnx
--     - InferPlugin Used: OFF
--     - Licensing: opensource
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RT_LIB
    linked by target "sample_algorithm_selector" in directory D:/TensorRT/samples/opensource/sampleAlgorithmSelector
    linked by target "sample_char_rnn" in directory D:/TensorRT/samples/opensource/sampleCharRNN
    linked by target "sample_dynamic_reshape" in directory D:/TensorRT/samples/opensource/sampleDynamicReshape
    linked by target "sample_fasterRCNN" in directory D:/TensorRT/samples/opensource/sampleFasterRCNN
    linked by target "sample_googlenet" in directory D:/TensorRT/samples/opensource/sampleGoogleNet
    linked by target "sample_int8" in directory D:/TensorRT/samples/opensource/sampleINT8
    linked by target "sample_int8_api" in directory D:/TensorRT/samples/opensource/sampleINT8API
    linked by target "sample_mlp" in directory D:/TensorRT/samples/opensource/sampleMLP
    linked by target "sample_mnist" in directory D:/TensorRT/samples/opensource/sampleMNIST
    linked by target "sample_mnist_api" in directory D:/TensorRT/samples/opensource/sampleMNISTAPI
    linked by target "sample_movielens" in directory D:/TensorRT/samples/opensource/sampleMovieLens
    linked by target "sample_movielens_mps" in directory D:/TensorRT/samples/opensource/sampleMovieLensMPS
    linked by target "sample_nmt" in directory D:/TensorRT/samples/opensource/sampleNMT
    linked by target "sample_onnx_mnist" in directory D:/TensorRT/samples/opensource/sampleOnnxMNIST
    linked by target "sample_plugin" in directory D:/TensorRT/samples/opensource/samplePlugin
    linked by target "sample_reformat_free_io" in directory D:/TensorRT/samples/opensource/sampleReformatFreeIO
    linked by target "sample_ssd" in directory D:/TensorRT/samples/opensource/sampleSSD
    linked by target "sample_uff_fasterRCNN" in directory D:/TensorRT/samples/opensource/sampleUffFasterRCNN
    linked by target "sample_uff_maskRCNN" in directory D:/TensorRT/samples/opensource/sampleUffMaskRCNN
    linked by target "sample_uff_mnist" in directory D:/TensorRT/samples/opensource/sampleUffMNIST
    linked by target "sample_uff_plugin_v2_ext" in directory D:/TensorRT/samples/opensource/sampleUffPluginV2Ext
    linked by target "sample_uff_ssd" in directory D:/TensorRT/samples/opensource/sampleUffSSD
    linked by target "sample_onnx_mnist_coord_conv_ac" in directory D:/TensorRT/samples/opensource/sampleOnnxMnistCoordConvAC
    linked by target "trtexec" in directory D:/TensorRT/samples/opensource/trtexec

CMake Warning (dev) in plugin/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "nvinfer_plugin_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in plugin/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "nvinfer_plugin_static".
This warning is for project developers.  Use -Wno-dev to suppress it.`

**Comment by ttyio** [comment]
Sorry @ddlau , TRT has delivered windows build in binary release, however, we have no windows support for the open source yet:-(

**Comment by ddlau** [comment]
> Sorry @ddlau , TRT has delivered windows build in binary release, however, we have no windows support for the open source yet:-(

ok, alright
but any clues about what "RT_LIB" actually refers to? e.g. from linux distributions...

**Comment by ttyio** [comment]
> > Sorry @ddlau , TRT has delivered windows build in binary release, however, we have no windows support for the open source yet:-(
> 
> ok, alright
> but any clues about what "RT_LIB" actually refers to? e.g. from linux distributions...

Hello @ddlau , It is POSIX system library /lib/x86_64-linux-gnu/librt.so.1

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
