### ISSUE TITLE
dynamic shape

### ISSUE THREAD

**Issue by liupengkd** [NVIDIA/TensorRT#511]
## Environment

**TensorRT Version**: 7
**GPU Type**: 1080ti
**Nvidia Driver Version**: 430
**CUDA Version**: 10
**CUDNN Version**: 7.6
**Operating System + Version**: 16.04

## Steps To Reproduce

In the version 7 dynamic shape example, 
![image](https://user-images.githubusercontent.com/15835439/80296690-b55cb600-87af-11ea-9fab-a1376088e255.png),Is the first dimension the batch dimension? If I don't fix the batch input, do I need to change the batch to -1? The input like this becomes dims4 (-1,1, -1, -1)

**Comment by rmccorm4** [comment]
Hi,

Yes, the first dimension is the batch dimension in an EXPLICIT_BATCH network.

If the ONNX model's batch dimension is dynamic (-1), then you can specify a range of values in your optimization profile to support dynamic shape. But note, you will need to explicitly set the input dimension for your execution context for each input of different shape.

See this post for some more details: https://forums.developer.nvidia.com/t/tensorrt-7-onnx-models-with-variable-batch-size/115302/6?u=nves_r
