### ISSUE TITLE
there are some bugs in tensorrt7.0.0.11

### ISSUE THREAD

**Issue by yflv-yanxia** [NVIDIA/TensorRT#514]
## Description
Part of my network is as follows:
[part_network](https://github.com/yflv-yanxia/issues/blob/master/part_network.JPG)
Outputs of layer "relu-fc4"  are same to tensorrt6 and tensorrt7.
Outputs of layer "deconv5"  are also same to tensorrt6 and tensorrt7.
However,  outputs of layer "fc45"  are different between tensorrt6 and tensorrt7, the tensorrt6's results are correct, the tensorrt7's results are wrong.
So, I think there must be some bugs in operation "element wise addition"("fc45") of "tensorrt7.0.0.11

## Environment
**TensorRT Version**:  7.0.0.11
**GPU Type**:  titan rtx
**Nvidia Driver Version**:  418.74
**CUDA Version**:  libcudart.so.10.0.130
**CUDNN Version**:  libcudnn.so.7.6.3

## Relevant Files
models, data, scripts could download from the following links:
[scripts_data_trt7model](https://github.com/yflv-yanxia/issues/blob/master/trt7_bug.7z)
[trt6model](https://github.com/yflv-yanxia/issues/blob/master/model_trt6.zip)

## Steps To Reproduce
change the opencv path and tensorrt path in CMakeLists.txt.
cd build
cmake ..
make
./yscp

Look forward to your reply。

**Comment by rmccorm4** [comment]
Hi,

Please convert your workflows to ONNX and try the ONNX parser to see if you see the same regression.

The Caffe parser is deprecated as of TRT 7.0 moving forward.
