### ISSUE TITLE
How to protect the model file model.engine when deploying? How to encode the model or pack the model into .so or .bin?

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#515]
I want to use tensorRT to deploy a model for a company, but I want to protect my model, so how can I do that? Is is possible to encode the .engine file or just pack it into .bin?
Thanks in advance.
Best, 
Edward

**Comment by rmccorm4** [comment]
Hi @Edwardmark ,

1. The serialized engine files are already stored in binary, not plaintext. 
2. When deserializing an engine, I don't believe there is currently an API that exposes how to examine the underlying model used in the engine.
3. Even if you could examine the underlying model from the engine somehow, it is likely that various layer fusions and optimizations were made when building the engine that would make the resulting engine different from the original model.

**Comment by duong0411** [comment]
Do u have a solve about encryption model engine ?
