### ISSUE TITLE
How can we calculate the flops and params of the compressed model

### ISSUE THREAD

**Issue by czs1886** [NVIDIA/TensorRT#517]
Is there any tool that can calculate the flops and params of the compressed model? (In my case its a pth file)

**Comment by rmccorm4** [comment]
For TensorRT, it comes with a tool called `trtexec` which has some benchmarking capabilities as far as flops go. You can find some more details here: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec

As far as parameters of the model goes, I'm not sure for TensorRT.

You mention `.pth` file, which is a saved PyTorch model. The preferred TensorRT route from PyTorch is to convert your PyTorch model to ONNX, and then use the ONNX parser to convert to TensorRT.

**Comment by czs1886** [comment]
> For TensorRT, it comes with a tool called `trtexec` which has some benchmarking capabilities as far as flops go. You can find some more details here: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec
> 
> As far as parameters of the model goes, I'm not sure for TensorRT.
> 
> You mention `.pth` file, which is a saved PyTorch model. The preferred TensorRT route from PyTorch is to convert your PyTorch model to ONNX, and then use the ONNX parser to convert to TensorRT.

Actually I'm using torch2trt tool so the output is als oa .pth file. However, when I use the ordinary flops counter, it came out with key error. Do you know it there's any way to do it? 
Thank you so much.

**Comment by rmccorm4** [comment]
Sorry, I'm not too familiar with `torch2trt. It would be better to ask there, (which I see you just did :slightly_smiling_face: ) 

https://github.com/NVIDIA-AI-IOT/torch2trt/issues/308#issue-608729202

**Comment by Xinchengzelin** [comment]
If the actual FLOPs(We deploy the engine in our project) is less than  `trtexec` FLOPs,  the reason is the deploy code we write,  right?

**Comment by lix19937** [comment]
For trt engine, I think we have no APIs for this (assuming that parameters mean weights). But if you dump the kDETAILED EngineInspector output, it shows the weight size for each layer, so you can sum them up.

For pth file, I think you can load and then use torchsummary, like follow     
```py
from torchvision import models
from torchsummary import summary

vgg = models.vgg16()
summary(vgg, (3, 224, 224))
```
