### ISSUE TITLE
CUDA execution error after the inference in tensorrt finishes

### ISSUE THREAD

**Issue by omais-shafi** [NVIDIA/TensorRT#518]
## Description
I am running tensorrt with C++ API and I am able to perform inference successfully. The end line of the inference is to destroy the CUDA context but I face an error like this there.

Cuda Error in ~ExecutionContext: 4 (unspecified launch failure)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception

Any inputs will be appreciated?

**Comment by rmccorm4** [comment]
Hi @omais-shafi ,

Can you share some code, model, and an associated Makefile to reproduce the issue?

**Comment by VCBE123** [comment]
> ## Description
> I am running tensorrt with C++ API and I am able to perform inference successfully. The end line of the inference is to destroy the CUDA context but I face an error like this there.
> 
> Cuda Error in ~ExecutionContext: 4 (unspecified launch failure)
> terminate called after throwing an instance of 'nvinfer1::CudaError'
> what(): std::exception
> 
> Any inputs will be appreciated?

Maybe you destroy the Context twice  If you use the smart pointer. You can see the closed issue.

**Comment by mk-nvidia** [comment]
Closing due to no response from issue reporter.
