### ISSUE TITLE
What is the meaning of Tactic when using trtexec

### ISSUE THREAD

**Issue by ginn24** [NVIDIA/TensorRT#52]
Hi, I'm trying to profile my model using trtexec. 
I got this error but I can't understand the meaning of Tactic and message. 
What is the meaning of Tactic? 
Also, How can I calculate the time taken per layer? 

```
--------------- Timing module/slice3/conv3/Conv2D(14)
Tactic 313790760974845026 time 8.02246
Tactic 4840826699149504854 time 11.5004
Tactic 5144900180810042977 time 12.6861
Tactic 7995089803833173579 time 12.6612
Tactic 8967263056866968576 time 11.786
Tactic -9018593586369639207 time 10.8774
Tactic -3998689942157953075 time 10.2664
Tactic -3448915218022119398 time 11.6557

--------------- Timing module/slice3/conv3/Conv2D(1)
Tactic 0 time 12.7072
Tactic 1 time 11.7415
Tactic 2 scratch requested: 301989888, available: 16777216
Tactic 4 scratch requested: 138792665088, available: 16777216
Tactic 5 scratch requested: 1149812736, available: 16777216
Tactic 6 scratch requested: 26216448, available: 16777216
```

**Comment by DilipSequeira** [comment]
Tactic is an opaque UID that TensorRT uses to identify its algorithm choice for a particular layer (or, if it fused some layers, a combination of layers.) Often these values are hashes of something-or-other, so don't expect to make anything useful of them.

For time per layer, your best option is to use either TensorRT's profiling interface, or NVIDIA's CUDA profiling tools.
