### ISSUE TITLE
2D Convolutions and Tensor Cores

### ISSUE THREAD

**Issue by RicardSilva** [NVIDIA/TensorRT#522]
## Description

I have three parallel 2d conv nodes. They all have the same input and output size.
The difference is one has (6,6), other (12,12), other (18,18) padding and matching dilation dimensions. The kernel shape is (3,3) for all of them. While running with fp16 the optimizer does not manage to find CUDNN kernel implementations that use tensor cores for all of them.

The one with (6,6) always runs on TCUs regardless of input size.
The one with (12,12) runs on TCUs for some input sizes.
The one with (18,18) never runs on TCUs.

My guess is that there is some rule that only triggers TCUs usage if the input/work size/output size is a multiple of 8 or something like that. But I would like to clarify what the rules are instead of trying to guess.

Thanks for your help

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: RTX 2080 ti
**Nvidia Driver Version**:  410.93
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: Debian 9

**Comment by rmccorm4** [comment]
> My guess is that there is some rule that only triggers TCUs usage if the input/work size/output size is a multiple of 8 or something like that. But I would like to clarify what the rules are instead of trying to guess.

I think that is exactly right. Multiples of 8 is mentioned several times throughout CUDNN documentation for Tensor Core utilization best practices:

https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#tensor-ops-guidelines-for-dl-compiler
