### ISSUE TITLE
sampleUffMaskRCNN - No conversion function registered for layer: PyramidROIAlign_TRT yet

### ISSUE THREAD

**Issue by asgtech** [NVIDIA/TensorRT#525]
## Description

Converted UFF model doesn't run under TensorRT because of warning "No conversion function registered for layer: PyramidROIAlign_TRT yet" 

## Environment

**TensorRT Version**: trt7.0.0.11-ga-20191216_1-1
**GPU Type**: RTX 2070
**Nvidia Driver Version**: 440.82
**CUDA Version**: 10.2
**CUDNN Version**: libcudnn7/unknown,unknown,now 7.6.5.32-1+cuda10.2 amd64 [installed,automatic]
**Operating System + Version**:  Ubuntu 18.04
**Python Version (if applicable)**: python3/bionic-updates,now 3.6.7-1~18.04 amd64 [installed]
**TensorFlow Version (if applicable)**:  tensorflow-gpu (1.14.0)
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: BareMetal

## Relevant Files

Was just following the instructions as described including converting the suggested model
https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

## Steps To Reproduce

I followed the instructions exactly

[uff conv log.txt](https://github.com/NVIDIA/TensorRT/files/4571897/uff.conv.log.txt)

**Comment by asgtech** [comment]
I also attempted the same conversion using solution 1 with the container from this post
https://github.com/NVIDIA/TensorRT/issues/123#issuecomment-551269792

And got exactly the same result

**Comment by wangzhangup** [comment]
Windows OS, no problem, works fine.

**Comment by sugger23** [comment]
> Windows OS, no problem, works fine.

how do you use the custum plugins on Windows?

**Comment by ttyio** [comment]
Hello @asgtech , thanks for reporting,
have you tried latest release 7.2 ?
https://github.com/NVIDIA/TensorRT/tree/release/7.2

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
