### ISSUE TITLE
Output dimensions: nvinfer1::IPluginV2DynamicExt:::getOutputDimensions()

### ISSUE THREAD

**Issue by rgc183** [NVIDIA/TensorRT#527]
When implementing `nvinfer1::IPluginV2DynamicExt:::getOutputDimensions(int outputIndex, const nvinfer1::DimsExprs* inputs, int nbInputs, nvinfer1::IExprBuilder& exprBuilder)`, what if extent of any of the dimension is unknown?

I am writing a plugin for `NonZero` op, where I want to return the indices of the elements. However, I don't know how many elements will be passing the condition from the input tensor. In this case my output will be:

```
nvinfer1::DimsExprs output;
  output.nbDims = 2;
  output.d[0] = exprBuilder.constant(inputs[0].nbDims);
  output.d[1]  = ??? (unknown)
```
There is no way that I will know the d[1] here. How to workaround this? 
One way I can think of is, return 2 tensors, first with size equal to number of elements in input tensor , so that it will have first `K` entries with indices of elements which are nonzero and second tensor with value `K`. But If I do this, all the subsequent layers will need a stitching.

**Comment by Raneee** [comment]
Igot the same probelm with you, had you solved your problom? thanks!

**Comment by ttyio** [comment]
Hello @rgc183 , thanks for reporting.
Sorry currently we don't support data-dependent dimensions. Could you look into the model to check if the `NonZero` can be replaced, sometimes onnx exporter just try to generate some indices to embedding layer, it will also use `NoneZero`, in this case it can be replaced with `Range`

**Comment by ttyio** [comment]
closing since no response for more than 1 month, please reopen if you still have question, thanks!

**Comment by DonggeunYu** [comment]
@ttyio how to replace `NonZero` using `Range`. Could you explain it in detail?

**Comment by ttyio** [comment]
Hello @DonggeunYu 
When export `torch.arange` in opset 10 or below, `NonZero` is exported, the fix is to export as opset 11, more detail can be found in below test code:

    class TestModel(torch.nn.Module):
       def forward(self, x):
            return torch.arange(x.shape[0])
    input0 = torch.zeros(64, 64)
    model = TestModel()
    torch.onnx.export(model, input0, "test_op10.onnx", verbose=True, opset_version=10)
    torch.onnx.export(model, input0, "test_op11.onnx", verbose=True, opset_version=11)

**Comment by DonggeunYu** [comment]
I don't use the arange function. I'm having trouble using torch.nonzero().

**Comment by DonggeunYu** [comment]
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass, self).__init__()
    def forward(self, x: torch.Tensor):
        t = torch.nonzero(torch.tensor(x))
        t = x[t]
        return t

the_model_class = TheModelClass()
the_model_class = the_model_class.cuda()
the_model_class.eval()
call = torch.tensor([[1., 2., 3.], [2., 3., 4.], [3., 4., 5.]]).cuda()
torch.onnx.export(the_model_class,
                      call,
                      "test.onnx",
                      export_params=True,
                      verbose=True,
                      opset_version=11,
                      do_constant_folding=False,)

**Comment by ttyio** [comment]
Hello @DonggeunYu , can this run on cpu as preprocess or postprocess of tensorrt model? sorry currently there is no nonzero support in trt, also it is hard to implement as plugin since the output shape is data-dependent.

**Comment by DonggeunYu** [comment]
@ttyio
Thank you for kindly letting me know :)
