### ISSUE TITLE
is it possible a plugin contains IConvolutionLayer and IPoolingLayer

### ISSUE THREAD

**Issue by VirtualEarth** [NVIDIA/TensorRT#53]
for example, this plugin is a   transition layer  in densenet.

**Comment by DilipSequeira** [comment]
Welcome to uncharted territory!

It might be possible, but I don't know anyone who's tried it. You might consider using cudnn's  API to run the convolution and pooling ops inside the plugin.

**Comment by rmccorm4** [comment]
Closing since no response, feel free to open a new issue or ask for this one to be re-opened
