### ISSUE TITLE
how to get the gpu name using by tensorRT cpp?

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#533]
For tensorRT does not support different gpu with the same engine file, I need to determine the type of gpu used by tensorRT, after set cuda_visible_divices outside the code, how to get the gpu name in cpp tensorRT? Thanks.

**Comment by rmccorm4** [comment]
Hi @Edwardmark ,

This isn't specific to TensorRT. This blog post might have the answer for you through CUDA API: https://devblogs.nvidia.com/how-query-device-properties-and-handle-errors-cuda-cc/
