### ISSUE TITLE
 [TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::938, condition: mEngine.bindingIsInput(bindingIndex)

### ISSUE THREAD

**Issue by laohur** [NVIDIA/TensorRT#536]
ENV: docker nemo asr+tensorrt7 quartznet15x5
models: encoer.onnx and decoder.onnx 
same dims works by Triton,but get dims error by TensorRT:
> [I 200507 09:33:30 loader:123] Using builder configuration flags: 0/1
[NeMo I 2020-05-07 09:33:36 actions:729] Evaluating batch 0 out of 1
  ---- client start encode
[D 200507 09:33:36 loader:443] Total # of Profiles: 1, Bindings Per Profile: 2, Active Profile: 0
[D 200507 09:33:36 loader:448] Start Binding: 0, End Binding: 2
[D 200507 09:33:36 loader:365] Iteration 0 not found in cache, generating new buffers for all inputs
[D 200507 09:33:36 loader:264] Updating seed to: 1588844016
[I 200507 09:33:36 loader:487] audio_signal batch_size0: 10 context.get_binding_shape(binding): (-1, 64, -1)
[I 200507 09:33:36 loader:496] audio_signal batch_size1: 10 context.get_binding_shape(binding): (10, 64, 192)
[I 200507 09:33:36 loader:487] outputs batch_size0: 10 context.get_binding_shape(binding): (10, 1024, 96)
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::938, condition: mEngine.bindingIsInput(bindingIndex)
[I 200507 09:33:36 loader:496] outputs batch_size1: 10 context.get_binding_shape(binding): (10, 1024, 96)
[I 200507 09:33:36 loader:210] Resizing audio_signal buffer to (10, 64, 192)
[I 200507 09:33:36 loader:210] Resizing outputs buffer to (10, 1024, 96)
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (257) - Cask Error in allocateContextResources: 7 ( Failed to update runtime arguments.)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
inference time 1.817155122756958 1.8219968960620463
  ---- client start decode
[D 200507 09:33:37 loader:443] Total # of Profiles: 1, Bindings Per Profile: 2, Active Profile: 0
[D 200507 09:33:37 loader:448] Start Binding: 0, End Binding: 2
[D 200507 09:33:37 loader:365] Iteration 0 not found in cache, generating new buffers for all inputs
[D 200507 09:33:37 loader:264] Updating seed to: 1588844017
[I 200507 09:33:37 loader:487] encoder_output batch_size0: 10 context.get_binding_shape(binding): (-1, 1024, -1)
[I 200507 09:33:37 loader:496] encoder_output batch_size1: 10 context.get_binding_shape(binding): (10, 1024, 96)
[I 200507 09:33:37 loader:487] output batch_size0: 10 context.get_binding_shape(binding): (10, 96, 5901)
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::938, condition: mEngine.bindingIsInput(bindingIndex)
[I 200507 09:33:37 loader:496] output batch_size1: 10 context.get_binding_shape(binding): (10, 96, 5901)
[I 200507 09:33:37 loader:210] Resizing encoder_output buffer to (10, 1024, 96)
[I 200507 09:33:37 loader:210] Resizing output buffer to (10, 96, 5901)
[TensorRT] ERROR: ../rtSafe/cuda/cudaConvolutionRunner.cpp (362) - Cudnn Error in execute: 8 (CUDNN_STATUS_EXECUTION_FAILED)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
inference time 0.003978718537837267 0.026257600635290146
tensor(5900)

**Comment by rmccorm4** [comment]
Hi,

This looks like a possible issue with either your TRT engine or your Triton config file mismatching. I would redirect this to https://github.com/nvidia/triton-inference-server, and add more information on your config file and share your original model if possible.

**Comment by ynma-hanvo** [comment]
i am also get this error with a tensorRT resnet50v2.onnx network,  my tensorrt is 7.2.1
msg is :
: Assigning persistent memory blocks for various profiles
ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1136, condition: profileMaxDims.d[i] >= dimensions.d[i]

**Comment by jinfagang** [comment]
@ynma-hanvo  Do know why this error happen?"

**Comment by ketronium** [comment]
A bit late here, but I get this error when I try to run inference on a tensor with the incorrect batch size. It goes away when doing a forward pass with the correct batch size.

**Comment by AleiChan** [comment]
> i am also get this error with a tensorRT resnet50v2.onnx network, my tensorrt is 7.2.1
> msg is :
> : Assigning persistent memory blocks for various profiles
> ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1136, condition: profileMaxDims.d[i] >= dimensions.d[i]

hi, i got the same err, can you help me?

**Comment by phamdat09** [comment]
I have the same issue. Someone can help me ??
