### ISSUE TITLE
Problem with batch_size > 1

### ISSUE THREAD

**Issue by PythonImageDeveloper** [NVIDIA/TensorRT#540]
Hi all,
I want to optimizing our detection model on tensorrt. However, when I set max_batch_size > 1, inference time increases proportionally to batch size. 

Basically:
> batch size=1 fp16 infTime is about 10ms
> batch size=4 fp16 infTime is about 39ms
> batch size=1 fp32 infTime is about 34.4ms
> batch size=4 fp32 infTime is about 129ms

How to solved this problem?
The nvidia team suggested me to use optimizer profiler to solve this problem. but becasue I'm new in this work , I don't know how to solve this probelm.
I used [link](https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/build_engine.py) for converting.

**Comment by rmccorm4** [comment]
Hi @PythonImageDeveloper,

The code you referenced is for converting a UFF model to TensorRT. The UFF parser only supports implicit batch models, which is not supported by Optimization profiles.

You'll want to try converting your model to ONNX, such as with `tf2onnx`, and creating an optimization profile as you described.

Check out this post which discusses a simple example of creating an explicit batch dynamic shape engine with an optimization profile: https://forums.developer.nvidia.com/t/tensorrt-7-onnx-models-with-variable-batch-size/115302/6?u=nves_r

**Comment by PythonImageDeveloper** [comment]
Thanks,
If I want implicit batch size like 5, Is it possible to use UFF parser for Tensorrt?
