### ISSUE TITLE
Cannot use precision Int32 with weights of type Float

### ISSUE THREAD

**Issue by rgc183** [NVIDIA/TensorRT#541]
I am trying to convert onnx model exported from tensorflow to tensorRT. However, it throws an error:

```
[ ERROR] Min__1082: cannot use precision Int32 with weights of type Float
[ERROR] Layer Min__1082 failed validation
[ ERROR] Network validation failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
Aborted (core dumped)
```
For the particular node, I tried setting ` layer->setPrecision(nvinfer1::DataType::kFLOAT)`, it still does not work. Yes my inputs for this op are floats. 

Its a private model.

## Environment
**TensorRT Version**: 7.0
**GPU Type**: 
**Nvidia Driver Version**: 418.67
**CUDA Version**:  10.0
**CUDNN Version**:  7.4.2.24-1+cuda10.0 
**Operating System + Version**: Ubuntu 18.04

 ONNX IR version:  0.0.6
Opset version:    11
Producer name:    tf2onnx
Producer version: 1.6.0
Domain:           
Model version:    0

**Comment by rmccorm4** [comment]
Hi @rgc183 ,

Did you try exporting your model to ONNX using opset 11? See this related issue: https://forums.developer.nvidia.com/t/error-strided-slice-1-cannot-use-precision-int32-with-weights-of-type-float-with-op-tf-reshape/119135/2?u=nves_r

**Comment by rgc183** [comment]
There are some of the ops in my model which are not supported below 11. That's why I am using opset 11.

**Comment by miaow1988** [comment]
I've got a similar problem when I use transpose layers. It was OK when I use TensorRT 5 instead of TensorRT 7. I still can't solve this problem.

**Comment by ttyio** [comment]
Hello @rgc183 , have you tried latest TRT 7.2?

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by nikhil-nakhate** [comment]
I am facing this problem too. I am bound by the TRT version which is 6.2.4. I am using opset version 7. Do you suggest using a different version?
