### ISSUE TITLE
getBatch() was not called when doing int8 calibration

### ISSUE THREAD

**Issue by le8888e** [NVIDIA/TensorRT#546]
Hello,
    I tried to quantize an onnx model by int8 calibration. I used class BatchStream and Int8EntropyCalibrator2 and tried calibration data format of .batch and .ppm. In both cases, getBatchSize(), readCalibrationCache() and writeCalibrationCache() was called but getBatch() was not. So I can't get a right calibration table.
    Could you please tell me what is probably going wrong? Thank you.

**Comment by rmccorm4** [comment]
Hi @le8888e ,

I have a detailed INT8 calibration sample here: https://github.com/rmccorm4/tensorrt-utils/blob/master/classification/imagenet/README.md

and the calibrator class is here: https://github.com/rmccorm4/tensorrt-utils/blob/master/classification/imagenet/ImagenetCalibrator.py

Please take a look through these as a reference.
