### ISSUE TITLE
Engine file created with Tensorrt7 is much bigger than Tensorrt4

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#547]
## Description

I am planning to upgrade to tensorrt7, when I convert my caffe model to trt engine file, I found that is much bigger than before, about 340M  vs 800M, and curiously, when I set the max batchsize to 10, it is bigger than set the max batchsize to 50

## Environment

**TensorRT Version**: 7.0.1.1
**GPU Type**: 1080TI
**Nvidia Driver Version**: 390.77 
**CUDA Version**: CUDA9.0
**CUDNN Version**: 7.6.5
**Operating System + Version**:  ubuntu 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by HaoLiuHust** [comment]
use onnx is much smaller

**Comment by rmccorm4** [comment]
Hi @HaoLiuHust, 

The Caffe parser is deprecated as of TensorRT 7, please convert your model to ONNX and try the ONNX parser.

**Comment by HaoLiuHust** [comment]
I have made a mistake, I am using onnx to convert to trt model, it's much bigger

**Comment by HaoLiuHust** [comment]
@rmccorm4

**Comment by HaoLiuHust** [comment]
and it's much slower when using trt model than caffe model in tensorrt7, nearly 8 times slower

**Comment by HaoLiuHust** [comment]
and using onnx model directly also much faster than convert it to trt model
