### ISSUE TITLE
Slice layer does not work if size is 0.

### ISSUE THREAD

**Issue by rgc183** [NVIDIA/TensorRT#549]
Slice layer throws an error if sizes are 0. 

```
node_name: slice size must be positive, size = [0]
```
The output dims are set to -1 when size is 0. 

##Environment
TensorRT Version: 7.0
GPU Type:
Nvidia Driver Version: 418.67
CUDA Version: 10.0
CUDNN Version: 7.4.2.24-1+cuda10.0
Operating System + Version: Ubuntu 18.04

ONNX IR version: 0.0.6
Opset version: 11
Producer name: tf2onnx
Producer version: 1.6.0
Domain:
Model version: 0

**Comment by rmccorm4** [comment]
Hi @rgc183,

Tracking RFE for Empty Tensor support here: https://github.com/NVIDIA/TensorRT/issues/337
