### ISSUE TITLE
How could I use the Plugin Layer PriorBox in ONNX model 

### ISSUE THREAD

**Issue by urbaneman** [NVIDIA/TensorRT#553]
## Description

When I try parse a mobilenet-V2-SSD onnx model, I got the error

```
[05/18/2020-13:50:38] [W] [TRT] onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 237 [PriorBox]:
ERROR: ModelImporter.cpp:134 In function parseGraph:
[8] No importer registered for op: PriorBox
```

The model can parse and infer with OpenCV DNN, I find the `PriorBox` and `DetectionOutput` has been defined in TensorRT. And this layer's params of onnx are the same as `caffe-ssd`.

Could I use this plugin and how?

I tried use `initLibNvInferPlugins` before `createInferBuilder`, but it doesn't work.

## Environment

**TensorRT Version**: TensorRT-7.0.0.11 \
**GPU Type**: NVIDIA P4000 \
**Nvidia Driver Version**: 442.50
**CUDA Version**: 10.0 \
**CUDNN Version**: 7.65 \
**Operating System + Version**: Windows 10 \
**PyTorch Version (if applicable)**: pytorch 1.1

Thanks so much!

**Comment by ttyio** [comment]
Hello @urbaneman , thanks for reporting
From https://github.com/onnx/onnx/blob/master/docs/Operators.md, `PriorBox` is not a native ONNX operator. If you have plugin implementation for this layer, you could add new ONNX operator follow `InstanceNormalization`. thanks.

code: https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L1610

**Comment by urbaneman** [comment]
Hi @ttyio, thanks for your reply.
I will try it.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
