### ISSUE TITLE
Unable to parse ONNX from TF UpSampling models

### ISSUE THREAD

**Issue by pwuertz** [NVIDIA/TensorRT#555]
## Description

I'm trying to import a Tensorflow model that uses `UpSampling2D` layers.
Conversion of the model via `tensorflow-onnx` / `tf2onnx` seems to work (with opset versions >=9).
Parsing such a model with TensorRT however fails with varying error messages.

Conversion with opset 9:
```
ERROR: builtin_op_importers.cpp:3240 In function importUpsample:
[8] Assertion failed: scales_input.is_weights()
```

Conversion with opset 10:
```
ERROR: builtin_op_importers.cpp:2412 In function importResize:
[8] Assertion failed: scales.is_weights() && "Resize scales must be an initializer!"
```

Conversion with opset 11:
```
ERROR: ModelImporter.cpp:92 In function parseGraph:
[8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
```

## Environment

**TensorRT Version**: 7
**GPU Type**: NVidia 2070
**Nvidia Driver Version**: 440
**CUDA Version**: 10.2
**CUDNN Version**: 7.6
**Operating System + Version**: Ubuntu 20.04
**Python Version**: 3.8
**TensorFlow Version**: 2.2.0
**tf2onnx Version**: 1.6.0

## Steps To Reproduce

Create a Tensorflow model with an UpSampling layer and save it as keras or saved_model.
```python
import tensorflow as tf
from tensorflow.keras import layers, models

layer_in = layers.Input(shape=(512, 512, 1), name="Input")
layer_out = layers.UpSampling2D()(layer_in)
model = models.Model(inputs=[layer_in], outputs=[layer_out])
model.save("model_upsample.h5")  # Keras format
tf.saved_model.save(model, "saved_model_upsample")  # "saved_model" format
```

Convert the model to ONNX. Works with keras and saved_model, --opset must be 9, 10, or 11.
```bash
# keras -> onnx
python -m tf2onnx.convert \
    --keras model_upsample.h5 --output model.onnx --opset OPSET
# saved_model -> onnx
python -m tf2onnx.convert \
    --saved-model saved_model_upsample --output model.onnx --opset OPSET
```

Parse the ONNX model with TensorRT in C++ using `nvonnxparser::createParser`, `parser->parseFromFile`, or running `trtexec`, which shows the same errors:
```bash
trtexec --onnx=model.onnx
```
The converted ONNX models for opsets 9-11 are here: [onnx_models.zip](https://github.com/NVIDIA/TensorRT/files/4643146/onnx_models.zip)

**Comment by rmccorm4** [comment]
Hi @pwuertz ,

Please see this related issue, and try the recommended solution of building the OSS ONNX parser master branch: https://github.com/NVIDIA/TensorRT/issues/386#issuecomment-604183816

**Comment by pwuertz** [comment]
Hi, my bad. I found the other issue but mistook the "use ONNX master" hint and tried tf2onnx master, with no luck. Will try again with the tensorrt parser components from master.

**Comment by pwuertz** [comment]
Works with the ONNX parser component built from current TensorRT OSS master. Thank you!

**Comment by x-jeff** [comment]
@pwuertz  same problem.How did you solve this problem？

**Comment by pwuertz** [comment]
@x-jeff I reduced my TensorRT 7.0 installation to the core components (`libnvinfer-dev`, `libnvinfer-plugin-dev`), then built the opensource components from this repository here from master. I think I had to fix a few problems for getting the build done on Ubuntu 20.04. Now with the ONNX parser from master and `tf2onnx` from master, the model was importable in TensorRT.

You also could try `keras2onnx`, which managed to export the Upsample layers directly, but failed in other ways. I did stick to `tf2onnx` after getting a working import.

**Comment by pavloshargan** [comment]
> @x-jeff I reduced my TensorRT 7.0 installation to the core components (`libnvinfer-dev`, `libnvinfer-plugin-dev`), then built the opensource components from this repository here from master. I think I had to fix a few problems for getting the build done on Ubuntu 20.04. Now with the ONNX parser from master and `tf2onnx` from master, the model was importable in TensorRT.
> 
> You also could try `keras2onnx`, which managed to export the Upsample layers directly, but failed in other ways. I did stick to `tf2onnx` after getting a working import.

Hello, for the last week I'm trying to do the same thing, but don't really understand this part "reduce TensorRT 7.0 installation to the core components (libnvinfer-dev, libnvinfer-plugin-dev)". How did you do this?

**Comment by OutSorcerer** [comment]
An alternative workaround for those who can not or do not want to compile TensorRT OSS or has to use older ONNX opset e.g. opset 7:

```
# TF version is 2.4.1
# model is Keras model with UpSampling2D layer

def monkey_patched_UpSampling2D_call(self, inputs):
    # Original implementation was:
    #     return backend.resize_images(
    #         inputs, self.size[0], self.size[1], self.data_format,
    #         interpolation=self.interpolation)
    return tf.image.resize(inputs, size=self.output.shape[1:3], method=self.interpolation)


tf.keras.layers.UpSampling2D.call = monkey_patched_UpSampling2D_call

tf.saved_model.save(model, "test_saved_model")

!python3 -m tf2onnx.convert --saved-model "test_saved_model" --output "test_saved_model.onnx" --opset 7
```

The produced ONNX works on NVidia Jetson TX2 (Jetpack 4.4.1, TensorRT 7.1.3.0).

**Comment by pwuertz** [comment]
By "reduced TensorRT 7.0 installation" I meant that I went from a regular TensorRT installation with all of the debs being installed, to a state where I only installed `libnvinfer-dev` and `libnvinfer-plugin-dev` and their requirements. Then I built the opensource components from this repository against those headers / libs.
