### ISSUE TITLE
tensorRT 7.0.0.11 Windows and CentOS can not load caffemodel

### ISSUE THREAD

**Issue by EdwardVincentMa** [NVIDIA/TensorRT#556]
I use both Win10 and CentOS7， And i can run sampleSSD's caffemodel. And also RetinaFace. But can not run LFFD(A Light and Fast Face Detector).  CentOS7 shows error: "Can not find lffd.caffemodel" at the function "parser->parse()" as bellow:
![image](https://user-images.githubusercontent.com/39480728/82201869-93300100-9933-11ea-96d8-6f9f98306a14.png)

Win10 Shows that blobNameToTensor is a null ptr as bellow:
![image](https://user-images.githubusercontent.com/39480728/82202306-4a2c7c80-9934-11ea-8527-0429f446b794.png)

My input tensor size is [3, 640, 640]。

**Comment by rmccorm4** [comment]
Hi @EdwardVincentMa ,

> blobNameToTensor was nullptr

This means it probably failed to find your model. I would try replacing `locateFile(*)` with the hard-coded string paths to your `.prototxt` and `.caffemodel` files as a quick sanity check.

**Comment by EdwardVincentMa** [comment]
Thanks for answering me！
I tried and tested each layer from the beginning. It is found that the caffe split layer is not supported., it is as bellow:

![image](https://user-images.githubusercontent.com/39480728/82272057-23aa2800-99ac-11ea-9f93-22d67a90ce52.png)

**Comment by EdwardVincentMa** [comment]
the

> Thanks for answering me！
> I tried and tested each layer from the beginning. It is found that the caffe split layer is not supported., it is as bellow:
> 
> ![image](https://user-images.githubusercontent.com/39480728/82272057-23aa2800-99ac-11ea-9f93-22d67a90ce52.png)

if add the split layer, on Win10 the "blobNameToTensor" code in *blobNameToTensor->find(s.c_str())  is a null ptr

**Comment by EdwardVincentMa** [comment]
![image](https://user-images.githubusercontent.com/39480728/82295068-bdd89300-99e1-11ea-9242-249a335fa1da.png)

**Comment by rmccorm4** [comment]
Hi @EdwardVincentMa ,

It looks like the Split op is supported by the ONNX parser: https://github.com/onnx/onnx-tensorrt/blob/84b5be1d6fc03564f2c0dba85a2ee75bad242c2e/builtin_op_importers.cpp#L2987-L3053

The Caffe/UFF parsers are deprecated as of TRT 7.0, please migrate your model/workflow to ONNX models.

@yflv-yanxia recently converted their Caffe model to ONNX here: https://github.com/NVIDIA/TensorRT/issues/514 --> https://github.com/NVIDIA/TensorRT/issues/529, maybe they can help share how they converted Caffe->ONNX. Or you could look for some resources online.

**Comment by EdwardVincentMa** [comment]
> Hi @EdwardVincentMa ,
> 
> It looks like the Split op is supported by the ONNX parser: https://github.com/onnx/onnx-tensorrt/blob/84b5be1d6fc03564f2c0dba85a2ee75bad242c2e/builtin_op_importers.cpp#L2987-L3053
> 
> The Caffe/UFF parsers are deprecated as of TRT 7.0, please migrate your model/workflow to ONNX models.
> 
> @yflv-yanxia recently converted their Caffe model to ONNX here: #514 --> #529, maybe they can help share how they converted Caffe->ONNX. Or you could look for some resources online.
