### ISSUE TITLE
trt model is much slower and bigger than caffe and onnx model

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#558]
## Description

A same model, when using it with caffeparser, it cost about 28ms to infer a batch, when use it with onnxparser, it cost about 36ms. After convert the onnx to trt model(serialize runtime engine), it cost nearly 200ms to do a batch. By the way, the model size is much bigger than its original onnx model file(770M VS 346M). Why?

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080TI
**Nvidia Driver Version**: 390.77
**CUDA Version**: 9.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: ubuntu 16.04 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @HaoLiuHust ,

Can you try running this in a more recent container such as `nvcr.io/nvidia/tensorrt:20.03-py3` (https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt )? I'm curious if you'll get faster inference results with a newer CUDA version that the container comes with, since you're running with CUDA 9.

**Comment by HaoLiuHust** [comment]
@rmccorm4 I have tested with CUDA 10.2, it's OK, the speed is nearly the same when use onnx or trt model. Thanks.
I have an another question, the original onnx model(or caffe model) is about 346 MB, after convert it to trt model, it becomes 845M. I have used it in tensorrt4, the generated trt model was 346MB, what makes it becomes so much bigger in tensorrt7?

**Comment by hadoop2xu** [comment]
i get the same case, why?

**Comment by HaoLiuHust** [comment]
@hadoop2xu they said maybe more optimization kernel used in tensorrt7...

**Comment by vinaykumarngitub** [comment]
I have same issue with respect to the inference time of Caffe and ONNX tensorRT. 
I am performing tensorRT inference on caffe model: Time = 1.3 ms/image
Similarly, performing tensorRT inference on ONNX model: Time = 2.7 ms/image
May I know why this time lag in case of onnx model inference.?


TensorRT Version: 7.0.0.11
GPU Type: GTX 1050 TI
Nvidia Driver Version: 441
CUDA Version: 10.0
CUDNN Version: 7.6.5
Operating System + Version: Windows 10
Python Version (if applicable):
TensorFlow Version (if applicable):
PyTorch Version (if applicable):
Baremetal or Container (if container which image + tag):
