### ISSUE TITLE
Layer for selecting non zero elements from tensor

### ISSUE THREAD

**Issue by rgc183** [NVIDIA/TensorRT#559]
Is there any layer or workaround which will give indices of non zero elements from the tensor.
for example: {{1,2,0}, {3,0,4}}; => {{0,0},{0,1},{1,0},{1,2}}
the output tensor will be of shape: [num_non_zero, num_input_dims]

**Comment by rgc183** [comment]
@rmccorm4

**Comment by whatlas** [comment]
need this too

**Comment by ttyio** [comment]
Hello @rgc183  @whatlas , thanks for reporting.
NoneZero operator's output shape is data dependent, and current TensorRT dynamic shape has no data-dependent dimension support yet. I will create internal issue to tracking this.

**Comment by JaheimLee** [comment]
> tracking

Onnx opset 14 support torch.triu() method. But Tensorrt doesn't has that op now. I think maybe they are the same problem.

**Comment by andrearosasco** [comment]
Does that mean that there isn't a way to do boolean indexing on TensorRT? I'm trying to find a workaround but I can't think of anything.

**Comment by nvpohanh** [comment]
This is on the roadmap.

**Comment by ttyio** [comment]
nonezero is already supported, closing

**Comment by erwangccc** [comment]
Hi, @ttyio 

I wander that if i create a NonZero Plugin whose input format is bool type at v8.4.1, can we convert a onnx model to trt engine successfully? My env is at v8.4.1. Maybe NonZero is available at v8.5.

**Comment by ttyio** [comment]
Hello @erwangccc no, there is no data dependent shape support for plugin in 8.4.

**Comment by CeoiZidung** [comment]
> Hello @erwangccc no, there is no data dependent shape support for plugin in 8.4.

Hi, Could this data dependent shape be supported by 8.x？ if could, how can i set the builder?

**Comment by ttyio** [comment]
> > Hello @erwangccc no, there is no data dependent shape support for plugin in 8.4.
> 
> Hi, Could this data dependent shape be supported by 8.5.x？ if could, how can i set the builder?

Sorry not yet.
