### ISSUE TITLE
tesla P40 does not support FP16?

### ISSUE THREAD

**Issue by jlygit** [NVIDIA/TensorRT#56]
hello,
I run the fp16 mode on P40 when used tensor RT and it can not speed up. 
maybe tesla P40 does not support FP16?
thks

**Comment by DoiiarX** [comment]
Did you got the answer?

**Comment by fbldp** [comment]
Did you got the answer? @DoiiarX @jlygit

**Comment by DoiiarX** [comment]
> 你得到答案了吗？

don't support. no error but no speed up.

**Comment by DoiiarX** [comment]
> Did you got the answer? @DoiiarX @jlygit

https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html

https://developer.nvidia.com/cuda-gpus

Tesla P40 is only 6.2 less than 7.0 which is supported at min.
