### ISSUE TITLE
Calculating MAP using tensorrt C++

### ISSUE THREAD

**Issue by omais-shafi** [NVIDIA/TensorRT#560]
I want to calculate the MAP for my data in C++ TensorRT. For the python version, I could obtain the MAP but for C++, I didn't get anything yet. Can anyone please help with this?

**Comment by ttyio** [comment]
Hello @omais-shafi , thanks for reporting
Could you elaborate more on what is `MAP`? did you mean the ONNX operator to TRT native layer mapping?

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!
