### ISSUE TITLE
multi threads no concurrency effect

### ISSUE THREAD

**Issue by feilingdeng** [NVIDIA/TensorRT#561]
## Description

when only one thread takes ten ms, two threads takes twenty ms, no concurrency effect, seems like has a internal lock in trt, what should i do?

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 2080 Ti
**Nvidia Driver Version**: 3.20.3
**CUDA Version**: 10.2
**CUDNN Version**: 7.6
**Operating System + Version**: win 10 professional

**Comment by kunyao2015** [comment]
same problem, Is there any solution?

**Comment by ttyio** [comment]
Hello @feilingdeng , @kunyao2015 thanks for reporting

Did you run inference in different CUDA stream? You could also run nsight compute to check the SM occupancy and other execution detail, thanks.

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!

**Comment by hoangmt** [comment]
@ttyio I still face this problem. https://github.com/NVIDIA/TensorRT/issues/1238
I need to run efficientdet tensorrt (thanks you guys for helping with the conversion) with another model and wish to cut down the time by multithread. However, from my toy models in the above link, the times seem to be the same.
