### ISSUE TITLE
Repeated execution inference leads to video memory leak（c++ api）

### ISSUE THREAD

**Issue by liupengkd** [NVIDIA/TensorRT#563]
## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 440.82
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.3
**Operating System + Version**: Ubuntu 16.04

##description

I use dynamic size to run a test data set. The size of each image in this data set is different. Run one image at a time, and set the size through the context before running. Then perform forward reasoning. It is found that every time forward reasoning is performed, the program's occupation of video memory will increase, both in synchronous and asynchronous ways. Even if I release the occupied video memory before and after each forward reasoning, my forward code is as follows:

set shape

```
context_->setBindingDimensions(inputIndex_, Dims4(1, 3, d_h, d_w));
```

inference

```
    bool Test::DoInference(float* input, std::vector<float*>& output, int numImages, std::vector<int>& buffsize)
    {
        if(!context_)
            return false;

        void* buffers[5];
        

        //malloc the memory of device for input and outputs
        HandleError(cudaMalloc(&buffers[inputIndex_], buffsize[0]));
        for (int i = 0; i < 4; i++)
        {
            HandleError(cudaMalloc(&buffers[outputIndex_[i]], buffsize[i + 1]));
        }


        //copy input data to device memory from host memory
        HandleError(cudaMemcpyAsync(buffers[inputIndex_], input, buffsize[0], cudaMemcpyHostToDevice, stream_));
        //HandleError(cudaMemcpy(buffers[inputIndex_], input, buffsize[0], cudaMemcpyHostToDevice));
        
        //infer network
        context_->enqueueV2(buffers, stream_, nullptr);
        //context_->executeV2(buffers);
        
        //copy the result of network(output) to host memory from device memory
        for (int i = 0; i < 4; i++)
        {
            HandleError(cudaMemcpyAsync(output[i], buffers[outputIndex_[i]], buffsize[i + 1], cudaMemcpyDeviceToHost, stream_));
            //HandleError(cudaMemcpy(output[i], buffers[outputIndex_[i]], buffsize[i + 1], cudaMemcpyDeviceToHost));
        }

        //synchronize between device and host
        HandleError(cudaStreamSynchronize(stream_));

        //cuda free and destory
        for (int i = 0; i < 5; i++)
        {
            HandleError(cudaFree(buffers[i]));
        }

        return true;
    }
```

Every time I run Doinference, the video memory usage will increase (2-4M). As the number of runs increased, the memory usage gradually increased, which eventually led to an explosion of video memory. Through debugging, in the process of repeatedly performing forward inference of a single picture, there will be no changes in memory usage elsewhere

**Comment by ttyio** [comment]
Hello @liupengkd , thanks for reporting
Do you have custom plugin in the network? Is it possible the leak come from the plugin? Or are you using only native TRT layers?

Also, have you tried TRT 7.2? thanks!

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!
