### ISSUE TITLE
How to use serialized engine do inference？

### ISSUE THREAD

**Issue by EdwardVincentMa** [NVIDIA/TensorRT#566]
Hi~
I can convert caffemodel to serialized engine file, and load this file to trtUniquePtr Obj(mLoadEngine) by runtime->deserializeCudaEngine() function.

And then :
auto context = sample::TrtUniquePtr<nvinfer1::IExecutionContext >(mLoadEngine->createExecutionContext());
It's OK.
And how to use this context to do inference?  trtUniquePtr obj can not adapt BufferManager‘ s first param, I can not use BufferManager to create buffers as samnpleSSD.

The following code will have an error：
![image](https://user-images.githubusercontent.com/39480728/82517907-c13e5c80-9b50-11ea-99b9-e16944801675.png)
And how to use BufferManager to do inference with TrtUniquePtr<nvinfer1::ICudaEngine> obj engine?

**Comment by piaohe111** [comment]
I have met the same problem !  Have you solved it ?
