### ISSUE TITLE
TensorRT6 : nvcc fatal   : redefinition of argument 'std'

### ISSUE THREAD

**Issue by KingWangSeet** [NVIDIA/TensorRT#570]
## Description 
When I make the TnesorRT 6.0:

[ 54%] Built target nvcaffeparser_static
Scanning dependencies of target nvonnxparser_plugin
[ 54%] Building CUDA object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o
nvcc fatal   : redefinition of argument 'std'
make[2]: *** [parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o] Error 1
make[1]: *** [parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
make: *** [all] Error 2

## Environment

Building for TensorRT version: 6.0.1.0, library version: 6.0.1
-- Targeting TRT Platform: x86_64
-- CUDA version set to 9.0
-- cuDNN version set to 7.6
-- Protobuf version set to 3.0.0

## Steps To Reproduce

Step1: cmake .. -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc  -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out -DCUDA_VERSION=9.0 -DCUDNN_VERSION=7.6   **It's ok**

Step2: make

**Comment by KingWangSeet** [comment]
<img width="435" alt="微信图片_20200524223632" src="https://user-images.githubusercontent.com/23491388/82756814-13140a80-9e0f-11ea-8a04-79f2143c9d92.png">

**Comment by KingWangSeet** [comment]
<img width="435" alt="Error_20200524223632" src="https://user-images.githubusercontent.com/23491388/82756838-33dc6000-9e0f-11ea-974b-d84527ac232e.png">

**Comment by KingWangSeet** [comment]
When I make  VERBOSE=1:
<img width="369" alt="Error_20200525094111" src="https://user-images.githubusercontent.com/23491388/82770675-ecd08800-9e6b-11ea-9172-e9f9bc05f8d0.png">

**Comment by KingWangSeet** [comment]
Solve it by 
delete the **list(APPEND CUDA_NVCC_FLAGS -std=c++11)** in the **TensorRT/parsers/onnx/CMakeLists.txt**

**Comment by Hassan313** [comment]
@KingWangSeet Hi King, thank you very much. You saved my day.
