### ISSUE TITLE
TensorRT on Jetson

### ISSUE THREAD

**Issue by eagle717** [NVIDIA/TensorRT#571]
hi, community:

where cat I get the tenssor-7.1 core library (for example, libnvinfer-7.1.0, libnvonnxparser-7.1.0) for  cuda-10.0, current from officical release, we can only get tensorRT lib for cuda-10.2!
Thanks.

**Comment by ttyio** [comment]
Hello @eagle717 , sorry for late response
For L4T platform, the TensorRT is distributed with JetPack, and TRT7.1.3 is used in JepPack 4.4.
https://developer.nvidia.com/embedded/jetpack

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
