### ISSUE TITLE
Implementing transformer decoder using TensorRT

### ISSUE THREAD

**Issue by GarrettLee** [NVIDIA/TensorRT#578]
## Description

Hi,

I am trying to implement a transformer decoder with multiple sequence steps. At first, I didn't use [`tensorrt.ILoop`](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html?highlight=loop#tensorrt.ILoop). I did something like this

```Python
# This is not my actual code. It is simplified here.
yi = '<SOS>'
state = init_state()
for i in range(sequence_len):
    # functions `word_embedding` and `decoder` are implemented with TensorRT
    xi = word_embedding(yi)  # using network.add_gather here
    yi, state = decoder(xi, state)
```

I implemented `word_embedding` using `network.add_gather`. I found it really slow for TensorRT to build cuda engine. It is almost stuck at `builder.build_cuda_engine(network)`. 

Then I tried to implement the `for` statement using `tensorrt.ILoop`. Unfortunately, `network.add_gather` is not supported by `tensorrt.ILoop`. 

Here are my questions:

1. Is it normal that implementation with `for` statement is so slow? If yes, will using `tensorrt.ILoop` help?

2. Any advice on implementing word embedding in `tensorrt.ILoop`?

Thanks in advance.

## Environment

**TensorRT Version**:   7.0.0-1
**GPU Type**:  NVIDIA P100
**Nvidia Driver Version**:  
**CUDA Version**:  10.0
**CUDNN Version**:  
**Operating System + Version**:  Ubuntu 18.04
**Python Version (if applicable)**:  3.6
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by ttyio** [comment]
Hello @GarrettLee  , thanks for reporting.
For the tactic slowness, could you try release 7.2? we have tactic cache support, for layers in a loop that has same problem size, the tactic time is saved when tactic cache is hit.
For the gather support in ILoop, I have create internal feature request to track this.

**Comment by ttyio** [comment]
The gather support in ILoop will be in next release 
closing, thanks!
