### ISSUE TITLE
How does tensorrt.py script calibrate the graph without the the calibration dataset? 

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/TensorRT#58]
Hi all, i would like to know how does tensorrt.py script calibrate the graph without the calibration dataset? 

```python
def get_trt_graph_from_calib(graph_name, converter, data, input_node, output_node,
                             output_dir, num_loops=100):
  """Convert a TensorRT graph used for calibration to an inference graph."""
  converter.convert()
  def input_fn():
    iterator = get_iterator(data)
    return {input_node: iterator.get_next()}
  trt_graph = converter.calibrate(
    fetch_names=[output_node],
    num_runs=num_loops,
    input_map_fn=input_fn)
  write_graph_to_file(graph_name, trt_graph, output_dir)
  return trt_graph
```

**Comment by rmccorm4** [comment]
Hi @vilmara,

I'm pretty sure that the `input_fn` defines how to feed the data into the calibrator to do calibration:
```
def input_fn():
    iterator = get_iterator(data)
    return {input_node: iterator.get_next()}
```

And they pass in data to use for calibration when they call this function in that script: https://github.com/pplior/tensorflow-models/blob/master/research/tensorrt/tensorrt.py#L447-L451

See the docs on this: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#tf-trt-api
