### ISSUE TITLE
faster rcnn tensorRT 

### ISSUE THREAD

**Issue by yshvrdhn** [NVIDIA/TensorRT#580]
## Description

H
Is there a way to support pytorch fasterrcnn conversion to tensorrt.
## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by felipevw** [comment]
Nvidia supposedly says yes, but I am having a lot of issues. All the ONNX models for object detection present a lot of unsupported operations. I posted [this](https://forums.developer.nvidia.com/t/tensorrt-onnx-error/125391/2).
Right now I am thinking of using onnx-simplifier or try to load the model through pytorch2trt and load a tensorrt engine in C++.
If you find anything that could help me, I would appreciate a lot.

**Comment by yshvrdhn** [comment]
sure If I find something I will let you know

**Comment by ttyio** [comment]
Hello @yshvrdhn , currently we have a uff sample that can run with faster rcnn in 
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffFasterRCNN
Also there is a TF-TRT sample in 
https://github.com/tensorflow/models/blob/master/research/object_detection/models/faster_rcnn_resnet_v1_feature_extractor.py

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
