### ISSUE TITLE
Two output nodes in uff mode

### ISSUE THREAD

**Issue by ArtlyStyles** [NVIDIA/TensorRT#584]
Can I have two output nodes in the uff mode and use tensorRT to run it?

**Comment by pranavm-nvidia** [comment]
Yes, you can register multiple outputs: https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/parsers/Uff/pyUff.html#tensorrt.UffParser.register_output

**Comment by ttyio** [comment]
Close since we already answered and there is no activities in the past 3 weeks, please create another issue if you still have problems, thanks!
