### ISSUE TITLE
TF-TRT5.1 - Unconverted TensorFlow Ops ArgMax on TensorFlow Container 19.07 (TensorFlow 1.14)

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/TensorRT#59]
hi all, I am running tensorrt.py script using the TensorFlow Container 19.07 (TensorFlow 1.14) and I got the Unconverted TensorFlow Ops message `There are 4 ops of 3 different types in the graph that are not converted to TensorRT: ArgMax, NoOp, Placeholder`, (For more information see https://docs.nvidia.com/deeplearning/dgx/tf-trt-user-guide/index.html#supported-ops).

Why the system doesn't convert  ArgMax operations eventhough it is shown as supported on TensorFlow Container 19.07 (TensorFlow 1.14)?

**Comment by trevor-m** [comment]
Hey @vilmara, there are a few reasons why an ArgMax op may not be converted. It could be due to parameters (TRT doesn't support INT64 types or manipulation of the batch dimension), or due to segmentation (if the ArgMax is the output of the model - this can be solved by following it with an Identity and setting that identity as the output).

You can see the exact reason by running your script with the `TF_CPP_VMODULE=segment=2` environment variable.

**Comment by vilmara** [comment]
Hi @trevor-m , thanks for your promt reply. I am using ArgMax as the output of the model. I ran again the test witht the envirment variable `TF_CPP_VMODULE=segment=2` and got this:

```
Not a TF-TRT candidate, (Op type: ArgMax), (Op name: ArgMax), (Reason: excluded by segmenter option)
2019-08-02 19:17:52.106718: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:460] There are 4 ops of 3 different types in the graph that are not converted to TensorRT: ArgMax, NoOp, Placeholder, (For more information see https://docs.nvidia.com/deeplearning/dgx/tf-trt-user-guide/index.html#supported-ops).
```

Do you have a link or sample where I can see how to solve it by "following it with an Identity and setting that identity as the output"?

Thanks

**Comment by trevor-m** [comment]
@vilmara When constructing your model, simply add an identity node like this:
```
x  = tf.placeholder(...)
# ... rest of model ...
x = tf.argmax(x, axis=1)
# Add identity
x = tf.identity(x, name='output')
```
Then make sure you use 'output' for the output name when freezing the graph or using the TF-TRT API.
