### ISSUE TITLE
Compile Error while make -j in CentOS?

### ISSUE THREAD

**Issue by warren-lei** [NVIDIA/TensorRT#590]
## Description
`third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx-ml.pb.cc.o): In function `onnx2trt_onnx::TypeProto::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0x3bb): undefined reference to `google_private::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx-ml.pb.cc.o): In function `onnx2trt_onnx::GraphProto::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0x7bc): undefined reference to `google_private::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0x7d4): undefined reference to `google_private::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx-ml.pb.cc.o): In function `onnx2trt_onnx::StringStringEntryProto::SerializeWithCachedSizes(google_private::protobuf::io::CodedOutputStream*) const':
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0xaf5): undefined reference to `google_private::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_private::protobuf::io::CodedOutputStream*)'
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0xb0d): undefined reference to `google_private::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_private::protobuf::io::CodedOutputStream*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx-ml.pb.cc.o): In function `onnx2trt_onnx::TypeProto_Opaque::SerializeWithCachedSizes(google_private::protobuf::io::CodedOutputStream*) const':
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0xbf5): undefined reference to `google_private::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_private::protobuf::io::CodedOutputStream*)'
onnx_onnx2trt_onnx-ml.pb.cc:(.text+0xc0d): undefined reference to `google_private::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google_private::protobuf::io::CodedOutputStream*)'

...

`
ModelImporter.cpp:(.text+0x8ceb): undefined reference to `google_private::protobuf::TextFormat::PrintToString(google_private::protobuf::Message const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
collect2: error: ld returned 1 exit status
make[2]: *** [parsers/onnx/getSupportedAPITest] Error 1
make[1]: *** [parsers/onnx/CMakeFiles/getSupportedAPITest.dir/all] Error 2
make: *** [all] Error 2
`
I can not find the error reason.
`

**Comment by warren-lei** [comment]
eg:
`
virtual void | setErrorRecorder (IErrorRecorder *recorder)=0
`
In class IBuilder, how to use this method?

**Comment by mk-nvidia** [comment]
@warren-lei please add details of the version of TensorRT you used, CUDA versions, and whether you tried a native or container build.

**Comment by warren-lei** [comment]
After commenting out onnx, the compilation is successful.
Thanks for your reply.

**Comment by warren-lei** [comment]
> @warren-lei please add details of the version of TensorRT you used, CUDA versions, and whether you tried a native or container build.

After commenting out onnx, the compilation is successful.
Thanks for your reply.

**Comment by ttyio** [comment]
Closing since the issue solved, thanks!

**Comment by redlibo** [comment]
Same thing happens to me. 
centos7.8 cuda10.2 cudnn8.0 tensorrt7.2.1

[ 98%] Linking CXX executable getSupportedAPITest

cd /usr/src/TensorRT/build/parsers/onnx && /usr/local/cmake/bin/cmake -E cmake_link_script CMakeFiles/getSupportedAPITest.dir/link.txt --verbose=1
/usr/local/bin/g++  -Wno-deprecated-declarations  -DBUILD_SYSTEM=cmake_oss -Wall -Wno-deprecated-declarations -Wno-unused-function -O3 -DNDEBUG   CMakeFiles/getSupportedAPITest.dir/getSupportedAPITest.cpp.o CMakeFiles/getSupportedAPITest.dir/ModelImporter.cpp.o  -o getSupportedAPITest ../../third_party.protobuf/lib64/libprotobuf.a libnvonnxparser_static.a -lpthread -ldl third_party/onnx/libonnx_proto.a ../../third_party.protobuf/lib64/libprotobuf.a /usr/src/TensorRT-7.2.1.6/lib/libnvinfer.so /usr/src/TensorRT-7.2.1.6/lib/libnvinfer_plugin.so /usr/src/TensorRT-7.2.1.6/lib/libmyelin.so

libnvonnxparser_static.a(builtin_op_importers.cpp.o)：‘onnx2trt::(anonymous namespace)::importFallbackPluginImporter(onnx2trt::IImporterContext*, onnx2trt_onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&)’：
builtin_op_importers.cpp:(.text+0x3e7c0)：undefined reference to ‘google_private::protobuf::internal::NameOfEnum[abi:cxx11](google_private::protobuf::EnumDescriptor const*, int)’

...

collect2: error: ld returned 1 exit status
make[2]: *** [parsers/onnx/CMakeFiles/getSupportedAPITest.dir/build.make:106：parsers/onnx/getSupportedAPITest] Error 1
make[1]: *** [CMakeFiles/Makefile2:1223：parsers/onnx/CMakeFiles/getSupportedAPITest.dir/all] Error 2
make: *** [all] Error 2

**Comment by ttyio** [comment]
@redlibo Have you tried docker?
