### ISSUE TITLE
Tensorflow -> ONNX -> TRT not working for Object Detection

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/TensorRT#592]
Hello everyone,

As suggested by the TRT documentation and Nvidia forums I am trying to move away from UFF into ONNX adoption.

Our workflow is to train on cloud GPUs and then run inference on Jetson Nano (JP44) with Triton.

Unfortunately the recommended way of going Tensorflow -> ONNX -> TensorRT doesn't work for any of the standard TF Object Detection models, nor the ones we train ourselves.

Reproduction:

1. Download **SSD Mobilenet V2 COCO** from TF Zoo. [OK]
2. Convert the model from savedmodel to ONNX. [OK]
```
python3 -m tf2onnx.convert --saved-model /workspace/ssd_mobilenet_v2_coco_2018_03_29/saved_model --output /workspace/ssd.onnx --opset 11 --fold_const 
```
3. Convert ONNX-Optimized model to TRT engine. [FAIL]

I get the following errors:

```
root@0ad2809d6ee2:/workspace# /usr/src/tensorrt/bin/trtexec --onnx=ssd.onnx 
&&&& RUNNING TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --onnx=ssd.onnx
[06/05/2020-08:55:54] [I] === Model Options ===
[06/05/2020-08:55:54] [I] Format: ONNX
[06/05/2020-08:55:54] [I] Model: ssd.onnx
[06/05/2020-08:55:54] [I] Output:
[06/05/2020-08:55:54] [I] === Build Options ===
[06/05/2020-08:55:54] [I] Max batch: 1
[06/05/2020-08:55:54] [I] Workspace: 16 MB
[06/05/2020-08:55:54] [I] minTiming: 1
[06/05/2020-08:55:54] [I] avgTiming: 8
[06/05/2020-08:55:54] [I] Precision: FP32
[06/05/2020-08:55:54] [I] Calibration: 
[06/05/2020-08:55:54] [I] Safe mode: Disabled
[06/05/2020-08:55:54] [I] Save engine: 
[06/05/2020-08:55:54] [I] Load engine: 
[06/05/2020-08:55:54] [I] Builder Cache: Enabled
[06/05/2020-08:55:54] [I] NVTX verbosity: 0
[06/05/2020-08:55:54] [I] Inputs format: fp32:CHW
[06/05/2020-08:55:54] [I] Outputs format: fp32:CHW
[06/05/2020-08:55:54] [I] Input build shapes: model
[06/05/2020-08:55:54] [I] Input calibration shapes: model
[06/05/2020-08:55:54] [I] === System Options ===
[06/05/2020-08:55:54] [I] Device: 0
[06/05/2020-08:55:54] [I] DLACore: 
[06/05/2020-08:55:54] [I] Plugins:
[06/05/2020-08:55:54] [I] === Inference Options ===
[06/05/2020-08:55:54] [I] Batch: 1
[06/05/2020-08:55:54] [I] Input inference shapes: model
[06/05/2020-08:55:54] [I] Iterations: 10
[06/05/2020-08:55:54] [I] Duration: 3s (+ 200ms warm up)
[06/05/2020-08:55:54] [I] Sleep time: 0ms
[06/05/2020-08:55:54] [I] Streams: 1
[06/05/2020-08:55:54] [I] ExposeDMA: Disabled
[06/05/2020-08:55:54] [I] Spin-wait: Disabled
[06/05/2020-08:55:54] [I] Multithreading: Disabled
[06/05/2020-08:55:54] [I] CUDA Graph: Disabled
[06/05/2020-08:55:54] [I] Skip inference: Disabled
[06/05/2020-08:55:54] [I] Inputs:
[06/05/2020-08:55:54] [I] === Reporting Options ===
[06/05/2020-08:55:54] [I] Verbose: Disabled
[06/05/2020-08:55:54] [I] Averages: 10 inferences
[06/05/2020-08:55:54] [I] Percentile: 99
[06/05/2020-08:55:54] [I] Dump output: Disabled
[06/05/2020-08:55:54] [I] Profile: Disabled
[06/05/2020-08:55:54] [I] Export timing to JSON file: 
[06/05/2020-08:55:54] [I] Export output to JSON file: 
[06/05/2020-08:55:54] [I] Export profile to JSON file: 
[06/05/2020-08:55:54] [I] 
----------------------------------------------------------------
Input filename:   ssd.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    tf2onnx
Producer version: 1.6.0
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Unsupported ONNX data type: UINT8 (2)
ERROR: image_tensor:0:191 In function importInput:
[8] Assertion failed: convertDtype(onnxDtype.elem_type(), &trtDtype)
[06/05/2020-08:55:56] [E] Failed to parse onnx file
[06/05/2020-08:55:56] [E] Parsing model failed
[06/05/2020-08:55:56] [E] Engine creation failed
[06/05/2020-08:55:56] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --onnx=ssd.onnx
```

**Comment by turowicz** [comment]
Honestly what is the point of migrating to ONNX if TRT doesn't support the most basic workflow.

**Comment by turowicz** [comment]
@deadeyegoodwin perhaps you know someone who might help?

**Comment by turowicz** [comment]
@jignparm perhaps there is something I can set during the tf2onnx conversion to fix this?

**Comment by turowicz** [comment]
Or should I just start using Transfer Learning Toolkit instead of Tensorflow? Would that make my experience much smoother or are there hurdles with it too?

**Comment by qin2294096** [comment]
@turowicz 
In your traceback, it says 'Unsupported ONNX data type: UINT8 (2)'. 
So I think you can try to change the input data type in tensorflow graph from tf.uint8 to tf.float32.

**Comment by turowicz** [comment]
@qin2294096 the graph is provided from [TF model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) so unfortunately its not possible to do it without having to retrain the models - which defeats the point of using TF and their model zoo in the first place.

TensorRT is being advertised as a easy to use drop in replacement for inference runtime, but it doesn't seem to support the most commonly used frameworks and models?

**Comment by rgc183** [comment]
You can modify onnx parser onnx2trt_utils.cpp to convert uint8 to another data type maybe fp16 or float32 and provide your inputs in float tensor. It works. I have done the same thing.

**Comment by turowicz** [comment]
@rgc183 I'm afraid that wouldn't work as all weights would have to be recalculated. 

Why isn't TRT team interested in having support for TF Object Detection, one of the most commonly used frameworks in the wild.

**Comment by svetlanadataper** [comment]
I have the same problem, I am surprised this is not looked into more ....I cannot convert from ONNX to TRT

**Comment by rgc183** [comment]
I thought convert_weights is doing the conversion. I faced the issue only for inputs and type casting worked for me.

**Comment by svetlanadataper** [comment]
> I thought convert_weights is doing the conversion. I faced the issue only for inputs and type casting worked for me.

Hello,

How did you do the conversion if you don't mind telling from ONNX to TRT?

Thank you

Svetlana

**Comment by rgc183** [comment]
@svetlanadataper Just add 
`case ::ONNX_NAMESPACE::TensorProto::UINT8: *trt_dtype = nvinfer1::DataType::kFLOAT; break;`
https://github.com/onnx/onnx-tensorrt/blob/master/onnx2trt_utils.cpp#L212 and make sure that you pass all uint8 data as float. If any of your intermediate layer is using UINT8, you can use `cast` operator: https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L317

**Comment by Ram-Godavarthi** [comment]
Hi @rgc183 ,

Hi, I have install onnx using pip3 install tf2onnx

I want to convert my custom trained ssd inception v2 model to onnx and then to tensorRT (c++)

what command should I run and what modifications should I do??
Where will I find this file in my system to make changes??

case ::ONNX_NAMESPACE::TensorProto::UINT8: *trt_dtype = nvinfer1::DataType::kFLOAT; break;
https://github.com/onnx/onnx-tensorrt/blob/master/onnx2trt_utils.cpp#L212



Please let me know the possible steps to make it work in tensorrt.

Thank you

**Comment by turowicz** [comment]
@rmccorm4 could you assign a milestone to this issue?

**Comment by turowicz** [comment]
> @svetlanadataper Just add
> `case ::ONNX_NAMESPACE::TensorProto::UINT8: *trt_dtype = nvinfer1::DataType::kFLOAT; break;`
> https://github.com/onnx/onnx-tensorrt/blob/master/onnx2trt_utils.cpp#L212 and make sure that you pass all uint8 data as float. If any of your intermediate layer is using UINT8, you can use `cast` operator: https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L317

@rgc183 does this mean your inference works well with this solution?

**Comment by bnascimento** [comment]
> @svetlanadataper Just add
> `case ::ONNX_NAMESPACE::TensorProto::UINT8: *trt_dtype = nvinfer1::DataType::kFLOAT; break;`
> https://github.com/onnx/onnx-tensorrt/blob/master/onnx2trt_utils.cpp#L212 and make sure that you pass all uint8 data as float. If any of your intermediate layer is using UINT8, you can use `cast` operator: https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L317

Hi guys, I tried @rgc183 solution for a tf2.x object detection api model. But stumbled into another issue.

# onnx2trt model.onnx -o model.trt
----------------------------------------------------------------
Input filename:   model.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    tf2onnx
Producer version: 1.8.0
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
Parsing model
[2020-10-26 13:06:18 WARNING] /opt/onnx-tensorrt/onnx2trt_utils.cpp:221: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2020-10-26 13:06:18 WARNING] /opt/onnx-tensorrt/onnx2trt_utils.cpp:247: One or more weights outside the range of INT32 was clamped
While parsing node number 8 [Resize -> "Resize__36:0"]:
ERROR: /opt/onnx-tensorrt/builtin_op_importers.cpp:2616 In function importResize:
[8] Assertion failed: (transformationMode == "half_pixel" || transformationMode == "pytorch_half_pixel" || transformationMode == "align_corners") && "TensorRT only supports half_pixel, pytorch_half_pixel, and align_corners transofmration modes for linear resizes when sizes are provided!"

Has anyone seen similar issue before?

**Comment by DJT777** [comment]
@bnascimento 

I am getting that exact output.

**Comment by bnascimento** [comment]
that error I believe is because of lack of support from onnx to bilinear interpolation 
see https://github.com/tensorflow/models/blob/master/research/object_detection/protos/image_resizer.proto 
change fixed resizer (or the resizer your model is using to use nearest neighbor instead.
compile the proto with 
`protoc object_detection/protos/*.proto --python_out=.` as seen on the module instructions https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md
retrain again with NN interpolation 
and try then
after this you should stumble into another issue. maybe we can help each other advance this
cheers

**Comment by DJT777** [comment]
@bnascimento 

thanks for sharing information on this. Would be good to solve it.

**Comment by hoangmt** [comment]
Any update on this issue?
In case someone still have this error "Assertion failed: convertDtype(onnxDtype.elem_type(), &trtDtype)" and other error relate to UINT8, INT64, it can be solved by converting format using onnx_graphsurgeon. For example:
```python
import onnx_graphsurgeon as gs
import onnx
import numpy as np
graph=gs.import_onnx(onnx.load('ssd_mobilenet_v2_320x320_coco17_tpu-8.onnx'))
for inp in graph.inputs:
    inp.dtype = np.float32
onnx.save_model(gs.export_onnx(graph), 'outputmodel.onnx')
```
However, after fixing this type of not supported format, I still face the problem of nms operator.

**Comment by stardust2602** [comment]
> Any update on this issue?
> In case someone still have this error "Assertion failed: convertDtype(onnxDtype.elem_type(), &trtDtype)" and other error relate to UINT8, INT64, it can be solved by converting format using onnx_graphsurgeon. For example:
> 
> ```python
> import onnx_graphsurgeon as gs
> import onnx
> import numpy as np
> graph=gs.import_onnx(onnx.load('ssd_mobilenet_v2_320x320_coco17_tpu-8.onnx'))
> for inp in graph.inputs:
>     inp.dtype = np.float32
> onnx.save_model(gs.export_onnx(graph), 'outputmodel.onnx')
> ```
> 
> However, after fixing this type of not supported format, I still face the problem of NonMaxSuppression operator. There are tricks of converting using BatchedNMS_TRT pluggin, something like below:
> 
> ```python
> for node in graph.nodes:
>     if node.op == 'NonMaxSuppression':
>         node.op = "BatchedNMS_TRT"
>         max_output_boxes_per_class, iou_threshold, score_threshold = node.inputs[2:]
>         attrs = {
>                 "shareLocation": True,
>                 "numClasses": 10,
>                 "backgroundLabelId": -1,
>                 "topK": 1024,
>                 "keepTopK": max_output_boxes_per_class,
>                 "scoreThreshold": score_threshold,
>                 "iouThreshold": iou_threshold,
>                 "isNormalized": True,
>                 "clipBoxes": True
>             }
>         node.attrs =attrs
>         node.inputs[0].dtype = np.int32
>         node.outputs[0].dtype = np.int32
>         node.inputs = node.inputs[0:2]
> ```
> 
> Nevertheless, this still does not work. I guess something todo with the difference in output of BatchedNMS_TRT and original NonMaxSuppression

Hi, any updates on this ?

**Comment by turowicz** [comment]
@sabaridsn we have dropped TF in favour of Pytorch and YOLO

**Comment by azhurkevich** [comment]
If somebody is still interested, you can try a [sample](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) we've posted in fall. Please follow the [instructions](https://github.com/NVIDIA/TensorRT/blob/main/samples/python/tensorflow_object_detection_api/README.md) closely. This is for pretrained TFOD models from the [zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). If you have a custom model we cannot guarantee flawless conversion but it can certainly be done, if you are willing to read through code. I made sure there are a lot of comments that will help.

**Comment by ttyio** [comment]
closing inactive issues, thanks all!
