### ISSUE TITLE
gpu memory leak when using dynamic input 

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#593]
## Description

I am upgrading tensorrt4 to tensorrt7, when using dynamic input in tensorrt7, gpu usage was keep growing, but use fixed batchsize, its performance is slower than dynamic input. 
https://forums.developer.nvidia.com/t/context-setbindingdimensions-casing-gpu-memory-leak/83423

I found that your team have already fixed this problem, when will it release?

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 
**Operating System + Version**: 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by liupengkd** [comment]
@HaoLiuHust  the interface(context_->setBindingDimensions) seems to be non-reentrant，In the life cycle of a context, it seems that it can only be called once.Multiple calls will have the problem of cumulative video memory. The dynamics of trt more reflect the angle of engine file generation。

**Comment by HaoLiuHust** [comment]
testing it on 2080Ti, it will be ok @liupengkd , it definitely a bug

**Comment by liupengkd** [comment]
@HaoLiuHust I only tested in 1080ti. When I re-entered the size setting interface, it leaked video memory. I submitted an issue at the time, but the official website did not reply. Then I found that when I do not reenter the size setting interface, it will not accumulate video memory

**Comment by HaoLiuHust** [comment]
But if you not re-enter it, you are using your dynamic model with static batchsize @liupengkd

**Comment by HaoLiuHust** [comment]
tested on tensorrt 7.1 GA, no memory leak now on 1080Ti

**Comment by xusk** [comment]
> tested on tensorrt 7.1 GA, no memory leak now on 1080Ti

are you sure ?  the tensorrt 7.0.11  find gpu memery leak

**Comment by HaoLiuHust** [comment]
> > tested on tensorrt 7.1 GA, no memory leak now on 1080Ti
> 
> are you sure ? the tensorrt 7.0.11 find gpu memery leak

Yes, I am sure, I have use 7.1 GA in our products.

**Comment by xusk** [comment]
> > > tested on tensorrt 7.1 GA, no memory leak now on 1080Ti
> > 
> > 
> > are you sure ? the tensorrt 7.0.11 find gpu memery leak
> 
> Yes, I am sure, I have use 7.1 GA in our products.

thanks, i’m ok

**Comment by marsmiao** [comment]
> tested on tensorrt 7.1 GA, no memory leak now on 1080Ti

Are you sure the different batch-size output is correct? maybe you check the memory leak but not the result?

**Comment by HaoLiuHust** [comment]
> > tested on tensorrt 7.1 GA, no memory leak now on 1080Ti
> 
> Are you sure the different batch-size output is correct? maybe you check the memory leak but not the result?

We already used it in our products, it is correct
