### ISSUE TITLE
TensorRT InstanceNormalization is too slow

### ISSUE THREAD

**Issue by jalola** [NVIDIA/TensorRT#595]
## Environment

**TensorRT Version**:  7.0.0-1+cuda10.2
**GPU Type**: V100
**Nvidia Driver Version**: 410.79
**CUDA Version**: 10.2
**CUDNN Version**: 7
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 2.1.0+nv
**PyTorch Version (if applicable)**: 1.5.0
**Baremetal or Container (if container which image + tag)**: nvcr.io/nvidia/tensorflow:20.02-tf2-py3

## Relevant Files

The example and output onnx file can be downloaded here:
https://github.com/jalola/tensorrt-instancenorm/blob/master/keras_instance_norm_1.onnx

## Steps To Reproduce

I used this code below to convert TF model to onnx and then convert onnx to TensorRT normally. However, the speed of tensorRT is very slow, like 10 times slower. I also tried raw code of `InstanceNormalization` (not using tensorflow_addons) but the speed is also slow like 2 times than TF.

I will try with Pytorch and let you know

```
import os
import tensorflow as tf
import tensorflow_addons as tfa
os.environ["CUDA_VISIBLE_DEVICES"] = str(0)
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[int(0)], True)

tf.keras.backend.set_learning_phase(0)

model = tf.keras.models.Sequential([
  tf.keras.layers.Reshape((512,512,1), input_shape=(512, 512)),
  tf.keras.layers.Conv2D(filters=64, kernel_size=(3,3), data_format="channels_last", padding="SAME"),

  tfa.layers.InstanceNormalization(axis=3, 
                                   center=True, 
                                   scale=True,
                                   beta_initializer="random_uniform",
                                   gamma_initializer="random_uniform"),
  tf.keras.layers.Conv2D(filters=3, kernel_size=(3,3), data_format="channels_last", padding="SAME")
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
              
              
output = "tf_model/saved_model_1.0/"
onnx_file = "onnx/keras_instance_norm_1.onnx"

tf.saved_model.save(model, str(output))

# I use this command to convert tensorflow model to onnx
# python3.6 -m tf2onnx.convert --opset 11  --saved-model $output --output $onnx_file
```

**Comment by jalola** [comment]
I also tried Pytorch, when the model is converted to onnx, it looks simpler when it cannot be converted to TensorRT due to "InstanceNormalization : Unsupported layer"

**Comment by rexxar-liang** [comment]
some problem.

**Comment by ttyio** [comment]
Hello @jalola , sorry for the delay response,
according to https://github.com/onnx/onnx-tensorrt/issues/374 the error is fixed in latest build.
Have you tried release 7.2? thanks!

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
