### ISSUE TITLE
sample ssd inference on tensorRT for video file using c++ api

### ISSUE THREAD

**Issue by Ram-Godavarthi** [NVIDIA/TensorRT#597]
Hi,

I am finding it difficult to implement/modify the code to read the video file and perform inference in tensorRT for a ssd mobilenet model. I could able to do it for single input (dog.ppm, bus.ppm). But how to do it for a video file.

Any suggestions would be appreciated.

Thank you

**Comment by ttyio** [comment]
Hello @Ram-Godavarthi , thanks for reporting
we have a video decoder API, here is the link:
https://docs.nvidia.com/video-technologies/video-codec-sdk/nvdec-video-decoder-api-prog-guide/

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
