### ISSUE TITLE
RNNv2 documentation

### ISSUE THREAD

**Issue by haifenghan** [NVIDIA/TensorRT#598]
From the link https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html?highlight=rnnv2#tensorrt.IRNNv2Layer, I see the variables num_layers and data_length have the same description:

> num_layers – int The layer count of the RNN.

> data_length – int The layer count of the RNN.

Are they the same or is it an issue?

**Comment by ttyio** [comment]
Thanks @haifenghan for reporting, now fixed in the link, could you help to check?

**Comment by haifenghan** [comment]
It's OK for me. Thanks for the update @ttyio
