### ISSUE TITLE
Error saving serialization engine

### ISSUE THREAD

**Issue by EdwardVincentMa** [NVIDIA/TensorRT#599]
Each time the serialized engine is saved, the saved file size is different. But the ngineFile.write(static_cast<char*>(serializedEngine->data()), serializedEngine->size()) function did not return false.

Because SerializedEngine->size() is different every time.

**Comment by rmccorm4** [comment]
Hi @EdwardVincentMa, 

I don't understand, is this a question? The engine file size likely differs based on the underlying tactics/kernels chosen at build time, which can be different on each build. With TRT 7.1, there is an IAlgorithmSelector API which I believe can be used to make this more deterministic.

**Comment by ttyio** [comment]
Close since we already answered and there is no activities in the past 3 weeks, please create another issue if you still have problems, thanks!
