### ISSUE TITLE
sampleSSD inference on jetson nano error

### ISSUE THREAD

**Issue by Ram-Godavarthi** [NVIDIA/TensorRT#600]
Hi,

I am trying to execute sampleSSD from /usr/src/tensorrt/sample/sampleSSD folder. 
I have made the changes specified inthe README file as:
replaced type: Flatten -> Reshape
replaced flatten_param { .... } -> reshape_param{....}

also replaced detect_out top: with keep_count.

But I am getting this error.

Can someone throw some suggestion to it to make it work.

&&&& RUNNING TensorRT.sample_ssd # ./sample_ssd
[05/08/2020-11:45:45] [I] Building and running a GPU inference engine for SSD
Plugin layer output count is not equal to caffe output count
Segmentation fault (core dumped)

Here is the file: 
[ssd.prototxt](https://drive.google.com/file/d/1bMTJL6TbuLBRsjGiz6aH1humqp0o8CW9/view?usp=sharingl)

Thank you

**Comment by ttyio** [comment]
Hello @Ram-Godavarthi , sorry for the delay response,
which version are you using?
Have you tried latest release 7.2?

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
