### ISSUE TITLE
Custom Mask RCNN- Assertion `mAnchorsCnt == (int) (mAnchorBoxesHost.size() / 4)' failed

### ISSUE THREAD

**Issue by ApoorvaSuresh** [NVIDIA/TensorRT#604]
I can build and run inference on the model, but it gets aborted mid-way:

[05/09/2020-17:25:01] [I] Building and running a GPU inference engine for Mask RCNN
[05/09/2020-17:25:20] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[05/09/2020-17:26:36] [I] [TRT] Detected 1 inputs and 2 output network tensors.
sample_maskRCNN: /home/adm.Z662728/code/TensorRT/plugin/proposalLayerPlugin/proposalLayerPlugin.cpp:344: virtual void nvinfer1::plugin::ProposalLayer::configurePlugin(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, const nvinfer1::DataType*, const nvinfer1::DataType*, const bool*, const bool*, nvinfer1::PluginFormat, int): Assertion `mAnchorsCnt == (int) (mAnchorBoxesHost.size() / 4)' failed.
Aborted

I do not understand where the issue could be, **Assertion `mAnchorsCnt == (int) (mAnchorBoxesHost.size() / 4)' failed.** is not quite self-explainatory. 

If someone has any idea how to resolve this issue or has some input, please let me know.

Thanks in advance :)

**Comment by ttyio** [comment]
Hello @ApoorvaSuresh , from the doc https://github.com/NVIDIA/TensorRT/tree/master/plugin/proposalLayerPlugin

We have 

int[3] | image_size | Input image size in CHW. Only supports C=3 and defaults to [3,1024,1024].
-- | -- | --


What's your `image_size` and input tensor dimension to this plugin? Thanks.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
