### ISSUE TITLE
Onnx model load failed

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#607]
## Description

I am loading an Onnx model, tested it with onnxruntime, it is ok, but when using it with tensorrt, it crashed in parser->parseFromFile

![image](https://user-images.githubusercontent.com/7233091/84262147-aeb3b380-ab4f-11ea-9687-097e432d3d58.png)

seems global average pooling load failed

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080Ti
**Nvidia Driver Version**: 440 
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

[1105fbr_4_refine.zip](https://github.com/NVIDIA/TensorRT/files/4758105/1105fbr_4_refine.zip)

## Steps To Reproduce

load this onnx model

**Comment by rmccorm4** [comment]
Hi @HaoLiuHust ,

It seems this has already been fixed in TensorRT 7.1:

```
PASSED TensorRT.trtexec # trtexec --explicitBatch --onnx=1105fbr_4_refine.onnx
```

Please try upgrading. I can re-open this issue if you still have problems after upgrading.
