### ISSUE TITLE
validateInputsCutensor

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#608]
## Description
[TensorRT] ERROR: ../rtSafe/cuda/cutensorReformat.cpp (226) - Assertion Error in executeCutensor: 0 (validateInputsCutensor(src, dst))

## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment]
Hi @taomiao ,

Please share the model and code used to reproduce this error per the template.

**Comment by wyhao31** [comment]
Same error. The dimension looks ok to me. No idea about such error message.

**Comment by ttyio** [comment]
Hello @taomiao @wyhao31 , thanks for reporting.
Could you retry release 7.2? share the model with us if the issue still exist, thanks!

**Comment by ttyio** [comment]
Closing because no response for more than 3 weeks, please reopen if you still see issue, thanks.
