### ISSUE TITLE
inconsistent on 1080Ti and 2080Ti

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#610]
## Description

Running a same model on 1080Ti and 2080Ti, all is ok on 1080Ti, but 2080Ti will raise an error when batch size is larger than 1.

ERROR: ../rtSafe/cuda/caskFullyConnectedRunner.cpp (288) - Cuda Error in execute: 1 (invalid argument)
ERROR: FAILED_EXECUTION: std::exception

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080Ti and 2080Ti
**Nvidia Driver Version**: 440
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: 16.04 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by HaoLiuHust** [comment]
I found that on 2080Ti, context->execute(n, buffer) can not change n when doing inference, otherwise it will be crashed in ERROR: ../rtSafe/cuda/caskFullyConnectedRunner.cpp (288) - Cuda Error in execute: 1 (invalid argument)
ERROR: FAILED_EXECUTION: std::exception

**Comment by HaoLiuHust** [comment]
I have tried sampleMNIST, if I put cudaStreamCreate(&stream) at SampleMNIST construction function, problem will be produced, other wise , it will be OK

**Comment by HaoLiuHust** [comment]
you can reproduce the problem with sampleMNIST.cpp provide in https://drive.google.com/drive/folders/1BAcKVbOEt3DYL_k7IMdubn1TBM2Jbnhq?usp=sharing

**Comment by HaoLiuHust** [comment]
tested on P100, it's ok. Only 2080Ti has these problems

**Comment by ttyio** [comment]
Hello @HaoLiuHust , thanks for reporting
Could you help to try if the problem still exist in TensorRT 7.2, please download from https://developer.nvidia.com/nvidia-tensorrt-download. 
thanks!

**Comment by HaoLiuHust** [comment]
Tested it on 7.1GA, it's ok now. Sorry for the late confirm
