### ISSUE TITLE
rectangular gridAnchorPlugin support for tensorrt7 

### ISSUE THREAD

**Issue by yshvrdhn** [NVIDIA/TensorRT#612]
## Description
Is there a particular reason why the rectangular feature map support for Achor Plugin support for tensorrt7 has not been upgraded from tensorrt6 ? 

Also How do I make it work for rectangular input ? (720 , 1280)  I am getting an error : https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleUffSSD/sampleUffSSD.cpp#L179 

## Environment

**TensorRT Version*:7.1 developer preview
**GPU Type**: nvidia xavier jetson jetpack JetPack 4.4 Developer Preview

https://github.com/rajeevsrao/TensorRT/tree/release/6.0/plugin/gridAnchorPlugin

## Relevant Files

https://github.com/rajeevsrao/TensorRT/blob/release/6.0/plugin/gridAnchorPlugin/gridAnchorPlugin.cpp

**Comment by yshvrdhn** [comment]
@rajeevsrao

**Comment by edumotya** [comment]
I think that the reason is that the plugin GridAnchorRect_TRT is bugged, see #247.

**Comment by yshvrdhn** [comment]
@rmccorm4 Any updates on this issue will be helpful ? As giving rectangular inputs is a basic need.

**Comment by rajeevsrao** [comment]
I will post a fix within this week.

**Comment by PiyalGeorge** [comment]
Wow i too have been sitting on this issue for days, still not getting it.

**Comment by yshvrdhn** [comment]
any updates @rajeevsrao ?

**Comment by abx67** [comment]
Same here, waiting for rectangular update @rajeevsrao  Many thanks!

**Comment by rajeevsrao** [comment]
Sorry to keep you waiting - I was busy with the 7.1 OSS release. Updated ETA for this is by end-of-week (07/10).

**Comment by rajeevsrao** [comment]
@yshvrdhn @edumotya @PiyalGeorge @abx67 can you please verify if this resolves the issue: https://github.com/NVIDIA/TensorRT/pull/679

**Comment by ttyio** [comment]
Close since we already fixed the issue and there is no activities in the past 3 weeks, please create another issue if you still have problems, thanks!
