### ISSUE TITLE
Problems converting Onnx file to TensorRT model

### ISSUE THREAD

**Issue by anoushsepehri** [NVIDIA/TensorRT#613]
## Description

I am having problems trying to convert an Onnx file to a TensoRT engine on the Jetson Nano. I am following the nvidia walkthrough which can be found here:

https://devblogs.nvidia.com/speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt/

I have converted my tensorflow saved model to an ONNX file using tf2onnx however when I try to convert the Onnx file to an TensorRT engine I get the follow error:

[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "onnx2rt.py", line 22, in <module>
    eng.save_engine(engine, engine_name) 
  File "/home/anoushs/Tensorflow_code/engine.py", line 24, in save_engine
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'

Any help would be much appreciated. I was trying to look at other people who had this problem however they all used pytorch backends.

## Environment on Jetson Nano
**TensorRT Version**: 6.0.1 (from the standard jetpack install)
**Operating System + Version**: jetpack 4.3
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 2.1.0

The scripts I used are exactly the same as in the Nvidia blog post

**Comment by Darshcg** [comment]
I am also getting the exact same error with exactly the same environment on Jetson Nano.

**Comment by Tiemichael** [comment]
Same here with Tensorflow2.1 and TensorRT7.1

**Comment by anoushsepehri** [comment]
> Same problem (AttributeError: 'NoneType' object has no attribute 'serialize') with Tensorflow2.1.1 and TensorRT7.1 when following https://devblogs.nvidia.com/speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt.
> Is this supposed to run on a Jetson Nano?

How did you install tensoflow 2.1.1 using jetpack 4.4

**Comment by rmccorm4** [comment]
Hi @anoushsepehri 

> TensorRT Version: 6.0.1

This blog is targeted at TRT 7, so you'll likely run into issues with TRT 6.

As for Tensorflow, I suspect the blog was using TF 1.x, and not 2.x, so I would try using TF 1.x when converting the model to ONNX.

**Comment by anoushsepehri** [comment]
> Hi @anoushsepehri
> 
> > TensorRT Version: 6.0.1
> 
> This blog is targeted at TRT 7, so you'll likely run into issues with TRT 6.
> 
> As for Tensorflow, I suspect the blog was using TF 1.x, and not 2.x, so I would try using TF 1.x when converting the model to ONNX.

Hi @rmccorm4 

Thank you for your response. I have tried both TRT 6 in jetpack 4.3 and TRT 7 in jetpack 4.4. I have also tried tensorflow 1.15 and tensorflow 2.1.0 however they all produce the same error. I viewed my onnx model in netron and based on the properties it says there are multiple outputs.

On another note, when using TRT 7 I get warnings saying my weights are INT64 and they were clamped to INT32.

What do you suggest moving forward?

Thanks

**Comment by Tiemichael** [comment]
> > Same problem (AttributeError: 'NoneType' object has no attribute 'serialize') with Tensorflow2.1.1 and TensorRT7.1 when following https://devblogs.nvidia.com/speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt.
> > Is this supposed to run on a Jetson Nano?
> 
> How did you install tensoflow 2.1.1 using jetpack 4.4

I build TF2.1.1 from source - running fine

**Comment by CallmeZhangChenchen** [comment]
Why don't you try PB to UFF? It's officially recommended.

ERROR: Network must have at least one output,

I often encounter this error, but the solution is also very inexplicable. You should check whether your output layer name corresponds to your network

**Comment by Darshcg** [comment]
Hi @anoushsepehri,
Can you try with Containers on Nano? I think it should work.
I ran the Docker Image of the Jupyter Notebook in my Laptop with CUDA 10.2 and 440 driver, it worked fine.

**Comment by anoushsepehri** [comment]
> Hi @anoushsepehri,
> Can you try with Containers on Nano? I think it should work.
> I ran the Docker Image of the Jupyter Notebook in my Laptop with CUDA 10.2 and 440 driver, it worked fine.
> Also, the Docker engine and Nvidia docker already comes installed with jetpack 4.3 and 4.4.

Hi @Darshcg 
Can you please point me to the container that you ran? I am not as familiar with running Nvidia docker containers on the Jetson Nano.

Thanks

**Comment by anoushsepehri** [comment]
> Why don't you try PB to UFF? It's officially recommended.
> 
> ERROR: Network must have at least one output,
> 
> I often encounter this error, but the solution is also very inexplicable. You should check whether your output layer name corresponds to your network

@CallmeZhangChenchen 
I believe UFF is being deprecated and ONNX is now the preferred method.

**Comment by Darshcg** [comment]
Hi @anoushsepehri,
Sorry for the delayed response.
Here is the pull command: docker pull megh13/nv-stack:inception_workshop
https://hub.docker.com/r/megh13/nv-stack/tags

**Comment by Darshcg** [comment]
@CallmeZhangChenchen,
ONNX is Mostly preferred now.

**Comment by CallmeZhangChenchen** [comment]
Mm, you are right  @Darshcg

**Comment by anoushsepehri** [comment]
@Darshcg I tried using the docker container however same errors

Has anyone had success with converting a model from the TensorFlow object detection API to a tensorRT engine? I happen to be able to generate an engine for a UNET model I developed in Tensorflow 2.1.0 without the OD API, but only when I converted to ONNX with Opset 10, Opset 11 failed with the same errors (requiring at least one output). 

@rmccorm4 Hopefully whenever you have time or if there's anyone else that can help with this situation.

**Comment by Ram-Godavarthi** [comment]
I too have the same problem with tf2onnx -> tensorRT inference.

It says unsupported datatype UINT8(2).
I am using TensorRT 6.0.10
jetson nano.
I wont be using TensorRT 7 in near future because of my project requirements. I need to stick with version 6.0.10.

Any workaround for this??
tensorflow to onnx ocnversion was fine. But then the problem comes up when I run trtexec --onnx=ssd_inception_v2_2018.onnx

**Comment by nvpohanh** [comment]
```
[TensorRT] ERROR: Network must have at least one output
```

@anoushsepehri This error usually means that there was another error before this. Could you share the full log? Or try TRT 8.4 to see if the issue still exists.

@Ram-Godavarthi Support for UINT8 is already on the roadmap and should be ready by next or next-next TRT releases. Thanks

**Comment by ttyio** [comment]
UINT8 is already supported in 8.5, closing and thanks!
