### ISSUE TITLE
No importer registered for op: Tile

### ISSUE THREAD

**Issue by rgc183** [NVIDIA/TensorRT#615]
I want to implement `Tile` operator in TensorRT 6. Because of limitation of hardware I cannot use TensorRT 7. 
I see that it is supported in 7, and Slice layer is been used along with Wrap mode set for implementation of Tile operator. However, 6 does not support Wrap mode for Slice layer so we cannot use the same method in 6. 
I am looking for any alternate way of doing this.

**Comment by dcmrlee** [comment]
Same problem.  Any idea how to work around?

**Comment by yux94** [comment]
> I want to implement `Tile` operator in TensorRT 6. Because of limitation of hardware I cannot use TensorRT 7.
> I see that it is supported in 7, and Slice layer is been used along with Wrap mode set for implementation of Tile operator. However, 6 does not support Wrap mode for Slice layer so we cannot use the same method in 6.
> I am looking for any alternate way of doing this.

Could you please point out how to implement tile in tensorRT7?  I cannot find it in python api docs, many thanks !

**Comment by rmccorm4** [comment]
Hi @rgc183 

> Because of limitation of hardware I cannot use TensorRT 7.

Can you elaborate on this? What hardware is limited? 

TensorRT 7.1 was just released with support for Linux x86, Windows x86, and Jetson

**Comment by rgc183** [comment]
@rmccorm4 Pegasus drive AGX only supports till trt 6

**Comment by peterlee909** [comment]
Same question. Need help. Please.

**Comment by ttyio** [comment]
@rgc183  @peterlee909 thanks for reporting and sorry for the delay response.
Could we modify the model to use `slice` and `concatenation` since there is no `wrap` mode in trt6?

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by mhmmdjafarg** [comment]
Hi, any workaround for this? Im also facing this issue, and no idea how to implement it for custom plugin. 
Im using it for driveworks4.0

**Comment by mhmmdjafarg** [comment]
> @rgc183  @peterlee909 thanks for reporting and sorry for the delay response.
> Could we modify the model to use `slice` and `concatenation` since there is no `wrap` mode in trt6?

Hi @ttyio could you elaborate more on this? Thanks

**Comment by ttyio** [comment]
Hi @mhmmdjafarg , is the `repeats` field constant in your model? if so we can use `concatenation` to create the `tile` output. Else, maybe we need first `concatenation` to a max output, then using `slice` to shrink the output to the correct size.

Take the https://github.com/onnx/onnx/find/main#tile example, A = [[1, 2], [3, 4]], B = [1, 2], tile(A, B) = [[1, 2, 1, 2], [3, 4, 3, 4]]. If we know `B` is constant, then just `concat` A, else we first `concat` A and output a max output, then use `slice` with `shapeOf(A) * B` as slice output size, thanks!

**Comment by mhmmdjafarg** [comment]
Hi @ttyio , sorry for latrle reply i was working on another solution. 

Yes my repeat is constant 1D array with value (1, 20, 1) and my input is 3d with dimension (32000, 1,32) 
So the output will have dimensions (32000, 20,32) 

Could you please refer to the link docs or show me how? I'm new to this related concat and slice works

Thank you

**Comment by mhmmdjafarg** [comment]
Yes that will do, thank you!

However I ended up creating my own plugin based on TPAT Custom Plugin
