### ISSUE TITLE
Stuck on "Building The TensorRT OSS Components"

### ISSUE THREAD

**Issue by Engineering-Applied** [NVIDIA/TensorRT#619]
I am very new to the NVIDIA community and wanted to get my Jetson Nano up and running TensorRT
I am getting an error when I run these lines:

 ```
cd $TRT_SOURCE
 mkdir -p build && cd build
 cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out
 make -j$(nproc)
```

Particularly on the line <_cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out_>
The error is the following:

```
joshnano@joshnano:~/TensorRT/build$ cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=~/TensorRT/build/out
Building for TensorRT version: 7.0.0.1, library version: 7.0.0
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:46 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/joshnano/TensorRT/build/CMakeFiles/CMakeOutput.log".
See also "/home/joshnano/TensorRT/build/CMakeFiles/CMakeError.log".
```
Any help or a point in the right direction would be helpful, as I could have overlooked anything since I am still very new to this platform.

My system details are
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
```

**Comment by rmccorm4** [comment]
Hi @Engineering-Applied ,

This may not be a copy-paste solution as they seem to be for other jetson platforms (not nano), but hopefully these will be enough to put you in the right direction:
* https://github.com/NVIDIA/TensorRT/issues/9#issuecomment-575106079
* https://github.com/NVIDIA/TensorRT/issues/244
* https://forums.developer.nvidia.com/t/indexerror-list-index-out-of-range-object-detection-and-instance-segmentations-with-a-tensorflow-ma/108306/9

**Comment by ttyio** [comment]
close since no response for 3 weeks, please reopen if you have more questions, thanks!
