### ISSUE TITLE
uff_graph.binary(inputs[0], inputs[1], 'add', name) IndexError: list index out of range

### ISSUE THREAD

**Issue by yjiangling** [NVIDIA/TensorRT#626]
Hi all,
    I'm trying to convert a tensorflow pb model into uff model, it give the following error.

uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range

The pb model can be acquired in the below netdisk:

url: https://pan.baidu.com/s/19aa5LXK7KYSh6SwSTMYb1Q
code: mwyj

Is there anyone can give me some help? Thanks a lot in advanced!

**Comment by yjiangling** [comment]
BTW, the environment in my computer is:
Ubuntu 16.04
TensorFlow-GPU 1.12.0
Cuda 9.0
Cudnn 7.3
TenosrRT 5. 1

**Comment by rmccorm4** [comment]
Hi @yjiangling ,

I recommend upgrading to TensorRT 7.1, using [tf2onnx ](https://github.com/onnx/tensorflow-onnx) to convert your model to ONNX, and use the TensorRT ONNX parser instead.

**Comment by yjiangling** [comment]
> Hi @yjiangling ,
> 
> I recommend upgrading to TensorRT 7.1, using [tf2onnx ](https://github.com/onnx/tensorflow-onnx) to convert your model to ONNX, and use the TensorRT ONNX parser instead.

Ok, thank you, I'll try it later.

**Comment by MeghaGhosh** [comment]
HI @rmccorm4 I could successfully convert the h5 model to uff and compile the sample and run inference on google colaboratory. However when I'm doing the same on an Ubuntu server, I keep getting the uff_graph.binary(inputs[0], inputs[1], 'add', name) IndexError: list index out of range error no matter what i try. I have tried installing the dependencies directly and also tried a couple of different NGC tensorflow containers. Can you tell me which container is compatible with the latest commit on the maskrcnn uff sample? If i use the ONNX parser, how should I update the inference code for the same?

**Comment by Tyler-D** [comment]
@MeghaGhosh , Try this: 

1) nvcr.io/nvidia/tensorflow:18.12-py3
2) install uff, graphsugeon, keras==2.1.3
3) Modify uff's transpose convolution
4) Export:
NOTE: UFF has been tested with TensorFlow 1.14.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.5
=== Automatically deduced input nodes ===
[name: "input_image"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: 3
      }
      dim {
        size: 1024
      }
      dim {
        size: 1024
      }
    }
  }
}
]
=========================================

Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_mask_trt as custom op: PyramidROIAlign_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p5upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p4upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p3upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: SpecialSlice_TRT yet.
Converting mrcnn_detection_bboxes as custom op: SpecialSlice_TRT
Warning: No conversion function registered for layer: DetectionLayer_TRT yet.
Converting mrcnn_detection as custom op: DetectionLayer_TRT
Warning: No conversion function registered for layer: ProposalLayer_TRT yet.
Converting ROI as custom op: ProposalLayer_TRT
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_classifier as custom op: PyramidROIAlign_TRT
DEBUG [/usr/local/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py:96] Marking ['mrcnn_detection', 'mrcnn_mask/Sigmoid'] as outputs
No. nodes: 3049

**Comment by MeghaGhosh** [comment]
Thank you, I will try that. I currently got it working without a container on Ubuntu 18.04 with CUDA 10.0, CUDNN 7.6 and TensorRT 7.0.0.11. (tensorflow-gpu 1.13.1) I guess previously I had set the PATH and LD_LIBRARY_PATH incorrectly.

**Comment by rmccorm4** [comment]
Hi,

Since it's been a few months, I'm going to assume this has been resolved. Feel free to update if otherwise.

**Comment by pra-dan** [comment]
@MeghaGhosh Can you please share the colab notebook that you used ? I am unable to convert my h5 to uff either way. Thanks

**Comment by aurelm95** [comment]
@MeghaGhosh Could you share with us your google collab to convert the h5 model to uff and compile the sample and run inference?? Thanks!

**Comment by pra-dan** [comment]
@aurelm95 look at this. Might help https://prashantdandriyal.medium.com/mask-rcnn-h5-weights-to-frozen-graph-75860228590e

**Comment by aurelm95** [comment]
> @aurelm95 look at this. Might help https://prashantdandriyal.medium.com/mask-rcnn-h5-weights-to-frozen-graph-75860228590e

Thank you very much! This works!
