### ISSUE TITLE
[BUG] error while loading shared libraries: libnvcaffeparser.so.7.0.0

### ISSUE THREAD

**Issue by beizhengren** [NVIDIA/TensorRT#628]

**Comment by bifeng** [comment]
how to solve this error?

**Comment by YouSenRong** [comment]
have you solve this problem? I meet this problem while run the trtexec.

**Comment by liuxingwt** [comment]
Add the tensorRT lib path to environment varible, executing this command:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/workspace/TensorRT/downloads/TensorRT-7.1.3.4/lib`
set "/workspace/TensorRT/downloads/TensorRT-7.1.3.4/lib" as your own TensorRT Release path.
