### ISSUE TITLE
import convTranspose error when transfer onnx to tensorrt

### ISSUE THREAD

**Issue by yongguanjiangshan** [NVIDIA/TensorRT#629]
## Description

in c++, when call parseFromFile(), I get the next error. How can i solve this problem?

`While parsing node number 180 [ConvTranspose]:
ERROR: builtin_op_importers.cpp:570 In function importConvTranspose:
[6] Assertion failed: shaped_bias_weights.shape.d[0] == kernel_weights.shape.d[1]`

## Environment

**TensorRT Version**: 7.0
**GPU Type**: TITAN Xp
**CUDA Version**: 10.0.130
**CUDNN Version**: 7.6.0
**Operating System + Version**: ubuntu16.04
**Python Version (if applicable)**: 3.6
**PyTorch Version (if applicable)**: 1.4

**Comment by rmccorm4** [comment]
Hi @yongguanjiangshan ,

Can you share a simple ONNX model that reproduces this error?

**Comment by mk-nvidia** [comment]
Closing due to no response from issue reporter. Please reopen if this problem still exists.
