### ISSUE TITLE
will PluginTensorDesc support kBOOL format?

### ISSUE THREAD

**Issue by zjd1988** [NVIDIA/TensorRT#630]
I have a network like below
![企业微信截图_15925389628073](https://user-images.githubusercontent.com/7134030/85095429-f3aca980-b223-11ea-98cc-ba61d1a2615c.png)

I wrote a NonZero plugin, when i ran buildCudaEngine and got

"
../rtSafe/blobInfo.cpp:788: nvinfer1::PluginTensorDesc nvinfer1::rt::configFromEngineTensor(const nvinfer1::rt::EngineTensor&): Assertion `isFormatSet && "The format is not supported. "' failed.
"

so, i checked PluginTensorDesc and found
![企业微信截图_15925392774716](https://user-images.githubusercontent.com/7134030/85095652-9f55f980-b224-11ea-9131-3ec39b9d09db.png)

**Comment by ping28198** [comment]
I  have the same question

**Comment by zjd1988** [comment]
![企业微信截图_16009116198073](https://user-images.githubusercontent.com/7134030/94091117-039edf80-fe4a-11ea-9bc6-bec9844901e5.png)
@ping28198  latest document not support yet

**Comment by ttyio** [comment]
Hello @zjd1988 @ping28198 , thanks for reporting.
For `NoneZero`, besides kBOOL, this operator's output shape is data dependent, and current TensorRT dynamic shape has no data-dependent dimension support yet. I will create internal issue to tracking this.

**Comment by ttyio** [comment]
closing since duplicate to https://github.com/NVIDIA/TensorRT/issues/559, thanks
