### ISSUE TITLE
error: convert .h to uff 

### ISSUE THREAD

**Issue by phamquangnam** [NVIDIA/TensorRT#631]
Hi,

I try to convert mask rcnn model (.h5) to uff. But I get error like that:
![Screenshot from 2020-06-19 17-45-35](https://user-images.githubusercontent.com/40291833/85124811-ba406200-b254-11ea-8b8f-2b7d9df14407.png)

How can I fix that?

Thanks.

**Comment by rmccorm4** [comment]
Hi @phamquangnam ,

I recommend trying keras2onnx or tf2onnx to convert your model to ONNX, and then use the TensorRT ONNX parser.

**Comment by mk-nvidia** [comment]
Please note that we're deprecating the UFF parser. As @rmccorm4 mentioned, please utilize the ONNX parser.
