### ISSUE TITLE
Gtx 1650 TensorRT6 Create cuda engine erro

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [NVIDIA/TensorRT#633]
## Description

Gtx 1650 TensorRT6 Create cuda engine erro

## Environment

**TensorRT Version**:  6.0.1.5
**GPU Type**: 1650
**Nvidia Driver Version**: 435
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.4
**Operating System + Version**: ubuntu18.04
**Python Version (if applicable)**: no
**TensorFlow Version (if applicable)**: no
**PyTorch Version (if applicable)**: no
**Baremetal or Container (if container which image + tag)**: 
onnx 

## Relevant Files

VIDIOC_REQBUFS: Inappropriate ioctl for devic

## Steps To Reproduce

Code that can run through on other machines before, changed an environment, reported an error，

**engine = infer->deserializeCudaEngine(trtModelStream.data(), size, nullptr);**

**VIDIOC_REQBUFS: Inappropriate ioctl for devic**

  Please include:
  * Exact steps/commands to build your repro
  * Exact steps/commands to run your repro
  * Full traceback of errors encountered 
-->

**Comment by rmccorm4** [comment]
> VIDIOC_REQBUFS: Inappropriate ioctl for devic

Hi @CallmeZhangChenchen,

This just seems like something is misconfigured with your GPU environment (Driver, CUDA, etc.)

I would recommend double checking that your environment is correct, and possibly re-installing the NVIDIA driver, CUDA, and then TensorRT.

You could also try to use the GPU container images on NGC: https://www.nvidia.com/en-us/gpu-cloud/containers/

**Comment by CallmeZhangChenchen** [comment]
Hi @rmccorm4 
thank you very much,

Before that, I tested **NVIDIA-SMI nvcc - V and compiled devicequery**, which shows that pass works normally with **trtexec -- onnx = *. Onnx -- saveengine = * *. TRT**

I will try to reinstall an environment to see if it will be fixed

**Comment by CallmeZhangChenchen** [comment]
Hi @rmccorm4 
This problem has been solved, it is the problem of the driver, because I am a laptop, the system is ubuntu18.04, the driver installed using the default installation method, the version is 435, and the above problem appears,

I reinstalled the driver, the official recommendation GTX1650 is 430.9, after installation, the program runs successfully

But there is still a problem. If I want to upgrade my cuda version to 11, it is a bit difficult, because it requires a minimum of 450 driver
