### ISSUE TITLE
When will multiple GPU inferences be supported?

### ISSUE THREAD

**Issue by qingfengmingyue** [NVIDIA/TensorRT#634]
When will multiple GPU inferences be supported?

**Comment by rmccorm4** [comment]
Hi @qingfengmingyue ,

I believe multi-gpu is already supported. See the FAQs: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#troubleshooting

> Q: How do I use TensorRT on multiple GPUs?
A: Each ICudaEngine object is bound to a specific GPU when it is instantiated, either by the builder or on deserialization. To select the GPU, use cudaSetDevice() before calling the builder or deserializing the engine. Each IExecutionContext is bound to the same GPU as the engine from which it was created. When calling execute() or enqueue(), ensure that the thread is associated with the correct device by calling cudaSetDevice() if necessary.

**Comment by ttyio** [comment]
Close since we already answered and there is no activities in the past 3 weeks, please create another issue if you still have problems, thanks!
