### ISSUE TITLE
Load Caffe model bug, Unnamed Layer* 2 ！

### ISSUE THREAD

**Issue by EdwardVincentMa** [NVIDIA/TensorRT#637]
TensorRT 7.0.0.11
GPU: GTX 1070
cuda: 9.0
cudnn:7.6.5
Four caffe models are loaded in the LPR network, and only one model has this problem as bellow.The other 3 models were loaded without problems.
![image](https://user-images.githubusercontent.com/39480728/85355507-54e3be00-b53f-11ea-9471-22ca2591d8eb.png)

The constant  weights has count 32 not 12. The error message is incorrect.

This is a small network. In the parser->parse() function, a problem occurred in the layer circled in the figure. There will be no problem by removing this layer and subsequent layers.
![image](https://user-images.githubusercontent.com/39480728/85358570-a80d3f00-b546-11ea-8bc6-f102e5e9cc1c.png)
![image](https://user-images.githubusercontent.com/39480728/85360643-359f5d80-b54c-11ea-8d46-356d73154545.png)

The constant weights has count 32 not 12. The error message is incorrect.

**Comment by rmccorm4** [comment]
Hi @EdwardVincentMa ,

Are you able to try converting to ONNX models and trying the ONNX parser instead?

**Comment by ttyio** [comment]
Caffe is deprecated in release 7.0, close since there is no activities in the past 3 weeks, please create another issue if you still have problems, thanks!
