### ISSUE TITLE
Refitting An Engine: weights count error

### ISSUE THREAD

**Issue by ningningG** [NVIDIA/TensorRT#639]
I want to change weights and bias of all the convolution layer in the engine, but the weights count is reported wrong.

```
[F] [TRT] Assertion failed: newWeights.count == original.count
C:\source\builder\refit.cpp:596
Aborting...
```

If only one layer's weights and bias are changed, the error message becomes as follows:

```
[05/24/2020-16:46:40] [F] [TRT] Assertion failed: tDims.nbDims > 3
C:\source\rtSafe\tensorLayout.cpp:19
Aborting...
```

The 'refitter->getMissing' returns 0.

The code to change one layer's weights and bias(weights_shape=[64, 3, 3, 3], bias_shape=[64]) is:
```
Weights newWeights_tmp;
newWeights_tmp.count = 1728;
float* newWeightsLocal = new float[1728];
for (int i = 0; i < 1728; i++)
{
	newWeightsLocal[i] = 0.0001 * i;
}
newWeights_tmp.values = newWeightsLocal;
newWeights_tmp.type = DataType::kFLOAT;

Weights newBias_tmp;
newBias_tmp.count = 64;
float* newBiasLocal = new float[64];
for (int i = 0; i < 64; i++)
{
	newBiasLocal[i] = 0.0001 * i;
}

newBias_tmp.values = newBiasLocal;
newBias_tmp.type = DataType::kFLOAT;

IRefitter* refitter = createInferRefitter(*mEngine, gLogger);
refitter->setWeights("conv0_fwd", WeightsRole::kKERNEL, newWeights_tmp);
refitter->setWeights("conv0_fwd", WeightsRole::kBIAS, newBias_tmp);
```

What is the cause of the error?  How to define the new weights correctly? Anyone knows?

**Comment by ys0232** [comment]
have same problem. Can solve this problem when update Tensorrt-7.0 to Tensorrt-7.1?

**Comment by BowenFu** [comment]
> have same problem. Can solve this problem when update Tensorrt-7.0 to Tensorrt-7.1?

This should have been fixed in Tensorrt-7.1.

**Comment by mk-nvidia** [comment]
@ningningG @ys0232 Can you please check if you still hit this problem with TensorRT-7.2 or TensorRT-7.1? Thanks

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
