### ISSUE TITLE
Can't download TensorRT 7.x, "Failed to ssl_handshake: handshake failed"

### ISSUE THREAD

**Issue by ausk** [NVIDIA/TensorRT#640]
Hi, I want to use TensorRT 7.x on my PC . So I should download the install package from the site: https://developer.nvidia.com/nvidia-tensorrt-7x-download.

> TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6.zip
> TensorRT-7.0.0.11.Ubuntu-18.04.x86_64-gnu.cuda-10.2.cudnn7.6.tar.gz
> TensorRT-7.0.0.11.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn7.6.tar.gz

But I don't know why all packages are 1 kb.
![image](https://user-images.githubusercontent.com/4545060/85646124-fac53300-b6cd-11ea-9283-2ab377171094.png)

Then I just open the zip in editor, I see the content is:

>Failed to ssl_handshake: handshake failed

![image](https://user-images.githubusercontent.com/4545060/85646288-60192400-b6ce-11ea-8671-4293665b1054.png)

Please, can anyone tell me how to download the full packages correctly?

**Comment by ZhiweiREN97** [comment]
Same issue

**Comment by TFDeeplearner** [comment]
Same issue

**Comment by AarynBaelish** [comment]
same issue

**Comment by Zenvi** [comment]
Same. Possibly there's sth wrong behind the website.

**Comment by gp1998-star** [comment]
cuda好像都出错了

**Comment by Smellly** [comment]
same issue

**Comment by rmccorm4** [comment]
Hi, I raised this issue and it's being looked investigated.

**Comment by xkszltl** [comment]
@rmccorm4 @ausk 
What's the outcome of investigation?
We hit this kind of issue frequently.
