### ISSUE TITLE
tensorRT do batch inference successfully when batch_size <=5, but failed when batch_size >5 

### ISSUE THREAD

**Issue by pustar** [NVIDIA/TensorRT#642]
## Environment

**TensorRT Version**:  5.0
**GPU Type**:  gtx 1070
**Nvidia Driver Version**:   NVIDIA-SMI 432.00       Driver Version: 432.00       CUDA Version: 10.1
**CUDA Version**:   10.0
**CUDNN Version**: 7.3
**Operating System + Version**:  Win 10
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## bug report

I use tensorRT do batch inference successfully when batch_size <=5, but it failed when batch_size >5.
Program runs normally, but its output are all zeros when batch_size > 5, my single frame output_size is 768*768, while my single frame input_size is 256x256. But if the batch_size is less or equal to 5, the batch inference result is correct.
I don't know why my batch inference's batch_size cannot be more than 5. 
Any suggestion will be appreciated!
My input and output are as following:
```
		float *input = (float *)malloc(10*1*256*256 * sizeof(float));
		static float output[10 * 768 * 768];
```

**Comment by musicbeer** [comment]
hi，this issue may help you，good luck！
https://github.com/NVIDIA/TensorRT/issues/19

**Comment by mk-nvidia** [comment]
@pustar Were you able to resolve your bug? Please also try out newer TensorRT versions, 7.2 should be available this week.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
