### ISSUE TITLE
Build instructions don't work for ARM systems

### ISSUE THREAD

**Issue by jwatte** [NVIDIA/TensorRT#643]
## Description

I am trying to build self-hosted (not cross-compiling) on the NVIDIA Jetson series.

## Environment

**TensorRT Version**:  master as of 2b8863ddff04fabfe13fa5c201ab04a7e82bd470
**GPU Type**:  NVIDIA Jetson
**Nvidia Driver Version**:  NVIDIA Jetpack 4.4
**CUDA Version**: 10.2 
**CUDNN Version**:  8.0
**Operating System + Version**: Jetpack 4.4 (Ubuntu 18.04)
**Python Version (if applicable)**: 3
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: both

Baremetal:

1) make sure all prerequisites are installed on the system
2) git clone NVIDIA/TensorRT
3) cd TensorRT
4) mkdir build && cd build
5) cmake ../

Get an error that the directly "onnx" doesn't contain a CMakeLists.txt file

Container:

  docker build -f docker/ubuntu.Dockerfile --build-arg UBUNTU_VERSION=18.04 --build-arg CUDA_VERSION=10.2 --tag=tensorrt-ubuntu .

Trying to run this container fails, as it seems to be pulling the x86_64 Ubuntu version, not the AArch64 version.
(The error is that the executable format is wrong. which seems to match with that problem.)

If there are special instructions or flags to use based on the specific architecture, those should probably be available here in the instructions.

**Comment by rmccorm4** [comment]
Hi @jwatte,

> Get an error that the directly "onnx" doesn't contain a CMakeLists.txt file

It looks like you didn't clone the submodules (such as `parsers/onnx`):
```
cd TensorRT
git submodule update --init --recursive
```

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
