### ISSUE TITLE
compiled under windows system

### ISSUE THREAD

**Issue by manhongnie** [NVIDIA/TensorRT#645]
Can these codes be compiled under windows system? I compiled it and kept saying that zlib couldn't be found, wouldn't I add it?

**Comment by ttyio** [comment]
Hello @manhongnie , sorry currently there is no official support for windows build in the opensource repo.

**Comment by ShiinaMitsuki** [comment]
> Can these codes be compiled under windows system? I compiled it and kept saying that zlib couldn't be found, wouldn't I add it?

I added zlib but still cant compile under windows, using TensorRT 7.1.3.4 , visual studio 2017.
