### ISSUE TITLE
Using SUM in IElementWiseLayer wil get wrong results

### ISSUE THREAD

**Issue by float123** [NVIDIA/TensorRT#648]
## Description
Hello, I encountered a problem when I using tensorrt.
My network structure is similar to ResNet. I sum the two network layers:
`SUM = network.add_elementwise(layer1.get_output(0), layer2.get_output(0), trt.ElementWiseOperation.SUM)`
But the results are not in accordance with the expectation.
I print out the results：
print layer1:
![图片](https://user-images.githubusercontent.com/39334643/86102956-c0ed9580-baee-11ea-86ff-be13eb84024e.png)
print layer2:
![图片](https://user-images.githubusercontent.com/39334643/86103142-f85c4200-baee-11ea-91a8-e3641983e6c9.png)
The results of tensorrt calculation:
![图片](https://user-images.githubusercontent.com/39334643/86104084-2a21d880-baf0-11ea-8f0c-159f5332fb0b.png)
I've found that this problem is only encountered in summation. If I use the following method, I can get the correct result:
```
out1 = network.add_elementwise(layer1.get_output(0), layer2.get_output(0), trt.ElementWiseOperation.SUB)
out2 = network.add_elementwise(out1.get_output(0), layer2.get_output(0), trt.ElementWiseOperation.SUM)
out3 = network.add_elementwise(out2.get_output(0), layer2.get_output(0), trt.ElementWiseOperation.SUM)
```
![图片](https://user-images.githubusercontent.com/39334643/86104527-baf8b400-baf0-11ea-8887-e587bbc7de88.png)

What is the reason? Is it caused by the inconsistency of the number of digits?

## Environment

**TensorRT Version: TensorRT7.0**: 
**GPU Type: NVIDIA P4**: 
**Nvidia Driver Version: 410**: 
**CUDA Version 10.0**: 
**CUDNN Version 7.6.5**: 
**Operating System + Version: ubuntu18.4**: 
**Python Version (if applicable): 3.6.8**:

**Comment by rmccorm4** [comment]
Hi @float123 ,

Can you try running this with TensorRT 7.1 and see if the issue still occurs?

**Comment by tswc** [comment]
Do we have some further updates？ I run into the same situation.
