### ISSUE TITLE
 The tools 'trtexec' in TensorRT7.0.0.11，and I feel that the problem is very big！

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [NVIDIA/TensorRT#649]
## Description

I found that the tool **trtexec** in tensorrt6.1 is not same  as tensorrt7.0. 

## Environment

**TensorRT Version**: 7.0.0.11 and 6.0.1.5
**GPU Type**: 2080susper
**Nvidia Driver Version**: 440.36
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.4
**Operating System + Version**: ubuntu16.04
**Python Version (if applicable)**: no
**TensorFlow Version (if applicable)**: no
**PyTorch Version (if applicable)**: no
**Baremetal or Container (if container which image + tag)**: n0

## Relevant Files

model:
[face.onnx.tar.gz](https://github.com/NVIDIA/TensorRT/files/4852140/face.onnx.tar.gz)

（Because the onnx suffix is not supported, I compressed it）

file1:

[tensorrt6-1.txt](https://github.com/NVIDIA/TensorRT/files/4852123/tensorrt6-1.txt)

file2:
[tensorrt6-2.txt](https://github.com/NVIDIA/TensorRT/files/4852130/tensorrt6-2.txt)

file3:
[tensorrt7-1.txt](https://github.com/NVIDIA/TensorRT/files/4852136/tensorrt7-1.txt)

file4:
[tensorrt7-2.txt](https://github.com/NVIDIA/TensorRT/files/4852134/tensorrt7-2.txt)

## Steps To Reproduce

This model （face.onnx）is a face detection model.
I use this tools(trtexec in tensorrt6) to convert the onnx  model and the prequel can get the correct result.
Commond :home/zcc/App/TensorRT-6.0.1.5/bin/trtexec --onnx=face.onnx --fp16 --saveEngine=face6.trt
The result information converted with this command is at file1
But the same command in tensorrt7,  no box  ,The result information converted with this command is at file4
Here is a  long long woring : [W] [TRT] Explicit batch network detected and batch size specified, use enqueue without batch size instead.
So I used  this Commannnd: home/zcc/App/TensorRT-7.0.0.11/bin/trtexec --onnx=face.onnx --fp16 --explicitBatch --batch=1 --saveEngine=face7.trt
That warning disappeared.  The result information converted with this command is at file3 . 
in tensorrt7 ,  this  --iterations=N              Run at least N inference iterations (default = 10) ,iterations=10 ,But Iterated many times, shouldn’t it be 10 by default?
Although there is no warning, but the result is still no frame.
context->executeV2(buffers.getDeviceBindings().data()); Here I also removed the old version Batch

Same Commond in tensorrt6: home/zcc/App/TensorRT-6.0.1.5/bin/trtexec --onnx=face.onnx --fp16 --explicitBatch --batch=1 --saveEngine=face6.trt
is erro.he result information converted with this command is at file2.

Now I use the same codein tensorrt7 , the result is still wrong.
I want to know, in tensorrt7.0 what should I do?

**Comment by rmccorm4** [comment]
Hi @CallmeZhangChenchen ,

Can you also try using TensorRT 7.1 with the `--explicitBatch` flag, and see if it gives you correct results?

**Comment by CallmeZhangChenchen** [comment]
Hi @rmccorm4 ,
Thank you for your reply.

My PC is a 2080 super graphics card, and the environment is cuda10.0. The cuda version required by tensorrt7.1 is too high, so I can't change it in a short time. If you think it’s a version problem, I can upgrade and test it
But I have tried it on Xavier NX, TensorRT version is 7.1 . it is the same error, there is still no result

**Comment by rmccorm4** [comment]
Hi @CallmeZhangChenchen ,

It's hard to say. Sounds like a potential regression. 

Can you share the ONNX model?

**Comment by CallmeZhangChenchen** [comment]
Hi @rmccorm4 

I have uploaded the model above.
model:

https://github.com/NVIDIA/TensorRT/files/4852140/face.onnx.tar.gz
（Because the onnx suffix is not supported, I compressed it）

If you need it, I can also upload the source code here.

**Comment by rmccorm4** [comment]
Hi @CallmeZhangChenchen ,

Assuming the results you're getting in TRT 6.0 with `trtexec --onnx=face.onnx` are correct, then it looks like a regression.

I get consistent results from:
* TRT6.0 + OSS (19.12 branch) full-dims support explicit batch
* TRT 7.0 explicit batch
* TRT 7.1 explicit batch

But all 3 of these are different from the TRT 6.0 implicit batch results. I'll file a bug on this.

**Comment by CallmeZhangChenchen** [comment]
Hi @rmccorm4 
Ok thank you very much！

**Comment by rmccorm4** [comment]
Hi @CallmeZhangChenchen ,

It looks like TensorRT 7.1 results are the same as ONNX Runtime for this model. So it might actually be that TensorRT 6 was not totally correct.

Can you share more details on your inference code? Perhaps there's an issue there.

**Comment by CallmeZhangChenchen** [comment]
Hi @rmccorm4 
When I converted the model, the onnx version was 1.4.1, which was converted by mxnet1.6.0

[code.tar.gz](https://github.com/NVIDIA/TensorRT/files/4888783/code.tar.gz)

The above compressed package is my streamlined Cmake project, environment, temsorrt6.0, opencv3.4.6, eigen3, cuda10.0, cudnn7.6
I have tested this project and can get the correct results.
You can change the configuration path in CMakeList.txt, sorry to write a little mess!

But switching to tensortrt 7.0 or 7.1 has no results.

**Comment by rmccorm4** [comment]
Hi @CallmeZhangChenchen ,

The C++ package you shared is pretty involved, and requires OpenCV installation, etc. so it would be difficult for me to go line by line looking for the issue and testing it.

Instead, I ran your model/engine through some [python inference code](https://github.com/rmccorm4/tensorrt-utils/blob/493aa3827ff2c9886436ee4cbe60fed79d5bd263/inference/infer.py) I have to get a better sense of the model/engine. It uses random inputs by default, but you could[ tweak the code](https://github.com/rmccorm4/tensorrt-utils/blob/493aa3827ff2c9886436ee4cbe60fed79d5bd263/inference/infer.py#L92-L120) to read in your sample image and pre/post-process accordingly instead if you'd like:
```
root@f84bcb24b148:/workspace/tensorrt-utils/inference# python3 infer.py -e /mnt/face20.06.engine 
Loaded engine: /mnt/face20.06.engine
Active Optimization Profile: 0
Engine/Binding Metadata
        Number of optimization profiles: 1
        Number of bindings per profile: 11
        First binding for profile 0: 0
        Last binding for profile 0: 10
Generating Random Inputs
        Using random seed: None
        Input [data] shape: (1, 3, 360, 640)
Input Metadata
        Number of Inputs: 1
        Input Bindings for Profile 0: [0]
        Input names: ['data']
        Input shapes: [(1, 3, 360, 640)]
Output Metadata
        Number of Outputs: 10
        Output names: ['slice_axis20', 'conv8_3_bbox', 'slice_axis21', 'conv11_3_bbox', 'slice_axis22', 'conv14_3_bbox', 'slice_axis23', 'conv17_3_bbox', 'slice_axis24', 'conv20_3_bbox']
        Output shapes: [(1, 1, 89, 159), (1, 4, 89, 159), (1, 1, 44, 79), (1, 4, 44, 79), (1, 1, 21, 39), (1, 4, 21, 39), (1, 1, 10, 19), (1, 4, 10, 19), (1, 1, 4, 9), (1, 4, 4, 9)]
        Output Bindings for Profile 0: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

---

I skimmed through your code, and since this model has fixed-shape (batch size of 1 in ONNX model), I believe the only real change you should need to make to your code is to change `context.execute(1, buffers)` to `context.executeV2(buffers)`. You likely already tested this since I saw it commented out in the code.

---

> But switching to tensortrt 7.0 or 7.1 has no results.

You say this has "no results" rather than "incorrect results". This leads me to believe that there's some mistake in the inference code.

I would recommend you try to simplify the example, and try comparing line-by-line the output shapes/results of your inference and pre/post-processing between TRT 6 and TRT 7, and see at what point the results start to differ. If you can narrow it down like this, I might be able to help a bit better.

**Comment by rmccorm4** [comment]
Closing due to no response.

**Comment by marsmiao** [comment]
> Hi @CallmeZhangChenchen ,
> 
> The C++ package you shared is pretty involved, and requires OpenCV installation, etc. so it would be difficult for me to go line by line looking for the issue and testing it.
> 
> Instead, I ran your model/engine through some [python inference code](https://github.com/rmccorm4/tensorrt-utils/blob/493aa3827ff2c9886436ee4cbe60fed79d5bd263/inference/infer.py) I have to get a better sense of the model/engine. It uses random inputs by default, but you could[ tweak the code](https://github.com/rmccorm4/tensorrt-utils/blob/493aa3827ff2c9886436ee4cbe60fed79d5bd263/inference/infer.py#L92-L120) to read in your sample image and pre/post-process accordingly instead if you'd like:
> 
> ```
> root@f84bcb24b148:/workspace/tensorrt-utils/inference# python3 infer.py -e /mnt/face20.06.engine 
> Loaded engine: /mnt/face20.06.engine
> Active Optimization Profile: 0
> Engine/Binding Metadata
>         Number of optimization profiles: 1
>         Number of bindings per profile: 11
>         First binding for profile 0: 0
>         Last binding for profile 0: 10
> Generating Random Inputs
>         Using random seed: None
>         Input [data] shape: (1, 3, 360, 640)
> Input Metadata
>         Number of Inputs: 1
>         Input Bindings for Profile 0: [0]
>         Input names: ['data']
>         Input shapes: [(1, 3, 360, 640)]
> Output Metadata
>         Number of Outputs: 10
>         Output names: ['slice_axis20', 'conv8_3_bbox', 'slice_axis21', 'conv11_3_bbox', 'slice_axis22', 'conv14_3_bbox', 'slice_axis23', 'conv17_3_bbox', 'slice_axis24', 'conv20_3_bbox']
>         Output shapes: [(1, 1, 89, 159), (1, 4, 89, 159), (1, 1, 44, 79), (1, 4, 44, 79), (1, 1, 21, 39), (1, 4, 21, 39), (1, 1, 10, 19), (1, 4, 10, 19), (1, 1, 4, 9), (1, 4, 4, 9)]
>         Output Bindings for Profile 0: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
> ```
> 
> I skimmed through your code, and since this model has fixed-shape (batch size of 1 in ONNX model), I believe the only real change you should need to make to your code is to change `context.execute(1, buffers)` to `context.executeV2(buffers)`. You likely already tested this since I saw it commented out in the code.
> 
> > But switching to tensortrt 7.0 or 7.1 has no results.
> 
> You say this has "no results" rather than "incorrect results". This leads me to believe that there's some mistake in the inference code.
> 
> I would recommend you try to simplify the example, and try comparing line-by-line the output shapes/results of your inference and pre/post-processing between TRT 6 and TRT 7, and see at what point the results start to differ. If you can narrow it down like this, I might be able to help a bit better.
> 
> You could also try to run your model through the ONNX Runtime and see if you can get results that way. As I mentioned that the TRT 7.1 results match the ONNX Runtime results, but the TRT 6 results do not. Using `onnxruntime==1.3.0`

Have u ever tried to use same context for different batch-sized input which is accepted by the profile? As far as I have observed, it will cause huge problem.

**Comment by CallmeZhangChenchen** [comment]
@marsmiao   yes  ！trt7 onnx  when  batch size  is not one ,  problem will have problems。 Take a look at the official introduction. The usage has changed

**Comment by CallmeZhangChenchen** [comment]
@rmccorm4    Sorry ,

I work overtime every day in my country。
I use TRT7.1 and 6.1 , and when I compare them, I find the root cause of the problem

There are 8 outputs in the network. At the end of the Score output, there is a slice layer, which can get the frame score. I found that the scores of four regression boxes are the same, and the four regression scores are different
So I think there is something wrong with the slice layer, and I plan to implement it manually。
