### ISSUE TITLE
How to convert caffemodel to Weights class?

### ISSUE THREAD

**Issue by ground-truth** [NVIDIA/TensorRT#65]
I want to convert caffemodel file to Weights class. In the tensorrt/samples/sampleMNISTAPI, the model file is in wts format. So how can I use deploy.prototxt and caffemodel file and API to build a network?

**Comment by DilipSequeira** [comment]
I believe the wts files were created by dumping the weights from caffe using its API. This was somewhat labor intensive, so I would recommend using the caffe parser.
