### ISSUE TITLE
TensorRT 5.1 Make Error: parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/build.make:82: recipe for target 'parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o' failed

### ISSUE THREAD

**Issue by Hassan313** [NVIDIA/TensorRT#650]
Hi I am trying to installing the TensorRT 5.1, however in the make process, I encounter the below problem:

[ 38%] Built target caffe_proto
[ 50%] Built target nvcaffeparser
[ 61%] Built target nvcaffeparser_static
[ 61%] Building CUDA object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o
nvcc fatal   : redefinition of argument 'std'
parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/build.make:82: recipe for target 'parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o' failed
make[2]: *** [parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o] Error 1
CMakeFiles/Makefile2:1172: recipe for target 'parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2

Can anybody kindly help me?

Thank you.

**Comment by rmccorm4** [comment]
Hi @Hassan313 ,

Please see this related issue: https://github.com/NVIDIA/TensorRT/issues/570

Hopefully this will solve your issue.

**Comment by Hassan313** [comment]
@rmccorm4 Hi Ryan, Thank you very much for pointing to the solution. Yes, it did solve my problem.
