### ISSUE TITLE
ssd inception v2 2018 tensorflow model in tensorrt

### ISSUE THREAD

**Issue by Ram-Godavarthi** [NVIDIA/TensorRT#651]
Hi,
I am trying to run inference on jetson nano using ssd inception v2 2018 model.
But It is not getting loaded. 
But i could able to load ssd inception 2017 model and run inference using sampleUfSSD.cpp code.

But I would like to train my dataset suing ssd inception v2 model and run inference.

Can I use ssd inception v2 2018 model to run inference using sampeUffSSD?
Currently it supports inception v2 2017 model.

What versions of tensorflow and tensorflow api should be checkedout to train ssd_inception v2 model and run inference using sampleUffSSD??

**Comment by rmccorm4** [comment]
Duplicate post tracked here: https://forums.developer.nvidia.com/t/inference-on-video-file-using-tensorrt-in-sampleuffssd-model-c/126655/4

**Comment by Ram-Godavarthi** [comment]
Hello,

I have not yet the got answer for this.

Please update the answer this.
Thank you
