### ISSUE TITLE
OSS docker image for Xavier crashes when run

### ISSUE THREAD

**Issue by CF2220160244** [NVIDIA/TensorRT#655]
How can I make a tensorrt docker for Xavier，when I run the across-complie docker image in Xavier it has the error：

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: src: /usr/lib/aarch64-linux-gnu/libcudnn.so.7, src_lnk: libcudnn.so.7.6.3, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libcudnn.so.7, dst_lnk: libcudnn.so.7.6.3\\\\nsrc: /usr/lib/libvisionworks_sfm.so, src_lnk: libvisionworks_sfm.so.0.90, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/libvisionworks_sfm.so, dst_lnk: libvisionworks_sfm.so.0.90\\\\nsrc: /usr/lib/libvisionworks_sfm.so.0.90, src_lnk: libvisionworks_sfm.so.0.90.4, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/libvisionworks_sfm.so.0.90, dst_lnk: libvisionworks_sfm.so.0.90.4\\\\nsrc: /usr/lib/libvisionworks_tracking.so, src_lnk: libvisionworks_tracking.so.0.88, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/libvisionworks_tracking.so, dst_lnk: libvisionworks_tracking.so.0.88\\\\nsrc: /usr/lib/libvisionworks_tracking.so.0.88, src_lnk: libvisionworks_tracking.so.0.88.2, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/libvisionworks_tracking.so.0.88, dst_lnk: libvisionworks_tracking.so.0.88.2\\\\nsrc: /etc/vulkan/icd.d/nvidia_icd.json, src_lnk: /usr/lib/aarch64-linux-gnu/tegra/nvidia_icd.json, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/etc/vulkan/icd.d/nvidia_icd.json, dst_lnk: /usr/lib/aarch64-linux-gnu/tegra/nvidia_icd.json\\\\nsrc: /usr/lib/aarch64-linux-gnu/libcuda.so, src_lnk: tegra/libcuda.so, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libcuda.so, dst_lnk: tegra/libcuda.so\\\\nsrc: /usr/lib/aarch64-linux-gnu/libdrm_nvdc.so, src_lnk: tegra/libdrm.so.2, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libdrm_nvdc.so, dst_lnk: tegra/libdrm.so.2\\\\nsrc: /usr/lib/aarch64-linux-gnu/libv4l2.so.0.0.999999, src_lnk: tegra/libnvv4l2.so, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libv4l2.so.0.0.999999, dst_lnk: tegra/libnvv4l2.so\\\\nsrc: /usr/lib/aarch64-linux-gnu/libv4lconvert.so.0.0.999999, src_lnk: tegra/libnvv4lconvert.so, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libv4lconvert.so.0.0.999999, dst_lnk: tegra/libnvv4lconvert.so\\\\nsrc: /usr/lib/aarch64-linux-gnu/libv4l/plugins/nv/libv4l2_nvvidconv.so, src_lnk: ../../../tegra/libv4l2_nvvidconv.so, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libv4l/plugins/nv/libv4l2_nvvidconv.so, dst_lnk: ../../../tegra/libv4l2_nvvidconv.so\\\\nsrc: /usr/lib/aarch64-linux-gnu/libv4l/plugins/nv/libv4l2_nvvideocodec.so, src_lnk: ../../../tegra/libv4l2_nvvideocodec.so, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libv4l/plugins/nv/libv4l2_nvvideocodec.so, dst_lnk: ../../../tegra/libv4l2_nvvideocodec.so\\\\nsrc: /usr/lib/aarch64-linux-gnu/tegra/libcuda.so, src_lnk: libcuda.so.1.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/tegra/libcuda.so, dst_lnk: libcuda.so.1.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/tegra/libnvbufsurface.so, src_lnk: libnvbufsurface.so.1.0.0, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/tegra/libnvbufsurface.so, dst_lnk: libnvbufsurface.so.1.0.0\\\\nsrc: /usr/lib/aarch64-linux-gnu/tegra/libnvbufsurftransform.so, src_lnk: libnvbufsurftransform.so.1.0.0, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/tegra/libnvbufsurftransform.so, dst_lnk: libnvbufsurftransform.so.1.0.0\\\\nsrc: /usr/lib/aarch64-linux-gnu/tegra/libnvbuf_utils.so, src_lnk: libnvbuf_utils.so.1.0.0, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/tegra/libnvbuf_utils.so, dst_lnk: libnvbuf_utils.so.1.0.0\\\\nsrc: /usr/lib/aarch64-linux-gnu/tegra/libnvid_mapper.so, src_lnk: libnvid_mapper.so.1.0.0, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/tegra/libnvid_mapper.so, dst_lnk: libnvid_mapper.so.1.0.0\\\\nsrc: /usr/share/glvnd/egl_vendor.d/10_nvidia.json, src_lnk: ../../../lib/aarch64-linux-gnu/tegra-egl/nvidia.json, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/share/glvnd/egl_vendor.d/10_nvidia.json, dst_lnk: ../../../lib/aarch64-linux-gnu/tegra-egl/nvidia.json\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvcaffe_parser.so.6, src_lnk: libnvparsers.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvcaffe_parser.so.6, dst_lnk: libnvparsers.so.6.0.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvcaffe_parser.so.6.0.1, src_lnk: libnvparsers.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvcaffe_parser.so.6.0.1, dst_lnk: libnvparsers.so.6.0.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvinfer.so.6, src_lnk: libnvinfer.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvinfer.so.6, dst_lnk: libnvinfer.so.6.0.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so.6, src_lnk: libnvinfer_plugin.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so.6, dst_lnk: libnvinfer_plugin.so.6.0.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvonnxparser.so.6, src_lnk: libnvonnxparser.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvonnxparser.so.6, dst_lnk: libnvonnxparser.so.6.0.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvonnxparser_runtime.so.6, src_lnk: libnvonnxparser_runtime.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvonnxparser_runtime.so.6, dst_lnk: libnvonnxparser_runtime.so.6.0.1\\\\nsrc: /usr/lib/aarch64-linux-gnu/libnvparsers.so.6, src_lnk: libnvparsers.so.6.0.1, dst: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/lib/aarch64-linux-gnu/libnvparsers.so.6, dst_lnk: libnvparsers.so.6.0.1\\\\n, stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=18722 /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged]\\\\nnvidia-container-cli: mount error: stat failed: /home/nvidia/docker/docker/overlay2/56fc30ef15ccaccec9bd3ed824bb7bfbbe495e7ad914529cb3aea0f3a9cea11f/merged/usr/local/cuda-10.0/compat/libcuda.so.410.129: no such file or directory\\\\n\\\"\"": unknown.
`

**Comment by ttyio** [comment]
Hello @CF2220160244 , thanks for reporting.
We can following https://github.com/NVIDIA/TensorRT#setting-up-the-build-environment ?
run the command line on your desktop to build a docker image support cross compile:

     ./docker/build.sh --file docker/ubuntu-cross-aarch64.Dockerfile --tag tensorrt-cross-jetpack --os 18.04 --cuda 10.2

this binary can then copy to your Xavier device.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
