### ISSUE TITLE
The color image to input should be in BGR order

### ISSUE THREAD

**Issue by RaajithaG** [NVIDIA/TensorRT#657]
This is more out of curiosity than an issue. I have noticed a comment "The color image to input should be in BGR order" in sampleUffSSD.cpp. I have a SSD mobilenet v1 model trained on RGB inputs. Would there be an issue if the input buffer consists of images in RGB order instead of BGR?

**Comment by mk-nvidia** [comment]
Yes, the network wouldn't produce the right results in the case above.
You could shuffle the channels of the weights of the first layer to match your input channel order.
