### ISSUE TITLE
Couldn't even parse the official pytorch implementation of resnet18 with TRT7.1.3.4 trtexec

### ISSUE THREAD

**Issue by jianyin2016** [NVIDIA/TensorRT#658]
## To reproduce:
- scripts to generate onnx
```
import pretrainedmodels.models.torchvision_models as pmt
import torch
import onnx
from torch.nn.functional import interpolate as interpolate

# class upsample(torch.nn.Module):
#     def __init__(self, num_classes=9):
#         super(upsample, self).__init__()
#
#     def forward(self, x):
#         output = interpolate(x, scale_factor=8, mode="bilinear", align_corners=True)
#         return output

model = pmt.resnet18()
model = model.cuda()

inputs = torch.ones(32, 3, 224, 224).cuda()
torch.onnx.export(model, inputs, './defaultRes18.onnx',
                  export_params=True,
                  verbose=True,
                  training=False,
                  input_names=None,
                  output_names=None,
                  operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
                  opset_version=11,
                  do_constant_folding=True,
                  example_outputs=None,
                  strip_doc_string=True,
                  dynamic_axes=None,
                  keep_initializers_as_inputs=True
                  )
onnx_model = onnx.load('./defaultRes18.onnx')
onnx.checker.check_model(onnx_model)
```
- trtexec args
`--explicitBatch --onnx=.\defaultRes18.onnx --minShapes=input:1x3x224x224 --optShapes=input:16x3x224x224 --maxShapes=input:32x3x224x224 --saveEngine=.\defaultRes18.engine --verbose`

- dump info
`[07/03/2020-11:01:41] [V] [TRT] ModelImporter.cpp:180:  [Gemm] outputs: [198 -> (-1, 1000)],
[07/03/2020-11:01:41] [V] [TRT] ModelImporter.cpp:494: Marking 198_1 as output: 198
[07/03/2020-11:01:41] [W] [TRT] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.`

## environment:
os:win7
python:3.7
pytorch:1.4
tensort:7.1.3.4
cuda:10.2

**Comment by jalola** [comment]
Hi,

When exporting from Pytorch to onnx, please use batch_size = 1, and then add dynamic_axes so the onnx will know the model converted with dynamic batch. Something like this:


```
model = pmt.resnet18()
model = model.cuda()

dummy_input = torch.ones(1, 3, 224, 224).cuda()

onnx_bytes = io.BytesIO()
extra_args = {'opset_version': 11, 'verbose': True, 'do_constant_folding': True}
torch.onnx.export(model, dummy_input, onnx_bytes, input_names=['model_input'],
                    output_names=['model_output'],
                    dynamic_axes={'model_input': {0: 'batch_size'},
                                  'model_output': {0: 'output_size'}}, **extra_args)

onnx_file = "model.onnx"
with open(onnx_file, 'wb') as out:
     out.write(onnx_bytes.getvalue())

```

When you check the onnx model, you will see its input shape is dynamic because it is tagged by a variable not fixed number
print('The model is:\n{}'.format(onnx_model.graph.input))

Then you can convert to tensorrt as you did

check more here: https://pytorch.org/docs/stable/onnx.html#frequently-asked-questions

**Comment by jianyin2016** [comment]
@jalola 
Hi, thanks for your suggestion,actually i had a step-by-step try as you suggested just now, unfortunately, tetexec still got a crashdump after printing `Calling isShapeTensor before the entire network is constructed may result in an inaccurate result` . maybe you are right about the dynamic shape of onnx, but I guess the crashdump is caused by other reasons, as my test example works well with `tensorRt7.0.0.11`.

**Comment by jalola** [comment]
I see, sorry, I have not used TRT 7.1 yet

**Comment by ttyio** [comment]
Hello @jianyin2016 , thanks for reporting.

Could you try export using dynamic batch:

> import pretrainedmodels.models.torchvision_models as pmt
> import torch
> import onnx
> from torch.nn.functional import interpolate as interpolate
> model = pmt.resnet18()
> model = model.cuda()
> inputs = torch.ones(1, 3, 224, 224).cuda()
> torch.onnx.export(model, inputs, './defaultRes18.onnx',
>                   export_params=True,
>                   verbose=True,
>                   training=False,
>                   input_names=None,
>                   output_names=None,
>                   operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
>                   opset_version=11,
>                   do_constant_folding=True,
>                   example_outputs=None,
>                   strip_doc_string=True,
>                   dynamic_axes={'input.1': {0: 'batch_size'}},
>                   keep_initializers_as_inputs=True
>                   )
> onnx_model = onnx.load('./defaultRes18.onnx')
> onnx.checker.check_model(onnx_model)

Then run with latest TensorRT 7.2? thanks!

**Comment by jianyin2016** [comment]
Hi， @ttyio ，
It seems allright now after a quite simple test with the newly released TRT7.2 :)

**Comment by ttyio** [comment]
Thanks @jianyin2016 , closing
