### ISSUE TITLE
question about TensorRT mixed precision

### ISSUE THREAD

**Issue by wanghr323** [NVIDIA/TensorRT#668]
Hi, I've recently been using tensorRT for mixed precision inference, and according to the documentation instructions I can set the entire network to int8 precision:.
```
    if (p->datatype == DataType::kINT8)
    {
        config->setFlag(BuilderFlag::kINT8);
    }
```
Then I can set the precision of some of these layers to fp32.
Using：

`network->getLayer(i)->setPrecision(PerTensorPrecision.at(tname));`

Now I have a question, how do I see exactly which layers are set to what precision by TensorRT? How can I check if the setup is successful?(We know that there are some layers that cannot use int8 precision)

**Comment by ttyio** [comment]
Hi @wanghr323 , we can enable verbose log, and find the layer precision start with line "Engine Layer Information".
