### ISSUE TITLE
Segmentation fault in int8 calibration using existing calibration cache file

### ISSUE THREAD

**Issue by liming312** [NVIDIA/TensorRT#669]
## Description

When I convert a model to int8 quantized model using existing calibration cache file (just generated in last run), there is "Segmentation fault" error as shown in the image below. But I do the conversion with calibration data (do not use off-the-shell calibration cache file), there is no such error.

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: Tesla T4
**Nvidia Driver Version**: 418.67
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: Debian 9.11
**Python Version (if applicable)**: 3.7.4
**TensorFlow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: 1.4.0
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

Here is the conversion output. The are many warnings above the first line in the image.
![image](https://user-images.githubusercontent.com/67087947/86595710-f3afe780-bf4d-11ea-8670-4d84e28b590f.png)

**Comment by tianwen0110** [comment]
hi, have you solved this problem?
