### ISSUE TITLE
IndexError: _Map_base::at

### ISSUE THREAD

**Issue by liming312** [NVIDIA/TensorRT#671]
## Description

When I convert a model from ONNX to TensorRT, there is an error "IndexError: _Map_base::at" as shown in the image below. In this model, I intentionally removed a FC layer for debugging purpose. If I add the original FC layer to make it a normal classification network, everything works well.

![image](https://user-images.githubusercontent.com/67087947/86717440-091d2400-bfd7-11ea-8460-f318f836bdbb.png)

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: Tesla T4
**Nvidia Driver Version**: 418.67
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: Debian 9.11
**Python Version (if applicable)**: 3.7.4
**TensorFlow Version (if applicable)**: N/A
**PyTorch Version (if applicable)**: 1.4.0
**Baremetal or Container (if container which image + tag)**:

**Comment by TangJiamin** [comment]
Hello, I want to konw why the problem happened and how did you solve this problem. If you can reply, I will be so appreciate!
