### ISSUE TITLE
how to make memset op async and use the same cuda stream for performing that operation

### ISSUE THREAD

**Issue by makaveli10** [NVIDIA/TensorRT#674]
Yolov5 tensorRT model works fine when not hooked up in deepstream so to fix that I need to make this memset op async and use the same cuda stream for cudaMemset [line no 4] op:

    void YoloLayerPlugin::forwardGpu(const float *const * inputs, float* output, cudaStream_t stream, int batchSize) {
           int outputElem = 1 + MAX_OUTPUT_BBOX_COUNT * sizeof(Detection) / sizeof(float);
          for(int idx = 0 ; idx < batchSize; ++idx) {
            CUDA_CHECK(cudaMemset(output + idx*outputElem, 0, sizeof(float)));
        }
        int numElem = 0;
        for (unsigned int i = 0; i < mYoloKernel.size(); ++i)
        {
            const auto& yolo = mYoloKernel[i];
            numElem = yolo.width*yolo.height*batchSize;
            if (numElem < mThreadCount)
                mThreadCount = numElem;
            CalDetection<<< (yolo.width*yolo.height*batchSize + mThreadCount - 1) / mThreadCount, mThreadCount>>>
                (inputs[i], output, numElem, yolo.width, yolo.height, (float *)mAnchor[i], mClassCount, outputElem);

**Comment by rmccorm4** [comment]
Hi @makaveli10 ,

Is this a question? Or an observation?

**Comment by mk-nvidia** [comment]
Closing due to no response from the user.
