### ISSUE TITLE
TensorRT backend Optimizations

### ISSUE THREAD

**Issue by abidmalikwaterloo** [NVIDIA/TensorRT#676]
I am looking into TensorRT optimizations. Any idea where to start? and how to contribute?
I apologize if this is not the right forum to ask this question.

**Comment by rmccorm4** [comment]
Hi @abidmalikwaterloo ,

Can you clarify what you're looking for? If you're asking how to start out and learn more about TensorRT, I recommend installing the latest TensorRT 7.1 package (or using a docker image from [NGC](https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt), and running through the samples for a better understanding of the capabilities and usage of TensorRT.

**Comment by mk-nvidia** [comment]
Closing due to no response from user.
