### ISSUE TITLE
TensorRT docker image script error

### ISSUE THREAD

**Issue by Scharfsinnig** [NVIDIA/TensorRT#682]
## Description

![image](https://user-images.githubusercontent.com/9099493/87278278-9f40d500-c516-11ea-817c-4c040a14c51b.png)
![image](https://user-images.githubusercontent.com/9099493/87278288-a36cf280-c516-11ea-8dac-c55e2bda23d4.png)

## Environment

**TensorRT Version**:  nvcr.io/nvidia/tensorrt:20.06-py3
**GPU Type**: Tesla-T4
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by Scharfsinnig** [comment]
Where is the 20.05?

**Comment by rmccorm4** [comment]
Hi @Scharfsinnig ,

That's likely a typo, I'll check it out. For now, please manually change the tag to 20.06 which was just added.

**Comment by Scharfsinnig** [comment]
> Hi @Scharfsinnig ,
> 
> That's likely a typo, I'll check it out. For now, please manually change the tag to 20.06 which was just added.

Thanks! I will try it later. I also found that the tensorrt-20.x series have some different file missing in docker images. Such as cafe model missing, pgm data missing and so on. I tried to put the TensorRT-5's data dir into tensorrt-20.x's container, rerun the same command, and it worked.
So, please check the missing files.

**Comment by mk-nvidia** [comment]
This has been fixed since 20.06. Closing.
