### ISSUE TITLE
Can I set the input tensor of an INetworkDefinition with batch dim?

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/TensorRT#69]
Can I add an Input with NCHW tensor format to an INetworkDefinition?
like
```
INetworkDefinition* net = builder->createNetwork();
auto tensor = net->addInput("input", DimsNCHW{32, 32, 32, 32});
...
```
When I build the ICudaEngine, I have already set the max batch size in the dims of the tensors. So what is the batch size I should set in the IBuilder?
```
builder->setMaxBatchSize(1);
```
or
```
builder->setMaxBatchSize(32);
```

**Comment by DilipSequeira** [comment]
In the current release, TensorRT treats batch size separately: it assumes you will provide the input tensor sizes without a batch dimension, and then configure the batch size separately. 

At build time you do this using the maxBatchSize attribute (telling TensorRT the max batch size you will use, which is also the batch size it optimizes for.) In your case this would be 32.

At runtime, you would then provide the batch size corresponding to your input tensor as a parameter to enqueue().

Future versions of TensorRT will be provide additional flexibility in defining the network.

**Comment by dongfangduoshou123** [comment]
@DilipSequeira 
Hi  
The plugin's core function：enqueue(int batchSize,
                            const void* const* inputs,
                            void** outputs,
                            void* workspace,
                            cudaStream_t stream)
what about the memory layout of param: const void* const* inputs and void** outputs？
for example:one plugin has 3 input, 2 output，batchsize= 4
Is an array with three-dimensional float pointers.  each float pointer in the array pointing to each input corresponding to the batch?

or

Const void * const * inputs is a 4-D array of float pointers.each float pointer in the array pointing to three inputs's first addr corresponding to the batch index?

Thank you!

**Comment by rmccorm4** [comment]
Hi @xiaocenxiaocen,

The above is correct for TensorRT 5.x, this refers to "implicit batch networks".

With TensorRT 6.x, "explicit batch networks" are now supported, so you can explicitly provide a batch dimension (-1 for dynamic batch size), and build your engine with the explicit batch flag. See this section from the docs for more details: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes
