### ISSUE TITLE
I have a problem about setMaxBatchSize in TensorRT7.0

### ISSUE THREAD

**Issue by oyrq** [NVIDIA/TensorRT#696]
I have the same problem [issue](https://github.com/NVIDIA/TensorRT/issues/437)
 Thanks!

## Environment
**TensorRT Version**: 7.0
**GPU Type**: 2080
**Nvidia Driver Version**: 418.45
**CUDA Version**: 10.1

**Comment by kevinch-nv** [comment]
Closing this issue since it looks like you've resolved your problem in #437.
