### ISSUE TITLE
credentials for downloads - please don't

### ISSUE THREAD

**Issue by bvandenbon** [NVIDIA/TensorRT#697]
Why do we need to enter credentials on your webpage to download tensorrt ? What is the vision behind this ? What do you try to accomplish with this ? - I don't understand. Don't you want to make TensorRt more popular ?

As you know, it's already a really complicated installation procedure to get TensorRT + CUDNN + CUDA 10.2 + ... working but this kind of stuff just pushes it to the limit.

In practice it means that whenever we get the choice to download software as OpenCL or Cuda , we always pick the OpenCL version, just because automating the installation of Cuda software takes about 4 days of work. 

As for these specific files, it means that we will have to put up our own mirror servers for these files. So again, what are you trying to accomplish ? It makes it very hard to do any kind of automation, but at the same time, does it accomplish anything positive ?

**Comment by rajeevsrao** [comment]
@bvandenbon I understand your frustration, and will forward your feedback to our marketing team. The reason we do this is to capture some analytics about TensorRT users and their usecases so we can better serve those markets.

**Comment by xkszltl** [comment]
We had the same kind of questions for years, and it's the biggest blocker for our TensorRT adoption, especially on Windows.

The analytics you captured is inaccurate, because the "probe" is too huge for your sample, and you'll be observing the side effect of the probe.

**Comment by mk-nvidia** [comment]
@bvandenbon @xkszltl We do provide a way of downloading TensorRT without entering credentials (not for Windows, unfortunately):
[4.2.1. Using The NVIDIA Machine Learning Network Repo For Debian Installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#maclearn-net-repo-install-rpm)

> This installation method is for advanced users who are already familiar with TensorRT and want to get their application running quickly or to setup automation, such as when using containers. New users or users who want the complete installation, including samples and documentation, should follow the local repo installation instructions 

Does this help?

**Comment by xkszltl** [comment]
That's exactly what I did for Linux, but when we building something cross-platform it's more of all-or-none situation.

**Comment by bvandenbon** [comment]
@mk-nvidia yes, this is very valuable ! 👍 
Thank you for this information !
