### ISSUE TITLE
why dynamic range for layer output tensors is set twice in sampleINT8API.cpp

### ISSUE THREAD

**Issue by chenbohua3** [NVIDIA/TensorRT#698]
In the same function, [here](https://github.com/NVIDIA/TensorRT/blob/650d4b655d1b30b39e476f9317445d680f023fbb/samples/opensource/sampleINT8API/sampleINT8API.cpp#L340) and [here](https://github.com/NVIDIA/TensorRT/blob/650d4b655d1b30b39e476f9317445d680f023fbb/samples/opensource/sampleINT8API/sampleINT8API.cpp#L396)

Is there any special purpose？

**Comment by mk-nvidia** [comment]
Thanks for pointing this out, we're taking a look.

**Comment by rajeevsrao** [comment]
Fixed in the TensorRT OSS 7.2.1 release:
https://github.com/NVIDIA/TensorRT/blob/release/7.2/samples/opensource/sampleINT8API/sampleINT8API.cpp#L340
