### ISSUE TITLE
Pull the image error

### ISSUE THREAD

**Issue by yw155** [NVIDIA/TensorRT#7]
Hi @rajeevsrao, when I pull the TensorRT image container, I meet the error as follows:

19.05-py3: Pulling from nvidia/tensorrt
7e6591854262: Pull complete 
089d60cb4e0a: Pull complete 
9c461696bc09: Pull complete 
45085432511a: Pull complete 
6ca460804a89: Extracting [==============>                                    ]  2.261MB/7.715MB
2631f04ebf64: Download complete 
86f56e03e071: Download complete 
234646620160: Downloading [===>                                               ]  42.09MB/615.2MB
7f717cd17058: Download complete 
e69a2ba99832: Download complete 
bc9bca17b13c: Download complete 
1870788e477f: Download complete 
603e0d586945: Downloading [===>                                               ]  32.92MB/492.7MB
717dfedf079c: Downloading 
1035ef613bc7: Waiting 
c5bd7559c3ad: Waiting 
d82c679b8708: Waiting 
059d4f560014: Waiting 
f3f14cff44df: Waiting 
96502bde320c: Waiting 
bc5bb9379810: Waiting 
e4d8bb046bc2: Waiting 
4e2187010a7c: Waiting 
9d62684b94c3: Waiting 
e70e61e48991: Waiting 
adecb91612fe: Waiting 
ba27dafb70e8: Waiting 
16bde716c9b2: Waiting 
476faeed0740: Waiting 
5af7c8a6b101: Waiting 
960591fee98d: Waiting 
0dd138c184ff: Waiting 
7ef953567062: Waiting 
bd9a54f5a193: Waiting 
144852c40661: Waiting 
171a26eec2d4: Waiting 
999acb71c4df: Waiting 
3f301e4ba386: Waiting 
3fc30e0f9cba: Waiting 
38d1459042f4: Waiting 
aafa1a9d16eb: Waiting 
unauthorized: authentication required

I also meet the same error when I use docker file to build environment.
Do you know how to solve it? Thanks.

**Comment by xieydd** [comment]
Because of gfw, if you have a vpn , it will be no problem. @yw155

**Comment by yw155** [comment]
@xieydd, thanks for your reply. It may not be the problem as you mentioned since I can pull the image on another machine.

**Comment by rajeevsrao** [comment]
Sounds like it was a VPN issue. Closing.

**Comment by yw155** [comment]
Hi @rajeevsrao, thanks for your reply. If it was a VPN issue, how the first several items can be downloaded?
