### ISSUE TITLE
Error when cmake - Missing CUDA_nvinfer_LIBRARY

### ISSUE THREAD

**Issue by minhtcai** [NVIDIA/TensorRT#700]
Hi, I've trying to cmake but I got this error: 

################

-- Found CUDNN: /usr/local/cuda-10.0/lib64/libcudnn.so
-- Found CUDNN include: /usr/local/cuda-10.0/include
-- Found OpenCV: /usr (found version "3.2.0") 
-- Found OpenCV: /home/minh/opencv/build (found version "4.4.0") 
install dir:/usr/local
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_nvinfer_LIBRARY
    linked by target "tkDNN" in directory /home/minh/tkDNN

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

#################
My system:
Ubuntu 18.04
GTX970M
CUDA 10.0
CUDNN 7.6.5
OpenCV 4.4
TensorRT 7.0.0-1+cuda10.0 (install using Debian https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing)

When I run "dpkg -l | grep TensorRT", it shows libnvinfer7 libraries.
Please help, than you very much!

**Comment by VRTCPL** [comment]
Same issue

**Comment by Sudhakar17** [comment]
@minhtcai @VRTCPL : Did you guys find the solution? I am facing the same problem.

**Comment by nguyenquyem99dt** [comment]
I also have the same issue.
