### ISSUE TITLE
struct TRT_DEPRECATED RegionParameters

### ISSUE THREAD

**Issue by gilgilad** [NVIDIA/TensorRT#701]
Tensorrt 7.1  marks struct  RegionParameters as deprecated. 
However 
TENSORRTAPI nvinfer1::IPluginV2* createRegionPlugin(nvinfer1::plugin::RegionParameters params);

is using it . is there another implementation of the struct?

**Comment by mk-nvidia** [comment]
@gilgilad Thanks for pointing this out. This will be fixed in the next release. Closing.
