### ISSUE TITLE
With TensorRT 7.1.3 the UFF parser is still incapable of loading 3D convolution layers

### ISSUE THREAD

**Issue by ralovich** [NVIDIA/TensorRT#705]
## Description

With TensorRT 7.1.3 the UFF parser is still incapable of loading 3D convolution layers.

## Environment

**TensorRT Version**: 7.1.3
**GPU Type**: GTX 1080
**Nvidia Driver Version**: 440.100
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.0.180
**Operating System + Version**: Ubuntu 20.04
**Python Version (if applicable)**: NA
**TensorFlow Version (if applicable)**: NA
**PyTorch Version (if applicable)**: NA
**Baremetal or Container (if container which image + tag)**: NA

## Relevant Files

With TensorRT 7.1.3 the UFF parser is still incapable of loading 3D convolution layers:
UffParser: Validator error: mixed_35x35x256a/branch5x5/Conv/Conv3D: Unsupported operation _Conv3D

## Steps To Reproduce

- convert the .pb model from https://github.com/ralovich/trt-regression to UFF
- try loading above UFF into TRT 7.1.3 for inference

**Comment by mk-nvidia** [comment]
@ralovich We announced deprecation of the UFF and Caffe parsers in TensorRT7, and won't be adding any new features to them. We recommend switching to the ONNX parser.
https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html

**Comment by ralovich** [comment]
Thanks, the ONNX import appears to work for us since TensorRT 7.1.3.4.
