### ISSUE TITLE
Cannot run /demo/BERT

### ISSUE THREAD

**Issue by mirkocoric** [NVIDIA/TensorRT#709]
## Description

Tried to run /demo/BERT
Successfully went through steps 1-3 from https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT quick start guide

Step 4 
mkdir -p /workspace/TensorRT/demo/BERT/engines && python3 builder.py -m /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_v2_large_fp16_128_v2/model.ckpt-8144 -o /workspace/TensorRT/demo/BERT/engines/bert_large_128.engine -b 1 -s 128 --fp16 -c /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_v2_large_fp16_128_v2

throws an error:
ImportError: libcublas.so.10.2: cannot open shared object file: No such file or directory

I tried the same approach with container with CUDA 10.2 (went through steps 1-3 with only change ./docker/build.sh --file docker/ubuntu.Dockerfile --tag tensorrt-ubuntu --os 18.04 --cuda 10.2)

Now error is gone, but I got Segmentation fault (core dumped)

## Environment

**TensorRT Version**: 7.1.3.4
**GPU**: GeForce RTX 2080 Ti
**Nvidia Driver Version**: 450.57
**CUDA Version**: 11.0 (tried also 10.2)
**CUDNN Version**: 8.0

**Comment by xvolica** [comment]
meet the same problem

**Comment by ttyio** [comment]
Hello @xvolica @mirkocoric , thanks for reporting.

Which TRT version did you download when you setup `$TRT_RELEASE`, we should match the cuda version in the docker (both 10.2 or both 11.0).

Also, could you try latest 7.2:
7.2 binary: https://developer.nvidia.com/tensorrt
7.2 opensource: https://github.com/NVIDIA/TensorRT/tree/release/7.2/demo/BERT

**Comment by xvolica** [comment]
I'm using TensorRT-7.1.3.4.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0.tar to directly install without docker, and try to convert a transformer model from onnx to trt.
I can't find the error infos now and succeed by another way.

**Comment by ttyio** [comment]
Closing, please reopen if you still have question, thanks!
