### ISSUE TITLE
Could not find faster_rcnn_test_iplugin.prototxt

### ISSUE THREAD

**Issue by ashkanaev** [NVIDIA/TensorRT#71]
Hello! 

Can't find faster_rcnn_test_iplugin.prototxt nowhere.
I've check whole repository and  faster_rcnn_models.tgz archive. 
Where is this file located? 

Thanks,
Awaiting for your prompt response!

**Comment by andi4191** [comment]
@ashkanaev :
1. Download the TensorRT tar from https://developer.nvidia.com/tensorrt
2. Extract the tar file.
3. Please check the data/faster-rcnn path for faster_rcnn_test_iplugin.prototxt
