### ISSUE TITLE
找不到zlib库

### ISSUE THREAD

**Issue by MrLee12138** [NVIDIA/TensorRT#714]
你好，我在windows10环境下通过cmake编译TensorRT5.1，提示找不到zlib库，但是我已经在thirdparty文件夹下添加了zlib库并且已经编译，请问这个问题如何解决呢？谢谢

**Comment by Jacoobr** [comment]
请问解决这个问题了吗 @MrLee12138

**Comment by mk-nvidia** [comment]
@MrLee12138 TensorRT5.1 is pretty old now, please retry with the latest TensorRT version to see if this error still exists. Please also paste logs of all relevant error messages.

**Comment by mk-nvidia** [comment]
Closed due to no response.
