### ISSUE TITLE
[TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (1255) - Cuda Error in NCHWToNHWC4: 400 (invalid resource handle)

### ISSUE THREAD

**Issue by Water2style** [NVIDIA/TensorRT#720]
## Description
I converted a pytorch .pt model to ONNX, and then ONNX to TensorRT. 
But the tensortRT output is all 0.

[TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (1255) - Cuda Error in NCHWToNHWC4: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
******trt_outputs******  [array([          0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0,           0], dtype=float32)]

## Environment

**TensorRT Version**:   7.1
**GPU Type**:    Xavier NX
**Nvidia Driver Version**:    Jetpack 4.4
**CUDA Version**:  Jetpack 4.4
**CUDNN Version**:   Jetpack 4.4
**Operating System + Version**:   Jetpack 4.4
**Python Version (if applicable)**:   3.6
**TensorFlow Version (if applicable)**:  
**PyTorch Version (if applicable)**:  1.5
**Baremetal or Container (if container which image + tag)**:

**Comment by G-Bong** [comment]
I met same issue

**Comment by Pudge-tao** [comment]
I also confuse about this error in dynam input

**Comment by gutianchang** [comment]
i meet same issue. does anyone know how to use do_inference in sub-thread?

**Comment by mk-nvidia** [comment]
@Water2style @G-Bong @Pudge-tao @gutianchang Please attach an example network that shows this problem, so that we can work on determining the bug.

**Comment by mk-nvidia** [comment]
Closing due to no response.
