### ISSUE TITLE
Bug report for batchedNMSPlugin

### ISSUE THREAD

**Issue by roborocklsm** [NVIDIA/TensorRT#722]
## Description

According to README of **batchedNMSPlugin**, the boxes input are of shape `[batch_size, number_boxes, number_classes, number_box_parameters]`. The box location usually consists of four parameters such as `[x_min, y_min, x_max, y_max]`. 

But when I try to do with `number_box_parameters>4` (some other prediction head binding with prior bboxes), it fails.

## Environment

**TensorRT Version**:  7.1
**GPU Type**: Jetson Xaiver AGX
**Nvidia Driver Version**:  - 
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6
**TensorFlow Version (if applicable)**: 2.0
**PyTorch Version (if applicable)**: -
**Baremetal or Container (if container which image + tag)**: - 

**Use ManagerSDK to host the Jetson machine with Jetpack4.4**

## Relevant Files

```bash
#assertionbatchedNMSPlugin.cpp,155
```

## Steps To Reproduce

Sorry I could not apply my original code, but if you change the input **number_box_parameters** of your program this issue would be reproduced.

**Comment by roborocklsm** [comment]
Or the output of batchedNMSPlugin could be a list of selected indices, this problem (feature?) would be solved.

**Comment by ttyio** [comment]
Hello @roborocklsm , thanks for reporting
Could you use `nmsPlugin` since you have the `prior boxes`, the `batchedNMSPlugin` only support `box locations`, so the `number_box_parameters` always equal to 4.
https://github.com/NVIDIA/TensorRT/tree/master/plugin/nmsPlugin

**Comment by roborocklsm** [comment]
Yes, I know. @ttyio 
I am just saying the op would more flexible if **number_box_parameters** could be replaced by a list of selected indices. Anyway, I re-wrote it by myself.

**Comment by ttyio** [comment]
Thanks for the suggestion @roborocklsm 

The intuition of this interface come from https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression?hl=en
we cannot change it now for backward compatible issue, and it is cool you can customize the plugin to fit in your workflow.

May I close this since there is no more blocking issue here? thanks!

**Comment by roborocklsm** [comment]
Sure, go ahead plz.

**Comment by ttyio** [comment]
thank you @roborocklsm
