### ISSUE TITLE
build container, the dockerfile does not contain cuDNN-8.0

### ISSUE THREAD

**Issue by MrRace** [NVIDIA/TensorRT#724]
I try to build the IMAGE use the centos.Dockerfile in `TensorRT/tree/master/docker`. But in the [Prerequisites Part](https://github.com/NVIDIA/TensorRT#prerequisites) the cuda and cudnn are all needed. It seems that the ` centos.Dockerfile `  lose the `cuDNN-8.0`.

**Comment by mk-nvidia** [comment]
@MrRace what build command did you use to build the container?
