### ISSUE TITLE
[Q] Why is different the host latency? (between min, max, median latency  and end to end latency) 

### ISSUE THREAD

**Issue by kycocotree** [NVIDIA/TensorRT#728]
Ubuntu 18.04
TensorRT 7.1.3
CUDA 10.2
CuDNN 8.0
GPU: Tesla T4
Model: yolo v3 (I'am customized a input size for my work.)

![Screenshot from 2020-07-30 13-41-30](https://user-images.githubusercontent.com/30614126/88881474-7b95c280-d26a-11ea-8826-fc9a60e58727.png)

![Screenshot from 2020-07-30 13-41-51](https://user-images.githubusercontent.com/30614126/88881481-7fc1e000-d26a-11ea-8421-123817131b56.png)

See the inference test result.
Max host latency is 48.7096 ms but end to end host latency is 309.081 ms.

Why is different between them? 
What is mean a end to end host latency?

**Comment by mk-nvidia** [comment]
CC @rmccorm4 @kevinch-nv @rajeevsrao

**Comment by ttyio** [comment]
Hello @kycocotree , 
the `end to end host latency` include memcpy h2d/d2h, and the `host latency` exclude memcpy h2d/d2h.

closing, please reopen if you still have question, thanks!
