### ISSUE TITLE
Is it possible to build TensorRT7 with Cuda10.1?

### ISSUE THREAD

**Issue by X-funbean** [NVIDIA/TensorRT#733]

**Comment by rmccorm4** [comment]
Hi @X-funbean ,

The only combinations supported are those outlined in the Support Matrix for a given release: https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/support-matrix/index.html

Currentlly, you can't build the TRT_RELEASE from source with custom versions, you have to download the pre-built packages from the website.
