### ISSUE TITLE
[TensorRT] ERROR: ../builder/Layers.cpp (3986) - Assertion Error in validate: 0 (nbResizeDim >= 0)

### ISSUE THREAD

**Issue by Pudge-tao** [NVIDIA/TensorRT#735]
## Environment

**TensorRT Version**: 7.1。3.4
**GPU Type**: Tesla T4
**Nvidia Driver Version**: 440.64.00
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.1.13
**Operating System + Version**: centos7
**Python Version (if applicable)**: 3.7
**TensorFlow Version (if applicable)**: tensorflow2.2
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by linukc** [comment]
@Pudge-tao how did you solve this problem?
