### ISSUE TITLE
IndexError: Attribute not found: pads

### ISSUE THREAD

**Issue by silaopi** [NVIDIA/TensorRT#737]
When I try to convert onnx to tensorrt engine, this error occurs. Does anyone know how to fix it?

        with open(args.onnx_file_path, 'rb') as model:
            print('Beginning ONNX file parsing')
            if not parser.parse(model.read()): --> Report error here: IndexError: Attribute not found: pads
                print("ERROR: Failed to parse the ONNX file.")
                for error in range(parser.num_errors):
                    print (parser.get_error(error))

Environments:
pytorch 1.5
cuda 10.2
tensorrt 7.0.0.11
nvidia driver 440.1
onnx 1.7

Full error information is here:
Traceback (most recent call last):
  File "/home/mk/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mk/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/4T-1/tian/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/4T-1/tian/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/4T-1/tian/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/home/mk/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/mk/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/mk/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/4T-1/tian/project/dolores_dev/convert.py", line 36, in <module>
    utils.ONNX2TRT(args, calib=calib)
  File "/4T-1/tian/project/dolores_dev/utils/trtcalibrator/trtconvertor.py", line 35, in ONNX2TRT
    if not parser.parse(model.read()):
IndexError: Attribute not found: pads

**Comment by mk-nvidia** [comment]
@silaopi Please share either the model or a test case that reproduces the error.

**Comment by silaopi** [comment]
@mk-nvidia 
Model is shown below:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import utils
import ignite

class FastSCNN(nn.Module):
    def __init__(self, in_channels, num_classes, official_train_model=None, fine_tune=False, aux=False, **kwargs):
        super(FastSCNN, self).__init__()
        self.aux = aux
        self.fine_tune = fine_tune
        self.learning_to_downsample = LearningToDownsample(
            in_channels, 32, 48, 64)
        self.global_feature_extractor = GlobalFeatureExtractor(
            64, [64, 96, 128], 128, 6, [3, 3, 3])
        self.feature_fusion = FeatureFusionModule(64, 128, 128)
        self.classifier = Classifer(128, num_classes)
        if self.aux:
            self.auxlayer = nn.Sequential(
                nn.Conv2d(64, 32, 3, padding=1, bias=False),
                nn.BatchNorm2d(32),
                nn.ReLU(True),
                nn.Dropout(0.1),
                nn.Conv2d(32, num_classes, 1)
            )

        if fine_tune:
            for i in self.learning_to_downsample.parameters():
                i.requires_grad = False
            for i in self.global_feature_extractor.parameters():
                i.requires_grad = False
            for i in self.feature_fusion.parameters():
                i.requires_grad = False


    def forward(self, x):
        size = x.size()[2:]
        higher_res_features = self.learning_to_downsample(x)
        x = self.global_feature_extractor(higher_res_features)
        x = self.feature_fusion(higher_res_features, x)
        x = self.classifier(x)
        #outputs = []
        # x = F.interpolate(x, size, mode='bilinear', align_corners=True) # Tensor不支持双线性插值上采样
        x = F.interpolate(x, size, mode='nearest', align_corners=None)
        # x = F.log_softmax(x, dim=1)
        # 
        # x = F.log_softmax(x)
        # outputs.append(x)
        # if self.aux:
        #     auxout = self.auxlayer(higher_res_features)
        #     auxout = F.interpolate(auxout, size, mode='bilinear', align_corners=True)
        #     outputs.append(auxout)
        # return tuple(outputs)
        return x


class _ConvBNReLU(nn.Module):
    """Conv-BN-ReLU"""

    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=0, **kwargs):
        super(_ConvBNReLU, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size,
                      stride, padding, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(True)
        )

    def forward(self, x):
        return self.conv(x)


class _DSConv(nn.Module):
    """Depthwise Separable Convolutions"""

    def __init__(self, dw_channels, out_channels, stride=1, **kwargs):
        super(_DSConv, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(dw_channels, dw_channels, 3, stride,
                      1, groups=dw_channels, bias=False),
            nn.BatchNorm2d(dw_channels),
            nn.ReLU(True),
            nn.Conv2d(dw_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(True)
        )

    def forward(self, x):
        return self.conv(x)


class _DWConv(nn.Module):
    def __init__(self, dw_channels, out_channels, stride=1, **kwargs):
        super(_DWConv, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(dw_channels, out_channels, 3, stride,
                      1, groups=dw_channels, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(True)
        )

    def forward(self, x):
        return self.conv(x)


class Attention_block(nn.Module):
    def __init__(self, F_g, F_l, F_int):
        super(Attention_block, self).__init__()
        self.W_g = nn.Sequential(
            nn.Conv2d(F_g, F_int, kernel_size=1,
                      stride=1, padding=0, bias=True),
            nn.BatchNorm2d(F_int)
        )

        self.W_x = nn.Sequential(
            nn.Conv2d(F_l, F_int, kernel_size=1,
                      stride=1, padding=0, bias=True),
            nn.BatchNorm2d(F_int)
        )

        self.psi = nn.Sequential(
            nn.Conv2d(F_int, 1, kernel_size=1, stride=1, padding=0, bias=True),
            nn.BatchNorm2d(1),
            nn.Sigmoid()
        )

        self.relu = nn.ReLU(inplace=True)

    def forward(self, g, x):
        g1 = self.W_g(g)
        x1 = self.W_x(x)
        psi = self.relu(g1 + x1)
        psi = self.psi(psi)

        return x * psi


class LinearBottleneck(nn.Module):
    """LinearBottleneck used in MobileNetV2"""

    def __init__(self, in_channels, out_channels, t=6, stride=2, **kwargs):
        super(LinearBottleneck, self).__init__()
        self.use_shortcut = stride == 1 and in_channels == out_channels
        self.block = nn.Sequential(
            # pw
            _ConvBNReLU(in_channels, in_channels * t, 1),
            # dw
            _DWConv(in_channels * t, in_channels * t, stride),
            # pw-linear
            nn.Conv2d(in_channels * t, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels)
        )

    def forward(self, x):
        out = self.block(x)
        if self.use_shortcut:
            out = x + out
        return out


class PyramidPooling(nn.Module):
    """Pyramid pooling module"""

    def __init__(self, in_channels, out_channels, **kwargs):
        super(PyramidPooling, self).__init__()
        inter_channels = int(in_channels / 4)
        self.conv1 = _ConvBNReLU(in_channels, inter_channels, 1, **kwargs)
        self.conv2 = _ConvBNReLU(in_channels, inter_channels, 1, **kwargs)
        self.conv3 = _ConvBNReLU(in_channels, inter_channels, 1, **kwargs)
        self.conv4 = _ConvBNReLU(in_channels, inter_channels, 1, **kwargs)
        self.out = _ConvBNReLU(in_channels * 2, out_channels, 1)

    def pool(self, x, size):
        # adaptiveavgpool = nn.AdaptiveAvgPool2d(size)
        avgpool = utils.AdaptiveAvgPoolRT2d(x.shape, size)
        # tmp_adaptive = adaptiveavgpool(x)
        # tmp_avg = avgpool(x)

        return avgpool(x)

    def upsample(self, x, size):
        # return F.interpolate(x, size, mode='bilinear', align_corners=True) # TensorRT不支持双线性插值上采样
        return F.interpolate(x, size, mode='nearest', align_corners=None)

    def forward(self, x):
        size = x.size()[2:]
        feat1 = self.upsample(self.conv1(self.pool(x, 1)), size)
        feat2 = self.upsample(self.conv2(self.pool(x, 2)), size)
        feat3 = self.upsample(self.conv3(self.pool(x, 3)), size)
        feat4 = self.upsample(self.conv4(self.pool(x, 6)), size)
        x = torch.cat([x, feat1, feat2, feat3, feat4], dim=1)
        x = self.out(x)
        return x


class LearningToDownsample(nn.Module):
    """Learning to downsample module"""

    def __init__(self, in_channels, dw_channels1=32, dw_channels2=48,
                 out_channels=64, **kwargs):
        super(LearningToDownsample, self).__init__()
        self.conv = _ConvBNReLU(in_channels, dw_channels1, 3, 2, 1)
        self.dsconv1 = _DSConv(dw_channels1, dw_channels2, 2)
        self.dsconv2 = _DSConv(dw_channels2, out_channels, 2)

        # self.bottleneck1 = self._make_layer(LinearBottleneck, 32, 16, 1, 1, 1)
        # self.bottleneck2 = self._make_layer(LinearBottleneck, 16, 24, 2, 6, 2)
        # self.bottleneck3 = self._make_layer(LinearBottleneck, 24, 32, 3, 6, 2)
        # self.bottleneck4 = self._make_layer(LinearBottleneck, 32, 64, 4, 6, 2)

    def _make_layer(self, block, inplanes, planes, blocks, t=6, stride=1):
        layers = []
        layers.append(block(inplanes, planes, t, stride))
        for i in range(1, blocks):
            layers.append(block(planes, planes, t, 1))
        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv(x)
        x = self.dsconv1(x)
        x = self.dsconv2(x)

        # x = self.bottleneck1(x)
        # x = self.bottleneck2(x)
        # x = self.bottleneck3(x)
        # x = self.bottleneck4(x)
        return x


class GlobalFeatureExtractor(nn.Module):
    """Global feature extractor module"""

    def __init__(self, in_channels=64, block_channels=(64, 96, 128),
                 out_channels=128, t=6, num_blocks=(3, 3, 3), **kwargs):
        super(GlobalFeatureExtractor, self).__init__()
        self.bottleneck1 = self._make_layer(
            LinearBottleneck, in_channels, block_channels[0], num_blocks[0], t, 2)
        self.bottleneck2 = self._make_layer(
            LinearBottleneck, block_channels[0], block_channels[1], num_blocks[1], t, 2)
        self.bottleneck3 = self._make_layer(
            LinearBottleneck, block_channels[1], block_channels[2], num_blocks[2], t, 1)
        self.ppm = PyramidPooling(block_channels[2], out_channels)

    def _make_layer(self, block, inplanes, planes, blocks, t=6, stride=1):
        layers = []
        layers.append(block(inplanes, planes, t, stride))
        for i in range(1, blocks):
            layers.append(block(planes, planes, t, 1))
        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.bottleneck1(x)
        x = self.bottleneck2(x)
        x = self.bottleneck3(x)
        x = self.ppm(x)
        return x


class FeatureFusionModule(nn.Module):
    """Feature fusion module"""

    def __init__(self, highter_in_channels, lower_in_channels, out_channels, scale_factor=4, **kwargs):
        super(FeatureFusionModule, self).__init__()
        self.scale_factor = scale_factor
        self.dwconv = _DWConv(lower_in_channels, out_channels, 1)
        self.conv_lower_res = nn.Sequential(
            nn.Conv2d(out_channels, out_channels, 1),
            nn.BatchNorm2d(out_channels)
        )
        self.conv_higher_res = nn.Sequential(
            nn.Conv2d(highter_in_channels, out_channels, 1),
            nn.BatchNorm2d(out_channels)
        )
        self.relu = nn.ReLU(True)

    def forward(self, higher_res_feature, lower_res_feature):
        # lower_res_feature = F.interpolate(lower_res_feature, scale_factor=4, mode='bilinear', align_corners=True) # TensorRT不支持双线性插值上采样
        lower_res_feature = F.interpolate(lower_res_feature, scale_factor=4, mode='nearest', align_corners=None)
        lower_res_feature = self.dwconv(lower_res_feature)
        lower_res_feature = self.conv_lower_res(lower_res_feature)

        higher_res_feature = self.conv_higher_res(higher_res_feature)
        out = higher_res_feature + lower_res_feature
        return self.relu(out)


class Classifer(nn.Module):
    """Classifer"""

    def __init__(self, dw_channels, num_classes, stride=1, **kwargs):
        super(Classifer, self).__init__()
        self.dsconv1 = _DSConv(dw_channels, dw_channels, stride)
        self.dsconv2 = _DSConv(dw_channels, dw_channels, stride)
        self.conv = nn.Sequential(
            nn.Dropout(0.1),
            nn.Conv2d(dw_channels, num_classes, 1)
        )

    def forward(self, x):
        x = self.dsconv1(x)
        x = self.dsconv2(x)
        x = self.conv(x)
        return x


class net(FastSCNN):
    def __init__(
            self,
            in_channels,
            num_classes,
            official_train_model,
            fine_tune=False):
        super().__init__(in_channels, num_classes, official_train_model, fine_tune)
```

**Comment by mk-nvidia** [comment]
Thanks @silaopi, we're looking at the problem

**Comment by sdu2011** [comment]
any update？ meet same error

**Comment by tbaron-nv** [comment]
@sdu2011 it tried to take your code and create a model. I don't seem to reproduce your problem on TRT 7.2 Can you please share the onnx model or provide more precise instruction on how to create the model from your code.

**Comment by silaopi** [comment]
> @silaopi I tried to take your code and create a model. I don't seem to reproduce your problem on TRT 7.2 Can you please share the onnx model or provide more precise instruction on how to create the model from your code.

Since I only have CUDA 10.2 on my server, so I tried TRT 7.2.1(CUDA 10.2 and CUDNN 8.0) and still got same error. The `utils.AdaptiveAvgPoolRT2d` in the network, pt model, pth model, onnx model and all the code relate to the conversion is here:

[https://drive.google.com/drive/folders/10G5ePZUc4P023E_962Z6_MsHe6ACDwHb?usp=sharing](url)

**Comment by tbaron-nv** [comment]
@silaopi thanks for the models, I've still a few issues reproducing the issue. 
I did encountered a few other issues that prevents tensor-rt from successfully importing and running your model

1. In the onnx model you supplied there is usage for float64 which tensor-rt currently doesn't support
2. We are finding an unsupported shape tensor operation - currently under investigation.

I tried looks at the python script you provided (pt2onnx) to check onnx creation but it is importing model.model which I'm not sure which python package that is.

**Comment by silaopi** [comment]
> @silaopi thanks for the models, I've still a few issues reproducing the issue.
> I did encountered a few other issues that prevents tensor-rt from successfully importing and running your model
> 
> 1. In the onnx model you supplied there is usage for float64 which tensor-rt currently doesn't support
> 2. We are finding an unsupported shape tensor operation - currently under investigation.
> 
> I tried looks at the python script you provided (pt2onnx) to check onnx creation but it is importing model.model which I'm not sure which python package that is.

Sorry, I forgot to upload the `model.model` paclage. Now you can see all of them here (the same link in my previous comment): [https://drive.google.com/drive/folders/10G5ePZUc4P023E_962Z6_MsHe6ACDwHb?usp=sharing](url)

And for those issues you encountered:
1. I didn't specify to use float64 in the model saving and tracing process. When I convert the pt model to trt engine, I also got warnings of `[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.` which makes me confuse. Since it is only a warning, I didn't pay too much attention on it.
2. The network of the model I provided is the same one that I commented early in this issue. I don't understand what you mean of "an unsupported shape tensor operation". Maybe it is the `AdaptiveAvgPoolRT2d`  used in my network, whick I implemented by myself and you can find it under `utils` package, since tensorrt does not support the `AdaptiveAvgPoolRT` provide by pytorch.

Thank you by the way.

**Comment by tbaron-nv** [comment]
1. Double refer to double precision floats. layer constant_189 uses double data type which isn't supported by TRT at the moment.
2. Unsupported shape tensor - I was a bit vague cause I had to do some more investigation regarding this issue; Layer floor_192 is part of a shape calculation, i.e is part of calculation chain that leads to a resize operation. floor_192 isn't support as part of shape generation at the moment in TRT. 

Other than these two missing features I couldn't find the pad issue you originally reported, further more I couldn't find the AdaptiveAvgPoolRT2d in the onnx. 
If you can generate an onnx which just the AdapativeAvgPoolRT2d in it. I would be more than happy to take a look.

**Comment by silaopi** [comment]
@tbaron-nv 
Hi, my problem have been solved and it turned out to be an error during model saving process...
About other issues:
1. The double precision and the unsupported shape tensor problem disappear after I solve the model saving issue.
2. About `[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.`, it is caused by `num_batches_tracked` of `torch.nn.BatchNorm`. And it is ok to just leave it.

For other people who use tensorrt, it is necessary to use `onnx-simplify` to simplify the onnx model, otherwise tensorrt would report errors like `[TensorRT] ERROR: ModelImporter.cpp:465: Found (Unnamed Layer* 179) [Unary]_output as a shape tensor output from a layer that does not support it!`.

Thank you for your time! I will close this issue.

**Comment by tbaron-nv** [comment]
@silaopi thanks for letting me know. 

As a side note, pytorch by default using int64 for indexing while tensor-rt only support int32 types it will try to automatically convert it. 
This is a just warning and its usually safe to ignore but make sure you are don't have overflow

**Comment by ahangchen** [comment]
> @tbaron-nv
> Hi, my problem have been solved and it turned out to be an error during model saving process...
> About other issues:
> 
> 1. The double precision and the unsupported shape tensor problem disappear after I solve the model saving issue.
> 2. About `[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.`, it is caused by `num_batches_tracked` of `torch.nn.BatchNorm`. And it is ok to just leave it.
> 
> For other people who use tensorrt, it is necessary to use `onnx-simplify` to simplify the onnx model, otherwise tensorrt would report errors like `[TensorRT] ERROR: ModelImporter.cpp:465: Found (Unnamed Layer* 179) [Unary]_output as a shape tensor output from a layer that does not support it!`.
> 
> Thank you for your time! I will close this issue.

@silaopi How you solve the  `IndexError: Attribute not found: pads`？ I meet the same problem and I find it's caused by torch.nn.averagepool2d. I can successfully save the onnx by torch.onnx.export，but when parse by tensorRT，the attr pads of averagepool2d is not found.

**Comment by silaopi** [comment]
@ahangchen Hi, the `torch.nn.AvgPool2d` is supported by TensorRT, and `torch.nn.AdaptiveAvgPool2d` is not. If you are using the first one, I suggest you try different `opt_version` when you convert torch script model to onnx model.

**Comment by yanghgai** [comment]
> > @tbaron-nv
> > Hi, my problem have been solved and it turned out to be an error during model saving process...
> > About other issues:
> > 
> > 1. The double precision and the unsupported shape tensor problem disappear after I solve the model saving issue.
> > 2. About `[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.`, it is caused by `num_batches_tracked` of `torch.nn.BatchNorm`. And it is ok to just leave it.
> > 
> > For other people who use tensorrt, it is necessary to use `onnx-simplify` to simplify the onnx model, otherwise tensorrt would report errors like `[TensorRT] ERROR: ModelImporter.cpp:465: Found (Unnamed Layer* 179) [Unary]_output as a shape tensor output from a layer that does not support it!`.
> > Thank you for your time! I will close this issue.
> 
> @silaopi How you solve the `IndexError: Attribute not found: pads`？ I meet the same problem and I find it's caused by torch.nn.averagepool2d. I can successfully save the onnx by torch.onnx.export，but when parse by tensorRT，the attr pads of averagepool2d is not found.

Hi, I meet the same problem, have you solved this problem?
