### ISSUE TITLE
pytorch nearest upsample results is not match trt results

### ISSUE THREAD

**Issue by mythke** [NVIDIA/TensorRT#743]
## Environment

**TensorRT Version**: 7.1.3.0
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.0
**Operating System**: Xavier JetPack 4.4
**ONNX Version**: 1.7.0
**Python Version (if applicable)**: 3.6.9
**PyTorch Version (if applicable)**: 1.6.0

## Relevant Files

I use pytorch model to onnx to tensorrt as follow:
Firstly, I use torch.onnx (opset=12) to generate a onnx file.
Secondly, I use onnxsim to simple the onnx file.
Finally, I use trt to generate trt model.
But tensorrt result is not match pytorch result. I debug as fellow.
Firstly, I check onnx. I use onnxruntime to inference a image. its result is the same as pytorch result.
Secondly, I check pytorch model middle layer output. I find after`torch.nn.Upsample(scale_factor=2.0, mode=nearest)`, the feature map is not match tensorrt results.

**Comment by asmasaad** [comment]
I have the same issue

**Comment by ttyio** [comment]
Hello @mythke @asmasaad , this is fixed in 8.0, thanks!

**Comment by ttyio** [comment]
The 8.0EA download link is in https://developer.nvidia.com/nvidia-tensorrt-download
I will close this, please reopen if you still have question, thanks!
