### ISSUE TITLE
the number  of marked output  will affect result

### ISSUE THREAD

**Issue by blazeCCC** [NVIDIA/TensorRT#744]
i am trying Implement a 3-d detection network with tensorRT C++ api ,it has two errors:
(1): when i mark more than one itensor as output,it can acquire  a correct result,but when i  only mark one itensor as ouput ,it can't acquire a correct result(i just compare tensorRT output with pytorch's output)
(2) it's also have a warning  ,but i only add a 128 * 472 *252 tensorrt as output(it is one of a multi head)
08/12/2020-14:58:12] [V] [TRT] Tactic: 0 time 7.86432
[08/12/2020-14:58:12] [V] [TRT] Tactic: 1 time 5.19699
[08/12/2020-14:58:12] [V] [TRT] Tactic: 2 time 8.73267
[08/12/2020-14:58:12] [V] [TRT] Tactic: 4 skipped. Scratch requested: 8726249472, available: 1610612736
[08/12/2020-14:58:12] [V] [TRT] Tactic: 5 time 47.5023
[08/12/2020-14:58:12] [V] [TRT] Tactic: 6 tim  do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
all network's memory should not be as large as  8 GB,someone else could help me,thanks!

**Comment by blazeCCC** [comment]
i have try to increase the workspace from 1GB to 10 GB ,it;s have same error and may can result in other problems!

**Comment by mk-nvidia** [comment]
@blazeCCC please include the following information in the bug so we can help you.
A link to a repro case would also be very helpful in diagnosing the problem


## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (which commit + image + tag)**: 


## Relevant Files




## Steps To Reproduce

**Comment by mk-nvidia** [comment]
Closing due to no response from user.
