### ISSUE TITLE
Jetson Xavier NX build

### ISSUE THREAD

**Issue by MohammadKassemZein** [NVIDIA/TensorRT#748]
Did anyone manage to build the project on Xavier NX with Jetpack 4.4?

**Comment by thunder95** [comment]
simillar question, i am using tensorrt 6,  so need to build the project  on xavier nx with jetpack4.3.

**Comment by mk-nvidia** [comment]
@MohammadKassemZein / @thunder95 are you hitting errors while building, or are you looking for directions to build on this platform? Are you cross compiling or building natively?

**Comment by mk-nvidia** [comment]
Closing due to no response from user.
