### ISSUE TITLE
NvUffParser problem

### ISSUE THREAD

**Issue by chegnyanjun** [NVIDIA/TensorRT#75]
Why i can not find the NvUffParser’s source code,i can find .h file, but i can not find the .cpp file,i want to see and learn it.Does anyone can help me.tkx.

**Comment by narendasan** [comment]
The UFF Parser source code has not been released. You will need to continue to use the compiled binaries.

**Comment by chegnyanjun** [comment]
ok,tks.




------------------ 原始邮件 ------------------
发件人: "Naren Dasan"<notifications@github.com>;
发送时间: 2019年8月20日(星期二) 上午6:16
收件人: "NVIDIA/TensorRT"<TensorRT@noreply.github.com>;
抄送: "cyj"<2735123258@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NVIDIA/TensorRT] NvUffParser problem (#75)




The UFF Parser source code has not been released. You will need to continue to use the compiled binaries.

**Comment by guods** [comment]
@narendasan Where can I found the complied binaries about UFF Parser?

**Comment by rmccorm4** [comment]
Hi @guods,

This repository just contains the open source components. The UFF parser binaries should come with the full TensorRT release (https://developer.nvidia.com/nvidia-tensorrt-download) or in our NGC containers (https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt). 

You can see some of the packages that come with the TensorRT release described here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html#installing-debian

I believe `libnvparsers6` is related to the UFF parser.
