### ISSUE TITLE
[Bug] Can't generate engine on very small network

### ISSUE THREAD

**Issue by twmht** [NVIDIA/TensorRT#751]
## Description

my workflow:
pytorch small network -> pytorch to onnx -> onnx to tensorrt (engine generation failed)

## Environment

**TensorRT Version**:  TensorRT 7.1.3
**GPU Type**:  RTX 2080 Ti
**Nvidia Driver Version**:  440
**CUDA Version**:  cuda10.2
**CUDNN Version**:  cudnn8
**Operating System + Version**:  ubuntu 18.04
**Python Version (if applicable)**:  3.7
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**:  1.6
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

[log.txt](https://github.com/NVIDIA/TensorRT/files/5107261/log.txt)

## Steps To Reproduce

network archtecture

``` python
class Flatten(torch.nn.Module):
    def forward(self, input):
        return input.flatten(1)



class Net(torch.nn.Module):
    def __init__(self, width_mult=1.):
        super(Net, self).__init__()
        in_channels = int(512 * width_mult)
        out_channels = int(128 * width_mult)
        self.layers = torch.nn.Sequential(
                                       nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=1, padding=0),
                                       nn.BatchNorm2d(out_channels),
                                       nn.ReLU6(),
                                       nn.Conv2d(out_channels, out_channels, kernel_size=7, groups=out_channels),
                                       nn.BatchNorm2d(out_channels),
                                       nn.ReLU6(),
                                       Flatten(),
                                       torch.nn.Linear(out_channels, 200)
                                       )
    def forward(self, x, prob=0):
        x = self.layers(x)
        return x
```

convert net to onnx

``` python
    model = Net(width_mult=0.35)
    x = torch.ones((1, 179, 7, 7))
    model.eval()
    torch.onnx.export(model, x, 'net.onnx', input_names=['data'], output_names = ['out'])

```

convert onnx to tensorrt
```python

onnx_path='./net.onnx'
with open(onnx_path, 'rb') as f:
    onnx_bytes = f.read()

log_level=trt.Logger.VERBOSE
logger = trt.Logger(log_level)
builder = trt.Builder(logger)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, logger)
parser.parse(onnx_bytes)

max_batch_size = 20
fp16_mode = False
input_tensor = network.get_input(0)
input_tensor.shape = (-1, 179, 7, 7)
config = builder.create_builder_config()
if fp16_mode:
    config.flags = 1 << int(trt.BuilderFlag.FP16)
config.max_workspace_size = 1<<25
config.min_timing_iterations = 3
config.avg_timing_iterations = 2
profile = builder.create_optimization_profile()
profile.set_shape('data', min=(1, 179, 7, 7), opt=(6, 179, 7, 7), max=(max_batch_size, 179, 7, 7))
config.add_optimization_profile(profile)
builder.max_batch_size = max_batch_size
engine = builder.build_engine(network, config)
```

this would throw

```
[TensorRT] ERROR: ../builder/cudnnBuilderBlockChooser.cpp (117) - Assertion Error in buildMemGraph: 0 (mg.nodes[mg.regionIndices[outputRegion]].size == mg.nodes[mg.regionIndices[inputRegion]].size)
```

The network architecture is very simple, i am not sure why tensorrt not work.

any idea?

**Comment by rmccorm4** [comment]
Hi @twmht ,

I was able to reproduce your error by running your code, but I was able parse your model successfully using `trtexec`:
```
# Start TensorRT container
nvidia-docker run -it -v $PWD:/mnt nvcr.io/nvidia/tensorrt:20.08-py3

# Install dependencies
pip install torch==1.6 onnx==1.7

# Create net.onnx model from script above
python repro.py

# Parse ONNX model
trtexec --explicitBatch --onnx=net.onnx --minShapes=data:1x179x7x7 --optShapes=data:6x179x7x7 --maxShapes=data:20x179x7x7
...
&&&& PASSED TensorRT.trtexec # trtexec --explicitBatch --onnx=net.onnx --minShapes=data:1x179x7x7 --optShapes=data:6x179x7x7 --maxShapes=data:20x179x7x7
```

I think there may be an issue with your script above. Please try double checking or simplifying the script to isolate the issue, as the ONNX model seems fine.

**Comment by twmht** [comment]
@rmccorm4 

so we can parse the onnx model produced from my script with trtexec, but can't parse with tensorrt python api?

**Comment by twmht** [comment]
@rmccorm4 

I finally found out a workaround by changing `input.flatten(1)` to `input.view([input.size(0), -1])`. 

after that it can be parsed with python api.

by the way, I also tried to use torch2trt(https://github.com/NVIDIA-AI-IOT/torch2trt)  to convert to engine directly from pytorch.  the engine is built.  but the result is wrong when using multi batch.

for example, 

I stack the same images and ensemble to batch size=4, the result is expected as same 4 output.

and next I stack same 4 images and ensemble to batch size=8, the result is not expected.  the last four output is not same as the front four output. this is very weird.

**Comment by twmht** [comment]
Here is the code to convert `torch.view` with `torch2trt` (https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/view.py#L17)

I have tried to change

```
    layer.reshape_dims = tuple(output.shape[1:])
```

to

```
    layer.reshape_dims = ctx.method_args[1]
```

but the multibatch issue still occurs. I am not sure what is the correct way to deal with `torch.view` when using torch2trt.

**Comment by twmht** [comment]
@rmccorm4 

I have tried to simplify my code as possible as I can.

you can ignore the pytorch part and only parse the onnx model by using tensorrt python api above.

```python
onnx_path='./net.onnx'
with open(onnx_path, 'rb') as f:
    onnx_bytes = f.read()

log_level=trt.Logger.VERBOSE
logger = trt.Logger(log_level)
builder = trt.Builder(logger)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, logger)
parser.parse(onnx_bytes)

max_batch_size = 20
fp16_mode = False
input_tensor = network.get_input(0)
input_tensor.shape = (-1, 179, 7, 7)
config = builder.create_builder_config()
if fp16_mode:
    config.flags = 1 << int(trt.BuilderFlag.FP16)
config.max_workspace_size = 1<<25
config.min_timing_iterations = 3
config.avg_timing_iterations = 2
profile = builder.create_optimization_profile()
profile.set_shape('data', min=(1, 179, 7, 7), opt=(6, 179, 7, 7), max=(max_batch_size, 179, 7, 7))
config.add_optimization_profile(profile)
builder.max_batch_size = max_batch_size
engine = builder.build_engine(network, config)
```

I believe this is python api bug since `trtexec` works as expected.

**Comment by rmccorm4** [comment]
Hi @twmht ,

Your issue is this line:
```python
input_tensor.shape = (-1, 179, 7, 7)
```

Your ONNX model has a fixed batch size (you can view the model with Netron). You can also see this by the error TensorRT throws when you remove that line:
```
root@c33f74018f70:/mnt# python test.py 
[TensorRT] ERROR: data: kOPT dimensions in profile 0 are [6,179,7,7] but input has static dimensions [1,179,7,7].
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    with builder.build_engine(network, config) as engine, open(args.output, "wb") as f:
AttributeError: __enter__
```

You're trying to force it to have a dynamic batch dimension with this line. However, this doesn't necessarily account for all of the other layers in the model that might also have a input/output shapes with a fixed batch size.

If you want your model to have dynamic shape, you need to export it from PyTorch with dynamic shape (`torch.onnx.export(..., dynamic_axes=...)`). You should not manually edit the ONNX model with your code as it will likely have unexpected consequences.

There's good documentation on exporting with dynamic shape here: https://pytorch.org/docs/stable/onnx.html#frequently-asked-questions

And I have an example here: https://gist.github.com/rmccorm4/b72abac18aed6be4c1725db18eba4930

**Comment by rmccorm4** [comment]
Also, your issue here about dynamic batching is also likely related to trying to force dynamic batch on a fixed-shape model. You need to re-export your ONNX model with dynamic shape, and then try again, and you should get correct results with various batch sizes - assuming you set up your optimization profile and setup the execution context dimensions correctly.

You can use this code as a reference for how to do dynamic shape inference in python: https://github.com/rmccorm4/tensorrt-utils/blob/master/inference/infer.py

**Comment by twmht** [comment]
@rmccorm4 

got it. I will try that as soon as possible.

by the way, I thought I could modify the dynamic batch without regenerating the onnx file due to this post (https://elinux.org/TensorRT/ONNX).

they said I can do this
```
 auto input = network->getInput(0);
 input->setDimensions(Dims4{-1, 3, 224, 224});
```

is this corresponding to python code below?

```
input_tensor = network.get_input(0)
input_tensor.shape = (-1, 179, 7, 7)
```

**Comment by rmccorm4** [comment]
It's possible that it would work, but it's not guaranteed for every model and is bad practice.

That link mentions that here:

> If you still got below error after you modified the dimensions, that means you have to regenerate your onnx model with dynamic input shape

**Comment by mk-nvidia** [comment]
@twmht Is your bug resolved? If so please close this issue.

**Comment by twmht** [comment]
@mk-nvidia 
not confirm yet. I will close this issue if the problem is gone.

**Comment by mk-nvidia** [comment]
@twmht Is https://github.com/onnx/onnx-tensorrt/issues/519 the same issue as this one? If so please close one of these issues. Makes our tracking job a bit easier. Thanks!

**Comment by twmht** [comment]
@mk-nvidia 

yup. the two issues are both related. closing this now.
