### ISSUE TITLE
How to ensure portable across platforms?

### ISSUE THREAD

**Issue by HomeWave** [NVIDIA/TensorRT#756]
When using TensorRT to build engine, can we choose not perform GPU platform related optimization, so as to ensure that the serialized plan file can be used on different GPU platforms? In short, how to ensure/get portable across GPU platforms? Looking forward to the answer...

**Comment by Semen52** [comment]
As far as I know this is impossible for TRT 7.0. For example the same plan is portable between 2080Ti and RTX5000.

**Comment by mk-nvidia** [comment]
@HomeWave sorry, this is unsupported. Furthermore we don't have any plans to support it in the near future.
