### ISSUE TITLE
please add more network_api python samples 

### ISSUE THREAD

**Issue by bing1zhi2** [NVIDIA/TensorRT#757]
when I convert onnx model from pytorch to tensorRT, It has a lot of issues and it's hard to reslove them , So I want to use network api,but the sample ‘network_api_pytorch_mnist’ is too simple , It 's hard to learn how to write a network accroding existing network code.

**Comment by georgeliu95** [comment]
Do you mean how to reconstruct a network in TensorRT? If so, I am studying these things too. And I think we can use `network.add_xxx` to define our networks. See our API document [TensorRT Python API](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/index.html) for more information.

**Comment by bing1zhi2** [comment]
@georgeliu95 Yes .   I konw the api document, but don't konw  how to add same layer to my network, like lstm,seems to need to set four gate weights,but don't know how exactly to do it.  the c ++ example is hard to read....

**Comment by bing1zhi2** [comment]
I  reconstruct some network sucessfully in TensorRT with python api, and I push it to my github: 
 https://github.com/bing1zhi2/TensorRT_samples
I found It's simple if you take same time to read the offical doc( actually I haven't  figured out how to add lstm layer   :-D ， maybe some other day? <(*￣▽￣*)/ )
