### ISSUE TITLE
How to extract the features of the middle layer of the model 

### ISSUE THREAD

**Issue by WSTao** [NVIDIA/TensorRT#764]
tensorrt extracts the features of the middle layer of the model as the input of the custom layer. For example, extract the conv3 layer features and input them to the custom ROIPooling layer

**Comment by XiaoyuWang199** [comment]
You can mark out the layer you want as output layer, then extract the output layer features.

**Comment by ttyio** [comment]
Thanks to @XiaoyuWang199 to provide the solution. I will close this issue. @WSTao you can reopen if you have more questions, thanks all again.

**Comment by Bonsen** [comment]
@XiaoyuWang199 I have the same problem, could u please show any "mark out the layer" code for example ?

**Comment by Bonsen** [comment]
I find caffe we can mark:
1. for (auto& s : outputs)
2. network->markOutput(*blobNameToTensor->find(s.c_str()));

if uff we can mark:
1. parser->registerInput("Input_0", DimsCHW(1, 28, 28), UffInputOrder::kNCHW);
2. parser->registerOutput("Binary_3");

it seems onnx can't mark out output?
1、parser->parse(onnx_filename, DataType::kFLOAT);
2、parser->convertToTRTNetwork();
3、nvinfer1::INetworkDefinition* trtNetwork = parser->getTRTNetwork();

@ttyio @XiaoyuWang199

**Comment by ttyio** [comment]
Hello @Bonsen , using the `INetworkDefinition` , we can query total layers using `getNbLayers()`, then use `getLayer(int32_t index)` to retrieve each layer. the returned layer can be marked as output using `markOutput()`. 

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_network_definition.html

**Comment by Bonsen** [comment]
Hi @ttyio, I will try it, thanks!!!
