### ISSUE TITLE
 how to add two ITensor   using python api .

### ISSUE THREAD

**Issue by bing1zhi2** [NVIDIA/TensorRT#766]
Can't find an useful layer In INetworkDefinition

**Comment by pranavm-nvidia** [comment]
You probably want the [Element-wise layer](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Network.html?highlight=add_elementwise#tensorrt.INetworkDefinition.add_elementwise) with the [SUM op](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html#tensorrt.ElementWiseOperation)

**Comment by bing1zhi2** [comment]
yes,It is.... thank you~
