### ISSUE TITLE
Inference on a model prequantized in pytorch

### ISSUE THREAD

**Issue by chrschinab** [NVIDIA/TensorRT#770]
Hallo,
I want to run inference on a resnet50 model prequantized to INT8 in pytorch . Is there a way to deploy this model in TensorRT? As far as I understood only a quantized ONNX model is accepted by TensorRT. However, currently, Pytorch does not support the conversion to quantized ONNX.
Is it possible to deploy a model prequantized in TFLite with TensorRT?

**Comment by mk-nvidia** [comment]
A future release of TensorRT will be able to import a prequantized model from PyTorch. These models can be quantized using [the toolkit](https://github.com/NVIDIA/TensorRT/tree/master/tools/pytorch-quantization) we released earlier.
We don’t yet support deploying a prequantized model from TFLite

**Comment by skyw** [comment]
Hi

Pytorch does support export (fake) quantized model to ONNX. Although per channel support hasn't been merged to master because it depends on ONNX opset13. See https://github.com/pytorch/pytorch/pull/42835.
