### ISSUE TITLE
Onnx GraphSurgeon subgraph does not cleanup correctly

### ISSUE THREAD

**Issue by Eralien** [NVIDIA/TensorRT#772]
## Description

I was doing some tests based on the OnnxGS example 3 (isolate a subgraph). This example demonstrated how to separate a subgraph by giving input and output tensors, and leaving everything else to OnnxGS.

However, when I was trying to cut out a different part of the graph, an unused node was not eliminated after calling `cleanup()` method.

What the original model is:
![original model](https://user-images.githubusercontent.com/26458167/92564171-56559480-f2ab-11ea-91ae-335e7cdce3df.png)

The subgraph I was trying to make:
![subgraph2](https://user-images.githubusercontent.com/26458167/92564291-80a75200-f2ab-11ea-81e9-0ceaa1a236bf.png)

The subgraph I got:
![subgraph1](https://user-images.githubusercontent.com/26458167/92564317-8ac95080-f2ab-11ea-8e47-b8df78e17795.png)

I solved this issue by setting input node list of Variable "mul_out" as an empty list. So I assumed that the `cleanup` method checks all input and output nodes from the input and output tensors. Yet maybe all parent nodes of input tensors should be ignored during this process.

## Environment

**TensorRT Version**: 7.1.3.4
**GPU Type**: 2080Ti
**Nvidia Driver Version**: 440
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6

## Relevant Files

The example code I used: [https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon/examples/03_isolating_a_subgraph](https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon/examples/03_isolating_a_subgraph) 

## Steps To Reproduce

My code was exactly the [example code](https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon/examples/03_isolating_a_subgraph) except changing 
```python
graph.inputs = [tensors["x0"].to_variable(dtype=np.float32),
                tensors["mul_out"].to_variable(dtype=np.float32, shape=(1, 3, 224, 224))]
graph.outputs = [tensors["Y"].to_variable(dtype=np.float32)]
```

How I solved this issue:
```python
graph.tensors()["mul_out"].inputs = []
graph.cleanup().toposort()
```

**Comment by pranavm-nvidia** [comment]
Good catch, this is happening because `cleanup()` walks backwards from the output tensors to figure out what tensors are used. The problem is that it doesn't stop even once it gets to a tensor that is a graph input.

Thanks for pointing this out, I'll fix it shortly.
