### ISSUE TITLE
NvInfer.h not found

### ISSUE THREAD

**Issue by vujadeyoon** [NVIDIA/TensorRT#773]
Dear all,

I manage to install TensorRT using a tar file by referring to the [official NVIDIA site](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar) and try to convert PyTorch model to TensorRT model. The example codes for the TensorRT are [TensorRT-RetinaFace](https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface).
However, I'm having a problem with a Nvinfer.h.
I think the Nvinfer.h is not existed in my machine.

I installed below packages such as GPU driver, CUDA toolkit, cuDNN and TensorRT by referring to the [DL installation](https://github.com/vujadeyoon/DL-UbuntuMATE18.04LTS-Installation) and [TensorRT-Torch2TRT](https://github.com/vujadeyoon/TensorRT-Torch2TRT).
My machine environments are as follows:
- Operating System (OS): Ubuntu MATE 18.04.3 LTS (Bionic)
- Graphics Processing Unit (GPU): NVIDIA TITAN RTX, 4ea
- GPU driver: Nvidia-440.100
- CUDA toolkit: 10.1 (default), 10.2
- cuDNN: cuDNN v7.6.5
- PyTorch: 1.3.0
- TensorRT: 7.0.0.11
- Torch2TRT: 0.1.0
 
The debug information is as below.
```bash
/home/vujadeyoon/Desktop/tensorrtx/example/decode.h:6:10: fatal error: NvInfer.h: No such file or directory
 #include "NvInfer.h"
```

My questions are below:

1. How to install the Nvinfer.h.
2. Could not the Nvinfer.h be installed when installing TensorRT using a tar file?
3. Please give me any other advice.

Best regards,
Vujadeyoon.

**Comment by vujadeyoon** [comment]
Dear all,

I found a solution related to the problem, non-NvInfer.h.
The installation method related to TensorRT plugin seems to be missing from the [official NVIDIA site](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar). 
I wrote the installation method and experiments between PyTorch and TensorRT-Torch2TRT are summarized for the customized ResNet-18 including interpolation function in the below [github](https://github.com/vujadeyoon/TensorRT-Torch2TRT).
Please refer to Sections 3-F in the [github](https://github.com/vujadeyoon/TensorRT-Torch2TRT) in order to install the TensorRT correctly.

- Github: https://github.com/vujadeyoon/TensorRT-Torch2TRT

Best,
Vujadeyoon

**Comment by rajeevsrao** [comment]
@vujadeyoon can you confirm you downloaded the tarball for 7.0.0.11 from here? It should have an include folder with the NvInfer headers:
https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/7.0/7.0.0.11/tars/TensorRT-7.0.0.11.Ubuntu-18.04.x86_64-gnu.cuda-10.2.cudnn7.6.tar.gz

Alternatively you can get them from the open source 7.0 branch: https://github.com/NVIDIA/TensorRT/tree/release/7.0/include

**Comment by rajeevsrao** [comment]
Closing due to no response. Please reopen if the concern is not addressed.
