### ISSUE TITLE
Algorithms selected propblem while use int8 precision

### ISSUE THREAD

**Issue by XiaoyuWang199** [NVIDIA/TensorRT#778]
## Description
Algorithms selected propblem while use int8 precision。  TensorRT 7.1 add a new function to choose the algorithm manually.
it works well in fp32 percision because algorithms are  choosed for inference.  while in calibration progress,  choose algorithms will 
occur problems . 
[TRT][Debug]Builder timing cache: created 0 entries, 0 hit(s)
[TRT][ERROR]../builder/tacticOptimizer.cpp (1577) - Assertion Error in computeCosts: 0 ((strictTypeConstraints \|\| nbAlgoChoices > 0) && "Number of Algorithm choices for a node must not be zero, unless strictTypeConstraints is true.")

same problem will happen in official sample when I add the choose algorithms function(copy from sampleAlgorithmselector) to sampleINT8.  and disable readcache while excuse calibration to allow choosing algorithm during the calibration  progress.

![图片](https://user-images.githubusercontent.com/44442065/93036858-9afa7a80-f673-11ea-86c7-7703bf7da978.png)

we can found the algorithms nbchoices for caliration is much less for  inference nbchoices  for the same layer. (both for conv0+relu0 layer,    before calibration algorithm has only 1 choose while  after calibration has 34 choices )
![图片](https://user-images.githubusercontent.com/44442065/93037468-11e44300-f675-11ea-8393-94a30f8902dc.png)

![图片](https://user-images.githubusercontent.com/44442065/93037388-e7928580-f674-11ea-9a24-bfa2a36a8dfd.png)
and may occur the bug.  

and for conv1/dw it seems have 0 choices and throws an error, but it seems that algorithms  caskconvolution Tactic 182513... is worked, and why it shows  "Number of Algorithm choices for a node must not be zero, unless strictTypeConstraints is true.
![图片](https://user-images.githubusercontent.com/44442065/93037588-612a7380-f675-11ea-94e0-7f138fd70db1.png)

[TRT][Debug]Builder timing cache: created 0 entries, 0 hit(s)
[TRT][ERROR]../builder/tacticOptimizer.cpp (1577) - Assertion Error in computeCosts: 0 ((strictTypeConstraints \|\| nbAlgoChoices > 0) && "Number of Algorithm choices for a node must not be zero, unless strictTypeConstraints is true.")

## Environment

**TensorRT Version**:  TensorRT v7.1.3
**GPU Type**:  NVIDIA TESLA P4000
**CUDA Version**:   cuda10.2
**CUDNN Version**:  8.0

**Baremetal or Container (which commit + image + tag)**: 
![图片](https://user-images.githubusercontent.com/44442065/93036672-26bfd700-f673-11ea-8816-65a1394903c5.png)

**Comment by ttyio** [comment]
Hello @XiaoyuWang199 , thanks for reporting.

This is an internal optimization that we only provide 1 tactic candidate in the first pass of calibration, to speed up the build process of the first pass. And seems this optimization broken the algorithmselector :-(

Do you have any specific reason that you want to enable algorithmselector in the first pass of calibration? Thanks.

**Comment by ttyio** [comment]
close since there is no response in more than 2 weeks, please reopen if you still have question, thanks!
