### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by linssswww** [NVIDIA/TensorRT#78]
When I follow the compile step， it show error information.

 cd $TRT_SOURCE
 mkdir -p build && cd build 
 cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out
 make -j$(nproc)

I run 'make -j$(nproc)' command
it show error which it say 'Unsupported protocol'

this is compile information

xx:~/ljn_workplace/TensorRT/build$ make -j$(nproc)
Scanning dependencies of target third_party.protobuf
Scanning dependencies of target nvonnxparser_plugin
Scanning dependencies of target nvinfer_plugin
[  0%] Creating directories for 'third_party.protobuf'
Scanning dependencies of target nvinfer_plugin_static
[  0%] Performing download step (download, verify and extract) for 'third_party.protobuf'
-- Downloading...
   dst='/home/dl6/ljn_workplace/TensorRT/build/third_party.protobuf/src/protobuf-cpp-3.0.0.tar.gz'
   timeout='none'
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retrying...
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
[  0%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/nmsPlugin/nmsPlugin.cpp.o
[  0%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/reorgPlugin/reorgPlugin.cpp.o
[  1%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/gridAnchorPlugin/gridAnchorPlugin.cpp.o
[  2%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/nmsPlugin/nmsPlugin.cpp.o
[  2%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/nvFasterRCNN/nvFasterRCNNPlugin.cpp.o
[  2%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/regionPlugin/regionPlugin.cpp.o
[  3%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/priorBoxPlugin/priorBoxPlugin.cpp.o
[  3%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/batchedNMSPlugin/batchedNMSPlugin.cpp.o
[  4%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/batchedNMSPlugin/batchedNMSInference.cpp.o
[  4%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/normalizePlugin/normalizePlugin.cpp.o
[  4%] Building CUDA object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o
[  4%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/batchedNMSPlugin/gatherNMSOutputs.cu.o
[  5%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/flattenConcat/flattenConcat.cpp.o
[  5%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/cropAndResizePlugin/cropAndResizePlugin.cpp.o
[  5%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/normalizePlugin/normalizePlugin.cpp.o
[  7%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/priorBoxPlugin/priorBoxPlugin.cpp.o
[  7%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/proposalPlugin/proposalPlugin.cpp.o
[  7%] Building CUDA object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/ResizeNearest.cu.o
[  8%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/batchTilePlugin/batchTilePlugin.cpp.o
[  8%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/reorgPlugin/reorgPlugin.cpp.o
[  8%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/allClassNMS.cu.o
[  9%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/gridAnchorPlugin/gridAnchorPlugin.cpp.o
[  9%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/bboxDeltas2Proposals.cu.o
[ 10%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/regionPlugin/regionPlugin.cpp.o
[ 10%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/nvFasterRCNN/nvFasterRCNNPlugin.cpp.o
[ 10%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/common.cu.o
[ 10%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/batchedNMSPlugin/batchedNMSInference.cpp.o
[ 10%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/cropAndResizeKernel.cu.o
[ 11%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/batchedNMSPlugin/batchedNMSPlugin.cpp.o
[ 11%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/batchedNMSPlugin/gatherNMSOutputs.cu.o
[ 11%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/flattenConcat/flattenConcat.cpp.o
[ 13%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/decodeBBoxes.cu.o
[ 14%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/cropAndResizePlugin/cropAndResizePlugin.cpp.o
[ 14%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/detectionForward.cu.o
[ 14%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/proposalPlugin/proposalPlugin.cpp.o
[ 14%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/batchTilePlugin/batchTilePlugin.cpp.o
[ 14%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/extractFgScores.cu.o
[ 15%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/allClassNMS.cu.o
[ 15%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/bboxDeltas2Proposals.cu.o
[ 16%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/gatherTopDetections.cu.o
[ 17%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/common.cu.o
[ 17%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/generateAnchors.cu.o
[ 17%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/gridAnchorLayer.cu.o
[ 19%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/kernel.cpp.o
[ 19%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/nmsLayer.cu.o
[ 19%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/normalizeLayer.cu.o
[ 20%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/permuteData.cu.o
[ 20%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/priorBoxLayer.cu.o
[ 21%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/proposalKernel.cu.o
[ 21%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/proposalsForward.cu.o
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
[ 21%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/cropAndResizeKernel.cu.o
[ 21%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/decodeBBoxes.cu.o
[ 21%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/regionForward.cu.o
/home/dl6/ljn_workplace/TensorRT/plugin/common/kernels/proposalKernel.cu(34): warning: variable "ALIGNMENT" was declared but never referenced

[ 22%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/detectionForward.cu.o
[ 22%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/extractFgScores.cu.o
[ 23%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/reorgForward.cu.o
[ 23%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/roiPooling.cu.o
[ 23%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/rproiInferenceFused.cu.o
[ 23%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/sortScoresPerImage.cu.o
[ 25%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/kernels/sortScoresPerClass.cu.o
[ 25%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/common/nmsHelper.cpp.o
[ 25%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/gatherTopDetections.cu.o
[ 26%] Building CUDA object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/Split.cu.o
[ 26%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/InstanceNormalization.cpp.o
[ 27%] Building CXX object plugin/CMakeFiles/nvinfer_plugin_static.dir/InferPlugin.cpp.o
[ 28%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/generateAnchors.cu.o
[ 28%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_plugin.dir/plugin.cpp.o
[ 28%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/gridAnchorLayer.cu.o
[ 28%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/kernel.cpp.o
[ 29%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/nmsLayer.cu.o
[ 29%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/normalizeLayer.cu.o
[ 29%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/permuteData.cu.o
[ 30%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/priorBoxLayer.cu.o
[ 30%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/proposalKernel.cu.o
[ 32%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/proposalsForward.cu.o
/home/dl6/ljn_workplace/TensorRT/plugin/common/kernels/proposalKernel.cu(34): warning: variable "ALIGNMENT" was declared but never referenced

-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
[ 32%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/regionForward.cu.o
[ 32%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/reorgForward.cu.o
[ 33%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/roiPooling.cu.o
[ 33%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/rproiInferenceFused.cu.o
[ 33%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/sortScoresPerClass.cu.o
[ 34%] Building CUDA object plugin/CMakeFiles/nvinfer_plugin.dir/common/kernels/sortScoresPerImage.cu.o
[ 34%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/common/nmsHelper.cpp.o
[ 34%] Building CXX object plugin/CMakeFiles/nvinfer_plugin.dir/InferPlugin.cpp.o
[ 34%] Linking CXX static library ../out/libnvinfer_plugin_static.a
[ 34%] Built target nvinfer_plugin_static
[ 35%] Linking CXX shared library ../out/libnvinfer_plugin.so
[ 35%] Built target nvinfer_plugin
[ 36%] Linking CXX static library libnvonnxparser_plugin.a
[ 36%] Built target nvonnxparser_plugin
Scanning dependencies of target nvonnxparser_runtime
Scanning dependencies of target nvonnxparser_runtime_static
[ 38%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_runtime_static.dir/PluginFactory.cpp.o
[ 38%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_runtime_static.dir/NvOnnxParserRuntime.cpp.o
[ 38%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_runtime.dir/NvOnnxParserRuntime.cpp.o
[ 38%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_runtime.dir/PluginFactory.cpp.o
[ 38%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_runtime_static.dir/builtin_plugins.cpp.o
[ 39%] Building CXX object parsers/onnx/CMakeFiles/nvonnxparser_runtime.dir/builtin_plugins.cpp.o
[ 39%] Linking CXX shared library ../../out/libnvonnxparser_runtime.so
[ 40%] Linking CXX static library libnvonnxparser_runtime_static.a
[ 40%] Built target nvonnxparser_runtime_static
[ 40%] Built target nvonnxparser_runtime
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
CMake Error at third_party.protobuf-stamp/download-third_party.protobuf.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    

CMakeFiles/third_party.protobuf.dir/build.make:90: recipe for target 'third_party.protobuf/src/third_party.protobuf-stamp/third_party.protobuf-download' failed
make[2]: *** [third_party.protobuf/src/third_party.protobuf-stamp/third_party.protobuf-download] Error 1
CMakeFiles/Makefile2:139: recipe for target 'CMakeFiles/third_party.protobuf.dir/all' failed
make[1]: *** [CMakeFiles/third_party.protobuf.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

how can I solve the problem ?

**Comment by nfeng0105** [comment]
You may need to rebuild cmake with './bootstrap --system-curl' and try again, refer to below page
https://stackoverflow.com/questions/44633043/cmake-libcurl-was-built-with-ssl-disabled-https-not-supported/44633762

**Comment by linssswww** [comment]
@nfeng0105 thank for your reply， I have solved this problem by other way.

**Comment by LouisNUST** [comment]
@linssswww hi,how did you resolve this problem? I have the same problem.

**Comment by linssswww** [comment]
@LouisNUST I just download the file by firefox， and copy this file to path which it need， and meanwhile I  modify the makefile .  If you do not, It will cover your file which you copy

**Comment by LouisNUST** [comment]
@linssswww  which makefile should be modifed and how to do that? thanks for your reply.

**Comment by wangguojun2018** [comment]
> You may need to rebuild cmake with './bootstrap --system-curl' and try again, refer to below page
> https://stackoverflow.com/questions/44633043/cmake-libcurl-was-built-with-ssl-disabled-https-not-supported/44633762

I solved the problem  with your answer

**Comment by smiletobingxue** [comment]
@linssswww hi, I came across the same problem, could you teach me how to modify the makefile, thank you in advance!

**Comment by x-jeff** [comment]
@nfeng0105 thanks.The same problem was solved by the method you provided

**Comment by ChenCVer** [comment]
> @linssswww hi,how did you resolve this problem? I have the same problem.

can you tell me how to modfy the MakeFile??

**Comment by tingshua-yts** [comment]
this  is work for me
- comment `URL ${Protobuf_PKG_URL}` in third_party/protobuf.cmake
- download protobuf-cpp-3.20.1.tar.gz and unpack it to build/third_party.protobuf/src/third_party.protobuf
