### ISSUE TITLE
IBuilder::buildEngineWithConfig returns `nullptr`

### ISSUE THREAD

**Issue by golden0080** [NVIDIA/TensorRT#782]
## Description

I used C++ API to build new TensorRT engine from ONNX parser.
I had to make hacks to make ONNX parser to support Custom Plugins and the parsed network looks fine.
But when calling `IBuilder::buildEngineWithConfig`, the result is always `nullptr` and no information to help me debug this.

## Environment

**TensorRT Version**: 7.0.0
**GPU Type**: Nvidia 2080Ti
**Nvidia Driver Version**: 440
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (which commit + image + tag)**: 

## Relevant Files

Cannot share code unfortunately.

**Comment by pranavm-nvidia** [comment]
Can you try with verbose logging?

**Comment by golden0080** [comment]
Managed to make it work by setting a bigger `MaxWorkspaceSize` to builder.
I will try verbose logging and really think if the function returns `nullptr` and it deserves some logging higher than verbose only.

**Comment by golden0080** [comment]
Tried with verbose logging:
```
----------------------------------------------------------------
Input filename:   cuda-bnet-voxel.onnx
ONNX IR version:  0.0.7
Opset version:    11
Producer name:    tf2onnx
Producer version: 1.5.4
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
 ----- Parsing of ONNX model cuda-bnet-voxel.onnx is Done ---- 
2020-09-16 18:14:13.304061: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-16 18:14:14.380019: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
```

Basically nothing after building function returns.

**Comment by mk-nvidia** [comment]
@golden0080 Thanks for reporting this, we should fix both the root cause and the logger behavior. Can you please share your model so we can repro this at our end?

**Comment by golden0080** [comment]
Hi, @mk-nvidia unfortunately this model is proprietary and I'm unable to share.
I think the silent failure issue came when I set `MaxWorkspaceSize` to un-reasonably large or small (might set it to 0 mistakenly).

**Comment by golden0080** [comment]
Thanks for the attention to this ticket, and I was able to work around the issue with:
Setting `MaxWorkspaceSize` to a reasonable size.

I think for similar issues, people could try to sanity check their `IBuilder` config.

**Comment by beizhengren** [comment]
@golden0080 Hi, I met the same problem that `buildEngineWithConfig` return nullptr. And I tried to change `MaxWorkspaceSize`
but not work. How should I debug this problem, thank you!

**Comment by nvpohanh** [comment]
When `buildEngineWithConfig` returns a nullptr, it means something went wrong in the engine building process, and there could be many different causes. When seeing this, please share verbose logs so that we can assist you to find the right solution.

**Comment by nvpohanh** [comment]
@SheenChi TRT 7.1 does not support Ampere GPUs.

**Comment by SheenChi** [comment]
I can run the program on A30 normally with TRT 7.1. If this problem is cause by trt version to low, Is TRT8.4 support 3090 gpu

**Comment by nvpohanh** [comment]
Yes, could you try TRT 8.4 GA on 3090 GPU?

**Comment by SheenChi** [comment]
ok, I will try it, thanks
