### ISSUE TITLE
IResizeLayer with dynamic batch size

### ISSUE THREAD

**Issue by uni19** [NVIDIA/TensorRT#783]
TensorRT version 7.1.3.4

```cpp
    auto layer = net->addResize(*in);
    layer->setOutputDimensions(outShape);
```

To work with dynamic batch size, the first dimension of outShape is set -1.   Then, TensorRT complains "../builder/cudnnBuilderGraph.cpp (780) - Assertion Error in checkDimsSanity: 0 (dims.d[i] >= 0)".

So, how can I make IResizeLayer works with dynamic batch size? Or this is not supported?

Thanks

**Comment by pranavm-nvidia** [comment]
You can use [setInput](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/api/c_api/classnvinfer1_1_1_i_resize_layer.html#a0c8fca7b93c914f8fd7272b3687fe99b) to set the output shape to a runtime value

**Comment by uni19** [comment]
> You can use [setInput](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/api/c_api/classnvinfer1_1_1_i_resize_layer.html#a0c8fca7b93c914f8fd7272b3687fe99b) to set the output shape to a runtime value

@pranavm-nvidia  Thank you for your response very much！

First, my model have multiple resize layer, if using multiple input shape binding to specify their output shape, I think this is not easy to use.

Second, if use IShapeLayer for this, how can I compute the target output shape? Add a plugin to compute the output shape?

**Comment by pranavm-nvidia** [comment]
@uni19 Yes, it would be fairly verbose for multiple resize layers. An automated import path, like the ONNX parser, might be easier to use.

To do it it manually though, you can use regular TRT layers with IShapeLayer. For example, to double the image size for an NCHW input (in psuedo-code):
```
shape = addShape(in)->getOutput(0)
shape *= (1, 1, 2, 2) # Use elementwise PROD with a constant second input for this

layer = addResize(in)
layer->setInput(1, shape)
```
(of course, in this example case, you could just use [setScales](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/api/c_api/classnvinfer1_1_1_i_resize_layer.html#adaad346ef772c6dfa4ec8cc74b117214) instead)

**Comment by uni19** [comment]
@pranavm-nvidia For the scale factor case, I can use `addScales`. But I want to fix the target output size. It seems that i need to add a plugin.

**Comment by uni19** [comment]
@pranavm-nvidia  Oh, I think I can do this, thank you
`
shape = shape * (1, 1, 0, 0) + (0, 0, h, w)
`
