### ISSUE TITLE
how to use TensorRT registered plugins in My application?

### ISSUE THREAD

**Issue by CaptainJohansson** [NVIDIA/TensorRT#784]
according to the develop guide,  the first step is to call initLibNvInferPlugins(void* logger, const char* libNamespace)() in my application code and then add an embedded plugin (such as leakyReLU)using the below codes:
//Use the extern function getPluginRegistry to access the global TensorRT Plugin Registry
    auto creator = getPluginRegistry()->getPluginCreator("LReLU_TRT", "1");
    // const PluginFieldCollection* pluginData = creator->getFieldNames();
    // -------------------- pluginfield -------------------------------------
    PluginField* tempField;
    tempField = (PluginField*)malloc(sizeof(PluginField));
    float pluginVariable[] = {0.1};
    tempField = new PluginField("negSlope", &pluginVariable[0], PluginFieldType::kFLOAT32, 1);
    const PluginFieldCollection pluginData = {1, tempField};
    // ---------------------------------------------------------------------
    // const PluginFieldCollection pluginData;
    IPluginV2 *pluginObj = creator->createPlugin("leak_relu", &pluginData);
    assert(pluginObj != nullptr);
    ITensor* inputTensor[] = {data};
    auto leaky = network->addPluginV2(&inputTensor[0], 1, *pluginObj);
Since the LeakyReLU implementation contains a hyperparameter, usually 0.1, but a nullptr is obtained through the getFiledNames function. My code is to create a new PluginFieldCollection object, but I want to know if there are other ways to implement the plugin call.

**Comment by CaptainJohansson** [comment]
//Use the extern function getPluginRegistry to access the global TensorRT Plugin Registry
    auto creator = getPluginRegistry()->getPluginCreator("LReLU_TRT", "1");
    // const PluginFieldCollection* pluginData = creator->getFieldNames();
    // -------------------- pluginfield -------------------------------------
    PluginField* tempField;
    tempField = (PluginField*)malloc(sizeof(PluginField));
    float pluginVariable[] = {0.1};
    tempField = new PluginField("negSlope", &pluginVariable[0], PluginFieldType::kFLOAT32, 1);
    const PluginFieldCollection pluginData = {1, tempField};
    // ---------------------------------------------------------------------
    // const PluginFieldCollection pluginData;
    IPluginV2 *pluginObj = creator->createPlugin("leak_relu", &pluginData);
    assert(pluginObj != nullptr);

**Comment by ttyio** [comment]
Hello @CaptainJohansson , you are using the correct way to construct plugin when you do not have the header file of the plugin. If you own the plugin source, you can get rid of the `pluginfield`. Here is an example in the C++ demoBERT in `rel-6.0` :

- register plugin: https://github.com/NVIDIA/TensorRT/blob/release/6.0/demo/BERT/plugins/skipLayerNormPlugin.cu#L132
- plugin constructor:  https://github.com/NVIDIA/TensorRT/blob/release/6.0/demo/BERT/plugins/skipLayerNormPlugin.h#L36
- create plugin: https://github.com/NVIDIA/TensorRT/blob/release/6.0/demo/BERT/layers/transformer.h#L38


Hope it helps, thanks!

**Comment by scuizhibin** [comment]
When I get a trt file containing a custom plugin, how do I deserialize it?

**Comment by ttyio** [comment]
Hello @scuizhibin , you need load the custom plugin before deserialize the trt file like this:

      ctypes.CDLL("libcustomer_plugin.so", mode=ctypes.RTLD_GLOBAL)
