### ISSUE TITLE
Missing Makefile in <TensorRT root directory>/samples/sample_uff_maskRCNN directory

### ISSUE THREAD

**Issue by SharifElfouly** [NVIDIA/TensorRT#785]
## Description

I'm currently trying to run the TensorRT Uff-MaskRCNN sample like described [here](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN).

I'm able to run the first step **Prerequisites** successfully but get stuck at the first step of **Running the sample**, where the the model should be compiled using the Makefile. The problem is that there is no Makefile at all, only a CMakeList file.

All of this happens inside the provided Docker Image: _nvcr.io/nvidia/tensorflow:19.10-py3_

Any help would be greatly appreciated.

**Comment by mk-nvidia** [comment]
This seems to be a bug at our end, sorry for the trouble.

**Comment by ttyio** [comment]
@SharifElfouly , have you tried build the sample using CMake follow

https://github.com/NVIDIA/TensorRT/tree/release/8.0#building-tensorrt-oss

Thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
