### ISSUE TITLE
How to use OpenCV in "sampleOnnxMNIST.cpp" ?

### ISSUE THREAD

**Issue by Scottchou7** [NVIDIA/TensorRT#794]
Hi, I am new to C++ and TensorRT. I trained a MobileNetV1 to classify my own data in Keras. I tried to load this model by modifying "[sampleOnnxMNIST.cpp](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleOnnxMNIST/sampleOnnxMNIST.cpp#L238-L264)". However the output value was wrong. I think the reason is the way I use OpenCV. I have referenced "[sampleFasterRCNN.cpp](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleFasterRCNN/sampleFasterRCNN.cpp#L281-L293)" but still wrong. Below is my code. Can anyone help? Thanks.(BTW: I use [keras2onnx](https://github.com/onnx/keras-onnx) convert .h5 to .onnx)

OS: Win10 (Visual Studio 2017)
GPU: 2080 Ti
TensorRT version:  7.1.3.4
Tensorflow version: 1.15
Keras version: 2.2.4
CUDA version: 11.0
Cudnn version: 8.0.2
onnx version: 1.6.0

```
bool SampleOnnxMNIST::processInput(const samplesCommon::BufferManager& buffers)
{
        const int inputC = mInputDims.d[1];
	const int inputH = mInputDims.d[2];
	const int inputW = mInputDims.d[3];
	const int batchSize = mParams.batchSize;

	cv::Mat origin_image = cv::imread("D:/TensorRT/TensorRT-7.1.3.4/data/test1.jpg", 1);
	if (!origin_image.data)
	{
		cerr << "Error : could not load image." << endl;
		return false;
	}
	cv::Mat resize_image;
	cv::resize(origin_image, resize_image, cv::Size(inputH, inputW), cv::INTER_CUBIC);

	// Fill data buffer
	float* hostDataBuffer = static_cast<float*>(buffers.getHostBuffer(mParams.inputTensorNames[0]));
	for (int i = 0, volImg = inputC * inputH * inputW; i < batchSize; ++i)
	{
		for (int c = 0; c < inputC; ++c)
		{
			for (unsigned j = 0, volChl = inputH * inputW; j < volChl; ++j)
				hostDataBuffer[i * volImg + c * volChl + j] = 1.0 - float(resize_image.data[j * inputC + 2 - c]/255.);
		}
	}
    return true;
}
```

**Comment by Scottchou7** [comment]
```
----------------------------------------------------------------
Input filename:   net.onnx
ONNX IR version:  0.0.7
Opset version:    10
Producer name:    keras2onnx
Producer version: 1.6.0
Domain:           onnx
Model version:    0
Doc string:
----------------------------------------------------------------
[09/23/2020-09:45:42] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/23/2020-09:46:13] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[09/23/2020-09:46:37] [I] [TRT] Detected 1 inputs and 1 output network tensors.
[09/23/2020-09:46:37] [I] Output:
[09/23/2020-09:46:37] [I]  Prob 0  0.0598 Class 0: *
[09/23/2020-09:46:37] [I]  Prob 1  0.0598 Class 1: *
[09/23/2020-09:46:37] [I]  Prob 2  0.0598 Class 2: *
[09/23/2020-09:46:37] [I]  Prob 3  0.0598 Class 3: *
[09/23/2020-09:46:37] [I]  Prob 4  0.0598 Class 4: *
[09/23/2020-09:46:37] [I]  Prob 5  0.0598 Class 5: *
[09/23/2020-09:46:37] [I]  Prob 6  0.0598 Class 6: *
[09/23/2020-09:46:37] [I]  Prob 7  0.0598 Class 7: *
[09/23/2020-09:46:37] [I]  Prob 8  0.0598 Class 8: *
[09/23/2020-09:46:37] [I]  Prob 9  0.0598 Class 9: *
[09/23/2020-09:46:37] [I]  Prob 10  0.0598 Class 10: *
[09/23/2020-09:46:37] [I]  Prob 11  0.0598 Class 11: *
[09/23/2020-09:46:37] [I]  Prob 12  0.0598 Class 12: *
[09/23/2020-09:46:37] [I]  Prob 13  0.0598 Class 13: *
[09/23/2020-09:46:37] [I]  Prob 14  0.1626 Class 14: **
[09/23/2020-09:46:37] [I]
```

**Comment by aunsid** [comment]
How did you fix this? Do you have the code for "Fill data buffer?"

**Comment by aunsid** [comment]
if anyone is looking for this

bool SampleUffSSD::processInput(const samplesCommon::BufferManager& buffers)
     const int batchSize = mParams.batchSize;

     // Available images
-    std::vector<std::string> imageList = {"dog.ppm", "bus.ppm"};
+    std::vector<std::string> imageList = {"test.jpeg"};
     mPPMs.resize(batchSize);
     assert(mPPMs.size() <= imageList.size());
     for (int i = 0; i < batchSize; ++i)
     {
-        readPPMFile(locateFile(imageList[i], mParams.dataDirs), mPPMs[i]);
+        readImage(locateFile(imageList[i], mParams.dataDirs), image);
     }
 
     float* hostDataBuffer = static_cast<float*>(buffers.getHostBuffer(mParams.inputTensorNames[0]));
     // Host memory for input buffer
-    for (int i = 0, volImg = inputC * inputH * inputW; i < mParams.batchSize; ++i)
+    for (int i = 0, volImg = inputH * inputW; i < mParams.batchSize; ++i)
     {
-        for (int c = 0; c < inputC; ++c)
+        for (unsigned j = 0, volChl = inputH * inputW; j < inputH; ++j)
         {
-            // The color image to input should be in BGR order
-            for (unsigned j = 0, volChl = inputH * inputW; j < volChl; ++j)
-            {
-                hostDataBuffer[i * volImg + c * volChl + j]
-                    = (2.0 / 255.0) * float(mPPMs[i].buffer[j * inputC + c]) - 1.0;
+                   for( unsigned k = 0; k < inputW; ++ k)
+                       {
+                cv::Vec3b bgr = image.at<cv::Vec3b>(j,k);
+                hostDataBuffer[i * volImg + 0 * volChl + j * inputW + k] = (2.0 / 255.0) * float(bgr[2]) - 1.0;
+                hostDataBuffer[i * volImg + 1 * volChl + j * inputW + k] = (2.0 / 255.0) * float(bgr[1]) - 1.0;
+                hostDataBuffer[i * volImg + 2 * volChl + j * inputW + k] = (2.0 / 255.0) * float(bgr[0]) - 1.0;
             }
         }
source: https://forums.developer.nvidia.com/t/custom-trained-ssd-inception-model-in-tensorrt-c-version/143048/14
