### ISSUE TITLE
how to get the bert inference performance on A100?

### ISSUE THREAD

**Issue by wangweiw** [NVIDIA/TensorRT#796]
I could run the benchmark on A100, and get the results like this :
![image](https://user-images.githubusercontent.com/3614967/94234859-180fd480-ff3d-11ea-8c46-5c498ec3651d.png)

But how to convert the latency time into sentence/s?
![image](https://user-images.githubusercontent.com/3614967/94234901-2fe75880-ff3d-11ea-94f5-ae6f4a404653.png)

**Comment by ttyio** [comment]
Hello @wangweiw , thanks for reporting.

we can use formula `1000ms / time_per_batch_in_ms * batch_size` to calculate `sentences/s`, and in your case the `batch_size` is 1, so you only need `1000/1.70694....`

**Comment by ttyio** [comment]
Close since get no response for more than 2 weeks, please reopen if you have more questions, thanks!
