### ISSUE TITLE
Parse faster_rcnn_test_iplugin.prototxt  error when running sampleFasterRCNN.

### ISSUE THREAD

**Issue by liangshaohua** [NVIDIA/TensorRT#8]
[I] Begin parsing model...
[**libprotobuf ERROR E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\text_format.cc:298**] Error parsing text-format ditcaffe.NetParameter: 483:21: Message type "ditcaffe.LayerParameter" has no field named "roi_pooling_param".
[E] [TRT] CaffeParser: Could not parse deploy file
[I] End parsing model...

I download the TensorRT-5.1.5.0 GA for windows from https://developer.nvidia.com/nvidia-tensorrt-5x-download. The sampleMNIST can run successfully, but the sample_fasterRCNN run failed.The error is strange,because my computer doesn't have an e-disk and my protobuf is v3.8.0. When comparing it with TensorRT OSS , I found that they are very different.  And how build the TensorRT OSS on windows 10?

**Comment by rajeevsrao** [comment]
@liangshaohua 

Did you use the docker based build, and if not can you try that? Also whats the OS on your build machine?

Windows support is not verified for the TensorRT OSS workflow in this release, although you could try generating VS solution from the CMakeFiles provided.

**Comment by liangshaohua** [comment]
My machine is windows10 x64 with VS2015. I didn't use docker, and the TensorRT I use is downloaded from NVIDIA. I found that your TensorRT OSS  is not the same as NVIDIA TensorRT. Thank you!

**Comment by rajeevsrao** [comment]
Sorry, we don't support Windows just yet for the OSS builds.
