### ISSUE TITLE
create PRROI_TRT plugin fail

### ISSUE THREAD

**Issue by linssswww** [NVIDIA/TensorRT#80]
my code:
import torch
import tensorrt as trt
import numpy as np
import time
import pycuda.driver as cuda
import pycuda.autoinit
import cv2
from torchvision import models as models

import onnx

G_LOGGER = trt.Logger(trt.Logger.WARNING)
trt.init_libnvinfer_plugins(G_LOGGER, "")
PLUGIN_CREATORS = trt.get_plugin_registry().plugin_creator_list

poolingH = trt.PluginField("poolingH", np.array([7], dtype=np.float32), trt.PluginFieldType.INT32)
poolingW = trt.PluginField("poolingW", np.array([7], dtype=np.float32), trt.PluginFieldType.INT32)
featureStride = trt.PluginField("featureStride", np.array([8], dtype=np.float32), trt.PluginFieldType.INT32)
preNmsTop = trt.PluginField("preNmsTop", np.array([2000], dtype=np.float32), trt.PluginFieldType.INT32)
nmsMaxOut = trt.PluginField("nmsMaxOut", np.array([2000], dtype=np.float32), trt.PluginFieldType.INT32)
anchorsRatioCount = trt.PluginField("anchorsRatioCount", np.array([3], dtype=np.float32), trt.PluginFieldType.INT32)
anchorsScaleCount = trt.PluginField("anchorsScaleCount", np.array([1], dtype=np.float32), trt.PluginFieldType.INT32)
iouThreshold = trt.PluginField("iouThreshold", np.array([0.7], dtype=np.float32), trt.PluginFieldType.FLOAT32)
minBoxSize = trt.PluginField("minBoxSize", np.array([0], dtype=np.float32), trt.PluginFieldType.FLOAT32)
spatialScale = trt.PluginField("spatialScale", np.array([1.0], dtype=np.float32), trt.PluginFieldType.FLOAT32)

anchorsRatios = trt.PluginField("anchorsRatios", np.array([1, 2, 0.5], dtype=np.float32), trt.PluginFieldType.FLOAT32)
anchorsScales = trt.PluginField("anchorsScales", np.array([0.2], dtype=np.float32), trt.PluginFieldType.FLOAT32)

field_collection = trt.PluginFieldCollection([poolingH, poolingW, featureStride, preNmsTop, nmsMaxOut, anchorsRatioCount, anchorsScaleCount, iouThreshold, minBoxSize, spatialScale, anchorsRatios, anchorsScales])
plugin = PLUGIN_CREATORS[12].create_plugin(name = "RPROI_TRT", field_collection = field_collection)

error information:
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

how can I solve this problem?

**Comment by nan0755** [comment]
Have you solve this problem?
I think the key solution is how to pass `anchorsRatios = trt.PluginField("anchorsRatios", np.array([1, 2, 0.5], dtype=np.float32), trt.PluginFieldType.FLOAT32)` to c++ api, i.e. the two elements np.array.
