### ISSUE TITLE
3080 support

### ISSUE THREAD

**Issue by zhangyux15** [NVIDIA/TensorRT#800]
## Description
I run tensorrt sample with 3080 failed, but works for 2080ti by setdevice.

## Environment

**TensorRT Version**: 7.1.3.4
**GPU Type**: 3080
**Nvidia Driver Version**: 456.38
**CUDA Version**: 11.0
**CUDNN Version**: 8.0
**Operating System + Version**: Windows
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (which commit + image + tag)**: 

## Relevant Files

TensorRT.sample_onnx_mnist

## Steps To Reproduce
I just run the onnx sample:

RUNNING TensorRT.sample_onnx_mnist # E:\TensorRT-7.1.3.4.Windows10.x86_64.cuda-11.0.cudnn8.0\TensorRT-7.1.3.4\samples\sampleOnnxMNIST\\..\..\bin\sample_onnx_mnist.exe
[09/27/2020-02:51:07] [I] Building and running a GPU inference engine for Onnx MNIST

Input filename:   ../../data/mnist/mnist.onnx
ONNX IR version:  0.0.3
Opset version:    8
Producer name:    CNTK
Producer version: 2.5.1
Domain:           ai.cntk
Model version:    1
Doc string:

[09/27/2020-02:51:27] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/27/2020-02:51:28] [E] [TRT] C:\source\rtSafe\cuda\caskUtils.cpp (98) - Assertion Error in nvinfer1::rt::task::trtSmToCask: 0 (Unsupported SM.)
&&&& FAILED TensorRT.sample_onnx_mnist # E:\TensorRT-7.1.3.4.Windows10.x86_64.cuda-11.0.cudnn8.0\TensorRT-7.1.3.4\samples\sampleOnnxMNIST\\..\..\bin\sample_onnx_mnist.exe

**Comment by zerollzeng** [comment]
I am wondering what's the TensorRT 8.0 release date, in next major version the 30x series device should be supported.

**Comment by mk-nvidia** [comment]
We're in the process of releasing an updated TensorRT version 7.2.x very soon which will add support for RTX 30xx GPUs, thanks for your patience.

**Comment by zerollzeng** [comment]
So when will 8.x cversion comes out? 😃

Mayank Kaushik <notifications@github.com> 于 2020年10月1日周四 上午12:22写道：

**Comment by xkszltl** [comment]
@mk-nvidia Any timeline/ETA for the very soon 7.2.x?

**Comment by mk-nvidia** [comment]
@xkszltl 7.2.1 is now live.

**Comment by sherlockchou86** [comment]
Seems 7.2.1 would not work with cuda 11.1 on 3080. Anybody has tested it successfully on 3080?

**Comment by dirtmaxim** [comment]
@sherlockchou86 I tested, it works. I built TensorFlow with 7.2.1 support https://github.com/yaroslavvb/tensorflow-community-wheels/issues/168

**Comment by sherlockchou86** [comment]
it works now！my mistake as the driver was not installed successfully with the right version

**Comment by pustar** [comment]
> We're in the process of releasing an updated TensorRT version 7.2.x very soon which will add support for RTX 30xx GPUs, thanks for your patience.

I am facing 'Assertion Error in nvinfer1::rt::task::trtSmToCask: 0 (Unsupported SM.)' problem,  with RTX 3060, cuda 11.0, win10, cudnn 8.1

**Comment by pustar** [comment]
> it works now！my mistake as the driver was not installed successfully with the right version

Would you please tell me the proper version of cuda and cudnn which work fine with Tensorrt 7.2.4?

**Comment by pustar** [comment]
Which version of tensorflow did you use?   Which version of  cuda and tensorrt? Can you tell me? Thank you very much

> @sherlockchou86 I tested, it works. I built TensorFlow with 7.2.1 support [yaroslavvb/tensorflow-community-wheels#168](https://github.com/yaroslavvb/tensorflow-community-wheels/issues/168)
