### ISSUE TITLE
[TRT] FAILED_EXECUTION: Unknown exception

### ISSUE THREAD

**Issue by Jacoobr** [NVIDIA/TensorRT#804]
When i try to run the [instanceNormalizationPlugin](https://github.com/NVIDIA/TensorRT/tree/master/plugin/instanceNormalizationPlugin), i get the Error bellow:

```
[E] [TRT] C:\source\rtExt\cuda\cudaPluginV2DynamicExtRunner.cpp (108) - Cuda Error in nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute: 1 (invalid argument)
[E] [TRT] FAILED_EXECUTION: Unknown exception
```
And the input buffers is a [1x16x200x200] float32 data, when run the code bellowed, the error occurred!!
```
//status = context->executeV2(buffers.getDeviceBindings().data()); // calculate the prediction result.
 status = context->enqueue(mParams.batchSize, buffers.getDeviceBindings().data(), stream_, nullptr);
```
BTY, the network build with explicitBatch:
```
const auto explicitBatch = 1U << static_cast<uint32_t>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH);
auto network = SampleUniquePtr<nvinfer1::INetworkDefinition>(builder->createNetworkV2(explicitBatch));
```
Anyone has any idea about this error?

**Comment by ttyio** [comment]
@Jacoobr , thanks for reporting.

could you provide the full steps for repro? thanks.

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!
