### ISSUE TITLE
ScatterND Plugin not found while converting onnx into tensorrt model

### ISSUE THREAD

**Issue by sunilpankaj** [NVIDIA/TensorRT#805]
Able to convert pytorch model into onnx and validated onnx output with pytorch. it's working fine. But when I try to convert onnx into tensorrt engine, it fails at onnx parser and return this error.

[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1

Onnx version : 1.6.0 
Tensorrt version : 7.1.3.4

Can anyone please help here, how can I add ScatterND plugin in python and how can I use it ? Is there any other way to solve this problem ?

Thanks in advance.

**Comment by Jacoobr** [comment]
Hi, sunilpankaj. Maybe you should register the ScatterND in [builtin_op_importers](https://github.com/onnx/onnx-tensorrt/blob/fbebb144744b3be8defecd8478d74940056df305/builtin_op_importers.cpp). The builtin_op_importers write the logical operations  that tensorrt called when onnx-tensorrt try to convert onnx model to trt engine. BTY, you also can implement the ScatterND with plugin manner, like [plugin](https://github.com/NVIDIA/TensorRT/tree/master/plugin).  Last but not least, DEFINE_BUILTIN_OP_IMPORTER(ScatterND){} is must if you want the onnx-tensorrt parse you own ScatterND operation. Hope this can help U~.

**Comment by zldrobit** [comment]
I encountered the same problem as OP.
I use trtexec tool for converting onnx to TensorRT model.
I notice that there's no ScatterND plugin in TensorRT.

**Comment by ttyio** [comment]
Hello @sunilpankaj  @zldrobit 
Sorry there is no support for ScatterND yet. You can follow @Jacoobr 's suggestion to implement your own plugin and register in ONNX parser. thanks!

**Comment by ajaichemmanam** [comment]
@ttyio @Jacoobr 
Can you give a sample scatterND plugin implementation? and how to use it?

**Comment by GrainsofSalt** [comment]
I am having the same issue. @Jacoobr @ttyio Is there any sample documentation for implementing a plugin like this?

**Comment by alicera** [comment]
I also meet the [TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1

**Comment by mfoglio** [comment]
Same here

**Comment by PhilCuriosity** [comment]
> 嗨，sunilpankaj。也许你应该登记在ScatterND [builtin_op_importers](https://github.com/onnx/onnx-tensorrt/blob/fbebb144744b3be8defecd8478d74940056df305/builtin_op_importers.cpp)。Builtin_op_importers编写了在onnx-tensorrt尝试将onnx模型转换为trt引擎时tensorrt调用的逻辑操作。顺便说一句，您还可以通过plugin方式实现ScatterND，例如[plugin](https://github.com/NVIDIA/TensorRT/tree/master/plugin)。最后但并非最不重要的一点是，如果您希望onnx-tensorrt解析自己的ScatterND操作，则必须DEFINE_BUILTIN_OP_IMPORTER（ScatterND）{}。希望这对你有帮助。

有没有实例代码啊

**Comment by htran170642** [comment]
Have you guys converted to tensorrt 7.1x sucessfully? Thanks

**Comment by alicera** [comment]
If it has the tourial for creating the custom operator, it will be good

**Comment by ttyio** [comment]
FYI, ScatterND is native op in next TRT release, in about 2 months, thanks

**Comment by alicera** [comment]
Hi @ttyio 
Thanks.
Do you have the tutorial for creating the custom operator?

**Comment by ttyio** [comment]
Hi @alicera ,
Here is the `instanceNormalization` sample:
plugin: https://github.com/NVIDIA/TensorRT/tree/master/plugin/instanceNormalizationPlugin
parser: https://github.com/onnx/onnx-tensorrt/blob/7d4f86d540738be76da0fe41bed401f4ce67614c/builtin_op_importers.cpp#L2106

**Comment by alicera** [comment]
Hi @ttyio 
Thanks.
By the way, how to check the tensorRT version for my os?

**Comment by ttyio** [comment]
Hi @alicera 
For python 

      >>> import tensorrt
      >>> print(tensorrt.__version__)

For C++, you can use getInferLibVersion(), thanks

**Comment by alicera** [comment]
Does it has the easy command to check the version, like watch nvidia-smi?
Or go to xxx folder to see the info.

**Comment by ttyio** [comment]
Hi @alicera 
Maybe you can search libnvinfer.so in you system and check which file it is link to.

**Comment by LukeAI** [comment]
@ttyio  - so apparently the [21.07 TensorRT container](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_21-07.html) includes the ScatterND plugin. - Do you know if there some way to install this, natively?

**Comment by htran170642** [comment]
@LukeAI I did build successfully ScatterBN plugin with Tensorrt 7.2.2.3. You just clone the repo with your expected version and copy folder ScatterND  in folder plugin then rebuild your tensorrt.

**Comment by stardust2602** [comment]
> @LukeAI I did build successfully ScatterBN plugin with Tensorrt 7.2.2.3. You just clone the repo with your expected version and copy folder ScatterND in folder plugin then rebuild your tensorrt.

Hi, can it work with ScatterElements op ?

**Comment by qiuhongxiang** [comment]
> Does it has the easy command to

where the repo?

**Comment by qiuhongxiang** [comment]
@htran170642 where the repo?

**Comment by nvpohanh** [comment]
I think ScatterND is supported as of TRT 8.4 EA. @rajeevsrao could you confirm?

**Comment by htran170642** [comment]
> @htran170642 where the repo?

this repo: https://github.com/NVIDIA/trt-samples-for-hackathon-cn
but you'd better use Tensorrt 8x, it's already supported many plugins like that

**Comment by rajeevsrao** [comment]
Yes, TensorRT 8.4 EA release has support for ONNX ScatterND Operator.
https://developer.nvidia.com/nvidia-tensorrt-8x-download

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Comment by daxiongpro** [comment]
> 

hi，can you make a tutorials for making ScatterND plugin on Tensorrt7.2.2 ? thx!

**Comment by daxiongpro** [comment]
> @LukeAI I did build successfully ScatterBN plugin with Tensorrt 7.2.2.3. You just clone the repo with your expected version and copy folder ScatterND in folder plugin then rebuild your tensorrt.

hello, can you make a tutorial for making ScatterND Plugin on TensorRT 7.2.2.3 ? thx very much!
