### ISSUE TITLE
[TensorRT] ERROR: (Unnamed Layer* 4) [ElementWise]: elementwise inputs must not be Int32

### ISSUE THREAD

**Issue by haif-liu** [NVIDIA/TensorRT#808]
## Description
when i use parser.parse(model.read()),

[TensorRT] ERROR: (Unnamed Layer* 4) [ElementWise]: elementwise inputs must not be Int32

tensort 5.1

**Comment by ttyio** [comment]
@haif-liu , thanks for reporting
Could you try latest tensorRT 7.2?

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!
