### ISSUE TITLE
Slow 3D convolution on RTX 2070 (by using -fp16, too)

### ISSUE THREAD

**Issue by Mishok43** [NVIDIA/TensorRT#816]
## Description

I have a simple 3D Convolution model and have some problem with inferecing it using TensorRT on RTX 2070.
Model:
![image](https://user-images.githubusercontent.com/19211368/95453269-30d3ad80-0973-11eb-85c8-e0391ebbe282.png)

This is dump profile with **fp16**:
![image](https://user-images.githubusercontent.com/19211368/95453093-ea7e4e80-0972-11eb-8ad9-ef22e8931d02.png)
**fp32**:
![image](https://user-images.githubusercontent.com/19211368/95453133-fb2ec480-0972-11eb-96d2-5277e0920518.png)
As you can see 3d convolutions take a lot of time, and i think it's really strange, and they don't speed up by switching to fp16. 
Does it mean that 3D Convolutions are not optimized still and I'm supposed to use Conv2D for better performance?

## Environment

**TensorRT Version**: TensorRT-7.1.3.4.Windows10.x86_64.cuda-11.0.cudnn8.0
**GPU Type**:  RTX 2070
**Nvidia Driver Version**:  456.43
**CUDA Version**:  11
**CUDNN Version**: 8.0
**Operating System + Version**: Windows 10
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (which commit + image + tag)**: 

## Relevant Files

[model16.zip](https://github.com/NVIDIA/TensorRT/files/5347531/model16.zip)

## Steps To Reproduce
I attached my model (onnx 11) and log file for fp16 (verbose mode).

**Comment by ttyio** [comment]
Hello @Mishok43 , thanks for reporting.

I have checked your log, and I'd like to point out 2 things:

1.  some lines like  `Tactic: xxx skipped. Scratch requested: aaa, available: bbb`
It means you can have more tactic as candidate if you increase the `max_workspace_size` in `builderConfig`. https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/NetworkConfig.html#tensorrt.IBuilderConfig 

2. the 3d conv filter `K`, `C` are too small, this small workload not fit fp16 tensorcore well and it is expect that get not much benefit from it.
e.g, from log line `Layer(Convolution): conv3d, Tactic: 0, adjusted_input6[Half(1,128,128,128)] -> convolution_output6[Half(2,128,128,128)]`
so the C=1, K=2. We can get a better fp16 perf if we have a larger C, K.

**Comment by Mishok43** [comment]
Thank you, I got it. Because of your recommendations I have changed the arhitecture of my model to different one
![image](https://user-images.githubusercontent.com/19211368/96524158-27561980-1280-11eb-929d-3b811952bb6d.png)
But the tensorrt inference is really strange for UpSampling3D layers. It generates a lot of layers with names: StatefulPartitionedCall/functional_1/up_sampling3d_1/split:12 copy and  (Unnamed Layer* 229) [Slice] for them, which take the majority of the inference time of my model. ( I have attached again the model and profile data)
[3dmodel.zip](https://github.com/NVIDIA/TensorRT/files/5405490/3dmodel.zip)

**Comment by ttyio** [comment]
> up_sampling3d_1

Thanks @Mishok43 for reply, these upsampling3d_1/split:* is not generated by tensorRT, if you check your original onnx model, check node `StatefulPartitionedCall/functional_1/up_sampling3d_1/split`, you can see they are in the onnx. 

Could you try [onnx-simplifier](https://github.com/daquexian/onnx-simplifier) to polish the model, to see if this tool can reduce these copies?

**Comment by Mishok43** [comment]
@ttyio 
Thank you for the advice, I tried to use keras2onnx instead of tf2onnx and it has helped me to get rid of these strange layers. But, anyway, I returned to my main problem with fp16 optimization of 3D Convolutions -> it doesn't work((( 
![image](https://user-images.githubusercontent.com/19211368/97002240-63200600-1542-11eb-9f09-ce6f6051f9c0.png)
My 3D layers:
![image](https://user-images.githubusercontent.com/19211368/97002408-9cf10c80-1542-11eb-8243-a9d0c6c122e2.png)
![image](https://user-images.githubusercontent.com/19211368/97002458-b2fecd00-1542-11eb-9f98-d3d1bd1efdd7.png)
And I understand that the two last layers isn't able to optimize because the number of channels is not % 8 == 0. But what's about the 1th, 2th, 3rd convolutions? 96->96, 96->48, 48->24 -> a lot of channels for optimization, as it seen to me. I tried to set memory workspace to big numbers, but it doesn't  help me, too. I attached my model.

[model_export.zip](https://github.com/NVIDIA/TensorRT/files/5429342/model_export.zip)

**Comment by Mishok43** [comment]
I changed the number of channels  for the last 2 layers to 32 and LReLu to ReLU activiation -> doesn't help((

**Comment by ttyio** [comment]
Hello @Mishok43 , sorry I have no RTX2070 in hand, so I tried another Turing GPU (RTX 8000) on your updated model, and I see tensorcore acceleration on the 3d conv nodes, once the acceleration is open, we can observe reformat before and after `conv3d` (because of the leaky_relu).  

I notice I am using different TensorRT version. Could you try:
- TensorRT 7.2
- --workspace=4096  ( I tried this size and not see any warning, so I did not try small workspace)
Thanks!

**Comment by Mishok43** [comment]
I tried TensorRT-7.2.1.6.Windows10.x86_64.cuda-11.1.cudnn8.0 and TensorRT-7.2.1.6.Windows10.x86_64.cuda-11.0.cudnn8.0  (because i didn't find TensorRT-7.2.0 for Windows for downloading from nvidia official website) with workspace==4096 -> Nothing has changed. What can I do to investigate the reasons of this strange behaivour?

**Comment by ttyio** [comment]
Hello @Mishok43 , could you run on you system using command line:

> trtexec.exe --onnx=model_export.onnx --fp16 --workspace=4096  --saveEngine=fp16.engine --verbose --dumpProfile > run.log

and send back the `run.log` ? Thanks!

**Comment by Mishok43** [comment]
Hello @ttyio , I attached the log file: 
[run.log](https://github.com/NVIDIA/TensorRT/files/5476002/run.log)

**Comment by ttyio** [comment]
Hello @Mishok43 , thanks for sharing.
Hmmm, it seems you are not loading tensorrt 7.2, because we have supported dynamic plugin `BatchedNMSDynamic_TRT` since 7.2, see below link:

    https://github.com/NVIDIA/TensorRT/blob/release/7.1/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp
    https://github.com/NVIDIA/TensorRT/blob/release/7.2/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp

But from your log, I see only:

    [11/02/2020-18:10:36] [V] [TRT] Plugin creator registration succeeded - ::BatchedNMS_TRT

The correct 7.2 run should also has a line like this:

    ****** Registered plugin creator - ::BatchedNMSDynamic_TRT 

Could you using depends tools (https://www.dependencywalker.com/) to check the 7.2 tensorrt is loaded? this also reminder me that we should support print out the loaded tensorrt version in the verbose log.

**Comment by Mishok43** [comment]
I logged NV_TENSORRT_VERSION variable value and it's 7201. And I didn't understand how can I use dependancy walker for this task, I only was able to find field tensorrt_version_7_0_0_11: 
![image](https://user-images.githubusercontent.com/19211368/98040914-2c939680-1e32-11eb-9497-65de404d0335.png)
Hope this info could help. Thank you @ttyio

**Comment by ttyio** [comment]
Hello @Mishok43 , 
> I logged NV_TENSORRT_VERSION variable value and it's 7201.
How did you do this? did you modify the trtexec code? This macro is defined in header, and it is only the static version that compiler seen from the header. There is another API `getInferLibVersion` you can use to check the version number dynamically from nvinfer.dll. 

From your screenshot, we are using a 7.0 TRT; if you right click the `NVINFER.DLL` in the left tree, you can enable "full paths" from the context menu. And you can double confirm that the nvinfer.dll loaded is 7.0.
You might need change the `PATH` environment to make sure the right `nvinfer.dll` is used, another easier way is to put the nvinfer.dll in the same directory as trtexec.exe, make sure system can load it correctly. Once you change the `PATH` or move the file to the same directory, you can still use dependency walker to verify it. or check `BatchedNMSDynamic_TRT` in the verbose log.

**Comment by Mishok43** [comment]
@ttyio Yes, I logged by changing code this version. Man, you're awesome, I set the correct PATH and everything is working fine now! Inference time is decreased to about 1.45 ms in fp16 mode (3.2ms in fp32 mode)! Thank you, really.

**Comment by ttyio** [comment]
You are welcome @Mishok43 , and glad to hear the updated perf number :-)

I will close this now, have a good day~
