### ISSUE TITLE
How can I compile without git and internet

### ISSUE THREAD

**Issue by shamoqianting** [NVIDIA/TensorRT#817]
Hi guys,
Is it possible to compile tensorRT from source in an environment without internet connection ?
 I mean the automatically download using git can not be used. But I can download the needed sources from another computer.
I tried but got stuck at the step of building protobuf.
what I got is the following:

`[  0%] Performing download step (download, verify and extract) for 'third_party.protobuf'
-- Downloading...
   dst='/data1/angelahuang/install_files/TensorRT-7-tag20.01/TensorRT/build/third_party.protobuf/src/protobuf-cpp-3.0.0.tar.gz'
   timeout='none'
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retrying...
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
[ 17%] Built target nvinfer_plugin
[ 36%] Built target nvinfer_plugin_static
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...`

I tried to download the file protobuf-cpp-3.0.0.tar.gz and put it under ./build/third_party.protobuf/src/, but still I got error:

`[  0%] Performing download step (download, verify and extract) for 'third_party.protobuf'
-- File already exists but no hash specified (use URL_HASH):
  file='/data1/angelahuang/install_files/TensorRT-7-tag20.01/TensorRT/build/third_party.protobuf/src/protobuf-cpp-3.0.0.tar.gz'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/data1/angelahuang/install_files/TensorRT-7-tag20.01/TensorRT/build/third_party.protobuf/src/protobuf-cpp-3.0.0.tar.gz'
   timeout='none'
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retrying...
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
[ 17%] Built target nvinfer_plugin
[ 36%] Built target nvinfer_plugin_static
-- Using src='https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...`

can anyone be kind to help me with this please ？

**Comment by ZhangChuann** [comment]
I come across same problem， have you solve it？thank you

**Comment by ZhangChuann** [comment]
1. vim ./third_party.protobuf/src/third_party.protobuf-stamp/download-third_party.protobuf.cmake
2. change as follow：
![image](https://user-images.githubusercontent.com/10493733/96883061-8bf8ba80-14b2-11eb-908a-9f78d58ad092.png)

3. make， and sucessful
