### ISSUE TITLE
How to serialize model with the required computing power

### ISSUE THREAD

**Issue by mltloveyy** [NVIDIA/TensorRT#818]
Is there an interface function that can set the computing power to generate the desired serialization model？
The computing power of my robot and the notebook are different, and it's more troublesome to rebuild on the robot.
Use the notebook generated model on the robot, it will get an error named "The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 7.5, please rebuild."

**Comment by ttyio** [comment]
Hello @mltloveyy , thanks for reporting.
Sorry current TensorRT serialized engine files are not portable across platforms, we have to build the engine on the production deployment environment. 

More details in https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work

Could you elaborate more on the troublesome to rebuild on the robot? Thanks.

**Comment by ttyio** [comment]
closing since no response for more than 1 month, please reopen if you still have question, thanks!
