### ISSUE TITLE
How to design a caffe plugin layer

### ISSUE THREAD

**Issue by leosk-knight** [NVIDIA/TensorRT#819]
@kevinch-nv As mentioned in issue 491: https://github.com/NVIDIA/TensorRT/issues/491, How to design a caffe plugin layer?
How do I define denseblock_param? in trtcaffe.proto?
For the release version of TensorRT, is there a demo to demonstrate how to add a user-defined plugin?

**Comment by mk-nvidia** [comment]
@leosk-knight Please see https://docs.nvidia.com/deeplearning/tensorrt/sample-support-guide/index.html#plugin_sample
As indicated earlier, we're deprecating the UFF and caffe paths and recommend switching to ONNX.
