### ISSUE TITLE
nvinfer1::IPluginV2DynamicExt::enqueue  (float *)outputs[1] == nullptr

### ISSUE THREAD

**Issue by jianxiezhendong** [NVIDIA/TensorRT#822]
I write a op which has multiple output using the TensorRT plugin. But when I get the second address of output, I find the address points to nullptr. 
Could you give me some ideas?

**Comment by pranavm-nvidia** [comment]
Just to double check, are you returning the correct number of outputs in:
```
virtual int32_t getNbOutputs() const noexcept = 0;
```
?

**Comment by jianxiezhendong** [comment]
@pranavm-nvidia Yes, I set the correct number of outputs in this function.

**Comment by jianxiezhendong** [comment]
@pranavm-nvidia Thanks for your reply! I solved this problem. In function "executeV2", I make an error in "engine bindings". The number of outputs bindings  is less than the correct num. Thanks!

**Comment by ttyio** [comment]
close since this is solved, thanks
