### ISSUE TITLE
Resize layer provides two ways to resize tensor dimensions. But got the different results, when the mode is kLINEAR

### ISSUE THREAD

**Issue by crystalwan** [NVIDIA/TensorRT#823]
## Description

Hi, We used tensorrt c++ API to create resize layer to achive upsample Function. The input size is (1,512,7,10), the outputsize is (1,512,14,20). We use the two ways to set the output Dimensions(), but got the different results, why?

way 1:
`IResizeLayer* upsample = network->addResize(*conv1->getOutput(0));`
`Dims4 upsample_dim{1,512,14,20};`
`upsample->setOutputDimensions(upsample_dim);`
`upsample->setResizeMode(ResizeMode::kLINEAR);`
`upsample->setAlignCorners(true);`

way 2:
`IResizeLayer* upsample = network->addResize(*conv1->getOutput(0));`
`std::vector<float> upsample_sacles{1,1,2,2}`;
`upsample->setScales(upsample_scales.data(), upsample_scales.size())`
`upsample->setResizeMode(ResizeMode::kLINEAR);`
`upsample->setAlignCorners(true);`

## Environment

**TensorRT Version**: 6.0.1.5
**GPU Type**: 2080TI
**Nvidia Driver Version**:430.50 
**CUDA Version**: 10.0
**CUDNN Version**: 
**Operating System + Version**: Ubuntu 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (which commit + image + tag)**:

**Comment by ttyio** [comment]
Hello @crystalwan , thanks for the question.

When we did not provide the `scale` input, TRT will take the responsibility to calculate the `scale`, and we will check the `ResizeMode` and `AlignCorners`, when `alignCorners` is `true` and `resizeMode` is `kLINEAR`, the scale calculation behavior the same as `coordinate_transformation_mode` set to "align_corners" in ONNX (https://github.com/onnx/onnx/blob/master/docs/Operators.md#resize), the formula is `x_original = x_resized * (length_original - 1) / (length_resized - 1)`, so the result is different than you directly set scale to `2`.

PS. sorry for the bad documentation about the `IResizeLayer`, we have plan to enhance it.

**Comment by crystalwan** [comment]
> Hello @crystalwan , thanks for the question.
> 
> When we did not provide the `scale` input, TRT will take the responsibility to calculate the `scale`, and we will check the `ResizeMode` and `AlignCorners`, when `alignCorners` is `true` and `resizeMode` is `kLINEAR`, the scale calculation behavior the same as `coordinate_transformation_mode` set to `align_corners` in ONNX (https://github.com/onnx/onnx/blob/master/docs/Operators.md#resize), the formula is `x_original = x_resized * (length_original - 1) / (length_resized - 1)`, so the result is different than you directly set scale to `2`.
> 
> PS. sorry for the bad documentation about the `IResizeLayer`, we have plan to enhance it.

Thanks.
When I want to build a engine with dynamic shapes , the IResizeLayer can't use the first way to set the Output Dimensions to achieve upsample operation, because the last layer output dimensions is (1,512,-1,-1). And we must ensure the inference result be consistent to the first way (specify output dimensions directly).  What should I do, any suggestions?

**Comment by ttyio** [comment]
Thanks @crystalwan 
I have checked pytorch implementation, and you are right, when `align_corners = true`, we should always use the output dims and input dims to calculate the `transformation_mode`, else we will hit this mismatch.

Before we fix this issue, you can WAR it by using `IResizeLayer::set_input`, I have prototype a python version code, the C++ code should be similar, could you take a try? thanks.


`
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(explicit_batch_flag) as network, builder.create_builder_config() as builder_config:
        input0 = network.add_input(name="input", dtype=trt.float32, shape=(1, 1, -1, -1))
        inputS = network.add_shape(input0)

        scale = network.add_constant(shape=(4, ), weights=trt.Weights(np.ascontiguousarray([1, 1, 2, 2], dtype=np.int32)))
        newsize = network.add_elementwise(inputS.get_output(0), scale.get_output(0), trt.ElementWiseOperation.PROD)

        resizeLayer = network.add_resize(input0)
        resizeLayer.resize_mode = trt.ResizeMode.LINEAR
        resizeLayer.align_corners = True
        resizeLayer.set_input(1, newsize.get_output(0))
        network.mark_output(resizeLayer.get_output(0))


        profile = builder.create_optimization_profile()
        profile.set_shape("input", min=(1, 1, 1, 1), opt=(1, 1, 7, 10), max=(1, 1, 7, 10))
        builder_config.add_optimization_profile(profile)

        engine = builder.build_engine(network, builder_config)
        with engine.create_execution_context() as context:
            context.set_binding_shape(0, (1, 1, 7, 10))
            context.set_shape_input(1, (1, 1, 14, 20))

            a_input = gpuarray.to_gpu(np.arange(1, 71).astype(np.float32))

            a_output = gpuarray.to_gpu(np.arange(1, 281).astype(np.float32))
            context.execute_async_v2(bindings=[int(a_input.gpudata), int(a_output.gpudata)], stream_handle=stream.handle)
            stream.synchronize()

`

**Comment by crystalwan** [comment]
> Thanks @crystalwan
> I have checked pytorch implementation, and you are right, when `align_corners = true`, we should always use the output dims and input dims to calculate the `transformation_mode`, else we will hit this mismatch.
> 
> Before we fix this issue, you can WAR it by using `IResizeLayer::set_input`, I have prototype a python version code, the C++ code should be similar, could you take a try? thanks.
> 
> ```
>     input0 = network.add_input(name="input", dtype=trt.float32, shape=(1, 1, -1, -1))
>     inputS = network.add_shape(input0)
> 
>     scale = network.add_constant(shape=(4, ), weights=trt.Weights(np.ascontiguousarray([1, 1, 2, 2], dtype=np.int32)))
>     newsize = network.add_elementwise(inputS.get_output(0), scale.get_output(0), trt.ElementWiseOperation.PROD)
> 
>     resizeLayer = network.add_resize(input0)
>     resizeLayer.resize_mode = trt.ResizeMode.LINEAR
>     resizeLayer.align_corners = True
>     resizeLayer.set_input(1, newsize.get_output(0))
>     network.mark_output(resizeLayer.get_output(0))
> 
>     profile = builder.create_optimization_profile()
>     profile.set_shape("input", min=(1, 1, 1, 1), opt=(1, 1, 7, 10), max=(1, 1, 7, 10))
>     builder_config.add_optimization_profile(profile)
> 
>     engine = builder.build_engine(network, builder_config)
>     with engine.create_execution_context() as context:
>         context.set_binding_shape(0, (1, 1, 7, 10))
>         context.set_shape_input(1, (1, 1, 14, 20))
> 
>         a_input = gpuarray.to_gpu(np.arange(1, 71).astype(np.float32))
> 
>         a_output = gpuarray.to_gpu(np.arange(1, 281).astype(np.float32))
>         context.execute_async_v2(bindings=[int(a_input.gpudata), int(a_output.gpudata)], stream_handle=stream.handle)
>         stream.synchronize()
> ```

Thanks,
I try to use `IResizeLayer::set_input` with c++ codes in my project, it works!

**Comment by ttyio** [comment]
Thanks @crystalwan , internally we have fixed this, closing since we have workaround for the public release. and please reopen if you have more question.
