### ISSUE TITLE
UNSUPPORTED_NODE: Assertion failed: scales.is_weights() && "Resize scales must be an initializer!

### ISSUE THREAD

**Issue by Darshcg** [NVIDIA/TensorRT#825]
Dear Team,

I am trying to convert my Custom Pytorch model to TRT model. 

I converted the Pytorch model to the ONNX model successfully using the code below:

```
from models import *
from datasets import letterbox #*
from utils import *
import numpy as np
import sys, random
import torch
import torchvision
from torchvision import models, transforms
from PIL import Image
import io
import torch.nn as nn
from torch.autograd import Variable
import cv2
import os
import logging

img_size=(416, 416)
cfg = 'yolov3-spp.cfg'
imgsz = img_size

import torch
import torch.onnx


model_pt_path = "last.pt"
model_def_path = "models.py"

model = Darknet(cfg, imgsz)
model.load_state_dict(torch.load(model_pt_path),strict=False)

dummy_input = torch.randn(1,3,416,416)

torch.onnx.export(model, dummy_input, "onnx_model_name.onnx", opset_version=10)
```

This worked Successfully.
But while Converting ONNX Model to TRT Model I am getting an error. The Complete log has been attached below:

```
WARNING: TensorRT Python 2 support is deprecated, and will be dropped in a future version!
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
In node -1 (importResize): UNSUPPORTED_NODE: Assertion failed: scales.is_weights() && "Resize scales must be an initializer!"
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "ONNX_to_TRT.py", line 43, in <module>
    save_engine(engine, engine_name) 
  File "ONNX_to_TRT.py", line 16, in save_engine
    buf = engine.serialize() 
AttributeError: 'NoneType' object has no attribute 'serialize'
```

May I know how to get rid of this?

Environment:
**TRT version: 7.1
Target: Jetson Nano.
CUDA Version: 10.2**

Thanks in advance

**Comment by ttyio** [comment]
Hello @Darshcg , thanks for reporting.
Currently onnx-trt parser only support `scale` data provide in the initializer if you use onnx `resize` with `scale` input, could you share your onnx model? let's check if the `scale` is static value, thanks!

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!

**Comment by guyiyifeurach** [comment]
I met same question, and it use a float value. And I want to know, how to fix the problem? @ttyio Thank you!
![image](https://user-images.githubusercontent.com/32059046/143360213-fd484e8a-0cbb-4d26-9917-912a3af2bc6b.png)

**Comment by ttyio** [comment]
Hello @guyiyifeurach , we have no support `scales` as input tensor, we only support `scales` as initializer (static value in onnx model)

**Comment by XL634663985** [comment]
> 我遇到了同样的问题，它使用了一个浮点值。我想知道，如何解决这个问题？@ttyio谢谢你！ ![图片](https://user-images.githubusercontent.com/32059046/143360213-fd484e8a-0cbb-4d26-9917-912a3af2bc6b.png)
How to solve this problem please？
