### ISSUE TITLE
index to gather must not exceed length of vector

### ISSUE THREAD

**Issue by gabepack** [NVIDIA/TensorRT#826]
## Description

I'm encountering an error when attempting to convert an ONNX model that my team uses for inference to TensorRT. The model can be parsed, but engine construction fails with the following.

```
[TensorRT] ERROR: Gather_2: index to gather must not exceed length of vector
[TensorRT] ERROR: Builder failed while analyzing shapes.
```

Strangely, if I extract the small sub-model that contains `Gather_2` and the few relevant graph nodes and inputs that precede `Gather_2`, I am able to build an engine for the small sub-model.

Noting that the sub-model extraction utility first performs shape inference, I applied shape inference to the full model but to no avail.

The sub-model is like so.

```
>>> import onnx
>>> onnx.load('onnx_opset11/model.onnx').graph.node[:3]
[input: "input_ids"
output: "197"
name: "Shape_0"
op_type: "Shape"
, output: "198"
name: "Constant_1"
op_type: "Constant"
attribute {
  name: "value"
  t {
    data_type: 7
    name: "Constant_1_attr::value"
    raw_data: "\001\000\000\000\000\000\000\000"
  }
  type: TENSOR
}
, input: "197"
input: "198"
output: "199"
name: "Gather_2"
op_type: "Gather"
attribute {
  name: "axis"
  i: 0
  type: INT
}
]
```

The optimization profile shapes for `input_ids` are simply like `profile.set_shape('input_ids', (1, 256), (1, 256), (1, 256))`.

Any guidance is appreciated.

## Environment

**TensorRT Version**: 7.1.3.4
**GPU Type**: Tesla M60
**Nvidia Driver Version**: 418.87.00
**CUDA Version**: 11.0
**CUDNN Version**: 8.0.4
**Operating System + Version**: Ubuntu 18..04.5
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: NA
**PyTorch Version (if applicable)**: 1.6.0
**Baremetal or Container (which commit + image + tag)**: nvcr.io/nvidia/tensorrt:20.09-py3 (nvcr.io/nvidia/tensorrt@sha256:af35aa6b82c40e659d34c33596996221ec05f8cb4d7dbcd5a8a501d351db2dbd)

**Comment by ttyio** [comment]
Hello @gabepack , thanks for reporting issue
From you attached sub-model, it only change the input shape from `(1, 256)` to `(256, 1)`, right? I cannot see any issues here.
Could you share us with the failed model for debug? thanks

**Comment by gabepack** [comment]
Hi @ttyio, thanks for your response. I'm not sure if the sub-model is changing the input shape from `(1, 256)` to `(256, 1)`. I'm fairly new to debugging these models, so you could very well be correct regarding this.

Since the trained version of our model is proprietary, I'm sharing with you the same model but trained only on 1 epoch of STSb. This is a T5 model that's been converted from PyTorch to ONNX, so it's rather large (~4.6GB). It also exhibits the same `index to gather must not exceed length of vector` failure. You can download it from https://casetext-gabe.s3-us-west-2.amazonaws.com/generic_t5_3sts.tar.

Also, here's the Python 3 script I'm using in my attempt to convert from ONNX to TensorRT.

```
import os

import tensorrt

log = tensorrt.Logger(tensorrt.Logger.WARNING)
with tensorrt.Builder(log) as factory:
    with factory.create_network(1 << int(tensorrt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)) as model:
        with tensorrt.OnnxParser(model, log) as parser:
            model_path = os.path.join('generic_t5_3sts', 'model.onnx')
            if parser.parse_from_file(model_path):
                message = 'Parsed ONNX model at %s.' % model_path
            else:
                message = 'Could not parse ONNX model at %s.' % model_path
            print(message)
            for error in range(parser.num_errors):
                print(parser.get_error(error))
            for model_input in range(model.num_inputs):
                model_input = model.get_input(model_input)
                print('input %s' % model_input.name)
                print('    shape %s' % model_input.shape)
                print('    type %s' % model_input.dtype)
            for model_output in range(model.num_outputs):
                model_output = model.get_output(model_output)
                print('output %s' % model_output.name)
                print('    shape %s' % model_output.shape)
                print('    type %s' % model_output.dtype)
            for layer in range(model.num_layers):
                layer = model.get_layer(layer)
                print('layer %s' % layer.name)
                print('    type %s' % layer.type)
                print('    precision %s' % layer.precision)
                for layer_input in range(layer.num_inputs):
                    layer_input = layer.get_input(layer_input)
                    if layer_input is None:
                        print('    input NONE')
                    else:
                        print('    input %s' % layer_input.name)
                        print('        shape %s' % layer_input.shape)
                        print('        type %s' % layer_input.dtype)
                for layer_output in range(layer.num_outputs):
                    layer_output = layer.get_output(layer_output)
                    print('    output %s' % layer_output.name)
                    print('        shape %s' % layer_output.shape)
                    print('        type %s' % layer_output.dtype)
        with factory.create_builder_config() as conf:
            conf.max_workspace_size = 1 << 32
            profile = factory.create_optimization_profile()
            profile.set_shape('input_ids', (1, 256), (1, 256), (1, 256))
            profile.set_shape('attention_mask', (1, 256), (1, 256), (1, 256))
            profile.set_shape('token_weights', (1, 256), (1, 256), (1, 256))
            conf.add_optimization_profile(profile)
            with factory.build_engine(model, conf) as engine:
                trt_path = 'g3s.xlarge_generic_t5_3sts.trt'
                with open(trt_path, 'wb') as stream:
                    stream.write(engine.serialize())
                print('Saved TensorRT engine to %s.' % trt_path)
```

**Comment by ttyio** [comment]
thanks @gabepack for sharing the model, I have tried it works with TRT 7.2, my bad, I should suggest you to try 7.2 first. 
Could you also try 7.2? thanks!

**Comment by gabepack** [comment]
Ah, ok, thanks @ttyio, I'll try to get TRT 7.2 working with it and let you know how I fare.

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!
