### ISSUE TITLE
Cannot run global average pool on an input with dynamic spatial dimensions

### ISSUE THREAD

**Issue by GY0913** [NVIDIA/TensorRT#829]
when I export my model to  onnx file and try to parse the onnx network,I got this error:
Assertion failed: !isDynamic(kernelSize) && "Cannot run global average pool on an input with dynamic spatial dimensions!"
environment：
pytorch 1.5
trt：TensorRT-7.0.0.11
cuda：10.2

**Comment by ttyio** [comment]
@GY0913 , thanks for reporting.
Could you try latest 7.2 release? thanks!

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!
