### ISSUE TITLE
upgrading from tensorrt 7.1.0 to 7.1.3

### ISSUE THREAD

**Issue by iemanjohary** [NVIDIA/TensorRT#830]
## Description

I developed a plugin in tensorrt version 7.1.0 and it was working great without any problem the engine was refittable and almost every minute i refite it. now I upgraded my tensorrt to 7.1.3 and the same code without any change taking inference witout any problem but after reffing the engine when taking inference it shows this error and abort.

terminate called without an active exception
Aborted (core dumped)

I must say the boolean that refitter passes is true and it seems there is no problem with refitting  but after refitting it dosent take inference any more. and I created engine with kfp16 and kSTRICT_TYPES flags 

## Environment

**TensorRT Version**: 7.1.3
**GPU Type**: jetson tx2
**jetpack Version**: 4.4 
**Python Version (if applicable)**: 3.6.9

**Comment by ttyio** [comment]
Hello @iemanjohary , thanks for reporting.
Could you provide a repro for us for debugging? thanks!

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!
