### ISSUE TITLE
onnx convert error

### ISSUE THREAD

**Issue by bladesaber** [NVIDIA/TensorRT#832]
## Description

[TensorRT] ERROR: (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
In node 1 (importBatchNormalization): INVALID_NODE: Assertion failed: scale_weights.shape == weights_shape
Number of errors: 1
Description of the error: Assertion failed: scale_weights.shape == weights_shape
Line where the error occurred: 695
Error code: INVALID_NODE
Model was not parsed successfully
double free or corruption (!prev)

## Environment

**TensorRT Version**:  6.0.1.5
**GPU Type**:  GTX1660 TI
**Nvidia Driver Version**:  nvidia-435
**CUDA Version**: CUDA10.0
**CUDNN Version**: Cudnn 7.6.5
**Operating System + Version**:  ubuntu 18.0.4
**Python Version (if applicable)**: 3.7.8
**TensorFlow Version (if applicable)**: None
**PyTorch Version (if applicable)**: 1.6
**Baremetal or Container (which commit + image + tag)**: 

## Relevant Files

the code I use:
def ONNX_build_engine(trt_model_name, onnx_model_name, batch_size=1):
    logger = logging.getLogger(__name__)
    TRT_LOGGER = trt.Logger()
    explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)  # trt7
    with trt.Builder(TRT_LOGGER) as builder, \
            builder.create_network(explicit_batch) as network, \
            trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_batch_size = batchsize
        builder.max_workspace_size = 2 << 30
        print('Loading ONNX file from path {}...'.format(onnx_model_name))
        with open(onnx_model_name, 'rb') as model:
            print('Beginning ONNX file parsing')
            if not parser.parse(model.read()):
                for error in range(parser.num_errors):
                    print(parser.get_error(error))
        if parser.num_errors == 0:
            print('Completed parsing of ONNX file')
            print('Building an engine from file {}; this may take a while...'.format(onnx_model_name))

            ####
            # builder.int8_mode = True
            # builder.int8_calibrator = calib
            if fp16:
                builder.fp16_mode = True
            ####
            print("num layers:", network.num_layers)
            # last_layer = network.get_layer(network.num_layers - 1)
            # if not last_layer.get_output(0):
            #  network.mark_output(network.get_layer(network.num_layers - 1).get_output(0))
            network.get_input(0).shape = [batchsize, 3, 550, 550]  # trt7
            # network.get_input(1).shape = [batchsize, 1, maxinputlen]#trt7
            # print(network.get_input(0).name, network.get_input(1).name)
            # print(network.get_output(0).name, network.get_output(1).name)
            engine = builder.build_cuda_engine(network)
            print("engine:", engine)
            if engine is not None:
                print("Completed creating Engine")
                with open(trt_model_name, "wb") as f:
                    f.write(engine.serialize())
                return engine
        else:
            print('Number of errors: {}'.format(parser.num_errors))
            for i in range(parser.num_errors):
                error = parser.get_error(i)  # if it gets mnore than one error this have to be changed
                desc = error.desc()
                line = error.line()
                code = error.code()
                print('Description of the error: {}'.format(desc))
                print('Line where the error occurred: {}'.format(line))
                print('Error code: {}'.format(code))
            print("Model was not parsed successfully")

ONNX_build_engine('./yolact.trt', './yolact.onnx', batch_size=1)

**Comment by bladesaber** [comment]
Please someone give me help, :)

**Comment by pranavm-nvidia** [comment]
Can you try this with a newer version of TensorRT?

**Comment by lifei1229** [comment]
> Please someone give me help, :)

so, have you solved it now?
