### ISSUE TITLE
INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName) in tensorrt 7.0.0.11

### ISSUE THREAD

**Issue by bladesaber** [NVIDIA/TensorRT#833]
## Description

INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)

with strange Warning: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32. 

I believe my onnx exported by pytorch..onnx.export is based on float32

## Environment

**TensorRT Version**:  7.0.0.11
**GPU Type**: GTX1660TI
**Nvidia Driver Version**: nvidia-435
**CUDA Version**: cuda10.0
**CUDNN Version**: cudnn7.6.5
**Operating System + Version**:ubuntu 18.0.4 
**Python Version (if applicable)**:  3.7.8
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.4
**Baremetal or Container (which commit + image + tag)**: 

## Relevant Files

code I use:

logger = logging.getLogger(__name__)
    TRT_LOGGER = trt.Logger()
    explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)  # trt7
    with trt.Builder(TRT_LOGGER) as builder, \
            builder.create_network(explicit_batch) as network, \
            trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_batch_size = batchsize
        builder.max_workspace_size = 2 << 30
        print('Loading ONNX file from path {}...'.format(onnx_model_name))
        with open(onnx_model_name, 'rb') as model:
            print('Beginning ONNX file parsing')
            if not parser.parse(model.read()):
                for error in range(parser.num_errors):
                    print(parser.get_error(error))
        if parser.num_errors == 0:
            print('Completed parsing of ONNX file')
            print('Building an engine from file {}; this may take a while...'.format(onnx_model_name))

            ####
            # builder.int8_mode = True
            # builder.int8_calibrator = calib
            if fp16:
                builder.fp16_mode = True
            ####
            print("num layers:", network.num_layers)
            # last_layer = network.get_layer(network.num_layers - 1)
            # if not last_layer.get_output(0):
            #  network.mark_output(network.get_layer(network.num_layers - 1).get_output(0))
            network.get_input(0).shape = [batchsize, 3, 550, 550]  # trt7
            # network.get_input(1).shape = [batchsize, 1, maxinputlen]#trt7
            # print(network.get_input(0).name, network.get_input(1).name)
            # print(network.get_output(0).name, network.get_output(1).name)
            engine = builder.build_cuda_engine(network)
            print("engine:", engine)
            if engine is not None:
                print("Completed creating Engine")
                with open(trt_model_name, "wb") as f:
                    f.write(engine.serialize())
                return engine
        else:
            print('Number of errors: {}'.format(parser.num_errors))
            for i in range(parser.num_errors):
                error = parser.get_error(i)  # if it gets mnore than one error this have to be changed
                desc = error.desc()
                line = error.line()
                code = error.code()
                print('Description of the error: {}'.format(desc))
                print('Line where the error occurred: {}'.format(line))
                print('Error code: {}'.format(code))
            print("Model was not parsed successfully")

**Comment by pranavm-nvidia** [comment]
This should be fixed in 7.1 and newer

**Comment by bladesaber** [comment]
Thanks for your response, I will try version 7.1 . Newer Tensorrt need high CUDA, Hoping CUDA 10.0 and 10.1 will be supported in the coming future. ^_^
