### ISSUE TITLE
Core dump with Bert inference on Tesla-P4

### ISSUE THREAD

**Issue by ZhangChuann** [NVIDIA/TensorRT#837]
## Description
I can run "python build.py" correctly, and generate "bert_base_128.engine" sucessful.

but during run： python3 inference.py -e /workspace/TensorRT/demo/BERT/engines/bert_base_128.engine -p "TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs. It includes parsers to import models, and plugins to support novel ops and layers before applying optimizations for inference. Today NVIDIA is open-sourcing parsers and plugins in TensorRT so that the deep learning community can customize and extend these components to take advantage of powerful TensorRT optimizations for your apps." -q "What is TensorRT?" -v /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_v2_base_fp32_128_v2/vocab.txt

I get below result :

root@7eadbe4ccd8d:/workspace/TensorRT/demo/BERT# python3 inference.py -e /workspace/TensorRT/demo/BERT/engines/bert_base_128.engine -p "TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs. It includes parsers to import models, and plugins to support novel ops and layers before applying optimizations for inference. Today NVIDIA is open-sourcing parsers and plugins in TensorRT so that the deep learning community can customize and extend these components to take advantage of powerful TensorRT optimizations for your apps." -q "What is TensorRT?" -v /workspace/TensorRT/demo/BERT/models/fine-tuned/bert_tf_v2_base_fp32_128_v2/vocab.txt

Passage: TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs. It includes parsers to import models, and plugins to support novel ops and layers before applying optimizations for inference. Today NVIDIA is open-sourcing parsers and plugins in TensorRT so that the deep learning community can customize and extend these components to take advantage of powerful TensorRT optimizations for your apps.

Question: What is TensorRT?
Aborted (core dumped)

## Environment

**TensorRT Version:  docker: nvcr.io/nvidia/tensorrt:20.09-py3
**GPU Type:  Tesla P4
**Nvidia Driver Version:  440.64.00
**CUDA Version**:  11.0
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files
![image](https://user-images.githubusercontent.com/10493733/96713951-07d00580-13d4-11eb-851c-5e0af58dd08d.png)

**Comment by ZhangChuann** [comment]
who can help me? thanks

**Comment by mk-nvidia** [comment]
@ZhangChuann Thanks for reporting this issue. We're taking a look.

**Comment by ZhangChuann** [comment]
Thanks. If you have some progress or question, please make me known.

**Comment by ttyio** [comment]
Hello @ZhangChuann , thanks for reporting.

Could you try `nvcr.io/nvidia/tensorrt:20.10-py3`(TensorRT 7.2.1) ? We have some fix for BERT, more detail in https://github.com/NVIDIA/TensorRT/issues/726#issuecomment-716247157, thanks!

**Comment by ZhangChuann** [comment]
@ttyio ，I will try it soon and give you my feedback.

**Comment by ZhangChuann** [comment]
@ttyio , when I try inference_c.py (alse on tensorrt:20.09-py3 and 20.10-py3 is trying), I came across core dumped similary. And I run in gdb mode: 
gdb --args python3 inference_c_debug.py -e $TRT_SOURCE/demo/BERT/engines/bert_base_128.engine -p "TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs." -q "What is TensorRT?" -v $TRT_SOURCE/demo/BERT/models/fine-tuned/bert_tf_v2_base_fp32_128_v2/vocab.txt

and the backtrace is as follow: (Wish it can give you some clues)
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a248b1 in __GI_abort () at abort.c:79
#2  0x00007fffd84a8c6a in int bert::embSkipLayerNorm<float>(CUstream_st*, int, int, int, int const*, int const*, float const*, float const*, float const*, float const*, float const*, float*) ()
   from /workspace/TensorRT_REPO/TensorRT/build/out/libnvinfer_plugin.so.7
#3  0x00007fffd8460713 in bert::EmbLayerNormPluginDynamic::enqueue(nvinfer1::PluginTensorDesc const*, nvinfer1::PluginTensorDesc const*, void const* const*, void* const*, void*, CUstream_st*) ()
   from /workspace/TensorRT_REPO/TensorRT/build/out/libnvinfer_plugin.so.7
#4  0x00007fffd9f36922 in nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute(nvinfer1::rt::CommonContext const&, nvinfer1::rt::ExecutionParameters const&) const () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.7
#5  0x00007fffd9eb8bf8 in nvinfer1::rt::ExecutionContext::enqueueInternal(CUevent_st**) ()
   from /usr/lib/x86_64-linux-gnu/libnvinfer.so.7
#6  0x00007fffd9ebb5d4 in nvinfer1::rt::ExecutionContext::enqueueV2(void**, CUstream_st*, CUevent_st**) ()
   from /usr/lib/x86_64-linux-gnu/libnvinfer.so.7
#7  0x00007ffff2a1edde in BertInference::run (this=0x1037600, inputBuffers=0x1230000, warmUps=0, iterations=1)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/infer_c/bert_infer.h:261
#8  0x00007ffff2a1f173 in BertInference::run (this=0x1037600, inputIds=0x218f1bb0, segmentIds=0x24e0a980, 
    inputMask=0x22e50450, warmUps=0, iterations=1)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/infer_c/bert_infer.h:293
#9  0x00007ffff2a2d8af in BertInferenceRunner::run (this=0x1037600, inputIds=..., segmentIds=..., inputMask=...)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/infer_c/infer_c.cpp:43
#10 0x00007ffff2a3a691 in pybind11::cpp_function::cpp_function<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}::operator()(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>) const (
    __closure=0x11f7058, c=0x1037600, args#0=..., args#1=..., args#2=...)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/build/_deps/pybind11-src/include/pybind11/pybind11.h:72
#11 0x00007ffff2a4d579 in pybind11::detail::argument_loader<BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16> >::call_impl<pybind11::array_t<float, 16>, pybind11::cpp_function::cpp_function<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}&, 0ul, 1ul, 2ul, 3ul, pybind11::detail::void_type>(pybind11::cpp_function::cpp_function<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}&, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul>, pybind11::detail::void_type&&) (this=0x7fffffffd300, f=...)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/build/_deps/pybind11-src/include/pybind11/cast.h:1870
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffff2a481d1 in pybind11::detail::argument_loader<BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16> >::call<pybind11::array_t<float, 16>, pybind11::detail::void_type, pybind11::cpp_function::cpp_function<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}&>(pybind11::cpp_function::cpp_function<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}&) && (this=0x7fffffffd300, f=...)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/build/_deps/pybind11-src/include/pybind11/cast.h:1847
#13 0x00007ffff2a41c5d in void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}, pybind11::array_t<float, 16>, BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}&&, pybind11::array_t<float, 16> (*)(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const (__closure=0x0, call=...)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/build/_deps/pybind11-src/include/pybind11/pybind11.h:154
#14 0x00007ffff2a42002 in void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}, pybind11::array_t<float, 16>, BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<pybind11::array_t<float, 16>, BertInferenceRunner, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::array_t<float, 16> (BertInferenceRunner::*)(pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>)#1}&&, pybind11::array_t<float, 16> (*)(BertInferenceRunner*, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>, pybind11::array_t<int, 16>), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detai---Type <return> to continue, or q <return> to quit---
l::function_call) () at /workspace/TensorRT_REPO/TensorRT/demo/BERT/build/_deps/pybind11-src/include/pybind11/pybind11.h:132
#15 0x00007ffff2a2a966 in pybind11::cpp_function::dispatcher (self=<PyCapsule at remote 0x7ffff2d5e750>, 
    args_in=(<infer_c.bert_inf at remote 0x7ffff2d0af48>, <numpy.ndarray at remote 0x7fffc3244170>, <numpy.ndarray at remote 0x7fffc32441c0>, <numpy.ndarray at remote 0x7fffc3244210>), kwargs_in=0x0)
    at /workspace/TensorRT_REPO/TensorRT/demo/BERT/build/_deps/pybind11-src/include/pybind11/pybind11.h:627
#16 0x0000000000566ddc in _PyCFunction_FastCallDict () at ../Objects/methodobject.c:231
#17 0x000000000050a783 in call_function.lto_priv () at ../Python/ceval.c:4875
#18 0x000000000050c1f4 in _PyEval_EvalFrameDefault () at ../Python/ceval.c:3335
#19 0x0000000000509918 in PyEval_EvalFrameEx (throwflag=0, 
    f=Frame 0x24d570d8, for file inference_c_debug.py, line 148, in inference (features=[<Feature at remote 0x7ffff2d59c10>], tokens=['TensorRT', 'is', 'a', 'high', 'performance', 'deep', 'learning', 'inference', 'platform', 'that', 'delivers', 'low', 'latency', 'and', 'high', 'throughput', 'for', 'apps', 'such', 'as', 'recommenders,', 'speech', 'and', 'image/video', 'on', 'NVIDIA', 'GPUs.'], _NetworkOutput=<type at remote 0x24e0bbf8>, networkOutputs=[], eval_time_elapsed=0, feature_index=0, feature=<...>, input_ids=<numpy.ndarray at remote 0x7fffc3244170>, segment_ids=<numpy.ndarray at remote 0x7fffc32441c0>, input_mask=<numpy.ndarray at remote 0x7fffc3244210>, eval_start_time=<float at remote 0x7ffff30ac5e8>)) at ../Python/ceval.c:754
#20 _PyFunction_FastCall (globals=<optimized out>, nargs=617967832, args=<optimized out>, co=<optimized out>) at ../Python/ceval.c:4933
#21 fast_function.lto_priv () at ../Python/ceval.c:4968
#22 0x000000000050a64d in call_function.lto_priv () at ../Python/ceval.c:4872
#23 0x000000000050c1f4 in _PyEval_EvalFrameDefault () at ../Python/ceval.c:3335
#24 0x0000000000507f24 in PyEval_EvalFrameEx (throwflag=0, f=Frame 0xae0858, for file inference_c_debug.py, line 211, in <module> ())
    at ../Python/ceval.c:754
#25 _PyEval_EvalCodeWithName.lto_priv.1836 () at ../Python/ceval.c:4166
#26 0x000000000050b053 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, 
    locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4187
#27 PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:731
#28 0x0000000000634dd2 in run_mod () at ../Python/pythonrun.c:1025
#29 0x0000000000634e87 in PyRun_FileExFlags () at ../Python/pythonrun.c:978
#30 0x000000000063863f in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:419
#31 0x0000000000638815 in PyRun_AnyFileExFlags () at ../Python/pythonrun.c:81
#32 0x00000000006391e1 in run_file (p_cf=0x7fffffffdcdc, filename=<optimized out>, fp=<optimized out>) at ../Modules/main.c:340
#33 Py_Main () at ../Modules/main.c:810
#34 0x00000000004b0dc0 in main (argc=10, argv=0x7fffffffded8) at ../Programs/python.c:69
(gdb) 
(gdb) py-bt
Traceback (most recent call first):
  <built-in method run of PyCapsule object at remote 0x7ffff2d5e750>
  File "inference_c_debug.py", line 148, in inference
    h_output = bert.run(input_ids, segment_ids, input_mask)
  File "inference_c_debug.py", line 211, in <module>
    eval_time_elapsed, prediction, nbest_json = inference(features, doc_tokens)

**Comment by ZhangChuann** [comment]
> @ttyio ，I will try it soon and give you my feedback. Besides, which TensorRT code branch should I use? master or latest release branch?

OK，I think I should use Tag7.2.1 of TensorRT repo.

**Comment by ttyio** [comment]
> > @ttyio ，I will try it soon and give you my feedback. Besides, which TensorRT code branch should I use? master or latest release branch?
> 
> OK，I think I should use Tag7.2.1 of TensorRT repo.

Yes, please try 7.2.1, thanks!

**Comment by ZhangChuann** [comment]
@ttyio , very cool. It is sucessful at nvcr.io/nvidia/tensorrt:20.10-py3(TensorRT 7.2.1) . And I got the correct result. (Thank you.)
root@TENCENT64:/workspace/TensorRT_REPO/TensorRT-7.2.1/demo/BERT# CUDA_VISIBLE_DEVICES=1 python3 inference.py -e $TRT_SOURCE/demo/BERT/engines/bert_base_128.engine -p "TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs. It includes parsers to import models, and plugins to support novel ops and layers before applying optimizations for inference. Today NVIDIA is open-sourcing parsers and plugins in TensorRT so that the deep learning community can customize and extend these components to take advantage of powerful TensorRT optimizations for your apps." -q "What is TensorRT?" -v $TRT_SOURCE/demo/BERT/models/fine-tuned/bert_tf_v2_base_fp32_128_v2/vocab.txt

Passage: TensorRT is a high performance deep learning inference platform that delivers low latency and high throughput for apps such as recommenders, speech and image/video on NVIDIA GPUs. It includes parsers to import models, and plugins to support novel ops and layers before applying optimizations for inference. Today NVIDIA is open-sourcing parsers and plugins in TensorRT so that the deep learning community can customize and extend these components to take advantage of powerful TensorRT optimizations for your apps.

Question: What is TensorRT?
------------------------
Running inference in 76.339 Sentences/Sec
------------------------
Answer: 'a high performance deep learning inference platform'
With probability: 36.313
