### ISSUE TITLE
ctx->tensors().count(inputName)

### ISSUE THREAD

**Issue by bladesaber** [NVIDIA/TensorRT#838]
I really need help

## Description

I have install tensorrt oss, but it still report the error.

trtexec  --onnx=test.onnx --saveEngine=ttt.trt

it output:
ctx->tensors().count(inputName)

and when I use onnx-simplifier
it output:
Assertion failed: convertOnnxWeights(initializer, &weights, ctx)

## Environment

**TensorRT Version**:  7.0.0.11
**GPU Type**: GTX1660Ti
**Nvidia Driver Version**: nvidia-435
**CUDA Version**: 10.0
**CUDNN Version**: 7.6
**Operating System + Version**: ubuntu 18.0.4 
**Python Version (if applicable)**: 3.7.8
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by pranavm-nvidia** [comment]
This was fixed in 7.1

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!
