### ISSUE TITLE
 Models which have the same speed in PyTorch have very different speed in tRT

### ISSUE THREAD

**Issue by Bilal-Yousaf** [NVIDIA/TensorRT#839]
## Description

Models which have the same speed in PyTorch have very different speed in tRT, whereas they have simillar layers.

## Environment

**TensorRT Version**: 7.1.3
**GPU Type**: RTX 2070 Super
**Nvidia Driver Version**: 450.66
**CUDA Version**: 11.0
**CUDNN Version**: 
**Operating System + Version**: Ubunu 20.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.5.0
**Baremetal or Container (if container which image + tag)**: container

## Relevant Files

I have attached links to two models here:

1. [fast_pytorch_slow_trt.onnx](https://drive.google.com/file/d/1t2zrS8JkVlEXo028h20oSFi7wuLdBGmp/view?usp=sharing)
2. [slow_pytorch_fast_trt.onnx](https://drive.google.com/file/d/1jqEU7obxq-N1PhoP1hLJOJWHR7zPgIqk/view?usp=sharing)

These models are trained in PyTorch and converted to onnx using torch.onnx.export function and then simplified using [onnx-simplifier](https://github.com/daquexian/onnx-simplifier).

## Steps To Reproduce

Run trtexec --onnx=<onn file path> --saveEngine=<output file path> --verbose command to generate trt engine and the inference time reported by this command after conversion is noted which shows that fast_pytorch_slow_trt runs at 98 FPS and slow_pytorch_fast_trt 149 FPS, whereas in PyTorch they have nearly same FPS.

**Comment by ttyio** [comment]
Hello @Bilal-Yousaf , sorry for the delay response, I see the links are broken, could you share the onnx again? thanks!

**Comment by ttyio** [comment]
Closing since now activity for more than 3 weeks, please reopen if you still have question, thanks!
