### ISSUE TITLE
does trt support the ceil_mode for maxpool2d?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [NVIDIA/TensorRT#84]
i convert the pytorch model which use `ceil_mode` in `maxpool2d` to onnx and it works. and when i convert onnx model to trt model, it still works. but when i run the trt model, it fails to get the right shape because the `ceil_mode` does not work correctly.
any help is appreciated!

**Comment by DilipSequeira** [comment]
It should correspond to TensorRT's PaddingMode::kEXPLICIT_ROUND_UP mode. 

Sounds like a bug. It would be helpful if you can provide the input size you're using and the output size you're expecting.

**Comment by rmccorm4** [comment]
Closing since no response. Feel free to open a new issue or ask to have this one re-opened.
