### ISSUE TITLE
ONNX does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by AD2605** [NVIDIA/TensorRT#841]
Hello all. 
I am trying to build the latest release from source. However while running the cmake command I get the following error - 
```
/home/atharva/Downloads/TensorRT-20.10/parsers/onnx

  does not contain a CMakeLists.txt file.
```
Could anyone help me with this please ?

**Comment by MuhammadAsadJaved** [comment]
> Hello all.
> I am trying to build the latest release from source. However while running the cmake command I get the following error -
> 
> ```
> /home/atharva/Downloads/TensorRT-20.10/parsers/onnx
> 
>   does not contain a CMakeLists.txt file.
> ```
> 
> Could anyone help me with this please ?

@AD2605  It's not in the parsers, it's in the samples. 

Try this 

```
$ cd /home/atharva/Downloads/TensorRT-20.10/samples/opensource/trtexec/
$ sudo make
```

**Comment by MuhammadAsadJaved** [comment]
> Hello all.
> I am trying to build the latest release from source. However while running the cmake command I get the following error -
> 
> ```
> /home/atharva/Downloads/TensorRT-20.10/parsers/onnx
> 
>   does not contain a CMakeLists.txt file.
> ```
> 
> Could anyone help me with this please ?

@AD2605  Have you cloned the repo  --recursive? 

```
git clone -b master https://github.com/nvidia/TensorRT TensorRT
cd TensorRT
git submodule update --init --recursive
export TRT_SOURCE=`pwd`
```

**Comment by AD2605** [comment]
Hi, @MuhammadAsadJaved Thanks for replying. 
I will try out what you suggested. I actually just went on GitHub and downloaded the master as zip. 
Also, `/home/atharva/Downloads/TensorRT-20.10/parsers/onnx` is empty upon extracting the zip.

**Comment by mk-nvidia** [comment]
@AD2605 as @MuhammadAsadJaved pointed out, you're missing the submodule. Unfortunately GitHub doesn't provide a way of getting the submodule when you download a zip (see [here](https://stackoverflow.com/questions/12936014/include-a-github-submodule-automatically-in-download)). Please clone the repo using git.
