### ISSUE TITLE
machine-learning repo is broken after TRT 7.2.1 update

### ISSUE THREAD

**Issue by xkszltl** [NVIDIA/TensorRT#844]
## Description

We're trying to get the latest trt but hit this issue.
As you can see `curl -sSL 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/'` incorrectly return the dir of `ubuntu1804`, not `x86_64`.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/5203025/97062845-58f81900-15cf-11eb-998a-e5f973acb278.png">

I also tried the browser, with cache it's correct:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/5203025/97062984-e471aa00-15cf-11eb-825c-f2ebd8db905e.png">
But with InPrivate mode, it's wrong:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/5203025/97062986-f18e9900-15cf-11eb-93cc-1b3c20a7d92f.png">

**Comment by xkszltl** [comment]
Note that I tried it both in US/China nodes (301 to .cn domain), both have the same behavior, indicating this may be a large scope CDN bug.

**Comment by xkszltl** [comment]
I also tried clicking x86_64 button in Safari InPrivate mode (i.e. no cache):
  - From a wrong `https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64/`, I got 404 of `https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64/x86_64/` (doubled dir)
  - From `https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/` I randomly get correct or wrong `x86_64` dir.

**Comment by ttyio** [comment]
Hello @xkszltl , thanks for reporting
Could you try if the service is recovered now?

**Comment by xkszltl** [comment]
US response seems good with a few curl, will do more tests to confirm.
China response is still bad.

**Comment by xkszltl** [comment]
By "bad" I mean randomly among:
- Normal response
- Wrong dir as described above
- A single line of `Failed to ssl_handshake: closed` (This is from http body, not a curl error msg).
    * <img width="1792" alt="image" src="https://user-images.githubusercontent.com/5203025/97192175-a26c8200-17e2-11eb-931f-99bcd977a197.png">
- 504 Gateway timeout
- ...

**Comment by xkszltl** [comment]
No, US service is still broken.
Running `curl -sSL 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64'` result in partial response:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/5203025/97260640-2ad93a00-1858-11eb-962b-5e432ed6c03a.png">

```
    <li>
      <span class='file'><a href='libnccl2_2.6.4-1+cuda10.1_amd64.deb'>libnccl2_2.6.4-1+cuda10.1_amd64.deb</a></span>
      <span class='size'>24MB</span>
      <span class='date'>2020-03-23 16:53</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.6.4-1+cuda10.2_amd64.deb'>libnccl2_2.6.4-1+cuda10.2_amd64.deb</a></span>
      <span class='size'>26MB</span>
      <span class='date'>2020-03-23 16:53</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.7.3-1+cuda10.1_amd64.deb'>libnccl2_2.7.3-1+cuda10.1_amd64.deb</a></span>
      <span class='size'>24MB</span>
      <span class='date'>2020-05-20 17:51</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.7.3-1+cuda10.2_amd64.deb'>libnccl2_2.7.3-1+cuda10.2_amd64.deb</a></span>
      <span class='size'>26MB</span>
      <span class='date'>2020-05-20 17:51</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.7.3-1+cuda11.0_amd64.deb'>libnccl2_2.7.3-1+cuda11.0_amd64.deb</a></span>
      <span class='size'>34MB</span>
      <span class='date'>2020-05-20 17:51</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.7.5-1+cuda10.1_amd64.deb'>libnccl2_2.7.5-1+cuda10.1_amd64.deb</a></span>
      <span class='size'>24MB</span>
      <span class='date'>2020-06-24 17:51</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.7.5-1+cuda10.2_amd64.deb'>libnccl2_2.7.5-1+cuda10.2_amd64.deb</a></span>
      <span class='size'>26MB</span>
      <span class='date'>2020-06-24 17:51</span>
    </li>
    <li>
      <span class='file'><a href='libnccl2_2.7.5-1+cuda11.0_amd64.deb'>libnccl2_2.7.5-1+cuda11.0_amd64.deb</a></span> 
```

You can see the last returned block of `<li>`, and everything after, is truncated.

**Comment by xkszltl** [comment]
More specifically, we have a workflow that wants to download `nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb`.
Because we don't know its exact name (don't want to hard-code version), we curl the dir and do some grep/sed to figure out.
It doesn't work recently and we realized the response is truncated.

**Comment by ttyio** [comment]
Thanks @xkszltl , I have reported internally to track the issue.

**Comment by zeroepoch** [comment]
@xkszltl can you try now. There were some known issues with the download page by mistake when TRT 7.2.1 was launched. It might take some time for these changes to propagate to all mirrors. Both the incorrect listing and the partial listing were issues we were aware of that are now resolved.

**Comment by xkszltl** [comment]
Thanks!
Currently I'm seeing good result in China (but not always), still truncated in US.
Will keep checking.

**Comment by xkszltl** [comment]
Still stably seeing truncated result in US (accessing from multiple nodes in Azure's West US 2 region)

**Comment by xkszltl** [comment]
Interesting.
I found the truncated issue is limited to the combination of ubuntu1804 and HTTPS.
HTTP/ubuntu1604/rhel7 responses all look good.

**Comment by xkszltl** [comment]
This command shows the availability of version `7.2.1` from Azure WestUS2 machine.
Note the special line of `https com ubuntu1804: 0`

```
for protocol in http{,s}; do for site in com cn; do for dist in ubuntu{14,16,18,20}04 rhel{7,8}; do curl -sSL "$protocol://developer.download.nvidia.$site/compute/machine-learning/repos/$dist/x86_64/" | grep 7.2.1 | wc -l | sed "s/^/$protocol $site $dist: /"; done; done; done
```
<img width="175" alt="image" src="https://user-images.githubusercontent.com/5203025/97707900-ef0dd100-1af2-11eb-9c7c-9f1f140adc2f.png">

**Comment by zeroepoch** [comment]
There is definitely something going on with the mirroring. Here in San Jose I see:
```
$ for protocol in http{,s}; do for site in com cn; do for dist in ubuntu{14,16,18,20}04 rhel{7,8}; do curl -sSL "$protocol://developer.download.nvidia.$site/compute/machine-learning/repos/$dist/x86_64/" | grep 7.2.1 | wc -l | sed "s/^/$protocol $site $dist: /"; done; done; done
http com ubuntu1404: 6
http com ubuntu1604: 42
http com ubuntu1804: 36
http com ubuntu2004: 0
http com rhel7: 36
http com rhel8: 0
http cn ubuntu1404: 6
http cn ubuntu1604: 42
http cn ubuntu1804: 36
http cn ubuntu2004: 0
http cn rhel7: 36
http cn rhel8: 0
https com ubuntu1404: 6
https com ubuntu1604: 42
https com ubuntu1804: 36
https com ubuntu2004: 0
https com rhel7: 36
https com rhel8: 0
https cn ubuntu1404: 6
https cn ubuntu1604: 42
https cn ubuntu1804: 36
https cn ubuntu2004: 0
https cn rhel7: 36
https cn rhel8: 0
```

**Comment by xkszltl** [comment]
Start to get good result in our recent test

**Comment by zeroepoch** [comment]
Can we close this issue or is the problem still happening?

**Comment by xkszltl** [comment]
I think it's can be closed.
I'm still seeing unstable result in China but maybe I can wrap it with some aggressive retrying loop.
