### ISSUE TITLE
sampleOnnxMNIST

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [NVIDIA/TensorRT#845]
Many developers have problems when using tensorrt7 to load the onnx model for multi batch prediction. The official example does not give any useful information after the updated version. I hope to change it to multi batch processing and release it to an example,I hope it works as well as 5.1.5 .

**Comment by ttyio** [comment]
Hello @CallmeZhangChenchen , 
sorry for the lack of samples. Now we have plan to improve the document and samples, before that, could you read `trtexec` source code https://github.com/NVIDIA/TensorRT/tree/release/7.2/samples/opensource/trtexec,  it supports option `--minShapes, --optShapes, --maxShapes` that update the dynamic dimensions in the onnx model.
Thanks!

**Comment by CallmeZhangChenchen** [comment]
OK, I've implemented it in C + +, but it's a bit difficult without examples
