### ISSUE TITLE
how can I Use trtexec Loadinputs 

### ISSUE THREAD

**Issue by asmasaad** [NVIDIA/TensorRT#850]
Hello All,

it is not mentioned in any doc, How can we use LoadInputs what is the format needed?

/usr/src/tensorrt/bin/trtexec --onnx=[model] --loadInputs=[input]

**Comment by ttyio** [comment]
Hello @asmasaad , thanks for reporting
loadInputs works like this:
> --loadInputs='input_ids':id.bin,'input_mask':mask.bin,'segment_ids':segment.bin
Here the `input_ids`, `input_mask` and `segment_ids` are the inputs names,  and the `*.bin` are raw binary encoded files. e.g, for each float32 values, they encoded into 4bytes, 4bytes, 4 bytes...

**Comment by ttyio** [comment]
I will close this since no response in more than 3 weeks, please reopen if you still see issue, thanks!

**Comment by silverlining21** [comment]
Hi @ttyio ,could provide any sample data format about` -loadInputs`, description about it seems little confusing.

**Comment by ttyio** [comment]
Hello @silverlining21 , we just copy the whole data from host to device, see https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L448

So they are just raw bytes of the network input.

**Comment by silverlining21** [comment]
Got it, thanks.

**Comment by sonersec** [comment]
@ttyio Can you plese send me an example of loadInputs parameter. I can't do it.

**Comment by ttyio** [comment]
@sonersec , if you want to loadInputs with an int32 array, pseudocode to generate the data:

     with open("id.bin", "wb") as f:
         for d in rand_data :
               f.write(d.to_bytes(4, byteorder="little"))


args to trtexec: --loadInputs='input_ids':id.bin,

**Comment by sonersec** [comment]
@ttyio Thank you for reply. What is the format of rand_data? for example If I want to run 100 iterations, do I need to put 100 numbers in rand_data? I want to make it fixed input for each iteration so I put it 0 for 100 times. Am I correct?

**Comment by ttyio** [comment]
Hello @sonersec , rand_data is an array. e.g, we want to feed `input_ids` with 128 integers in each iteration. then you need prepare rand_data with 128 integers. And trtexec will inference with the same input for 100 iterations.

**Comment by sonersec** [comment]
@ttyio Thank you. I have last question. I am simulating on VGG19 network. I need to input 224x224 image files for input. Does this mean in the input vector, I need 224x224x3 integer values.

**Comment by ttyio** [comment]
Hello @sonersec , usually float values for image input, you can check the input of your network construction code.

**Comment by JiaoPaner** [comment]
@ttyio  if want to loadInputs with an float array, how to generate the bin file?

**Comment by ttyio** [comment]
@JiaoPaner ,  this is the right way:

         output_file.write(struct.pack("<f",value))

notice trtexec just read the whole file into buffer, and do memcpy from host to device.

**Comment by ahmedius2** [comment]
@ttyio what if we are building an engine for a model taking dynamically sized inputs? How should I arrange the files for the loadInputs argument in that case? Should we put the inputs with the maximum sizes?

**Comment by ahmedius2** [comment]
> @ttyio what if we are building an engine for a model taking dynamically sized inputs? How should I arrange the files for the loadInputs argument in that case? Should we put the inputs with the maximum sizes?

I found that we should use the optimal dimensions in this case. Also here is the code to write all the tensors to files:

```
for name, t in inputs_dict.items():
    data = t.cpu().numpy()
    with open(f"deploy_files/{name}.bin", "wb") as f:
        data = np.ravel(data)
        if data.dtype == np.float32:
            for d in data:
                f.write(struct.pack("<f", d.item()))
        elif data.dtype == np.int64:
            for d in data:
                f.write(struct.pack("<q", d.item()))  # 'q' is for int64
        elif data.dtype == np.int32:
            for d in data:
                f.write(struct.pack("<i", d.item()))  # 'i' is for int32
        elif data.dtype == np.bool_:
            for d in data:
                f.write(struct.pack("<B", d.item()))  # 'B' is for unsigned char
        else:
            raise ValueError(f"Unsupported data type: {data.dtype}")
print('Done.')
````

**Comment by ttyio** [comment]
> > @ttyio what if we are building an engine for a model taking dynamically sized inputs? How should I arrange the files for the loadInputs argument in that case? Should we put the inputs with the maximum sizes?
> 
> I found that we should use the optimal shapes (--optShapes given to trtexec) in this case. Also here is the code I used to write all the tensors to files:
> 
> ```
> for name, t in inputs_dict.items():
>     data = t.cpu().numpy() # t is a pytorch tensor
>     with open(f"deploy_files/{name}.bin", "wb") as f:
>         data = np.ravel(data)
>         if data.dtype == np.float32:
>             for d in data:
>                 f.write(struct.pack("<f", d.item()))
>         elif data.dtype == np.int64:
>             for d in data:
>                 f.write(struct.pack("<q", d.item()))  # 'q' is for int64
>         elif data.dtype == np.int32:
>             for d in data:
>                 f.write(struct.pack("<i", d.item()))  # 'i' is for int32
>         elif data.dtype == np.bool_:
>             for d in data:
>                 f.write(struct.pack("<B", d.item()))  # 'B' is for unsigned char
>         else:
>             raise ValueError(f"Unsupported data type: {data.dtype}")
> print('Done.')
> ```

Yes, use `--shapes` if it is specified, otherwise use `--optShapes`.
