### ISSUE TITLE
How to build in Ubuntu 16.04

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [NVIDIA/TensorRT#852]
Hi,   I am confused about one thing.  Do we first need install TensorRT from Nvidia Webiste (https://developer.nvidia.com/nvidia-tensorrt-7x-download) according to our system and cuda etc?  and Then also build TensoRT from source (https://github.com/NVIDIA/TensorRT) from here if we want to use samples, onnx parsers and trtexec etc? 

Or only building from source is enough?  Or only one method from those two is enough?  The TensorRT-OSS is different from TensorRT? 

Can we use different versions fo Cuda and cudnn? For example, can i use install TensorRT-7-1 with cuda 10 in ubuntu 16.04 ? 

It's a little confusing.

**Comment by ttyio** [comment]
Hello @MuhammadAsadJaved , thanks for the question.
Currently we only opensourced samples, plugins, and parsers, so we still have to install the tensorRT core binary first. 
We do not need to build the opensource if we do not want to modify the samples, plugins or parsers. we have a binary distribution in the binary package.
For the cudnn and cuda version, it is already specified in the download page, we need download the same version as our system environment. You can also check it from our release notes https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html
Hope this can answer your question.
