### ISSUE TITLE
How to configure getBatch when model has multiple inputs.

### ISSUE THREAD

**Issue by chenbohua3** [NVIDIA/TensorRT#857]
In sample of int8 calibration, model to be optimized has only one input, so `getBatch` function return `float*`. When model has multiple inputs, how to configure `getBatch`? Do we need to return vector<float*> of which each float* points to one input of the model?

**Comment by 0yueyunfei0** [comment]
你好，你解决这个问题了吗

**Comment by vogaliccb** [comment]
Same question

**Comment by arthursunbao** [comment]
+1
