### ISSUE TITLE
No network_api_pytorch in /usr/src/tensorrt/samples/python/

### ISSUE THREAD

**Issue by chaoren2357** [NVIDIA/TensorRT#859]
Hi! I use jetpack 4.4 in my Nvidia AGX Xavier to install TensorRT 7.1.3.0. However, when I follow the tutorial in https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/sample-support-guide/index.html#network_api_pytorch_mnist , I can't find /usr/src/tensorrt/samples/python/network_api_pytorch . 
```
(py36) zi@zi-desktop:/usr/src/tensorrt/samples/python$ ls
common.py                    introductory_parser_samples  uff_ssd
end_to_end_tensorflow_mnist  network_api_pytorch_mnist    yolov3_onnx
engine_refit_mnist           onnx_packnet
int8_caffe_mnist             uff_custom_plugin
```
How can I get the folder network_api_pytorch?

**Comment by rajeevsrao** [comment]
@chaoren2357 The python samples are currently only included with our GA releases.
See: https://developer.nvidia.com/tensorrt
