### ISSUE TITLE
TensorRT-7.1.3.4/samples/common/buffers.h:447: undefined reference to `sample::gLogError

### ISSUE THREAD

**Issue by chegnyanjun** [NVIDIA/TensorRT#864]
hi, i am  use  tensorrt to accerate a simple classification model, liek resnet,i learned a similar project(tensorrt's googlenet),after i write my code and run it, it occurs such problem, can anybody help me?
my envir:ubuntu16.04+cuda10.2+tensorrt7.1.3.4+cudnn8.0.

**Comment by mk-nvidia** [comment]
`gLogError` is defined in `${SAMPLES_DIR}/common/logger.cpp`. You need to make sure to link your sample to this file. See `CMakeLists.txt` for any sample, it has the line `include(../../CMakeSamplesTemplate.txt)`. `CMakeSamplesTemplate.txt` adds logger.cpp.
Does this fix your problem?

**Comment by chegnyanjun** [comment]
＠mk-nvidia,thanks for your reply, i have fixed my problem.thank you so much.

**Comment by FengZhiheng** [comment]
I also have the same problem, my CMakeLists.txt  have 
```
INCLUDE_DIRECTORIES(/usr/local/TensorRT-8.6.1.6/include/) 
INCLUDE_DIRECTORIES(/usr/local/TensorRT-8.6.1.6/samples/common/)
```
my env:
system: linux centos
cuda:10.2
tensort:8.6.1.6

**Comment by KOOSNATHI** [comment]
Hi 
after i have done coding my program of simple_shell i experience these right after adding my gcc compiler command line what should i do to make it right ?


/usr/bin/ld: /tmp/ccia5GLt.o: in function `exit_cmd':
cmd_exit.c:(.text+0x28): undefined reference to `free_buffers'
/usr/bin/ld: /tmp/ccEShV1t.o: in function `execution':
execu.c:(.text+0x85): undefined reference to `free_buffers'
/usr/bin/ld: /tmp/ccJamUGt.o: in function `main':
shell.c:(.text+0x8a): undefined reference to `free_buffers'
/usr/bin/ld: shell.c:(.text+0x96): undefined reference to `free_buffers'
collect2: error: ld returned 1 exit status
