### ISSUE TITLE
onnx-to-tensorrt not working for custom ssd mobilenetv2 model

### ISSUE THREAD

**Issue by 1208overlord** [NVIDIA/TensorRT#865]
I have trained own ssd mobilenetv2 model with custom data.
I thought to run it on Xavier AGX, and was going to convert to tensorrt.
I thought tensorflow-onnx-tensorrt is the good way to do it.
And then, successfully generated onnx file, but continued to fail to convert onnx to tensorrt.
Many people other than me have same issue, but I didn't find the best solution for me.
I tried with many ways that they suggest, but same error exist.
What should I do to fix it?

**Comment by 1208overlord** [comment]
Additional information
I am using TensorRT 6.0.10 version and trained with tensorflow 1.15 version.

**Comment by rajeevsrao** [comment]
@1208overlord Can you provide more specifics about the issue you are seeing (error log) when parsing the ONNX model via TensorRT or share the ONNX model?

**Comment by 1208overlord** [comment]
And then, I will share my model to be converted.

https://we.tl/t-ug58VPlMZq

Please help me with this conversion to Tensorrt

**Comment by nvpohanh** [comment]
@1208overlord Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists in TRT 8.4. Thanks
