### ISSUE TITLE
Cannot build  "trtexec" in TensorRT 7.2.1

### ISSUE THREAD

**Issue by GabbySuwichaya** [NVIDIA/TensorRT#870]
## Description

I am not sure how this should be done. 
I have installed  **TensorRT-7.2.1.6** with the tar file. 
That is I have followed  [installation of the Nvidia webpage](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar)

```
$ cd ~/TensorRT-7.2.1.6/samples/trtexec

~/TensorRT-7.2.1.6/samples/trtexec$ make

````
Then, I get the following error

````
../Makefile.config:10: CUDA_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDA_INSTALL_DIR=<cuda_directory> to change.
../Makefile.config:15: CUDNN_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
../Makefile.config:28: TRT_LIB_DIR is not specified, searching ../../lib, ../../lib, ../lib by default, use TRT_LIB_DIR=<trt_lib_directory> to change.
make: Nothing to be done for 'all'.

````
 
Also, I have installed the **TensorRT Open Source Software** package from **https://github.com/NVIDIA/TensorRT**.  I have successfully built the package using the following instruction **https://github.com/NVIDIA/TensorRT#building-tensorrt-oss.** 

Then, I tried to make the **trtexec**

```
$ cd ~/TensorRT/samples/opensource/trtexec

~/TensorRT/samples/opensource/trtexec$ ls.

CMakeLists.txt  prn_utils.py  profiler.py  README.md  tracer.py  trtexec.cpp

~/TensorRT/samples/opensource/trtexec$ make

make: *** No targets specified and no makefile found.  Stop.

~/TensorRT/samples/opensource/trtexec$ cmake .


CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/docker/TensorRT/samples/CMakeSamplesTemplate.txt:22 (set_ifndef):
  Unknown CMake command "set_ifndef".
Call Stack (most recent call first):
  CMakeLists.txt:26 (include)


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/docker/TensorRT/samples/opensource/trtexec/CMakeFiles/CMakeOutput.log".

````

## Environment

**TensorRT Version**:  7.2.1
**GPU Type**:  Titan V
**Nvidia Driver Version**:  455.23.04
**CUDA Version**:  CUDA 11.1
**CUDNN Version**:  8
**Operating System + Version**:  Ubuntu 18.04
**Python Version (if applicable)**:  3.6.9
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**:   1.4.0+cpu
**Baremetal or Container (if container which image + tag)**: 

 ## Steps To Reproduce

- Install TensorRT 7.2.1 with tar file, following [the Nvidia webpage](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar)
- Install the following packages to run **/home/docker/TensorRT-7.2.1.6/samples/python/onnx_packnet** , i.e., 
torch==1.4.0+cpu; platform_machine=="x86_64" and sys.platform=="linux"
onnx==1.6.0
numpy
pycuda
- Install git, pkg-config, wget, zlib.
- Install cmake 
````wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz
tar -xzvf cmake-3.16.5.tar.gz
./bootstrap --system-curl
make -j8 
make install
````
-  Install TensorRT by building the package with the instruction from https://github.com/NVIDIA/TensorRT#building-tensorrt-oss. 
- Build *onnx-graphsurgeon* following the instruction from 
 https://github.com/NVIDIA/TensorRT/tree/release/7.1/tools/onnx-graphsurgeon**
- Then, I try to build `trtexec` and fail to do so.

**Comment by rajeevsrao** [comment]
@GabbySuwichaya cmake is only supported on the top level `~/TensorRT` directory which builds all the OSS components. Please follow the instructions in the README verbatim.

**Comment by austinmw** [comment]
@rajeevsrao The README only says to run `make` in the trtexec directory. When I do this I get:

> make: Nothing to be done for 'all'.

**Comment by SokolovskiR** [comment]
> @rajeevsrao The README only says to run `make` in the trtexec directory. When I do this I get:
> 
> > make: Nothing to be done for 'all'.

I have the same  error on a Jetson Nano developer kit while trying to create an inference engine from ONNX model. Have you found a solution?

**Comment by faranaziz** [comment]
Same here. After building the docker file, its impossible to find **trtexec** anywhere.

**Comment by MoshiurRahmanFaisal** [comment]
Follow this guide line for installing TensorRT with Command-Line Wrapper: trtexechttps://medium.com/@moshiur.faisal01/install-tensorrt-with-command-line-wrapper-trtexec-on-ununtu-20-04-lts-3e44f4f36a2b

**Comment by MarouaneMja** [comment]
Actually, you have to go to (inside the docker container), the folder /workspace/TensorRT/build/sample/trtexec , then run the `make`

**Comment by siddagra** [comment]
> @rajeevsrao The README only says to run `make` in the trtexec directory. When I do this I get:
> 
> > make: Nothing to be done for 'all'.

Yeah the documentation for trtexec build is quite poor.. Many errors and basically uninstallable unless u pull a large docker file.. For just a CLI.

**Comment by siddagra** [comment]
> Follow this guide line for installing TensorRT with Command-Line Wrapper: trtexechttps://medium.com/@moshiur.faisal01/install-tensorrt-with-command-line-wrapper-trtexec-on-ununtu-20-04-lts-3e44f4f36a2b

did not work for me...

**Comment by siddagra** [comment]
> @GabbySuwichaya cmake is only supported on the top level `~/TensorRT` directory which builds all the OSS components. Please follow the instructions in the README verbatim.

using cmake at TensorRT directory also doesnt work.

**Comment by sparsh23145** [comment]
All the above steps for installing trtexec didn't work for me too. Its documentation is not appropriate.

**Comment by sparsh23145** [comment]
> ## Description
> 
> I am not sure how this should be done. I have installed **TensorRT-7.2.1.6** with the tar file. That is I have followed [installation of the Nvidia webpage](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar)
> 
> ```
> $ cd ~/TensorRT-7.2.1.6/samples/trtexec
> 
> ~/TensorRT-7.2.1.6/samples/trtexec$ make
> ```
> 
> Then, I get the following error
> 
> ```
> ../Makefile.config:10: CUDA_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDA_INSTALL_DIR=<cuda_directory> to change.
> ../Makefile.config:15: CUDNN_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
> ../Makefile.config:28: TRT_LIB_DIR is not specified, searching ../../lib, ../../lib, ../lib by default, use TRT_LIB_DIR=<trt_lib_directory> to change.
> make: Nothing to be done for 'all'.
> ```
> 
> Also, I have installed the **TensorRT Open Source Software** package from **https://github.com/NVIDIA/TensorRT**. I have successfully built the package using the following instruction **https://github.com/NVIDIA/TensorRT#building-tensorrt-oss.**
> 
> Then, I tried to make the **trtexec**
> 
> ```
> $ cd ~/TensorRT/samples/opensource/trtexec
> 
> ~/TensorRT/samples/opensource/trtexec$ ls.
> 
> CMakeLists.txt  prn_utils.py  profiler.py  README.md  tracer.py  trtexec.cpp
> 
> ~/TensorRT/samples/opensource/trtexec$ make
> 
> make: *** No targets specified and no makefile found.  Stop.
> 
> ~/TensorRT/samples/opensource/trtexec$ cmake .
> 
> 
> CMake Warning (dev) in CMakeLists.txt:
>   No project() command is present.  The top-level CMakeLists.txt file must
>   contain a literal, direct call to the project() command.  Add a line of
>   code such as
> 
>     project(ProjectName)
> 
>   near the top of the file, but after cmake_minimum_required().
> 
>   CMake is pretending there is a "project(Project)" command on the first
>   line.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at /home/docker/TensorRT/samples/CMakeSamplesTemplate.txt:22 (set_ifndef):
>   Unknown CMake command "set_ifndef".
> Call Stack (most recent call first):
>   CMakeLists.txt:26 (include)
> 
> 
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
> 
>     cmake_minimum_required(VERSION 3.16)
> 
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/docker/TensorRT/samples/opensource/trtexec/CMakeFiles/CMakeOutput.log".
> ```
> 
> ## Environment
> 
> **TensorRT Version**: 7.2.1 **GPU Type**: Titan V **Nvidia Driver Version**: 455.23.04 **CUDA Version**: CUDA 11.1 **CUDNN Version**: 8 **Operating System + Version**: Ubuntu 18.04 **Python Version (if applicable)**: 3.6.9 **TensorFlow Version (if applicable)**: **PyTorch Version (if applicable)**: 1.4.0+cpu **Baremetal or Container (if container which image + tag)**:
> ## Steps To Reproduce
> 
>     * Install TensorRT 7.2.1 with tar file, following [the Nvidia webpage](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar)
> 
>     * Install the following packages to run **/home/docker/TensorRT-7.2.1.6/samples/python/onnx_packnet** , i.e.,
>       torch==1.4.0+cpu; platform_machine=="x86_64" and sys.platform=="linux"
>       onnx==1.6.0
>       numpy
>       pycuda
> 
>     * Install git, pkg-config, wget, zlib.
> 
>     * Install cmake
> 
> 
> ```
> tar -xzvf cmake-3.16.5.tar.gz
> ./bootstrap --system-curl
> make -j8 
> make install
> ```
> 
>     * Install TensorRT by building the package with the instruction from https://github.com/NVIDIA/TensorRT#building-tensorrt-oss.
> 
>     * Build _onnx-graphsurgeon_ following the instruction from
>       https://github.com/NVIDIA/TensorRT/tree/release/7.1/tools/onnx-graphsurgeon**
> 
>     * Then, I try to build `trtexec` and fail to do so.

I also did follow these exact same steps but unable to install 'trtexec'.

**Comment by cholland-nv** [comment]
Has anyone solved this?
