### ISSUE TITLE
Onnx-Trt engine for custom mobilenet-v2-fn model

### ISSUE THREAD

**Issue by 1208overlord** [NVIDIA/TensorRT#873]
Hello, I built my custom mobilenet-v2-fn model and trained it
I wanted to run it on Jetson Xavier, and tried to convert into trt engine via tensorflow-onnx-trt.
And then, successfully generated onnx, but failed to convert onnx to trt engine.
Please help me

Beginning ONNX file parsing
[TensorRT] ERROR: Parameter check failed at: …/builder/Network.cpp::addInput::671, condition: isValidDims(dims, hasImplicitBatchDimension())
Completed parsing of ONNX file
Building an engine from file ssd_mobilenet_v2_coco_2018_03_29/model_edit.onnx; this may take a while…
[TensorRT] ERROR: Network must have at least one output
Completed creating Engine
Traceback (most recent call last):
File “onnx_runtime_pretrained.py”, line 87, in
engine = get_engine(onnx_file_path, engine_file_path)
File “onnx_runtime_pretrained.py”, line 82, in get_engine
return build_engine()
File “onnx_runtime_pretrained.py”, line 78, in build_engine
f.write(engine.serialize())
AttributeError: ‘NoneType’ object has no attribute ‘serialize’

def get_engine(onnx_file_path, engine_file_path=""):
"""Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""
def build_engine():
flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
"""Takes an ONNX file and creates a TensorRT engine to run inference with"""
with trt.Builder(TRT_LOGGER) as builder, builder.create_network(flag) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
builder.max_workspace_size = 1 << 28 # 256MiB
builder.max_batch_size = 1
# Parse model file
print('Loading ONNX file from path {}...'.format(onnx_file_path))
with open(onnx_file_path, 'rb') as model:
print('Beginning ONNX file parsing')
parser.parse(model.read())
print('Completed parsing of ONNX file')
print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
engine = builder.build_cuda_engine(network)
print("Completed creating Engine")
with open(engine_file_path, "wb") as f:
f.write(engine.serialize())
return engine()

return build_engine()
I used this script to convert.

**Comment by ttyio** [comment]
Hello @1208overlord , thanks for reporting.
which TRT version are you using?
The error says `addInput()` failed, Could you visualize your model to check the input dimension of your model? If there are any dynamic shape dims, you have to create an dynamic optimize profile before build engine. thanks!

**Comment by ttyio** [comment]
BTW, you can also try trtexec, we release the binary in the trt package, also there is source code in https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec

**Comment by 1208overlord** [comment]
https://we.tl/t-F6dV0Cuvrz
This is my model(fr0zen, checkpoint and onnx I converted myself)
Could you please try on your side?
It gives many errors, unfortunately

**Comment by ttyio** [comment]
Hmmm, for the `addInput` failure, this is because INT8 input not support in onnx parser, can be workaround by replace this int8 input with int32 input.

After this workaround, I still see failure from `resize` node, TRT has known issue for `resize`, we did not support all the coords transformation modes in 7.2. This will be fixed in next major release. Sorry for that...

**Comment by 1208overlord** [comment]
you say, it is impossible to do for my model for now?

**Comment by ttyio** [comment]
Hello @1208overlord 
we have to wait for next TRT major release, or adjust your model, change the resize and make the `transformationMode` in the onnx-trt support list, see:

https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L2599

**Comment by ttyio** [comment]
The 8.0EA download link is in https://developer.nvidia.com/nvidia-tensorrt-download
I will close this, please reopen if you still have question, thanks!
