### ISSUE TITLE
Conditional flow over network

### ISSUE THREAD

**Issue by ylmzkaan** [NVIDIA/TensorRT#879]
Hi, I have a network with a backbone and two heads attached to the backbone. I define this network using the TensorRT C++ API. One of the heads is computationally expensive and I want to get predictions from that head in every 10th inference instead of every time I do forward pass. 

I wonder if it possible to set up such a conditional flow over the network with TensorRT C++ API.

**Comment by rajeevsrao** [comment]
@ylmzkaan We do not support any data-dependent conditional ops/layers in TensorRT as of 7.2 release.

**Comment by vjsrinivas** [comment]
@rajeevsrao I'm assuming conditionals are now supported by TRT: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-conditionals

What is the minimum version that supports conditionals?
