### ISSUE TITLE
Why the first batch is very slow ? 

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TensorRT#881]
In my experiments on the semantic segmentation task, I found that the forward of the first batch is rather slower than the latter. One surgery is that I manually call the `enqueue`  one time before feeding the true data. So what's the reason behind this issue?  And how to prevent the latency?

**Comment by nvpohanh** [comment]
TRT needs to allocate/rearrange some resource after any change in input dimensions (including the very first time right after the context is created). Therefore, it is the correct approach to call the `enqueue` once in the set-up/warm-up stage of your program.

**Comment by JosephChenHub** [comment]
> TRT needs to allocate/rearrange some resource after any change in input dimensions (including the very first time right after the context is created). Therefore, it is the correct approach to call the `enqueue` once in the set-up/warm-up stage of your program.

thanks ! That sounds reasonable.

**Comment by hitbuyi** [comment]
the same phenomenon happens to me
