### ISSUE TITLE
Cudnn Error in execute: 3 when inferencing image with dynamic shape

### ISSUE THREAD

**Issue by hao6699** [NVIDIA/TensorRT#885]
## Description
When Inferencing image with dynamic shape, some images work well , while some images throw out this error:
[TensorRT] ERROR: ../rtSafe/cuda/cudaConvolutionRunner.cpp (362) - Cudnn Error in execute: 3 (CUDNN_STATUS_BAD_PARAM)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception

I have trained a model by keras, and transfor h5 to the onnx tpye using keras2onnx library. Then I use build_trt.py to produce trt engine. However, when I use test.py to inference, some images work well, and some don't. In my example, right.jpg works well, error.jpg don't. However, when I set the fixed shape in build_trt.py, both images work well. I can't finger out why this happen.
I did more test, and find some shapes work well, but some shapes don't. All shapes works well in keras model and onnx model

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: RTX 2080 TI
**Nvidia Driver Version**: 430.40
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.4
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 1.14.0
**PyTorch Version (if applicable)**: Not Used
**Keras Version**: 2.3.0
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

https://drive.google.com/file/d/1PrMEWOnsocAtPXupsd1KGFnsHGHTCdsC/view?usp=sharing

## Steps To Reproduce

1. Decompression test.trt.zip
2. run the build_engine in build_trt.py to produce trt engine or just use the produced crnn_engine.trt
3. run test.py

**Comment by rajeevsrao** [comment]
@hao6699 thanks for providing the testcase. Will look into this shortly.

**Comment by Piteryo** [comment]
Any updates on this? Ran into the same problem.

**Comment by ttyio** [comment]
Hello @hao6699 @Piteryo , this is already fixed in release 7.2.3 . Could you take a try? thanks!

**Comment by ttyio** [comment]
Close since no activation for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by DrewdropLife** [comment]
> Hello @hao6699 @Piteryo , this is already fixed in release 7.2.3 . Could you take a try? thanks!

7.2.3 I have tried it, but the same error is reported.

**Comment by hao6699** [comment]
yes, 7.2.3 works fine with me

**Comment by DrewdropLife** [comment]
> yes, 7.2.3 works fine with me

I tried with 7.2.3.4, but also failed...
