### ISSUE TITLE
INT8 mode layer fusion

### ISSUE THREAD

**Issue by JettHu** [NVIDIA/TensorRT#887]
## Description

Some "layer fusion" does not work while I enable INT8 mode building. And my model runs slower than float16 in int8 mode. Is it caused by this.

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: V100DX-8C
**Nvidia Driver Version**: Driver Version: 430.46
**CUDA Version**: 10.0.130
**CUDNN Version**: 7.6.5
**Operating System + Version**: centos 7.0
**Python Version (if applicable)**: python3.6.8
**PyTorch Version (if applicable)**: 1.3.1+cu100

## Steps To Reproduce

Here is the logs.

### FLOAT32 & FLOAT16 MODE

```bash
[INFO ] 2020-10-28 14:45:53,824 trt_logger.cpp(52): [TRT] Layer(PointWise): PWN(PWN(PWN(PWN((Unnamed Layer* 56) [Constant], (Unnamed Layer* 57) [ElementWise]), (Unnamed Layer* 60) [ElementWise]), (Unnamed Layer* 62) [ElementWise]), (Unnamed Layer* 78) [ElementWise]), Tactic: 256, (Unnamed Layer* 55) [Constant]_output[Float(256,1,1)], (Unnamed Layer* 59) [PluginV2DynamicExt]_output_0[Float(256,128,128)], (Unnamed Layer* 61) [ElementWise]_output[Float(256,128,128)], (Unnamed Layer* 77) [Shuffle]_output[Float(256,1,1)] -> (Unnamed Layer* 78) [ElementWise]_output[Float(256,128,128)]
```

I take `PWN` as a layer fusion. So what `PWN` stands for. On Float32 & Float16 mode the `PWN` works. 

### INT8 MODE

``` bash
[INFO ] 2020-10-28 15:01:24,788 trt_logger.cpp(52): [TRT] Layer(ElementWise): (Unnamed Layer* 60) [ElementWise], Tactic: 1, (Unnamed Layer* 59) [PluginV2DynamicExt]_output_0[Float(256,128,128)], (Unnamed Layer* 57) [ElementWise]_output[Float(256,1,1)] -> (Unnamed Layer* 60) [ElementWise]_output[Float(256,128,128)]
[INFO ] 2020-10-28 15:01:24,788 trt_logger.cpp(52): [TRT] Layer(Scale): (Unnamed Layer* 58) [Constant] + (Unnamed Layer* 61) [ElementWise], Tactic: 0, (Unnamed Layer* 59) [PluginV2DynamicExt]_output_1[Float(256,128,128)] -> (Unnamed Layer* 61) [ElementWise]_output[Float(256,128,128)]
[INFO ] 2020-10-28 15:01:24,789 trt_logger.cpp(52): [TRT] Layer(ElementWise): (Unnamed Layer* 62) [ElementWise], Tactic: 1, (Unnamed Layer* 60) [ElementWise]_output[Float(256,128,128)], (Unnamed Layer* 61) [ElementWise]_output[Float(256,128,128)] -> (Unnamed Layer* 62) [ElementWise]_output[Float(256,128,128)]
```

On the INT8 mode, `PWN` gone...😥

**Comment by pranavm-nvidia** [comment]
Are you disabling FP16 when you build in INT8 mode? You should enable both for best performance

**Comment by JettHu** [comment]
> Are you disabling FP16 when you build in INT8 mode? You should enable both for best performance

Yes, I did. I tried both only INT8 mode and set both flag(FP16&INT8). And got the same reuslt about PWN.

**Comment by rajeevsrao** [comment]
@JettHu can you please carve out an isolated testcase for this, if possible? We would like to investigate.
PWN stands for PointWiseNodes and they can be fused unlike the ElementWise layers in your int8 example.

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
