### ISSUE TITLE
Convert TF frozen graph to UFF graph

### ISSUE THREAD

**Issue by xiesibo** [NVIDIA/TensorRT#89]
[TensorRT] ERROR: UFFParser: Validator error: net/fc7/BiasAdd: Unsupported operation Identity
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "trt_optimize.py", line 50, in <module>
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by xiesibo** [comment]
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
FROZEN_GDEF_PATH = 'data/frozen_trt.pb' # ADJUST
ENGINE_PATH = 'data/engine.plan' # ADJUST
INPUT_NODE = 'net/input' # ADJUST
OUTPUT_NAMES = ['net/plate/BiasAdd','net/blet/BiasAdd']#
INPUT_SIZE = [3, 224, 224] # ADJUST
MAX_BATCH_SIZE = 1 # ADJUST
MAX_WORKSPACE = 1 << 32 # ADJUST
DATA_TYPE = trt.float16 # ADJUST # float16 | float32

### Convert TF frozen graph to UFF graph

uff_model = uff.from_tensorflow_frozen_model(FROZEN_GDEF_PATH, OUTPUT_NAMES)
### Create TRT model builder

trt_logger = trt.Logger(trt.Logger.INFO)
builder = trt.Builder(trt_logger)
builder.max_batch_size = MAX_BATCH_SIZE
builder.max_workspace_size = MAX_WORKSPACE
builder.fp16_mode = (DATA_TYPE == trt.float16)
### Create UFF parser

parser = trt.UffParser()
parser.register_input(INPUT_NODE, INPUT_SIZE)
parser.register_output(OUTPUT_NAMES[0])
parser.register_output(OUTPUT_NAMES[1])
### Parse UFF graph

network = builder.create_network()
parser.parse_buffer(uff_model, network)
### Build optimized inference engine
print('***parser',parser)
engine = builder.build_cuda_engine(network)
### Save inference engine

**Comment by kaka7** [comment]
the logs output "Unsupported operation Identity" may failed to create engine so that nonetype .

**Comment by rmccorm4** [comment]
Hi @xiesibo,

As @kaka7 mentioned, this is due to the Identity op not being supported at the time. This has since been added to the list of supported ops with TensorRT 6.x: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/uff/Operators.html#identity

Please try again after upgrading :slightly_smiling_face:
