### ISSUE TITLE
Unsupported Ops in the supported list?

### ISSUE THREAD

**Issue by whillas** [NVIDIA/TensorRT#897]
## Description

I'm getting this warning
```
2020-11-12 22:51:05.463845: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:486] There are 1987 ops of 12 different types in the graph that are not converted to TensorRT: BiasAdd, Identity, DepthwiseConv2dNative, IdentityN, MatMul, Placeholder, NoOp, VarHandleOp, Const, ReadVariableOp, FusedBatchNormV3, Conv2D, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops).
```
So i look up the [supported Ops](https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#supported-ops) and find that 

- Identity
- DepthwiseConv2dNative
- Const
- Conv2D

Are in the suppored list for Tensorflow models? What gives

## Environment

I'm running this in [Triton Inference Server container 20.10(]https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-10.html#rel_20-10) so...

**TensorRT Version**: 7.2.1
**GPU Type**: GeForce RTX 2080
**Nvidia Driver Version**: 455.23.04
**CUDA Version**: 11.1
**CUDNN Version**: 8.0.4
**Operating System + Version**: Ubuntu 
**Python Version (if applicable)**: 3
**TensorFlow Version (if applicable)**: 1.15
**Baremetal or Container (if container which image + tag)**: Triton Inference Server container 20.10

## Relevant Files

Efficientnet-b5 model from TF 1.15
https://console.cloud.google.com/storage/browser/imagr-public-bucket/efficientnet-b5

## Steps To Reproduce

Load model in Triton and perform inference.

**Comment by pranavm-nvidia** [comment]
TF-TRT partitions the graph into segments supported by TRT. If the segment is too small, then it's excluded from conversion to TRT (you can control this via the `minimum_segment_size` parameter). The reason being that for very small subgraphs, the overhead would outweigh any benefits of offloading to TRT.

**Comment by whillas** [comment]
Yeah, that doesn't really explain why its saying that `Conv2D` is not supported which is a worry to me :(

**Comment by pranavm-nvidia** [comment]
Well it's not saying that it's unsupported - just that it's not being converted:

> that are not _converted_ to TensorRT

**Comment by whillas** [comment]
Thats retarded
