### ISSUE TITLE
Installation on Tegra platforms

### ISSUE THREAD

**Issue by xonobo** [NVIDIA/TensorRT#9]
The TensorRT release binaries are available for x86 and Power PCs. How can I try TensorRT OSS on TX1, TX2, and Tegra Nano?

**Comment by rajeevsrao** [comment]
We are working on this and will provide an update soon.

**Comment by xonobo** [comment]
There is a new release. Is there any progress on this issue?

**Comment by xonobo** [comment]
Here is my installation steps for TX2 with a JetPack 4.3:

> # Build commands
> git clone https://github.com/nvidia/TensorRT TensorRT
> cd TensorRT
> git checkout 19.12
> git submodule update --init --recursive
> mkdir -p build && cd build
> cmake -DCUBLASLT_LIB=/usr/local/cuda-10.0/targets/aarch64-linux/lib/libcublas.so -DCUDNN_VERSION=7.6 -DCUDA_VERSION=10.0 -DPROTOBUF_VERSION=3.8.0 -DGPU_ARCHS=62 ..
> CC=aarch64-linux-gnu-gcc make -j8
> CC=aarch64-linux-gnu-gcc make install
> # System wide installation commands
> sudo cp ../lib/* /usr/lib/aarch64-linux-gnu
> sudo cp ../include/* /usr/include/aarch64-linux-gnu
> sudo cp ../bin/onnx2trt /usr/bin/
> sudo cp ../bin/trtexec /usr/bin/
