### ISSUE TITLE
the dims of tensorRT prediction got changed?

### ISSUE THREAD

**Issue by hegc** [NVIDIA/TensorRT#904]
## Description

the dims of tensorRT prediction got changed, trt model is transformed from onnx using trtexec.

1.npy and 2.npy has same shapes, but different results.

for onnx:
input: (1, 1, 200, 832)
output: (1, 1, 200, 832)

for trt: 1.npy
input: (1, 1, 200, 832)
output: (1, 1, 200, 832)

for trt: 2.npy
input: (1, 1, 200, 832)
output: (1, 1, 832, 200)
I have to transpose the output!!!

## Environment

**TensorRT Version**: TensorRT-7.2.1.6
**GPU Type**: Tesla V100
**Nvidia Driver Version**: 440.64.00
**CUDA Version**: 10.2
**CUDNN Version**: cudnn-10.2-linux-x64-v8.0.5.39
**Operating System + Version**: Linux  3.10.0-862.el7.x86_64
**Python Version (if applicable)**: 3.6.2
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.7.0+cu101
**onnx**: 1.6.0
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

Scripts and models are [here.](https://github.com/hegc/trt_model)

## Steps To Reproduce

In [https://github.com/hegc/trt_model](https://github.com/hegc/trt_model), just run the two inference py-script. 
I think it's bugs. Whether the input of trt engine are dynamic or not, the dimension of output for 2.npy is confused. Any help will be greatly appreciated.

**Comment by pranavm-nvidia** [comment]
Seems like the code is just reshaping it to a different shape? https://github.com/hegc/trt_model/blob/master/trt_infer.py#L56

**Comment by hegc** [comment]
Can the Relu6 be transferred to tensorRT?

**Comment by hegc** [comment]
And clamp op...I think it's a bug!

**Comment by hegc** [comment]
1.npy is C_CONTIGUOUS numpy array...
2.npy is F_CONTIGUOUS numpy array...
