### ISSUE TITLE
Convert onnx to tensorrt model failed

### ISSUE THREAD

**Issue by Sparkling-Water** [NVIDIA/TensorRT#912]
## Description
Hello, I'm trying to convert onnx to tensorrt model, but I got an error message as following:
'
Graph construction and optimization completed in 0.125233 seconds. 
Constructing optimization profile number 0 [1/1].
Builder timing cache: created 0 entries, 0 hit(s) 
../builder/cudnnBuilder2.cpp (2025) - Assertion Error in getSupportedFormats: 0 (!formats.empty()) 
create engine failed 
Aborted (core dumped)
'

My code is as following:
`
void compile_onnx(vector args) {
bool use_fp16{false};
if ((args.size() >= 4) && args[3] == "--fp16") use_fp16 = true;
TrtSharedEnginePtr engine = parse_to_engine(args[1], use_fp16);
serialize(engine, args[2]);
}
`

I don't know how to solve this problem. Can you help me？Thanks!

## Environment

**TensorRT Version**: 7.1.3
**GPU Type**: TX2
**Nvidia Driver Version**:Jetpack4.4 
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System + Version**:Ubuntu18.04 
**Python Version (if applicable)**: 3.6.9

**Comment by Wunaiq** [comment]
Have you solved this issue?
I got the same error. Could you share your solution?
