### ISSUE TITLE
There seems to be something wrong with this performance calculation in fcPlugin. 

### ISSUE THREAD

**Issue by suxi1314** [NVIDIA/TensorRT#915]
There seems to be something wrong with this performance calculation. The "perf.time"  is divided by "kernelRepeats" twice.
https://github.com/NVIDIA/TensorRT/blob/c796c84bff32445886b9333bcf43581b2824acfb/plugin/fcPlugin/fcPlugin.cpp#L59
https://github.com/NVIDIA/TensorRT/blob/c796c84bff32445886b9333bcf43581b2824acfb/plugin/fcPlugin/fcPlugin.cpp#L115

**Comment by ttyio** [comment]
Hello @suxi1314 , good catch!
Could you create a merge request for this? thanks!!

**Comment by nvpohanh** [comment]
PR: #1979

**Comment by nvpohanh** [comment]
Filed an internal merge request to fix this.

**Comment by nvpohanh** [comment]
This has been fixed internally and will be available in next release. Thanks for reporting the issue.
