### ISSUE TITLE
ONNX model working for onnxruntime, not for TensorRT

### ISSUE THREAD

**Issue by dhernandez0** [NVIDIA/TensorRT#917]
## Description

When trying to load an ONNX model with TensorRT, I'm getting errors, however, the model is able to run with onnxruntime. The model is DETR (https://github.com/facebookresearch/detr) modified a bit (models/segmentation.py) because Einsum is not supported currently by TensorRT. I've attached the code in a zip file, and steps to reproduce the issue.

## Environment

**TensorRT Version**: 7.2.1.6-1+cuda10.2
**GPU Type**: GeForce GTX 1660 Ti
**Nvidia Driver Version**: 455.45.01
**CUDA Version**: 10.2
**CUDNN Version**: -
**Operating System + Version**: Ubuntu 18.04.5 LTS
**Python Version (if applicable)**: Python 3.6.9
**TensorFlow Version (if applicable)**: -
**PyTorch Version (if applicable)**: 1.7.0
**Baremetal or Container (if container which image + tag)**: -

## Relevant Files

1. code and onnx models: https://drive.google.com/file/d/1Nh-wcU2jItq7UIgilKuVffa7gCBRVj_B/view?usp=sharing
2. https://github.com/daquexian/onnx-simplifier

## Steps To Reproduce

> python3 export_onnx.py ./000000000285.jpg
> trtexec --onnx=./detr_resnet50_panoptic.onnx

The error I get after these steps is:

> [W] [TRT] onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
> ERROR: builtin_op_importers.cpp:2248 In function importPad:
> [8] Assertion failed: inputs.at(1).is_weights()
> [E] Failed to parse onnx file
> [E] Parsing model failed
> [E] Engine creation failed
> [E] Engine set up failed

However, if I use onnx-simplifier (https://github.com/daquexian/onnx-simplifier):

> python3 -m onnxsim detr_resnet50_panoptic.onnx detr_resnet50_panoptic.simple.onnx
> trtexec --onnx=./detr_resnet50_panoptic.simple.onnx

The error is a bit different:

> [E] [TRT] ../builder/myelin/codeGenerator.cpp (401) - Myelin Error in compileGraph: 64 (myelinProgramAnalysisError : Mismatched shape for tensor (Unnamed Layer_ 2020) [Identity]_output', current shape:b,[1,100,8,28,25], vs. expected shape:b,[].
> )
> [E] [TRT] ../builder/myelin/codeGenerator.cpp (401) - Myelin Error in compileGraph: 64 (13_kernel_agentINS0_14__parallel_for16ParallelForAgentINS0_6__fill7functorINS_6detail15normal_iteratorINS_10device_ptrIPfEEEESA_EElEESD_lEEvT0_T1_)
> [E] Engine creation failed
> [E] Engine set up failed

The zip file includes both onnx models already generated to make it easier to reproduce.

**Comment by mk-nvidia** [comment]
Thanks for the detailed report, we'll take a look.

**Comment by DataXujing** [comment]
@dhernandez0 Did you solve this problem? 
```
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (401) - Myelin Error in compileGraph: 64 (myelinProgramAnalysisError : Mismatched shape for tensor (Unnamed Layer_ 1837) [Identity]_output', current shape:b,[1,1,1,625], vs. expected shape:b,[].
)
[TensorRT] ERROR: ../builder/myelin/codeGenerator.cpp (401) - Myelin Error in compileGraph: 64 (myelinProgramAnalysisError : Mismatched shape for tensor (Unnamed Layer_ 1837) [Identity]_output', current shape:b,[1,1,1,625], vs. expected shape:b,[].
```

**Comment by Engineero** [comment]
Any updates on this? I am running into the same issue, same error, using a modified DETR converted to ONNX and then parsed with TensorRT version 7.1.3.0.

**Comment by DataXujing** [comment]
TensorRT for DETR: <https://github.com/DataXujing/TensorRT-DETR>

**Comment by NikhilChowdary-MCW** [comment]
Hi @dhernandez0 , @mk-nvidia , @Engineero ,
Any update on how to solve this error?

**Comment by kevinch-nv** [comment]
I'm able to run the attached model with TensorRT8 with the following command:

`./trtexec --onnx=detr/detr_resnet50_panoptic.simple.onnx --workspace=123097600`

**Comment by ttyio** [comment]
Closing since this is solved in last comment, thanks!
