### ISSUE TITLE
Cuda Error in launchNaiveSliceImpl: 400 (invalid resource handle)

### ISSUE THREAD

**Issue by xusk** [NVIDIA/TensorRT#925]
## Description

multi-threading in  yoloV5 plugin enqueue 
../rtExt/cuda/slice.cu (148) - Cuda Error in launchNaiveSliceImpl: 400 (invalid resource handle)
FAILED_EXECUTION: std::exception

but if without threading the result is  ok
 
## Environment

**TensorRT Version**: 7.1.3
**GPU Type**:  1080Ti
**Nvidia Driver Version**:  418
**CUDA Version**:  10.2

**Comment by ttyio** [comment]
Hello @xusk , thanks for reporting.
Did you create separate IExecutionContext for the multiple threads?

**Comment by xusk** [comment]
> Did you create separate IExecutionContext for the multiple threads?
yes

**Comment by ttyio** [comment]
@xusk , could you help to verify if the issue still repro with 7.2, if so could you send out a repro for further triage? thanks!

**Comment by xusk** [comment]
> @xusk , could you help to verify if the issue still repro with 7.2, if so could you send out a repro for further triage? thanks!

still error

**Comment by ttyio** [comment]
@xusk , could you share a repro? thanks!

**Comment by xusk** [comment]
> > @xusk , could you help to verify if the issue still repro with 7.2, if so could you send out a repro for further triage? thanks!
> 
> still error

like this https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5.cpp

but I use in multi-threading

**Comment by ttyio** [comment]
Hello @xusk , we did not see any multi thread issue in our internal test, so we need you provide repro for further triage. Thanks for understanding.

**Comment by xusk** [comment]
> Hello @xusk , we did not see any multi thread issue in our internal test, so we need you provide repro for further triage. Thanks for understanding.

send  ttyio@hotmail.com

**Comment by ttyio** [comment]
Hello @xusk , email received, have not look into it yet.
I see you close the issue, have you root cause it? thanks

**Comment by xusk** [comment]
> Hello @xusk , email received, have not look into it yet.
> I see you close the issue, have you root cause it? thanks

yeah , I  solve it

when  in python "import tensorrt as trt "  it's error , but I don't know why

and  I really don't need it , it's ok now

**Comment by phamdat09** [comment]
@xusk Hello, I have the same issues. How did you solve it ?? Thanks

**Comment by Nextheartbeat** [comment]
Hello, if it is encapsulated as a class, use the service to remove the problem will appear

**Comment by 489397771** [comment]
@phamdat09 @xusk  Hello, I have the same issues too. How did you solve it ?? Thanks

**Comment by xusk** [comment]
> @phamdat09 @xusk Hello, I have the same issues too. How did you solve it ?? Thanks

send xushoukui@gmail.com ?

**Comment by karpaoi** [comment]
@489397771 @phamdat09 Hello @xusk. I also have this problem. How did you solve it? Much appreciate any kind of help.

**Comment by phamdat09** [comment]
@karpaoi As I remember, the input of some plugins is dynamic input. Then, you have to change the code to adapt it

**Comment by hyperfraise** [comment]
Same issue when trying to optimize https://github.com/derronqi/yolov7-face

No noticeable errors, but I see this print during the inference, and outputs are all 0 :  
[10/31/2023-17:49:53] [TRT] [E] 1: [slice.cu::launchNaiveSliceImpl::247] Error Code 1: Cuda Runtime (invalid resource handle)
