### ISSUE TITLE
Confusion of execute_async of Python API

### ISSUE THREAD

**Issue by RizhaoCai** [NVIDIA/TensorRT#930]
## Description
I have some confusion about the context. execute function.

According to the TensorRT Python API document, there are `execute` and `execute_async`.
![image](https://user-images.githubusercontent.com/37952703/100312457-5719df00-2fed-11eb-9c87-8fde535d9772.png)

However, according to [here](https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html#optimize-python)
![image](https://user-images.githubusercontent.com/37952703/100312484-70229000-2fed-11eb-9f10-acd67bbb075b.png).

| Inference time should be nearly identical when execute or execute_async is called through the Python API as opposed to the C++ API. 

Q1: I understand what execute and execute_async are doing. But why the time is identical through the Python API. Is it that `execute_async` is faster than `execute` through C++ API? Why?

Q2: Also, there are `execute_async` and `execute_async_v2`. What are the difference between them? The [document ](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/ExecutionContext.html?highlight=execute_async#tensorrt.IExecutionContext.execute_async_v2)does not tell the difference clearly

![image](https://user-images.githubusercontent.com/37952703/100312615-c2fc4780-2fed-11eb-920b-81cfce181d1e.png)

**Comment by ttyio** [comment]
+ @pranavm-nvidia  for help, thanks!

**Comment by pranavm-nvidia** [comment]
The reason is that there's a bug where `execute_async`/`execute_async_v2` don't release the GIL, so they effectively behave like blocking calls. This will be fixed in the next release.

**Comment by ttyio** [comment]
Thanks @pranavm-nvidia .
Hello @RizhaoCai , for the Q2, the difference between V1 and V2 API is that we use full dimensions in the V2 API, the batch is implicit dim in the input tensor shape, there is no extra `batch_size`  param to set.

**Comment by RizhaoCai** [comment]
> Thanks @pranavm-nvidia .
> Hello @RizhaoCai , for the Q2, the difference between V1 and V2 API is that we use full dimensions in the V2 API, the batch is implicit dim in the input tensor shape, there is no extra `batch_size` param to set.



> The reason is that there's a bug where `execute_async`/`execute_async_v2` don't release the GIL, so they effectively behave like blocking calls. This will be fixed in the next release.

@ttyio @pranavm-nvidia 

Noted. Thank you.

**Comment by minhhoangbui** [comment]
@ttyio Can I assume that `v1` is faster than `v2` since the batch-size is mentioned explicitly

**Comment by ttyio** [comment]
Hello @minhhoangbui , there is no performance difference, and for the latest ONNX parsers we only support implicit batch-size.

**Comment by pranavm-nvidia** [comment]
> Hello @minhhoangbui , there is no performance difference, and for the latest ONNX parsers we only support implicit batch-size.

@ttyio I think you meant **ex**plicit batch-size?

**Comment by ttyio** [comment]
@pranavm-nvidia , thanks for correcting, yes explicit batch-size ;-)

**Comment by minhhoangbui** [comment]
@ttyio @pranavm-nvidia it's a bit confusing to me. Do you mean that we should use `execute_async` and `execute_async_v2` is outdated

**Comment by ttyio** [comment]
@minhhoangbui 
explicit batch means full dims, execute_async_v2 
implicit batch means execute_async

**Comment by mfoglio** [comment]
> The reason is that there's a bug where `execute_async`/`execute_async_v2` don't release the GIL, so they effectively behave like blocking calls. This will be fixed in the next release.

Hi @pranavm-nvidia ! Could this be the reason why I don't see a difference between the execution time and CPU usage between flags SCHED_YIELD and SCHED YIELD? More details here ( https://forums.developer.nvidia.com/t/pycuda-how-to-enable-sched-yield-to-reduce-cpu-usage/165512 ) Thanks!

**Comment by pranavm-nvidia** [comment]
@mfoglio It's hard to say without seeing your inference code. Would you be able to share a snippet?

**Comment by mfoglio** [comment]
Well, I am basically using this code https://stackoverflow.com/a/56668893/1315621 . If you need a runnable code I can come up with it. Let me know. And thanks for you availability!

**Comment by pranavm-nvidia** [comment]
Sorry, I need to amend my [original comment](https://github.com/NVIDIA/TensorRT/issues/930#issuecomment-742591850):

> The reason is that there's a bug where execute_async/execute_async_v2 don't release the GIL, so they effectively behave like blocking calls. This will be fixed in the next release.

In fact execute_async/execute_async_v2 do *not* behave like blocking calls - they do hold the GIL longer than they need to, but this should only affect cases where you use multiple threads. The bigger problem would be in the synchronous calls which would hold the GIL for the entire duration of inference.

Additionally, if you're only using 1 context, I wouldn't expect execution time to be affected by async vs. synchronous inference, since you wouldn't be overlapping multiple inferences. 
It is strange that you're seeing a busy wait on the CPU though. Are you sure this isn't coming from the `stream.synchronize()` rather than the `execute_async()`?

**Comment by mfoglio** [comment]
Thank @pranavm-nvidia . I am using multiple threads (therefore multiple contexts) calling tensorRT inference from multiple threads. Yes, I do believe that the CPU high usage is caused by `stream.synchronize()` but I don't know if that is related to `execute_async()`

**Comment by pranavm-nvidia** [comment]
@mfoglio You may want to look at [this comment](https://github.com/NVIDIA/TensorRT/issues/999#issuecomment-756605632). I think what you're seeing is probably similar.

**Comment by mfoglio** [comment]
Hi @pranavm-nvidia  and thanks for the support last time. I am noticing strange behavior, possibly a bug.

Shouldn't 
```
context.execute(bindings=bindings, batch_size=len(batch_input_image))
```
and 
```
context.execute_async(bindings=bindings, stream_handle=stream.handle, batch_size=len(batch_input_image))
stream.synchronize()
```
be equivalent?

I am using cupy arrays as input buffers and I get different results
```
        cp.copyto(cuda_inputs[0], input_images). # copy buffe
        # Make self the active context, pushing it on top of the context stack.
        self.cfx.push()
        # Execution (see two options above)
        # ...
         self.cfx.pop()
output_images = cuda_outputs[0].copy(). #copy back results
```
  The problem is that sometimes `output_images` contain wrong results if I use the async call as if I copied the array before the execution was completed. Furthermore, the entire process is run within a thread lock to be sure no other operations are happening in the buffers.

**Comment by pranavm-nvidia** [comment]
@mfoglio Is `cfx` the CUDA context? If so, wouldn't you want to do that before you allocate?

Also how are you constructing the stream? From the [cupy docs](https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.Stream.html#cupy-cuda-stream), it looks like they expose the underlying CUDA stream in a `ptr` attribute rather than `handle`

**Comment by mfoglio** [comment]
Thank you for your extremely fast answer. I tried to use both a pycuda stream and a copy stream. You are right, when using the cupy Stream I use `stream.ptr`.

`self.cfx` is a CUDA context:
```
self.device = cuda.Device(0)
self.cfx = self.device.make_context() 
```

The memory is already allocated on the GPU, with `cp.copyto(cuda_inputs[0], input_images)` I just copy the array into the buffer. Is that correct?
```
        for binding in engine:
            shape = [engine.max_batch_size, *engine.get_binding_shape(binding)]
            dtype = trt.nptype(engine.get_binding_dtype(binding))
            # Allocate host and device buffers
            cuda_mem = cp.zeros(shape=shape, dtype=dtype)  # cuda.mem_alloc(host_mem.nbytes)
            # Append the device buffer to device bindings.
            bindings.append(cuda_mem.data.ptr)
            # Append to the appropriate list.
            if engine.binding_is_input(binding):
                cuda_inputs.append(cuda_mem)
            else:
                cuda_outputs.append(cuda_mem)
```

**Comment by pranavm-nvidia** [comment]
@mfoglio When you push the CUDA context onto the stack, it would invalidate allocations/stream from the previous context. 

IMO it would be better to drop `pycuda` here and use `cupy` exclusively (or vice-versa).

**Comment by mfoglio** [comment]
Thank you. I didn't know I could use TensorRT without pycuda. I will eliminate the context too.

Question: without the context, can I still use different TensorRT models within the same Python application?

**Comment by pranavm-nvidia** [comment]
Yeah, should be fine to use multiple TRT models. If you want parallelism, you can create separate CUDA streams for each

**Comment by mfoglio** [comment]
Man, you are a life savior! Thank you so much!

**Comment by mfoglio** [comment]
@pranavm-nvidia when using cupy, should I need to keep some "fixed" preallocated buffers on the GPU or could I just run the model on arbitrary cupy arrays (of the correct shape and type) using their pointer such as `context.execute_async(bindings=[int(d_input), int(d_output)], stream_handle=stream.handle)` where the `d_input` and `d_output` are cupy arrays?

**Comment by pranavm-nvidia** [comment]
@mfoglio Should be fine to use arbitrary cupy arrays

**Comment by mfoglio** [comment]
Hey @pranavm-nvidia , following up the conversation, I need your help again. I tried to run multiple models within the same context but I believe something wrong is happening and they can't run together (I don't know why, I see many `pycuda.cuda.autoinit()` in the code, maybe this?). Also, the two models are running in different threads to this possibly interfere with the contexts (not sure again). I have finally managed to make both the models running by creating one context for each, and by pushing and popping the context before running each of them:
```
        self.cfx.push()
        context.execute_async(bindings=bindings, stream_handle=stream.ptr, batch_size=len(batch_input_image))
        stream.synchronize()
        self.cfx.pop()
```
As I was saying, each model has its own context `self.cfx`.

Now, since the code is running in parallel, I am wondering what would happen if the first thread T1 push its context, the second thread T2 push its context, and then T1 run its model `context.execute_async()`. Would T1 try to run the model in the context of T2, therefore, leading to a crash?

**Comment by pranavm-nvidia** [comment]
@mfoglio Are you still using cupy? If so, can you try removing all mentions of `pycuda` (including `autoinit`) from your code? I don't see any reason you wouldn't be able to run multiple models in a single CUDA context, even with multiple threads.

**Comment by mfoglio** [comment]
You are right. Removing all the `import pycuda.autoinit` solved the issue. Thanks again, man. Really, thanks.

**Comment by mfoglio** [comment]
@pranavm-nvidia I am still here fighting synchronization issues. The following code does not wait at all if I see the `cp.cuda.Stream(non_blocking=True)` while it seems to work if `non_blocking=False` - actually, I am not yet sure it is working even in that other case (it seems often the model is returning some detections from the previous frames... I am not sure if that could be a synch issue).
But why shouldn't it work with `non_blocking=True`?
```
        # Select stream
        stream.use()
        # Copy cupy array to the buffer
        input_images = cp.array(batch_input_image)
        cp.copyto(cuda_inputs[0], input_images)
        # Run inference.
        context.execute_async(bindings=bindings, stream_handle=stream.ptr, batch_size=len(batch_input_image))
        # Copy results from the buffer
        output_images = cuda_outputs[0].copy()
        # Split results into batch
        list_output = cp.split(output_images, indices_or_sections=len(batch_input_image), axis=0)
        # Squeeze output arrays to remove axis of length one
        list_output = [cp.squeeze(array) for array in list_output]
        # Synchronize the stream
        stream.synchronize()
```
The input data, `batch_input_image`, is received as parameter from the function. The caller has obtained `batch_input_image` by calling the following function
```
        with cp.cuda.Stream():
            return [cp.array(np_array) for np_array in batch]
```
Sorry for bothering you again. And thank you for your help.

**Comment by mfoglio** [comment]
@pranavm-nvidia I am still here fighting synchronization issues. The following code does not wait at all if I set the `cp.cuda.Stream(non_blocking=True)` while it works with `non_blocking=False`.
Why shouldn't it work with `non_blocking=True`? I checked the input data and it is fine. But it ends up with my model returning random detections (random data).
```
        # Select stream
        stream.use()
        # Copy cupy array to the buffer
        input_images = cp.array(batch_input_image)
        cp.copyto(cuda_inputs[0], input_images)
        # Run inference.
        context.execute_async(bindings=bindings, stream_handle=stream.ptr, batch_size=len(batch_input_image))
        # Copy results from the buffer
        output_images = cuda_outputs[0].copy()
        # Split results into batch
        list_output = cp.split(output_images, indices_or_sections=len(batch_input_image), axis=0)
        # Squeeze output arrays to remove axis of length one
        list_output = [cp.squeeze(array) for array in list_output]
        # Synchronize the stream
        stream.synchronize()
```

Sorry for bothering you again. And thank you for your help.

**Comment by mfoglio** [comment]
Hi @pranavm-nvidia , I am working on the same code again and I still can’t find an explanation for the code above. I even tried to copy results from buffer using `cp.copyto` with no success.

**Comment by pranavm-nvidia** [comment]
@mfoglio Not entirely sure why that is. Are any of the `cupy` operations (e.g. the memcpys) running on the default stream?

**Comment by mfoglio** [comment]
@pranavm-nvidia could check here https://github.com/cupy/cupy/issues/6104#issue-1055041809 ?
