### ISSUE TITLE
can I use fp16 data as input

### ISSUE THREAD

**Issue by xufuzhi** [NVIDIA/TensorRT#934]
I build an engine with fp16 data type.But I get wrong output if I feed some fp16 input data, why I need feed fp32 type input when I have a fp16 type engine?
Thank you!

**Comment by nvpohanh** [comment]
You can set the `dtype` of the input/output tensors: https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/LayerBase.html#tensorrt.ITensor

**Comment by rajeevsrao** [comment]
@xufuzhi closing based on the documentation link provided by @nvpohanh. Please go through our developer guide and know if you have further questions.
