### ISSUE TITLE
input_1: dynamic input is missing dimensions in profile 0

### ISSUE THREAD

**Issue by za13** [NVIDIA/TensorRT#939]
I created an NN I trained in Python, converted it to ONNX, and now am trying to run that with TensorRT in C++. The C++ code I have is below (it is based on the code in https://www.learnopencv.com/how-to-run-inference-using-tensorrt-c-api/)

    #include <iostream>
    #include <fstream>
    #include <NvInfer.h>
    #include <NvInferRuntime.h>
    #include <memory>
    #include <NvOnnxParser.h>
    #include <vector>
    #include <cuda_runtime_api.h>
    #include <opencv2/imgcodecs.hpp>
    #include <opencv2/core/cuda.hpp>
    #include <opencv2/core.hpp>
    #include <algorithm>
    #include <numeric>

    class Logger : public nvinfer1::ILogger
    {
    public:
        void log(Severity severity, const char* msg) override {
            // remove this 'if' if you need more logged info
            if ((severity == Severity::kERROR) || (severity == Severity::kINTERNAL_ERROR)) {
                std::cout << msg << "\n";
            }
        }
    } gLogger;

    struct TRTDestroy
    {
        template <class T>
        void operator()(T* obj) const
        {
            if (obj)
            {
                obj->destroy();
            }
        }
    };

    template <class T>
    using TRTUniquePtr = std::unique_ptr<T, TRTDestroy>;

    size_t getSizeByDim(const nvinfer1::Dims& dims)
    {
        size_t size = 1;
        for (size_t i = 0; i < dims.nbDims; ++i)
        {
            size *= dims.d[i];
        }
        return size;
    }

    std::vector<std::string> getClassNames(const std::string& imagenet_classes)
    {
        std::ifstream classes_file(imagenet_classes);
        std::vector<std::string> classes;
        if (!classes_file.good())
        {
            std::cerr << "ERROR: can't read file with classes names.\n";
            return classes;
        }
        std::string class_name;
        while (std::getline(classes_file, class_name))
        {
            classes.push_back(class_name);
        }
        return classes;
    }

    void preprocessImage(const std::string& image_path, float* gpu_input, const nvinfer1::Dims& dims)
    {
        cv::Mat frame = cv::imread(image_path);
        if (frame.empty())
        {
            std::cerr << "Input image " << image_path << " load failed\n";
            return;
        }
        cv::cuda::GpuMat gpu_frame;
        gpu_frame.upload(frame);
        int channels=1;
        auto input_width = dims.d[1];
        auto input_height = dims.d[0];
        auto input_size = cv::Size(input_width, input_height);
        cv::cuda::GpuMat resized=gpu_frame;
        cv::cuda::GpuMat flt_image;
        resized.convertTo(flt_image, CV_32FC1, 1.f / 255.f);
        std::vector<cv::cuda::GpuMat> chw;
        for (size_t i = 0; i < channels; ++i)
        {
            chw.emplace_back(cv::cuda::GpuMat(input_size, CV_32FC1, gpu_input + i * input_width * input_height));
        }
        cv::split(flt_image, chw);
    }

    void postprocessResults(float *gpu_output, const nvinfer1::Dims &dims, int batch_size)
    {
        std::vector<float> cpu_output(getSizeByDim(dims) * batch_size);
        cudaMemcpy(cpu_output.data(), gpu_output, cpu_output.size() * sizeof(float), cudaMemcpyDeviceToHost);

        auto cols = dims.d[1];
        auto rows = dims.d[0];
        cv::Mat Finalmat = cv::Mat(rows, cols, CV_32FC1); 
        memcpy(Finalmat.data, cpu_output.data(), cpu_output.size()*sizeof(float));
        Finalmat.convertTo(Finalmat, CV_8UC3, 255.0);
        cv::imwrite("/tensorRT.bmp", Finalmat);
    }

    void parseOnnxModel(const std::string& model_path, TRTUniquePtr<nvinfer1::ICudaEngine>& engine,
                        TRTUniquePtr<nvinfer1::IExecutionContext>& context)
    {
        nvinfer1::IBuilder *builder = nvinfer1::createInferBuilder(gLogger);
        const auto explicitBatch = 1U << static_cast<uint32_t>(nvinfer1::NetworkDefinitionCreationFlag::kEXPLICIT_BATCH);
        nvinfer1::INetworkDefinition *network = builder->createNetworkV2(explicitBatch);
        TRTUniquePtr<nvonnxparser::IParser> parser{nvonnxparser::createParser(*network, gLogger)};
        
        // parse ONNX
        if (!parser->parseFromFile(model_path.c_str(), static_cast<int>(nvinfer1::ILogger::Severity::kINFO)))
        {
            std::cerr << "ERROR: could not parse the model.\n";
            return;
        }

        //create Config to configure engine parameters such as max memory or set FP16 mode
        TRTUniquePtr<nvinfer1::IBuilderConfig> config{builder->createBuilderConfig()};

        nvinfer1::IOptimizationProfile* profile = builder->createOptimizationProfile();
        profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims3(3,100,200));
        profile->setDimensions("foo", nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims3(3,1024,1024));
        profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims3(3,4096,4096));

        config->addOptimizationProfile(profile);
        // allow TensorRT to use up to 1GB of GPU memory for tactic selection.
        config->setMaxWorkspaceSize(1ULL << 30);
        // use FP16 mode if possible
        if (builder->platformHasFastFp16())
        {
            config->setFlag(nvinfer1::BuilderFlag::kFP16);
        }
        // we have only one image in batch
        builder->setMaxBatchSize(1);
        // generate TensorRT engine optimized for the target platform
        engine.reset(builder->buildEngineWithConfig(*network, *config));
        context.reset(engine->createExecutionContext());
    }

    // main pipeline ------------------------------------------------------------------------------------------------------
    int main(int argc, char* argv[])
        if (argc < 3)
        {
            std::cerr << "usage: " << argv[0] << " [model_name].onnx [image_name].jpg\n";
            return -1;
        }
        std::string model_path(argv[1]);
        std::string image_path(argv[2]);
        int batch_size = 1;

        TRTUniquePtr<nvinfer1::ICudaEngine> engine{nullptr};
        TRTUniquePtr<nvinfer1::IExecutionContext> context{nullptr};
        parseOnnxModel(model_path, engine, context);

        std::vector<nvinfer1::Dims> input_dims; // we expect only one input
        std::vector<nvinfer1::Dims> output_dims; // and one output

        std::vector<void*> buffers(engine->getNbBindings()); // buffers for input and output data
        for (size_t i = 0; i < engine->getNbBindings(); ++i)
        {
            auto binding_size = getSizeByDim(engine->getBindingDimensions(i)) * batch_size * sizeof(float);
            cudaMalloc(&buffers[i], binding_size);
            if (engine->bindingIsInput(i))
            {
                input_dims.emplace_back(engine->getBindingDimensions(i));
            }
            else
            {
                output_dims.emplace_back(engine->getBindingDimensions(i));
            }
        }
        if (input_dims.empty() || output_dims.empty())
        {
            std::cerr << "Expect at least one input and one output for network\n";
            return -1;
        }

        // preprocess input data
        preprocessImage(image_path, (float *) buffers[0], input_dims[0]);
        // inference - "enqueue" asynchronously executes inference on a batch. 
        context->enqueue(batch_size, buffers.data(), 0, nullptr);
        // postprocess results
        postprocessResults((float *) buffers[1], output_dims[0], batch_size);

        for (void* buf : buffers)
        {
            cudaFree(buf);
        }
        return 0;
    }

For training the NN, creating the .keras and ONNX files, I used Docker container 19.10, which has CUDA 10.1 and Ubuntu 18 because according to this source, if I wanted to use the GPU with TF then I needed CUDA 10.1: https://www.tensorflow.org/install/source#gpu

When I ran ./trt_sample owl.onnx testImage.bmp, I got this error:

    ----------------------------------------------------------------
    Input filename:   owl.onnx
    ONNX IR version:  0.0.7
    Opset version:    12
    Producer name:    keras2onnx
    Producer version: 1.7.0
    Domain:           onnxmltools
    Model version:    0
    Doc string:       
    ----------------------------------------------------------------

    	WARNING: ONNX model has a newer ir_version (0.0.7) than this parser was built against (0.0.3).
    While parsing node number 1 [Conv]:
    ERROR: ModelImporter.cpp:296 In function importModel:
    [5] Assertion failed: tensors.count(input_name)
    ERROR: could not parse the model.
    Segmentation fault (core dumped)

If I then tried to run the ONNX file and TensorRT with Docker container 20.03, which has CUDA 10.2 and TensorRT 7.0.0, then I get this error:

	----------------------------------------------------------------
    Input filename:   owl.onnx
    ONNX IR version:  0.0.7
    Opset version:    12
    Producer name:    keras2onnx
    Producer version: 1.7.0
    Domain:           onnxmltools
    Model version:    0
    Doc string:       
    ----------------------------------------------------------------
    input_1: dynamic input is missing dimensions in profile 0.
    Network validation failed.
    Segmentation fault (core dumped)

When I ran the model with `trtexec`, it seems to work successfully. The output from trtexec is: https://drive.google.com/file/d/1RdaoUFZ4KmQH3Iv-opRf87DRnrMyzJ9g/view?usp=sharing

ONNX File at https://drive.google.com/file/d/1GH4PBS1Y7vrJgnOMGnGGYmsAnUBcyvXX/view?usp=sharing

**Comment by pranavm-nvidia** [comment]
Looks like your code doesn't set dimensions for `input_1`:
```
    nvinfer1::IOptimizationProfile* profile = builder->createOptimizationProfile();
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims3(3,100,200));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims3(3,1024,1024));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims3(3,4096,4096));
```
Do you need to change "foo" -> "input_1"?

**Comment by za13** [comment]
so just change `foo` to `input_1`? I wasn't sure what to do with the code. I just had "foo" there because I copied/pasted that part from another post I read that had a similar error to see if it would work or not

**Comment by pranavm-nvidia** [comment]
Right, the first argument is supposed to be the input name.

**Comment by za13** [comment]
now I get the error `input_1: number of dimensions is 4 but profile 0 has 3`

so I changed 

    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims3(3,100,200));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims3(3,1024,1024));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims3(3,4096,4096));

to 

    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims4(1,100,200,1));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims4(1,1024,1024,1));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims4(1,4096,4096,1));

because I want to perform inference on images that can range from size 100x200 to 4096x4096

but if I run it on a 1024x1024 image, then I get: `input_1: for dimension number 1 in profile 0 does not match network definition (got min=100, opt=1024, max=4096), expected min=opt=max=1024)`

so how can I have the code accept images ranging from size 100x200 to 4096x4096?

if I change


    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims4(1,100,200,1));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims4(1,1024,1024,1));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims4(1,4096,4096,1));

to


    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMIN, nvinfer1::Dims4(1,1024,1024,1));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kOPT, nvinfer1::Dims4(1,1024,1024,1));
    profile->setDimensions("foo", nvinfer1::OptProfileSelector::kMAX, nvinfer1::Dims4(1,1024,1024,1));

then I get this error:

    terminate called after throwing an instance of 'cv:Exception'. what() OpenCV(4.5.1-pre) /workspace/opencv/modules/core/src/matrix_wrap.cpp:112: error: (-213: The function/feature is not implemented (You should explicitly call download method for cuda::GpuMat object in function 'getMat_'

**Comment by pranavm-nvidia** [comment]
What are the input dimensions of your ONNX model? From the error message, it sounds like the second dimension isn't dynamic.

Regarding the OpenCV error, my best guess is that you can't use one of the processing functions (e.g. maybe `convertTo` or `cv::split`) on a `GpuMat` in `preprocessImage`?

**Comment by za13** [comment]
looks like it was because I had

    cv::split(flt_image, chw);

instead of 

    cuda::cv::split(flt_image, chw);

that seemed to fix the problem. However, now I get this error:
  
    Parameter check failed at: engine.cpp::enqueue::298, condition: bindings[x] != nullptr

Why do I get this error when I already have the below in the code?

    nvinfer1::IBuilder *builder = nvinfer1::createInferBuilder(gLogger);
    const auto explicitBatch = 1U << static_cast<uint32_t>(nvinfer1::NetworkDefinitionCreationFlag::kEXPLICIT_BATCH);

**Comment by pranavm-nvidia** [comment]
That error is coming from this line:
```
context->enqueue(batch_size, buffers.data(), 0, nullptr);
```
It sounds like `buffers` has a `nullptr` in it somewhere. That could be because `cudaMalloc` is failing (you can check the return value). 

Also, since it looks like you want explicit batch, synchronous inference, this line should probably be:
```
context->executeV2(buffers.data());
```

**Comment by za13** [comment]
how can I check the return value of `cudaMalloc`?

I only need to run inference on 1 image at a time. So not sure if synchronous or asynchronous is better?

if I replace `context->enqueue(batch_size, buffers.data(), 0, nullptr);` with `context->executeV2(buffers.data());` then I get

    parameter check failed at engine.cpp::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)

**Comment by pranavm-nvidia** [comment]
> how can I check the return value of cudaMalloc?

You can check if the return value is `cudaSuccess`:
```
auto status = cudaMalloc(...)
if (status != cudaSuccess)
{
    // Handle failure here
}
```

> I only need to run inference on 1 image at a time. So not sure if synchronous or asynchronous is better?

With how it's currently written, I don't think asynchronous execution would offer any advantage.


Adding `context->setBindingDimensions` is the right thing to do. Do you see the same error if you run `trtexec` with `--fp16`?

The other possibility is that the sizes are wrong when you allocate the input/output memory:
```
cudaMalloc(&buffers[i], binding_size);
```
You can check `binding_size` to make sure it matches what you expect.

**Comment by za13** [comment]
seems like cudaMalloc is working. The `binding_size` returns 18446744073705357312

if I try `./trtexec --onnx=owl.onnx --shapes=input:1x1024x1024x1 --fp16`, then it passes

**Comment by pranavm-nvidia** [comment]
The `binding_size` seems like an integer underflow is happening. I would've expected the size to be `1 * 1024 * 1024 * 1 *4 = 4194304`. Most likely `engine->getBindingDimensions(i)` has some -1s in it to indicate dynamic dimensions. You may want to use the context dimensions instead.

**Comment by za13** [comment]
how do I use context dimensions instead? How would I modify the code?

**Comment by pranavm-nvidia** [comment]
When you compute the binding size:
```
        auto binding_size = getSizeByDim(engine->getBindingDimensions(i)) * batch_size * sizeof(float);
```
you can change `engine->getBindingDimensions(i)` to `context->getBindingDimensions(i)`. Make sure you're setting the input dimensions (`context->setBindingDimensions`) prior to this call though.

**Comment by za13** [comment]
you mean change

	for (size_t i = 0; i < engine->getNbBindings(); ++i)
    {
        auto binding_size = getSizeByDim(engine->getBindingDimensions(i)) * batch_size * sizeof(float);
        cudaMalloc(&buffers[i], binding_size);
        if (engine->bindingIsInput(i))
        {
            input_dims.emplace_back(engine->getBindingDimensions(i));
        }
        else
        {
            output_dims.emplace_back(engine->getBindingDimensions(i));
        }
    }

to this?

	for (size_t i = 0; i < engine->getNbBindings(); ++i)
    {
        if (engine->bindingIsInput(i))
        {
            input_dims.emplace_back(engine->getBindingDimensions(i));
        }
        else
        {
            output_dims.emplace_back(engine->getBindingDimensions(i));
        }

        auto binding_size = getSizeByDim(engine->getBindingDimensions(i)) * batch_size * sizeof(float);
        auto status = cudaMalloc(&buffers[i], binding_size);
    }

when I do that `binding_size` is still 18446744073705357312 and I get 

    parameter check failed at engine.cpp::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)

**Comment by pranavm-nvidia** [comment]
And this is after `context->setBindingDimensions` right? You may want to use a debugger to figure out why `binding_size` is wrong.

**Comment by za13** [comment]
it seems like the problem is that `input_dims[0].d[i]` is -1 for `i=1` in the loop `for (size_t i = 0; i < engine->getNbBindings(); ++i)`

Also, at the line `auto binding_size = getSizeByDim(context->getBindingDimensions(i)) * batch_size * sizeof(float);`, the code shows that `context->getBindingDimensions(i).nbDims` is -1

**Comment by pranavm-nvidia** [comment]
Sounds like your model has dynamic batch, so it's expected that `engine->getBindingDimensions()` will include -1s to indicate dynamic dimensions. 

Since you want the runtime input dimensions, you should probably use `context->getBindingDimensions()` for `input_dims` as well.

As for `context->getBindingDimensions(i).nbDims` being `-1`, I'm really not sure why that would be the case. Can you check if `context->allInputDimensionsSpecified()` return `true` prior to getting the dimensions?

**Comment by za13** [comment]
I set `context->getBindingDimensions()` for `input_dims`

`context->allInputDimensionsSpecified()` returns `False`

**Comment by pranavm-nvidia** [comment]
Does your network have multiple inputs? Otherwise, are you sure you're calling `context->setBindingDimensions()` _prior_ to the calls to `context->getBindingDimensions()`?

It may help to look through some of the [examples](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleDynamicReshape/sampleDynamicReshape.cpp#L335)

**Comment by za13** [comment]
I didn't have `setBindingDimensions` before `getBindingDimensions`

I changed the code inside `main` so that it is now:

    int main(int argc, char* argv[])
        
        std::string model_path(argv[1]);
        std::string image_path(argv[2]);
        int batch_size = 1;

        TRTUniquePtr<nvinfer1::ICudaEngine> engine{nullptr};
        TRTUniquePtr<nvinfer1::IExecutionContext> context{nullptr};
        parseOnnxModel(model_path, engine, context);

        std::vector<nvinfer1::Dims> input_dims; // we expect only one input
        std::vector<nvinfer1::Dims> output_dims; // and one output

        context->setBindingDimensions(0, nvinfer1::Dims4(1,1024,1024,1));

        std::vector<void*> buffers(engine->getNbBindings());

        context->executeV2(buffers.data());
        
        ...


    }

I now get the error

    engine.cpp (902) Cuda error in executeInternal: 700 (an illegal memory access was encountered)

**Comment by za13** [comment]
can you answer my last question?

**Comment by pranavm-nvidia** [comment]
From your newest code, it doesn't seem like you're allocating `buffers`? You'd need to `cudaMalloc` them and then memcpy your input data.

**Comment by za13** [comment]
you mean something like this?

    std::vector<void*> buffers(engine->getNbBindings());

    for (size_t i = 0; i < engine->getNbBindings(); ++i)
    {
        auto binding_size = getSizeByDim(context->getBindingDimensions(i)) * batch_size * sizeof(float);
        std::cout<<binding_size<<"\n";

        auto status = cudaMalloc(&buffers[i], binding_size);
        cudaMemcpy(buffers[i], input_dims[i], batch_size*sizeof(float), cudaMemcpyDeviceToHost);
    }

    context->executeV2(buffers.data());

that gives the error `cannot convert __gnu_cxx::__alloc_traits<std::allocator<nvinfer1:Dims>>::value_type {aka nvinfer1::Dims} to 'const void*' for argument 2 to cudaError_t cudaMemcpy(void*, const void*, size_t, cudaMemcpyKind)`

**Comment by pranavm-nvidia** [comment]
Right, because `input_dims` is a `vector<Dims>`. From your earlier code, it seems like you wanted to use `preprocessImage` to copy the data to the device? You should be able to use that here too.

**Comment by rajeevsrao** [comment]
Thanks for the answers @pranavm-nvidia. Closing this issue unless you have more questions @za13

**Comment by za13** [comment]
This issue is not resolved

I tried to simplify the code by using:

	from __future__ import print_function

	import warnings

	import matplotlib.pyplot as plt
	import numpy as np
	import pandas as pd
	from imutils.paths import list_images
	from keras import backend as K
	from keras.callbacks import CSVLogger
	from keras.layers import *
	from keras.models import Model
	from keras.optimizers import Adam
	from scipy.io import loadmat
	from scipy.misc import imread
	from skimage.io import imsave
	from skimage.transform import resize

	from scipy.io import loadmat
	import cv2
	import tensorflow as tf

	Ny=1024
	target_size = (Ny, Ny)

	warnings.filterwarnings('ignore')

	LR= 1e-4
	E, BS = 2,4 


	def get_unet(img_rows, img_cols):
	    inputs = Input((img_rows, img_cols, 1))
	    conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
	    conv1 = BatchNormalization()(conv1)
	    conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(conv1)
	    conv1 = BatchNormalization()(conv1)
	    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

	    conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(pool1)
	    conv2 = BatchNormalization()(conv2)
	    conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(conv2)
	    conv2 = BatchNormalization()(conv2)
	    pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

	    conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool2)
	    conv3 = BatchNormalization()(conv3)
	    conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv3)
	    conv3 = BatchNormalization()(conv3)
	    pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)

	    conv4 = Conv2D(256, (3, 3), activation='relu', padding='same')(pool3)
	    conv4 = BatchNormalization()(conv4)
	    conv4 = Conv2D(256, (3, 3), activation='relu', padding='same')(conv4)
	    conv4 = BatchNormalization()(conv4)
	    pool4 = MaxPooling2D(pool_size=(2, 2))(conv4)

	    conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
	    conv5 = BatchNormalization()(conv5)
	    conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(conv5)
	    conv5 = BatchNormalization()(conv5)
	    
	    conv5 = Dropout(0.5)(conv5)

	    up6 = concatenate([UpSampling2D(size=(2, 2))(conv5), conv4], axis=3)
	    conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(up6)
	    conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(conv6)

	    up7 = concatenate([UpSampling2D(size=(2, 2))(conv6), conv3], axis=3)
	    conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(up7)
	    conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv7)

	    up8 = concatenate([UpSampling2D(size=(2, 2))(conv7), conv2], axis=3)
	    conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(up8)
	    conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(conv8)

	    up9 = concatenate([UpSampling2D(size=(2, 2))(conv8), conv1], axis=3)
	    conv9 = Conv2D(32, (3, 3), activation='relu', padding='same')(up9)
	    conv9 = Conv2D(32, (3, 3), activation='relu', padding='same')(conv9)


	    conv10 = Conv2D(1, (1, 1), activation='sigmoid')(conv9)
	    '''
	    def get_unet(img_rows, img_cols):
	        inputs = Input((img_rows, img_cols, 1))
	        conv9=inputs

	        conv10 = Conv2D(1, (1, 1), activation='sigmoid')(conv9)
	    '''    
	    
	    model = Model(inputs=[inputs], outputs=[conv10])
	    
	    model.compile(optimizer=Adam(lr=LR), 
	                      loss='binary_crossentropy',
	                      metrics=['binary_crossentropy'])


	    return model


	train_images=np.zeros([1, 1024,1024,1], dtype=float)
	annot_train=np.zeros([1, 1024,1024,1], dtype=float)
	test_images=np.zeros([1, 1024,1024,1], dtype=float)
	annot_test=np.zeros([1, 1024,1024,1], dtype=float)

	img = cv2.imread('owlResized.bmp', 0)/255.0 
	label = cv2.imread('owlResized.bmp', 0)/255.0
	train_images[0,:,:,0], annot_train[0,:,:,0] =img, label
	test_images[0,:,:,0], annot_test[0,:,:,0] =img, label

	print("finished reading")
	C = np.concatenate([annot_test, annot_train])
	I = np.concatenate([test_images, train_images])

	unet = get_unet(Ny, Ny)
	filepath="W-E_{epoch:02d}-L_{loss:.6f}"+outName+".h5"
	history = unet.fit(I, C, verbose=2, epochs=E, batch_size=BS, validation_split=0.1)

	#save pb
	unet.save('owlSimple', overwrite=True, include_optimizer=False, save_format='tf')

Then did

    python3 -m tf2onnx.convert --opset 12 --saved-model ./owlSimple --output owlSimple12.onnx

I also tried opset of 9,10,11. They all seemed to convert successfully

When I tried to run opsets 11 and 12 in TensorRT (TensorRT with Docker container 20.03, which has CUDA 10.2 and TensorRT 7.0.0), I would get as error:

	ERROR: ModelImporter.cpp:92 In function parseGraph:
	[8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
	ERROR: could not parse the model.

	setBindingDimensions
	Segmentation fault (core dumped)

With opset 10, I got:

	While parsing node number 45 [Resize]:
	ERROR: builtin_op_importers.cpp:2412 In function importResize:
	[8] Assertion failed: scales.is_weights() && "Resize scales must be an initializer!"
	ERROR: could not parse the model.

and with Opset9 I got

	While parsing node number 45 [Upsample]:
	ERROR: builtin_op_importers.cpp:3240 In function importUpsample:
	[8] Assertion failed: scales_input.is_weights()
	ERROR: could not parse the model.

I got those errors even when I did

    wget https://raw.githubusercontent.com/rmccorm4/tensorrt-utils/master/OSS/build_OSS.sh
    source build_OSS.sh


If I further simplified the Unet by replacing the Unet with 

    inputs = Input((img_rows, img_cols, 1))
    conv9=inputs
    conv10 = Conv2D(1, (1, 1), activation='sigmoid')(conv9)

as seen in the commented out code above, then I get these errors when running the various opsets in TensorRT:

     input_2:0: dynamic input is missing dimensions in profile 0.
     Network validation failed.
     Segmentation fault (core dumped)
