### ISSUE TITLE
onnx2tensorRT for transformer layer

### ISSUE THREAD

**Issue by wanlipeng** [NVIDIA/TensorRT#940]
## Description
my pytorch network include transformer layers, pytorch-onnx-tensorRT,
convert onnx model to tensorRT, when I used tensorRT version7.0 ,Meet "Segmentation fault (core dumped)" problem,, 
But When I use tensorRT version6.0, Meet "UNSUPPORTED_NODE:Assertion failed:axis>=0 && axis <nbDims"

**Comment by rajeevsrao** [comment]
@wanlipeng few questions:
1) Can you please clarify which TensorRT layer/node op failed
2) Please provide a simplified test to reproduce the issue, if possible
3) Have you tried running with a more recent version of TensorRT (7.x)

**Comment by wanlipeng** [comment]
@rajeevsrao Thank you for your replay, I have make done!!

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Comment by henbucuoshanghai** [comment]
trt7.0 and trt8.0 support the transformer?

**Comment by ttyio** [comment]
@henbucuoshanghai , could you try latest 8.2 release? it is supported. thanks!

**Comment by henbucuoshanghai** [comment]
thank you，I will try it。
Does trt8.2 has the api for ln  and bn?

**Comment by ttyio** [comment]
Hi @henbucuoshanghai , for onnx user, you can use the ONNX2TRT parser. For native TRT user, we support scale, reduceMean, add, sub, pow, sqrt ... so you can use these APIs to create ln and bn. Thanks!

**Comment by henbucuoshanghai** [comment]
thanks, wonderful answer
