### ISSUE TITLE
build engine from onnx file error

### ISSUE THREAD

**Issue by whatlas** [NVIDIA/TensorRT#943]
Hi, I have one onnx model to deploy, which was generated by pytorch 1.4.0-cuda

on my computer with GTX 2080TI with CUDA-10.0 & CUDNN-7.6.5 & TensorRT-7.0.0.11, i can simply use

> trtexec --onnx=model.onnx --saveEngine=test.engine --verbose

to get the engine file.

BUT, on my AGX Xavier 32G with CUDA-10.2 & CUDNN-8.0.0 & TensorRT-7.1.3.0, the same command throw out sth like this:

> [E] [TRT] onnx2trt_utils.cpp:467: Found unsupported datatype (11) when importing initializer: _criterion.total_ops
> ERROR: ModelImporter.cpp:92 In function parserGraph:
> [8] Assertion failed: convertOnnxWeights(initializer. &weight, ctx)
> [E] Failed to parse onnx file
> [E] Parsing model failed
> [E] Engine creation failed
> [E] Engine set up failed

The onnx file is [here,](https://github.com/whatlas/onnx_bug/blob/main/model.onnx) Any suggestion?

**Comment by rajeevsrao** [comment]
@whatlas please provide the ONNX file so we can take a look.

**Comment by whatlas** [comment]
> @whatlas please provide the ONNX file so we can take a look.

It's here: https://github.com/whatlas/onnx_bug/blob/main/model.onnx

**Comment by whatlas** [comment]
hi，its been a while, any progression？

**Comment by ciderpark** [comment]
meet the same error on jetson nano, any help?

**Comment by nvpohanh** [comment]
@whatlas @ciderpark Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by whatlas** [comment]
> @whatlas @ciderpark Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

sorry i am no more in that project so i got no hardware for the test.

back to Feb 2021, i managed to convert the model to tensorrt by rewriting the pytorch model by tensorrt-python-api and numpy, it worked well without onnx.
