### ISSUE TITLE
Use deserializeCudaEngine() to build int8 engine, in C++ API, gpu memory usage is more than python API

### ISSUE THREAD

**Issue by tycallen** [NVIDIA/TensorRT#949]
## Description
The serialized engine file is already int8 and calibrated. In Python API, infer will consume ~490MB GPU mem, but in C++ it arise to ~1500MB
How to check and fix this problem?

## Environment

**TensorRT Version**: 7.1.3.4
**GPU Type**: 2080Ti
**Nvidia Driver Version**: 440.100
**CUDA Version**: 10.2
**CUDNN Version**: 7.5
**Operating System + Version**: Ubuntu 16.04
**Python Version (if applicable)**: 3.6.9

**Comment by tycallen** [comment]
Any help？

**Comment by rajeevsrao** [comment]
Hello @tycallen that is not expected behavior. Our python API is just a wrapper around the C++ APIs. Can you please help provide a repro testcase (onnx model and build/inference scripts you are using) so we can take a look?

**Comment by tycallen** [comment]
> Hello @tycallen that is not expected behavior. Our python API is just a wrapper around the C++ APIs. Can you please help provide a repro testcase (onnx model and build/inference scripts you are using) so we can take a look?

Ok, I will notice you here when the preparation is done. Thanks.

**Comment by ttyio** [comment]
I will close since no response for more than 3 weeks, please reopen if you still have question, thanks!
