### ISSUE TITLE
Lack of understanding how to migrate SSD code written for TensorRT5 to the latest TensorRT7.

### ISSUE THREAD

**Issue by bnascimento** [NVIDIA/TensorRT#950]
While migrating from TensorRT5 to TensorRT7 I stumbled into a lack of understanding how to correctly use the new V2 plugin system on c++. For example, calls like createSSDDetectionOutputPlugin or createSSDAnchorGeneratorPlugin are now deprecated. Is there an example how to use use SSD on TensorRT7?

**Comment by rajeevsrao** [comment]
@bnascimento Please see these SSD implementations supported in TensorRT 7.x:
Caffe: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleSSD
UFF: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffSSD

We will be posting an ONNX implementation in an upcoming release.
