### ISSUE TITLE
How to convert pytorch bert model to tensorrt engine model file?

### ISSUE THREAD

**Issue by pogevip** [NVIDIA/TensorRT#953]
I had read the demo https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py.
I tried to convert pt ==> onnx ==> tensorrt engine, 
But when onnx ==> tensorrt engine, 
![image](https://user-images.githubusercontent.com/27748841/101503194-ce1b8400-39ac-11eb-9de1-9c0c5a9489b2.png)

**Comment by ttyio** [comment]
Hello @pogevip , thanks for reporting.
You have to rewrite `load_onnx_weights_and_quant` in builder.py, because the naming in your ONNX is not the same as the ONNX we provide.

**Comment by pogevip** [comment]
Yes,thank you
