### ISSUE TITLE
Custom Plugin: getPluginCreator could not find plugin RetinaFaceDecode version

### ISSUE THREAD

**Issue by thaint2901** [NVIDIA/TensorRT#955]
## Description
I am testing a decode plugin for retinaface header. I successfully built trt engine with my custom plugin however i got this error while loading the engine using python trt:

```
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin RetinaFaceDecode version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (323) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
```

For more detail please check my github repo.

## Relevant Files

https://github.com/thaint2901/retinaface-header-cuda/tree/master/csrc

### build export

```bash
cd cpp
mkdir build && cd build
cmake -DCMAKE_CUDA_FLAGS="--expt-extended-lambda -std=c++14" ..
make
```

### build engine

```
./export faceDetector_540_960_dyn_sim.onnx faceDetector_540_960_dyn_sim.plan
```

### test with python

```python
import tensorrt as trt
import pycuda.autoinit
import pycuda.driver as cuda

weight_paths = "./faceDetector_540_960_dyn_sim.plan"
trt_logger = trt.Logger(trt.Logger.VERBOSE)
bindings = []
host_inputs = []
cuda_inputs = []
host_outputs = []
cuda_outputs = []
with open(weight_paths, 'rb') as f, trt.Runtime(trt_logger) as runtime:
    engine = runtime.deserialize_cuda_engine(f.read())
stream = cuda.Stream()

input_volume = trt.volume((3, im_height, im_width))
batch_size = 1
max_batch_size = engine.max_batch_size  # error because engine return None
print("max_batch_size: ", max_batch_size)
```

## Environment

Container: pytorch:20.06-py3

**Comment by pranavm-nvidia** [comment]
@thaint2901 You need to load your plugin prior to deserializing the engine. `dlopen`ing the executable might work:
```python
import ctypes
ctypes.CDLL("./export")
```
Although a cleaner solution would be to build a separate `.so` for your plugins and load that instead.

**Comment by thaint2901** [comment]
> @thaint2901 You need to load your plugin prior to deserializing the engine. `dlopen`ing the executable might work:
> 
> ```python
> import ctypes
> ctypes.CDLL("./export")
> ```
> 
> Although a cleaner solution would be to build a separate `.so` for your plugins and load that instead.

Can you provide a code use example?

**Comment by pranavm-nvidia** [comment]
It seems like you're building your plugins into a Python module, so it might be enough just to import it.
If you want to go with the shared library way, the basic approach would be something like:
```bash
# Build CUDA code
nvcc <options> plugin.cu -o plugin.cu.o                              
# Build host code
g++ <options> plugin.cpp -o plugin.o                                  
# Link everything into a shared library
g++ <options> -shared plugin.cu.o plugin.o -o libplugin.so 
```
and then load `libplugin.so` with `ctypes`.
