### ISSUE TITLE
trt7's gpu compute usage is more than trt6

### ISSUE THREAD

**Issue by qianwangn** [NVIDIA/TensorRT#957]
## Description

There is up to 20% performance regression on Tesla T4 for FCOS，compared to tensorrt6
## Environment

**TensorRT Version**:  7.1.3
**GPU Type**: T4
**Nvidia Driver Version**: 450.51.06
**CUDA Version**: 10.2
**CUDNN Version**:  7.5.0
**Operating System + Version**: Ubuntu18.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by qianwangn** [comment]
@rajeevsrao

**Comment by rajeevsrao** [comment]
@qianwangn which specific implementation you are referring to? Thanks.

**Comment by qianwangn** [comment]
@rajeevsrao I use this version FCOS: https://github.com/aim-uofa/AdelaiDet

**Comment by qianwangn** [comment]
Have you made any progress? @rajeevsrao

**Comment by rajeevsrao** [comment]
@qianwangn we are back in office in the NY2021. Will check and update then.

**Comment by qianwangn** [comment]
Have you made any progress? @rajeevsrao

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists in TRT 8.4. Thanks
