### ISSUE TITLE
BatchedNMS plugin cannot handle greater than 4096 rectangles in the input.

### ISSUE THREAD

**Issue by ledinhtri97** [NVIDIA/TensorRT#959]
Hello! I want to know about detail of document. In above information in document of BatchedNMS plugin. That mean 4096 box each input Batch or on all total Batch input?

**Comment by pranavm-nvidia** [comment]
The limitation applies to the `topk` value, which I explained briefly [here](https://github.com/NVIDIA/TensorRT/issues/893#issuecomment-725532331).
