### ISSUE TITLE
tensorrt 7.2 convert SSD-mobilenet: corrupted double-linked list

### ISSUE THREAD

**Issue by superxc** [NVIDIA/TensorRT#962]
## Environment

**TensorRT Version**: tensorrt 7.2.1
**GPU Type**: rtx2070s
**Nvidia Driver Version**: 450.80.02
**CUDA Version**: cuda11
**CUDNN Version**: cudnn 8
**Operating System + Version**: ubuntu 18.04 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 
using caffe model

**Comment by ttyio** [comment]
Sorry @superxc  for the delay response, the caffe is deprecated, could you try onnx? thanks!

**Comment by ttyio** [comment]
Close since no activation for more than 3 weeks, please reopen if you still have question, thanks!
