### ISSUE TITLE
ONNX model on TRT 7.2.1 versus TRT 6

### ISSUE THREAD

**Issue by ttdd11** [NVIDIA/TensorRT#963]
Currently we have a model that works in TRT 6 and are looking to move to TRT 7.2.1 for 3000 series compatibility. In trt 7.0 the model was not working, and I was hoping to use Polygraph to compare the onnx results to the trt results as the full trt test is quite lengthy. 

Is this tool for linux only?  Any help with getting Polygraph working on windows/testing this on linux would be appreciated.

**Comment by pranavm-nvidia** [comment]
Polygraphy itself is OS-agnostic. However, we don't have TensorRT Python bindings available for Windows, so you'll only be able to use functionality not dependent on TRT. 

If you're able to test on Linux, I'd strongly recommend doing that instead. 

If you have to use Windows, you could run inference with TRT yourself (with C++) and convert the results to numpy arrays, which you can then use to construct a [RunResults](https://github.com/NVIDIA/TensorRT/blob/master/tools/Polygraphy/polygraphy/comparator/struct.py#L48) instance. At that point, you'll be able to use Polygraphy for comparisons. This will be a lot of manual effort though, and Linux would definitely be a lot easier.

**Comment by ttdd11** [comment]
Okay thanks for this.

Alternatively if I run inference using TRT 7.2.1 and there are problems with my onnx model, at that point would someone internally take a look a provide recommendations or would I have to determine the specific node that isn't working as intended and submit that?

**Comment by pranavm-nvidia** [comment]
It helps if you're able to isolate the problem to a single node or small subgraph. 
Having said that, it's certainly not a requirement for posting here - if you're seeing a bug in TRT, please do file an issue.
