### ISSUE TITLE
Assertion Error in min

### ISSUE THREAD

**Issue by Jialeen** [NVIDIA/TensorRT#965]
I used "trtexec --onnx=/mnt/deeplabV3_plus.onnx --saveEngine=/mnt/deeplabV3_plus.engine --fp16 --verbose --explicitBatch" to get tensorrt model, but the error came out:
----- Parsing of ONNX model /mnt/deeplabV3_plus.onnx is Done ---- 
[12/16/2020-06:50:01] [F] [TRT] Assertion failed: !empty()
../builder/intInterval.cpp:20
Aborting...
[12/16/2020-06:50:01] [E] [TRT] ../builder/intInterval.cpp (20) - Assertion Error in min: 0 (!empty())
[12/16/2020-06:50:01] [E] Engine creation failed
[12/16/2020-06:50:01] [E] Engine set up failed

Can anyone help me?
Thanks!

**Comment by ttyio** [comment]
Hello @Jialeen , thanks for reporting!
Could you check your onnx model, we need also provide `--minShapes`, `--optShapes`, `--maxShapes` and `--shapes` for model with dynamic shape. You can run `trtexec --help` for more details about the command lines.

**Comment by pustar** [comment]
help, the same problem
`
		nvinfer1::Dims dimension{ 1, 1, 256, 256 }; //   1U << TensorFormats::kCHW4 | 1U << TensorFormats::kCHW32.
		network->getInput(0)->setDimensions(nvinfer1::Dims(dimension));
		mEngine = builder->buildCudaEngine(*network);
		assert(mEngine);
`
[01/21/2021-17:49:31] [F] [TRT] Assertion failed: !empty()
C:\source\builder\intInterval.cpp:20
Aborting...

[01/21/2021-17:49:31] [E] [TRT] C:\source\builder\intInterval.cpp (20) - Assertion Error in nvinfer1::builder::Int32Interval::min: 0 (!empty())
Assertion failed: mEngine,

**Comment by nvpohanh** [comment]
@pustar Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists in TRT 8.4. Thanks
