### ISSUE TITLE
TensorRT can parse yolov5 ONNX model but no detect any object

### ISSUE THREAD

**Issue by alicera** [NVIDIA/TensorRT#966]
TensorRT Version - 7.2.1:
GPU Type - dGPU aws TESla T4:
Nvidia Driver Version - 455.38:
CUDA Version - 11.1:
Operating System + Version -> Ubuntu 18.04:

I was trying to convert yolov5s onnx model to TensorRT which didnt throw any error I have no idea about.

yolov5 can detect the object for FP16
yolov5 cant detect any object for INT8

**Comment by ttyio** [comment]
Hello @alicera , thanks for reporting.
Have you tried different INT8 calibrator? thanks!

**Comment by alicera** [comment]
calibratorV2

**Comment by alicera** [comment]
Hi ttyio,
Do you have try the new version https://github.com/ultralytics/yolov5

**Comment by ttyio** [comment]
@alicera , check https://github.com/NVIDIA/TensorRT/issues/997#issuecomment-768866894, replace silu with relu, INT8 works after retrain your network

**Comment by alicera** [comment]
Thanks for your advance.
I already try it.
The tensorRT support the silu and relu6  with INT8, now?

**Comment by ttyio** [comment]
Yes @alicera

**Comment by alicera** [comment]
TensorRT version?

**Comment by ttyio** [comment]
TRT support silu from 7.0 using pointwise fusion and can be fused with conv/gemm for none INT8 case.
And in 8.0 we did more optimization and there are more chances that can be fused with conv/gemm when precision is INT8.

From the issue I linked, it is not functional issue, but more like the silu in the yolov5 is int8 sensitive, not depend on trt version.
