### ISSUE TITLE
nvidia driver

### ISSUE THREAD

**Issue by alicera** [NVIDIA/TensorRT#968]
## Description

Is "455.45.01" based on "455.38" ?

Or  "455.45.01" and "455.38" are different. In the future, they will be integrated , like "460.78"

![image](https://user-images.githubusercontent.com/59388989/102466347-e022b400-4089-11eb-9452-abf65477dd8f.png)

**Comment by nvpohanh** [comment]
Hi @alicera , this question is not specific to TensorRT. Could you ask in NVIDIA's Geforce forum instead: https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/ ? Thanks
