### ISSUE TITLE
yolov2 prototxt The caffe parser cannot parse the Reorg. An error occurred has no field named "reorg_param"

### ISSUE THREAD

**Issue by SophieXuhui** [NVIDIA/TensorRT#969]
## Description

When run yolov2 prototxt, an error occurred:  
Error parsing text-format ditcaffe.NetParameter: 991:15: Message type "ditcaffe.LayerParameter" has no field named "reorg_param".

The layer Reorg in prototxt is like this:

layer {
  name: "reorg"
  type: "Reorg"
  bottom: "conv13"
  top: "reorg1"
  reorg_param {
    stride: 2
  }
}
No typical Reorg layer using implemented in Readme about reorgPlugin, am i wrong in using this layer in Caffe, or Tensort doesn't support ?

When I comment the reorg_param part in Reorg layer, like this:
layer {
  name: "reorg"
  type: "Reorg"
  bottom: "conv13"
  top: "reorg1"
  #reorg_param {
    #stride: 2
  #}
}

Another error occurred:  could not parse layer type Reorg,  Failed to parse caffe model or prototxt, tensors blob not found.

## Environment

use Jetson TX2

**TensorRT Version**: 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version            Architecture       Description
+++-==========================-==================-==================-=========================================================
ii  tensorrt                   7.1.3.0-1+cuda10.2 arm64              Meta package of TensorRT

**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_21:14:42_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**CUDNN Version**: 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-=======================================================
ii  libcudnn8                 8.0.0.180-1+cuda1 arm64             cuDNN runtime libraries

**Operating System + Version**: 
Distributor ID: Ubuntu
Release:        18.04

**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by ttyio** [comment]
Sorry @SophieXuhui for the delay reponse, the caffe parser is deprecated, have you give a try on ONNX? thanks!

**Comment by ttyio** [comment]
The 8.0EA download link is in https://developer.nvidia.com/nvidia-tensorrt-download
I will close this, please reopen if you still have question, thanks!
