### ISSUE TITLE
why no effect when I speed up backbone in faster-rcnn model and ssd model？

### ISSUE THREAD

**Issue by linssswww** [NVIDIA/TensorRT#97]
I used tensorRT to speed up backbone in faster-rcnn model and ssd model.  but it just speed up a little.  10%

hardware:1080Ti
detection framework: mmdetection
model:ssd and faster-rcnn
tensorRTconvert library : trt2pytorch

**Comment by DilipSequeira** [comment]
How much time is being spent running the backbone in the original implementation?

**Comment by rmccorm4** [comment]
Closing due to no response - Feel free to ask for it to be reopened if you have more details.
