### ISSUE TITLE
Are Serialized engines not portable across platforms(OS) even with same TensorRT,CUDA,CUDNN, CuBlas version and GPU HW?

### ISSUE THREAD

**Issue by buaalingming** [NVIDIA/TensorRT#977]
hi, 
    "Serialized engines are not portable across platforms(means Linux and Windows.) or TensorRT versions."(from https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#platform-matrix）.
     Are Serialized engines not portable across platforms(OS) even with same TensorRT,CUDA,CUDNN, CuBlas version and GPU HW?
such as :
- Linux x86-64（ubuntu16.04）: CUDA 10.2, cuBlas 10.2.3.254. cudnn8.05, RTX 2080Ti （different driver version: Driver 450.57）

    

- Windows x64 (win10）：CUDA 10.2, cuBlas 10.2.3.254. cudnn8.05， RTX 2080Ti （different driver version: 441. 22）

    Thank you very much.

**Comment by nvpohanh** [comment]
It is not guaranteed to work across platforms (OS) even when the software stack versions are the same. It is still recommended to build the serialized engines on the targeted platforms directly.

**Comment by buaalingming** [comment]
When i use serialized engines across platforms, both of them are fail:
- Win10 report:

"
INFO: Use GPU: 0
[12/22/2020-14:32:10] [W] [TRT] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[12/22/2020-14:32:11] [E] [TRT] c:\source\rtsafe\coreReadArchive.h (271) - Serialization Error in nvinfer1::rt::readExternal: 0 (Type mismatch)
"

- Ubuntu report:
"
[TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[TensorRT] ERROR: coreReadArchive.h (271) - Serialization Error in readExternal: 0 (Type mismatch)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
"
@nvpohanh , Thank you.
