### ISSUE TITLE
sampleSSD detections are wrong when using a coco trained model

### ISSUE THREAD

**Issue by JimKlingshirn** [NVIDIA/TensorRT#98]
The sampleSSD example code works correctly when running a caffe model trained on the VOC dataset.  However it does not work correctly on a COCO trained model.  On cat.ppm, it detects dozens of umbrellas.  
 
Any ideas for fixing  (or debugging) this would be **greatly appreciated**!

Steps to reproduce:

1. Download the pretrained COCO model from the official SSD repository https://drive.google.com/uc?id=0BzKzrI_SkD1_dUY1Ml9GRTFpUWc&export=download
2. Edit the deploy.prototxt  as per Nvidia instructions (replace Flatten with Reshape, etc).
3. Change the list of 21 VOC classes in sampleSSD.cpp to the list of 81 COCO classes.
4. Change the number of classes in sampleSSD.cpp ( params.outputClsSize = 81;)
5. Convert caffe/examples/images/cat.jpg to cat.ppm using gimp.
6. Build with Ubuntu 16.04, Cuda 10.1, TensorRT 5.0.5.0
7. Run on a GTX1080-ti GPU

The modified file sampleSSD.cpp is attached:

[sampleSSD.cpp.zip](https://github.com/NVIDIA/TensorRT/files/3537546/sampleSSD.cpp.zip)

**Comment by rmccorm4** [comment]
Hi @JimKlingshirn,

Can you check if this is still true in TensorRT 7? Also, this thread may have some useful info: https://github.com/NVIDIA/TensorRT/issues/274

**Comment by rmccorm4** [comment]
Closing since no response
