### ISSUE TITLE
PyTorch-Quantization Toolkit

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/TensorRT#981]
Hi,

I am trying to following the example in PyTorch-Quantization Toolkit to do the int8 Quantization.
However, after I manager to get the generated onnx file. I fail to convert it to TRT engine.

The document end with exporting onnx, and not touching the converting trt engine part.
So is there some trick for the Quantization onnx->trt?

The trtexec convert error is as following:
```
While parsing node number 9 [QuantizeLinear]:
/data/TensorRT/parsers/onnx/builtin_op_importers.cpp:2315 In function importQuantizeLinear:
[6] Assertion failed: inputs.at(2).is_weights()
[12/23/2020-10:30:40] [E] Failed to parse onnx file
[12/23/2020-10:30:40] [E] Parsing model failed
[12/23/2020-10:30:40] [E] Engine creation failed
[12/23/2020-10:30:40] [E] Engine set up failed
```

I also compare the tensorflow resnet50 quant result, whose converted onnx could be built into trt engine without problem.
and I found there is something different. Does it cause the pytorch's onnx cannot be builted into trt?

Pytorch quantization toolkit generated onnx's first layer, which cause trtexec report issue in importQuantizeLinear.
![image](https://user-images.githubusercontent.com/18640128/103121701-58a3f900-46b8-11eb-8b8e-f4c9b52430f9.png)

Tensorflow generated onnx without problem.
![image](https://user-images.githubusercontent.com/18640128/103121762-96088680-46b8-11eb-8c89-c69613cbb668.png)

With the comparison, I could get the conclusion that tensorflow's version is simplier that with the constant part. Shall I manually cut the constant part out? Or is there some extra steps need to be done for this PyTorch-Quantization Toolkit Tutorial?

Thx,
Lei

**Comment by xtudbxk** [comment]
Could you please offer the resnet50 onnx file generated by tensorflow ? I also encounters some problems when using pytorch-quantization toolkit. Thanks ~

**Comment by leiwen83** [comment]
> Could you please offer the resnet50 onnx file generated by tensorflow ? I also encounters some problems when using pytorch-quantization toolkit. Thanks ~

The tensorflow onnx is generated following the guide from: https://github.com/NVIDIA/sampleQAT

**Comment by xtudbxk** [comment]
I just follow the instruction and generate the onnx file. But unfortunately, when I convert the generated onnx file to trt engine, it always failed and reported "Assertion `sI.count() == 1' failed.".  Did you have the same problem ? Or could you please offer the generated onnx files ?

**Comment by leiwen83** [comment]
> I just follow the instruction and generate the onnx file. But unfortunately, when I convert the generated onnx file to trt engine, it always failed and reported "Assertion `sI.count() == 1' failed.". Did you have the same problem ? Or could you please offer the generated onnx files ?

There is some trick over this onnx generation. You shall follow exact every step for the guidance.
That is first goto https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/resnet50v1.5 and generate trained pb. Then retrain with QAT. ->  goes to postprocess_ckpt.py, -> Exporting Frozen graphs- >fold_constants.py->tf2onnx.convert->postprocess_onnx.py 

After all those stuff, you could get your onnx buit into TRT

**Comment by xtudbxk** [comment]
I follwed the above steps and generated the onnx file. But it seems unsimilar with yours.
![捕获](https://user-images.githubusercontent.com/14304858/103404652-5c8bbb80-4b8f-11eb-8918-655d3b055077.PNG)
And there only exists one input for the conv node, which raised a problem again.

**Comment by xtudbxk** [comment]
And how did you get the onnx-graphsurgeon v 0.2.1 ? There only exists v 0.2.3 in the [official reposity](https://github.com/NVIDIA/TensorRT/tree/release/7.1/tools/onnx-graphsurgeon). So, I didn't run the 'postprocess_onnx.py'. Do you think the missing of this step cause the problem ?

**Comment by leiwen83** [comment]
> And how did you get the onnx-graphsurgeon v 0.2.1 ? There only exists v 0.2.3 in the [official reposity](https://github.com/NVIDIA/TensorRT/tree/release/7.1/tools/onnx-graphsurgeon). So, I didn't run the 'postprocess_onnx.py'. Do you think the missing of this step cause the problem ?

Yes, postprocess is the key. master branch shall also works.
