### ISSUE TITLE
TensorRT NOT match result from pytorch quantization

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/TensorRT#988]
Hi,

I am trying to convert onnx model with TensorRT. But there is something internal I don't quite understand.
That is as below graph shows, before entering the CONV stage, the input need to be adjust for quatization.
![image](https://user-images.githubusercontent.com/18640128/103476831-0c616300-4df4-11eb-9e68-03e693cf47d4.png)

And I could see from the memory dump that tensorRT would amplify the input by [1/0.007874015718698502] which is the yscale parameter for the QuantizeLinear. Following in CONV, tensorRT do the int8 multiply and int32 accumulation.
But before it leave the CONV, and ready to re-quantization into float32 again, I see there is a scale down operation, which make int32 fallen into int8 scale.
The scale down parameter is taken from TRT generated engine, which I cannot find in the onnx model. So the first question is how TensorRT calculate the scale down for CONV layer from int32 to int8 in its last stage.
Second question is that after CONV scale its result to int8, it still goes the dequatization and make it float32 again. where it use [1/0.009967146441340446] which is in the onnx model. But the final result is different. so does it means the scale down parameter in the CONV stage need to be adjusted?

I take the first value in the matrix as example.
In pytorch, it goes from 0.580392 [at the beginning]->73.709784 [quantization with multipled by 127] ->74 [clip around] ->0.582677[ dequantization with dividied by 127]-> 0.299564  [after conv]
In TensorRT, it goes from 0.580392 [at the beginning] ->74 [quantization into int8] -> 17236 [conv result] ->24 [conv last stage scale into int8] ->0.239212 [dequantization into float32]

Thx,
Lei

**Comment by xtudbxk** [comment]
Hi, again. The Q and DQ nodes after the conv node are inserted manually ? I generated the onnx model from pytorch quantization toolkit, too. But it seems there are no Q and DQ nodes following the conv node.
And I'm new to network quantization, sorry for no help to your questions.

**Comment by leiwen83** [comment]
Hi,

It is not inserted by manual, but cut from consecutive convolution node produced by pytorch quantization.
TensorRT current seems require D/DQ resided before/after conv.

**Comment by xtudbxk** [comment]
Thanks, I just converted the onnx to engine successfully. I modified the source code of pytorch quantization toolkit, and inserted the Q/DQ nodes manually to each conv node. And more, I encountered the issue 'Assertion failed: inputs.at(2).is_weights()' also. But when I remove the quantization for Transposed Conv node, it disappears.

**Comment by xtudbxk** [comment]
There are some pseudocode for the INT8 conv kernel in [s7310-8-bit-inference-with-tensorrt.pdf](https://on-demand.gputechconf.com/gtc/2017/presentation/s7310-8-bit-inference-with-tensorrt.pdf). And it describes the scale down operation with `I8_output = Saturate(Round_to_nearest_integer( F32_result )`. May this help you.
