### ISSUE TITLE
Is it possible to use TensorRT to accerate CPU inference?

### ISSUE THREAD

**Issue by LiChao-cy** [NVIDIA/TensorRT#992]
Can i disable GPU device and make CPU inference with TensorRT?

**Comment by ttyio** [comment]
Hello @LiChao-cy , is Triton what you are looking for?
https://github.com/triton-inference-server/server
Thanks

**Comment by LiChao-cy** [comment]
> Hello @LiChao-cy , is Triton what you are looking for?
> https://github.com/triton-inference-server/server
> Thanks

**Comment by LiChao-cy** [comment]
> Hello @LiChao-cy , is Triton what you are looking for?
> https://github.com/triton-inference-server/server
> Thanks

Thank you very much!  I'll have a look at that project.
