### ISSUE TITLE
请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。

### ISSUE THREAD

**Issue by Wulingtian** [NVIDIA/TensorRT#997]
系统：Ubuntu 18.04
trt版本：7.2.1
onnx版本：1.8.0
onnx转trt fp16是正常出框的，转成trt int8后不出框

**Comment by sonixixi** [comment]
有

**Comment by Wulingtian** [comment]
> 有

你解决了么？

**Comment by Wulingtian** [comment]
> 有

可以交流一下吗？我困扰好久了。

**Comment by sonixixi** [comment]
7.0可以

**Comment by ttyio** [comment]
Hello @Wulingtian, thanks for reporting.
Have you tried different calibrator algorithms?

**Comment by Wulingtian** [comment]
> Hello @Wulingtian, thanks for reporting.
> Have you tried different calibrator algorithms?

您好，感谢您的回复！不同的量化算法都有试过的，还是不出框，您那边能测试一下吗？

**Comment by ttyio** [comment]
@Wulingtian  could you provide the onnx and the input? thanks

**Comment by Wulingtian** [comment]
> @Wulingtian could you provide the onnx and the input? thanks

https://github.com/onnx/onnx/issues/3191#issuecomment-753427026 我在如上链接提供了onnx模型，输入尺寸是640*640，模型是关于安全帽检测的

**Comment by Wulingtian** [comment]
> @Wulingtian could you provide the onnx and the input? thanks

您好，请问有发现哪里有问题吗？

**Comment by ttyio** [comment]
Hello @Wulingtian , we also need calibration dataset and test images.

**Comment by Wulingtian** [comment]
> calibration

链接: https://pan.baidu.com/s/1-lWVELOAHeD-EmnVvbx01Q  密码: giqf    您好，如上链接提供了量化数据和测试数据

**Comment by Wulingtian** [comment]
> Hello @Wulingtian , we also need calibration dataset and test images. Thanks!

链接: https://pan.baidu.com/s/1-lWVELOAHeD-EmnVvbx01Q 密码: giqf 
您好，如上链接提供了量化数据和测试数据

**Comment by Wulingtian** [comment]
> Hello @Wulingtian , we also need calibration dataset and test images. Thanks!

您好，请问能正常出框吗？

**Comment by ttyio** [comment]
Hello @Wulingtian , file received, but we have not enough bandwidth to try it yet.
There are two ways you can try in your side:
- check per layer result from both int8 and fp32/fp16, find out those `int8 sensitive` layers and mark them as fp16 or fp32, then use mixed precision to see if the accuracy is back
- Besides entropy2, entropy and max. there is also an percentile max calibrator you can try see example in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/helpers/calibrator.py#L102

**Comment by Tracin** [comment]
> Sorry @Wulingtian , file received, but we have not enough bandwidth to try it yet.
> There are two ways you can try in your side:
> 
> * check per layer result from both int8 and fp32/fp16, find out those `int8 sensitive` layers and mark them as fp16 or fp32, then use mixed precision to see if the accuracy is back
> * Besides entropy2, entropy and max. there is also an percentile max calibrator you can try see example in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/helpers/calibrator.py#L102

Hi, I wonder how to use "get_quantile" and "get_regression_cutoff"  and what do these mean, I can not find any usage or introduction neither in this project nor in release note.
Thanks!

**Comment by ttyio** [comment]
Hello @Tracin , here is the C++ document for these 2 settings:
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_int8_legacy_calibrator.html#a470b671a787a37a56277345cf00c5997

**Comment by Tracin** [comment]
> Hello @Tracin , here is the C++ document for these 2 settings:
> https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_int8_legacy_calibrator.html#a470b671a787a37a56277345cf00c5997

Sorry, I still can not find the "user guide" where it says I can get more details in.

**Comment by ttyio** [comment]
> > Hello @Tracin , here is the C++ document for these 2 settings:
> > https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_int8_legacy_calibrator.html#a470b671a787a37a56277345cf00c5997
> 
> Sorry, I still can not find the "user guide" where it says I can get more details in.

Sorry @Tracin , there was `sampleINT8` in 4.0 release show how to use legacyCalibrator (the latest sampleINT8 use entropyCalibrator because it no longer ask for hyper-parameter.). There is function `searchCalibrations`  illustrates how to find the best calibration parameters by searching over the parameter combinations and score the network for each combination using some additional images. 
Could you download and check there? thanks.

**Comment by Wulingtian** [comment]
> Sorry @Wulingtian , file received, but we have not enough bandwidth to try it yet.
> There are two ways you can try in your side:
> 
>     * check per layer result from both int8 and fp32/fp16, find out those `int8 sensitive` layers and mark them as fp16 or fp32, then use mixed precision to see if the accuracy is back
> 
>     * Besides entropy2, entropy and max. there is also an percentile max calibrator you can try see example in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/helpers/calibrator.py#L102

我把yolov5s的激活函数替换为relu重新训练后，onnx转trt int8终于可以正常出框了！

**Comment by weixiaolian21** [comment]
> > Sorry @Wulingtian , file received, but we have not enough bandwidth to try it yet.
> > There are two ways you can try in your side:
> > ```
> > * check per layer result from both int8 and fp32/fp16, find out those `int8 sensitive` layers and mark them as fp16 or fp32, then use mixed precision to see if the accuracy is back
> > 
> > * Besides entropy2, entropy and max. there is also an percentile max calibrator you can try see example in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/helpers/calibrator.py#L102
> > ```
> 
> 我把yolov5s的激活函数替换为relu重新训练后，onnx转trt int8终于可以正常出框了！

请问你用relu出框后 map有没有计算过 我试了下map下降了好多 用的是entropy的量化方法

**Comment by PowerDi** [comment]
> > Sorry @Wulingtian , file received, but we have not enough bandwidth to try it yet.
> > There are two ways you can try in your side:
> > ```
> > * check per layer result from both int8 and fp32/fp16, find out those `int8 sensitive` layers and mark them as fp16 or fp32, then use mixed precision to see if the accuracy is back
> > 
> > * Besides entropy2, entropy and max. there is also an percentile max calibrator you can try see example in https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/helpers/calibrator.py#L102
> > ```
> 
> 我把yolov5s的激活函数替换为relu重新训练后，onnx转trt int8终于可以正常出框了！

很抱歉打扰你，请问可以将你改成relu的模型共享一下吗？我这边也遇到了同样的问题但我改成Relu最后的结果仍然是0，我们想排除一下模型的问题

**Comment by ttanzhiqiang** [comment]
https://github.com/ttanzhiqiang/onnx_tensorrt_project

**Comment by Levi-zhan** [comment]
> * check per layer result from both int8 and fp32/fp16, find out those `int8 sensitive` layers and mark them as fp16 or fp32, then use mixed precision to see if the accuracy is back

How can I find `int8 sensitive` layers? Do you have any reference examples？Thanks
